### PR TITLE
Code inset optimization

### PR DESCRIPTION
**Pull request by rdeline**
@jrieken The Python team was concerned that having a webview for each Jupyter notebook output is too heavyweight, since each webview runs in its own process. This PR introduces an optimization for code insets, which fixes this problem for the Python team and should be useful for many clients. If an inset's html is basic static content, then the inset's view zone includes that content directly; otherwise the content is placed in a webview, as before. The optimization uses a whitelisting approach, in the style of XSS sanitizing tools. In particular, if the html includes any kind of scripting, then the webview is used so that the scripts will be sandboxed. I've checked that the most common types of Jupyter output (print statements, panda tables, Mathplotlib plots) generate html that make it through the whitelist. So, with the optimization, most Jupyter sessions will show insets that do not create any webviews.

### CODE REVIEW

**Comment by mjbvz** [comment]
Overall, I'd prefer to sandbox the content in some way instead of inserting it directly into the dom. A few reasons:

* Safer failure. I always assume that someone will be able to get past the sanitizer. 
* We don't want CSS or anything from VS Code effecting the webview content.
* We don't want anything from the webview ever leaking into VS Code.

Webviews may be too heavyweight, but what about sandboxed iframes that uses `srcdoc`? 

```html
<iframe sandbox srcdoc="<html>...."></iframe>
```

---

We've also discussed only rendering webview insets that are visible. That way, at most one screen's worth of webviews should ever exist at time. We do similar list virtualization for many lists in VS Code, including for lines in the editor

**Comment by rdeline** [comment]
@mjbvz Are you suggesting to use `iframe sandbox` for whitelisted html content or for all code insets? What are the security and performance differences between `webview` and `iframe sandbox`? (I'm scouring the web, but not finding much so far.)

If anyone's curious, I started down the whitelisting road after I read in Adam Rule's study of 1M+ Jupyter Notebooks that 68% of cell outputs are just text (e.g. output from print statements). Obviously it's a  shame to fire up a process just to render a string. I haven't measured the prevalence myself, but other common cases include Panda tables (which are rendered as vanilla `table` elements) and Plotly plots (which are rendered as script-free `svg` elements). These are really the three cases I care about.

I'm somewhat skeptical about managing webviews based on the scroll viewport. While I've been playing with Python, I've noticed about a one-second lag (perceived, not measured) between an output showing up in the existing Python Interactive web panel and it showing up in an inset. Hiding or mitigating that latency would be a problem. Also, there's the issue of managing the webview's state as they come and go. Extension writers have to think about this for dealing with different Code sessions, but demand-paging the webviews would require state management within a session.

**Comment by mjbvz** [comment]
Yes, sandboxed iframes have higher overhead than inline html, but as a matter of principal we do not want to allow any extension to break VS Code. Sandboxed iframes (or webviews) let us isolate the capabilities, layout, and styling of the provided inset. 

As for list virtualization, we'll likely want to do that for any variety of the webview inset API. Hopefully we'll be able to hide most of the details of how this actually works from extensions however. See `CodeLensProvider` for an example of what a lazy resolving webview inset API could look like

**Comment by rdeline** [comment]
OK, an optimization strategy based on content is too brittle and risky. The better approach is to manage the webview resources based on viewport visibility (like code lens), so I'll cancel this PR.

**Pull request closed without merging**
