### PR TITLE
Add NuShell to core and separate out pwsh, python, julia, nu as GeneralShellType

### LINKED ISSUE #224326: Add Nushell as shell type in core
Part of: https://github.com/microsoft/vscode/issues/155530
This should allow clear separation when users attempt to "Terminal: Run Recent Command", as in only nu shell commands will show when in nu terminal.

### PR DESCRIPTION
**Pull request by anthonykim1**
Adding nushell to core 
Resolves: https://github.com/microsoft/vscode/issues/224326

### CODE REVIEW

**Comment by anthonykim1** [comment]
@Tyriar Haven't checked if this is the case for Windows, but for Mac/Linux, there are some additional things (like the nu prompt of '>', exit code, and date/time that seems to get attached along with the actual user commands itself.
Screenshot 2024-08-10 at 4 04 19 PM
Screenshot 2024-08-10 at 4 04 12 PM

Would this mean we should handle/adjust nushell prompt specifically in https://github.com/microsoft/vscode/blob/a3be5f6c2356b9d87ecb46dbb04c9cf8f103e964/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L484

as we do for some other shells (pwshPrompt, python, etc) in https://github.com/microsoft/vscode/blob/a3be5f6c2356b9d87ecb46dbb04c9cf8f103e964/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L919

**Comment by Tyriar** [comment]
> like the nu prompt of '>', exit code, and date/time that seems to get attached along with the actual user commands itself

This likely means that the command started and/or executed sequences aren't happening. There is also the command line sequence which overrides everything which i don't think nushell does atm.

**Comment by anthonykim1** [comment]
> This likely means that the command started and/or executed sequences aren't happening. There is also the command line sequence which overrides everything which i don't think nushell does atm.

Should we defer and wait this until nushell adds these sequences?

**Comment by Tyriar** [comment]
@anthonykim1 no we should add this, then we could request it and/or contribute. It looks like it's a constant defined in the code, but it's not being used right now: https://github.com/nushell/nushell/blob/0eabbb88dd3ec6fc2a82228f42a0d88678e8ff19/crates/nu-cli/src/prompt_update.rs#L49

**Comment by anthonykim1** [comment]
@Tyriar Got it, sounds good. I've filed the issue here: https://github.com/nushell/nushell/issues/13607

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
