### PR TITLE
 fix lightbulb jumping in the gutter (but like not the trash)

### LINKED ISSUE #226590: Lightbulb appears in line gutter and disappears resulting in jumping UI
Not sure how to repro but it happens when I switch tabs. The code actions that appear quickly are "Move to file" and "Move to a new file". 

https://github.com/user-attachments/assets/21f09964-5318-4fe8-b634-d687a67f333f

`foo.test.ts`

```typescript
import { mul } from '../src/foo';
import {expect, describe, it} from 'vitest';

describe('mul f<<CURSOR>>unction', () => { // CURSOR POSITION
	it('should return 6 for mul(2, 3)', () => {
		const result = mul(2, 3);
		expect(result).to.equal(6);
	});

	it('should return 0 for mul(0, 5)', () => {
		const result = mul(0, 5);
		expect(result).to.equal(0);
	});

	it('should return -15 for mul(-3, 5)', () => {
		const result = mul(-3, 5);
		expect(result).to.equal(-15);
	});

	it('should return 25 for mul(5, 5)', () => {
		const result = mul(5, 5);
		expect(result).to.equal(25);
	});

	it('should return 0 for mul(0, 0)', () => {
		const result = mul(0, 0);
		expect(result).to.equal(0);
	});

});

```

Version: 1.93.0-insider
Commit: e81aceaa07bab1ccdc94deae04168c8bd062f0de
Date: 2024-08-26T05:04:02.640Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

### PR DESCRIPTION
**Pull request by justschen**
fixes: https://github.com/microsoft/vscode/issues/226590

### CODE REVIEW

**Review by Yoyokrazy — DISMISSED** [review]
https://www.youtube.com/watch?v=79DijItQXMM

**Review by Yoyokrazy — APPROVED** [review]

**Comment by justschen** [comment]
what an iconic song

**Comment by Yoyokrazy** [comment]
> what an iconic song

you're welcome

**Comment by justschen** [comment]
what can i say except your'e welcome! for the tides, the sun, the sky

**Pull request merged**
