### PR TITLE
list: accessibility 

### LINKED ISSUE #95516: When there are errors in the file being edited and I press ctrl + shift + m, orca announces only the following: tree
Issue Type: <b>Bug</b>

1. Launch orca.
2. Create an empty java script file.
3. Insert the following line in the file.
lvar x
4. Press ctrl+shift+m.

Orca should announce the existence of errors but instead announces only the following: tree.

CC @isidorn

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:09:45.292Z)
OS version: Linux x64 5.6.4-arch1-1

### PR DESCRIPTION
**Pull request by isidorn**
fixes https://github.com/microsoft/vscode/issues/95516

- [x] introduce `accessibilityProvider.getWidgetAriaLabel`
- [x] remove `ariaLabel` from `listOptions` and adopt `accessibilityProvider.getWidgetAriaLabel`
- [x] Add getter and setter for `list.ariaLabel`
- [x] adopt getter and setter for list.ariaLabel in problems
- [x] introduce optional `accessibilityProvider.getWidgetRole`
- [x] remove `ariaRole` from `listOptions` and adopt `getWidgetRole`
- [ ] ~~make `accessilibiltyProvider` also mandatory for `List`~~ since all list options are optional will keep it optional

### CODE REVIEW

**Comment by isidorn** [comment]
I am happy with this changes and plan to merge this in tomorrow morning.
@joaomoreno let me know if you would like me to change something
fyi @sandy081 for changes in `markersView` to dynamically change `ariaLabel` of the markers tree.

**Review by joaomoreno — APPROVED** [review]
Good job, lgtm

**Comment by isidorn** [comment]
Thanks for review.
Ok, let's merge before there are conflicts since this touches half the workbench.

**Comment by akash07k** [comment]
Looks promising. is it arived in update?

**Comment by isidorn** [comment]
@akash07k yes it has. Usually all changes arrive in the update one day after the change.

**Pull request merged**
