### PR TITLE
Untitled Save As dialog defaults to All Types with blank name 

### PR DESCRIPTION
**Pull request by jel-massih**
This fixes issue #450

This is a UX change so reject if undesired behavior.

### CODE REVIEW

**Comment by bpasero** [comment]
-1, we should still propose a good file extension in case the user picked a mode from the status bar. if it is text, we should not propose text, I agree. We need to pick up Electron 0.34.2 at least where there are fixes around the save as dialog.

**Comment by jel-massih** [comment]
Updated to only use All Files when user specifies a mime type other than plain/text.

I return the name rather than empty when it is text/plain, so file name looks like `Untitled-2.*.*` [but is fixed in Electron 0.34.2+, where it should look like `untitled-2`].

**Comment by joaomoreno** [comment]
Closed and opened PR to get a later merge commit for Travis to build on and get this one green.

**Comment by bpasero** [comment]
I will merge this from by electron branch, thanks!

**Pull request closed without merging**
