### PR TITLE
update traffic lights on macos when title bar zooms

### LINKED ISSUE #155557: Zoomed title needs to update traffic lights position
image

### PR DESCRIPTION
**Pull request by sbatten**
fixes #155557

This adopts the same technique as Windows because we need to know about the titlebar's counter zoom behavior. however, it removes the workaround for https://github.com/electron/electron/issues/34822 which should be fixed in 18.3.6 when released and adopted

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
I think this is generally an elegant solution but:
* we cannot merge this before we updated Electron and I am not sure that happens soon, I am not even seeing that new Electron version released yet, maybe lobby in with Deepak
* I see a flicker on startup, and I think this is because the traffic lights now are only updated from the workbench which can load slow:
Recording 2022-07-22 at 06 24 10

PS: I find `updateTitleBarOverlay` a bit misleading, this is not an overlay, this is updating the native window controls (maybe then call it "window control overlay").

**Comment by sbatten** [comment]
@bpasero pushed some changes based on the feedback. most of the startup flicker is caused by the electron bug, but I've also added caching to improve the new window experience. With the fix from electron and the caching, there should be minimal to no jumping.

**Review by bpasero — CHANGES_REQUESTED** [review]
Please rather use the `IStateMainService` if you must cache something in `electron-main`, given: https://github.com/microsoft/vscode/blob/9aea0a6c112941c0635b635da91fefecd7dbfd38/src/vs/platform/storage/electron-main/storageMainService.ts#L251-L262

**Review by bpasero — APPROVED** [review]
Pushed a change to address this and gave it some testing on macOS, not Windows though. I am not sure if there is any downside in calling `updateWindowControls` on every startup even when the title area is not specially configured in any way.

**Comment by sbatten** [comment]
@bpasero thank you for that, i just test with the electron 19 build and it seems to work well

**Pull request merged**
