### PR TITLE
Replace languageId by languageSelector in all language feature registration functions

### LINKED ISSUE #2985: [Feature Request] Allow to register a language provider using a language selector instead of a single language
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

all `register*Provider` methods in monaco.languages take a `languageId` as first parameter.

However, they are just calling the `register` method from `LanguageFeatureRegistry` which can take a whole `LanguageSelector` as parameter.

### PR DESCRIPTION
**Pull request by CGNonofr**
It allows to register a language provider on more than one language at once.

This PR fixes https://github.com/microsoft/monaco-editor/issues/2985

### CODE REVIEW

**Comment by hediet** [comment]
This change has no runtime implications, it just affects typing and parameter names.

The suggested change looks reasonable.

**Comment by alexdima** [comment]
Thank you!

**Comment by CGNonofr** [comment]
btw, shouldn't it appear in the monaco-editor 0.33 changelog?

**Comment by hediet** [comment]
Sorry, we missed that!
It would be awesome if you could file a PR to monaco-editor to update the changelog.

Unfortunately we cannot update 0.33.0 on NPM anymore.

**Comment by CGNonofr** [comment]
:+1: => https://github.com/microsoft/monaco-editor/pull/3022

**Pull request merged**
