### PR TITLE
update description of `editor.accessibilitySupport`

### LINKED ISSUE #167975: improve description of `accessibilitySupport` setting
This setting has implications from the terminal to search to the editor and we should probably describe these here

Screenshot 2022-12-02 at 4 40 50 PM

### PR DESCRIPTION
**Pull request by meganrogge**
fix #167975

### CODE REVIEW

**Review by lramos15 — CHANGES_REQUESTED** [review]
We try and use `productService.nameShort` and not hard code VS Code so that it says `VS Code` and `VS Code - Insiders` in the appropriate channels

**Comment by meganrogge** [comment]
Just explored this and it will be really involved - would have to separate this setting from the `EditorOptions` such that `productService` can be passed in. 

@alexdima thoughts?

**Review by alexdima — DISMISSED** [review]
I agree, we shouldn't hard code VS Code in the settings names. Maybe we can use a more generic term than editor, like "workbench".

@bpasero You have a lot of experience in this area, do you have any advice?

**Comment by bpasero** [comment]
Yeah, we should not encode the application name. I typically refer then to "application" or "window". I typically also stay away from using "workbench" I think:

image

**Comment by alexdima** [comment]
:+1: We could also just omit the subject:
* auto: "use platform APIs to detect when a Screen Reader is attached"
* on: "assume a Screen Reader is attached"
* off: "assume a Screen Reader is not attached"
* "Controls if a Screen Reader is attached and the UI should optimize for it."

**Review by sandy081 — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
