### PR TITLE
Add tasks config in workspace file

### PR DESCRIPTION
**Pull request by alexr00**
Part https://github.com/microsoft/vscode/issues/1435

### CODE REVIEW

**Comment by alexr00** [comment]
Some notes on how this works:
- You can now have tasks in .code-workspace files and user settings
- There is **no** merging of tasks. Tasks that come from settings are separate from tasks.json are separate from .code-workspace.
- If you don't specify the cwd for the task then it will run in the folder you have open. If you have multiple folders open it runs in the first folder.
- This does **not** enable tasks when you don't have any folder open.
- If you define "global" task properties (i.e. properties that aren't specific to a task) they will **not** get inherited.

**Comment by alexr00** [comment]
Example of what this looks like when a workspace is open:
image

Example of what this looks like when there is no workspace open:
image

The folder name after the task name while in a workspace is existing behavior.

**Comment by alexr00** [comment]
@sandy081 this PR now just contains the changes needed to include tasks in .code-workspace

**Comment by sandy081** [comment]
1. Looks like updating workspace tasks through API is not implemented. Please check here https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L433

2. Please add tests for reading/updating tasks in workspace

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configuration/test/electron-browser/configurationService.test.ts#L1359

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configuration/test/electron-browser/configurationService.test.ts#L1486

**Review by sandy081 — CHANGES_REQUESTED** [review]
Missing support for updating workspace tasks through API and tests

**Review by sandy081 — APPROVED** [review]

**Comment by sandy081** [comment]
LGTM

**Comment by alexr00** [comment]
Thanks, I will merge in the October milestone!

**Comment by alexr00** [comment]
@isidorn I've merged tasks in .code-workspace files, however you still can't reference a prelaunch task in a workspace file. For workspace file tasks, you need to pass the IWorkspace to `getTask` and I didn't see an obvious way to get that.

Alternatively, if debug doesn't have the IWorkspace, the task system could just "guess" that the task requested is from the workspace file or settings if undefined is passed in.

**Comment by isidorn** [comment]
@alexr00 but I pass the workspaceFolder when I call teh `getTask` [here](https://github.com/Microsoft/vscode/blob/24bf6ecccb876f0301338f2bfa61a694e999be57/src/vs/workbench/contrib/debug/browser/debugService.ts#L761)
If you do not get a workspaceFolder in  that case I would think this is a bug on my end.

**Comment by alexr00** [comment]
When the launch config comes from the workspace file, you pass undefined. Even if you passed the workspace folder there would be a problem. If you pass a workspace folder then the tasks system look, for tasks defined in a tasks.json in that folder. Instead, you want the tasks defined in the .code-workspace file.

**Comment by isidorn** [comment]
Oke

**Pull request merged**
