### PR TITLE
avoid stray console log in code.

### PR DESCRIPTION
**Pull request by rebornix**
Though I check the diff changes before commit, I often miss a few `console.log` in the code. Maybe hygiene is a better place for doing this work.

This is my first time touching this hygine check so asking @joaomoreno for review.

### CODE REVIEW

**Comment by joaomoreno** [comment]
> [16:52:23] Error: Hygiene failed with 84 errors. Check 'build / gulpfile.hygiene.js'.

😆

**Comment by rebornix** [comment]
LOL, they should be ignore.

**Comment by bpasero** [comment]
Very cool 👍

**Review by joaomoreno — CHANGES_REQUESTED** [review]
We gotta find a way to have valid console.log calls.

**Comment by 5tunt** [comment]
why is this blocked

**Comment by bpasero** [comment]
It could simply do something similar as the unicode filter that allows for a `allow-any-unicode-next-line` comment:

https://github.com/microsoft/vscode/blob/009db05ffbf0a3e506e533196e2e2c9941521a77/build/hygiene.js#L47-L54

**Comment by 5tunt** [comment]
)$ git clone https://git.kernel.org/pub/scm/git/git.git

**Pull request closed without merging**
