### PR TITLE
Add context keys for platforms

### LINKED ISSUE #8962: Operating Specific Keybindings
I have a company issued OSX machine, linux boxes and windows machines all of which I do dev work on, moving back and forth, I try to keep my settings in sync, it would be very nice to have an operating specific syntax for the keybindings file, much how tasks.json does.

```json
{
	"version": "0.1.0",
	"windows": [
		{
			"key": "win+b",
			"command": "workbench.action.tasks.build"
		},{
			"key": "win+d",
			"command": "workbench.action.tasks.terminate"
		}
	],
	"osx": [
		{
			"key": "cmd+b",
			"command": "workbench.action.tasks.build"
		},{
			"key": "cmd+d",
			"command": "workbench.action.tasks.terminate"
		}
	]
}
```
Or better yet in line with #871 ...
```json
{
	"windows": [
		{
			"key": "win+b",
			"command": [
				"workbench.action.tasks.terminate",
				"workbench.action.tasks.build"
			]
		},{
			"key": "win+l",
			"command": "workbench.action.tasks.showLog"
		}
	],
	"osx": [
		{
			"key": "cmd+b",
			"command": [
				"workbench.action.tasks.terminate",
				"workbench.action.tasks.build"
			]
		},{
			"key": "cmd+l",
			"command": "workbench.action.tasks.showLog"
		}
	]
}

```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #8962 

---

This allows the following when clauses:

- `"when": "isLinux"`
- `"when": "isMac"`
- `"when": "isWindows"`
- `"when": "!isLinux"` (isMac || isWindows)
- `"when": "!isMac"` (isLinux || isWindows) 
- `"when": "!isWindows"` (isLinux || isMac)

### CODE REVIEW

**Comment by alexandrudima** [comment]
:+1:

**Comment by alexandrudima** [comment]
This PR will make PR https://github.com/Microsoft/vscode/pull/45995 obsolete

**Comment by GandalfSaxe** [comment]
Does this work for settings as well? Or should I make a separate issue for that?

**Comment by Tyriar** [comment]
@GandalfSaxe it doesn't work for settings as they don't support when clauses, I image the solution there would look similar to language-specific settings:

```
{
  [os=linux]: {
    blah
  }
}
```

I think there's an issue tracking this.

**Comment by GandalfSaxe** [comment]
@Tyriar That makes sense. That'd be really great to have!

I don't think there is an existing issue. The only I could find was #5595, which was closed with reference to the very issue this PR fixed, #8962. Unless you can find a relevant issue, I'll make a new one shortly 🙂

**Comment by Tyriar** [comment]
@GandalfSaxe I opened that issue, thanks.

**Comment by GandalfSaxe** [comment]
@Tyriar Did this PR stop working? I can make a separate issue, but they don't seem to work for me anymore. It's like they're completely ignored now.

See the following video, where I try to set a shortcut for `git.clean` (discard):

**Comment by Tyriar** [comment]
@GandalfSaxe seems to be working for me? 😕 

Does the actual keybinding work? Maybe it's an issue with the context menu?

**Comment by GandalfSaxe** [comment]
@Tyriar Sorry I was too quick there. I did a bit of testing, and it turned out to be quite a subtle issue not related to this PR at all - it seems to work perfectly.

I tried to use ⌃⌘D as a shortcut, and it turnes out that this is an undocumented global shortcut for looking up the selected word in the macOS Dictionary app. But it doesn't show up in System Preferences -> Keyboard -> Shortcuts. Instead you have to run a terminal command and restart: https://apple.stackexchange.com/questions/22785/how-do-i-disable-the-command-control-d-word-definition-keyboard-shortcut-in-os-x

It seems like some other people were affected by this in Emacs. Good to know, and bad on Apple for hiding this shortcut so thoroughly. Anyway, the `when` clause works fine 🙂 


Btw It seems like the issue with the context menu illustrated above is half fixed:

- It no longer shows the Windows shortcut when there is a Mac shortcut also
- However if only a Windows shortcut is set, it does show this even  There is still a bit of an issue in that the context menu show the Windows shortcut even though it doesn't actually work - so it's cosmetic, but misleading.

**Comment by Tyriar** [comment]
@sbatten keybindings that don't match the context are showing in the context menu? See https://github.com/Microsoft/vscode/pull/54894#issuecomment-413517796

**Comment by sbatten** [comment]
@Tyriar yea, I just tested this on an old 1.22 build, it looks like the context menus and application menu ignore context for keybindings.

**Pull request merged**
