### PR TITLE
sticky scroll support namespace / property / struct

### LINKED ISSUE #157375: Sticky Scroll: In C#, namespace, struct, property should stick, attributes shouldn't stick
Does this issue occur when all extensions are disabled?: Almost yes (you need C# extension to make sticky scroll work, and issue happens when only C# extension is enabled)

- VS Code Version: 1.70.0 (system setup), commit: da76f93349a72022ca4670c1b84860304616aaa2
- OS Version: Windows 11 21H2 (22000.832)

### Code:
code

### Actual:
actual

Namespace, property doesn't appear, and attributes appear instead of actual class.

### Expected:
expected

Namespace, property, and actual class should appear.

### Code:
code2

### Actual:
actual2

When you scroll down, Struct doesn't appear.

### Expected:
expected2

Struct should appear.

### PR DESCRIPTION
**Pull request by DingWeizhe**
fix #157375
- support namespace / property / struct.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Instead of sticky scroll hardcoding the `SymbolKind`s it makes sticky, perhaps the [language configuration file](https://code.visualstudio.com/api/language-extensions/language-configuration-guide) of the Symbol Provider should declare which kinds are sticky.

**Comment by DingWeizhe** [comment]
To discuss the topic more clearly, I split this PR into two PR

**Comment by DingWeizhe** [comment]
In fact, I think it should not be judged against Kind,
Otherwise, it would be difficult to specify what is needed and what is not needed in various programming languages.

@gjsjohnmurray  suggestion of letting users customize is a good idea, but I think the list should be a list of disabled kinds, not enabled. otherwise we still need to have a default enabled list for each language.

Also without judging against Kind, in some programming languages (like HTML or JSON) there will be too many lines sticking, which I think can be solved by sticking only the last N lines.

**Comment by gjsjohnmurray** [comment]
> To discuss the topic more clearly, I split this PR into two PR. another one here: #157441

Other PR is actually #157466

**Comment by DingWeizhe** [comment]
> > To discuss the topic more clearly, I split this PR into two PR. another one here: #157441
> 
> Other PR is actually #157466

thanks for the correction

**Comment by DingWeizhe** [comment]
the problem is sloved by PR https://github.com/microsoft/vscode/pull/157483

**Pull request closed without merging**
