### PR TITLE
Add config parameter to disable collapsible cursors (#37967)

### PR DESCRIPTION
**Pull request by KarelCasier**
Fix to issue: https://github.com/Microsoft/vscode/issues/37967

Initial Behaviour:
initial_behaviour

Disable collapsible cursors in user settings:
```
{
    "editor.multiCursorCollapsible": false
}
```

New Behaviour:
new_behaviour

### CODE REVIEW

**Comment by alexandrudima** [comment]
Thank you for your contribution!

**Comment by brunoscopelliti** [comment]
Hey @alexandrudima ,
I'm happy to see this is moving, anyway I seem not to be able to set `"editor.multiCursorCollapsible": false`. When I try, I get the *Unknown configuration settings* warning.
Also when I search between the available settings, I get no results for `multiCursorCollapsible`.

I've just updated vscode to version **1.22.1**.
Any thoughts?

**Comment by brunoscopelliti** [comment]
I get the *Unknown configuration settings* warning also for `editor.multiCursorMergeOverlapping`.

**Comment by alexandrudima** [comment]
@brunoscopelliti You need an insiders build which contains the change. Changes pushed on Friday make their way only to the Monday insiders build (i.e. we don't publish insiders builds on the weekend). There is a build from 4 hrs ago (4971d889244a2e569ff03b7211c50e2a159e6e71) which should contain this change.

**Comment by brunoscopelliti** [comment]
@alexandrudima Thanks for the clarification.

**Pull request merged**
