### PR TITLE
FIXED: issue window opened as modal/child, fixes #42024

### LINKED ISSUE #42024: Issue reporter: why it is "always on top"?
Version 1.20.0-insider
Commit 60440c72461e96893766bce73d7bdf1f5136a19f
Date 2018-01-23T07:19:15.823Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10 x64

Steps to Reproduce:

1. Cmd/Ctrl + p and choose "Help: open issue reporter"

What happens?
The window that opens always stays on top of any other windows (`always on top`).

### PR DESCRIPTION
**Pull request by warpdesign**
I think the issue reporter window shouldn't be opened as `always on top`. This PR opens it as modal instead.

See #42024.

### CODE REVIEW

**Comment by bpasero** [comment]
One thing to keep in mind is that the issue reporter can be opened without any other window being open.

**Comment by nico-onmap** [comment]
Didn't know that: how to reproduce this behavior?

**Comment by bpasero** [comment]
@nico-onmap the idea is that from the help menu you can "Report Issue" and it would open the reporter.

**Comment by nico-onmap** [comment]
Right, I was thinking about Windows where you cannot have a menu bar without a window. But on macOS (and Linux) it can happen indeed.

**Comment by bpasero** [comment]
@nico-onmap yeah macOS only

**Comment by nico-onmap** [comment]
@bpasero This should handle macOS special case properly now.

**Comment by nico-onmap** [comment]
After all, using modal option wasn't such a good idea: in macOS, sheets are used when modal is specified, and they have no close button, so there was no way to close the issue reporter without sending a new report.

I only left the `parent` option, which will be null if there is no window opened which is fine: this is the default option for this paremeter.

**Comment by RMacfarlane** [comment]
@nico-onmap Thanks, this looks good

**Pull request merged**
