### PR TITLE
Fix for issue #39458

### PR DESCRIPTION
**Pull request by bitshiftza**
Fixes #39458 
Implemented algorithm for determining code preview popup content based off matching brackets.

### CODE REVIEW

**Comment by bitshiftza** [comment]
@jrieken Closed the previous PR #52259  (made a small mess). This one has the algorithm implemented with the changes you suggested in the previous PR.

**Comment by bitshiftza** [comment]
@jrieken Closed the previous PR #52259  (made a small mess). This one has the algorithm implemented with the changes you suggested in the previous PR.

**Comment by jrieken** [comment]
lgtm. thanks @bitshiftza

**Comment by hediet** [comment]
I did not manage to trigger `getPreviewRangeBasedOnBrackets` by using the PHP or TypeScript language server.
Since `targetSelectionRange` seems to be set always in my experiments, I assume `getPreviewRangeBasedOnBrackets` is no longer needed.

As there are no tests for this code and the code is hard to read and undocumented, I removed it in 1d7f8442.

This helps me to refactor `findNextBracket`, as this piece of code no longer holds me hostage.

I'm sure the new bracket pair matching API would make this algorithm obsolete anyway.

**Pull request merged**
