### PR TITLE
Use `-` instead of `0` on count badges

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR implements an[ idea from @bilogic](https://github.com/microsoft/vscode/issues/168820#issuecomment-1539821681) on #168820, which was supported by @lszomoru and @daviddossett

After:
Screenshot 2023-09-21 110312

Before:
Screenshot 2023-09-21 110049

And a mockup trying U+2219 (Bullet Operator) as an alternative to the "-" character in one place:
Screenshot 2023-09-21 105828

As currently implemented all count badges with a zero value use the new symbol unless the constructor call explicitly specifes `false` on the new `symbolicZero` property of ICountBadgeOptions

### CODE REVIEW

**Comment by bilogic** [comment]
Thanks! Really appreciate your help!

**Comment by bilogic** [comment]
Anything I can do to move this forward?

**Review by imbobz — APPROVED** [review]

**Comment by bilogic** [comment]
Help :)

**Comment by gjsjohnmurray** [comment]
@bilogic the team are in endgame at the moment. I'm hoping this may get attention from one of them next week 🤞

**Review by imbobz — APPROVED** [review]

**Comment by lszomoru** [comment]
Thank you all for your patience. We have discussed this internally and we have explored multiple options: 1) hide the counter when the value is `0`, 2) use a special character, 3) use colour to distinguish. Since there are already multiple places in the product where the counter is only being shown when the value is non-zero, I would like us to explore this option in the source control repositories view. I will go ahead and explore this approach and will update the PR with my findings.

**Comment by lszomoru** [comment]
Further looked into this and I have stumbled upon the `scm.providerCountBadge` setting which was added couple of years ago. As we already have a setting, I have made changes so that the "Source Control Repositories" view uses this setting. Let's see how it feels and we can adjust the behaviour based on feedback. Here is a PR with my change - https://github.com/microsoft/vscode/pull/194696.

**Pull request closed without merging**
