### PR TITLE
fix: change default keybinding of cursorColumnSelectUp to ctrl+shift+…

### LINKED ISSUE #36819: Change default keybinding of cursorColumnSelectUp to ctrl+shift+up on Windows
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063

Current default keybindings on Windows:

```json
{ "key": "ctrl+shift+alt+up",     "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
// ...
{ "key": "ctrl+shift+up",         "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
{ "key": "shift+up",              "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
```

`cursorUpSelect` has two key bindings, which seems unnecessary. On Linux the default key bindings are (IIRC):

```json
{ "key": "ctrl+shift+up",         "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
// ...
{ "key": "shift+up",              "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
```

Which makes a lot more sense IMHO. Also using this default on Windows would also align Windows/Linux key bindings and maybe even avoid complications like #4391.

(same for `*Down` of course)

### PR DESCRIPTION
**Pull request by mikaoelitiana**
…up on Windows

fixes #36819

### CODE REVIEW

**Comment by alexandrudima** [comment]
I actually ended up reverting this commit.

I cannot accept it because the column selection keybindings work together:
```
{ "key": "ctrl+shift+alt+down",   "command": "cursorColumnSelectDown",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+left",   "command": "cursorColumnSelectLeft",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+pageup", "command": "cursorColumnSelectPageUp",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+right",  "command": "cursorColumnSelectRight",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+up",     "command": "cursorColumnSelectUp",
                                     "when": "textInputFocus" },
```

Changing just two of them only creates confusion. And we cannot change all of them because ctrl+shift+left and ctrl+shift+right are used for word selection.

**Comment by jhasse** [comment]
What's the difference between `cursorColumnSelectLeft` and a simple <kbd>Shift</kbd>+<kbd>Left</kbd>?

**Comment by alexandrudima** [comment]
The latter wraps (goes up) at line starts.

**Comment by jhasse** [comment]
Ah I see, quite a minor detail IMHO.  Also it doesn't seem to work with multiple cursors for me or is this a bug? If not, I don't see the use-case for the command at all.

I'm using `cursorColumnSelectUp/Down` to quickly get multiple cursors in a straight line. As I can't even use `cursorColumnSelectLeft` after that in a meaningful way and they do different things (adding a new cusor vs. expanding the selection), I don't see how they are related (beside the name).

Also note that `cursorColumnSelectLeft/Right` doesn't have any keybindings assigned by default on Linux and no one seems to mind (no issue about it).

**Pull request merged**
