### PR TITLE
Show warning for a long commit message

### LINKED ISSUE #7138: Enhance git commit message (show a counter with (50 - commit message length))
I am using VSCode on Ubuntu 14.04 x64

VSCode About:

Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:30:20.458Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

Steps to Reproduce:

1. Open a git repo folder
2. Make a change
3. Go the "GIT" tab
4. Start typing a git message

I am thinking of a counter starting with 50 (The number of character that'll be used as the short message appearing in git commits), it helps write meaning full messages, without have a word cut and completed in the description part, the behavior is taken as is from GitKraken

### PR DESCRIPTION
**Pull request by sijad**
fixes #7138
50 characters limit is hardcoded, should it be a configurable setting?

### CODE REVIEW

**Comment by sijad** [comment]
I'm not sure about the message if you could help me come up with a better one that would be great,
also in this new changes only first line of commit will check, what about to check if other lines are under 72 character?

[stopwritingramblingcommitmessages](http://stopwritingramblingcommitmessages.com/):

> Keep your message to 50 characters or less
> If you have more to say than that, put it in additional paragraphs wrapped to 72 characters.

**Comment by joaomoreno** [comment]
Thanks, looks great! I've added a few more changes on top:

- Rephrased it to `It is recommended to keep the commit's first line under 50 characters. Feel free to use more lines for extra information.`
- Added a `git.enableLongCommitWarning` configuration setting for those who don't want to be disturbed
- Changed the `String` split for a `RegExp`.

**Comment by massimocode** [comment]
Hey should this be disabled by default? Or at least a bit more generous than 50 chars?

**Comment by massimocode** [comment]
I just looked it up and found this conversation on SO
http://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting

Seems like the linux kernel contributions recommend 70-75 chars max. Those guys live on the command line where these things matter so I'm guessing we can be a little more relaxed than 50 characters.

**Comment by massimocode** [comment]
Looks like the git commit man page recommends 50 characters or less
https://www.kernel.org/pub/software/scm/git/docs/git-commit.html#_discussion

I gotta go retrain myself!

**Comment by Pho3nixHun** [comment]
Can we have this 50 character limit as a variable in the config and not hardcoded?

**Comment by n370** [comment]
@Pho3nixHun fair enough!

**Comment by robsonsobral** [comment]
Is this dead?

**Pull request merged**
