### PR TITLE
List Navigation for accessibility focus/tabindex  Issue #24119 (replaces PR #24628)

### PR DESCRIPTION
**Pull request by cleidigh**
Cleaned commits
added modifications for both extensions and SCM
See issue #24119 and replaced PR #24628  for main comments

AfterReview still need to address listing key bindings
and up\down after action Escape
Ideally bubble action keyboard events to list row container
Make key bindings list behave the same

### CODE REVIEW

**Comment by cleidigh** [comment]
@joaomoreno 
- Extensions, SCM and key bindings list all parallel operation
- focus enables action items
- can Tab to manage extension when line has focus - previously had to Tab back
- can select add or clean with Tab in SCM without open operation required which lost focus to editor

- still would like to capture escape to refocus list item not sure how to bubble up

should be good point for review

**Comment by joaomoreno** [comment]
I see a few issues in the current state:

- Extensions view:
  - Focus the list. Press <kbd>Down</kbd> and <kbd>Up</kbd> a few times, you can go up and down in the list. Press <kbd>Tab</kbd> to focus the focused element's actions. Press <kbd>Tab</kbd> again to focus what comes after the action bar. Press <kbd>Shift Tab</kbd> twice to focus back to the list. Now <kbd>Down</kbd> and <kbd>Up</kbd> no longer work.
- SCM view:
  - It has exactly the same issue as the extensions view. Plus:
  - Focus the list. Press <kbd>Tab</kbd> to focus the inline actions. <kbd>Down</kbd> and <kbd>Up</kbd> are still handled by the list when focused in the action bar.

All in all, the PR touches a lot of code. It would be great if we took smaller steps. First: tackle any list accessibility issues. Then, descend onto the use cases and see why they really break.

**Comment by cleidigh** [comment]
@joaomoreno 
Thanks for the review!
I totally agree about the up/down issue it's also related to why I wanted to capture Escape with an action item focused. This is a problem currently if you press escape when an action item is focused
you end up without a focus and unable to use up/down

I also agree this touches more files than I would like. because of the tab and ask issue I could not figure out a simple way. I'm not sure what smaller steps might make sense. let me bullet point the main
things I was trying to accomplish:

- make the three current list -based functions operate as parallel as possible
- conservation of keystrokes to get to actions 
- make keyboard focus equivalent to mouse hover (I think this makes sense as a UI behavior for lists)

Specifically for the extensions list:
- there is currently no relationship between the focused or selected line and the actions associated with it,
if you arrow to an extension, check out its home page you have to completely Tab back to the item
to do any of the actions 

SCM
- you cannot get to the actions without being forced to press Enter, forcing opening up diff and having to go back to SCM to get to the actions. I do realize you can use the context menu.

Maybe addressing the action access with Tab for SCM would be a smaller first step - have to fix the up/down issue mentioned.

I guess the main question for you is if you agree that list focus be equivalent to hover allowing access 
to the actions on the same line with the next Tab focus? If not then maybe I'm barking up the wrong tree ;-)

Either way I'm hoping to contribute something to the April Release. 

Thanks and let me know what you think is best to proceed...

**Comment by joaomoreno** [comment]
> I guess the main question for you is if you agree that list focus be equivalent to hover allowing access to the actions on the same line with the next Tab focus? If not then maybe I'm barking up the wrong tree ;-)

Yes, that sounds like the first logical step. Let's start here.

Also, in my opinion, the up and down keys shouldn't work at all when the actions are focused. They should only work when the list itself is focused.

**Comment by cleidigh** [comment]
@joaomoreno 
Agree about the Up and Down. I think this was an unintended consequence of having focus
on the list item and it is still handing these keyboard events.
I've been holding off doing more until you agreed with the focus issue so now I'll look into that.

One other keyboard behavior that is related is the handling of Escape while an action item is focused.
Right now the focus outline will disappear but, the current tab index remains the same nothing focus nothing outlined . you have to Shift+Tab back into the list to navigate. it's a bit of an odd state.

How about returning focus to the list item if escape is pressed on any of the action items of that line ?

**Comment by cleidigh** [comment]
@joaomoreno 
I just confirmed something I had seen before, the list key bindings behavior with the edit action focused
and Up/Down does all sorts of weird things. this appears to be a base issue between actions and the focus list item. by making SCM work more like key bindings you now see the same issue there.

I also think there's some relationship with the issue #25352 when going into and out of the list.

**Comment by joaomoreno** [comment]
> How about returning focus to the list item if escape is pressed on any of the action items of that line?

Makes sense.

**Comment by cleidigh** [comment]
@joaomoreno 
The Up/Down issue was indeed a bubble up issue that currently exists with all lists, just more apparent
depending upon the action bars.

I will push my latest code without removing some of the other code for now so you can see everything.

The one reasonable issue I do not like is that when action items are focused with the keyboard
the line item turns into the inactive color (because the list lose is focus)
I think this looks weird - the old git did not do this, and I think this makes much more sense.
it's a more intertwined problem to fix since you have to detect action bar focus without list focus
and not turn the item inactive.

**Comment by cleidigh** [comment]
@joaomoreno 
I can see there has been a lot of new work, I have to re- based and adjust.
I think I've solved the two main issues and I have an idea on fixing the inactive color.
for the latter I have to incorporate the updated code. I will do a rebase and merge and adjust.
I hope I can do this without too much time, also got distracted with the theme issues.

**Comment by cleidigh** [comment]
did re- base first commit fixes Up Down problem with current action bar code
prevents bubble up
SCM CSS fixed only show action bar items on focus

last problem is to fix list line item going to inactive color when action item is focused
have to look at the new code to see where to do the fix I think I know what to do

**Comment by cleidigh** [comment]
@joaomoreno 
brought back the logical list focus you had before so the item list can have the focus color
when the action bars focused by keyboard

if you can look at the behavior and see if it all makes sense (I think more clearly tracks the old git)
and improves the keyboard experience

**Comment by cleidigh** [comment]
@joaomoreno  
just wanted to check to see if you have an opinion on the SCM list/action handling - 
Hopefully a thumbs up! if so I can finish it by making the key bindings with parallel operation.
Thanks

**Comment by joaomoreno** [comment]
Sorry for the silence @cleidigh, been really busy lately and (un)fortunately I'm going on vacation for a couple of weeks. I'll have to check this when I'm back. But don't take this away, you'r doing good work here.

**Comment by cleidigh** [comment]
@joaomoreno 
No problem, I've seen all the SCM traffic.
have a great vacation !

**Comment by cleidigh** [comment]
@joaomoreno 
Hope you had a good vacation
did you get a chance to look at this?

**Comment by joaomoreno** [comment]
Hi @cleidigh! Thanks for the ping. Unfortunately, not yet. You'll have to wait a short while longer. Sorry for that.

**Comment by joaomoreno** [comment]
@cleidigh I took another approach towards fixing #24119. I believe all issues were addressed.

**Pull request closed without merging**
