### PR TITLE
Replace applicationStorageMainService with stateMainService

### LINKED ISSUE #169363: Use state service for process explorer state
This is a follow up from https://github.com/microsoft/vscode/pull/169090

I would suggest to not use the storage service for process explorer state but `IStateMainService`. That is the same service we also use to store window state for workbench windows.

Using storage service from the main process requires you to await the `whenReady` event because unlike state service, the storage service is not ready when you use it:

https://github.com/microsoft/vscode/blob/461b3f6184b1668be469901bf0fc75a426e0bb81/src/vs/platform/storage/electron-main/storageMainService.ts#L298-L309

State service is always available and can be used as a drop-in replacement.

Here is where its used for windows and the key we use is `windowsState`, so maybe it should be `processExplorerWindowState`.

https://github.com/microsoft/vscode/blob/461b3f6184b1668be469901bf0fc75a426e0bb81/src/vs/platform/windows/electron-main/windowsStateHandler.ts#L217

### PR DESCRIPTION
**Pull request by Kalmaegi**
resolved #169363

### CODE REVIEW

**Comment by weartist** [comment]
@Tyriar  I found a small problem, here if we use the screen scale as a divisor, it will cause the length and width to be reduced when it is created, on Mac, the scale is 2, probably because we did not consider the screen scale when storing?

https://github.com/microsoft/vscode/blob/461b3f6184b1668be469901bf0fc75a426e0bb81/src/vs/platform/issue/electron-main/issueMainService.ts#LL284

**Comment by bpasero** [comment]
Cool!

**Review by Tyriar — CHANGES_REQUESTED** [review]
@weartist oh so do we need to also store the scale and only update it when it changes? Going from one monitor to the other for me worked fine so I think something fishy is going on 🤔

**Comment by weartist** [comment]
> @weartist oh so do we need to also store the scale and only update it when it changes? Going from one monitor to the other for me worked fine so I think something fishy is going on 🤔


It may be related to the operating system, I will look at the related logic, if you do not use scale, will the size of the window on your Windows be enlarged?

**Comment by Tyriar** [comment]
Yes, saving the state on my second monitor would make the window 50% larger when I reopen the explorer.

**Comment by weartist** [comment]
> Yes, saving the state on my second monitor would make the window 50% larger when I reopen the explorer.

That probably does need to be scaled, my monitors have the same resolution, I'll check the logic here

**Comment by bpasero** [comment]
I am not sure if it would be worthwhile maybe making this code reusable:

https://github.com/microsoft/vscode/blob/9e8d78012d76469ca55c2eda2d83d882b30a5479/src/vs/platform/windows/electron-main/windowImpl.ts#L1226

We use it to validate the window state is in bounds of the display. In general I would argue that window state storing and restoring is relatively complex, so there is probably lots of good knowledge already for workbench windows to look at.

**Comment by weartist** [comment]
> I am not sure if it would be worthwhile maybe making this code reusable:
> 
> 
> 
> https://github.com/microsoft/vscode/blob/9e8d78012d76469ca55c2eda2d83d882b30a5479/src/vs/platform/windows/electron-main/windowImpl.ts#L1226
> 
> 
> 
> We use it to validate the window state is in bounds of the display. In general I would argue that window state storing and restoring is relatively complex, so there is probably lots of good knowledge already for workbench windows to look at.
> 
> 
> 
> Here is how we serialize the state: 
> 
> 
> 
> https://github.com/microsoft/vscode/blob/9e8d78012d76469ca55c2eda2d83d882b30a5479/src/vs/platform/windows/electron-main/windowImpl.ts#L1112


Thank! I'll go and understand the logic here

**Comment by weartist** [comment]
@Tyriar   Does your monitor have amplified DPI? e.g 200% DPI
strangely, the size we obtained was already scaleFactor, My monitor resolution is 3840 x 2160, I was at the time of getting its size 1920 x 1080 and scaleFactor is 2, when I drag the new window to full screen, The resulting dimensions are almost 1920 x 1080, It doesn't look like you need to consider scaleFactor, so I was wondering if there were other factors affecting the scaling of the created window, Probably not a location-related issue

**Comment by Tyriar** [comment]
@weartist it's a 4k monitor at 1.5 scale in the OS, next to a 1080p monitor at 1 scale

**Review by Tyriar — APPROVED** [review]
Thanks for the follow up! For the scale issue, I tested it again and it does still happen. it's relatively minor as I think it would only happen when you have mixed scale monitors.

**Review by rebornix — APPROVED** [review]

**Pull request merged**
