### PR TITLE
:up: chokidar@3.4.3

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes ##108441

### CODE REVIEW

**Comment by paulmillr** [comment]
Is there a reason vscode uses several different versions of chokidar & readdirp?

**Comment by bpasero** [comment]
@paulmillr can you clarify? If you mean that we have 2 `package.json`, this is because VSCode ships a client product and a server product (for remote access). In both cases we use `chokidar`, but the versions should match.

**Review by lszomoru — APPROVED** [review]

**Comment by paulmillr** [comment]
Main yarn.lock mentions chokidar@^2.0.0, `chokidar@*`, chokidar@2.1.8, chokidar@3.4.0.

**Comment by bpasero** [comment]
@paulmillr those are very likely just `devDependencies`...

**Pull request merged**
