### PR TITLE
fix: snap package validation

### LINKED ISSUE #127081: Snap packages fail validation
Snap packages are now failing validation with the following two errors:

- found errors in file output: unusual mode 'rwsr-xr-x' for entry './usr/share/code-insiders/chrome-sandbox' security-snap-v2_squashfs_files
- checksums do not match. Please ensure the snap is created with either 'snapcraft pack <DIR>' (using snapcraft >= 2.38) or 'mksquashfs <dir> <snap> -noappend -comp xz -all-root -no-xattrs -no-fragments' (using squashfs-tools >= 4.3). If using electron-builder, please upgrade to latest stable (>= 20.14.7). See https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/17 for details. security-snap-v2_squashfs_repack_checksum What does this mean?

Very likely broken by https://github.com/microsoft/vscode/commit/92999c339e2666998bd45d13fa355cecc7947b8b, specifically https://github.com/microsoft/vscode/commit/92999c339e2666998bd45d13fa355cecc7947b8b#diff-74c4ea7e8a7229121137b67faf75b6808d948fbbd120adb7b0f763a52b975dedR30-R32

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/127081

### CODE REVIEW

**Comment by deepak1556** [comment]
To verify `SNAP_ENFORCE_RESQUASHFS=1 snap-review <path-to>/code-insiders.snap`

- [ ] Validated

**Comment by deepak1556** [comment]
Since resquash test doesn't allow setuid bit for `chrome-sandbox`, if we need to pass the validation step then we cannot chmod `4755` in any of the lifecycle steps. Two options for snap package,

1) Always disable sandbox but eventually we should change our confinement from classic for this to be safer.

2) Disable setuid sandbox, so that app always default to user namespace sandbox which is available on all kernels >=3.10. For users unable to use namespace sandbox suggest workaround https://github.com/electron/electron/issues/17972#issuecomment-486927073 if they can configure.

**Comment by deepak1556** [comment]
Another option, reach out to the snapcraft team and see if we can get an exception in the resquash test.

**Comment by bpasero** [comment]
my 2 cents: if we cannot get sandbox to work with snap, we should stop releasing VSCode on snap.

Until we are there to enable sandbox, we can go back to no sandbox if that helps for snap only.

**Comment by deepak1556** [comment]
Agree, will disable sandbox in snap for now, opened https://github.com/microsoft/vscode/issues/127140 to track next steps.

**Pull request closed without merging**
