### PR TITLE
Plan item #41678 enable @ts-check 

### PR DESCRIPTION
**Pull request by egamma**

### CODE REVIEW

**Comment by joaomoreno** [comment]
@egamma As Travis and AppVeyor complain, there's a problem with this. The build folder fails to build:

```
build → npm run compile> code-oss-dev-build@1.0.0 compile /Users/joao/Work/vscode/build> tscerror TS5055: Cannot write file '/Users/joao/Work/vscode/build/dependencies.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.editor.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.extensions.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.hygiene.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.mixin.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.test.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.vscode.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.vscode.linux.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/gulpfile.vscode.win32.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/lib/builtInExtensions.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/lib/electron.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/joao/Work/vscode/build/lib/watch/index.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/lib/watch/watch-nsfw.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/lib/watch/watch-win32.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/npm/postinstall.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/joao/Work/vscode/build/npm/preinstall.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/build/npm/update-all-grammars.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/joao/Work/vscode/build/npm/update-grammar.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/joao/Work/vscode/build/npm/update-theme.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/src/buildfile.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/joao/Work/vscode/src/vs/code/buildfile.js' because it would overwrite input file.error TS5055: Cannot write file '/Users/joao/Work/vscode/src/vs/workbench/buildfile.js' because it would overwrite input file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev-build@1.0.0 compile: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev-build@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joao/.npm/_logs/2018-01-25T16_00_11_441Z-debug.log
```

**Comment by joaomoreno** [comment]
@egamma Also... how exactly does `src/buildfile.js` get checked? It doesn't have a `@ts-check` marker nor does its corresponding `tsconfig.json` have `checkJS`...

**Comment by egamma** [comment]
> @egamma As Travis and AppVeyor complain, there's a problem with this. The build folder fails to build:

The issue is that when you enable allowJS in the tsconfig.json, then TypeScript will transpile the JS files.  I need to find a way to specifc `--noEmit` for the .js files.

**Comment by egamma** [comment]
> @egamma Also... how exactly does src/buildfile.js get checked? It doesn't have a @ts-check marker nor does its corresponding tsconfig.json have checkJS...

I was surprised as well, but the TS type checker reaches it also when running `tsc --noEmit` from the `build` folder. So I assume there is a dependency from a source file in the build folder to src/buildfile.js.

**Comment by joaomoreno** [comment]
You're right!

https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L25

**Comment by egamma** [comment]
Here is the issue, when you want to enable `checkJS` in the tsconfig.json then you also must enable `allowJS`. Now, when you enable allowJS then TypeScript will compile and emit output for .js files (useful when you want to downlevel compile JS).

I see different options:

1. add @ts-check to all the .js files we want to have type checked. Downside is that we must remember to add the comment to the .js files. Also it is not clear to me how I can configure the parameters you would configure in the tsconfig.json.

1. Add the setting `"javascript.implicitProjectConfig.checkJs": true` as a workspace setting. It seems that this doesn´t affect compilation, but adds many more files to the language server and this might slow down things. 

1. Add two tsconfig.json files to the build folder. One is used by the language service and will be used for checking, one will be used for compiling the project during the build.

I´ll add option 2) to the PR for testing.

**Comment by egamma** [comment]
Hmm, .js files are still compiled so option 2 is not an option...

**Comment by egamma** [comment]
I´ve looked into options 2) and 3). The issue with these options is that the project of the tsconfig.json in the `build` folder is ignored. This means some typings are not retrieved from the `build` folder but from the global typings cache. The version of a global typing can differ from the one inside the build folders. This means you get different error messages from Typescript. You can work around them by adding reference path comments that point to the typings in the `build` folder.
```ts
/// <reference path='lib/typings/event-stream.d.ts'/>
```
Such comments are a pain to maintain and duplicates the project context from the tsconfig.json.

My conclusion is that the checkJS must use the project context defined by `tsconfig.json` and that Typescript should support that you can enable `checkJS` without having to enable `allowJS`.

**Comment by egamma** [comment]
@joaomoreno closing in favor of #42731 (this one is messy and mixes different experiments).

**Pull request closed without merging**
