### PR TITLE
Enable terminal themes via tmTheme

### LINKED ISSUE #6979: Exploration: Introduce a way for the integrated terminal to be themed
In a post-#6766 world. Need to be able to customize the 16 primary colors as well as foreground and background as a minimum. Font size/line height and other layout-related settings may also be included?

---
- [x] Implement terminal themes
- [ ] Add documentation
- [ ] Add terminal theme color sets to vscode's themes

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #6979

@sandy081 @aeschli @alexandrudima requesting feedback on the approach.

image

### CODE REVIEW

**Review by sandy081 — COMMENTED** [review]
@Tyriar In Terminal theme contribution only `color` is set. But I see following selectors  are also applied

```
.monaco-workbench .panel.integrated-terminal .xterm .xterm-color-${index} { color: ${color}; }` +
                `.monaco-workbench .panel.integrated-terminal .xterm .xterm-color-${index}::selection { background-color: ${rgba}; }` +
                `.monaco-workbench .panel.integrated-terminal .xterm .xterm-bg-color-${index} { background-color: ${color}; }` +
                `.monaco-workbench .panel.integrated-terminal .xterm .xterm-bg-color-${index}::selection { color: ${color}; }`;
```

Why not others are not set?

**Comment by Tyriar** [comment]
@sandy081 yeah I'll need to add selection and background colors. What do you think about the `terminal*` global properties in tmThemes?

**Comment by sandy081** [comment]
@Tyriar `terminal*` properties looks ok to me. Assuming they are the properties used in other terminal themes. Putting under a scope also makes sense, not sure if it overlaps or scopes are only used for editor tokens.

- You would also need to adopt these properties in our packaged themes (in extensions folder).
- I see there are lot of terminal themes available for other terminals, it would be nice to generate our themes from those themes. @aeschli might help you here.
- We would also need to document these new settings

**Comment by Tyriar** [comment]
I didn't explicitly state this but this is an entirely new set of global properties just like the find/highlight colors that only VS Code reads. It's a little tricky to automate generation but certainly possible, what would need to happen for theme generation:

- Do the regular generation on a tmTheme
- Source the colors from one of the various formats in https://github.com/mbadolato/iTerm2-Color-Schemes or something, I found terminator formats the easiest to pull the colors from
- Insert them into the previously generated tmTheme

I think you would be asking for trouble if you tried to add it to a scope, if encapsulating these is that important maybe grouping them in another dict within the global settings would work (but that may break other tmTheme parsers).

Here's a little background on the topic if you didn't see it https://github.com/Microsoft/vscode/issues/6766, the options are basically:

- Add a bunch of settings for the ansi colors (rejected in https://github.com/Microsoft/vscode/issues/6766). Now that settings can be modified by extensions themes could edit these now, it's not a particularly elegant solution though
- Add the colors to global settings in tmThemes (this PR)
- Integrate with some other already existing theme format such that a theme extension can include a terminal theme in addition to a tmTheme

**Comment by sandy081** [comment]
@Tyriar Thanks for the explanation. 

I am ok with current approach (global settings). Please make sure that you also take care of following

- Adding selection and background colours
- Adopt in our packaged themes
- Documentation
- Generation strategy

Thanks.

LGTM

**Review by sandy081 — APPROVED** [review]

**Comment by Tyriar** [comment]
Renamed to use the prefix `ansi` instead of `terminal` as it's more correct and would make more sense if we want to use them elsewhere. Going to push this and reopen #6979 to track the remaining items.

**Comment by aeschli** [comment]
@Tyriar I'm also ok with the suggested changes.
- having a separate dictionary in the plist file should not be an issue. plist is just a key-value store, and these are basically our themes now, no requirement that they can be consumed by others. There's also the JSON format witch I use for the default themes.
- You'd still need to add good defaults if case a theme does not contain any terminal colors. I suggest to do this in still in your css (not in the theme service)
- users would use our yeoman generator https://github.com/Microsoft/vscode-generator-code to create a theme from an existing theme. You could help them there by asking if you want to add terminal colors as well.

**Comment by Tyriar** [comment]
@aeschli do you mean something like this?

```xml
<dict>
	<key>name</key>
	<string>Monokai</string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#272822</string>
				...
			</dict>
		</dict>
		<dict>
			<key>ansiColors</key>
			<dict>
				<key>red</key>
				<string>...</string>
				...
			</dict>
		</dict>
```

The defaults are staying the same as they were previously. Good idea on the generator, but how do we generate our own packaged themes? Or were they just a one time conversion/fork?

**Comment by fungl164** [comment]
Hi, would it be possible to have a light editor theme with a dark background for the terminal when using custom colors through this feature?  The contrast is highly valuable.
  
Also, what is the current status of this for creating custom themes? Many thanks!

**Comment by Tyriar** [comment]
@fungl164 this has been put on hold until workbench themes has been looked into https://github.com/Microsoft/vscode/issues/3112, since the terminal is part of the workbench it will probably be themed using a different mechanism.

**Comment by fungl164** [comment]
Ok.  Thanks you!

**Pull request merged**
