### PR TITLE
fix 235221: Sanitizing the html content by closing the unclosed tags

### LINKED ISSUE #235221: Unclosed markdown comment at the end of the file causes local markdown link at the start of the file to malfunction
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows 10 (19045)

Just watch til the end.

https://github.com/user-attachments/assets/ae9da5f4-398a-4ee6-97e5-48006e0dc96e

### PR DESCRIPTION
**Pull request by Parasaran-Python**
fix #235221: Sanitizing the html content and closing the unclosed tags

The unclosed comment tag in markdown causes a breakage in the final html thats generated by the markdown rendering engine.

The script tags for markdown preview which are dynamically inserted to the DOM are engulfed by the unclosed comment tag and are then treated as a part of the comment by the JS engine.

### CODE REVIEW

**Comment by Parasaran-Python** [comment]
In case the explanation in the description wasnt very clear

image

Check the script tag, this is how its expected to be

Due to the unclosed tag in markdown
image

Its rendered as a comment inside the above div tag, thereby causing the breakage

other events like showing markdown text content on dblClick are also not bound due to this breakage.

 @mjbvz could you please go through this PR and provide your inputs.

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look. However I don't think this is the right approach 

Using a regex to try fixing/sanitizing html is not robust. Instead I think we should try switching to use proper dom apis

1.  pass the rendered markdown into the webview, for example in `vscode-markdown-preview-data`
1.  In the webview scripts, use something like `innerHTML` to write the rendered markdown into the document on load

let me know if you have any questions about this

**Comment by Parasaran-Python** [comment]
Sure, dom parsers werent directly working as this code probably is not directly executed in browser env, that's why I had tried the regex approach.

Will try passing this to a webview, in the meanwhile any reference or an example of the same would be helpful @mjbvz in case something of this sort is already being done in this repo.

**Comment by Parasaran-Python** [comment]
> Thanks for taking a look. However I don't think this is the right approach
> 
> Using a regex to try fixing/sanitizing html is not robust. Instead I think we should try switching to use proper dom apis
> 
>     1. pass the rendered markdown into the webview, for example in `vscode-markdown-preview-data`
> 
>     2. In the webview scripts, use something like `innerHTML` to write the rendered markdown into the document on load
> 
> 
> let me know if you have any questions about this

Sure will try the suggested approach.

**Comment by Parasaran-Python** [comment]
@mjbvz I think I understood what you are trying to convey,

image

You suggest passing the markdown content inside an attribute of the shown meta tag

And consuming it inside webview like this

image


Please correct me if I'm wrong.

**Comment by mjbvz** [comment]
Yes that sounds correct 👍

**Comment by Parasaran-Python** [comment]
> Yes that sounds correct 👍

@mjbvz I have made the changes to best of my understanding, could you please re-review.
Thanks.

**Comment by Parasaran-Python** [comment]
Seems like a " in markdown is breaking things, will check.

**Comment by Parasaran-Python** [comment]
Encode and decode seems to fix it,

Tried multiple special chars,

image


works fine.

**Review by mjbvz — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
