### PR TITLE
Change icon name on Linux for icon theme compatibility

### LINKED ISSUE #65750: Use com.visualstudio.code* for Linux icon
See https://github.com/Microsoft/vscode/pull/62650, https://github.com/numixproject/numix-core/issues/2964

### PR DESCRIPTION
**Pull request by beruic**
This change is made under the assumption that the '-oss' part is removed for final official distribution builds.

The issue it resolves can be read about here: https://github.com/numixproject/numix-core/issues/2964

Fixes https://github.com/Microsoft/vscode/issues/65750

### CODE REVIEW

**Comment by wmyhen6** [comment]
Unable to open

**Comment by beruic** [comment]
@wmyhen6 what is it that you are unable to open?
Is it the issue I refer to, or my repository?

**Comment by Tyriar** [comment]
Thanks for the PR but this is not all that would be involved in changing this and it could have knock on effects for some other projects. Seems to me like numix should just add a code icon https://github.com/numixproject/numix-core/issues/2964#issuecomment-210201845

I opened discussion when I joined the team about changing the command from code to vscode to avoid potential conflicts, but at that point it was already too late. Now we're aligning things with the command name, and there haven't been any conflict issues to my knowledge.

**Comment by Tyriar** [comment]
The same concerns exist for the name though, and they turned out not to be a problem. Changing the icon alone would cause work for us and other teams and I don't think it's worth it when numix can just use "code".

**Comment by Tyriar** [comment]
> Other applications use that icon name as a call for a generic icon representing code, editors, etc.

@Foggalong do you have an example of one of these?

**Comment by bilelmoussaoui** [comment]
The new freedesktop standards asks dev's to use a RDNN for the desktop file name and the icon name to avoid this kind of issues. Please don't change the icon to yet an other name and follow the specs.

**Comment by bilelmoussaoui** [comment]
For the FreeDesktop specs:
- Appstream files: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html
- Desktop files: https://standards.freedesktop.org/desktop-entry-spec/latest/
- The desktop file names convention: https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id

**Comment by Tyriar** [comment]
Sounds good, I opened https://github.com/Microsoft/vscode/issues/65750 to track this. It needs a bit more work though, mostly in our product build. I don't have time to look into it just now though.

**Comment by Tyriar** [comment]
@joaomoreno I think this is ready to go, let me know if you see any problems with it. There's a corresponding commit to distro in the tyriar/62650-linux-icon branch

**Review by joaomoreno — APPROVED** [review]
If you run a build and everything works OK, then this lgtm.

**Comment by beruic** [comment]
Can anyone determine which is the right solution to the current merge conflict?

**Comment by Tyriar** [comment]
@beruic I'll be merging this today, it will finally happen this milestone 😉

**Pull request merged**
