### PR TITLE
Resolve tilde-forwardslash in path to home directory

### LINKED ISSUE #43560: Allow for tilde-forwardslash expansion in cli path argument
Some editors provide special expansion for `~/` to user HOME directory. This expansion does not rely on shell's path expansion capability. For example, (unlike Windows PowerShell) in CMD, `~/` has no special meanings, yet nano-editor when invoked as  `nano ~/fs.js` in CMD or PS gets launched with the file `c:\users\username\fs.js`.

Code currently supports delayed expansion for environment variables: `code %userprofile%\fs.js` in CMD or `code $env:UserProfile\fs.js` in PS, but `~/` is not supported in either. Please add support for this popular shortcut.

Note that in Windows, `~\` is not the substitute of `~/`.

### PR DESCRIPTION
**Pull request by am11**
Closes #43560.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
I suggest to implement this without forcing a new NPM dependency onto us.

**Comment by am11** [comment]
@bpasero, I like your suggestion. It actually simplifies the implementation as we only handle `~/` case. OTOH, `untildify` converts `~\` to `$env:HOME` as well, which is not the desired behavior.

Also, only the first occurrence matters, e.g. `~/dir/~/file.ext` would resolve to `c:\users\username\dir\~\file.ext` on Windows.

**Comment by am11** [comment]
@bpasero, I have rebased it over master. Could this be considered for the next release? :)

**Comment by am11** [comment]
@bpasero, this is over an year old. Could you please take another look? Thanks!

**Comment by bpasero** [comment]
Closing, I am not convinced this is the right thing to do.

**Pull request closed without merging**
