### PR TITLE
87456: Configuration to increase the terminal cursor width

### LINKED ISSUE #87456: Configuration to increase the terminal cursor width
There is an option called `editor.cursorWidth` which can be used to increase the cursor width; however, this doesn't change the terminal emulator's cursor width. This is slightly annoying. For example, please see my screenshot:

code

### PR DESCRIPTION
**Pull request by BuraChuhadar**
This PR fixes #87456

This PR would set terminal bar cursor width.

### CODE REVIEW

**Comment by varmanishant** [comment]
Thank You @BuraChuhadar , I think it will be nice if it is called as cursorWidth itself if that is possible? We already have `editor.cursorWidth`.

**Comment by BuraChuhadar** [comment]
@varmanishant added the changes you asked. Let me know if you have other feedback.

**Comment by varmanishant** [comment]
Appreciate, @BuraChuhadar .

**Review by Tyriar — APPROVED** [review]
Tested with updated xterm and it works great, thanks!

**Pull request merged**
