### PR TITLE
Fixed #4375 - Multiple Cursors now go to the next logical line 

### LINKED ISSUE #4375: Creating multiple cursors by using Cmd-Option-Down arrow goes to the next visual line, not the next logical line
- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5

Steps to Reproduce:
1. write a long line of text that wraps in the editor
2. place the cursor on the first line and press Cmd-Option-Down (on OS X).

This creates a second cursor on the next visual line, which means it is somewhere on the same logical line depending on how the text is wrapped. When creating multiple cursors on adjacent lines, often it is to perform the same edit on multiple (logical) lines that are aligned with each other. The current behavior having the second cursor appear instead at some situation-specific place on the same logical line throws a wrench in this workflow. I can't think of a good situation where it makes sense (though I do realize it is consistent with pressing the down arrow without cmd-option)

Definitions: a logical line is a line in the file on disk. A visual line is a line in the editor. A logical line may span multiple visual lines when there is wrapping.

### PR DESCRIPTION
**Pull request by irrationalRock**
This PR fixes https://github.com/Microsoft/vscode/issues/4375.

When adding multiple cursors it now only creates cursors for logical lines instead of visual lines.

Adding Cursors Down:
movedown

Adding Cursors Up:
moveup

Thanks for considering this PR.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
I'm sorry, but this is not a good way to tackle this.

This should be implemented inside `CursorMoveCommands.addCursorUp` and `CursorMoveCommands.addCursorDown` which should each get a new argument if they should use the view model or the model. In both of these functions, `MoveOperations.translateDown` or `MoveOperations.translateUp` can accept the view model or the model.

Then, `InsertCursorAbove` and `InsertCursorBelow` can use a new introduced argument by looking at the `args` passed in to their `run` methods.

Finally, this new behaviour would be something triggerable via passing args to the keybindings. e.g.:

```json
{
  "key": "alt+cmd+up",
  "command": "editor.action.insertCursorAbove",
  "when": "editorTextFocus",
  "args": {
    "logicalLines": true
  }
},

```

The argument can be called something different than `logicalLine`. I'm not sure of a good name at this time.

**Comment by irrationalRock** [comment]
Thanks for your feedback. I'll take your suggestions and hopefully have something out by the end of the week.

**Comment by irrationalRock** [comment]
@alexandrudima . A made a couple of changes based on your suggestions.

First I move my logical line logic to `addCursorDown`/`addCursorUp`.  It now takes in an additional argument for the model. That allows to choose whether you want to have logical line enabled or not.

However, I need a bit of help when it comes to turning this option on and off. I saw that you mentioned that it would be possible to have be triggerable via keybindings. Would the logicalLine args be passed through to `EditorAction` constructor?

Do you want it to look like how the `down` variable is implemented in `AbstractMoveLinesAction`?

I'm wondering can you expand on that?

**Comment by alexandrudima** [comment]
:+1:

**Review by alexdima — APPROVED** [review]

**Pull request merged**
