### PR TITLE
Add list of strings option to editor.fontFamily

### PR DESCRIPTION
**Pull request by astrolemonade**
This is for https://github.com/microsoft/vscode/issues/164275

This allows users to use a list of strings instead of single string for editor.fontFamily.

### CODE REVIEW

**Comment by cmarincia** [comment]
I tried to add support for `terminal.integrated.fontFamily` too but it seems like it does not provide a way to transform the value before validation.

**Review by alexdima — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Comment by alexdima** [comment]
Thank you!

**Comment by lakshits11** [comment]
Hy can we do something for UI...some people dont want to go to settings.json to change their font, they(including me) always have habit of pressing `ctrl+,` and changing font directly from UI. So what I propose is to do something like this for UI:

You can do like this extension clangd has done:



We can add font names in a list and can provide checkboxes in front of each item to comment/uncomment the font name.

**Comment by alexdima** [comment]
@lakshits11 I agree and thanks for raising this. The font family is a very often configured setting and it must be configurable from the settings UI.

**Comment by lakshits11** [comment]
@alexdima  @cmarincia  Also I think theres no sense in commenting and uncommenting the font since only one font is usable in editor at a time so user can change it manually whenever he wants(if we consider the prev format)

Also suppose think you have 10 different font names in ur list, and now when u want to use a font u would have to comment all other fonts and uncomment the one u want to use. Isn't it gonna be time consuming? Please suggest ur side too.

**Comment by cmarincia** [comment]
Commenting those families is much more easier than selecting the list of comma separated fonts and moving it to the end of `editor.fontFamily`. I think reverting it seems like a bad move, the UI is not affected and also the previous format is still usable.

**Pull request merged**
