### PR TITLE
Resolve vars in text for sendSequence to Terminal

### LINKED ISSUE #66337: Enable use of snippet variables in workbench.action.terminal.sendSequence
Hi :)

I would love to be able to use [task variables](https://code.visualstudio.com/docs/editor/variables-reference) to send snippets of code to my terminal. 
```json
{ "key": "ctrl+shift+t",
  "command": "workbench.action.terminal.sendSequence", 
  "args": { "text": ". ${file}" } 
```
I am developing all the time interactively with editing a file and fiddling in a REPL (in integrated Terminal)  alongside, where I have my environment loaded. I edit a function, I load the file from the REPL, and then test it interactively.

The difference to `Tasks` is that I have state in the REPL. This then can be used for different languages with a simple configuration. 

I have written a [Sublime Plugin](https://github.com/fbehrens/sublime_ExternalREPL) for this feature,
and I will write a Extension, according to your response.

Thanks for reading, and keep up the good work

### PR DESCRIPTION
**Pull request by njkevlani**
Fixes #66337 

`configurationResolverService` is used to resolve variables like `${file}`, `${fileBasename}`, etc.

Can be tested by 

```json
{      
	 "key": "ctrl+shift+t",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "cat ${fileBasenameNoExtension}\n" }
}
```

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Works great! Will merge after CI passes

**Comment by njkevlani** [comment]
Sounds great :)

**Comment by fbehrens** [comment]
@Tyriar great that it is implemented. (How) is it possible to see if the MR is in INSIDERS or RELEASED ?

**Comment by njkevlani** [comment]
@fbehrens It is included in current `insider` edition.

**Comment by njkevlani** [comment]
> @Tyriar great that it is implemented, thanks @njkevlani . (How) is it possible to see if the MR is in INSIDERS or RELEASED ?

Glad to be helpful :)

**Comment by fbehrens** [comment]
Works like a charm.

I have another edge case question concerning the feature, more about haw the task variables are resolved. Don't expect an answer, and hope it is OK to ask here.

On Windows `${file}` is `d:\scripts2\libwba\src\tools\environment.fs`, but `${relativeFile}` is `src/tools/environment.fs` . Is there a way to influence the path seperator  (`\` vs `/`) ?

**Pull request merged**
