### PR TITLE
Update editor walkthrough to the latest synatx

### PR DESCRIPTION
**Pull request by taldromi**
Since many people (including beginners) are exposed to editor walkthrough I thought it would be instructionally helpful to update the code to the latest syntax.

### CODE REVIEW

**Comment by alonmln** [comment]
This seems really important

**Comment by wahidshafique** [comment]
Why the iteration over emojis? Seems irrelevant to the point being made. Also the function transformation is not analogous. Check out [this](https://stackoverflow.com/questions/40300940/declaring-a-function-in-es6) for more details. Short answer paraphrased by a commenter -> 

> the first is a function declaration, the second is a function expression assigned to a variable

**Comment by taldromi** [comment]
I did the iteration over emojis because it demonstrates that VS Code supports rendering emojis, the power of Unicode💪, and it's more suitable than brand names.
Also, check out this [post ](https://medium.com/@kimtnguyen/how-to-deploy-es6-node-js-express-back-end-to-heroku-7e6743e8d2ff) about ES6 and Express.js, where you can see similar arrow function syntax.

**Comment by chrmarti** [comment]
We should use `for of` to iterate over arrays. And then there is also the trouble of IE not supporting the newer syntaxes.

**Comment by chrmarti** [comment]
Going with `for of` and `function` for top-level functions (and constructors!). I think arrow functions have their place, but there are still regular use cases for `function`, despite its lengthy name.

**Pull request merged**
