### PR TITLE
add options for user provided extension gallery

### LINKED ISSUE #21839: Feature Request: Support for private marketplace/gallery
We have created several VSIX extension that have no use to anybody else except our company. We would like to host our own private extension gallery and have an ability to specify alternative extension gallery paths (like "Additional Extension Galleries" in Visual Studio 2015).

- VSCode Version: 1.10.1
- OS Version: Windows 10

### PR DESCRIPTION
**Pull request by GitMensch**
Option 1: product.json in userdata, will be merged with general product.json and may override different entries
Option 2: Adjust gallery URLs via environment variables

This PR fixes #21839

### CODE REVIEW

**Comment by GitMensch** [comment]
...  Note to the hygiene check: the document is formatted by vscode via "Format Document" already.

**Comment by sandy081** [comment]
I am sorry that we do not accept PR for this feature request because it needs lot of brain storming, design discussions and also product team approvals.

**Comment by GitMensch** [comment]
There is a feature request since begin of 2017, since back then MS provided answers along

> Currently we don't have a way to do this but it's not the first time we have heard this request [...]. We don't have this in our current backlog but this will help us keep track of it.

It has nearly 1000 votes so obviously is something the users are interested in.
Among those we've seen a lot of corporate users that currently need to manually install vsix, often after getting approval form their IT staff - a self-hosted extension marketplace within the local net would solve this and if I remember correctly there are at least 2 free and open source marketplaces - nothing that MS even needs to take care.

> I am sorry that we do not accept PR for this feature request because it needs lot of brain storming, design discussions and also product team approvals.

@sandy081 Do you really want to tell me that there was no brain storming and design discussion about that @microsoft in the last 4 and a half year?

I note that there are two options provided in the PR:

* the first one allows a one time setup in the user data directory
* the second one allows a setting via environment, so can possibly override both the current default and the possibly changed one by the first option (if it is used) and other than the one-time-override is also perfectly working with logon scripts
* neither of those change ANY default that MS provides (only if the user manually provided one of these)

I suggest the following: go to the team, check your previous decisions and design goals on this (if there are some); then check the two options provided in the PR and discuss if any of those would harm the general design; if not tell me if there are necessary adjustments and then we'll finally be able to solve this issue.

What do you say?

BTW: I (and at least 1000 other users) would totally be happy if you take a design decision to just move those entries from an entry in product.json to a user setting with the current default - but as this is a completely _change_ of the current way other than this PR which provides a possible override I did not do that.

**Comment by sandy081** [comment]
I understand your concerns and to give more info, this is in our and Marketplace team's road map and we are discussing about a solution here with Marketplace team and the details are not yet concrete. Hence I would not like to have a temporary or workaround solution here. Hope you understand.

cc @prashantvc

**Pull request closed without merging**
