### PR TITLE
delegate encryption and credentials to server if we have a remote

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Today, if you use server with a remote machine, your credentials are stored in local storage in plaintext. Rather than keeping the secrets on the client, they should instead be stored securely in the keychain on the remote server.

This PR leverages the node environment we have on the remote side and leverages keytar to talk to the vault on the remote side.

This PR fixes https://github.com/microsoft/vscode-internalbacklog/issues/2573

### CODE REVIEW

**Review by alexdima — COMMENTED** [review]
Also nice!

**Comment by jeanp413** [comment]
Hey @TylerLeonhardt quick question: 
After this change, could you explain how does settings sync credentials are registered when running with a remote server on web? What I'm referring is the credentials this [getCurrentAuthenticationSessionInfo](https://github.com/microsoft/vscode/blob/8dbbccae210345f3097e099483a25853171ab3b3/src/vs/workbench/services/authentication/browser/authenticationService.ts#L95-L108) method requests which are registered in [LocalStorageCredentialsProvider](https://github.com/microsoft/vscode/blob/8dbbccae210345f3097e099483a25853171ab3b3/src/vs/code/browser/workbench/workbench.ts#L40-L51) but after this PR, when having a remote, `LocalStorageCredentialsProvider` is no longer used and we delegate to the `CredentialsMainService` on the remote instead which doesn't have those credentials.

**Comment by TylerLeonhardt** [comment]
@jeanp413 are you asking if we worked on a migration plan for credentials that first were using `LocalStorageCredentialsProvider` but are now using `CredentialsMainService`? We only use `LocalStorageCredentialsProvider` for building out of sources and running without a remote. A migration plan wasn't worth the effort for just that scenario.

**Comment by jeanp413** [comment]
I see, thanks for the clarification :+1:

**Pull request merged**
