### PR TITLE
Fixes error after dropping invalid element over editor area

### LINKED ISSUE #124946: Error after dropping invalid element over editor area
- VS Code Version: stable and from sources

Steps to Reproduce:
editor_invalid_drop

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #124946

### CODE REVIEW

**Comment by sbatten** [comment]
added reviewers based on those involved in the issue discussion

**Review by bpasero — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]

**Comment by isidorn** [comment]
Looks good to me!
@sbatten should we merge this in?

**Review by isidorn — APPROVED** [review]

**Comment by Tyriar** [comment]
FYI this broke terminal DND, I'm mostly changing it back in https://github.com/microsoft/vscode/pull/127080/commits/9403dff419f40ea13b5b4494e6eb07adae5b3246

**Comment by jeanp413** [comment]
@Tyriar sorry about that, I did this PR before `DataTransfers.TERMINALS` was added. 
But is it really needed to change the list datatype back to `DataTransfers.RESOURCES`? The point of this PR is to use `DataTransfers.RESOURCES` just for file resources.
I think that checking for `DataTransfers.TERMINALS`  in `editorDropTarge.ts` and setting the datatype to `DataTransfers.TERMINALS` inside the terminal tab list while starting a drag and drop action should fix the terminal DND.

**Comment by isidorn** [comment]
@jeanp413 that sounds good to me.
If @Tyriar agrees, maybe you could open a new PR which also tackles the terminal?

**Comment by Tyriar** [comment]
Will change 👍

**Comment by Tyriar** [comment]
That's tracked in https://github.com/microsoft/vscode/issues/127077

**Comment by isidorn** [comment]
@Tyriar  Great. Did you also unrevert your revert?

**Comment by Tyriar** [comment]
@isidorn it's like it was in the PR now, just Terminals data transfers are also accepted.

**Comment by isidorn** [comment]
Awesome, thanks 👏

**Pull request merged**
