### PR TITLE
add problem matcher for Haxe compiler messages

### PR DESCRIPTION
**Pull request by nadako**
As language extensions currently can't contribute problem matchers (and #492 is in the backlog), I thought maybe we could just have a problem matcher for Haxe bundled right in the VS Code. It's simple enough, hence the PR.

### CODE REVIEW

**Comment by nadako** [comment]
Hmm, it can be improved by adding endLine and endColumn, I'll close this for now.

**Comment by nadako** [comment]
Oh, and while we're at it, Haxe reports 1-based lines, however characters are 0-based byte offsets (it doesn't deal with file encodings at the moment). I know it's a little crazy, but would it make sense for VS Code to support setting whether line/column numbers are zero-based or 1-based in problem matchers? I wouldn't be surprised if other compilers/tools are reporting differently too.

**Comment by dbaeumer** [comment]
@nadako beside defining the pattern you need to add the problem matcher to the registry at the end of that file as well. Do you want to work on this as well?

**Comment by nadako** [comment]
Right, sorry I somehow forgot about that!

**Comment by nadako** [comment]
Done. I didn't quite understood however the `applyTo`, but since error can be in any file and haxe will report that, using `allDocuments` seems to be right. Same with `FileLocationKind`. Haxe can report both relative and absolute. Will `Relative` work for that?

**Comment by nadako** [comment]
I'm sorry, can I ask another question about these? I'm not sure if there's a bug or my problem matcher is wrong.

Why it behaves like this - only underlining a single column instead of the whole range:


I tested the regexp with that string and it seems to capture line/col numbers correctly: https://regex101.com/r/rB7zF3/1

I'm using the same pattern as in this PR:
```json
    "problemMatcher": {
        "owner": "haxe",
        "pattern": {
            "regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
            "file": 1,
            "line": 2,
            "endLine": 3,
            "column": 4,
            "endColumn": 5,
            "severity": 6,
            "message": 7
        }
    }
```

**Comment by dbaeumer** [comment]
Regarding applyTo: if it is an external build command run through tasks then allDocuments is fine. Whether you report absolute or relative paths doesn't matter as long as the problem matcher is configured correctly. The TS compiler for example reports problems relative to the workspace folder.

That is why it is configured as:
```
	fileLocation: FileLocationKind.Relative,
	filePrefix: '${cwd}',
``` 

Regarding error positions: we do have some smartness here in the editor. If you only provide line/column then we automatically underline the word. If you provide line/column and endLine/End/Column then we take exactly that.

I saw you commenting on the language server protocol as well. If you are implementing a full language server for Haxe then you actually don't need any of this since the language server can report errors as well and the proper transformation of line/column can be done in code.

**Comment by nadako** [comment]
> Regarding error positions: we do have some smartness here in the editor. If you only provide line/column then we automatically underline the word. If you provide line/column and endLine/End/Column then we take exactly that.

But in the example above I provide `line` (3), `column` (8) and `endColumn` (29), why does it still only underlines a single character?

> I saw you commenting on the language server protocol as well. If you are implementing a full language server for Haxe then you actually don't need any of this since the language server can report errors as well and the proper transformation of line/column can be done in code.

Well, language server doesn't deal with building, and the build could be invoked from a Makefile, grunt or anything else, so it makes sense to have an universal problem matcher, so yeah I'd love this to be merged.

--- 

By the way, about position transformation, wouldn't it be a good idea to have a `TransformPosition` request in language server protocol that takes whatever problem matcher captured and transforms it to  proper `Location`?

**Comment by dbaeumer** [comment]
In the example  "src/Main.hx:3: characters 8-29 : String should be Int"  I think the mapping must be as follows:

file: 1,
line: 2,
column: 4
endLine: 2,
endColumn: 5
message: 7

Your mapping sets endLine to 3 which is undefined. Due to the code in problemMatcher#createLocation (line 283) a problem with only line and column is created. Since this points to a blank we even don't expand this to a word.

I see the problem you have since the error messages seem to be dynamic. You either need to tweak the pattern so that group indexes stay stable (hard to say if feasible). Another idea is to have two problem matchers for now which each have a static pattern.

@nadako please note that I am away on vacation for two weeks. 
@jrieken can you help @nadako and merge the PR

**Comment by dbaeumer** [comment]
Regarding the transform position request: yes sounds reasonable however it would case a round trip. For the node implementation of the server we implemented a text document that can do basic transformation. Would this be too complicated in your case?

**Comment by Simn** [comment]
> Your mapping sets endLine to 3 which is undefined. Due to the code in problemMatcher#createLocation (line 283) a problem with only line and column is created. Since this points to a blank we even don't expand this to a word.

Would it be feasible to support the no-endLine-but-two-columns case there? Having a single line with two columns doesn't seem to be _that_ outlandish, so I wouldn't be surprised if that occurred elsewhere, too.

**Comment by nadako** [comment]
I agree, maybe it would be better to tweak the `createLocation`'s first condition not to check for `endLine`, and for the value do something like `endLineNumber: endLine || startLine`.

Tweaking the regexp would result in a complete madness I'm afraid, and using two problem matchers sounds really inconvenient.

**Comment by dbaeumer** [comment]
Addressed in https://github.com/Microsoft/vscode/issues/6233

**Comment by dbaeumer** [comment]
And sorry for the late response. I was on vacation :-)

**Comment by nadako** [comment]
Nice, thanks!

**Comment by dbaeumer** [comment]
@nadako could you check whether the problem matcher now works with the changes from #6233

**Comment by dbaeumer** [comment]
@nadako any objection to close this PR or do you still need to have the haxe problem matcher in core?

**Comment by nadako** [comment]
@dbaeumer can we add problem matchers via extensions now? if yes, i'd love to do that in my extension, but if not, having it in core would be handy.

**Comment by dbaeumer** [comment]
@nadako unfortunately not. But instead of adding this to the core I will try to make this happen in September. Makes sense to not have to many matchers preshipped.

**Comment by dbaeumer** [comment]
Feature request is https://github.com/Microsoft/vscode/issues/492

**Comment by nadako** [comment]
Awesome, thank you!

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

**Comment by dbaeumer** [comment]
@nadako finally. With the March release coming out soon you can now contribute problem matchers and patterns using the package.json of an extension. So I will close this PR since we don't need to have this in the core anymore.

**Comment by nadako** [comment]
Nice, I'll check it out soon, thanks!

**Comment by dbaeumer** [comment]
See the typescript extension in our source tree for an example.

And there is more you might be interested. In the next release you can contribute task from your extension. So you can have a Haxe compile task. However it only works with the new terminal task runner. 

You might want to look at the gulp extension in our source tree.

**Comment by nadako** [comment]
Thanks a lot, I'll take a look.

**Pull request closed without merging**
