### PR TITLE
Added new command to switch between workspaces

### PR DESCRIPTION
**Pull request by heycalmdown**
rebase #11493 to clean the mess

### CODE REVIEW

**Comment by bpasero** [comment]
@heycalmdown on a second thought, can we rethink the fact that this only shows opened workspaces? imho it would be better to actually show all windows that are opened and call it "Switch Window".  Rationale:
* for your use case it actually would still work because my understanding is that all your windows are just having workspaces associated
* for other users that want to quickly switch windows, it would be very convenient to be able to use this feature and see all opened windows at a glance

Trying to make this feature more useful to more users 👍

**Comment by heycalmdown** [comment]
Okay, sounds reasonable. I'll make it work as you described.

**Comment by bpasero** [comment]
@heycalmdown awesome 👍

**Comment by heycalmdown** [comment]
screen shot 2016-09-08 at 3 18 13 pm

This might take a benefit when having ambiguous workspace and same format with "Open Recent", but looks too verbose. So I settled at this -

screen shot 2016-09-08 at 3 19 46 pm

similar than

screen shot 2016-09-08 at 3 18 36 pm

It'll help the reporter of #2382

**Comment by heycalmdown** [comment]
@bpasero time to review now :)

**Comment by bpasero** [comment]
@heycalmdown thanks, merged! 👍

**Comment by bpasero** [comment]
Created https://github.com/Microsoft/vscode/issues/11671 to track this for September.

**Comment by heycalmdown** [comment]
Thanks!

**Pull request merged**
