### PR TITLE
editors - Redundant conditions specified for keyboard shortcuts (#97381)

### LINKED ISSUE #97381: Redundant conditions specified for keyboard shortcuts
Issue Type: <b>Bug</b>

I noticed that some keyboard shortcuts have the same condition specified which seems redundant. 

image

image

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.17763

### PR DESCRIPTION
**Pull request by ZainChen**
This PR fixes #97381
editors - Redundant conditions specified for keyboard shortcuts (#97381)

### CODE REVIEW

**Comment by ZainChen** [comment]
Fix #97381

**Comment by jrieken** [comment]
Not a big fan of the approach but letting @alexdima decide. For format we can just find the (static registrations and fix them there)

**Comment by ZainChen** [comment]
Thank you. What is the format and static fix?:open_mouth:

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/846aec810ede01f4c262cbffe59a7ac7e33c5b4b/src/vs/editor/contrib/format/formatActions.ts#L217 and further down is where format defines (statically) its conditions. Things that are listed in the `precondition` don't need to go into keybinding/menu item conditions

**Review by alexdima — CHANGES_REQUESTED** [review]
I'm not a fan of this because this code executes statically on startup and now we add the price of deduping when conditions to the startup code loading path. Also, most of the times there are no duplicates since most of the keybindings don't suffer from this problem.

 IMHO it would be much better if these actions simply fix their registration.

**Comment by ZainChen** [comment]
https://github.com/microsoft/vscode/pull/99085
Hi, I found some duplication in these places. Is it better to delete these?:smiley:

**Comment by ZainChen** [comment]
Use the code to find all the commands, All duplicate registration locations were found.:metal:
I added these to this PR：#99085
```json
{
  "key": "shift+alt+f",
  "command": "editor.action.formatDocument",
  "when": "editorHasDocumentFormattingProvider && editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly"
}
{
  "key": "shift+alt+f",
  "command": "editor.action.formatDocument.none",
  "when": "editorTextFocus && !editorHasDocumentFormattingProvider && !editorHasDocumentFormattingProvider && !editorReadonly"
}
{
  "key": "ctrl+k ctrl+f",
  "command": "editor.action.formatSelection",
  "when": "editorHasDocumentSelectionFormattingProvider && editorHasDocumentSelectionFormattingProvider && editorTextFocus && !editorReadonly"
}
{
  "key": "shift+tab",
  "command": "acceptAlternativeSelectedSuggestion",
  "when": "suggestWidgetVisible && textInputFocus && textInputFocus"
}
{
  "key": "shift+enter",
  "command": "acceptAlternativeSelectedSuggestion",
  "when": "suggestWidgetVisible && textInputFocus && textInputFocus"
}
{
  "key": "tab",
  "command": "insertNextSuggestion",
  "when": "hasOtherSuggestions && textInputFocus && textInputFocus && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'"
}
{
  "key": "shift+tab",
  "command": "insertPrevSuggestion",
  "when": "hasOtherSuggestions && textInputFocus && textInputFocus && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'"
}
{
  "key": "ctrl+f2",
  "command": "editor.action.changeAll",
  "when": "editorTextFocus && editorTextFocus && !editorReadonly"
}
```

**Comment by jrieken** [comment]
ok, closing this PR then

**Pull request closed without merging**
