### PR TITLE
Add an option to enable/disable JSDoc autocomplete

### PR DESCRIPTION
**Pull request by jsynowiec**
Hopefully addresses #23642

This PR introduces a new settings option for TypeScript extension:
```json
"jsDocCompletion.enabled": {
  "type": "boolean",
  "default": true,
  "description": "%jsDocCompletion.enabled%"
}
```
which allows to enable or disable expanding `/**` using `docCommentTemplate` tsserver command. When set to `false` the default SnippetString is used.

mar-31-2017 12-37-02

### CODE REVIEW

**Comment by jsynowiec** [comment]
Ok, I now see why it was done using an internal command. Reading docs and looking into other ways of restoring the previous behavior rather than immediately resolving the `CompletionItem` without showing the item preview. All ideas are welcome.

**Comment by jsynowiec** [comment]
Hopefully all should be OK now.

**Comment by chrmarti** [comment]
@jsynowiec Thanks for the PR! We're currently finishing the upcoming release and will look into it some time next week.

**Comment by mjbvz** [comment]
Thanks @jsynowiec! This looks like a good change. It came in a little late for the upcoming March release but it should be in the April insiders builds once those resume and in the 1.12 release

**Pull request merged**
