### PR TITLE
Add Yu Gothic UI to font-family jp

### LINKED ISSUE #79579: Japanese GUI font-family
I suggest about Japanese GUI font-family. (not editor font family)

Current vscode specified "Meiryo" in Japanese font-family, but normally Windows 10 using "Yu Gothic UI" as Japanese system font.
We should add Yu Gothic UI to vscode font-family because Yu Gothic UI has a better character width and rendering than Meiryo.

#### Current (workbench.main.css)
```
.windows:lang(ja) {
    font-family: Segoe WPC, Segoe UI, Meiryo, sans-serif
}
```

#### Suggestion (workbench.main.css)
```
.windows:lang(ja) {
    font-family: Segoe WPC, Segoe UI, Yu Gothic UI, Meiryo, sans-serif
}
```

### PR DESCRIPTION
**Pull request by harujii**
Fix #79579
Prioritize Yu Gothic UI over Meiryo.

### CODE REVIEW

**Review by octref — CHANGES_REQUESTED** [review]
It needs to be Yu Gothic, not Yu Gothic UI, which has the condensed kana:

Yu Gothic:

image

Yu Gothic UI:

image

But I just checked, currently for `lang="ja"`, we are falling back to Yu Gothic on Windows 10, which is Chrome's default choice for Japanese characters. Here's stable:

image

**Comment by harujii** [comment]
@octref 
Yu Gothic is not suitable for UI text and not familiar to Japanese as a UI font.
Is there any reason why vscode don't use the condenced font?

The reason to falling back to Yu Gothic is that probably don't have Meirio installed on your PC.
Meiryo is supplemental font for japanese. 
To use it, install the Japanese language pack on your PC.
see also: https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list

**Comment by bpasero** [comment]
@octref thanks for doing that, let's wait for more feedback.

**Comment by octref** [comment]
A bit more testing:

Win 10 defaults to Yu Gothic UI (narrow):

win-jp

macOS defaults to Hiragino Kaku Gothic ProN (wide):

mac-jp

Anyway, I throw out a Twitter poll for 7 days:

https://twitter.com/octref/status/1169661657900961792

image

**Comment by octref** [comment]
The feedback so far heavily leans towards the narrower one.
@harujii I'd be fine if you also make `Meiryo` -> `Meiryo UI` change.

This should only affect Windows Japanese users.

**Comment by bpasero** [comment]
@octref feel free to merge when you feel like it.

**Pull request merged**
