### PR TITLE
[css] Update css intellisense and css.plist

### PR DESCRIPTION
**Pull request by dstorey**
Had some strange merge issues when trying to keep the repo up to date, and GitHub Desktop started acting funny after OS upgrade, so sorry for the noise in the last couple of commits as I sorted it out.

Included in this PR:

First part of modernising css.plist:
- Big update of CSS properties. Should now include most valid CSS properties.
- Add missing pseudo elements/classes: fullscreen, placeholder and the input pseudo classes
- Add missing CSS units
- Add speech media type
- Fix comments about colours to point to spec and not incorrect info about being non-standard from W3Schools

Big update to css-scheme.xml for CSS intellisense and generate new JSON file:
- Add Edge browser support info. Mostly complete except some pseudo classes/elements.
- Update other browser support to be as close as possible to reality. Some still need to be checked
- Update specs where appropriate
- Remove old properties and values that no longer exist
- Add new CSS properties from almost all CSS specs except old unmaintained spec and a couple of others: CSS Logical Properties and Round Display. SVG CSS properties also still need checking and updating. Especially for browser support.
- Updated some of the descriptions to be more concise and consistent, and add some missing ones
- Update at-rules: @keyframes and @supports

### CODE REVIEW

**Comment by egamma** [comment]
We have just frozen for the Dec update. This is a larger PR it might not make it into the Dec update.

**Comment by dstorey** [comment]
This (in theory) should be a safe merge. 3 of the changed files are just updating tests to take into account that the data changed and flexbox snow flex in the latest standard (and supported that way by browsers). 

The other 4 files are just data changes. It fixes a lot of copy paste issues in the old existing data where the description from another property is used. It also adds a lot of new properties, of which many are compiled out for the moment until 2 browsers support them. I've tested most of the new features added and they're working, except Edge still isn't showing up. I've created another bug for that, as it isn't related to this commit, and I haven't tracked down why yet.

**Comment by egamma** [comment]
@aeschli what is your assessment?

**Comment by aeschli** [comment]
@egamma @dstorey Let's put that into the January build. Testing for the December build has already started.

**Comment by dstorey** [comment]
@aeschli @egamma if this isn't going in until Jan then I’ll probably add more commits to it, as there are some more things to add to CSS.plist (such as property values…currently I've just updated the long list of properties), and to remove a lot of the duplication in the XML file (all colours are repeated for each property when they’re already included via the restriction attribute. This makes it really difficult to maintain the list as it is multiple screens of entries each you need to scroll through.)

**Comment by egamma** [comment]
@dstorey this makes good sense for me.

**Comment by dstorey** [comment]
@aeschli this should be done now. There is more to do to get various at-rules accepted in syntax highlighting (they are not a simple list like property/values, and need regexp and more understanding of the format of cSS.plist) and the linter, and some of the CSS functions like gradients could be made smart like the colour functions, but it is a good base to work from.

Changes to the css-scheme and resulting browsers.js should be straightforward and don't need too deep a review. Only thing I added beyond spec and browser support updates is that I added a bunch of suggested unicode-range ranges from the Unicode spec, updated font-feature-settings values to include all the OpenType features from that spec, along with the friendly name as a description, and included a bunch of cubic-bezier values that are commonly used based on the Penner algorithms. These make those three properties easier to understand as the values are rather cryptic and usually need to be looked up.

Might want to check intelliSense.ts more as I'm not a TypeScript developer. I just copied how the other reductions were done for the various reductions I added. They could probably be combined in one method to save code, rather than a bunch of copy/pasted code.

I added new restrictions if a collection of values were defined as a data type in CSS and were used by multiple specs. It adds quite a bit more code to languageFacts.ts but saves a bunch from browsers.js. The main drawback I see, except splitting the definitions into multiple files is that they lose their browser support information. Most of that can't be seen anyway as the descriptions are clipped to one line.

The other thing that should be checked is the css.plist. Beyond expanding the values and properties, I added a few more blocks to handle @viewport and a number of CSS functions like the various filter and transform functions. I copied the regexp for highlighting numbers within the functions from elsewhere in the file. I also removed the \b surrounding the property name regexp as it was stopping the prefixes from being highlighted with the name. I'm not sure if there is any performance impact as I'm not a regexp expert.

The only other changed files should be the test file that previously tested for old flex box syntax.

**Comment by aeschli** [comment]
Delivered PR, thanks @dstorey, an amazing contribution!

**Pull request merged**
