### PR TITLE
add CMake syntax highlighting

### PR DESCRIPTION
**Pull request by ethvard**
as above ^

### CODE REVIEW

**Comment by aeschli** [comment]
We don't want to own any grammars in the VS Code. Instead, we always import them from a grammar repo that is actively maintained by someone in the community 

There's a popular extension https://marketplace.visualstudio.com/items?itemName=twxs.cmake that adds syntax highlighting for CMake. It depends on the grammar from https://github.com/zyxar/Sublime-CMakeLists

- what are the pros/cons of each grammar?
- is your actively grammar maintained?

**Comment by ethvard** [comment]
There is no actively maintained CMake grammar repository, and unfortunately I will not be maintaining one. I should probably contribute to the original textmate repository with cmake grammar and then try here (I will not).

The grammar is converted from https://github.com/textmate/cmake.tmbundle (last updated in 2015) and improved by support for block comments, simple highlighting for generator expressions and updated list of available commands. I can provide screenshot showing some differences between this and twxs's extension.

I think that this PR is good starting point to further development and it is better to have this, more up-to-date, than outdated (last updated in 2017) third-party extension just for syntax highlighting. Thank you for your time.

**Comment by ethvard** [comment]
### twxs's extension / this PR
Bez tytułu

**Comment by aeschli** [comment]
Thanks for the reply. As said, for us it's crucial to rely on a maintained grammar. We don't have the expertise with CMake. It's better done in an extension.

**Pull request closed without merging**
