### PR TITLE
 Tab label functionality similar to window.title

### LINKED ISSUE #43806: Allow custom setting/control of workbench tab titles
Hi there,

In my project, I have files with quite long file names (beyond my control).  This limits me to having 3-4 tabs show in my workbench at once.  I would like to be able to rename these tabs, or control their label format myself, in order to have more condense tab titles and thus more easily navigate my tabs.  This was roughly suggested by #21662 but was not really addressed by #12965 -- any of the options for `workbench.editor.labelFormat` still give me tab titles that are too long.  Can `workbench.editor.labelFormat` be modified, for example, to optionally take a formatter lambda function we can provide?  As just one example of a reasonable formatter one might write, it could be that you fix tab titles to 20 chars, and for long filenames you truncate and prepend with "...".  Additionally, one might want to assign nickname/shorthand tab titles for commonly used files.  Please pardon me if there is already a way to do this (would love to know how!), but if not, I'd sincerely appreciate considering this as a feature request.

Thanks!

### PR DESCRIPTION
**Pull request by mehanix**
This PR fixes #43806, implementing custom tab name functionality similar to `window.title`. 

This is especially useful for projects where the directory is the most meaningful name, instead of the file name. You can also add separators or choose whether to show or hide the file extension.

Since tab auto-shrinking is already supported by `'workbench.editor.tabSizing': 'shrink'`, i figured it was redundant to add it here.

Using the `folderName` setting, in conjuncture with the fact that file type is represented by an icon, provides a very clean look and is great at saving space on small devices (such as my 14" laptop).

Achieved effect (note the folder structure):

Screenshot from 2020-07-17 21-05-14

Another possible configuration:
Screenshot from 2020-07-17 21-06-58

Question: should `editor.labelFormat` provide the same functionality or should it be left as-is? As it is now, it is a bit redundant. I figure it would be useful to alter the label in the same way.

Thank you!

### CODE REVIEW

**Comment by mehanix** [comment]
Okay, upon discussion on the issue page, I implemented the following solution: 

* TabTitleOverride is a dictionary which pairs glob patterns that select files in the project with variable templates (like window.title).
* This enables users to set patterns which target files and rename them according to their specific needs. 

I believe this provides enough flexibility to accomodate a lot of use cases, for example: (note the folder structure and how tab names change - "Main Index File" is an index.html file located in the root project folder)

done

I also added autocompletion:
ezgif com-optimize

As of now, there are no tests written. I could write some, but I'm not too familiar with this codebase and can't figure out where to add them (or whether I should make a new file for them).

I could use some directions and feedback as to what to do next.

Thank you!

**Review by mocanew — APPROVED** [review]

**Comment by mehanix** [comment]
Hello,

I know this is in the backlog so it's not a priority but is there a chance I could get some sort of feedback? While working on it, I generated a bit of discussion on the issue page therefore I believe there is interest for this feature.

Thank you!

**Comment by bpasero** [comment]
@mehanix some high level feedback without going into too much detail:
* shouldn't this be implemented in the `getName` method of the editor rather than being specific to tabs? what if I have tabs disabled but still want to control the title? and note that we show editor names in more places than just tabs, so it would need to be consistent
* rather than allowing to use glob patterns to scope the setting to certain files, I would make the setting resource capable (see [example here](https://github.com/Microsoft/vscode/blob/4a45c7464472ac6d8ac361c72b2188cf8d1ff304/src/vs/workbench/browser/workbench.contribution.ts#L180-L180)) and let the user define it per language type
* how does this work together with the existing `workbench.editor.labelFormat` setting that seems very similar? maybe that setting should optionally allow to define the value via template syntax?

**Review by bpasero — CHANGES_REQUESTED** [review]
@mehanix some high level feedback without going into too much detail:
* shouldn't this be implemented in the `getName` method of the editor rather than being specific to tabs? what if I have tabs disabled but still want to control the title? and note that we show editor names in more places than just tabs, so it would need to be consistent
* rather than allowing to use glob patterns to scope the setting to certain files, I would make the setting resource capable (see [example here](https://github.com/Microsoft/vscode/blob/4a45c7464472ac6d8ac361c72b2188cf8d1ff304/src/vs/workbench/browser/workbench.contribution.ts#L180-L180)) and let the user define it per language type
* how does this work together with the existing `workbench.editor.labelFormat` setting that seems very similar? maybe that setting should optionally allow to define the value via template syntax?

**Pull request closed without merging**
