### PR TITLE
Fix layers overlap and cutting at edges.

### PR DESCRIPTION
**Pull request by rebornix**
@sbatten and I ran into a couple layering issues after  `translate3d` was adopted in the workbench, which fall into below two categories

* Views are cut at the part edges. For example, when invoking the compact menu from the activity bar, the menu is cut at the edge of the activity bar https://github.com/microsoft/vscode/issues/85061
* Views are be covered by siblings (part of https://github.com/microsoft/vscode/issues/85313)

They are side effects of  `translate3d` creating a new rendering layer. If `overflow` is set to `hidden`, content inside the new rendering layout will be cut the edges of the layer. If `position` is not set properly, elements might find wrong containing box and affect how `z-index` is applied.

### CODE REVIEW

**Comment by sbatten** [comment]
Collecting the series of commits that have been made to address issues caused by new layer hinting approach along with this PR and above issues.

[Original Commit](https://github.com/microsoft/vscode/commit/dccaf037f35ed2d73fa97e48e8e053887d0366b1)

[Fix #1 for menubar](https://github.com/microsoft/vscode/commit/90aec68c507840481201e594ac801c7f33cc1c47)

[Fix #2 for menubar](https://github.com/microsoft/vscode/commit/90aec68c507840481201e594ac801c7f33cc1c47)

[Related Fix for Bad CSS](https://github.com/microsoft/vscode/commit/40a67d113d0fd74fdb60c304eb5e3899210481f1)

[Fix for compact menubar](https://github.com/microsoft/vscode/commit/a5ac1db64147292588a1890c1a5a9cc0518fc1db)

**Comment by deepak1556** [comment]
For better public awareness, we would have to remove `translate3d` as layering hint hack while preserving AA in near future as chromium team is working to remove it https://bugs.chromium.org/p/chromium/issues/detail?id=1012775

But they have considered our use case as a priority issue before removing that hint, so please follow https://bugs.chromium.org/p/chromium/issues/detail?id=1016062 where more concrete solutions will be up.

@alexandrudima @bpasero are already in the loop, just adding here for more eyes.

**Review by alexdima — APPROVED** [review]
Using `"fixedOverflowWidgets": false` should work fine. Regarding the other CSS changes, I am sorry I don't understand them so I cannot offer a review.

**Comment by rebornix** [comment]
I already pushed the suggestion widget position fix to master and now this PR only contains layout css change.

**Comment by sbatten** [comment]
@rebornix and I have decided since we need a solution for this issue and we are not getting a review before Thursday, we just need to merge this now to get it time in the wild. We can always revert, but we won't get that missed testing time back if we don't merge now.

**Pull request merged**
