### PR TITLE
Make Telemetry Opt-In instead of Opt-Out

### PR DESCRIPTION
**Pull request by jcgruenhage**
Telemetry should always be Opt-In.

### CODE REVIEW

**Comment by MikeGitb** [comment]
I'd very much like to see this being merged.
I hope not everyone at Microsoft cares as little about user privacy as the Windows team.

**Comment by chrisdias** [comment]
Hi @jcgruenhage -

Thanks for submitting this PR!  

As I'm sure you can understand, we believe it is generally better for telemetry to be on by default while providing a way for users to turn it off if they so desire.

Here's the reasoning.

We use telemetry data to make VS Code a better product. Crash reports and performance profiles help us find and resolve issues that would be impossible to reproduce in house. Usage data helps us understand how people use the product so that we can make better decisions when adding new features or changing existing behaviors.  

For example, we recently analyzed the usage of a core API that is impacted by our work on [multi-root workspaces](https://github.com/Microsoft/vscode/issues/396), a highly requested experience. Without the telemetry data to understand usage, we would likely break extensions and the downstream millions of developers using those extensions when we release the multi-root feature.  

With telemetry off by default, we would collect much, much less information and not be able to make decisions as effectively. Because of this, we turn on telemetry collection by default and ask users to opt out if they do not want to send this information.

We understand that some will disagree with this approach, it is inevitable! But, we feel like we are striking the right balance which allows us to build a better product (for everyone) while providing the ability to control the data people send.

Thank you again for the PR. We appreciate every contribution made to Code even if we can't accept all of them.

**Comment by jcgruenhage** [comment]
> We use telemetry data to make VS Code a better product. Crash reports and performance profiles help us find and resolve issues that would be impossible to reproduce in house.

That's why I didn't disable crash reporting.

> Usage data helps us understand how people use the product so that we can make better decisions when adding new features or changing existing behaviors.

Do it like atom, and ask for that opt-in on first launch, if you need it so desperately. Other than that, there is tons of feedback everywhere, I can't imagine you really need that so badly :)

> For example, we recently analyzed the usage of a core API that is impacted by our work on multi-root workspaces, a highly requested experience. Without the telemetry data to understand usage, we would likely break extensions and the downstream millions of developers using those extensions when we release the multi-root feature.

Then do that stuff on a prerelease build. It is common practise to test stuff like that on prerelease builds, where telemetry makes more sense (I'd still have it as an "encouraged" opt in though).

On the rest, it is of course your decision, so go ahead and do as you see fit, I just don't really think your reasoning makes sense.

**Comment by jens1o** [comment]
I'm also disappointed. I also think we should instead make it like other Editors and ask on first launch.

**Comment by madflow** [comment]
> With telemetry off by default, we would collect much, much less information and not be able to make decisions as effectively. 

Can you give an example how collecting "more" telemetry has lead to more effective decisions?

> Because of this, we turn on telemetry collection by default and ask users to opt out if they do not want to send this information.

Where is this implemented? I only stumbled upon the telemetry settings by accident. Is there a dialog on the first start that I clicked away?

**Comment by jcgruenhage** [comment]
> and ask users to opt out

> Where is this implemented?

I guess they mean they ask those to disable it, that complain somewhere, the users that don't notice it, that don't complain, will never be asked to opt out.

**Comment by chrisdias** [comment]
Sure - https://code.visualstudio.com/blogs/2016/11/3/rollback is an example of how having more telemetry helped us make better decisions, more quickly. We knew right away the number of people who had upgraded and we knew the potential load we would then place on npmjs.org based on historical upgrade rates (across time zones) combined with the potential number of types being downloaded by ATA.  
 
Had we had only a small sampling of data (assuming a reasonable percentage do not opt into telemetry, because we would not know how many didn't opt-in), we would not have been able to estimate the potential impact on npmjs.org.  Yes, we could have simply "thrown the switch" to rollback the release but we also had discussions with npmjs.org on whether or not to add more bandwidth based on what we predicted (based on telemetry) the expected workload to be.
 
On the code.visualstudio.com home page we state that "By downloading and using Visual Studio Code, you agree to the license terms and privacy statement."
 
image
 
This jumps you to the bottom of the page where we tell you how to opt out of crash reporting, which also tells you how to opt out of telemetry collection in the FAQ.
 
There are two things that I think we can do to improve this:
 
1. At the bottom of the home page I can include text that also says you can opt out of telemetry reporting (similar to opting out of crash reporting), something like this:
 
> If you would prefer not to have this data sent please see the [How to disable telemetry](https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-telemetry-reporting) and [How to disable crash reporting](https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-crash-reporting) FAQs to learn how to disable it.


2. On the [Download](https://code.visualstudio.com/Download) and [Insiders Download](https://code.visualstudio.com/insiders) pages I can add the following text (which is currently only on the home page):
 
> VS Code automatically sends telemetry data and crash dumps to help us improve the product. If you would prefer not to have this data sent please see the [How to disable telemetry](https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-telemetry-reporting) and [How to disable crash reporting](https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-crash-reporting) FAQs to learn how to disable it.

 
Thanks again for providing this feedback. We are listening and we do have periodic reviews of our approach, but for now we do not plan to change the default.

**Comment by jcgruenhage** [comment]
Would it be possible to show that on the first launch instead? If an admin installs VS Code and a user then opens it, they have never seen that info. Putting it on the download site would already be an improvement though.

**Comment by madflow** [comment]
@chrisdias Thank you for your bringing a little bit more insights to this matter. I would aplaude the effort to document this more extensively like you proposed!

However - I like the approach

+ Opt-In, on the first start
+ Be able to view the data collected
+ Always enabled on nightly/test builds

Sort of like Mozilla (claims) to do it:

https://wiki.mozilla.org/Telemetry/faq

I will consider opening a new issue ticket.

**Pull request closed without merging**
