### PR TITLE
fix: force pwsh to read PATH variables

### PR DESCRIPTION
**Pull request by Banyc**
This PR fixes #

### CODE REVIEW

**Comment by roblourens** [comment]
Is there an issue for this or some other context?

**Comment by Banyc** [comment]
@roblourens @Tyriar When applying the default settings, if vscode sets pwsh as a default terminal, it does not inherit PATH variables from the initial bash, thus causing problems. After adding `-l` argument, the pwsh works as expected. So, I submit this change to make this expected behavior as default.

**Comment by Tyriar** [comment]
@TylerLeonhardt know if should we be running pwsh as a login shell by default on macOS? We run other shells as login shells.

**Comment by TylerLeonhardt** [comment]
@Tyriar yes we should. I run pwsh as my login shell on macOS today.

**Review by Tyriar — COMMENTED** [review]
While this might be the best experience, it's not supported in v6 so we can't make this the default unfortunately https://github.com/PowerShell/PowerShell/issues/7704#issuecomment-422985015

**Pull request closed without merging**
