### PR TITLE
Report extension list

### PR DESCRIPTION
**Pull request by digitarald**

### CODE REVIEW

**Comment by sandy081** [comment]
If the intention is to report installed extensions in every window, I would recommend to do it here - 

https://github.com/microsoft/vscode/blob/7e3c3e6e42fc0abaccc89ba84e40e36b8ccab5b9/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L720-L727.

But it seems the event name is called `extensionsLoad`, so I am confused about the real purpose of this event.

**Comment by isidorn** [comment]
@sandy081 there are more details in an issue I pinged you on.

I think the event is just a list of extensions installed. So the reporting happens on load but I do not think the event should be called like that. How about `"installedExtensions"`?

I personally find the inlined interfaces a bit ugly. Maybe move them all the way up. Unless we do this in other places then I guess it is fine. Is anything else needed that this is registered for telemetry gdpr?

**Comment by sandy081** [comment]
If it is just to report installed extensions, I would do it in the extensions workbench service as mentioned in my previous comment. `installedExtensions` makes sense to me.

Yes, I also recommend to extract the inlined interfaces to separate types and use it while reporting. For eg:

https://github.com/microsoft/vscode/blob/310108c376cb6274eeed8adeff9be32de946d8ad/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L834-L837

**Comment by digitarald** [comment]
@isidorn @sandy081 updated with your feedback.

**Review by isidorn — APPROVED** [review]
This looks good to me. Let's give Sandy some time to give a glance, I know he is writing his Connect :)

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
