### PR TITLE
Updated "Code - OSS" icon for macOS Big Sur

### PR DESCRIPTION
**Pull request by LcJuves**
This PR fixes visual inconsistency under macOS Big Sur

<div align="center"></div>

### CODE REVIEW

**Review by glaukiol1 — APPROVED** [review]

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
Thanks for submitting the PR! It would be great if we could get the OSS shape and shadows to match our regular ones:

image

Let me know if you need a Figma file and I can share ours

**Comment by LiangchengJ** [comment]
However, my icon design template was downloaded from Apple’s official website, and there should not be any uneven shape and shadows.

The corresponding website and design resource links are as follows:
- https://developer.apple.com/design/resources
- https://devimages-cdn.apple.com/design/resources/download/macOS-11-Sketch.dmg

Oh, what's wrong~
Finally, I still hope you can share the figma file, let us design a better `Code - OSS` icon for macOS Big Sur.

**Comment by misolori** [comment]
We'd prefer to have all of our icons match, [here's a sample of our Figma template](https://www.figma.com/file/MOrJ7JsJE0TkPmQiZXxWrE/macOS-Big-Sur-Icons?node-id=0%3A1) that we used. I dropped a sample icon that you can replace.

image

**Comment by LiangchengJ** [comment]
Okay, [here](https://www.figma.com/file/YfHtZUzbzkR0dQecwEue4P/macOS-Big-Sur-Icons?node-id=0%3A1) is the final design draft.
The SVG of the center icon is [here](https://camo.githubusercontent.com/15f23822b544642691379499666333e388fb848fdb1e60ad303b50422c72db6d/68747470733a2f2f6769746c61622e636f6d2f4c69616e676368656e674a2f7765622d66726f6e74656e642f2d2f7261772f6d61696e2f6173736574732f7376672f636f64656f73732e737667).

The final effect is as follows:

**Comment by misolori** [comment]
Since we're already in endgame for this release I'm marking this for June

**Comment by LiangchengJ** [comment]
Okay, I have merged the behind commits

**Comment by misolori** [comment]
@LiangchengJ reviewing this again and I'm seeing the drop shadow come through the middle of the shape, which isn't pretty. Do you mind updating it to fix that? my original sample has an example of this

image

**Comment by LiangchengJ** [comment]
Okay, no problem~
Let's see how this one: 
[Figma](https://www.figma.com/file/YfHtZUzbzkR0dQecwEue4P/macOS-Big-Sur-Icons?node-id=0%3A1)

image


@misolori

**Review by aiwinn — APPROVED** [review]

**Review by miguelsolorio — APPROVED** [review]
Awesome, this looks good to me!

**Comment by aiwinn** [comment]
Miguel SolorioMiguel SolorioMiguel Solorio

ในวันที่ พ. 16 มิ.ย. 2021 12:49 Miguel Solorio ***@***.***>
เขียนว่า:

**Pull request merged**
