### PR TITLE
add options for jumping to next/previous problem

### LINKED ISSUE #135249: Go to next problem sorted by diagnostic start position
## Requested Feature
From my current cursor position, I will like to jump to the problem with the closest diagnostic start position (ie the next/previous underlined word, no matter the color).

## Issue Description
Consider the following python snippet:

```
import math
impor math # warning, error
import mat # warning
print('hello' # error
```

At time of writing, pylance (from the python extension) reports 4 alternating error/warning problems with the above snippet. When cycling through the problems from line 1 (via `editor.action.marker.next`), the cursor jumps to lines in the order `2(error)->4(error)->2(warning)->3(warning)`.

While this may be the expected behaviour (as indicated by the command title `Go to Next Problem (Error, Warning, Info)`), I found this non-line-sequential behaviour to be fairly confusing as I expected my cursor to simply jump to the next underlined word.

Additionally, diagnostic severity levels are reevaluated every time we exit a chain of continuous jumps (eg. via `ESC`). For example, if we go from `2(error)->4(error)->2(warning)->ESC`, rerunning the command causes the cursor to jump to `2(error)` again.

It will be nice if we can implement a similar command which jumps to the next problem ordered by diagnostic start positions. In the above example, the expected behaviour for a cursor cycling through problems from line 1 would be `2(warning)->2(error)->3(warning)->4(error)`.

### PR DESCRIPTION
**Pull request by pohzipohzi**
This PR fixes #135249

Default behaviour:

before

After setting `"problems.compareOrder": "position"`:

after

### CODE REVIEW

**Review by jrieken — CHANGES_REQUESTED** [review]
Thanks for starting this. 

Tho, we cannot change the behavior just like that for all our users. Traversing diagnostics by severity (error, warning, info, hint) was a conscious decision. Please understand that users like the current behavior just like you dislike it. Therefore, this needs to be behind a user-setting.

**Review by jrieken — CHANGES_REQUESTED** [review]

**Review by jrieken — CHANGES_REQUESTED** [review]

**Review by jrieken — APPROVED** [review]
Thanks. This is looking good. Approving but since we are currently in endgame I can only merge in a few days

**Comment by ArturoDent** [comment]
I am seeing two `severity` options listed for the setting - one without a description.

compareOrder

**Comment by jrieken** [comment]
Thanks for pointing that out. The JSON schema default value didn't match the enum set. I have pushed a fix

**Pull request merged**
