### PR TITLE
fix(terminalPanel): context menu ignore monaco-sash click

### LINKED ISSUE #83172: Terminal split line right click issue
- VSCode Version: 1.39.2
- OS Version: macOS 10.15 (19A602)

Steps to Reproduce:

1. View -> Terminal
2. Split Terminal
3. Right mouse click on split line
4. Click (left mouse btn) somewhere to dismiss context menu

'split line' keep moving between terminals

right-click_bug

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by spiska**
This PR fixes #83172

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
The fix seems reasonable but I can't seem to reproduce the problem, is there any trick to it? Does it need a physical mouse not a trackpad maybe?

**Comment by spiska** [comment]
I updated linked issue (added step 4). 
I'm using macOS and physical mouse. Just target mouse cursor between terminal (hover on split line) and press right mouse click. A context menu will appear, but also it starts resizing of terminal after context menu hide.
In this case, I think, context menu should stay hidden like in another places in VSC.

**Comment by Tyriar** [comment]
@joaomoreno is it by design that the sash handles right clicks at all? Seems weird resizing a sash on Windows with right click.

**Comment by spiska** [comment]
Yes, it's weird, but I checked behavior across VSC and is same as here 😇

**Comment by joaomoreno** [comment]
I'd be more in favor of simply disabling sash resizing on right click, before I'd bleed knowledge of monaco-sash in here.

**Comment by spiska** [comment]
I don't think so. This is better solution for two reasons. As I mention, same behavior is in another cases in VSC. And second, if you show context menu by click on split line, you can't know which console window is affected (for example, which window you are spliting).

**Comment by Tyriar** [comment]
> I'd be more in favor of simply disabling sash resizing on right click, before I'd bleed knowledge of monaco-sash in here.

This is what I was getting at, the terminal component probably shouldn't know about `.monaco-sash`. I think the sash should swallow the event on right click and not to anything and avoid context menus from the event bubbling.

**Comment by Tyriar** [comment]
Closing since the fix should look different to this and be inside the sash code.

**Pull request closed without merging**
