### PR TITLE
Add lots of useful Rust Snippets

### PR DESCRIPTION
**Pull request by CryZe**
The old ones were lacking quite a lot of useful snippets, so I added them.

### CODE REVIEW

**Comment by aeschli** [comment]
@CryZe First thanks a lot for the nice contribution. We were discussing in the team and realized that the snippets wouldn't better be contributed through an extension. That would give you more freedom of making changes, and gives others the opportunity to select if they want these snippets or not.
Maybe we should remove our default snippets, so they don't interfere with snippets from extension.
What do you think?

**Comment by CryZe** [comment]
I'm not fully sure, but the developer of the RustyCode extension might have some opinions on that @saviorisdead (I hope mentioning works if he's not involved in this repo).

**Comment by saviorisdead** [comment]
I think it would better move this to `RustyCode`, as @aeschli said, cause it would be easier to support/change it. But again it may force user to install `RustyCode` just for snippets.

**Comment by aeschli** [comment]
I removed the snippets from the built-in extension to clear the way for snippet extensions and give users the choice if which snippets to install.
@CryZe It would be great if you could publish your snippets as extension. Let me know if I can help.

**Pull request closed without merging**
