### PR TITLE
Add SplitView to Settings editor

### LINKED ISSUE #79581: Allow settings UI TOC to be resized
The TOC in settings is rather narrow, and frequently truncates extension names. This feels especially unnecessary when using a wider display.
Screen Shot 2019-08-21 at 9 11 34 AM

This is not only triggered by extension names, but also affects built-in settings in non-English languages:
Screen Shot 2019-08-21 at 9 14 16 AM

Ideas:
- Change the balance between the TOC and Settings Pane to give TOC more room
- Increase the max-width and allow both TOC and Settings Pane to grow proportionally.
- ...?

### LINKED ISSUE #92935: Cannot easily switch settings categories
I have reported a related issue about a tree of settings categories not being focusable, but this is very new. Another thing is that even if it were focusable, when I would focus it and search for some group of settings like extensions/c#, then by pressing tab I would land on the c# settings. However when pressing tab after the last c# setting I land on the next category, and when pressing shift+tab on the first setting I land on the previous category. I do not see any easy way to return to a tree. It looks almost like all the settings of vscode were just displayed in one big group, so searching through them (if you don't use a search field) is non trivial.

### PR DESCRIPTION
**Pull request by rzhao271**
Fixes https://github.com/microsoft/vscode/issues/79581
Fixes https://github.com/microsoft/vscode/issues/92935

This PR adds a splitview to the Settings editor so that one can widen the table of contents, along with the ability to customize the border colours used within the Settings editor (settingsHeaderBorder and settingsSashBorder).
It also refactors the code so that the colours are in their own registry (like how the terminal does it), and groups some more constants at the top of the `SettingsEditor2.ts` file.
Additionally, because we're using a splitview, users can now easily tab back from the editor to the table of contents.

Note that a lot of the CSS changes are just to apply the CSS rules to the Settings editor renderers properly, because there are now extra DOM elements between the Settings editor container and the renderer containers due to the splitview.
Also, I did not add snapping to the left side, because even though one would be able to hide the table of contents, it would cause the sash to be very close to the sidebar sash, making it harder for the user to re-show the table of contents.

Another note is that when the overall Settings editor width is too small (i.e. below 600px), the table of contents still automatically hides.

Screencap of splitview feature

### CODE REVIEW

**Comment by misolori** [comment]
This is super cool, glad to see this finally get an update! A couple of notes:

- The shadow not extending all the way horizontally is looking a little odd, any way to make the extend all the way but still make the toc sticky?
  image

- The reflow of content looks a little odd here with the horizontal scrollbar, can we avoid that and keep resizing the containers until we get into the narrow view?
  CleanShot 2022-01-23 at 18 20 05@2x

- Can we keep the top/bottom padding the same? It looks a little strange that the bottom goes all the way to the bottom
    

- The range for the toc resize doesn't seem very big, below is what the max is. Should we bump this up a little higher? And can we also decrease the minimum for those who want a more compact view?
  CleanShot 2022-01-23 at 18 25 24@2x

- Similar to other sash resize, i would expect this one to persist across reload/windows and it does not

**Comment by rzhao271** [comment]
Current status of applying PR feedback:
- [ ] shadows: investigating. Still need to discuss what the final appearance will be like.
- [x] reflow/bottom scrollbar. We now switch to a single view when the total width is smaller than the ToC and editor min widths.
- [ ] sash padding: investigating. Still need to discuss what the final appearance will be like.
- [ ] min width range: will push up the change in a bit. I plan on decreasing the min editor width to 500px, and shortening the string setting inputboxes to at least 400px. The ToC min width will still be at 100px.
- [ ] persisting the sash width: still not working

**Comment by rzhao271** [comment]
I currently have it so that there is no gap between the sash and the top border, and we keep the shadows independent of each other, rather than have a single shadow.

Extended sash example

**Comment by roblourens** [comment]
I think this looks nice. Previously the horizontal line wasn't really a border for the scrollable content, it was more an underline for the tabs (user, workspace, folder) which is why the shadow was offset. Now it's being used as both where it gets a highlight for the active tab, and is also the boundary for the splitview and has the shadow right beneath it. I think this looks fine, as long as @misolori agrees.

**Comment by misolori** [comment]
My only concern is this appearing like a pseudo-view pane (which it's not) but I also wouldn't mark it a ship-blocker

**Pull request merged**
