### PR TITLE
remove "so far" from Problems message 

### PR DESCRIPTION
**Pull request by chrisdias**
this PR removes "so far" from the empty Problems message. "So far" presumes that you will have errors later!

### CODE REVIEW

**Comment by egamma** [comment]
@chrisdias @sandy081 since we are tweaking the message...

I was wondering whether we should be more explicit in the message and replace 'problems' with 'errors or warnings', we do not have to be as compact in the message as in the panel title:

'No errors or warnings have been detected in the workspace'

**Comment by sandy081** [comment]
How about more descriptive like and consistent with command palette?

image

'No problems (errors, warnings, infos) have been detected in the workspace'

**Comment by chrisdias** [comment]
`infos` isn't really a word, afaict. `Info` is the informal version of `information`.  I am not a linguist, but according to [this](https://ell.stackexchange.com/questions/17748/information-or-informations) Stack Exchange comment, `information` is non-countable so you don't add an `s`.

Information in this case is really a type of message, as is an error or warning, so the full descriptive text would be this:

`No error, warning, or informational messages have been detected in this workspace.`

While descriptive, it is quite long, and I'm not sure is necessary, especially as information messages are not nearly as common as errors and warnings.

So I think there are two options:

`No errors or warnings have been detected in this workspace.`
`No errors or warnings have been detected in the current file.`

or

`No problems have been detected in this workspace.`
`No problems have been detected in the current file.`

Personally, I think the latter is fine (which is what is in the PR), it is the most concise.

**Review by sandy081 — APPROVED** [review]
LGTM

**Pull request merged**
