### PR TITLE
Markdown and common toolbar icons consistency pass

### PR DESCRIPTION
**Pull request by chryw**
#50438 
@misolori @bpasero 
I did a consistency pass to some icons on the editor top right toolbar area.
- visually aligned these icons
- aligned svg code style (responsive, hide halo and foreground, etc.)
- removed some unnecessary css styles so they don't override the global size of these icons

There might be other icons could show up in that area. I only tested below icons and made sure they look good. Please let me know if this change makes other icons inconsistent.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
@chryw the ellipsis icon seems a bit inconsistent now:

Search (new left, old right, seems to be smaller now):
image

Panel (new left, old right, seems to be much larger now):
image

**Comment by bpasero** [comment]
ping @chryw @misolori

**Comment by chryw** [comment]
@bpasero will fix today

**Comment by bpasero** [comment]
@chryw thanks, I merged this to master for our June release 👍

**Pull request merged**
