### PR TITLE
Register loading icon for async tree

### LINKED ISSUE #95878: Loading icon is not showing for slow tree nodes
Issue Type: <b>Bug</b>

In latest Insiders build instead of loading icon I see spinning chevron for some tree nodes.
It's mostly noticeable in GitHub Pull Request extension tree, however I was able to reproduce it in Call Hierarchy while expanding some nested trees. 

Looks like `.codicon-loading:before` has lower priority than `.codicon-tree-item-expanded:before` which prevents icon change.

/cc @aeschli 

VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:44:55.510Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by IllusionMH**
This PR fixes #95878

I haven't found easy way to reference icon class for toggling expect to create common method which will be compatible with `toggleClass`. Other option would be to manually put whole class name or `'codicon-' + Codicon.icon.id` (which looks even worse).

Moved icons to separate file to ensure that order won't depend on imports order and made is similar to `searchIcons.ts`

/cc @aeschli

### CODE REVIEW

**Comment by aeschli** [comment]
@IllusionMH Thanks for jumping on it, I already started working on a solution where there's only one icon set at a time (the order in css should never matter)

**Comment by IllusionMH** [comment]
I was thinking about this approach but wouldn't it also remove `codicon` class from element?

**Comment by aeschli** [comment]
Yes, but it's added again if needed for the twisty.

**Comment by aeschli** [comment]
I created #95915 for a fix to avoid depending on the definition order

**Comment by aeschli** [comment]
> it also remove codicon class from element
Oh, I see that can happen when the twisty class name is removed.

Let's see if #95915 goes through, otherwiuse I fix it

**Comment by IllusionMH** [comment]
Oh I see, this approach should work because of later classes change in `abstractTree`, but not in general case.

Thanks for review and update!

**Pull request merged**
