### PR TITLE
Fix #173735

### LINKED ISSUE #170706: Markdown code block highlighting not present for Preview but present in editor
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
- OS Version: MacOS Ventura 13.1

Steps to Reproduce:

1. Create .md file and create ` ```py3 ` block with some Python code
2. Open preview

image

As you can see, the code in the editor on the left is being highlighted, but in the preview on the right it is not.

The issue occurs for ` ```py3 `.

For ` ```py ` and ` ```python ` it works for both editor and preview. For ` ```python3 ` there is no highlighting at all.

### LINKED ISSUE #173735: Markdown "shell" code fence language not recognized by Markdown Preview
Type: <b>Bug</b>

[Shell language](https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/lib/linguist/languages.yml#L6204).

` ```sh `:
sh

` ```shell `:
shell

` ```plaintext ` (for comparison):
c3

VS Code version: Code - Insiders 1.76.0-insider (25514d899f4bd877803defb213719f8af3d997d3, 2023-02-07T05:22:19.428Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

Extensions: none

### PR DESCRIPTION
**Pull request by maski07**
I fixed this issue referred to this pull request. [#170706](https://github.com/microsoft/vscode/commit/934e0ee5d87ba5d4b6f5ceb6914d1fbacced8532)

If this is in order, please consider merging this pull request.

Closes #173735

### CODE REVIEW

**Comment by maski07** [comment]
@pr-yemibedu icrosoft-github-policy-service agree

**Comment by htan-114** [comment]
> 

maski07:main

**Comment by maski07** [comment]
image

**Comment by maski07** [comment]
image

**Review by mjbvz — APPROVED** [review]

**Comment by maski07** [comment]
Thank you for merging the PR!

**Comment by maski07** [comment]
Sorry, I made a mistake.

**Comment by maski07** [comment]
Thank you for approving!

**Review by TylerLeonhardt — APPROVED** [review]

**Pull request merged**
