### PR TITLE
Fix #88294 Add commitData in commit interface

### LINKED ISSUE #88294: Git Extension: Commit interface should provide date and author name
It would be very useful to have commit date, author name, ... in the `Commit` interface when calling `getCommit([...])`

Something similar to this:

```ts
export interface Commit {
    readonly hash: string;
    readonly message: string;
    readonly parents: string[];
    readonly commitDate?: Date;
    readonly authorEmail?: string | undefined;
    readonly authorName?: string | undefined;

}
```

### PR DESCRIPTION
**Pull request by zjysdhr**
This PR fixes #88294

### CODE REVIEW

**Comment by zjysdhr** [comment]
by #89262, we only need to add commitData.

**Comment by joaomoreno** [comment]
Thanks! :+1:

**Comment by alexdima** [comment]
@joaomoreno I had to revert this via aa70f38ab24143de1948cd49154257b39b30b2f0 because it was causing a test to fail, and it appeared to be a real failure, not just a test fluke.

**Comment by joaomoreno** [comment]
Thanks for the heads up @alexdima

**Comment by joaomoreno** [comment]
I've fixed it: the tests needed adoption.

**Pull request merged**
