### PR TITLE
🎁 Add support for `fish` shell history

### LINKED ISSUE #155530: Support other shell types for terminal shell integration history
Currently only pwsh, bash and zsh shell types are allowed to restore and fetch history for shell integration:

https://github.com/microsoft/vscode/blob/8846ac54887deb74afdb262cbdaecdd12b824f98/src/vs/workbench/contrib/terminal/common/history.ts#L82-L94

This needs to be more flexible to support other REPLs like fish, [julia](https://github.com/microsoft/vscode/issues/155315), python, etc.

### PR DESCRIPTION
**Pull request by babakks**
Partially fixes #155530

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
This looks great! I'm off for a week but will check it out then 👍

**Comment by babakks** [comment]
@Tyriar I updated the PR by extracting the `sanitizeFishHistoryCmd` function and adding some unit tests to verify its RegExp substitution works correctly.

**Review by Tyriar — APPROVED** [review]
Thanks @babakks, awesome PR. Just pushed a shell type detection edge case fix I hit.

**Review by joyceerhl — APPROVED** [review]

**Comment by babakks** [comment]
@Tyriar Happy to hear that. You're welcome.

**Pull request merged**
