### PR TITLE
Fix hardcoded rpm dependencies for armv7hl and aarch64

### PR DESCRIPTION
**Pull request by psgreco**
Related to RPM part of https://github.com/microsoft/vscode/issues/106473

### CODE REVIEW

**Comment by joaomoreno** [comment]
Oh I see, that's how you encode it for RPM! Thanks @psgreco, will trigger some builds and give it a try.

**Comment by joaomoreno** [comment]
@psgreco I just realized you're Pablo from https://forums.centos.org/viewtopic.php?f=55&t=73495&sid=efd80c413274e6e262c64bdd2812de74&start=20. Thanks for your work there, I have SD cards with CentOS 7 and 8 for RPi4, all thanks to you!

The RPMs produced now seem much better but still hit some roadblocks when installing. Here's the output on my Pi with CentOS 8:

```
[joao@localhost Downloads]$ sudo yum localinstall code-insiders-1.52.0-1606210971.el7.aarch64.rpm 
Last metadata expiration check: 0:12:56 ago on Tue 24 Nov 2020 03:41:09 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_2.11)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.3)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.3.2)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.3.4)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.4)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.6)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.7)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libc.so.6(GLIBC_2.9)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libm.so.6(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libpthread.so.0(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libpthread.so.0(GLIBC_2.3.2)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
  - nothing provides libpthread.so.0(GLIBC_2.3.3)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Any thoughts?

**Comment by psgreco** [comment]
> @psgreco I just realized you're Pablo from https://forums.centos.org/viewtopic.php?f=55&t=73495&sid=efd80c413274e6e262c64bdd2812de74&start=20. Thanks for your work there, I have SD cards with CentOS 7 and 8 for RPi4, all thanks to you!
> 
Hehe, same one, happy to help ;)
> The RPMs produced now seem much better but still hit some roadblocks when installing. Here's the output on my Pi with CentOS 8:
> 
> ```
> [joao@localhost Downloads]$ sudo yum localinstall code-insiders-1.52.0-1606210971.el7.aarch64.rpm 
> Last metadata expiration check: 0:12:56 ago on Tue 24 Nov 2020 03:41:09 PM UTC.
> Error: 
>  Problem: conflicting requests
>   - nothing provides libc.so.6(GLIBC_2.11)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.3)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.3.2)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.3.4)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.4)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.6)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.7)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libc.so.6(GLIBC_2.9)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libm.so.6(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libpthread.so.0(GLIBC_2.2.5)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libpthread.so.0(GLIBC_2.3.2)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
>   - nothing provides libpthread.so.0(GLIBC_2.3.3)(64bit) needed by code-insiders-1.52.0-1606210971.el7.aarch64
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```
> 
Yeah, that looks much better, TBH, my patch was a complete shot in the dark so we could get to this point, the real failures
> Any thoughts?

Is there a simple way for me to build `code` here So I can get you a final version? or just point me to the version you're testing right now and I can take another look

**Comment by joaomoreno** [comment]
Absolutely, here's a download link for the build tarball: https://az764295.vo.msecnd.net/insider/5987e4076572afbac347b1ec7946ecc59ecaf682/code-insider-arm64-1606240510.tar.gz

Thanks a lot for your help.

**Comment by psgreco** [comment]
Continues in https://github.com/microsoft/vscode/pull/111253

**Pull request merged**
