### PR TITLE
Add Copy Command Label to Keyboard Shortcuts.

### LINKED ISSUE #125091: Double hover
Testing #125005

image

### LINKED ISSUE #125092: [FR] Copy Command Title
Currently, for copying a command like `Add Cursor Above` on the "Keyboard Shortcuts" page, there're two options:

1. Copy

   Copies

   ```json
   {
     "key": "ctrl+alt+up",
     "command": "editor.action.insertCursorAbove",
     "when": "editorTextFocus"
   }
   ```

2. Copy Command ID

   Copies `editor.action.insertCursorAbove`

But really, quite often, we just want to copy `Add Cursor Above`, and there's no option for that.

Therefore, I'm making a feature request for it.

### PR DESCRIPTION
**Pull request by timfenney**
This PR fixes #125092.

### CODE REVIEW

**Comment by timfenney** [comment]
@sandy081 did you get time to take a l:eyes:k at this yet?

**Comment by sandy081** [comment]
Instead of context menu can you please make the text selectable?

**Comment by timfenney** [comment]
> Instead of context menu can you please make the text selectable?

It is a good idea! What way should it be selectable? The UI already allows:

- single click to select row
- double click to add keyboard shortcut

...for this reason, I am not sure what is a good UX here. What do you think @sandy081 :thinking: ?

Also, we have 2 ways of copying aspects of the command via context menu already. Is it orthogonal to have a 3rd way of copying something from the command somewhere else?

**Comment by sandy081** [comment]
Please ignore my previous comment. After thinking more I felt initial approach of providing the copy command in the context menu makes sense. Please let me know if the changes with context menu option are ready for review.

**Comment by timfenney** [comment]
@sandy081 it is ready for review :+1:

**Review by sandy081 — APPROVED** [review]
LGTM

**Pull request merged**
