### PR TITLE
Fixes Extension Feature Contributions doesn't render markdownDescription

### LINKED ISSUE #95671: Extension Feature Contributions doesn't render markdownDescription
Issue Type: <b>Bug</b>

```js
"errorLens.padding": {
	"type": "string",
	"default": "",
	"markdownDescription": "Adds padding for the message. Visible difference when `message` colors are set. [Issue #23](https://github.com/usernamehw/vscode-error-lens/issues/23). Example: `2px 1ch`.",
	"examples": [
		"2px 1ch"
	]
},
```

Screenshot (185)

VS Code version: Code - Insiders 1.45.0-insider (ec0d19789f89d4c25895f4a0cf364276cfb0c6ed, 2020-04-20T06:08:30.812Z)
OS version: Windows_NT x64 6.2.9200

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #95671

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Any reason not to get this merged?

**Comment by sandy081** [comment]
@jeanp413 Sorry that this was lost from my notice - can you please update your branch and resolve the conflicts?

**Comment by jeanp413** [comment]
done :+1:

**Review by sandy081 — APPROVED** [review]
Changes look good. Thanks. Approved.

**Pull request merged**
