### PR TITLE
Add support for trigger points

### PR DESCRIPTION
**Pull request by gayanper**
A trigger breakpoint is a kind of breakpoint which act as a trigger for
other breakpoints to be enabled for the debugger. A trigger point is used
when one wants to avoid hitting certain breakpoints until a specific path
is executed where the trigger point is placed in the the specific path.

The current implementation softly disable all none trigger breakpoints
until one of the trigger breakpoints is hit. When that happen all none
trigger breakpoints are enabled and the trigger points will be softly
disabled.

### CODE REVIEW

**Comment by gayanper** [comment]
Implementation for https://github.com/microsoft/vscode/issues/152428 as a starting point

**Comment by connor4312** [comment]
Thanks for the PR, I'll review this in the next few days! If you have time, could you also include a [gif](https://gifcap.dev/) of what the experience is with this PR so we can give initial high level feedback? 🙂

**Comment by gayanper** [comment]
Yes i will attach a screencast tomorrow. May be we need a new icon as well. But I will wait to get feedback on the approach first.

**Comment by gayanper** [comment]
https://user-images.githubusercontent.com/7471994/188278973-14562d91-dd77-4853-9974-407898cbbd88.mp4

screencast on the current supported functionality.

**Comment by gayanper** [comment]
@connor4312 hope the screencast shows the functionality currently implemented

**Comment by connor4312** [comment]
Initial feedback looking at the demo: the functionality is cool, but it's missing visual indicators: I would expect other breakpoints to be in the "disabled" state and that the "triggerpoint" would have a differentiating icon. 

Also interested in @roblourens' feedback on the overall feature

**Comment by gayanper** [comment]
> Initial feedback looking at the demo: the functionality is cool, but it's missing visual indicators: I would expect other breakpoints to be in the "disabled" state and that the "triggerpoint" would have a differentiating icon.
> 
> Also interested in @roblourens' feedback on the overall feature

I think we can make the other breakpoints disabled at the rendering level with the new property. A "different icon for trigger point" do we need to a add a new icon into vscode icon library ?

**Comment by roblourens** [comment]
Not sure how I feel about this as a feature - it definitely needs clear UI. Probably a new breakpoint icon for the trigger breakpoint itself, and some indication for breakpoints that are waiting for the trigger breakpoint. But also is this how people expect it to work- that all breakpoints wait on the one trigger breakpoint? Can you have multiple trigger breakpoints? Can you combine it with conditions? I would expect that maybe you have a particular breakpoint that is waiting on a trigger breakpoint, but you can still have other normal breakpoints too, but that makes the UX much more complicated. Is this how it works in other IDEs?

**Comment by gayanper** [comment]
> Not sure how I feel about this as a feature - it definitely needs clear UI. Probably a new breakpoint icon for the trigger breakpoint itself, and some indication for breakpoints that are waiting for the trigger breakpoint. But also is this how people expect it to work- that all breakpoints wait on the one trigger breakpoint? Can you have multiple trigger breakpoints? Can you combine it with conditions? I would expect that maybe you have a particular breakpoint that is waiting on a trigger breakpoint, but you can still have other normal breakpoints too, but that makes the UX much more complicated. Is this how it works in other IDEs?

@roblourens I have update the patch to mark the breakpoints disabled. I have attached the new screencast. And i also agree with might need two icons for both trigger point and dependent breakpoints as well. 

In other IDEs:

Eclipse: In Eclipse the functionality is like the current implementation with different overlay icons on the breakpoints.
IntelliJ: In InteliJ you can configure a breakpoint to be disabled until a selected breakpoint is hit. 

I'm open to enhance this feature to implement either of the functionality. And i fully agree the current state of this patch is not so good, having all breakpoints disabled might not be a good idea as well given vscode is a polygot editor/ide.

**Comment by gayanper** [comment]
new screencast
https://user-images.githubusercontent.com/7471994/188962383-a0a1c3cd-e936-4bb0-85a1-872330878c53.mp4

**Comment by gayanper** [comment]
Closing due to https://github.com/microsoft/vscode/pull/166202

**Pull request closed without merging**
