### PR TITLE
Show a quickpick for changing display language

### LINKED ISSUE #22758: Suggestion: ability to restart when changing language
- VSCode Version: 1.10.0
- OS Version: Any

When changing the language (`configure language` command), VSCode needs to be restarted to use the new language.

I wish that VSCode prompted me to restart (if I wanted to) when changing the language.

### PR DESCRIPTION
**Pull request by RMacfarlane**
While verifying issues I had to change my display language a couple of times, and I think the experience for it could be bit better.

Instead of opening the `locale.json` file, this PR uses the localization service to get the list of available languages and display it in a quick pick. The current language is selected by default, and the placeholder text explains that VS Code will restart on selection. When something is selected, the `locale.json` file is written to as before and VS Code gets restarted.

screen shot 2019-02-27 at 5 10 17 pm

When running out of sources I don't ever see the UI language change - I haven't dug into how nls gets loaded so I'm not sure if that's expected or not. But I do see that the `locale.json` file is updated correctly.

This fixes https://github.com/Microsoft/vscode/issues/22758

Let me know if you think this is a good change. Thanks!

### CODE REVIEW

**Comment by dbaeumer** [comment]
@RMacfarlane thanks a lot for the PR.

**Comment by dbaeumer** [comment]
I looked over it and I have a suggestions: I think we should indicate whether the corresponding language pack is available locally. If not it might even be cool to install it. Otherwise the expierence might not be nice when selecting a LP that is not installed.

**Comment by RMacfarlane** [comment]
Ah, thanks! I had misread the code for `getLanguageIds`. I've changed it now so that the quick pick is only populated with languages that are available locally, and there's an option at the bottom to install more languages that opens the extension's viewlet with a query for language packs.

**Comment by dbaeumer** [comment]
@RMacfarlane have you updated the PR. I think I don't see the new code changes.

**Comment by RMacfarlane** [comment]
@dbaeumer it should be updated now, I just rebased against master

**Comment by dbaeumer** [comment]
@RMacfarlane LGTM. Feel free to merge in.

**Comment by RMacfarlane** [comment]
@dbaeumer Thanks for reviewing! I pushed one more change to show a confirmation dialog before restarting, based on feedback when demoing to the Redmond team. I'll go ahead and merge since that addition is very simple.

**Pull request merged**
