### PR TITLE
Use path_helper in user shell in darwin

### LINKED ISSUE #21655: PATH issues with Fish shell on macOS
So while having a problem PATH related I created an issue in the omnisharp vscode repo about this. However right after doing a quick `chsh /bin/bash` and a restart of vscode my suspicions were right and now I'm coming back to you guys.

The issue in omnisharp vscode: 
https://github.com/OmniSharp/omnisharp-vscode/issues/1259

Previous fix I'm pointing to:
https://github.com/Microsoft/vscode/issues/8434

Seems that somehow this fix regressed again. Or my shell does even more effort to break it...

I'm still using fish with powerline as my shell and it seems to break the env (and in turn PATH) parsing again.

I propose a change to the PATH resolution strategy for OSX:

- Run `path_helper` for an initial view of an ok customizable PATH of an OSX installation. It gathers all paths from the file `/etc/paths` and paths in files in `/etc/paths.d` like the one for `dotnet`. It outputs a PATH string of these paths.
- Do the hacky thing with reading out a login shell's env and parsing the PATH from it.
- Use the hacky output if there is actually any. Every login shell runs `path_helper` but also includes all user customizations to PATH from say .bash_profile. 
- If the shell is so custom it breaks the hacky way of fishing out the PATH then just use the `path_helper` output.

This way the result will at least always be a working env (for say quite integrated things like spawning a `dotnet` process for doing a restore).
Because everyone should be able to expect that after installing a pkg like the dotnet cli vscode (and its extensions) can always find and work with it seamlessly.

```
dotnet --info output:
.NET Command Line Tools (1.0.0-rc4-004849)

Product Information:
Version: 1.0.0-rc4-004849
Commit SHA-1 hash: 7dcefb5076

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.12
OS Platform: Darwin
RID: osx.10.12-x64
Base Path: /usr/local/share/dotnet/sdk/1.0.0-rc4-004849
VS Code version: 1.10.0-insider
C# Extension version: 1.7.0
```

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #21655

### CODE REVIEW

**Comment by idan** [comment]
Managed to work around the build issues with NPM5 and get a copy of this branch running via `./scripts/code.sh`. I rebased onto master before building with `./scripts/npm.sh install`

The flowtype extension executes without complaint and without needing to launch vscode from inside a terminal whose CWD is the project directory. I manually instrumented the flowtype extension [here](https://github.com/flowtype/flow-for-vscode/blob/master/lib/pkg/flow-base/lib/FlowHelpers.js#L183) to log the `process.env.PATH` and it appears to include everything. 🎉 🎉 🎉 ✨ 🍰 

However, this is still an instance of vscode launched from inside a terminal. I wracked my brains trying to figure out how to produce a double-clickable build [from the instructions](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) to no avail. `gulp vscode-darwin` succeeds but the resulting binary at `.build/electron/Code - OSS.app` opens up a generic electron window like this:

2017-07-23 at 15 13

Attempting to drop various promising-looking files on the DnD target didn't yield anything (various files in `out`, `out-build`, and `out-vscode`.)

Any pointers on how to test this effectively?

**Comment by joaomoreno** [comment]
@idan If you'd like to run this build, just [download it](https://az764295.vo.msecnd.net/insider/a3efde81118e78328316a61686006b59775d76a5/VSCode-darwin-insider.zip).

**Comment by joaomoreno** [comment]
cc @idan @NinoFloris

**Comment by NinoFloris** [comment]
Doing a process.env in this build shows me it actually did not run? still just path defaults

**Comment by idan** [comment]
Same here

**Comment by joaomoreno** [comment]
That is odd @NinoFloris, as Code should be running `path_helper` as suggested in #21655. So, apparently, that doesn't fix it.

**Comment by NinoFloris** [comment]
it should as running path_helper from within fish shell returns a lot of info.
Probably something with the build or the call to path_helper going wrong.

**Comment by joaomoreno** [comment]
> it should as running path_helper from within fish shell returns a lot of info.

> I might be thick but how does getDarwinEnvironment actually return an environment from that func?

It doesn't launch `/usr/libexec/path_helper` from fish shell, it just spawns it and parses its result. Launching from within fish shell is a chicken-egg problem... if we could do that, the whole thing would be fixed.

**Comment by idan** [comment]
OK, so I looked at [how atom is handling this](https://github.com/atom/atom/blob/master/src/update-process-env.js#L79), and it looks like it's the same sort of setup.

After some experimentation, it seems that the wiring of stdout is busted. When I try running `path_helper` like so from inside code's developer console on my machine, I get the correct `$PATH`:

```js
(() => {
    const cp = require('child_process')
    const buffers = []
    const child = cp.spawn(process.env.SHELL, ['-lc', 'command /usr/libexec/path_helper'], {encoding: 'utf8', detached: true, stdio: 'pipe'})
    child.on('error', (e) => {
        console.error(e)
    })
    child.stdout.on('data', (data) => {
        buffers.push(data)
    })
    child.on('close', (code, signal) => {
        console.log(Buffer.concat(buffers).toString('utf8'))
    })
})();
```

The above results in output (redacted) like:

```
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~ALLMYOTHERPATHENTRIES~"; export PATH;
```

I know that originally this used a stdio setup like `['ignore', 'pipe', process.stderr]`, but this led to stdout being empty.

If invoked with -i, it produces the same output, but prefixed with a block like:

```
begin;  function __direnv_export_eval --on-event fish_prompt; 	eval (direnv export fish); end  
 ;end <&3 3<&-
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~ALLMYOTHERPATHENTRIES~"; export PATH;
```

Not sure how this affects other shells yet; but at least it's showing the correct value for me, which is progress. Maybe it's a good clue on how to proceed?

**Comment by joaomoreno** [comment]
The use of `command ` before `path_helper` is interesting... I wonder what that does?

**Comment by joaomoreno** [comment]
https://askubuntu.com/questions/512770/what-is-use-of-command-command

If you remove `command ` from that snippet does it still work?

**Comment by joaomoreno** [comment]
Yes, using `pipe` makes your setup work, but pretty much everyone else fail. We tried it and ended up reverting it: 44fcdbf31c60eb7ee660df6b6d2dedc4c735a9bc

**Comment by joaomoreno** [comment]
@idan People over at https://github.com/Microsoft/vscode/issues/21655 say this is no longer an issue. How about for you?

**Comment by idan** [comment]
Looks good in 1.19! 😍

**Comment by joaomoreno** [comment]
Awesome sauce.

**Pull request closed without merging**
