### PR TITLE
adding modal progress to progressService2

### PR DESCRIPTION
**Pull request by sbatten**

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Some minor feedback:
* this should probably not live in `platform` but `workbench/services` unless the standalone editor also needs it
* you still need to add it to `workbench.main.ts` / `workbench.nodeless.main.ts` so that the service is properly registered
* the spinning progress icon seems cropped on Linux at least (see screenshot below)
* now that I think about it, should this move into `IProgressService2` instead of being a separate service? we can sell this as "modal progress". Sorry for not bringing this up earlier.

image

**Comment by bpasero** [comment]
Also, not sure if you accept UX feedback already, but should the custom dialog show a title so that it looks and feels more like a native dialog? I feel like showing the thing with close button but without title is weird.

Native dialog title:
image

**Comment by sbatten** [comment]
@bpasero I think having the title might make it appear to be draggable which is currently not supported and not likely to happen anytime soon.

**Comment by sbatten** [comment]
@bpasero I've updated the PR with both service implementations. Here is a comparison of usage to see which is preferred:
```ts
export class ShowLoadingDialogAction extends Action {
	public static readonly ID = 'workbench.action.showLoadingDialog';
	public static readonly LABEL = nls.localize('showLoadingDialog', "Show Loading Dialog");

	constructor(
		id: string,
		label: string,
		@IOverlayService private readonly overlayService: IOverlayService
	) {
		super(id, label);
	}

	public run(): Promise<any> {
		const dialogPromise = this.overlayService.show('The process is taking longer than expected. Please wait or cancel the process...', ['Cancel']);

		return new Promise((resolve) => {
			setTimeout(() => dialogPromise.cancel(), 200000);

			dialogPromise.finally(() => resolve());
		});
	}
}

export class ShowProgressDialogAction extends Action {
	public static readonly ID = 'workbench.action.showProgressDialog';
	public static readonly LABEL = nls.localize('showProgressDialog', "Show Progress Dialog");

	constructor(
		id: string,
		label: string,
		@IProgressService2 private readonly progressService: IProgressService2,
		@INotificationService private readonly notificationService: INotificationService
	) {
		super(id, label);
	}

	public run(): Promise<any> {
		const tokenSource = new CancellationTokenSource();
		const task = (progress: IProgress<IProgressStep>): any => {
			progress.report({ message: 'The process is taking longer than expected. Please wait or cancel the process...'});

			return new Promise((resolve, reject) => {
				tokenSource.token.onCancellationRequested(reject);

				setTimeout(() => {
					resolve();
				}, 5000);
			});
		};

		const onDidCancel = () => {
			tokenSource.cancel();
		};


		return this.progressService.withProgress({ location: ProgressLocation.Dialog }, task, onDidCancel).then(() => {
			this.notificationService.info('Process finished');
		}, () => {
			this.notificationService.info('Process canceled by user');
		});
	}
}
```

**Comment by bpasero** [comment]
@sbatten I like the progress service more because overlay service implies you can do more with it whereas it is really only for showing global progress.

**Comment by sbatten** [comment]
@bpasero I tried to repro the cropped icon on linux with different zoom levels without success. let me know if you still see this.

**Comment by bpasero** [comment]
@sbatten I still see it, even on macOS:

image

Are you up for some more feedback? I think if you provide a "Dismiss" button by default, the progress should move into a different place, e.g. why not make it a notification then that continues to show progress?

**Pull request merged**
