### PR TITLE
UI freeze when trusting/untrusting current folder (fix #159224)

### LINKED ISSUE #159224: UI freeze when trusting/untrusting current folder
Type: <b>Bug</b>

1. With VS Code workspace open
1. Open workspace trust manager
1. Trust or untrust the workspace

**bug**
This causes a 30second UI freeze for me

VS Code version: Code - Insiders 1.71.0-insider (Universal) (9529e11f6481ae53bba821b05e34549491b9415e, 2022-08-25T13:02:01.718Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
tsl-problem-matcher|amo|0.6.2
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.11
emojisense|bie|0.9.1
folder-source-actions|bie|0.2.1
github-markdown-preview|bie|0.3.0
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-eslint|dba|2.2.6
typescript-notebook|don|2.0.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
codespaces|Git|1.10.3
copilot|Git|1.43.6621
remotehub|Git|0.41.2022082501
vscode-pull-request-github|Git|0.49.2022082509
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
vscode-postfix-ts|ipa|1.10.1
search-editor-apply-changes|jak|0.1.1
latex-workshop|Jam|8.29.0
vscode-platform-specific-sample|joa|1.15.0
vscode-memfs|jri|0.0.3
vscode-position|jtr|1.1.2
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.5
vscode-docker|ms-|1.22.1
vscode-language-pack-de|MS-|1.71.8240936
python|ms-|2022.13.12371004
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.8.1002391036
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.248.0
remote-ssh|ms-|0.85.2022082215
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.11.1
hexeditor|ms-|1.9.8
js-debug-nightly|ms-|2022.8.1917
live-server|ms-|0.2.13
remote-explorer|ms-|0.1.2022082509
remote-repositories|ms-|0.19.2022082501
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.119
vscode-js-profile-flame|ms-|1.0.4
vscode-marketplace-extension-browser|ms-|0.0.6
vsliveshare|ms-|1.0.5695
java|red|1.9.0
code-spell-checker|str|2.6.0
notification-tester|svi|2.5.1
rest-book|tan|6.2.1
ayu|tea|1.0.5
luna-paint|Tyr|0.16.0
sort-lines|Tyr|1.9.1
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0

(2 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by bpasero**
My part of the change addresses the consuming side of the event `IEditorResolverService.onDidChangeEditorRegistrations` but after discussion with @sandy081 we should probably also look into debouncing the source to reduce the overhead on possible other listeners.

### CODE REVIEW

**Comment by sandy081** [comment]
@bpasero changes are good, especially configuration is updated only once now instead of three times. 

But, I think the real issue is that following event is called too many times (80 times for the @mjbvz 's set up). 

https://github.com/microsoft/vscode/blob/35b971c92d210face8c446a1c6f1e470ad2bcb54/src/vs/workbench/services/editor/common/editorResolverService.ts#L141

So the right fix is that this event should be called only once.

**Comment by lramos15** [comment]
@sandy081 Is there a way to know when profiles are being swapped and when the swap has completed? That one is firing a lot because it must register all the new custom editor extensions which are being added and removed from the user's environment. This could be debounced but not sure if that is the suggested best solution

**Comment by sandy081** [comment]
I do not think there is an event that says contribution points are read now CC @alexdima 

I see Notebooks and CustomEditors are registering editors while handling the extension points. It is quite common that during then there can be multiple registrations and triggering an event per each registration is not effective and costly. You can either support registering multiple editors (bulk register) so that the consumers can register all editors at once or provide an API to buffer events like below

https://github.com/microsoft/vscode/blob/12dbd7614b3b9cb0bc34b670a09a2b93545f120d/src/vs/platform/contextkey/browser/contextKeyService.ts#L295

**Comment by lramos15** [comment]
> You can either support registering multiple editors (bulk register) so that the consumers can register all editors at once

We wouldn't be able to do this because we want unique disposables per registered extension so if an extension uninstalls it can then be removed from the service.



> provide an API to buffer events like below

I guess we could do this. The burden is placed on the consumer of the API instead of us as the service which isn't an ideal flow but I cannot think of a better way without a way of checking `onDidExtensionsLoadComplete` or something

**Comment by sandy081** [comment]
> We wouldn't be able to do this because we want unique disposables per registered extension so if an extension uninstalls it can then be removed from the service.

Probably the API can return an array of disposable for each?

**Comment by lramos15** [comment]
I tried my best to use the `bufferChangeEvent` method to silence some of the events. Notebooks are especially difficult with the way their provider model is structured.

**Comment by bpasero** [comment]
👍

**Comment by bpasero** [comment]
@sandy081 ?

**Review by sandy081 — APPROVED** [review]
Thanks for fixing this.

**Comment by sandy081** [comment]
BTW you can also consider [MicrotaskEmitter](https://github.com/microsoft/vscode/blob/0ddb3aef528d970c8371db1fc89775ddcaa61e1b/src/vs/base/common/event.ts#L988) to reduce multiple events in the one event loop into single event.

**Pull request merged**
