### PR TITLE
Editor tabs: prevent close button of last tab on wrapped row from right-justifying

### LINKED ISSUE #126532: WrapTabs closing icon too far
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0

Steps to Reproduce:

1. `"workbench.editor.wrapTabs": true,`
2. Open multiple tabs

Is this an expected behavior?
I found the closing icon way too far away from the file name:
Screenshot from 2021-06-16 23-03-41

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #126532 by making the Close button easier to reach when tabs are wrapping and the tab is the last one in a wrapping row.

### CODE REVIEW

**Comment by bpasero** [comment]
I am way too afraid of touching CSS in tabs like that. There is so many things going on in there, you don't even wanna know. For starters, when `"workbench.editor.tabSizing": "shrink"` is configured, we now get gradients rendered by default even when enough space is there:

image

I also can't help but think that this looks somewhat broken:

image

Given the tab stretches all the way to the end.

**Comment by gjsjohnmurray** [comment]
@bpasero thanks for your feedback. I realize the CSS making tabs work is a beautiful and fragile thing, but I decided to have another go. The change I just pushed seems to avoid the original impact on the `"workbench.editor.tabSizing": "shrink"` case.

And I think it's not really a problem how the tab extends beyond the Close button. For me, the current situation ranks as a papercut. Frequently I hover over the unselected last tab in a wrapped row and am startled not to see the Close button appear immediately on the right of the label. Then I remember to look all the way to the end, see it there, then have to take my mouse for a walk.

**Comment by gjsjohnmurray** [comment]
@bpasero would you consider merging this early in the new iteration? If feedback is unfavourable then it can easily be reverted.

**Comment by bpasero** [comment]
I will miss this month for being on vacation. Will look into this as part of our issue grooming iteration that is coming up.

**Comment by bpasero** [comment]
I am not so happy with the result because it moves the close button in every tab closer to the end of the label and away from the right hand side of the tab:

image

Since I did not hear about this issue from other users so far, I will probably not change the location of the close button.

**Comment by gjsjohnmurray** [comment]
I have pushed a change that should limit the effect on the close button to only the rightmost tab of all rows except the last one.

**Comment by gjsjohnmurray** [comment]
@bpasero would you be willing to merge this early in the November iteration that just opened so we can see if anyone likes/dislikes it, or if it causes any broblems that can't easily be fixed?

**Comment by gjsjohnmurray** [comment]
Can we merge this and see if anybody squeals?

**Comment by bpasero** [comment]
I am sorry but have decided to not accept the change in this area and since we are in grooming iteration, I am closing this PR.

**Comment by gjsjohnmurray** [comment]
OK, I understand. Glad to see that PRs are being groomed as well as issues.

**Pull request closed without merging**
