### PR TITLE
Corrected Turkish context menu texts' encoding errors.

### PR DESCRIPTION
**Pull request by onurravli**
Corrected Turkish context menu texts' encoding errors. For example, `Windows Gezgini ba�lam men�s�ne "%1 �le A�" eylemini ekle` changed to `Windows Gezgini dizin bağlam menüsüne "%1 İle Aç" eylemini ekle`.

### CODE REVIEW

**Comment by onurravli** [comment]
@microsoft-github-policy-service agree [company="@ravlico"]

**Comment by onurravli** [comment]
@microsoft-github-policy-service agree company="ravlico"

**Comment by onurravli** [comment]
Opened an issue. #167706

**Comment by onurravli** [comment]
@microsoft-github-policy-service agree company="ravlico"

**Comment by roblourens** [comment]
The source of our loc files is https://github.com/microsoft/vscode-loc, please submit your PR there

**Pull request closed without merging**
