### PR TITLE
Support for before & after decorations

### PR DESCRIPTION
**Pull request by aeschli**

### CODE REVIEW

**Comment by aeschli** [comment]
You can use branch aeschli/css-decorators-test to see the API in use by css test extension

**Comment by aeschli** [comment]
@alexandrudima I made the changes we discussed:
- only one call to `deltaDecorations`
- `beforeContentClassName` & `afterContentClassName` on `IModelDecorationOptions`, creating extra decorations in `viewModelDecorations.ts`
- add 'border', 'outline', 'contentText', 'contextIconPath' to API

Still not sure if to enable SVG content. At the moment it is text and file path to an icon. We should maybe also allow URL to remote servers.

**Comment by siegebell** [comment]
vscode 1.3.0-insider; commit a6aa32032

I'm using your feature with an injection attack (for `display: none` or `font-size: 0pt`; see #6201) to visually replace one string with another (#2402).

Here are a couple issues I'm seeing:
1. The `before` decoration does not work if its range is empty and it falls at the end of a line. The `after` decoration does not work if its range is empty and falls at the beginning of a line.
2. `contentText` does not preserve syntax coloring.

**Comment by egamma** [comment]
@siegebell thanks for the feedback, please file separate issues for the issues you have encountered.

**Comment by vasily-kirichenko** [comment]
@aeschli Is there documentation or usage examples available anywhere for this feature? I cannot find any.

**Comment by aeschli** [comment]
Sorry, no documentation besides the [regular API doc](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ThemableDecorationAttachmentRenderOptions).

A general sample code on decorators can be found [here](https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample), and a use case of before decorators [here](https://github.com/Microsoft/vscode/blob/master/extensions/css/client/src/colorDecorators.ts).

**Comment by vasily-kirichenko** [comment]
@aeschli thanks!

**Pull request merged**
