### PR TITLE
 Fix different error message in source and package.nls for npm package

### PR DESCRIPTION
**Pull request by qcz**

### CODE REVIEW

**Comment by egamma** [comment]
@qcz Thanks for the fix!

**Comment by qcz** [comment]
@egamma: This PR is missing from the Thank You section of [v1_18.md](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md) :)

**Comment by egamma** [comment]
@qcz sorry, I forgot to assing a milestone to the PR, this is why we didn't find it. I will add it.

**Comment by qcz** [comment]
@egamma: No problem! Thanks!

**Pull request merged**
