### PR TITLE
Git commit using '--signoff'

### PR DESCRIPTION
**Pull request by FabianLauer**
This PR addresses issue #7010. It adds support for committing with the `--signoff` flag enabled.

Instead of using a checkbox under the commit message input as suggested by @FrenchBen in the original issue, I added 2 actions to the context menu since signed off commits are fairly rare.

vscode-git-signoff-actions

### CODE REVIEW

**Comment by joaomoreno** [comment]
Thanks!

**Comment by FabianLauer** [comment]
Awesome, thanks! 😃 
I hope I didn't cause you more work than the PR saved, looks like you made quite a few changes in these files afterwards 😳

**Comment by joaomoreno** [comment]
No no, thank you! It was pretty great already, I simply did small refactorings. Most importantly, I made a `protected abstract commit()` on the `BaseCommitAction`, which lets us reuse most of the code between all those actions. 👍

**Comment by FabianLauer** [comment]
Great, thanks for the insight, very helpful 😃

**Pull request merged**
