### PR TITLE
Use different problem colors for editor and tree

### LINKED ISSUE #43179: Add separate theme colors for explorer rendered diagnostics
The new error highlight in the explorer window is great, but for some reason the colours are all black for me. I've tried different themes, but it doesn't make any difference:

image

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #43179

### CODE REVIEW

**Comment by bpasero** [comment]
@jrieken @usernamehw yeah I would suggest to make this independent from the `list` prefix, so that this color can be used in more places. It seems to me the color would be used in places where our `ResourceLabel` is used today. Maybe it should then be `resourceLabel.errorForeground` and `resourceLabel.warningForeground` to make it a little bit more specific to where this color is used.

/cc @aeschli for input on the color name

**Comment by aeschli** [comment]
I'd go for list because the new color must play well with the list colors (list.invalidItemForeground, list.hoverBackground, list.inactiveFocusBackground...)
If the same color is used in tab, then we, to be correct, should also introduce 'tab.errorForeground`

**Comment by jrieken** [comment]
@aeschli Color naming suggestions?

**Comment by aeschli** [comment]
As suggested in the PR, `list.errorForeground` and `list.warningForeground`.
The color description should be improved to `Foreground color of list items containing errors`

**Comment by jrieken** [comment]
Thanks guys. @usernamehw Can you update the command according to https://github.com/Microsoft/vscode/pull/49020#issuecomment-386593162.

**Review by jrieken — APPROVED** [review]
Thanks. Looking good.

**Pull request merged**
