### PR TITLE
Monokai UI theme - first pass for #25327

### PR DESCRIPTION
**Pull request by cleidigh**
will continue to add
Hope will also do Monokai dimmed

### CODE REVIEW

**Comment by bpasero** [comment]
@cleidigh awesome, let me know when you are ready to get merged 👍

**Comment by cleidigh** [comment]
@bpasero 
just added dimmed - same UI colors for now but scheme updated to json

I can probably tweak some more but maybe you want to merge for now since deadline close?
what about name scheme change?

**Comment by bpasero** [comment]
@cleidigh I can merge today in the afternoon and adopt the new color names, feel free to tweak this theme until then. We can also make changes afterwards.

**Comment by cleidigh** [comment]
@bpasero 
I am on US East Coast time so you will have to merge before I get up - assuming I crash soon ;-)

but I just realized  dimmed is messed up have to export original base will try to fix now

**Comment by cleidigh** [comment]
@bpasero 
phew - okay fixed my screwup
I'll see what I can do tomorrow but go ahead whenever you need to

**Comment by bpasero** [comment]
@cleidigh sounds good, thanks for doing this!

**Comment by cleidigh** [comment]
@bpasero 
hopefully I can do more in May !
over and out

**Comment by bpasero** [comment]
@cleidigh I merged it but commented out `focusBorder` and `foreground` because for my taste the colors did not really add up. If you feel strong about it I suggest to make an extension theme and publish ist. 

Like the rest of the colors, cool stuff! We can always tweak colors easily later.

**Comment by cleidigh** [comment]
@bpasero 
sounds good - I just like a hyperactive focus for some of the icons - not for everybody - not worth it separate theme since now everyone can do what they like !!

any other testing out help needed?

**Comment by bpasero** [comment]
No, it's all good!

**Comment by cleidigh** [comment]
@bpasero 
okay, but I've got plenty of time over the weekend to do stuff - just not clear which issues are hanging that would be of help... poke me if something makes sense

then I need a couple good projects for May

**Comment by bpasero** [comment]
Awesome, our help-wanted query is a good start for contributions: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by cleidigh** [comment]
@bpasero 
did you also drop the bluegray active and inactive Tab Colors - just updated insiders those colors are gone?

**Comment by bpasero** [comment]
@cleidigh latest color definition is this for tabs:

```
        // --- workbench: tabs
        "tab.activeBackground": "",
        "tab.inactiveBackground": "",
        "tab.activeForeground": "",
        "tab.inactiveForeground": "",
        "tab.border": "",
```

I might have missed an adoption here in your theme, maybe you can point me to the colors.

**Comment by cleidigh** [comment]
@bpasero 
yes I think all the namespace differences between setting hints, developer export of json, and system code
probably got something crossed. I will double check my local branch/settings and post any differences to use you here...

**Comment by bpasero** [comment]
@cleidigh ok good, we still have time to fix themes. I wanted to make a pass over them tomorrow.

**Comment by cleidigh** [comment]
@bpasero 
it's actually a bunch more colors dropped to default - was definitely conflicts between the three naming points
it is taking me a while to go through each one especially since some names changed just last night

sorry to bother you but there was one color I really wanted to change for contrast, could not identify: 
- foreground font color of assigned key bindings from F1 command palette dropdown

**Comment by bpasero** [comment]
@cleidigh sorry, I was quite sure I adopted all colors when I made the changes today, let me know which ones in particular and I can add them back.

I think you are referring to the color `pickerGroup.foreground`

**Comment by cleidigh** [comment]
@bpasero 
it wasn't your fault it was just how there were several locations with changing names as I was working on it
nature of the beast - I'm going to fix and add a few more colors I wanted such as above
will post as complete with new names as PR so you don't have to cherry pick

**Pull request merged**
