### PR TITLE
Initial import of code-tunnel code

### PR DESCRIPTION
**Pull request by connor4312**
This imports the code from the CLI dir in https://github.com/microsoft/vscode-cli into `src/cli` verbatim. It does not do any further integration or updates (though more will be coming today) to avoid having to review anything on top of this decently large PR.

Music for today: https://www.youtube.com/watch?v=LDU_Txk06tM

### CODE REVIEW

**Comment by jonathanpv** [comment]
:)

**Comment by jeanp413** [comment]
Really cool :tada:

**Comment by connor4312** [comment]
@joaomoreno thanks, fixed that! Also added tweaks to the precommit hygenie hook to ignore excluded files...

**Review by roblourens — APPROVED** [review]

**Comment by joaomoreno** [comment]
@connor4312, @roblourens IMO this still had some issues:

- All indentation is using spaces. We are notorious for using tabs, [it's our very first workspace setting](https://github.com/microsoft/vscode/blob/6d7beb43a0a3de03fe2b1ee53899416fac36154c/.vscode/settings.json#L2).
- Where's the CI counterpart that makes sure this gets (1) built and (2) tested?
- Could some of this 12k LoC code simply be extracted into crates? For example, the `tunnels` folder.
- I'm seeing this on my `Rust Analyzer Language Server` output, very likely due to line endings?

```
[ERROR rust_analyzer::lsp_utils] failed to run build scripts

error: failed to run custom build command for `code-cli v0.1.0 (C:\Users\jomo\Work\vscode\cli)`

Caused by:
  process didn't exit successfully: `c:\Users\jomo\Work\vscode\cli\target\debug\build\code-cli-2c1500dd85926b7e\build-script-build` (exit code: 1)
  --- stderr
  File missing copyright header: c:\Users\jomo\Work\vscode\cli\src\auth.rs
  File missing copyright header: c:\Users\jomo\Work\vscode\cli\src\commands.rs
  File missing copyright header: c:\Users\jomo\Work\vscode\cli\src\constants.rs
  File missing copyright header: c:\Users\jomo\Work\vscode\cli\src\desktop.rs
...
```

**Comment by connor4312** [comment]
Thanks, I will make followup PR(s) to address this

- I didn't think this was configurable with rustfmt, but apparently it is. Will do it.
- I have another branch that has CI builds, but I wanted to keep the level of "overwhelming" on this PR to the minimum
- Maybe... a lot of it depends also on "common" core in the CLI. I think as we add more Rust commands and get closer to the [rule of three](https://blog.codinghorror.com/the-delusion-of-reuse/), we might get a better sense of what, if anything, could be split off into separate crates.
- I ran into that and fixed it already in the branch with the builds 🙂

**Pull request merged**
