### PR TITLE
Replaced all old style imports to ES6

### PR DESCRIPTION
**Pull request by malekpour**
I changed all AMD and CommonJS imports to ES6 style. This paves switching from amd style modules to ES6 in the future.

All files in `src/vs/**/*.ts` and `extensions/**/*.ts` are searched and replaced. JavaScript output is ~~almost~~ identical.

``` ts
import x = require('module') => import x from 'module'
```

### CODE REVIEW

**Comment by isidorn** [comment]
We've discussed this in the team and decided to close it since we don't have guidelines for import statements so each developer has his style of importing and this might force an unwanted style somewhere since the PR touches a lot of different code areas.

**Comment by malekpour** [comment]
Although the `srccode

**Comment by malekpour** [comment]
Although the `src` structure is very well maintained, imports has been messed up. Currently the code locked to `amd`, but I was able to build the whole project using es2015 module kind using this PR.
We all know that `amd` was a hack like temporary solution and will be deprecated.
Regardless of what happens to this PR, having a guideline for imports as really important.

**Comment by egamma** [comment]
> ...Currently the code locked to amd

Since the code is all in TS we can easily switch to another module system and we have done this in the past.

**Comment by malekpour** [comment]
I found so many useful vscode base and common classes to use in my projects.

Tried to compile using ES6 module type (to provide to webpack & babel). Here is what TS complains about require style module imports (thousands of lines).
`error TS1202: Import assignment cannot be used when targeting ECMAScript 6 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.`

PR compiles with no issues to any TS module type and the most important thing is that when module type is `amd` output is %100 identical.

**Comment by egamma** [comment]
>Tried to compile using ES6 module type 

I'm really sorry but this is not a scenario that is currently high on our backlog. We will not get to investigate into using ES6 module types in the next couple of iterations.

**Pull request closed without merging**
