### PR TITLE
editors - fix mergeAllGroups (#118268)

### LINKED ISSUE #118268: Command "View: Join all editor groups" not working after update
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Create multiple editor groups
2. Open Command Pallette
3. type "View: Join all editor groups"
4. Hit enter 

I expect that the editors groups would be joined into a single editor group. But nothing happens.

If I use an alternative command "View: Join editor group with Next Group" it works as expected, joining the current editor with the next group.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #118268

### CODE REVIEW

**Comment by isidorn** [comment]
Code change looks good and I have verified this indeed fixes the issue -> approved.

**Review by isidorn — APPROVED** [review]

**Comment by janosh** [comment]
Just curious: Would it make sense to add a test for this?

**Comment by bpasero** [comment]
Yes, feel free to add one via PR.

**Comment by janosh** [comment]
Not sure where to put it...

**Comment by bpasero** [comment]
@janosh this made me actually move the method into the `IEditorGroupsService` and write a test: https://github.com/microsoft/vscode/commit/1bb87db91d3c1f1427392e80be47c37d0602b374

**Comment by janosh** [comment]
@bpasero Thanks a lot!

**Pull request merged**
