### PR TITLE
Sort extensions by install count rather than alphabetically. 

### PR DESCRIPTION
**Pull request by waderyan**
It is easy to game the current system for extensions. This PR should solve that by sorting extensions based on install count. 

There was some concern about adding the "install count" filter to the API. Here is the profiling using a python script and [cProfile](https://docs.python.org/2/library/profile.html#module-cProfile). 

| Test Run | No Install Count | Retrieving Install Count |
| --- | --- | --- |
| 1 | 2.212 | 1.792 |
| 2 | 1.792 | 2.193 |
| 3 | 1.805 | 1.798 |
| 4 | 1.755 | 1.856 |
| 5 | 1.708 | 1.874 |
| Mean | 1.854 | 1.903 |

As you can see there is a slight slow down. Seems trivial to me though. 

Feedback on the UI is appreciated. 

You'll notice I made a trade off in the UI to remove "days ago" in favor of install count. I rearranged install count with version. I played around with adding "installs" next to the number, but decided against it only so as not to clutter the UI. 

screen shot 2016-01-15 at 3 07 30 pm

Here is the old UI for reference. 

screen shot 2016-01-15 at 3 44 15 pm

### CODE REVIEW

**Comment by joaomoreno** [comment]
Pimped up the UI. Also did a few extra fixes as per commit messages.

image

**Comment by waderyan** [comment]
Excellent! This looks great.

**Comment by gregvanl** [comment]
Very cool to fix the ordering and I like the download image.  However I prefer having the version number right after the extension name.  How about we move the version number back to the left and put the download count and image below the author on the right.  The download could be hidden when the extension has focus and the README and download button are visible.

**Comment by waderyan** [comment]
Those are good suggestions. It does make sense to have the version number next to the product name.

**Comment by joaomoreno** [comment]
@gregvanl Can you file an issue for milestone January so I have this under my radar?

**Pull request merged**
