### PR TITLE
Add high contrast light theme on monaco editor

### LINKED ISSUE #3085: [Feature Request] Support light high contrast theme
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Monaco editor currently only support a black high contrast theme even tho the default theme is a light theme.

### PR DESCRIPTION
**Pull request by CGNonofr**
This PR fixes https://github.com/microsoft/monaco-editor/issues/3085

### CODE REVIEW

**Comment by aeschli** [comment]
Looks good!

**Comment by CGNonofr** [comment]
> Looks good!

Is there something I'm expected to do to get this PR merged?

**Review by aeschli — APPROVED** [review]

**Comment by Oceanside22** [comment]
commits @ronerony33

**Review by alexdima — APPROVED** [review]

**Comment by aeschli** [comment]
'Hygiene and Layering ' is not completing. Any idea @lszomoru ?

**Comment by alexdima** [comment]
The branch is a bit old and doesn't contain the latest CI build definition. `main` needs to be merged into it.

**Comment by alexdima** [comment]
I've ported the changes to a new PR at https://github.com/microsoft/vscode/pull/149165

**Pull request closed without merging**
