### PR TITLE
Use light icons for high contrast light theme in treeview

### LINKED ISSUE #175923: Tree view uses inverse icons on High contrast light theme.
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Use any extension that uses tree view 
2. Dark icons are used on high contrast light theme making them invisible.

image
image

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #175923 

Screenshot:
image

Before:
image

### CODE REVIEW

**Comment by daviddossett** [comment]
@alexr00 could you take a look at this? Figured you would have good familiarity with the treeview bits.

**Comment by aasimkhan30** [comment]
@alexr00 , did you get time to review the PR?

**Comment by alexr00** [comment]
@aasimkhan30 I had a question for @daviddossett here: https://github.com/microsoft/vscode/issues/175923#issuecomment-1460025320

I'm not sure that using the "opposite" icon is the right choice and wanted to confirm.

**Comment by aasimkhan30** [comment]
@alexr00, I agree. There should be a provision in the vscode api to provide icons for both HC light and HC dark. Currently, the both hc dark uses dark icons. This PR makes hc light use light icons to make them look more visible.

**Comment by aasimkhan30** [comment]
Closing this PR for now.

**Pull request closed without merging**
