### PR TITLE
Disable git pager

### LINKED ISSUE #94988: Git output with user defined pager
- VSCode Version: 1.44.0
- OS Version: Windows 10 / 1909

### The issue
Git allows user to set up a custom pager app. See [`core.pager`](https://www.git-scm.com/docs/git-config#Documentation/git-config.txt-corepager) option in git configuration.
And this can ruin VS Code communication with git. Commands such as `git show`/`git diff`/etc., which are uses pager, can truncate output or provide invalid output.

### How to fix it
VS Code just need to pass [`--no-pager`](https://www.git-scm.com/docs/git/2.26.0#Documentation/git.txt---no-pager) arg when calling git. To always receive the raw output.
For example here:
https://github.com/HanabishiRecca/vscode/commit/a13569c2aa886c831fdcd8b13cf4ea3ccc3d475a

### PR DESCRIPTION
**Pull request by HanabishiRecca**
This PR fixes #94988
This is just an example, not the actual fix.

### CODE REVIEW

**Comment by joaomoreno** [comment]
> This is just an example, not the actual fix.

Why? It would be great if you could provide an actual fix.

**Comment by HanabishiRecca** [comment]
@joaomoreno, I don't have possibility to build VS Code now.
I've tested this only in a cheaty way - by injecting fix directly in the release.

изображение

**Comment by HanabishiRecca** [comment]
But if it passed all checks, maybe can be used? If you consider this fix as acceptable.

**Comment by avdg** [comment]
Maybe possible to use env variable `GIT_PAGER` instead? Other option is to use git config

**Pull request closed without merging**
