### PR TITLE
Load folder settings when workspace uses a new FileSystemProvider (fix #182309)

### LINKED ISSUE #182309: Folder settings not initially respected when folder added to workspace requires a FileSystemProvider extension to be activated
Does this issue occur when all extensions are disabled?: not applicable

- VS Code Version: 1.79.0-insider
- OS Version: Windows 11 x64

Steps to Reproduce:

1. Have an extension that implements a FileSystemProvider and serves a `/.vscode/settings.json` file containing a setting.
2. Create a workspace that uses this FSP.
3. Observe that the setting has no effect until the workspace is reloaded.

I will prepare a branch of fsprovider-sample to demonstrate the issue.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #182309.

To verify, check that the repro on the issue now works correctly.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@sandy081 any chance you could look at this ahead of endgame?

**Comment by gjsjohnmurray** [comment]
> When cache is used, we resolve the folder configuration later and emit configuration change event if there is a change. It seems in this case, configuration change event is not getting triggered. Can you please check if this is true?

@sandy081 the problem is that cache wasn't even being used in this situation, regardless of whether or not the folder's uri depended on a FSP that wasn't yet available, because `this.initialized` had already been set `true`.

I have reverted my original change and made a different one.

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for the fix. Even though the fix works, I think it is not the right fix. Because, we would like to use cache only when workspace is not initialised. In this case, it is getting re-initialised with different workspace and therefore we have to use cache. This mean, `initialized` flag has to be reset. I prepared another fix and created the PR - https://github.com/microsoft/vscode/pull/183925 - Closing this PR in favour of that. Again very much appreciated for looking into this.

**Comment by gjsjohnmurray** [comment]
Thanks @sandy081. Happy to have helped get the correct fix done.

**Pull request closed without merging**
