### PR TITLE
Unset ZDOTDIR before standard scripts run and add VSCODE_SHELL_INTEGRATION

### LINKED ISSUE #145582: Add `VSCODE_SHELL_INTEGRATION` variable
> A special variable that signifies that VSCode is attempting to enable shell integration. For example, VSCODE_SHELL_INTEGRATION=1. It has to be set at the very beginning so that user rc files can see it.

_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

### LINKED ISSUE #145583: Show message in the terminal when shell integration is disabled by the shell
Pertains to the feedback
_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

### LINKED ISSUE #145587: zsh config doesn't initialize correctly with shell integration enabled
Turned on shell integration again, and my zsh configuration still isn't loading correctly, so I dug into it. I have these lines in my .zshrc which come from Prezto:

```
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  echo init
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
```

With shell integration disabled, $ZDOTDIR is not defined, and it enters the block. With it enabled, $ZDOTDIR is `/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-zsh` so my config isn't sourced

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #145587
Fixes https://github.com/microsoft/vscode/issues/145583
Fixes https://github.com/microsoft/vscode/issues/145582

### CODE REVIEW

**Review by meganrogge — APPROVED** [review]

**Comment by romkatv** [comment]
Would it be possible to suppress the message? I don't think it's worth keeping it even with an option. In general, shells don't print things during initialization.

**Comment by Tyriar** [comment]
@romkatv I understand your perspective, but then shell integration silently fails and that would result in "bugs" getting reported to us forever. We could have the line be a link with a hover that includes some documentation explaining it?

**Comment by romkatv** [comment]
My goal is for shell integration in vscode to work with powerlevel10k. If it worked out of the box, I would be more than happy. Unfortunately, it doesn't work and I don't think it's feasible to fix that from within vscode. Here are some of the features of powerlevel10k that pose a challenge when it comes to shell integration:

- [Instant prompt](https://github.com/romkatv/powerlevel10k#instant-prompt)
- [Show on command](https://github.com/romkatv/powerlevel10k#show-on-command)
- [Transient prompt](https://github.com/romkatv/powerlevel10k#transient-prompt)
- [Current directory that just works](https://github.com/romkatv/powerlevel10k#current-directory-that-just-works)

Powerlevel10k support shell integration with terminals that respect OSC 133 and/or OSC 7. I can implement support for the protocol used by vscode, too (although I would very much prefer if vscode used OSC 133; FWIW, I don't see any feasibly extensions to that protocol that could give any additional functionality to zsh users). The logic I'm envisioning is as follows.

When powerlevel10k sees `VSCODE_SHELL_INTEGRATION=1` during initialization, it unsets this variable and enables shell integration according to the protocol used by vscode.

This will work fine but unfortunately vscode will print a misleading message saying that shell integration is disabled. I see two ways how I can work around this issues. If instant prompt is enabled, stdout is already redirected to a file, so I can find this message and remove it. If intant prompt is not enabled, I can replace `echo` with a function that will special-case the message and do avoid printing it. Both of these are ugly hacks.

Would it be possible to not print the message?

**Comment by Tyriar** [comment]
> When powerlevel10k sees VSCODE_SHELL_INTEGRATION=1 during initialization, it unsets this variable and enables shell integration according to the protocol used by vscode.

Oh I see, I thought you would be disabling it outright. That sounds great, in that case we'll exit the script without warning and instead warn to the devtools console which is only visible if the user is investigating a problem.

If you wanted to adopt the sequences as described below, the chances they will change is pretty low.

https://github.com/microsoft/vscode/blob/97d358236cd332ea6d2308c32dd44d39fc07a9b5/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L52-L116

Comments on some of them:

- `CommandLine = 'E'` - This is currently only used for pwsh and the behavior when used on non-Windows is somewhat undefined right now. We'll support this on Linux/macOS if we need it for more reliable command extraction
- `Property = 'P'` - [Here are the current properties](https://github.com/microsoft/vscode/blob/97d358236cd332ea6d2308c32dd44d39fc07a9b5/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L189-L205), you'll want to send OSC 633 `;Cwd=/path/in/this/format` ST on each prompt. If you want sending it only when it changes should be sufficient. It's not necessary to send `IsWindows` as we assume non-Windows hosts by default.

**Comment by romkatv** [comment]
https://github.com/microsoft/vscode/blob/97d358236cd332ea6d2308c32dd44d39fc07a9b5/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L52-L116
> 
> Comments on some of them:
> 
> * `CommandLine = 'E'` - This is currently only used for pwsh and the behavior when used on non-Windows is somewhat undefined right now. We'll support this on Linux/macOS if we need it for more reliable command extraction

I'm positive that it's impossible to extract the command line from Zsh Line Editor (zle) in general. I hope you can support this on Linux.

> * `Property = 'P'` - [Here are the current properties](https://github.com/microsoft/vscode/blob/97d358236cd332ea6d2308c32dd44d39fc07a9b5/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L189-L205), you'll want to send OSC 633 `;Cwd=/path/in/this/format` ST on each prompt. If you want sending it only when it changes should be sufficient.

How should I escape `\007` in cwd? (I see that your code doesn't escape it; you probably want to fix that.)

What about SSH? If I send cwd from the remote host, will vscode mistakenly treat it as if this was cwd from the local host?

Other terminals solve this problem by requiring hostname to be supplied together with cwd.

**Comment by Tyriar** [comment]
> I'm positive that it's impossible to extract the command line from Zsh Line Editor (zle) in general. I hope you can support this on Linux.

On pwsh we use `Get-History` to do this, `history` in zsh seems to give the full entry with `\n` replacing new lines. You can only get this once the command has finished running but that's a fine compromise if it's very accurate.

> How should I escape \007 in cwd? (I see that your code doesn't escape it; you probably want to fix that.)

Good call, this is how we escape the command line sequence:

https://github.com/microsoft/vscode/blob/97d358236cd332ea6d2308c32dd44d39fc07a9b5/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L164-L166

Following this I guess we can do <ST> for now to align with that. This was a temporary/good enough solution to get things up and running but if you have a more robust idea for escaping we can make those improvements soon.

> What about SSH? If I send cwd from the remote host, will vscode mistakenly treat it as if this was cwd from the local host?

Well subshell support isn't there currently and how to handle that was going to get figured out there. We assume all terminals are "local" to the window currently (which may be remote depending on the type of window). For subshells my thinking was to add a unique shell id sequence to every prompt so we are able to detect when each shell starts and begins, including ones on the same hostname.

We also have a special way of defining URIs for remote connected windows which we may use to be able to identify files that are available in the workspace, eg. `vscode-remote://wsl+ubuntu/home/daniel/`

Currently the cwd feeds into the tab's title as well as resolving links relative to it, if you send cwd for an SSH the folder in a tab should show up like this as I don't think it's validated against the FS:

image

The only other side effect is that links clicked in the terminal will try resolve which shouldn't cause much harm.

So if you're able to hook into ssh sessions and integrate with them you can either do nothing until we get https://github.com/microsoft/vscode/issues/144358 done or send them as normal paths.

**Comment by Tyriar** [comment]
> I understand that it makes your life easier in the short term. Users of your software have different incentives though.

How good of a solution it is depends on how successful we are in making our script the defacto script where all you need to do to get shell integration is to make sure the script runs. powerlevel10k certainly poses some special challenges because of its complexity though. As I mentioned before we're trying to get this enabled by default eventually so a huge amount of users who have not yet configured their shell get to experience the feature with zero config, even if their shell has zero customizations.

We also want more capabilities than the existing finalterm/iterm2 shell integration sequences allow, this is essential to get it working on Windows as we're in brand new territory there having rich pwsh integration on Windows and we want to keep our options open. I can imagine we will be adding more sequences over time to add more capabilities. If we accept existing shell integration used by other terminals that will inevitably lead to flaky and inconsistent results. For example one of the end goals of shell integration is to get native autocomplete and we may need special sequences to make that feature really shine.

We also have the option if it would help to add some special handling to our script for any shell or powerlevel10k if that's useful.

> The user doesn't see or deal with the tree.

Yeah you might have convinced me, bit busy to think it through thoroughly atm. I'll make some notes on https://github.com/microsoft/vscode/issues/144358

**Comment by romkatv** [comment]
> How good of a solution it is depends on how successful we are

I'll buy that. If your new shell integration protocol allows you to implement new cool features, then it's justified. I don't know which features you could implement that cannot be implemented on top of OSC 133 (plus potentially an extension to send the command line) but I'll be happy to see them. The current version of zsh integration in vscode doesn't have anything that cannot be done with OSC 133 and OSC 7 though.

> As I mentioned before we're trying to get this enabled by default eventually so a huge amount of users who have not yet configured their shell get to experience the feature with zero config

Zsh users on Windows don't run with empty zshrc. They all have user rc files. It's really easy for them to clone a git repo and source a file from it. They all know how to do it. Having the terminal injecting code into shell is something most users never expect to happen though. Given that shell injection from the terminal cannot be made to work reliably, you'll want to provide a git repo with a standalone file at some point. Once you do that, consider removing shell injection altogether. Instead, you can add a button that modifies `~/.zshrc`. This would be in line with how zsh ecosystem works.

**Comment by Tyriar** [comment]
> Once you do that, consider removing shell injection altogether. Instead, you can add a button that modifies ~/.zshrc. This would be in line with how zsh ecosystem works.

Our approach is somewhat atypical as most terminals are opt-in with an install step. If I remember right kitty auto installs it and some of the feedback they got was that it's intrusive, which I agree with, so we were trying to be as unintrusive as possible. As soon as you have a manual step the amount of users that would engage with the feature would drop significantly. This is an important part of why we too this approach, we want it to _just work_ for the majority of users and fail unobtrusively for more advanced cases. Imagine connecting VS Code to a container or a new machine, opening a terminal and shell integration/autocomplete just works with zero config, that's the vision.

In the off chance that shell integration fails to inject before the shell starts, or the shell disables it, or something else goes wrong, we want to fail early and continue, then the user has the option to disable injection all together and go with the manual setup route we'll provide https://github.com/microsoft/vscode-docs/issues/5219

---

This discussion is all super valuable so thank you so much for that! It was probably obvious that I'm not that familiar with zsh, I'm mostly a bash and pwsh user these days. The more we chat, the more I think that it's probably not ready for you to try to integrate since things are still in flux. The best approach to make sure you don't waste time is to just force disable shell integration with our new environment variable and then revisit in a few months?

**Comment by romkatv** [comment]
>  If I remember right kitty auto installs it and some of the feedback they got was that it's intrusive

Kitty is the only other terminal that does what vscode does -- shell injection via `ZDOTDIR` override. And yes, it's intrusive. As a member of zsh community I cannot stress enough how negatively this approach is perceived. It looks as abuse of power by the terminal and a violation of the established contract. It's not the job of the terminal to inject code into shell, especially when the same result can be accomplished via the existing means.

> This is an important part of why we too this approach, we want it to just work for the majority of users

This is a noble goal but I doubt it's achievable. If integration works only until the user restarts shell with `exec zsh`, users won't be able to rely on it being there and won't establish habits that utilize shell integration. If I'm to start using a shortcut that copies the output of the last command into clipboard or opens it in `$PAGER`, I'll want that shortcut to actually work rather than be best effort.

I think I've made my opinion clear. It's your product, so your choice of course.

> The best approach to make sure you don't waste time is to just force disable shell integration with our new environment variable and then revisit in a few months?

That sounds good to me. Feel free to @-mention me on anything related to integration with zsh.

**Pull request merged**
