### PR TITLE
Create My microsoft

### PR DESCRIPTION
**Pull request by ReyBan78**
This PR fixes #

### CODE REVIEW

**Review by hello-smile6 — CHANGES_REQUESTED** [review]
What's the point of this? What issue does it close?

**Comment by ReyBan78** [comment]
> What's the point of this? What issue does it close?

Thanks team

**Comment by hello-smile6** [comment]
> > What's the point of this? What issue does it close?
> 
> Thanks team

What?

**Comment by chrisdias** [comment]
It looks like you are new to GitHub, welcome!  Here's a good place to start if you want to contribute: https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Pull request closed without merging**
