### PR TITLE
Open in background on vscode.[open|openWith|diff]

### LINKED ISSUE #96964: Allow opening editors in the background via extension api (commands)
Currently extensions can't control whether or not an editor is opened in the background (not active) or not. For example, in both the built-in Git extension and GitLens, we have commands that open multiple files or diffs. Today VS Code will open a document for each file and then show an editor for each, which will then become the active editor. This is costly, slow (relatively), and causes the UI to visibly jump around as the active editor get switched repeatedly.

We already have a way to support this functionality in core and just need to expose it for the `vscode.open`, `vscode.openWith`, and `vscode.diff` commands. All of those command already take a `TextDocumentShowOptions`, so I would propose a new `TextEditorOpenOptions` interface which is identical to `TextDocumentShowOptions` with the additional `background` flag:

```ts
export interface TextEditorOpenOptions {
	/**
	 * An optional view column in which the [editor](#TextEditor) should be shown.
	 * The default is the [active](#ViewColumn.Active), other values are adjusted to
	 * be `Min(column, columnCount + 1)`, the [active](#ViewColumn.Active)-column is
	 * not adjusted. Use [`ViewColumn.Beside`](#ViewColumn.Beside) to open the
	 * editor to the side of the currently active one.
	 */
	viewColumn?: ViewColumn;

	/**
	 * An optional flag that when `true` will stop the [editor](#TextEditor) from taking focus.
	 */
	preserveFocus?: boolean;

	/**
	 * An optional flag that controls if an [editor](#TextEditor)-tab will be replaced
	 * with the next editor or if it will be kept.
	 */
	preview?: boolean;

	/**
	 * An optional selection to apply for the document in the [editor](#TextEditor).
	 */
	selection?: Range;

	/**
	 * An optional flag that controls if an [editor](#TextEditor)-tab will be opened in the background.
	 */
	background?: boolean
}
```

I'm proposing a new interface because `TextDocumentShowOptions` is also shared with the `window.showTextDocument` function and since it requires a `TextDocument` and returns a `TextEditor` it isn't a good fit for this new flag (because it seems silly to have to open a text document to load in the background and also there won't be a `TextEditor` created so there isn't one to return).

### PR DESCRIPTION
**Pull request by eamodio**
This PR fixes #96964

### CODE REVIEW

**Comment by jrieken** [comment]
Adding @bpasero and @joaomoreno who own these commands. Still, I was assuming this becomes "real" API when tackling the "open editor" api. Is there an urgent rush for this now?

**Comment by eamodio** [comment]
Nothing urgent -- just felt like very low hanging fruit that could help the overhead and experience in the short term.

**Comment by joaomoreno** [comment]
I believe it's @bpasero only.

**Review by bpasero — CHANGES_REQUESTED** [review]
Can you clarify why we cannot simply add more properties to the existing `TextDocumentShowOptions` but have to introduce a new `TextEditorOpenOptions` that does not even inherit from `TextDocumentShowOptions`?

**Pull request merged**
