### PR TITLE
Git: Separate the commit length limit of subject line and description…

### PR DESCRIPTION
**Pull request by mptap**
… lines #60300

### CODE REVIEW

**Comment by mptap** [comment]
@mark-wiemer Done, thanks!

**Comment by joaomoreno** [comment]
It would be great if we didn't break existing users which already have configured `git.inputValidationLength`.

**Comment by mptap** [comment]
@joaomoreno Updated

**Comment by dylmye** [comment]
Any update on this @joaomoreno ? :)

**Review by sharabiania — APPROVED** [review]

**Review by medin-n — APPROVED** [review]

**Comment by joaomoreno** [comment]
- Removed `bodyValidationLength` which wasn't doing anything
- Renamed to `inputValidationSubjectLength`
- Set the default to `null`, which inherits the value of `inputValidationLength`

Thanks! :beers:

**Pull request merged**
