### PR TITLE
git.checkout: Create new branch using the input text in the checkout quick pick

### LINKED ISSUE #60895: Suggestion: Create git branch action in checkout dropdown after typing in new branch name
When you open the git checkout dropdown and search for a branch that doesn't exist, there is a "Create new branch" and then you have to type the name in again.

I propose an action in the dropdown that if a branch doesn't exist so if I search for "feature/my-new-branch", there will be an item that has the following action:

```
Create "feature/my-new-branch" branch.
```

and when you select it, it would generate the new branch and checkout into it.

### PR DESCRIPTION
**Pull request by segevfiner**
### TODO
- [ ] We should probably make the "+ Create new branch" item label dynamic to show that it's going to create a new branch immediately using the entered value. I can listen for `onDidChangeValue`, and update a property on the `CreateBranchItem`, but I'm not sure how to request the `QuickPick` to query the label again. **EDIT:** I implemented this locally by simply reassigning `QuickPick.items`, but before I push this to the PR... I think this might have an unintended side effect since the label will always include the typed value in the quick pick. This might cause the create branch entry to get selected at a higher priority.
- [ ] When the branch name fails `git.branchValidationRegex`, the current code in this PR will open the create new branch input box with the inputted branch name, but it will only show the validation error once the user edits/hits enter on the newly opened input box. `validateInput` is not called for the initial value.
- [ ] The sample [vscode-extension-samples/quickinput-sample/src/quickOpen.ts](https://github.com/Microsoft/vscode-extension-samples/blob/5078e6bd3d4874ca5aa7ddf94bc3028c1974d35d/quickinput-sample/src/quickOpen.ts) seems to call dispose on the event registrations. But since we already `dispose` of the `QuickPick` on `onDidHide` is that really necessary?

Fixes #60895

@ParkourKarthik There is a bug in `createCommand` that made your PR not work. Fixed in this PR.

### CODE REVIEW

**Comment by ParkourKarthik** [comment]
@segevfiner Thanks mate!

**Comment by segevfiner** [comment]
Here is the patch which I haven't pushed to this PR to fix the first TODO (see the PR description):
```diff
diff --git a/extensions/git/src/commands.ts b/extensions/git/src/commands.ts
index 538b2bf9c1..c756089dc0 100755
--- a/extensions/git/src/commands.ts
+++ b/extensions/git/src/commands.ts
@@ -27,7 +27,7 @@ class CheckoutItem implements QuickPickItem {
 
 	constructor(protected ref: Ref) { }
 
-	async run(repository: Repository, _name: string): Promise<void> {
+	async run(repository: Repository): Promise<void> {
 		const ref = this.ref.name;
 
 		if (!ref) {
@@ -51,7 +51,7 @@ class CheckoutRemoteHeadItem extends CheckoutItem {
 		return localize('remote branch at', "Remote branch at {0}", this.shortCommit);
 	}
 
-	async run(repository: Repository, _name: string): Promise<void> {
+	async run(repository: Repository): Promise<void> {
 		if (!this.ref.name) {
 			return;
 		}
@@ -91,15 +91,23 @@ class MergeItem implements QuickPickItem {
 
 class CreateBranchItem implements QuickPickItem {
 
+	public branchName?: string;
+
 	constructor(private cc: CommandCenter) { }
 
-	get label(): string { return localize('create branch', '$(plus) Create new branch'); }
+	get label(): string {
+		if (this.branchName) {
+			return localize('create named branch', "$(plus) Create '{0}' branch", this.branchName);
+		} else {
+			return localize('create branch', '$(plus) Create new branch');
+		}
+	}
 	get description(): string { return ''; }
 
 	get alwaysShow(): boolean { return true; }
 
-	async run(repository: Repository, name: string): Promise<void> {
-		await this.cc.branch(repository, name);
+	async run(repository: Repository): Promise<void> {
+		await this.cc.branch(repository, this.branchName);
 	}
 }
 
@@ -1405,8 +1413,13 @@ export class CommandCenter {
 		quickPick.placeholder = localize('select a ref to checkout', 'Select a ref to checkout');
 
 		return new Promise<boolean>(resolve => {
+			quickPick.onDidChangeValue(value => {
+				createBranch.branchName = value;
+				// Trigger an update of the items
+				quickPick.items = quickPick.items;
+			});
 			quickPick.onDidAccept(() => {
-				quickPick.selectedItems[0].run(repository, quickPick.value);
+				quickPick.selectedItems[0].run(repository);
 				resolve(true);
 				quickPick.hide();
 			});
```

**Comment by segevfiner** [comment]
@joaomoreno I think you implemented this yourself. If so, feel free to close this one.

**Comment by joaomoreno** [comment]
@segevfiner Oh... I failed to notice there were other PRs open for this issue. :man_facepalming: 

Sorry for that and thanks any way! :beers:

**Comment by segevfiner** [comment]
@joaomoreno BTW might want to take a look at the implementation here and the notes on the comment PR since I raised a few points on the details of implementing this. I haven't checked your implementation though so I don't know how it works exactly.

**Pull request closed without merging**
