### PR TITLE
Move IHoverService to `vs/editor`

### LINKED ISSUE #174957: QuickPick tooltip does not work with monaco editor
Does not seem to work with monaco editor:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.0-dev.20230221#XQAAAALvAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2oTw2fdL6lWdZifSWhc9gCAnQP7m4UuZTiIrIS9pAX04f3NkJ4AQau3w4ptki3gIWzH16T25difg-USIlgIuHWaQW4UjFBxI-jBU9CCZvEu13dcLUzxHa2RS-cZPn3SUFjJ7GMRNa5TRRLvbbknTUUPnGnxar4EkxtMcz3UWzcPw7gwPrXA2ETDLZD6pzubVK4cRDgrJ-nQDGEGSznsdtWADDS76FtsSvadmrN2k6HKqxxAJifVZ9_y18H8iBaHxJeXQIlCfrGMw4UcJLViU6ZOWTXo2r5jcGb6eBiWWzHQkbRWLgLpEeGEEX2mMNqXcX66uxk6kXUMbzHaazjocZTM48Yb0ghedAGBgg8MBo7-my6v31YX-oznM2BHhLx4xcXvZt-Er7NN6AfB4eVUFXikzJnyQkRObpprGjjsT7VGpm4nnjz7-yY8jQy3GXiKxfETPEHA8xDoP5VCuJRF9r3jrsGpDAVlLPBFDRZM17BR1t39a-I5DbygpV9e4DMS2OceRGge4dtGFH7aSJMLV7_fmZHcJDxxfKP-34NC2

_Originally posted by @hediet in https://github.com/microsoft/vscode/issues/174699#issuecomment-1438143516_

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This moves the `IHoverService` into `vs/editor` so it can work in the standalone editor.

fixes https://github.com/microsoft/vscode/issues/174957

This is broken up into 4 commits...
1. The first is the important renames
2. The second is all the misc files that needed path updates
3. The third & fourth moves the `QuickPickHoverDelegate` into platform so that it can be used in the `StandaloneQuickInputService`

In order to get this to work it involved moving the MarkdownRenderer which was originally in contrib into editor/widget... because let's be honest, it's basically a widget.

I verified this change works in both Code OSS:
image

& Monaco Editor Playground:
image

The demo was made with an additional code change that isn't in this PR. It just adds a `tooltip` to the Symbols quick pick

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
(Haven't tested this) There was not much code was shared between editor and workbench before if I remember right, does this move the editor over to more of how the workbench hover service works? Is there a concern about regressions there?

**Comment by TylerLeonhardt** [comment]
@Tyriar they are separate. There's an _editor_ hover which is tightly coupled to the editor:
https://github.com/microsoft/vscode/blob/ed220eff3fca4afd17b4714fc3e8e85e98319144/src/vs/editor/contrib/hover/browser/hover.ts#L54

this provides a "not tied to the editor" hover that can be used in other parts of the Monaco UI (like the command palette)

**Comment by Tyriar** [comment]
It's a little confusing having hover service live in editor/ then, could it not go into platform?

**Comment by TylerLeonhardt** [comment]
@Tyriar that would be very challenging with the dependence of `markdownRenderer` which uses all of this editor specific stuff:
https://github.com/microsoft/vscode/blob/ed220eff3fca4afd17b4714fc3e8e85e98319144/src/vs/editor/browser/widget/markdownRenderer/browser/markdownRenderer.ts#L13-L17

**Review by hediet — APPROVED** [review]
Thanks! And thanks for caring about the monaco-editor :)

**Pull request merged**
