### PR TITLE
Clarify the proprietary distribution in the README

### PR DESCRIPTION
**Pull request by resynth1943**
I'd like it if this README actually explained what the "traditional Microsoft license" is.

In relation to: #105978; #91036; #80291; #71638; #18083; #17996; #17994; #3321; #60

### CODE REVIEW

**Comment by resynth1943** [comment]
@chrisdias is anything wrong with this addition ...?

**Comment by chrisdias** [comment]
Hi sorry for not responding sooner. 

I'm not sure this adds anything to the readme. It restates "traditional" as "proprietary" and it is a commentary ("it is not open source") on the license, where we have a link to the license.

**Comment by resynth1943** [comment]
> It restates "traditional" as "proprietary"

Yes, it provides more information. "Traditional" does not provide any valuable information.

> it is a commentary ("it is not open source") on the license, where we have a link to the license.

Isn't it your job to simplify this for the end-user? Who would realistically read a LICENSE? All of this "VSCode is open-source" propaganda being shared by Microsoft has successfully duped people into thinking this is not a proprietary program.

It's *your* role to explain what your "traditional Microsoft license" is. One assumes VSCode would be open-source after looking at this repository. If Microsoft doesn't do more to combat that, it's deceitful and harmful to the FOSS community.

Thanks.

**Comment by joepie91** [comment]
This looks like a reasonable addition to me; currently it is indeed implied that the VS Code distribution is open-source through the general marketing and perception around it (I regularly run into people believing VS Code is open-source), and it is IMO important to clearly contrast between the proprietary VS Code distribution and the open-source codebase that it is built upon.

**Comment by resynth1943** [comment]
@joepie91 Definitely agreed.

There needs to be more accountability here. This short addition explains that VSCode is proprietary software, which is a welcome contrast to Microsoft's marketing:
- ["Open-source"](https://web.archive.org/web/20180729022429/https://code.visualstudio.com/) (*2019*)
- ["Built on open-source"](https://web.archive.org/web/20200601010316/https://code.visualstudio.com/) (*2020*)

Some honesty wouldn't go amiss, it may even garner respect from the community. Instead of misleading advertising, why don't we just be tell it like it is? "This software is a proprietary build of the [Visual Studio Code](https://github.com/microsoft/vscode) repository."

**Pull request closed without merging**
