### PR TITLE
Support some links with spaces

### LINKED ISSUE #97941: Support path links that contain spaces in the integrated terminal
- VSCode Version: 1.45.1
- OS Version: MacOS 10.15.4

Steps to Reproduce:

1. create a vscode python project in a directory with a space that contains some code that produces a failing test or stacktrace
2. hover over the paths in the stacktrace and notice that those with a space in a directory name are not rendered as links.  those without spaces are.

I have created a tiny repo that reproduces the bug: https://github.com/nielsvaneck/vscode_space_path_bug

Does this issue occur when all extensions are disabled?: *Yes*

### PR DESCRIPTION
**Pull request by Tyriar**
Supported:

- Python style links: `From "<path>", line <line>`
- Lines that only contain a path: `<path>`
- Independently styled file paths: `foo<underlined_path>bar`

Fixes #97941

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]
Would be great to have a simple unit test to ensure we don't regress here.

**Comment by Tyriar** [comment]
Was thinking that while working on these improvements. I might do a follow up but right now it's difficult to test the links that need to test the file paths.

**Comment by bromelio** [comment]
Please also include the following error line format in the fix:

`C:\[any number of subfolders]\Program.cpp(18,29) : error 149: '}' - unexpected token`

Thank you!

**Comment by Tyriar** [comment]
@bromelio what compiler is that from?

**Comment by Tyriar** [comment]
@bromelio done in https://github.com/microsoft/vscode/pull/169850
image

**Comment by Tyriar** [comment]
@bromelio done in https://github.com/microsoft/vscode/pull/169850

image

**Pull request merged**
