### PR TITLE
Add settings for changing the workbench font size and font

### LINKED ISSUE #519: Allow to change the font size and font of the workbench
At the moment, we can only change the font size / font of the editor. If we want to change the font size, we need to use a roundabout method of "zooming in / out". It would be nice if this could be adjusted through the preferences.

### PR DESCRIPTION
**Pull request by ElijahPepe**
This PR fixes #519.

This does need to be refined a bit; I did this rather hastily.

### CODE REVIEW

**Comment by ElijahPepe** [comment]
This PR adds the settings necessary for setting a font size and font family for the workbench and applies it in themeing.ts. I'm not sure if anything else is necessary like watching for changes to the settings and applies them retroactively.

**Comment by ElijahPepe** [comment]
@sbatten, any word?

**Comment by bpasero** [comment]
Same discussion starting from https://github.com/microsoft/vscode/pull/63602#issuecomment-472025321 applies here again.

**Comment by ElijahPepe** [comment]
> Same discussion starting from [#63602 (comment)](https://github.com/microsoft/vscode/pull/63602#issuecomment-472025321) applies here again.

Ah, okay, I see the issue. I will attempt to find as many instances as I can of certain pixel values being hardcoded and alter them.

**Comment by ElijahPepe** [comment]
I _think_ I got all of the hardcoded values, but I'm not entirely sure.

**Comment by Tuneabq** [comment]
👍💯✅

**Comment by ElijahPepe** [comment]
Tests should be green now.

**Comment by laurentlb** [comment]
The PR is very large. I wonder if maintainers are more likely to accept it if we split the PR:
- A first PR that does the safe refactor-only changes (pass IConfigurationService around).
- A 2nd PR that replaces the constants with the computed sizes.

If the first PR is merged and the 2nd PR is small enough, my team at Google can help test it and iterate on it.

**Comment by ElijahPepe** [comment]
I'm going to close this for now while @laurentlb and I work towards splitting this PR up and getting changes made through at a much slower and more deliberate pace.

**Comment by isidorn** [comment]
@ElijahPepe @laurentlb thanks for doing that. Please ping me on any new PRs you open.

**Pull request closed without merging**
