### PR TITLE
fix: hover link encode unnecessarily

### LINKED ISSUE #108819: Follow Link tooltip for urls in markdown files encode query string unnecessarily
Issue Type: <b>Bug</b>

- Open a new file
- **(!important)** Set file type to Markdown
- Create a markdown link with a query string name-value pair containing an equals sign ("=") like `[example](https://www.example.com?encoded=unnecessarily)`
- Hover over the url (i.e. "https://www.example.com?encoded=unnecessarily") to engage the Follow Link tooltip
- Click "Follow link" link
- Observe that the browser address bar shows an encoded equals sign ("=") in the url (i.e. "https://www.example.com/?encoded%3Dunnecessarily")

I cannot reproduce this issue with online monarch-editor (https://microsoft.github.io/monaco-editor/index.html) if that helps.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (19.88GB free)|
|Process Argv|--crash-reporter-id 482ad8b0-81a6-4635-87db-d66b654487d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.145.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15

</details>

### PR DESCRIPTION
**Pull request by chenjigeng**
This PR fixes #108819

### CODE REVIEW

**Comment by chenjigeng** [comment]
The reason for this problem is that if you pass in a URI link, it'll call the toString function to display it .And the toString function of the URI will by default encode.
https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L372

image
image

So is there a need for encode? If not, we can solve this problem by toString(true).

image

**Review by mjbvz — CHANGES_REQUESTED** [review]
Fixing this in core VS Code feels risky since it will effect all languages.

Can you try tracking down why markdown generates a command link that gets corrupted by this encoding?

**Comment by alexdima** [comment]
The current `link.url.toString()` was introduced when this feature was added in https://github.com/microsoft/vscode/commit/1c28c30760ed2f329afba38d6f523ec7199e20af by @rebornix .

@jrieken We need a bit of help here. Here we generate markdown that later on gets clicked on and reaches the opener service. What is the best way to include this link in the markdown? With `.toString()` or `.toString(true)` ?

**Comment by jrieken** [comment]
> Here we generate markdown that later on gets clicked on and reaches the opener service. What is the best way to include this link in the markdown? With .toString() or .toString(true) ?

The `URI` unfortunately has bugs that we cannot fix anymore (there are too many extensions relying on these bugs) and therefore links can be a string or URI. So, try to have a string. However, when having a URI it is safe to call `toString(true)` because it will skip all encoding except for absolutely necessary bits (like # inside the path etc). However, toString(true) might already be too late because the actual bugs in URI are in parse so it really depends on how these uris are created

**Comment by alexdima** [comment]
OK, then I will accept the PR on the hover side.

But @jrieken the markdown link provider is stuck with using `URI`. I think our `modes.ts` allows for simple strings, but the API only allows `URI` [here](https://github.com/microsoft/vscode/blob/98166ea0b190351aa7902b2d3dd9f35b7aadaeb6/src/vs/vscode.d.ts#L4098)

**Comment by alexdima** [comment]
Thank you @chenjigeng

To reproduce:
```md
[example](https://www.example.com?encoded=unnecessarily)
```

**Comment by jrieken** [comment]
> But @jrieken the markdown link provider is stuck with using URI. I think our modes.ts allows for simple strings, but the API only allows URI here

Yeah, we have https://github.com/microsoft/vscode/issues/85930 for that

**Pull request merged**
