### PR TITLE
list: allowMultipleSelection

### PR DESCRIPTION
**Pull request by isidorn**
I decided to read the option only on one place in the setSelection. Let me know if you do not like that and I can change.
I tried it with the breakpoint view and it works just fine.

### CODE REVIEW

**Comment by joaomoreno** [comment]
Ended up doing a bit of extra stuff on top. 👍

**Comment by isidorn** [comment]
@joaomoreno thanks for this, I checked how you did it and makes sense.

**Comment by Chillee** [comment]
Is it possible that this PR caused this? https://github.com/VSCodeVim/Vim/issues/2177

Our current package.json keybindings are bound like this:
```
      {
        "key": "k",
        "command": "list.focusUp",
        "when": "listFocus"
      },
      {
        "key": "o",
        "command": "list.toggleExpand",
        "when": "listFocus"
      },
```

**Comment by joaomoreno** [comment]
@Chillee That would be this: https://github.com/Microsoft/vscode/issues/39211

**Comment by Chillee** [comment]
@joaomoreno ah nice. Thanks!

**Pull request merged**
