### PR TITLE
Introduce aria role to tree and list

### LINKED ISSUE #52390: Breakpoint checkboxes have wrong role
**Environment Details:**
VSCode Version : 1.24.0
OS Version : HighSierra10.13.5

**Additional Details:**
MAS Violated: MAS 1.3.1
ScreenReader : VoiceOver

**Repro Steps:**
1. Launch VS Code while VoiceOver is ON.
2. Navigate to Activity Bar and select "View Debug " button.
3. Navigate to "All Exceptions" and "User Handled Exceptions" checkboxes in "Breakpoints" section.

**Actual:**
Screenreader reads the tick boxes as list boxes. The role of the "All Exceptions" and "User Handled Exceptions" controls is incorrect.

**Expected:**
Screenreader should read the proper role of the controls as tickboxes so that proper action can be performed by the user.

**Recommendations:**
Provide proper role to the "All Exceptions" and "User Handled Exceptions" controls as tick boxes.(checkboxes)
or,
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
The screenreader users will not be able to know the correct role of the controls to perform appropriate actions on the controls present on the screen.

**MAS Reference:**
MAS 1.3.1 - https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachment For Reference:**
[A11y_VSCode_ViewDebug_VoiceOver_TickboxAsListBox.pptx](https://github.com/Microsoft/vscode/files/2118031/A11y_VSCode_ViewDebug_VoiceOver_TickboxAsListBox.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by isidorn**
This PR introduces an option for the list and the tree such that the clients can customize the aria role of tree items.
This PR also adopts this in the breakpoints view.

fixes #52390

### CODE REVIEW

**Comment by cleidigh** [comment]
@isidorn 
cc: @roblourens 
Looks good for assigning item roles within List or tree .

What about the ability to pass aria role for the tree itself?  For the new settings editor , the elements are organized as a form and we had override the attribute on the tree to change from tree => form.

Any objection to me adding an ariaRole option item for the tree widget?

**Comment by roblourens** [comment]
Sounds ok to me, @isidorn?

**Comment by isidorn** [comment]
@cleidigh yes that sounds like a great idea, please provide a PR and ping me and @joaomoreno on it. Thanks

**Comment by isidorn** [comment]
@joaomoreno I was not properly assigning `role` to each list item, instead I was only assigning it to the top container. 
Thus I have pushed https://github.com/Microsoft/vscode/commit/fd189286ae049d54d238c5aeb0b77032459fe17b

What I might not like is that currently the ariaLabel is per list and ariaRole is for each item. So maybe to rename the `ariaRole` to `ariaItemRole`. What do you think?

**Comment by joaomoreno** [comment]
Yes, I would definitely rename it.

**Comment by isidorn** [comment]
After investigation and testing I had to revert the PR. Reason being that the NVDA on mac only properly reads out things for the combination of `tree` / `treeitem` roles. For `list` / `listitem` roles and for checkbox it is silent all the time.
Using checkbox on windows also keeps nvda silent. 
Thus it seems it does not make sense to customize these roles since it breaks screen reader behavior.

**Comment by isidorn** [comment]
Due to my above explanation it does not seem like a good idea to do additional PRs in this area @cleidigh 
Hope that makes sense

**Pull request merged**
