### PR TITLE
Link tsconfig compiler option names to reference pages

### PR DESCRIPTION
**Pull request by weswigham**
This makes the names of compiler options in `tsconfig` files able to be `CTRL` or `CMD`-clicked on to go directly to their associated documentation on the `typescriptlang.org` website.

cc @orta who suggested the change

### CODE REVIEW

**Comment by mjbvz** [comment]
Not sure that document links are the best fit for this feature. Could these links be added to the JSON schema documentation for jsconfigs and tsconfigs instead? That way they would show up on hover and in IntelliSense

**Comment by weswigham** [comment]
@orta ?

**Comment by orta** [comment]
Yeah, I was planning on improving those for 4.1/4.2 - so we could move this there instead 👍🏻

**Comment by mjbvz** [comment]
Thanks. I think that better matches how our other json intellisense works. Adding links in the schema should also help users who are writing tsconfig

Closing this for now but let me know if you think any work is required on the VS Code side to support this

**Pull request closed without merging**
