### PR TITLE
[WIP] Inline all decorations

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
https://github.com/Microsoft/vscode/issues/19749

CC: @jrieken

### CODE REVIEW

**Comment by jrieken** [comment]
Yeah, this how I said not to do it ;-) There is basically two issue with it and one makes not being able to reuse the goto error controller/widget. So problem 1 is that the widget reveals the line, therefore always scrolling to the last error which is unwanted and problem 2 is that errors that are on the same line are not sharing the widget.

**Comment by Krzysztof-Cieslak** [comment]
> Yeah, this how I said not to do it ;-)

That just the version I have done earlier, just created this PR to discuss it here ;)

I'll try to fix it soon.

**Comment by Krzysztof-Cieslak** [comment]
OK, I think I've fixed 1 - I've added optional parameter to `ZoneWidget.show` which controls if showing widget should also scroll to it and reveal it. It defaults to true [old behavior], so all other places using this method are not changed

To the 2 - I actually like that each error is in its own widget, not sure if we should change it. But your call in the end.

**Comment by jrieken** [comment]
Sorry for delay and for me making this more complicated now. I am prepending I didn't see the `scrollTip` hack and proposing a different solution which doesn't use the ZoneWidget anymore. That is because the ZoneWidget is quite dated and needs a bigger overhaul. So, if you feel a little adventurous and if you want to make a long lasting contribution bear with me ;-) 

Let me explain two concepts the editor supports and how the ZoneWidget fits into this:

* on the one side there are editor widgets that overlay the text, like the suggestion or find widgets
* then there are view zones which can be used make room in between two lines. Originally this was added for the diff editor and the green/red stocked areas that show additions/removals. 

The ZoneWidget is a combination of the two above. There is a view zone in it that "makes space" and then there a widget which is "manually" positioned on top of that view zone. Because for the editor it's two different things the widget itself needs to self-manage it, like manually setting [`style.top`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L160) on the widget when the zone scrolls etc. Nothing that runs fast and nothing we are particularly proud of 🙈 

The good news is that for showing all diagnostics, it's enough to just use view zones. The bad news is that it makes this PR a little more involving. The abstract of this feature would then be

* label the existing bits toxic and start fresh'ish
* have a new controller, like the [`MarkerController`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L338) that knows an editor and the services
* in the controller use the [`changeViewZones`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/editorBrowser.ts#L490)-api and reuse/get inspired by the [`MessageWidget`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L177). Because view zones are fast, simply create new zones for all markers when they change while active.
* have some actions that drive the above controller 

I hope I didn't scare you with this - I know it's a little work but it will result an implementation which is better then what we have today and that's what we want. I also happily assist you with getting this done. Happy Coding.

**Comment by Krzysztof-Cieslak** [comment]
Thanks for all explanations, I'll come back to this PR on the weekend / next week.

**Pull request closed without merging**
