### PR TITLE
Terminal ligatures take 4

### LINKED ISSUE #34103: Support ligatures in terminal
Regresses with performance improvements in terminal's renderer https://github.com/Microsoft/vscode/pull/33954

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #34103

### CODE REVIEW

**Comment by Tyriar** [comment]
Not sure why this is happening:

image

The typescript build succeeds.

**Comment by Tyriar** [comment]
Product build needs to wait a while as xterm.js was only just published

**Comment by Tyriar** [comment]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=302680&view=results

**Comment by Tyriar** [comment]
Product build worked on macOS 🎉 

There's one pretty obvious issue where the background will often be wrong when typed out:

Screenshot 2024-11-04 at 9 15 54 am

I suspect it's the cell having the cursor background and then not being re-rendered when that cell is marked to skip rendering due to being a ligature part.

**Comment by Tyriar** [comment]
Tracked in https://github.com/microsoft/vscode/issues/233005

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
