### PR TITLE
follow up title part changes

### PR DESCRIPTION
**Pull request by bpasero**
@sbatten a few follow up changes:
* I felt it was more natural to move the registration of title service to the services land and with that I moved the native pieces over as well
* I removed usages of `isWeb` that still existed in the electron title

### CODE REVIEW

**Review by sbatten — APPROVED** [review]
I have no issue with these changes. The title bar part is wearing 2 hats currently as the part and the service, much like other parts. I think this makes us a little inconsistent where parts live but I don't find this too troubling as they are still easy to find.

**Comment by bpasero** [comment]
@sbatten I decided to not go with this approach but rather actually have `src/vs/workbench/electron-browser/parts/titlebar/titlebarPart.ts` to be symmetric with our parts in `browser`. 

I still register the title service outside of these files because I do not want to register the same service twice (which would happen if the `registerSingleton` was left in the files).

**Comment by sbatten** [comment]
sounds good. one think I notice is the name `NativeTitlebarPart`. This is a bit strange because it actually is a custom title bar (opposite of native) but running in the non-web (native?) case.

**Comment by bpasero** [comment]
@sbatten good catch, I renamed it to `TitlebarPart`. Happy with the model now.

**Pull request merged**
