### PR TITLE
Add CJK-aware line wrapping, and basic Kinsoku Shori (禁則処理) to Visual Studio Code

### PR DESCRIPTION
**Pull request by be5invis**
The main idea is adding a forth character class, `BREAK_IDEOGRAPHIC`, which behaves normally like both `BREAK_BEFORE_CLASS` and `BREAK_AFTER_CLASS`, unless it is before a `BREAK_AFTER_CLASS` character, or after a `BREAK_BEFORE_CLASS` character.

### CODE REVIEW

**Comment by be5invis** [comment]
@Tyriar @alexandrudima Should I escape all non-ASCII symbols in the .ts files?

**Comment by be5invis** [comment]
@alexandrudima @dbaeumer 
Are there anything I did not cover?

**Comment by alexandrudima** [comment]
Looks good! Thank you @be5invis !

**Pull request merged**
