### PR TITLE
Added cursor pointer in monaco select box for consistency

### LINKED ISSUE #152465: application: consistent behavior when interacting with `select` components
**Details**

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Ubuntu 18.04.6 LTS

**Steps to Reproduce:**

1. start the application
2. open the **debug** view and interact with the debug launch configuration select component - notice that the cursor is a pointer
3. open the **preferences** view and interact with preferences that provide enum values (select components) - notice that the **cursor** is not a pointer

**Description**

In order to improve usability and consistency across the product, the **select** components should behave similarly and display a `cursor: pointer` when interacting with the select components. The individual options provided by the component already display the proper pointer, but not when first interacting with the select.

**Additional Information**

_debug view_: (cursor is a pointer when first interacting with the select)

https://user-images.githubusercontent.com/40359487/174296343-6c65de92-aeec-40d1-be33-f8a3d6f4077e.mp4

_preferences view_: (cursor is not a pointer when first interacting with the select)

https://user-images.githubusercontent.com/40359487/174296387-7b48f921-3e57-474d-b8b7-c666d5341efc.mp4

### PR DESCRIPTION
**Pull request by Balastrong**
This PR fixes #152465

### CODE REVIEW

**Comment by rzhao271** [comment]
I noticed in the file that there's different rules for `.monaco-action-bar .action-item .monaco-select-box` and `.mac .monaco-action-bar .action-item .monaco-select-box`. Does that mean the decision to use `cursor: pointer` is OS-dependent? @misolori

**Comment by rzhao271** [comment]
TODO:
- [ ] Investigate on macOS whether the selectbox should also be a pointer
  - [ ] If no, the CSS needs to be applied only to other OSes
  - [ ] If yes, the macOS CSS needs to be adjusted

**Comment by misolori** [comment]
>  Investigate on macOS whether the selectbox should also be a pointer

I'd follow the same pattern done in the debug viewlet, which is to show a pointer on the dropdown.

**Review by rzhao271 — DISMISSED** [review]

**Comment by rzhao271** [comment]
I'll merge this in August so that it gets more Insiders testing.

**Review by roblourens — APPROVED** [review]

**Review by rebornix — APPROVED** [review]

**Pull request merged**
