### PR TITLE
Avoid key fingerprint prompt for FIDO/U2F keys

### LINKED ISSUE #164402: Git operations using SSH with a FIDO/U2F key trigger a host authentication dialog
Type: <b>Bug</b>

Git operations using SSH with a FIDO/U2F key (`ecdsa-sk` or `ed25519-sk`) trigger an incorrect `"key" has fingerprint "undefined" Are you sure you want to continue connecting?` dialog when SSH prompts for user presence.
The security key still starts blinking and tapping it makes the operation succeed, but the dialog still remains and is incorrect.

I assume the SSH CLI output (`Confirm user presence for key ...`) is misinterpreted as a host key verification prompt?

A security key and a modern OpenSSH version are required to reproduce (I'm using a Yubikey and OpenSSH 9.1p1 installed using Homebrew on macOS). A key can be generated using e.g. `ssh-keygen -t ed25519-sk`.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.83GB free)|
|Process Argv|. --crash-reporter-id 35069983-5026-4390-94a6-9fa2b4b209ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-tools|gee|1.3.1
copilot|Git|1.54.7077
go|gol|0.35.2
rust-analyzer|rus|0.3.1248
vscode-lldb|vad|1.8.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

### PR DESCRIPTION
**Pull request by SeriousBug**
The ssh key fingerprint prompt is incorrectly displayed for ssh keys backed by FIDO/U2F hardware keys such Yubikey. This PR avoids the incorrect prompt.

fixes #164402

### CODE REVIEW

**Comment by kenibrewer** [comment]
@lszomoru @SeriousBug Is there any way that we could get this pull request merged? I've started using a FIDO/U2F hardware key and have run into this problem too.

**Comment by Tchekda** [comment]
In my case, git doesn't prompt anything while waiting for the security key, so I'm not sure this PR going to work for everyone

**Comment by kvarga** [comment]
Is this still being looked at? I can't use my Yubikey within VS Code so have to push/pull from Terminal.

**Comment by SeriousBug** [comment]
I gave up, and just switched to non-Yubikey keys. Closing this PR because it looks like this is not ever getting merged or otherwise resolved.

**Comment by mbailey** [comment]
Looks like it may have been fixed? I stopped seeing the msg in the last couple of days.

**Pull request closed without merging**
