### PR TITLE
Increased the allowed regex search matches to max number value to acc…

### PR DESCRIPTION
**Pull request by aasierra**
…omodate high match volumes

This PR was made to fix issue 496 where there is a limit of 999 match values to a file.
Link to issue https://github.com/Microsoft/vscode/issues/496

### CODE REVIEW

**Comment by aasierra** [comment]
@alexandrudima Looks like omnisharp:fetch failed?

**Comment by alexandrudima** [comment]
@aasierra Yes, the build failure is unrelated to your change.

I see the need to highlight more than the first 1k results, but I feel reluctant to remove the limit altogether. It is not so much a problem to find all these matches, but afterwards they are converted into model decorations (tracked ranges) and the view model converts them again for fast painting times (in case of wrapping).

I'm thinking about 20MB files where as you begin typing in the find widget there could be >1M find matches. From my playing with it, I am certain the model/view model are not in such a good shape to deal with these many decorations at this time.

I will do some additional testing to see if there is something low hanging, otherwise an alternative solution (for unlimited find results highlighting) would be to make the entire find widget not rely on decorations and bake the concept into the view  -- to get O(viewport) complexity.

**Comment by joaomoreno** [comment]
Closed and opened PR to get a later merge commit for Travis to build on and get this green.

**Comment by aasierra** [comment]
@alexandrudima I totally understand, would a better solution (and this is one I would be willing to look into) be to have highlighting and other actions update as you scroll the document?

**Comment by aasierra** [comment]
@joaomoreno I am going to close this for now however @alexandrudima What do you think of these changes as a starting point for how to search within the current view context. This code is a little buggy and does not update on scroll yet but poses the idea I was talking about earlier. The idea is that viewImpl.getView is used and altered to return the search range that should be matched against. Thoughts?

**Pull request closed without merging**
