### PR TITLE
Emmet - Fixing bug in toggle comment with multi cursor

### PR DESCRIPTION
**Pull request by gushuro**
Fixing https://github.com/Microsoft/vscode/issues/27874

togglecomment

### CODE REVIEW

**Review by ramya-rao-a — CHANGES_REQUESTED** [review]
Good job!
Can you add a few tests as well?
https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/test/toggleComment.test.ts

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
@gushuro The tests around the excludeLanguages are still failing. They don't when running from VS Code, but they do fail when running `./scripts/test-integration.sh` from the terminal

**Review by ramya-rao-a — CHANGES_REQUESTED** [review]
@gushuro The tests around the excludeLanguages are still failing. They don't when running from VS Code, but they do fail when running `./scripts/test-integration.sh` from the terminal

**Comment by gushuro** [comment]
Apparently, setting the tests to modify the user global settings (instead of the workspace ones) was preventing the tests to fail when running from VS Code, but making them fail when invoking the script. Undid that change so the CI doesn't fail.

**Review by ramya-rao-a — APPROVED** [review]

**Pull request merged**
