### PR TITLE
[WIP] Hackathon: Find-All-References in viewlet/panel

### PR DESCRIPTION
**Pull request by amcasey**
Strategy: clone the Search viewlet/panel, replace file search with symbol search, and then delete as much code as possible.

Status: works in (at least) some cases but UI is unpolished and tests are limited.

Open Question: how to ship.

**THIS IS NOT READY TO BE MERGED**

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @mattbierner @roblourens

**Comment by amcasey** [comment]
FYI @billti

**Comment by roblourens** [comment]
Hey @amcasey, sorry your email got buried over the weekend. I think @jrieken is the right person to look at this. He is OOF for a couple days.

**Comment by amcasey** [comment]
@roblourens Thanks!  No rush, I just want to keep things moving.  I'm pretty sure there's a bunch more work for me to do - I just need to know what it is.

**Comment by amcasey** [comment]
Ping

**Comment by amcasey** [comment]
FYI @kieferrm.  It should be in a state where you can play around with it locally.  I've quite intentionally done everything through *new* commands so that the existing FAR experience remains unaffected (as in VS, Peek Definition and Go to Definition can coexist).

**Comment by jrieken** [comment]
I honestly don't really know what to do with this. It's a giant code change. There are open questions like what tackles this? Do we want two UIs for ref search et al? Who will maintain this?

> Strategy: clone the Search viewlet/panel, replace file search with symbol search, and then delete as much code as possible.

Not sure that was a good choice - the search viewlet is the dinosaur in our code base, has seen many owners and might not be free of debt. 

@amcasey Did you consider implementing this as extension? We have api-commands that allow you to trigger reference search operations and we also have tree views that allow you to populate a section in a viewlet (or have a new viewlet).

**Comment by jrieken** [comment]
> My preference would be to ship it as an in-box extension but @kieferrm mentioned that he didn't think the public API was sufficient for what I was trying to accomplish.

@kieferrm Wonder why? Small things might be missing but the overall thing should be relatively easy to implement as extension. This is somewhat similar to my [References++](https://marketplace.visualstudio.com/items?itemName=jrieken.references-plusplus)-extension. While it uses a text document as "UI", it also uses [api commands](https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/src/provider.ts#L54) to get to the "business logic"

**Comment by amcasey** [comment]
I'm going to shelve this for now.  I'll attempt to follow the model of References++ when I return to it.

**Pull request closed without merging**
