### PR TITLE
Fix-78397 Implement case preservation in search as well

### LINKED ISSUE #78397: Implement case preservation in search as well
In https://github.com/microsoft/vscode/issues/9798 we implemented some support for preserving the match case while doing a find/replace. We need the same feature in search.

### PR DESCRIPTION
**Pull request by skprabhanjan**
@roblourens , Here is the implementation of case preservation in search to fix #78397 .

> ideally copying it into a shared file so that find and search will use the same preserve case logic.

I could not achieve this as both use a different replacePattern files.

Please review this and let me know :) 
I have tested it and this works perfectly fine :)

### CODE REVIEW

**Review by roblourens — CHANGES_REQUESTED** [review]
Thank you, this is almost perfect! One change, please create a file in src/vs/base/common called search.ts, and create a function there that does the work to check and apply the casing patterns. Basically it should just be the lines starting with `matches[0].toUpperCase() === matches[0]`. We should be able to share that code between the search side and the find side. Please copy the ReplacePattern unit tests for it too. Thanks!

**Comment by skprabhanjan** [comment]
@roblourens, thanks for the review .
I will do that change and commit it post this weekend :)

**Comment by skprabhanjan** [comment]
Hi @roblourens , All changes done as per your review :) 
Please let me know if anything needs to be changed, Thanks !

**Comment by roblourens** [comment]
This is great, thanks!

**Pull request merged**
