### PR TITLE
Remove bigNumbersDelta

### PR DESCRIPTION
**Pull request by remcohaszing**
If I understand correctly, this is just a hack to support IE. However, [IE is no longer supported](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0200-11022020), so this is no longer necessary.

This is getting somewhat in the way of #194609.

### CODE REVIEW

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
Thanks!

**Review by bpasero — APPROVED** [review]

**Comment by remcohaszing** [comment]
Correct me if I’m wrong, but the CI failure appears to be unrelated to these changes.

**Comment by hediet** [comment]
Yes, I believe so too

**Comment by jalaladdinrafiyev** [comment]
Love you guys

**Pull request merged**
