### PR TITLE
"공백" is better than "공간" in korean

### PR DESCRIPTION
**Pull request by whitekid**

### CODE REVIEW

**Comment by johnliu2016** [comment]
@lukaschal, please take care of this through linguistic and fix in /Localize/kor/vscode/src/vs/workbench/browser/parts/editor/editorStatus.nls.resx.lcl

      <Item ItemId=";spacesSize" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Spaces: {0}]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[공간: {0}]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

Expected string is "공백: {0}"

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@whitekid Please, is it possible to add ENU and KOR screenshots of mentioned issue ?

**Comment by whitekid** [comment]
@lukaschal here is screenshot
space-en
space-kor

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\workbench\browser\parts\editor\editorStatus.nls.resx
ID: ".resx", 0; "spacesSize"
SRC: Spaces: {0}
TGT: 공백: {0}

**Comment by whitekid** [comment]
@lukaschal where is editorStatus.nls.resx? I can't find in this repository.

**Comment by lukaschal** [comment]
@johnliu2016 Please, could you take a look ?

**Comment by johnliu2016** [comment]
@whitekid editorStatus.nls.resx is intermediate format for loc, for counterpart on GitHub, see vscode/i18n/kor/src/vs/workbench/browser/parts/editor/editorStatus.i18n.json

**Pull request closed without merging**
