### PR TITLE
Don't register download action if there is no downloadUrl

### PR DESCRIPTION
**Pull request by dashdotdawn**
https://github.com/microsoft/vscode/issues/168448

### CODE REVIEW

**Comment by joaomoreno** [comment]
A better fix would be to fix the action's `precondition`: https://github.com/microsoft/vscode/blob/f7d084d7d81082c3ca0b6af52c1f6701e55ed381/src/vs/workbench/contrib/update/browser/update.contribution.ts#L155-L156

**Review by joyceerhl — CHANGES_REQUESTED** [review]
Thanks for the fix--as @joaomoreno mentions we can fix this with a more precise `precondition`, there is an example of how to do this with the `RELEASE_NOTES_URL`: https://github.com/microsoft/vscode/blob/0e20196eae2e98186c881b00de5eb6a9715264bf/src/vs/workbench/contrib/update/browser/update.contribution.ts#L46

Following that example, we would want to introduce a new `DOWNLOAD_URL` context key similar to https://github.com/microsoft/vscode/blob/0e20196eae2e98186c881b00de5eb6a9715264bf/src/vs/workbench/contrib/update/browser/update.ts#L34 and initialize it from `productService.downloadUrl` similar to https://github.com/microsoft/vscode/blob/0e20196eae2e98186c881b00de5eb6a9715264bf/src/vs/workbench/contrib/update/browser/update.ts#L110-L113

Then the `precondition` would become

```ts
	precondition: ContextKeyExpr.and(IsWebContext, DOWNLOAD_URL), // Only show when running in a web browser and a download url is available
```

If you don't want to make this change please let me know and I can take the PR from here.

**Comment by dashdotdawn** [comment]
@joyceerhl Thanks a lot for your good advice! I have made changes according to it.

**Comment by dashdotdawn** [comment]
@microsoft-github-policy-service agree

**Review by joyceerhl — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by joyceerhl** [comment]
Thank you for the fix @dashdotdawn!

**Pull request merged**
