### PR TITLE
Support terminal bell

### LINKED ISSUE #32184: Support bell character in terminal
- VSCode Version: 1.14.2 cb82febafda0c8c199b9201ad274e25d9a76874e
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Start VSCode
2. Launch a Terminal
3. Run 
> echo -ne '\007'
4. Check if any sound is emitted

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #32184

---

@mjbvz any issue/alternative to the changes to CSP?

### CODE REVIEW

**Review by mjbvz — APPROVED** [review]
CSP change looks fine

**Comment by mjbvz** [comment]
Although you may be able to avoid needing a csp change by using the web audio api instead of an `<audio>` tag for the bell. Not sure about this however

**Comment by Tyriar** [comment]
@mjbvz good to know, created https://github.com/xtermjs/xterm.js/issues/1181

**Comment by felipenmoura** [comment]
Is this in the stable version?
I'm currently using 1.19.2 and "the bell never rings" in terminal!

**Comment by Tyriar** [comment]
@felipenmoura the milestone indicates the version it will be release in, the January release is due out in 1-2 weeks.

**Comment by felipenmoura** [comment]
Awesome, thanks :)

**Comment by EvilJordan** [comment]
This is still not fixed, correct? Opening an integrated terminal in OSX and typing this: `echo -ne '\007'` results in no bell, despite `"terminal.integrated.enableBell": true`

**Comment by Tyriar** [comment]
@EvilJordan I'm seeing errors when I try to run the bell, see https://github.com/xtermjs/xterm.js/issues/1694

**Comment by EvilJordan** [comment]
@Tyriar Indeed, I see this in the Developer Tools console: `ERR Unable to decode audio data`

**Pull request merged**
