### PR TITLE
Document focus suggest details with ctrl+alt+space

### PR DESCRIPTION
**Pull request by jjaeggli**
This change allows the current ctrl + alt + space shortcut perform the following action:

* When shortcut is pressed, document focus moves to the suggest details widget. This allows it to be used by screen readers.
* When arrow keys are used within the suggest widget, while details is focused, the focus indicator is removed from details, and removes the details state.
* When ctrl + alt + space is pressed when in suggest, but details is not shown, opens details

This changes the behavior in the following way:

* When moving between different items in the list, Details state is removed. This is because the details focus indicator now follows page focus. The details state allows keyboard users to navigate within long documentation using page up and page down. The user will need to re-enter the details state each time. Ie. it is not sticky.

This makes the following additional changes:

* move operations performed on the details dom to methods in suggestWidgetDetails.ts.
* adds a case statement for handling operations on state exit. Some operations could be moved here to remove duplication.
* adds button semantics to the close button

Screenshot 2023-08-09 at 2 47 42 PM

A followup to this behavior to make the suggest details widget more accessible would be to upgrade it to a modal dialog when ctrl+alt+space is pressed, allowing visual keyboard users to tab-focus to links within the markdown documentation

### CODE REVIEW

**Comment by jjaeggli** [comment]
@meganrogge @jrieken thanks in advance for taking a look.

**Comment by meganrogge** [comment]
Thanks very much for working on this. I will test it tomorrow. 

Have you tried out the new `Accessible View` feature @jjaeggli? I wonder if we should also use that for the details so that SR users can inspect it char by char.

Example: 

With screen reader mode on, trigger a hover and focus it. Use `alt+f2` to inspect it in the accessible view. We could add support for that here too.  

Screenshot 2023-08-09 at 2 38 24 PM

**Comment by meganrogge** [comment]
@jjaeggli I'm using a laptop atm in insiders, so have configured a different key binding for accessibility help and it's working for me. Can you run `Developer: Toggle Keyboard Shortcuts Troubleshooting` to see what's happening?

**Comment by meganrogge** [comment]
`ctrl+space` still doesn't work for me to trigger inline suggest and thus I cannot test this change, so will have to leave it with @jrieken, but your explanation of the change above makes sense to me

**Comment by dzmitrymishyn** [comment]
Is there any progress here? 
@jrieken could you please take a look at this

**Comment by jrieken** [comment]
> ctrl+space still doesn't work for me to trigger inline suggest and thus I cannot test this change

@meganrogge This is not about inline suggest but about normal completions which do trigger via `ctrl+space` unless macOS took that to switch keyboard layouts. Uncheck those

image

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
> When ctrl + alt + space is pressed when in suggest, but details is not shown, opens details

That was the part that was senstive to timing because details show via RAF and therefore focus cannot be set immediately but only once the details have been rendered

**Review by TylerLeonhardt — APPROVED** [review]

**Pull request merged**
