### PR TITLE
Adopt `vscode-textmate@6.0.0`

### PR DESCRIPTION
**Pull request by alexdima**

### CODE REVIEW

**Comment by SNDST00M** [comment]
https://github.com/microsoft/vscode/pull/131428.patch and `git apply 131428.patch` are your friends (with corrections)

**Comment by SNDST00M** [comment]
Actually I'll write PR and try fix it

**Comment by alexdima** [comment]
> https://github.com/microsoft/vscode/pull/131428.patch and git apply 131428.patch are your friends (with corrections)
> Actually I'll write PR and try fix it

Yes, I could do that and then do `git commit --author`, which will credit your work correctly in GitHub. But if you create the PR, that would allow our Thank you tool to also pick it up and [give you credit in our release notes](https://code.visualstudio.com/updates/v1_63#_pull-requests)

**Comment by SNDST00M** [comment]
`SEMANTIC_USE_STRIKETHROUGH` is missing, whats the strat on adding that to `TokensStore2.addSemanticTokens`?

**Comment by SNDST00M** [comment]
Note to self: new PR at #139413 and context in #43504

**Pull request merged**
