### PR TITLE
Adds move views command

### PR DESCRIPTION
**Pull request by eamodio**
This adds a move views command to allow extensions to control the layout of multiple views in one shot.

I really want to get this in so that in GitLens I can maintain my _GitLens: Set Views Layout_ command, as well as the view control from the Welcome view and Interactive Settings editor.

image

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
@eamodio shouldn't this be an official `vscode.` command if it is meant to be used by extensions and be contributed from `src/vs/workbench/api/common/apiCommands.ts`?

**Comment by eamodio** [comment]
@bpasero good idea. I've moved it into `vscode.*` although until this bakes more, we won't publicize it

**Comment by sbatten** [comment]
As discussed, this needs more vetting and we have known issues in the multiwindow case, so this shouldn't be broadcast for wider use. but let's get it in and have gitlens "selfhost"

**Review by sbatten — APPROVED** [review]
random deleted line

**Pull request merged**
