### PR TITLE
Fix context menu inaccurate positioning

### LINKED ISSUE #113175: Linux: native context menu runs action under mouse when opened
Issue Type: <b>Bug</b>

When I right click, the menu will flash on and then off almost immediately, like maybe 100 or 200 milliseconds. This is not all the time, but I am not able to narrow it down. It seems to be only in the editor that this issue exists. I can sometimes "fix" it by right clicking on the left side, like in the Explorer, then going back to the editor. I do not have this issue with any other software on my system. This started maybe Wed this last week, so approx around Dec 16th.

I removed 2 SCSS extensions which I believed were at fault, but with them uninstalled, the problem still exists. Those were my most recently installed extensions, the rest have been there a while.

Regarding what happens, when the right click menu disappears it seems like an option is being selected, almost like there is some sort of double click happening... the first right click to open the menu and a second to select something. I believe this to be the case as different things happen after I right click that normally require me to explicitely call said function.

VS Code version: Code - Insiders 1.53.0-insider (c927a8015b9e26bd454d6e293bb0384aa1975d06, 2020-12-18T05:27:50.274Z)
OS version: Linux x64 5.4.0-59-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2799)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.32GB (0.37GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 99855e03-cc37-4ed5-907b-28a1bf4d8453|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
project-manager|ale|12.0.1
code-gnu-global|aus|0.2.2
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
xml2json|bui|1.2.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-mysql-client2|cwe|2.8.6
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.0.6
vscode-html-css|ecm|1.2.1
vscode-npm-script|eg2|0.3.13
apacheconf-snippets|eim|1.3.0
git-project-manager|fel|1.7.1
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.1
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.22.0
beautify|Hoo|1.5.0
vscode-git-add-and-commit|iva|2.1.1
search-node-modules|jas|1.3.0
shortcut-menu-bar|jer|1.5.0
vscode-gnupg-tool|JHe|1.3.9
vscode-sshfs|Kel|1.19.1
sftp|lix|1.12.9
code-beautifier|mic|2.3.3
xml-format|mik|1.0.2
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
vetur|oct|0.31.3
java|red|0.73.0
vscode-xml|red|0.14.0
shellman|Rem|4.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
bash-debug|rog|0.3.9
joplin-vscode-plugin|rxl|0.3.0
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.13
html5-boilerplate|sid|1.1.1
sonarlint-vscode|Son|1.19.0
code-spell-checker|str|1.10.2
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.12.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-maven|vsc|0.27.0
codetour|vsl|0.0.42
gistfs|vsl|0.1.12
nodejs-extension-pack|wad|0.1.9
eno|Wsc|2.3.41
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0
ab-html-formatter|zov|0.0.2

</details>

### LINKED ISSUE #187111: Strange Behavior when right-click
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.31-2-MANJARO

Steps to Reproduce:

After right-clicking at certain locations, the context menu automatically selects the option closest to the mouse cursor. This is not a mouse issue as I encountered the same problem on two different Manjaro machines using different mice. I initially thought it was an issue with extensions until I disabled all extensions, but the problem still persists. This behavior is not observed in other software.
Here is a video showing this bug.

https://github.com/microsoft/vscode/assets/1586755/83193acb-73cc-42bf-86d7-60050c5db994

### PR DESCRIPTION
**Pull request by hsfzxjy**
This PR should fix #113175, fix #187111.

Previously VSCode adopts a formula like `clientX = Math.floor(pageX * zoom)` to calculate the coordiate on screen for showing up the context menu. The formula leads to numeric loss when `zoom != 1`, causing nonnegligible shift of context menu in some cases, and finally presented as user annoyance as described in abovementioned issues.

However, for most of the time the desired position for context menu is the current position of cursor, which actually need not to be calculated by ourselves. [Electron Docs](https://www.electronjs.org/docs/latest/api/menu#menupopupoptions) states that leaving the `x` and `y` arguments as `undefined` will indicate the context menu popping up at current mouse cursor position. 

Therefore, this PR utilizes the Electron API for more accurate context menu popup positioning, and hopefully should fix these related issues, if there's no other defeat in upstream Electron.

### CODE REVIEW

**Review by deepak1556 — COMMENTED** [review]
Thanks for the PR! Have you been able to verify if the change addresses the mentioned issue ? I have not been able to repro them on my machine so cannot validate this change. But agree that Electron calculates the cursor coordinates when not explicitly configured at https://github.com/electron/electron/blob/93024be3b26ff66a7978ba278990a0a0f55bc9d3/shell/browser/api/electron_api_menu_views.cc#L33

Also a follow-up question, when would `isCurrentCursor` not be needed ? I wondering if we should always use current cursor position for desktop. Maybe @sbatten can chime in on this.

**Comment by hsfzxjy** [comment]
> Thanks for the PR! Have you been able to verify if the change addresses the mentioned issue ? 

Yes. It address the issue that the menu shifting from the current cursor position. 

So now if keeping cursor unmoved during right-click, there won't be accidental click. 

But if cursor is moved during right-click, there's still a chance of accidental click since Linux DE will acknwledge menu item on mouseup -- this is a problem of Linux DE and we can't interfere with.

> I have not been able to repro them on my machine

It might be easier to repro with

1. Linux desktop
2. zoom factor > 1
3. menu with long list of items, such that menu spawns at a position where cursor is at the middle of one of its vertical edges instead of at the corner.

> when would `isCurrentCursor` not be needed ?

I don't know. But since this is a public API, I would rather ensure its forward compatibility so as not to break existing code. Adding an optional argument sounds reasonable.

**Comment by deepak1556** [comment]
Thanks for testing, I have tried different variants documented in the upstream issue https://github.com/electron/electron/issues/31641, unable to repro with my current display setup.

I am good with merging this change once API changes are approved by @sbatten. We can get feedback from the affected users with insiders build.

**Review by bpasero — COMMENTED** [review]
> and hopefully should fix these related issues

Yeah, I am not 100% convinced it does. https://github.com/electron/electron/issues/31641 is reported with a standalone sample that does seem to rely on Electron positioning the menu properly ([code pointer](https://gist.github.com/exceedsystem/d9cca97cbfb450d0ad151b193aaf6a98#file-main-js-L20)).

Nevertheless, I think having a way to signal back to the Electron context menu to position it where the mouse is is an interesting idea. But the adoption is a bit challenging because from the outside we always have to pass in `x` and `y` for our custom menu to position properly which has no other way of getting to the cursor location otherwise. 
On top of that, we seem to be having cases where - even though the context menu should open from mouse interaction - we put it to a slightly different location by a few pixels (for example [here](https://github.com/microsoft/vscode/blob/de6839abe8ba06d86bd1f0827dc2b60e53e5dac4/src/vs/editor/contrib/contextmenu/browser/contextmenu.ts#L106)). 

I think from the internal API I would expect another `or` type to signal the mouse position is wanted, such as:

```ts
HTMLElement | { x: number; y: number; width?: number; height?: number; } | { mouseX: number; mouseY: number }
```

To make it very explicit that in the one case a x/y position is wanted and in the other case the mouse location is preferred.

Finally, - given my first point - I wonder if a pragmatic workaround for VS Code could be to always offset the menu by `1px` on Linux at least it the cursor location is wanted.

**Comment by hsfzxjy** [comment]
> Yeah, I am not 100% convinced it does. [electron/electron#31641](https://github.com/electron/electron/issues/31641) is reported with a standalone sample that does seem to rely on Electron positioning the menu properly ([code pointer](https://gist.github.com/exceedsystem/d9cca97cbfb450d0ad151b193aaf6a98#file-main-js-L20)).

Something I have observed:

1. I cannot reproduce the bug with the linked gist.
2. I ran into this bug with VSCode previously, but after applying this PR the bug is gone.

So here's my guessing -- this bug on VSCode has two causes

1. Some misbehaviors in Electron, which might triggered under specific hardware settings (e.g., the settings for author of [electron/electron#31641](https://github.com/electron/electron/issues/31641), but not mine)
2. Some misbehaviors in VSCode, which is the numerical loss during transforming coordinates.

I think this PR fixes cause 2, and should reduce the possibility to trigger this bug on VSCode for certain users -- but sadly I have no approach to prove this. Perhaps this should be tested by those affected by this bug and collect their responses.

---

Regarding your proposed alternatives:

> I wonder if a pragmatic workaround for VS Code could be to always offset the menu by 1px on Linux at least it the cursor location is wanted.

This won't work for two reasons

1. We don't know the context menu will be popped up at the left side or right side of the cursor. Thus we don't know the offset should be `+1px` or `-1px`.
2. Most importantly, the bug is caused by the numerical loss during `* zoom_factor`. This can be proven by the popular comment in https://github.com/microsoft/vscode/issues/113175#issuecomment-785282557 . When zoom factor does not equal to 1, the effect of offseting by 1px might be eliminated, nor would it solve the problem of numerical loss.



> I think from the internal API I would expect another `or` type to signal the mouse position is wanted, such as:
> 
> ```ts
> HTMLElement | { x: number; y: number; width?: number; height?: number; } | { mouseX: number; mouseY: number }
> ```

This is also not possible, unfortunately. Although `MouseEvent.screenX` and `.screenY` are irrelavant to zoom factor, they are relative to the top-left corner of the screen instead of _the top-left corner of the webview_. So before passing them to Electron API, we should subtract them by the left and top position of the webview on the screen, which is however not accessible.

So overall, I think this PR is a more pragmatic solution.

**Comment by bpasero** [comment]
I think https://github.com/microsoft/vscode/pull/188674 is in good shape, running a build now to give people to test. Given the chance of breakage, this can only be merged early in a new release cycle, such as next week (this week we are winding down for endgame).

Builds should also be used to test various things:
* this Linux issue most importantly
* custom menus still work nicely (e.g. on Windows)
* with / without zooming

**Comment by bpasero** [comment]
The change is in via https://github.com/microsoft/vscode/pull/188674. Sorry for not having continued here but I wanted to get the change in asap because we do have a testing day today where this change is covered in https://github.com/microsoft/vscode/issues/188709

I will make sure to have this PR mentioned in our thank you notes for our upcoming release 🙏

**Comment by hsfzxjy** [comment]
@bpasero It's OK. Thanks for the follow up to this long-term issue!

**Pull request closed without merging**
