### PR TITLE
Updated integrated themes indent guide colors

### LINKED ISSUE #8410: Indentation guides hard to see in darker themes
Testing #8232 on a MacBook Pro Retina display with brightness 2 steps below max while using a power adapter. This is my usual setting a regularly lit environments.

In the following themes the indentation guides should be changed to improve their visibility:

- [x] * Abyss
- [x] * High Contrast
- [x] * Monokai

In the following themes the indentation guides are subtle and easy to miss. However, changing those is optional.

- [x] * Dark (and Dark+)

### PR DESCRIPTION
**Pull request by bgashler1**
Fixes #8410

### CODE REVIEW

**Comment by sandy081** [comment]
@bgashler1 The primary TM setting we are using for indentation guides is `guide` and `invisibles` is the fall back if `guide` setting is not set. `invisibles` is mainly used for rendering white spaces color. So, changing `invisibles` will also impact white spaces color. If it is intentional, then we also need to change it for our default themes (Dark, Dark+, High Contrast)

#### Indentation Guides
- **TM Setting** : `guide`
- **Selector**: `.lines-content .cigr`

#### White spaces
- **TM Setting** : `invisibles`
- **Selector**:  `.token.whitespace`

**Comment by sandy081** [comment]
Moving this to September milestone, since it is too late to make into August

**Comment by bgashler1** [comment]
@sandy081 does this look right?

**Comment by sandy081** [comment]
@bgashler1 LGTM

**Pull request merged**
