### PR TITLE
Introduce new setting "editor.formatOnSaveBeforeRun"

### PR DESCRIPTION
**Pull request by stefanhaller**
This PR introduces a new setting `editor.formatOnSaveBeforeRun` that controls
whether files that are auto-saved as part of running a task or debugging are
also formatted (if `editor.formatOnSave` is true).

Along the way it fixes the problem that the reRunTask command didn't respect the
`task.saveBeforeRun` setting.

This PR addresses #104296.

### CODE REVIEW

**Comment by stefanhaller** [comment]
@alexr00 @isidorn Please have a look. I made the new option default to true, because I'm still convinced that this is the most sensible default, as I (and others) explained in #104296. I can easily change it to false of course, if you insist.

**Comment by isidorn** [comment]
Thanks for the PR, however I just closed that issue as out of scope. Which means we do not really want it in vscode core right now.
I can leave this PR open for now and we might look deeper into it in the future.

**Review by splatterxl — COMMENTED** [review]
seems good to me!

**Comment by isidorn** [comment]
Closing as no plans to merge

**Pull request closed without merging**
