### PR TITLE
Display 'No problems' in the status bar when no errors and warnings

### LINKED ISSUE #51010: Visual noise -- do not show icons on Errors & Warnings status bar when there are no problems
The error / warning icon keeps catching my attention even though there are 0 errors/warnings. I don't know if users would want to hide the problem count entirely if it's zero (that could be an option), but I would prefer if it read "No Problems" without any icon.

### PR DESCRIPTION
**Pull request by 1AmNegan**
Fixes #51010

### CODE REVIEW

**Comment by dbaeumer** [comment]
@stevencl can you cast your vote on this. I am actually not a fan of changing this since it will make the status bar more unstable when moving from 0 -> n or from n -> 1.

Please assign back if you think this is something we should merge in.

**Comment by dbaeumer** [comment]
@bpasero FYI.

**Comment by stevencl** [comment]
I'm not convinced that this is better than what we have today, although I would like to learn more about what makes the current counter distracting when there are zero errors and warnings. The other problem is that this text would need to be localized.

**Comment by bpasero** [comment]
Let's put on the UX agenda.

**Comment by sandy081** [comment]
Closing this as it is not intended.

**Pull request closed without merging**
