### PR TITLE
chore: bump electron@29.4.0

### LINKED ISSUE #146422: [Linux] Open file or Open folder creates dialog behind active window
Native dialogs **Open file** or **Open folder** opening behind main window on RHEL 8/EL 8 clones.

This has only happened after updating to 1.66.0.

Desktop Environment: gnome.

https://user-images.githubusercontent.com/68813857/161046219-18409912-09af-4f77-ba08-f7b33a203fd5.mp4

### LINKED ISSUE #210842: Accessibility: setting caret position via IAccessible2 doesn't work
Type: <b>Bug</b>

Hello, this is an accessibility regression. cc: @isidorn
### Steps to reproduce:
1. On Windows with NVDA screenreader open any text file in VSCode. Please leave the cursor at the very beginning of the document.
2. Press `NVDA+Control+z` to open NVDA python console.
3. Paste the following text and press enter:
    ```
    import api, core, tones, time, ui
    
    def f():
        f = api.getFocusObject()
        t = f.makeTextInfo('caret')
        result = t.move('character', 10)
        if result == 0:
            raise RuntimeError
        newOffset = t._start._startOffset
        t.updateCaret()
        t.updateCaret()
        time.sleep(0.5)
        tt = f.makeTextInfo('caret')
        ttOffset = tt._start._startOffset
        if ttOffset != newOffset:
            raise RuntimeError(f"Invalid offset: {newOffset=} {ttOffset=}")
        ui.message("Success")
    
    
    
    ```
    This snippet creates a function `f()` that retrieves cursor state, then moves it by 10 characters right.
4. Paste the following line to NVDA Python console. Press enter to run it and immediately `alt-tab` to VSCode window (you need to do it within 2 seconds of pressing Enter).
    ```
    core.callLater(2000, f)
    ```
5. Wait a second or two until NVDA says "Success".

### Expected result
Cursor should be moved to position 10 in the file.

### Actual result
VSCode is left in a very weird state:

1. I am blind so I can't tell whether the cursor has moved visually.
2. If you press `RightArrow` `LeftArrow` in VSCode, then it reads 1st and 0th characters, so it behaves as if cursor didn't move at all.
3. If I retrieve cursor position via IAccessible2 API again (see `tt = f.makeTextInfo('caret')` statement in my snippet above) then it reports correct cursor location (otherwise exception would have been raised.
So TLDR: VSCode cursor ends up in an inconsistent state, but from the point of view of keyboard commands `LeftArrow` and `RightArrow` cursor position doesn't move at all.

### Technical information
NVDA uses IAccessible2 to talk to VSCode. Cursor position is updated via setCaretOffset method:
https://accessibility.linuxfoundation.org/a11yspecs/ia2/docs/html/interface_i_accessible_text.html#ae0943c1f912e4f35704fe4a0ee98e862

Thanks!

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (0.82GB free)|
|Process Argv|--crash-reporter-id 9a96d9f3-a840-44d8-9d62-0bac44c9d4b9|
|Screen Reader|yes|
|VM|67%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.4
better-cpp-syntax|jef|1.17.2
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
extension-test-runner|ms-|0.0.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31022790

```

</details>

### LINKED ISSUE #212678: Can't start new terminal session / watch task are not running correctly
Version: 1.90.0-insider (user setup)
Commit: bbc4ba1eff648ee542972589216f211b7a6a08f2
Date: 2024-05-14T05:48:27.714Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22635

Running VS Code remote WSL

Here is what I see:

https://github.com/microsoft/vscode/assets/1931590/3ee23206-fe7c-4131-a22e-07a8e979cbf8

Observe:

- the terminal does not open
- the watch task somehow hangs. It should print something like:

```
[11:03:24 AM] Starting compilation in watch mode...

[11:03:27 AM] Found 0 errors. Watching for file changes.
```

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/210842
Fixes https://github.com/microsoft/vscode/issues/212678
Fixes https://github.com/microsoft/vscode/issues/146422

### CODE REVIEW

**Review by kieferrm — APPROVED** [review]

**Comment by crhy** [comment]
I'm having the same issue. Linux Mint 21.3 Mate with Compiz. Most frequently annoying with Chromium and Kdenlive.

How do I force an update to the fixed branch?

**Comment by deepak1556** [comment]
@crhy please clarify the issue you are facing. The changes from this PR will be available with `1.90.0` release next week.

**Comment by crhy** [comment]
> @crhy please clarify the issue you are facing. The changes from this PR will be available with `1.90.0` release next week.

I'm having that issue in the latest Mint Mate version where you click Upload in Chromium for example, and the file dialog is missing until you minimize the main window.  Then it appears.

**Comment by deepak1556** [comment]
Issue should be addressed in latest stable, please try it out.

@WilliamKyle those are our internal builds that contain additional patches on top of OSS Electron. We will explore Electron 30 update in the upcoming milestones, please follow https://github.com/microsoft/vscode/issues/214394 for updates

**Pull request merged**
