### PR TITLE
fix: use product.applicationName on darwin builds

### PR DESCRIPTION
**Pull request by inclyc**
`product.applicationName`, by default in OSS version is `code-oss`, We may want to keep this naming rule to be consistent with Linux oss versions.

### CODE REVIEW

**Comment by inclyc** [comment]
@microsoft-github-policy-service agree

**Comment by bpasero** [comment]
Why?

**Comment by inclyc** [comment]
Hi @bpasero 

> Why?

Because for Linux builds we currently put the "code.sh" into `'bin/' + product.applicationName`. However on darwin, the name is still `code` for `Code - OSS`, this might be confusing for users on macOS with "Visual Studio Code" installed. (I suppose the name `code` is specific to that release right?) 
The PR makes the CLI executable name be consistent with Linux version.

https://github.com/microsoft/vscode/blob/b526328f9e34109ab3582199bfbde0232606e376/build/gulpfile.vscode.js#L389C18-L389C50

**Comment by bpasero** [comment]
I am not sure what this may break tbh. Maybe @joaomoreno has an idea about the impact?

Still, this PR does not address an actual issue, so I am not sure why we should have it.

**Pull request closed without merging**
