### PR TITLE
Add "Close to the Left" option above "Close to the Right" in Tab actions

### PR DESCRIPTION
**Pull request by tperalta82**
Added a Close to the Left option to close tabs to the left
Does the same of "Close to the Right" but, to the left tabs

image

### CODE REVIEW

**Comment by tperalta82** [comment]
@microsoft-github-policy-service agree

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
gh pr checkout 236833

**Comment by benibenj** [comment]
Thanks for the contribution, however, we are not planning on adding more actions to the tab context menu as it is already full with actions and we do not want to make the list any longer. There is the `close others` actions which combined with multi select can act the same way. We also have the `View: Close Editors to the Left in Group` command which you can use.

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
### ****

**Pull request closed without merging**
