### PR TITLE
Allow to pass in editor options to vscode.open command

### PR DESCRIPTION
**Pull request by bpasero**
Enables https://github.com/Microsoft/vscode/issues/30674

### CODE REVIEW

**Comment by jrieken** [comment]
Well, there is this [`		export function showTextDocument(document: TextDocument, options?: TextDocumentShowOptions): Thenable<TextEditor>;
`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4070) which makes me believe we don't need this

**Comment by bpasero** [comment]
@jrieken that is true, however my feeling is that many extensions (including even the Git one from @joaomoreno) simply use `vscode.open` as convenience to open a file without having to do the `openTextDocument+showTextDocument` dance. 

This change aligns `vscode.diff` and `vscode.open` commands with regards to the editor options that you can set.

**Comment by jrieken** [comment]
> simply use vscode.open as convenience to open a file without having to do the openTextDocument+showTextDocument dance.

We can make an easy fix for that and allow to pass an `Uri` in addition to a document. Having all the commands for frequent use isn't good API, it's untyped, hard to discover. If something is a common scenario it should be come real API

**Comment by bpasero** [comment]
@jrieken yeah that sounds like a good approach. However, I would argue if we have such API we should maybe think about deprecating `vscode.open` for text resources and only allow to use it for opening links and maybe binary files. What I am trying to get at is that the current extra argument for `ViewColumn` does not make sense when passing in a HTTP URL. So this command is already a bit weird.

**Comment by bpasero** [comment]
Continues via https://github.com/Microsoft/vscode/pull/30829

**Pull request closed without merging**
