### PR TITLE
fix: swap end for flex-end in browser/hover.css

### PR DESCRIPTION
**Pull request by repraze**
Fixes incorect justify-content value set in https://github.com/microsoft/vscode/pull/210472.

This resolves an autoprefixer warning while bundling with monaco-editor.

``` txt
autoprefixer: end value has mixed support, consider using flex-end instead
```

### CODE REVIEW

**Comment by repraze** [comment]
Any issues merging this?

**Comment by aiday-mar** [comment]
Hi thank you for the PR, this PR looks good, sorry. I think I previously approved it? Not sure what happened.

**Comment by aiday-mar** [comment]
I will ask someone else to review it too

**Review by aiday-mar — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by repraze** [comment]
Thanks! I'll be glad to see this warning gone.

**Pull request merged**
