### PR TITLE
Add Rust source code file association

### LINKED ISSUE #107413: Rust file icon for file explorer
I use Rust on a daily basis. I want to have an icon for the Rust file type (.rs) visible in the file explorer.

### PR DESCRIPTION
**Pull request by arnabanimesh**
This PR fixes  #107413

Added Rust windows icon and Mac icon and added relevant code changes to implement them.

### CODE REVIEW

**Comment by joaomoreno** [comment]
Looping in @misolori for reviewing the icon.

**Comment by misolori** [comment]
In the past we’ve explicitly not added new file icons as we often get requests for other file types. Not sure if we want to set this precedent cc @bpasero

**Comment by bpasero** [comment]
@misolori @aeschli is the file icon lead

**Comment by aeschli** [comment]
@bpasero This is for the OS icons, @joaomoreno owns this.

**Comment by misolori** [comment]
I also took a look at the files in this PR and there are some issues with the icns file (wrong icon and corrupted images)

image

**Comment by misolori** [comment]
I think we still need to decide whether we're going to allow others to contribute towards other OS file icons as #60699 links to the various requests we've received that we've closed as out-of-scope.

**Comment by arnabanimesh** [comment]
I edited the `sass.icns` file from the original repo while creating icns. It seems windows and mac icons are different.

**Comment by joaomoreno** [comment]
@misolori I was not aware of our position on this. Closing this PR for those reasons.

**Pull request closed without merging**
