### PR TITLE
Move strip comments into own module and write tests

### PR DESCRIPTION
**Pull request by dbaeumer**
Move the strip comments functionality into its own module and provides tests.

It also avoids catastrophic back trace behavior with the string matching (single and double quote) patterns by making the handling of the escape characters `\` and the capturing of the following characters more explicit. 

To test this you can do the following:

- open https://regex101.com/
- switch to JS mode
- use the old pattern `("(?:[^\\"]*(?:\\.)?)*")|('(?:[^\\']*(?:\\.)?)*')|(\/\*(?:\r?\n|.)*?\*\/)|(\/{2,}.*?(?:(?:\r?\n)|$))` (the problematic part is actually `("(?:[^\\"]*(?:\\.)?)*")|('(?:[^\\']*(?:\\.)?)*')`)
- As a test string use `"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`
- This will result in a time out
- You can switch also to PCRE2 mode which will tell you about the backtracking  problem.

Use the new pattern `("[^"\\]*(?:\\.[^"\\]*)*")|('[^'\\]*(?:\\.[^'\\]*)*')|(\/\*[^\/\*]*(?:(?:\*|\/)[^\/\*]*)*?\*\/)|(\/{2,}.*?(?:(?:\r?\n)|$))`

Everything should be fine. I also improved performance to find multi line comments using a similar technique as I used for the escape character `\` in strings.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@alexdima @jrieken can you please have a look. It is a long time that I wrote code for VS Code :-)

**Review by alexdima — APPROVED** [review]
LGTM. The only problematic thing I can see is that we now need to ship this file separately. But I also don't have a better idea for how to test it if the code stays in `main.js`.

**Review by bpasero — APPROVED** [review]
👏 , especially having tests now.

Sorry for not doing an in-depth review of the RegEx. I followed your steps and verified it works as you advertise.

**Comment by dbaeumer** [comment]
@bpasero @alexdima thanks for the review. Will merge the PR.

**Pull request merged**
