### PR TITLE
Don't show chat views unless the setting is set

### PR DESCRIPTION
**Pull request by roblourens**
Otherwise they will be empty because new welcome views are gated on this
Fix microsoft/vscode-copilot#10759

### CODE REVIEW

**Review by rzhao271 — APPROVED** [review]

**Comment by bpasero** [comment]
@roblourens thanks for this fix and the one in https://github.com/microsoft/vscode/pull/235019. I think the guard around `config.chat.experimental.offerSetup` is not needed though if the `ChatContextKeys.Setup.installed` condition is set properly (which I think you addressed in https://github.com/microsoft/vscode/pull/235019). Welcome views should not appear when `ChatContextKeys.Setup.installed` is set. That key was intended to actually fix https://github.com/microsoft/vscode/issues/229631.

**Comment by roblourens** [comment]
I think I was also seeing the case that `triggered` was true, but the setting was off. Seems like in general if the welcome views are gated on the setting, then the view needs to be as well.

**Comment by roblourens** [comment]
Oh I see- the `installed` key is independent of this new work.

I think we still need it on `triggered` because that can be set and persisted as true, but should be gated on `offerSetup`

**Comment by bpasero** [comment]
Yeah no worries, the setting will be going away anyway in January I would assume. Thanks!

**Pull request merged**
