### PR TITLE
Add keybinding shortcut for "Preserve case" replace option

### LINKED ISSUE #107208: "Preserve case" replace option : add a key shortcut
I'm using the "**Preserve case**" option in the **Replace field** quite often.  
And it's the only option in the panel that does not have its own **keybinding shortcut** (or at least I can't find it to set it up).

Would you consider adding a shortcut entry for this toggle?

Thank you!

### PR DESCRIPTION
**Pull request by turara**
This PR resolves #107208 with

- Adding "togglePreserveCase" command actions for editor and search view with default keybinding of "alt-(cmd)-p"
- Adding keybinding label to ReplaceInput and ContextScopedReplaceInput classes.

### CODE REVIEW

**Comment by turara** [comment]
Related to #107588.

**Comment by turara** [comment]
Is there anything I need to do about the failure of VS Code check?

**Comment by roblourens** [comment]
Looks good to me but we are in our endgame week for the next release and I will review and merge it next week.

**Comment by turara** [comment]
Thanks! I see.

**Comment by turara** [comment]
@roblourens Thank you for reviewing and merging! This is my first decent contribution to OSS. I'm very happy 😃

**Comment by roblourens** [comment]
Congratulations! I hope to see more from you 😁

**Pull request merged**
