### PR TITLE
add ignoreSubmodules option

### LINKED ISSUE #88715: Reopen Add Option: "Git: Ignore new commits in submodules"
@joaomoreno This is a reopen of https://github.com/microsoft/vscode/issues/78016

I'm sorry I didn't reply to that issue, for some reason GitHub never notified me of the response.

In any event, `git` does recognize the elements of removing submodules from the list of modified files. For instance, when looking at this in VSCode: https://github.com/microsoft/vscode/blob/master/extensions/git/src/git.ts#L1025
```
const args = ['diff', '--name-status', '-z', '--diff-filter=ADMR'];
```
Changing to the below ignores submodules
```
const args = ['diff', '--name-status', '-z', '--diff-filter=ADMR', '--ignore-submodules'];
```

While I don't believe the `git` team ever got around to documenting it, it is in this commit as of March of last year: https://github.com/git/git/commit/b680ee1495fb55e2a4236456971b3d427989eb55#diff-ab603fc6eadf618560316097522fe585

The request is to add an option in the settings to toggle that constant as to remove submodules from the listing of modified files in the tree.

### PR DESCRIPTION
**Pull request by Fmstrat**
This PR fixes https://github.com/microsoft/vscode/issues/88715
_(now that it has ~~for when it reaches~~ 20 up-votes)_

**Purpose:** Adds a setting to ignore modifications to submodules in the file tree so that large monorepos don't show numerous modifications.

**Testing:**
- Open VSCode to a repo with submodules
- Go to settings and find the "Ignore Submodules" setting
- Check and uncheck the box to watch the 'M' convert to an 'S'

### CODE REVIEW

**Comment by Fmstrat** [comment]
Hey all,

Looks like I'm failing tests in https://dev.azure.com/vscode/VSCode/_build/results?buildId=35951&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=47d55512-6160-5b27-084a-e3e9b13d4d4b

.. but I don't see any reason why? Perhaps there is something else in the branch causing that error?

```
  1) IndexTreeModel setCollapsible:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
2
should loosely deep-equal
1
      + expected - actual
      -2
      +1  
      at Context.<anonymous> (file:///home/vsts/work/1/s/out/vs/base/test/browser/ui/tree/indexTreeModel.test.js:308:20)
```

**Comment by joaomoreno** [comment]
No worries, these were broken in `master`, not related to your changes.

**Comment by Fmstrat** [comment]
Thanks @joaomoreno, Any idea when this could be merged in?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Comment by Fmstrat** [comment]
Oh I see this hit a merge, thanks! Any idea when it will be pushed into the VSCode Repo (Ubuntu)?

**Pull request merged**
