### PR TITLE
Update editor placeholder

### PR DESCRIPTION
**Pull request by bpasero**
For https://github.com/microsoft/vscode/issues/130971

@lychung7 @daviddossett maybe you could give me a 👍  / 👎  on the visuals, I tried to get close to the designs from Lydia. 

The main knobs to adjust is these CSS rules, and I was guessing the `font-size` and `gap`, so maybe you could just let me know if tweaks are needed.

https://github.com/microsoft/vscode/blob/7a9dee210dd15d7acfcc66cd12e3dce54be1ae4d/src/vs/workbench/browser/parts/editor/media/editorplaceholder.css#L6-L34

Recording 2022-04-07 at 13 44 55

//cc @misolori 

The easiest to get one of these editors is to:
* open a file
* close VSCode
* delete the file on disk
* start VSCode again

### CODE REVIEW

**Review by miguelsolorio — APPROVED** [review]

**Comment by bpasero** [comment]
Thanks! Merging in to get selfhost feedback early on, happy for more changes as a follow up as needed. I will also have to see how it looks like with multiple links appearing as actions.

I assume we would want to go with links and not buttons right?

**Comment by daviddossett** [comment]
Looks good! Links probably work better here given the longer strings used for actions. Feels a bit lighter compared to buttons as well.

One nit: there's a bit of inconsistency between the action phrasing. One is a brieg call to action ("Try again") and another is a question ("Do you want to open it anyway?"). 

Could shorten to "Open anyway"?

**Comment by bpasero** [comment]
Thanks, yeah I can change the wording. One thing to keep in mind is that I still have to somehow move the previous error toast into this place holder including text and actions. This will probably mean:
* error text can potentially be really large (e.g. in case of an exception) and probably needs trimming or a way to expand/collapse
* actions will be quite arbitrary depending on the editor that threw the error

**Comment by misolori** [comment]
@bpasero would we be able to separate out the title + message? might help for readability, i know our toasts do not have titles so not sure what we can do here

**Comment by bpasero** [comment]
@misolori what we can always do is show the generic error message we had before and show the specifics as details, how would you style this in CSS?

**Pull request merged**
