### PR TITLE
Multi root++

### PR DESCRIPTION
**Pull request by bpasero**
Introduces the concept of a workspace that can be opened.

fyi @Tyriar the backup service is getting a new method to store backups per workspace (now we have per folder and for empty windows). this is needed because workspaces have their own backup location.

### CODE REVIEW

**Comment by Tyriar** [comment]
@bpasero this is quite a bit to digest. The main thing I was clarity on is where workspaces get saved inside `Backups/` now and what the contents of `Backups/workspaces.json` is?

**Comment by bpasero** [comment]
@Tyriar sorry for not clarifying, I was actually doing changes to the model after opening the PR. The idea is to have a new backup location for when you are in the workspace context (in the same way we have a location for empty workspaces via a random ID and folder workspaces via the folder path). Workspace backups are stored using the ID of the workspace and they need to store more than just the path of the workspace, also the ID. I need this information to be able to restore these workspaces properly in https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L322

**Comment by Tyriar** [comment]
Ok, so something like this?

```js
{
  "rootWorkspaces": [
    { id: "something", configPath: "something else" },
    { id: "something", configPath: "something else" }
  ]
  "folderWorkspaces": [
    "/foo",
    "/bar"
  ],
  "emptyWorkspaces": [
    "1499807564375"
    "1499807564376"
  ]
}
```

Everything will be an implicit workspace in the future won't it? Does it make sense to do a migration to clean this up?


```js
{
  "workspaces": [
    { id: "something", configPath: "something else" }, // /foo and /bar
    { id: "something", configPath: "something else" }, // /foo
    { id: "something", configPath: "something else" }  // "empty workspace"
  ]
}
```

Or should these still be separate? I'm still a little hazy on the distinction between that "workspace mode" when you add a second folder mentioned the other day.

**Comment by bpasero** [comment]
@Tyriar yes exactly that is the format of the JSON file now (I also added quite some tests to cover the workspace scenario).

We decided to back off from the idea of converting every folder that was previously opened to a workspace. Instead, since workspace is now an explicit concept you enter it by opening it, not through the existing metaphor of opening a folder. As such, I also left untouched the hot exit data for folders. In summary, all changes for multi root that I pushed to the main side should have 0 impact on existing users that work only with folders.

Will post to the UX channel for how the flow works given that strategy tomorrow when insiders is out. E.g. one visible impact is that switching from 1 to 2 folders (or more) will trigger a window reload and a change of the ID that is used (e.g. for hot exit we use the workspace ID and no longer the folder path). This makes switching to a multi root workspace similar to switching from 0 to 1 folder and is a more explicit gesture.

**Pull request merged**
