### PR TITLE
feat: use configNamespace for registering language providers of other extensions

### LINKED ISSUE #75890: Typescript language server plugin should use a different workspace config key
_(great, clicked a github popup and lost everything i've wrote, here we go again)_

- VSCode Version: [master branch](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts#L120)
- OS Version: Windows 10

Steps to Reproduce:
Its quite complicated

Does this issue occur when all extensions are disabled?:
Yes, but the issue is with an [extension](https://github.com/Ventilador/vue-lang-extension) im building.

Currently the typescript language feature extension uses the [LanguageProvider](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/languageProvider.ts#L24) to register capabilities for a ts-based language from a tsserver plugin. The thing is, when creating the descriptor for the languageProvider, the [TypeScriptServiceClientHost](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts#L120) hardcodes the "_typescript-plugins_" id to the descriptor, later, when the language provider gets registered, there are some language capabilities, like [completions](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/completions.ts#L707), [formatting](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/formatting.ts#L95), [implementationsCodeLens](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/implementationsCodeLens.ts#L100), [jsDocCompletions](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/jsDocCompletions.ts#L118), [referencesCodeLens](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/referencesCodeLens.ts#L102), [dependentRegistration](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/utils/dependentRegistration.ts#L89) and [tagClosing](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/tagClosing.ts#L172), that use the [ConfigurationDependentRegistration](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/utils/dependentRegistration.ts#L89), which as the name says, it registers the capability only if a certain config value is set to truthy. That config is based on the descriptors id, which is used as a main section to search the config file, it ends up doing

`vscode.workspace.getConfiguration(descriptor.id, null).get('suggest.enabled')`

where `descriptor.id` is "_typescript-plugins_".
Im currently working around it, and configured my contributions as follows
```
{
  "configuration": {
    "title": "Vue-lang",
    "properties": {
      "typescript-plugins.suggest.enabled": {
        "type": "boolean",
        "default": true,
        "description": "Enable the usage of intellisense."
      },
      "typescript-plugins.format.enable": {
        "type": "boolean",
        "default": true,
        "description": "Enable/disable the vue document formatter."
      },
      "typescript-plugins.implementationsCodeLens.enabled": {
        "type": "boolean",
        "default": true,
        "description": "Enable/disable the vue document implementations CodeLens helper"
      },
      "typescript-plugins.suggest.completeJSDocs": {
        "type": "boolean",
        "default": true,
        "description": "Enable/disable the vue document suggestions for jsDocs."
      },
      "typescript-plugins.referencesCodeLens.enabled": {
        "type": "boolean",
        "default": true,
        "description": "Enable/disable the vue document references CodeLens helper."
      },
      "typescript-plugins.autoClosingTags": {
        "type": "boolean",
        "default": true,
        "description": "Enable/disable the vue document auto closing tags."
      }
    }
  }
}
```
notice my **config section**, has to be **typescript-plugins**.
Perhaps that value could be included in the `contributes.typescriptServerPlugins` 
```
contributes.typescriptServerPlugins.configNamespace: "string"
// or
contributes.typescriptServerPlugins.capabilities: ["arrayOfString"]
```

_kinda offtopic:_
are there any other language provided feature that are enabled like those listed in my issue? might just ask since i have you guys here

### PR DESCRIPTION
**Pull request by znck**
This PR fixes #75890

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks for the PR. 

Can you just provide a bit more detail on what you need #75890 for. It was opened almost a year ago and hasn't seen much attention since then

**Comment by znck** [comment]
I am building a ts plugin for Vue. The config option either enables all the plugins or none. It was working till now because only one plugin (angular) existed till now. We need  this if someone wants to enable Vue but disable angular.

**Comment by mjbvz** [comment]
Thanks. It's pretty late in the VS Code iteration so I'm to take a look at this for May

**Comment by mjbvz** [comment]
Thanks!

**Pull request merged**
