### PR TITLE
Add Textmate's `strikethrough` fontStyle

### LINKED ISSUE #78358: Support fontStyle "strikethrough" about theme
Feature Request.

## Request
Currently v1.36.1, supported fontStyles in theme customization are `bold`, `italic` and `underline`.

But I want to use `strikethrough` too. like this:

```json
		{
			"name": "FinishedTaks",
			"scope": [
				"task.fiinshed"
			],
			"settings": {
				"foreground": "#ffff00",
				"fontStyle" : "strikethrough"
			}
		}
```

## FYI
VSCode sources:

-  [src/vs/editor/common/modes/supports/tokenization.ts#L63](https://github.com/microsoft/vscode/blob/013501950e78b9dde5c2e6ec3f2ddfb9201156b7/src/vs/editor/common/modes/supports/tokenization.ts#L63)
- [src/vs/editor/common/modes.ts#L70](https://github.com/microsoft/vscode/blob/aba87f135229c17c4624341b7a2499dcedafcb87/src/vs/editor/common/modes.ts#L70)

TextMate source:

- [Frameworks/theme/src/theme.cc#L76](https://github.com/textmate/textmate/blob/b17253ae035978964ae3d137a847554d211caff7/Frameworks/theme/src/theme.cc#L76)

TextMate supports strikethrough.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes #78358. Related to #43504, based on the corresponding feature in Textmate:

- https://github.com/textmate/textmate/commit/2593550f9a736111e399a5cd162261f564f8a554
- https://github.com/microsoft/vscode/issues/43504#issuecomment-780361568

### CODE REVIEW

**Comment by SNDST00M** [comment]
@alexdima h e l p (maybe in september or october of course)

**Review by alexdima — CHANGES_REQUESTED** [review]
Unfortunately this is incorrect.

Such a change needs to begin in the project [`vscode-textmate`](https://github.com/microsoft/vscode-textmate). The bit encoding format for tokens is defined in that project at: https://github.com/microsoft/vscode-textmate/blob/a53ae3c12bef5499a7dc548b3058ee64bfcbd222/src/main.ts#L201-L233

Once that project has a new token bit encoding format, it needs to be published with a new major version (since this is a breaking change) and then adopted in VS Code.

Also, the enums are powers of 2 because they represent bits, so `FontStyle.Strikethrough` would be 8. But for it to be 8, then all the other information bits need to be shifted by 1.

**Comment by SNDST00M** [comment]
Alright, I'll be closing this and letting Microsoft get to this if and when #43504 goes through

**Comment by alexdima** [comment]
@SNDST00M  I'm having trouble reopening this PR because the original repository has been deleted. I have adopted the latest `vscode-textmate` in https://github.com/microsoft/vscode/pull/139361 . Could you please recreate this PR?

**Pull request closed without merging**
