### PR TITLE
Allow extensions to specify custom tree view resoure type

### LINKED ISSUE #43216: Icons for TreeViewItems fallbacking to default folder item if file uri is used.
Example: 
image 1

As far as I understand this line is a problem - https://github.com/Microsoft/vscode/blob/5755810a58ac76ffedb037647f1cd6fec406efe9/src/vs/workbench/browser/parts/views/treeView.ts#L334

If an item has Expended or Collapsed state (which basically means it's an item with childs) then we expect folder icon. 

In general, I don't think we should have such convention at all, and consumers should be able to set any icon they want - in case of my extension, tree view shows some information from the file, so it makes sense for me to use file icon on the node with child elements.

CC: @sandy081

### PR DESCRIPTION
**Pull request by vbfox**
The FileKind was previously guessed from the collapsability of the item,
extensions now have the capability to set it manually.

Here the top level item come from vscode great icons theme for `.fsproj` files:
2018-02-09 22_11_07- extension development host - welcome - iotestxxx - code - oss dev

Fixes #43216

### CODE REVIEW

**Comment by vbfox** [comment]
@sandy081 here is the PR I was speaking about in #43216 I think it's ready for review

**Comment by sandy081** [comment]
@vbfox Thanks for the PR. Why not using the trailing slash to determine if the resource is a directory or not?

**Comment by vbfox** [comment]
I preferred to be explicit as the extension often know what type of resource it is and also to avoid breaking extensions that would have started to depend on the current behavior.

But I can change it, It simplify the code a lot.

**Comment by sandy081** [comment]
I see your point, but we already have `FileType` in our proposed API [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L72). Re-using that type might be right approach.

@bpasero May I know if we can reuse `FileType` here ?

**Comment by bpasero** [comment]
@sandy081 that is @jrieken area

**Comment by sandy081** [comment]
@vbfox I do not think using a new property which is file specific is good idea as the tree is generic. Another idea is, since this is related to icon, overload `iconPath` property to determine the resource type.

```
iconPath?: string | Uri | { light: string | Uri; dark: string | Uri } | 'file' | 'folder' ;
```

**Comment by sandy081** [comment]
Another idea is to define a ThemeIcon and use it for icon. 

```
export namespace ThemeIcon {
	const file: ThemeIcon;
	const folder: ThemeIcon;
}

export class ThemeIcon {
         readonly id: string;
}

iconPath?: string | Uri | { light: string | Uri; dark: string | Uri } | ThemeIcon;
```

**Comment by vbfox** [comment]
I think I like the `'file' | 'folder'` in `iconPath` solution the most, it's explicit simple and widely useful.

Especially if it also style as a file or folder without resource URI (In this case using the generic icons for file or folder)

I'll take a shoot at implementing that

**Comment by sandy081** [comment]
@vbfox Thanks for considering that. 

I would prefer last solution of using `ThemeIcon`. This will be more explicit that given resource URI, icon for the tree item should be File theme icon or Folder them icon.

**Comment by vbfox** [comment]
@sandy081 I did the changes, choose the name `ThemeIconCategory` instead of `ThemeIcon` because I felt that a ThemeIcon would designate a single icon like a ThemeColor point to a single color and it's not what's happening here. But I can change it.

The multi process / saniziting was the most foreign thing for me so I hope I did it correctly:
* `ThemeIconCategory` is the type sent by the extension and is transformed to and `IThemeIconCategory` keeping only the id field
* The object matching `IThemeIconCategory` is passed to the main process and detected in `customView.ts` via it's id property

**Comment by sandy081** [comment]
@aeschli Would like to know your opinion on the name `ThemeIconCategory`?

**Comment by aeschli** [comment]
Should be ThemeIcon, like ThemeColor.
ThemeIconCategory doesn't fit.
The idea is to give our icons an identifier ('folder-icon', 'file-icon', 'refresh-button'...), and let icon themes provide a different icon

**Review by sandy081 — APPROVED** [review]
Changes look good to me. There are some minor comments about the API documentation and little tweaks in passing theme icon. Since today is the code freeze, I will merge this PR and do the  little tweaks myself. I hope you do not mind with that.

Thanks

**Pull request merged**
