### PR TITLE
allow context menu in file explorer rename widget

### LINKED ISSUE #130564: creating new file/folder and name it by copy-paste, NOT WORKING with right-click
Issue Type: <b>Bug</b>

I want to create a new file/folder with the the name copied elsewhere. So I right-click  the explorer, select "new ...", then try right-click in the box that expect to enter a name.

expected behaviour: right-click menu opens with copy/paste options in it.

current behaviour: right-click cancels the operation and then opens the explorer menu for currently selected file.

PS: copy-paste works from keyboard but in cases right-click is is a faster action to take, this slows down productivity.

PS: title is already long, but I have found that trying to rename an existing file/folder by copy/paste from right-click also does this same bug. right-click into the box just cancels the operation and opens menu for active file/folder

-----------------------
I have tested many older versions of VS, so apparently the problem has started somewhere in summer to fall of 2018. (all windows zip versions set portable by "data" folder in extracted folder)

v1.20.0: context menu opens for copy/paste correctly
v1.28.0: context menu opens but the action is cancelled while the context menu stays on the screen.
v1.38.1: context menu opens for a very short time (less than a second) and closes along with cancelling the action
v1.49.3: right-click cancels the action and opens a context menu for the file/folder already selected before the action.
v1.57.0 and v 1.59.0 are the same as v1.49.3

-----------------------

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.94GB free)|
|Process Argv|. --crash-reporter-id 584324ec-9312-4a21-82cb-89491f399328|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
prettier-vscode|esb|8.1.0
vs-code-http-server-and-html-preview|Fli|2.2.2
vscode-jsonp|luy|1.0.1
js-interactive|Moh|1.1.11
csharp|ms-|1.23.13
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.5.1
vetur|oct|0.34.1
material-icon-theme|PKi|4.9.0
vscode-npm-scripts|tra|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172

```

</details>

### PR DESCRIPTION
**Pull request by joaomoreno**
fixes #130564

cc @lramos15

### CODE REVIEW

**Comment by joaomoreno** [comment]
Recording 2022-12-23 at 16 32 04

**Review by aeschli — APPROVED** [review]

**Review by bpasero — APPROVED** [review]

**Comment by yilmazdurmaz** [comment]
@joaomoreno, thank you for your time. in case we did not miss a nasty detail about the problem, then this will also give closure to #130952

**Comment by joaomoreno** [comment]
It sure does!

**Comment by yilmazdurmaz** [comment]
is the fix somehow excluded from 1.74.3?

or broken again by some other fix?

at least the problem has a better boundary now: both native and custom "windows->dialog style" seems to behave the same. 

depending on "window->title bar style", on Windows, it either cancels the edit box (custom title bar) and opens file explorer menu, or tries to open a menu for a split-second but the edit box stays (native title bar).

Web editor (vscode.dev) does not have these options and just behaves the same as in the first case.

**Comment by yilmazdurmaz** [comment]
1.75.0 seems to have applied the fix and the context menu works fine.

Thanks again @joaomoreno

**Pull request merged**
