### PR TITLE
[folding] Changed 'shift + click' folding behavior to collapse only inner ranges when current range is unfolded

### LINKED ISSUE #78557: [folding] shift+click should only fold inner ranges
In other IDEs like Rstudio Shift+click on the arrows near the line number folds the fold-able sub parts of that part.

Peek 2019-08-06 14-34

This is very handy since it only folds everything within the scope of a specific region and can help user to have a better view on the sub-parts.

### PR DESCRIPTION
**Pull request by GustavoASC**
This PR fixes #78557.
Changed 'shift + click' folding behavior to collapse only inner ranges when current range is unfolded.

### CODE REVIEW

**Comment by aeschli** [comment]
Ok, let's give this a try. I hope this doesn't break other users. We can still add an other modifier key.

Thanks Gustavo!

**Comment by HsunGong** [comment]
Can `Shift-Click` be replace by `Click-only`? Cause In `VScode v1.41`, unfold just need `click`.

**Comment by waldyrious** [comment]
Cross-linking #16517 for future reference, since #78557 didn't mention it and I can't add a mention there now as the thread is locked.

**Comment by aeschli** [comment]
@HsunGong The behavior of `Click` has not changed (it still unfolds).

**Pull request merged**
