### PR TITLE
Fix webview focus issues that prevent cut/copy/paste when opening files with a quick pick

### LINKED ISSUE #116897: Webviews can prevent keyboard shortcuts from working in quick picks
- VS Code Version: 1.50
- OS Version: Windows 10 && Mac OSX Catalina

Steps to Reproduce:

1. Open a full-editor webview in the main editor area
2. Open a text file in the editor
3. Close the text file using a keyboard shortcut (Cmd+W or Ctrl+F4); the full-editor webview should now receive focus
4. Press Cmd+P to open the quick-pick file selector
5. Select a file from the quick pick editor; VS Code will jump you to that file
6. While editing this file, press Cmd+P again to open the quick-pick file selector

Expected Results:
* I can use keyboard shortcuts for Cut / Copy / Paste while in the quick pick editor

Actual Results:
* All keyboard shortcuts are disabled in this quick pick window.

Root Cause:
During step 5 of the reproduction, VS Code switches focus to the code file you selected from the quick pick.  Additionally, a delayed action fires as the quick pick closes.  The delayed action tells the system to return focus to the element that previously had focus, which was the full-editor webview.

The full-editor webview thinks it has focus, and as a result it absorbs all cut/copy/paste commands that are defined in webview.contribution.ts.

Does this issue occur when all extensions are disabled?: No

### PR DESCRIPTION
**Pull request by tspence**
This PR fixes #116897.

When you use a full-screen webview, and then change focus away from it with a quick-pick (e.g. Cmd+P or Ctrl+P to open the file access quick pick), two different focus events happen rapidly:
* The quick pick tells the editor to open a new file, and
* The quick pick closes, which sends a focus message to the host telling it to return the focus back to the previously focused element.

Because webviews also have a special `_focused` flag, and because that flag is used to determine whether a webview should steal Cut/Copy/Paste commands, users can experience that cut/copy/paste no longer work in a second quickpick opened after the webview thinks it has focus.

This change prevents the webview from thinking it has focus when something else has taken place prior to the quick pick's close event.

### CODE REVIEW

**Comment by tspence** [comment]
This may also be related to #109874

**Comment by mjbvz** [comment]
Thanks! Let's test this in insiders and see if it causes any issues. Currently on track for VS Code 1.54

**Comment by mjbvz** [comment]
I had to revert this due to a regression (https://github.com/microsoft/vscode/issues/117595):

1. Open a md file
2. Open the preview to the side
3. Try using arrow keys to scroll the preview 

The arrow keys no longer work since the webview is not focused. 

@tspence Please look into revisiting when you have a chance

**Comment by tspence** [comment]
Thanks for the feedback!  I'll see if I can investigate an alternative approach to solve this issue.  

The root problem for me seemed to be:
1. Focus is on a webview
2. Open quick pick file selector
3. Choose one of the available files
4. Simultaneously: Quick pick closes and returns focus to webview; && quick pick selects a file and notifies VS Code to open and focus it.

In some cases when the webview is busy, it gets the notification to obtain focus after the quick pick has opened the new file.  This seemed to affect us at FB more often because one of our webviews does lots of source control work.

A better fix might be to delay the "launch new file" action until after the quick pick has closed, or to make the quick pick not return focus to the previous webview if it took some action.

I'll consider what I can do and test something out using the #117595 issue you linked before resubmitting.

**Pull request merged**
