### PR TITLE
Use IconSelectBox to change terminal icon, remove dupes

### LINKED ISSUE #199964: Make the new icon picker generally usable for other components and adopt in terminal
Forked off from https://github.com/microsoft/vscode/issues/188972#issuecomment-1753216468 as that issue is closed.

Related: https://github.com/microsoft/vscode/issues/171076

We currently have a blaring inconsistency in the UI with 2 separate icon pickers:

image

image

I consider this icon picker work still a work in progress and not completed because of this. To fix this, before the terminal adopts we need more icons in the picker (https://github.com/microsoft/vscode/issues/171076) such that the regression in functionality in the terminal is not so severe. For example we must have icons debian, ubuntu, etc.

Breakdown of work:

- [ ] Define the subset of codicons to be exposed to the user https://github.com/microsoft/vscode/issues/171076 @hbons 
- [ ] Define how the icons are exposed to different components, this may need some smarts around what icons are displayed when filtering vs not such that the icon picker size doesn't get too large @hbons 
- [ ] Implement the changes in the icon picker and make it usage in the terminal @sandy081 
- [ ] Adopt the new API in the terminal @Tyriar

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #199964

Screenshot 2024-03-29 at 9 14 46 AM

### CODE REVIEW

**Review by meganrogge — DISMISSED** [review]
Looks great, though some tests are failing

**Comment by Tyriar** [comment]
@meganrogge just going to remove those tests instead of getting the icon box working in the smoke tests

**Review by meganrogge — CHANGES_REQUESTED** [review]
few more tests

**Review by amunger — APPROVED** [review]

**Review by meganrogge — APPROVED** [review]

**Comment by AnrDaemon** [comment]
So, ugh, what about icons for profiles? I want each profile marked with appropriately recognizable language icon. But the only those I've found were Java and Python.

**Pull request merged**
