### PR TITLE
Fix vertical alignment for quick-input count

### LINKED ISSUE #89049: Alignment issues with quick pick
image

I see the following problems:

- "4 selected" is not vertically aligned and the "Turn on"
- The the S in selected should probably be lower case?
- The "Turn on" button is taller than the text input

### PR DESCRIPTION
**Pull request by lszomoru**
This PR fixes #89049

Since the pill itself has an explicit line-height: 11px we need to sent the same line-height for the container element so that the container element has the same heigh (11px) as the pill. Below is a screenshot of the quick-pick dialog with the proposed change.

image

### CODE REVIEW

**Comment by chrmarti** [comment]
@lszomoru I was aligning text baselines previously. Note how the pill's text is now a little off compared to the OK text. Should all text move one pixel up to preserve that?

**Comment by lszomoru** [comment]
@chrmarti, I see what you mean. 
I think that is a problem with the `OK` string alignment rather than the pill. Let me see if I can fix the `OK` string.

**Comment by lszomoru** [comment]
@chrmarti, I have updated the PR. Here is a screenshot containing both changes:

image

**Comment by chrmarti** [comment]
I wonder if the baseline of the text/placeholder in the input field should still align with the badge's and button's text baseline. Like currently:
image

@misolori Do you have a recommendation?

**Comment by misolori** [comment]
I think I may have already fixed this with the updated pill design PR https://github.com/microsoft/vscode/pull/97104#issuecomment-625399541

**Comment by lszomoru** [comment]
@misolori sweet. I will close this PR.

**Pull request closed without merging**
