### PR TITLE
UwU'd the entire souce(i think)

### PR DESCRIPTION
**Pull request by elegantShock2258**
This PR fixes # uhhhh applesauce?

### CODE REVIEW

**Comment by goodevilgenius** [comment]
If Microsoft doesn't approve this PR, it proves that they hate open source.

**Comment by Slimakoi** [comment]
I love this PR

**Review by elegantShock2258 — COMMENTED** [review]
LGTM!

**Comment by leJad** [comment]
good, now make owo it

**Comment by MrZeusTheCoder** [comment]
uwu, good idea.

**Comment by Nhalrath** [comment]
I will never forget this PR

**Comment by arnavbhatt288** [comment]
deadinside

**Comment by NSG650** [comment]
Just why
image

**Comment by TheThunderGuyS** [comment]
I am unsure if I should be impressed or scared by this commit

**Comment by sudo-nautilus** [comment]
My man!

UwU 

Great effort, but why

**Comment by Devnol** [comment]
Urls are uwu'd too breaking a large amount of the project. Please fix.

**Comment by Devnol** [comment]
Actually the entire project is broken because non-string elements are also uwuified rendering them invalid unless ran using a modified nowodejs  interpreter and typescwipt compiler. Please either revert non-string elements or create such a js interpreter and ts compiler.

**Comment by elegantShock2258** [comment]
> 
> My man!
> 
> UwU 
> 
> Great effort, but why 

why are you running nautilus as root?

**Comment by sudo-nautilus** [comment]
> > 
> > My man!
> > UwU 
> > Great effort, but why 
> 
> why are you running nautilus as root?

I was lacking for a better username btw

**Comment by elegantShock2258** [comment]
> > > 
> > > My man!
> > > UwU 
> > > Great effort, but why 
> > 
> > 
> > why are you running nautilus as root?
> 
> I was lacking for a better username btw

Please don't do it irl

**Comment by sudo-nautilus** [comment]
> > > > 
> > > > My man!
> > > > UwU 
> > > > Great effort, but why 
> > > 
> > > 
> > > why are you running nautilus as root?
> > 
> > 
> > I was lacking for a better username btw
> 
> Please don't do it irl

Hmmm interesting

**Comment by rojserbest** [comment]
Yaykrosoft

**Comment by techno-arch** [comment]
there is a reason god is in his heaven

**Comment by ItzOnlyAnimal** [comment]
what the fuck HAHAHHAHA

**Comment by robiot** [comment]
Now this is a real pr xd

**Comment by ahnaf-zamil** [comment]
What a PR, I hope they push this code to production. We will get UwU Studio Code XD

**Comment by ProDev76** [comment]
the jr engineer of facebook has arrived.

**Comment by elegantShock2258** [comment]
> the jr engineer of facebook has arrived.
HOW THE HELL DID YOU FIND THIS JIM!! I TOLD YOU ABOUT THIS AFTER THE MEETING!!

**Comment by ProDev76** [comment]
> > the jr engineer of facebook has arrived.
> 
> 
> 
> HOW THE HELL DID YOU FIND THIS JIM!! I TOLD YOU ABOUT THIS AFTER THE MEETING!!

https://user-images.githubusercontent.com/70071615/137471340-d8d79516-ab05-44ca-a157-a160b9fc6149.mp4

**Comment by sudo-nautilus** [comment]
> > > the jr engineer of facebook has arrived.
> > 
> > 
> > HOW THE HELL DID YOU FIND THIS JIM!! I TOLD YOU ABOUT THIS AFTER THE MEETING!!
> 
>  video0_2.mp4


https://user-images.githubusercontent.com/78522210/137568370-2d343db3-584f-4bb5-a1f5-51865c9279e6.mp4

**Comment by ProDev76** [comment]
> 
> 
> Don't worry someone already made... it?... https://twitter.com/uwu_net

We need a .uwu gTLD

**Pull request closed without merging**
