### PR TITLE
Update markdown.code-snippets

### PR DESCRIPTION
**Pull request by Jack-Works**
Add a Markdown snippet for table

### CODE REVIEW

**Comment by mjbvz** [comment]
Would this be better left up to extensions? An extension could provide snippets for all different markdown table sizes, instead of only 3x3 tables

**Comment by Jack-Works** [comment]
so is there a plan to add that to the markdown plugin?🤔

**Comment by mjbvz** [comment]
No, it's a good candidate for an extension though. First check to see if such an extension already exists. If not, you may want to try creating it

**Comment by mjbvz** [comment]
Closing this as an extension candidate

**Pull request closed without merging**
