### PR TITLE
Support extending icon themes

### LINKED ISSUE #14662: [file icons] Adding default fileicon support to language contributions
It would be nice if extensions could specify custom file icons for the
file types it supports. For visual consistency this could be implemented
to only be used as a fallback if the user's selected theme does not specify
an icon.

### PR DESCRIPTION
**Pull request by SPGoding**
This PR resolves #14662.

It enables extension authors to extend existing icon themes. I chose not to go with [the "default icon" idea](https://github.com/Microsoft/vscode/issues/14662#issuecomment-477725268) proposed by [sentry07](https://github.com/sentry07), as (from my point of view) it's more complicated to implement and only provides a subset of [the features which this PR adds](https://github.com/Microsoft/vscode/issues/14662#issuecomment-473921069).

This is my first time contributing real changes to VS Code, so I apologize in advance for any hacky implementation/negligence ;)

# Changes

A new optional property named `extends` is added under [`contributes.iconThemes[]`](https://code.visualstudio.com/api/extension-guides/file-icon-theme).
When `extends` is present, the value of `label` is ignored as extenders won't be shown in icon theme list at all.

```json
{
	"contributes": {
		"iconThemes": [
			{
				"id": "general-extender",
				"path": "./general-extender-icon-theme.json",
				"extends": {
					"all": true
				}
			},
			{
				"id": "vs-seti-extender",
				"path": "./vs-seti-extender-icon-theme.json",
				"extends": {
					"ids": [
						"vs-seti"
					]
				}
			},
			{
				"id": "i-dont-know-why-but-you-can-do-this-extender",
				"path": "./i-dont-know-why-but-you-can-do-this-icon-theme.json",
				"extends": {
					"all": true,
					"ids": [
						"vs-seti"
					]
				}
			}
		]
	}
}
```

- `extends`
	- `all`: Whether to extend all icon themes generally or not. Defaults to `false`.
	- `ids`: Ids of file icon themes that should be extended specifically.

## Extending Generally

When the extender is extending another icon theme because and only because `"all"` is set to `true`, the following properties in the extender will be ignored:
- `file`
- `folder`
- `folderExpanded`
- `rootFolder`
- `rootFolderExpanded`

The following properties in the extender will be merged into the icon theme if and only if the icon theme already contains specific folder icons:
- `folderNames`
- `folderNamesExpanded`

The following properties in the extender will be merged into the icon theme if and only if the icon theme already contains specific file icons:
- `languageIds`
- `fileExtensions`
- `fileNames`

Things under `light` and `highContrast` are merged using the same strategy.

Properties in `iconDefinitions` and `fonts` are always merged.

Note: the extender cannot override existing associations/definitions in other icon themes when extending generally.

## Extending Specifically

When the extender is extending other icon themes because the IDs of those themes are specifically listed in `ids`, there are no limits like the ones shown in [Extends Generally](#Extends-Generally).
The extender is free to override existing associations and definitions in the listed themes.

## Conflicts

When multiple extenders are extending the same icon theme with the same association, the one extending specifically wins.
If multiple extenders are extending specifically, or if all of the extenders are extending generally, there's no guarantee on who will win.
Therefore, it's not encouraged to extend existing icon themes to add icons for popular languages.

# To Test

I couldn't find existing tests for the icon theme feature, and also couldn't figure out how to add tests for the `extends` feature... I have a stupid manual test environment set-up at [here](https://github.com/SPGoding/vscode-icon-theme-extender-tester).

# Thanks

Thank everyone from #14662 who provided really helpful information and/or thoughts!

### CODE REVIEW

**Comment by aaronfranke** [comment]
Does this mean that `"all": true` has the behavior described in this comment? https://github.com/microsoft/vscode/issues/14662#issuecomment-477725268

**Comment by SPGoding** [comment]
> Does this mean that `"all": true` has the behavior described in this comment? [#14662 (comment)](https://github.com/microsoft/vscode/issues/14662#issuecomment-477725268)

Yes, with the limitations mentioned by aeschli at [here](https://github.com/microsoft/vscode/issues/14662#issuecomment-558191061) implemented.

**Comment by hugonteifeh** [comment]
Any news on this?

**Comment by JiriTrecak** [comment]
Any news on this? This would make adding new language-specific icons a breeze when your extension is providing the language implementation itself before the language becomes more mainstream, for example. Good job on this PR @SPGoding , really well done

**Comment by aeschli** [comment]
Thanks @SPGoding for taking the time. The implementation it is simple and pragmatic, that's great. But for my taste the feature is too generic.

I'd prefer a more targeted solution along the lines of a icon contribution and a default icon association, similar as seen here: https://github.com/Microsoft/vscode/issues/14662#issuecomment-477725268
I have planned such a icon contribution point for https://github.com/Microsoft/vscode/issues/14662 and the default language extension would be good fit for that.
There's already the an icon registry (https://github.com/microsoft/vscode/blob/master/src/vs/platform/theme/common/iconRegistry.ts) and what's missing is a the code that wires it up an extension point, similar to https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/themes/common/colorExtensionPoint.ts

**Comment by SPGoding** [comment]
Would you like to see a PR for that?

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/114942 is issue for the registry.
Thanks for offering help. I think I can work on the next week, that will be easier.

**Pull request closed without merging**
