### PR TITLE
chat - track most recent code editor as context

### PR DESCRIPTION
**Pull request by bpasero**
fix https://github.com/microsoft/vscode-copilot/issues/9410

### CODE REVIEW

**Review by roblourens — COMMENTED** [review]
Running this, I see that if some visible but not focused editor is being used for implicit context, and I click the x to close that tab, then implicit context still shows that closed file. What event do we have to listen to in order to update in that case?

**Comment by roblourens** [comment]
Also, if I have a chat editor, I wanted to find the most recently focused editor. 


image

I think I previously tried to use `getEditors` for this but I think there's no way to get the selection or visible region, is there?

**Review by roblourens — APPROVED** [review]

**Comment by bpasero** [comment]
> Running this, I see that if some visible but not focused editor is being used for implicit context, and I click the x to close that tab, then implicit context still shows that closed file. What event do we have to listen to in order to update in that case?

@roblourens good catch, we need to use `onDidVisibleEditorsChange` in that case, I have a new PR: https://github.com/microsoft/vscode/pull/233173

> Also, if I have a chat editor, I wanted to find the most recently focused editor.
> 
> I think I previously tried to use `getEditors` for this but I think there's no way to get the selection or visible region, is there? Where is that stored when the editor is not open?

@roblourens yes, `getEditors` gives you all opened tabs, either visible or not. But tabs that are not active will just carry their `URI`, but no model because we only ever have 1 model for the visible editor (if its a text editor). So if we have support for implicit context that is just `URI` based, we could adopt this.

One somewhat hacky way we could do is to peek into the view state that is associated with an editor, because we do keep the selection as state in the editor memento, do you think that would be feasable?

**Comment by roblourens** [comment]
> because we do keep the selection as state in the editor memento, do you think that would be feasable?

No clue 😅 where is that stored, is it even readable externally? Or I could try to cache all of this for previous tabs externally, or fall back to just doing the URI without selection/viewport info.

**Comment by bpasero** [comment]
Yeah, its currently not accessible but with some engineering could probably be made accessible. A fallback to just `Uri` would be a good intermediate step.

**Comment by roblourens** [comment]
Yeah. I can do the Uri for now

**Pull request merged**
