### PR TITLE
Include tilde (~) in markdown syntax tokens

### LINKED ISSUE #146219: vscode API bug: MarkdownString appendText does not escape tilde
Does this issue occur when all extensions are disabled?: N/A (Extension API bug)

- VS Code Version: 1.64.2
- OS Version: Linux x64 5.13.0-37-generic snap

MarkdownString appendText should be escaping `~` so it doesn't interpret it as strike-through.

Example code:
```js
text = '~Path/~etc-XY.txt'; // renders wrong, with strikethrough
text = 'a://example.com/~Path/~etc-XY.txt'; // renders wrong, with strikethrough
text = 'https://example.com/~Path/~etc-XY.txt'; // no strikethrough, but linkified (expected behavior?)
return new vscode.MarkdownString().appendText(text);
// show it, for example, in a hover provider
```

It renders like:
~Path/~etc-XY.txt
a://example.com/~Path/~etc-XY.txt

When it should be:
\~Path/\~etc-XY.txt
a://example.com/\~Path/\~etc-XY.txt
(I escaped it with `\~` here on GitHub)

Also, I find it strange that appendText can be linkified automatically on URLs.
If this is expected behavior, this should be documented (but it should NOT be!).
I think the proper thing would be to escape URLs as well, so it's not linkified:
https\://example.com/~Path/~etc-XY.txt
(here in GitHub, I can escape it by replacing `:` with `\:` or by adding a comment `<!---->:`)

### PR DESCRIPTION
**Pull request by babakks**
This PR fixes #146219

### CODE REVIEW

**Comment by geekley** [comment]
@babakks Shouldn't `:` and `;` be backslash-escaped as well? To prevent links and HTML character entities from being treated specially? E.g.:
```md
https\://example.com
&amp\;
```
https\://example.com
&amp\;

**Comment by geekley** [comment]
Also, IMO `\n` would be better escaped by "&nbsp; \n" (2 spaces then newline) rather than "\n\n" (2 newlines).
The former makes a newline, the latter starts a new paragraph (this distinction doesn't seem to exist in github-flavored markdown, since it treats every newline as a newline; but it does in classical/vscode markdown).

Though I admit this is minor and also debatable.

**Comment by babakks** [comment]
@geekley I see your point, but I think we'd better off stick with the standard markdown definition on escapable characters ([here](https://daringfireball.net/projects/markdown/syntax#backslash)) which does not include `;` or `:` (though, for example, Github supports escaping them).

**Comment by geekley** [comment]
@babakks 
OK, but that definition doesn't include `~` either. In fact `~` is not special in original markdown, so VSCode is using some other "flavor". And I did test all three backslash-escaping chars in VSCode and they do work.

If you want to ensure reliable behavior, you'd have to know which markdown spec VSCode actually uses. I assume it's likely it may be using CommonMark, which is a much more ["proper"](https://commonmark.org/#why) standard than the original -- and, at least on latest version I saw now, it does include escaping for those characters and many others as you can see here:
https://spec.commonmark.org/0.30/#backslash-escapes

If you still don't want to rely on backslash escaping, there's also the option of preceding them with a comment (I tested that too on all three): `<!---->:` and `<!---->;`
In the `~` case, it also did seem to work, but if you want to be extra safe it might be prudent to surround it on both sides (since it can be used on start or end of strikethrough): `<!---->~<!---->`

But I think the best solution would be confirming whether it's using CommonMark and which version, and then include all escaping of that spec's version, specially because we may be missing some other edge cases.

**Comment by geekley** [comment]
Ah OK, VSCode API does state that it's using CommonMark:
`@types/vscode v1.65.0 index.d.ts`
```js
    /**
     * Human-readable text that supports formatting via the [markdown syntax](https://commonmark.org).
     *
     * Rendering of {@link ThemeIcon theme icons} via the `$(<name>)`-syntax is supported
     * when the {@linkcode supportThemeIcons} is set to `true`.
     *
     * Rendering of embedded html is supported when {@linkcode supportHtml} is set to `true`.
     */
    export class MarkdownString {
```
So, the full list of chars should be:
```
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```
\!\"\#\$\%\&\'\(\)\*\+\,\-\.\/\:\;\<\=\>\?\@\[\\\]\^\_\`\{\|\}\~

**Comment by babakks** [comment]
@geekley I think you're right. it makes sense to update the character set.

@jrieken Do you agree?

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
I generally agree but let's keep this PR focused on the ~ issue

**Review by sandy081 — APPROVED** [review]

**Comment by geekley** [comment]
> I generally agree but let's keep this PR focused on the ~ issue

@jrieken @babakks Is there an open issue/PR for the rest of the CommonMark chars that should be escaped, so that I can subscribe to it?

**Pull request merged**
