### PR TITLE
hide git ignored files in explorer

### PR DESCRIPTION
**Pull request by sohailrajdev97**
As suggested by @isidorn, creating an empty pull request to discuss possible solutions for #38878. Once we finalize a solution, changes will be pushed to this PR.

### CODE REVIEW

**Comment by isidorn** [comment]
1. I suggest to introduce a new setting which would control this
2. This would need to be contributed from the Git extneisons and I believe this is the copmlicated part, because the Explorer currently has not notion of Git

Actually using an extension which updates the files.include setting might be the way to go here for now.
Though let's ping @joaomoreno for potential ideas.

As a code pointer here's a [FilesFilter](https://github.com/microsoft/vscode/blob/bddccf854580a3c6eac972233dcd969a05b9a35f/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L502) though the issue is that he can not have any knowledge of Git.

**Comment by joaomoreno** [comment]
Yeah this is problematic and not related to SCM. We would need a contribution story for exclusion lists. Maybe @jrieken and @bpasero has seen such request in the past?

**Comment by isidorn** [comment]
We also have request from Working Sets extension for exclusion lists. But for now we thought to go with the approach that setting update `files.exclude` and we potentially introduce setting out of workspace.

**Comment by isidorn** [comment]
Since this discussion did not get far I am clsoing this PR as out of scope

**Pull request closed without merging**
