### PR TITLE
fix(quickinput): make `inputBox.enable` work

### LINKED ISSUE #69441: VSCode API: InputBox.enabled doesn't work
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create basic extension with `yo code`
2. Add code which shows inputbox and set `enabled=false`: 
```typescript
let input = vscode.window.createInputBox();
input.enabled = false;
input.show();
```
3. VSCode allows input despite `enabled` setting for the input.

### PR DESCRIPTION
**Pull request by devanshj**
Fixes #69441

How to test:
1. Follow steps for reproduction given in the issue
2. Check if the input is disabled
3. Find out in what case the input was getting focused out which led [this commenting](https://github.com/microsoft/vscode/commit/edb49f690017abfbae10370750f6494f5fee6732#diff-5fda188a521639e37ab9524324510e25R1069), check if the input is not getting focused out in that case.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Hi @devanshj! Sorry this sat for so long. I'm taking over as owner of the quick pick and I'd like to get a better understanding for why you made the changes you did. Do you think you could give me an overview?

**Comment by devanshj** [comment]
Hi Tyler! No problems it's OSS after all haha, better late than never. I'm sorry too I missed this notification.

Sure I can give you the context (afaict)
Our issue was that setting `input.enabled = false;` wasn't getting propagated to the dom input. That's because this was commented...
https://github.com/microsoft/vscode/blob/558b08e79054aadad9580e5fe9960987c50f5f29/src/vs/base/parts/quickinput/browser/quickInput.ts#L1620
As the comment says it was done to avoid losing focus and it loses focus because of...
https://github.com/microsoft/vscode/blob/558b08e79054aadad9580e5fe9960987c50f5f29/src/vs/base/browser/ui/inputbox/inputBox.ts#L321
So to not avoid losing focus (perhaps for a11y reasons) the author via commenting stopped the propagation of `enabled` to the dom ui, which basically was a bad fix that resulted in our original issue as a regression.

So my PR first reverts the bad fix and uncomments it and then uses a flag for to avoid losing focus in our case. I could have removed `this.blur()` altogether but the inputbox ui is used literally everywhere and not only in quickinput so I didn't have the context why `this.blur()` was written in the first place and I'm pretty sure there must have been a reason, hence instead of removing it altogether I made a flag especially for quickinput's consumption. And not only that I had to make sure the flag is backwards compatible (meaning `undefined` should result in blurring as it'll be `undefined` in other places of inputbox consumption) hence such naming and convention.

I hope all this makes sense.

> I'm taking over as owner of the quick pick

Nice! I'm a little familiar with this area of the codebase, I'll see if I can get back to closing some issues. I might help you more if my PRs get merged quickly \*nudge\* \*nudge\* :P haha kidding take your time!

**Comment by TylerLeonhardt** [comment]
Ok I've thought about this some more and think there are a couple things that need to be explored:

1. Uncommenting out the code and doing nothing else - I'm not convinced there's a problem with loosing focus when disabled
2. I only saw 2 other references of `InputBox#disable()` in the Find and Replace widget that @rebornix owns. We chatted and said that we could put a `inputbox.blur()` call right above the `inputbox.disable()` calls and then remove the call to `blur()` from `InputBox#disable()`.

But yeah I really wanna be proven that the focus is needed because I personally don't understand why it would still need focus if it's being disabled. The only thing I can think of is that the quickpick disappears if the input box looses focus but I haven't tested it.

@devanshj can you give this a try? Try using a purely uncommented disabled in your scenario and see if there's any negative to having the blur get called. Make sure to try it with a multi-step quick pick too as the commit it was commented out was around the time that multi-step was added.

If you want to go the extra mile to see how a screen reader reads this disablement, I think that would also be very very good information.

Sorry your PR has been opened a while but I promise to work towards getting this in!

**Comment by chrmarti** [comment]
@TylerLeonhardt What about the case where the extension first disables and then enables the widget again? Wouldn't you in that case expect the focus to be restored on the input box? Maybe this can be addressed in the `InputBox` widget better than I did by commenting that line.

**Comment by devanshj** [comment]
Hi @TylerLeonhardt I understand this PR still requires some work from my side but quite frankly I don't have the bandwidth right now sorry! But no worries no pressure to get this in, you can even put this in the backlog if you wish and we can get back to this when I have some time (maybe after a week or two can't commit though). If you can take this forward by yourself that works too.

Some quick remarks from my side if they help
- +1 on removing `blur()` from `disable()` call, focus and disability aren't very strongly coupled semantically, it makes more sense that they are handled separately userland.
- Although I can't prove it now but I strongly think there must be issues with the input getting blurred when disabled or else there wouldn't be a reason to comment that line. Needless to say we should be concrete about it on why it's needed before proceeding further.

I'll get back to this as soon as I can, cheers!

**Comment by TylerLeonhardt** [comment]
I ended up fixing this at some point in https://github.com/microsoft/vscode/pull/163739

**Pull request closed without merging**
