### PR TITLE
do not implicitly add `onTaskType:x` activation events for extensions which contribute a task of type `x`

### LINKED ISSUE #192043: VS Code 1.81.1 starts *all* onTaskType extensions when debugging
This issue is to ressurrect #175821 which was fixed, then closed, then reverted without comment.

The issue remains in 1.81.1. Attempting to run any task loads ALL extensions.

For example, for me it loads PlatformIO, Rust Analyzer, etc. when I'm working on a C project.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.1
- OS Version: Linux

Steps to Reproduce:

1. See #175821

### PR DESCRIPTION
**Pull request by meganrogge**
fix #192043

see https://github.com/microsoft/vscode/issues/192043#issuecomment-2233904025

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Is this a breaking change and/or need doc updates?

**Comment by meganrogge** [comment]
This implicit activation wasn't ever documented - which likely added to the confusion. I also don't see the `onTaskType` activation event in general documented https://code.visualstudio.com/api/references/activation-events.

**Comment by roblourens** [comment]
Wow, that list is really out of date and it doesn't say anything about implicit activation events

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode-docs/issues/7446 to fix that

**Pull request merged**
