### PR TITLE
Add command 'explorer.selectedFiles' #3553

### LINKED ISSUE #3553: Get selected file/folder in the explorer view
It would be nice if it was possible to retrieve the selected file/folder in the explorer view. The use where I want to use it is for my `vscode-yo` extension to be able to run the generator in the selected directory. An API for this would be nice.

### PR DESCRIPTION
**Pull request by QoobIY**
This improvement allows you to get the URI of the selected files in explorer

This PR fixes #3553

### CODE REVIEW

**Comment by moshfeu** [comment]
Is it common to have a **command** to **get** information? I meam, what will happen if it been called from the command palette?

**Comment by QoobIY** [comment]
> Is it common to have a **command** to **get** information? I meam, what will happen if it been called from the command palette?

It will return the same thing that would come to registerCommand (https://code.visualstudio.com/api/references/vscode-api#commands.registerCommand) as the second argument if the context menu was called in explorer.  (list of URIs of selected files in explorer)

**Comment by isidorn** [comment]
Thanks for your PR, however this is not how we would tackle that feature request.
Ideally we would introduce real API. Having a command is a workaround which we currently do not want to have.
Thus for now assigning this PR to the backlog and we have no plans to merge it in.

**Comment by QoobIY** [comment]
> Thanks for your PR, however this is not how we would tackle that feature request.
> Ideally we would introduce real API. Having a command is a workaround which we currently do not want to have.
> Thus for now assigning this PR to the backlog and we have no plans to merge it in.

I can add it to api, tell me only in which of the object

**Comment by isidorn** [comment]
We do not want to add it to the API just yet. Once we decide to do that it has to go through our API discussion process.

**Comment by moshfeu** [comment]
@isidorn is there ETA?

**Comment by isidorn** [comment]
No. Backlog means no plans to tackle this at the moment.

**Comment by isidorn** [comment]
No plans to merge, thus closing.

**Pull request closed without merging**
