### PR TITLE
Allow a task to execute an extension command.

### PR DESCRIPTION
**Pull request by GabeDeBacker**
#63153 

Creates a mechanism for allowing an extension to define a task that actually executes an extension command.

This pull request is just to gather some initial feedback.

The implementation is not yet done.

What needs to be considered:
1) Cancellation support when an extension command is running as a task
2) Allow a task to be defined in JSON (update the JSON schema)
3) Reconcile a task-definition's properties with "options" that can be specified by a task provider.
4) And more that I may be missing..

### CODE REVIEW

**Comment by roblourens** [comment]
Is there an issue for this? Has it been discussed with anyone?

**Comment by GabeDeBacker** [comment]
>           Is there an issue for this? Has it been discussed with anyone?

This is being discussed with @dbaeumer in an offline email thread. No issue has been opened yet. This PR is for preliminary thinking only.

**Comment by dbaeumer** [comment]
@GabeDeBacker thanks for the PR. I am very busy the next couple of days. I will not find time before next week. Sorry for that.

The underlying issue for the PR is: https://github.com/Microsoft/vscode/issues/11396

**Comment by dbaeumer** [comment]
@GabeDeBacker Look quickly at the terminal changes. They should come as a separate PR since I think they do make sense in isolation and are useful for other tasks.

**Comment by GabeDeBacker** [comment]
Abandoning this branch, doing work in a new branch.

**Comment by imuni4fun** [comment]
I am trying to chain 3 manual steps together for building documentation:
- Run C# script using **oleg-shilo.cs-script** (VS Code command)
- Export markdown to html using **yzane.markdown-pdf** (VS Code command)
- Run C# script to fix plantuml urls using **oleg-shilo.cs-script** (VS Code command)

I am hoping to have this in a task in tasks.json.  This sounds like it may give the ability to do that.  At the moment, I have to have the correct file open in the editor for the run commands to work.  Perhaps that can be passed as an arg to the command or maybe there is an "open file" command in VS Code that could be put in this sequence.  Just throwing it out there for use-case consideration.

**Pull request closed without merging**
