### PR TITLE
chore(ci): prevent ci from running on fork

### PR DESCRIPTION
**Pull request by btea**
The scheduled ci tasks in the fork repository will always fail to execute, and then my mailbox will receive a lot of failure reminder emails.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Here's how I deal with it:

image

**Comment by btea** [comment]
@gjsjohnmurray Looks good, thanks for the reminder.

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray Looks good, thanks for the reminder.

👍 - and it's a recommendation at https://github.com/microsoft/vscode/wiki/How-to-Contribute#getting-the-sources

**Comment by btea** [comment]
Thanks, I didn't notice this before, I will close this pr.

**Pull request closed without merging**
