### PR TITLE
themes - ColorScheme support (#105715)

### PR DESCRIPTION
**Pull request by bpasero**
This PR is for #105715

### CODE REVIEW

**Comment by aeschli** [comment]
Looks good. Instead of the new enum `ColorScheme` can we use the theme types we already have:
https://github.com/microsoft/vscode/blob/57e9e1ad6076f1fa8b7216dfd95879ec714ce6aa/src/vs/platform/theme/common/themeService.ts#L72?

I'm ok to rename ThemeType to ColorScheme.

**Comment by bpasero** [comment]
@aeschli yeah I thought about that too, but wasn't sure if `electron-main` should have a dependency to `themeService`. Are you ok if I still keep the type in `common/window.ts`?

**Comment by aeschli** [comment]
What If I extract it to `vs/platform/theme/common/colorSchemes.ts` ?

**Comment by bpasero** [comment]
@aeschli yeah sounds good with me, even `vs/platform/theme/common/theme.ts` would work.

**Pull request merged**
