### PR TITLE
rename splitview panels to panes

### PR DESCRIPTION
**Pull request by sbatten**
Refs #85164 

1st commit does symbol renaming and updates css values
2nd commit renames files to avoid confusion

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]

**Comment by isidorn** [comment]
Great changes! Approved.
You just missed one place 
https://github.com/Microsoft/vscode/blob/65050271c24788f74456cc9210931dbecf9c79c5/src/vs/workbench/browser/parts/views/customView.ts#L46
`CustomTreeViewPanel` should be `CustomTreeViewPane`

Love this
Screenshot 2019-11-20 at 10 57 57

**Review by isidorn — APPROVED** [review]

**Comment by joaomoreno** [comment]
@isidorn 

This is still true in `master`, without @sbatten's changes:

Screenshot 2019-11-20 at 10 57 57

The splitview doesn't know anything about panels.

**Comment by isidorn** [comment]
@joaomoreno ok. My bad. However I also checked full text search in other areas and it looks much better

**Review by sandy081 — APPROVED** [review]

**Comment by sandy081** [comment]
👏 ✅

**Pull request merged**
