### PR TITLE
Fix cannot specify custom path for built-in profiles on Windows

### PR DESCRIPTION
**Pull request by dan-petty**
Fix paths misconfigured if build-in profile with same name exists

### CODE REVIEW

**Comment by dan-petty** [comment]
https://github.com/microsoft/vscode/issues/161219

**Comment by dan-petty** [comment]
@microsoft-github-policy-service agree

**Comment by dan-petty** [comment]
To test set a custom path for "Git Bash" profile in settings.json:
```
    "terminal.integrated.profiles.windows": {
        "Git Bash": {
            "path": "C:\\custom\\path\\to\\git\\bin\\bash.exe"
        }
    }
```

**Review by Tyriar — APPROVED** [review]
I have a little trouble reproducing, I think because the git bash source picks up my install, but this fix looks good and safe 👍

**Review by meganrogge — APPROVED** [review]

**Pull request merged**
