### PR TITLE
Dragging an active view between side bars or panel does not activate it (fix #231922)

### LINKED ISSUE #231922: Dragging an active view between side bars or panel does not activate it
Steps to Reproduce:

1. move an active view (such as Chat) to the secondary sidebar where there are already views

=> 🐛 the view moves but not as active view

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Comment by benibenj** [comment]
Just to clarify, the title of the PR/Issue is `Dragging an active view between side bars or panel does not activate it`, however, this will cause any drag and drop between different locations to activate the container, no matter if the container was active before. I do believe this is the ideal behaviour, but just want to point this out because the title of the PR talks about a different behaviour.

**Comment by bpasero** [comment]
Yeah you are right! And I think that is OK behaviour.

We are even a bit inconsistent here: tabs open before you begin to drag, while views actually do not.

**Review by benibenj — CHANGES_REQUESTED** [review]
The DnD behaviour is not consistent anymore. DnD an inactive view between different side bars will cause it to activate, however, Dnd inside the same side bar will not cause it to activate.

Also, if we always want the view to activate on drop, I think we should already activate it on drag start

**Comment by bpasero** [comment]
@benibenj pushed a fix. I think we should not make a view active on drag start because that makes it harder to drop it into the current view to split it.

**Review by benibenj — APPROVED** [review]

**Review by benibenj — APPROVED** [review]

**Pull request merged**
