### PR TITLE
CodeActionProvider.providedKinds

### PR DESCRIPTION
**Pull request by mjbvz**
Adds a new optinal `providedKinds` property on `CodeActionProvider`. This is a list of `CodeActionKinds` that the provider may return. The list will be used for deciding when to show the `refactor` and `source action` context menus. It is not used for filtering the returned code actions

Possibly helps address #45383

### CODE REVIEW

**Comment by jrieken** [comment]
We pass this information along the register-call because that makes it clear that those cannot change. Making it a property, apart from being different to other places, makes this harder to watch

**Comment by DanTup** [comment]
There's no milestone on this but the changes are in vscode.d.ts - I presume this plans to ship in 1.23?

**Comment by DanTup** [comment]
@mjbvz Is it possible to change the label that appears for "Organize Imports"? It doesn't seem to use the name form the Code action (in the palette). For ex in Dart we call it "Organize Directives" and I guess C# calls it [`Organize Usings`](https://blogs.msdn.microsoft.com/zainnab/2010/06/29/organize-usings-c-only/).

**Comment by mjbvz** [comment]
The command itself is called organize imports for consistency across languages. However the code action entry in the `source` context menu will show whatever name you put on on the code action.

**Pull request merged**
