### PR TITLE
Allow action labels to be long in comment header

### PR DESCRIPTION
**Pull request by alexr00**
Part of #164288

### CODE REVIEW

**Comment by alexr00** [comment]
@jrieken, was it your intent https://github.com/microsoft/vscode/commit/b77a8910a181e17af4d1f6a77100f5e227ed9f1d that all menu bars not allow actions to be larger than an icon?

**Comment by jrieken** [comment]
> @jrieken, was it your intent with https://github.com/microsoft/vscode/commit/b77a8910a181e17af4d1f6a77100f5e227ed9f1d that all menu bars not allow actions to be larger than an icon?

The opposite in fact. Label-only actions should get the same layout logic as normal icons - take the width they need and be properly aligned. I believe you suffer from setting an explicit width here: 
https://github.com/microsoft/vscode/blob/84a929b8b7ea25af7f2c5fb4e76b6a65028a7a6c/src/vs/workbench/contrib/comments/browser/media/review.css#L361

**Review by jrieken — COMMENTED** [review]
Not setting explicit widths might be a better fix here

**Comment by alexr00** [comment]
Glad I checked. Removing the width does seem like a better fix.

**Review by jrieken — APPROVED** [review]

**Pull request merged**
