### PR TITLE
chore: update node-pty@0.11.0-beta27

### PR DESCRIPTION
**Pull request by deepak1556**
Breaking out the relevant change from https://github.com/microsoft/vscode/pull/166430

### CODE REVIEW

**Comment by deepak1556** [comment]
Build triggered: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=199872&view=results

**Comment by Tyriar** [comment]
Oh yeah, then there's distro complications you need to fix and it ends up failing: https://github.com/microsoft/vscode/pull/170123

**Comment by Tyriar** [comment]
FYI it was this PR that broke us updating: https://github.com/microsoft/node-pty/pull/487

**Comment by deepak1556** [comment]
Thanks for the context, I will investigate the failures today.

**Comment by deepak1556** [comment]
Turned out to be a packaging issue which is why the issue was isolated to product builds, the new helper executable was ignored because of missing file extension.

**Comment by deepak1556** [comment]
Builds are green : https://monacotools.visualstudio.com/Monaco/_build/results?buildId=200022&view=results

**Comment by deepak1556** [comment]
I reverted the distro change to make it easier for merge, will perform the changes in `vscode-distro` branch post merge.

**Review by bpasero — APPROVED** [review]

**Comment by Tyriar** [comment]
Thanks @deepak1556!

**Pull request merged**
