### PR TITLE
Emmet: canceling wrap shouldn't add tab to the active editor

### PR DESCRIPTION
**Pull request by mrmlnc**
Source: #8450

Before:

After

### CODE REVIEW

**Comment by mrmlnc** [comment]
Works fine with HTML and other syntaxes that are supported by Emmet, but does not work with files with `plain text` syntax and syntaxes that are nor supported by Emmet.

**Comment by egamma** [comment]
@mrmlnc Thanks for the PR. If refactored the implementation so that there this special casing on the actionId is no longer needed.
```json
		if (actionId === 'editor.emmet.action.expandAbbreviation') {
			this.editor.trigger('emmet', Handler.Tab, {});
		}
```
The solution was to move the noEpansionOccurred from the EditorAccessor to the EmmetAction base class. The method is then overridden for the ExpandAbbreviation action.

**Comment by mrmlnc** [comment]
@egamma Great idea :tada:

**Comment by mrmlnc** [comment]
@egamma, but we have a problem:
```
*** Error: /src/vs/workbench/parts/emmet/node/actions/base64.ts(81,24): Property 'noExpansionOccurred' does not exist on type 'EditorAccessor'.
*** Error: /src/vs/workbench/parts/emmet/node/actions/updateTag.ts(38,24): Property 'noExpansionOccurred' does not exist on type 'EditorAccessor'.
*** Error: /src/vs/workbench/parts/emmet/node/actions/wrapWithAbbreviation.ts(38,24): Property 'noExpansionOccurred' does not exist on type 'EditorAccessor'.
*** Finished with 3 errors.
```

**Comment by egamma** [comment]
hmm, looks like the incremental compile didn't flag this, let me fix that

**Comment by egamma** [comment]
pushed a fix

**Pull request merged**
