### PR TITLE
Fix 63749 - Markdown, U+2028, and "Go to Symbol in File..."

### LINKED ISSUE #63749: Bug: Markdown, U+2028, and "Go to Symbol in File..."
Suppose you take the following file, except that the line containing `foo` also contains `U+2028` somewhere in it.

```markdown
# A
- foo

# B
- bar
```

`vscode` will render `U+2028` as a question mark in a diamond, and the list of symbols that appear in the 'Go to Symbol in File...'  popup will be shifted (by the number of `U+2028` characters present in the file). Screenshots that illustrate this are below.

screen shot 2018-11-25 at 19 03 03

screen shot 2018-11-25 at 19 03 08

(Why did this come up? If you triple-click ' felicita - hej! ' in [this link](https://www.residentadvisor.net/reviews/22851), and paste it into `vscode`, it actually has a pair of enclosing `U+2028` characters. It seems unique to that page...)

### PR DESCRIPTION
**Pull request by skprabhanjan**
@mjbvz , Added UNICODE_NEWLINE_REGEX to replace those characters, fixes #63749 .
Please review this and let me know if any changes are needed :)
Thanks.

PS: Unit tested for many cases with those  `U+2028` chars and it works all fine :)

### CODE REVIEW

**Comment by rebornix** [comment]
Just FYI, text buffer in VSCode/Monaco doesn't support U+2028 and U+2029 right now

**Comment by mjbvz** [comment]
@rebornix Do you recommend this workaround?

@skprabhanjan Please also add tests for this. There is skipped one already that should cover it, see 2f9f0c35ccb681f9a1ff53e7619677b00a23cb95

**Comment by skprabhanjan** [comment]
> @skprabhanjan Please also add tests for this. There is skipped one already that should cover it, see [2f9f0c3](https://github.com/Microsoft/vscode/commit/2f9f0c35ccb681f9a1ff53e7619677b00a23cb95)

Added the test. (Removed the .skip)

**Comment by mjbvz** [comment]
Thanks! The fix will be in the next VS Code insiders build and will be released with VS Code 1.30

**Comment by rebornix** [comment]
@mjbvz the change for markdown is good ;)

**Pull request merged**
