### PR TITLE
Allow to theme keybindings widgets in quick open command palette

### LINKED ISSUE #120201: Allow to theme keybindings widgets in quick open command palette
The Command Palette is almost perfect - thanks a lot!: 
it even displays **keyboard shortcuts. Unfortunately, they are sometimes not readable**:

image

According to the theme-color reference: https://code.visualstudio.com/api/references/theme-color
it is not possible to adjust the keyboard shortcut color 😞. 

Can you please allow us to configure it by something like:
```
   "workbench.colorCustomizations": {
        "[Color Scheme Name]":{
            "symbolIcon.hotkeyForeground": "#ff0011"
        }
    }
}
```

Thanks a lot, kind regards,
Thomas

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This PR fixes #120201 partially... It only fixes it for keybinding labels in the command palette and not elsewhere and also doesn't handle refresh correctly.

alt: #120588

### CODE REVIEW

**Comment by bpasero** [comment]
I suggest to take these changes over to https://github.com/microsoft/vscode/pull/120588. It makes sense to me that the widget itself defines colors that can be passed in as options with a good fallback because that is needed for the standalone editor to work where we do not have theming support (afaik).

Imho when the colors can be defined as options, we do not have to have a theming participant even.

//cc @sandy081 as widget creator

**Comment by sandy081** [comment]
Does #120588 also covers this PR right?

**Comment by bpasero** [comment]
I suggest to close this and continue in https://github.com/microsoft/vscode/pull/120727

**Comment by TylerLeonhardt** [comment]
From my 1on1 with Ben... to do this correctly:

* move colors in CSS to standalone/quickinput CSS (to support defaults for standalone editor)
* Add to existing stylesheet in base/parts/quickinput.ts similar to what I did to the ListRenderer
* Look at @bpasero's example for watermark for attachKeybindingLabelStyler for watermark, keybinding editor

**Pull request closed without merging**
