### PR TITLE
update to windows latest

### PR DESCRIPTION
**Pull request by TylerLeonhardt**

### CODE REVIEW

**Comment by deepak1556** [comment]
Thanks for looking into this @TylerLeonhardt , adding some data from my attempt previously.

You would need https://github.com/microsoft/vscode/commit/0fc82449a701d1a1807720f09f4a2279157aa859 for the tar failure.

There are some integration test failures on the `FileSearchEngine` component once you get past the above error https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142015 , didn't spend time on this.

**Comment by TylerLeonhardt** [comment]
Thanks @deepak1556! I've added your change - let's see where we are at after.

**Review by joaomoreno — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
I’m gonna open an issue on…. pipelines? I guess? Considering:
* can’t repro in Actions
* can’t repro locally
* _can_ repro in Pipelines

**Review by raghavthind2005 — APPROVED** [review]

**Comment by joaomoreno** [comment]
What's the issue?

**Comment by joaomoreno** [comment]
Interesting how it's all related to unicode file names, right? Given that everything works by spawning ripgrep with args... I suspect something in the process invocation messes up the unicode, maybe it's spawned with `shell: true` and the shell screws it up?

@roblourens Any thoughts?

**Comment by TylerLeonhardt** [comment]
ok figured it out… the version of tar that ships in the Windows image doesn’t like the unicode characters in the path… this is causing the test failures.

so Compile step targz’s it… and then Windows un-targz’s it… and in that un-targz’ing the file name is messed up.

So then the next question is………….. who’s fault is it? The windows tar expanding or the linux tar compressing and not providing enough info to the expander?

Tried a bunch of different things and no luck… opened an issue on tar:
https://github.com/libarchive/libarchive/issues/1629

**Comment by joaomoreno** [comment]
As a mitigation, could we use install _good_ version of tar?

**Review by sbatten — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Thanks for the rec to use Extract Files task @sbatten 👏  that worked nicely!

**Comment by joaomoreno** [comment]
When `num(commits) > num(lines changed)`:

gif

**Pull request merged**
