### PR TITLE
Changed brace matching style from full outlines to underlines

### PR DESCRIPTION
**Pull request by janzich**
This is to address #13379. Sometimes, I also find it difficult to see what's going on.

### CODE REVIEW

**Comment by jrieken** [comment]
@janzich This is not really adding an option

**Comment by janzich** [comment]
I know. Sorry for not making myself clear. This is supposed to address the concern in the linked issue.

I was also thinking about a background highlight (which is used by some editors and IDE's as well), but the underline was easier.

**Comment by Lusito** [comment]
Love this! Tho I guess since in Visual studio there is an option, it would be nice to have an option here as well... If possible, also add a way to completely disable it, so one can use plugins like [Rainbow Brackets](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets) instead.

**Comment by alexandrudima** [comment]
@janzich IMHO this should be implemented through custom VSCode keys in the TM themes (i.e. similar to how we read "caret" from the TM themes and generate CSS out of that), we could read more settings (if present), such as bracketMatchColor, bracketMatchStyle: "underline" | "border" | "none", etc. I'm not sure of the exact names and values they should take, but IMHO that is the way forward in changing appearance of the editor. Please let me know if you'd like to come up with a proposal for custom properties and implement it, I can help out with code pointers and ... advice :). Thank you!

**Pull request closed without merging**
