### PR TITLE
Making TM_SELECTED_TEXT snippet variable work with overtyped text

### LINKED ISSUE #62907: Preserve Current Selection when using snippet with TM_SELECTED_TEXT variable
Currently snippets with prefixes set become rather useless when they contain the selected text variable.

I have a snippet like this:
```
  "lint_checking": {
    "prefix": "lin",
    "body": [
      "//lint_checking ${1:RULE_ID} off",
      "$TM_SELECTED_TEXT",
      "//lint_checking ${1:RULE_ID} on"
    ],
    "description": "lint pragmas"
  }
```
What I want is being able to select text, start typing lin (which will of course remove the selection) and then IntelliSense will recommend lin as a completion. When I press enter I want the selection to reappear, surrounded by my snippet.

This behavior is actually standard in other editors and I was kind of surprised to find no useful way to use snippets with a completion prefix when the selction variable is being used.

If this is unwanted by some users this should be made configurable as an option, but as a hardware developer I find myself in the situation quite often where this would be useful, as such 'surrounding pragmas' are pretty common.

Another variant would be to make snippets able to be promoted to commands for the Ctrl+Shift+P command palette, so we don't have to go into the insert snippet sub palette. I do not want to assign dedicated Key Bindings, as it just becomes to much. The prefix 'is the keybinding'.

### PR DESCRIPTION
**Pull request by n-gist**
I connected it to undo edit stack.
Fixes #62907

overtyping_showcase

I added a separate variable TM_OVERTYPED_TEXT first. But then decided to combine with TM_SELECTED_TEXT with simply "if there is no selected text, try to get overtyped text from undo". This does not break the previous behavior, so existing snippets should get this option.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
I don't think this is the best approach here. Going in the undo stack to find overtyped text is IMHO too risky.

I suggest a better approach would be for the suggest controller to listen to `onWillType` (I think it does so already).

If `onWillType` fires and there are selections, the text contents of the selections can be captured. Later, if a snippet containing `TM_SELECTED_TEXT` is inserted, the captured values can be used as substitutions for `TM_SELECTED_TEXT`.

**Comment by n-gist** [comment]
Yes, it should be more correct and cleaner in code also.
Then, is it ok to produce garbage on every overtype case? Or, it should have some memory space for it, 50-100 bytes, for example, with ability to increase temporarily. One per resource?

**Comment by alexdima** [comment]
> Then, is it ok to produce garbage on every overtype case? 

I think that should be OK. The suggest controller shares the lifetime with the editor instance, so there will be only a few of those instantiated (as many as there are visible editors at the same time). In there, I think you could hold some property of the last overtyped text. @jrieken can provide better directions if he has a better place to store this in mind.

> Or, it should have some memory space for it, 50-100 bytes, for example, with ability to increase temporarily.

:+1: You could introduce a limit, like if the overtyped text is over 1 million characters, then don't store it. That would make the feature not work in that case, but I guess that is OK.

> How to detect if it expired?

Whenever the code editor gets a new model, the property should be cleared. But it should be cleared in other cases too, like explicit selection change (the selection change event from the editor has a reason that could be used for this purpose).

**Comment by jrieken** [comment]
> The suggest controller shares the lifetime with the editor instance, so there will be only a few of those instantiated (as many as there are visible editors at the same time). In there, I think you could hold some property of the last overtyped text.

You could add similar class like [this](https://github.com/microsoft/vscode/blob/dfbd59cf49ae685a09d98ff15cfa90042a3d9cff/src/vs/editor/contrib/suggest/suggestCommitCharacters.ts#L13), like `LastOverTypedInfo`-thing. Tho, I would add that into snippet land, e.g `snippetController` and only pass to the [`insert`](https://github.com/microsoft/vscode/blob/72d14ad2fb6fa9dbf9484b92f927dbf39c9d60d2/src/vs/editor/contrib/snippet/snippetController2.ts#L79)-function which indicates if the last overtyped word should be used.

**Comment by n-gist** [comment]
Wow, sorry, I didn't want that. Mixed a little with branches: / How to remove it?

**Pull request closed without merging**
