### PR TITLE
Add support for multiple rulers with different colors

### LINKED ISSUE #54312: Support multiple rulers with different colors

### PR DESCRIPTION
**Pull request by mallardduck**
This change set:

- adds an interface for Ruler Color Options,
- adds a union type of that interface and number,
- adjust the rulers type hint to use said union type,
- adds a mechanism to apply boxShadow to fastDomNode, and
- updates the way rulers are rendered to support individual colors.

I've also ensured that descriptions are provided for settings.json. So now, all nodes will provide explanations.

There may be other ways to implement adjusting the boxShadow - certainly open for input if adding the `setBoxShadow` isn't as preferred.

----

This PR fixes #54312 by allowing ruler colors to be defined in `settings.json`.

### CODE REVIEW

**Comment by methodbox** [comment]
@mallardduck
Looks like the first commit rejected. Take a look?

Thanks for doing the PR. I’m excited to use this feature!

**Comment by methodbox** [comment]
Looks like the merge failed due to a problem with the actual test, but not sure. Line 11 just says `undefined`.

```bash
Run .\scripts\test-integration.bat --tfs "Integration Tests"
Active code page: 65001
"Running integration tests out of sources."

undefined

  Search-integration

    √ Text: GameOfLife (51ms)

    √ Text: GameOfLife (RegExp) (57ms)

    √ Text: GameOfLife (unicode escape sequences)
```

**Comment by mallardduck** [comment]
@methodbox I think that's not the cause of the failure. If you check, the same test for different commits on this PR that message was being thrown in all of them without failure.

**Comment by mallardduck** [comment]
@methodbox, yeah looks fine now.

Just need someone from Microsoft to review, give feedback and/or accept it.

**Comment by mallardduck** [comment]
@connor4312 @alexdima - Hey there, I know that I read that multiple ruler colors was in a backlog for a later release point. However I'm wondering if we can get this merged in sooner than later, since I have provided a working implementation?

**Comment by alexdima** [comment]
Thank you!

**Comment by methodbox** [comment]
@alexdima

Any idea when this will make it into distributed builds?

**Comment by alexdima** [comment]
@methodbox This will make it to insiders in the next couple days (insiders is now frozen until stable is shipped), and will come to stable with the February stable release ~4weeks from nwo

**Pull request merged**
