### PR TITLE
Add unique build number per build to support fuzzy settings search

### PR DESCRIPTION
**Pull request by roblourens**
@joaomoreno I wanted to give a heads up on this change.

I'm adding a new build number which is unique for the commit built. It's based on the version number (e.g. 1.18) and the number of commits since the last tag. So if this is 1.18 and there have been 532 commits since the 1.17.0 tag, the build number will be 11800532. It goes into the product.json and the exported settings file.

I'm adding it for a couple reasons. Previously we would treat any new 1.18.0 build as the latest authoritative set, and any 1.18.0 client would get settings from that build. Not usually a big problem since this would only affect people running old versions of insiders. But this lets us serve settings for the exact build.

It also gives the remote endpoint flexibility. For example if it indexes a new build, and there is some problem with the indexing process, we can disable that new build and serve settings from the previous new build.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@roblourens We always use the commit id as a build identifier everywhere. Why don't you take that?

**Comment by roblourens** [comment]
I would prefer that too but it needs to increment per build. The database stores setting entries with a start and end build number, with any build in between containing that build. And the fallback mechanism described above needs to know what the 'previous' build was.

**Comment by joaomoreno** [comment]
OK.

Can we make this field name *very* specific to your problem? I don't want anyone else to start depending on it. Call it `settingsSearchBuildId`, for example.

Also, hope that we never reach `1.100` 😆

**Comment by roblourens** [comment]
Done. I'm also gambling that we don't have more than 10,000 commits in a release 🤔

**Pull request merged**
