### PR TITLE
actionViewItem - make sure to also set the aira-label on the label el…

### PR DESCRIPTION
**Pull request by isidorn**
Same as https://github.com/microsoft/vscode/pull/157256 just against the release branch since this is a breaking change.
I believe this is the lowest risk fix available.

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
Isn't updating of `aria-label` already done here:

https://github.com/microsoft/vscode/blob/73fd3f11032e7b83c2ae011b5516e6ddd19e3db2/src/vs/base/browser/ui/actionbar/actionViewItems.ts#L221

?

**Comment by isidorn** [comment]
@bpasero yes and same as https://github.com/microsoft/vscode/pull/157256
So that aria-label update sets the aria-label on the outer element that no longer is focused. And this PR does a minimal change to also set the aria-label on the actual element that has focus, `this.label`. So aria-label will be set on two elements instead of one, but on main we can clear this out - since I am not sure what is the inheritance structure of ActionViewItems

**Comment by bpasero** [comment]
Yeah I was thinking some cleanup could be done, e.g. some method for updating the ARIA label that then is being overridden in the subclass to apply it further.

**Comment by isidorn** [comment]
@bpasero thanks for a good suggestion. I have just updated this PR based on your feedback. Let me know what you think.

**Review by rebornix — APPROVED** [review]

**Review by bpasero — APPROVED** [review]

**Pull request merged**
