### PR TITLE
Re-render sticky scroll when line numbers display mode is changed

### LINKED ISSUE #210814: Sticky Scroll does not update when line numbers display mode is changed
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.89.0
Commit: Unknown
Date: Unknown
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.146.1-microsoft-standard-WSL2
```
Steps to Reproduce:

1. Enable sticky scroll and set line numbers to 'on'
2. Navigate to a code block that triggers one or more sticky lines
3. Change the line display mode to relative
4. Observe that the sticky line numbers do not update
5. Bonus: Specifically when switching from non-relative to relative line numbers, the sticky lines do not correctly display the relative line numbers (per #195711) as you move the cursor up and down.

This is particularly annoying when using [vscode-vim](https://github.com/VSCodeVim/Vim) with smart relative lines enabled, which toggles between absolute and relative lines depending on whether you are in insert or normal mode.

Video of repro:

https://github.com/microsoft/vscode/assets/5664347/0c04f6a3-1efb-4c9b-bf0b-7a3552d86ee3

### PR DESCRIPTION
**Pull request by timorthi**
Fixes #210814 

This forces a re-render when the line numbers display mode is updated. 

This also forces a `_readConfiguration` call when the display mode changes, as there is a listener registered in `_readConfiguration` that ensures line numbers are updated as the cursor moves while in relative display mode.

Video showing desired behavior after the changes in this PR. This video also shows smart relative lines enabled in [vscode-vim](https://github.com/VSCodeVim/Vim), which toggles between absolute and relative lines depending on whether you are in insert or normal mode:

https://github.com/microsoft/vscode/assets/5664347/2efbd386-b964-4d00-9842-fc4d06c38ed3

### CODE REVIEW

**Comment by aiday-mar** [comment]
Hi @timorthi thank you for the PR. After looking at the code, I believe the cleanest way to solve this issue would be to refactor the code so that we have a method `readConfiguration` which would read the configuration, and have another method `readConfigurationChange` which would take in the configuration change event as a parameter. Then you could write:

```
readConfigurationChange(e : ConfigurationChange) {
  this.readConfiguration();
  ...
  if (e.hasChanged(EditorOption.lineNumbers)) {
      this._renderStickyScroll(0);
  }
}
```

In this manner the readConfigurationChange method would reuse the readConfiguration method and would add additional logic on top in the form of rerendering the widget.

**Comment by timorthi** [comment]
@aiday-mar Updated!

**Comment by timorthi** [comment]
@microsoft-github-policy-service agree

**Comment by aiday-mar** [comment]
Great thanks!

**Review by aiday-mar — APPROVED** [review]

**Review by bpasero — APPROVED** [review]

**Pull request merged**
