### PR TITLE
feat: select the folding provider to use

### PR DESCRIPTION
**Pull request by daiyam**
The PR allows to select the folding provider to use. The name of the provider is the name of the extension that provides it.

It follows the recommendations of @aeschli (https://github.com/microsoft/vscode/pull/54200#issuecomment-1158712923)

### CODE REVIEW

**Review by ProKashif — DISMISSED** [review]

**Comment by gjsjohnmurray** [comment]
@aeschli will this help #138093?

**Comment by daiyam** [comment]
@gjsjohnmurray Yes, it should help in conjunction of an extension like mine ([Explicit Folding](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding)).

**Comment by daiyam** [comment]
@aeschli Hi, could you tell me if the PR needs any modifications? Thx

**Comment by daiyam** [comment]
+1

**Comment by daiyam** [comment]
@aeschli Hi, what can I do for the PR to be merged? Thx

**Comment by aeschli** [comment]
Sorry, I didn't find time yet to review the PR...

**Comment by aeschli** [comment]
I made a few changes. The problem is that the folding code is in the editor layer which does not have the concept of extensions (it is also used in the Monaco editor). So when using the extension id in the foldingStrategy setting, we have to talk about an abstract id instead of the extension id. But then users will not understand it.
-> I came up with a separate settings `editor.defaultFoldingRangeProvider` which is defined in the workbench layer

**Comment by daiyam** [comment]
@aeschli Thank you for the update.
I don't quiet understand the separation issue between the editor layer and extensions. Since `src/vs/editor/contrib/folding/browser/folding.ts` was only importing `ExtensionIdentifier` which is already imported by `src/vs/editor/common/languages.ts`.
But if I'm ok with the changes you made. It solves the current issue.

**Review by alexdima — APPROVED** [review]

**Comment by aeschli** [comment]
It's not about the import, which is fine to use, but the description of `editor.foldingStrategy`: we can'twrite that the valid settings are `indent` | 'auto` | extension-id. That sentence would not make sense in Monaco. So there's now a separate setting (`editor.defaultFoldingProvider`), only available in VS Code, used when `auto` is the folding strategy.

@daiyam Thanks for your help!

**Comment by daiyam** [comment]
@aeschli Thx

OK, I understand, Since it is a Monaco's property, it should conform to its definition (defined by Monaco).
All the while, I was trying to avoid an additional property...

**Comment by aeschli** [comment]
Its already possible to scope the setting to a specific language
```
        "[javascript]": {
                "editor.defaultFoldingRangeProvider": "aeschli.ext-foldingrangeprovider"
        }
```
And if your files represent a certain type of xml files, you could think of defining a language for it. Thats of course something a extension would have to implement and is more than just the language definition.

**Pull request merged**
