### PR TITLE
Adopt search viewlet to align with ViewsViewlet

### PR DESCRIPTION
**Pull request by sandy081**
Implement https://github.com/Microsoft/vscode/issues/70221

### CODE REVIEW

**Comment by sandy081** [comment]
@roblourens Adopted Search viewlet to align with ViewsViewlet. Please take a look.

**Comment by roblourens** [comment]
I think it's different because it's the only viewlet that also must exist in the Panel. This doesn't break that does it?

**Comment by sandy081** [comment]
No, it is different because it does not have custom views. Yes, search view exists in both sidebar and panel but not the viewlet. I refactored and separated viewlet, view and panel parts and made sure it does not break when search view is located in sidebar or panel.

**Review by roblourens — APPROVED** [review]

**Comment by isidorn** [comment]
This looks good.  @sandy081 nice job!

**Review by isidorn — APPROVED** [review]

**Pull request merged**
