### PR TITLE
Add new command to refresh outline

### PR DESCRIPTION
**Pull request by gayanper**
A new command is introduced for outline service to refresh outline
from other extensions.

### CODE REVIEW

**Comment by gayanper** [comment]
I didn't find any tests related to outline, But I feel its better if we can add one. Please guide me how to to that by pointing me to a similar tests if you think adding test would be good.

**Comment by jrieken** [comment]
@gayanper Thanks for contributing however this isn't what we are after. Extensions shouldn't have the ability to force update the outline via commands. If we agree on the need for "out of band" outline updates it should be done via a provider event (similar to existing ones)

**Comment by gayanper** [comment]
@jrieken thanks for feedback, can you point me to a existing implementation. I was not sure for what I should search for when you say "provider event", I some what new to vscode architecture :)

**Comment by gayanper** [comment]
@jrieken  Did you mean something similar to https://github.com/microsoft/vscode/blob/20bd040c95fb761b4aa13f67ea3cb70aac8cce63/src/vs/workbench/contrib/timeline/common/timeline.ts#L99 which is used in Timeline Provider ?

**Comment by jrieken** [comment]
Yes, but a better sample might be `vscode.CodeLensProvider#onDidChange`. _However_ I quite don't understand the need yet. Our assumption is that outline only changes when the underlying document changes, e.g it is a pure syntax function and without other context

**Comment by gayanper** [comment]
> Yes, but a better sample might be `vscode.CodeLensProvider#onDidChange`. _However_ I quite don't understand the need yet. Our assumption is that outline only changes when the underlying document changes, e.g it is a pure syntax function and without other context

The requirement we have in VSCode java is, we would like to have the toggle to show inherited document symbols in quick pick and outline. We thought to implement it using the LS configuration which is switched from the client. So once the LS configuration is updated, there is no way for us to notify the outline view or the quick pick to reload symbols. 

For quick pick this is some what manageable since the switching of the LS configuration will close the quick pick outline. But for the outline view it needs to be closed and open again or the document much have a change to refresh the outline.

There was a another request in VSCode XML LS to refresh the outline when preferences are updated to show extra information of the XML document which is described in the linked issue.

Do you have any good suggestion to implement this without needing this reference functionality ?

**Comment by zardoy** [comment]
I've had a requirement to update document outline after some user settings change that affects it. The most important here, is that requirement comes from TypeScript plugin, I can track settings change in my extension, but sadly cannot retrigger `navtree`, because lack of this command. Even if TypeScript adopted this proposed event and exposed it via command like `_typescript.updateOutline`, it woulnd't resolve my case, as TS plugin can be used with different extensions.

> Extensions shouldn't have the ability to force update the outline via commands. 

@jrieken But what is behind this decision?

Previously we used code that was making `edit`s in every visible text editor (replacing first character) and it worked, but it was making editors `dirty` and it was super annoying, now we try to close and open all visible tabs, which outline should be outdated.

**Pull request closed without merging**
