### PR TITLE
Don't update title area for filterview

### LINKED ISSUE #3676: Remote Explorer shows double drop down
- Install the Codespaces extension
- Try a Sample in a remote container
- Switch to Codespaces in the Remote Explorer
-> The remote explorer is not properly updated (this has been reported)
image

- Reload the window
-> Two drop downs appear

image

We should protect the Remote Explorer Code so that this behaviour cannot happen.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes microsoft/vscode-remote-release#3676

### CODE REVIEW

**Comment by alexr00** [comment]
Updating the title actions whenever views are added/removed breaks the filter view (remote explorer). I'm not confident that this is the best fix. What secondary actions are being updated here?

**Comment by isidorn** [comment]
Hi Alex, the secondary actions are the ones in the `...` menu, and those can show the hidden views in a viewlet. For example here's the explorer:
So with your fix, your `filterView` might have stale action in the `...` view if some views get hidden or added.

Before we talk more about your fix, what is the actual problem here? Why the `filterView` can not handle some additional updates to the titleArea?

Screenshot 2020-09-16 at 10 07 44

**Comment by alexr00** [comment]
@isidorn The filter view works by adding and removing views when the filter is changed (in the remote explorer, this is the dropdown). Every time a view is added or removed, the title actions are updated, which means that the drop down in the remote explorer is re-instantiated each time it is used to select a remote. Each time that drop down is instantiated, it selects the "correct" remote (i.e. if you are currently attached to a container it will default to "Containers" in the drop down). 

So, what the user sees is this:
- User is attached to a container and opens the remote explorer
- Remote explorer shows Containers in the drop down and shows containers views
- User uses drop down to select WSL
- WSL views show in the view container
- But the drop down goes instantly back to Containers because it has just be re-instantiated ❌
- And, because the filter has changed (the dropdown has changed), the view starts trying to add and remove views again, so now the view container shows both wsl views and container views ❌

**Comment by alexr00** [comment]
Sometimes those many re-instantiations even cause multiple drop downs to show in the title area. Here is an example of the behavior. The Forwarded Ports view belongs _only_ when the containers filter is selected, but you can see it flicker and get re-added when the drop down re-selects containers when it is re-initialized. 
recording (1)

**Comment by isidorn** [comment]
@alexr00 thanks for providing more details. But can we simply cache the the drop down so it is not instantiated every time?
Also your fix in this PR seems ok since this filter view is special and does not show mulitple views at once it seems.

**Comment by alexr00** [comment]
@isidorn I tried caching the drop down, but I think there is something about it that requires an update. When I cached it, it simply didn't show up. I will try again just to be sure.

**Comment by alexr00** [comment]
Confirmed that caching doesn't work. I would need input from someone who knows views better than me to understand why.

@isidorn would you rather make a change to only update the secondary actions instead of the whole title area since that is what you actually wanted?

**Comment by isidorn** [comment]
Since you want to do this for the recovery release I believe your proposed fix is less risky and I would go with that.
For master and insiders I can look into adding a new event such that only the secondary actions get updaded

**Comment by alexr00** [comment]
In that case, I have opened a PR for merging my fix into `release/1.49`: https://github.com/microsoft/vscode/pull/106853
Closing this PR in favor of that one, and because we might not use this fix for `master`.

**Comment by alexr00** [comment]
After further discussion, we will keep this change for master.

**Pull request merged**
