### PR TITLE
Give hierarchy to the Open View quick pick. Fix #58555

### LINKED ISSUE #58555: Give better structure to `view`
image

Currently this command is very confusing in two ways:

- Why are panel items shown here? Are they "Views" or not?
- This quick pick result flattens the original hierarchy. Views contain Explorer, and Explorer contains the Sub Trees. It doesn't make sense that in the result `Explorer` and `Open Editors` are in the same level.

### PR DESCRIPTION
**Pull request by octref**

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
That seems wrong:

image

**Comment by octref** [comment]
@bpasero I made some change, but this doesn't prevent someone contributing a treeview named `Terminal` so later `Terminal` group will become `Views / Terminal` group (it should be `Panels / Terminal`).

**Comment by octref** [comment]
image

**Review by bpasero — APPROVED** [review]
@sandy081 since you added the views of a viewlet into the picker and you are the one overseeing contributed views I am moving this to you to decide if this should go in or not. I am fine with the current approach but also with the new approach.

The only thing that seems a bit weird is to use "/" to outline the hierarchy of a view. Maybe there is a better character to use (Views > Extensions).

**Comment by sandy081** [comment]
@octref I see `Views /` is repeating for all. I think Group on the right is to mention the location of the views. Other than for side bar views group rest all are correctly mentioning the location in the group. How about just changing the first group name to `Side Bar` or `Activity Bar`?

**Comment by octref** [comment]
@sandy081 I updated the PR to address comments. It looks like this now:

image

**Comment by sandy081** [comment]
@octref Is `Output / Extensions` still a bug or fixed?

Did you try using a different character `>` to represent hierarchy (like in breadcrumbs)?

**Comment by sandy081** [comment]
ping @octref for above comment?

**Comment by octref** [comment]
I think I pasted a photo from an old build...I just did a rebase on master and here is how it looks:

image

image

**Comment by sandy081** [comment]
@octref LGTM. Please try to use `>` instead of `/` in the hierarchy and see if it looks good.

**Review by sandy081 — APPROVED** [review]

**Comment by octref** [comment]
image

image

I don't have a strong preference. Let me know which one works best for you @sandy081

**Comment by sandy081** [comment]
Lets got with `/` which is also used in our bread crumbs. 

Please push it.

**Pull request merged**
