### PR TITLE
Support drag multi instance in termianal tabs

### LINKED ISSUE #224070: Not able to move multi tab in the terminal list at the same time
- VS Code Version: 
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
- OS Version: MacOS Sonoma 14.5

### Current behaviour
CleanShot 2024-07-27 at 15 08 12

### Expect behaviour
CleanShot 2024-07-27 at 19 47 14

### PR DESCRIPTION
**Pull request by BABA983**
Close #224070 

The idea was to compare the first selected instance and the target instance position, if the first selected instance was before the target instance we moved them after the target instance. 

I'm not sure if it is an ideal approach. Looking forward to any suggestions.

The next step might be to replace the old method with the new one.

https://github.com/user-attachments/assets/4baa11d0-ecf5-49b8-9201-28ee4c72ced9

### CODE REVIEW

**Comment by meganrogge** [comment]
Thanks so much for working on this and for creating the issue in the first place. 

[This](https://github.com/microsoft/vscode/pull/224252) provides a simpler approach, so we will go with that.

**Comment by BABA983** [comment]
> Thanks so much for working on this and for creating the issue in the first place.
> 
> [This](https://github.com/microsoft/vscode/pull/224252) provides a simpler approach, so we will go with that.

@meganrogge I agree [#224252](https://github.com/microsoft/vscode/pull/224252) is a more simple approach, but it doesn't resolve the issue completely. The order is incorrect after drag. Shouldn't we fix it correctly?

**Comment by meganrogge** [comment]
I tested this PR and saw similar issues with the order after drag depending on which tab was focused first.

**Comment by meganrogge** [comment]
If you want to submit a PR that fixes the order after drag, I would be open to that

**Comment by BABA983** [comment]
> I tested this PR and saw similar issues with the order after drag depending on which tab was focused first.

Yep, currently the first selected one will be the first one in the source group. 

> If you want to submit a PR that fixes the order after drag, I would be open to that

Sure, fixing the order will provide a better user experience.

> The idea was to compare the first selected instance and the target instance position, if the first selected instance was before the target instance we moved them after the target instance.

Should we preserve the previous order or follow the user-selected order? I'm not sure which approach is better.

**Comment by tisilent** [comment]
FYI. Original order would be better.
The order of user selection can cause confusion.

**Comment by meganrogge** [comment]
Original order would be great, thanks

**Pull request closed without merging**
