### PR TITLE
Fix accidently starting all onTaskType extensions when running any task; fixes #175821

### LINKED ISSUE #175821: VS Code 1.76 starts *all* onTaskType extensions when debugging
Type: <b>Bug</b>

1. Open the "Remote Extension Host" output window
2. Start Debugging (F5)
3. Note that every extension with an `onTaskType:something` activation event activates.

Pre 1.76, no extensions with `onTaskType` would activate, unless you were actually running that task.

vs-code-debug-all-task-types

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.23405
Modes:
Sandboxed: No
Connection to 'SSH: one_click' could not be established  Connecting with SSH timed out
Remote OS version: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.22GB free)|
|Process Argv|--crash-reporter-id d2ee1b87-344a-4fdd-bf7b-2ab4787239c4|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: one_click' could not be established  Connecting with SSH timed out

|Item|Value|
|---|---|
|Remote|SSH: wave_analysis|
|OS|Windows_NT x64 10.0.22000|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|32.00GB (24.03GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.6
remotehub|Git|0.52.0
wavework|Mic|1.2023.216002
blazorwasm-companion|ms-|1.1.4
vscode-edge-devtools|ms-|2.1.1
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.28.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.30.0
remote-server|ms-|1.0.0
material-theme|zhu|3.15.6
midl3-language-server|Ale|0.0.31
vscode-eslint|dba|2.4.0
vscode-research|dev|1.2022.1111005
vulnerability-extension|dev|1.2023.217002
copilot|Git|1.76.9071
vscode-azdo-codereview|Mic|1.2022.722003
vscode-nmake-tools|Mic|4.0.220809006
wavespace-remote-companion|Mic|1.2022.317002
azure-pipelines|ms-|1.208.0
vscode-dotnet-runtime|ms-|1.6.0
sarif-viewer|MS-|3.3.5
azure-account|ms-|0.11.3
cpptools|ms-|1.14.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706

```

</details>

### PR DESCRIPTION
**Pull request by Mai-Lapyst**
This fixes issue #175821 by only starting extensions of the task's type when trying to reload task after a workspace save.

The original issue falsly is marked as closed, the bug itself isn't resolved; this PR fixes it for good.

To test them:
- open vscode and manually install any extension that has an `onTaskType` activation event such as [rust-lang.rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer).
- create an new empty folder with nothing else than an `package.json` with following content:
  ```json
  {
    "scripts": {
      "test": "echo 'sucessfull runned npm-task'"
    }
  }
  ```
- now press F1 and use `Tasks: Run Task`, select `npm` (to discover npm tasks) and run `npm: test`
- vscode now also activates the rust extension which was previously not loaded; this is indicated by the new `rust-analyzer` item in the statusbar which only gets added once the extension is loaded

### CODE REVIEW

**Comment by Mai-Lapyst** [comment]
> Does this also fix the issue where launch configs with prelaunchTask will enable everything as well?

It should; when testing with following configuration, no additional extensions are activated:
- `.vscode/task.json`:
  ```
  {
	  "version": "2.0.0",
	  "tasks": [
		  {
			  "type": "npm",
			  "script": "test",
			  "group": "test",
			  "problemMatcher": [],
			  "label": "run 'npm: test'",
		  }
	  ]
  }
  ```
- `.vscode/launch.json`:
  ```
  {
      "version": "0.2.0",
      "configurations": [
          {
              "type": "node",
              "request": "launch",
              "name": "Launch Program",
              "skipFiles": [
                  "<node_internals>/**"
              ],
              "program": "${workspaceFolder}/t.js",
              "preLaunchTask": "run 'npm: test'"
          }
      ]
  }
  ```

**Comment by meganrogge** [comment]
I tried your above steps and am not seeing the extension get activated when I run an npm task (no status bar item). When I run a command from that extension, I do see it.


https://user-images.githubusercontent.com/29464607/228937058-f198fd3c-5db0-4d61-b578-b24d777704ef.mov

**Comment by meganrogge** [comment]
I see it work when I use a different extension with `onTaskType` though. Looks like they've removed that 

Screenshot 2023-03-30 at 12 02 13 PM

**Review by meganrogge — APPROVED** [review]

**Comment by 50Wliu** [comment]
Whoops, I forgot my own repro steps :D. It needs to be a preLaunchTask set to `${defaultBuildTask}`, and then one of the tasks in tasks.json needs to have
```json
"group": {
  "kind": "build",
  "isDefault": true
}
```

Even if it doesn't fix that case, this is still a good improvement!

(Also, I suppose for clarity: I do not work on VS Code despite the "Member" tag)

**Comment by Mai-Lapyst** [comment]
> It needs to be a preLaunchTask set to `${defaultBuildTask}`

Looked into it and it's not the task that is the problem; it's the variable: when launching, it first tries to resolve all variables present inside the config:

https://github.com/microsoft/vscode/blob/b9202b64081bb1267792a8d2d023e4c746ed0f73/src/vs/workbench/contrib/debug/browser/debugService.ts#L479

When i replace the line above with following code, it works:

```ts
let resolvedConfig = configByProviders;
resolvedConfig.preLaunchTask = 'run \'npm: test\'';
```

I think it's best to fix this issue in another PR, or should it better be included in this one?

**Comment by Mai-Lapyst** [comment]
Digged depper into this and it seems that the current behaviour regarding `${defaultBuildTask}` is correct:

https://github.com/microsoft/vscode/blob/b9202b64081bb1267792a8d2d023e4c746ed0f73/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L305-L306

When resolving `${defaultBuildTask}`, vscode needs to find all buildtasks first to then filter out the default ones; since all extensions can contribute tasks, all extensions need to be launched here.

I think it's best to discuss this behaviour and any possible change in this in a new issue.

**Comment by meganrogge** [comment]
Yes @Mai-Lapyst you are correct in your understanding and that is why I said in the original issue that the behavior was expected.

**Review by alexr00 — APPROVED** [review]
I didn't test it out, but the change looks reasonable!

**Pull request merged**
