### PR TITLE
[fix-panel-auto-maximize] removes condition which contraints panelHeight

### LINKED ISSUE #41625: Terminal panel automatically maximized
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.5

Description:
The terminal panel automatically maximized when I resize the window.

I think this was caused by the method of maximizing this panel. Maybe it was like this:
```c
if(window.height - panel.height > MAX_PANEL_HEIGHT)
    enablePanelMaximize();
else /*...*/;
```

And when I resize the window to be less high, the condition is reached because I only changed the window's height, didn't change the panel's.

Although this is not a serious problem, I still feel annoyed as I should use my mouse to click the button each time I do so.

Hope you can fix this 😄

---

Steps to Reproduce:

1. Open an empty window, no folder open needed
2. Open the powershell terminal, and make it longer(x-axis)
3. Put the window on a top corner, either left-top or right-top(You can drag it there using mouse or using keyboard Win+Right,Win+Up)
By now, you can see the maximize button has changed

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by shobhitchittora**
Closes: #41625 

Checklist - 
- [x] No Lint errors
- [x] Tests pass
- [x] Hand tested the fix

### CODE REVIEW

**Comment by shobhitchittora** [comment]
@isidorn I removed the condition which was creating the problem ( as below ). Why was it added in the first place? Anything I missed?

https://github.com/Microsoft/vscode/blob/0bddf58ab12619c49cfb0cac3b24f0fa23bfe91c/src/vs/workbench/browser/layout.ts#L471

**Comment by isidorn** [comment]
@shobhitchittora thanks for the PR. The check was there if the panel got explictly maximized(using the action) that it shuold stay maximized. Though I prefer that we remove this, so your PR is fine.
However now the previousMaxPanelHeight variable is not used at all so make sure to remove it a couple of lines above.

**Comment by shobhitchittora** [comment]
@isidorn Thanks for pointing that out. Just curious shouldn't the unused var be flagged by eslint in the editor itself and not allow me to push. Instead It was showing up as (green underlined) - 
screen shot 2018-01-19 at 4 57 57 am

PS: regarding the issue I also checked with triggering `window.action.toggleMaximizedPanel` and it works ✨.

**Comment by isidorn** [comment]
@shobhitchittora I get tslint errors the way I have vscode setup and that is how I found this. Not sure why you did not see it though

**Pull request merged**
