### PR TITLE
Set an explicit order for "Run and Debug".

### PR DESCRIPTION
**Pull request by rehmsen**
This allows extensions to register content to go right after this button by also specifying order 1. 1 was chosen because we want this to be the first piece of content in the debug view.

Addresses #172009.

### CODE REVIEW

**Comment by bhavyaus** [comment]
Sorry about the assignment/reassignment. Looking at this myself as a part of https://github.com/microsoft/vscode/issues/172009

**Comment by rehmsen** [comment]
Hi Bhavya, does this change make sense to you? Do you need me to change anything?

**Review by connor4312 — APPROVED** [review]

**Comment by rehmsen** [comment]
It seems I lost approval when updating the branch? Can someone approve and merge before it gets out of date again?

**Comment by rehmsen** [comment]
@connor4312, can you reapprove as I updated to head? If possible, can you merge right away to avoid it getting out of sync again?

**Review by connor4312 — APPROVED** [review]

**Comment by connor4312** [comment]
ping @roblourens

**Review by roblourens — APPROVED** [review]
I don't totally follow why this doesn't result in that button moving before or after other content, but it seems that it doesn't, and this is fine.

**Comment by rehmsen** [comment]
It does not move before the "Open file" link above because that is in a different group and the order is only within a group (groups themselves also have an ordering). It does not move after the other buttons because when order is not set, it defaults to order 5, which is after the order 1 that I set here explicitly.

Thanks for the approval and merging!

**Pull request merged**
