### PR TITLE
resources: ignore trailing slash when comparing

### LINKED ISSUE #36946: FileSystemProvider: explorer does not pick up new files via FileChange event
- VSCode Version: Version 1.18.0-insider (1.18.0-insider), 509630f
- OS Version: 10.12.6

Steps to Reproduce:
1. Create a file system provider that implements file change notifications
2. Open a provided folder in the explorer view
3. Add a file (resulting in a file-change event for both the file and parent folder)
4. Observe: vscode does not update the contents of the folder to show the new file. (Deleted files *are* removed from the folder.)

*Side note*: `vscode.FileChangeType.Updated`, `vscode.FileChangeType.Added`, and `vscode.FileChangeType.Deleted` seem to be undefined, so I've hardcoded them as 0, 1, 2 respectively.

### PR DESCRIPTION
**Pull request by isidorn**
fixes #36946

This time did it on resources. Makes more sense here as you said

### CODE REVIEW

**Comment by bpasero** [comment]
@isidorn do we know at which point do resources enter our system that have a trailing slash? I would think that the majority of users of this method will never have a trailing slash, is that a fair statement?

**Comment by isidorn** [comment]
@bpasero yes I believe that is a fair statement.
The trailing slash enters the system from the remote `fileSystemProvider`, an example of that can be found here https://github.com/Microsoft/vscode/issues/36946
Also @jrieken can provide more details since he tried the whole example out

**Comment by bpasero** [comment]
Imho we should do the normalization at that point if possible. So far we never had trailing slashes ending up in our system because we `realpath` typically before trusting a workspace folder for example.

**Comment by jrieken** [comment]
Yeah, I would say wherever we accept and open URIs or paths this can happen and I believe that's OK to happen because the folder `/foo` can be called `/foo` or `/foo/` or `/foo/./` or `/foo/../foo/`. 

What I do think is a little naive and wasteful is the creation new strings all the time, you could embed the logic simply inside the `isEqualOrParent` function by accepting trailing slashes.

**Comment by bpasero** [comment]
> What I do think is a little naive and wasteful is the creation new strings all the time

Related to that I noticed that [`ltrim`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L93) and [`rtrim`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L117) seem to return a substring even if the `needle` is not found in the `haystack`. I would think those methods could return quickly the `haystack` if the `indexOf` is -1.

**Comment by jrieken** [comment]
For once, we should use `trim`, `trimLeft`, and `trimRight` that come with the browser and use the existing ones as fallback only.

> I would think those methods could return quickly the haystack if the indexOf is -1.

I believe they do... While indexOf === 0 and when it's not found it will do a substring of 0 which should be a noop.

**Comment by isidorn** [comment]
@jrieken I thought the browser `string.trim()` removes whitespace and not custom characters? Also I can not find `trimLeft` or `trimRight`
If the `ltrim` and `rtrim` do not return a new string then I guess this implementation is not bad since only in the corner case I will create a new string.
Though if you prefer I can look at exact string indeces to also cover this case to not create an additional string.

**Comment by isidorn** [comment]
What is needed for this PR so we proceed?
@jrieken would you like me to look at indeces inside `isEqualOrParent`. Downside of this approach is that it will also effect the `paths` library not only `resources`. Also it seems that I am only creating new strings in a corner case
@bpasero do you want me to do some measuring by comparing random paths with and without the pr?

**Comment by bpasero** [comment]
@isidorn I would just add a check to see if `path[path.length] === '/'` and only then do the trimming. That should still be fast and avoids any string creation.

**Comment by jrieken** [comment]
> would you like me to look at indeces inside isEqualOrParent. Downside of this approach is that it will also effect the paths library not only resources. 

@isidorn I think that's fair and everyone would benefit from it. With https://github.com/Microsoft/vscode/commit/06ba86f404358c644e07dc7c81848bf07dcaf813#diff-6483307f755ba6e74fda5c954b3d08f2 @bpasero deleted the tests and I would restore them. 

Also the way how the function is implemented seems to have changed overtime, esp. that the inputs aren't normalised anymore can be a problem. Think of [`paths.isEqualOrParent('foo/bar/test.ts', 'foo/./bar')`](https://github.com/Microsoft/vscode/blob/d09e7bc373eb084b4d42825bbb41534f3f5d9c20/src/vs/base/test/common/paths.test.ts#L154) and related cases. Unless it changed `path#normalize` is 'save' to use because it makes sure to quickly return when paths are already normal. Then the only thing that's left to check is the common prefix length (case sensitive or not) and to check that the remainders are just path separators.

**Comment by jrieken** [comment]
> Also I can not find trimLeft or trimRight

fyi - That's the problem of our lib.d.ts and the endless IE11 story. The implementation tho could check if that and export `String.trimLeft` instead of our custom thing. We do similar things with [`dom.addClass`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/dom.ts#L172). However, tweaking the strings-util shouldn't be within the scope of this PR

**Comment by bpasero** [comment]
As far as I remember, `path.normalize()` showed up as the top perf hit when running `isEqualOrParent` with many thousand elements (at the time I checked - not sure if meanwhile this method changed). It is true that we no longer support the equals check for non-normalized paths, however so far this has not been an issue likely because our paths are already normalized when entering our system. 

Bottom line: `isEqual` and `isEqualOrParent` currently do not work with:
* paths that have trailing slashes (even node.js `path.normalize()` does not seem to remove them)
* paths that have relative segments (`../ or ./`) within

**Comment by jrieken** [comment]
Both are called like crazy, one startup in a normal workspace (showing a full explorer), I count 1180 calls to `isParentOrEqual` and 813 calls to `normalize` (with 86 non-normal paths). Unsure why that is sooo many. 

Since a while (around two years) the `normalize`-function is optimised for the fact that most paths are normal, on aforementioned startup it costs 2.6ms which you are likely to triple with a correct implementation of `isEqualsOrParent` (which is maybe OK?) 

So, I would recommend the following. Leave `paths#isEqualOrParent` as incorrect as it is today and stop calling it. Move `base/common/resources.ts` into a layer which allows the usage of node-api, then use `path.posix`-functions (e.g `path.posix.normalize`) and use `uri.path` only. Use `ignoreCase` only for `file`-schemes

**Comment by jrieken** [comment]
I have filed https://github.com/Microsoft/vscode/issues/45971 and https://github.com/Microsoft/vscode/issues/45972 and I now think that we should make `isEqualOrParent` correct and we should revisit the caller being responsible for ~90% of the calls

**Comment by bpasero** [comment]
After discussion with @jrieken a pre-req for making `isEqual` / `isEqualOrParent` more correct (by using `normalize`) is to remove this method from hot-loops such as https://github.com/Microsoft/vscode/issues/45971, https://github.com/Microsoft/vscode/issues/46103 and https://github.com/Microsoft/vscode/issues/45972

**Comment by isidorn** [comment]
We have removed it from the most common hot-loop in explorer. However there are still some usages captured in this item https://github.com/Microsoft/vscode/issues/46549

**Comment by bpasero** [comment]
...and https://github.com/Microsoft/vscode/issues/46103

**Comment by isidorn** [comment]
Let's close in favor of https://github.com/Microsoft/vscode/pull/48682

**Pull request closed without merging**
