### PR TITLE
add ignoreCurrentOpen user settings to address #6923

### PR DESCRIPTION
**Pull request by sanggonlee**
Added the boolean "ignoreCurrentOpen" in the workbench.quickOpen user settings which controls whether the current open file should be focused under the Quick Open action.
Addresses #6923 
true does not focus the current open file.
false focuses the current open file (default and the current behaviour).

### CODE REVIEW

**Comment by bpasero** [comment]
Thanks, but I am not planning to merge this, meanwhile workbench.action.quickOpenPreviousEditor was added as command which does this.

**Comment by lorisleiva** [comment]
@bpasero Hi, are you still against this type of behaviour? All relevant issues and PR are closed and locked but neither the `quickOpenPreviousEditor` command nor the `cmd+p+p` keystroke replicate the behaviour that we are used to in other editors.

It seems like we are one boolean option away from fixing this with this PR.

**Comment by bpasero** [comment]
@lorisleiva what is missing from the `workbench.action.quickOpenPreviousEditor` command, have you tried it?

**Comment by lorisleiva** [comment]
@bpasero Terribly sorry, it works very well. I tried to call it without setting up the keystroke before and it must have ran another unrelated command.

**Pull request closed without merging**
