### PR TITLE
Tweak get started detail pane

### PR DESCRIPTION
**Pull request by miguelsolorio**
Final polish tweaks for #111753

- Adjusted the layout when it gets into taller/wider/narrow views
- Updated the default placeholder images
- Made the unfinished icons in the detail view gray
- Placed a min-width images so they don't shrink too small

## Default
image

## Narrow
image

## Tall
image

### CODE REVIEW

**Review by rheh — APPROVED** [review]
Code LGTM.  Not sure if is matters but the file sizes on the PNGs far exceed the originals.

**Comment by misolori** [comment]
@rheh the previous images were cropped versions so there's more to the images now. But a fair point about optimizing the images, will do that.

**Comment by JacksonKearl** [comment]
Looks good overall, but I'm seeing some intermediary window sizes that render a bit oddly: 
image

**Comment by JacksonKearl** [comment]
Digging into this a bit more, I think media queries aren't the right solution here -- they measure the whole screen size but depending on the sidebar and the panel the actual content size can be very different, which explains what I was seeing above. Similar cheese appears in the vertical direction when the panel is expanded. I'm going to look more into using flexbox to achieve the desired result.

**Comment by misolori** [comment]
Ok, feel free to close this one if you've got a better one.

**Pull request merged**
