### PR TITLE
add exclude from search in context menu

### LINKED ISSUE #162628: Add "exclude" option for search in context menu
Add an option to exclude a folder in future searches in the context menu. This folder would be added to the "files to exclude" in the search bar.

image

### PR DESCRIPTION
**Pull request by andreamah**
Fixes #162628

image

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
For consistency with the option above it in the menu I think the word "from" should not be capitalised.

**Comment by andreamah** [comment]
> For consistency with the option above it in the menu I think the word "from" should not be capitalised.

That's a good point, nice catch!

**Comment by gjsjohnmurray** [comment]
Maybe drop the "..." from both of them too?

**Comment by andreamah** [comment]
It's just because `Find in Folder...` from the explorer context also has the `...`, and these two new options do very similar (if not the same) thing as that. I just created https://github.com/microsoft/vscode/issues/163709 to discuss perhaps dropping the `...` from `Find in Folder...`, which would likely cause these two to also drop their `...`.

**Review by roblourens — APPROVED** [review]

**Pull request merged**
