### PR TITLE
debugger console recognizes italic ansi code

### LINKED ISSUE #67510: Debug console does not support italic ANSI escape sequence
Many popular terminals such as GNOME support the use of the escape code `\x1B[3` to provide italics, but the debug console in VS code does not. So for example the following does not render as italic in the debug console:

```
const t = "\x1B[3mitalics!\x1B[0mand not italics";
console.log(t);

```

### PR DESCRIPTION
**Pull request by flurmbo**
Fixes #67510

### CODE REVIEW

**Comment by isidorn** [comment]
This looks good.
@flurmbo in order to merge this in can you please:
1. resolve the confilicts 
2. test that it works in latest
3. write unit tests that cover your case. Here's a pointer https://github.com/Microsoft/vscode/blob/f6caa53cdd87f3fcee7de78d6a5b60a6835cde29/src/vs/workbench/contrib/debug/test/browser/debugANSIHandling.test.ts#L1

**Comment by flurmbo** [comment]
@isidorn sure I'll try to get to it in the next few days!

**Comment by flurmbo** [comment]
Hey @isidorn I made the changes you asked for, let me know what you think!

**Comment by isidorn** [comment]
Thanks a lot. This week we are in endgame which means we only bugfix and take limited changes. Due to that I am assigning this to march and I will probably review next week.

**Comment by isidorn** [comment]
@flurmbo great work, merging this in. Nice tests

**Pull request merged**
