### PR TITLE
Add prev/next panel item actions. Fix #44625

### LINKED ISSUE #44625: Add a command to go to previous or next panel item
Add a command to go from Problems -> Output -> Debug Console -> Terminal and the reverse (or whatever panel item is active, in their order).

Ctrl+Q is not what I want. I do not want to press Ctrl+Q 10 times to do that when I want to switch between task/terminal.
I also don't want to assign 4 shortcuts for going directly to Problems / Output / Debug Console / Terminal.

This remains one of the few things in VS Code where I have to resort to mouse.

I hope the same command can be added to viewlets switching.

Related: https://github.com/Microsoft/vscode/issues/15262

### PR DESCRIPTION
**Pull request by octref**
@isidorn Not done yet. I found `panelService` is not returning the panels in correct order when some of them were hidden / move-around.

Any idea how can I retrieve the order and visibility of the panels? `IPanel` and `IPanelIdentifier` don't seem to have it.

### CODE REVIEW

**Comment by octref** [comment]
I also wanted to suggest having Ctrl-Tab and Ctrl-Shift-Tab bound to them using `panelFocus`. But it seems we don't have that `when` condition and have to do `terminal/output/problems/debug-console focus`. But when I look even closer there seems to be no `output` focus or `debug-console` focus...

Just want to know if you are pro or against adding those two shortcuts behind the when clause.

**Comment by isidorn** [comment]
Against since it will break muscle memory of users. Currently ctrl-tab changes the editor no matter the focus. I would not just change this.

**Comment by octref** [comment]
@isidorn How about cmd + `]` and `[`? They are bound to `indentLine` or `outdentLine` by default on `editorTextFocus`. I'm thinking about making them go to next/prev Viewlet or Panel Item when Sidebar or Panel has focus.

**Comment by isidorn** [comment]
@octref let's start without a default shortcut and if we see that this action is popular we can easily add one later. This is a better strategy than adding first since it is later hard to remove

**Comment by isidorn** [comment]
@octref thanks for your PR. However this week we are in endgame and on Thu I go on vacation so I will review this next milestone. Hope that makes sense.

**Comment by octref** [comment]
Sure, see you next month :)

**Comment by isidorn** [comment]
@octref thanks again for your PR. However I find it strange that we add `next / previous panel` and we do not add `next / previous viewlet`.
How does this go together with the `Views > Open View` action.
From the implementation perspecitve everything looks great. Except that I would try to do more code reuese between the two actions. Since they are doing everything the same just the +1 or -1 on to which panel to navigate.

fyi @sandy081 since he is tackling various views this milestone

**Comment by octref** [comment]
@isidorn 

> However I find it strange that we add next / previous panel and we do not add next / previous viewlet.

I think it's better to do that as another PR. I can do it too.

> How does this go together with the Views > Open View action.

I never used it. I believe that action serves a different purpose than this one. Ideally in each group (editor, viewlets, panels) I just want an action to go to the prev/next thing **visually**, not to recall names of each parts of VS Code and **jump** to it.

What I asked for in #15262 (UI part aside) is **contextual ctrl+tab**. Ideally I hope we can have these commands / when clauses

Ctrl-Shift-Tab:
- `workbench.action.previousPanelItem` when `panelFocus`
- `workbench.action.previousViewlet` when `viewletFocus` (or `sidebarFocus`)
- `workbench.action.previousEditor` when `editorFocus`

Ctrl-Tab:
- `workbench.action.nextPanelItem` when `panelFocus`
- `workbench.action.nextViewlet` when `viewletFocus` (or `sidebarFocus`)
- `workbench.action.nextEditor` when `editorFocus`

**Comment by isidorn** [comment]
@octref thanks. The PR looks good to me know. And these actions make sense.
Let's see what @bpasero and @sandy081 think about introducing these actions and if they are ok we can merge it in.

**Comment by sandy081** [comment]
I think having similar action to navigate viewlets is good. How about navigating views inside viewlet?

**Comment by bpasero** [comment]
@isidorn if you want to merge for April, feel free to review. otherwise running out of time, moving to May.

**Comment by isidorn** [comment]
@bpasero I reviewed this and the code is good. I just need your blessing to add the "Next Panel" / "Previosu Panel" actions. You do not have to look at the code

**Comment by bpasero** [comment]
@isidorn oh OK. We can have the actions but I am with @sandy081 and think for consistency we could have the same actions for viewlets as well.

@octref I think commands like "Previous Panel item" should user uppercase all the way (e.g. Previous Panel Item)

**Comment by isidorn** [comment]
@bpasero great, thanks for feedback
@octref then this PR is good, just update the label and once you provide the viewlet actions PR I will merge both these things in. In the meantime let's keep this on deck.

**Comment by octref** [comment]
@isidorn @bpasero I've cleaned up the API a bit, including

- `getOrderedPanels(): string[]` -> `getPinnedPanels(): IPanelIdentifier[]` to follow more of our terminology and align with `getPanels`
- Clarified a bit on that `getPanels` return panels following the visual order

I have a question though. In `compositeBar.ts`, now we have this:

```ts
	private getVisibleComposites(): string[] {
		return Object.keys(this.compositeIdToActions);
	}

	public getPinnedComposites() {
		return this.pinnedComposites;
	}
```

They seem to be doing the same thing.
- Why is `getVisibleComposites` using `Object.keys(this.compositeIdToActions)` instead of `pinnedComposites`? Are those two different in some scenarios?
- Can I remove `getPinnedComposites` and make `getVisibleComposites` public?

**Comment by isidorn** [comment]
@octref sorry for not responding I was on vacation when you asked the question.
And now @sandy081 has refactored the whole rold of the compositeBar so you would have to check with him.
So for us to continue here can you please resolve conflicts possible with the help of Sandeep and once we have taht we can merge that in if @sandy081 agrees

**Comment by octref** [comment]
A lot has changed on master.. I'll open a new PR.

**Pull request closed without merging**
