### PR TITLE
Make activity bar slimmer

### PR DESCRIPTION
**Pull request by miguelsolorio**
This PR makes the activity slimmer and changes the width from `50px` to `40px` and changes the icon size (relatively) from `24px` to `18px`. I also added a mask for extension icons to match the same size, and adjusted the badge size/position.

**Before**
image

**After**
image

**Side by side comparison**
image

### CODE REVIEW

**Comment by innerlee** [comment]
Is this configurable?

**Comment by bpasero** [comment]
@misolori I appreciate the PR but personally I do not like it so we should a) talk about it in the UX call and b) think about making this configurable.

**Comment by sandy081** [comment]
It might impact existing custom view containers whose icons are following the spec we defined [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviewscontainers)

**Comment by misolori** [comment]
@sandy081 I did add a mask for all extension icons so they fit in the new size.

**Comment by sandy081** [comment]
I see

**Comment by misolori** [comment]
Per our sync today, I'll explore using css media queries to properly adjust the activity bar depending the window/screen size.

**Comment by isidorn** [comment]
Not for this milestone, pushing out to August

**Comment by misolori** [comment]
Will create a new PR when this is ready to be revisited

**Pull request closed without merging**
