### PR TITLE
Improve debug viewlet dropdown outline

### LINKED ISSUE #95870: Inconsistent focus feedback on dropdown
Small nit, I often find this feedback to not look so polished:

image

vs.

image

The debug dropdown is probably special, but can we expand the outline around the entire control?

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #95870

debugviewletdropdownoutline

### CODE REVIEW

**Comment by isidorn** [comment]
Great PR as usual.
However there is one issue: you have increased the font size to 13. Even though I like that change, the issue is that all other dropdowns still use the font size 11. And we should be consistent and have the same font size.

So we have two options:
* Reduce font size back to 11
* Look into increasing all the other font sizes for our select boxes

fyi @misolori

**Comment by jeanp413** [comment]
@isidorn about the font size, when inspecting the select box element the rule `font-size: 11px` in `start-debug-action-item` wasn't being applied, instead the chrome default (`13.333px`) was being used so I just change it to `13px` to keep de layout as before. I can revert that change back to `11px`

**Comment by isidorn** [comment]
@jeanp413 I think I know what the issue is. I am on Mac and you are on some other platform.
On the mac we use the native select boxes, on other platform we have our own select box solution.
And when I try it on the mac I see the font size difference, and you probably do not see it since it might not be aplied to our custom select box.

Yes, I suggest to just revert the font size change.

**Comment by jeanp413** [comment]
Reverted the font size back to 11px.

> @jeanp413 I think I know what the issue is. I am on Mac and you are on some other platform.
On the mac we use the native select boxes, on other platform we have our own select box solution.

I'm on linux ubuntu 18.04 and the native `<select>` element is used
The below screenshot is from stable where you can see the font size used is `13.333px`

image

**Comment by isidorn** [comment]
Ok, this is great now.
Might be then that this font is only applied on the mac, thus I see the difference and you do not.

All in all, great PR. Merging in. Thanks a lot!

**Pull request merged**
