### PR TITLE
Fix #21857

### LINKED ISSUE #21857: editorScroll has regressed in VSCode 1.10
In VSCodeVim, we are using the "editorScroll" command to move both the cursor and the page up and down by half-pages when the user types Ctrl-u and Ctrl-d, respectively.

In VSCode 1.9.1, this worked fine.

In VSCode 1.10.0, this has broken. The cursor no longer consistently moves up or down the page.

This has accumulated (relatively, for us anyways) a large number of thumbs up on our issues page: https://github.com/VSCodeVim/Vim/issues/1348#issuecomment-283712969 

Help!

### PR DESCRIPTION
**Pull request by rebornix**
Use current viewport info to predict the view line info after layout change.

### CODE REVIEW

**Comment by sandy081** [comment]
@rebornix It's been quite a while that I worked in this code so not sure if there were any refactoring or design changes underwent. 

So not sure why we need to change the cursor position explicitly now which was not needed before and was happening by triggering the scroll event. And what does this triggering of scroll event does now.

Thanks

**Comment by rebornix** [comment]
@sandy081 Previously ViewLines got registered in viewEventDispatcher before View. So the workflow is like

* Run command
* Emit Scroll Request event
* VIewLines receives this event, change layout
* View receives this event, call back to Cursor to update the cursor position, which reads the layout info.

Right now, in change https://github.com/Microsoft/vscode/commit/45b6708cf30cad76981357544b9ab651c262ec42 , we registered View into the dispatcher first. Now the workflow becomes

* Run command
* Emit Scroll Request event
* View receives this event, call back to Cursor to update the cursor position, which reads the old layout info and the cursor is not actually updated correctly.
* ViewLines receives this event, change layout


So in this PR, I tried to update the cursor position explicitly instead of relying on event handlers in View parts as when the layout gets updated is not guaranteed, it depends on when we register all the view parts and which view part changes the layout. Make sense?

**Comment by sandy081** [comment]
@rebornix That explains the root cause of the bug. Thanks for the explanation and @alexandrudima also mentioned the same.

**Comment by alexandrudima** [comment]
This PR is obsolete

**Pull request closed without merging**
