### PR TITLE
Fix #43465

### LINKED ISSUE #43465: Tabbar shadow glitch when minimap on the left side
### Issue Type
Bug

### Description

Go to Settings and change `editor.minimap.side` setting to the `left`. Then you see that there is no shadow at the right side under tabbar (where minimap used to be) 
image

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.15.1-2-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1612)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.59GB (0.15GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.12.0
material-icon-theme|PKi|3.2.2
copy-relative-path|ale|0.0.1
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-gist|ken|1.2.0
Go|luk|0.6.76
atom-keybindings|ms-|3.0.4
syncing|non|1.5.3
advanced-new-file|pat|1.1.0
psi-header|psi|1.3.5
partial-diff|ryu|0.5.1
vscode-fileutils|sle|2.7.1
Align|ste|0.2.0
vscode-todo-highlight|way|0.5.11
vscode-jumpy|wma|0.3.1

</details>
Reproduces without extensions

### PR DESCRIPTION
**Pull request by aushakou**
This fixes #43465, removing shadow glitch under tab bar when minimap on the left side.
By the way, I wrote a [blog post](https://aushakou.wordpress.com/2018/02/20/researching-and-trying-to-fix-a-bug-in-vs-code/) about fixing this issue.
I would appreciate any comments and suggestions
Thanks.

### CODE REVIEW

**Comment by alexandrudima** [comment]
@aushakou Thank you for the PR.

This does not fix the issue, although it comes pretty close. The shadow element is placed before the minimap element in the DOM, and thus, the minimap is painted on top of the shadow element:

image

**Comment by aushakou** [comment]
@alexandrudima I would like to continue working on this issue if it is possible. But I need some clarification about how the shadow element should be placed. 
Should it be painted on top of the minimap? Or beside the minimap? 
Thanks.

**Comment by alexandrudima** [comment]
We could rearrange the dom nodes in https://github.com/Microsoft/vscode/blob/ab7f6e871d1af714ae454a06e2745a6ec0521704/src/vs/editor/browser/view/viewImpl.ts#L227:L234

But now I am having second thoughts if we should do this change at all:

Here is the case where scrolling to the right, the minimap also drops a shadow, and the top shadow and the right shadow form a nice corner at the minimap boundary. With this change things would not line up:

image

**Comment by aushakou** [comment]
@alexandrudima From my understanding, if the minimap is on the right side, everything seems to be fine. If the minimap is on the left side, there are two issues. 
Issue 1: shadow on the top is too short. 
Issue 2: there is no shadow on the right side.

scr-vscode

This PR seems to fix issue 1 (the top shadow) by increasing the width of the shadow. 
Issue 2 (shadow on the right side) is still unresolved.

scr-vscode-f

I think we should add the shadow on the right side by sticking it to the vertical scrollbar. And I think it might require a separate issue.

**Comment by alexandrudima** [comment]
@aushakou Sorry about that. I somehow misunderstood the issue, and didn't place the minimap to the left.

---

May I suggest we do the following:

When the minimap is to the left, we make the right-hand side area of the editor behave as if the minimap is disabled. Namely: 
 * the scrollbar should be transparent
 * the top shadow should extend over the scrollbar
image

---

* The fact that the minimap is enabled and placed to the left could be detected from the `EditorLayoutInfo` with `layoutInfo.minimapWidth > 0 && layoutInfo.minimapLeft === 0`

* Make the scrollbar transparent in this case in [`decorationsOverviewRuler.ts`](https://github.com/Microsoft/vscode/blob/6ad67e2af55e2cefa0aafbff1748151da2508048/src/vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler.ts#L60:L62)

* Make the shadow extend over the scrollbar in [`scrollDecoration.ts`](https://github.com/Microsoft/vscode/blob/43ead8169a6290ec5dedb2168685ed0576dbbb07/src/vs/editor/browser/viewParts/scrollDecoration/scrollDecoration.ts#L57)

**Comment by aushakou** [comment]
@alexandrudima I tried to fix this issue by following your suggestions and it seems to work fine.
When the minimap is on the left side:

minimap-left

When the minimap is on the right side:

minimap-right

When the minimap is disabled:

no-minimap

**Comment by alexandrudima** [comment]
Nice! Thank you for your contribution! :heart:

**Comment by aushakou** [comment]
@alexandrudima Thanks for your guidance and suggestions.

**Pull request merged**
