### PR TITLE
Modified The Badges so that they are centered

### PR DESCRIPTION
**Pull request by pybash1**
Modified The Badges so that they are centered

### CODE REVIEW

**Review by rheh — COMMENTED** [review]
The formatting looks different from the rest of the file.  Tabs vs space I think

**Comment by joaomoreno** [comment]
Sorry but this really doesn't add much value to the product. Thanks anyway.

**Comment by play4Tutorials** [comment]
ok.. but what if we made the title and others centered as well.... that would match them? I thought that might look better

**Comment by play4Tutorials** [comment]
And also(off-topic), what if we changed the badges from plastic to flat or flat & square

**Comment by joaomoreno** [comment]
No, thanks.

If you want to help out, please refer to our [Contribution Guide](https://github.com/microsoft/vscode/wiki/How-to-Contribute):

> After cloning and building the repo, check out the [issues list](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue). Issues labeled [`help wanted`](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) are good issues to submit a PR for. Issues labeled [`good first issue`](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) are great candidates to pick up if you are in the code for the first time. If you are contributing significant changes, please discuss with the assignee of the issue first before starting to work on the issue.

**Comment by play4Tutorials** [comment]
ok..

**Pull request closed without merging**
