### PR TITLE
Added Enabled View to Extension Viewlet

### PR DESCRIPTION
**Pull request by gonzofish**
Addresses #22866

Added Enabled action to extensions viewlet
Added "Extensions: Show Enabled Extensions" action to workbench
Set showing enabled in extensions to default view when opening extensions viewlet

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I like that the user can filter out the disabled extensions. But I don't think that should be the default behaviour. I would keep the `@installed` view as the default behaviour.

**Comment by gonzofish** [comment]
You know, I thought that too but followed the feature request...I'll change
it

**Comment by leocaseiro** [comment]
I was wondering if this feature is ready to be merged.

I'm happy to give some help.

Thanks

**Comment by gonzofish** [comment]
Yeah me too. I updated it as requested but never heard anything after.

**Comment by sandy081** [comment]
@gonzofish Sorry for not looking into this.. I will take a look.. But may I know is it possible to resolve the conflicts?

**Comment by gonzofish** [comment]
@sandy081 no worries! I hadn't noticed the conflicts. I can definitely fix them today.

**Comment by leocaseiro** [comment]
Hi @gonzofish, I don't want to be "push", so I was wondering If you could give me access to this branch, so I can help fixing the conflicts, in case you're being busy.

Thanks

**Comment by BugraC** [comment]
@sandy081 this is https://github.com/Microsoft/vscode/pull/30367 on top of @gonzofish's which only fixes the merge conflicts.

**Comment by sandy081** [comment]
@BugraC Thanks. Will take a look.

**Comment by gonzofish** [comment]
@BugraC thanks for updating in my absence

I had some things come up and was away from Internet access for the last week, sorry for the radio silence

**Comment by sandy081** [comment]
@gonzofish Merged the PR from @BugraC.

**Pull request closed without merging**
