### PR TITLE
improve handling fallback of theme colors in terminal

### LINKED ISSUE #57038: Improve handling of fallback theme colors in terminal
See https://github.com/Microsoft/vscode/issues/56864#issuecomment-414939406

### PR DESCRIPTION
**Pull request by ParkourKarthik**
This closes #57038 

@Tyriar 
Yet to change defaults for `TERMINAL_BORDER_COLOR`.
I am not able to relate it to any appropriate editor colors (though there are `editorWidgetBorder`, `editorHoverBorder`, etc).

Should I consider hard-coding the defaults same as `PANEL_BORDER`?
https://github.com/Microsoft/vscode/blob/07618102efdd63f09949ce54c161e7fd2a954ee8/src/vs/workbench/common/theme.ts#L184-L188

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
@ParkourKarthik why can't PANEL_BORDER be imported like editorBackground?

We also want to remove the fallback code here as it's handled when the color is registered now:

https://github.com/Microsoft/vscode/blob/f7b8c9b7df54f23b02fb36ba0cb12a5a96c8c4e9/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L313-L316

**Comment by ParkourKarthik** [comment]
Yep, we could import it. Wanted to make sure that it is the correct one. I'll remove the respective fallback code as well.

**Comment by ParkourKarthik** [comment]
@Tyriar
Could you please review and close this PR.

**Review by Tyriar — APPROVED** [review]
Looks good, will merge after the release is branched off. Thanks!

**Pull request merged**
