### PR TITLE
Added "open editors" sorting option by recently saved

### PR DESCRIPTION
**Pull request by sashaGee**
A partly implementation of request from https://github.com/Microsoft/vscode/issues/12453

While having many files opened and using most of them as readonly reference, i like to see the files i  actually modified recently at the very top of "opened editors" list. Especially helpful when there are file with similar names. SublimeText has similar feature which i miss a lot.

Settings key:
Editor.recentlySavedFirst, true/false

### CODE REVIEW

**Comment by bpasero** [comment]
My 2 cents: I don't like to see "Opened Editors" sorted differently from the sorting of the workbench tabs in the editor space. Both have to be in sync imho.

**Comment by sashaGee** [comment]
The tabs are being updated accordingly. 

Before save:
screen shot 2017-11-13 at 5 01 24 pm

After Save:
screen shot 2017-11-13 at 5 02 03 pm

As you can see "readme.md" tab changed position to 1st.

**Comment by surferau** [comment]
Example of multiple groups interaction.

before save:
screen shot 2017-11-13 at 8 01 13 pm

After save:
screen shot 2017-11-13 at 8 01 38 pm

**Comment by bpasero** [comment]
I find it very ugly to put the code to sort opened editors in the "Open Editors" view domain. If any, this has to live in the `editorStacksModel.ts` which is the foundation of all tabs and opened editors.

**Comment by surferau** [comment]
You can put it whenever you want, free country

**Pull request closed without merging**
