### PR TITLE
#101995 extend tooltip of menu item that defines 'alt' command

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR implements #101995

junk

If a menu item specifies an additional `alt` commmand the tooltip gets a second line displaying this when the <kbd>Alt</kbd> key is not down.

The goal is to improve discoverability of places where two alternative commands exist.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
ping @sbatten who commented on the original issue I opened

**Comment by gjsjohnmurray** [comment]
@sbatten any chance of this merging in time for February release?

**Comment by sbatten** [comment]
@gjsjohnmurray probably no and that's my fault for not coming back to the PR in time. I just did the code review and I think it looks good. As with anything, I'd like to see it in insiders for the month in case there are any surprises. I think we can merge this right after release. 

/cc @bpasero 
one question I have, do we refer to option/alt key differently on macOS here? or is Alt the right terminology?

**Comment by bpasero** [comment]
@sbatten the key needs to be called "Option" on macOS: https://en.wikipedia.org/wiki/Alt_key#macOS

**Comment by bpasero** [comment]
@gjsjohnmurray I think we need to localize the key though, as the name maybe different in other languages.

**Comment by gjsjohnmurray** [comment]
@bpasero what is the right way to do this? I used https://github.com/microsoft/vscode/blob/01cfa2f8352f129fc922b2a9b3ec938f1bb93f84/src/vs/workbench/contrib/debug/browser/debugHover.ts#L108 as my model for the `isMacintosh` test. Does the keylabel text get localized in that instance?

**Comment by bpasero** [comment]
No, it needs 2 distinct messages.

**Comment by gjsjohnmurray** [comment]
Based on the keyboard images at https://support.apple.com/en-us/HT201794 most keyboard layouts use `⌥` (U+2325). Exceptions on that page are English, Japanese, Korean, Taiwanese and Thai which use the text 'option'. In all cases the text 'alt' also appears on the key.

Having said that, the [Magic Keyboard](https://en.wikipedia.org/wiki/Magic_Keyboard_(Mac)) apparently labels it with `⌥` and 'option'.

Shall we leave it to the translators to decide on a per-language basis? Presumably they'd pick either `⌥` or 'Option' (should that be uncapitalized?).

Are the nls.localize translations file-specific? That is, if I add this in the file I'm changing for this PR
```ts
const = nls.localize({ key: 'macOSaltKey', comment: ['label or symbol on the Alt / Command key (commonly U+2325)'] }, 'Command')
```
and do the same to fix debugHover.ts, will the translators have to duplicate the translation? If yes, is there a central place to export the string from?

**Comment by gjsjohnmurray** [comment]
If the `⌥` symbol gets used in some localizations perhaps the tip should use regular square brackets to denote the key instead of the fancy THREE-D TOP-LIGHTED LEFTWARDS EQUILATERAL ARROWHEAD and THREE-D TOP-LIGHTED RIGHTWARDS EQUILATERAL ARROWHEAD shown in the PR's original screenshot, e.g.

image

image

(screenshots above simulated on my Windows dev platform)

image

**Comment by gjsjohnmurray** [comment]
@bpasero please see my questions at https://github.com/microsoft/vscode/pull/116211#issuecomment-785037014

It makes sense to me for there to be one place setting the per-OS (and possibly per-language) text or symbol representing the Alt/Option key when it needs to be referred to in display strings.

I'd like to get this PR into Insiders soon so it can get good exposure.

**Comment by bpasero** [comment]
I don't fully understand why we have to solve this newly for this case? I am quite sure we already have existing tooltips with the Alt-key as part of them, why can we not reuse what we do there?

**Comment by sbatten** [comment]
This might be the right thing to use https://github.com/microsoft/vscode/blob/ed5e512a2f855598edb19c7c2a6ceabe66477bbd/src/vs/base/common/keybindingLabels.ts#L61-L83

**Comment by gjsjohnmurray** [comment]
Thanks @sbatten, this is what I was looking for. I have pushed a change to use it. At the same time I switched to using regular square brackets around the altKey representation.

**Review by sbatten — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
@sbatten thanks for the feedback. I have pushed the changes you suggested, so I think this is now ready to be merged.

**Comment by sbatten** [comment]
@gjsjohnmurray merged! thanks!

**Pull request merged**
