### PR TITLE
Don't stop checking for updates after one has been installed.

### LINKED ISSUE #44685: Update: Updating VS Code should check for updates first.
If I have an update pending and a new update comes, in order to get the latest version I need to update (and reload window), then check for updates and update again (reloading the window again).

Steps to Reproduce:

1. Open VS Code Insiders
2. Check for updates --> a little `1` appears.
3. Wait 24 hours
4. Click the gear
5. Find out there is no way to check for new updates until the previous update is installed.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by VishalMadhvani**
fixes #44685

Not sure of what else I need to do for this pr...
Couldn't see any tests but I assume either the pr build will fail or hopefully someone will let me know.

### CODE REVIEW

**Comment by VishalMadhvani** [comment]
any thoughts on this @sandy081, @joaomoreno ??

**Review by joaomoreno — COMMENTED** [review]
I don't think this is complete, since after the service is `Ready`, there won't be a `Check for Updates` action anymore.

**Comment by joaomoreno** [comment]
Also this doesn't for macOS, Squirrel won't allow to download two updates.

**Comment by joaomoreno** [comment]
Also this

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Also this fails to address Linux and Windows.

**Comment by joaomoreno** [comment]
Closing due to inactivity.

**Pull request closed without merging**
