### PR TITLE
Update peek styles

### PR DESCRIPTION
**Pull request by miguelsolorio**
Refs #130516

This PR updates the default styles for all of our peek views (info, error, warning, regular peek) based on the feedback from #130516. I've also updated the next/previous arrows to use the same icons from the inline diff peek.

https://user-images.githubusercontent.com/35271042/129959699-da94a563-4c3e-40f9-a694-0e5cc37dec89.mp4

This also makes our info/warning/error icons a bit brighter:

CleanShot 2021-08-18 at 12 26 56@2x

### CODE REVIEW

**Comment by connor4312** [comment]
Does this also affect the test peeks?

**Comment by misolori** [comment]
@connor4312 I actually didn't look at the test peeks, just pushed some changes to cover this area (would love your feedback/review):

CleanShot 2021-08-18 at 16 59 38@2x

**Review by connor4312 — APPROVED** [review]

**Comment by misolori** [comment]
@sandy081 can you do a quick review & merge if it looks good? I'll be out for the next week and wanted to get this in before endgame

**Review by sandy081 — APPROVED** [review]
LGTM

**Pull request merged**
