### PR TITLE
move isHiddenByDefault

### PR DESCRIPTION
**Pull request by sbatten**

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]

**Comment by jrieken** [comment]
Thanks for following up. I pushed a little change that keep all hide logic inside the `PersistedMenuHideState` object so that those arguments aren't needed anymore

**Review by jrieken — APPROVED** [review]

**Comment by Tyriar** [comment]
@sbatten @jrieken this appears to now break the reason for the change in the first place; I cannot toggle visibility of the overflowed item anymore after this was merged:

image

image

**Comment by jrieken** [comment]
Did you do the adoption of moving this default hide state into the menu registration?

**Comment by Tyriar** [comment]
Yep

image

**Comment by Tyriar** [comment]
Let me try a full rebuild 🤔

**Comment by Tyriar** [comment]
My bad, I had the wrong group

**Pull request merged**
