### PR TITLE
Fix #40011: Tweak overflow behaviour when setting tab is narrow

### LINKED ISSUE #40011: Settings: bad overflow behaviour of setting tabs when space is little
I would expect a "..." overflow behaviour here:

image

### PR DESCRIPTION
**Pull request by RTX2080S**
Show ellipsis when the setting tab is narrow, as issue described in #40011

See fixed: 
image

### CODE REVIEW

**Comment by sandy081** [comment]
@Radon222 This fix breaks the `Folder Settings`. Drop down arrow is not shown.

image

**Review by sandy081 — CHANGES_REQUESTED** [review]
This will make folder settings label to not show the drop-down

**Comment by Radon222** [comment]
right, will think of another way to fix @sandy081

**Comment by Radon222** [comment]
See #40462 for updated pull request

**Pull request closed without merging**
