### PR TITLE
fix: switch `pnpm` and `yarn` order in `detectedPackageManagerNames`

### LINKED ISSUE #175609: npm extension chose `yarn` rather than `pnpm` when repo use `pnpm`
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

Steps to Reproduce:

1.  clone https://github.com/ant-galaxy/oasis-engine-toolkit
2. run `pnpm install` in terminal
3. use `npm extension` to run `lint` command from `package.json script`
Screenshot 2023-02-28 at 10 03 27
Screenshot 2023-02-28 at 10 03 36
Screenshot 2023-02-28 at 09 58 28
Screenshot 2023-02-28 at 09 58 34

### PR DESCRIPTION
**Pull request by susiwen8**
- Close #175609

### CODE REVIEW

**Comment by susiwen8** [comment]
@meganrogge Hi, Please take a look

**Review by meganrogge — DISMISSED** [review]
👍🏼 works, thanks

**Review by rebornix — DISMISSED** [review]

**Comment by meganrogge** [comment]
@tyriar pointed out that this is not the right fix because we want to make sure the more popular package manager, `npm` is preferred. 

Can you try just swapping the order of `yarn` and `pnpm` here to see if that fixes it?

**Review by Tyriar — APPROVED** [review]

**Comment by Tyriar** [comment]
@meganrogge you need to re-approve it as we force 2 approvals now

**Review by meganrogge — APPROVED** [review]

**Pull request merged**
