### PR TITLE
Fix 'e.getModifierState is not a function' error for browser auto filled form events

### PR DESCRIPTION
**Pull request by BusinessDuck**
Some browser events may not contains `getMidifierState` method. For example events, that produced by forms auto-fills.
Check the demo stand in associated issue https://github.com/microsoft/vscode/issues/205214

Optional chaining for that method should solve the problem.

Test cases:
1) Autofill form by browser
2) Create event through the `new Event()` programmatically and dispatch, that will produce error also because correct way to use `new KeyboardEvent()`

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
Any chance of a swift fix? The diff is trivial and this issue really affects Monaco users heavily.

**Comment by BusinessDuck** [comment]
Is that looks better now?

**Comment by silverwind** [comment]
Yes, thanks. The fix is good enough to get the error away.

I would also recommend the VSCode team to check why VSCode is "listening in" on events that are targetend external elements that are not part of VSCode's root element.

**Review by alexdima — APPROVED** [review]

**Comment by alexdima** [comment]
Thank you!

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
