### PR TITLE
Fix typo s/precidence/precedence/

### PR DESCRIPTION
**Pull request by kachick**
This PR fixes just a typo, I found it in https://github.com/rubyide/vscode-ruby/pull/709
If this change is not needed, please close this PR 🙏

### CODE REVIEW

**Review by shivaylamba — APPROVED** [review]

**Review by bl-ue — APPROVED** [review]

**Review by 0xfffffff0075e2040 — APPROVED** [review]

**Review by miladbarazandeh — APPROVED** [review]

**Comment by alexr00** [comment]
@kachick thank you for the PR! However, we pull this file from an upstream repo with a script, so the next time that script is run your change would get overwritten. If you want to make this change, please consider making a PR to the upstream repo.

https://github.com/microsoft/vscode/blob/3f1f36333d3453f67a36b6bfb1206e9159e9c4f0/extensions/ruby/syntaxes/ruby.tmLanguage.json#L2-L6

**Comment by kachick** [comment]
@alexr00 Yes, I already did it in https://github.com/textmate/ruby.tmbundle/pull/138. It is merged. So I should just wait for `script is run`?

**Comment by alexr00** [comment]
Ah, I didn't read carefully enough! I'll be running the script to pull grammar changes next week so the change will come in then.

**Comment by kachick** [comment]
Thank you for the updating plan! 🙏 

BTW...  https://github.com/textmate/ruby.tmbundle was root repository, but looks not active than VSCode community for now. 😅 
Don't you plan to import syntaxes from other active extensions? An example, https://github.com/rubyide/vscode-ruby 🤔

**Comment by alexr00** [comment]
@kachick since there are rarely issues with the ruby grammar we have no plans to change which repo we get our grammar from.

**Comment by kachick** [comment]
Hmm... Sure! Thanks for the answer! 🙏

**Pull request closed without merging**
