### PR TITLE
Added ARM64 build support

### PR DESCRIPTION
**Pull request by ava1ar**
Changes required to build master on arm64 machine (Samsung Chromebook+ with ArchLinux running inside crostini container was used). [Builds and runs](https://imgur.com/mQkK8xU) fine with the proposed changes.

### CODE REVIEW

**Comment by jkol** [comment]
This is missing an arm64 entry in the object inside of `getDebPackageArch` in `build\gulpfile.vscode.linux.js`

**Comment by manfredbrandl** [comment]
Dont we need to Update to Electron 2.0.x #52782 with this?

**Comment by ava1ar** [comment]
@manfredbrandl it was updated already when the PR was submitted, but got reverted later...

**Comment by manfredbrandl** [comment]
In #54873 Electron was updated to 2.0.5 .

**Comment by joaomoreno** [comment]
Guys, no need to keep this PR up-to-date. Supporting ARM64 is more than just accepting a PR. It requires us to update our release and test channels and commit to supporting it in the long run, which is not a development decision. The work here is great in which it contains the engineering effort to enable it, but there's a lot more to accepting such a change.

**Comment by ava1ar** [comment]
@joaomoreno I am making arm64 builds of vscode for myself, so just wanted to share the required changes with the community, so may be somebody else use it and start getting own builds with arm64. I perfectly understand, that new architecture unboarding requires lot of things to be done, so feel free to do whatever you want with this PR.

**Comment by magic-k** [comment]
Allowing an easy way to compile for arm and making arm builds official is not the same thing. I can build for arm64 already out of the box with the current master. This PR simply adds the components for arm64 to build packages. BTW the same lines for armhf are already there. 
@joaomoreno i guess you confuse this PR with issues that want official arm builds.

**Comment by glebm** [comment]
The produced `deb` package is invalid. You also need to add the architecture mapping, then it works:

```
sed -i 's|arm: .armhf.|&, arm64: "arm64"|' build/gulpfile.vscode.linux.js
```

**Comment by glebm** [comment]
@roblourens Looks like ripgrep 0.9.0 release is missing the arm64 zip  https://github.com/roblourens/ripgrep/releases/tag/0.9.0

**Comment by roblourens** [comment]
arm64 should be there now.

**Comment by glebm** [comment]
@roblourens Thanks!

**Comment by magic-k** [comment]
No. Only ripgrep from arm64. Microsoft has currently not the ressources to maintain arm builds. And obviously it's not very high on theit priority list. We have to wait fo arm64 windows notebooks :-)
I track vscode on my own git repo with the arm64 patches. So i can regulary build it on my own.

**Comment by joaomoreno** [comment]
Yeah, you are right, we can just merge this in an not officially release builds. Would that be enough for you guys?

**Comment by headmelted** [comment]
Thanks!

This would be a massive help, I'll get to work on a pull request. I have it
in place now (more or less), it just needs cleaned up a little.

**Comment by joaomoreno** [comment]
Wait. I was talking about this extremely minimal PR. What do you have in mind instead?

**Comment by glebm** [comment]
This PR has one small issue, https://github.com/Microsoft/vscode/pull/52119#issuecomment-413698694

**Comment by ava1ar** [comment]
@glebm @joaomoreno Let me fix the mentioned issue, give me an hour or so.

**Comment by headmelted** [comment]
@joaomoreno sorry, replied to the email on my phone and got threads crossed.

There are a few other additions her and there needed for ARM64 that I've identified. In fairness, I'm exclusively cross-compiling from x64 so it may be the case that they only impact that scenario.

Basically, this surrounds issues about what "arm" means to the packaging system on the OS - generally it's taken as an alias for "armhf" or "armv7l", neither of which would work on an ARMV8/ARM64 device verbatim. I wouldn't expect this to affect someone compiling directly on ARM64 hardware, as this would be picked up from the OS in that instance.

I previously maintained a fork, the problem with that was that these are not significant changes (effectively just cleaning up a few "arm" references), so it was a bit of a waste for something that really belongs in the core codebase.

In any case, when I've ironed out the details I'll submit a PR that should clarify - as said it's very minimal changes so that you folks can decide if you want to include it or not.

Apologies if this hijacked the thread, just wanted to clarify.

**Comment by ava1ar** [comment]
@headmelted sounds like extra things you mention are for cross-compilation only, since I am able to successfully build the arm64 version of the vscode using only changes from this PR. I can include required changes to this PR if there are no objections from @joaomoreno and they are small. Otherwise let's split them into different PR to merge this first and cross-compilation related stuff later.

**Comment by headmelted** [comment]
Absolutely, sounds like the right way to go.

**Comment by ava1ar** [comment]
So, the PR is ready. Let me know if anything still needs to be done to merge it. Thanks!

**Comment by headmelted** [comment]
There's a couple of changes I'd make in addition to this that mirror some of the edits in PR #24943.  I don't think _that_ PR is likely to be accepted now (it's been some time since it was submitted, and I think the builds have migrated to VSTS from Travis in that time).

Everything in _this_ PR seems fine, so if you guys are happy to merge this PR for ARM64 on ARM64 builds, I can submit a second one with the extra changes needed for ARM64 cross-compiling (they won't impact on other builds, and are quite minor).

If I copy over my additions into a new PR before _this_ PR is merged it'll just replace @ava1ar 's work and I don't want to do that as there's nothing wrong with it and I'd feel like a jackass.

Hope that all makes sense. 👍

**Comment by joaomoreno** [comment]
@ava1ar Looks good, I'll check it asap.

> ARM64 cross-compiling

@headmelted Sorry for being blunt, but since we do not produce any output in our continuous build, what use would be this for now?

**Comment by joaomoreno** [comment]
@headmelted No worries, it was a great explanation, thanks!

**Review by joaomoreno — COMMENTED** [review]
LGTM

**Review by joaomoreno — APPROVED** [review]

**Comment by joaomoreno** [comment]
@jrieken Asking you to review the version bump of `electron-mksnapshot`.

**Review by jrieken — APPROVED** [review]
👍

**Comment by ava1ar** [comment]
Thanks a lot for merging this! ARM64 users just became a bit happier :)

**Comment by headmelted** [comment]
Looking at this again I think if I adapt my patches to fit in with this PR (I was using different arm aliases - doesn't really matter) I can get the needed additions down to two lines of JS in the same file.  Will add when this is merged in.

**Comment by headmelted** [comment]
PR raised as #58436.

I can re-work my own scripts to fit in with the scheme used here (as it should be).  This should be all that's required to allow me (or anyone else) to cross-compile for ARM and ARM64.

**Comment by joaomoreno** [comment]
@headmelted That's great news. We can then close https://github.com/Microsoft/vscode/pull/24943 ?

**Comment by headmelted** [comment]
Sure. 🙂

It's two different things really - that PR was more involved in that it
would actually get the CI/CD builds of Code cross-compiling to ARM directly.

This one is a much lower-impact addition that will allow someone to
cross-compile to ARM using their own build scripts.

I think given the difficulties you mentioned in officially supporting ARM
this is the best way forward - it'll support cross-compiling now if someone
wants to do that. 🙂

Thanks for the quick turnaround by the way!

**Comment by roblourens** [comment]
I updated yarn.lock for electron-mksnapshot

**Comment by Tyriar** [comment]
LGTM 👍

**Comment by joaomoreno** [comment]
> I updated yarn.lock for electron-mksnapshot

D'oh

**Comment by DVLP** [comment]
How to build for Dex?

**Pull request merged**
