### PR TITLE
feat(Diagnostics): Add proposed DiagnosticTag.Deprecated enum member

### LINKED ISSUE #56694: Add DiagnosticTag.Deprecated
Now that `DiagnosticTag` has been added to the API, I would like to support the proposal from #51104 to use it for tagging deprecated items.

I figure the associated styling might be a strikethrough as proposed in #50972 but you guys can work that out separately.

### PR DESCRIPTION
**Pull request by kamranayub**
Closes #56694
Relates to #50972

## Changes

- Add proposed `DiagnosticTag.Deprecated` member
- Add `MarkerTag.Deprecated`

## TODO

- [ ] Add similar testing like #52218 (see https://github.com/microsoft/vscode/commit/8bb27cd255508611021969f79061d1b5b6a6283f) ?

### CODE REVIEW

**Comment by kamranayub** [comment]
@sandy081 @jrieken I'm still trying to understand the different aspects of this. I added `MarkerTag` like was done previously for `Unnecessary` but now that I re-read the proposal for #50972 I'm thinking that isn't needed because this won't be a marker; it will somehow get tied to `[CompletionItem.deprecated](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)`.

Am I understanding that correctly? If so, I can revert those two changes.

**Comment by jrieken** [comment]
@kamranayub both requests, #56694 and #50972, are independent and need separate solutions. Having `DiagnosticsTag.Deprecated` will allow extensions to render certain diagnostics "special", e.g a common rendering of deprecated is a strikeout (in addition to the severity based rendering). Compare this to the faded rendering of unused/unnecessary code.

**Comment by kamranayub** [comment]
Thanks for clarifying. I will revert the two Marker changes.

**Comment by kamranayub** [comment]
Ah, I assumed `MarkerTag` was specifically only for being able to render squigglies based on the usage I saw for `MarkerTag.Unnecessary` in https://github.com/microsoft/vscode/commit/8bb27cd255508611021969f79061d1b5b6a6283f#diff-489874091c7caf27cd2ed52e59c41147

**Comment by kamranayub** [comment]
@jrieken Brought those changes back. Is the next step to try and perform some rendering using this new API or just add a test case for mapping the `DiagnosticTag` to `MarkerTag`?

**Comment by kamranayub** [comment]
Making progress.

**Rendering `CompletionItem.deprecated`**

image


**Rendering `MarkerTag.Deprecated`**

image


Both examples above are NOT *actually* implemented with the language provider, they are just hardcoded to include deprecated tag or set `CompletionItem.deprecated` so I could see the styling work.

```diff
diff --git a/extensions/typescript-language-features/src/features/completions.ts b/extensions/typescript-language-features/src/features/completions.ts
index fdfabd4365..89e80b8319 100644
--- a/extensions/typescript-language-features/src/features/completions.ts
+++ b/extensions/typescript-language-features/src/features/completions.ts
@@ -50,6 +50,9 @@ class MyCompletionItem extends vscode.CompletionItem {
        ) {
                super(tsEntry.name, MyCompletionItem.convertKind(tsEntry.kind));

+               // TODO: Remove
+               this.deprecated = true;
+
                if (tsEntry.source) {
                        // De-prioritze auto-imports
                        // https://github.com/Microsoft/vscode/issues/40311
diff --git a/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts b/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts
index 2571d395a5..7a88de73fe 100644
--- a/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts
+++ b/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts
@@ -261,6 +261,7 @@ export default class TypeScriptServiceClientHost extends Disposable {
                if (diagnostic.reportsUnnecessary) {
                        converted.tags = [vscode.DiagnosticTag.Unnecessary];
                }
+               converted.tags = [vscode.DiagnosticTag.Deprecated];
                (converted as vscode.Diagnostic & { reportUnnecessary: any }).reportUnnecessary = diagnostic.reportsUnnecessary;
                return converted as vscode.Diagnostic & { reportUnnecessary: any };
        }
```

**Comment by jrieken** [comment]
Please do not mix both features into one PR, please extract the changes for the completion item into a separate PR. Thanks

**Review by jrieken — CHANGES_REQUESTED** [review]
one PR, one feature request

**Review by mjbvz — APPROVED** [review]
The diagnostics tag changes look good to me

**Comment by jrieken** [comment]
@kamranayub fyi - I have moved the completion related commits into https://github.com/microsoft/vscode/tree/joh/completionsDeprecated. There is some little work left there and I would appreciate another PR off that

**Comment by jrieken** [comment]
This works like a charm. Thanks @kamranayub

**Comment by jrieken** [comment]
Merged despite an open question regarding the use of both tags, today deprecated will overrule unnecessary. Let's wait for the bug

**Pull request merged**
