### PR TITLE
[themes] Add ability to reload themes without restarting the editor

### LINKED ISSUE #45963: [icon themes] Expose API to provide a dynamic icon theme.
This is an API feature request.

We at `vscode-icons` extension support project detection which dynamically re-generates our icon manifest file including or not project specific icons. Additionally to that, we provide the ability to the user to provide its own custom icons and more.

All these features, in the end, require the editor to be reloaded, simply because the icon manifest gets loaded at the start of the editor and with no ability to trigger a reload upon icon manifest recreation.
This results in a poor UX.

If we could have an API to trigger an icon manifest reload, we can have a much smoother transition between changes.

Relating request: https://github.com/vscode-icons/vscode-icons/issues/1177

//cc @robertohuertasm @jens1o @PKief @EmmanuelBeziat @LaurentTreguier @file-icons @DavidBabel @be5invis

### PR DESCRIPTION
**Pull request by JimiC**
Resolves #45963

This PRs adds the ability to reload a theme (color or icon) without the need to restart the editor.

Replaces #60136

### CODE REVIEW

**Comment by JimiC** [comment]
Looks like `createUnloadedTheme` requires `undefined` for `settingsId` and `extensionData`.

**Comment by aeschli** [comment]
We had long discussions in the team about this feature. By design, the content of extensions are expected to be immutable. Only our extension management code should make changes.
Adding a watcher is the wrong approach. Instead we should add a icon/color theme provider API in code that would allow you to implement a more powerful icon theme.
But that API isn't going to happen very soon, so I added a hidden/ & in-official flag for you where you can turn on a watcher for your theme.
```
		"iconThemes": [
			{
				"id": "vs-minimal",
				"label": "Minimal (Visual Studio Code)",
				"path": "./fileicons/vs_minimal-icon-theme.json",
				"_watch": true
			}
		]
```
No warranties on that flag and it might also be removed any time if necessary. But I will let you know once we have the proper API in place. 

Thanks for your help!

**Comment by JimiC** [comment]
So that's what `_watch` is all about. Sorry if I'm wrong but I only see this being declared for color themes and not icon themes (`ColorThemeData`).

Just for the record, I proposed an API but it was rejected for not fitting to the current API (https://github.com/Microsoft/vscode/pull/60136#issuecomment-451407036). I'm totally in favor of an API point and that was my original approach. But in order to see the reloading feature happening, I went with whatever was suggested.

I don't want to sound bitter but a temp solution is like no solution at all. Never the less, I'll try to see the cup half-full and not half-empty. Some will say that from not having this at all, at least we can have it as it is.

**Comment by aeschli** [comment]
Yes, sorry, my fault that we went down that pass. But also a reload API doesn't make any sense given that extensions are not supposed to make changes to their content. You guys also only do that to work around limitations on the icon theme syntax.
What you want is a file icon theme provider that lets you return an icon for a given file path. However, that's quite a lot of changes and probably requires us to refactor the way icon associations are made.

**Pull request merged**
