### PR TITLE
Fixes #44237: Add column number in tasks

### LINKED ISSUE #44237: Add variable to tasks.json for cursor column number
- VSCode Version: 1.20.1
- OS Version: All

The [variables available](https://code.visualstudio.com/docs/editor/variables-reference) for tasks.json are very helpful. Unfortunately, while the line number is available in ${lineNumber}, there's no line column variable. 

The column number would be helpful for me because I have a script which can perform different actions based on where the cursor is.  If the cursor is on a function name, for example, it can launch a documentation program (outside of vscode) to show me the function documentation.  But I need both the cursor line and column passed to the script so it can determine (or at least guess) in what type of context the cursor is found.

Is there a way we could get a ${column} value to return the column number for use in tasks?  Thanks!

### PR DESCRIPTION
**Pull request by goodmind**
#44237

### CODE REVIEW

**Comment by goodmind** [comment]
RIP

**Comment by roblourens** [comment]
The PR is stale but as a feature this makes sense to me, why not provide the column if we provide the line?

**Comment by alexr00** [comment]
@goodmind this makes sense to me too. If you resolve the conflicts I'll try it out and see if we can merge it.

**Review by alexr00 — APPROVED** [review]

**Review by lszomoru — APPROVED** [review]

**Comment by keithel** [comment]
I was looking at @goodmind 's commit and comparing it to what i was doing - similar, but i missed some things, and wow it looked quite different... Then I realized i was looking at a commit from 2018, and @alexr00 you merged master into his branch... Now it makes much more sense.

Thank you for doing this! It will be very helpful for people using the Axivion static analysis tool, and I'm sure many other uses.

**Pull request merged**
