### PR TITLE
Fix uninstall hanging

### LINKED ISSUE #164689: Uninstalling VS Code takes a long time, when enabling the Windows 11 context menu action
Testing #164465

When uninstalling VS Code with enabled Open menu entry the uninstaller seems to hang at the beginning and it takes quite some time until it finishes. I never experienced this when testing the final Windows bits during endgame.

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Fix #164689.

### CODE REVIEW

**Comment by abhijit-chikane** [comment]
,,,

**Review by 0x4248 — APPROVED** [review]

**Review by deepak1556 — CHANGES_REQUESTED** [review]
Can you please expand on the change, I am not sure how this resolves the uninstallation hang.

**Comment by ChaseKnowlden** [comment]
There was a typo in the UninstallRun element that wasn't removing at all.

**Comment by deepak1556** [comment]
Triggered custom build to verify https://monacotools.visualstudio.com/Monaco/_build/results?buildId=227850&view=results

**Comment by deepak1556** [comment]
Inno setup compilation failed with the following error,

```
2023-08-16T05:23:09.4553478Z Error on line 107 in D:\a\_work\1\s\build\win32\code.iss: Unknown constant "Remove-AppxPackage -Package "Microsoft.VSCodeInsiders_1.0.0.0_neutral__8wekyb3d8bbwe"".
2023-08-16T05:23:09.4553848Z 
2023-08-16T05:23:09.4554151Z Use two consecutive "{" characters if you are trying to embed a single "{" and not a constant.
```

I remember adding the extra `{` for the same reason. Closing as the change does not solve the mentioned issue. Thanks for working on it!

**Pull request closed without merging**
