### PR TITLE
Support new extension #25709

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Support `capfile` and `.stylelintrc`.
This commit is devided.
Please merge or cherry-pick useful commit.

### CODE REVIEW

**Comment by mrmlnc** [comment]
The `.stylelintrc` is not extension is filename. Also this file can use JSON syntax.

**Comment by Ikuyadeu** [comment]
@mrmlnc, Thank you! I fixed to JSON.
But that as extensions like `.eslintrc`.

**Comment by mrmlnc** [comment]
Sorry, but I don't fully understand your actions.

I say that `.stylelintrc` can have following syntaxes (for more details see [docs](https://stylelint.io/user-guide/configuration/#loading-the-configuration-object)):

  * JSOC
  * YAML
  * JS

Also the `.stylelintrc` file may have extensions like: `.json`, `.js`, `.yaml`, `.yml`. For example, `.stylelintrc.json`.

IMO, mapping of these files should be moved to the plugins, because it's not a «core» features. For `stylelint` is `vscode-stylelint`, for example.

Anyway last word for VS Code team members.

**Comment by Ikuyadeu** [comment]
@mrmlnc Thank you for the detailed explanation.
Yes, I can't decide it.

Now, if you make `.stylelintrc.yml`, that be yaml.
This changes work only for `.stylelintrc` to json.

**Comment by egamma** [comment]
@aeschli we should move ".jscsrc", ".eslintrc" to the corresponding extensions.

**Comment by Ikuyadeu** [comment]
#25939 is already fixed, this PR only fix #25709.

**Comment by aeschli** [comment]
I agree with @mrmlnc. As `.stylelintrc` can be either YAML, JS or JSON so we shouldn't set it to JSON by default.
Users that are sure that the file uses JSON can add that association to their workspace settings. Or they can rename the file to `.stylelintrc.json`.

**Pull request closed without merging**
