### PR TITLE
Add support for custom root URL path through command line option `--route-base-url-path`

### PR DESCRIPTION
**Pull request by oakaigh**
## Setup (HOWTO Test)
- Specify a base URL: `<base-url-path>`
- Git clone the repo
- Build VSCode per ["How-to-Contribute"](https://github.com/microsoft/vscode/wiki/How-to-Contribute)
- Run from CLI
```
./scripts/code-server.sh --port 9888 --route-base-url-path <base-url-path>
```
- Server available at `http://localhost:9888/<base-url-path>`
- (Optionally) Run a proxy routing requests to `<base-url-path>`
- Profit

## Example
- Run from CLI
```
./scripts/code-server.sh --port 9888 --route-base-url-path /user/someuser/proxy
```
- Server available at `http://localhost:9888/user/someuser/proxy`

## Notes
- Non-absolute paths should work; but not all the time especially since sources files are then loaded relative to the current URL, which changes as, for instance, user opens a workspace. The server, however, only serves files from a static path and "pushes" that path to the client at loading time. The server is not informed of the expected path change whatsoever.
- Trailing `/` does not need to be present in the path.

## Related Issues
https://github.com/gitpod-io/openvscode-server/issues/320
https://github.com/microsoft/vscode/issues/153679
https://github.com/microsoft/vscode/issues/165391

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks!

Can you keep the PR as minimal as possible? E.g. don't modify `.gitignore` or `uti.ts`.

What's not so nice is the global `RemotePaths`.

**Comment by oakaigh** [comment]
@aeschli 

> What's not so nice is the global `RemotePaths`.

Well yes, it’s not pretty. The design choice was kind of borrowed from `RemoteAuthoritiesImpl` I guess? (`RemoteAuthoritiesImpl` initiates a global instance `RemoteAuthorities`, whose properties are set within the constructors of the `*Service`s - this is even uglier imo)
I don’t see any other way of doing it other than changing all classes that use `RemotePaths` to take a `RemotePathsImpl` instance instead, which would likely involve a lot of work.

> Can you keep the PR as minimal as possible? E.g. don't modify `.gitignore` or `uti.ts`.

Sure! Updates coming soon.

**Comment by aeschli** [comment]
I tried to avoid the global `RemotePaths`:
https://github.com/microsoft/vscode/tree/aeschli/serverRootPath

**Comment by oakaigh** [comment]
I forgot to mention: the JavaScript Debug Terminal does not seem to be working in this PR right now; this causes the test to fail. I currently do not have time to investigate. Any help is appreciated!

@aeschli Ideally instead of passing the path as a string we could make it a service like `PathResolverService` to allow for more flexibility. What do you think?

**Review by dcar2121 — APPROVED** [review]

**Review by dcar2121 — APPROVED** [review]

**Comment by oakaigh** [comment]
PR moved to https://github.com/microsoft/vscode/pull/202491

**Comment by aeschli** [comment]
Implemented by https://github.com/microsoft/vscode/pull/202491

Note that I changed the argument to `--server-base-path`

**Pull request closed without merging**
