### PR TITLE
Avoid recompiling remote native node modules

### LINKED ISSUE #112320: Build: Linux, avoid rebuilding node modules
https://github.com/microsoft/vscode/blob/d819caf1d27650eb1171657339ffe68726c7a5af/build/azure-pipelines/linux/product-build-linux.yml#L112-L120

Is there any way we can avoid rebuilding these, as we're looking into cutting down build times? Can we try to compile them correctly the first time around? What's the issue here?

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #112320

### CODE REVIEW

**Comment by joaomoreno** [comment]
Build is running, let's see how it goes.

**Comment by joaomoreno** [comment]
CI build passed.

Triggered product build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97399&view=results

**Comment by joaomoreno** [comment]
CI passed. Triggering product build so we verify the assets: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97403&view=results

**Comment by joaomoreno** [comment]
@deepak1556 We already started getting build assets for that commit on our builds page: 56c83dc694. Do you mind downloading them and checking if the changes worked? Ie if everything is compiled as expected, with the right glibc dependencies, both client and server?

**Comment by deepak1556** [comment]
* ea290c5ced which doesn't rebuild, is using gcc-5

```
$ strings ~/Downloads/vscode-server-linux-x64/node_modules/spdlog/build/Release/spdlog.node | grep GLIBCXX
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4.21
GLIBCXX_3.4.20
GLIBCXX_3.4
```

* 56c83dc694 which uses rebuild step has correct gcc-4.8 toolchain

```
$ strings ~/Downloads/vscode-server-linux-x64/node_modules/spdlog/build/Release/spdlog.node | grep GLIBCXX
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4
```

**Comment by deepak1556** [comment]
This is because even when I ignore the cache, `product-build-linux.yml` skips install dependency step https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97463&view=results and uses the result from `product-compile` and hence our env changes are not picked up.

@joaomoreno how can we make sure `product-build-linux` doesn't skip install dependency step ?

Also follow-up question, now that we have different cross-compilation setups, why do we want to install dependencies in the `product-compile` step and save them to cache. Can we just let each platform stage do that operation and save the right result to cache ?

**Comment by joaomoreno** [comment]
Oh. I forgot that as well. The product compile should be the same as the product linux yarn install. That way the product linux reuses the compilation efforts from the product compile. Pushing that and triggering new build.

**Comment by joaomoreno** [comment]
@deepak1556 thanks for the verification steps. e18139116aabf6ea484fbc65260fa39090abab23 did the trick:

```
➜  single cat vscode-server-linux-x64/product.json| grep commit
        "commit": "e18139116aabf6ea484fbc65260fa39090abab23",
➜  single strings vscode-server-linux-x64/node_modules/spdlog/build/Release/spdlog.node| grep '^GLIBCXX'
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4
➜  single cat VSCode-linux-x64/resources/app/product.json| grep commit
        "commit": "e18139116aabf6ea484fbc65260fa39090abab23",
➜  single strings VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node| grep '^GLI
BCXX'
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4.21
GLIBCXX_3.4.20
GLIBCXX_3.4
```

Merging it.

**Pull request merged**
