### PR TITLE
fix(jsDoc): remove one space indentation on multiple enters after closing jsDoc

### LINKED ISSUE #92094: JSDoc Header @file will move cursor one space after Enter
Issue Type: <b>Bug</b>

When a JSDoc header exists on a module, there is a bug where the cursor jumps a space after Enter is pressed.

## Replication

1. Create a new JS file in any project.
1. Enter the following JSDoc Header.
1. Press Enter after positioning the cursor under the header.

```js
/**
 * @file File Description.
 */
```

Screencast with the issue on an empty document: https://d.pr/i/XvJqiF

Screencast with the issue on a document with requires: https://d.pr/i/fUnF2i

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

### PR DESCRIPTION
**Pull request by AshreneRoy**
This PR fixes #92094

### CODE REVIEW

**Comment by mjbvz** [comment]
@AshreneRoy Thanks for looking into this. However I'm not sure this is the correct fix. The file you changed is language agnostic for the most part so we'd like avoid hardcoding jsdoc logic into it. 

@rebornix May know more about what the proper fix would

**Comment by AshreneRoy** [comment]
Sure @mjbvz. Would be great if @rebornix could point me to the right approach.

**Comment by AshreneRoy** [comment]
Please let me know if we are waiting for something here @mjbvz @rebornix

**Comment by mjbvz** [comment]
Closing as we don't want to add jsdoc specific logic in core. Instead the fix should be somewhere in the JS/TS language configuration: 

https://github.com/microsoft/vscode/blob/e8760a5d6c0e09ab692e5b3e414eca018745490f/extensions/typescript-language-features/src/languageFeatures/languageConfiguration.ts#L0-L1


although the linked issue has also [been closed at this point]((https://github.com/microsoft/vscode/issues/92094#issuecomment-707424495) so I'm not sure if this can be fixed with our current APIs

**Pull request closed without merging**
