### PR TITLE
Publish to new CDN

### PR DESCRIPTION
**Pull request by joaomoreno**

### CODE REVIEW

**Review by Thompson1985 — COMMENTED** [review]
Thank you

**Comment by joaomoreno** [comment]
@microsoft-github-policy-service rerun

**Comment by joaomoreno** [comment]
@microsoft-github-policy-service rerun

**Review by lszomoru — APPROVED** [review]

**Comment by lszomoru** [comment]
👏🏻👏🏻👏🏻

**Review by Thompson1985 — COMMENTED** [review]
Okay thanks

**Pull request merged**
