### PR TITLE
Fix #62365 : Added useGlobalStorageForSuggestions Setting

### LINKED ISSUE #62365: suggestSelection 'recentlyUsedByPrefix' share recentlyUsed in different project
### this is my problem:
the project A
image
the project B
image

### I want :
once `con` -> `console` in project A 
it become `con` -> `console` in project B

### PR DESCRIPTION
**Pull request by skprabhanjan**
@jrieken , here is my initial implementation as per your comments to fix #62365 .
Can you please review this and suggest if anything needs to be changed or added ?
Thanks :)

### CODE REVIEW

**Comment by jrieken** [comment]
Don't forget the `_saveState` function ;-) Then we should also think about the name of the setting

**Comment by skprabhanjan** [comment]
@jrieken , Did you get some time to review this and also fix a name for the setting ? XD
Thanks :)

**Comment by jrieken** [comment]
Looking good. Thanks. I will merge and tweak the name of the setting a little.

**Review by jrieken — COMMENTED** [review]
👍

**Pull request merged**
