### PR TITLE
#40288 find replace in resolved config variable

### LINKED ISSUE #40288: Feature Request: Tasks variables replacing
*Sublime Text* has this feature
> `${relativeFile/a/b/}` replace `a` to `b`
> http://sublimetext.info/docs/en/reference/build_systems.html#variables

I use WSL script for work in VSCode. So I need change file or dir path slash, or change suffix some times.

I think this will be a useful feature.

#40256

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
fixes #40288

### CODE REVIEW

**Comment by pradeepmurugesan** [comment]
@isidorn you got sometime to review the changes ?

**Comment by isidorn** [comment]
This PR has conflicts with the main branch due to changes done by @weinand 
@weinand can aslo decide if we would like to take in this PR, if yes conflicts first need to be fixed. Anyways nothing for april

**Comment by pradeepmurugesan** [comment]
@isidorn Resolved the conflicts

**Comment by weinand** [comment]
@isidorn let's revisit this in May.

**Comment by isidorn** [comment]
This will not happen in July, pushing out to August.

**Comment by alexandrudima** [comment]
Cleaning up milestone

**Comment by id0Sch** [comment]
any chance of this happening?

**Comment by grooveygr** [comment]
This implementation will only replace the first instance of a string.
Bash string replacement also offers a "double slash" syntax (`parameter//pattern/string`) for replace all functionality.
For instance, this can come in handy when re-writing path names to python module names (`a/b/c` -> `a.b.c`)
WDYT, should this be part of this PR or part of a new issue?

**Review by riverpaper — APPROVED** [review]

**Comment by roblourens** [comment]
Sorry that this slipped through the cracks. I think the PR is stale now but it's an interesting feature. I'll hand it to @alexr00 to decide whether it's worth revisiting

**Comment by alexr00** [comment]
@pradeepmurugesan thank you for the PR. Given that https://github.com/microsoft/vscode/issues/40288 was closed as out of scope, we won't be merging this PR right now.

**Pull request closed without merging**
