### PR TITLE
Redone YAML grammar

### PR DESCRIPTION
**Pull request by nDmitry**
Some symbols can break syntax highlighting with current YAML grammar, e.g.:

There is a new implementation of YAML grammar that can be found in newer sublime and textmate versions, and I think we can easily use it in VS Code. Here's the highlighting with the new grammar:

---

Imported from sublimehq/Packages and textmate/yaml.tmbundle.
Originally created by @FichteFoll with additional patches from @Briles and @wbond.
Ported to tmLanguage by @infininight.

Known limitations:
- Most indentation is not checked, except for block scalars, where it is also not verified (i.e. highlights even if less indentation used than required).
- Properties are sometimes incorrectly highlighted for nested block collections (`- !!seq -`).

Synced as of sublimehq/Packages@c52dd91, textmate/yaml.tmbundle@953d955

### CODE REVIEW

**Comment by nDmitry** [comment]
Related: textmate/yaml.tmbundle#1

**Comment by christiandreher** [comment]
I have a similar issue. You could try if this also works now. Heres a screenshot:

sl-bug-yml

Here's the original code:

```yml
### DEPLOY

# Deploy to staging server
deploy-staging:
  stage: deploy
  script:
    - rsync -avzh --progress --delete -e ssh -p "dist-prod/" "${DEPLOY_SERVER_STAGING_USER}@${DEPLOY_SERVER_STAGING_URL}:${DEPLOY_SERVER_STAGING_TARGET}"
  only:
    - master

# Deploy to production server
deploy-prod:
  stage: deploy
  script:
    - rsync -avzh --progress --delete -e ssh -p "dist-prod/" "${DEPLOY_SERVER_PROD_USER}@${DEPLOY_SERVER_PROD_URL}:${DEPLOY_SERVER_PROD_TARGET}"
  only:
    - tags

```

**Comment by nDmitry** [comment]
Seems working too now.

screen shot 2016-09-09 at 15 40 11

**Comment by christiandreher** [comment]
Awesome, great job :) Thank you very much, this bothered me for weeks now :)

**Comment by FichteFoll** [comment]
I just want to note that this piece *originally* included a licence, in both the ST and the textmate repos.

According to the [CLA](https://cla.microsoft.com/cladoc/microsoft-contribution-license-agreement.pdf), submissions including work of a third-party are valid as long as the original copyright and license information are retained.

**Comment by nDmitry** [comment]
Thanks, I have updated the license.

**Comment by aeschli** [comment]
I updated the grammar to textmate/yaml.tmbundle@9a4135d (2016-08-24), added tests and also updated the license.
See @5ba13ddbf359ae3767ea394d03589395089fa529 and @5073dfcc3739ba0ec4e1affeb033ae17d1519227

Thanks a lot @nDmitry and @FichteFoll, great work!

**Comment by Haider-BA** [comment]
how can I link yaml-cpp **library and header files** in Visual Studio code C++? I put yaml-cpp include director in "${workspaceRoot}/externals/include"..

**Pull request closed without merging**
