### PR TITLE
Add indent based code folding

### PR DESCRIPTION
**Pull request by aeschli**

### CODE REVIEW

**Comment by aeschli** [comment]
@alexandrudima Alex, FYI

**Comment by aminroosta** [comment]
@aeschli 

Is there a way for extensions to figure out which parts of code are folded?
For example vim extensions need this to properly move the cursor when different parts of code are being folded.

I think this is not possible right now and if that's the case, what do you think about exposing `getHiddenAreas()` function to extensions?

**Comment by aminroosta** [comment]
@aeschli atom editor uses the same indentation based folding but also includes the line after a fold-range with a `foldEndPattern` regex check. The regex pattern is different for each language.

For css: `'foldEndPattern': '(?<!\\*)\\*\\*/|^\\s*\\}|\\/*\\s*@end\\s*\\*\\/'`
For js : `'foldEndPattern': '^\\s*\\}|^\\s*\\]|^\\s*\\)'`

Some language extensions in vs code already have this pattern ([php](https://github.com/Microsoft/vscode/blob/master/extensions/php/syntaxes/php.json#L21) but not all of them.

Clearly this needs to be added to all language extensions but it doesn't seem to be easy.
Specially because each extension has it's own syntaxes files (even with different formats).

Do you think supporting C based languages with this approach is a good idea (just for now)?
Should i send a PR only supporting languages with block folding ( {  } ).

**Comment by aeschli** [comment]
@aminroosta There is currently no API in the extension host to find out about folded regions. But there is ongoing work for improving VIM support to enable operations in the view model, see #9143

Supporting folding end patterns is a good suggestion. For now we have no work planned as other issues have higher priority.

**Comment by rebornix** [comment]
@aminroosta we already have new APIs for cursor movement across visible lines, you can run 

```
vscode.commands.executeCommand("cursorMove", {
      to: "lineUo", // or "lineDown"
      noOfLines: 1
    });
```

to move across folded lines.

**Comment by rebornix** [comment]
@aminroosta current implementation of VSCodeVim is not handling cursor moving correctly. We are changing cursor position ourselves, which breaks the cursor moving in folded code. But now I find that we should leverage Code's existing command `cursorLeft`, `cursorLeftSelect`, etc to perform the real cursor moving. In this case, we don't need to know the hidden lines information any more.

**Comment by aminroosta** [comment]
@aeschli I just found another use case :-), implementing toggle-fold command.
without information on folding areas that would be impossible.

**Comment by sandy081** [comment]
@rebornix I am seeing following behavior in VS Code and it is similar to Vim behavior you mentioned in your example

jul-22-2016 11-10-27

**Comment by sandy081** [comment]
After discussing with @rebornix fixing the issue #9619 will let Vim to completely use VS Code apis for cursor movements, thereby, fixing the folding issue automatically.

**Pull request merged**
