### PR TITLE
Added fly-out animation to menu

### PR DESCRIPTION
**Pull request by dandalton1**
Just as it sounds; I changed two lines of CSS to add transitions.

One is to add a transition to the `left` position of the code editor that lasts for 200 milliseconds.
One is to add a transition to the `width` of the code editor that, again, lasts for 200 milliseconds.

Doing just the `left` would add a jittering to the upper-right hand side of the buttons, since the width would be updated immediately. Computing both the `left` and `width` as the menu "flies out" would keep the position of those upper-right hand buttons constant.

### CODE REVIEW

**Comment by RMacfarlane** [comment]
Hey @dandalton1, thanks for submitting a PR! Is there an issue tracking this?

**Comment by dandalton1** [comment]
#59664 (a continuation of #56021) references this. I can't find anything else that specifically mentions a menu animation.

**Comment by RMacfarlane** [comment]
This change seems to assume that the sidebar is on the left:
transition

I suggest scoping css changes as specifically as possible, if this should only effect the sidebar, then try to target only that. You can use the `Developer: Toggle Developer Tools` to bring up chrome dev tools and examine classes.

**Comment by dandalton1** [comment]
It seems to me that the logic for controlling the content for the sidebar also happens instantaneously; affecting VSCode's DOM instantly in the process. I'm going to propose adding a 200 ms delay via `setTimeout()` or something similar (possibly in a `try`/`catch` to make sure it's compatible with older browsers that maybe don't support `setTimeout()`). I'll find out more and commit/comment again later on.

**Comment by dandalton1** [comment]
I'm gonna simply close this after further consideration; animating the width of the sidebar makes a ghosting effect even after "sliding out" started to work. At least I tried, and I'm sorry for the inconvenience!

**Comment by RMacfarlane** [comment]
Thanks for giving it a shot!

Maybe you've already looked through these, but we do have a "good first issue" tag that are good places to start contributing, if you're interested.

**Pull request closed without merging**
