### PR TITLE
Make OSS product long name actually long

### LINKED ISSUE #2982: OSS .desktop program name should be "Visual Studio Code( - OSS)"

### PR DESCRIPTION
**Pull request by Tyriar**
'Code - OSS' didn't look great in the launcher.

Fixes #2982

---

@joaomoreno is this is fine for Windows and Mac? Matches format of official build.

### CODE REVIEW

**Comment by joaomoreno** [comment]
I believe this was a purposeful choice. We don't want to apply the `Visual Studio` brand to the OSS flavour of Code. @chrisdias has the word on this.

**Comment by colbyrussell** [comment]
It might actually be useful in communication to refer to the distinction as "vscode" and "osscode" (or "oscode"?).  This would have probably helped out in issue #60 (see [comment 6](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005)).  Compare to Chromium and Google Chrome.

Maybe @chrisdias has an opinion on this?

**Comment by chrisdias** [comment]
The OSS version is just that - the OSS version, it is not Visual Studio. It is only "Visual Studio" when we build the distro which applies our branding, licensing, telemetry, etc. We should not merge this in.

**Comment by Tyriar** [comment]
@chrisdias thanks for the clarification :)

**Comment by colbyrussell** [comment]
@Tyriar Close #2982?

**Pull request closed without merging**
