### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by MattMarquise**
Simply made code more organized.

This PR fixes an issue where the code wasn't aligned properly in the head and body sections. I simply fixed that problem.

### CODE REVIEW

**Comment by bpasero** [comment]
Sorry, but we do not accept changes to test files.

**Comment by MattMarquise** [comment]
@bpasero is there any open source repos from Microsoft that I could review code in?

**Comment by MattMarquise** [comment]
I'm trying to get better at reviewing code.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Pull request closed without merging**
