### PR TITLE
Only apply TS Dot Accept Suggestion if Previous Character is a valid identifier

### LINKED ISSUE #17584: Making dot-completion and object spread operator work together
- VSCode Version: 1.8.1

```ts
let x = { a: 1, b: 2 }
let y = {
  c: { d: 4 },
  ...x // <-- here
}
```

When you actually type the above code, the first `.` you type will trigger completion, showing `c`. If you press the second `.`, it will become `.c.` and should completion of `d`.

To avoid this, you have to press `[esc]` after you type the first `.`.

UPDATE: this occurs with `typescript@2.2.0-dev20161219`, but not in `typescript@2.2.0-dev20161206`.
Seems like a regression.

### LINKED ISSUE #17770: Import intellisense bug for some packages
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.7.1|
|csharp|ms-vscode|1.6.1|
|debugger-for-chrome|msjsdiag|2.4.1|
|vscode-format|ryannaddy|0.0.6|
|shader|slevesque|0.2.2|
|shader-toy|stevensona|0.1.8|

---

Steps to Reproduce:

1. Install pixi.js from npm with typings
2. Try to import a relative path downwards( import Person from '../person' for instance ). The import will suggest "pixi.js" as it includes a '.' character or something.

### LINKED ISSUE #17825: Please do NOT autocomplete the TypeScript module name when ".." is typed.
- VSCode Version: 1.8.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Create a project that references at least one module with name(s) containing the character “.”, like `zone.js`, in package.json.
2. Run `npm install`.
3. Create a TypeScript file.
4. Type `import {} from ".."` in the created file.
5. While I was trying to reference a module from the parent folder of the one the created file is within, what is automatically completed, instead, is something like `import {} from "zone.js"`.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #17825
Fixes #17770
Fixes #17584

**Bug**
When typing two or more `.` in a row, we end up unexpectedly accepting suggestions in TS files. This is caused by the custom keybinding that ts registers for `.`.

**Fix**
Only accept the suggestion on `.` if the previous character is a valid identifier character. This is accomplished by registering a new command in TS. 

I'm not too happy with this workaround, but wasn't able to find a better way to do this. Let me know if you have any suggested improvements.

### CODE REVIEW

**Comment by dbaeumer** [comment]
Seams reasonable to me since this can't be handled otherwise.

**Comment by joaomoreno** [comment]
@mjbvz @dbaeumer 

I had to revert this PR since it broke pressing `.` when the suggestion widget is visible:

kapture 2017-01-10 at 10 09 00

Having the `.` character be put in the buffer in a delayed fashion via the extension host is not the best way to go, since it will cause typing delay.

I talked to @jrieken about this and he pointed to #7326, an API request which could solve these issues in a better way. I suggest to approach this problem with that in mind. 👍 

- Reopened #17825, #17770, #17584
- Reverted in 31997b32c354b0531f296379cec364b094ee362d

**Comment by dbaeumer** [comment]
@joaomoreno thanks.

**Comment by mjbvz** [comment]
@joaomoreno Thanks for catching this and the quick revert. Never was too happy with this approach so I'll look into #7326. This is a pretty major annoyance when working with TS files and I'd like to fix it for 1.9 if possible

**Pull request merged**
