### PR TITLE
Remove Jupyter specific loader special case

### LINKED ISSUE #121245: Investigate not including our loader in the notebook webview by default
Notebook webviews currently always loads [our loader script](https://github.com/microsoft/vscode/blob/3e22994cad3d1f97d56649fd23a06fc1a443c177/src/vs/loader.js). This allows output renderers to use amd style module loading, which I believe is how Jupyter renderers work.

However for non-Jupyter notebooks, it would be nice if we could use JavaScript modules instead. This would let us avoid loading/parsing an extra script inside the webview and also reduce the size of the custom api we give to output renderers

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
This PR fixes #121245

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
@mjbvz . I was making the change quick here: https://github.com/microsoft/vscode-jupyter/pull/6318/files to ship requirejs with the Jupyter preloads. To test with I made the change in the draft PR here that was basically just your closed change here: https://github.com/microsoft/vscode/pull/123632 to remove the special case.

Wasn't fully sure though if you would like to make the change to remove the special case yourself. So I put this PR up as a quick draft. If this isn't the right fix I can just close this or alter.

**Review by mjbvz — APPROVED** [review]
LGTM. Feel free to merge if everything is good on the Jupyter side

**Comment by mjbvz** [comment]
Since it's late in the iteration now, let's merge this next week for VS Code 1.59 instead

**Comment by IanMatthewHuff** [comment]
@mjbvz So sorry I should have commented back here when we talked about it. I mentioned in the morning notebook standup on Tuesday that I didn't see the need the take this late in endgame and Peng / Rob agreed. So sounds like we are on the same page I'll look to submit early next iteration.

**Comment by mjbvz** [comment]
Thanks! Will go out in the first 1.59 insiders builds

**Pull request merged**
