### PR TITLE
Remove experimental from WCO enable setting name

### PR DESCRIPTION
**Pull request by rzhao271**
Ref #161218
Ref #167060

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Are we expecting more settings for `windowControlsOverlay` or not, because if not I think I would prefer a shorter key.

**Comment by rzhao271** [comment]
I don't expect more settings for the WCO. I'm renaming the setting now

**Comment by bpasero** [comment]
👍 , leaving it to @sbatten for this one

**Comment by sbatten** [comment]
Actually, now that I think about it, we don't really need/want to do this rename. The setting should not exist in the long term. There is no reason for us to support disabling the WCO if they function well. The setting just allows opting out in case there are early adoption issues.

**Comment by rzhao271** [comment]
SGTM
Closing

**Comment by bpasero** [comment]
Yup agree, +1 if we end up removing this setting altogether.

**Pull request closed without merging**
