### PR TITLE
Update countBadge.css

### LINKED ISSUE #132456: Label badge not aligned vertically
Steps to Reproduce:

1. Open the problems panel with at least one problem in it
2. Badge widget next to the file name is not aligned vertically
    image

### PR DESCRIPTION
**Pull request by deontic**
reduce the CSS required to align the problems count-badge
N.B the commit message should just be "reduce the CSS required" the previous fix does align vertically.

RE  #132456

### CODE REVIEW

**Comment by lszomoru** [comment]
@Un-index, thank you very much for the contribution. I have checked out the branch but as you can see from the screenshot below, adding `vertical-align: text-top;` does not address the vertical alignment issue. 

image

**Comment by Un-index** [comment]
Weird. It seems to be working for me:
image

**Comment by lszomoru** [comment]
I just pulled your branch, compiled and run it. As you can see from the screenshot below, the `monaco-count-badge` does have `vertical-align` set but the alignment does not work for me as expected. The badge continues to be aligned to the bottom of its container.

image

**Comment by Un-index** [comment]
Could you tell me how to compile from my branch so I could further see what's happening?

**Comment by lszomoru** [comment]
You can find the list of prerequisites [here](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) and the list of steps to build and run [here](https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run).

**Comment by Un-index** [comment]
I built it from my repo and it seems to be aligned:

image

**Comment by lszomoru** [comment]
I have tested your pull request on macOS (using `scripts/code.sh`) though I would not have expected to have different behaviour on different operating systems. I wonder if it might be related to zoom levels. Are you using any custom zoom level on your machine? I am using `"window.zoomLevel": 1` on the machine on which I am testing. Also are you saying that you have confirmed that your approach does not work in `yarn web`? If so, we need to opt for a solution that works on all runtime platforms (desktop, and web).

**Comment by Un-index** [comment]
I meant it could be possible that it doesn't work there (was assuming that's where you tested it) although I don't see any reason why that could happen so it probably works there too (problems are not showing up for me there so I can't test that).

I've tested the build on another Windows device and it seems to working there as well. I've tested with multiple zoom levels  ("window.zoomLevel":  -1, 0, 1, 2) and that seems fine too.

**Comment by lszomoru** [comment]
I did revert my change as while the fix was working it was too generic. I will take another look at this later this week.

**Comment by Un-index** [comment]
Maybe just one more person could test it to see if this fix is specific to my device?

**Comment by Un-index** [comment]
@lszomoru  hi, it's been a while
do you think we should close this issue since there might be things that warrant more directed activity

**Comment by lszomoru** [comment]
@Un-index, I still want to get to the bottom of this, but will push this out to October.

**Comment by joaomoreno** [comment]
Closing this as beyond stale.

**Pull request closed without merging**
