### PR TITLE
Dialogs: Add explicit `reorderButtons` option.

### PR DESCRIPTION
**Pull request by rehmsen**
The default is `auto`, which will reverse buttons on Mac and Linux.

This removes the unexpected and undocumented side-effect of `cancelId` triggering button reversal (#170492). For backwards compatibility, in this change I kept the behavior that when `cancelId` is set, the cancel button is moved to the second last position.

In the VSCode code base, almost all dialogs that have multiple buttons also set a `cancelId`, so this change will not affect them. There are two exceptions:

* in [workspace.contribution.ts:347](https://github.com/microsoft/vscode/blob/d8568bb19e5acb54253afb2cb48123785db2f8d9/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L347), trusted and untrusted buttons will change. I believe this in line with user expectations on their platform (having the primary/safe option on the right for Mac/Linux)
*  [fileDialogService.ts:235](https://github.com/microsoft/vscode/blob/d8568bb19e5acb54253afb2cb48123785db2f8d9/src/vs/workbench/services/dialogs/browser/fileDialogService.ts#L235) uses `cancelId=-1` to indicate there is no cancel button - which has the probably undesired side-effect of moving the last button ("Open files" or "Learn more")  to the second last position because of how slice works with negative indices.  This is unchanged by this commit and needs to be fixed separately.

### CODE REVIEW

**Comment by rehmsen** [comment]
@microsoft-github-policy-service agree [company="Google"]

**Comment by rehmsen** [comment]
@microsoft-github-policy-service agree company="Google"

**Comment by rehmsen** [comment]
@bpasero for awareness (with whom I have discussed on my related PR #171595 and issue #170492.

Please let me know what I can do to get this merged. Cna someone run the workflows for me? Apparently I cannot trigger this from my end.

**Comment by bpasero** [comment]
I am not a fan of an explicit option for this. See https://github.com/microsoft/vscode/issues/170492#issuecomment-1398181474

**Review by bpasero — CHANGES_REQUESTED** [review]
I have a new method for massaging dialog options based on HIG:

https://github.com/microsoft/vscode/blob/f861ec8105266783a6bc4e09e7f90ec49a606cb2/src/vs/platform/dialogs/common/dialogs.ts#L431-L519

I was planning to adopt this for native and custom dialogs, but only next week when the next milestone starts. Let me know what you think.

**Comment by rehmsen** [comment]
Hi Benjamin,

thanks for putting all the work in. I love the explicitness, the comments explaining what we are trying to do, and the pointer to the relevant HIGs - that is a big improvement over the status quo.
I have a couple of detail questions/suggestions around readability of the code, but I am not sure I can comment line by line somehow and whether that would be helpful for you. Let me know.
I am also not very familiar with the VSCode development process, so I am not sure how long each milestone is and how long waiting for the next one would put it off. Generally, this is not something that we need urgently, I would just love to keep momentum while we have all the context etc. If the actual releases is pushed out a bit, that is less of a problem.

Again, thanks for digging into this so thoroughly and working on improving this across the board.

Ole

**Comment by bpasero** [comment]
One idea I have is to do: https://github.com/microsoft/vscode/pull/171595#issuecomment-1402192320

**Comment by bpasero** [comment]
Work happens here: https://github.com/microsoft/vscode/pull/172754.

I will comment there on the API and close this one. Thanks for pushing me for revisiting this 👍

**Pull request closed without merging**
