### PR TITLE
Fix #55470

### LINKED ISSUE #55470: Image preview CTRL+Wheel zooming inverted after attempting to drag image
Issue Type: <b>Bug</b>

Similar issue as #48514 but I managed to find a way to reproduce it (occurs at least on previews, been unable to test on comparisons, but if it occurs on simple previews I'd imagine it's likely for all image displays).  
Searching issues leads to a lot of references to #43138, possibly related?

Steps to reproduce:  
1. Launch Code
2. Open an image
3. CTRL+mouse wheel should correctly zoom in with scroll up, and out with down.
4. Attempt to pan the image by left-click and dragging (not something Code seems to support).
5. Scroll zoom should now be inverted.

Restarting Code usually fixes it until reproduced again, but not always. Re-launching without an image open and opening/scrolling in some other text-based files seems to help.

Does this issue occur when all extensions are disabled?: **Yes**

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe *[Workspace folder path, redacted as contains private work info]*|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vscode-todo-plus|fab|2.2.1
vscode-firefox-debug|hbe|1.4.3
svn-scm|joh|1.31.0
debugger-for-chrome|msj|4.8.2
material-icon-theme|PKi|3.5.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by hunghw**

### CODE REVIEW

**Comment by mjbvz** [comment]
How did you test this?

**Comment by hwhung0111** [comment]
First, I built vscode on Windows 10 and tested on it. Then, I tested the issue on the other two OSs by the virtual machine.

**Comment by mjbvz** [comment]
What input methods did you use to verify this? Mainly scroll wheel, track pad.

It seems to work ok on macos. The scroll wheel zoom behavior now matches what photoshop does

**Comment by hwhung0111** [comment]
I tested three kinds of zoom in/out ways. 
- ctrl + scroll wheel
- pinch on touchpad
- click other program and move cursor on the image in the vscode and use "ctrl + scroll wheel".

**Comment by mjbvz** [comment]
Ok, let's merge this to insiders and see if it causes any problems for real world users

**Comment by mjbvz** [comment]
The fix will be in the next VS Code insiders build

**Pull request merged**
