### PR TITLE
fix #161239

### LINKED ISSUE #161239: Resizing editor panes is really slow once settings editor is opened
Open a text editor and settings editor side by side and resize the sash in between and notice a lot of lag:

Recording 2022-09-19 at 15 57 29 (1)

A lot of time spend in `listView#probeDynamicHeight`:

image

[CPU-20220919T155811.cpuprofile.zip](https://github.com/microsoft/vscode/files/9599535/CPU-20220919T155811.cpuprofile.zip)

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixed #161239

### CODE REVIEW

**Comment by bpasero** [comment]
👏 make is smooth for me again.

**Review by bpasero — APPROVED** [review]

**Comment by joaomoreno** [comment]
I actually was looking forward to a review by @rebornix, this is why I assigned him to it. @rebornix can you make sure things look good to you here?

@bpasero Did this PR appear in #codereview?

**Comment by bpasero** [comment]
@joaomoreno no I just gave my approval after testing it, was not aware of auto merge.

**Comment by rebornix** [comment]
@joaomoreno the fix is great, it's working great, thanks for the fix!

**Pull request merged**
