### PR TITLE
feat: enable sandbox for proxy auth window

### LINKED ISSUE #97301: Debt: use ipc to communicate with the auth dialog
Follow-up to https://github.com/microsoft/vscode/issues/97199 , since `executeJavaScript` calls are hard to debug and they are just inline script evaluation that can easily break CSP.

1) We should change `BrowserWindowConstructorOptions` for the auth window

**from**

```
const opts: BrowserWindowConstructorOptions = {
			alwaysOnTop: true,
			skipTaskbar: true,
			resizable: false,
			width: 450,
			height: 220,
			show: true,
			title: 'VS Code',
			webPreferences: {
				nodeIntegration: true,
				webviewTag: true
			}
		};
```

**to**

```
const opts: BrowserWindowConstructorOptions = {
	alwaysOnTop: true,
	skipTaskbar: true,
	resizable: false,
	width: 450,
	height: 220,
	show: true,
	title: localize('authRequire', "Proxy Authentication Required"),
	webPreferences: {
	      sandbox: true,
               contextIsolation: true,
               preload: require.toUrl('vs/code/electron-browser/proxy/auth-preload.js')
	}
};
```

2) Setup ipc channel in the preload script

3) Replace `executeJavaScript` call in `vs/code/electron-main/auth.ts` with `win.webContents.send`

This will align well with https://github.com/microsoft/vscode/issues/92164 

/cc @bpasero once you setup a structure for how preload communication should look, we can adopt it here.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/97301

Steps to verify:

* Clone https://github.com/joaomoreno/proxy-containers
* cd basic-auth && ./run.sh
* open Code - OSS
* Settings > Proxy > http://127.0.0.1:3129
* Open developer tools
* fetch('https://github.com')
* play with the auth dialog

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
I only did a high level check and defer to Joao for deeper review as he owns this code.

As feedback, please move these files out of `electron-browser` into `electron-sandbox`

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Sorry for taking long reviewing this. Behavior seems good. But I do see the menu actions, on Linux:

image

**Comment by joaomoreno** [comment]
Btw, since I don't have Docker right now, I tested with this snippet over after [this line](https://github.com/microsoft/vscode/blob/4f65b914448897ecb5b5ca29003b469c54668504/src/vs/code/electron-main/auth.ts#L38-L38):

```
		setTimeout(() => {
			this.onLogin({
				event: { preventDefault() { } },
				authInfo: {
					isProxy: true,
					host: 'joaomoreno.com',
					port: 1234
				},
				cb: (u, p) => {
					console.log(`${u}:${p}`);
				}
			} as any)
		}, 2000)
```

**Comment by deepak1556** [comment]
@joaomoreno I don't see the menu actions in my linux testing, can you try again with the updated branch. Thanks!

**Comment by joaomoreno** [comment]
Strange, I just picked this up again and was able to reproduce it the very first time I launched. And then never again: I've tried many many times, it just doesn't repro.

**Review by joaomoreno — APPROVED** [review]

**Comment by deepak1556** [comment]
Thanks for the review!

**Pull request merged**
