### PR TITLE
change seedSearchStringFromSelection to enum never, always, selectionOnly

### LINKED ISSUE #113830: [Insider/1.53.0] Find editor.action.nextSelectionMatchFindAction seeds from the Nearest Word, not from the last searched word/string
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0:

Steps to Reproduce:
1. Double click on a function name in the code say "function1", press F3.
2. On the found part, move the cursor and click beside any other string say "string1", without selecting it, I would expect VSCode shall still be searching for "function1".
3. Press F3, **VSCode will go to the next occurence of "string1" and not "function1"**
**Example:**
`Void function1( type arg1, type string1 );`

Does this issue occur when all extensions are disabled?: Yes

Not sure why https://github.com/microsoft/vscode/issues/107144 was closed without resolving the issue.

VSCode will force to seed the word near cursor in normal editor, which is not expected. Reference: UltraEdit.

https://user-images.githubusercontent.com/397543/103669402-4ff7d080-4f9e-11eb-9673-537c5c8866e8.mov

### PR DESCRIPTION
**Pull request by swinder0161**
never: Never seed search string from the editor selection
always: Always seed search string from the editor selection, including word at cursor position
selectionOnly: Only seed search string from the editor selection

This PR fixes #113830

### CODE REVIEW

**Comment by swinder0161** [comment]
@rebornix Please check code change, I am trying to fix the failed item.

**Comment by swinder0161** [comment]
@rebornix with new commit I have solved the failed item and also the problem that seed from cursor was never stopped even if seedSearchStringFrom Selection is false.

please help to review and merge.

**Comment by swinder0161** [comment]
@rebornix Any suggestion? please let me know if any change needed

**Comment by rebornix** [comment]
@swinder0161 I'll take a look this week and have it merged.

**Comment by swinder0161** [comment]
> @swinder0161 I'll take a look this week and have it merged.

Hi @rebornix I hope you got time to review. Please let me know if any changes needed.

Thanks,
@swinder0161

**Comment by swinder0161** [comment]
- _const seedSearchStringFromSelectionOnly = editor.getOption(EditorOption.find).seedSearchStringFromSelection !== 'always';_
+ **const seedSearchStringFromNonEmptySelection = editor.getOption(EditorOption.find).seedSearchStringFromSelection === 'selection';**

@rebornix after this change did you confirm that the problem of seed from cursor was never stopped is solved too?

**Comment by rebornix** [comment]
@swinder0161 you are right, it should be checking always, thanks!

**Comment by swinder0161** [comment]
Do you want a PR from me? or else you can do it directly on your side.

**Comment by rebornix** [comment]
@swinder0161 thanks for offering help. I validated that checking `=== 'selection'` behaves the same as `!== 'always'`.

**Comment by swinder0161** [comment]
I will validate also and confirm. Thanks for informing.

**Pull request merged**
