### PR TITLE
Remove side effect from `array.some` callback

### PR DESCRIPTION
**Pull request by CGNonofr**
`some` method callback is supposed to be side-effect free. Also, `findIndex` is now well supported

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
The change looks good, but I'm missing where the side effect is?

**Comment by CGNonofr** [comment]
The `index` variable is declared outside of the callback and modified inside the callback

**Review by Tyriar — APPROVED** [review]
Oh I thought you meant _getTerminalObjectIndexById has a side effect. I wouldn't call .some setting some value outside it's callback a problem, it's basically the same thing as doing it with a for loop. Regardless, the code looks better with your changes so thanks 🙂

**Review by meganrogge — APPROVED** [review]

**Comment by CGNonofr** [comment]
> Oh I thought you meant _getTerminalObjectIndexById has a side effect. I wouldn't call .some setting some value outside it's callback a problem, it's basically the same thing as doing it with a for loop. Regardless, the code looks better with your changes so thanks slightly_smiling_face

It's a problem it you want to tree-shake the code and expect calls to `some` to be side-effect free

**Pull request merged**
