### PR TITLE
Resolve relative REPL paths

### PR DESCRIPTION
**Pull request by felixfbecker**
@bpasero is this the correct usage? Still cannot build + test

https://github.com/Microsoft/vscode/issues/13370

### CODE REVIEW

**Comment by isidorn** [comment]
Usage looks good to me -> merging in.
Thanks :beers:

**Comment by felixfbecker** [comment]
The usage apparently wrong - absolute paths are broken now. Seems like you cannot call that function with an absolute path.

**Comment by felixfbecker** [comment]
Absolute paths are broken now
```
Unable to open 'DefinitionResolver.php': File not found (c:\Users\felix\git\OpenSource\php-language-server\C:\Users\felix\git\OpenSource\php-language-server\src\DefinitionResolver.php).
```
Seems like the context service cannot resolve paths that are already absolute.

**Comment by isidorn** [comment]
@felixfbecker thanks for fixing and testing this feature - you are doing the whole cycle :)

It seems like we should include node 'path' and perform this check https://nodejs.org/api/path.html#path_path_isabsolute_path

Let me know if you are on it, if not no worries I can push it as well.

**Comment by felixfbecker** [comment]
I'm always running on Insiders, and need to click on links in the REPL on a minutely basis 😉 

I though about using `path.isAbsolute()` too, but that would only work for paths, not `file://` URIs.
Other options:
- Capture the "root" component of the regexp again to check if it exists
- Modify the context service to accept relative paths

Btw I'm a bit surprised everything works correctly in the output panel, but not in the REPL - shouldn't they share the same code for stuff like this?

**Comment by isidorn** [comment]
@felixfbecker yes, perfectly that code would be shared. I could actually look into that refactoring next week.
I would not modify the context service without approval from @bpasero 
I would also try to reduce regex magic to a minimum - for simplicity.

**Comment by felixfbecker** [comment]
Another improvement that I would like, currently the terminator `at ` is accepted (for NodeJS exceptions like `uncaught Error Bla at index.js:3`), PHP exceptions have a similar wording, but say `uncaught Error Bla in index.php:3`.

**Comment by felixfbecker** [comment]
And it would be so awesome if the REPL had the same features as the output panel - especially finding and selecting more than one page of text. At the same time the output panel should have the CLI color support of the REPL.

**Comment by isidorn** [comment]
The problem with aligning repl and output lies in the fact the repl is using a tree as an implemenation detail and output an editor. You can read up more about this here https://github.com/Microsoft/vscode/issues/11462

**Pull request merged**
