### PR TITLE
fix for "Cannot Create keybinding to restart a specific Task" 

### PR DESCRIPTION
**Pull request by vemoo**
Issue: #35910.

Also fixes a couple of related issues in src/vs/workbench/parts/tasks/node/processTaskSystem.ts task termination.

### CODE REVIEW

**Comment by vemoo** [comment]
I fixed some typos in some translation keys in [this commit](https://github.com/Microsoft/vscode/pull/36474/commits/0470c68e0c6b39203f61e18d40559e40789ffb4c) becase at the time I could't find any translations in the repository. But now I see there are translations, should I revert that change? or update the keys in the translations also?

**Comment by dbaeumer** [comment]
There is no need to revert nor to update the translation. This happens automatically when we pull the next time from our translation database.

**Comment by vemoo** [comment]
After using vscode for a while I realised this pull request introduces some changes when stopping and restarting tasks.

Right now when terminating or restarting a task, the following happens:

- in the old task system (0.1.0) the task is terminated or restarted directly
- in the new task system (2.0.0) even if there's only one task running a quick pick is always show

In this pull request I unified the code so both stop or terminate the task without asking the user if there's only one running.
What's the intended behaviour?

Also, if an argument is passed but no task is found, should there be some kind of notification for the user?

**Comment by dbaeumer** [comment]
@vemoo 

In tasks 2.0 we always prompt on terminate even if only one task is running. Since task 2.0.0 can run multiple task in parallel we need a dialog for n >= 2 and to make things consistent we always show the dialog. However if a keyboard short cut is bound to terminate a specific task no picker should be shown.

If an argument is passed but the task is not found I would show a picker with the currently running tasks. This is consistent with a short cut to executing a task.

**Comment by vemoo** [comment]
Is there anything else I can do to help this pull request get merged?

**Comment by dbaeumer** [comment]
@vemoo actually I was not sure if your PR addresses these two issues:

> However if a keyboard short cut is bound to terminate a specific task no picker should be shown.

> If an argument is passed but the task is not found I would show a picker with the currently running tasks. This is consistent with a short cut to executing a task.

**Comment by vemoo** [comment]
Yes, with this PR, when terminating a task with an argument

- If the task is found: it's terminated without showing the picker
- If the task is not found: the currently running tasks are show in the picker

**Comment by vemoo** [comment]
I've rebased onto current upstream master, and fixed the conflict.
Now the changes in this PR also use the "notificationService" instead of the "messageService".

**Comment by dbaeumer** [comment]
A lot has changed here especially the fact to be able to reference a task via a task identifier. So I merged the PR by hand and modified it to:

- use the picker directly when no arg is provided. This ensures that we have proper progress
- use task identifier
- only available for task 2.0.0

**Pull request closed without merging**
