### PR TITLE
typo in chs translation

### PR DESCRIPTION
**Pull request by izhangzhihao**
试图=>视图

### CODE REVIEW

**Comment by johnliu2016** [comment]
@lukaschal, typo in chs translation
https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization?path=%2FLocalize%2Fchs%2Fvscode%2Fextensions%2Fmarkdown%2Fpackage.nls.resx.lcl&version=GBmaster&_a=contents
      <Item ItemId=";markdown.preview.scrollEditorWithPreview.desc" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[When the markdown preview is scrolled, update the view of the editor.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[当 Markdown 预览滚动时，更新编辑器的试图。]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@izhangzhihao Please, is it possible to add ENU and CHS screenshot of mentioned string/dialog ?

**Comment by izhangzhihao** [comment]
image

**Comment by lukaschal** [comment]
Fixed as suggested.

File: extensions\markdown\package.nls.resx
ID: ".resx", 0; "markdown.preview.scrollEditorWithPreview.desc"
SRC: When the markdown preview is scrolled, update the view of the editor.
TGT: 当 Markdown 预览滚动时，更新编辑器的视图。

**Comment by izhangzhihao** [comment]
@lukaschal It's not fixed yet!

**Comment by johnliu2016** [comment]
Thanks @izhangzhihao for re-verify, the fix just stays in loc files. @dbaeumer can tell when the fix appears in build.

**Pull request closed without merging**
