### PR TITLE
Isidorn/extensions statusbar

### PR DESCRIPTION
**Pull request by isidorn**
Merge in the extensions status bar to get feedback
@stevencl I will merge what I showed yesterday about the status bar. We try it out for a few days and if we are against it I will remove it.

### CODE REVIEW

**Comment by stevencl** [comment]
I understand the motivation for this and I am aware that this is a stopgap solution due to the fact that we do not have a richer notification UX.

As a stopgap though, I think I would prefer that we have a command in the View menu, 'Show extension warnings and errors' that is off by default. The issue with having an icon in the status bar that when clicked shows the extension commands is that it doesn't provide all that much value to begin with. Then, when there are errors, the changes in colour may be more likely to be missed, as many users may not have been paying that much attention to the icon in the status bar.

Another stopgap solution would be to add another label next to the icon whenever there are errors which shows the number of errors. If that is clicked then we show the extension errors immediately rather than just showing the extension commands.

More importantly though, this highlights the need for a rich notification UX in the product. We have started littering the status bar with notifications like these, all of which when clicked present some info at the top of the screen (in the command palette/quick open). The distance between the status bar and quick open is sufficiently large for these affordances to feel disconnected. While it helps reduce the number of different UX affordances we have in the product (a good thing) I think it requires too much travel with the mouse and doesn't support a holistic view of all of the notifications and warnings that the user needs to pay attention to.

Ideally we require a much richer notification UX for the whole product. This is something we need to work on and is on our UX backlog.

**Comment by isidorn** [comment]
@stevencl all your points make sense
@egamma @chrisdias should decide if the current solution is a good enough for temporary or we even do not want that.

**Comment by egamma** [comment]
@stevencl makes good points.

We need a way to show a user conflicts in the extensions. This is a pain point we have to address now and we need to deliver a minimal tactical solution for this. 

>Another stopgap solution would be to add another label next to the icon whenever there are errors which shows the number of errors. If that is clicked then we show the extension errors immediately rather than just showing the extension commands.

This works for me.

**Comment by isidorn** [comment]
So we agreed on the following:
* if there are no warning or errors - do not show anything in the status bar
* if there are - show the number next to the icon
* leave everything colorless to fit better with the other status bar items
* ask @bgashler1 for a nice icon (sent email)
* on click show all the errors and warnings via message service

As for the future we want to look into adding more color to the status bar.

**Comment by stevencl** [comment]
Sounds good

**Comment by isidorn** [comment]
Ok I have incorporated your feedback,
I am temporarily using an old monaco icon, will incorporate a new one once @bgashler1 provides one.

I still have to look into adding an uninstall action.
To see the new status bar, just create an extension conflict in your extensions folder, e.g duplicate an extension and in the duplicated extension change the publisher.

screen shot 2015-12-11 at 11 20 31

**Pull request merged**
