### PR TITLE
aeschli/127597

### LINKED ISSUE #127597: default light colors `list.focusHighlightForeground` too close to `list.activeSelectionBackground`
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 and Insiders
- OS Version: Windows 10

Hi, I'm writing an extension contributing a theme.

package.json
```json
"themes": [
      {
        "label": "my theme",
        "uiTheme": "vs",
        "path": "./themes/my-color-theme.json"
      }
]
```
my-color-theme.json
```
{
  "name": "my theme",
  "semanticHighlighting": true,
  "semanticTokenColors": {
    "keyword": { "foreground": "#00f" }
  }
}
```

I only want to provide some semantic token colors and don't have any workbench colors. It works well inheriting default light theme until 1.57, probably by #122893

I know I can add `list.focusHighlightForeground` in my theme to bypass this. But I'd like to simply inherit all default colors.

Steps to Reproduce:

1. Open command palette and type to filter
image

### PR DESCRIPTION
**Pull request by aeschli**
This PR fixes #127597

When creating a light theme with no colors defined, relying on our default color, you get an issue in the quick pick as seen in https://user-images.githubusercontent.com/52692178/123897782-0925da80-d932-11eb-8ec7-a819242354fb.png

### CODE REVIEW

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
I think you meant to update `listFocusHighlightForeground` instead? Otherwise the rest of the highlight labels get updated and break color contrast

CleanShot 2021-07-05 at 12 56 20@2x

EDIT: it looks like you already discovered this in https://github.com/microsoft/vscode/issues/127597#issuecomment-873063207 let's discuss alternative plans after our planning call

**Comment by aeschli** [comment]
recording (1)

I updated the patch. the list.focusHighlightForeground default is now either
- if the theme defines `list.activeSelectionBackground` it is `list.highlightForeground`
- else `#9DDDFF`

This comes from the observation that existing themes that modified `list.activeSelectionBackground` made it work with  `list.highlightForeground`.

**Review by miguelsolorio — APPROVED** [review]
Tested this out locally and this looks good! One minor comment is that the function name `IfDefinedThenElse` feels a bit verbose, but then again I have no better suggestions 😄

**Comment by misolori** [comment]
Also, looks like this PR is set to merge into `release/1.58` so we might want to create a new PR

**Comment by aeschli** [comment]
I'll make the change directly on main (without PR). As discussed, we won't fix the issue for 1.58 as the bad contrast was already in 1.57 only very few themes are affected.

**Comment by aeschli** [comment]
Closing the PR. Pushed #127597 to main. Tracked in #127597.

**Pull request closed without merging**
