### PR TITLE
Fix(#112373): scroll in editor causes hover disappear

### LINKED ISSUE #112373: Scrolling in editor hover causes it to disappear
- VSCode Version: 1.52.0
- OS Version: Darwin x64 19.6.0

When scrolling in the info panel that appears when hovering over code or errors, it disappears entirely if you scroll near the bottom. This makes it extremely frustrating to try and look at errors, because they disappear before you can see them.

Info panel scrolling mov

Steps to Reproduce:

1. Write a function with a large documentation page (easiest method is using JSDoc)
2. Mouse over function and try scrolling to the bottom of documentation (where error and warning messages usually appear)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #112373 

`editor` scroll event will close `hover widget` at line [here](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/hover/hover.ts#L120)
So I have added a flag(`_isOnHover`) to control weather editor scroll event should close hover or not. But I think this isn't the best way to do.
Ideally, when mouse was over hover widget, an event should notify `editor` do not response scroll event, `editor` should be `locked`. Just like normal web app, when popup show, user can scroll in popup element, but It won't trigger page scroll. But I didn't find the way to do that.  scroll in hover widget won't trigger editor scroll, maybe that is a lead.
Anyway, that is what I have done now.
Kapture 2020-12-25 at 11 55 14

### CODE REVIEW

**Comment by ulugbekna** [comment]
Thanks for the PR! 

Regarding the behavior when we reach the end of the scroll item: wouldn't it be nicer if the background didn't scroll when the mouse is over hover pop-up, i.e., if the mouse is over the pop-up and we scrolled to the end of the pop-up, nothing should happen on scroll-down?

**Comment by susiwen8** [comment]
@alexdima Hi, I just found the way to make `editor` `fixed`
Kapture 2021-01-11 at 00 05 54

### main idea
add `onmousemove` event for `AbstractScrollableElement`, so we can know which `element` the `cursor` was above.
If cursor was on `hover`, `scroll element` wasn't fired in the `hover`, then just return, it won't trigger `scroll` for `editor`.

### deficiency
I used `findParentWithClass` to check weather `cursor` was on `hover`, and `classList` for `editor`, feels ugly.

PS: There are two proposals in this PR. First one in `hover.ts`, second one in `scrollableElement.ts`.

**Comment by alexdima** [comment]
@susiwen8 Thank you for the PR.

The `ScrollableElement` already has an option to get this behavior called `alwaysConsumeMouseWheel`, so I've chosen to use that option in hovers via https://github.com/microsoft/vscode/commit/61c6334a3f8b5affea69e29bfd657aa534193a4e

**Comment by EECOLOR** [comment]
Why was this not merged? Or am I missing something?

**Comment by hasezoey** [comment]
@EECOLOR it seems like @alexdima chose an different implementation than this PR (shown in the mentioned commit)

**Pull request closed without merging**
