### PR TITLE
Fixes relative paths to folders below code-workspace not preserved

### LINKED ISSUE #83156: Relative paths to folders below code-workspace not preserved on save.
- VSCode Version: 1.39.2
- OS Version: MacOS 10.14.6 (18G87)
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Edit Thing1.code-workpace to include a folder below the current code-workspace(e.g. "../docs")
2. Click "Save WorkSpace As..." and save to a file named Thing2.code-workpace.

Result: Thing2.code-workpace has its relative path turned into an absolute path.

Thing1.code-workpace:
```
{
    "folders": [
      {
        "path": "."
      },
      {
        "path": "../docs"
      }
    ], ...
```

Thing2.code-workpace:
```
{
    "folders": [
      {
        "path": "."
      },
      {
        "path": "/Users/John/myProject/docs"
      }
    ], ...
```

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #83156

Currently only when the workspace config folder is parent of a workspace folder, it's path is saved using a relative path.
This PR extends the use of relatives paths when the workspace config folder is equal or a child of a workspace parent folder.

```
{
	"folders": [
		{
			"name": "Folder1",
			"path": "../.."
		},
		{
			"name": "Folder2",
			"path": "../../../Folder2"
		},
		{
			"path": "."
		}
	],
	"settings": {}
}
```
image

### CODE REVIEW

**Review by aeschli — COMMENTED** [review]
Can't this be implemented much simpler, by basically removing the `isEqualOrParent(folderURI, targetConfigFolderURI)` check?
There are still cases where relative paths are not possible, e.g. on Windows when the locations are on different drives, or the URIs have different schemas or servers. That case should be detected by `resource.relativePath`

**Comment by jeanp413** [comment]
I intended to just use relatives when the workspace config folder is equal or a child of a workspace parent folder as shown in the snippet in #83156
Example: 
If workspace config file is located in `/foo/bar/**/ws.code-workspace` and the workspace folders are:
- /foo/bar/wsfolder1
- /foo/bar/wsfolder1/aaa/wsfolder1_child
- /foo/bar/yyy/zzz/wsfolder2
- /xxx/wsfolder3

Then the first three folders will use relative paths.

I didn't thought that always using relatives paths (except for the cases you mentioned) was preferred. If that's the case then let me know and I'll update the PR

**Comment by aeschli** [comment]
In your example the folder `/` would be the common `workspace parent folder`. So all folders that have the same root as the workspace config file can be represented with a relative path.
But in some scenarios I believe users might prefer absolute paths. So I think what we should do is to always preserve whether a path is relative or absolute.
When the config file is saved the first time (is no longer untitled), we should store all paths relative, if the have the same root as the config file.
What do you think? @bpasero @sandy081 Your input?

**Comment by bpasero** [comment]
> When the config file is saved the first time (is no longer untitled), we should store all paths relative, if the have the same root as the config file.

Yes, I thought we would do that already.

**Comment by jeanp413** [comment]
Pushed some changes to use relative paths whenever possible

**Comment by aeschli** [comment]
I reviewed the issue and found it a bit too complicated. In order to speed this up a bit, I gave it a try myself and came up with https://github.com/microsoft/vscode/pull/93776.
I hope that's ok for you.

**Pull request closed without merging**
