### PR TITLE
Layout when switching from welcome to terminal.

### PR DESCRIPTION
**Pull request by rehmsen**
Before this change, VSCode assumed in multiple places that we only ever either have terminals open (on desktop) or a "welcome" screen (on web, explaining that terminals are not supported). Switching between the two causes a broken layout. This is currently not visible in VSCode because VSCode opens a new terminal as soon as the terminal panel is opened, and closes the terminal panel when the last terminal is closed.

With this change, that assumption is removed and the question whether a welcome screen is available is centralized in one place. This makes it easier for downstream forks to have a welcome screen when first opening the panel, and when the last terminal is closed. In VSCode itself, this still works as before.

This change also removes relying on the side-effect of the `shouldShowWelcome` getter to write a member variable, and removes superfluously setting that member variable when is it already set.

### CODE REVIEW

**Comment by rehmsen** [comment]
Any update here? Do you need anything from me?

**Comment by rehmsen** [comment]
Hi @sbatten, is there any chance this will be reviewed? Should I update the PR one more time? Or do you have a general concern with this change and the PR should be declined?

**Comment by sbatten** [comment]
sorry @rehmsen, this was lost in my notifications and I think @Tyriar should have been assigned.

**Review by Tyriar — DISMISSED** [review]
Thanks and sorry about the delay 😅 

Not sure how to test welcome screens but we'll make sure it gets verified in vscode.dev

**Review by lramos15 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
