### PR TITLE
Fix #166642: Make Run Tests and Debug Tests default profile in sync 

### LINKED ISSUE #166642: Make Run Tests and Debug Tests default profile in sync
Currently, in vscode extension when changing default profile under Run Tests button, it doesn't automatically change it under Debug Tests button. I had to change it again in debug tests.

Does it make sense to make them in sync instead of doing it twice?

Screen Shot 2022-11-17 at 9 41 00 AM

We are using playwright for test automation and we constantly change default profile to switch browsers. I have to change it twice in both run tests and debug tests.
https://github.com/microsoft/playwright/issues/18885

### PR DESCRIPTION
**Pull request by ambujsahu81**
-  fixes [#166642](https://github.com/microsoft/vscode/issues/166642)
- changes in this pull request adds a small code that updates either ( run tests or debug tests ) default profiles to make them sync with any changes done to either of them. It uses label property to sync the default profiles.

### CODE REVIEW

**Comment by ambujsahu81** [comment]
> @ambujsahu81 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by ambujsahu81** [comment]
@microsoft-github-policy-service agree

**Comment by connor4312** [comment]
There's some extra behavior necessary here. Take the following case:

- The user has both FooTestRunner and Playwright tests in their repo
- Playwright has a same-labelled Debug and Run profile, but FooTestRunner does not
- Whenever the user changes their default Playwright playwright, all FooTestRunner configs will get deselected 🐛 

So you will want to preserve the previously selected profiles for any controllers who _didn't_ have a same-labelled profile. I would probably do this by imperatively building a new list and iterating over `controllerProfiles` to handle each one.

**Comment by ambujsahu81** [comment]
> There's some extra behavior necessary here. Take the following case:
> 
> * The user has both FooTestRunner and Playwright tests in their repo
> * Playwright has a same-labelled Debug and Run profile, but FooTestRunner does not
> * Whenever the user changes their default Playwright playwright, all FooTestRunner configs will get deselected 🐛
> 
> So you will want to preserve the previously selected profiles for any controllers who _didn't_ have a same-labelled profile that we switch to. I would probably do this by imperatively building a new list and iterating over `controllerProfiles` to handle each one.

@connor4312 Thank you so much for the feedback. I will work on the feedback and try to add the suggested behavior. 🙂

**Pull request merged**
