### PR TITLE
Rebase current branch onto another branch

### LINKED ISSUE #108725: Git "rebase onto selected" support
Rebase the current branch onto another one selected from the list.

### PR DESCRIPTION
**Pull request by tomerstav**
Added a new command 'Rebase Branch Onto...' in the git command options that lets you select a branch to rebase your current branch onto. Behind the scenes git checkouts the selected branch and runs git rebase [previous branch]. 

Screen Shot 2020-10-18 at 9 18 24 PM

This PR fixes #108725

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Although this looks polished, it's doing the wrong thing. It checks out the target branch and rebases that to the current branch. It should instead just do `git rebase TARGET_BRANCH`.

**Comment by tomerstav** [comment]
@joaomoreno Looks good now? Any other changes you would like?

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Yes, we probably should remove all `onto` references from the command names, etc, so not to confuse users who know what `--onto` does.

Also, when providing a choice picker to the user, we should automatically highlight the branch's upstream, if defined.

**Comment by joaomoreno** [comment]
Thanks!

**Pull request merged**
