### PR TITLE
Avoid native promises when importing modules

### PR DESCRIPTION
**Pull request by bpasero**
We have seen issues when mixing native promises and WinJS promises in the past (e.g. the famous `this._state.then is not a function`  #49177).

It is very easy to mix native promises and WinJS promises when using async imports like so:

`return TPromise.timeout(0).then(() => import("something"));`

To prevent this from happening this PR introduces a `winJSRequire()` method that is not using native promises at all, but WinJS directly.

@Microsoft/vscode since it touches lots of areas and raising awareness

@jrieken and @alexandrudima to review if that makes sense to you

Unfortunately I did not find a way to have the import type flow through in the method so the usage of this method unfortunately has to repeat the import value twice.

### CODE REVIEW

**Review by jrieken — APPROVED** [review]
:+1: as discussed

**Review by Tyriar — APPROVED** [review]

**Review by alexdima — CHANGES_REQUESTED** [review]
I personally find the usage of an utility function to decrease code readability.

AFAICT, the following two snippets produce the same result:
```ts
const r1 = TPromise.wrap(import('vscode-textmate'));
const r2 = winJSRequire<typeof import('vscode-textmate')>('vscode-textmate');

```
AFAICT, they both return correctly an instance of a WinJS Promise:

image

That is what I was using before in `TMSyntax.ts`. I would suggest to go with the `TPromise.wrap` syntax and to write a TSLint rule that looks for usages of `import` and reminds us that we should use `TPromise.wrap` around them.

**Comment by bpasero** [comment]
@alexandrudima 

> AFAICT, the following two snippets produce the same result

Well, in the one case a native promise is created and in the other not, so even though both might produce the same result, your solution still mixes native promises and WinJS promises.

I can see if `TPromise.wrap(<native promise>)` causes the same issue with `this._state.then is not a function` to verify that assumption.

**Comment by bpasero** [comment]
@alexandrudima with `TPromise.wrap(import('xyz'))` I am still hitting an error `this._state.then is not a function`. Steps:
* uncomment the 2 `console.log` statements in `bulkEditService` ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L426))
* change [`doMoveItemToTrash`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/fileService.ts#L931) to the implementation leveraging `TPromise.wrap(import('electron'))` (see below)
* run `scripts/test-integration.sh`
* see output appearing at the end (`"TypeError: this._state.then is not a function", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.js (458)`)

```typescript
private doMoveItemToTrash(resource: uri): TPromise<void> {
	const absolutePath = resource.fsPath;

	return TPromise.wrap(import('electron')).then(electron => {
		const result = electron.shell.moveItemToTrash(absolutePath);
		if (!result) {
			return TPromise.wrapError(new Error(isWindows ? nls.localize('binFailed', "Failed to move '{0}' to the recycle bin", paths.basename(absolutePath)) : nls.localize('trashFailed', "Failed to move '{0}' to the trash", paths.basename(absolutePath))));
		}

		this._onAfterOperation.fire(new FileOperationEvent(resource, FileOperation.DELETE));

		return void 0;
	});
}
```

This does not happen with my proposed solution that avoids mixing native promises with WinJS promises where this can happen if the native promise resolves directly (the `electron` import is already resolved). I think this issue could also reproduce with other node.js imports that are loaded multiple times in different locations where the second load finds the module already in the cache.

**Comment by alexandrudima** [comment]
I can reproduce and here is a reduction:

---

### Refinement 1

```ts
	let p1 = TPromise.wrap<number>(new Promise<number>(function(c, e) { c(1); }));
	Promise.all([p1]);
	// ==> Uncaught TypeError: this._state.then is not a function
```

---

### Refinement 2

```ts
	let p1 = TPromise.wrap<number>(new Promise<number>(function(c, e) { c(1); }));
	let thenFunc = p1.then.bind(p1);
	setTimeout(() => {
		thenFunc(() => {
			console.log(`finished`);
		});
	}, 0);
	// ==> Uncaught TypeError: this._state.then is not a function
```

---

### Refinement 3 that does not use native Promise at all!

```ts
	let c;
	let p1 = new TPromise(function(_c, e) { c = _c; });
	let thenFunc = p1.then.bind(p1);
	setTimeout(() => {
		c(1);
		thenFunc(() => {
			console.log(`finished`);
		});
	}, 0);
	// ==> Uncaught TypeError: this._state.then is not a function
```

IMHO dropping native promises in imports will only cover a subset of refinement 3. This exception will occur anytime someone captures the `then` method before the winjs promise is resolved...

**Comment by bpasero** [comment]
@chrmarti any reason you did not push your solution forward?

**Comment by alexandrudima** [comment]
@bpasero I discussed with @chrmarti on Friday, he was not sure if this was the right solution. But now we have more proof (beyond native promises) that the root cause is the `then` function being overwritten from the state.

I suggest we go forward and merge @chrmarti's PR in debt week.

**Pull request closed without merging**
