### PR TITLE
labelService: allow extensions to contribute label formatting rules

### LINKED ISSUE #66209: Label service rules should be contributable via extension

### PR DESCRIPTION
**Pull request by isidorn**
fixes #66209 
Now it is possible for extensions to contribute label formatting rules. Here's how such a contribution would look like inside a `package.json` for example.

```json
"contributes": {
		"resourceLabelFormatters": [
			{
				  "scheme": "vscode",
                                  "authority": "wsl*",
                                  "formatting": {
				      "label": "${path}",
				      "separator": "/",
				      "tildify": true,
				      "workspaceSuffix": "WSL"
                                 }
			} 
		]
}
```

I will present this tomorrow in standup so we can discuss than more.

fyi @alexandrudima @chrmarti @egamma

### CODE REVIEW

**Comment by alexandrudima** [comment]
:+1: Nice! I think `labels` might be too generic for the extension point.

**Comment by isidorn** [comment]
Thanks for feedback. Here's some alternative names
`labelDisplayRules`
`labelsDisplay`
`uriLabels`
`uriLabelRules`

**Comment by roblourens** [comment]
How loose is `"authority": "wsl*"`, would it match `wsl2+something` or only `wsl+something`?

**Comment by roblourens** [comment]
- `"tildify": true,` - How do we determine the home directory on the remote?
- `normalizeDriveLetter` Why should the extension author control this? Is this true when the remote is windows and false when it isn't?

**Comment by isidorn** [comment]
@roblourens for now we would only support the * as a prefix. However the exact rules of this can be broadened and we do not have to specify them from start.
Determining the homeDirecotry on the remote would have to come from the [`environmentService`](https://github.com/Microsoft/vscode/blob/1bae354b9be012ffbdb63dec7f390938fc7cf225/src/vs/platform/environment/common/environment.ts#L94). So if that one is proper the label would properly be tildified
I agree, let's remove the `normalizeDriveLetter` for now
`seperator` leaving it as a string gives us more flexibility. Yes it could be boolean, but for now I would keep it as a string

Thanks for feedback

**Pull request merged**
