### PR TITLE
Custom TitleBar Randomly Becomes Unclickable (fix #52522)

### LINKED ISSUE #52522: Custom TitleBar Randomly Becomes Unclickable
- VSCode Version: 1.25 Insiders
- OS Version: Windows 10

Steps to Reproduce: Didn't notice a particular pattern to reproduce 

1.Click ALT
2.Hover over the menu
3.Try clicking, nothing happens,

For clarity: https://i.imgur.com/Opf3BLf.png

Does this issue occur when all extensions are disabled?: Yes/No
Yes

### PR DESCRIPTION
**Pull request by sbatten**
Refs #52522 

Please test on macOS against regression before approving. (Don't have mine on me right now)

This is to address the issue where the mouse events are trapped in the draggable region of the titlebar even when we draw a non-draggable menu underneath. The hack forces a mouse out and in event to get cursor events back allowing the menubar to function properly. The repro is inconsistent, but I could not repro with this fix so I hope it works.

### CODE REVIEW

**Comment by bpasero** [comment]
I feel like we could look into this for July, I would first like to understand the issue better and reproduce it (it does not reproduce in my VM).

**Comment by bpasero** [comment]
@sbatten are you still planning to make changes here or should I review?

**Comment by sbatten** [comment]
@bpasero we were holding off on this to see if the alt-toggle behavior change would resolve the issue. It doesn't seem to fix it, so I think this fix/a fix are still necessary

**Comment by bpasero** [comment]
@sbatten yeah I am now hitting this also all the time

**Review by bpasero — CHANGES_REQUESTED** [review]
I verified this does not seem to break macOS and it seems to fix Windows. However I would suggest some changes:
* I am not a big fan of `::before` elements for no good reason, rather we could just create a DIV in the title bar part that serves as the app-region: drag element for good
* Instead of toggling a class to show/hide, just use [`Builder.hide()`](https://github.com/Microsoft/vscode/blob/f62aad4aa7531feb1554ee8d98b07230b4f3dd79/src/vs/base/browser/builder.ts#L940) followed by [`Builder.showDelayed()`](https://github.com/Microsoft/vscode/blob/f62aad4aa7531feb1554ee8d98b07230b4f3dd79/src/vs/base/browser/builder.ts#L921)

**Comment by sbatten** [comment]
@bpasero the only way I can repro this now is by taking advantage of bad alt behavior that will be fixed tomorrow. it is probably still reproducible another way but more rare. further, showing and hiding the drag region in testing didn't work when I initially opened the PR which is we went with modifying the height (to trigger a mouse event). However, using builder.hide() is working right now. If we see errors in the future, we can make the change then. For now, I'll keep it simple as is.

**Review by bpasero — APPROVED** [review]

**Pull request merged**
