### PR TITLE
Added remove and disable all breakpoints actions to the command palette

### PR DESCRIPTION
**Pull request by trstringer**
This pull request is the code for issue #7490

### CODE REVIEW

**Comment by isidorn** [comment]
Great job - thanks 🍻 
For consistency I have also added EnableAllBreakpoints as a global workbench action.

**Comment by tstringer** [comment]
@isidorn thanks so much!  Much appreciated :smile: Super quick question (and definitely no urgency :exclamation: to answer this at all), when I was working with the build copy of vs code, and when I ran it with `./scripts/code.bat` all looked great, except I couldn't add an extension and attempting to debug a node.js app indicated that the node subsystem couldn't be found. Was I doing something wrong there?

**Comment by isidorn** [comment]
Node debug adapter is an extension which gets packed in vscode as part of our build process. So when you run vscode out of source it is missing.
In order to overcome that you need to copy the node debug extension from an installed vscode (search for node-debug inside your vscode install location) to the extension folder of vscode-oss-dev\extensions (this should live in your users folder I think). Sorry for not giving the correct win paths I am currently on a mac.

**Comment by tstringer** [comment]
@isidorn no problem, that is a perfect explanation actually!  Thanks so much!!  That'll come in handy for future code and PRs :wink: :+1:

**Pull request merged**
