### PR TITLE
php-language-features: Add html indent rule

### LINKED ISSUE #62077: HTML editing features don't work well in PHP files
- VSCode Version: Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 7

Steps to Reproduce:

1. Create new PHP file
2. Type in div.class, hit tab, hit enter

Current Solution:

Change file type to HTML, and then back to PHP

Proposed solution: 

In a file type where HTML tab-completion works, HTML auto-indenting should also work

Does this issue occur when all extensions are disabled?: Quick Google search did not provide clear instructions on how to perform this in Windows.

### PR DESCRIPTION
**Pull request by Abdillah**
This PR fixes #62077.

## Testing the change
1. Create new file.
2. Change file type to PHP.
3. Type in some nested matching html tags without manually indenting the line:

a. Without the change.
```
<div>
<div>
</div>
</div>
```

b. With the change.
```
<div>
    <div>
    </div>
</div>
```

### CODE REVIEW

**Comment by roblourens** [comment]
I think this issue is different than I thought it was, since it starts working as soon as the html extension is activated. @aeschli so the `onLanguage:html` activationEvent is only triggered when a .html file is opened, even though the html language configuration applies to parts of a php file? Do you think we should add `onLanguage:php` to the html extension?

**Comment by Abdillah** [comment]
Do two extensions allowed to share each other code (like sharing one server)? If we can make sure both HTML and PHP extension server recognize embedded PHP, Javascript, and CSS, that would be ideal IMO.

But I don't think that HTML extension parse PHP language. It should switch to PHP when recognize the syntax, or just give warning.

<sub>I am new here might not get the context right</sub>

**Comment by Abdillah** [comment]
Turns out the PHP already support Javascript and CSS. I am not aware of this just by looking at the code. Is there any HTML ext. activation in PHP language mode somewhere?

**Comment by aeschli** [comment]
PHP defines HTML as an embedded language here: https://github.com/microsoft/vscode/blob/master/extensions/php/package.json#L44. The bug is that VSCode doesn't activate 'html' when it needs it's indent rules. As HTML defines the indent rules in code, activation is necessary.

It's a VSCode issue. I suggest to create a new issue and assign it to  @alexdima.

The PR is not good, PHP must not define any html settings, it will cause conflicts. PHP could define a new language `php-html`, use that for embedding and define rules for that. But I wouldn't do that as it leads to duplication.

**Comment by roblourens** [comment]
Oh, I get it. Thanks @aeschli. Filed https://github.com/microsoft/vscode/issues/98621

**Pull request closed without merging**
