### PR TITLE
Fix code folding keyboard mix up

### PR DESCRIPTION
**Pull request by tht13**
The current implementation for keyboard bindings to code folding works as advertised (in the default keyboard bindings file) for single fold/unfold, but foldAll/unfoldAll is flipped.
This pull request fixes that.

Note: it is possible that the keyboard bindings are back to front i.e open/close square bracket. I have not changed them and do not know which you intended to do what. Feedback in the comments on this would be appreciated.

### CODE REVIEW

**Comment by tht13** [comment]
#3070 contains some of the same changes but not all

**Comment by aeschli** [comment]
@tht13 Thanks for the PR. I fixed the issue.

**Comment by tht13** [comment]
You missed this line https://github.com/Microsoft/vscode/blob/fdd96243b3768909bab79da605c8982145efe2c6/src/vs/editor/contrib/folding/browser/folding.ts#L448 and line #L440 above it where the ID's are switched. I am not sure if they have any afect on the code but thought I would point it out :smile:

**Comment by tht13** [comment]
never mind I see you fixed it in 41640b87 :+1:

**Comment by aeschli** [comment]
Thanks @tht13 for having an eye on it. Right, I first forgot it.

**Pull request closed without merging**
