### PR TITLE
fix #189138

### LINKED ISSUE #189138: Race condition in resolving workspace configuration
Sometimes in multi-folder workspace the `vscode.workspace.workspaceFolders` will return empty array even though there are some folders in the workspace.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 4.19.0-18-amd64

happens with latest insiders too

- OS Version: 
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-18-amd64
      Architecture: x86-64

Steps to Reproduce:

1. clone this extension demonstrating the problem https://github.com/vaclavHala/vscode-workspace-race/tree/master/workspace-race
2. run the extension from vscode
3. add exactly 3 folders to the workspace (the bug manifests for any number of folders as long as you already have a multifolder workspace, 3 are required for the repro just for simplicity)
4. run command `Run workspace race`
5. after some time error will appear meaning the bug has manifested, see debugger log in the development vscode from which you launched the repro or in developer tools directly in the runtime vscode
6. in the log you will see some sequence of expected messages alternating between 2/3 folders in the workspace, the last message will be an empty array

Sometimes the bug manifests after a few seconds, sometimes it may take up to a few minutes. 

Note I'm always waiting for `vscode.workspace.onDidChangeWorkspaceFolders` to fire before touching the workspace again after any update, as demonstrated in the repro

### PR DESCRIPTION
**Pull request by sandy081**
fix #189138

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
You should not check for the capability, the file service will take care of it. Even if a provider does not have atomic read capability, the file service will queue the read with any other write, to ensure some level of atomicity.

**Review by bpasero — CHANGES_REQUESTED** [review]
You should not check for the capability, the file service will take care of it. Even if a provider does not have atomic read capability, the file service will queue the read with any other write, to ensure some level of atomicity.

https://github.com/microsoft/vscode/blob/ad94cf18189746d2e942fda257950901049b3af3/src/vs/platform/files/common/fileService.ts#L483-L485

**Comment by sandy081** [comment]
I have added this check because, I remember I had to do it for atomic write option. Thought it is safe to add. If you think it is not needed, will remove it.

**Comment by bpasero** [comment]
@sandy081 I would remove it

**Comment by sandy081** [comment]
Done

**Review by bpasero — APPROVED** [review]

**Pull request merged**
