### PR TITLE
Update scm colors in ruler to match editor colors

### LINKED ISSUE #86207: SCM decoration colors in the overview ruler don't match minimap and gutter
- VSCode Version: 1.41 Insiders
- OS Version: Windows

The SCM change decorations in the overview ruler are all the same color (blue is the default) while in the editor and minimap add/modify/delete are different colors.

The colors are themeable editorOverviewRuler.addedForeground, etc. but I wonder why we leave them all blue by default?

### PR DESCRIPTION
**Pull request by miguelsolorio**
Let's try this again 😁 From the [previous comment](https://github.com/microsoft/vscode/issues/86207#issuecomment-564760812):

> We discussed this during today's UX sync and the consensus was making it consistent is the right direction however we should dim the colors so that they don't take too much focus away. I'll setup a PR that shows this.

So let me know if this works better, I dimmed the colors down to a 60% opacity and the error colors are significantly brighter in the ruler:

image

Fixes #86207

### CODE REVIEW

**Review by alexdima — APPROVED** [review]
:+1: Let's try selfhosting with it to gather feedback

**Comment by joaomoreno** [comment]
Did no one find this annoying? It was the first thing I noticed when coding for 2 minutes after being back. :laughing:

**Comment by misolori** [comment]
@joaomoreno @alexdima thoughts so far since it's been for a few weeks?

**Comment by alexdima** [comment]
Honestly, I believe it takes me longer now to figure out if I have errors left in a file when looking at the overview ruler. Or it takes me the same time, but I feel my brain working harder to figure it out.

**Comment by joaomoreno** [comment]
I still get pretty annoyed... but I can certainly live with it if no one else complains.

**Comment by alexdima** [comment]
@misolori Could you perhaps make a poll in the ux channel so we find out how others in the team like it?

**Pull request merged**
