### PR TITLE
Implements horizontal guides for bracket guides.

### LINKED ISSUE #133880: Feature Request: Line Scopes - Contextual Pairs only and Horizontal Lines
Continuation from closed issued

@hediet Just looking at the screenshots in that PR I don't personally feel this feature has been implemented and this issue should remain open to track it. At the _very_ least follow up issues should be created so it doesn't get forgotten.

> scope lines for all bracket pairs are shown

This is not how BPC2 worked and I could easily see people thinking this adds too much visual clutter distracting from the point of highlighting the _current_ block/bracket pair you're in. To @CoenraadS's comment "I even got emails from teachers about how much it helped their students". If every block's guide is shown then this can't happen as easily

> there are no horizontal lines

However _more_ importantly, _this_ is the biggest benefit of this feature and the whole reason to use it in my opinion. Just look at the difference it makes in @JustinGrote's comment https://github.com/microsoft/vscode/issues/131001#issuecomment-911940363 or the main screenshots shared by @CoenraadS https://github.com/microsoft/vscode/issues/131001#issuecomment-900328555. I already use `editor.renderIndentGuides` which gives much the same effect as what is shown in the PR so the changes you made would not help me much. However if the horizontal lines are added then I think I (and others) would actually switch away from BPC2

_Originally posted by @jjspace in https://github.com/microsoft/vscode/issues/131001#issuecomment-928042608_

### LINKED ISSUE #134266: Feature Request: Line Scopes - Contextual Pairs only
Continuation from closed issue #131001 @hediet 

> scope lines for all bracket pairs are shown

This is not how BPC2 worked and I could easily see people thinking this adds too much visual clutter distracting from the point of highlighting the _current_ block/bracket pair you're in. To @CoenraadS's comment "I even got emails from teachers about how much it helped their students". If every block's guide is shown then this can't happen as easily

_Originally posted by @jjspace in https://github.com/microsoft/vscode/issues/131001#issuecomment-928042608_

### PR DESCRIPTION
**Pull request by hediet**
I don't like the hack with `nextGuides`, but I thought at least 30 minutes on how to do it better.

It is for this corner-case where two bracket pairs share a common line:

recording

Horizontal guides are only shown for the active bracket pair guide.
Currently, there is not setting.

When there is text before the closing bracket, the horizontal line is drawn at the bottom:
recording

These settings are changed/introduced:
```ts
const defaults: InternalGuidesOptions = {
    bracketPairs: 'none',
    bracketPairsVertical: 'active',
    highlightActiveBracketPair: true,
};

'editor.guides.bracketPairs': {
    type: ['string', 'boolean'],
    enum: [true, false, 'active'],
    default: defaults.bracketPairs,
    description: nls.localize('editor.guides.bracketPairs', "Controls whether bracket pair guides are enabled or not.")
},
'editor.guides.bracketPairsVertical': {
    type: ['string', 'boolean'],
    enum: [true, false, 'active'],
    default: defaults.bracketPairsVertical,
    description: nls.localize('editor.guides.bracketPairsVertical', "Controls whether vertical bracket pair guides are enabled or not.")
},
'editor.guides.highlightActiveBracketPair': {
    type: 'boolean',
    default: defaults.highlightActiveBracketPair,
    description: nls.localize('editor.guides.highlightActiveBracketPair', "Controls whether bracket pair guides are enabled or not.")
},
```

### CODE REVIEW

**Comment by IllusionMH** [comment]
Am I missing something or horizontal lines don't have separate setting?
in BPC2 it was separate setting that I preferred not to enable as it was rarely useful for me.

**Comment by hediet** [comment]
> While there is no setting at this moment, do you have plans to add one before merge to main?

I think these settings are reasonable:
* show bracket guides: `boolean | 'active'` (default false) - enables/disabled all bracket guides. If `active`, only active bracket guides are shown
* show horizontal bracket guides: `boolean | 'active'` (default `active`) - enables/disabled all horizontal bracket guides. If `active`, only active bracket guides are shown.

What do you think?

**Comment by IllusionMH** [comment]
I'm not sure if `boolean | 'third option'` is common pattern intended (not just third value added somewhere later), however if it's intended to have 3 states from the start maybe it make sense to have enum `'off' | 'active' | 'all'`?

Also is it possible to have "show bracket guides: `'active'`" and "show horizontal bracket guides: `true` (or `'all'` in case of enum)"?

**Comment by hediet** [comment]
> I'm not sure if boolean | 'third option' is common pattern intended

I noticed that too, it is `on` | `off` | `active` now. on/off is a common pattern, I'm not sure if we should swap `on` with `all`.

> Also is it possible to have "show bracket guides: 'active'" and "show horizontal bracket guides: true (or 'all' in case of enum)"?

Horizontal bracket pair guides are only shown if the vertical guide is shown.
Thus, if show bracket guides is active, it does not matter if horizontal bracket guides is `true`/`on` or `active`.

**Comment by IllusionMH** [comment]
Agree that `off` vs `all` doesn't look consistent, but then I remembered my initial intent - `none` instead of just `off` (which is definitely pairs with `on`).

So alternative set of values can be `'none' | 'active' | 'all'` which might be slightly more descriptive than `on`/`off`

It is same as ` typescript.inlayHints.parameterNames.enabled` (`'none' | 'literals' | 'all'`) and similar to `editor.find.autoFindInSelection` and `terminal.integrated.confirmOnExit` (if you count `never`/`always` as `none`/`all`)

**Review by alexdima — APPROVED** [review]

**Comment by hediet** [comment]
The test failure does not look like it is caused by this change.
Probably it is already fixed in main.

**Pull request merged**
