### PR TITLE
Implement smooth caret animation with toggleable setting

### PR DESCRIPTION
**Pull request by JeffreyCA**
Addresses #20310

This Pull Request implements the option for having a smooth caret animation while typing, moving the cursor, and selecting text. It is very similar to the animation in Office 2013 and 2016 products. 

This feature request was gaining some traction over the last couple of weeks, and today several people suggested how it could be implemented via a change in the CSS. This implementation is based on @IncognitoJam's suggestion [here](https://github.com/Microsoft/vscode/issues/20310#issuecomment-394726109).

### CODE REVIEW

**Comment by JeffreyCA** [comment]
Any updates? @alexandrudima

**Comment by JeffreyCA** [comment]
@aeschli @alexandrudima any comments on this? It's been 2 months.

**Comment by alexandrudima** [comment]
Works great! Thank you!

**Comment by JeffreyCA** [comment]
Finally! Thanks for merging it in! 😃

**Comment by rainerklier** [comment]
cool!

**Comment by JeffreyCA** [comment]
There's a small issue where after you toggle the setting, when you switch back to an editor tab the changes do not get applied immediately. I had to switch between two different tabs before the settings applied.

**Pull request merged**
