### PR TITLE
Add a propopsed `isReadonly` field to `TextDocument`

### PR DESCRIPTION
**Pull request by mjbvz**
For #91697

This new field tracks if the file is on a readonly file system or not. This can be helpful for text based custom editors

### CODE REVIEW

**Review by mastery-dhananjay-jadhav — APPROVED** [review]

**Comment by jrieken** [comment]
This makes sense given that we have `TextDocument#save` and `TextDocument#isDirty` but I now wonder about binary editors and notebook editors. Should we have similar APIs there or should we have some central API like `vscode.workspace.fs.isReadyOnly(schemeOrUri: string | Uri):boolean`?

**Comment by mjbvz** [comment]
I like the idea of top level function instead. If we add a function in the `fs` namespace though, should it also handle virtual documents? 

We'd also have to keep track of registered file systems on the extension host side if we want the API to be synchronous

**Comment by jrieken** [comment]
> I like the idea of top level function instead. If we add a function in the fs namespace though, should it also handle virtual documents?

Fair question - it's not strictly correct but pragmatic. Tho then there are likely many other schemes that cannot be saved, like `vscode-settings` or `inmemory`. We could say that we don't know anything about them (`undefined`) or say that they cannot be saved because no fs exists for them. 

> We'd also have to keep track of registered file systems on the extension host side if we want the API to be synchronous

Glad you are asking: https://github.com/microsoft/vscode/blob/43184b2beda9edb613caadc2bab29ec50bad863f/src/vs/workbench/api/common/extHostFileSystem.ts#L150

**Comment by mjbvz** [comment]
Closing in favor of #106378

**Pull request closed without merging**
