### PR TITLE
Fix :  Unexpected scopes when grammar is embedded in HTML grammar #112189

### PR DESCRIPTION
**Pull request by rahul3v**
Works fine now for both single and double quotes
Will fix the issue #112189

Also submitted the PR to `textmate/html.tmbundle`

#### Currently :

earlierInlineJs

#### After change :

InlineJs

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks for the contribution. However, the change needs to go to https://github.com/textmate/html.tmbundle.

See the file header:
```
	"information_for_contributors": [
		"This file has been converted from https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist",
		"If you want to provide a fix or improvement, please create a pull request against the original repository.",
		"Once accepted there, we are happy to receive an update request."
	],
```

**Comment by rahul3v** [comment]
well @aeschli , I do have requested **PR** for that at textmate, but that repository didn't finalize the PR yet, and last PR at that repository was closed a very long time ago, like almost 1 year before to be specific.

**Comment by alexr00** [comment]
@rahul3v we can't be experts in every language on a team of our size, which is why we rely on the community for the grammars we use. I am open to the idea of moving away from the grammar we get from https://github.com/textmate/html.tmbundle if there is a better/better supported one.

**Comment by rahul3v** [comment]
well @alexr00 I can understand that, I do have made a PR, lets see, 
otherwise you can have it tasted, as I have directly tested the changes I made on my VSCODE (using current version 1.52.1) and it works fine for me.

**Pull request closed without merging**
