### PR TITLE
"コードの書式設定" is translation error.

### PR DESCRIPTION
**Pull request by sifue**
fix Japanese translation. "コードの書式設定" means "configure formatting".
"選択範囲のフォーマット" is same as translation of Visual Studio.

### CODE REVIEW

**Comment by sifue** [comment]
Sorry. I see "// Do not edit this file. It is machine generated.`".
Which file I can edit to fix?

**Comment by dbaeumer** [comment]
@johnliu2016 another PR to me merged into the translation DB.

**Comment by johnliu2016** [comment]
@lukaschal string locations, the final suggested translation is "選択範囲のフォーマット"
[format.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Fformat%2Fcommon%2Fformat.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";formatAction.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Format Code]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[コードの書式設定]]></Val>
          </Tgt>
        </Str>

[formatActions.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Fformat%2Fcommon%2FformatActions.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";formatAction.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Format Code]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[コードの書式設定]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
Waiting for linguistic approval.

**Comment by lukaschal** [comment]
Please, is it possible to add ENU screenshots of VS Code and VS with mentioned strings ? It seems source is not same on these two strings.

**Comment by johnliu2016** [comment]
@sifue can you provide the context s/s for loc reference

**Comment by lukaschal** [comment]
Source in a VS is a "Format selection".

vs-enu

**Pull request closed without merging**
