### PR TITLE
Add message that indicates you can press ESC to cancel a search, fixes #2494

### LINKED ISSUE #2494: Make it clear how to cancel a running search
Did some research, hope it is not duplicate... Is there functionality (some shortcut maybe?) to break searching? Because when you develop a project, you often need to search stuff across all files. No problem here, until you actually have project with like many many files. For example, if you have project where node_modules are not ignored in search (since even there you sometimes need to search stuff) or you have some internal directory with internal builds, you get like too many results and you are not able to break search to specify search more closely or to just get rid of searching. Usually ends up with crash of vscode... 

Version 0.10.6 (0.10.6)

### PR DESCRIPTION
**Pull request by chrisdias**
Fixes #2494

### CODE REVIEW

**Comment by bpasero** [comment]
@chrisdias I would prefer a solution that does not add a message to the search results. maybe we can add some affordance to the search controls to the top? I suggest we talk in the UX meeting about it.

**Comment by bpasero** [comment]
@chrisdias what about we add a placeholder message into the search box that indicates ESC stops the search? Similar to how we do it for Git:

image

**Comment by bpasero** [comment]
Not a beauty either -_-

image

**Comment by chrisdias** [comment]
i like being consistent, and i do find the Git message useful.  How about: 

`Press Enter to Search, ESC to Cancel`

**Comment by bpasero** [comment]
:+1: pushed, lets see how it goes. Lets abandon this one then.

**Comment by chrisdias** [comment]
@bpasero should i press the "delete branch" button above?

**Comment by bpasero** [comment]
@chrisdias yes please!

**Comment by tmquinn** [comment]
Was this change removed? Long running searches in vscode have been driving me crazy until I discovered this thread... But I am not seeing it in mac version

**Pull request closed without merging**
