### PR TITLE
Update status bar when opening a binary file as text

### LINKED ISSUE #59832: Editor status remains empty when forcing to open a binary file as text
Steps to Reproduce:

1. open a file we think is binary
2. click on the link to force open as text
3. the editor status bar does not update

### PR DESCRIPTION
**Pull request by atitoa93**
Fixes #59832 

WIP: Making sure no extra work happen if the active editor remains the same. More information in the issue comments.

### CODE REVIEW

**Comment by bpasero** [comment]
@atitoa93 yeah we still need that other listener unfortunately otherwise the editor status does not update when you click between 2 opened editors in 2 separate groups.

**Comment by atitoa93** [comment]
Ops, Nice catch 👍

**Comment by bpasero** [comment]
Yeah, this works, though now we update 2 times when opening an editor. I was hoping for a solution where we maybe have a new event that is very specific to this case (opening a binary file) that the editor status could listen to (similar to the encoding change). I realize this is a bit more work, so I can also try to come up with a bit more advice as needed.

**Comment by atitoa93** [comment]
@bpasero Here is the approach I came with.
- Adding a new filed in `FileEditorInput` class called `forceOpenAsTextFromBinary` for example, maintaining this field with the current callback `setForceOpenAsText`.
- Register a new event called `onDidVisibleEditorOpenAsTextFromBinary` for example, and fire this event only if the input has `forceOpenAsTextFromBinary=true`.

What do you think?

**Comment by bpasero** [comment]
@atitoa93 yes something like that, it should be another thing we could add to `activeEditorListeners` in `updateStatusBar` and should probably be declared on `IFileEditorInput` so that the dependency layers are OK.

**Comment by atitoa93** [comment]
@bpasero While developing the approach I mentioned above, came to my mind a more elegant and generic solution. All that I have to do is considering `opening as text from binary` an active editor change (and actually it's almost like changing to a different editor).
The generality in this solution that it will work with any (current and future) dependency, not just the status bar.

**Comment by bpasero** [comment]
@atitoa93 I thought about that too, but that solution you implemented makes it very specific to file editor inputs and we would have to add more custom code for other inputs that behave similar. That is why I would prefer either my initial idea or a more generic approach that works for all editors.

**Comment by atitoa93** [comment]
@bpasero I see what you mean. What about applying the same technique but with the ‘EditorInput’ class instead of ‘FileEditorInput’, naming the new attribute something like ‘newInputInPlace’ for example.

**Comment by bpasero** [comment]
@atitoa93 I find it weird to have a property/method for this "state", when is this state being reset? An event would make much more sense imho.

**Comment by atitoa93** [comment]
@bpasero I did the change to be an event instead of an attribute, but there is something weird happening, It renders only the selection change. I spent a lot of time trying to figure out why but I couldn't.  Any help will be appreciated.

**Comment by bpasero** [comment]
@atitoa93 instead of listening on the level of the editor service, why not just listen at the place where it is needed: https://github.com/Microsoft/vscode/blob/c09511ccc1f67b08ebda9141d49a030cc381865e/src/vs/workbench/browser/parts/editor/editorStatus.ts#L566

There is already an array of active editor listeners that will get cleaned up when the editor changes. To get to the editor, just call `const activeEditor = this.editorService.activeEditor`

**Comment by bpasero** [comment]
@atitoa93 so you say this does not work:

```ts
this.activeEditorListeners.push(activeEditor.onDidOpenInPlace(() => {
	this.updateStatusBar();
}));
```

Can you debug what happens in the `updateState` method if you do this?

**Comment by atitoa93** [comment]
@bpasero Quick update: it works fine if I run it on debugger mode and putting a breakpoint in `updateState` method. But, when I run it on development mode, it only renders the selection change. I'll continue debugging and investigating more the `delayedRender` thing, I believe it's something around there.

**Comment by atitoa93** [comment]
@bpasero So after a debugging session lasts for a couple of hours, I couldn't discover what exactly causes the problem. But, what is happening is the execution of `updateStatusBar` runs before `TextFileEditor::setInput` therefore all the changes trackers methods in `updateStatusBar` find the `model` undefined and don't change the state. Seems that the two methods aren't dependent on each other as when it runs on debugging mode it works fine.
I added `setTimeout(() => this._onDidOpenInPlace.fire(), 100);` To delay updating the status bar a bit and it worked just fine. I would like to understand why that behavior happens and for sure figure out a better way to solve it.

**Comment by bpasero** [comment]
@atitoa93 I like your solution very much, fixed the timeout. Thanks!

**Pull request merged**
