### PR TITLE
Use custom node-gyp for SDL pipeline

### PR DESCRIPTION
**Pull request by rzhao271**

### CODE REVIEW

**Comment by rzhao271** [comment]
The VS Code Scan failed due to Binskim, which is currently being resolved elsewhere.
What is relevant for the scan results is that the dependencies are being installed and compiled properly.

**Comment by rzhao271** [comment]
Building the custom node-gyp is still good. 
CI run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=210534&view=results

We can merge this in and wait for the symbols, or we can wait for the symbols first.

**Comment by deepak1556** [comment]
Lets wait for the pdb files and get a green CI before merging.

**Comment by deepak1556** [comment]
Pdb are now available starting with https://github.com/microsoft/vscode-electron-prebuilt/releases/tag/22.4.5, please rebase on top of `main` once https://github.com/microsoft/vscode/pull/179857 gets merged.

**Comment by rzhao271** [comment]
Symbols are still not being downloaded. Looks like the scan gulp file might be a bit broken. Investigating.

**Comment by rzhao271** [comment]
This took me way too long to figure out.
Upstream PR: https://github.com/joaomoreno/gulp-atom-electron/pull/80

**Comment by deepak1556** [comment]
👏 spectre flag is only raised for Electron related binaries and keytar as expected.

I am good with the changes of this PR but lets wait for @joaomoreno who will be back on Monday and we can get a new version of `gulp-atom-electron` and we can switch to it instead.

**Comment by rzhao271** [comment]
We're now using `@vscode/gulp-electron`!
The SDL scan continues to pass with keytar.node marked as the only native node module without Spectre mitigation added.

SDL scan: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211604&view=results
Raw Binskim log for that scan: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/211604/logs/55

**Review by deepak1556 — APPROVED** [review]

**Pull request merged**
