### PR TITLE
Use serverDataFolderName in check-requirements-linux.sh

### PR DESCRIPTION
**Pull request by aeschli**
Instead of serverApplicationName it should be serverDataFolderName

- serverDataFolderName matches with the data folder that is already there
- serverDataFolderName starts with a . which is IMO what we want.

### CODE REVIEW

**Comment by deepak1556** [comment]
Any reason we want the file to be hidden by default ? I went with `serverApplicationName` to avoid the file from being hidden.

**Review by kalebers — APPROVED** [review]

**Comment by aeschli** [comment]
I think it should be hidden as it's an VS Code internal file. No point for a user to see or manipulate.
I was think that this is the file the extension will create after running the script the first time. Or maybe I misunderstood.

That said, the file won't work to remember that the OS passes the compatibility check. Maybe we need a file that has the error code as content?

**Comment by deepak1556** [comment]
> I think it should be hidden as it's an VS Code internal file. No point for a user to see or manipulate.

No actually it is the opposite, this file is meant for users to force the legacy server. If the detection script is not returning the right result on a setup for whatever reason we need a way for the users to override the result.

> Thinking more about it, the file won't work to remember that the OS passes the compatibility check. Maybe we need a file that has the error code as content?

I was thinking the extensions would setup that file depending on the exit code from this script.

**Comment by deepak1556** [comment]
> If the detection script is not returning the right result on a setup for whatever reason we need a way for the users to override the result.

Thinking again, should this rather be a setting on the client side to force the legacy server and avoid introducing a separate file ? That way it works for both classic and exec server cases, also the extension controls the behavior.

```
remote.useLegacyServer: "true" | "false"
```

**Comment by aeschli** [comment]
@deepak1556 Now that `check-requirements` is no longer part of the server start script, I suggest we remove the 
```
if [ -f "$HOME/@@SERVER_DATA_FOLDER_NAME@@-use-legacy" ]; then
```
check and leave it to the extensions to have a marker file or a setting.

**Review by deepak1556 — APPROVED** [review]
sounds good, thanks!

**Pull request merged**
