### PR TITLE
feat: add rename symbol within <script> tags

### LINKED ISSUE #85411: [html] can't "rename symbol" within <script> tags
**Problem**
In an HTML file with <script> tags, the "rename symbol" command is unavailable.   
VSCode 1.40.1

**Workaround**
"find and replace," but that's always a bit scarier, because it requires vigilance to avoid renaming the wrong thing.  

**Example**  
`<p>catalog</p> ` 
`<script>`  
`let cat = 'hiss';`  
`cat = 'purr';`  
`</script>` 

**Desired behavior:** 
select `cat` --> **rename symbol** to "feline" --> should just replace the variable `cat` with `feline`, leaving "catalog" alone.  

But, this option is unavailable.  

So, the alternative is to find-and-replace all --> "cat" to "feline" --> "felinealog". 
Or need to go one-by-one and check, which can be tricky in a long file.  
Of course, you can be clever searching for " cat " with spaces, but this is just a simple example.  

**Possible solutions**
In an HTML file, the rename could either affect all so-named symbols in all <script> tags in the file, or local to the current <script> tag.  

Thanks for considering this!

### PR DESCRIPTION
**Pull request by chenjigeng**
This PR fixes #85411

### CODE REVIEW

**Comment by aeschli** [comment]
The `ts.LanguageService` offeres proper support for rename:
```
       getRenameInfo(fileName: string, position: number, options?: RenameInfoOptions): RenameInfo;
        findRenameLocations(fileName: string, position: number, findInStrings: boolean, findInComments: boolean, providePrefixAndSuffixTextForRename?: boolean): readonly RenameLocation[] | undefined;
```

Did you try to use that?

**Comment by chenjigeng** [comment]
OK~I try to use ts.LanguageService and it work

**Comment by aeschli** [comment]
Vwry cool. We shoud also add a test. I think https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/test/folding.test.ts#L19 is a good template. Just create a new file rename.test.ts based on that and test the outputs of the rename.

**Comment by chenjigeng** [comment]
OK~let me see how do we do that

**Comment by chenjigeng** [comment]
@aeschli Please take a look at the test case I wrote and the code has been updated a bit

**Comment by chenjigeng** [comment]
I don't know why CI/monaco fail.I tried to run it locally, and it was successful

**Comment by aeschli** [comment]
Change looks good, thanks!
I will merge the PR next week, we're currently in testing week and do not add new features.

**Comment by chenjigeng** [comment]
OK~ thanks for your advice

**Comment by chenjigeng** [comment]
If possible, please merge this PR. I'm afraid there may be conflicts after a long time @aeschli

**Comment by aeschli** [comment]
Thanks for the work, @chenjigeng !

**Pull request merged**
