### PR TITLE
Ux/panels

### PR DESCRIPTION
**Pull request by isidorn**
Adding panels to the activity bar
More details: https://github.com/Microsoft/vscode/issues/11989

### CODE REVIEW

**Comment by isidorn** [comment]
@bpasero @bgashler1  fyi here is the work I still want to tackle - probably on Monday:

1. Registered viewlets should specify id and keybinding of action for toggling them - this should be used for the title in the hover of the activity bar
2. Get rid of [Badge hacks](https://github.com/Microsoft/vscode/blob/ux/panels/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L174) 😱
3. Revisist order of panels in activity bar
4. Get new icons from @bgashler1

**Comment by bpasero** [comment]
@isidorn great, you also seem to need a icon to show the arrow the other direction. once you click on it to show the panel icons, I would expect it to twist around.

**Comment by bpasero** [comment]
Suggestion from @bgashler1 : `transform: rotate(180deg)` animation of .5s or so

**Comment by isidorn** [comment]
Yeah - makes sense, I will play around with the animiation.
@bpasero we need to introduce some nice badge hierarchy - to avoid my hacks, we should discuss on Monday

**Pull request merged**
