### PR TITLE
add option to seedSearchStringFromCursor

### LINKED ISSUE #113830: [Insider/1.53.0] Find editor.action.nextSelectionMatchFindAction seeds from the Nearest Word, not from the last searched word/string
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0:

Steps to Reproduce:
1. Double click on a function name in the code say "function1", press F3.
2. On the found part, move the cursor and click beside any other string say "string1", without selecting it, I would expect VSCode shall still be searching for "function1".
3. Press F3, **VSCode will go to the next occurence of "string1" and not "function1"**
**Example:**
`Void function1( type arg1, type string1 );`

Does this issue occur when all extensions are disabled?: Yes

Not sure why https://github.com/microsoft/vscode/issues/107144 was closed without resolving the issue.

VSCode will force to seed the word near cursor in normal editor, which is not expected. Reference: UltraEdit.

https://user-images.githubusercontent.com/397543/103669402-4ff7d080-4f9e-11eb-9673-537c5c8866e8.mov

### PR DESCRIPTION
**Pull request by swinder0161**
This PR fixes #113830

### CODE REVIEW

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by rheh — APPROVED** [review]

**Comment by swinder0161** [comment]
@bpasero @rebornix is there any problem with this pull request?

**Comment by swinder0161** [comment]
@bpasero @rebornix Please let me know if any further change needed to merge this simple change

**Comment by swinder0161** [comment]
is there any hope of my patch going in?

I am getting little hopeless for a needed small improvement.

**Comment by swinder0161** [comment]
@joaomoreno @rebornix I have rebased the patch to main branch today, Please review and help merge it if ok.
Please feedback if any changes needed.

**Comment by alexdima** [comment]
cc @rebornix

**Comment by swinder0161** [comment]
@rebornix a small commit waiting for merge since 6 months is a shame.
I am sure we do better than this

**Comment by swinder0161** [comment]
hi @msftgits @rebornix  @alexdima  @joaomoreno 
Do I deserve to get a comment from anyone in microsoft or who has merging rights?
Why the patch is not getting merged? atleast give me pointer on what is wrong.

**Comment by rebornix** [comment]
@swinder0161 thanks for your contribution and sorry for the late response. May I ask why `seedSearchStringFromSelection: single` doesn't help in this particular case?

**Comment by swinder0161** [comment]
@rebornix I did not understand your question. Please help to explain.

**Comment by swinder0161** [comment]
@rebornix I have posted a video in the issue https://github.com/microsoft/vscode/issues/113830

Please check

**Comment by rebornix** [comment]
@swinder0161 thanks for the video and contribution, I'm not questioning that if adding this new setting will fix the problem, or if what you are asking makes sense. What I'm saying is this can be probably fixed by passing in right `seedSearchStringFromSelection` value other than introducing a new one.

Firstly to make sure I understand the problem here, quick question: does setting `editor.find.seedSearchStringFromSelection: false` fix the problem for you?

**Comment by swinder0161** [comment]
@rebornix I tried as you suggested, it does not solve the problem.

"editor.find.seedSearchStringFromSelection": false,

**Comment by swinder0161** [comment]
https://user-images.githubusercontent.com/397543/125320137-04f9b400-e359-11eb-87d9-07ba82aecc9f.mov

**Comment by rebornix** [comment]
@swinder0161 just want to double confirm, it seems in the video above, after you change it to `false`, it seems it's the setting is not saved (the file tab still has a dirty indicator). Can you save and then try again?

**Comment by swinder0161** [comment]
my bad while recording video @rebornix , now video with only false set

https://user-images.githubusercontent.com/397543/125323042-0082ca80-e35c-11eb-912f-3e6dea8decf3.mov

**Comment by rebornix** [comment]
@swinder0161 thanks for being patient with me. Now I fully understand the problem, I think it makes sense to honor `editor.find.seedSearchStringFromSelection` in command `editor.action.nextSelectionMatchFindAction` .

**Comment by swinder0161** [comment]
I added option to allow some one who is used to by now to continue using
seed from cursor.

I personally want to use seed from selection but not seed from cursor.

I used ultraedit for past 13 years and I am comfortable that way

Someone who started with code and have become comfortable with seed from
cursor, would feel annoyed if now you change the behaviour in find next.

Both are possible if merge my patch.
That is the reason i have set default for seed from cursor as true to
continue using existing behaviour.

**Comment by swinder0161** [comment]
@rebornix Do you have any further comments?

**Comment by rebornix** [comment]
The existing seed from selection right now supports both seeding from cursor and real selection. I think a better approach to tackle this is turning the value of this setting from Boolean to Enum, e.g.  'selectionOnly|always|never'

**Comment by swinder0161** [comment]
@rebornix I agree to your suggestion, you want me to create a new PR for that?

**Comment by swinder0161** [comment]
@rebornix please check https://github.com/microsoft/vscode/pull/128659 I test is failing though, I am checking that.
Please check the code change, if this is what you were expecting.

**Pull request closed without merging**
