### PR TITLE
GPG support 

### LINKED ISSUE #5065: Add support for signing commits with GPG
VS Code should optionally be able to sign git commits with a given GPG key, as it is a good practice for authorization nowadays.

### PR DESCRIPTION
**Pull request by dmportella**
Hello Added GPG support

Closes #5065 

I have added a new Git Config `git.enableCommitSigning` that will tell vscode `smartCommit` to pass the `-S` flag to git. This way all commits menu items, UI commit features will take advantage of this.

You still need to set the git up to signing which can be found here: https://help.github.com/articles/signing-commits-using-gpg/

What will *not* take advantage is if someone uses the terminal to commit (that they will need pass the `-S` themselves)

I have made all changes that I can tell are needed.

If there is anything missing please let me know and I will make changes.

Please note that I didn't find any git tests in the extension.

### CODE REVIEW

**Comment by dmportella** [comment]
I fixed the conflicts

**Comment by dmportella** [comment]
i have made changes to keep up with master
Its running the build now.
This ticket was on the june milestone but it was removed. still no feedback and i am going to start losing the interest of keeping it synced with master.

I know busy oss projects are huge lots of people talking asking for stuff etc.

So it is cool just let me know if there is anything else I can do to help or just close pull request if you the project is not interested on this change.

kind regards

**Comment by joaomoreno** [comment]
All good @dmportella, I'll take a look at this in due time. 👍  Thanks!

**Comment by joaomoreno** [comment]
Thanks a lot! 🍻

**Comment by dmportella** [comment]
naisu... i can see its been released thank you

**Comment by cdenneen** [comment]
Is this still working?
```
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by Ryonez** [comment]
```
git commit --quiet --allow-empty-message --file - -S
gpg: cannot open tty `no tty': No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```


Yup, this issue is still present.

**Comment by dmportella** [comment]
There would be a few reasons for this to occur typically it its the environment that is not setup correctly, vscode only cares and passed just the required flag to tell git to use signing if git is not setup correct for signing or gpg is not setup correctly you will see errors like this.

git configs need to be setup properly (vscode doesnt do that for you it require you to set it up first).

gpg needs to be setup correctly with the right key to allow git signing to work.

https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work might be good start to just verify that your system is setup correctly if it is I heard sme times where the system is allowing the pass-phase dialog to open so the signing fails. The later is a bit harder to troubleshoot.

If you describe your environment and setup it will be easier to diagnose

**Comment by dmportella** [comment]
I have been using this feature since it was release is 3 difference setups (linux mint, ubuntu 17, 18 and windows) it has worked for me. I have now added support to my local environment to use yubikey to sign my work. Every time  of course i had to setup git to use gpg for signing etc.

Let me know about you system and i can help

**Comment by dmportella** [comment]
just having a look around it might be that your setup is not allowing the system passphase dialog to open. try with another key as a test only that doesnt need any passphase. Just to isolate the issue.

**Comment by chez14** [comment]
I can confirm i get the same problem with @Ryonez too. I used password-protected PGP, and there's no way gpg ask for password in vscode.

I'm able to commit via terminal, and it's annoying that you should commit via terminal, while you stage the changes on the vscode. I hate it so much.

I'm on Ubuntu.
```
> git commit --quiet --allow-empty-message --file - --all -S
gpg: cannot open tty `/dev/tty': No such device or address
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Pull request merged**
