### PR TITLE
Keep Timeline view collapsed across reloads (fix #197334)

### LINKED ISSUE #197334: Timeline view in sidebar opens automatically on launch
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Launch VS Code (with an open folder)
2. Show explorer view if not already visible
3. Timeline view will be visible/expanded
4. Collapse the Timeline view
5. Exit and relaunch VS Code
6. Timeline view is visible/expanded again (expected behavior: it shall remain collapsed)

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #197334.

See the issue for repro steps.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Please add this to the November 2023 milestone.

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for the PR. I looked into the history and found the root cause breaking this. Fixed it in this PR - https://github.com/microsoft/vscode/pull/198961

Hence closing this PR.

**Comment by gjsjohnmurray** [comment]
OK

**Pull request closed without merging**
