### PR TITLE
Fix #14729 - Don't escape newlines in console eval results. They are still escaped elsewhere.

### LINKED ISSUE #14729: Allow multiline eval results in debug console
I'd prefer to see a multiline result instead of escaped newlines
image

### PR DESCRIPTION
**Pull request by roblourens**
One possibility... my comment on the issue

> at first I wanted to skip massageValue for eval results in the console, but it seems like strings in an object preview like ["a\nb"] should stay on one line. We could leave the logic up to the debug adapter like you say, but other debugger authors are assuming that their strings will be escaped for them. Is that too big of a breaking change?

Also, we could do massageValue only when an object is returned, i.e. when the eval result has a variablesReference, so that object previews with newlines will remain escaped, but that seems too inconsistent.

### CODE REVIEW

**Comment by isidorn** [comment]
@roblourens thanks for the pr - looks good overall.
However as @weinand specified in https://github.com/Microsoft/vscode/issues/14729#issuecomment-257517434 can you please only apply your change if the adapter supports that capability.

**Comment by isidorn** [comment]
@roblourens just to check if you are planning to continue on this PR to respect the flag `supportsValueEscaping`?
If not then let me know so I take over.

**Comment by roblourens** [comment]
Oh yeah I'll finish it, sorry

**Comment by isidorn** [comment]
@roblourens no hurries - just was not sure what is the plan here :)

**Comment by roblourens** [comment]
I'm confused about when `KeyValueOutputElement` is used? It seems like it should be in the console in some cases but it seems like everything there is an Expression.

**Comment by isidorn** [comment]
@roblourens `KeyValueOutputElement` is used when output is written to the debug console and that output is actually a complex object. One example is when an extension is being debugged and it does a `console.log(some_object)`
Now that you mention it this is quite some old code and I see an issue there - so I would restructure it a bit.

**Comment by roblourens** [comment]
Ah ok. I need to pass the session in there so it knows whether that prop is set. That looks doable. But I thought it wasn't possible to log an object, since OutputEvent just has `output: string`.

**Comment by isidorn** [comment]
You should be able to get the session by `this.stackFrame.thread.process.session`

**Comment by roblourens** [comment]
Updated the PR, but I actually am not sure about this method now. Why shouldn't the client be responsible for how strings are formatted? You also could want the same string formatted differently, like with escaped newlines in the variables pane but with newlines when hovering. I'm not sure the last comment I made on the issue makes any sense now so I'm wondering if I misunderstood.

**Comment by isidorn** [comment]
@roblourens after discussing this deeper with @weinand we have decided to go with the following approach. VSCode frontend from now on does whitespace massaging and decides in what view it wants to do that. The debug adapter backend can do optional additional massaging of the message but is not required to do that. From your last comment I see that you are also leaning towards that so I believe we are aligned here now.
Namely vscode will show \n \t instead of new line, tab key in the views where there is limited space: variables, watch, complex hover. And it will show the actual new line and tab key in views with lots of space: hover in viewlets, console, hover of a simple variable.

Due to this we have decided to remove the `supportsValueEscaping` capability as we believe this is the desired behavior for all adapters.

**Comment by roblourens** [comment]
This looks perfect. Thanks!

**Pull request closed without merging**
