### PR TITLE
Match run recent command behavior to reverse-i-search

### LINKED ISSUE #154016: Provide run recent command sorting that behaves closer to reverse-i-search
I've had run recent command on ctrl+r for a while. It does provide a nice experience with an overview of what you have been doing, but the more you use it the less relevant the search results become. Since the sorting of the groups is already in reverse search order, the groups could still remain (current session, then previous session, then <shell> history).

Instead of a new command this could reuse the same one with an argument to configure a keybinding to do either and also a persisted sorting toggle at the top of the quick pick.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #154016

Defaults to contiguous and allows toggling temporarily to fuzzy. I think this is how it will end up being used instead of a fixed setting.

Recording 2022-07-06 at 12 55 50

@meganrogge terminal review please
@TylerLeonhardt quick pick review please

### CODE REVIEW

**Review by TylerLeonhardt — DISMISSED** [review]

**Comment by TylerLeonhardt** [comment]
I'm not the biggest fan of the button. It feels clunky... but since you don't want a title bar, and we don't have toggles in the input box... I don't know what else to suggest and we should get feedback.

**Comment by Tyriar** [comment]
Will get some UX feedback before it goes out 👍

**Comment by meganrogge** [comment]
Ran OSS and this is what I saw when I initially ran `Run Recent Command`
Screen Shot 2022-07-06 at 8 51 42 PM

Toggled the button and saw this
Screen Shot 2022-07-06 at 8 51 51 PM

**Comment by meganrogge** [comment]
looks like contiguous is sometimes including fuzzy results or i'm misunderstanding how it should work 

https://user-images.githubusercontent.com/29464607/177666924-4a328803-fb23-4db3-9f59-71be26dfa4c4.mov

**Comment by Tyriar** [comment]
@meganrogge looks like the issue there is it's not checking the case correctly, all 3 should show for both search types for a single character

**Comment by Tyriar** [comment]
I'll check out what's going on with the sorting tomorrow too

**Comment by meganrogge** [comment]
The task output in my first screenshot is puzzling and definitely shouldn't be showing up there. I'll investigate

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/154353 for that

**Comment by Tyriar** [comment]
@meganrogge I think it's ready now since it's now case insensitive

**Review by meganrogge — APPROVED** [review]

**Pull request merged**
