### PR TITLE
Tweak URI search tree iterator to support folder-level query parameters

### LINKED ISSUE #139383: Creating a new folder in a folder provided by a `FileSystemProvider` with a parameter in the URI causes an unnecessary reloading of the root folder
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Clone the sources for the MemFS sample extension.
2. Add this logging line at the beginning of `readDirectory()` on line 45:
```javascript
console.log(`Reading directory ${uri.path}`);
```
3. Add this logging line at the beginning of `createDirectory()` on line 143:
```javascript
console.log(`Creating directory ${uri.path}`);
```
4. Launch the MemFS extension in debug mode.
5. Create the following workspace and open it:
```json
{
  "folders": [
    {
      "name": "MemFS - Sample",
      "uri": "memfs:/"
    }
  ],
  "settings": {}
}
```
6. Create new folder `aaa` in `MemFS - Sample`. You should see the following text logged to your `Debug Console`:
```
Reading directory /
Creating directory /aaa
Reading directory /aaa
```
7. Edit the workpsace so it now looks like this:
```json
{
  "folders": [
    {
      "name": "MemFS - Sample",
      "uri": "memfs:/?notaparam=1"
    }
  ],
  "settings": {}
}
```
8. Create new folder `aaa` in `MemFS - Sample`. You should see the following text logged to your `Debug Console`:
```
Reading directory /
Creating directory /aaa
Reading directory /aaa
Reading directory /
Reading directory /aaa
```

I would expect to see the same behavior in both cases. Discovered during the investigation of https://github.com/intersystems-community/vscode-objectscript/issues/809

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.65GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 8728ef25-68c4-4e80-aafe-921e2dc7ba3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
servermanager|int|2.0.6
vscode-objectscript|int|1.2.3-dev.807
language-server|int|1.2.7
vscode-docker|ms-|1.18.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

### PR DESCRIPTION
**Pull request by JacksonKearl**
This PR fixes https://github.com/microsoft/vscode/issues/139383

@jrieken not sure about this one. On one hand I'd expect `getWorkspaceFolder(URI.parse("memfs:/aaa?query=1")` with a workspace folder `"memfs:/?query=1"` to return that folder, on the other hand this is a pretty core routine and the change could have some unintended side effects. (for instance, should `getWorkspaceFolder(URI.parse("memfs:/aaa?query=1")` return `"memfs:/"` if that's the only folder available?)

### CODE REVIEW

**Comment by bpasero** [comment]
There was related need in file service land and the workaround I had pushed then was to first remove `query` and `fragment` from the URI before passing to the ternary search tree:

https://github.com/microsoft/vscode/blob/2dbc9940401bf829cc12a0351685b6c35d930325/src/vs/platform/files/common/fileService.ts#L223

**Review by jrieken — CHANGES_REQUESTED** [review]
I think this isn't a right approach and I would suggest to do something else. 

First, it is really unclear how the query part should be contributing to the logic of the TST or to workspace containment. There aren't nice rules and ultimately it depends on the scheme and how it interprets them. I see the following options

1. ignore the `query` and `fragment` part when querying/building the TST. Do it either similar to how @bpasero did it or add ctor options to the `UriIterator` to ignore query and fragement (similar to the already existing [option](https://github.com/microsoft/vscode/blob/79e49b266765a6f788f79f15f6d578a43263cd44/src/vs/base/common/map.ts#L202) for path casing). Tho, it does raise the question if ignoring is always correct. That's a question the TST cannot answer, but the workspace service maybe can?
2. Add logic to say `foo:///bar/foo?bbb` is a child of `foo:///bar/?bbb` but _not_ a child of `foo:///bar/?aaa`. I am afraid that adding such logic to the TST won't be easy and you maybe need to combine option 1 with some post-look-up checks like this

**Comment by bpasero** [comment]
I wonder if we miss a method on the file system provider to return the parent `URI` given a `URI`. If you think about "parent folder" it is mainly around how a file system provider would be able to resolve that. You cannot assume that paths are split by `/` or `\` I suppose.

**Comment by jrieken** [comment]
> You cannot assume that paths are split by / or \ I suppose.

Nah, we say that file system providers must adhere use posix paths: https://github.com/microsoft/vscode/blob/b261d64b68c6c6a5d261f7088d59dedba51a04d3/src/vscode-dts/vscode.d.ts#L7711-L7712

**Comment by bpasero** [comment]
I like the idea of adding that option to the TST to ignore query and fragment and would adopt that where I need this today too.

**Comment by JacksonKearl** [comment]
Updated to add a new option to the URI iteratior that ignores queries and fragments

**Review by jrieken — APPROVED** [review]
Initially I was thinking of two knobs, one to ignore query and another to ignore fragment but this is good and we can differentiate once the use-case occurs. Nice changes, thanks for doing this

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
