### PR TITLE
Empty links in recent workspaces list

### LINKED ISSUE #74362: Recent Workspaces list broken with UNC paths and root of a drive
- VSCode Version: compiled local from `master` branch
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder and select the root of a partition drive
2. Open a network folder
3. Close the folder

Does this issue occur when all extensions are disabled?: Yes

image

Got this while I was trying to fix #48403

The was a similar problem in issue #38546

### PR DESCRIPTION
**Pull request by lmcarreiro**
Fix #74362

Before:

image

After:

image

### CODE REVIEW

**Comment by aeschli** [comment]
maybe its best to use path.basename and path.dirname for this

**Comment by isidorn** [comment]
Discussion here https://github.com/microsoft/vscode/issues/74362

**Comment by isidorn** [comment]
Clossing as out of scope.
Thank you again for your PR.

**Comment by aeschli** [comment]
Pushed a fixed.

**Pull request closed without merging**
