### PR TITLE
fix: disable Save, Save as, Save All if editor is readonly

### LINKED ISSUE #202151: Selecting while preview pane is selected as no effect.
Type: <b>Bug</b>

While viewing a .md file with the Preview window selected, the option to save the file is still active, but has not effect.  The actual .md code edit window must be selected for save to have effect.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id 7e33ccd6-f60f-471c-8c28-1c7b021334af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.21.0
mermaid-markdown-syntax-highlighting|bpr|1.6.0
figma-vscode-extension|fig|0.3.1
plantuml|jeb|2.17.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

### PR DESCRIPTION
**Pull request by gioboa**
Fixes #202151 and general readonly editor situations

### File selected

image

### Markdown Preview Selected

image

### CODE REVIEW

**Comment by grgar** [comment]
Disabling Save All seems wrong as that is expected to save editors other than the focused one. I would expect that to save README.md open in the other editor when the preview is focused.

**Comment by gioboa** [comment]
Well, that's a fair consideration. I followed the feedback in the issue but we can easily change the behaviour.

**Review by Sfkdr — APPROVED** [review]

**Comment by gioboa** [comment]
@grgar can I do something to unblock this PR?

**Comment by bpasero** [comment]
This is unlikely to happen given our experiences with running multiple overlapping file watchers on the same folders. Quite the opposite, in the future we might actually register just 1 recursive watcher per folder

**Comment by gioboa** [comment]
Thanks @bpasero for your feedback

**Pull request closed without merging**
