### PR TITLE
Formatting issue in the documentation.

### PR DESCRIPTION
**Pull request by Inffinite**
This PR fixes #

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
https://en.wikipedia.org/wiki/Serial_comma

**Comment by DEntis-T** [comment]
BUG in the DOCUMENTATION.

**Comment by KendallDoesCoding** [comment]
You just added a comma, it's not a BUG... Please update title.

**Comment by KendallDoesCoding** [comment]
> You just added a comma, it's not a BUG... Please update title.

Just a formatting issue.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by Inffinite** [comment]
> You just added a comma, it's not a BUG... Please update title.

Updated.

**Comment by KendallDoesCoding** [comment]
Thanks a lot!

**Review by precha1989 — APPROVED** [review]

**Review by precha1989 — APPROVED** [review]

**Review by precha1989 — APPROVED** [review]

**Pull request closed without merging**
