### PR TITLE
Update contributing guidelines; some issues may be OS specific

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by RMacfarlane** [comment]
Thanks @RDIL, good catch. I think it would be good to have a new bullet point for OS version instead of having it on the same line as VSCode version. Could you please make that change?

**Comment by RDIL** [comment]
Sure!

**Comment by RDIL** [comment]
Feedback addressed.

**Comment by RMacfarlane** [comment]
Thank you!

**Pull request merged**
