### PR TITLE
editor.insertSpaceAfterComment setting

### PR DESCRIPTION
**Pull request by muravjov**
Hi,

Please look at my PR, which introduces setting editor.insertSpaceAfterComment to make VScode to format line comments like

```
		//model.tokenizeIfCheap(startLineNumber);
```
instead of 
```
		// model.tokenizeIfCheap(startLineNumber);
```
(no space just after //)

By default original behaviour is remained, with the space.

### CODE REVIEW

**Comment by muravjov** [comment]
One more need about not inserting space: https://github.com/Microsoft/vscode/issues/9879#issuecomment-249177340

**Comment by muravjov** [comment]
Finally I've been able to get through all checks.

**Comment by muravjov** [comment]
Hi @alexandrudima ,
any chance for taking up my PR?

**Comment by lbmaian** [comment]
Any possibility of getting this merged in? I've been resorting to local patching `_createAddLineCommentsOperations` to get rid of the space after the `//`, which of course results in an "unsupported" warning for VS Code.

**Comment by kirkouimet** [comment]
Let's merge this in!

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
