### PR TITLE
WIP: Early changes for adding cmnds in refWidget

### PR DESCRIPTION
**Pull request by timbanaveen**
WIP: Early code for #21692

### CODE REVIEW

**Comment by timbanaveen** [comment]
Hi @bpasero 

I have added changes related to key events in reference widgets, please review.
also, is there any registry for mouse events ?

Thanks

**Comment by bpasero** [comment]
@timbanaveen I am a bit confused by your solution, we should not introduce new commands, but reuse the ones we already have for list and tree. I am currently not having enough resources to check on this, please maybe hold on work here until I had a chance to come back to you 👍

**Comment by timbanaveen** [comment]
@bpasero, Sure will not do any changes in this PR, till said so :)

**Comment by bpasero** [comment]
Closing for now.

**Pull request closed without merging**
