### PR TITLE
Show readonly filename decoration after revert that also resets mtime (fix #221014)

### LINKED ISSUE #221014: `workbench.action.files.revert` doesn't update readonly indicator when file mtime becomes earlier
Type: <b>Bug</b>

I work with an unusual environment (InterSystems IRIS) in which source code is stored within the environment.

An InterSystems VS Code extension implements a `FileSystemProvider` to support editing of this code.

My company has a specialized source control tool (Deltanji) which uses a "reserve-before-edit" paradigm.

A FileSystemProvider `stat` call on an unreserved file returns the `FilePermission.Readonly` bit in `permissions`. This causes VS Code to treat the file as readonly and display the padlock icon on its tab :+1:

When a file is reserved the next `stat` reports a new `mtime` and clears the bit. This removes the padlock and enables editing :+1:

If the user then cancels the reservation a `workbench.action.files.revert` command is run by the source control extension. This correctly loads the original version of the code, but despite `stat` also setting the readonly bit in `permissions` the padlock icon does not appear and the code remains editable :bug:

I traced the cause to this code:

https://github.com/microsoft/vscode/blob/603b0ee03b82cc77f90f56a5e0ecfbeee3213de1/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L1009-L1014

I will submit a PR.

VS Code version: Code - Insiders 1.92.0-insider (82104a3a6cf8713b81e5bbd97960dbf5c82a816a, 2024-07-05T00:00:00.000Z)
OS version: Windows_NT x64 10.0.22631
Modes:

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #221014.

A "reserve-before-edit" type of SCM tool can result in a FileSystemProvider `stat` result with both an earlier `mtime` and a changed (set) `FilePermission.readonly` bit in `permissions`. VS Code was ignoring this, leaving the reverted document editable.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Yes, I like this. Two feedback:
- I think we can also apply the `locked` property  alongside `readonly` which is for when a file system marked a file as not writeable
- could we have 2 tests to test this if possible per text file model and stored file working copy?

**Comment by gjsjohnmurray** [comment]
I have added handling for `locked` and written tests.

**Comment by gjsjohnmurray** [comment]
Any chance of merging this for July?

**Comment by gjsjohnmurray** [comment]
@bpasero can this be milestoned for August?

**Review by bpasero — APPROVED** [review]
Thanks!

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
