### PR TITLE
Warn user when they open a file within the install folder tree (#138815)

### LINKED ISSUE #138815: Windows: Warn users when opening a folder inside VS Code's installation directory
Issue Type: <b>Bug</b>

I was doing some projects on my and had saved them properly , but now none of them are there and everything has been erased. In VScode it shows it had opened them early but nothing is there now, everything has been erased including alot of hardwork i had put on those projects.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.84GB free)|
|Process Argv|--crash-reporter-id b519655f-0e31-4412-b139-3fb603b4c088|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
java|red|1.1.0
vscode-java-debug|vsc|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #138815

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
/assign @joaomoreno

Set as a draft because I am not convinced it is hooked in at the best place. The warning only appears when a file is opened with the native file dialog. Once it has been opened the warning will not appear during reload.

No warning yet appears when the user opens the installation folder or a subfolder of it. This means they might create new files in there from within VS Code and never be warned of the consequences.

**Comment by bpasero** [comment]
Wouldn't a better approach be to listen to any editor opening (via `IEditorService.onDidChangeActiveEditor` and friends) and comparing the editor resource with the installation directory and bring up a notification then? That would cover really all cases and not just the ones from `vscode.openFiles` IPC messaging.

**Comment by bpasero** [comment]
Actually a more dramatic approach would be to simply mark files from the installation directory as readonly via the file service 🤷

**Comment by gjsjohnmurray** [comment]
@bpasero thanks for the feedback. I'm willing to try either of these ideas. I particularly like the simplicity of the one about treating all files (and folders) in the install tree as readonly in VS Code. Maybe augmented by a notification to explain why it's happening?

@joaomoreno what do you think?

**Comment by gjsjohnmurray** [comment]
> Wouldn't a better approach be to listen to any editor opening (via `IEditorService.onDidChangeActiveEditor` and friends)

This puzzled me initially, until I discovered that the `IEditorService` event is actually named `onDidActiveEditorChange`

**Comment by gjsjohnmurray** [comment]
image

**Review by joaomoreno — COMMENTED** [review]
Even though `permissions: readonly` sounds appealing, the fact that you can still make operations in files doesn't convince me.

I'd say we keep this approach.

**Review by joaomoreno — DISMISSED** [review]

**Review by bpasero — CHANGES_REQUESTED** [review]
Some feedback:
- move into `src/vs/workbench/electron-sandbox/window.ts` as `notifyOnAppRootEditors` on the existing editor change listener
- use `EditorResourceAccessor.getOriginalUri(this.editorService.activeEditor, { supportSideBySide: SideBySideEditor.BOTH })` to handle side by side editors
- maybe scope the `warnOfFileInInstallationFolder` storage key a bit more
- use a modal dialog instead of a notification?

**Comment by gjsjohnmurray** [comment]
@bpasero thanks for your feedback.

> maybe scope the `warnOfFileInInstallationFolder` storage key a bit more

Do you mean give it a better name? What would you suggest?

> use a modal dialog instead of a notification?

I initially considered that but felt it would be too severe, particularly now it appears whenever a qualifying editor gets activated.

@joaomoreno thanks for your contributions. I plan to push changes later today.

**Comment by bpasero** [comment]
@gjsjohnmurray how about a message inside the editor? @hediet might have pointers how that is possible, not sure it can be done today, but it feels like the message belongs into the editor.

**Comment by hediet** [comment]
>  @hediet might have pointers how that is possible, not sure it can be done today, but it feels like the message belongs into the editor.

It can be done today, but there were some discussions around introducing yet another UX concept. I'd do it with notifications for now.

image

**Comment by bpasero** [comment]
Fair, lets keep notifications. modal dialog is quite brutal given this listener is very generic.

**Review by bpasero — DISMISSED** [review]

**Comment by bpasero** [comment]
I think the wording is fine, but @daviddossett @misolori fyi if you have more ideas. I am a bit concerned that we just show an "OK" button with no other action, maybe it should be "Acknowledged" instead.

image

**Comment by gjsjohnmurray** [comment]
Or "Understood" instead of "Acknowledged"?

**Comment by bpasero** [comment]
Yeah.

**Comment by gjsjohnmurray** [comment]
image

**Review by bpasero — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]
Very cool, thanks @gjsjohnmurray!

**Pull request merged**
