### PR TITLE
Add selected text to configuration variable #27466

### PR DESCRIPTION
**Pull request by yitongding**
Add ${selectedText} configuration variable to tasks.json and launch.json, proposed in issue #27466

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for the pr, however this week we are wrapping up our milestone which means I will review this PR start of next week.

@dbaeumer fyi

**Comment by isidorn** [comment]
Looking at the original issue I am not so convinced this is needed in our core. What is the big use case scenario that could profit from this PR?
Since none of the debug users asked for this afaik I am assigning to @dbaeumer so he can decide if this is good to have or not wrt to the tasks.json.

**Comment by dbaeumer** [comment]
@yitongding I agree with @isidorn. Can you please outline in which cases a selected text is needed for tasks ?

**Comment by yitongding** [comment]
@dbaeumer @isidorn Hi, thanks for reviewing!

Here is my use case for selected text:

As a frontend developer, I use a e2e test framework called nightwatch. When running the test, there is an option to choose which test case in the current test file I would like to run. So the command will be like `nightwatch --test header.js --testcase 'should render'`.

Currently, I use `task.json` to run the test with `arg: ['--test', '${file}']`. However, this will run the whole test file, and sometimes it could takes very long time before the test case I really care gets to run. With `arg: ['--test', '${file}', '--testcase', '${selectedText}']`, I'll be able to run the target text case only by selecting the test case title.

Hopefully, I made my self clear 😄

**Comment by dbaeumer** [comment]
@yitongding thanks for the example. This makes sense to me.

**Comment by roman-petrov** [comment]
@dbaeumer, actually, I see almost the the same case with running Karma tests in our project, that's why I voted for this issue.

**Comment by dbaeumer** [comment]
@isidorn any comments on the code. It looks good to me.

**Comment by isidorn** [comment]
@dbaeumer I will review a bit lataer today and if it looks good I will merge it in. Thanks

**Comment by isidorn** [comment]
@yitongding I just reviewed the code and it looks good to me. Thanks a lot
@yitongding if you would also like to provide a pr to our vscode-docs that would also be really appreciated. If not @dbaeumer and me will cover this in our release notes and documentation in endgame week.

**Comment by yitongding** [comment]
@isidorn Thanks for reviewing!
I've made a pr to Microsoft/vscode-docs#1317

**Comment by gregvanl** [comment]
@yitongding @isidorn I'm having trouble getting this to work. Here's my tasks.json:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo",
            "args": [
                "${selectedText}"
            ]
        }
    ]
}
```
I just see "Executing task: echo ${selectedText}". If I use ${file} or ${lineNumber} it works fine.

**Comment by isidorn** [comment]
@gregvanl we have frozen insiders during the holidays. So once we update the insiders start of january this shoul work just fine :)

**Comment by nileshkhaire** [comment]
It seems that ${selectedText}  variable is not added yet. Anyone know in which release this will be added ? I need this for one of the task :(

**Comment by nileshkhaire** [comment]
Sorry this feature is already added in latest release but documentation is missing .

**Comment by eightbit** [comment]
Request:
`${selectedText}` gets truncated to the first line, please consider including a multi-line selection when populating the variable.
Example:
```
"JS Block Quote": {
	"prefix": "c2",
	"body": [
		"/* ${selectedText} */",
	],
	"description": "JS Block Quote"
}
```
Thanks.

**Pull request merged**
