### PR TITLE
Fix/debug auto decode link

### LINKED ISSUE #112032: Debug Console Linker automatically decodes link
Issue Type: <b>Bug</b>

When debugging code and a link has a URI encode clinking the link in the debug console will auto decode the URL. This causes issues as some APIs expect the paramaters to be URI encoded. When just logging links to the terminal it doesn't do that.

Try the following code:
```
const url = "https://www.test.com/?params=CountryCode%3DUSA%26Name%3Dlramos15";
console.log(url);
```
Steps to reproduce
1. Set a breakpoint on `console.log(url);`
2. Start debugging
3. Type url into the debug console
4. Ctrl+click and navigate to the URL. It will automatically decode to `https://www.test.com/?params=CountryCode=USA&Name=lramos15`, with no way to disable this. Runnig the code normally and following the url in the terminal doesn't do this.

VS Code version: Code - Insiders 1.52.0-insider (5e350b1b79675cecdff224eb00f7bf62ae8789fc, 2020-12-04T10:15:27.849Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.42GB free)|
|Process Argv|C:\\Users\\ramosl\\Desktop\\Fall 2020 - Hw 8 --crash-reporter-id 6835f0a3-d9c6-4053-812a-2c4e35492724|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

### PR DESCRIPTION
**Pull request by chenjigeng**
This PR fixes #112032

### CODE REVIEW

**Comment by isidorn** [comment]
@lramos15 for some reason I can not add you as a reviewier.... Maybe you can add yourself

@chenjigeng thanks a lot for the PR. I plan to review it this milestone, I also want to give a chance to @lramos15 to review if he wants

**Comment by lramos15** [comment]
@isidorn It won't let me be a reviewer because I'm not currently employed at Microsoft. I come back January 11th though. 
@chenjigeng Why are we still decoding within the opener service? Doesn't that mean the URL the user sees in the popup will be different than the URL the user actually gets sent to.

**Comment by chenjigeng** [comment]
@lramos15 As I mentioned in the issue, this PR is mainly to solve problems 1 and 3.
The change to question 2 is too broad. OpenerService is currently being relied upon in all sorts of places and is based on the current logic. I am afraid that if I change the logic directly this time, it will have too much impact.

**Comment by chenjigeng** [comment]
I was going to add a needDecode option inside the URI to determine whether to decode. Because in OpenerService internal, if the incoming object is a URI object, it will not try to parse it.And it looks very good. 
However, OpenerService encodes the URI object when it opens the link, this can be a problem and I don't know why here is going to encode. Can you help me take a look at this place @isidorn @jrieken 
image

https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/services/openerService.ts#L203

**Comment by isidorn** [comment]
Moving to On Deck and @lramos15 can review once he finds time and is back at Microsoft. There is no rush here imho.

**Comment by lramos15** [comment]
@isidorn The changes made look good to me and also follow what the terminal does for me. My main worry comes down to @chenjigeng's comment about the opener service still showing a decoded link in the modal that pops up. This means that the text the user sees in the modal might not match the text the user sees in their URL bar which creates a bad UX experience. I also understand their concern that changing the opener service affects a lot of places in our code. If you think the disconnect is ok then this is ok to merge as it not only fixes links but files too.

**Comment by isidorn** [comment]
Let's go with the current approach as it is less risky so we do not have to change the opener service. Thus merging.
Thanks!

**Pull request merged**
