### PR TITLE
Option to hide the status bar implemented

### LINKED ISSUE #6356: Option to hide the status bar
For those wishing to further minimize distractions and/or maximize screen space, an option to hide the status bar (the blue bar at the bottom) might be nice.

### PR DESCRIPTION
**Pull request by kisstkondoros**
This fixes #6356

### CODE REVIEW

**Comment by bpasero** [comment]
@kisstkondoros thanks 👍

**Comment by bpasero** [comment]
@kisstkondoros can you merge this PR with master and resolve the conflicts? also I noticed a bug: you do not seem to read the status bar visibility setting on startup here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/workbench.ts#L412

**Comment by kisstkondoros** [comment]
@bpasero Will do it, thanks for spotting the issue :+1:

**Comment by kisstkondoros** [comment]
@bpasero I've rebased the branch :+1:

**Pull request merged**
