### PR TITLE
Implement split action with dropdown in notifications

### LINKED ISSUE #110721: Align the `install` buttons in the recommendations dialog with the extensions viewlet
The recommendations dialog currently shows 3 buttons 
image

Suggest to change the Install button to be a drop down with the option to not sync as in the Extensions Viewlet 
image

### PR DESCRIPTION
**Pull request by sandy081**
This PR fixes #110721

Implement split action with dropdown in notifications

- Added support for menu actions in `notify` & `prompt` methods of `INotificationService`
  - You can `ActionWithMenuAction` If using `notify`
  - You can pass menu actions through `menu` property if using `prompt`
  - These are supported only for primary actions

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Works great overall, I have only looked into the changes for notifications and have some feedback:
* I think we need to introduce a new base interface for `menu` because `IPromptChoice` has a property `isSecondary` that does not make a lot of sense when the choice is presented as part of the dropdown
* when I tested it, the `keepOpen` option was not respected, i.e. my notification remained open when I selected a choice from the menu, even when I had `keepOpen: false`

I also noticed that it is not possible to leverage this new UI piece from the more generic `notify` method, but I think that is OK for now.

Finally there is a bit of a UX bug here: the menu seems to open as context menu where my mouse is but it should really open anchored to the button, otherwise it looks like this:

image

**Comment by sandy081** [comment]
> I think we need to introduce a new base interface for menu because IPromptChoice has a property isSecondary that does not make a lot of sense when the choice is presented as part of the dropdown

✅ - Introduced `IBasePromptChoice`

> when I tested it, the keepOpen option was not respected, i.e. my notification remained open when I selected a choice from the menu, even when I had keepOpen: false

✅ - Good catch. I was not passing options with action runner to dropdown menu.

> I also noticed that it is not possible to leverage this new UI piece from the more generic notify method, but I think that is OK for now.

It is possible. You have to pass `ActionWithMenuAction` action, just like `SubmenuAction` for sub menus - Updated the doc of `INotificationActions`

> Finally there is a bit of a UX bug here: the menu seems to open as context menu where my mouse is but it should really open anchored to the button, otherwise it looks like this:

For me, it shows the menu underneath the action. Seems you are using custom dropdown, could be an issue with underlying context menu service. I have no clue how it works. Any pointers?

**Comment by bpasero** [comment]
@sandy081 try web

**Comment by sandy081** [comment]
@bpasero Fixed the menu position.

**Comment by bpasero** [comment]
🚢  it

**Comment by bpasero** [comment]
@sandy081 there is still that bug that `keepOpen` flag is ignored...

**Comment by sandy081** [comment]
Yah sorry, I broke (did not pass action runner) it while fixing the menu position in web. Fixed it. Thanks.

**Pull request merged**
