### PR TITLE
Add follow on Twitter badge

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Added `follow on twitter` badge

This is how it looks like:-
[Twitter](https://twitter.com/intent/follow?screen_name=code)

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@jamesgeorge007  I've already worked on #61886

**Comment by jamesgeorge007** [comment]
@weinand @keiferrm Does this make sense to you?

**Review by open-source-explorer — DISMISSED** [review]

**Comment by jamesgeorge007** [comment]
@jrieken Thoughts?

**Comment by jamesgeorge007** [comment]
@weinand @kieferrm @jrieken Thoughts?

**Comment by Tyriar** [comment]
This is stale, I also don't think we should have minimal badges on the repo and it's also changed name since

**Pull request closed without merging**
