### PR TITLE
Add multi-select renames to terminalAction

### PR DESCRIPTION
**Pull request by tisilent**
part of #193380

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
The main part of this I wanted to accomplish was actually to pass the context instances over correctly. See how the context menu passes instances through to the extension host using `TerminalContextActionRunner` here:

https://github.com/microsoft/vscode/blob/b93639dfa3d6e86233fa9246ee5e45abf64b7505/src/vs/workbench/contrib/terminal/browser/terminalContextMenu.ts#L32-L65

This is a more solid way that the hack we do currently where we query for selected instances using `terminalGroupService.lastAccessedMenu`:

https://github.com/microsoft/vscode/blob/b93639dfa3d6e86233fa9246ee5e45abf64b7505/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1611-L1642

**Review by Tyriar — APPROVED** [review]
This does work and is am improvement though so lgtm, we can tackle the instance context in another one.

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by tisilent** [comment]
I also feel that there is another purpose, so I didn't touch the color. Minor episode, this action takes 200 milliseconds when multiple instances are rename.

**Comment by tisilent** [comment]
'TerminalGroupService' lastAccessedMenu may cause issues with some shortcut actions.
#196578

**Comment by Tyriar** [comment]
The refactor ended up being bigger than expected, but this is what I had in mind: https://github.com/microsoft/vscode/pull/196853

**Pull request merged**
