### PR TITLE
fix #65585

### LINKED ISSUE #65585: Invisible element is focused when SCM split view is collapsed
Repro:

1. Open SCM viewlet
2. Collapse git pane
3. Press shift+tab a few times and tab a few times, notice that there's an element that can be focused in between the 2 headers. `document.activeElement` points at this, which appears to be a tree inside the pane:

screen shot 2018-12-21 at 10 19 20 pm

### PR DESCRIPTION
**Pull request by bpasero**
This would not be needed if the SCM viewlet was using our base infrastructure for views. We should really get that going next milestone 👍

### CODE REVIEW

**Comment by joaomoreno** [comment]
Unfortunately this breaks the collapse animation... I'll take it as a starting point, maybe we leave it for next month. Thanks man!

> This would not be needed if the SCM viewlet was using our base infrastructure for views.

I don't think that's true. I can repro in Debug, Extensions viewlet, etc.

**Comment by bpasero** [comment]
@joaomoreno if that was true, it would also be broken for "Open Editors" view? I still see the animation with the change on macOS at least:

grid-tw

**Comment by joaomoreno** [comment]
@bpasero Even in the GIF the animation is broken: pay close attention to the body contents when you collapse the panel, it disappears as soon as the animation starts.

**Comment by joaomoreno** [comment]
Will close it in favor of https://github.com/Microsoft/vscode/issues/65585#issuecomment-459248678

**Pull request closed without merging**
