### PR TITLE
Adds sort lines (ascending and descending) command

### PR DESCRIPTION
**Pull request by martellaj**
- Took a crack at issue #536, given it had the `help wanted` label
- Adds keyboard shortcuts to sort lines (chose arbitrary shortcuts, probably want to change those)
- Didn't create formal test cases (won't have the time for a while), but did verify changes using strings from [random.org](https://www.random.org/strings/?num=10&len=10&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new)

### CODE REVIEW

**Comment by csholmq** [comment]
Nice job. Question is; should this be merged or handled by an extension? E.g. [Sort lines](https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines)

**Comment by martellaj** [comment]
I know Sublime Text has this functionality built in and that it's often a requested feature for IDEs. I don't see a downside of including it without having to download a third party extension, given that it's an operation on code lines with essentially no logic (I'm on the OneDrive team and would love to alphabetize our dependencies. :yum:).

Really I was just trying to contribute where I could to a product I love using. Would love to see it merged!

**Comment by Tyriar** [comment]
Commenting so I get a participating notification. I want to deprecate my extension if it gets in :)

**Comment by alexandrudima** [comment]
@martellaj

Thank you! :+1: 

I took the liberty to tweak the keybindings and add some tests while merging.

**Comment by martellaj** [comment]
Sweet! Happy to contribute. ☺️ Keep rocking, guys!

**Comment by rafareino** [comment]
It took me a few minutes to me to understand how this works.

To me at least, do not seems particularly obvious that I **must** select the lines before sorting out, what if it acts like Copy/Paste with no selection (defaults to whole line) the command should either alert if there isn't any selection to act upon, or act over the whole file instead.

**Comment by faintsignal** [comment]
Can someone please provide a link to the documentation for this feature?  I can't find this feature in any of the menus.

**Comment by martellaj** [comment]
Interesting. Seems it's no longer showing up in the command palette, but does show up as keyboard shortcuts.

**Comment by faintsignal** [comment]
@martellaj Ahh, thank you. I do see it in the command palette if I type "sort". I was expecting to access the feature from one of the Edit/Selection/context menus.

**Comment by martellaj** [comment]
Yep, I'm seeing it in the command palette now, too. Pretty sure it was absent on the Insider build I was on 2 days ago though. Regardless, all good now. 👍

**Comment by OlafvdSpek** [comment]
How does one access this feature?

Typing `sort` doesn't return anything.

**Comment by martellaj** [comment]
@OlafvdSpek You're sure you're in the command palette, right? I still see it FWIW.

image

**Comment by OlafvdSpek** [comment]
No, I was trying the Ctrl-P one.. sorry.

**Pull request merged**
