### PR TITLE
updated the file for "Enter" issue.

### PR DESCRIPTION
**Pull request by mhumayunsaeed**
Following was the issue which is associated with this pull request.
https://github.com/microsoft/vscode/issues/178879

The suggested fix is to add the line `"editor.acceptSuggestionOnEnter": "on"` to your settings.json file in Visual Studio Code and restart the program. This should help resolve the issue.

To test if the fix for the Enter button issue in Visual Studio Code has worked, you can try the following steps:

- Open Visual Studio Code and navigate to a file where you were previously experiencing the issue with the Enter button.

- Try pressing the Enter button to see if it is now functioning as expected.

- If the Enter button is still not working, you can try using the “Ctrl + Enter” workaround that was mentioned earlier to see if that resolves the issue.

- If the Enter button is still not working after trying these steps, please let me know and we can explore other potential solutions.

### CODE REVIEW

**Comment by julekgwa** [comment]
Doesn't work for me 

https://user-images.githubusercontent.com/5516477/229348150-80a529f5-fe2d-443e-90a1-e7ce5118e380.mov

**Comment by Humayun-glitch** [comment]
Did you try CTRL+Enter?

**Comment by Humayun-glitch** [comment]
Or try adding this. `"editor.acceptSuggestionOnEnter": "smart"`

**Comment by Humayun-glitch** [comment]
Disable the extension, [diegolincoln.vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components)
This fix also seems to work.

**Comment by roblourens** [comment]
That setting is a personal preference- you can add it to your own workspace or your user settings, but we won't change it in the workspace settings for the vscode repo, that only would impact vscode developers

**Comment by Humayun-glitch** [comment]
Sure, I hope I contributed to the community.

**Pull request closed without merging**
