### PR TITLE
:up: jschardet@2.2.1 (#33720)

### LINKED ISSUE #33720: Wrong guess encoding as Windows 1252
Upstream issue: https://github.com/aadsm/jschardet/issues/48

- VSCode Version: Version 1.15.1
- OS Version: Windows 10.0.15063

Steps to Reproduce:

1. The `settings.json` of my vscode 

```
    "files.encoding": "utf8",
    "files.autoGuessEncoding": true,
```

2. Ceate two txt files, make sure the files are saved as `utf-8`

test1.txt
```
Created on: 2017年9月2日
测
```

test2.txt
```
Created on: 2017年9月2日
测试
```

3. Reopen the files,`test1.txt` guessed encoding is `Windows 1252` and `test2.txt` guessed encoding is `utf-8`.

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #33720

### CODE REVIEW

**Comment by bpasero** [comment]
@gyzerok I believe this would allow us to remove this `any` cast:

https://github.com/microsoft/vscode/blob/a50bf5d7dfd143fc1f02df65452b4587ebe45bd5/src/vs/workbench/services/textfile/common/encoding.ts#L241

However, the type is not clear, I think it must be `string`, why not `Uint8Array`?

**Comment by gyzerok** [comment]
@bpasero yeah you are right.

I was planning to update the version once we are finished with the PR I have currently open, but you beat me to it :)

> However, the type is not clear, I think it must be `string`, why not `Uint8Array`?

It has to be `string` indeed. With `Uint8Array` it won't work. I misunderstood the source code and it is actually mistake on my side. It is fixed in the currently open PR as

```ts
const binaryString = encodeLatin1(limitedBuffer.buffer);
```

**Comment by bpasero** [comment]
Oh yeah, forgot about that. This PR will not be merged until Friday or Monday next week since `master` is currently blocked for feature work.

**Comment by bpasero** [comment]
@gyzerok fyi `master` is open for `1.48 July` work, so feel free to remove that `any` cast in a new PR.

**Pull request merged**
