### PR TITLE
update swc

### PR DESCRIPTION
**Pull request by jrieken**

### CODE REVIEW

**Review by lszomoru — DISMISSED** [review]

**Comment by starball5** [comment]
Linux and Windows unit tests seem to be choking on expected vs. actual for JSON strings encoding ANSI escape sequences- particularly the part that encodes the escape character. Actual: `\\x1b`, expected: `\u001b`.

Also https://dev.azure.com/vscode/VSCode/_build/results?buildId=113364&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=dc9350bd-9972-5ec1-4dbd-7003b29c63a7&l=11516 and https://dev.azure.com/vscode/VSCode/_build/results?buildId=113364&view=logs&j=2d439be5-f03d-54e6-66eb-93d556f69561&t=a48edd54-4c60-5454-969f-898c5c0e930a&l=12528

**Comment by starball5** [comment]
swc changelog is [here](https://github.com/swc-project/swc/blob/main/CHANGELOG.md). https://github.com/swc-project/swc/pull/8490 in 1.3.103 catches by eye, but I have no idea if it's actually related or not. I'm curious what you see if you try to bisect the patch version update range and see which patch causes the failure.

**Comment by starball5** [comment]
So the update just isn't going to happen?

**Comment by jrieken** [comment]
Yeah, at least not now.

**Pull request closed without merging**
