### PR TITLE
Use grid descriptors for workbench grid layout

### PR DESCRIPTION
**Pull request by joaomoreno**
- [x] Create the grid based on descriptors
- [x] Use `moveView` instead of `addView` and `removeView`.
- [x] Clean up that huge overloaded `layout()` call. Layout should always be as cheap as possible. Currently it is doing much more, like adding views when they aren't there or updating their visibility.
- [x] Make sure all view visibilities work
- [x] Make sure all state is saved and restored

### CODE REVIEW

**Comment by joaomoreno** [comment]
The `layout` call was way too overloaded with visibility state management. Lots of code pieces are calling `layout()` just because of that: eventually the grid state converged to what it should be. But there are many other code pieces which eventually call `layout()`, such as `setEditorHidden()`, so `skipLayout` was introduced.

Whenever a view toggles its visibility, we should **never** need to call `layout` at all. This is just extra unnecessary work. All these `skipLayout` flags should be deleted, simply because `layout` should never be called in these methods.

**Comment by sbatten** [comment]
@joaomoreno totally agree on the layout calls, I had just been thinking on that this morning

**Comment by sbatten** [comment]
@joaomoreno I pushed a commit. It works well. I think we can merge without regression but the grid still has some issues with cachedViewSizes.

**Comment by joaomoreno** [comment]
Nice :ok_hand: 

Feel free to merge

**Pull request merged**
