### PR TITLE
Add branch name validation and whitespace config

### LINKED ISSUE #50241: [feature] git extension - add branch name validation
Description:
* Add validation to the git create branch, ensuring that project branch conventions are kept.
* Make the `whitespace` char `-` configurable *(we default space etc. to underscore - meaning we cannot just past in issue title and be done)*

Example implementation:
vscode-create_branch_validation

I can create an initial pr. with the implementation for further discussion, if this is something the vscode team would consider.

eg. if the change should enable extensions to lint/validate the branch name or be a configuration etc.

Kind regards Morten

### PR DESCRIPTION
**Pull request by raix**
This pull request adds following options to the `git` extension.
* Adds `git.createBranchNameConvention.regexp`
* Adds `git.createBranchWhitespaceChar`

Preview:
vscode-create_branch_validation

This is an initial pr. with the implementation for further discussion, if this is something the vscode team would consider.

eg. if the change should enable extensions to lint/validate the branch name or be a configuration etc.

Fixes #50241

Preview of alternative: Adding an extension api, searching tickets not fixed - also write the branch name after whitespaces etc. have been replaced:
vscode-create_branch_validation_via_extension

### CODE REVIEW

**Review by sommai232323 — APPROVED** [review]

**Comment by raix** [comment]
@joaomoreno is it possible to run this build again? I think to remember it failed installing npm modules.

**Comment by joaomoreno** [comment]
@raix Let's merge master into it first, then a new build will be triggered.

**Comment by joaomoreno** [comment]
Thanks! :beers: 

Did a few changes to the settings names.

**Comment by raix** [comment]
Thanks @joaomoreno sounds good 👍

**Pull request merged**
