### PR TITLE
Update to Electron 0.37.x

### PR DESCRIPTION
**Pull request by bpasero**
Fixes the following issues:
- Linux: Button order in dialogs: https://github.com/Microsoft/vscode/issues/1297
- Mac: Storage flush on update: https://github.com/Microsoft/vscode/issues/172
- Show the application window as soon as possible: https://github.com/Microsoft/vscode/issues/163

Might have impact on following issues on blurriness:
- https://github.com/Microsoft/vscode/issues/1896
- https://github.com/Microsoft/vscode/issues/1334
- https://github.com/Microsoft/vscode/issues/254
- https://github.com/Microsoft/vscode/issues/959

**Updates:**
- Chrome from 45 to 49
- node.js from 4.1.1 to 5.10.0
- libuv from 1.7.4 to 1.8.0

### CODE REVIEW

**Comment by 1dot75cm** [comment]
Please fix this issue. I try to stripping `electron` from `vscode` rpm package. It return following error.

RPM spec: http://copr-dist-git.fedorainfracloud.org/cgit/mosquito/test/vscode.git/tree/vscode.spec?id=17ce85d650470e023ff37e7412d62c5aa222b304
RPM:  https://copr.fedorainfracloud.org/coprs/mosquito/test/build/163492/

```
Version 0.10.11
Commit 8b7f21e10bf69745bde4330a337e9501972e983b
Shell 0.36.8
Renderer 47.0.2526.110
Node 5.1.1
$ dnf install https://copr-be.cloud.fedoraproject.org/results/mosquito/test/fedora-23-x86_64/00163492-vscode/vscode-0.10.11-1.fc23.x86_64.rpm
$ export ELECTRON_ENABLE_LOGGING=1
$ export ELECTRON_ENABLE_STACK_DUMPING=1
$ electron /usr/lib64/vscode
[6978:0227/175217:INFO:CONSOLE(133360)] "IRequestService.makeRequest: Url is required.: Error: IRequestService.makeRequest: Url is required.
    at RequestService.makeRequest (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:137627:23)
    at GalleryService.queryCache (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:121102:40)
    at GalleryService.query (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:121057:30)
    at ExtensionTipsService._getAvailableExtensions (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:92773:41)
    at ExtensionTipsService._init (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:92735:46)
    at new ExtensionTipsService (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:92705:18)
    at create (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:5252:14)
    at file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:61565:45
    at AccessLock.runUnlocked (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:61393:24)
    at ServicesMap.createInstance (file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js:61564:31)", source: file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js (133360)
......
[6978:0227/175219:INFO:CONSOLE(109401)] "%c[Plugin Host]", source: file:////usr/lib64/vscode/out/vs/workbench/workbench.main.js (109401)
```

**Comment by bpasero** [comment]
@1dot75cm we are currently blocked by a native crash in V8: https://github.com/atom/electron/issues/4299

**Comment by felixfbecker** [comment]
Node 5, yes please...

**Comment by 1dot75cm** [comment]
Commit https://github.com/Microsoft/vscode/commit/0787cde294d5eadf12dfd1ad38f2996241021f0c with `electron 0.36.11` is work fine on Fedora 23. 
RPMS: https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/173746/

The `electron 0.37.4` with https://github.com/Microsoft/vscode/commit/0787cde294d5eadf12dfd1ad38f2996241021f0c still crashes. @bpasero 
RPMS without node-weak by [disable-weak.patch](http://copr-dist-git.fedorainfracloud.org/cgit/mosquito/test/vscode.git/tree/disable-weak.patch): https://copr.fedorainfracloud.org/coprs/mosquito/test/build/173751/

**Comment by bpasero** [comment]
We do not recommend to build VS Code with newer Electron version until VS Code itself moved forward!

**Pull request merged**
