### PR TITLE
Allow markdown preview to scroll past content

### LINKED ISSUE #15795: Allow markdown preview to scroll past content
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a markdown document
2. Open the markdown preview
3. Try and scroll past the content in the markdown preview.

image

The changes required to implement this are probably a small subset of what is required to implement #5047, but I'm hoping this can be done easily and released soon, whereas #5047 may require significantly more work. If #5047 is implemented in the meantime then I expect it can supersede this issue.

### PR DESCRIPTION
**Pull request by mjbvz**
Issue #15795

Allows the markdown preview to scroll past its contents, like we do with the markdown editor.

nov-22-2016 13-00-26

Closes #15795

### CODE REVIEW

**Comment by jrieken** [comment]
Unsure if this should also honour the `"editor.scrollBeyondLastLine": true` setting?

**Comment by adamralph** [comment]
Awesome! Which version will this be released in?

**Comment by mjbvz** [comment]
@adam It's already in today's insiders build and should land in the official 1.8 release

**Comment by adamralph** [comment]
@mjbvz great, thank you!

BTW, it's @adamralph, `@adam` is someone else. 😉

**Pull request merged**
