### PR TITLE
improve titlebarpart layout perf

### LINKED ISSUE #60326: layout trashing in titlebarPart
* close all editors et al
* start performance recording
* reload workbench
* 🐌 notice how the titlebar part trashes the layout

screenshot 2018-10-09 at 17 11 42

### PR DESCRIPTION
**Pull request by sbatten**
fixes #60326

### CODE REVIEW

**Review by bpasero — DISMISSED** [review]
While this fixes the perf issue, I now see the title content jumping from right to center shortly after the window has opened. Why do we need the calculated styles in the first place, can we not introduce CSS rules that take care and avoid this altogether?

**Comment by sbatten** [comment]
@bpasero sorry about the delay here, fyi I just force pushed a totally different commit into this branch so the initial changes aren't here anymore. please see new code.

**Comment by bpasero** [comment]
@sbatten there is still a noticable flicker of the title right after startup:

before

Another thing I noticed is that the fonts do not seem to align (title to menu items):

image

The title seems slights higher.

Would it not be possible to do the layout via CSS rules only? What is the behaviour of the title that forces it to require a custom JS layout after a timeout?

**Comment by sbatten** [comment]
@bpasero the title is centered differently in 2 cases.
* If room allows, center the title with respect to the entire window
* Else center the title between the menu and window controls.

AFAIK this is not possible with just CSS and flex box.

**Comment by bpasero** [comment]
@sbatten maybe check what watermark does and do the same: [here](max-height-478px)

**Comment by sbatten** [comment]
@bpasero watermark never deals with extra elements in its own div correct? The js calculations aren't for centering. We just need to know if we should position inside the flex box or absolutely. The rest is then handled by CSS. The reason we are seeing jitter is that we have to delay this calculation so that the menubar dimensions are accurate.

**Comment by bpasero** [comment]
@sbatten sorry I have no clue why GH did not deliver your message to me. I will soon be out for vacation so we should try to finish this. I would suggest to go with your change if it resolves the layout trashing on startup and then we fix jitter as a follow up bugfix if possible.

**Pull request merged**
