### PR TITLE
Fix Japanese transration "noExt"

### PR DESCRIPTION
**Pull request by MisakiAkatsuki**
In Japanese, "拡張機能なし" means "no extension package".
If "no file extension" is expressed in Japanese, it will be "拡張子なし".

noext

### CODE REVIEW

**Comment by johnliu2016** [comment]
@lukaschal,  please send below string to linguistic review, it's incorrectly translated to JPN.

/Localize/jpn/vscode/src/vs/workbench/services/textfile/electron-browser/textFileService.nls.resx.lcl
      <Item ItemId=";noExt" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[No Extension]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[拡張機能なし]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\workbench\services\textfile\electron-browser\textFileService.nls.resx
ID: ".resx", 0; "noExt"
SRC: No Extension
TGT: 拡張子なし

**Comment by MisakiAkatsuki** [comment]
@johnliu2016 and @lukaschal, Thank you!

**Pull request closed without merging**
