### PR TITLE
Declare documentRangeFormatting in JSON LS

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
See reason in https://github.com/Microsoft/vscode/pull/72124

**Comment by aeschli** [comment]
We have a setting `json.fomatter.enabled` to configure whether the formatter is on or off. This needs to continue to work.
Fix has to:
- pass in the initial setting through the InitializeParams (e.g. `InitializeParams.initializationOptions.settings`)
- register the formatter like that:
```const capabilities: ServerCapabilities = {
		foldingRangeProvider: enableFormatter ? { id: 'json.Formatter ' } : false ;
	};
```
- use `RegistrationRequest` and `UnregistrationRequest `to register/unregister by id when the setting changes.

**Comment by mickaelistria** [comment]
Why not just enabling it by default? AFAIK, the capability here is for the manual formatting, not the automated one. I don't get what's the value of making the manual one off by default and -as mentioned in #72124- I see it introduce complexity? Is it because VSCode uses another formatter?

**Comment by aeschli** [comment]
Enabling by default on the server means the language client will register the formatter with VSCode. If you have multiple formatters registered for a given document (e.g. also prettier registers a JSON formatter), we now need to prompt the user which formatter or sometimes even pick just one.

Until the last VSCode build, the only way to avoid the conflict was to configure wach formatter and e.g. use the 'json.formatter.enabled' setting to disable the built in formatter. When false, the sever deregisters, causing the client to deregister.

Even there are now new ways of solving formatter conflicts in VSCode, we can't remove the setting in the LS server. Not only to be backward compatible to VSCode users but also to JSON LS clients.

**Comment by mickaelistria** [comment]
It's a client issue (how to dispatch a request to multiple possible provider) leaking into a server implementation. Dealing with enablement in the server isn't a proper solution when dealing with conflicts, the remediation of the conflict must be the client informed to pick one provider or the other.

I think it's much simpler as a contributor and as an "embedder" that I just tweak the JSON Language Server on my side. I don't plan to implement the described workflow, so let's close this PR.

**Pull request closed without merging**
