### PR TITLE
fixed issue show clock badge on Activity Bar icon when tests are running

### PR DESCRIPTION
**Pull request by AvaVellozzi**
https://github.com/microsoft/vscode/issues/201982

**Proposed Changes:**
1. The script introduces error handling improvements to prevent runtime errors related to accessing undefined properties. Specifically, it checks whether `clockIcon.element` is undefined before creating the `NumberBadge` instance. If the element is undefined, it logs an error message to the console.

2. The code is organized into two classes, `TestingProgressUiService` and `TestingProgressTrigger`, to encapsulate related functionality. This improves code readability, maintainability, and separation of concerns.

3. The code utilizes TypeScript's type system to enforce type safety and prevent type-related errors. This ensures that the code adheres to TypeScript's strict type checking rules and enhances the overall reliability of the application.

**Testing Instructions:**
1. To test the error handling improvement, deliberately set `clockIcon.element` to undefined before invoking the `updateActivityBarIcon` method. Then, observe whether the error message is logged to the console as expected.

2. Review the code structure and verify that related functionality is encapsulated within the appropriate classes (`TestingProgressUiService` and `TestingProgressTrigger`). Ensure that each class has a clear responsibility and adheres to the single responsibility principle.

### CODE REVIEW

**Comment by AvaVellozzi** [comment]
> @AvaVellozzi please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company=Ava Vellozzi]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

**Comment by AvaVellozzi** [comment]
> @AvaVellozzi please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="Ava Vellozzi"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

**Comment by AvaVellozzi** [comment]
@microsoft-github-policy-service agree

**Comment by connor4312** [comment]
We should be able to use the IProgressService for this, we should not need to interact directly with the activity bar. The `UnmanagedProgress` class may be a useful utility.

**Pull request closed without merging**
