### PR TITLE
Add support for F20-F24 keys in keyboard shortcuts

### LINKED ISSUE #89166: The F20-F24 key's are "unknown"
- VSCode Version: Tested on VSCode Insiders 1.42.0-insider
- OS Version: Windows 10 Version 1909 (OS Build 18363.592)
 - Keyboard: Corsair K95 platinum RGB cherry mx brown

Steps to Reproduce:

1. Map one of your keyboard keys to the f20 key.
2. Go to the keybindings.json.
3. Click on the buttun "Define Keybinding (Ctrl+K Ctrl+K)".
4. Press the button you assigned the f20 key to.
5. It says unknown
2020-01-23 15-10-41 mp4_snapshot_00 04 750

When I do the same thing but for any key f1-f19 it shows the correct key and works just fine.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by iliazeus**
There seems to be no real reason why these specific keys were excluded. They even had the placeholder `IMappingEntry` entries.

The `keyCodeOrd` column of the `mappings` array was unused in the code. Instead of renumbering the numbers in that column after the addition of new keys, I have removed it entirely.

Resolves #89166

### CODE REVIEW

**Review by alexdima — APPROVED** [review]

**Review by ulugbekna — APPROVED** [review]

**Comment by themarkwilliams** [comment]
Apologies if this is not the right place to comment. . . 

Tested this with VS Code 1.78.1 installed, F20-F24 are still showing as "unknown'.

**Comment by iliazeus** [comment]
Can you tell me your arch/os, and how did you test it? And also which `Keyboard: Dispatch` value is selected in the settings?

It is working fine for me on version `1.78.1`, on x64 Linux; both with `code` and `keyCode` dispatch.

**Comment by themarkwilliams** [comment]
x64, Windows 11. 

I did not have a keyboard.dispatch value configured in my settings.json. I added it both ways, but it had no impact. Initial googling shows that value isn't used by Windows, but I could be wrong.

I was attempting to setup some VSCode hotkey mappings using a Stream Deck. SD Device Buttons mapped to F1 - F19 work fine in VSCode. F20-F24 all show unknown when trying to use those as the mapped key. 

To make sure it isn't the SD causing the issue, I used Keyboard Manager in Powertoys to map F24 to the Enter key and the SD triggers that fine.

**Comment by ulugbekna** [comment]
@themarkwilliams could you please create a new issue for this, so we could track it? Also, please, include the gif of pressing F20-F24 with the screencast mode on (invoke command "Developer: Toggle Screencast Mode") and keyboards troubleshooting on

**Comment by iliazeus** [comment]
@ulugbekna @themarkwilliams this issue is probably caused by me forgetting to set the `eventKeyCode` (sixth, just before `VK_` codes) column of the F20-F24 keys :smiling_face_with_tear: 

https://github.com/microsoft/vscode/pull/179591/files#diff-138162afd36e83b6c3e992d79cfc212f1b3bb9753411737b37b3307baface3f8R613-R617

I left zeros there, should've probably set to 131-135, as [here](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) or [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#:~:text=keydown%20event%20caused%20by%20function%20keys)

**Comment by themarkwilliams** [comment]
Issue 182200 created - https://github.com/microsoft/vscode/issues/182200

**Pull request merged**
