### PR TITLE
SimpleFindWidget Add next,previous,history: Fixes #29708 #29661

### LINKED ISSUE #29708: Find: No find history
Testing #29479

The find widget in the editor provides a find history (alt+up/alt+down), there is currently no such support in the terminal.

### PR DESCRIPTION
**Pull request by cleidigh**
@rebornix 
@Tyriar 
- Of course the last five percent was all the work
- The need for a new context for FindInput Focused was somewhat messy
- Had to touch more files than expected, was necessary as there are four clients 
- Re-FactoringTheFindWidget for common use everywhere will take quite a bit of work
  since it's so intertwined with the editor
- Hopefully this is useful until we re- factor that

 Fixes #29708 #29661 also services the modified simpleFindWidget to all users

### CODE REVIEW

**Comment by mjbvz** [comment]
@cleidigh Looks like something went wrong with the commit or PR. I only see whitespace diffs. Can you please try resubmitting the changes

**Comment by cleidigh** [comment]
@rebornix 
Sorry I seem to be in some kind of merge hell ... git is not cooperating.
May have to redo this PR.

**Comment by rebornix** [comment]
@cleidigh maybe some rebasing and force push can help.

**Comment by cleidigh** [comment]
Closing and replacing with PR #32113

**Pull request closed without merging**
