### PR TITLE
Flush debounced events when disposing of a listener

### PR DESCRIPTION
**Pull request by Tyriar**
This is a behavior change and could introduce regressions, it seems like a reasonable assumption to make though.

Part of #173111

Should we add an option?

### CODE REVIEW

**Comment by bpasero** [comment]
Adding more stake holders of events. To give some background: we have code that listens to `Event` via the `debounce` or `accumulate` helpers while also registering as disposable:

https://github.com/microsoft/vscode/blob/fe8228c713c9a990e7f14ae034dfb3d190628ef2/src/vs/workbench/browser/parts/editor/editorStatus.ts#L621

If the user is able to trigger an action that both fires the event and disposes the emitter, that event is lost when debounced. 

So the suggested fix is to ensure that when disposing an emitter that is throttled, any withheld events are sent immediately, otherwise they are lost.

**Comment by jrieken** [comment]
> Should we add an option?

Definitely and I would even argue that flush/force emitting on dispose is an anti-pattern to begin with

**Review by jrieken — CHANGES_REQUESTED** [review]
needs an option and motivation

**Review by jrieken — APPROVED** [review]

**Review by Tyriar — COMMENTED** [review]
Merging this as it's pretty safe as it's only adopted in `Event.defer`

**Pull request merged**
