### PR TITLE
[Coffeescript] Fix coffeescript parse bug

### LINKED ISSUE #499: [coffeescript] syntax highlighting broken when divide symbol is not separated using space
screen shot 2015-11-23 at 8 16 36 pm

### PR DESCRIPTION
**Pull request by vedanshujain**
Fixes #499

### CODE REVIEW

**Comment by vedanshujain** [comment]
This fixes https://github.com/Microsoft/vscode/issues/499

**Comment by vedanshujain** [comment]
@aeschli Hey, I noticed you added tokeniser tests for coffee.. Do you want me to add this specific case and some more there as well (If you are not planning to do it yourself)?

**Comment by aeschli** [comment]
@vedanshujain Thanks a lot for the fix suggestion. I uses a slightly different approach (with a look ahead). See issue #499.
Thanks anyway for your help.

**Comment by vedanshujain** [comment]
@aeschli thanks.. looks good

**Pull request closed without merging**
