### PR TITLE
Refactored code used in many files to the vs/utils folder

### PR DESCRIPTION
**Pull request by japrozs**
Refactored code

### CODE REVIEW

**Comment by bpasero** [comment]
What issue is this fixing?

Note: we typically do not accept changes that do cleanup changes.

**Comment by japrozs** [comment]
That's okay

**Comment by japrozs** [comment]
It's not fixing an issue. I just transferred all the utility code into a utils folder

**Comment by bpasero** [comment]
> I just transferred all the utility code into a utils folder

VSCode does not accept PRs like that. Please see https://github.com/microsoft/vscode/wiki/How-to-Contribute#pull-requests

**Pull request closed without merging**
