### PR TITLE
Implement tab close button configuration.

### PR DESCRIPTION
**Pull request by jez9999**
Allows the user to enable/disable per-tab close buttons.

Addresses issue #10739.

### CODE REVIEW

**Comment by bpasero** [comment]
@jez9999 I propose a much simpler change where we simply display: none on the editor close action (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/media/tabstitle.css#L168). 

I know that initially I thought we want to keep the dirty indicator but actually I noticed ST is also just removing the entire thing and I am fine with that.

Besides the CSS change I do not think anything else is needed?

**Comment by jez9999** [comment]
Erm, who cares what Sublime Text is doing?  Do you always copy them?

The dirty indicator is a very useful thing to have and I strongly disagree with removing it.  What's wrong with my way of doing things?

**Comment by jez9999** [comment]
While we're citing other editors, Visual Studio with the Productivity Power Tools allows you to remove the tab close buttons but keep the dirty indicator.

**Comment by bpasero** [comment]
@jez9999 looking at other editors gives us a chance to predict what users might expect from such a feature. I just picked a random editor that seems to be quite popular in the target audience of developers we have. There are many more indicators throughout the UI that tell you an editor is dirty, it is not just limited to tabs.

**Comment by jez9999** [comment]
@bpasero I don't think the fact that ST implements theirs in a lazy way is an indication that users will be "expecting" the lack of a dirty tab indicator.  And I've done the work for you here so it's not much of an argument to say that it is more complex - the work is done.

**Comment by bpasero** [comment]
@jez9999 I agree with your points mostly but 

> the work is done

Is never true for a project that goes on unless we make you a team member and you keep maintaining this feature.

I should have a chance later to look more closely at the change.

**Comment by bpasero** [comment]
Thanks for this PR but I decided to implement it differently (see https://github.com/Microsoft/vscode/commit/8185338229f6b14373cb2020fccd5d8f818e2c2d)

**Comment by jez9999** [comment]
Correction: You decided to implement something different which nobody had asked for.

**Pull request closed without merging**
