### PR TITLE
Polish breadcrumbs icons spacing

### PR DESCRIPTION
**Pull request by mbelsky**
Hey,

There is a simple fix for #79005

### CODE REVIEW

**Review by jrieken — COMMENTED** [review]
Did you test that this doesn't have an affect to other places where these icons are being used? `symbol-icon` is popular, being used for quick outline and the outline tree as well.

**Comment by mbelsky** [comment]
I've found `symbolKindToCssClass` imports in these files

- [ ] src/vs/editor/contrib/documentSymbols/outlineTree.ts
- [ ] src/vs/editor/standalone/browser/quickOpen/quickOutline.ts
- [x] src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts
- [ ] src/vs/workbench/contrib/callHierarchy/browser/callHierarchyTree.ts
- [ ] src/vs/workbench/contrib/quickopen/browser/gotoSymbolHandler.ts
- [ ] src/vs/workbench/contrib/search/browser/openSymbolHandler.ts

I'll check all of them on this weekend

**Comment by MJ-Mohith** [comment]
It would be great if you upload a screenshot of both previous and after your change.

**Comment by mbelsky** [comment]
@jrieken thank you for review. I've created a special css rule to fix that issue. 

I'm not sure that `src/vs/workbench/browser/parts/editor/media/breadcrumbscontrol.css` is a correct file for this change however I choose it because `src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts` renders this nodes.

**Comment by MJ-Mohith** [comment]
Did you test your change and see the effect when you build your instance of vscode?

**Comment by jrieken** [comment]
Changes look better (less risky). Thanks. Maybe move the change above line 20 as the rules in that range talk about `monaco-breadcrumb-item`.

**Comment by jrieken** [comment]
wrt the value, I feel like the padding should be 4px. It's a little hard to compare as the tree shows items in a larger font (and uses a different implementation)

**Comment by mbelsky** [comment]
@MJ-Mohith yes, I did

@jrieken Sure, today I'll move this rule above.

And about the padding: I've seen the tree's padding is 4px, however `file monaco-breadcrumb-item` has 6px padding. 
Screenshot 2019-08-20 at 12 51 43

So I've selected 6px as value because it's a breadcrumb item too.

Well should I change it to 4px?

**Comment by jrieken** [comment]
> And about the padding: I've seen the tree's padding is 4px, however file monaco-breadcrumb-item has 6px padding.

Ah, that's where it comes from. Yeah, makes sense then. Consistency is key

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
Thanks

**Pull request merged**
