### PR TITLE
fix replacement index,length for terminal completions

### LINKED ISSUE #236254: requesting completions for `code ` does not work, but typing does
1. Type `code `. `ctrl+space` 
2. 🐛 no suggestions
3. Type `-`, all of the expected options show up.

Debugging shows the options (`--locale` etc.) are all being returned from the extension correctly, so `SimpleCompletionModel` is filtering them out.

cc @Tyriar 

Seems like we need some tests for the renderer side filtering of provided completions.

### LINKED ISSUE #236256: incorrect terminal file completions
https://github.com/user-attachments/assets/7c2cfeb0-7c3d-4cea-af67-7e740c52a83e

cc @Tyriar

### LINKED ISSUE #236257: command completions  incorrectly showing when I type `/`
Image

cc @Tyriar

### PR DESCRIPTION
**Pull request by meganrogge**
adds more tests cases and:

fixes #236256
Screenshot 2024-12-16 at 12 04 55 PM

fixes https://github.com/microsoft/vscode/issues/236257
Screenshot 2024-12-16 at 12 04 29 PM

fixes https://github.com/microsoft/vscode/issues/236254
Screenshot 2024-12-16 at 12 10 11 PM

### CODE REVIEW

**Comment by Tyriar** [comment]
Can this one complete from after the last `/`? Otherwise it won't scale it eventually the completion in the widget will get truncated:

image

like this:

```
.npmrc
bat/
...
```

**Comment by meganrogge** [comment]
It continues completing if that's what you mean

Screenshot 2024-12-16 at 12 53 52 PM

**Review by rebornix — APPROVED** [review]

**Comment by Tyriar** [comment]
@meganrogge it should be this:

image

**Comment by meganrogge** [comment]
seems like that's a feature request?  with extension completions disabled, in pwsh, it works like this:

Screenshot 2024-12-16 at 4 18 37 PM

**Comment by meganrogge** [comment]
I'm not sure how to do that without breaking things.

**Pull request merged**
