### PR TITLE
Fix a bug for not warn properly when file to create already exists

### PR DESCRIPTION
**Pull request by laphets**
fix#59549
Fix a bug for not warn properly when file to create already exists

**Now it looks like this:**
image

### CODE REVIEW

**Comment by laphets** [comment]
@bpasero Can you help me checking it, thx

**Comment by bpasero** [comment]
@laphets please stay away from using sync-fs methods.

**Comment by laphets** [comment]
@bpasero Hmmm, so do you have any suggestion on solving this problem..

**Comment by laphets** [comment]
@bpasero I'm now using find method of ExplorerItem. Is this acceptable?

**Comment by isidorn** [comment]
Thanks for your PR, howver we are not accepting PRs in this area currently - because the code is tedious and it is easy to introdcue issue.
If you would like to contribute to VSCode I suggest you search for issues tagged with `help-wanted` and `good-first-issue`.

Cheers

**Comment by isidorn** [comment]
Clossing as out of scope.
Thank you again for your PR.

**Pull request closed without merging**
