### PR TITLE
Escape special glob chars when using "Find in Folder"

### LINKED ISSUE #82415: Find in Folder includes all folders upon search on named folder in workspace
Issue Type: <b>Bug</b>

1. Create a workspace add the following folder, plus couple of other folders

```
//...
    {
      "path": "C:\\Users\\...\\folder1",
    },
    {
      "path": "C:\\Users\\...\\folderNamed",
      "name": "folderNamed (Special Folder)"
    },
    {
      "path": "C:\\Users\\...\\folder2",
    }
//...
```
2. go to explorer view tab
3. create same file with `lorem-ipsum` text in all the folders
4. right click on the `folderNamed (Special Folder)`
5. click on `File in Folder...`
6. ensure that **files to include** set as `./folderNamed (Special Folder)`
7. type `lorem` in the folder into the **Search** box
8. you will see that it retrieves from **folder1** and **folder2** too

where it should only retrieve from `folderNamed (Special Folder)`.
behaviour works fine on `folder1` and `folder2` since they are not named.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (39.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
markdown-imsize|amo|0.0.2
azds|azu|1.0.120191007
emojisense|bie|0.5.3
markdown-mermaid|bie|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.31.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.1
prettier-vscode|esb|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.12.0
mdmath|goe|2.4.0
cloudcode|goo|0.0.12
asciidecorator|hel|0.2.0
rest-client|hum|0.22.2
ftp-simple|hum|0.7.4
reg|ion|1.0.1
markdown-extended|jeb|1.0.13
markdown-extension-pack|jeb|0.0.3
plantuml|jeb|2.12.1
super-replace|jeb|0.3.1
sharppad|jma|1.1.0
vscode-peacock|joh|3.1.5
vscodeilviewer|jos|0.0.1
jq-syntax-highlighting|jq-|0.0.2
docomment|k--|0.1.8
wordcounter|kir|1.9.3
rainbow-csv|mec|1.3.1
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-logicapps|ms-|0.2.18
vscode-kubernetes-tools|ms-|1.0.4
mssql|ms-|1.6.0
sqlops-debug|ms-|1.3.0
vscode-postgresql|ms-|0.2.0
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
autorest|ms-|2.0.1
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
github-issues-prs|ms-|0.9.1
Go|ms-|0.11.7
mono-debug|ms-|0.15.8
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.950
vsliveshare-audio|ms-|0.1.66
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
debugger-for-chrome|msj|4.12.0
color-highlight|nau|2.3.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.1
quicktype|qui|12.0.46
vscode-yaml|red|0.5.3
elastic|ria|0.13.3
vscode-odata|sta|0.1.0
vscode-markdown-paste-image|tel|0.12.3
usql-vscode-ext|usq|0.2.15
vscodeintellicode|Vis|1.1.9
application-insights|Vis|0.4.2
vscode-redis|vit|1.2.0
azure-iot-edge|vsc|1.17.0
azure-iot-toolkit|vsc|2.10.0
vscode-ansible|vsc|0.5.2
WebTemplateStudio-dev-nightly|WAS|0.0.1925201
vscode-todo-highlight|way|1.0.4
t4-support|zbe|0.4.3

</details>

### PR DESCRIPTION
**Pull request by davidnx**
Fixes #82415

### CODE REVIEW

**Comment by davidnx** [comment]
For inspiration, see also: [Python's glob.escape](https://docs.python.org/3/library/glob.html#glob.escape) function.
Their docs indicate only `?`, `*`, and `[` need to be escaped, but tests with VS Code globbing indicated that `]` too needed escaping. In this PR, I am handling all four, and converting them to character range sequences.

**Comment by andreamah** [comment]
Thanks for the contribution! 

Trying this out, it might be a bit confusing to see extra square brackets in the "files to include" field when you want to search within them. Rather, would it be possible to change the way that the path gets interpreted the search actually happens? I believe that it happens around here:
https://github.com/microsoft/vscode/blob/3c275da9a161f38a545ed5b566d49d447e98cdfd/src/vs/workbench/services/search/common/queryBuilder.ts#L159

That way, we don't see any difference in the UI.

Another thing: I tried it out and I'm still getting results from others folders? Unsure why.
image

**Comment by davidnx** [comment]
@andreamah The screenshot you sent is indeed perplexing, though if it is a legit bug I don't think it's related to my changes -- perhaps the existing globbing functionality is broken on some platforms? Seems unlikely, but I can't think of another reason why it wouldn't be working on your side. Can you share which platform or OS you tried it on? Below are my results on Windows, and everything works as expected:

* Folder structure I am using for the test (I tried to mimic what you had based on the limited information from your comment):
  image

* And here are results showing search works correctly with the escaped glob pattern that my change produced:
  image

As you can see, only the results in `subfolder[new]` appear, as desired. I don't know why it behaved differently in your tests, and I would suggest it may be a separate bug on globbing, no on how this PR is escaping glob patterns. This PR looks correct as far as I can tell.

---

Re. your comment:
> _it might be a bit confusing to see extra square brackets in the "files to include" field when you want to search within them. Rather, would it be possible to change the way that the path gets interpreted the search actually happens?_

I think what you're proposing is equivalent to saying "let's get rid of globbing as the mechanism to specify search paths in VS Code", which would be a very significant change, likely undesirable, and certainly out of scope for this PR. Globbing is a fine and commonplace choice for search tools, and it requires escaping special characters. I don't see any way around that... This PR simply implemsnts escaping properly, which was missing before.

Let me know how I can help further, I think this PR will improve the experience of VSCode users.

**Review by andreamah — APPROVED** [review]
Thinking this over again, it seems to make a lot of sense. I also didn't run into the bug that I ran into last time, so I'll just bring it up again if I see it again.

Thanks for the contribution!!

**Review by mjbvz — APPROVED** [review]

**Review by roblourens — APPROVED** [review]

**Pull request merged**
