### PR TITLE
Issue #79599 - CSS LS fails if InitializationOptions.dataPaths not set

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by octref** [comment]
Thanks! I think a clearer fix would be to change:

```ts
const dataPaths: string[] = params.initializationOptions.dataPaths;
```

to

```ts
const dataPaths: string[] = params.initializationOptions.dataPaths || [];
```

Do you mind doing that instead?

**Comment by mickaelistria** [comment]
I'm not at all a TypeScript expert, so I'll trust your suggestion and submit a new version of the commit.

**Comment by mickaelistria** [comment]
@octref I updated the patch as suggested.

**Comment by octref** [comment]
Thanks!

**Pull request merged**
