### PR TITLE
Add model change events separate from group

### LINKED ISSUE #134359: API Access to "Open Editors": events fired multiple times on open and close
Does this issue occur when all extensions are disabled?: Yes/No  Unable to test in extension host environment.

@lramos15 

With this code:

```js
vscode.window.onDidChangeActiveTab(tab => {
  console.log(`tab : ${tab}`);
});

vscode.window.onDidChangeTabs(tabs => {
  console.log(`tabs : ${tabs}`);
})
```

1.  Open a new file in preview and each listener is triggered two times.  

2.  Open a new file not in preview and each listener is triggered three times.  

3.  Close a file (preview or not) that is focused and each listener is triggered two times.  

4.  Close a file (preview or not) that is NOT focused and each listener is triggered one time.   

I assume #4 is the correct behaviour and the others are incorrect.  

-----------------

Version: 1.61.0-insider (user setup)
Commit: c9e8266ee24f34107ff52d836a4e8f533afb93c5
Date: 2021-10-01T14:45:54.159Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

### PR DESCRIPTION
**Pull request by lramos15**
This PR fixes #134359

@bpasero Separating this out into a PR to address some of the comments and iterate on https://github.com/microsoft/vscode/commit/82b8de69a72653a00610ca08e1d3b56d88cfec8d

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
My feedback for the first round of review is listed in https://github.com/microsoft/vscode/commit/82b8de69a72653a00610ca08e1d3b56d88cfec8d. Please ping once incorporated for a second round.

`Event.Relay` is defined here: https://github.com/microsoft/vscode/blob/76c3eb94c9a29c2f4a54af3dd522a376a8ef28a7/src/vs/base/common/event.ts#L879

**Review by bpasero — CHANGES_REQUESTED** [review]
After looking at this a second time I think this new event is somewhat misleading and maybe we need to revisit how we achieve this. To clarify: today we have a `IEditorGroupView.onDidGroupChange` event that is more like a UI-event with its own set of problems (as indicated by https://github.com/microsoft/vscode/issues/134359).

Then we have a `IEditorGroupModel` which today does not have a single event for changes but many events for each kind of change. We use that as one of the sources in `IEditorGroupView` to send events out to listeners.

For the tabs API, it would imho be beneficial to be able to listen to change events directly on the model and not the view to send the events out when they occur. This resonates with me because the tabs API should reflect the state of `EditorGroupModel` always.

Instead of exposing a new event on `IEditorGroupView` I would rather suggest to expose the `model` from it and provide an event that resembles any change that happens in the model. Something like: `IEditorGroupView.model.onDidChangeModel` with an associated event that explains the kind of change. I would even go as far and then change the `IEditorGroupView` to use this event as well, dropping [all the fine grained listeners](https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L526-L536) we have. I don't think keeping both aggregated event and fine grained event around is necessary. 

Ideally we could drop any UI-event listening from the tabs model API and switch entirely over to the model-event. If there is an event missing right now in the model, we should consider adding it.

Thoughts?

**Comment by lramos15** [comment]
@bpasero This makes sense. Is there ever a change to the view which wouldn't affect the underlying model?

**Comment by bpasero** [comment]
Not sure, maybe there are some events that are not yet fired from the model, such as whether the group is active or not. We can always add more events to the model.

**Comment by lramos15** [comment]
I don't know why but I decided to do all this work on a separate branch because it felt like a larger pivot and I wanted to start fresh. Closing this and using #137388 as the PR which addressed the model event we decided on

**Pull request closed without merging**
