### PR TITLE
Add missing call to super.dispose()

### PR DESCRIPTION
**Pull request by nicksnyder**

### CODE REVIEW

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/commit/1c7479e970499383d292e1264cfaeda794a24864 

@sandy081 Why? The ZoneWidget doesn't use anything of widget. So, instead of adding the missing dispose-call I'd opt to not inherit from it

**Comment by nicksnyder** [comment]
It doesn't look like anything in the codebase depends on ZoneWidget extending Widget so you can just close this PR and revert 1c7479e970499383d292e1264cfaeda794a24864 if that is your preference.

**Comment by jrieken** [comment]
Let's wait for @sandy081

**Comment by sandy081** [comment]
Yes, there was no need to extend the `Widget` class. I had plans to use the `ZoneWidget` for the Settings editor and needed some changes but was not needed. Looks like above change was slipped in then. Will revert it. Thanks for brining to me.

**Comment by nicksnyder** [comment]
@sandy081 great, can you `git revert 1c7479e970499383d292e1264cfaeda794a24864` and then close this PR without merging

**Comment by sandy081** [comment]
There are some merges involved. So removed it in a new change

**Pull request closed without merging**
