### PR TITLE
Closes #156527 expands the `vscode.moveViews` command to allow targeting of locations

### LINKED ISSUE #156527: Expand the `vscode.moveViews` command to allow moving views into a location
Currently the `vscode.moveViews` command allows extensions to move views into an explicit view container, but you can't move a view into a location without a explicit target (while a view can be drag and dropped into an arbitrary location).

/cc @sbatten

### PR DESCRIPTION
**Pull request by eamodio**
Closes #156527

/cc @sbatten

### CODE REVIEW

**Comment by sbatten** [comment]
The goal here is to allow creating a new view container with the view?

**Comment by eamodio** [comment]
The main use case is for extensions to be able to provide action(s) to allow easy movement of a view/views. While I'm not planning to do this, but as GitLens allows you to move its views from the SCM side bar to the GitLens side bar, we could allow you to move them into the panel or to the secondary side bar.

Without this extensions need to "pre-allocate" view containers in the slots that it would move them into, which until https://github.com/microsoft/vscode/pull/156526 lands isn't even possible for the secondary side bar.

**Review by Drerootz1 — COMMENTED** [review]
Good

**Review by Drerootz1 — APPROVED** [review]
Good

**Review by Militarysuperior3 — APPROVED** [review]

**Comment by sbatten** [comment]
Hmm, that makes me think that #156526 is the solution. Generally, we've always tried to avoid extensions doing view movement after drag and drop became available.

**Comment by eamodio** [comment]
@sbatten https://github.com/microsoft/vscode/pull/156526 is a solution for a lot of use cases (and would solve my GitLens needs), but I could still see the value in this, since we are already allowing extensions to move views around, this just allows it to all-the-places.

**Comment by sbatten** [comment]
I think we will move on https://github.com/microsoft/vscode/pull/156526

**Pull request closed without merging**
