### PR TITLE
Web - run smoke tests using playwright

### PR DESCRIPTION
**Pull request by bpasero**
This replaces puppeteer with [playwright](https://github.com/microsoft/playwright) and adds support for `--browser <chromium|firefox|safari>`

### CODE REVIEW

**Comment by bpasero** [comment]
@Tyriar one thing I could not figure out: after the test finishes, the server instance seem to hang around and as such I cannot run the same test again because the port 9888 is blocked. I see there is code in place to kill the server but that does not seem to work? Curious if you noticed that as well.

**Comment by bpasero** [comment]
@Tyriar nevermind my question, I figured out how to configure the server so that it would automatically close when the connection closes. It works fine now.

**Comment by bpasero** [comment]
I think this is good for a review. Follow up work:
* figure out why some of the tests are disabled for web specifically
* verify this works on Windows (seems broken) and Linux

**Comment by bpasero** [comment]
Pushed a fix for Windows.

**Comment by Tyriar** [comment]
Still seems to be broken on Windows?

image

**Comment by bpasero** [comment]
@Tyriar they seem to work fine for me on Windows with latest commits in this PR. Did you run "`cd test/automation && tsc`" to compile to latest?

**Comment by Tyriar** [comment]
That's better, it still gets stuck on the first test though:

image

The quick pick appears to open before the remote is fully connected to.

**Comment by bpasero** [comment]
@Tyriar the test is flaky, I doubt this is related to playwright. We should fix flaky tests as a follow up, this is a team efford we are doing this milestone.

**Comment by pavelfeldman** [comment]
> @Tyriar the test is flaky, I doubt this is related to playwright.

*Might be related - @dgozman and myself saw a race there when VS Code was overwriting something already typed into that box. It looked like a real problem that could happen in the wild back then.*

**Pull request merged**
