### PR TITLE
Make v8-profiler, css-parser URI http-proxy friendly

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by jrieken** [comment]
Can you elaborate a little on this?

**Comment by nehaljwani** [comment]
On a machine behind corporate proxy:
```
(vscode) [nwani@machine vscode ] (master)$ node --version
v8.9.1

(vscode) [nwani@machine vscode ] (master)$ npm --version
5.5.1

(vscode) [nwani@machine vscode ] (master)$ env | grep -i proxy
https_proxy=http://proxy.my-corporate.com:3128

(vscode) [nwani@machine vscode ] (master)$ ./scripts/npm.sh install --arch=x64

> code-oss-dev@1.19.0 preinstall /spare/scratch/1510575918/vscode
> node build/npm/preinstall.js

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/jrieken/v8-profiler.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Connection refused
npm ERR! github.com[1: 192.30.253.112]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

^C^C^C
```

Now apply this patch and npm succeeds
```
(vscode) [nwani@machine vscode ] (master)$ sed -i 's,git://,git+https://,' npm-shrinkwrap.json 

(vscode) [nwani@machine vscode ] (master *)$ git diff
diff --git a/npm-shrinkwrap.json b/npm-shrinkwrap.json
index 203fa2d..d0014ac 100644
--- a/npm-shrinkwrap.json
+++ b/npm-shrinkwrap.json
@@ -544,7 +544,7 @@
     "v8-profiler": {
       "version": "5.6.5",
       "from": "jrieken/v8-profiler#vscode",
-      "resolved": "git://github.com/jrieken/v8-profiler.git#5e4a336693e1d5b079c7aecd286a1abcfbc10421"
+      "resolved": "git+https://github.com/jrieken/v8-profiler.git#5e4a336693e1d5b079c7aecd286a1abcfbc10421"
     },
     "vscode-debugprotocol": {
       "version": "1.24.0",

(vscode) [nwani@machine vscode ] (master *)$ ./scripts/npm.sh install --arch=x64

> code-oss-dev@1.19.0 preinstall /spare/scratch/1510575918/vscode
> node build/npm/preinstall.js

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> typechecker@2.0.8 preinstall /spare/scratch/1510575918/vscode/node_modules/typechecker
> node ./cyclic.js


> oniguruma@6.1.1 install /spare/scratch/1510575918/vscode/node_modules/oniguruma
> node-gyp rebuild
```

**Comment by nehaljwani** [comment]
This is similar to the change: https://github.com/Microsoft/vscode/commit/87c476a3acb733dca04ba1d0958f2ed5672267b3

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
Thanks @nehaljwani

**Pull request merged**
