### PR TITLE
Activity bar active indicator cleanup

### LINKED ISSUE #83328: Activity bar icon focus indicator is hard to see (probably should be independently themable)
If you switch to the explorer sidebar when there is no folder/workspace open you will see the active activity bar line is not correct.
image

This seems to happen anytime a sidebar doesn't set input focus into the view. It also can happen with custom views.

### LINKED ISSUE #84353: Activity Bar UI Quirks
The latest VSCode activity element background color makes it easy to redesign the interface in a sidebar-connected to the activity style as shown below:

vscode

There's a weird looking extra space at the top though. Can we make it better?

vscode

You can test this with latest version of my 🦄 [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) theme.
 
- VSCode Version: 1.40
- OS Version: macOS High Sierra

Does this issue occur when all extensions are disabled?: Yes

Looking forward!

### PR DESCRIPTION
**Pull request by miguelsolorio**
This PR cleans up the sizing of activity bar elements. Previously they were 48x40 which would make them an odd size whenever you used `activityBar.activeBackground`:

image

So now they are an even 48px (square) and I've also adjusted the padding/margin so that there is no top margin on the first item (fixes #84353):

image

And lastly I introduced a new color token, `activityBar.activeFocusBorder`, for the active border when in focus, which is off by default (fixes #83328):

FYI @bpasero

### CODE REVIEW

**Comment by isidorn** [comment]
`activityBar.activeFocusBorder` works as expected.
As for the cleanup of the activity bar sizes. I like that they are squares know. What I do not like:
* The active border is now too long, and is even stronger than before. Before I could somehow survive it, but now I feel like it has gone over the top and that is simply screaming in my face for attention
* When the active border is on the first element the border goes all the way to the top title. I understand some user requested for this to be removed, however I disagree with this and simply find it ugly

I think decreasing just the size of the active border would solve my both concerns

**Review by isidorn — CHANGES_REQUESTED** [review]
_

**Comment by misolori** [comment]
> The active border is now too long, and is even stronger than before...I think decreasing just the size of the active border would solve my both concerns.

This is an effect of making the items square, we can't really make the border shorter without making the container back to the old size. besides, it would look really weird to have it this way if you use a background color (see below). And the width is at 2px, 1px was way too hard to notice, especially being at the left-most side of the screen where things behind affects the contrast.

image

> When the active border is on the first element the border goes all the way to the top title. I understand some user requested for this to be removed, however I disagree with this and simply find it ugly

This is actually something that always bothered me, other apps don't have this top margin:

image

So if you're not a fan of these changes I can simply just do the focus color token.

**Comment by isidorn** [comment]
I am not a fan of these changes, however I do not think I should be the one to decide against this. They are not bad changes, I just do not like strong UX in area which I personally do not find important in my day to day flow.
If you like them I think it is fair to push them to insiders and we can get more feedback and then decide.
We can also do the middle ground, decrease the width back to 1 px and keep the height increase. I am flexible.

**Comment by misolori** [comment]
I'll post this to our UX channel and see what the feedback is before merging in then.

**Comment by isidorn** [comment]
Good idea. Thanks!

**Comment by misolori** [comment]
Got several 👍  from the UX channel, will merge this in and look at the feedback next week for insiders.

**Pull request merged**
