### PR TITLE
Automatically adapt to windows: "Color Theme", "File Icon Theme", "User Snippets".

### PR DESCRIPTION
**Pull request by ZainChen**
Automatically adapt to windows: "Color Theme", "File Icon Theme", "User Snippets".
The main problem: There are too many "Color Theme" or "File Icon Theme" content, some of which will not be visible.
Before change:
image
After the change:
image

### CODE REVIEW

**Comment by ZainChen** [comment]
@chrmarti Hello, can this function be implemented with this code? Is there any need for improvement?

**Comment by ZainChen** [comment]
"Review requested: Review has been requested on this pull request. It is not required to merge.", does this mean that this code will not be merged? If so, hope to point out the inappropriate place, thank you very much.

**Comment by chrmarti** [comment]
Hi @ZainChen, sorry, I haven't had a chance to look into this. Please be patient while I'm busy working on other things.

Thanks for contributing to VS Code.

**Comment by ZainChen** [comment]
Hi, very happy to hear from you, hope this code can help VS code.
image

**Comment by chrmarti** [comment]
I wonder if there is a way to do this using CSS. That would be preferable to computing it in code.

**Comment by ZainChen** [comment]
Tried to modify the '.quick-input-widget' and '.quick-input-list' styles and didn't achieve the desired effect. Still trying.

**Comment by ZainChen** [comment]
Tried this situation. Will make vscode unsightly. 
image

**Comment by ZainChen** [comment]
I did not expect how to use css to achieve. But my current calculation method minimizes code modifications. Comply with the calculation rules of the "command" window. If css can't do it, consider this method.
image

**Comment by bpasero** [comment]
I think we implemented this, I see the picker getting smaller based on window heights.

**Comment by chrmarti** [comment]
Indeed, we did that on the side.

Thanks for the PR! Unfortunately this is now obsolete, closing.

**Pull request closed without merging**
