### PR TITLE
spinner for splashscreen

### PR DESCRIPTION
**Pull request by okobsamoht**
This PR is not fixing any issue
This PR is to add a spinner on the splash screen.
The spinner colors depends on the activity bar and the status bar colors

### when there is no opened folder
Screenshot from 2022-07-12 10-41-46

### when there is opened folder
Screenshot from 2022-07-12 10-41-53

### CODE REVIEW

**Review by okobsamoht — COMMENTED** [review]
reviewed

**Review by Dopeman31 — APPROVED** [review]
Fix

**Comment by Dopeman31** [comment]
Fix

**Comment by bpasero** [comment]
Thanks for the PR but we are not considering a change in this area via contribution at the moment.

**Pull request closed without merging**
