### PR TITLE
Feature: add window title separator prop

### LINKED ISSUE #94254: Allow customize the window title separator
The separator in `window.title` is a em dash but I would like to use my own "◆". Can I make a PR to add this?

### PR DESCRIPTION
**Pull request by muuvmuuv**
This PR fixes #94254

### CODE REVIEW

**Comment by muuvmuuv** [comment]
cc: @bpasero

**Review by bpasero — CHANGES_REQUESTED** [review]
Good start, but it seems I can trick a new line character into the title, so this needs to be normalized somehow:

`"window.titleSeparator": " <\n> "`

image

**Comment by bpasero** [comment]
Oh, I take it back, this already happens when configuring `window.title` with a newline.

**Comment by bpasero** [comment]
Thanks 👍

**Pull request merged**
