### PR TITLE
Update all icons to new iconography style

### PR DESCRIPTION
**Pull request by miguelsolorio**
🎉  This ([finally](https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif)) addresses #8017 and updates all of our iconography to have a consistent look. This is just the beginning and there will likely be more tweaks coming, but this at least gets the icons into Insiders and we can start testing for 1.37. 

:warning: **Note:** this does not include icons from the Ocitcons set (that work will come later) which are used in the status bar and other areas.

Here's a summary of the changes:

- All icons now use a single (monochrome) color
- All icons use a bevel edge/corner
- All icons use the same stroke width (with the exception of the debug toolbar)
- Highlighted icons (like debug, notifications, etc.) can use additional colors
- Activity bar icons are now 24x24 (we use a mask to resize all other icons) and are on a 48x48 square
- Activity bar badges are slightly smaller

image

FYI @microsoft/vscode

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
@misolori change looks OK to me in principle, but I wonder why there are differences to our icon exploration. E.g.

Explorer Icons Before
image

Explorer Icons Now (round corners? new folder icon not transparent?)
image

Activity Bar icons before (smaller)
image

Activity bar icons now (larger):
image

Twistie Arrows before (smaller):
image

Twistie Arrows now (larger?):
image

All in all this change does not seem to reflect the exploration we selfhosted on and provided feedback on.

**Comment by misolori** [comment]
@bpasero there are only minor updates to the icons but they largely still remain the same. We did an icon review with the design team and they noticed a few icons that needed to be polished to be more consistent. 

The bevel corners was something we added towards the end of the exploration to make them consistent as we were using a mixture ([see here](https://github.com/microsoft/vscode/issues/8017#issuecomment-502809582)). And we also went through all of the icons and made sure all icons were using the same stroke weight.

We did increase the activity bar icons by 1px so that they [fit the entire 24x24 square](https://user-images.githubusercontent.com/35271042/60409990-dbf39580-9b7a-11e9-9708-94e98f392083.png) (they previously didn't take up the entire space). Previously they looked off-centered and smaller to extension icons so this helps address that.

So all of these minor changes are for polish, we're still using the same icon/metaphor and the outline style. If we find additional issues we can continue to tweak them, but know the design team did do a thorough review to ensure they're all consistent. We'll also provide icon guidelines for extension authors to follow for creating their own icons.

**Review by bpasero — APPROVED** [review]

**Comment by bpasero** [comment]
Ok, feel free to merge then.

**Comment by bpasero** [comment]
@misolori please note https://github.com/microsoft/vscode/commit/e8792f4b7917148973938d826099211ff3ce2b47 that now caused a merge conflict (I moved a few icons and CSS from `electron-browser` to `browser`).

**Comment by misolori** [comment]
@bpasero thanks for the heads up, fixed the merge conflict and updated the new icons. Will merge after our planning call.

**Pull request merged**
