### PR TITLE
Better readable highlighted line for kimbie-dark-theme

### PR DESCRIPTION
**Pull request by vajahath**
modifies `editor.lineHighlightBackground` for better readable highlighted line. :art: 
## before
theme-before
## now
theme-now

### CODE REVIEW

**Comment by aeschli** [comment]
Word highlight is
`
        "editor.wordHighlightBackground": "#4a4a7680",
        "editor.wordHighlightStrongBackground": "#6a6a9680"
`
Do you wany to add this to this PR?

**Comment by vajahath** [comment]
Thanks. I'll be addressing this on Monday. I'm away from PC this weekend.

**Comment by vajahath** [comment]
Don't know why that check is failing..

**Comment by aeschli** [comment]
Both `editor.wordHighlightBackground` and `editor.wordHighlightStrongBackground` have to use transpareny, otherwise they hide other decorations ate the same place...

**Comment by aeschli** [comment]
@vajahath Can you add transpareny to `editor.wordHighlightBackground` and `editor.wordHighlightStrongBackground`?

**Comment by aeschli** [comment]
Closing due to inactivity

**Pull request closed without merging**
