### PR TITLE
in multiple git repositories workspace, can't view/focus changes on keypress up arrow and enter in `source control provider view`

### PR DESCRIPTION
**Pull request by cedric05**

### CODE REVIEW

**Comment by cedric05** [comment]
currently
ezgif com-video-to-gif

**Comment by cedric05** [comment]
is this pr under consideration? or left out?

**Comment by joaomoreno** [comment]
Under consideration.

**Comment by cedric05** [comment]
@joaomoreno i think i kinda entered limbo state.

**Comment by joaomoreno** [comment]
Great fix, sorry for the delay, thanks! :beers:

**Pull request merged**
