### PR TITLE
Match word links without the cwd if the cwd resolved text wasn't found

### LINKED ISSUE #152275: Single search match not handled correctly when a command uses `cd <path> &&`
Expected behavior here is that activating the link should open the file without the quickpick because there is only a single match, but even if there were 2 matches the end segment matches exactly so it should be covered if the other match does not _end with_ the end of the path. Might be caused by the line/col number or separators?

image

This ends up happening regardless of whether shell integration is disabled when `yarn smoketest` is run in vscode because the cwd of the inner process is `test/smoke` via the `cd` here:

https://github.com/microsoft/vscode/blob/18408b909006d18e2e08e8b1c50d20b31854b644/package.json#L38

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #152275

### CODE REVIEW

**Review by meganrogge — CHANGES_REQUESTED** [review]
Accidental merge issue w announceSearchResults

**Comment by Tyriar** [comment]
@meganrogge not sure what you mean?

**Comment by meganrogge** [comment]
Weird the diff was showing changes before that it's not anymore after you merged main.

**Review by meganrogge — APPROVED** [review]

**Comment by Dopeman31** [comment]
Fix

**Pull request merged**
