### PR TITLE
Debug: Allow click to show getter property value

### PR DESCRIPTION
**Pull request by f111fei**
When I use chrome debugger, I find variables can't show the getter property value.  The PR to resolve the problem.

Before:
qq 20160729214752

After:

## How to implemented

Add a protocal command called `getVariable` to `DebugProtocol`. the command can get the variable`s value. See:
https://github.com/f111fei/vscode/blob/70007f9c238c89c5a3e8508b3ed8359f164312d5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L541

Add a property called `unsolved` to `DebugProtocol.Variable` .  If `unsolved` is true, the variable need use `getVariable` function to get correct value. See:
https://github.com/f111fei/vscode/blob/70007f9c238c89c5a3e8508b3ed8359f164312d5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L957

When click the unsolved variable, the `debugService.getVariable` to update the variable and render.

Last, implement the `getVariable` command in `vscode-chrome-debug-core`. I push the PR about the implement, See: https://github.com/Microsoft/vscode-chrome-debug-core/pull/75

Moreover, we need to update `debugProtocol.d.ts`. See:  https://github.com/Microsoft/vscode-debugadapter-node/pull/49

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for the PR!

We always try to keep the vscode debug code language agnostic - we are not trying to add things that only work for adapters of certain types. This has worked quite well in the past and we try to continue this practice. As far as I see this only profits the chrome debugger.

However this PR contains additions to the debug protocol which is carefully designed by @weinand. Due to that I am assigning this PR to him, if he approves of the protocol additions I can reveiw the VSCode ux code. Though I have raised my concern above.

**Comment by f111fei** [comment]
I think the node debugger will also profits.

**Comment by weinand** [comment]
@f111fei no, the node-debugger does not profit from this change because node-debug automatically resolves getters in the debug adapter. So node-debug does not suffer from this problem. The problem you are trying to fix is a problem of the chrome debugger extension alone.

In addition we think that having to click on getters manually is a bit laborious.

I'm very sorry that we cannot accept this PR because we do not plan to extend the debug protocol.

I suggest to always create an issue and discuss the problem with the community first before creating a PR.

**Comment by f111fei** [comment]
@weinand 
So I will open an issue to discuss how to resolve the problem.
See https://github.com/Microsoft/vscode-chrome-debug-core/issues/77

**Comment by weinand** [comment]
@f111fei thanks, that's a good approach.

**Pull request closed without merging**
