### PR TITLE
remote: allow _ in ext host resolvedauthority

### PR DESCRIPTION
**Pull request by connor4312**
Cherry pick of https://github.com/microsoft/vscode/pull/168649

### CODE REVIEW

**Review by aeschli — CHANGES_REQUESTED** [review]
[src/vs/server/node/serverConnectionToken.ts](https://github.com/microsoft/vscode/blob/d7e58d3776f0b0a9b7af44b49a1f514daa3bee24/src/vs/server/node/serverConnectionToken.ts#L96) has the same string

**Comment by aeschli** [comment]
and
https://github.com/microsoft/vscode/blob/fa2af3d4f9f569d491f22d15cf8f319ee1a7f25b/src/vs/server/node/serverEnvironmentService.ts#L116

**Comment by aeschli** [comment]
The safer fix would be to not use `_` in the connection token....

**Comment by aeschli** [comment]
FYI @alexdima

**Comment by connor4312** [comment]
> The safer fix would be to not use _ in the connection token....

This requires a new release of both the CLI and extension. Which we could do, but that is a more complex change versus this one character regex change.

It looks like the remaining places are just in comments (and an error string). I can put in a PR to stable to update those, but I don't think they need to be in the recovery.

**Comment by aeschli** [comment]
Adding @alexdima as he knows all about what happens with the connection token. I believe all is fine, but I also see it is fed into the sign service.
@connor4312 I still suggest to update the remaining comments and error output for consistency. I'll push a commit

**Comment by connor4312** [comment]
I've also made an alternative PR here: https://github.com/microsoft/vscode/pull/168900

**Comment by aeschli** [comment]
Thanks a lot @connor4312 !

**Comment by alexdima** [comment]
We've discussed this in the standup and we find this solution easier than the one involving a protocol version change (https://github.com/microsoft/vscode/pull/168900)

**Review by aeschli — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Pull request merged**
