### PR TITLE
Bracket support for #if and #endif in cpp

### LINKED ISSUE #159586: C/C++ Preprocessor #if and #endif should have distinct colors just like brackets
Noticed that SourcePawn extension has this feature, it should be enabled for built-in C/C++ preprocessor #if and #endif, just like for brackets [] () {}

SourcePawn:
image

C/C++:
image

Could probably be done for other languages that have keywords rather than braces for opening and closing a block, e.g. Lua's if-then-end:
image

### PR DESCRIPTION
**Pull request by OtherHorizon**

### CODE REVIEW

**Review by ProKashif — APPROVED** [review]

**Review by hediet — APPROVED** [review]

**Comment by aeschli** [comment]
Calling `#if` and `#elseif` 'brackets' is a stretch and I don't think we do this in other languages...

**Comment by hediet** [comment]
@aeschli this is about `#if` and `#endif` (not `#elseif`). There are languages that use `begin` and `end` or even `\begin` and `\end` as bracket pairs.

What are your concerns about this new "bracket" pair?

**Comment by aeschli** [comment]
Sorry, yes, of course I meant `endif`.

Just worrying of unexpected issues and follow up work as we don't use brackets in that way yet. But I see in our source code we have examples and tests for keywords as brackets. Your call, @hediet

I assume https://github.com/microsoft/vscode/issues/159586 is the motivating issue.

**Review by aeschli — APPROVED** [review]

**Comment by jlelong** [comment]
Trailing commas are not allowed in JSON objects. With this PR, the `c++` language configuration file cannot read with standard JSON parser anymore.

**Comment by sean-mcmanus** [comment]
@jlelong It's fixed with https://github.com/microsoft/vscode/pull/161192 .

**Pull request merged**
