### PR TITLE
Draft: Allow to change the font, font size and line height of the sidebar.

### PR DESCRIPTION
**Pull request by saighost**
Add configuration of workbench for font.
#519

### CODE REVIEW

**Comment by MoOx** [comment]
Does this PR change the default values?
Could you add screenshots if anything is visible?

**Review by MoOx — APPROVED** [review]
I am new to vscode codebase, but seems fine.

**Comment by MoOx** [comment]
@lowkey702 I think we got it.

**Comment by MoOx** [comment]
@lowkey702 Please stop being stupid. You are not helping here, just make too much noize. One approval is clearly enough.

**Comment by saighost** [comment]
> Could you add screenshots if anything is visible?

I set default values of font font-family form shell.css, and remove fixed font size or use 'inherit' Instead in css file of workbench.

I will add some screenshots here later.

**Comment by kaypon** [comment]
Patiently waiting on this PR to go through! Do we have any screenshots?

- Thanks for all the hard work put into this PR!

**Comment by aioue** [comment]
@saighost do you think you might have time to resolve the latest conflicts, please?

The bulk of the changes are in `workbench.ts` which @bpasero may be able to comment-on/approve.

**Comment by bpasero** [comment]
@saighost I appreciate the effort, but before you start fixing merge conflicts and/or catching up, can I ask how this PR solves the issue of elements in the UI requiring more space with a larger font compared to what we have today?

Just to give an example: today we hardcode the height of tree/list items to be 22px in height, e.g. for search view:

image

There is probably a ton more assumptions also in CSS where we set a height/width without checking for the actual font being used. This to me is the biggest challenge in providing a setting for variable font family/sizes.

**Comment by jonbp** [comment]
@saighost At a basic level I think we'd all love the ability to set a different UI font face.

I understand that tweaking line-heights/font-sizes would be too many moving parts to think about, also this is probably already catered for with the zoom level.

In my own personal use case i don't really like the Ubuntu font on linux as the UI font, i much prefer Roboto and would like the ability to add this into the mix.

**Comment by bpasero** [comment]
@saighost how can we provide a setting for the font without solving the issue of hardcoded dimensions throughout the workbench? That only asks for trouble imho.

**Comment by saighost** [comment]
Sorry, for so late. I have a long holiday at Spring Festival time.
In this PR, I remove lots of hardcode in css and .ts files.
Most I use 'inherit' Instead hardcode in css file of workbench, but not everywhere.
I can't  make it too complex to use, so only divided them into two categories in workbench.
And I try to learn form 'Theme' but It looks like very complicated and not applicable for font size. 
To solving the issue of hardcoded:
Need a 'FontProvider' for layout and height should be calculated in layout for most cases.
Lots of interface should refactoring, many view need to fix.
I wrote plugin for eclipse, so I am used to using interface of JFace and SWT. 
CSS is out of my domain.
So I push wrote this PR, only work with title and some content parts in sidebar, but I can't give you a complete and compatible font system for workbench.There is a long way to go.

ps: I can't believe there are so many hardcodes in your code.

**Comment by saighost** [comment]
BTW, most users in issues want to change sidebar, not all of workbench.
@bpasero I don't want to mark you trouble. You can close it.

**Comment by bpasero** [comment]
I am fine leaving this open but I want to avoid that people think this is the full solution. Can you maybe turn this PR into a "Draft PR"?

**Comment by saighost** [comment]
I tried but not so many time for it.

**Comment by bpasero** [comment]
This is stale, has merge conflicts and a draft for the reasons outlined. Feel free to fix the merge conflicts and open a new PR as draft. Closing.

**Comment by shirshak55** [comment]
hmm we are not getting custom font for sidebar in vscode now :(

**Pull request closed without merging**
