### PR TITLE
dismiss context menus on window focus lost

### LINKED ISSUE #57658: Custom context menu location on activity bar is not consistent if sidebar on the right
If you right click on the explorer icon for the context menu, the menu shows at a different location if the sidebar is on the right:

image

image

I would expect the same location in both cases (below the icon, over the activity bar)

### LINKED ISSUE #57736: Windows: custom context menu does not close when window loses focus
- OS Version: Windows 10

Steps to Reproduce:

1. open 2 windows of VSCode side by side
2. right click to open context menu in one
3. right click in the other window

=> 🐛 context menu in first window does not close

### PR DESCRIPTION
**Pull request by sbatten**
fixes #57736

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
OK in principle, one thing to keep in mind is that a window blur event can fire in more situations, even if the window is still focused:
* clicking into dev tools
* clicking into a webview component (e.g. markdown preview)

If you want the native method, use `IWindowService#onDidChangeFocus()`. This would need a "simple" implementation for the standalone editor though.

**Review by joaomoreno — APPROVED** [review]
Looks good.

Pro tip: Instead of `addDisposableListener`, there's also the `domEvent` util in `vs/base/browser/event` which lets you use our event class. :sunglasses:

**Comment by sbatten** [comment]
@joaomoreno I changed it so I would know how it worked. Any reason for one over the other? Are we trending toward one in our codebase?

**Comment by joaomoreno** [comment]
It's up to personal preference. :+1: 

PS: `menuDisposables` should be the third argument here, not the second:

```
domEvent(window, EventType.BLUR)(() => { this.contextViewService.hideContextView(true); }, menuDisposables);
```

**Pull request merged**
