### PR TITLE
Prioritize PATH executables over local directories in terminals

### LINKED ISSUE #79346: The preLaunchTask 'build' terminated with exit code -2.
In VSCode (not Insiders) I am seeing this error in a dialog box when hitting F5 to compile in Ubuntu:

The preLaunchTask 'build' terminated with exit code -2.

In the terminal window itself, this error is reported:

The terminal shell path "dotnet" is a directory

Version: 1.37.1
Commit: f06011a
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

This error is new, happens on all projects on this machine, and the errors began after installing updates.

BUT PLEASE NOTE: I have been aware that my dotnet folder is itself named dotnet -- not the (standard, I believe?) name .dotnet with a leading period. This is unorthodox, and due to the error message I was seeing, I decided now was a good time to align my machine with the norm. I renamed my folder to .dotnet and adjusted as necessary stuff in my .bashrc file.

Rebooted, and error is gone.

That said, I do think this is a bug in the latest version of VSCode. In older versions I did not have this problem.

### LINKED ISSUE #83772: Terminal executable does not check path if a dir of the same name exists at the cwd
Context https://github.com/OmniSharp/omnisharp-vscode/pull/3372#issuecomment-548450832

Repro:

1. Have `dotnet` in `$PATH`
2. Open a folder
3. Create a `dotnet` folder inside the root
4. Set the terminal shell as `dotnet`

### LINKED ISSUE #106661: Find full path for executables for `process` task on OSs other than Windows
- VSCode Version: 1.49.0
- OS Version: Debian GNU/Linux 10 (x64 5.7.0-0.bpo.2-amd64)

Steps to Reproduce:

1. Install VSCode and C# Omnisharp extension.
2. Install dotnet SDK.
3. Create a console app project in any folder ("dotnet new console" command).
4. Open this folder in VSCode.
5. Wait for editor to download required components.
6. Select "Run - Start Debugging" or press F5. Agree to add required assets.
7.  Select "Run - Start Debugging" or press F5 again.

Does this issue occur when all extensions are disabled?: Yes

Screenshot from 2020-09-14 16-58-12

I've started to get this error some time ago. When I'm trying to run any task I get a message:
"The terminal process failed to launch: Path to shell executable "dotnet" is not a file of a symlink."

I tried uninstalling the editor and .Net SDK and installing it again. Also tried to replace the symlink "/usr/bin/dotnet" manually, but problem remains. 

This problem only appears when trying to run some tasks from menu/button/key. If I type the command manually it works Ok.

This is also mentioned here:
https://stackoverflow.com/questions/63088161/visual-studio-code-c-sharp-debugging-problem-the-terminal-process-failed-to-lau
The OP's workaround is to replace the command "dotnet" with "/usr/bin/dotnet" in "tasks.json" file (worked for me too).

### PR DESCRIPTION
**Pull request by tobil4sk**
Right now, when validating an executable, the check to ensure the path is a file and not a directory comes before the check for executables in PATH. This means that a sub directory of the current process's PWD will take priority over an executable in PATH, and so an error will be given saying that the specified path "is not a file or a symlink", even if there is a valid executable in PATH which was intended to be executed.

This fix reorders the checks to ensure that the executable in PATH takes priority over a sub directory of the local PWD.

Fixes #106661 (or rather the root issue behind it, which was misdiagnosed in the thread. The error was not happening because the OS couldn't find `dotnet` in PATH, but because the `dotnet` folder in the home directory (which is usually set as the PWD when starting VSCode from an application menu) took priority over the `dotnet` executable that would be found in PATH.

To test that this issue is fixed:
1. Have an executable available from $PATH, such as `python`
2. Install an extension that has a task which runs an executable ([Here is a minimal sample extension which runs `python`](https://github.com/microsoft/vscode/files/9387119/Archive.zip))
3. Start VSCode by running `code .` in a directory which contains a sub directory with the same name as the executable (in this case, `python`)
4. Run the task which runs the executable (called `test-task` in the sample extension I have uploaded)
5. Validate that the python interactive cli starts, and there is no `The terminal process failed to launch: Path to shell executable "python" is not a file or a symlink.` error.

Also properly fixes #79346, which is the same issue.

Also fixes #83772

The steps to test this issue are the same as specified in the original issue (which can be replaced with any executable):
> 1. Have dotnet in $PATH
> 2. Open a folder
> 3. Create a dotnet folder inside the root
> 4. Set the terminal shell as dotnet

And then of course now verify that the terminal opens and there is no: `The terminal process failed to launch: Path to shell executable "dotnet" is not a file or a symlink.` error popup.

### CODE REVIEW

**Comment by tobil4sk** [comment]
I think there is still one potential issue with this solution, which is that findExecutable itself can sometimes return the path to a directory. In this case, the error won't be caught before the terminal launches. I'll push another commit to fix this.

**Comment by tobil4sk** [comment]
Actually, that is not an issue with this solution, and is an unrelated problem which is already present on the main branch. I'll try to handle that in a separate issue/PR.

**Comment by Tyriar** [comment]
I see this when I try open a terminal:

```
  ERR EACCES: permission denied, stat 'C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe': Error: EACCES: permission denied, stat 'C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe'
```

Pushed a fix to cover that exception only and throw for others (which we can fix if they're hit)

**Review by Tyriar — APPROVED** [review]

**Comment by Tyriar** [comment]
@meganrogge second review please

**Review by meganrogge — APPROVED** [review]

**Comment by tobil4sk** [comment]
Great stuff, thanks for your time!

**Pull request merged**
