### PR TITLE
Retry request to extension gallery for raw gallery extensions

### PR DESCRIPTION
**Pull request by joyceerhl**
This change might unblock @alexr00 in vscode.dev since this particular request fails on a daily basis for her.

### CODE REVIEW

**Comment by sandy081** [comment]
@joyceerhl I do not understand the reasoning for re-try. I think adding a re-try to request service is not correct, we do not want a base feature to retry if fails by itself. It shall be the caller of the service. 

Before adding the re-try, may I understand the issue here?

**Comment by joyceerhl** [comment]
AlexR sometimes sees the explorer in vscode.dev/github fail to load entirely, and this is in the log when that happens 

```
log.ts:324   ERR RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery Error: XHR failed
```

but a page reload usually fixes things so it seems like a transient error that we should be handling with retry logic.

This PR doesn't retry requests by itself, it just adds an option so that callers of the request service can easily add retries by passing an option, but if no retries option is passed it will attempt the request just once. I added it as an option to the base request service because we may want additional retry logic elsewhere to improve the reliability of the VS Code for the Web experience, but this is a starting point for now.

**Comment by sandy081** [comment]
I am not convinced about adding retry to request service. IMO It's same as adding retry to browser fetch api. We shall also not retry always, sometimes the error is indeed valid. 

Regarding the error that is seen, there seems to be a real error some where which needs to be diagnosed and addressed. I see that our logs are not giving enough info about this error. Can we please ask to provide dev tools console log and also network requests trace to get more information and understand?

**Comment by joyceerhl** [comment]
I copied the logs to https://github.com/microsoft/vscode/issues/164467

**Comment by sandy081** [comment]
Closing this PR as the associated issue is redundant now

**Pull request closed without merging**
