### PR TITLE
Simplify start debug command handler

### LINKED ISSUE #64858: Cleanup debug.contribution startDebugHandler
Somehow I missed the change in the debug.contribution.ts and only now found it out.
What I do not udnerstand is why we need all this code? 
I think this handler should be removed and the action should be called like it was done previously.

Code pointer: https://github.com/Microsoft/vscode/blob/89a775140e619970b13e2b23f53597a3315b80e9/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L137

It would be great if we could tackle this in December.
Thanks

### PR DESCRIPTION
**Pull request by RMacfarlane**
Fixes https://github.com/Microsoft/vscode/issues/64858

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for this PR, I am currently burried in explorer refactoring.
I will check it out in the next couple of days

**Comment by isidorn** [comment]
@RMacfarlane thanks again for the PR. I have cleaned this up a bit. Can you please verify once you find the time that your scenario still works (it should).

**Comment by RMacfarlane** [comment]
Thanks, verified!

**Comment by isidorn** [comment]
Thanks!

**Pull request merged**
