### PR TITLE
typo: fix to misspellings of 'current'

### PR DESCRIPTION
**Pull request by rockett-m**
simple typo fix
fixed 'curruentActiveMimeType' to 'currentActiveMimeType'
fixed 'concurent' to 'concurrent'

### CODE REVIEW

**Comment by rockett-m** [comment]
@microsoft-github-policy-service agree

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/How-to-Contribute#spell-check-errors

**Comment by rockett-m** [comment]
@gjsjohnmurray do you recommend skipping the comment fix and separating the remaining two fixes into separate issues/PRs?

**Comment by mjbvz** [comment]
Closing since I don't think there's enough benefit

**Pull request closed without merging**
