### PR TITLE
Allows for filtering by file extension in Change Language Mode

### LINKED ISSUE #106886: Change Language Mode drop-down should allow filtering by file extension
In the [Change Language Mode drop-down](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file), it would be nice if we could filter by extension. e.g. at the moment for a `.jsx` file, typing `jsx` returns nothing. I have to start typing `javascriptreact`:

select-language-type-vscode

For TypeScript, `ts` gives you:

select-language-type-vscode-ts

Which doesn't seem intuitive. I'd expected the same results, but taking the extension into account and ordering them:

```
TypeScript > TypeScript React > JSON with Comments > CSS (Styled Components
```

### PR DESCRIPTION
**Pull request by incakoala**
This PR fixes #106886

Adding file extensions to a language's description allows a user to filter for a specific extension name (e.g. `jsx` will return `JavaScript React`)

Screen Shot 2020-10-01 at 3 10 15 PM
Screen Shot 2020-10-01 at 5 14 46 PM

(GHC's OSD)

### CODE REVIEW

**Comment by Love0ne** [comment]
Thank you for being diligent. I have had some personal set backs and don't
have the data to explore more options. I'm broke and trying to find a
job,if you know anyone hiring let me know. Thank you for your time. Maybe
next year.

**Comment by bpasero** [comment]
Thanks for the PR. While this solves the issue I wonder if this visually is too hectic now:

image

I wonder if a better approach would be to:
* allow to match on the file extensions when typed
* not show the extensions in the UI

In other words, as a user I can find a language by typing e.g. "hpp" and C++ appears but we do not show the extensions in the UI, we just allow to find it:

image

@misolori @aeschli maybe you have more UI ideas.

**Comment by misolori** [comment]
I had the same thought about it being too busy. Could we add meta data to the quick pick list? Seems like that would be beneficial as we do that in the extensions and settings search (but those are "queries").

**Comment by bpasero** [comment]
@misolori to clarify what you mean: this metadata would be searchable but would not appear in the UI, right?

**Comment by misolori** [comment]
@bpasero correct

**Comment by bpasero** [comment]
@incakoala would you feel comfortable doing such a change? Maybe @tomerstav could also help out, given the work on https://github.com/microsoft/vscode/pull/107089

Fundamentally I think it requires some changes to the `IQuickPick` API to add text that is searchable when filtering but does not appear in the UI. Maybe @chrmarti as widget owner could comment if something like this already exists.

**Comment by tomerstav** [comment]
> @incakoala would you feel comfortable doing such a change? Maybe @tomerstav could also help out, given the work on #107089
> 
> Fundamentally I think it requires some changes to the `IQuickPick` API to add text that is searchable when filtering but does not appear in the UI. Maybe @chrmarti as widget owner could comment if something like this already exists.

I'm happy to help out. @incakoala please take charge and let me know where you need help

**Comment by bpasero** [comment]
@tomerstav @incakoala some code pointers to help: 
* I suggest to add a new `meta` field to [`IQuickPickItem`](https://github.com/microsoft/vscode/blob/b50a5846d55a20e231c8e74187447fdd9c952863/src/vs/base/parts/quickinput/common/quickInput.ts#L20-L20)
* this new field should appear as `saneMeta` in the [`ListElement`](https://github.com/microsoft/vscode/blob/ef169aecd7912897d5fd716243bf672109dca3b8/src/vs/base/parts/quickinput/browser/quickInputList.ts#L434-L434)
* we do not display this to the user but add it to the filter logic [here](https://github.com/microsoft/vscode/blob/ef169aecd7912897d5fd716243bf672109dca3b8/src/vs/base/parts/quickinput/browser/quickInputList.ts#L610-L610)

**Comment by tomerstav** [comment]
@incakoala Please let me know if you are still interested or if I should work on this myself and create a new pr?

**Comment by incakoala** [comment]
@tomerstav Yes I'd be interested in working on this -- sorry for the late response! Will let you know when I need help.   @bpasero thanks for the suggestions and pointers!

**Comment by bpasero** [comment]
Closing as stale, please open a new PR if you are still planning to work on this.

**Pull request closed without merging**
