### PR TITLE
Remove PPromise

### PR DESCRIPTION
**Pull request by joaomoreno**
This PR aims to remove the usage of progress of WinJS Promises.

The first commit removes the type definitions for progress, so this branch will remain broken until we remove all its usage.

- [x] Remove PPromise types
- [x] Remove usage of PPromise
  - [x] Theme picker @joaomoreno
  - [x] IPC events @joaomoreno
  - [x] Search IPC #53536 @joaomoreno
  - [x] QuickInput @joaomoreno 
  - [x] QuickOpenController @joaomoreno 
  - [x] File Watcher #53556 #53584 @joaomoreno 
  - [x] IPC (when all above are fixed) @joaomoreno
  - [x] Tasks #53875 @dbaeumer
  - [x] Search @roblourens

### CODE REVIEW

**Comment by joaomoreno** [comment]
Down to 38 errors only... I've updated the first comment with checkboxes on the areas left to adopt. Please go through your area and replace usages of promise progress with simple callbacks.

**Comment by joaomoreno** [comment]
Removed Search IPC PPromise usage, awaiting review: #53536 cc @roblourens  @chrmarti

**Comment by jens1o** [comment]
What will be the advantage of this?

**Comment by joaomoreno** [comment]
@jens1o This is just engineering debt. More details: https://github.com/Microsoft/vscode/issues/53526

**Comment by connorshea** [comment]
so is removing it from search done now 🤔

**Comment by roblourens** [comment]
image

**Comment by joaomoreno** [comment]
@roblourens  This is the last PPromise usage: 

https://github.com/Microsoft/vscode/blob/remove-ppromise/src/vs/workbench/api/node/extHostSearch.fileIndex.ts#L419

Is it as simple as removing `, onBatch` from that `then` call?

**Comment by roblourens** [comment]
Oops, yes done

**Comment by joaomoreno** [comment]
Thanks for all the help guys! :fireworks:

**Pull request merged**
