### PR TITLE
Added new command to switch between windows

### PR DESCRIPTION
**Pull request by heycalmdown**
Adds support to switch between windows.

> Switch Window

shows current opened windows in the quick open dialog. Then selecting one shows the window.

It is very needed while making service with TypeScript on the Micro Service Architecture.

### CODE REVIEW

**Comment by bpasero** [comment]
@heycalmdown thanks. it does not really work though when a window has no workspace associated (= empty window):

image

Also I wonder if this functionality is not already present in the "Open Recent" picker (from the command palette):

image

The difference is that the "open recent" picker contains a history of all folders opened in the past, but the ones that are opened in multiple windows should be to the top.

**Comment by heycalmdown** [comment]
Oh, the behavior of "Window" menu on Mac was exactly I want to get here with full support of vscode such as picking dialog or shortcut thing.

And surely I have to fix the empty line problem. I will eliminate them as my use-case, what about you thought?

The goal of these behaviors is relevant to my use-case working on Micro-Service Architecture.

I have almost forty microservices in my depot. I don't really launch for every services at once, but it easily reaches over ten.
Every services - which I called it *-island because it is isolated and self sufficient - are a proper Typescript project which has its own `tsconfig.json` and similar directory structure, so it has very same files on it. It looks like - 

screen shot 2016-09-06 at 5 19 00 pm

I prefer this way -

screen shot 2016-09-06 at 5 29 57 pm

About the "Open Recent", it works similarly. But it is bounded to 10 and includes workspaces not opened yet. This will be useful as very similar with "Window" on Mac as vscode integrated.

**Comment by heycalmdown** [comment]
This feature has to be named more "Switch Workspaces" not "Switch Windows".

**Comment by bpasero** [comment]
@heycalmdown let me know when I should review again

**Comment by heycalmdown** [comment]
Oh no. I just messed the history during merge upstream. :cry:
What should I do @bpasero? Do you prefer to make another clean PR?

**Comment by heycalmdown** [comment]
I was confused about which is the best practice making new actions, but https://github.com/Microsoft/vscode/pull/11493/commits/06538335c010afd03ad29c5c6c0dbb862dc537bc makes things more clearer. Thanks.

**Comment by bpasero** [comment]
@heycalmdown yes please a clean PR 👍

**Comment by heycalmdown** [comment]
@bpasero check the #11630

**Comment by bpasero** [comment]
Thanks.

**Pull request closed without merging**
