### PR TITLE
Improve issue template

### PR DESCRIPTION
**Pull request by ryanmcnamara**
Makes it easier to add items to the numbered list

### CODE REVIEW

**Review by invliD — APPROVED** [review]

**Comment by roblourens** [comment]
Github will show the correct numbers when it renders the list as markdown, so I prefer to just use `1. ... 1. ...` etc so the author doesn't have to manage item numbers themselves.

**Comment by egamma** [comment]
@roblourens 
>Github will show the correct numbers when it renders the list as markdown, so I prefer to just use  1. ... 1. 

This is what the PR does, we had 1.  ... 2. and PR changes this to 1. ... 1. so is your comment argues for accepting the PR or did you have something else in mind?

**Comment by roblourens** [comment]
Apologies, I read it backwards...

**Comment by michelkaporin** [comment]
As a author I find it uncomfortable to see 1. ... 1. as I am always tempted to change it to the proper numbering, even knowing that GitHub will manage it for me.

**Comment by alexandrudima** [comment]
I had the same reaction as @michelkaporin

**Comment by roblourens** [comment]
I like this style but the issue template definitely shouldn't confuse anyone, so maybe we should revert it.

**Comment by roblourens** [comment]
I've reverted it.

**Pull request merged**
