### PR TITLE
Stop the cursor from jumping when changing prefix in QuickAccess

### LINKED ISSUE #162914: When editing a query inside the quick access box, the cursor jumps to EOL if the edit changes the prefix to another search mode.
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Mac OS

Steps to Reproduce:

1. Open file search with CMD + P
2. Enter foo:bar (for instance copy and pasted from somewhere)
3. Go to the start of the line and delete 'foo' using the delete key
4. Once the ':' is at the front of the string, the mode switches to 'go to line' but this also causes the cursor to move to the end of the line making it hard to remove the prefix as intended. This happens for instance if you paste a URL and where planning to remove the http:// prefix.

https://user-images.githubusercontent.com/101328101/194491454-fe23d6ee-7f30-4b79-86b3-1ca5dd635996.mov

### PR DESCRIPTION
**Pull request by a-stewart**
This fixes #162914

When changing the prefix, we should check the cursor position on the currently visible picker (if one exists), and if so we should set this as the position for the new picker.

This requires a few changes to create a getter method for the selection, which doesn't currently exist.

Current (broken):
broken

This PR:
fixed

### CODE REVIEW

**Comment by a-stewart** [comment]
Marking as ready for review as we have had this change on prod in our internal fork for 2 weeks with no reported issues.

**Comment by a-stewart** [comment]
@TylerLeonhardt - friendly ping.

**Review by TylerLeonhardt — APPROVED** [review]
Very clean. I like this! Thanks for fixing!

**Review by chrmarti — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Hi @a-stewart. Unfortunately,I had to revert this PR as it caused this issue: https://github.com/microsoft/vscode/issues/204572

If you can come up with a solution that fixes the existing issue and doesn't cause that issue, I would accept a PR

**Pull request merged**
