### PR TITLE
Initial implementation of quick-fix support for typescript

### PR DESCRIPTION
**Pull request by kisstkondoros**
Code is heavily based on Atom-TypeScript's quick fix implementation
https://github.com/TypeStrong/atom-typescript/tree/master/lib/main/lang

It still needs a lot of work ...
image
image
image

### CODE REVIEW

**Comment by Tyriar** [comment]
I just created a feature request for one of these the other day https://github.com/Microsoft/vscode/issues/7073

**Comment by bpasero** [comment]
👍 for a way to get imports resolved via quick fix.

**Comment by dbaeumer** [comment]
@kisstkondoros thanks for the pull request. Although I like the features provided they don't fit architecturally how VS Code integrated with TypeScript. All TS smartness in VS Code is running in a separate process (the tsserver) maintained in this git repository (https://github.com/Microsoft/TypeScript).

Your pull request basically creates another compiler instance in the extension host, builds AST and resolves symbols. This doubles the memory consumption and in the worst case makes the extension host unresponsive which might impact other extensions. That is why all language smartness (even linters like eslint, tslint, ...) are run in a language server in its own process.

The best way to integrate quick fix into VS Code is to integrate it into the tsserver directly. VS Code basically consumes the tsserver as a binary. We don't own it and changes to the tsserver can't occur in the VS Code git repository. The tsserver is maintained here: https://github.com/Microsoft/TypeScript

Unless I don't miss anything I need to reject the PR and ask you to create a corresponding PR against the https://github.com/Microsoft/TypeScript repository.

**Comment by kisstkondoros** [comment]
@dbaeumer 
Hi, thanks for the detailed answer!

I thought this might be a temporary solution until https://github.com/Microsoft/TypeScript/issues/6943 is resolved. It is on the roadmap for TS 2.1 https://github.com/Microsoft/TypeScript/wiki/Roadmap#20

I'm a bit sad, but I understand the reasons behind.
I'll close the PR.

**Comment by dbaeumer** [comment]
@kisstkondoros we should not wait until TS 2.1. I would like to encourage you to work on a PR against the TS server. I do the same if I need features in there and I volunteer to get you started if you want. However the final answer if the PR gets accepted depends on the TS team. So why don't you ask in Microsoft/TypeScript#6943 if they would accept a PR?

**Comment by kisstkondoros** [comment]
@dbaeumer I'll certainly check what can I do in TS core with the topic (after work) :smile:

**Comment by kisstkondoros** [comment]
@dbaeumer finally I've reached a state which can push this forward (I hope) and published it in the mentioned post. Thank you for the motivation!

**Comment by dbaeumer** [comment]
@kisstkondoros great to hear that you are still working on this!

**Comment by WanderWang** [comment]
TypeScript team has finished it in TS2.1 right now , anything update ?

**Comment by dbaeumer** [comment]
We started to look into adapting TS 2.1 for VS Code 1.8

**Pull request closed without merging**
