### PR TITLE
fix psreadline not working with shell integration

### LINKED ISSUE #142161: enableShellIntegration breaks PowerShell PSReadLine module in terminal
- VS Code Version: 1.64.0
- OS Version: Windows 10 x64 21H1 (Build 19043)

## Steps to Reproduce:

1. Add `"terminal.integrated.enableShellIntegration": true` to `settings.json`
2. Restart the shell (pwsh v7.2)

## Previous Behavior

My existing PowerShell is setup with `PSReadLine` module 

```ps
// profile.ps1
// omitted
Import-Module PSReadLine
Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption -EditMode Windows
// omitted
```

It would look like the following (with listview of history)

image

## New behavior

When `enableShellIntegration` is configured/enabled and restarted the shell, this is how it looks like

image

The history does not show up

## Note

I do have other modules installed such as `Oh-My-Posh` and from the looks of it, it seems to be working fine since the theme is showing correctly as before

Not sure if any other modules are affected as well

### PR DESCRIPTION
**Pull request by LuanVSO**
This PR fixes #142161

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Thanks again 👍

**Comment by Tyriar** [comment]
This ended up causing the prompt to continually print, had to revert:
Recording 2022-02-04 at 13 15 25 (1)

**Comment by LuanVSO** [comment]
> This ended up causing the prompt to continually print, had to revert:
> Recording 2022-02-04 at 13 15 25 (1)
> 

how?

**Comment by Tyriar** [comment]
That's what happens with no changes in my profile on Windows and mac

**Comment by LuanVSO** [comment]
oh i know, for psreadline 2.1 it should be
```
$tmp = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext) 
```
i have a better idea of how to do this

**Comment by LuanVSO** [comment]
@Tyriar github.dev kinda broke so heres the new thing
image
```powershell
$__VSCodeOriginalPSConsoleHostReadLine = $function:PSConsoleHostReadLine

# TODO: Gracefully fallback when PSReadLine is not loaded
function Global:PSConsoleHostReadLine {
	$tmp = $__VSCodeOriginalPSConsoleHostReadLine.Invoke()
	# Write command executed sequence directly to Console to avoid the new line from Write-Host
	[Console]::Write("`e]133;C`a")
	$tmp
}
```

**Comment by Tyriar** [comment]
Works, thanks!

**Pull request merged**
