### PR TITLE
44146 automatically show problems panel

### PR DESCRIPTION
**Pull request by sebastianwitthus**
[Issue 44146](https://github.com/Microsoft/vscode/issues/44146):

> Feature Request
> 
> When problems are matched while running a task, I'd like the Problems panel to automatically appear. This is especially useful if I have presentation.reveal set to never.

This branch adds the option `revealProblem`, which controls whether a task should show the problems panel. Oriented on `reveal`, it offers `always`, `never` and `onProblem`.
The `reveal: silent` option already triggers the showing of the terminal when problems of MarkerSeverity `Error` are encountered. (see `terminalTaskSystem.ts` ) The hints have been updated to reflect this.

### CODE REVIEW

**Comment by sebastianwitthus** [comment]
`alexr00`: To avoid excessive DOM manipulation and/or confusing DOM handling, I no longer fire events for each `problemFound` (as my first suggestion did) but instead use the end-of-background-processing and end-of-task hooks already provided by the tasks.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thanks for the PR! There is a case that doesn't appear to be handled correctly though:
````
			"presentation": {
				"reveal": "always",
				"revealProblem": "onProblem"
			},
````
As discussed [here](https://github.com/Microsoft/vscode/issues/44146#issuecomment-476186124) this should cause the terminal to show, then the probelm panel to show if a problem occurs.

**Comment by sebastianwitthus** [comment]
I'll look into it

**Comment by sebastianwitthus** [comment]
@alexr00 I have just confirmed correct behaviour for

```
"presentation": {
  "reveal": "always",
  "revealProblem": "onProblem"
},
```

It works with both `WatchingProblemCollector` and `StartStopProblemCollector` using `tsc -w` and `tsc`, respectively. Have you triggered the `WatchingProblemCollector` by saving a watched file?

**Review by alexr00 — APPROVED** [review]
Looks good!

**Comment by alexr00** [comment]
Thanks for checking that scenario. I was hitting a different issue!

**Pull request merged**
