### PR TITLE
Improve when $LANG is set and expand the number of languages supported

### LINKED ISSUE #80072: the letter 'ñ' cannot be written in the vscode terminal
I write in the terminal 'manana', but I can't write 'mañana', it doesn't allow it. If I try to insert the letter 'ñ' in the word 'manana' it is not allowed either.
manana
manana
mañana
mañana

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #80072

### CODE REVIEW

**Comment by go2sh** [comment]
@Tyriar Is it possible to add a reference to the tasks.json documentation. I searched nearly two hours, why my `LANG=""` got overwritten with `LANG="de_DE.UTF-8"`. Its quite annoying as I have to force the locale to English to get the diagnostic matcher working...

**Comment by Tyriar** [comment]
fyi @alexr00 

@go2sh any reason why you don't do `export LANG="en_US.UTF-8"` in your `~/.bashrc`?

**Comment by go2sh** [comment]
German is my preferred language, so `de_DE` is okay for normal usage. But the gcc problem matcher only recognizes `Error` and not `Fehler`, so for this special case, I'd like the language to be changed. I use a special TaskDefinition with TaskProvider to supply Tasks with a ProcessExecution. So bashrc do not apply.

**Comment by Tyriar** [comment]
@go2sh I think for your case you're doing the right thing, You can either setLocaleVariables to `false` (which will be detectLocale to `"off"` soon from this PR) and handle it yourself or overriding the env just for tasks.

**Comment by go2sh** [comment]
@Tyriar Thank you. I just wanted to make sure with comment, that the option (either the old or new own) gets mentioned in the documentation (tasks page and api page under the *ExecutionOptions). As extension developer, I got a lot of reports regarding the `LANG` environment variable and I spent a lot of time reading and debugging the code to find the config option.

Also I like the PR very much because now you have a change to override the var without changing the configuration (as `auto` is the default compared to `true` before). I implemented a check in my extension for the old config option to warn the user to enable it, when he tries to override the `LANG` var.

**Pull request merged**
