### PR TITLE
Prefill new issue via Help > Report Issues

### LINKED ISSUE #7497: Prefill reported issue body with version and OS when triggered from menu
You can set the issue body using the query string https://github.com/Microsoft/vscode/issues/new?body=[body]

This would be convenient for the team to auto-fill this information when using Help > Report Issues, it would also help reduce an extra round trip if the community leaves out their OS and leave out the version. It will also give us the commit which will be increasingly useful information for insiders towards the end of the month.

I can't figure out how to do new lines in the query string is the only issue, `\n`, `<br>` and `&lt;br&gt;` all seem to not work.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #7497

---

cc @bpasero @joaomoreno 

image

### CODE REVIEW

**Comment by bpasero** [comment]
Should it not be identical to our template?

image

**Comment by Tyriar** [comment]
@bpasero I mentioned in the issue https://github.com/Microsoft/vscode/issues/7497

> I can't figure out how to do new lines in the query string is the only issue, `\n`, `<br>` and `&lt;br&gt;` all seem to not work.

**Comment by joaomoreno** [comment]
Does `%0A` work?

**Comment by Tyriar** [comment]
@joaomoreno https://github.com/Microsoft/vscode/issues/new?body=:0%0Ao.0

**Comment by Tyriar** [comment]
Just updated and tested, here's the output:

```
- VSCode Version: 1.3.0-dev
- OS Version: Darwin x64

Steps to Reproduce:

1.
2.
```

**Comment by Tyriar** [comment]
I'll merge and update the stable/insiders report URLs

**Pull request merged**
