### PR TITLE
Implementation of issue #950

### LINKED ISSUE #950: Select current line
Basically I'd just like feature parity with Atom on this.

first ctrl+l: should select the current focussed line
repeated ctrl+l should extend the selection to the end of the next line

Currently what happens:
ctrl+l: nothing

I looked through the shortcut config and couldn't find anything to do this. I also was unable to find any action for this in the source code of vscode.

### PR DESCRIPTION
**Pull request by MattiasPernhult**
Fixed #950

### CODE REVIEW

**Comment by benkaiser** [comment]
Thanks @MattiasPernhult and @Agetorp ! You guys are legends!

**Comment by alexandrudima** [comment]
Thank you @MattiasPernhult -- there were a few glitches that occurred when using it on a long line (wrapping), so I've made it to consistently use the view coordinates. Also created a test for it.

Thank you! :+1:

**Comment by benkaiser** [comment]
How long is it before you guys next do a release @alexandrudima ?

**Comment by alexandrudima** [comment]
@benkaiser [insider 14.12, stable 18.12](https://github.com/Microsoft/vscode/issues/917)

**Comment by benkaiser** [comment]
Thanks @alexandrudima

**Pull request merged**
