### PR TITLE
Add an option to allow to open in new window after git initializing or cloning 

### PR DESCRIPTION
**Pull request by abbychau**
https://github.com/Microsoft/vscode/issues/68945

This will add `New window` button for users to select after git initializing or cloning.

### CODE REVIEW

**Comment by abbychau** [comment]
@joaomoreno can you assign reviewers so to proceed this PR?

**Comment by svipas** [comment]
Finally, I'm always manually opening a new window and then cloning the repo.

**Comment by abbychau** [comment]
> Finally, I'm always manually opening a new window and then cloning the repo.

This PR is here for a few months... I don't know if they think that it is a bad idea or what orz...

**Comment by joaomoreno** [comment]
Thanks! :beers:

**Comment by svipas** [comment]
@joaomoreno You're MVP! 💃

**Pull request merged**
