### PR TITLE
Add more log information

### PR DESCRIPTION
**Pull request by NCC1701M**
This PR includes additional logging to get more information on #111177

### CODE REVIEW

**Comment by bpasero** [comment]
Why is this needed?

**Comment by NCC1701M** [comment]
To get a closer look if log messages are written because there wasn't any message in the log yesterday. And if log messages are written to see if all messages there or if something is missing which would indicate an error. Maybe it happens in the lambda function and the error doesn't reach the top try...catch. The log messages can be removed as soon as we had an closer look

**Comment by bpasero** [comment]
So has the issue come back to you?

**Comment by NCC1701M** [comment]
Yes, it never left. It has something to do with `vscode-remote://dev-container` entries in the `openedPathsList``in the `storage.json` file. Most likely with dev-containers which I created by using the command `Clone Repository in Container Volume`

grafik

When I remove those entries from `openedPathsList` it works as expected. When I add the entries all items from the task bar context menu are gone, except for those which are pinned or those which are not in the list at all.

**Comment by NCC1701M** [comment]
@bpasero When will the changes be available in the insider release?

**Comment by bpasero** [comment]
@NCC1701M I don't really understand the purpose of this PR, there is already logging for errors here:

https://github.com/microsoft/vscode/blob/962bedc4f47b26e4a6ddc917ee2a4d9445531fb9/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L383

If there was any exception we would already see it, no?

**Comment by NCC1701M** [comment]
I don't think so. And this PR is too test if the logging really works. Maybe for some kind of reason something happens and is not logged.

Only because there is logging doesn't mean it is working. What if the update jumplist function isn't called at all? We would never knew because the only logging method is in a catch block which would never be reached because of you don't call the method you never get an error.

If this method is called with the PR we can see it in the log window even though there is no error in this function.

But there is a error, believe me. And the error is pretty annoying. 

I would love to simply open the dev tools in VSCode and set a break point in workspacesHistoryMainServices but it is not possible because the file isn't there. Therefore we have to go another way (or even more ways) and one is to extend logging.

**Comment by bpasero** [comment]
@NCC1701M can you clarify why the try/catch here is not catching all the cases if there was an error:

https://github.com/microsoft/vscode/blob/5e6a2779f63c3a1a5d770498c4ead5fd8f34859a/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L333-L384

We assume that there is an exception happening somewhere in that block and if it was, you would get an error logged. Since there is no error logged, your logging would not reveal anything more either, no? For sure this code is triggered, how would it not?

**Comment by NCC1701M** [comment]
There could be several reasons why there is no error - at least on I have explained.

- The function might no be called at all, because the error happens in an different error which is not clearly identified as an error regarding to the problem
- The exception could already be handled in one of the functions which are called in the `updateWindowsJumpList` function and can also not clearly identified as an error regarding to this problem. There are several function call already in the map function like `isRecentWorkspace`, `splitName`, `localize` only to name a few.
- I'm not sure about the implementation of `arrays.coalesce` maybe it simply returns an empty array or something like that.

I've never said that the problem happens in this function. It could be elsewhere in VSCode. I'm only saying that it's not a problem by the window jumplist implementation. Sure Maybe there is an entry which causes the problem but, to handle those errors should be done in VSCode either by ignoring damaged entries or to prevent them to happen.

As I also mentioned before, the problem has something to to with vscode-remote://dev-container entries. Maybe they are to long for jumplist entries or something else, so the problem might also be in the Remote Container extension, but thats not on me to identify. This has to be done by the developers of VSCode and their extensions. And as far as I know. the Remote Container extension is also by microsoft.

I'm just trying to help by adding some additional log information trying to pin point the problem.

**Comment by bpasero** [comment]
@NCC1701M I am fine adding more log statements, but then I would suggest to add statements that print out more information from what we have today. The function is called, we know that, because it works for you when have no recent entries with remotes right? So we can rule that out. And if any of the code within would throw an exception, we would also find out about it because we have a global try/catch around it. So I think we can rule out that an exception occurs. 

As such, if there is an entry in the jump list that is causing the jump list to be empty, this is likely not a problem with an exception but something where Windows or Electron is not able to create the jump list altogether, but logging inside VSCode will likely not reveal this issue. 

I feel the best strategy to push this further is to try to come up with an isolated Electron sample project that sets the jump list with exactly the entries you have when it fails to render. Because then we could report this to Electron (https://github.com/atom/electron).

Does that make sense?

**Comment by NCC1701M** [comment]
Yeah I'm with you on the log entries with more information and feel free to add more log statements and information to the existing ones. 

Sure we can do that with an isolated electron app but before we do this, have you tried to reproduce the problem with the information given? And then tried to debug it VSCode? Or do you have suggestions how I can debug it with the released Code or code-insiders version?

**Comment by bpasero** [comment]
Yeah I tried to reproduce right from the beginning, here is what I did:
* be on Windows
* use VSCode to open a folder in WSL (that is a remote connection)
* verify that these remote folders appear in the recently opened list

See my comment https://github.com/microsoft/vscode/issues/111177#issuecomment-734111236

I do not have a docker setup on Windows, so maybe you could try to reproduce with WSL?

**Comment by bpasero** [comment]
@NCC1701M in https://github.com/microsoft/vscode/issues/111177#issuecomment-734105658 you indicated:

> The problem seems to be related to remote containers. I've added a vscode-remote://dev-container workspace by hand to the "workspaces3" array of storage.json and then the same problem happens.

Can you give me the exact URL you tried to see if I can reproduce that locally?

**Comment by NCC1701M** [comment]
I never had a problem with WSL remote connections. The problems are with docker container when I come them in a volume as described above.

I can send you the URL on Monday.

**Comment by bpasero** [comment]
I was able to use Docker on Windows and found the task menu to work even with Docker entries.

**Comment by NCC1701M** [comment]
> 
> 
> I was able to use Docker on Windows and found the task menu to work even with Docker entries.

Did you also used `Clone Repository in Container Volume` or did you used an existing repo on your disk and opend it in a container? Because the latter works for me as well.

Did you used a GitHub-repo? I used an Repo hosted on Azure DevOps. If you used a GitHub-Repo I'll try this one as well to see if this works for me as well.

**Comment by bpasero** [comment]
I actually selected to open a local folder inside the docker container. Happy to try out another case if you can give me one that reproduces this issue 👍

**Comment by NCC1701M** [comment]
> 
> 
> I actually selected to open a local folder inside the docker container. Happy to try out another case if you can give me one that reproduces this issue 👍

Open a local folder works for me as well. It's the `Clone Repository in Container Volume` which doesn't work. The URLs created by this function a much longer.

I sent you one example this morning by mail using the address you added to your GitHub profile.

**Comment by bpasero** [comment]
Ok thanks I reopened https://github.com/microsoft/vscode/issues/111177 for me to try out.

**Pull request closed without merging**
