### PR TITLE
bulk file edits: make sure to use textFileService when creating files

### LINKED ISSUE #112377: Files created from Explorer ignore files.encoding setting
I have following settings 

```json
    "files.encoding": "utf8bom",
```

image

I expect all my files created with UTF8 with BOM. 

It seems creating files via Explorer ignores setting UTF 8 with BOM and sets it always to UTF8. It would seem UTF 8 equals UTF 8 with BOM according to Explorer create file process. Changing in options utf8 to utf16 works correctly tho so it reads configuration properly. 

- VSCode Version: 1.52
- OS Version: Windows 10

Steps to Reproduce:

1. Create any file via Explorer 
2. Notice it's UTF 8

What works correctly:

1. Create a file via File -> New File
2. Notice it's UTF8 with BOM

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by isidorn**
This PR fixes https://github.com/microsoft/vscode/issues/112377

This PR adds an option to pass multiple `resources` to `create` in the `textFileService`.
A bit ugly part is that now only the `create` method in the `textFileService` accepts multiple resoruces and undo and cancellation arguments.

I have tested this out and these changes indeed fix the issue.
Note that I am converting a `VSBuffer` to a `string` via the `toString` method for each `edit`.

@bpasero let me know what you think
@jrieken fyi

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
The changes in text file land are fine to me. What I don't really understand is the need for converting a `VSBuffer` into a `string` via `toString`. That imho is dangerous because if the user picked a non UTF-8 encoding to create a file, `toString` is not safe to use. It needs to be the `VSBuffer` so that the encoding is preserved.

**Comment by isidorn** [comment]
@bpasero thanks for the review! Yes, that `toString` was phishy to me too.
What would be the recommend way of converting `VSBuffer` to `ITextSnapshot`
@jrieken might you have ideas?

**Comment by isidorn** [comment]
@bpasero thanks for the review.
I will change the `getEncodedReadable` to also work with the `VSBuffer` then I think we should be good

**Comment by bpasero** [comment]
To clarify: `getEncodedReadable` will use `iconv-lite` to return bytes from the string as configured by the encoding. These bytes are then passed to the working copy file service to put to disk.

If we need to preserve the actual string in the bulk edit service, e.g. for undo/redo, then this needs to be the original value before it was passed to `getEncodedReadable`, otherwise you would need to know the encoding to restore the original value.

Also keep in mind how efficient it is to use `string`, vs `ITextSnapshot`. The advantage of `ITextSnapshot` is that we don't have to create a new string from the editor model.

**Comment by isidorn** [comment]
Discussed with @jrieken, looked a bit more into the issue, and took a step back. Some findings:
* `edits` do not have to be textual (it can be an image) so it does not make sense to use the `textFileService` in all cases.
* The proper encoding for new empty files was working before because the Explorer was directly using the `textFileService` for creating empty content [pointer](https://github.com/microsoft/vscode/blob/e5a624b788d92b8d34d1392e4c4d9789406efe8f/src/vs/workbench/contrib/files/browser/fileActions.ts#L899)
* This does not work in Insiders because `workingCopyFileService` is used instead, which directly goes to the `fileService` thus bypasing the `textFileService` and the encoding. The `textFileService` gets the encoding from [here](https://github.com/microsoft/vscode/blob/8ae693bee2c5f24375d7b5caf9f45dd2dad2a102/src/vs/workbench/services/textfile/browser/textFileService.ts#L609). This is true even when an empty file is created, since we create an empty encoded readable which respectes the encoding [here](https://github.com/microsoft/vscode/blob/8ae693bee2c5f24375d7b5caf9f45dd2dad2a102/src/vs/workbench/services/textfile/browser/textFileService.ts#L188)

Due to the above I propose the following solution:
* Create folders and non empty file using the `workingCopyFileService`. Since non empty files do not have to be textual we can not use the `textFileService`
* Create empty files using the `textFileService`

Since only for empty files we have to read the actual encoding. Non empty files the bits coming in already have an encoding and we can go directly to the `workingCopyFileService`.

I have updated the PR to use this strategy. I have verified this fixes the issue.
@bpasero let me know what you think

**Review by bpasero — APPROVED** [review]
Yes, I think this is an elegant solution. If you or Jo feel that the direct use of `ITextFileService.createFile` is not nice inside `bulkEdit`, I am also open to make `getEncodedReadable` public so that you can create the right `VSBufferReadable` when the file is empty.

**Comment by isidorn** [comment]
@bpasero thanks for the review. That would also be an option.
I am fine with how things ended up. Let's see if Joh has some comments, if not I will merge this in later in the afternoon.

**Comment by jrieken** [comment]
@bpasero I am still curious how you store/remember the encoding for an empty file. Is the file not empty in that case but uses some bytes to store the encoding?

**Comment by bpasero** [comment]
@jrieken this is only required for encodings that use a byte order mark, which means: only UTF8 (with BOM), UTF-16LE and UTF-16BE. Those files, when empty, contain the BOM.

**Comment by jrieken** [comment]
Ah, thanks for clarifying. 

>  I am also open to make getEncodedReadable public so that you can create the right VSBufferReadable when the file is empty.

I believe that's nice. Ideally, [WorkspaceFileEditOptions](https://github.com/microsoft/vscode/blob/5cc0aa284968c66b0075ac3b89a70c2edb10b891/src/vs/editor/common/modes.ts#L1383-L1383) get's a new, optional property that carries a VSBuffer with the contents if the file. The explorer uses them some mechanics to create that buffer

**Comment by isidorn** [comment]
@bpasero let me know if you plan to make `getEncodedReadable` public. And if you will push that to master. If yes, then I can discard this PR and just adopt that method on master.
Otherwsie I will merge this in.

**Comment by bpasero** [comment]
Please go ahead and make it public as part of this PR because you also will need to adopt it.

**Comment by isidorn** [comment]
@bpasero I have updated the PR, check it out and let me know what you think?
I can also make the `getEncodedReadable` method take less arguments since my use case I only pass in the resource. Though I left it with all the arguments in case somebody wants to use it

**Review by bpasero — APPROVED** [review]
👍

**Comment by isidorn** [comment]
Thanks for the reviews and help. Merging in.

**Pull request merged**
