### PR TITLE
Fix storage error message to display details of error

### PR DESCRIPTION
**Pull request by SteveDesmond-ca**
When a storage error occurs, the `error` parameter passed to the
promise's `then()` method is an object, and therefore when attempted
to be output as a string via a template literal, the error is
displayed as `[object Object]`.

This PR updates the error output to output the entire error object as
JSON. There is no single property that provides enough detail to
display on its own, so JSON was determined to be the best waym to
summarize.

### CODE REVIEW

**Comment by stevedesmond-ca** [comment]
The original issue can be seen in the conversation of https://github.com/microsoft/vscode/issues/6442#issuecomment-493794022
Runtime output before

The underlying `error` object is
```json
{
  "errorCode":"load",
  "moduleId":"vscode-sqlite3",
  "neededBy":["===anonymous3==="],
  "detail":{"code":"MODULE_NOT_FOUND"}
}
```

I believe this is another spot where cross-compilation to ARM was not considered, and will create a separate PR to update the offending module.

**Comment by bpasero** [comment]
@stevedesmond-ca can you resolve the conflict?

**Comment by bpasero** [comment]
I am not convinced this is a good fix, rather I wonder why the loader is returning a JSON structure and not a real `Error`. I am expecting an `Error` object when import fails. @alexandrudima maybe you could chime in when you are back.

**Comment by alexandrudima** [comment]
@bpasero The loader does not give an `Error` instance when loading fails, it gives an object of the shape shown in the comment.

**Comment by alexandrudima** [comment]
Thanks for closing, I forgot to close it... it was fixed upstream...

**Pull request closed without merging**
