### PR TITLE
Implement API for listening to executed commands

### PR DESCRIPTION
**Pull request by kylecarbs**
Implements `vscode.commands.onDidExecuteCommand`. This does not send args with commands, only the command id and source.

```ts
vscode.commands.onDidExecuteCommand((event: vscode.CommandExecutedEvent): void => {
    console.log('We executed the command', event.commandId, event.source);
});
```

https://github.com/Microsoft/vscode/issues/1431
https://github.com/Microsoft/vscode/issues/26729

### CODE REVIEW

**Comment by kylecarbs** [comment]
The command source isn't passed around nicely for `CommandPalette` executions.

https://github.com/Microsoft/vscode/pull/66294/files#diff-66071720e6f855c0bc8b76044df35b3fR36

Suggestions around this would be helpful.

**Comment by jrieken** [comment]
ping

**Comment by prostoandrei** [comment]
@jrieken it would be very helpful for something like this:
https://github.com/Microsoft/vscode/issues/26729

For example https://github.com/halirutan/IntelliJ-Key-Promoter-X for IntelliJ is very useful tool

**Comment by jrieken** [comment]
I understand and like the feature request but this API request a little bug and not without discussion. For instance, the command execution source is a big no-no and I am not yet sure what it means to skip over arguments.

Did it ever occur to you to contribute this to the core and as an extension? Assuming you have this API what UX would your extension contribute?

**Comment by jrieken** [comment]
no activity, closing

**Comment by nolazybits** [comment]
I think the owner of this MR was just trying to get the actual event when a command gets fired. 
This will help create extension to promote shortcuts (https://github.com/Microsoft/vscode/issues/26729)

Could you please reopen this?

**Comment by jrieken** [comment]
please see here: https://github.com/microsoft/vscode/issues/78091#issuecomment-518545491

**Pull request closed without merging**
