### PR TITLE
Add numeric values support for terminal.integrated.fontWeight

### LINKED ISSUE #101467: Allow number values for editor.fontWeight
Currently `editor.fontWeight` only accepts values from `enum` which is convenient to pick from dropdown, however causes problems with fonts when there is noticeable difference between e.g. `300`, `350`, and `400` because `"350"` is not valid value.
Recently [new version of Cascadia Code](https://github.com/microsoft/cascadia-code/releases/tag/v2007.01) was released which provide nicer look for `"350"` value but marked as invalid.

I propose to allow numeric values in addition to current enum values (for backward compatibility) accordind to [CSS Fonts Module Level 4 > font-weight](https://drafts.csswg.org/css-fonts-4/#font-weight-prop)

Draft PR: #101468
If this request will be approved - I'll add same support to `terminal.integrated.fontWeight` and `terminal.integrated.fontWeightBold` options.

Only drawback that I see at this point - it's no longer possible to pick value from dropdown in Settings editor, however text values are still suggested in JSON.

UPD. As alternative it would be nice to have at least `*50` values at the end of the list of `*00` values

### LINKED ISSUE #106347: Allow number values for terminal.integrated.fontWeight and fontWeightBold
Follow up of https://github.com/microsoft/vscode/issues/101467 for terminal

PR https://github.com/microsoft/vscode/pull/106072

### PR DESCRIPTION
**Pull request by IllusionMH**
Fixes #106347
This PR supersedes #101468
Depends on https://github.com/xtermjs/xterm.js/pull/3062

Incorporates feedback from https://github.com/microsoft/vscode/issues/101467#issuecomment-684724245 and https://github.com/microsoft/vscode/pull/105880#issuecomment-686060780

I've simplified `FontWeight` to skip strings with numeric values and use `number` instead. ~This obviously leads to type error in terminal constructor call but works as expected and can be merged when Xterm.js updated with `number` type support.~ No type errors after `xterm@4.9.0-beta.32` update.

/assign @Tyriar

### CODE REVIEW

**Comment by Tyriar** [comment]
I pulled the xterm.js change in https://github.com/microsoft/vscode/commit/ec870eefbbef1ee6cfcb6a89d198c8022badffde

**Comment by IllusionMH** [comment]
@Tyriar thank you for Xterm PR review and update in this repo!

I've rebased on top of master - TS error is gone and continues to works as expected in different ranges (also removed unused import).

PR is ready for review and merge.

**Review by Tyriar — APPROVED** [review]
Thanks, works great!

**Comment by IllusionMH** [comment]
Thanks for review!

**Pull request merged**
