### PR TITLE
Fix for #26659.

### LINKED ISSUE #26659: Add way to open Markdown links in a different editor group
Scenario:

Markdown file is open in left editor group.  This file has a lot of links to other .md files that I want to preview in the right editor group.  But  Markdown links can currently only be opened into the same editor.

Please consider.  Thanks!

### PR DESCRIPTION
**Pull request by txava**
Clicking on a local file link will open up the editor on a separate editor group _(new or reuse existing one)_ as seen in the [video](https://www.youtube.com/watch?v=p8MBk1kAODg) _(For some reason the mouse pointer is not being recorded but still can an idea on what's happening)_

Fixes #26659

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks for taking a look at this. I think we should add a setting to control this behavior, similar to the existing `markdown.preview.openMarkdownLinks` setting. The default would be top open markdown links in the current group

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look at this. I think we should add a setting to control this behavior, similar to the existing `markdown.preview.openMarkdownLinks` setting. The default would be top open markdown links in the current group

Let me know if you have any questions about this

**Comment by txava** [comment]
@mjbvz Thanks for the review.
Just pushed another commit which adds a setting to control the behavior.

Cheers,
Sal

**Comment by mjbvz** [comment]
Thanks! Will be in the next VS Code insiders build and scheduled to be in VS Code 1.39

**Pull request merged**
