### PR TITLE
Use readonly #12732

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Adopted `readonly` in `vscode.d.ts`

### CODE REVIEW

**Comment by jrieken** [comment]
We cannot merge that yet

* we use typedoc to generate the extension API page and that isn't fit for TypeScript 2.0 yet
* it's unsure how readonly-ness should be expressed for objects we have created vs objects consumer create, e.g TextEditorOptions cannot be modified by setting a value ala options.lineNumbers = value but when creating a new objects they can

**Comment by Ikuyadeu** [comment]
Thank you.
So, I should close this PR once, or wait until typedoc to version up?
Can I be of any help for it?

**Comment by jrieken** [comment]
We are ready for this and want it for Jan

**Comment by jrieken** [comment]
@Ikuyadeu Can you also add `readonly` here (basically I have searched for `@readonly`)

- [ ] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1599
- [ ] all in `env` (https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3379)
- [ ] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3863
- [ ] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3914

**Comment by Tyriar** [comment]
Can the @readonly comment annotations be removed now?

**Comment by Ikuyadeu** [comment]
@jrieken Ok, 
- [x] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1599
added redonly.But, 

- [ ] all in env (https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3379)
- [ ] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3863
- [ ] https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3914
are yet. because they're using `export` and `namespace`.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/pull/13863#issuecomment-269386882 I wanna first check how the doc generation tool handles the native readonly flag.

**Comment by jrieken** [comment]
Something is very wrong... There are 25 files with changes

**Comment by Ikuyadeu** [comment]
@jrieken Sorry, I missed

**Comment by Ikuyadeu** [comment]
Reopened PR in #18251

**Pull request closed without merging**
