### PR TITLE
fix IExtensionRecommendationReson typo

### PR DESCRIPTION
**Pull request by samdenty**

### CODE REVIEW

**Comment by samdenty** [comment]
@microsoft-github-policy-service agree [company="stackblitz"]

**Comment by samdenty** [comment]
@microsoft-github-policy-service agree

**Comment by samdenty** [comment]
@microsoft-github-policy-service agree

**Comment by samdenty** [comment]
@microsoft-github-policy-service agree company="stackblitz"

**Comment by gjsjohnmurray** [comment]
@samdenty  please see https://github.com/microsoft/vscode/wiki/How-to-Contribute#spell-check-errors

**Review by sandy081 — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Pull request merged**
