### PR TITLE
xhtml is a profile not syntax in emmet

### PR DESCRIPTION
**Pull request by ramya-rao-a**
https://github.com/Microsoft/vscode/issues/18434#issuecomment-272997431

cc: @mrmlnc @egamma

### CODE REVIEW

**Review by egamma — COMMENTED** [review]
Removing `xhtml` from the list of `emmetSupportedModes` makes sense. Since in VS Code we have no language mode for `xhtml` but only `html`.

I'm now confused by this code that uses a profile to override the editors syntax. It was introduced as a partial fix for #9500 67bbb46e1852605fc88a6db254238be1c2bf9ec8. 

```typescript
		// user can overwrite the syntax using the emmet syntaxProfiles setting
		let profile = this.getSyntaxProfile(syntax);
		if (profile) {
			return profile;
		}
```
We are configuring emmet with the user defined profiles and preferences [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/emmetActions.ts#L92). Therefore we should let emmet handle the profiles. I'm therefore thinking we should remove the above code alltogether. It causes the issue in #18434 and this PR works around this code for xhtml. 

@mrmlnc what am I missing :smile:

**Comment by ramya-rao-a** [comment]
@egamma That is the part that enables emmet support for languages other than the "known" modes. 

What you [linked](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/emmetActions.ts#L92) loads profiles, yes, but here profile means the way html is output (like self closing tags, single quote for attributes etc.).

**Comment by mrmlnc** [comment]
Sorry, i'll see all issues with @mrmlnc tomorrow 👍 (now I have a lot of work on a new place of work 🔮)

**Comment by egamma** [comment]
@ramya-rao-a 

>That is the part that enables emmet support for languages other than the "known" modes.

Then isn't the root cause of the issue that we overload the setting `emmet.syntaxProfiles` as you describe in https://github.com/Microsoft/vscode/issues/18434#issuecomment-272997431.

Isn't a better fix is to eliminate this overloading and introduce a separate setting, e.g., `emmet.mapLanguage`. This settings supports to map a VS Code language to an emmet supported mode. 

```json
"emmet.mapLanguage": {
    "java": "html"
}
```
@mrmlnc what do you think?

**Comment by ramya-rao-a** [comment]
@egamma 
> Isn't a better fix is to eliminate this overloading and introduce a separate setting, e.g., emmet.mapLanguage

That was my first thought as well. But, that would break the experience for people who have already started using `emmet.syntaxProfile` to map their language to a known mode

**Comment by mrmlnc** [comment]
Hm, i don't fully understand your thoughts.

`"html": "xhtml"` should works fine, because this is example from http://docs.emmet.io/customization/syntax-profiles/. Now I don't understand why this is not work. 

Works for me inside `emmet.syntaxProfiles`:

```
"html": "jade",
"html": {
  "tag_case": "upper"
}
```

I'll look at this task in more detail soon.

**Comment by ramya-rao-a** [comment]
@mrmlnc 
`"html":"xhtml"` used to work exactly like the example in http://docs.emmet.io/customization/syntax-profiles/ before we made the change to use `emmet.syntaxProfile` to also map new languages to known syntax.

Now, when we set `"html":"xhtml"` in `emmet.syntaxProfiles`,  "xhtml" gets passed as a syntax (via the `getSyntax`), and then emmet provides only tag completion because it is not aware of any "xhtml" syntax. See https://github.com/emmetio/emmet/blob/master/lib/snippets.json, there is no "xhtml" syntax. And therefore all the html abbreviations that the user expects is missing.

**Comment by ramya-rao-a** [comment]
@egamma I have updated the PR with a slightly better fix.
- "xhtml" as before is removed from list of supported modes
- the overriding of syntax using profile will be done only if the profile is one of the supported modes
```javascript
// user can overwrite the syntax using the emmet syntaxProfiles setting
		let profile = this.getSyntaxProfile(syntax);
		if (profile && this.emmetSupportedModes.indexOf(profile) !== -1) {
			return profile;
		}
```

I believe this is a good solution for the current iteration.

But looking at the big picture, we should ideally have a separate setting for mapping languages to known syntax.

**Comment by egamma** [comment]
@ramya-rao-a 👍  This is a good fix and we can still look into adding a separate setting.

**Comment by ramya-rao-a** [comment]
Thanks @egamma PR is merged.
@mrmlnc Please add your thoughts here when you get some time.

**Pull request merged**
