### PR TITLE
fix: parse errors in coverage command

### LINKED ISSUE #155615: Cannot run unit tests coverage
Type: <b>Bug</b>

I was doing some researches and I wanted to run the command to generate the coverage report, as per documentation here: https://github.com/microsoft/vscode/blob/13d630d1f8a5e00f5db681ff4301f4f44531f756/test/unit/README.md#coverage

Running the `./scripts/test.sh` without `--coverage` works fine, all tests are passing.

However when I run it with the flag, I get the following error:

```
leonardo@MacBook-Air vscode % ./scripts/test.sh --coverage
yarn run v1.22.19
$ node build/lib/electron
✨  Done in 0.51s.
Found --crash-reporter-directory argument. Setting crashDumps directory to be '/Users/leonardo/PersProgetti/vscode/.build/crashes'
objc[10439]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x229e5b808) and /Users/leonardo/PersProgetti/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1158713c8). One of the two will be used. Which one is undefined.
[10436:0719/154640.435506:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: node:electron/js2c/renderer_init (33)
[10436:0719/154719.809929:INFO:CONSOLE(108)] "Uncaught SyntaxError: missing ) after argument list", source: node:vm (108)
[10436:0719/154720.178992:INFO:CONSOLE(108)] "Uncaught SyntaxError: Unexpected token '??'", source: node:vm (108)
```

Node version: 16.15.1

VS Code version: Code - Insiders 1.70.0-insider (a74adedba8fb56d14f01f7950340dab33cfeae57, 2022-07-19T05:21:29.044Z)
OS version: Darwin arm64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|. --disable-extensions --crash-reporter-id e77379eb-0ae3-49d7-afaa-dec9ef1ed204|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #155615

### CODE REVIEW

**Review by bpasero — DISMISSED** [review]

**Review by bpasero — DISMISSED** [review]

**Comment by bpasero** [comment]
Hm:

image

**Comment by connor4312** [comment]
Fixed one more time 😬

**Review by bpasero — DISMISSED** [review]

**Review by Balastrong — DISMISSED** [review]
Worked for me, thank you! :)

**Comment by connor4312** [comment]
Oops, forgot to turn on auto merge for this...

**Review by roblourens — APPROVED** [review]

**Pull request merged**
