### PR TITLE
Align badge theming with the GUI badge

### LINKED ISSUE #61959: Use standard badge color for `No Results` label in settings
In approx 1/4 of my installed themes this badge looks awful:

screenshot 94

Having no-results just doesn't feel like an error. Standard badge color (Like white here on github badge) is fine(because it's usually made for it).

P.S. no need for a new color, already too many of them.

P.P.S. actually new settings editor doing exactly that:
screenshot 95

So, it just needs to be aligned with the GUI version of settings.

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #61959

### CODE REVIEW

**Comment by usernamehw** [comment]
Not sure if `no-results` class should be deleted from the element.

**Comment by roblourens** [comment]
Looks great but yeah the no-results class can be removed, please do that too

**Review by roblourens — APPROVED** [review]
Thanks!

**Comment by usernamehw** [comment]
@roblourens, there is now an unused parameter `count` (I didn't see it)

https://github.com/Microsoft/vscode/blob/0817eb5df51f810d5a543f93a71e16c713a62570/src/vs/workbench/parts/preferences/browser/preferencesWidgets.ts#L649-L651

**Comment by roblourens** [comment]
Thanks, I just cleaned it up

**Pull request merged**
