### PR TITLE
Git: Pull from specific branch adds feature to #26738

### PR DESCRIPTION
**Pull request by BuraChuhadar**
Adding a feature to Microsoft/vscode#26738

### CODE REVIEW

**Comment by Tyriar** [comment]
Could you please link the issue this is resolving? If one doesn't exist please create one with the problem it solves and link it 😃.

**Comment by joaomoreno** [comment]
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.

**Comment by BugraC** [comment]
@joaomoreno I signed the CLA. I will fix the conflicts again. Please let me know if anything is missing besides the conflicts.

**Comment by joaomoreno** [comment]
Thanks 🍻  more info in #16100

**Pull request merged**
