### PR TITLE
Support object types in `when` conditions

### PR DESCRIPTION
**Pull request by dave-bartolomeo**
This PR implements #74699 

This change allows the `contextValue` property on a `TreeItem` to have `any` type, rather than just `string`. The value is added to the `Context` under the `viewItem` key as before. The implementation of `Context.getValue` has been updated to treat `a.b.c` as a lookup of the key `a` followed by accesses to the `b` property on `a` and the `c` property on the result of `a.b`.

**Backward compatibility concerns**
Are there existing context keys that contain `.`, other than for `config.*`, which is handled in a special `IContext` implementation?

**Testing**
I have not yet implemented any tests for the new feature. It appears that there are existing contextKey tests, but only for the expression parser and evaluator. Should I just add more tests for `Context`? Or should I test this some other way?

### CODE REVIEW

**Comment by dave-bartolomeo** [comment]
I've added a test for the `Context.getValue` function's support for object properties.

Is there any additional work I need to do before this can be merged?

**Comment by sandy081** [comment]
@dave-bartolomeo I would **not** recommend to introduce this support for all context values.

I am expecting that the tree item gives context object and the tree implementation inside VS Code creates individual context values from it.

It means that you have to still provide each key and value in your when expression while contributing the menu item.

For example, tree item can provide following context object

```json
{
  "key1": true,
  "key2": "value1",
  "key3": false
}
```

And the menu item contributing to the view item is as follows
```json
"menus": {
	[
		"view/item/context": [
				{
					"command": "nodeDependencies.editEntry",
					"when": "view == nodeDependencies && key1 && key2 == value1 && !key3",
					"group": "inline"
				}
		]
	]
}
```

Let me know if we are on same page

**Comment by dave-bartolomeo** [comment]
@sandy081 Thanks for taking a look. I can certainly make it work the way you suggest. However, I'm not sure I see any real semantic difference between your suggestion and mine. For example, with my implementation, I could do:
```
{
  key1: true,
  key2: "value",
  key3: { nested: false }
}
"when": "viewItem.key1 && viewItem.key2 == value && !viewItem.key3.nested"
```
With your solution, I could do the same thing by replacing `.` with `_`:
```
{
  viewItem_key1: true,
  viewItem_key2: "value",
  viewItem_key3_nested: false
}
"when": "viewItem_key1 && viewItem_key2 == value && !viewItem_key3_nested"
```
Both let me express the same rich context, but the second solution seems less natural, and inconsistent with the existing handling of `config.key.nestedKey`. Your suggestion also has the potential for name collisions between the properties of the context object and other keys already present from other sources (e.g. `view` and `config`). That problem could just be solved by making the new keys named `viewItem.key1`, `viewItem.key2`, etc., though.

In my particular scenario, there is actually one extension ([vscode-test-explorer](https://github.com/hbenl/vscode-test-explorer)) that is creating the actual `TreeItem`s based on data provided by multiple other extensions. I would be nice if one of those providers could give the extension a context object, and have the original extension expose that context object as a field of the actual `viewItem` context object, in addition to whatever other fields the extension itself puts directly on `viewItem`. I could make the extension flatten the context object with `_`s, but it seemed more straightforward a consistent to just handle property access notation within the `"when"` condition.

That said, if you don't find my above argument convincing, I'm happy to just implement it as you suggest. That design still lets me do what I need to do, even if it requires a little more code on the extension side.

**Comment by dave-bartolomeo** [comment]
I suppose I could also have the tree view contribute the individual keys after flattening the context object using `.` as the separator, That would make the code seem natural from the extension's point of view; it would just shift the implementation from the `Context` class to the tree view.

**Comment by sandy081** [comment]
@dave-bartolomeo I did not mean about the syntax. Saying that, I liked the syntax proposal from you.

My point is to not to implement this as generic support in `ContextKeyService` since it is specific to Tree, let Tree View implement this by setting the context values from the context object received from the tree item.

Ref - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/customView.ts#L858

**Comment by dave-bartolomeo** [comment]
Got it. I'll change the implementation to be in the TreeView.

**Comment by arminghm** [comment]
any update? :D

**Comment by lhein** [comment]
I am wondering too. Would be a great to have api addition.

**Comment by mforkel** [comment]
This feature would greatly simplify the implementation of my extension, which uses a TreeView for [quilt](https://manpages.debian.org/stable/quilt/quilt.1.en.html) patch data. The view displays hierarchies of folders (i.e. projects), patches, and files. Each type has attributes that determine which context menu items should be displayed (initialized, snapshot available, applied, top patch, patched, ...). Currently, I encode type and attribute values in a string and decode that string in the when clause using regular expressions. Because of the limitations of when clause operators (see #131819), I have to encode all boolean attributes (e.g. initialized or not_initialized, ...). All this would be much cleaner if for example I coud write something like `contextValue.type == folder && contextValue.initialized`.

**Pull request closed without merging**
