### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by kideny**
add zep extention

### CODE REVIEW

**Comment by dbaeumer** [comment]
@kideny could you explain what the zep file extension is and why it is necessary to open these files with C++ mode by default. You can always configure your own file extension -> language mapping using the `files.associations` setting.

**Comment by kideny** [comment]
zep is zephier file extention . Zephir is a compiled high level language aimed to the creation of C-extensions for PHP. we can have code highlight much better with C++ mode. I configure my file extension myself before,  but when vdcode update , i need to configure the file again ....please ,help me !!!

**Comment by dbaeumer** [comment]
You should be able to achieve this by setting the following user setting (File > Preferences > User Settings)

`"files.associations": { "*.zep": "cpp" }`

**Comment by kideny** [comment]
ok, i see .

**Pull request closed without merging**
