### PR TITLE
Fix logic for 1 editor Inc/Dec View command Fixes: #37347

### LINKED ISSUE #37347: Increase/Decrease View Commands: 1 Editor Logic Bug (H\V Panel orientation)
Code / Insiders
All OS

Part resize logic with one editor and panel.  Editor with focus, just panel does not resize.
@bpasero 
@isidorn 
To be clear and honest, this is my logic bug that actually is independent and pre-existing from
the vertical panel addition.  My issue not @isidorn ;-)  The bug is more obvious with vertical panel.

Steps to Reproduce:

1. Open code with one editor, panel open , sidebar hidden
2. Focus editor, try Increase/Decrease commands - editor does not resize
3. Focus panel, try resize - panel resizes correctly

Testing : #36906 
@Tyriar 
@octref 
I know you guys are testing and working on panel issues.  While not a panel issued directly
this bug is more noticeable with vertical panel so your guys call on PR integration...

Fixed with PR #37348

### PR DESCRIPTION
**Pull request by cleidigh**
Addresses focused editor resize problem with one editor and panel - editor does not resize.

Fixes: #37347

### CODE REVIEW

**Comment by isidorn** [comment]
@cleidigh thanks for this PR. I have checked and code and it looks good overall. Here's my feedback:
* consider using `this.editorCountForWidth` instead of `visibleEditors`
* do not use the `const isPanelVisible` and `isSidebarVisible` since you only use them once in code, just read them out from the `partService` where you need them (to simplify things)
* did you test out this change that it works properly in the following cases:
  * multiple editors and panel(both vertical and horizontal)
  * mutliple horizontal editors and panel(both vertical and horizontal)
  * all the comibinations from above with the all the sidebar locations (left, right, hidden)

Thanks a lot!

**Comment by cleidigh** [comment]
@isidorn 
- Removed const declarations, replaced with inline calls
- this.editorCountForWidth does not appear to exist, method local is used in several places:
const editorCountForWidth = this.editorGroupService.getGroupOrientation() === 'vertical' ? this.editorGroupService.getStacksModel().groups.length : 1;

- If I misinterpreted above, perhaps you like this method call better as a local substitute?
- I believe I tested all permutations, Inc/Dec appear to function correctly

I did observe one behavior with the panel vertical that may or may not be intentional:
- SetUp Code with following layout
- One editor, sidebar expanded to about 40% , vertical panel hidden
- Toggle panel on
- Panel opens to a width < 300px (panel minimum) about 208px
- Note at this point it appears that both vertical sashes are disabled 
- See screenshot, mouse cursor at sash edge does not turn into arrows, will not move sash
- various subsequent layouts will snap panel size to minimum
- if you agree, I can post issue but perhaps this is intentional

image

**Comment by isidorn** [comment]
@cleidigh it's great that you tested this. Merging in.

You did not see `this.editorCountForWidth` because you did not merge with latest master. I always recommend to do that to be up to date.
As for the issue found, we have fixed many vertical panel issues in the past couple of days so if you can no longer reproduce then it is probably fixed.

All in all, thanks for the great PR! Will merge and test it a bit.

**Comment by isidorn** [comment]
@cleidigh I have tryed this out and it works fine.
There is just one thing which is does not work well IMHO
If I focus on the panel, or on the sidebar and run your actions the editor will change size and not the panel / sidebar. Basically I can only get your actions to resize the editor which I think is wrong looking at the title of the action

**Comment by cleidigh** [comment]
@isidorn 
Thanks !

I am surprised, I need to do a search on the latest repository, maybe I did the search wrong
or had a misspelling.  I have to figure out how to do a merge without messing up a PR and progress.

More importantly; I would like to understand and make sure the commands are working
in a sensible fashion.  I am not sure what you mean when you say the sidebar nor the panel
resize when focused.

When I first made the commands months ago, I did make some behavior decisions.
First since there were only going to be to commands, I chose logic  that favored the editor size
or the primary axis of whatever focused part.  However, in the cases with all parts visible
sometimes I had to make a choice about which axis to change.

- 1 Editor, sidebar visible, no panel - if sidebar focused it expands/contracts same for the Editor
- Add bottom panel to above - if panel focused expands/contracts vertically, steals from Editor
- If Editor is focused with above layout , Editor expands/contracts horizontally stealing from the sidebar
  since the main axis of the editor is horizontal and I prioritize the sidebar below the panel
- The other combinations use basically the same logic
- I chose not to automatically collapse any part when it gets its minimum (that's what happens with the mouse)
- I thought since I'm moving in larger increments parts might close when you really don't want them to

Let me know which behaviors you'd like to change.
I am also going to do another issue / PR to support Split editors.
It drives me crazy I cannot resize the settings editors.  I can tweak the behaviors at the same time.

**Comment by isidorn** [comment]
What is not working is a very simple case for me

1. Have only panel open, focus panel. Do your action to increase size, size does not increase

Note that this also does not work for the sidebar and also if some editors are open.

Gif showing this
lala

**Comment by cleidigh** [comment]
@isidorn 
I just tested the zero editor case (my branch) - either only sidebar or only panel (your simple case)
Works as expected.

My guess is the merge with all the other panel and layout fixes I did not have since I did not merge
at the last moment (exactly your) comment, might be the issue.  

I will get latest and retest.

**Comment by cleidigh** [comment]
@isidorn 

Okay I figured it out.  Initially I could not see the detail in the animated gif.  I realized now you are using
the commands from the command palette.  The problem is that removes focus from the part so the command is not operate on anything.  I have key bindings which I use when the part is focused.

I can't really think how these commands could operate without maintaining focus on the part.  The
context keys would allow detecting visibility but not focus.  That is why the commands expect
to be executed within context, not the pallet.

Let me know if you agree.  I will still do some retesting to make sure the more recent  merge did not affect anything.

**Comment by isidorn** [comment]
@cleidigh works nicely with the shortcut. Thanks for explaining.
It is fine imho

**Comment by cleidigh** [comment]
@isidorn 
Great, thanks!
Split editor support next...

**Pull request merged**
