### PR TITLE
Experimentation in typescript-language-features

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This PR is a work-in-progress to perform experiments in the typescript-language-features extension so that we can figure out what users respond best to in experiences like the upcoming JavaScript walkthroughs (https://github.com/microsoft/vscode/pull/151665).

vscode-tas-client usage recommendations seem pretty undocumented, so I took some inspiration from

* https://github.com/microsoft/vscode/blob/c047af40b27be89e456b8703526adc1a138d563d/extensions/github-authentication/src/experimentationService.ts
* https://github.com/microsoft/vscode-js-debug/blob/f314b55c8035fa535c42411c522714124df2dce5/src/telemetry/vscodeExperimentationService.ts
* https://github.com/microsoft/vscode-python/blob/3698950c97982f31bb9dbfc19c4cd8308acda284/src/client/common/experiments/service.ts
* https://github.com/microsoft/vscode-java-dependency/blob/eed2e9f38364a705f735656cd7fe5f5fecdcb0d6/src/ExperimentationService.ts

and I'm hoping to get team guidance on next steps to see if it's working, along with hearing about anything that I've gotten blatantly wrong.

CC @mjbvz @connor4312 @devinvalenciano @luabud @isidorn @daytonellwanger

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
How exactly should I add a dependency without updating the lockfile?

**Comment by connor4312** [comment]
This looks sane to me

**Comment by DanielRosenwasser** [comment]
I think the only TODO in the code itself is to actually instantiate the service on extension initialization.

**Review by mjbvz — APPROVED** [review]
LGTM too. @DanielRosenwasser I think I'll have to re-submit this PR since it changes the lock file. There's not currently good way for non-team members to update that. Let me know if it is ready to be merged

**Comment by DanielRosenwasser** [comment]
Should be ready - if you'd like, you can cherry-pick into its own branch (or alternatively you can just merge in spite of the CI if you're all cool with that).

**Comment by mjbvz** [comment]
Cherry-picking this in with #153358

Thanks @DanielRosenwasser!

**Pull request closed without merging**
