### PR TITLE
Added separator in the Makefile function call syntax (Fixes #132473)

### LINKED ISSUE #132473: Makefile grammar for function call separator syntax
The `,` needs a syntax grammar

Screen Shot 1400-06-15 at 19 11 45

### PR DESCRIPTION
**Pull request by pouyakary**
This PR fixes #132473

This PR adds a tiny new grammar for the function call grammar that adds the `,` as a punctuation. So this:

Screen Shot 1400-06-15 at 19 11 45

Becomes this:

Screen Shot 1400-06-15 at 19 06 28

### CODE REVIEW

**Comment by pouyakary** [comment]
Can you please help me find where I should provide the testing for the new grammar?

**Comment by pouyakary** [comment]
I also opened a PR in the [fadeevab/make.tmbundle](https://github.com/fadeevab/make.tmbundle/pull/11)

**Comment by alexr00** [comment]
@pouyakary thank you for the PR! Since we do get this grammar from an upstream repo I will wait for your PR to fadeevab/make.tmbundle to be merged and then pick up the changes from there.

**Comment by pouyakary** [comment]
@alexr00 thanks a lot!

**Pull request closed without merging**
