### PR TITLE
Fix #39306 - allow tab to change file currently being renamed

### LINKED ISSUE #39306: While renaming a file in the explorer, hit Tab to rename the next file
Hello,

While working on Ionic projects, I happen to duplicate entire folders (Ionic pages), and therefore I have to rename all the files in the folder to match the new folder's name

It would be great to just hit Tab to focus the next file in the list and let me enter the new name for the said file

Thanks in advance

PS. Currently hitting Tab gives focus to the tabs

### PR DESCRIPTION
**Pull request by Dari-K**
So I've added a check for tab/shift tab to rename the next or previous file.Focusing has to happen after the rename action has fired, otherwise the renaming seems to cause the current file to be refocused again. The renaming can cause files to move as they are sorted by name, so I couldn't use `focusNext` and `focusPrevious`, because tabbing could then cause the file being renamed to jump around as the renamed file moves. I didn't see an easier way to get the next/previous element in the tree, is there one? I also had to move `const restoreFocus` because the rename action seemed to change `document.activeElement`, so after a rename focus was never restored.

### CODE REVIEW

**Comment by isidorn** [comment]
@Dari-K thanks for your PR. However we are currently wrapping up our milestone, which means I will review this PR next week.

**Comment by isidorn** [comment]
@Dari-K thanks again for this PR.
I just did a review and I am not so happy about how this is structured.
Could we instead leave the the `done` function untouched and the handler when he figures out the tab is pressed he would figure out who is next / previous element call done and once done is finished then start the rename for the next / previous element?

**Comment by Dari-K** [comment]
So I made made the changes, the structure looks a lot nicer now, but there's still a problem with what seems to be a race between the action fire in `done` and the `renameFile` I fire off. It causes a strange state like this: 
screen shot 2017-12-14 at 15 49 56
So I either need to have a timeout before doing my focusing/sending my action, or I need `done` to return the promise from the action it runs. I added a timeout, but that doesn't seem like a great solution.

Also I tried to use `nav.last()` and `nav.first` to make the renaming wrap around, but both just seemed to return null for some reason.

**Comment by isidorn** [comment]
@Dari-K ok the structure looks great now 👍
As for your issues I recommend you try out different strategies until you nail down the bug as I will have time only in a couple of weeks to try this out.

**Comment by Dari-K** [comment]
So I ended up using `focusLast()` and `focusFirst()` for the wrapping since `nav.first()` and `nav.last()` don't seem to work.

The focusing/rename still has to be in a `setTimeout`, but with 0 delay, because the following lines 
 in `done` cancel the renaming if you tab without changing a file name.
```
setTimeout(() => {
	if (restoreFocus) {
		tree.DOMFocus();
	}
	lifecycle.dispose(toDispose);
	container.removeChild(label.element);
}, 0);
```
I assume this is because my code in the `.then` ends up being run before the code in that `setTimeout` if `done` just returns a promise that resolves immediately.

**Comment by isidorn** [comment]
@Dari-K I have looked at your PR and now the code looks better.
Also tried it out and it works well overall, however there is a ux flash while you are changing the input element, for a short period of time you can see the value on the right. This produces a weird flash effect.

Unfortunetly I currently do not have the time to look into this. And I would not merge in this PR with this UX glitch, so it would be great if you could investigate what is going on here.
You might try to reduce the higlight / clear highlight calls as that might help
Unfortuently the gif is not a good enough tool to caputer this, in this gif you can only see it happening once at the end, but it acutally happens all the time just the gif does not capture it.

glitch

**Comment by Dari-K** [comment]
@isidorn will look into it, but I see this flashing on Code 1.19.0, so I don't think this is caused by my changes.

**Comment by isidorn** [comment]
@Dari-K I don't see that much flasshing in vscode 1.19 when I simply want to rename a file. However with the tab behavior this becomes more apparent

**Pull request closed without merging**
