### PR TITLE
Composite Bar

### PR DESCRIPTION
**Pull request by isidorn**
* Takes out all the composite handling from `activityBarPart`and puts it into `CompositeBar`
* `CompositeBar` is simplified and does not do any listening. He needs some actions and composites passed which is reflected in the `ICompoisteBarOptions` bag

There are still some todos however the all the original activity bar funcitonality is there and should work properly. I tested a bit and it looks good.

Futher ahead:
* Make the overflow computation more dynamic
* Render icon vs label based on `label` property in `ICompositeBarOptions`
* Adopt in `PanelPart`

Please code review this. For the further steps a code review would not be required imho

### CODE REVIEW

**Comment by isidorn** [comment]
Tried to getCompositeSize from the actionBar however that did not prove to be successful due to the fact that the compositeBar is written in such a way that it is removing actions from the composite bar once they are not visible.
So for now I pass the function to determine the length of a composite. On the up side this will not require the redraw for the initial layout, on the bad side I will see how ulgy it is to render the hidden html, or how precise I can get the numbers based on the viewlet character length (even though it is not monospace)

**Comment by bpasero** [comment]
@isidorn looks good to me, I like the direction. 

Generally I wonder if we still need or can reduce the methods `pin`, `unpin`, `isPinned` and `move`. For example, [`move` ](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L233) is calling `isPinned`, `pin` and `move` but can those calls not all be done from within the composite bar? I think the only thing that needs to be abstracted is the `openViewlet` call with the `pin` method. Then maybe the `onDidDropComposite` event is also not needed because everything can be handled from within the composite bar. 

Some more minor feedback:
* I think we can move the `compositeBar` into `vs/workbench/browser/parts/compositebar` given that it has more associated files (e.g. maybe a `media/compositeBar.css` later?)
* I think more things from `activitybarActions.ts` will probably move into `compositeBarActions.ts`, e.g. like `ActivityActionItem` and `ActivityAction`?

**Comment by isidorn** [comment]
@bpasero thanks a lot for the feedback! As for the minor feedback I will adress it and merge in the PR.
I will also try to extract the `openViewlet` call.

**Comment by isidorn** [comment]
@bpasero merged in to be on master. I have adressed the minor feedback, will look today into extracting the `openViewlet` call

**Pull request merged**
