### PR TITLE
Joh/diag source

### PR DESCRIPTION
**Pull request by jrieken**
Add source to diagnostic object such that user can tell what linter/language service/extension created what error, See #1010

### CODE REVIEW

**Comment by jrieken** [comment]
@egamma @dbaeumer Started to flesh out the API with a simple `source: string` property. Question is what rendering you guys prefer in 

1. Editor hover on diagnostics
2. In editor error view
3. error quick pick

I guess it should always be the same? And the should it be `message (source)` or `(source) message`

**Comment by egamma** [comment]
@jrieken @dbaeumer I prefer `message (source)`, since the message is the primary information and the source is auxilliary, but I might revisit my opinion based on usage :smiley_cat: 

What is the source for the built-in linter for JS or TS, is it empty?

**Comment by jrieken** [comment]
I'd make them empty to begin with.

**Comment by egamma** [comment]
+1 for keeping them empty

**Comment by jrieken** [comment]
Challenge is messages that end with a dot, like so:
screen shot 2015-12-10 at 17 04 41

**Comment by egamma** [comment]
@jrieken sorry what exactly is the issue with the messages ending with a dot.
Could we use [ ] instead of ()?
Can we use different colors when we render a marker and use blue for the source?

**Comment by jrieken** [comment]
It does't look nice ;-) maybe a nicer different color or font style and []-brackets

**Comment by jrieken** [comment]
Decided to put it in []-bracket in front of the message. From there on we can tweak
screen shot 2015-12-11 at 10 50 35
screen shot 2015-12-11 at 10 42 07
screen shot 2015-12-11 at 10 42 02

**Pull request merged**
