### PR TITLE
fix: remove unsed code on detecting file type

### PR DESCRIPTION
**Pull request by simpleapples**
This RP only remove unused code based on the comment on https://github.com/microsoft/vscode/blob/01d0314308fdf83801c3d7abf43b7a2702ea9263/src/vs/base/common/mime.ts#L172

Besides, it won't cause any functional change after remove the line.

### CODE REVIEW

**Comment by bpasero** [comment]
I do not see how that code is unused, it is an early return. Closing until further info is provided.

**Comment by simpleapples** [comment]
If you choose to remain the early return, the following code will nerver be executed.
https://github.com/microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L195-L198

**Comment by bpasero** [comment]
I do not really understand your suggestion, but we cannot simply remove the `break` statement as the idea was to break the for loop when we found a exact name match?

**Comment by simpleapples** [comment]
Oh, sorry, I forget the for loop.

Another question, why not add a break after line 180 and line 189?

Thank you for your patient : )

**Comment by bpasero** [comment]
Because in that case we still allow the other match.

**Comment by bpasero** [comment]
Oh, maybe you are onto something, looks like a `break` could indeed work...

**Comment by bpasero** [comment]
No, unfortunately not. We cannot `break` because we may get a `filenameMatch` later in the loop.

**Comment by simpleapples** [comment]
Totally understood, Thank you.

**Pull request closed without merging**
