### PR TITLE
link protection - read remotes only once on startup

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Thanks! Didn't know about `IdleValue` thats useful.

**Comment by bpasero** [comment]
@JacksonKearl it is basically a way to trigger "expensive" stuff at a time where the browser is not doing work. It still means we have some file access right on startup, but I think that is fair, given that this contribution only runs after the workbench has restored.

**Comment by JacksonKearl** [comment]
Thanks, I didn't know about `IdleValue`, looks helpful. My one concern would be if the auth provider or file system provider hasn't registered at the time it executes.

**Comment by bpasero** [comment]
@JacksonKearl yeah that is a good point, and my PR was maybe a bit optimistic and needs more work, feel free to take this over. We have events that fire when e.g. extension host is ready, so that would be an alternative to trigger this after that happens. After this event all file system providers should be registered, not sure about auth providers.

**Comment by JacksonKearl** [comment]
Noticed this had some issues whereby modifications made to the trusted domains during a session didn't get reflected until refresh. Changed to read the user-based trusted domains on auth provider added, workspace-based trusted domains on workspace folder change (should this maybe be workspace state change?), and the others, which run sync, are read on-the-fly.

**Pull request merged**
