### PR TITLE
support next-previous change in editor view #7717

### PR DESCRIPTION
**Pull request by bpceee**
This is for #7717 

keybingdings.json

    { "key": "cmd+down",    "command": "workbench.action.compareEditor.nextChange", "when": "textCompareEditorVisible"},
    { "key": "cmd+up",      "command": "workbench.action.compareEditor.previousChange", "when": "textCompareEditorVisible"},
    { "key": "cmd+down",    "command": "workbench.action.editor.nextChange", "when": "editorTextFocus && !textCompareEditorVisible"},
    { "key": "cmd+up",      "command": "workbench.action.editor.previousChange", "when": "editorTextFocus && !textCompareEditorVisible"}

Welcome suggestions!

### CODE REVIEW

**Comment by ironyman** [comment]
This would be pretty useful. Can we add default keybindings for this?

**Comment by bpceee** [comment]
Thanks @ironyman , I'd also like a default keybinding, but let's leave this kind of decision to team members..

**Review by alexdima — APPROVED** [review]
LGTM

**Review by joaomoreno — CHANGES_REQUESTED** [review]
@bpceee Unfortunately this has issues...

Try to run one of the move actions once and then make a change in the document. The inline diff editor suddenly pops up unexpectedly.

This happens because these actions create the widget, in order to create the model, but just don't show it. So the widget is there waiting to engage. We can't rely on the same machinery for these new actions, it will just create widgets.

Additionally, the select previous/next change actions are based on the one that is currently selected (displayed on the widget). The move previous/next change actions should always be based on your cursor.

**Comment by joaomoreno** [comment]
I ended up implementing this without using the widget. Sorry for not taking the PR, and thanks for your support and work!

**Pull request closed without merging**
