### PR TITLE
WIP: Explore option for multiselect in QuickOpen picker

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR was inspired by https://github.com/microsoft/vscode/issues/66971#issuecomment-1045993327

It is currently WIP. The UX is ready to see and try, but support for actually opening all items in the multiselect case is still a TODO.

Pinging @bpasero

junk

@misolori I'm not sure if I'm following the correct convention for toggle buttons whose icon changes. Mine show the icon representing the state you get after you click it.

I also experimented with `check` and `check-all` but as it's a file picker I decided `file` and `files` made more sense.

### CODE REVIEW

**Comment by bpasero** [comment]
@TylerLeonhardt is the owner of quick pick for a while now.

**Comment by gjsjohnmurray** [comment]
@bpasero thanks for the redirect.

As part of this I changed QuickInputController to permit icons in the customButton label.

**Comment by misolori** [comment]
Initial impressions: I'm not sure I am a fan of having a button toggle as part of the file picker, I'd be more inclined to introduce a new command that opened a multi-select quick pick instead.

**Comment by TylerLeonhardt** [comment]
Yeah I have the same thoughts as @misolori. I think we could have quick access provider specifically for multi-select that might be interesting. If you look for `QuickAccessProvider` in the code, you can see them. Also, if you open the Quick Open and use the prefix `?` you can see them all.

**Comment by gjsjohnmurray** [comment]
A drawback of doing this as a separate quick access provider (triggered by a '+ ' prefix, for example) is likely to be discoverability. I predict a lot of users won't find it.

**Comment by TylerLeonhardt** [comment]
Yeah that's always a challenge with new quick access providers... but I think we want to work on that problem of discoverability in issues like https://github.com/microsoft/vscode/issues/115641

**Comment by misolori** [comment]
The other factor to consider is, how many people are asking for this? When only a small percentage of users want something while introducing more noise to the majority is where it makes it harder to accept changes like these. That's why introducing this as a command or "mode" for those that do want it makes more sense, even if it isn't very discoverable (this isn't the only instance).

**Pull request closed without merging**
