### PR TITLE
Toggle Exclude Resource from Context Menus

### PR DESCRIPTION
**Pull request by rthaneda**
Implemented Feature Request from Issue #71836 with @TejDNagaraja
User can now toggle files and folders to be hidden from VSCode Explorer via Context Menus (see screenshot)
Passes UI Smoke tests

Screen Shot 2019-04-22 at 5 16 00 PM
Screen Shot 2019-04-22 at 5 16 11 PM
Screen Shot 2019-04-22 at 5 15 47 PM
Screen Shot 2019-04-22 at 5 15 29 PM
Screen Shot 2019-04-22 at 5 15 21 PM
Screen Shot 2019-04-22 at 5 15 15 PM

### CODE REVIEW

**Comment by WittHickmanYoung** [comment]
OK, I will have a try. Thanks! @rthaneda

**Comment by isidorn** [comment]
Thanks for this PR. However we do not want this funtionality in the core vscode.
This can easily been handled by the extension and due to that we would prefer if you do this as part of an extension.
We usualy prefer to first start a discussion before submiting a PR, for more details on our contribution guidelines check out this document https://github.com/Microsoft/vscode/wiki/How-to-Contribute
Thanks!

**Comment by noschang** [comment]
> Thanks for this PR. However we do not want this funtionality in the core vscode.
> This can easily been handled by the extension and due to that we would prefer if you do this as part of an extension.
> We usualy prefer to first start a discussion before submiting a PR, for more details on our contribution guidelines check out this document https://github.com/Microsoft/vscode/wiki/How-to-Contribute
> Thanks!

Why do you think it's not a good idea to integrate this feature to the main code?
In my opinion this is a very basic and useful feature and I can't see any reason to download a whole new extension just to add this.

**Comment by isidorn** [comment]
VSCode is minimalistic, even if it is basic we think it is perfectly fine to be done by an extension.
Also if it was that basic and needed 1000+ users would be requesting it.

**Comment by noschang** [comment]
Hi @isidorn. OK. Thanks for your reply

**Pull request closed without merging**
