### PR TITLE
check `shouldPersist` in `detachProcessAndDispose`

### LINKED ISSUE #7642: Built in terminal does not correctly work with nvm/npm
- VSCode Version: Version 1.2.0 (1.2.0) Current Insiders
- OS Version: OSX

Steps to Reproduce:

1. Open the built in terminal
2. Type nvm or npm *

The integrated terminal in the Insider's Builds does not correctly inherit the environment variables that the normal terminal contains. Specifically nvm/npm is not betting picked up. This is not an issue stable build where the terminal works as intended generally, there seem to have been some breaking changes with the terminal since the stable build and it now opens up a "bash" prompt as opposed to my user name and directory.

### LINKED ISSUE #7642: Leaking SSH processes with useLocalServer=false
- Set `"remote.SSH.useLocalServer": false`
- Open a Remote-SSH window
- Note `ps ax | grep ssh | wc -l`
- Reload the window
- `ps ax | grep ssh | wc -l` again, it has increased by 2
- Keep reloading the window, more ssh processes accumulate

I assume this is due to terminal persistence for Remote-SSH's local terminals. Since they are background terminals, they shouldn't be kept alive. I think we've fixed this before. If Remote-SSH should be killing its own terminal to prevent this, we can probably do that too.

### PR DESCRIPTION
**Pull request by meganrogge**
fix https://github.com/microsoft/vscode-remote-release/issues/7642

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
I don't understand this change, it's passing _not_ `shouldPersist` into an arg called `forcePersist`?

**Comment by meganrogge** [comment]
it's super confusing to me too. At first, I made the opposite of that change. But we pass `forcePersist: true` when it's a user's kill action, which we definitely don't want to persist. That's why I knew it had to be `!shouldPersist`

**Comment by Tyriar** [comment]
The detach request happens as a result of the user asking the backend to detach, which we do want to persist, no? Is `detachProcessAndDispose` called somewhere other than the user requesting to detach via the `Terminal: Detach Session`?

**Comment by meganrogge** [comment]
here's what we do on reload of the window - but we don't necessarily want to detach from the process in the case of `isTransient` terminals

https://github.com/microsoft/vscode/blob/beea143b432b485e07f862c55b6c147ae2f5e939/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L639-L646

**Comment by meganrogge** [comment]
Maybe my change was right the first time. I got confused because was thinking we definitely want to kill the process on user kill, but I'll check the pty service logs for this to be sure 

https://github.com/microsoft/vscode/blob/ff95485c9a333147930ff632058c7e44f60c9833/src/vs/platform/terminal/node/ptyService.ts#L669-L679

**Comment by meganrogge** [comment]
Yep, it was correct the first time. I have one normal terminal and one that `isTransient`. Not sure why it's included in the saved state though since we should be filtering it out 

Screenshot 2023-02-03 at 11 04 20 AM

**Comment by meganrogge** [comment]
without the change, we have: 

Screenshot 2023-02-03 at 11 06 37 AM

**Comment by meganrogge** [comment]
Screenshot 2023-02-03 at 11 14 39 AM

**Comment by meganrogge** [comment]
this looks like it's working as expected

**Pull request closed without merging**
