### PR TITLE
makes 'noUpdatesAvailable' info dialogs non-modal and less intrusive

### PR DESCRIPTION
**Pull request by mathiask88**
This PR fixes # - No associated issue

In my opinion the modal info dialog after checking for updates manually is disruptive. The notification service as used for any other notification around the update process is much nicer.

image
image

This is my personal opinion. If there is a specific reason for the modal dialog or you don't like the idea, feel free to close this PR.

### CODE REVIEW

**Comment by mathiask88** [comment]
Any update on this small changes? 
@joaomoreno already removed the modal dialogue for the main update process in https://github.com/microsoft/vscode/commit/7729e9c0810a78bddd8cf760ebbdb28202e6b1ea but for the extension update check there is still a modal one. Could we change that as well as I did in this PR? :)

**Comment by sandy081** [comment]
@joaomoreno Any reason why you have reverted the change (dialog -> notification) ?

**Comment by joaomoreno** [comment]
Please do not bundle these two things together. Product updates are certainly very different from extension updates.

> Any reason why you have reverted the change (dialog -> notification) ?

Yeah, because @bpasero complained, and he's correct.

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Do not combine these two areas. Do not merge this for the product update.

**Comment by sandy081** [comment]
Closing this based on above comment and also it is not addressing any issue

**Pull request closed without merging**
