### PR TITLE
Linux Snap: Prevent GDK_PIXBUF env from leaking out

### LINKED ISSUE #63194: Snap: User fonts are missing
I'm using Fira Code iScript

image

### PR DESCRIPTION
**Pull request by joaomoreno**
This is a nasty one:

- In order to fix https://github.com/microsoft/vscode/issues/63194 and https://github.com/microsoft/vscode/issues/57019, we needed to set some `GFK_PIXBUF` env for our snap executable (PR from Snap team: https://github.com/microsoft/vscode/pull/70884): https://github.com/microsoft/vscode/blob/d4da28357f193bd2d44eb5bd50ff877b8742b22c/resources/linux/snap/electron-launch#L24-L29
- That caused a crash when opening URIs in Firefox (https://github.com/microsoft/vscode/issues/85344), so in order to fix that, the Snap team recommended we delete that env right after startup: https://github.com/microsoft/vscode/commit/7d62a5b857e41d43e62bb6a17aa2fe6bd58019df
- That now causes a crash when opening any native dialog in VS Code in pretty much every Linux distribution other than Ubuntu (#100940)

This PR takes the debacle even further by reverting https://github.com/microsoft/vscode/commit/7d62a5b857e41d43e62bb6a17aa2fe6bd58019df and making sure every single `shell.openExternal` call is wrapped with a unset-set env operation,when running as a Linux Snap. This hopefully fixes both the issue with Firefox as well as the issue with the native dialogs.

- @bpasero: Does the wrapping of `shell.openExternal` make sense and is it in the right place?
- @Tyriar: Does the approach generally make sense to you?

I've triggered a build and I have VMs ready to verify whether it works, will let you know asap.

cc @flexiondotorg @sergiusens

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Overall this looks OK to me, but ideally we could have this logic inside `INativeHostMainService` and everyone else depends on this service. I think it should be possible to use it everywhere.

**Comment by joaomoreno** [comment]
@bpasero I actually started there, but stumbled over that `AddFirstParameterToFunctions` thing and didn't know if passing `undefined` would be OK. If everything works well, I'll adapt the PR to do that.

**Comment by bpasero** [comment]
@joaomoreno yeah that is fine, I use it in `electron-main` too, e.g. here:

https://github.com/microsoft/vscode/blob/0ae821e92d9c47ff6f3ad4c8df80b315397891bf/src/vs/code/electron-main/auth2.ts#L156-L156

**Comment by joaomoreno** [comment]
Fix works great 🎆 Tested Ubuntu, Manjaro and CentOS.

Will refactor tomorrow.

**Review by Tyriar — APPROVED** [review]
Approach seems fine, it's a shame we need to jump through these hoops though.

**Comment by joaomoreno** [comment]
@deepak1556 Says:

> Hey Joao! I was following your work on https://github.com/microsoft/vscode/compare/joao/snap , isn't the core problem related to the incorrect path to gdk-pixbuf-2.0 on these platforms ? for 64 bit we always default to x86_64-linux-gnu https://github.com/microsoft/vscode/blob/master/resources/linux/snap/electron-launch#L8 but the library is under /usr/lib/. Am i understanding the problem incorrectly ?

The actual problem is that Code should always use the gdk-pixbuf inside the snap. But by removing the env very early on (https://github.com/microsoft/vscode/commit/7d62a5b857e41d43e62bb6a17aa2fe6bd58019df) we hit the situation in which the About dialog reads the wrong env and looks up a path which doesn't exist in the snap and falls back to the OS. In Ubuntu this isn't a problem, but in other Linuxes the path doesn't exist.

https://github.com/microsoft/vscode/commit/7d62a5b857e41d43e62bb6a17aa2fe6bd58019df must be reverted, but we still need to address spawning other processes (eg Firefox), that's what this PR does.

**Pull request merged**
