### PR TITLE
clear focused thread if it does not exist

### LINKED ISSUE #133623: debug: toolbar does not update if focused thread no longer exists
- VS Code Version: 1.60.1
- OS Version: darwin/amd64

Steps to Reproduce:
Reported in the vscode-go repo: golang/vscode-go#1648

All threads are stopped expected toolbar to be:

Screen Shot 2021-09-22 at 12 39 23 PM

Instead got:
Screen Shot 2021-09-22 at 12 39 09 PM

This occurs when a stopped event is returned with no threadId AND the previously focused thread no longer exists, then the toolbar is left in the running state with the pause button enabled.

All of the active threads are paused:
Screen Shot 2021-09-22 at 12 25 40 PM

But the focused thread is still running, but actually does not exist anymore:
Screen Shot 2021-09-22 at 12 25 52 PM

The focused thread should be cleared if the thread no longer exists.

### PR DESCRIPTION
**Pull request by suzmue**
When working with multithreaded programs, threads that are focused may not exist at the next stop. Make sure that the focus is not on a non-existent thread, since this will cause the toolbar to fail to update appropriately.

This PR fixes #133623

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks for the PR! Will have to look at it for October

**Comment by suzmue** [comment]
In this case there is no exited event for the thread that was selected. But the future threads request, does not include the thread. I can definitely add a clearing check when the thread exits, but this check later is still important to handle debug adapters that are not as thorough about sending thread events. 

For Go, we use the threads view to present goroutines and would not want to send threads events for every goroutine that is created, since there may be many short lived goroutines. We do not even track the creation / exit of new goroutines, but will look for them when the threads request is sent.

We are also hoping that #116109 will yield some UI improvements.

**Comment by roblourens** [comment]
Ok thanks for the explanation. I am guessing that you set the `preserveFocusHint` flag, otherwise it would have been fixed up above: https://github.com/microsoft/vscode/blob/12ae331012923024bedaf873ba4259a8c64db020/src/vs/workbench/contrib/debug/browser/debugSession.ts#L925

Would it make sense to do fix in that function instead? So the condition would be `if (!event.body.preserveFocusHint && thread.getCallStack().length || threadDoesNotExist) {`

**Comment by rustyx** [comment]
Bump. we need this!

**Comment by suzmue** [comment]
> Would it make sense to do fix in that function instead? So the condition would be `if (!event.body.preserveFocusHint && thread.getCallStack().length || threadDoesNotExist) {`

I moved the logic to also check the condition here. But this also needs to be cleared in the case that there is no thread id returned in the stopped event (the thread id is optional so this case should be handled).

**Review by roblourens — APPROVED** [review]
Seems fine to me, thanks!

**Pull request merged**
