### PR TITLE
Relax condition on select all

### PR DESCRIPTION
**Pull request by JacksonKearl**
This enables `Ctrl+a` to select all in the Extensions Search, Logpoint Editor, and Repl Editor input areas.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
cc: @alexandrudima

**Comment by timjim-kr** [comment]
When will this roll out?  This has been really frustrating over the last 1+ months since it regressed.

**Comment by timjim-kr** [comment]
Thanks, Jackson.  It appears I was still on 1.25.1.  VSCode had been really aggressive about updating on restart over the last few months, but it looks like I had to force it to update on this one for some reason.

That said, I just updated to 1.26 and CMD+a (on Mac) is not selecting all in the cases where I would most often need it: File search, text search within file.

**Comment by JacksonKearl** [comment]
It’s possible, but this was only needed because these inputs use Monaco editors internally. The other inputs are normal html inputs and shouldn’t need special treatment.

**Pull request merged**
