### PR TITLE
replace 'Courier New' with 'monospace' in Linux font list

### LINKED ISSUE #5742: Default font on Ubuntu looks terrible (should we ship a font with vscode?)
- VSCode Version: 1.0
- OS Version: Ubuntu 16.04 

Ubuntu 16.04 (Xenial Xerus) no longer carries `Droid Sans Mono`, this causes font to be rendered with `Courier New` if Linux desktop user installed MS core fonts (more than likely). Given Ubuntu still carries open source fonts such as `DejaVu Sans Mono` or `Liberation Mono`, which are better for LCD than `Courier New`, consider: 
- Adding those to the font list
- Remove `Courier New` from font list - let the OS decide

### PR DESCRIPTION
**Pull request by andyli**
A workaround better than #33319.

Close #5742.

### CODE REVIEW

**Comment by jhasse** [comment]
I've tested it on Fedora 24 and it works as intended: `'monospace'` results in `Liberation Mono` just as `'Courier New'` did. The problem is that if `Courier New` is really installed, it will look terrible (I guess because it was designed with Windows' hinting algorithm in mind, not FreeType's), see https://github.com/Microsoft/vscode/issues/5742#issuecomment-256668325. @Tyriar mentioned that `monospace` doesn't help, but according to https://github.com/Microsoft/vscode/issues/5742#issuecomment-312703328 that seems to be a Chromium bug and should be fixed by adding single-quotes around it just like this PR does :)

**Review by alexdima — APPROVED** [review]
LGTM

**Comment by alexandrudima** [comment]
@Tyriar I see you would also like to test things out. This PR looks good to me. Please feel free to merge once you had a chance to review.

**Comment by Tyriar** [comment]
Yes I wanted to test this on a few distros to verify, targeting October 😃

**Pull request merged**
