### PR TITLE
Exposed Open/Save dialog title on public VSCode Proposed API

### LINKED ISSUE #82871: Expose dialog title in extensions API
The current openDialogOptions are:
```
canSelectFiles?: boolean
canSelectFolders?: boolean
canSelectMany?: boolean
defaultUri?: Uri
filters?:
openLabel?: string
```

Could we also have access to the dialog title?<br />I believe electron does expose it [here](https://electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options).

### PR DESCRIPTION
**Pull request by GustavoASC**
This PR fixes #82871.
Now open/save dialog title is exposed on public VSCode Proposed API.

I've tested on Ubuntu 19.10 with an extension which invokes showSaveDialog() and showOpenDialog() methods. Here's an usage example:

image

The example below shows _My open title_ on the top of Open Dialog.

image

**Note:** on this version of Ubuntu the _Save Dialog_ title is not shown, but it's an OS-related behaviour.
Every save dialog of VSCode running on Ubuntu 19.10 ignores the specified title as can be seen on 'File -> Save Workspace As...' (On Windows it shows 'Save Workspace' but on Ubuntu no title is shown).

### CODE REVIEW

**Comment by aeschli** [comment]
Change looks good to me.

**Comment by GustavoASC** [comment]
@alexr00 do you agree with these changes?

**Comment by alexr00** [comment]
Yes, I just haven't had a chance to merge this yet :)

**Review by alexr00 — APPROVED** [review]

**Comment by alexr00** [comment]
Thank you for the PR!

**Pull request merged**
