### PR TITLE
option to create empty editor splits instead of duplicating

### LINKED ISSUE #107863: Optionally open empty splits instead of copying split window
Pretty much the title. 99% of the time I make a split I want to open another file (possibly drag and dropped from elsewhere), and it's much clearer to have a blank editor than a duplicate wall of text. 

It looks like the copy functionality is pretty hardcoded in the depths of splitEditor so I have a PR that optionally skips it. Would be great if someone could point me how to go about adding to the configuration settings, or suggest another way to do it.

### PR DESCRIPTION
**Pull request by msftwindowslinux**
This PR fixes #107863

### CODE REVIEW

**Comment by bpasero** [comment]
Instead of a setting can we not just introduce new commands that do this?

**Comment by msftwindowslinux** [comment]
> 
> 
> Instead of a setting can we not just introduce new commands that do this?

I'm happy to do that too; wasn't sure if it's more or less intrusive to add more options vs commands.

**Comment by bpasero** [comment]
@msftwindowslinux I just realized we already have these commands: `workbench.action.newGroupLeft`, `workbench.action.newGroupRight`, `workbench.action.newGroupAbove`, `workbench.action.newGroupBelow`, so is there something missing?

**Comment by msftwindowslinux** [comment]
haha looks like that's it, sometimes harder to search the right words on stackoverflow / keybindings, sorry for the dup!

**Pull request closed without merging**
