### PR TITLE
Enable emmet customizations for preferences, profiles and snippets

### PR DESCRIPTION
**Pull request by ramya-rao-a**
#11679

Supporting Emmet Customizations in VS Code using json files as described http://docs.emmet.io/customization/

cc @mrmlnc

### CODE REVIEW

**Comment by mrmlnc** [comment]
My 2 cents:

0. The `_withEmmetPreferences` method has callback then we can use Async API. For example, `Promise.all().then -> callback`. In this case `getEmmetCustimizations` should return Promise.

1. In most cases, the user will not have customizations for Emmet. We can save editor time (FS calls) if we will be check existence of directory before check files. Also we can use Cache for this case, because preferences are updated on each call of Emmet (e.g. `fs.Stats.ctime`)?

2. Also in this case we can use https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/pfs.ts instead of Node Modules.

For example:

```
Promise.CheckExistsOfCustomizationsDirectory
  true: Promise.all([ readCustomizationsFiles }).then -> Update Preferences with files -> Callback
  false: Promise.then -> Update Preferences without files -> Callback

+

Cache
```

Ping/Pong to @egamma

**Comment by egamma** [comment]
Good 2 cents from @mrmlnc. 

@mrmlnc is correct, inside the VS Code Core you must not make sync fs calls and use the `pfs` helper module. `getEmmetCustomizations` needs to use the pfs helper functions and become async and return a `TPromise`.

Also Agreed that you should first check for the `extensionsPath` folder and only if it exists, then look for the different customizations to reduce the number of fs calls.

### Questions:
- how does the user know that the `extensionPath` is misconfigured. When users configure an extension path, then they assumes that the path exists. We should inform the user that the path does not exist. 
- is there a standard emmet extension path that should always be honored, e.g. ~/emmet?
- is it expected that '~' in the `extensionsPath` is expanded so that the user doesn't have to enter an absolute path name? 
- emmet provides a `loadExtensions()` function that we are not using, should we use it? https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/emmet.js#L96. 
- Currently we are hard coding the set of extension files that are loaded `snippets`, `preferences`, `syntaxProfiles`, are this all the supported files? Does emmet also support extensions in `.js` files?
- With regard to caching. What do other emmet integrations do with regard to loading the extensions, load them once on activation only and the user needs to restart when there are changes?

**Comment by mrmlnc** [comment]
My vision of questions:

  1. We can use `MessageService.show()` in this case?
  2. We should expand filepath. Recently, users of my plugins have been many questions on this subject.
  3. See 2.
  4. Yes, Emmet supports `js` files, but https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/emmet.js#L111 (we should create `FileAccessor` for https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/plugin/file.js#L116-L133)
  5. IMO, if file exists then we cache it. I think reboot is a normal solution.

**Comment by ramya-rao-a** [comment]
@egamma @mrmlnc Great points, I have updated the PR accordingly.

A few notes:

- At the moment `~` in the extensions path doesn't work and will not get expanded. I'll look into that separately
- `loadExtensions` in emmet refer to the `js` files that one can write to customize emmet which is out of scope for this PR and feature. There are 3 json files that can be used to customize emmet and that is what we are supporting here.
- Caching: The 3 json files will be read the first time emmet gets loaded and when `extensionPath` changes. I haven't seen what other editors do yet, but this looks like a good starting point.

**Review by egamma — APPROVED** [review]
The notes make good sense to me, thanks and this PR LGTM.

**Comment by ramya-rao-a** [comment]
Thanks @egamma 

@mrmlnc The PR is merged, but do let me know if you have more thoughts on this one.

**Pull request merged**
