### PR TITLE
Add icon explorations into electron-4.0.x

### PR DESCRIPTION
**Pull request by miguelsolorio**
This merges the icon redesign exploration that I've been working on. This uses the file icon themes, to change your theme go to `Preferences` > `File Icon Theme` and select either `VS Code Icon Explorations: Outline` or `VS Code Icon Explorations: Solid`. The default is set to `VS Code Icon Explorations: Outline`.

## VS Code Icon Explorations: Outline
image

## VS Code Icon Explorations: Solid
image

### CODE REVIEW

**Comment by bpasero** [comment]
@misolori this is no longer needed right since we plan to merge to master soon?

**Comment by misolori** [comment]
@bpasero we won't be merging into master until after our next release so I'll still leave this open in case there are any updates to the `electron-4.0.x` branch. I also need my branch to be the latest release build as we're doing user studies next week and don't want to overwrite the changes.

**Comment by bpasero** [comment]
Ok, I am expecting another PR when we merge to master, so I am unasigning myself.

**Comment by misolori** [comment]
This is no longer needed

**Pull request closed without merging**
