### PR TITLE
Add -h/-v command line args and linux/mac launch scripts

### LINKED ISSUE #378: Code --help should show usage
Currently --help just launches the app. The `-n` and `[path]` command line arguments aren't discoverable (see #48).

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #378

### CODE REVIEW

**Comment by Tyriar** [comment]
The usage script currently advertises the executable name as code on non-Windows platforms. This is not the case currently as there is no file in the path when installed on darwin or linux, this should be the case once a proper launch script is created.

@bpasero Are there any command line args I'm missing?
@chrisdias any concerns bringing in an [MIT-licensed](https://github.com/bcoe/yargs/blob/master/LICENSE) dep?

**Comment by bpasero** [comment]
@Tyriar thanks. I am not sure this can live in the application code because e.g. on Windows we have a startup script that makes sure no output from the application is printed to the console. 

@joaomoreno would it make sense to enrich the startup script with this? However we would also need a solution for Mac/Linux.

**Comment by joaomoreno** [comment]
I would love to get a single solution for all platforms. Truth is: starting up Electron is a mess.

**Comment by Tyriar** [comment]
I was actually working on similar scripts for Mac and Linux in order to capture output and not hold the terminal captive which I'm assuming is the reason for the windows script (code.cmd right?). Atom has a similar setup and gets around this by printing the output if `-h`, `-v`, etc. is passed in. That would allow the handling of command line args to be centrally located within bootstrap.js.

**Comment by bpasero** [comment]
@Tyriar but I think bootstrap.js is already too late, we have a script code.js on Windows at least that eats all the output. I would think the handling of "-h" and "-v" has to go in there and idealy is cross plat.

**Comment by Tyriar** [comment]
@bpasero oh I thought maybe that was what `@echo off` was in code.cmd, not too familiar with batch. Regardless if it's code.cmd or code.js, output could just be allowed for a handful of command line args as  it's known that bootstrap.js will handle them and exit(0). That way only the list of commands expecting output has to be implemented per platform (mac and linux could share the same script though).

**Comment by Tyriar** [comment]
Commit 8981819 adds the wrapper script for OSX (not yet tested) and Linux. It assumes the `Code` executable on Linux is located at `/usr/share/code/Code`.

Here's what it looks like on Ubuntu (note I have a new line at the start of my `PS1` which is what the extra `\n` is at the end of stdout):

screen shot 2016-02-03 at 2 00 36 pm

The plan for this script is to be renamed to `code` in the .deb package and be added to the path (and OSX package?).

**Comment by bpasero** [comment]
Talked a little bit with @joaomoreno about this this morning, here are some thoughts on how this ideally works:
* we encapsulate the code to print help into a JS file that we can use across all OS, similar to how Atom is doing it with their atom.js file (see comment on this below)
* on Windows and Linux we can use our installers to put "Code" on the command line
* on Mac we could provide an action from the File menu to "install Code to the path" and then do the right thins to go into the bash profile instead of asking the user to do this manually

As for running a JS file for the output, there are some issues. For one, we do not ship with node so we cannot just execute a JS file to show help (as opposed to Atom, who ships node 0.10.x for their APM tooling). So we have to execute Electron, which has other issues: If we start the full blown thing, we potentially get other output from Electron that we do not want (filed https://github.com/atom/electron/issues/4370). If we use the ELECTRON_RUN_AS_NODE environment variable, it seems that on Windows we cannot log to the console because Electron.exe is not compiled as console application.

As a general rule, we try to avoid dependencies to NPM modules for VS Code unless really needed because NPM modules tend to drag in a huge list of other dependencies and are typically always outdated and hard to keep up to date. If possible, the parsing/printing should just be implemented.

**Comment by bpasero** [comment]
@Tyriar @joaomoreno ok I actually looked into printing something from a JS script via Electron and their ELECTRON_RUN_AS_NODE environment variable to be able to run node and it actually works. Given that I suggest:
* help/version info goes into a script similar to https://github.com/Microsoft/vscode/blob/master/resources/win32/bin/code.js#L3
* this script will be used not just on windows but also linux/mac
* we find ways on all OS to put this script on the path, similar to https://github.com/Microsoft/vscode/blob/master/resources/win32/bin/code.cmd#L1

**Comment by Tyriar** [comment]
@bpasero @joaomoreno sounds good, so I'll rewrite the arg parsing code in code.js and have that spawn the process in the background as it is currently. `*_RUN_AS_NODE` is pretty handy :smiley: 

Also for installation, for OSX we should probably put the script in `/usr/bin` on installation. A program modifying your `.bash_profile` is a bit icky.

**Comment by bpasero** [comment]
@Tyriar I suggest you sync with @joaomoreno. I am assigning this PR to him as I am also soon leaving for vacation.

**Comment by Tyriar** [comment]
@bpasero will do. Enjoy!

**Comment by Tyriar** [comment]
Just pending process for `yargs` at this point.

**Comment by Tyriar** [comment]
The launcher script assumes some files/dirs exist. To get it to work under Linux as is, the following symlinks can be created:

```bash
sudo ln -s <path_to_built_vscode> /usr/share/code
ln -s <path_to_repo_with_change>/resources/common/bin/launcher.js <path_to_built_vscode>/launcher.js
```

Exposing code.sh to path and doing this setup will be handled in https://github.com/Microsoft/vscode/issues/2679 and https://github.com/Microsoft/vscode/issues/229

**Comment by joaomoreno** [comment]
@Tyriar sorry man, I still haven't had the chance to test this, but will do first thing tomorrow morning!

**Comment by Tyriar** [comment]
@joaomoreno no need to test the linux side, if you could look in to #2859 at some point that would be good though to help get rid of the manual set up on OSX.

**Comment by joaomoreno** [comment]
Absolutely, marked it for February. I would like to feel how cool this is. :+1:

**Pull request merged**
