### PR TITLE
Fixes #13905: Set relaunch command for window

### LINKED ISSUE #13905: Middle mouse click on taskbar icon doesn't open a new window
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abotteram.typescript-react-snippets-0.1.9, hars.CppSnippets-0.0.5, lukehoban.Go-0.6.44, ms-vscode.cpptools-0.9.2

Steps to Reproduce:
1. Middle click on running VS Code icon on the taskbar, it doesn't open a new window like many programs
2.  You can open a new window by right clicking the icon and choosing "New Window"

### PR DESCRIPTION
**Pull request by the-ress**
Sets relaunch command to open a new window.

Requires electron/electron#7952.
Fixes #13905.

### CODE REVIEW

**Comment by bpasero** [comment]
@the-ress can you elaborate a bit what `SetAppDetailsForWindow` does in the end?

**Comment by the-ress** [comment]
[`SetAppDetailsForWindow`](https://github.com/nwjs/chromium.src/blob/151b8e5d39b7edcf9eed78ebedf3b4eae9f93d28/ui/base/win/shell.cc#L117) sets these properties for the window (if they're not empty):

- [AppUserModel.ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391569(v=vs.85).aspx) - This needs to be set. Otherwise the other properties are ignored.
- [RelaunchIconResource](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391573(v=vs.85).aspx) - Icon for the taskbar button and the 'launch new instance' taskbar menu item.
- [RelaunchCommand](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391573(v=vs.85).aspx) - Command started by the 'launch new instance' menu item.
- [RelaunchDisplayNameResource](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391572(v=vs.85).aspx) - Label for the 'launch new instance' menu item.

Relaunch command and display name must always be set together. Otherwise neither is used.

image-2016_11_12-18_49_17

**Comment by bpasero** [comment]
@the-ress is there an example of an application that leverages this? if I right click on Chrome for example, I am not seeing a relaunch command.

**Comment by the-ress** [comment]
This is what I see when I right click Chrome:

image

Regular Chrome window doesn't override the relaunch command so it just launches chrome.exe without any arguments.

However if I run a chrome app, it opens a in new window that is owned by the same chrome.exe, but it changes its taskbar icon, name and relaunch command (using `SetAppDetailsForWindow`).

image

The relaunch commands is set to something like `chrome.exe --profile-directory=Default --app-id=ibhkjcfebdanponjgchgcgilkoahbpfh`. So when I middle-click the button (or shift+click, pin it or click the relaunch menu item), it opens the app and not a regular browser window.

**Comment by bpasero** [comment]
@the-ress that is pretty cool. So what your PR actually fixes is that middle click on the task bar icon opens a new window (something many people have asked for and which I was never sure how to do actually).

**Comment by the-ress** [comment]
Yes. (I referenced the issue in the title of this PR.)

**Comment by the-ress** [comment]
The electron part of this was released in [electron 1.4.11](https://github.com/electron/electron/releases/tag/v1.4.11).

**Comment by bpasero** [comment]
Thanks for letting me know 👍

**Comment by Tyriar** [comment]
Please make sure this PR plays nicely with hot exit, see https://github.com/Microsoft/vscode/issues/48#issuecomment-270183828

This needs to be addressed on Linux as well.

**Comment by bpasero** [comment]
@Tyriar not sure it is fair to ask for this in the same PR, maybe we should have a separate PR for the Linux problem.

**Comment by Tyriar** [comment]
I added a new CLI arg `--new-window-if-not-first` which should work for windows if that's the arg the shortcut uses. https://github.com/Microsoft/vscode/issues/48#issuecomment-270714743

**Comment by bpasero** [comment]
I think the new argument will not help in this case, see https://github.com/Microsoft/vscode/issues/48#issuecomment-270726810

**Comment by bpasero** [comment]
Optimistically merging this for April since we plan to land Electron 1.6.x.

**Pull request merged**
