### PR TITLE
Improve "Run Test at Cursor" command

### LINKED ISSUE #137984: "Test: Run Test at Cursor" is too picky
- VS Code Version: 1.62.3
- OS Version: macOS 11.6.1

For C++ tests using the C++ TestMate extension, "Test: Run Test at Cursor" only works if the cursor is on the first line of the test case at column 0. For python tests, it works if the cursor is anywhere on the first line of the test case, up to column 0 of the next line.

This is way too restrictive; if my cursor is on the first line of the test, I can just as well click the green icon that's right next to it. The point of the "Run Test at Cursor" is that it should work when my cursor is anywhere inside the test case (with the beginning of the test case potentially scrolled out of view).

And that's how it worked in Test Explorer UI; I'm missing that behavior.

Now, you might argue that it's the extension's responsibility to set the range of the TestItem appropriately to cover the whole test case. Yes, the C++ TestMate extension sets the range to `{line, 0, line, 0}`, and the Python extension to `{line, 0, line+1, 0}`, hence the behavior described above.

However, I'd argue that this is too much of a burden for extension developers. Most underlying test frameworks only report the starting lines of test cases; actually I'm not aware of a single one that reports where a test case ends. This means that all extensions would have to implement the same heuristic to extend a TestItem's range until either the next item in the same file, or the end of the file if there's no next one. I'd argue that this should be done by the testing framework.

Long story short: I'm proposing to treat the "no-man's land" between two TestItems (or after the last item) in a file as belonging to the item before it.

Does this make sense, @connor4312?

(Cc @matepek, @karthiknadig)

### PR DESCRIPTION
**Pull request by stefanhaller**
Treat the text between two tests as belonging to the previous test; this
improves the behavior for those test extensions that don't provide the full
range of a test case, but only the start line (most do, it seems).

Fixes #137984.

### CODE REVIEW

**Comment by stefanhaller** [comment]
Ping @connor4312

**Comment by stefanhaller** [comment]
@DanTup Would you be able to test this with multiple test items having the same range, please? I don't have a test extension that generates these.

This is similar to https://github.com/microsoft/vscode/issues/133519, except when the cursor is after a test case, not within.

**Comment by DanTup** [comment]
@stefanhaller I haven't got this repo set up to run from source right now, but here's some tweaked code from a test extension I used previously. It just registers some tests on a specific line of whatever file you open, and prints which ones are being run to the console:

```ts
import * as vscode from 'vscode';

let testController: vscode.TestController;

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "overlapping-tests" is now active!');

	let disposable = vscode.commands.registerCommand('overlapping-tests.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World from overlapping-tests!');
	});

	context.subscriptions.push(disposable);


	testController = vscode.tests.createTestController('foo', 'Foo');

	testController.createRunProfile("Run", vscode.TestRunProfileKind.Run, (request, token) => {
		const testsToRun = request.include?.map((item) => `    ${item.label}`).join("\n");
		console.log(`Running:\n${testsToRun}`);
	});
	vscode.workspace.onDidOpenTextDocument((td) => createTestsForFile(td));
	if (vscode.window.activeTextEditor) {
		createTestsForFile(vscode.window.activeTextEditor.document);
	}
	context.subscriptions.push(testController);
}

function createTestsForFile(td: vscode.TextDocument) {
	testController.items.replace([
		createTest(td.uri, 1, 1),
		createTest(td.uri, 1, 2),
		createTest(td.uri, 3, 1),
		createTest(td.uri, 3, 2),
	]);
}

function createTest(uri: vscode.Uri, line: number, testNum: number) {
	const test = testController.createTestItem(`l${line}t${testNum}`, `line ${line} test ${testNum}`, uri);
	test.range = new vscode.Range(new vscode.Position(line - 1, 0), new vscode.Position(line - 1, 1));
	return test;
}

export function deactivate() { }
```

You'll need to activate the test first (by running the "Hello World" command, or changing `activationEvents` to `*`). Hope this helps!

**Comment by connor4312** [comment]
Thanks!

**Pull request merged**
