### PR TITLE
More tightly couple crash reporter and telemetry level

### PR DESCRIPTION
**Pull request by lramos15**
This ensures the runtime args are dynamic with the telemetry level.

@bpasero What's the overhead like for doing this file write on every startup? We're already doing the file read so I assume it's ok

### CODE REVIEW

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
Looks reasonable to me. Though Ben would know better of course.

**Comment by lramos15** [comment]
> Looks reasonable to me. Though Ben would know better of course. edit: it got auto merged - maybe I should not have approved so we wait for Ben's feedback - sorry about that!

Can always make another PR :p

**Comment by bpasero** [comment]
@lramos15 not a big fan, given https://github.com/microsoft/vscode/issues/159650 we dont actually know if the phase in which this happens may block the window from opening or not. So for now I suggest to avoid more pressure on the main process, even if this is after window opening.

Irrespective, I think always writing to a file even if it may have not changed seems odd too, what is the purpose here and surely it can be done more efficiently?

**Comment by lramos15** [comment]
> Irrespective, I think always writing to a file even if it may have not changed seems odd too, what is the purpose here and surely it can be done more efficiently?

It seems like you fixed this is another PR so thank you for that as this should greatly reduce the load and only rewrite upon telemetry level changes. The purpose of this is that when the user changes their telemetry level the runtime argument for the crash reporter should change as well since that runtime argument is how we determine if the crash reporter is enabled or disabled

**Comment by bpasero** [comment]
Refs: https://github.com/microsoft/vscode/commit/31c8928c68ee0db73dccdc0828448e9a6c63333c#diff-ce90ef6ffd304cc541efa8135dc4878c7b61889d2b2d5ef69e196af6cea7647bR1271

**Pull request merged**
