### PR TITLE
Treeview multiselect is flakey

### LINKED ISSUE #208802: Treeview multiselect is flakey
I've been adding multi-select support to GitLens treeview and noticed a few issues with tree views with `canSelectMany` enabled

Using `shift-click`, `ctrl-click` don't usually work correctly the "first" time, but seem to (usually) fix themselves on repeated attempts.

https://github.com/microsoft/vscode/assets/641685/3b90fb79-37db-49ed-9a88-1db52e0d3217

In the above, I've made a quick modification to the TreeView Sample to enabled `canSelectMany` and just added a few more nodes to make it easier to see. And then clicked the first node, and then `shift-click`ed the last, and you can see that it didn't fully select all the nodes in between. But when I repeated the `shift-click` it fixed it. 

I am not sure what causes it to work/not work sometimes and not others -- but it always seems to not work the first time, but there are other cases when it is just flakey.

/cc @alexr00

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #208802

### CODE REVIEW

**Review by alexr00 — COMMENTED** [review]
The `rerender` comes from here:

https://github.com/microsoft/vscode/blob/fa74810f958f5896c87d538860b46a9d644e4ba3/src/vs/workbench/browser/parts/views/treeView.ts#L773-L777

That event is fired when the menu that has the inline actions has it's context change, which is expected to happen during multiselect.

**Comment by alexr00** [comment]
@joaomoreno moving to June.

**Comment by joaomoreno** [comment]
@alexr00 I would really love to get clear repro steps, on an extension sample. I just tried to repro this locally and really can't, despite watching all the videos in #208802.

**Comment by alexr00** [comment]
Here's a branch in the extension samples that shows the flake: https://github.com/microsoft/vscode-extension-samples/tree/alexr00/treeViewMultiselectFlake
Steps:
1. Open the tree-view-sample, npm install, and F5.
2. Open the "Test View"
3. Left click on "e"
4. Shift click on "a"
5. I expect all the nodes between "e" and "a" to be selected, but they aren't.

**Comment by alexr00** [comment]
@joaomoreno let me know if there's any other information I can provide for this!

**Comment by alexr00** [comment]
Well, I could repro 100% of the time at the time that I created the PR, but it appears to be fixed now.

**Pull request closed without merging**
