### PR TITLE
Make diff gutter decorators width configurable

### PR DESCRIPTION
**Pull request by usernamehw**
https://github.com/Microsoft/vscode/issues/39325#issuecomment-356243773

cc @joaomoreno

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Writing code by following the ts standards might be good for you.

**Comment by usernamehw** [comment]
@joaomoreno, is this gonna make it into **1.20**?

**Comment by joaomoreno** [comment]
@usernamehw Sorry, we'll get here eventually... you'll have to be patient.

**Comment by joaomoreno** [comment]
@usernamehw I believe you're going to have to resubmit this PR. Github can't seem to access the patch: https://github.com/Microsoft/vscode/pull/41370.patch

**Pull request closed without merging**
