### PR TITLE
add toml fixes: #51704

### PR DESCRIPTION
**Pull request by oneslash**
- add toml syntax
- add tests

### CODE REVIEW

**Comment by oneslash** [comment]
@mjbvz, could you please check my PR?

**Comment by mjbvz** [comment]
Thanks! This will be in the next vs code insiders build and scheduled to go with VS Code 1.28

**Comment by mjbvz** [comment]
After further discussion with the VS Code team, we have decided to revert this PR with f2f8b7cb08d80184d1df76234b236760ae9a72f5 See that issue for an explanation of why we feel this is the correct decision for guiding users to a better toml experience and for maintaining VS Code itself

Thank you for your contribution. I apologize that I did not ensure everyone was in agreement on our side before encouraging and accepting this PR

**Comment by oneslash** [comment]
No problem, the explanation is extensive

**Comment by nealot** [comment]
> * For the best toml experience, users should use one of the toml plugins from the marketplace as these provide intellisense and other advanced language features. We previously recommend these plugins when you opened a toml file. However if we ship a bundled toml grammar, these recommendations will no longer appear

VSCode comes with basic support for yaml even though there's a [popular yaml extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) with more features. I feel like if a developer was dissatisfied with basic support for a language, they would check the marketplace for something more suitable. 

When I first started using vscode, I installed a yaml extension because I was unhappy with just the default syntax highlighting. One of the best things about vscode is how the ux makes discovering extensions really easy for newbies, so I don't understand why basic support would discourage people from installing other extensions. If a user is happy enough to not look for alternatives, why is this a bad thing?

Some people would really just like some syntax highlighting for files that they only occasionally visit. I only spend a couple minutes with .xml or .toml files so I don't need errors like these before I finish typing "true":

screenshot_20181001_170429

> * Engineering maintenance costs on our side. Updating the grammar, maintaining tests, and handling issues related to it are all extra work that has to be considered.

I was personally satisfied enough with this PR that I ditched Better TOML for good. I'm not really keen on having intellisense for a language that tries to be minimal so it was just annoying. I wouldn't even mind if the team stopped updating the extension grammar, I just want some simple highlighting.

> For the best toml experience,

Funny enough, this was my best toml experience :laughing:

**Comment by oneslash** [comment]
@nealot, you have very strong points, however, @mjbvz has truth too.

I have a proposal, if we have a basic support for languages, to prompt a user with a bottom right notification saying "this is a basic support for (YAML | TOML | ETC.) if you would like to have advanced features please look into our extension marketplace ". WDYT @mjbvz?

**Pull request merged**
