### PR TITLE
document.isDirty appears to report false for dirty untitled document (fixes #723)

### LINKED ISSUE #723: document.isDirty appears to report false for dirty untitled document
Context: Vim extension.

```typescript
private doQuit(textEditor : vscode.TextEditor) {  
		if ((textEditor.document.isDirty || textEditor.document.isUntitled)  // if I don't check for this, isDirty reports false for untitled document
			&& !this.args.bang) {  
				throw new Error("unsaved changes");  
		}  
...
}
```

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Comment by bpasero** [comment]
@jrieken turns out, we already dispose the untitled model when it gets saved, the only thing missing is to set the dirty flag in the dispose, I think that is a fair thing to do.

**Comment by jrieken** [comment]
@bpasero Can you also make that change to the unit test?

**Comment by bpasero** [comment]
@jrieken done :+1:

**Comment by jrieken** [comment]
Done. Thanks

**Pull request merged**
