### PR TITLE
wrap handler for resize observer in requestAnimationFrame()

### PR DESCRIPTION
**Pull request by kfrederix**
Wrapping the `ResizeObserver` callback in `requestAnimationFrame()` should avoid the "loop limit exceeded" error which pops up under certain circumstances.

(fixes #183324)

### CODE REVIEW

**Review by thari — APPROVED** [review]

**Review by Hypenate — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Comment by kfrederix** [comment]
@microsoft-github-policy-service agree

**Comment by kfrederix** [comment]
@alexdima thank you for taking care of this!! :pray:

**Review by simonh1000 — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]

**Comment by kfrederix** [comment]
@alexdima I see that we have enough approvals. Is it ok to close this PR?

**Comment by simonh1000** [comment]
Is this fix being added to Monaco - that's where I need it

**Pull request merged**
