### PR TITLE
Display warning banner when workspace lies within appRoot (#138815)

### LINKED ISSUE #138815: Windows: Warn users when opening a folder inside VS Code's installation directory
Issue Type: <b>Bug</b>

I was doing some projects on my and had saved them properly , but now none of them are there and everything has been erased. In VScode it shows it had opened them early but nothing is there now, everything has been erased including alot of hardwork i had put on those projects.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.84GB free)|
|Process Argv|--crash-reporter-id b519655f-0e31-4412-b139-3fb603b4c088|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
java|red|1.1.0
vscode-java-debug|vsc|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #138815.

image

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
I just spotted the INativeEnvironmentService layer breaker. @bpasero maybe you can suggest the right way to resolve this.

**Comment by bpasero** [comment]
Yes I am on it.

**Comment by bpasero** [comment]
Thanks! Moved it into a place where we already show warnings.

**Review by bpasero — APPROVED** [review]

**Pull request merged**
