### PR TITLE
inline values

### PR DESCRIPTION
**Pull request by isidorn**
To address #13424

Chrome dev tools does this feature nicely, a picture for reference
screen shot 2016-11-25 at 16 24 13

### CODE REVIEW

**Comment by isidorn** [comment]
I have added an empty method with documentation on how this should behave
Some docs on developing vscode can be found [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)

@nojvek give it a try and let me know how it goes. I plan to continue on this on Monday unless you take it over.

**Comment by nojvek** [comment]
I'll take a stab. For this version, the scope ranges are not coming from the debugger API's right? The idea is to go through stack frames until global. Do a regex search for variable names and show decorators after line?

**Comment by isidorn** [comment]
For the first version just ignore the scope ranges - since they are only supported by the node2 debug adapter, and it would be cool to have this feature for all 20+ adapters that exist.

No, the idea is to just go through the focused stack frame and go inside all the non expenisve scopes fo that stack frame. No regex search, just a regular compar of does a variable name match a word.

**Comment by nojvek** [comment]
Yeah that's what I meant.

Basically.

Scopes = getCheapScopes(activeFrame)
Ranges = Scopes.map(scope => active editor.getText().match(/\b${scope.name
}\b/g)

Decoratortype  = new decoratortype(...)
DecoratorInstances = createDecoratorInstances(scopes, ranges)

Activeeditor.setDecorator(decoratortype, DecoratorInstances)

Writing this from a phone so camelcasing is misplaced

**Comment by isidorn** [comment]
Instead of mathcing against scope.name, you would match against something like scope.getChildern().then(children=> children.forEach(child => match child.name))

Also not sure about doing regex across whole text content of editor. I would prefer if you instead go through all the words in the text document since editor already parses the words nicely, and then word by word you can try to find across all variable names

**Comment by nojvek** [comment]
I see. I didn't realize that.

I would guess that for showing the gray highlights for matching words,
monaco builds an internal word => ranges map.

I'll hunt for the API and use that.

**Comment by isidorn** [comment]
For gray highlihgts we are using a json parser and look for keys. Not useful for this scenario.

**Comment by nojvek** [comment]
I have a prototype working.

image

Have some issues though.

2) How do I get list of words in a line. I couldn't find an exposed api. I am currently calling editor.getLines() and doing a single regexp match for each line which is composed from variables in scope. e.g ```const namesRegex = new RegExp(`\\b(${Object.keys(nameValueMap).join('|')})\\b`,'g')```

3) How do I call registerDecorator as an exposed api. Currently I'm hacking it so I can get the decorators working. There must be a nicer way. this.editor['_registerDecorationType'](...)

**Comment by isidorn** [comment]
@nojvek awesome! Let's continue the discussion in https://github.com/Microsoft/vscode/pull/16129

**Comment by isidorn** [comment]
Closing this ass all the interesting work is done in https://github.com/Microsoft/vscode/pull/16129

**Pull request closed without merging**
