### PR TITLE
Add stdout and stderr mimetype

### LINKED ISSUE #117273: Updating appending/updating output in Notebooks does not work as expected
- VS Code Version:OSS
- OS Version: Mac

Steps to Reproduce:

1. Use VSC API to add/replace outputs to create multiple does not work as expected
2. Sample code can be found here https://github.com/microsoft/vscode/pull/117272

**Requirement in Jupyter**
* We need to have two output items, one for stdout & another for stderr.
	* As we get new output for stderr, we'll update the stderr output by appending the corresponding output items to that output.
	* Similarly when we get new output for stdout, we'll append output items to that output.
* With the existing API, it doesn't seem to create multiple outputs.

@rebornix @jrieken /cc

Does this issue occur when all extensions are disabled?: N/A

### PR DESCRIPTION
**Pull request by jrieken**
This fixes https://github.com/microsoft/vscode/issues/117273

### CODE REVIEW

**Comment by jrieken** [comment]
@rebornix I am hitting a limitation in the renderer world here. I want outputs of type `application/x.notebook.stderr` to be merged with the mime type but I don't want it to be merged with `application/x.notebook.stream` (or, new for symmetry `application/x.notebook.stdout`). The `supportAppend` logic in the cell view model doesn't seem to support this

**Comment by rebornix** [comment]
I'll add support for that today.

**Comment by jrieken** [comment]
> I'll add support for that today.

👀

**Comment by rebornix** [comment]
My day is simply too long.

**Pull request merged**
