### PR TITLE
Extension install count, use current locale for number formatting Fixes #29491

### LINKED ISSUE #29491: Format the extension download count with commas
Would be easier to read as 2,545,308.

image

Also this might depend on the locale; Japanese for example counts by 10000, not 1000. Not sure if this looks natural.

### PR DESCRIPTION
**Pull request by cleidigh**
See #29491 for discussion
sorry had to squash commits

### CODE REVIEW

**Comment by cleidigh** [comment]
@sandy081 
Just want to check if there's one minor is okay to close out.
Cheers

**Comment by Tyriar** [comment]
Ping @sandy081, not sure if we want to do this for German (https://github.com/Microsoft/vscode/issues/29491#issuecomment-316936743).

**Comment by cleidigh** [comment]
@sandy081 
Do you have an opinion on whether to use appropriate locale format or commas always?

**Comment by sandy081** [comment]
@cleidigh Sorry for the delay.

Is there a reason why not using [toLocaleString](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) api?

**Comment by Hirse** [comment]
Does `toLocaleString` require a locale in this case or would it default to the correct one?
It one is required, how would the correct locale be retrieved?

I put the original comment because [this](https://github.com/cleidigh/vscode/blob/cc583e27bcb40b4a5e3f95395a3b2bdb6ded0365/src/vs/workbench/parts/extensions/browser/extensionsWidgets.ts#L84) looked wrong to me:
```js
installLabel = installCount.toLocaleString('en');
```

**Comment by cleidigh** [comment]
@sandy081 
No problem, I know you guys are busy with the multi-root stuff , great new addition!

@Hirse / @sandy081 
My inclination was to use platform.locale thus using the correct number formatting for any locale.
I did the PR just using the English locale (always commas) given others comments on simplicity.
I can change it to:

installLabel = installCount.toLocaleString(platform.locale);

**Comment by sandy081** [comment]
@cleidigh Yeah, using the locale makes sense to me. Can you please change it accordingly? Thanks.

**Comment by cleidigh** [comment]
@sandy081 
Done.
Sorry for the protracted discussion on a one liner !

**Comment by sandy081** [comment]
LGTM. Thanks for the PR.

**Pull request merged**
