### PR TITLE
Fix #16100 - Add `Git: Pull From` action

### LINKED ISSUE #16100: Be able to "git pull from" different places like "git push to"
In VS Code we able to push git repos to different places with "git push to" and choosing the remote server to push. I'll be nice if we can be able to choose from the repo to pull files, and manage the default remote, today the first remote repo added is the default isn't possible to change that via VS Code

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
CC: @joaomoreno as assignee to #16100

### CODE REVIEW

**Comment by joaomoreno** [comment]
Delaying this due to the upcoming SCM feature.

**Comment by joaomoreno** [comment]
@Krzysztof-Cieslak So sorry to let you know that I'll have to close this since the old Git world is deprecated.

I'd happily accept a PR on the new [git extension](https://github.com/Microsoft/vscode/tree/master/extensions/git). Or I can also implement it, I just don't want to step on your toes. Let me know what you want to do. 👍

**Comment by Krzysztof-Cieslak** [comment]
@joaomoreno, I guess I should be able to add it again ;) Will try to do it later this week.

**Comment by joaomoreno** [comment]
@Krzysztof-Cieslak Thanks man!

**Pull request closed without merging**
