### PR TITLE
Add selection parameter to vscode.open command

### PR DESCRIPTION
**Pull request by nicksnyder**
Allow extensions to specify text to select when opening a document via the vscode.open command.

### CODE REVIEW

**Comment by jrieken** [comment]
Not a fan. The open command is meant to be generic, opens webpages etc, etc. @nicksnyder Why can't you use the APIs we offer for this?

**Comment by nicksnyder** [comment]
What APIs are you referring to? I scanned through vscode.d.ts and didn't see another way to open a text document with a selection (from an extension), but I may have missed something.

**Comment by nicksnyder** [comment]
This could also be implemented as a brand new API/command if you are worried that the open command shouldn't be used in this way.

**Comment by eamodio** [comment]
Seems like adding this option to the `showTextDocument` api would be a better alternative than `vscode.open`

**Comment by jrieken** [comment]
It's two steps,(1) call `showTextDocument` and (2) set the selection on the editor it returns. I don't see justifying new API that combines there two calls

**Comment by nicksnyder** [comment]
Ah, I didn't realize you could just assign to editor.selection. No need for this.

**Pull request closed without merging**
