### PR TITLE
Enable "in" expression for URI context keys

### LINKED ISSUE #147732: URIs in context keys
We have a 'resource' context key which has the full URI of the open editor. Even though it's a URI type, it's actually used as a string:

https://github.com/microsoft/vscode/blob/204d0247033ab7d2f6d1949ae6fd6d87e46a91b3/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L254

and it only works as a string. The equals expr coerces the real URI to a string:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/platform/contextkey/common/contextkey.ts#L457

and the "in" expr, which I want to use, doesn't work with URI objects because it's checking object equality.

So I suggest that we change the type to just be a string that only contains the toStringified URI. Does that make sense or am I missing something about how this is meant to be used?

### PR DESCRIPTION
**Pull request by roblourens**
Fix #147732

Use the same == as the equals expr, and check toString if available. Could be generic like this or specifically URI-aware

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
This can easily backfire because the default `toString()` on objects produces `[object Object]`, which can easily lead to many `in` expressions now evaluating to true because we would be always comparing `[object Object]` against `[object Object]`. 

I'm sorry that I'm not 100% sure how to tackle this URI equality. Should we maybe adjust the equals context key expression to be URI aware?

cc @jrieken for thoughts. https://github.com/microsoft/vscode/issues/147732 for more context.

**Comment by roblourens** [comment]
Yeah. Seems like you aren't really "supposed" to use arbitrary objects, it seems like what is supported in these expressions is basically primitives and URIs as a special case. But if that's true, probably better to add specific handling for URIs.

**Comment by jrieken** [comment]
> cc @jrieken for thoughts. https://github.com/microsoft/vscode/issues/147732 for more context.

Should we limit context keys to be primitive values and force the two URI usages to be fed into contexts in their string form?

**Comment by roblourens** [comment]
We can do that, we just need to stringify the URI somewhere after it has been uri-transformed.

**Comment by jrieken** [comment]
I sketched up https://github.com/microsoft/vscode/pull/147926 to explore allowing only primitive values in context keys. Needed some explicit typings here and there but also has compile errors because it looks like real objects (widgets, model objects, etc) have found their way into the context key service. Tho, I generally feel that's the better direction and good cleanup. What do you think?

**Comment by roblourens** [comment]
Does that affect using objects and arrays with the 'in' keyword https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator or does it only affect the values in the objects and arrays?

**Comment by jrieken** [comment]
> Does that affect using objects and arrays with the 'in' keyword [code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator](https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator) or does it only affect the values in the objects and arrays?

Fair point - I wasn't are of that. Looks like primitives or arrays/objects of those. I'll update my PR

**Pull request closed without merging**
