### PR TITLE
Add ability to reverse the sort order in explorer

### LINKED ISSUE #149951: Reverse sort order in explorer
As a user, I want to be able to reverse the file order in explorer, so that I can see oldest/ latest in alphabet first.

## Example
`Explorer : Sort Order` set to `default` gives you
```
- 001-abc
- 002-dfg
- 003-efg
```
With `reverse order` enabled:
```
- 003-efg
- 002-dfg
- 001-abc
```
## Explanation

I use vscode not only for coding, but for writing my blog too. Files are named like this: `2022-05-19-article-title.md`.
**Example:**
Screenshot 2022-06-14 at 11 04 55

Old articles are the first in line and ordering them by `modified`, does not always help as some of them got touched later, to update them, or fix typos. As you can see in the screenshot below, using modified basically results in a rather chaotic order: 
Screenshot 2022-06-14 at 11 06 40

It would help if I can reverse any set order by setting an option.

### PR DESCRIPTION
**Pull request by lioman**
- add option to settings
- adapt interfaces
- reverse sort order in FileSorter if option is set

This PR fixes #149951

### CODE REVIEW

**Comment by lioman** [comment]
Any news on that @lramos15  - can I help to push this through?

**Comment by lramos15** [comment]
Not sure we want to add a third sort option, maybe this could go under `explorer.sortOrder`. Also we get a lot of sort option requests in general so not sure if we will be taking this in or investigating ways for extensions to provide sort orders to help cover everyone's needs.

**Comment by lramos15** [comment]
Yes but I wonder if we should just do `Sort order` as one option and then `Sort order - reverse` as the other. Basically doubling the list instead of having a third option, I'm not sure. The downside being that will grow the list quite a bit.

**Comment by lramos15** [comment]
Yeah that makes sense. I still wish there was an easy way for extensions to contribute sort order since we get a lot of sort asks in general and cannot maintain them all.

**Review by id-ekaagr — APPROVED** [review]
Please bring your attention here, for some dev this is a must have feature and this "reverse sort order in explorer" is not even a big ask.

**Comment by lioman** [comment]
This would be really valuable and a small change. Is there anything I can do to support this change @lramos15

**Review by lionel42 — APPROVED** [review]

**Review by brl0 — APPROVED** [review]

**Comment by id-aditya** [comment]
@connor4312

**Review by lramos15 — APPROVED** [review]

**Comment by lramos15** [comment]
Thanks for the contribution @lioman. And thanks for being patient. I was trying to debate better ways to do this as it opens the door to 100 other sort feature requests that we will have to maintain, but I understand the want for a simple reverse and don't want to continue to hold this feature back.

**Comment by id-aditya** [comment]
@lramos15 I know it's not the right place to ask. But I want to be shameless for a minute and ask what's the future of: https://github.com/microsoft/vscode/issues/519

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
