### PR TITLE
Use playwright for unit tests

### PR DESCRIPTION
**Pull request by jrieken**
This PR is an experiment of running our unit tests in webkit, chromium, and firefox using playwright. This can complement our current "run in electron renderer"-approach but only tests from/for the browser-layer can be run. 

**Open problems:**

* [ ] Using Firefox doesn't work me...
* [x] Using `**/test/**/{common,browser}/**/*.test.js` pulls in tests that somehow depends on node modules. That is a sign of bad layering somewhere...
* [x] we have `./test/assert.js` (copied from node) without `deepStrictEqual` and did an improper "implementation" of it (default to to deepEqual)
* [x] use of `Buffer` and `process` (and even more?)

**Try out:**

```
> yarn && node ./test/browser/index.js --run "**/{strings,arrays}.test.js --browser chromium"
```

### CODE REVIEW

**Comment by jrieken** [comment]
fyi @bpasero @Tyriar

**Comment by jrieken** [comment]
@bpasero Looks like many of the workbench tests make false claims about the layer in which they can run. I don't yet see the full dependency graph but I get loader errors like this:

```
vs/workbench/test/common/editor/editorDiffModel.test{
  	"phase": "loading",
  	"moduleId": "crypto",
  	"neededBy": [
  		"vs/platform/environment/node/environmentService"
  	]
```

**Comment by bpasero** [comment]
I am checking to split up `workbenchTestServices` into the layers...

**Comment by jrieken** [comment]
Thanks @bpasero

**Comment by bpasero** [comment]
@jrieken done via https://github.com/microsoft/vscode/commit/4f4e26aec864e324d48ba558de20d9029e93b405

**Comment by bpasero** [comment]
@jrieken I did a quick pass over our existing tests and moved a few to `browser` or `common` where possibly. I left all of the `extHost` & `mainThread` tests which live in `electron-browser` but possibly could move a well to you. 

PS: there was some `mock` stuff in `electron-browser` used by those that I moved into `workbenchTestServices` in `common`.

**Comment by jrieken** [comment]
Thanks @bpasero. Much better now, I still see usage of `Buffer` and `process`. I will push changes for low hanging bits

**Comment by jrieken** [comment]
merged so that we can go forward with this, I will create separate issues for failing tests and remaining work

**Pull request merged**
