### PR TITLE
Allowing a user to change screencast mode overlay position and height/width from settings.

### PR DESCRIPTION
**Pull request by matt-april**
* Added a new category to the workbench settings, `Screencast Mode` underneath `Zen Mode`.  This gives us a place to put future screencast mode settings as more are requested.

* Added 4 new settings to the `Screencast Mode` category, `Vertical Position`, `Horizontal Position`, `Height`, and `Width`, with default values that match the current hard coded values. 

* Updated `developerActions.ts` to pull the styles used for this overlay from the settings.

This fixes issue #66676.

### CODE REVIEW

**Comment by mattkwiecien** [comment]
@joaomoreno Any chance I could get a reviewer on this PR?  Wanted to make sure this PR doesn't slip through the cracks!

**Comment by joaomoreno** [comment]
@mattkwiecien Large backlog: https://github.com/Microsoft/vscode/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+assignee%3Ajoaomoreno

**Comment by mattkwiecien** [comment]
> @mattkwiecien Large backlog: https://github.com/Microsoft/vscode/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+assignee%3Ajoaomoreno

oh my... haha, no worries just wanted to make sure this didn't split through the crack!

god speed.

**Comment by joaomoreno** [comment]
I've just kept the vertical offset setting, I don't think we really need the other ones. Thanks! :beers:

**Pull request merged**
