### PR TITLE
expose waitOnExit in vscode.TerminalOptions for extensions

### PR DESCRIPTION
**Pull request by tdyas**
This PR exposes to extensions the the existing `waitOnExit` attribute on terminals.

### CODE REVIEW

**Comment by Tyriar** [comment]
@tdyas what's your use case? Is there some issue reference related to this PR?

**Comment by tdyas** [comment]
I didn't file an issue.

Background: My company has an extension to run a command-line test runner in a Terminal pane. We have to either sleep or wait for input in order to prevent the terminal pane from closing before the developer has a chance to see the output.

Given the existence of `waitOnExit` in the internal API, it would be nice to just leverage that existing functionality.

Is there any reason why waitOnExit is not already exported to extensions?

**Comment by dbaeumer** [comment]
Agree, this sound more like a use case for a task provider.

**Comment by tdyas** [comment]
I've looked at the task API, but it doesn't seem to have a way for the extension to access the output of the command that is run as a task. Whereas `vscode.proposed.d.ts` documents a `onDidWriteData` event for the terminal API  which I would assume is coming soon

Also are there any good examples of using the Task Provider API to customize tasks for the contents of a specific source code file?

**Comment by dbaeumer** [comment]
I wrote some additional documentation for tasks yesterday. Will be available as soon as we ship the next version of VS Code. What do you mean by:

> to customize tasks for the contents of a specific source code file?

**Comment by tdyas** [comment]
As I understand the docs, `resolveTasks` can be used fill in information to complete tasks. Are there any good examples of using it, e.g. for a "Run test" task provider how would resolveTasks be used to create a task for each test in a file?

**Comment by dbaeumer** [comment]
@tdyas no, the tasks need to be provided from `provideTasks` which is only called when necessary (e.g. the user presses Run Task). The idea of resolveTasks is to resolve incomplete tasks when available (but currently all task are complete. They have a Process or ShellExecution).

**Comment by Tyriar** [comment]
I'm closing this and unsubscribing as I don't think we should make this ext API, @ me if you need me 😄

**Pull request closed without merging**
