### PR TITLE
Reverse the initialization sequence for web worker ext host

### PR DESCRIPTION
**Pull request by joaomoreno**
After a brief discussion with @alexdima, we figured out a better initialization routine for the web worker extension host would be for the main thread side to create the `MessageChannel` and pass along the `MessagePort` instead of the current reverse flow.

I've tested the following scenarios:
- Electron extension host: no changes ✅
- Electron web worker extension host: works ✅
- Electron remote extension host: no changes ✅
- `yarn web` with iframe: works ✅
- `yarn web` without iframe: works ✅

Includes some drive-by improvements such as better typing as well as as waiting for the iframe to be loaded before sending out the init message.

### CODE REVIEW

**Review by alexdima — APPROVED** [review]
👏 Looks good, works good!

**Review by raghavthind2005 — APPROVED** [review]

**Comment by jrieken** [comment]
The reason for the "reverse flow" is that it guarantees that the worker is ready when message ports are send. I see that you are waiting for iframe-readyness but I don't know how in-flight messages are dealt with. What happens in case it takes forever to load/start the worker? Are messages still dispatched?

**Comment by joaomoreno** [comment]
[The spec](https://html.spec.whatwg.org/multipage/web-messaging.html#message-channels) appears to confirm that everything will be buffered until someone starts listening:

- Each `MessagePort` object also has a task source called the port message queue, initially empty. A port message queue can be enabled or disabled, and is initially disabled.
- The `start()` method steps are to enable this's port message queue, if it is not already enabled.
- The first time a MessagePort object's `onmessage` IDL attribute is set, the port's port message queue must be enabled, as if the `start()` method had been called.

**Comment by jrieken** [comment]
You are referring to the message ports spec but I am wondering about worker/iframe postMessage/onmessage

**Comment by joaomoreno** [comment]
> When posting a message to a Window of a browsing context that has just been navigated to a new Document is likely to result in the message not receiving its intended recipient: the scripts in the target browsing context have to have had time to set up listeners for the messages. Thus, for instance, in situations where a message is to be sent to the Window of newly created child iframe, authors are advised to have the child Document post a message to their parent announcing their readiness to receive messages, and for the parent to wait for this message before beginning posting messages.

Good point, [the spec even warns here](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-window-postmessage-options-dev). Let me see.

**Comment by joaomoreno** [comment]
I replaced the _waiting for the iframe to be ready_ with _waiting for a message_ part. Let me know what you think.

**Comment by joaomoreno** [comment]
Closing this, after discussion with @jrieken and @alexdima.

**Pull request closed without merging**
