### PR TITLE
fix: performance issues on large context menus

### LINKED ISSUE #136237: Freeze on scrolling tests
Issue Type: <b>Bug</b>

Requirements: pytest

```python
import pytest


@pytest.mark.parametrize('a', [1, 2])
@pytest.mark.parametrize('b', [1, 2, 3])
@pytest.mark.parametrize('c', ['a', 'b'])
@pytest.mark.parametrize('d', [True, False])
@pytest.mark.parametrize('e', [True, False])
@pytest.mark.parametrize("f", [True, False])
@pytest.mark.parametrize('g', [True, False])
@pytest.mark.parametrize('h', ['A', 'B'])
def test_create_commands(a,b,c,d,e,f,g,h):
    pass
```

https://user-images.githubusercontent.com/1027857/139619351-72c94a46-9a67-40d5-beeb-660f56e92cd4.mp4

Discover tets, click on gutter-button, and scroll tests with a mouse (vscode consume a lot of CPU and freeze) 

Extension version: 2021.11.1400738762-dev
VS Code version: Code - Insiders 1.62.0-insider (ff1e16eebb93af79fd6d7af1356c4003a120c563, 2021-10-29T07:49:33.336Z)
OS version: Linux x64 5.4.0-89-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2838)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|11.59GB (0.41GB free)|
|Process Argv|--unity-launch --crash-reporter-id d1dc4fc0-87bd-4ba9-b632-a18a280ca837|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627:30244334
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534
vsc1dsc:30385039

```

</details>

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #136237. Previously whenever focus was updated--such as on the
mousewheel event--focused and blurred every single item in the
actionbar. This PR makes a change to remember the last focused item,
only blur that item, and only focus if the item to be focused was not
already.

### CODE REVIEW

**Comment by zztalker** [comment]
@connor4312 Does this change included in:
```
Version: 1.63.0-insider
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:02:57.068Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-89-generic
``` ?

I don't notice any changes in behavior.

**Comment by connor4312** [comment]
It should be present in the latest 1.63 Insiders. I no longer see performance issues here on my machine -- the context menu is still long but it no longer freezes

**Comment by zztalker** [comment]
```
Version: 1.63.0-insider
Commit: 035eaab2cb31798c6ae90a35928c62117cb52fcd
Date: 2021-11-15T05:15:36.284Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-89-generic
```

https://user-images.githubusercontent.com/1027857/141927951-d64936c9-102c-45a3-89b5-39b481aac7f2.mp4

How can I help with debugging this?

**Comment by connor4312** [comment]
Please grab a performance profile: https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by zztalker** [comment]
@connor4312 https://drive.google.com/file/d/1lpou5tScoE6oIts5iOB8LmRLf1Vno_a9/view?usp=sharing 
image

**Comment by zztalker** [comment]
@connor4312 any news on this?

**Pull request merged**
