### PR TITLE
Makefile colorization: fix old issues and improvement (~4 changes)

### PR DESCRIPTION
**Pull request by fadeevab**
1. This pull request fixes the following issue: https://github.com/Microsoft/vscode/issues/25469
2. Additional improvements according to Makefile documentation.

**Before:**
before
**After:**
after

**Total list of changes at the moment**:

1. Allow spaces before ifeq, define, endif, ended, else.
2. Handle braces properly inside the variable, e.g. $(info ()()(())).
3. Handle backslash inside end-of-line inside the $(variable).
4. Handle $$ and special variables according to Makefile documentation.

### CODE REVIEW

**Comment by fadeevab** [comment]
@aeschli Pull request to textmate is updated as well (https://github.com/textmate/make.tmbundle/pull/15)

**Comment by aeschli** [comment]
Thanks @fadeevab . I will update the grammar next week (we're currently in the end game week).

**Comment by aeschli** [comment]
BTW, no need to make a PR. It's also good enough if you file me an issue and ask to to run the update script

**Comment by fadeevab** [comment]
I added commits and test cases. But I didn't ported them to TextMate yet. Wait until I update TextMate. The reason is that I develop in VSCode firstly. It's unreal to develop in XML format initially.

**Comment by fadeevab** [comment]
@aeschli , FYI, TextMate xml is updated, you can check [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ffadeevab%2Fmake.tmbundle%2Fmaster%2FSyntaxes%2FMakefile.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Ffadeevab%2Fvscode%2Fmaster%2Fextensions%2Fmake%2Ftest%2Fcolorize-fixtures%2Fmakefile&code=%24%28info+%5C%0D%0A%29)

**Comment by fadeevab** [comment]
@aeschli You can check it now.

Total list of changes at the moment:

1. Allow spaces before ifeq, define, endif, ended, else.
2. Handle braces properly inside the variable, e.g. $(info ()()(())).
3. Handle backslash inside end-of-line inside the $(variable).
4. Handle $$ and special variables according to Makefile documentation.

I didn't updated the latest expected result according to the new test, thus the latest build failed.

**Comment by aeschli** [comment]
Closing the PR. We are in sync with https://github.com/fadeevab/make.tmbundle

**Comment by fadeevab** [comment]
Thank you!

**Pull request closed without merging**
