### PR TITLE
call hierarchy api 

### PR DESCRIPTION
**Pull request by jrieken**
This PR refines the call hierarchy API proposal and adopts the UX for it. The new proposal is

```ts

	export enum CallHierarchyDirection {
		CallsFrom = 1,
		CallsTo = 2,
	}

	export class CallHierarchySymbol {
		kind: SymbolKind;
		tags?: ReadonlyArray<SymbolTag>;
		name: string;
		detail?: string;
		uri: Uri;
		range: Range;
		selectionRange: Range;

		constructor(kind: SymbolKind, name: string, detail: string, uri: Uri, range: Range, selectionRange: Range);
	}

	export class CallHierarchyItem {
		source: CallHierarchySymbol;
		targets: ReadonlyArray<CallHierarchySymbol>;
	}

	export interface CallHierarchyItemProvider {
		provideCallHierarchyItems(document: TextDocument, position: Position, direction: CallHierarchyDirection, token: CancellationToken): ProviderResult<CallHierarchyItem[]>;
	}

	export namespace languages {
		export function registerCallHierarchyProvider(selector: DocumentSelector, provider: CallHierarchyItemProvider): Disposable;
	}

```

### CODE REVIEW

**Comment by jrieken** [comment]
Another round of API ideas (closer to the original) 

```ts
		class CallHierarchyItem {
			kind: SymbolKind;
			name: string;
			detail?: string;
			uri: Uri;
			range: Range;
			selectionRange: Range;
		}

		interface CallsTo {
			source: CallHierarchyItem,
			sourceRanges: Range[]
		}

		interface CallsFrom {
			sourceRanges: Range[],
			target: CallHierarchyItem
		}

		interface CallHierarchyItemProvider {

			resolveCallHierarchyItem(document: TextDocument, postion: Position, token: CancellationToken): ProviderResult<CallHierarchyItem>;

			provideCallsTo(target: CallHierarchyItem, token: CancellationToken): ProviderResult<CallsTo[]>;

			provideCallsFrom(source: CallHierarchyItem, token: CancellationToken): ProviderResult<CallsFrom[]>;
		}
```

**Comment by rbuckton** [comment]
Will call hierarchy only be limited to calls to/from, or is it possible it will evolve to support other concepts such as:
- constructs/constructed by (i.e. via `new`)
- read by/written by (i.e. fields or accessors)

**Comment by jrieken** [comment]
> Will call hierarchy only be limited to calls to/from, or is it possible it will evolve to support other concepts?

Anything callable and anything that makes calls. The obvious are functions/methods but constructors and getters/setters are also valid. Generally, VS Code doesn't care/know about what's valid and it will simply ask the language brains for incoming/outgoing calls for a document position.

**Comment by jrieken** [comment]
fyi - closing this in favour of https://github.com/microsoft/vscode/issues/70231#issuecomment-530387021. That explains the latest proposal which we are very likely to settle on. Let's continue the discussions there.

**Pull request closed without merging**
