### PR TITLE
Unflow the panel when hidden

### PR DESCRIPTION
**Pull request by joaomoreno**
Related to #11385

### CODE REVIEW

**Comment by bpasero** [comment]
@isidorn or stay symmetric with what the sidebar does and set a "nopanel" class on the workbench (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L509)

Key thing is that the panel should have `display: none` when hidden same as sidebar.

**Comment by isidorn** [comment]
@joaomoreno looks good to me. Though staying symetric and setting the 'nopanel' is also fine. The ugly thing about that solution is that @bpasero uses important in [css](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/sidebar/media/sidebarpart.css#L19)

If we prefer this approach I can also update the sidebar to use the same logic and avoid using imporant.

**Comment by isidorn** [comment]
Ok, merging this PR and will update the sidebar to also use this approach.

**Comment by isidorn** [comment]
@bpasero updating the sidebar to use the same strategy produces a rendering glitch. The issue seems to be caused by setting display: block in the middle of the layout. If I set the display to block with a setTimeout(, 0) everything works fine.

glitch

**Comment by joaomoreno** [comment]
Ugh

**Comment by bpasero** [comment]
Just do what sidebar does in both cases...

**Pull request merged**
