### PR TITLE
Handle proxy authentication

### PR DESCRIPTION
**Pull request by joaomoreno**
This PR makes Code handle the `app.on('listen'` event from Electron, thus supporting proxy authentication.

image

### CODE REVIEW

**Comment by arek20** [comment]
Any progress on that or ETA when it will be merged. I really need access from behind the authenticated corporate proxy. Thank you!

**Comment by ninrod** [comment]
Sorry, in what version was this landed?

**Comment by ocean** [comment]
@ninrod This was released in [1.15](https://code.visualstudio.com/updates/v1_15#_proxy-server-authentication), which came out on 10 August 2017.

**Review by Zari65 — COMMENTED** [review]
:)

**Comment by webdr1** [comment]
Michaelpeoni Webdr1 referenced this pull request on Feb 11, 2019 
issues reaching repositories do to http://go.microsoft.com/fwlink/p/?LinkId=255141

**Pull request merged**
