### PR TITLE
Update inserted/removed diff character background

### LINKED ISSUE #159075: highlighted colors(red and green) in the background in compare view seems to be more brighter than before
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.70.2
- OS Version: windows 10

Steps to Reproduce:
1. Did some changes in current files
2. in diff-view the highlighted colors(red and green) are more brighter

image

### PR DESCRIPTION
**Pull request by daviddossett**
Fixes #159075 by slightly tweaking the background color of inserted and removed text on a diff line. It does not affect the entire line's background color

## Before 

CleanShot 2022-09-19 at 13 42 08@2x

CleanShot 2022-09-19 at 13 35 18@2x

## After

CleanShot 2022-09-19 at 13 41 47@2x

CleanShot 2022-09-19 at 13 48 45@2x

### CODE REVIEW

**Review by roblourens — APPROVED** [review]

**Comment by abhijitchikane** [comment]
This newly added background also doesn't looks promising
I just saw the githubs file difference and the color they have added looks good, if you could take inspiration from that it would be great
Anyway thanks for listening to our feedback

**Comment by daviddossett** [comment]
> This newly added background also doesn't looks promising I just saw the githubs file difference and the color they have added looks good, if you could take inspiration from that it would be great Anyway thanks for listening to our feedback

@abhijitchikane what about it in particular do you like?

**Comment by abhijitchikane** [comment]
Readability point of view it gives more ease to eyes

**Comment by daviddossett** [comment]
Here's something closer to their dark colors. Would need some tweaking but you get the idea:

CleanShot 2022-09-19 at 20 43 44@2x

**Comment by abhijitchikane** [comment]
Github dark mode is more darker than the vscode's one
Maybe thats why it is not highghting the same way it is in github

Anyway Thanks

**Comment by daviddossett** [comment]
Yep, that's correct.

**Comment by hediet** [comment]
@daviddossett should we merge this?

**Review by hediet — APPROVED** [review]

**Comment by daviddossett** [comment]
Merged. I'll look into potentially changing colors in addition to these opacity changes in the next iteration.

**Pull request merged**
