### PR TITLE
Prune find traversal with basename patterns

### PR DESCRIPTION
**Pull request by chrmarti**
@bpasero FYI, one way of addressing the performance regression with large node_modules #11874 would be to use -prune with find. Alternatively we could turn off the use of find. What do you think?

The string overflow #11842 and the multiple parallel find processes #11181 are separate bugs that need to be fixed, they are amplified by this one.

### CODE REVIEW

**Comment by bpasero** [comment]
@chrmarti how do you support glob pattern excludes?

**Comment by chrmarti** [comment]
This only supports **/something patterns, the other exclusions are still applied after we have read find's output. We could do something similar for **/*something patterns, but these do not seem to be as important for performance.

**Comment by bpasero** [comment]
@chrmarti if we can make find do less work by excluding folders that are in our exclude rules, what would speak against doing so?

**Comment by chrmarti** [comment]
@bpasero I'm not entirely comfortable with using command line tools as an API and was curious about your opinion.

**Comment by bpasero** [comment]
@chrmarti if we would implement our own native file walker as a tool we would also include support for excluding folders I think, so one way or the other, making it possible to do less work from the native solution seems always good to me. Of course I am not sure how find treats these excludes, have you tried?

**Comment by chrmarti** [comment]
On find's behavior: Using -name seems to not have any major performance impact while -path did slow things down a lot (measured when exclusions did not match any folder), probably because with -path you need to use a wildcard. -prune will let 'find' skip matching folders, so we get the desired performance gain there. I still need to investigate if and how I need to escape special characters in folder names (like *, ?, etc.).

I agree that we would need to implement exclusions in our own native library. This wasn't clear to me before we had these bug reports here. The alternative I was considering was to go back to our in-node file traversal also for OSX and Linux, until we have time to implement a native library (or someone else makes one available) some time in the future. But I'll now finalize this change and push it when done.

**Comment by chrmarti** [comment]
Committed a new change set: 50bb7aad57cbf1924e28472de52734be49645558

**Pull request closed without merging**
