### PR TITLE
Fix circular/infinite dispose Fixes: #40465

### LINKED ISSUE #40465: SelectBox Custom: Stack error , infinite disposal loop
New SelectBox custom implementation creates a circular disposal since toDispose is still passed to
the select box delegate where the class objects  are added into the disposable list which is really the parents list.

Steps to Reproduce:

1. start code, open a terminal (instantiates the drop-down lists)
2. Toggle panel (disposes SelectBox)
3. Code gives a stack err, panel becomes blank and unusable
4. Debugging shows an infinite disposal loop.

Debug added on disposal:

[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.472:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.473:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.474:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.475:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.475:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.476:INFO:CONSOLE(442)] "Dispose 14", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js (442)
[7432:1218/181741.476:INFO:CONSOLE(85)] "Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)
    at SelectBoxList.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:443:42)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:56
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)
    at SelectBoxList.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:443:42)
    at file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:56
    at Array.forEach (native)
    at Object.dispose (file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/base/common/lifecycle.js:22:19)", source: file:///C:/VSC Dev/vc-fork-cdl/vscode/out/vs/workbench/services/message/browser/messageService.js (85)

### PR DESCRIPTION
**Pull request by cleidigh**
Fixes: #40465 

Both SelectBox and SelectBox Delegate classes call dispose on the same list creating an infinite dispose Loop.

@bpasero 
Given that this crashes the panel,  would you like me to merge things like this on my own?

### CODE REVIEW

**Comment by bpasero** [comment]
Good catch, sorry for that 👍

**Comment by cleidigh** [comment]
@bpasero 
For something small like this, is it kosher to do the merge myself or do you prefer to do all the merging?

**Comment by bpasero** [comment]
@cleidigh yes just go ahead and merge. you can still assign me so that I am getting pinged 👍

**Comment by cleidigh** [comment]
@bpasero 
If you prefer to pass in toDispose into subclasses/functions , that was my original implementation.
I had the caller call the dispose that would include the child's disposables.  Did I do not understand something about what I originally had?

**Comment by bpasero** [comment]
@cleidigh I meant, I prefer that a widget has a public `dispose` method that is called from the outside. That is what we typically have in all our widgets.

**Comment by cleidigh** [comment]
@bpasero 
okay that makes sense.  Since SelectBox parent is the only one that implements Widget, it is the only one
they can have a public dispose    The delegates would have to have their disposed functions called by somebody else.  so is the current version where the delegates also have a dispose function called whenever the delegate itself is disposed by the parent correct?

**Comment by bpasero** [comment]
@cleidigh maybe a good example is [`IconLabel`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L83) where we have a `HighlightedLabel` inside. The dispose method of `IconLabel` calls the dispose method of `HighlightedLabel`.

**Pull request merged**
