### PR TITLE
Add drop into editor option

### PR DESCRIPTION
**Pull request by mjbvz**
This change adds a new `enableDropIntoEditor` editor option that enables/disables dropping an extermal resources into an editor

Previously this option was exposed `IEditorConstructionOptions`, however this did not correctly disable drop into editor when dragging and dropping unknown types (such as dragging emoji from the MacOS emoji panel)

With this change, disabling `workbench.editor.dropIntoEditor.enabled` should fully disable the new drop into behavior

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
I really like the feature so kudos for that :+1: . This looks great and thanks for asking for my review! Just a couple of notes:
* the issue https://github.com/microsoft/vscode/issues/12953 is not workbench specific i.e. it would be good if the fix for it would work also in the standalone editor case. i.e. dropping emojis in the editor should work even in the standalone editor. To get that working, it would mean to move much or most of the code from `DropIntoEditorController` into the `vs/editor/contrib` folder. I see that the file uses some `vs/workbench` imports and also uses the setting `workbench.editor.dropIntoEditor.enabled`, but if those pieces could be extracted, then everything else would make sense to move down to `vs/editor` IMHO. If you would use a simple `editor.dropInto.enabled` setting instead of a `workbench.` setting, then you would not need to do this translation from one setting to another and would remove one more "workbench" dependency. Running the editor standalone is very simple, it involves cloning the https://github.com/microsoft/monaco-editor repo as a sibling to vscode, running `npm install`, `npm run release`, and `npm run simpleserver` and then opening http://127.0.0.1:8080/monaco-editor/test/manual/?editor=src which would load the sources straight from the sibling vscode folder. 
* the rendering of the drag&drop feedback might be better done from the controller and not from within the editor widget. It looks like the editor widget can't do anything by itself with things that are dropped into it and displaying feedback for something it can't do seems the wrong way to cut things. But this is not so critical.
* the editor option might be better off by default until the previous bullet points are done, otherwise the standalone editor would always render the feedback, as well as editors used as simple widgets, like the source control input box, where the drag&drop feedback is shown even if the controller is not instantiated for it:

https://user-images.githubusercontent.com/5047891/162436225-8800efa8-83a7-496d-8998-0f88adce59f8.mp4

**Comment by mjbvz** [comment]
Thanks for the feedback @alexdima!

I agree we should support this feature for non-workbench editors too. The main challenge is that the the default drop implementation depends on the workspace folders and calls `extractEditorsDropData` to get lists of uris from the drop event

Do you think I should try moving `extractEditorsDropData` to the platform/editor layer so that everything can live under `editor`? Or should I keep this part in the workbench layer and have the editor delegate to it?

**Comment by alexdima** [comment]
> Do you think I should try moving `extractEditorsDropData` to the platform/editor layer so that everything can live under editor? 

If feasible, that sounds good! I noticed that the file has quite a bunch of `workbench` imports:
```
import { ITextFileService } from 'vs/workbench/services/textfile/common/textfiles';
import { IEditorIdentifier, GroupIdentifier, isEditorIdentifier, EditorResourceAccessor } from 'vs/workbench/common/editor';
import { IEditorService } from 'vs/workbench/services/editor/common/editorService';
import { IEditorGroup } from 'vs/workbench/services/editor/common/editorGroupsService';
import { IWorkspaceEditingService } from 'vs/workbench/services/workspaces/common/workspaceEditing';
import { IHostService } from 'vs/workbench/services/host/browser/host';
```

But some of them appear to be used only in some other code in the same file, so maybe it is feasible to move `extractEditorsDropData` down.

**Comment by mjbvz** [comment]
Ok, I've moved `dropIntoEditor` up to the `editor` layer. The change grew quite a bit because I also had to move a few other functions/class up, including moving `extractEditorsDropData` from `workbench` to `platform`

**Comment by alexdima** [comment]
@mjbvz Which of the 3 commits are new? I'm having trouble keeping track of the commits that I already reviewed.

**Comment by alexdima** [comment]
Aha! Now I notice that the branch was force-pushed:

image

Do you know if there is a way to review in such a case only the difference? When I press `Compare` I get a huge diff of all the team's been doing in 1 month, but I would also not really want to review all 31 changed files again if they haven't changed.

**Comment by mjbvz** [comment]
@alexdima Yes sorry I rebased to `main` and then force pushed the update. The current set of 31 changed files should all be part of this work. Most of the changes file are only update imports paths though so you can safely skip  them

**Review by alexdima — DISMISSED** [review]
🚀  Nice! I've also tested the standalone editor and I can drop emojis in it now!

**Review by roblourens — APPROVED** [review]

**Pull request merged**
