### PR TITLE
search panel

### LINKED ISSUE #9435: Search results need more space than the side bar allows
- VSCode Version: 1.3.1
- OS Version: OS X

I believe that often, search results need more horizontal space to be truly useful than the sidebar allows, unless you expand the sidebar very wide (which then means less room for open files, and requires you to manually resize it bigger and smaller when going between search and editing, if you like to have the file tree open when editing).

My suggestion would be that search should have the option to display the results in a new tab, in a similar way to Atom or Sublime, or alternatively, the search pane could be relocatable to the bottom of the screen, so it would gain horizontal space in exchange for vertical.

### PR DESCRIPTION
**Pull request by isidorn**
Moves search viewlet into panel area.
This is work in progress, created a PR just so people can easily try it out.

After trying out sublime and my prototype I suggest the following:

* to go into this mode we have a setting (to start), alternative is to enable DnD between viewlet and panel area, but users do not want it for other viewlets and allowing only for search feels weird
* we move the X action from the right to the left so it is not so disconnected (Open Editors already has it on left)
* we show 5 full line snippets for each result (like sublime), a snippet can contain multiple hits. - We can start with just showing 1 full line at least. The issue with 5 full ines is how to visually seperate them nicely in a tree

The last point is key to make sense of using all this horizontal space.
An alternative is to do a brand new design when search is horizontal.

fixes #9435

### CODE REVIEW

**Comment by isidorn** [comment]
From slack discussions some things to consider:
* Layouting now to save on vertical not horizontal space, put labels and input fields each on a single line
* show a lot more of the line in the snippet
* Show results in the same font / display as the editor
* Can we with this also tackle the issue of users wanting search results in editor area. I believe yes

**Comment by isidorn** [comment]
fyi @bpasero feedback very welcome. You can ignore changes inside the `search` world

**Comment by isidorn** [comment]
This PR does the following:
* Removes the assumption from search land that `SearchViewlet` is a `Viewlet`, it can now be a panel as well
* Adds a configuration `search.location`
* Adds listeners in `PanelPart` and `ActivityBar` on the changes of this configurations, so they add / remove search from their `compositeBar`
* Adds an API in `compositeBar` to add and remove composites

What still needs to be done (probably march milestone):
* Improve search ux in horizontal case such that the layouting uses the additional horizontal space (we have nice ideas already what to do)

What would be nice to do as debt:
* Refactor search that searchService has more functionality and not that every action needs to get a hold of the `SearchView`. Idealy every action would go to the `Service` and the `SearchView` would update based on events coming from the `Service` or the model

fyi @roblourens

**Comment by bpasero** [comment]
@isidorn not a big fan of encoding the knowledge of search settings into core workbench parts, imho this should somehow be provided by the composite (search viewlet) and not the activity bar or side bar. 

I am fine to leave this for debt week, but it would be good to address this, even if we are not expanding this feature to other parts if possible.

**Comment by bpasero** [comment]
@isidorn cool thanks

**Comment by isidorn** [comment]
@bpasero fyi created https://github.com/Microsoft/vscode/issues/45063 for improving horizontal search in march. I think I captured all your ideas but feel free to chime in

**Pull request merged**
