### PR TITLE
Support activity bar on top of primary side bar

### PR DESCRIPTION
**Pull request by sandy081**
- Activity bar position setting that supports side, top of primary side bar and hidden.
- Deprecated activity bar visibility setting in favour of this new setting
- Top position is supported only in custom title bar mode
- Global actions (account, gear) are shown in title bar to the right and badges are supported

image

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]

**Comment by abhijit-chikane** [comment]
@sandy081 
I would love to see this in action! 😊 One thing I would like to see is having similar functionality available for the secondary sidebar. Right now, the secondary sidebar just sits at the top, but it would be much better if you gave it the ability to move to the right and have a similar view as the activity bar. 🚀

Thanks!

**Comment by abhijit-chikane** [comment]
@sandy081 
I would love to see this in action! 😊 One thing I would like to see is having similar functionality available for the secondary sidebar. Right now, the secondary sidebar just sits at the top, but it would be much better if you gave it the ability to move to the right and have a similar view as the activity bar. 🚀

Thanks!

**Comment by abhijit-chikane** [comment]
@sandy081 
I would love to see this in action! 😊 One thing I would like to see is having similar functionality available for the secondary sidebar. Right now, the secondary sidebar just sits at the top, but it would be much better if you gave it the ability to move to the right and have a similar view as the activity bar. 🚀

Thanks!

**Comment by abhijit-chikane** [comment]
@sandy081 
I would love to see this in action! 😊 One thing I would like to see is having similar functionality available for the secondary sidebar. Right now, the secondary sidebar just sits at the top, but it would be much better if you gave it the ability to move to the right and have a similar view as the activity bar. 🚀

Thanks!

**Pull request merged**
