### PR TITLE
search: fix freezing ui on long lines

### LINKED ISSUE #109902: Search editor crashes (OOM) when matching a very long line (e.g. minified JSON)
- VSCode Version: 1.50.1
- OS Version: macOS 10.14.6 (18G6032)

Steps to Reproduce:

1. Extract this file into a VS Code workspace [workbench.web.api.js.map.zip](https://github.com/microsoft/vscode/files/5480398/workbench.web.api.js.map.zip)
2. Open a search editor and search for "// TODO".
3. The VS Code window will crash prompting to reload.

<details><summary>Stack Trace</summary>

```
(anonymous) (searchEditorSerialization.ts:41)
l (searchEditorSerialization.ts:35)
(anonymous) (searchEditorSerialization.ts:65)
(anonymous) (searchEditorSerialization.ts:65)
(anonymous) (searchEditorSerialization.ts:234)
(anonymous) (searchEditorSerialization.ts:234)
t.serializeSearchResultForEditor (searchEditorSerialization.ts:233)
doRunSearch (searchEditor.ts:524)
await in doRunSearch (async)
(anonymous) (searchEditor.ts:427)
(anonymous) (async.ts:260)
Promise.then (async)
trigger (async.ts:254)
triggerSearch (searchEditor.ts:426)
(anonymous) (searchEditor.ts:132)
fire (event.ts:587)
submitSearch (searchWidget.ts:631)
onSearchInputChanged (searchWidget.ts:510)
(anonymous) (searchWidget.ts:326)
fire (event.ts:587)
onValueChange (inputBox.ts:508)
(anonymous) (inputBox.ts:210)
```

</details>

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by connor4312**
Fixes https://github.com/microsoft/vscode/issues/109902. Makes the fishy logic smarter so that it cuts out text between matches and doesn't send (in the example repro) 26MB of text to be displayed in the renderer.

Ideally we could tell ripgrep to provide a narrower context, and there are some limited options for it, but they don't really fit what we need and don't work when ripgrep is outputting JSON regardless.

### CODE REVIEW

**Comment by roblourens** [comment]
Wow, thanks for tackling this. This replaces some long bits of text with `...`, which will show up in the search editor, FYI @JacksonKearl, I assume that is preferable to crashing.

I'm trying to figure out whether this makes a real change in behavior for replace. Tricky thing there is that you can have a lookahead or lookbehind pattern that will break if we truncate text outside of the match. We have to rerun the search regex on the local side to resolve regex group references. This can still break in some places currently like when there is a single match in a long line and we truncate. So this would make the same thing happen when there are multiple matches on a long line. Technically by adding `...` we could make something match that would not have matched before.

There are a bunch of ways those issues can be handled in the future, and I think this is a huge net improvement, so I'Il merge it with @JacksonKearl's 👍

**Comment by connor4312** [comment]
This is what the search editor looks like:

**Comment by connor4312** [comment]
Actually, not really sure if it's solvable. Links are parsed from the search editor text, not sure we can provide metadata. Alternately we could have something like `(123 characters skipped)` which we could then parse in the link handling.

**Comment by JacksonKearl** [comment]
I like `(123 characters skipped)`, it's helpful to know where in the very long line you are. 

Unclear to me if these breaks appear in the middle of the result lines or just at the beginning?

**Comment by connor4312** [comment]
They can appear anywhere in the line

**Comment by JacksonKearl** [comment]
Okay I spotted some in the screenshot now. In that case I think the `(123 characters skipped)` makes more sense, I wasn't able to see the elipsis in the screenshot originally, and they're pretty commonly used in code generally so it could get confusing.

**Comment by connor4312** [comment]
recording(8)

**Comment by roblourens** [comment]
I already have issues with this in the current build. Seems like when text is trimmed off the front of the line, navigating does not respect that. Example:

- Search "stuff" in vscode repo
- Look at the `emojis.json` result
- Navigate any any point on that line

I go to the wrong column which seems based on the offset of my cursor after the text has been removed, not before.

**Comment by connor4312** [comment]
Looks like I accidentally fixed that here as well  😛

**Comment by roblourens** [comment]
What if I search text that contains `([0-9]+) characters skipped\)`, is that so unusual?

**Comment by JacksonKearl** [comment]
It's probably pretty unusual for your text to contain `...([0-9]+ characters skipped)...`, but even if it does I think so long as things don't catastrophically break (as in, the cursor position should be capped to the line length instead of throwing or wrapping) we're better off than we are now. 

We could go even further with some fancy unicode chars... `«»⟦ ⟧ ⟨ ⟩ ⟪ ⟫ ⟮ ⟯ ⟬ ⟭ ⌈ ⌉ ⌊ ⌋ ⦇ ⦈ ⦉ ⦊`? http://xahlee.info/comp/unicode_matching_brackets.html

**Comment by roblourens** [comment]
Yeah. Could use fancy unicode ellipsis too …

**Comment by connor4312** [comment]
I added a zero-width space inside both of the parenthesis. Should be spooky enough to prevent it from being accidentally matched in user code.

**Comment by roblourens** [comment]
We can use a special character but I'd rather not use an invisible one. I know it's going to confuse us some day.

**Comment by roblourens** [comment]
Or I think it's probably fine to leave it as-is too, like Jackson said, a false match will be rare and not really cause a huge issue

**Comment by connor4312** [comment]
Mm, okay. I'll just go with fancy brackets and then make sure our bound checks are in order.

**Comment by connor4312** [comment]
Added grammar as well

**Review by roblourens — APPROVED** [review]
Awesome

**Comment by connor4312** [comment]
@JacksonKearl feel free to ping me if you any have concerns with this

**Pull request merged**
