### PR TITLE
Turn on `UtilityProcess` by default

### PR DESCRIPTION
**Pull request by alexdima**
This should now work since https://github.com/microsoft/vscode/commit/47652af0b6c5fb18133688708e41d4ef3ce5e239

### CODE REVIEW

**Review by lramos15 — DISMISSED** [review]

**Comment by alexdima** [comment]
@deepak1556 It looks like the `UtilityProcess` always logs `UnhandledPromiseRejectionWarning`. Having a `process` listener for `unhandledRejection` would typically silence that warning, but with the `UtilityProcess` it is always printed.

@bpasero I'm seeing the following integration test fail consistently, even locally -- `editor, opening multiple at the same time #134786`. On my machine, the result is an array which contains the 3 URIs, while the test asserts that only the 3rd URI is set. I don't quite understand what the test is doing, and I think perhaps the test is asserting some kind of specific timing behavior that might have changed now?

**Comment by bpasero** [comment]
@alexdima @deepak1556 how can I run locally with utility process?

**Comment by bpasero** [comment]
I have pushed a change to fix the integration tests with an explainer.

**Comment by deepak1556** [comment]
> It looks like the UtilityProcess always logs UnhandledPromiseRejectionWarning. Having a process listener for unhandledRejection would typically silence that warning, but with the UtilityProcess it is always printed

Sorry for this behavior, I had followed what existing main and renderer process following and they had set the mode to `warn`
https://github.com/electron/electron/blob/e2f42e5d994a27f461e503b72934e3e4111ce29f/shell/browser/electron_browser_main_parts.cc#L245-L246. I can revert to use the default mode from Node.js for the utility process which would be `throw` https://github.com/nodejs/node/blob/028a0a3723021a2f681502f19711b1c54d0fb6b4/lib/internal/process/promises.js#L63-L67

**Comment by bpasero** [comment]
@alexdima @deepak1556 one thing I noticed when trying to reproduce the test failures on Linux is that we loose the output from the extension host. Specifically this should print when running `scripts/test-integration.ts`:

image

However when utility process is enabled, I miss that output. 

Still have to understand how we transport test results back to the output, I may have written that code a long time ago...

**Comment by bpasero** [comment]
My gut feeling is that we have conditional code that checks for `process.send` to be there or not:

https://github.com/microsoft/vscode/blob/75362a62685799fee8c5f3760d006705ca31a5d5/src/bootstrap-fork.js#L26-L28

https://github.com/microsoft/vscode/blob/75362a62685799fee8c5f3760d006705ca31a5d5/src/vs/workbench/api/node/extHostExtensionService.ts#L86-L94

When running in a utility process, `process.send` is not there because the process was not forked. Rather, any assumption about `process.send` needs to be revisited and probably changed to use a message port instead?

Unfortunately I am no longer fully understanding all the code in `bootstrap-fork` around `VSCODE_LOG_NATIVE` and friends.

**PS:** I wonder if those test failures where flakes, latest builds seem to not hit integration test issues anymore.

**Comment by alexdima** [comment]
@deepak1556 One of the builds from yesterday ran into a NPE inside `UtilityProcess`. I've created an issue at https://github.com/microsoft/vscode/issues/152851

@bpasero I agree, the extension host needs to stop using `process.send` ASAP. That is already problematic with remote extension hosts where the logging would then reach the server process that spawned the remote extension host instead of the local renderer, so that's why [it tries to redirect process.send](https://github.com/microsoft/vscode/blob/58a042cb8e67a941f8f01e803a11ca8e56920358/src/vs/workbench/api/node/extHostExtensionService.ts#L88-L94) to `mainThreadConsole.$logExtensionHostMessage`. I will look into a separate PR to remove the usage of `process.send` completely.

**Review by lramos15 — APPROVED** [review]

**Comment by bpasero** [comment]
👏 , maybe as a follow up, configure the default as `false` if product quality is stable?

**Comment by alexdima** [comment]
@bpasero Do you have any hint how I could do that? I register the configuration in [a static context](https://github.com/microsoft/vscode/blob/6ab33e9bb2f72e65273ce1536e3f5225a90c5d05/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L227-L231) without access to the `IProductService`

**Comment by bpasero** [comment]
@alexdima since this is temporary, you can still just depend on the static `product` before we had the service:

https://github.com/microsoft/vscode/blob/09c5a6ed48269c3af355a6b9722e6eb36111a469/src/vs/platform/product/common/product.ts#L16

**Comment by alexdima** [comment]
I've created https://github.com/microsoft/vscode/issues/153465 so we don't forget

**Pull request merged**
