### PR TITLE
Add languages indicator to Settings editor settings

### LINKED ISSUE #145731: Indicate if setting has a language-specific value
Testing #145588

Introduce an indicator when a setting has language specific value when viewing that setting in non-language specific scope. 

For example

1. Filter to `@lang:css`
2. Change a setting
3. Remove filter
4. Search for that setting
5. There's no indication that the setting's value has changed for the current scope ('User') and also there is a language overriding this value.

image

Also same if the setting has a different value for other languages contributed in defaults

### PR DESCRIPTION
**Pull request by rzhao271**
This PR fixes https://github.com/microsoft/vscode/issues/145731, by adding a new label for language overrides. This label currently shows when a setting has an extension-contributed language-specific default setting value override, but it should also show when a setting has a language-specific value in general.

This PR is not yet ready to merge. I have created some smaller debt-reduction PRs to merge first that are independent of this feature.

### CODE REVIEW

**Comment by sandy081** [comment]
Is it possible to show how the label looks?

**Comment by rzhao271** [comment]
Here is an image of how the language indicator currently looks, next to the scope overrides indicator.
I added an icon to the scope overrides indicator as well so that we can remove the parentheses that were previously surrounding the label.

se-lang-indicator

**Comment by rzhao271** [comment]
It looks like GitHub doesn't re-sign commits for you when you select "Update with rebase" to update the PR branch.

**Comment by sandy081** [comment]
Please let me know if it is good for review?

**Comment by rzhao271** [comment]
Closing. I'll put up a newer PR soon that builds on top of PR #152401.

**Pull request closed without merging**
