### PR TITLE
Add atomic tabs option

### LINKED ISSUE #2798: Navigate Soft Tabs As If They Are Hard Tabs
If implemented properly, the user should not even realize they are working with spaces for indentation, which is one of the greatest pains of a person who prefers tabs for indentation working on a file that has spaces for indentation.
## Spaces should be treated as if they were tabs under the following conditions
1. The text editor's `insertSpaces` setting is `true` (or leading spaces precede tab characters on a line).
2. The cursor is within the range of leading indentation.
   1. We can't possibly guess where indentation ends and alignment begins, so this includes all leading whitespace (both spaces and tab characters, assuming each tab character is the width of `tabSize`).
3. The user attempts to do any of the following:
   1. Arrow-key navigation.
   2. Backspace.
   3. Delete.
   4. Mouse selections (more difficult to implement, I'm sure).
## Examples of how spaces are treated as tabs
1. If the cursor is at the beginning of the line and the right arrow key is pressed, the cursor jumps `tabSize` spaces, instead of just one.
2. If `tabSize` is `4` and the cursor is on position `6` (between tabs) and the left arrow key is pressed, the cursor jumps `2` spaces instead of `4`, landing gracefully on a tab stop.
3. If `tabSize` is `4` and the cursor is on position `4`, but the first non-whitespace character is on position `6`, then the space on position `5` is assumed to be alignment; thus, a right arrow key press would land on position `5`.
4. The backspace and delete keys should eliminate up to `tabSize` spaces in one batch, so that a single undo operation restores all of the spaces that were deleted.
5. Ideally, mouse selections would also be restricted to tab stops, so you can't individually select the spaces between a single indent.
## Exposing an editor setting
- Perhaps an editor setting called `navigateSoftTabsAsHard` should be exposed for those who wish to opt in or out of this feature. The default value is debatable.

### PR DESCRIPTION
**Pull request by Timmmm**
This treats tabs faked using spaces as if they were real tabs meaning that you can't select the middle of them. I have added a test, with 100% code coverage over the core logic. I've also tested this fairly extensively with hairy mixed-indentation files and with multiple cursors.

There are a few caveats that I need advice with:

1. I have not used `indentSize` anywhere (see [this comment](https://github.com/microsoft/vscode/issues/10339#issuecomment-695758695)).

2. I am not 100% sure I added the new `atomicTabs` setting everywhere it should be. I basically grepped for `insertSpaces` and added it in the same places (except a few bits where it didn't make sense). But that is loaaads of places so I might have missed some.

~~3. There is one bg with the mouse handling that I need advice on (not sure I've intercepted the mouse stuff in the right place). Basically if you just click it's fine, but if you select some text and then click in the selection it won't use the atomically snapped position.~~

This PR fixes #2798

### CODE REVIEW

**Comment by Timmmm** [comment]
Here is a video showing the behaviour, including the outstanding bug.

atomic_tabs2

**Comment by rmunn** [comment]
I'd recommend the name "atomic soft tabs" rather than "atomic tabs", as the latter would make some people (including me) think this changed the behavior of tab characters. "Soft tabs" is the usual name, AFAICT, for "hit the Tab key and N space characters get added to the file" feature (where N is, of course, the value of `indentSize`, because that's what people using a "soft tabs" feature expect to get when they hit the Tab key).

**Comment by Timmmm** [comment]
The Mac build failed due to a network failure. Is there any way to run it again other than pushing a dummy commit?

**Comment by rmunn** [comment]
Closing and reopening the PR also retriggers build steps, without needing a dummy commit.

**Comment by EPonyA** [comment]
Amazing to see this! I was recently surprised to find that it isn't already a core feature, but now I really hope it will be.

**Comment by Timmmm** [comment]
Ok this works perfectly as far as I can tell now. Who do I need to bribe to get it reviewed? :-D

**Comment by EPonyA** [comment]
It's very unfortunate that this isn't receiving the attention it deserves.

**Comment by Timmmm** [comment]
@alexdima Any chance of a review?

**Comment by alexdima** [comment]
This looks very good! Thank you! :heart:

I just did some changes on top:
- it's unlucky that you looked for `insertSpaces`, which is a special kind of editor option, one that lives with the text buffer. I've converted the option to a regular editor option, reducing the changed file count.
- I pushed a slight optimization to avoid walking the leading whitespace again in case of going left.
- small stylistic changes

I'm sorry I didn't get to this sooner.

**Comment by Timmmm** [comment]
Amazing, thank you so much!

**Comment by alexdima** [comment]
I've renamed the setting to `editor.stickyTabStops` since we already had a setting called `editor.useTabStops` to control the behaviour of backspace / delete for the spaces in the indentation.

**Comment by Timmmm** [comment]
I copied it from Atom

image

I thought it was a decent enough name - `atomicTabStops` would be fine too. Atomic in the sense that the tabs can no longer be split.

I'm not sure I understand `sticky`. Isn't sticky for things that stick? Like a sticky menu that sticks to the top of your screen. Are you thinking that the cursor sticks to the tab stop?

Anyway you guys are the bosses - not really too bothered what it is called as long as it exists! :-D

By the way I made a little video to demo it, in case you want something for the release notes.

**Comment by Timmmm** [comment]
Demo video:

[atomic_tabs.mp4.zip](https://github.com/microsoft/vscode/files/5625247/atomic_tabs.mp4.zip)

**Pull request merged**
