### PR TITLE
support screen reader reading the line when go to next/previous diff are used

### LINKED ISSUE #164988: [Accessibility]: Screen readers do not read currently focused line when using Alt+F5/Alt+Shift+F5
CC @isidorn

## System Info

Version: 1.73.0-insider (system setup)
Commit: 3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709
Date: 2022-10-27T21:34:51.585Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

## Reproducible Steps

1. Load screen reader (e.g., NVDA).

2. Open any diffs between two files (or PR).

3. Press `Alt+F5` to go to the next diff and `Alt+Shift+F5` to go to the previous diff.

4. See if screen reader reads aloud the currently focused line: it does not say anything.

## Expected Behaviors

Focused line needs to be auto-announced.

### PR DESCRIPTION
**Pull request by meganrogge**
fix #164988

https://user-images.githubusercontent.com/29464607/211625110-92ab6a2b-632a-4852-8963-e532bf699216.mov

### CODE REVIEW

**Comment by meganrogge** [comment]
@hediet I noticed that audio cues take some time to load, thus the necessity of a delay before the selection and content can be updated as mentioned here https://github.com/microsoft/vscode/issues/164988#issuecomment-1377757805

@Tyriar suggested we might be able to preload the audio cue files when screen reader mode is on. What do you think of that?

**Review by hediet — APPROVED** [review]

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
@meganrogge awesome work, thanks for driving this.
As for pre-loading the audio cues - how long is the lag now? If we think it is noticable we can do it on screen reader detection (as long as we do not do it on startup).

**Comment by jooyoungseo** [comment]
@meganrogge -- Does not work: Alt+F5/Alt+Shift+F5 only moves to changes with no audio cues being played. Screen reader does not announce focused line. Tested with JAWS 2023 and NVDA on Windows 11.

Version: 1.75.0-insider (system setup)
Commit: 6d40104789d03d41b8866a1e57847dae14c5cf0d
Date: 2023-01-12T05:34:21.597Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by meganrogge** [comment]
I tested with NVDA on Windows and both audio cues and announcement of the line happen for me.

**Comment by jooyoungseo** [comment]
@meganrogge Still does not work for me.

Nothing special settings.. 

``` json
{
    "editor.accessibilitySupport": "on",
    "audioCues.diffLineDeleted": "on",
    "audioCues.diffLineInserted": "on",
    "audioCues.diffLineModified": "on",
    "audioCues.volume": 100
}
```

## Reproducible Steps

1. Launch code-insiders in vscode main branch.

1. Execute "Source Control: Focus on Commits View" in command palette.

1. Arrow-down to "❰ upstream ❱➤  add audio cues for go to next/previous change (#170899) … Megan Rogge, 2 days ago".

1. Expand that commit via right-arrow key.

1. Arrow-down to select "audioCues.contribution.ts src/vs/workbench/contrib/audioCues/browser" and hit enter.

1. Press Ctrl+1 to focus in the source editor.

1. Press Ctrl+Home to go to the begining.

1. Press Alt+F5: I don't hear any audio cues nor screen reader announcement. However, the the cursor has jumped to the line saying "'description': localize('audioCues.diffLineInserted', "Plays a sound"

**Comment by meganrogge** [comment]
@jooyoungseo do you have any changes in the file that you opened?

**Comment by jooyoungseo** [comment]
@meganrogge Yes, but with no audio cues:

image

**Comment by meganrogge** [comment]
It won't play when you are in a diff view. It will play in a normal editor to indicate the changes.

**Comment by meganrogge** [comment]
So if you select the go to document icon there, it will take you to the normal editor - there is where it will work. A separate feature, though related, would be to support these in that type of editor

**Comment by jooyoungseo** [comment]
@meganrogge  -- Cannot find "go to document" icon by using screen reader. Does it have an alt text? I used to press Ctrl+1 after selecting a commit to focus in the editor area. Isn't that normal editor?

**Comment by meganrogge** [comment]
@jooyoungseo sorry, the alt text is open file and it is the first of the buttons

**Comment by meganrogge** [comment]
I will make a new issue to cover the diff editor case

**Comment by jooyoungseo** [comment]
@meganrogge -- Clicking Open file button does not move my focus to the normal editor area. Would you mind sharing your keyboard-only reproducible steps with NVDA?

**Comment by meganrogge** [comment]
Yes, follow your steps from above + Click the open file button then run View: Focus active editor group, make a few changes in the file, then run go to next change

**Comment by jooyoungseo** [comment]
@meganrogge Aw, now I understand. I had to make some changes in the opened editor. I wanted to use this to recognize what's changed in diff editor. BTW, Alt+F5 works as expected; however, revisiting any changed line manually via arrow keys does not trigger any audio cues. Is this an intended behavior? Isn't it better to play the same audio cue even when navigated via arrow keys?

**Comment by meganrogge** [comment]
@jooyoungseo I can consider supporting that as well. The thought is that there could also be errors on the line etc, so we don't want to overwhelm with the noises. (though errors on the line currently don't work and we're investigating that)

I created this and will work on it today to cover the diff view

https://github.com/microsoft/vscode/issues/171200

**Comment by meganrogge** [comment]
the way it works is when those commands are run, we evaluate the line and play the cue depending on the change found there. 

we'd have to evaluate if there's a change on the line any time the cursor moves if you'd like it to play when you use arrow keys. could you pls create this request if you're not concerned about overlapping/multiple audio cues per line?

**Pull request merged**
