### PR TITLE
Move event buffering from BackupService to file models

### LINKED ISSUE #14186: Buffer untitled/text file model changed events and make the event type consistent
From @bpasero in https://github.com/Microsoft/vscode/pull/14115#discussion_r84486381

> I see the need for an event when untitled or text files are changing so that the backup service can do its business, however I fear that this comes at the cost of spam: you will see many model content change events while the user is typing, so basically each key press will trigger this event. Performance should always be something to be concerned of, especially when it is typing performance we are talking about.
> 
> Some ideas:
> 
> buffer the model content change event and only start to emit the change after a certain delay
> do not always create an event object to send around
> I think buffering would be a good idea anyway because backups should also not be created without some delay.

From @bpasero  in https://github.com/Microsoft/vscode/pull/14115#discussion_r87146511

> @Tyriar I do not see a reason to create an object here each time a character is typed. the untitled event just sends around its resource URI and I would do the same thing here for files.
>
> Cannot say it often enough, this model content change event WILL FIRE like CRAZY. And perf is a hot topic after hot exit :)

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #14186

---

Summary of changes:

- Move 1000ms event buffer from `BackupService` to the `TextFileEditorModel` and `UntitledEditorModel` content change events.
- `TextFileEditorModel.onDidContentChange` now also fires on reverts
- Amended untitled content change event test to work with new buffer
- Reintroduced the commented out assertions from the text file content change event test and fixed to work with new buffer

### CODE REVIEW

**Comment by bpasero** [comment]
Started to review the changes and then made so many changes that I just pushed via https://github.com/Microsoft/vscode/commit/672b147604d0ea629857e05a1e764a758627b775

By using the `RunOnceScheduler` you save a lot of nasty promise handling. Also, since it uses timeouts you do not have to create expensive promises and cancel them (I should probably look into them for delaying auto save too).

I also renamed `backupAfterMillies`. I found it very weird to have it in the first place because its intent was to delay the delivery of the content change event and it has nothing to do with backups.

**Comment by Tyriar** [comment]
@bpasero might want to make the same changes to the `autoSaveAfterMillies` and the test as well as that's and the cast in the test was based on.

**Comment by Tyriar** [comment]
@bpasero yes the backup stuff is based on the auto save stuff so it should probably change too.

**Comment by bpasero** [comment]
@Tyriar it is a bit more complicated for the auto save case because I have to carry some state into the scheduled call (the version id). Need to tweak the `RunOnceScheduler` to allow for passing arguments over I guess...

**Pull request closed without merging**
