### PR TITLE
`alert` on terminal / chat clear

### LINKED ISSUE #185155: Alert screen reader users that something has occurred when `clear` is used
Reported by @jooyoungseo

Use `terminal: clear` or `chat: clear` as a SR user. 

🐛 there's no indication that that has succeeded. We could alert with info or use an audio cue

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #185155

### CODE REVIEW

**Review by roblourens — APPROVED** [review]
debug console? output channel? search results? Just thinking of other things that get cleared

**Comment by meganrogge** [comment]
Good points, I had assume

**Comment by meganrogge** [comment]
Yep, it already works for those - not the output channel though. They're a little verbose IMO, i'll ask JooYoung what he thinks.

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/issues/194672

**Pull request merged**
