### PR TITLE
Clear open recent. Fix #65935

### LINKED ISSUE #65935: Open recent should not show non-existent folders
### Problem

- Let's say you worked on project `pine/a`, `pine/b`
- One day you rename the parent folder `mv pine foo`
- VS Code keeps all the non-existent folders in Open Recent

If a folder does not exist on disk, or a workspace whose config file no longer exists, Open Recent command should not show it.

### PR DESCRIPTION
**Pull request by octref**

### CODE REVIEW

**Comment by bpasero** [comment]
Not a big fan of running FS operations on each entry whenever the list opens. Also it might confuse people that some entries are not showing up e.g. when an external disk is not connected. Anyhow, this would also have to be fixed in the File > Open Recent menu I guess.

**Comment by Astrantia** [comment]
@bpasero This wouldn't confuse me at all. This change is very welcome and a quality of life improvement.

**Comment by octref** [comment]
@bpasero Make sense, I'll see what alternatives are available. I also think the command should run instantly.

> For slow network connections

For now I'm only checking `file://` schemes so should be fine.

**Comment by octref** [comment]
Decided to drop this PR. Will open another one that introduces a command "Clean Open Recent" that removes unresolvable "Open Recent" entries. The thinking is running `mv` on a folder that contains a lot of workspaces is rare and users shouldn't pay the tax each time.

**Pull request closed without merging**
