### PR TITLE
fixes #92857

### LINKED ISSUE #92857: incorrect data structure description in collections.ts
This function in collections.ts:

```typescript
/**
 * Returns an array which contains all values that reside
 * in the given set.
 */
export function values<T>(from: IStringDictionary<T> | INumberDictionary<T>): T[] {
	const result: T[] = [];
	for (let key in from) {
		if (hasOwnProperty.call(from, key)) {
			result.push((from as any)[key]);
		}
	}
	return result;
}
```

Talks about a set, but a `set` implies uniqueness of values, so perhaps it's better to talk about a `collection`? Unless a set in this case is taken as the `(key -> value)` pairs. In any case the resulting array can't guarantee value uniqueness.

### PR DESCRIPTION
**Pull request by videlalvaro**
This PR fixes #92857

### CODE REVIEW

**Comment by aeschli** [comment]
Not sure. A dictionary is a set. We'll keep it as is.

**Comment by videlalvaro** [comment]
Bummer. I know this is a very low priority issue, but here's where I'm coming from

I was planning to write a blog post about how comments help with code understandability and wanted to use this case about an API that got improved thanks to a simple change.

Here's an article I wrote for the ACM explaining why I think this is important https://queue.acm.org/detail.cfm?id=3127495

And here I wrote about the importance of "paratexts" (as in Literary Theory) or code comments: https://dl.acm.org/doi/10.1145/3191697.3214326

From wikibooks: 

>Sets are groups of items, unordered with duplicates removed. The keys of a dictionary form a set, but each key has an associated value; these values could be duplicated within a dictionary.

I think calling that a set when we could either use `dictionary` or `collection` goes more aligned with what the code does, because `set` has a very specific and narrowing definition related to element uniqueness.

**Comment by aeschli** [comment]
Maybe change it to 'dictionary' ?

**Comment by videlalvaro** [comment]
Thanks.

Should we reopen this PR or go for a new one?

**Comment by videlalvaro** [comment]
@aeschli just updated the PR, thanks!

**Comment by aeschli** [comment]
Thanks @videlalvaro !

**Pull request merged**
