### PR TITLE
only prompt to attach problem matcher when not specified

### PR DESCRIPTION
**Pull request by zackschuster**

### CODE REVIEW

**Comment by dbaeumer** [comment]
@zackschuster can you please comment on why you think this is necessary. If the tasks.json file has an empty arrary then we never ask. This is to distinguish between a task not having a problem matcher in the first place and a task marked as only not needing a problem matcher.

**Comment by zackschuster** [comment]
@dbaeumer really? i've kept getting prompted on refresh (using a workspace in latest insiders), hence the PR. i assumed it was a general thing, but i can file a bug report instead.

**Comment by dbaeumer** [comment]
@zackschuster can you please file a bug report with steps. As said this should not happen if the tasks.json has a problem matcher defined or an empty array.

**Comment by zackschuster** [comment]
couldn't get around to filing a bug report, but it's officially stopped being an issue for me as of today so none needed (for now :smile:).

**Pull request closed without merging**
