### PR TITLE
Add openOnDebugBreak for openDebug

### LINKED ISSUE #49677: Provide an option to that the Debug View is shown automatically when the debugger breaks
Currently if I start my App with another View than Debug View open and the debugger breaks because of a break point or an exception I have to manually switch to the debug view.

It would be incredible if I could set an option to display the debug view in that cases automatically

Thanks for your great Work!

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Fix https://github.com/Microsoft/vscode/issues/49677

CC: @isidorn

### CODE REVIEW

**Comment by escamoteur** [comment]
Awesom, thanks a lot

**Comment by isidorn** [comment]
@Krzysztof-Cieslak thanks a lot for your PR. Merging in 🍻

**Comment by DanTup** [comment]
I usually use `openOnSessionStart` but I'd also like it to switch back to the debug sidebar when I break; is this possible with this change?

**Comment by isidorn** [comment]
Yes

**Pull request merged**
