### PR TITLE
Add Repl Filter (#4338) WIP

### PR DESCRIPTION
**Pull request by YisraelV**
Related to  #4338. @isidorn  this is a basic working version. The design is mostly derived from markers panel, and goes as follows: (I'm over explaining for the sake of documentation)
1. A filter has to be registered with the tree. A filter is a function which accepts a single tree node and decides whether it should be rendered.
2. The repl needs to register a filter action.
3. An action view item corresponding to the above action has to be created. The view item creates the input in the dom, and updates the action state based on user input (the panel itself can't touch the html because it's in the shared space of the toolbar) 
4. The repl listens on changes to the action state, and update the filter accordingly.

Requirements I wanted to discuss:
1. We probably want the matched text to be highlighted? This is implemented only for some of the repl item types.
2. The current filter is fuzzy, for example the pattern "99" matches the text "989".  In my opinion it's too liberal (but it's easier to implement since the renderers expect to receive a fuzzy score as filter data)
3. It's pretty minor but maybe create a new file for the filter stuff? because repl.ts is already very big, 

Also please let me know what is the deadline for this feature so I know if I can undertake this.
Thank you very much!

### CODE REVIEW

**Comment by isidorn** [comment]
@YisraelV thanks a lot for this PR. There is no deadline for this feature. Though next week we are starting our endgame and we stop merging in new feautres so we can do testing.
Due to that I suggest that we do not rush this and we plan to merge this the week after the next. So it will be a part of the end of September release.

I will do the inital review of this tomorrow and will provide feedback. Thanks!

**Comment by YisraelV** [comment]
@isidorn great. I just want to emphasize that the code is not ready for thorough review yet. I only created the PR in order to discuss design and requirement.

**Comment by isidorn** [comment]
Ok, then let me first answer your questions before I do the review.

1. Yes, we do want the Repl elements to be highlighted. Some elements do not support it yet - good catch. We can tackle this as part of this PR or unrelated to this.
2. Fuzzy filtering is fine and I would actually prefer that becuase we already do this across the workbench: problems view and quick open. And also Chrome dev tools also does a fuzzy filter (picture).
3. I think we can create a new file `replActions.ts` and put all the repl actions there (including the new ones which you just added). That way `repl.ts` should get leaner.

For potential inspiration checkout how Chrome dev tools does it. Just open the console and check the filter

I tried it out wihtout looking at the code. Here's some inital feedback:
1. You need positioning it is not nicely centered (checkout what problems is doing)
2. There should be a placeholder text so people discover this
3. I would expect that `esc` even when the focus is in the in Input box to clear the filter
4. Make sure to put an proper aria-label so we do not forget about accessibility
5. The filtering does not seem to work nicely (especially on variables) - checkout the gif. Probably something is missing in the `Variables` class to suport filtering

stderr

Screenshot 2019-08-22 at 17 02 03

**Comment by YisraelV** [comment]
Thanks for your response! I noticed some of the problems, but only meant this is a very basic version. When you have the time I'll appreciate it if you could take a look at the design of the code - mainly what classes are at play and how they interact, not the details as there's still a lot missing as you pointed out.

**Comment by YisraelV** [comment]
Also I didn't see potential code sharing with problems panel but maybe you'll see it differently.

**Comment by isidorn** [comment]
I just checked out the code and the design and the approach with the actions / action items makes a lot of sense.
I can do a more thorough review some time next week once you make more progress. Thanks!

**Comment by isidorn** [comment]
We can think about code sharing with problems once we polish this up
fyi @sandy081

**Comment by isidorn** [comment]
We have added this feature in the meantime, thus closing this PR.

**Pull request closed without merging**
