### PR TITLE
Viewlet Refactor

### PR DESCRIPTION
**Pull request by sbatten**
This PR refs #85164

The goal of this PR is to refactor the Viewlet structure so that code useful to enhancing panels in the same way is separated from the Viewlet inheritance path.

This PR
- Introduces new classes `PaneComposite`, `ViewPaneContainer`. `ViewPaneContainer` encapsulates the `SplitView` and `View`	management behavior currently unique to `Viewlet` in a standalone class. As a derived class of `Composite`, `PaneComposite` composes `ViewPaneContainer` allowing this enhancement behavior to be shared between `Viewlet` and `Panel`.
- Updates all existing derived `Viewlet`s, (e.g. Explorer), to extend from `ViewPaneContainer`. The goal is to make `ViewPaneContainer` implementations agnostic of their `Composite` container (`Panel` or `Viewlet`).
- Implements very simple `Viewlet` classes for each existing `Viewlet` to instantiate the new `ViewPaneContainer`.
- Renames `ViewletPane` to `ViewPane`

### CODE REVIEW

**Comment by isidorn** [comment]
@sbatten the changes you outlined here make a lot of sense to me.
I did not review the code, since there are quite some changes and a lot of it is duplicated work per viewlet if I am not mistaken. Point being: looks good from a birds eye view!

**Comment by sandy081** [comment]
@stevencl I went through the changes and they all looks good to me over all. I did a quick testing and found following

- Title of the view is not show in the title of the viewlet when there is only one view 

image

- Drag n drop of views inside viewlet is not working

- Remote explorer is not showing the filter dropdown

image

Otherwise most of the features are working good. 👏

**Comment by isidorn** [comment]
@stevencl let me know if you would like me to test this out. Or even better create a test plan item and assign me to it.

**Comment by stevencl** [comment]
@sbatten - I think comments from @isidorn and @sandy081 above were for you instead of me... :-)

**Comment by isidorn** [comment]
Yes! Sorry for the ping Steven Clarke :)

**Comment by sbatten** [comment]
@sandy081 updated to fixes the issues you found.

This PR will be checked in when master opens after endgame testing. I'll keep in up to date with master as necessary. Let's use an endgame test plan item (I will create and assign) to harden.

**Comment by sbatten** [comment]
Bringing in from TPI issue so as not to keep an issue open for non-checked in code:
- [ ] Debug view is not merged into viewlet header if it only view in debug viewlet #86056

**Pull request merged**
