### PR TITLE
fix parsed JSDoc author tag

### PR DESCRIPTION
**Pull request by hypercubestart**
addresses #80790 

I believe this is the best method of rendering the hover JSDoc author tag email address correctly, but open to any suggestions.

Also, I am unsure whether this issue also pertains to https://github.com/microsoft/vscode/blob/7aff0c42c8e2012bd2eab6e25bd6fed25c5b05be/src/vs/base/common/marked/marked.js#L820-L841 since both if statements handle `mailto`

### CODE REVIEW

**Comment by hypercubestart** [comment]
@jrieken can you review my PR please? thanks!

**Comment by mjbvz** [comment]
Thanks for looking into this issue. However this file is at a very low level in VS Code (and from the external `marked` library)

Instead, I think we should scope the fix to just the TypeScript extension. Here's the file where I believe this logic lives: https://github.com/microsoft/vscode/blob/8891b8551861cb72b76d6ae7d93c7a14cefa778f/extensions/typescript-language-features/src/utils/previewer.ts#L9

**Comment by hypercubestart** [comment]
@mjbvz I don't think limiting the fix to the TypeScript extension is possible. The first level of hover is correctly generated by the Typescript extension, but the contents of the second level of hover which displays the obfuscated email address seem to be generated from the marked.js file. Please advise.

**Comment by hypercubestart** [comment]
@mjbvz can you please re-review? Thanks!

**Comment by mjbvz** [comment]
Thanks! Fix will be in the next insiders build and is scheduled to go out with VS Code 1.42

**Pull request merged**
