### PR TITLE
Introduce Ctrl+D/Cmd+D temporary overwriting for find widget toggles

### LINKED ISSUE #8869: Ctrl+D should match whole words instead of substrings
Is there a way to highlight matching whole words of the word under cursor instead of all substrings?
In VScode, the current behaviour:
image
What I want (as seen in Sublime):
image
This is actually the default behaviour in Sublime Text and IntelliJ based IDEs.

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #8869

#### Ctrl+D temporary overwriting of the find widget toggles
* only when starting with a collapsed selection on a word, Ctrl+D will override the find widget flags: `wholeWords: true, matchCase:true, isRegex: false`. 
* for as long as Ctrl+D is pressed again, continuously, those flags will remain the effective search flags.
* if a find widget toggle is explicitly changed (e.g. pressing alt+w or alt+c or clicking on a toggle), or if editor focus is lost, or if the selection changes explicitly, the overrides will be reset.

### CODE REVIEW

**Comment by alexandrudima** [comment]
Some flows:
* in all cases the selection highlighter shows what Ctrl+D will do next

#### Find widget closed - starting with a collapsed selection
 * Ctrl+D uses `wholeWords: true and caseSensitive: true`
 * the find options are briefly shown to reflect the temporary overriden settings


#### Find widget closed - starting with a non-collapsed selection
 * Ctrl+D uses the find options
 * the find options are briefly shown


#### Find widget opened - starting with a collapsed selection
 * Ctrl+D uses `wholeWords: true and caseSensitive: true`
 * the find options reflect the temporary overriden settings
 * as soon as the editor loses focus, the find options rollback to their pre-Ctr+D values.


#### Find widget opened - starting with a collapsed selection
 * Ctrl+D uses the find options

**Comment by innerlee** [comment]
> find options are briefly shown

I find the options quite useful but their lives are too short. They always disappear when I want to click on them. Could these buttons be available at the status bar? If this request makes sense, then I will mv it to a issue.

**Comment by alexandrudima** [comment]
@innerlee I would not add any extra space for them. The reason for them popping up (only when doing `ctrl+D` or `ctrl+shift+L`) is to provide a bit of visual explanation of the used searched settings in the case when the find widget is closed. I would not want to waste any permanent screen estate on those. We can increase their timeout, but they're mostly a quick reminder guide (in the case the find widget is closed)

**Comment by innerlee** [comment]
I reconsidered the request to be not that useful. 99% of the case when I want to click the transient buttons is to set match cases to true. With the change of this pr, I do not need to care about their status most of the time.
But yeah, increase a little timeout will be good :)

**Comment by DaltheCow** [comment]
When I click on the 'Abl' or 'Aa' section I intend to turn that feature off until I turn it back on manually. Is there a way to make this remember that I don't want whole word match on? Because I often I don't want whole word match on when I'm using this

**Pull request merged**
