### PR TITLE
Enable Shift-Insert to paste primary clipboard on Linux, fixes #36170.

### LINKED ISSUE #36170: Shift-insert should insert the PRIMARY clipboard on Linux, not the CLIPBOARD clipboard
- VSCode Version:

Version 1.16.1
Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
Date 2017-09-14T16:26:20.018Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Linux dv 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Select some text with the mouse. This puts it in the PRIMARY clipboard.
2. Press Shift+Insert.

In well-behaved Linux applications, this will paste in the text you just selected. In vscode, however, it pastes in the text in the CLIPBOARD clipboard. To insert the text in the PRIMARY clipboard, you must precisely position the mouse cursor and middle-click.

https://wiki.archlinux.org/index.php/clipboard

Reproduces without extensions: Yes/No

### PR DESCRIPTION
**Pull request by sameer**
This PR fixes #36170 -- the Shift-Insert key combo will paste the primary clipboard as expected on Linux. 

I also removed code related to using the mouse middle-click to paste the primary clipboard because it actually did nothing. [`clipboard.readText('selection')`](https://electronjs.org/docs/api/clipboard#clipboardreadtexttype) just reads the text, it does not generate a paste event as the comment originally on line 55 suggests. Pasting the primary clipboard with middle-mouse works out-of-the-box as far as I can tell.

### CODE REVIEW

**Comment by sameer** [comment]
Hi @alexandrudima , just wondering if you have had a chance to look at this yet.

**Comment by sameer** [comment]
Hi @alexandrudima, when you have some time could you please take a look at this PR? Thank you.

**Comment by perlun** [comment]
@Tyriar @bpasero Any chance you could help getting someone to review this? It seems to have been floating around for very long, so would be great to get it reviewed & hopefully merged anytime soon.

**Comment by Tyriar** [comment]
@perlun @alexdima is probably the only one who can sign off on this one.

> `if (e.equals(KeyMod.Shift | KeyCode.Insert)) {`

I will say though that the current implementation probably isn't good enough as it hardcodes shift+insert instead of registering a custom keybinding.

**Comment by alexdima** [comment]
Thank you!

**Comment by evs-xsarus** [comment]
The behavior having SHIFT + INS pasting the now set clipboard fails when wanting to replace a piece of text. Done by first selecting that text. As I've never seen this behavior on linux before, I believe another shortcut for this keybinding should be better.

**Comment by perlun** [comment]
> The behavior having SHIFT + INS pasting the now set clipboard fails when wanting to replace a piece of text. Done by first selecting that text. As I've never seen this behavior on linux before, I believe another shortcut for this keybinding should be better.

It is true that it isn't present in all applications, but it exists in at least the following tools (terminal emulators):

- xterm
- Terminator

Some other tools use mouse button 2 (or middle button) for this. In IntelliJ it is configurable.

image

----

Anyway, if you dislike the new behavior, I suggest just overriding the keyboard bindings in this view. You can probably make Shift-Insert be an alias for the regular keyboard there as well if you like. (unsure if this can be done using the UI or if you have to hack the `.json` file in that case)

image

**Comment by vushe** [comment]
This new behavior is super weird and confusing. I support @evs-xsarus, another key combination should be offered.

**My current workaround:**

~/.config/Code/User/keybindings.json
```
    {
        "key": "shift+insert",
        "command": "editor.action.clipboardPasteAction",
        "when": "textInputFocus && !editorReadonly"
    },
```

**Comment by Tyriar** [comment]
Shift+insert is acting as expected now. If you want it to paste from the regular clipboard (not primary) you should use the workaround.

**Comment by perlun** [comment]
@vushe It's only weird for people used to Shift-Insert and Ctrl-V doing "the same thing", i.e. pasting from the clipboard (not from the primary selection). For people expecting these to do different things, the previous semantics felt odd.

Quoting @tobia in [the original issue](https://github.com/microsoft/vscode/issues/36170#issuecomment-338663417):

> That being said, terminal emulators and traditional Linux programs do make the distinction and developers and hackers make regular use of it.

I am happy to see that VS Code has now moved to becoming a "traditional Linux program". :wink: 

However, I do sense that there is a bit of a storm of people disliking the new behavior, and it's up to you @Tyriar and others to decide. I like the new default, but I could live with the default being changed (given that it's easy to edit the preferences to switch back to the new mode anyway)

**Comment by Tyriar** [comment]
The old behavior was a bug imo, maybe we could add a FAQ to the linux docs if it is a common issue though.

**Comment by Tyriar** [comment]
Can see some people having problems in linked issues of https://github.com/microsoft/vscode/issues/90222

**Comment by vushe** [comment]
@perlun, yes it's pretty confusing when you updated program and in the middle of work process have to search in Google, what has happened with `Shift+Insert`. But good that VS Code now supports feature I have never heard about. It's ok, as I wrote, I found a workaround.

@Tyriar, `Ctrl+Ins` still copies text. I don't know if this is consistent, and from that perspective doubt it was a bug before.

In any case, this is just my opinion and I'm happy that everyone's happy.

**Pull request merged**
