### PR TITLE
feat: detect default stash message microsoft#106907

### LINKED ISSUE #106907: when stashing, use commit message if populated
Current Behavior:
I have staged changes and typed a commit message.
I choose Stash > Stash
I am prompted to enter a stash description

Desired Behavior:
If commit message is entered, automatically use it as the stash description instead of prompting.

### PR DESCRIPTION
**Pull request by dfireBird**
This PR fixes #106907

Use commit message as default stash message if commit message box is populated.

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I would put this behind a setting. The text in the commit box might be equal to the commit template, which would be a poor indicator of a good stash message. Optionally, we can compare the value against the last known template message and only use it if it doesn't equal the template message.

**Comment by dfireBird** [comment]
By setting do you mean, a setting in preferences to toggle whether to use commit message as default stash message?

Sorry I never used git commit template, so I didn't knew about it. I can change the code.

**Comment by nrayburn-tech** [comment]
Yes, a user setting that can be configured.

When I am looking to add a setting, I search for a setting that I know exists. Then kind of follow what was needed to implement it. For example, you could search for “search.actionsPosition” in the src folder. Then you should be able to find it and see what sort of implementation you need. (It may be better to search for a git setting, so you’re in the same area already.)

Somebody else may be able to give you better details about what exactly is required. I don’t work in it enough to know the specifics.

**Comment by dfireBird** [comment]
> Yes, a user setting that can be configured.

I figured that out and already added in commit 94ab148 in my fork.
I also figured how to add a setting based on previous implementation of settings.

**Comment by dfireBird** [comment]
@joaomoreno Is this PR still in review?

**Pull request merged**
