### PR TITLE
Ensure hygiene filters are restored before moving to next task

### PR DESCRIPTION
**Pull request by Tyriar**
See https://github.com/Microsoft/vscode/pull/14115/files/2e1545d59d67c27f60e10cf32f11c74841dfa1d6#diff-97f7cff0ca69e05dd0c8b3914440d43f - this is probably an issue on all platforms. Perhaps the reason it's mainly been an issue for me is that I don't have the tslint extension installed?

### CODE REVIEW

**Comment by joaomoreno** [comment]
@Tyriar The funnelling behaviour is intentional. The rationale, at least for its original implementation, was:

all ⊃ eol ⊃ indentation ⊃ copyright ⊃ typescript

Each of those is a set of files.

Does this not apply anymore?

**Comment by Tyriar** [comment]
@bpasero kept telling me to fix my files, the reason being is that the coverage of the pre-commit hook is far smaller than the tslint extension.

The file I wanted that was getting skipped was `src/vs/code/test/electron-main/backup.test.ts`. `copyrightFilter` removes the pattern `'!**/test/**' for some reason would be the underlying cause if the tunnel was intentional, why wouldn't copyright statements be required for tests?

**Comment by joaomoreno** [comment]
Not really sure why. Let's not filter them out at that step then, see what happens. 👍  Should I look into it?

**Comment by Tyriar** [comment]
Removing it probably won't give any new warnings for tslint as `gulp tslint` runs exclusively with `tslintFilter` anyway.

**Comment by joaomoreno** [comment]
Oh I see, the subset of files in `gulp tslint` is larger than the one in `gulp hygiene`.

Fixed that in d5e8fcf by adding removing the `**/test/**` filter and fixing all the hygiene issues in there. Now, the subset of files that pass through `tslint` when running `gulp tslint` is the same as when running `gulp hygiene`. 👍

**Comment by Tyriar** [comment]
Thanks @joaomoreno!

**Pull request closed without merging**
