### PR TITLE
#36346 case sensitive sorting

### PR DESCRIPTION
**Pull request by ryanleecode**
There's no setting for` Intl.Collator `to do what we want here so I think this is the best option.

### CODE REVIEW

**Comment by bpasero** [comment]
@drdgvhbh creating a collator is can be an expensive operation, it should only be created once and then shared like the one we have already.

**Comment by drdgvhbh** [comment]
should be okay now.

**Comment by bpasero** [comment]
@drdgvhbh wouldn't it be much easier to have another `Intl.Collator` around that has the caseFirst option set instead of having to do the compare ourselves? I am fine creating this `Collator` as long as it is only created once and reused.

**Comment by drdgvhbh** [comment]
@bpasero I already looked in to that. The problem is there's no setting that will allow the `Intl.Collator` to compare the way we want. Take a look at this, its the same three words from #36346. 

https://jsfiddle.net/mnpjc3e2/1/

If you run that, the sorting order is still alphabetical, regardless of whether a word is all capitals. The sorting order that the we want is all capitals before all lowercase.

**Comment by bpasero** [comment]
Oh yeah, too bad that caseFirst does not seem to be supported in Chrome. I find the suggested fix quite complicated and worry about the runtime performance. I will revisit this later, but currently other things are requiring more attention from me.

**Pull request closed without merging**
