### PR TITLE
feat: decoration support `textUnderlinePosition`

### PR DESCRIPTION
**Pull request by bytemain**
I want to create an editor's decoration the same as the link:

CleanShot 2022-08-22 at 12 21 56@2x

but `vscode.window.createTextEditorDecorationType` only support `textDecoration` property.

CleanShot 2022-08-22 at 12 19 15@2x

```ts
const underlineDecoration = vscode.window.createTextEditorDecorationType({
  textDecoration: 'underline',
  // this is currently not support
  textUnderlinePosition: 'under',
});

```

### CODE REVIEW

**Comment by jrieken** [comment]
> I want to create an editor's decoration the same as the link:

There is a `vscode.DocumentLinkProvider` for that. Have you been aware of that? Any reason for not using it?

**Comment by bytemain** [comment]
yes, I know `vscode.DocumentLinkProvider`. I'm already using `Go To Definition` to archive the effect of jumping to other file, I'm just want the visual effect of link.

**Comment by jrieken** [comment]
Please share detail for why you need to do that? Also note that a link provider isn't what's used for go to definition. The API tries to establish "data-contracts", like return links, completions, definition etc, and not so much UX API. E.g we don't something to look like a link but not be backed by a link data structure

**Comment by bytemain** [comment]
For me, what I want to do is **Highlight the `<search>` element**, because it is different from other element, it is wrote by user, and user can use `Cmd+Click` to jump into the `search` element definition file.. So I gave it a `key point marker`, so I use `createTextEditorDecorationType` to do that. I think that the `link style` is a good hint for this.

**Comment by bytemain** [comment]
And I think this PR is an enhancement for the `createTextEditorDecorationType`, We provide more css style for user, and user can do what they want do

**Comment by bytemain** [comment]
Why don't I use `DocumentLinkProvider` because `LinkProvider` cannot jump into specific line of a file.

**Comment by jrieken** [comment]
Oh, of course it can. Just use a fragement with line-number and column, like `file:///foo/bar#L12,34` for line 12, column 34

**Pull request closed without merging**
