### PR TITLE
[RFC] Add extension Id to proposed api

### PR DESCRIPTION
**Pull request by Linskeyd**
Currently, extension publishers who create shared modules that they use across multiple extensions have to use boiler-plate to make shared modules context aware of which extension owns them.  

One boiler-plate approach for this is using the 'activate' method of an extension to pass the Id of the extension to a shared module, to let that module know which extension is using it.  If the vscode API exposed the activating extension Id, then the shared module could just depend on vscode and use the Id directly instead of requiring the extension developer to explicitly pass in the Id during extension activation.

Submitting this as an RFC to get the VS Code team's thoughts on this addition.  Happy to add tests to protect this if we decide to move forward with this change.  I'd also be happy to add other fields to a shared property that holds other extension metadata if the team wants to expose more than just the extension Id from the IExtensionDescription typed object.

Note: I noticed the '// Proposed' comment at the bottom of the extHost implementation.  Would you rather I move this addition to that section?

### CODE REVIEW

**Comment by Linskeyd** [comment]
It seems like the CLA signing is broken; I've tried multiple browsers but signing still seems to not submit properly.

**Comment by jrieken** [comment]
> have to use boiler-plate to make shared modules context aware of which extension owns them

What is the use-case for that? Is a shared module a util-collection like `path`? Why is the extension id (and not some other unique identifier) needed here?

**Comment by Linskeyd** [comment]
@jrieken you are correct that this would be used for shared util modules.  The reason to use extension Id over a different unique identifier is that extension Id is unique and also readily developer/user readable.  

One use-case we have is a utility that provides a "batteries included" experience for logging, where we can add things like named output channels per extension by simply importing a logger and using it (no passing of the exact extension Id necessary since with this PR the module could just get that from the VS Code API).  As you can imagine however, this could be expanded to other utility modules to enable them to identify artifacts/integrations in a developer friendly way.

**Comment by jrieken** [comment]
Can you sketch up how you would use this API? Would the shared lib import/require vscode and read that value?

**Comment by Linskeyd** [comment]
@jrieken Yes the shared lib would import vscode and read that value.  The code sample below illustrates this.

Extension A would take a package.json dependency on module B (where module B also depends on vscode). In module B's index.ts:

```
import * as vscode from 'vscode';

const EXTENSION_ID = vscode.extensionId;

export async function myUtilityFunction(arg: string): void {
    // Do other work with extension Id already known, not needing to be passed.
}
```

Without this change, the module would first require some initialization and validation (or to be passed to the exported function each time):

```
import * as vscode from 'vscode';

let EXTENSION_ID;

export function initialize(extensionId: string): void {
    // ... Perform validation on extensionId.
    EXTENSION_ID = extensionId;
}

export async function myUtilityFunction(arg: string): void {
    // Do other work with extension Id already known, not needing to be passed.
}
```

**Comment by jrieken** [comment]
> @jrieken Yes the shared lib would import vscode and read that value. The code sample below illustrates this.

The problem is that the value of the extension id is determined by looking at the file path that makes the request for 'vscode', e.g the file containing `require("vscode")`, and correlating that to an extension folder. If a lib is truly shared, e.g not copied in multiple node_modules folders, then this doesn't work (because it isn't contained in any extension folder). 

So, generally I think the approach is risky and error-prone, apart from the model questions, e.g vscode.env.extensionId doesn't make that much sense when vscode.env talks about the editor environment.

I think a less magically but more explicit solution would be better. Maybe have `ExtensionContent#extension` pointing the current extension so that it's easier retrieve your own id and other metadata.

**Comment by Linskeyd** [comment]
@jrieken, by shared I meant that both extensions would utilize the module, not that they necessarily had the same copy of the module (they would indeed, at least with VS Code's current model of packaging, each get a copy of the module).  In that case, where each extension has a copy of the shared module, the shared module would be able to accurately retrieve the extension Id from the 'vscode' api.  This also wouldn't be on the vscode.env.extensionId, it'd be on vscode.extensionId.

I'd be happy to have your suggestion though, where instead of having to pass a string literal, I could just get the extension context of the current extension and leverage that.  I'd be happy to write up a PR for that if you'd like.  Looks like I could update ['__loadExtensionContext' in 'extHostExtensionService.ts'](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostExtensionService.ts#L343).

**Comment by jrieken** [comment]
Check. Closing this PR in favour of a slight more explicit but clean solution, e.g `ExtensionContext#extension`. There is an [`Extension`](https://github.com/microsoft/vscode/blob/d10c9f75163176df87817ef06750365cd76976be/src/vs/workbench/api/common/extHost.api.impl.ts#L918)-type that you wanna reuse but likely have to extract into its own type first

**Pull request closed without merging**
