### PR TITLE
Make folding icons themeable

### LINKED ISSUE #87702: [folding] Allow folding controls to be themeable
I do not see a way to set the theme colour of the folding controls in the gutter.  The same is also true of the 'edit' control used for certain settings.json options.

### PR DESCRIPTION
**Pull request by miguelsolorio**
This PR fixes #87702 and makes the folding icons themeable via `editor.foldForeground`. I tried to keep the same naming convention as `editor.foldBackground`.

image

### CODE REVIEW

**Comment by misolori** [comment]
I also intentionally left out the "edit" controls from the settings UI as those aren't part of folding:

image

**Comment by aeschli** [comment]
`editor.foldBackground` is the color behind a folded range.
image

So `editor.foldForeground` is probably confusing.

What about `editorGutter.foldingIconForeground`

**Comment by misolori** [comment]
Good point, do you think users would know what a "folding controller" is? That's my only concern using the term "controller" as opposed to "icon".

**Comment by usernamehw** [comment]
Would it be possible to make 2 colors for each state: `expanded` / `collapsed` ?

**Comment by gjsjohnmurray** [comment]
> 
> 
> Good point, do you think users would know what a "folding controller" is? That's my only concern using the term "controller" as opposed to "icon".

I support @aeschli's proposal of `editorGutter.foldingControlForeground`. It uses the term "folding control", not "folding controller".

See comments on #89919 clarifying that "control" is preferred over "icon".

**Comment by innerlee** [comment]
How about enabling > and V to have different colors?

**Comment by misolori** [comment]
@aeschli updated the color token to use `editorGutter.foldingControlForeground`.

**Comment by aeschli** [comment]
Thanks @misolori !

**Pull request merged**
