### PR TITLE
experiment with html-zone

### PR DESCRIPTION
**Pull request by jrieken**
Some experiment with embedding web views into the editor. fyi @DonJayamanne

### CODE REVIEW

**Comment by jrieken** [comment]
To get a feel for this, add this keybinding

```
	{
		"key": "cmd+l l",
		"command": "_workbench.htmlZone",
		"when": "editorTextFocus"
	}
```

**Comment by DonJayamanne** [comment]
@jrieken , had a look at this and looks great. It is as discussed.
One problem I have with this approach (identified early on and discussed in our meeting) is the fact that I won't necessarily know the height of the contents, until they are rendered.

Sometimes, the contents could be an image, sometimes an iFrame, and sometimes javascript code.
Is it possible to build in an event that could be triggered to cause the html zone to resize.

The workflow would be as follows:
- we provide the html
- html zone is added with a default height of 4 lines
- once loaded, we measure the height (some how, not sure)
- Then we trigger the resize event of the zone

**Challenges:**
- passing back the calculated height from html webview into the extension (up-to extension author to figure this out or generic vs code solution - to auto resize zones)
- triggering a resize of the zone (vs code api)

I'll try to have a play with the changes. Thanks

**Comment by jrieken** [comment]
Understood - I think the height challenge can be tackled with a two step approach. Unsure if we can measure things from the *outside* but a zone can be always be resized afterwards or we add a sash to them (like in reference search)

My biggest current challenge is that there are layout issues with the web view. Often, for yet unknown reasons, it doesn't use its full (assigned) width. Makes me a little less positive about this...

**Comment by DonJayamanne** [comment]
>we add a sash to them (like in reference search)

Yes found that, was hoping we could expose that in some form. Cheers.

>Unsure if we can measure things from the outside

Agreed. That's one of the reason why I thought we could measure it form within the zone and then pass the information back to the extension and then again pass that information to vscode... fun and games :)

**Comment by jrieken** [comment]
@DonJayamanne I going to merge this despite it being more or less useless. I have spent quite some time just hunting layout weirdness (depending on multiple editor, screen resolutions etc) and I'd like to hear what you experience. 

A snippet using this goes like this:

```ts
    vscode.commands.registerCommand('extension.runInNode', () => {
        if (!vscode.window.activeTextEditor) {
            return;
        }
        const {viewColumn, selection} = vscode.window.activeTextEditor;
        if (!viewColumn) {
            return;
        }
        const resource = vscode.Uri.parse('testing:foo/bar/' + Date.now());
        return vscode.commands.executeCommand('_workbench.htmlZone', { editorPosition: viewColumn - 1, lineNumber: selection.active.line, resource });
    });

    const contentProvider = new class implements vscode.TextDocumentContentProvider {
        provideTextDocumentContent(uri: vscode.Uri, token: CancellationToken): string {

            return `<html>
            <body style="background-color: pink;">
                <h3>Hello World at ${new Date()}</h3>
            </body>
            </html>`;
        }
    }
```

There is a *very* long list of things that don't work. To name a few

* zone doesn't update when document updates
* zone cannot be clicked on
* zone has fixed height
* zone dies when editors are shuffled around


Again, this is to get feedback on the basics... The test would be if your zone always takes full width of the editor (as shown below) and isn't weirdly cropped on the right side

screen shot 2016-10-20 at 17 03 23

**Comment by DonJayamanne** [comment]
@jrieken 
Thanks, I will look at these and will post my feedback on https://github.com/Microsoft/vscode/issues/3220

**Pull request merged**
