### PR TITLE
Remove some duplicate configuration nodes

### PR DESCRIPTION
**Pull request by mjbvz**
For #79144

Currently we duplicate information for the `editor` and `workbench` configuration nodes in a few places (also duplicating the strings to be localized). This change extracts some of those to be constants instead

### CODE REVIEW

**Comment by sandy081** [comment]
As you mentioned in the issue, is not that the right way is to separate the section and configurations?

**Comment by mjbvz** [comment]
Yes that would be better overall. My goal with this PR is to reduce code duplication without requiring any new internal apis or making extensive changes. It's a step towards what was proposed in #79144

**Comment by sandy081** [comment]
Ok. Please get it reviewed from respective code owners.

**Comment by bpasero** [comment]
I think this change makes sense to me from the workbench level 👍

**Review by jrieken — COMMENTED** [review]
No strong feelings here but if there is a push for re-use wouldn't it be better to have `registerEditorConfiguration` and `registerWorkbenchConfiguration`? That could mean only one import (real code savings) and more overall simplicity.

**Comment by mjbvz** [comment]
Merging this initial step. We can continue tracking code quality improvements in #79144

**Pull request merged**
