### PR TITLE
fix download issues in webviews

### LINKED ISSUE #108602: Unable to click download button in a webview
- VSCode Version: 1.48.2 to latest insiders
- OS Version: linux kernel 4.18

Steps to Reproduce:

1. In an extension, create a webview which uses FileSaver js library , to save something in a file from a "save" button within the webview
2. Make sure you load the webview with `{ enableScripts: true, retainContextWhenHidden: true, enableCommandUris:true }`
3. try the extension. In VSCode before 1.48, there was no problem

The extension where I discovered the problem is `senx.warpscript-language` , in the WarpScript [image webview](https://github.com/senx/VSCode-WarpScriptLanguage/blob/master/src/webviews/imagePreview.ts).

Does this issue occur when all extensions are disabled?: No

It seems Chrome engine added another layer to sandbox default security in the meantime, now allow-downloads is necessary within the iframe sandbox settings. PR coming soon.

### PR DESCRIPTION
**Pull request by pi-r-p**
This PR fixes #108602

### CODE REVIEW

**Comment by pi-r-p** [comment]
I am pretty sure other Visual Studio Code extension developers will get the same problem...

**Comment by mjbvz** [comment]
Make sure to also add this in https://github.com/microsoft/vscode/blob/3b99352509cb2bf0cfc65fc567cea100e4a8a279/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L70

**Comment by pi-r-p** [comment]
Done. I was wondering why there is typescript + javascript here. Modifying typescript only do not have effect on the final build. Is there a transition ongoing ?

**Comment by mjbvz** [comment]
Thanks!

**Pull request merged**
