### PR TITLE
Make default JS renderer treat js as modules

### LINKED ISSUE #157076: JavaScript evaluated by the Notebook renderer is evaluated in the global scope
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: All
- OS Version: All

Steps to Reproduce:

1. Create a jupyter notebook with Pyhton
2.Run the following cell twice and have a look at the console output in the renderrers
```js
%%javascript
const helloWorld = 2134;
```

Basically the error indicates the fact that the const `helloWorld` has already been declared once before.

The problem is we're evaluating the JS in the same global scope.
Jupyter doesn't seem to be evaluating them in the global scope.

**Here's the problematic code**
```typescript
function renderJavascript(outputInfo, container) {
  const str = outputInfo.text();
  const scriptVal = `<script type="application/javascript">${str}</script>`;
  const element = document.createElement("div");
  const trustedHtml = ttPolicy?.createHTML(scriptVal) ?? scriptVal;
  element.innerHTML = trustedHtml;
  container.appendChild(element);
  domEval(element);
}
```

Not sure if others (extensions) rely on this to run in the global scope, hence I'd suggest adding a metadata for JS mimetypes to ensure the code is evaluated in a private scope, e.g. `isolated`.
Jupyter has similar concepts when rendering HTML, https://ipython.org/ipython-doc/3/notebook/nbformat.html#output-metadata

Perhaps we could do the same thing, to ensure the existing functionality stays as is (for the benefit of existing extension authors).

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #157076

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@mjbvz wouldn't this cause things to get evaluated in a different order.
E.g. what if we have 2 outputs:
* First output has mime type javascript, the JS code declares a global var e.g. `window.xyz = 1234`
* Second output has mime type html with a script tag and that code consumes `window.xyz`

Now. the JS code in both of them could run in a reversed order.
I feel this could break outputs.

Note, with plotly I can see that they do this kind of stuff, first output runs some js and setups the environment & the second output will have some JS that depends on the first being executed in order.

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
@mjbvz wouldn't this cause things to get evaluated in a different order.
E.g. what if we have 2 outputs:
* First output has mime type javascript, the JS code declares a global var e.g. `window.xyz = 1234`
* Second output has mime type html with a script tag and that code consumes `window.xyz`

Now. the JS code in both of them could run in a reversed order.
I feel this could break outputs.

Note, with plotly I can see that they do this kind of stuff, first output runs some js and setups the environment & the second output will have some JS that depends on the first being executed in order.

**Comment by mjbvz** [comment]
@DonJayamanne I believe modules are still evaluated in order. See the [mdn documentation on `defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer)

This change does not mark the scripts as `async`, which could run the scripts out of order (but probably won't for inline scripts)

**Comment by DonJayamanne** [comment]
I'm checking this from the same docs page, I'm probably misunderstanding it
Will need to test this out.

> module: Causes the code to be treated as a JavaScript module. The processing of the script contents is deferred.

**Comment by mjbvz** [comment]
@DonJayamanne I confirmed that the outputs are evaluated in order for simple cases. For `defer`:

> Scripts with the defer attribute will execute in the order in which they appear in the document.

I believe that also applies to modules

**Review by DonJayamanne — APPROVED** [review]

**Pull request merged**
