### PR TITLE
Replace @@ICON@@ in the flatpak gulp task

### LINKED ISSUE #44519: The flatpak gulp task forgets to replace all the placeholders
- VSCode Version: 1.20.1
- OS Version: Fedora 27

Steps to Reproduce:

1. Build the flatpak via `gulp vscode-linux-x64-flatpak`
2. The resulting `.desktop` file still contains placeholder `@@ICON@@`

Does this issue occur when all extensions are disabled?: Not Applicable

### PR DESCRIPTION
**Pull request by amtlib-dot-dll**
Fixes #44519

### CODE REVIEW

**Comment by amtlib-dot-dll** [comment]
I only changed Linux-related code, and I don't know why the Windows build failed :joy: 

The Linux build succeeded and probably the original code on the master branch will fail on AppVeyor

**Comment by Tyriar** [comment]
Changing the desktop file will break the icon in all the other packages unfortunately. I will likely be removing the flatpak task in the future as the burden of maintenance should be on those that are using it.

**Comment by amtlib-dot-dll** [comment]
Thank you for your information, by the way, may I ask why the icon property in the desktop file have different values? :joy: Thanks

**Comment by Tyriar** [comment]
@amtlib-dot-dll not sure how flatpak works, but it gets filled in with the app name "code" or "code-insiders" which resolves to the icon placed in pixmaps (for deb and rpm).

**Comment by amtlib-dot-dll** [comment]
Well but I am still puzzled because https://github.com/Microsoft/vscode/blob/1.20.1/resources/linux/code.desktop#L6 and https://github.com/Microsoft/vscode/blob/1.20.1/resources/linux/code.desktop#L18 is different, different?? 🤔I wonder why

In the deb package they are substituted to the same value https://github.com/Microsoft/vscode/blob/1.20.1/build/gulpfile.vscode.linux.js#L57-L58

So as the rpm package https://github.com/Microsoft/vscode/blob/1.20.1/build/gulpfile.vscode.linux.js#L133-L134

I am not familiar with how snappy works, but it is the only place where they are substituted to different values https://github.com/Microsoft/vscode/blob/1.20.1/build/gulpfile.vscode.linux.js#L57-L58

Thanks!

**Comment by amtlib-dot-dll** [comment]
> which resolves to the icon placed in pixmaps (for deb and rpm).

If only deb and rpm matters, changing https://github.com/Microsoft/vscode/blob/1.20.1/resources/linux/code.desktop#L18 to be the same as https://github.com/Microsoft/vscode/blob/1.20.1/resources/linux/code.desktop#L6 is OK because `@@NAME@@` and `@@ICON@@` are replaced by the same value, and therefore

> Changing the desktop file will break the icon in all the other packages unfortunately.

This may not happen 😃

**Comment by Tyriar** [comment]
I agree :smile: thanks for looking into it, I think it was an error that it's `@@NAME@@` in the other action. I can merge this in if you reopen/restore the branch.

**Comment by amtlib-dot-dll** [comment]
Thanks, I've created a new PR https://github.com/Microsoft/vscode/pull/44752 because the original one is deleted :smile:

**Pull request closed without merging**
