### PR TITLE
Add playwright-python to workspace tags

### PR DESCRIPTION
**Pull request by arjunattam**
This PR adds the [playwright](https://pypi.org/project/playwright/) module to workspace tags for Python.

cc @sana-ajani

### CODE REVIEW

**Comment by sana-ajani** [comment]
can you add the GDPR comment?

**Comment by arjun27** [comment]
Thanks for the review. Just added the comment for GDPR

**Comment by sana-ajani** [comment]
LGTM, @RMacfarlane can you review?

**Review by RMacfarlane — APPROVED** [review]
Looks good!

**Pull request merged**
