### PR TITLE
Fix single line if/else and loop indentation for Typescript and PHP

### PR DESCRIPTION
**Pull request by ssigwart**
This PR addresses #43244.  It does not solve the all the issues in there.  In particular, while I like single line `if` statements without brackets, I don't want VS Code to assume all my `if` statements are going to be a single line for 2 reasons:
1.  If I do add brackets, it then looks like this:
  ```typescript
  if (1)
    {
      console.log('');
    }
  ```
2.  I don't want to break other people's workflows.  It seems more intuitive to hit tab once if you want to do a single line `if` versus having to hit backspace if it were to assume it's going to be one line.

Here are the parts addresses:
- https://github.com/microsoft/vscode/issues/43244#issuecomment-436351839
- https://github.com/microsoft/vscode/issues/43244#issuecomment-380336219 - In particular where it mentioned hitting `ENTER` after a single line `if`.

Below are some sample files to test with.

### Typescript
```typescript
if (1)
	console.log('deindent');
else if (2)
	console.log('deindent');
else
	console.log('deindent');

// Change doesn't make this de-indent where after 2, 3, of 4
if (1)
	if (2)
		if (3)
			if (4)
				console.log('so dangerous');
			else
				console.log('deindent'); // Doesn't decrease indent by 2 after this line, but this is so dangerous of a format I don't want to support it


while (1)
	console.log('deindent');

for (var i = 0; i < 5; i++)
	console.log('deindent');

var i = 1;
if (i === 1)
	console.log('log from if');

console.log('line two'); // Alt-Down here should not indent
console.log('line one'); // Alt-Up here should not indent
```

### PHP
```php
<?php

if (1)
	echo('deindent');
else if (2)
	echo('deindent');
elseif (3)
	echo('deindent');
else
	echo('deindent');

// Change doesn't make this de-indent where after 2, 3, of 4
if (1)
	if (2)
		if (3)
			if (4)
				echo('so dangerous');
			else
				echo('deindent'); // Doesn't decrease indent by 2 after this line, but this is so dangerous of a format I don't want to support it


while (1)
	echo('deindent');

for ($i = 0; $i < 5; $i++)
	echo('deindent');

foreach ($arr as $val)
	echo $val . "\n";
```

### CODE REVIEW

**Comment by ssigwart** [comment]
I rebased this to fix a merge conflict.  It's a fairly simple change that would solve a pretty annoying daily issue.  It would be great if this could get merged.

**Review by aviden — APPROVED** [review]

**Review by aviden — DISMISSED** [review]

**Comment by ssigwart** [comment]
@rebornix, is there anything else I need to do to get this PR merged or is it just waiting on someone to have time to review it?

**Comment by ssigwart** [comment]
@hediet, if you could look at this one, I'd really appreciate it. Basically, it adds a deindent after single line code for PHP/TS/JS. For example, if you put your cursor where the `|` is below and hit Enter in a PHP file.

```php
if (1)
  1;|
```

**Review by me21 — CHANGES_REQUESTED** [review]
Could you please add C/C++ languages support to this PR also?

**Comment by ssigwart** [comment]
> Could you please add C/C++ languages support to this PR also?

I updated it to include C/C++.

**Review by me21 — APPROVED** [review]

**Review by hediet — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by ssigwart** [comment]
Thank you, @hediet and @TylerLeonhardt!

**Pull request merged**
