### PR TITLE
Implement AddSelectionToAllFindMatchAction command class

### LINKED ISSUE #1186: Add "select all matches" command
Similar to Sublime Text `cmd+ctrl+g` command which selects all the matches of current selection 

http://gfycat.com/DazzlingMeagerErin

### PR DESCRIPTION
**Pull request by mohsen1**
This command is bound to "cmd+ctrl+g" by default

Fixes https://github.com/Microsoft/vscode/issues/1186

### CODE REVIEW

**Comment by mohsen1** [comment]
This is going to an infinite loop since `_getNextMatch` circulates through all the matches...

**Comment by mohsen1** [comment]
Fixed the infinite loop issue by implementing `_getAllMatches` in `SelectNextFindMatchAction.

**Comment by alexandrudima** [comment]
@mohsen1 The code looks good, but this functionality is already there. See `SelectHighlightsAction` which does exactly the same: finds all matches using the `multiCursorFind` and then sets selections to those matches. I am sorry its identifier is very misleading (`editor.action.selectHighlights`), but it does the same and is bound by default to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>

**Comment by lsancho** [comment]
How can I copy the results and how to copy all the groups 1 of the results?

**Pull request closed without merging**
