### PR TITLE
remove only disabled breakpoints

### LINKED ISSUE #106180: Remove disabled breakpoints
Searched for words in title, nothing found.

On right click there are "Remove breakpoint" and "Remove All Breakpoints", I suggest : "Remove (only) disabled breakpoints"

Thanks

### PR DESCRIPTION
**Pull request by walidbarakat**
in case it will be accepted.

This PR fixes #106180

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for the PR, it looks like good work!
However for now we do not want this behavior in VS Code core, I believe it is better handled off by an extension (since there is all the necessery debug api for this to happen).
So for now I would prefer to keep this PR open and potentially merge it in the future.

**Comment by walidbarakat** [comment]
understood, i'm sorry didn't get the debug api, but i'm still new to vscode and if there's a way to make the diving in the code easier, like a communication way with the development team where i can make question about the code structure and components, that for sure would be a great help for contributors, specially newbies like me. thanks in advance.

**Comment by isidorn** [comment]
Maybe try out gitter channel - even though team members are not that active, I think community answers most of the questions
https://gitter.im/Microsoft/vscode

No worries, it is just personal taste if this should be a part of the extension or vscode core. I just think it should be inside an extension.

**Comment by walidbarakat** [comment]
thanks for the link, and about if it should be in core code or extension, i don't have an opinion about it yet, i need to understand the philosophy of vscode architecture, and i'm still subscribed for this PR to see what's dev team decision and why.

**Comment by isidorn** [comment]
As per my comment above we will not merge this in vscode core, thus closing this

**Pull request closed without merging**
