### PR TITLE
add right sidebar

### LINKED ISSUE #26777: Allow multiple views to show at the same time
Would be nice to be able to have both a left and right sidebar i,e file tree in left and VSC in right.

Kinda vibing off the multi panel layout of atom with github / git integration

Something like this 

lol screen shot 2017-05-17 at 10 19 26 copy

### PR DESCRIPTION
**Pull request by wzhudev**
This PR fixes #26777

This PR adds another sidebar (in the opposite position of the existing one) to the workbench. So users could drag views like Outline or Timeline to the second sidebar.

**Download Link**

win32: https://drive.google.com/file/d/171gvmP7JM6MHTMlQmnXtL8plmrPc8qmz/view?usp=sharing

TODO:

- [x] I am ~~not sure if~~ now pretty sure that we should add another activity bar on the right side as well
- [x] Provide a demo bundle for community feedback
- [ ] Startup mockup of Third Panel
- [ ] nls
- [ ] Housekeeping, improving code reuse etc

Preview:

https://user-images.githubusercontent.com/12122021/125544451-ed03cd41-f551-4355-8100-00590e5fdcb7.mp4

More screenshots:

With Panel on the bottom:

Snipaste_2021-07-14_13-44-45

With Panel on the right:

Snipaste_2021-07-14_13-44-57

Dragging other views into Third Panel:

Snipaste_2021-07-14_13-45-30

More screen shots:

image

image

image

### CODE REVIEW

**Comment by heartacker** [comment]
It will be great to have a pin icon for user to pined the three panel,
 If user unpined, The three panel will show  When long hover  or clicked, and auto hide when losting focus

make it like float panel，thanks

**Comment by cryzed** [comment]
This looks great!

**Comment by wendellhu95** [comment]
image

More screenshots.

**Comment by DominicVonk** [comment]
Hi, what's the progress of this?

**Comment by wendellhu95** [comment]
> Hi, what's the progress of this?

I've been busy with some personal stuff recently, but I am still working on it. Definitely will make it ready for review by the end of September.

**Comment by DominicVonk** [comment]
@wendellhu95 can I help you with something, to fasten the progress?

**Comment by wendellhu95** [comment]
> @wendellhu95 can I help you with something, to fasten the progress?

Hi! I believe that this feature is roughly implemented and usable by now. I would appreciate a lot if you could fix some bugs. Many thanks! :heart:

**Comment by martin-braun** [comment]
@wendellhu95 Thank you for your dedication and time. It's nice that you included even a win32 download link, but is it up2date?

**Comment by sbatten** [comment]
@wendellhu95 I am starting to explore the second sidebar option this milestone. I appreciate the work that is done here. I will start by exploring the UX involved in opening up to a second side bar and then start with a prototype. I wanted to let you know as we try to increase the flexibility of our layout, there may be changes under the hood that don't match the direction you have gone here. For that reason, while we may not take this PR, we are working towards a similar goal and I will not hesitate to mention your contributions in release notes as we take them.

**Comment by wendellhu95** [comment]
> @wendellhu95 I am starting to explore the second sidebar option this milestone. I appreciate the work that is done here. I will start by exploring the UX involved in opening up to a second side bar and then start with a prototype. I wanted to let you know as we try to increase the flexibility of our layout, there may be changes under the hood that don't match the direction you have gone here. For that reason, while we may not take this PR, we are working towards a similar goal and I will not hesitate to mention your contributions in release notes as we take them.

It's great to hear that you are working on this. Looking forward to that!

**Comment by wendellhu95** [comment]
> downloaded the build and started it up. Could not move the outline to the 3rd panel. It shows the plus sign like it will add it while dragging but when I let go of the mouse button the outline is not added. Same actions will add the outline to the bottom panel.

Hi. I've fixed that. You can build from this PR.

**Pull request closed without merging**
