### PR TITLE
Introduce minimap section headers, a la Xcode

### PR DESCRIPTION
**Pull request by dgileadi**
This addresses #74843. It adds section headers to the minimap, sourced from region markers and `MARK:` comments:

vscode-minimap

`MARK:` comments behave the same way as they do in Xcode's minimap—if the comment contains a hyphen before the header text then it displays a horizontal separator line above the section header.

This PR adds three settings to control the appearance of the section headers, or to turn them off:

vscode-section-header-settings

Feedback, testing and code fixes are very welcome!

### CODE REVIEW

**Review by KS-Hoog — APPROVED** [review]

**Comment by andyjeffries** [comment]
I've downloaded this and the patch works absolutely lovely with plain Ruby files:

Screenshot 2023-08-31 at 08 50 43

I don't know if this is a problem with the patch though or the `CraigMaslowski.erb` extension, but it doesn't work for either comment style in `.html.erb` files:

Screenshot 2023-08-31 at 08 51 54

**Comment by dgileadi** [comment]
> I don't know if this is a problem with the patch though or the `CraigMaslowski.erb` extension, but it doesn't work for either comment style in `.html.erb` files:

It seems to be a problem with the extension. The code for detecting section headers uses the region markers and comment markers from the language configuration file. [That extension's language configuration file](https://github.com/craigmaslowski/vscode-erb/blob/master/erb.configuration.json) defines `/*` and `*/` for its block comments, as well as `//` for its single line comments. If you make a comment using that style, you'll see the section header:
Screenshot 2023-08-31 at 9 20 05 AM

**Comment by andyjeffries** [comment]
Thanks @dgileadi , I've raised an issue https://github.com/craigmaslowski/vscode-erb/issues/5 in the extension repo.

**Comment by andyjeffries** [comment]
That extension is deprecated (but I still had it installed and thought VS Code). Just as a follow up, I'm actually using Shopify's [Ruby LSP extension](https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp) and iit's working perfectly. Hopefully soon this can be merged...

Screenshot 2023-09-03 at 11 23 52

**Comment by andyjeffries** [comment]
Hey @alexdima is there anything we can do as the community to help get this merged in and released? Thanks.

**Review by alexdima — CHANGES_REQUESTED** [review]
Thank you, this looks amazing!

The problem is that this is not implemented in a performant manner, so I can't accept this in the current shape. We need that the view is very fast in rendering a frame, or in reacting to a change event. The goal is to have the event reaction time + rendering time of the entire editor be under 10ms, to leave some browser slack time and allow for 60FPS.

The problem with the proposed change is that there are heavy computations done during view event handling/during rendering. These are easy to spot by looking for the `compute` calls which pass in the entire file. These will grind rendering to a halt for a very large file (100k lines, etc). The computation, by calling `tokenizeIfCheap` with incrementing line numbers, will also basically trigger synchronous tokenization of the entire buffer. `tokenizeIfCheap` will tokenize a line if the previous line is tokenized.

For similar problems, we have taken a different approach. For example, for detecting links in the editor, we have a link contribution which reacts to change events with a debounce pattern (so not every file change triggers a recomputation). The actual computation of detecting links is then done on a web worker, and the results are then collected and transformed into decorations which are set on the text model. The decorations are stored in a bunch of efficient interval trees which allows updating them while typing efficiently and also allows for querying them efficiently based on reading patterns (decorations that go in the overview ruler are stored in a different tree than those that don't, because the overview ruler always fetches them all, while the others are usually fetched for the viewport).

I would also recommend that here we implement this using pattern:
* we would have a piece of code (probably in editor/contrib) which reacts to when an editor gets set a new text model or to when the text model changes in a debounced way.
* it then can scan for these markers either on the UI thread with a time cap or on the web worker.
* once it has computed the locations, it sets decorations with those ranges on the text model
* the decorations need a new field to indicate the extra special minimap rendering
* at each frame, the minimap reads decorations from the text model and renders them as possible
* in the rendering code, we need to be as minimalistic as possible to repaint only when necessary, etc.

**Comment by dgileadi** [comment]
Thanks for the feedback, @alexdima. Your recommended changes are probably best implemented by someone familiar with the vscode code base (and of course with dedicated vscode development time). In the mean time, could you point me to the code in vscode that implements the link detection? That would help me better understand how more efficient section header detection could work.

**Comment by alexdima** [comment]
Sure
* here is the UI side of things: https://github.com/microsoft/vscode/blob/58558c00c3b6230337538d7071fcea9bdbc2f7c5/src/vs/editor/contrib/links/browser/links.ts#L34
* and here is the code that runs on a worker: https://github.com/microsoft/vscode/blob/8ab34a9802716d724ed8db588005fe05766f9506/src/vs/editor/common/languages/linkComputer.ts#L171

The link computation might appear a bit too complex because it goes through the language feature registry because there's vscode API for extensions to contribute link providers. Maybe a simpler example is the `UnicodeHighlighter`:
* the UI side: https://github.com/microsoft/vscode/blob/8ab34a9802716d724ed8db588005fe05766f9506/src/vs/editor/contrib/unicodeHighlighter/browser/unicodeHighlighter.ts#L38
* the worker side: https://github.com/microsoft/vscode/blob/8ab34a9802716d724ed8db588005fe05766f9506/src/vs/editor/common/services/editorSimpleWorker.ts#L396-L402

**Comment by dgileadi** [comment]
Okay @alexdima I think I've implemented what you suggested. Let me know what you think. Thanks!

**Comment by dgileadi** [comment]
Hi @alexdima is there anything I can do to help get this reviewed?

**Comment by andyjeffries** [comment]
Hey @KS-Hoog or @alexdima is there anything others in the community can help do to move this along? I see @dgileadi has made the changes requested.

**Comment by MaxLikesCode** [comment]
Hey @alexdima, is there anything we can do to get this implemented soon? I think @dgileadi made the requested changes.

**Comment by andyjeffries** [comment]
@bpasero (you are the lead committer to the project), we don't know if there's a process to get PRs reviewed, but this is a much requested feature that seems to have been implemented correctly 4 months ago yet is still waiting review.

If there's a more formal process to getting it reviewed other than just keep tagging Alex Dima (who may have stopped working on the project for all we know), could you please let us know.

Thank you

**Comment by pouyakary** [comment]
@andyjeffries @dgileadi 

I just wanted to thank you for going and implementing this! I'm really looking forward to seeing it in action (hopefully very soon!)

**Comment by andyjeffries** [comment]
Thank you, but it’s nothing to do with me, this was all @dgileadi ! I’m just championing the cause because I really want the functionality live…

**Comment by pouyakary** [comment]
@andyjeffries you're very welcome, and yes! while this @dgileadi has made an exceptional job on this; your championing also counts. Thank you very much for this!

@dgileadi, again! Thanks a lot! I too really wished to have this!

**Comment by andyjeffries** [comment]
Tagging a bunch of Microsoft people that have merge access in order to try to get this merged...

@dbaeumer @joaomoreno @sandy081 @jrieken 

@dgileadi is doing amazing work by writing the patch, entirely reworking it based on feedback, but we're now struggling to get Microsoft eyes on it to get it merged. Been six months of him keeping the patch up to date and mergeable.

If none of you are the right person to look at this and get it merged, please can you tag/assign it to someone that can...

Reached out over Twitter too...

https://twitter.com/andyjeffries/status/1753117856764723384?s=61&t=htpY2d2Fq46KUKVy2QJRHQ

**Comment by pouyakary** [comment]
@dgileadi @andyjeffries 

I have [posted this to Hacker News](https://news.ycombinator.com/item?id=39628061) you can spread the word by voting it up. I hope it becomes viral and catches the VSCode's maintainers.

**Comment by MaxLikesCode** [comment]
Bumping this again! This is an amazing feature that should be included in the coming release. It's all up to you now, @dbaeumer @joaomoreno @sandy081 @jrieken

Again, thanks @dgileadi for your great work!

**Comment by dgileadi** [comment]
Thanks @alexdima for your attention and helpful changes!

**Review by alexdima — APPROVED** [review]
Thank you! Excellent PR!

I did one small conceptual tweak where we now parse all mark headers and then eliminate the ones not in comments on the UI side, where we have good tokenization information available.

**Review by sandy081 — APPROVED** [review]

**Comment by pouyakary** [comment]
@dgileadi I just wanted to thank you and also @alexdima, @andyjeffries, and @sandy081. I wished for this feature to exist for so many years and finally having it means the world to me. Thank you so much for all the efforts ❤️, I just opened vscode and got the update and it made my day.

**Comment by detzt** [comment]
Such a pleasant surprise to see this after updating VSCode. I didn't even know I wanted this, but now I already feel how it improves my life. Thank you ❤️

**Comment by NHUJI** [comment]
This is a feature I've been dreaming of! I've added MARK to my codebase before as a way to manually differentiate between codes, and now it's actually useful!❤️

**Pull request merged**
