### PR TITLE
[java] update grammars

### LINKED ISSUE #36688: [java] Syntax Highlighting broken by method header on more than one line
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.5
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

Syntax highlighting is broken in the below code snippet:
``` Java
public static <M extends Map<Integer, String>> 
boolean TestGet(Supplier<M> c) {
 //TODO write unit test for get
 //Setup
 Map<Integer, String> map = c.get();
 return false;
}
```

Highlighting is fixed if full method header is on the same line:
```Java
public static <M extends Map<Integer,String>> boolean TestGet(Supplier<M> c){
//TODO write unit test for get
//Setup
Map<Integer, String> map = c.get();
return false;
}
```

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #36688 and https://github.com/redhat-developer/vscode-java/issues/338

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Comment by maxibanki** [comment]
LGTM, but it's very hard to see the difference, because you have used 2 spaces and not tabs like all the other syntax files. Please update / create a new one.

**Comment by snjeza** [comment]
I have updated the PR. 
BTW I have converted java.cson from https://github.com/textmate/java.tmbundle, but haven't converted https://github.com/atom/language-java/blob/master/grammars/java.cson.

**Comment by fbricon** [comment]
@snjeza the java colorization tests fail with that PR, see https://travis-ci.org/Microsoft/vscode/jobs/292198428

**Comment by snjeza** [comment]
@fbricon @aeschli @maxibanki I'm not sure how to change https://github.com/Microsoft/vscode/blob/master/extensions/java/test/colorize-results/basic_java.json

**Comment by aeschli** [comment]
@snjeza I updated the Java grammar we use to the latest version from https://github.com/atom/language-java and the issue looks fices

There is very little activity on https://github.com/textmate/java.tmbundle, so I don't want to switch to this (again).

**Comment by snjeza** [comment]
@aeschli Syntax highlighting still doesn't work. Try the following:

The VS Code master:

syntax2
The VS Code master with this PR:

syntax3

**Comment by aeschli** [comment]
@snjeza Please file issues against https://github.com/atom/language-java

**Pull request closed without merging**
