### PR TITLE
Use NPM chokidar.

### PR DESCRIPTION
**Pull request by paulmillr**
The pull request for fork has been merged.

### CODE REVIEW

**Comment by paulmillr** [comment]
thanks for good contribution environment — no bullshit. big hate to apache org experience

**Comment by bpasero** [comment]
@paulmillr can you elaborate how this version of Chokidar helps us? I run a fork of Chokidar to be able to pull in a version of fsevents that is not using `node-pre-gyp` as you can see from my fork at https://github.com/bpasero/fsevents/commits/vscode

**Comment by paulmillr** [comment]
That makes sense. Let me see what can be done here.

You've dropped node-pre-gyp, because it consumed too much space?

**Comment by bpasero** [comment]
@paulmillr first of all it sucks in tons of dependencies and second it does not work with Electron as outlined in https://github.com/strongloop/fsevents/issues/131. So I ended up with my workaround to have latest chokidar but a version of `fsevents` before `node-pre-gyp` landed.

**Comment by bpasero** [comment]
Closing for now, this needs more work.

**Pull request closed without merging**
