### PR TITLE
uri: fix URI#toString for IPV6 URIs

### LINKED ISSUE #154048: `vscode-uri`: `URI.toString()` wrongly encode IPv6 literals
`URI.toString()` wrongly encode IPv6 literals 

( This is an issue with https://www.npmjs.com/package/vscode-uri but if I understand correctly issues should be reported here )

`vscode-uri` can parse IPv6 literal address fine (examples are using node REPL)

```
> require('vscode-uri').URI.parse('http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html')
e {
  scheme: 'http',
  authority: '[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80',
  path: '/index.html',
  query: '',
  fragment: '',
  _formatted: null,
  _fsPath: null
}
// 👍
```

but `toString` will encode the `[`:
```
> require('vscode-uri').URI.parse('http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html').toString()
'http://%5Bfedc:ba98:7654:3210:fedc:ba98:7654:3210]:80/index.html'
//      ^^  🔴 [ is escaped !
```

This string representation of the URI cannot be used for example by a web browser.

This encoding seems to happen here
https://github.com/microsoft/vscode/blob/2fcd34a41b11b49f0d0f778752a117de292e25e0/src/vs/base/common/uri.ts#L651-L652

---

Does this issue occur when all extensions are disabled?: not applicable

- VS Code Version: main ( 7c78640d86e5de1ca0270912584d9d38beafeec1 )
- OS Version: linux

Steps to Reproduce:

```js
require('vscode-uri').URI.parse('http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html').toString()
```
actual:
```
'http://%5Bfedc:ba98:7654:3210:fedc:ba98:7654:3210]:80/index.html'
```
expected:
```
'http://[fedc:ba98:7654:3210:fedc:ba98:7654:3210]:80/index.html'
```

### PR DESCRIPTION
**Pull request by perrinjerome**
Fixes #154048

cc @xavth @jrieken

### CODE REVIEW

**Comment by jrieken** [comment]
Sorry, I fixed this issue without realising it had a PR linked to it. Closing with merge but the issue is fixed after all

**Comment by perrinjerome** [comment]
No problem @jrieken thank you for fixing the issue ! 

Looking forward to having this released in vscode-uri on npm :)

**Comment by jrieken** [comment]
It is published!

**Comment by perrinjerome** [comment]
@jrieken thanks a lot for the release !

**Pull request closed without merging**
