### PR TITLE
increase title part height when CC shows

### PR DESCRIPTION
**Pull request by jrieken**
This is for https://github.com/microsoft/vscode/issues/150262 and adds 4px extra height to the title bar part when the command center is shown. I made sure this looks good/better on macOS and works on web (which is similar/like windows/linux?)

Screenshot 2022-05-24 at 15 49 56

@sbatten Please review. Maybe for May, otherwise June

/cc @daviddossett @misolori for actual height values

### CODE REVIEW

**Comment by misolori** [comment]
I think we can bump it even more 😄

**Comment by daviddossett** [comment]
> I think we can bump it even more 😄

I haven't tried this yet, but it could look nice to match the editor tab header height for some visual rhythm.

**Comment by jrieken** [comment]
> tab header height for some visual rhythm.

:+1: did that. Things are looking nice, there is just one issue that the traffic light position is sometimes unstable, e.g when changing tabs. Need to drill into that, could be an electron bug

**Comment by jrieken** [comment]
@deepak1556 Can you please take a look at this? With the extra padding I am repositioning the traffic lights but it seems that they wiggle - without hitting [this code](https://github.com/microsoft/vscode/blob/83f6fecf08b360a2b722d0daafd31e8b07f99667/src/vs/platform/windows/electron-main/window.ts#L279). I also don't see another caller that would do this. Could this be an Electron bug?

https://user-images.githubusercontent.com/1794099/173046483-e82ddfea-4a4c-4bc3-af96-2f10e2df2ce7.mov

**Comment by jrieken** [comment]
@sbatten Can you review please. There is still the flicker (https://github.com/microsoft/vscode/pull/150272#issuecomment-1152218493) - I might push another change to disable the traffic-light centering until we know what the issue is

**Review by sbatten — DISMISSED** [review]
@jrieken I made some changes to make this work better on windows. on windows now, we increase the height of the controls when the titlebar height increases. this happens because of the command center as well as zoom. this is why the windows call happens from the titlebarpart and not in window

**Comment by jrieken** [comment]
Thanks @sbatten

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
