### PR TITLE
grammar fix

### PR DESCRIPTION
**Pull request by ArtificialZeng**
grammar fix

### CODE REVIEW

**Review by vinaysiwachituple — APPROVED** [review]

**Review by offensive-vk — APPROVED** [review]
seriously bro? grammar fixes 😭

**Comment by ArtificialZeng** [comment]
> seriously bro? grammar fixes 😭

thank you very muvh

**Review by ArtificialZeng — COMMENTED** [review]
good

**Comment by ArtificialZeng** [comment]
@offensive-vk Could you please give this PR 1 approving review? thank you very much

**Comment by joaomoreno** [comment]
If you'd like to help out, check out our [Contribution Guide](https://github.com/microsoft/vscode/wiki/How-to-Contribute):

> Issues labeled [`help wanted`](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) are good issues to submit a PR for. Issues labeled [`good first issue`](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) are great candidates to pick up if you are in the code for the first time.

**Pull request closed without merging**
