### PR TITLE
TypeScript should use double quotes for string in import snippet.

### PR DESCRIPTION
**Pull request by adyavanapalli**
From style guide: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines #22231

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks @adyavanapalli! This will be in the next insiders build

**Comment by tmcgannon** [comment]
Why can't this be configurable like tslint: https://palantir.github.io/tslint/rules/quotemark/ ?

**Comment by mjbvz** [comment]
@tmcgannon This change only applies to the snippet and makes our behavior more consistent with TypeScript. Use the [TSlint extension](https://github.com/Microsoft/vscode-tslint) to autofix the snippet after insertion if you prefer single quotes (or just type of the import statement directly instead of using the snippet)

**Comment by mikehaas763** [comment]
I just wanna gather some context. This change was introduced because other similar vscode snippets use double quote? Or what?

**Comment by mjbvz** [comment]
@mikehaas763 as noted, this PR was was to bring the snippet inline with the TS style guide

**Comment by mikehaas763** [comment]
Oh jeez not sure how I glossed over that. Makes sense. Although, I didn't see anywhere in the guide where it says double over single quotes. I'm sure it's in there though!

**Comment by adyavanapalli** [comment]
@mikehaas763 Look [here](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#strings)

**Comment by jmaronge** [comment]
I agree with @tmcgannon why can't this be configurable.  While the TS style guide says one thing lots of people use single quotes for strings instead of double quotes.  To say just "_Use the TSlint extension to autofix the snippet after insertion if you prefer single quotes (or just type of the import statement directly instead of using the snippet)_" defeats the purpose of the feature and requires a lot of extra work.  The idea of the snippet is to be a faster way to inserting the text but now you have made it virtually unusable for those who use single quotes for strings.

**Comment by adyavanapalli** [comment]
@jmaronge This can be still configured by editing the typescript snippet file (Preferences > User Snippets > Typescript) and inserting the following configuration code:
```
"Import external module.": {
	"prefix": "import statement",
	"body": [
		"import { $0 } from '${1:module}';"
	],
	"description": "Import external module."
}
```
After, for the user-defined snippet to appear first in the list of available snippets (as now two snippet entries  appear when you type `import`) , you must add the following configuration code to your `settings.json`:
```
"editor.snippetSuggestions": "top"
```

As for why double quotes are configured by default: it is simply because vscode code follows what is recommended by the typescript coding guidelines available [here](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#strings).

If this truly bothers you and makes the snippet *virtually unusable for those who use single quotes for strings*, you can edit the system default snippet file, which is available (on Windows) at the following location: `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\typescript.json`

Cheers! XD

**Comment by linusbrolin** [comment]
@adyavanapalli so instead of providing a simple settings line where the default is double quotes, but that could be overridden in the user settings, you instead propose editing a local json file that cannot be included in my project source code repository?

My tslint is configured to suggest single quotes.
The reasons for this are simple:
1. It _was_ the default when I first started the project, and I'm not going to replace every single single quote in my entire project now, just because the default has changed.
2. If I want a string to contain double quotes within the string, then using single quotes for the string itself is way better than having to escape the double quotes within the string.
One example where this would occur is when the string contains html.

There is no reason to not provide a setting for this.
Infact, other editors have settings for it, like WebStorm: https://stackoverflow.com/questions/39779272/webstorm-phpstorm-double-quotes-in-typescript-auto-import/39779498

**Comment by adyavanapalli** [comment]
@linusbrolin I have provided two solutions. One in which the default double-quotes snippet can be overridden with a single-quotes snippet and these configuration files can be placed *within* your project's repo. This is all done from within vscode. The second solution is for those seeking a permanent change in the default setting. Please re-read my above response.

**Comment by MetodoDigital** [comment]
As @adyavanapalli very well mentioned, you can edit the **_typescript.json_** file to get around this issue on _/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/_ for MacOS and _C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\_ for Windows.

Thx buddy.

**Pull request merged**
