### PR TITLE
Adopt TS 2.1.3-insiders

### PR DESCRIPTION
**Pull request by mjbvz**
Adopts the 2.1.3 insiders build of TS in the TS extension.

### CODE REVIEW

**Comment by mjbvz** [comment]
Did basic sanity pass for main ts/js functionality and things look good.

**Comment by dbaeumer** [comment]
This is fine with me. However there is one thing we need to keep in mind. We should only adopt 2.1.3 if the TS team can promise that they have a final version this week. We never ship a version of VSCode that uses a TS version with isn't official yet. We would enter the test pass with a dev version :-)

@mjbvz @waderyan can you please check with the TS team on this ?

**Comment by waderyan** [comment]
There was an email thread on this. Forwarding to the two of you. There was a delay in 2.1.3 because of a couple issues. Last word was that there were two more packages planned on being pushed before the final one. @kieferrm can you verify my understanding is correct?

**Comment by kieferrm** [comment]
2.1.3 is delayed and is planned to ship coming Wednesday. We'll get two additional drops on the insider. It is correct that in this case we will enter the test pass without having the final version in hands. However, they version we test with is promised to be the smallest possible delta to the final version.

**Pull request merged**
