### PR TITLE
Address improper fullscreen restore

### LINKED ISSUE #150790: macOS: missing custom title bar when restoring multiple windows
Steps to Reproduce:

1. configure in settings to restore fullscreen windows
2. open 2 windows fullscreen
3. quit
4. startup

=> only the one window goes into fullscreen, not the other (this is a electron limitation: https://github.com/microsoft/vscode/issues/148698). but the window that is not in fullscreen has misaligned control buttons:

image

In fact the custom title bar seems to not be there.

### PR DESCRIPTION
**Pull request by sbatten**
fixes #150790

I don't like it but we rely on the fullscreen status to make this decision and its lying to us. I've added some fuzzy detection to work around the limitation.

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
Timeout is a bit ugly, why is it needed?

**Comment by sbatten** [comment]
@bpasero when the event to change fullscreen state occurs, the window still needs to resize so detectFullscreen will not give good information.

**Review by bpasero — CHANGES_REQUESTED** [review]
I still see the issue with the traffic lights:

image

Steps:
* run out of sources
* set to restore fullscreen
* open 2 fullscreen windows
* quit and start again

Besides, I also see that with a single window the transition to fullscreen is not very nice:
* leave 1 window in fullscreen and configure to restore fullscreen
* quit and start again
* notice how the custom title appears and hides again quickly before the transition to fullscreen finishes

**Comment by bpasero** [comment]
Oh I tested from the wrong branch, indeed the traffic light issue is gone, however I see the custom title bar not moving away when I do this:
* 2 windows, both fullscreen
* restart
* set the window that is not fullscreen to fullscreen
* 🐛 the custom title bar is still visible

image

The other issue with the flicker persists even with your changes.

**Comment by sbatten** [comment]
hmmm, the persistent title bar makes me think the timeout is not reliable enough. maybe this needs to be addressed higher up (outside of layout)?

**Comment by bpasero** [comment]
Fyi I have https://github.com/microsoft/vscode/pull/158366 which tries to fix this on the level of where we open windows and I think it works good enough, so I believe we would not need this PR anymore.

**Comment by mjbvz** [comment]
Closing this based on Ben's comments and unassigning from August

**Pull request closed without merging**
