### PR TITLE
Change disassembly to use WorkbenchList

### PR DESCRIPTION
**Pull request by xisui-MSFT**
Change disassembly to use WorkbenchList: #130438

Created this since I wasn't able to properly merge the original PR: #133703.

Also need help since I'm not familiar enough with HTML/CSS:

1. Can't scroll horizontally even if `horizontalScrolling` is set to true. Didn't work like this several weeks ago, not sure what's wrong here.
2. List elements that contain source code are not indented correctly.
3. Based on my test in #130438, I wasn't able to find a way to fix the breakpoint column (elements) from scrolling horizontally.

### CODE REVIEW

**Comment by xisui-MSFT** [comment]
@roblourens @weinand  FYI. Also, we need some help in the items listed in the description, can you add 'help-needed' label to this PR, and probably ping those who may know how to solve these problems in your team?

**Comment by roblourens** [comment]
I agree with @yuehuang010's comment. Regarding the horizontal scrolling, make sure that you have enabled the global horizontal scrolling setting for the workbench which enables it in all lists. And make sure that you have the right CSS to size rows to the width of their contents, not the width of the container.

> I wasn't able to find a way to fix the breakpoint column (elements) from scrolling horizontally.

Sorry, I don't understand what you're asking

**Comment by xisui-MSFT** [comment]
@roblourens I'm not sure how to fix them so it would be great if you could provide more details.

> make sure that you have enabled the global horizontal scrolling setting for the workbench which enables it in all lists

Yes I have that enabled in both user and workspace settings (ID `workbench.list.horizontalScrolling`).

> make sure that you have the right CSS to size rows to the width of their contents, not the width of the container

Not sure how to do this or if I did something wrong?

> Sorry, I don't understand what you're asking

The entire page is a list, including the breakpoint column. So when scrolling horizontally, it would be scrolled out of the view port. We need a way to fix it from scrolling horizontally. I have tried some methods that works for native table/list like position:sticky, but none of them work.

Also, you didn't answer my second question so I try to add some details here. I would like the indentation the same as what we have currently. But with this PR, the disassembly lines that have source code are not indented correctly:
image

**Comment by roblourens** [comment]
You can use the developer tools to see the sizes of elements and what CSS is applied. You can look at the search view with horizontal scrolling enabled for a working example

image

The `.monaco-list-row` element should have the width of its content. That is measured here https://github.com/xisui-MSFT/vscode/blob/de7d0b420d7cb41e29df77307c929019ebb04eec/src/vs/base/browser/ui/list/listView.ts#L711 where it is applied to the DOM.

Regarding the sticky sidebar, I think that is doable with the list. https://stackoverflow.com/questions/57435232/position-sticky-not-working-for-horizontal-scrolling-when-element-width-increase looks helpful

I am not seeing that, I see this
image

**Comment by xisui-MSFT** [comment]
@roblourens I still need to spend some time to test (1) and (3). I think (2) is a display rounding error for certain resolution. I use an empty div of the same size as breakpoint element as a placeholder for source lines. So for some display resolution, the height of this div may be slightly larger than the height set, and therefore occupies the corresponding space in the following line. I think an acceptable workaround is to set its height to 1px since it's always blank and we won't need event listeners for it.

**Comment by roblourens** [comment]
> I use an empty div of the same size as breakpoint element as a placeholder for source lines

You probably want to do this with something like the margin or padding CSS properties, not an empty div.

**Comment by xisui-MSFT** [comment]
> > I use an empty div of the same size as breakpoint element as a placeholder for source lines
> 
> You probably want to do this with something like the margin or padding CSS properties, not an empty div.

Can padding/margin be fixed from scrolling?

**Comment by xisui-MSFT** [comment]
@roblourens List row size doesn't seem to fit to its content for me. Content (a child):
image
Where the size of list row:
image

And interestingly, the size of text is larger than both...:
image

Any insights?

**Comment by xisui-MSFT** [comment]
@roblourens ping since I didn't see any response for a long time 😊

**Comment by roblourens** [comment]
I've been out sick this week so far. In general I recommend looking at what the search view is doing and trying to copy it.

**Comment by roblourens** [comment]
I mean this one in the sidebar where horizontal scrolling works:

image

**Comment by xisui-MSFT** [comment]
Abandoning this PR since there are more issues than we expected, and yet we didn't see any progress in the past several weeks.

**Pull request closed without merging**
