### PR TITLE
Enable file actions in search results viewlet

### LINKED ISSUE #8594: Should be able to right-click and Copy Path from search results
- VSCode Version: 1.2.1
- OS Version:  OS X 10.10.5

Steps to Reproduce:
1. click the search icon in the left column
2. run a search that returns results
3. right-click on a filename
4. observe that no context menu is displayed

Expected result: should get context menu that includes "Copy Path" like that available in the Explorer section ("Working Files" or "Main")

### PR DESCRIPTION
**Pull request by kisstkondoros**
Resolves #8594

### CODE REVIEW

**Comment by bpasero** [comment]
I am not so happy with all the dependencies from search => file, typically we try to keep the inter-part-dependencies to one file (a top level files.ts or search.ts) and do not reach into the more internal parts of it. 

If this is about having an action to copy the path, I suggest to just contribute this one action from the search viewlet.

**Comment by bpasero** [comment]
I documented this in https://github.com/Microsoft/vscode/wiki/Code-Organization#workbench-parts now 👍

**Comment by kisstkondoros** [comment]
@bpasero Thanks for the explanation, and for writing it down somewhere!

If I got it right, the problem is about
```typescript
import { keybindingForAction } from 'vs/workbench/parts/files/browser/fileActions';
import { FileStat } from 'vs/workbench/parts/files/common/explorerViewModel';
```

In that case I'm wondering what can i do about 'keybindingForAction'.
Since there is nothing like e.g. parts/common there is no place to put, well the common stuff.

I have a look at FileStat, perhaps it can be replaced with IFileStat...

I guess you didn't really liked
```typescript
menuService.createMenu(MenuId.ExplorerContext, keybindingService)
```
either (in vs\workbench\parts\search\browser\searchResultsView.ts)

**Comment by bpasero** [comment]
@kisstkondoros do I understand your PR correctly that you want to contribute all file actions to the search viewlet or just the copy path action?

**Comment by kisstkondoros** [comment]
@bpasero IMO it totally makes sense

**Comment by bpasero** [comment]
I do not fully agree, I would not expect file modification actions nor compare actions in search results. For the purpose of solving #8594 I would introduce just one action to copy the path into the clipboard.

**Comment by sandy081** [comment]
I agree with @bpasero on above comment. But just showing one action might not look good. Showing Open specific actions makes sense to me.

Also, I think providing a context menu here might open up following questions:

- Expected to have the same in Problems view or other views where we have similar UI ?
- Expected to be consistent across views, similar context menus?
- Support for externally contributed context actions? If Markdown file is part of the result, then we might need preview action?

**Comment by bpasero** [comment]
Yes, whatever we do in search it should be contributable using the new menu extensions.

**Comment by bpasero** [comment]
@kisstkondoros I think unfortunately you picked a time for doing this PR where we are in the middle of introducing a new concept for providing context menu actions (see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/June_2016.md#menu-items-and-context-menu-entries). So, whatever we used to do in the workbench and editor to build the context menu is considered deprecated and old school and we intend to get those things converted to the new model.

As such, for the search viewlet we should also use the new way and I think @sandy081 and @jrieken are teaming up to get this going. 

I will assign @sandy081 to be the owner of this PR as such so that he is aware of the code and the desire to have a "Copy Path" command. However, I think we should not use the "old way" for menus.

**Comment by sandy081** [comment]
My opinion was not to have just one entry in the context menu as it does not look good.

Since context menu entries are contributable, why not providing an extension? I am not sure how many users would want to have it by default.

**Comment by bpasero** [comment]
Interesting idea, do we have all the things in place to contribute to the search result context menu?

One issue I can see is that from an extension it might be tricky to get access to the clipboard.

**Comment by bpasero** [comment]
Btw I think we can have more entries in the context menu. Candidates are:
* Open to the Side
* Reveal in Finder / Explorer
* Copy Path

**Comment by sandy081** [comment]
No Search results context menu is not yet ready for contributable. This has to be kept in mind while implementing context menu for files in Search.

How about providing Search / Replace specific action also in the context menu, like, Remove, Replace, Replace all? Probably they are duplicates of the actions on the right but just a thought?

**Comment by bpasero** [comment]
Yes we typically do not repeat the actions that are showing as primary actions on the element within the context menu (which only has secondary actions). But if there are search/replace specific actions not showing up as primary, we can add them too.

**Pull request closed without merging**
