### PR TITLE
Fix for #47852

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes issue #47852

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for the fix. But I'll be honest with you this looks like too much complication for an issue that only one user has hit and which looks like a corner case.
I appologise but I will not accept this right away as I fear this might cause some unrelated issues.
For now leaving this open.

**Comment by jeanp413** [comment]
Ok @isidorn I understand.
Just for the record the fix for the issue is in essence just [this line](https://github.com/Microsoft/vscode/pull/56775/files#diff-0e105d63bc1611d4c8f33f72a972b10fR875).
The other changes I made are needed to fix a bug (that I discover while testing and it's somewhat related) which is when you try to move multiple root folders and one of those is an ancestor of the others and it ends up just moving the parent folder due to the call to the function [resources.distinctParents](https://github.com/Microsoft/vscode/pull/56775/files#diff-0e105d63bc1611d4c8f33f72a972b10fL970).

**Comment by isidorn** [comment]
If that line is enough to fix the issue than I recommend to create a simple one line pr with only that change.
The second issue we can tackle independently

**Comment by jeanp413** [comment]
@isidorn I updated the PR containing just the one line fix for the issue.
Should I create a new issue for the other bug that I explained?

**Comment by isidorn** [comment]
@jeanp413 the PR looks good now. Did you test this PR out, does it fix the issue? Does drag and droping the workspace roots in regular cases work as expected?
Feel free to create a new issue for the bug you described

**Comment by jeanp413** [comment]
@isidorn yes, it works.
after

**Comment by jeanp413** [comment]
ping @isidorn

**Pull request merged**
