### PR TITLE
fix #106487 implement 'enablement' clause for viewsWelcome contribution's buttons

### LINKED ISSUE #106487: API: Add enablement to welcome view buttons
Below is a recording of a Control-R reload when no workspace is open and one non-builtin extension is contributing to to the Welcome view of Explorer.

junk

Observe how we start with Explorer's usual "NO FOLDER OPEN" view. Next my extension contributes its text and buttons. Finally the built-in git extension contributes text and a button. Since built-ins get higher priority the content from my extension jumps downward, perhaps while I'm reading it or trying to click one of its actions (link, button).

There's no progress indicator when the content is being fetched and assembled, and it's hard to know how long to wait before concluding that no other extensions are going to contribute.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
**UPDATE: The actual solution reached during discussion in this PR can be seen in [this comment](#issuecomment-725323081)**

This PR fixes #106487 by adding an "activating" message as suggested by @joaomoreno 

image

I included the "Learn More" button as a way of reserving the space that gets occupied by the "Clone Repository" button as soon as the git extension completes activation:

image

"Learn More" leads to the same place as the "read our docs" link in the second screenshot.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
The SCM view now does the same:
junk

**Review by joaomoreno — COMMENTED** [review]
I'm not really sure the _space reservation_ makes sense. Apart from the fact that the final message is taller than the loading one, making the button shift down, it doesn't feel like it's very useful to have a `Learn More` button there. I would simply remove it.

**Comment by gjsjohnmurray** [comment]
Here's how it looks when another extension is contributing as well:

junk

And without the "Learn More" button:

junk

Personally I think the placeholder button produces a less jarring experience, even though there's still some movement.

**Comment by gjsjohnmurray** [comment]
Another benefit of having a placeholder button is that I can add an animated codicon to its label. Currently it's not possible to use codicons in the plain text of welcome messages.

junk

**Comment by joaomoreno** [comment]
After seeing it live, I am getting second thoughts about this.

How about we provide a way to declare a disabled button instead? And possibly have a tooltip which would describe why the button is disabled when hovered? That way we can have 100% the same contents thus causing no jumping at all and avoid having a strange `Git extension is activating...` message. What do you think?

**Comment by gjsjohnmurray** [comment]
I was just investigating that possibility. The viewsWelcome contribution mechanism _almost_ lets me achieve this. There's an optional `preconditions` property to associate a context key expression with each button in the content. At the moment it's not wired up to get passed from an extension's viewsWelcome contribution, so I'll take a shot at doing that.

**Comment by joaomoreno** [comment]
Yeah it currently doesn't support `preconditions`, but we can certainly add it! It would be hard to add a tooltip for it though... since it would have to be a _tooltip for when the precondition doesn't match_.

**Comment by gjsjohnmurray** [comment]
How about this?

junk

Doesn't do anything with a tooltip, but it'd be easy to add a static one that says something like "Clone a repository when the git extension has activated"

**Comment by joaomoreno** [comment]
Wait.. we already support it?! YES looks much much better.

**Comment by gjsjohnmurray** [comment]
I've pushed the changes that make this work.

**Comment by joaomoreno** [comment]
[As you may know](https://github.com/Microsoft/vscode/wiki/Extension-API-process), new API additions require an `api` labelled issue, arguing for the addition. Also, until finalized they should be protected by the `proposed` mechanism. Let me know if you need help with those tasks.

**Comment by joaomoreno** [comment]
Sorry @gjsjohnmurray, closing this as per https://github.com/microsoft/vscode/issues/106487

**Comment by gjsjohnmurray** [comment]
@joaomoreno ironically I was just blowing the dust of this and about to get back to you for help with steering the API change through the required process.

The only additions needed are in viewsWelcomeContribution.ts and viewsWelcomeExtensionPoint.ts, plus a bugfix in viewPaneContainer.ts. So having read in the [Extension API Process doc](https://github.com/Microsoft/vscode/wiki/Extension-API-process) the following:

> All proposed APIs are defined in the vscode.proposed.d.ts file.

I'm not clear how to proceed. I don't need anything changed in vscode.d.ts or in its precursor vscode.proposed.d.ts

Please advise.

**Comment by joaomoreno** [comment]
I'm just wondering if this will really be worth the effort. I'm not entirely sold on the amount of work/extra code here vs. the added benefits.

**Comment by gjsjohnmurray** [comment]
I think it's worthwhile. The current experience of our extension's viewsWelcome contribution suddenly jumping down the screen because the Git extension has just completed its init is somewhat jarring. And the more extensions adopt viewsWelcome the more I foresee this kind of thing happening. The changes I propose (which really aren't extensive) provide extension developers a way of being better citizens in the shared space.

**Comment by joaomoreno** [comment]
@jrieken What do you think?

**Comment by gjsjohnmurray** [comment]
> 
> 
> @jrieken What do you think?

In pictures, here's current behaviour, where my extension contributes text and a button which subsequently gets bumped down when the git extension finishes initializing:

junk

And proposed, after the git extension has been tweaked to use the new capability:

junk

(ignore the extra text in the contribution from my extension, which was added between capture of the "before" case and the "after" case)

**Comment by jrieken** [comment]
I like the feature/enhancement, but I think the proposed changed to the contribution need some polish, I'd suggest `enablement` instead of `preconditions` and a simple string instead of an array (like other context key expressions)

**Comment by joaomoreno** [comment]
Alright,

**Comment by gjsjohnmurray** [comment]
> 
> 
> I like the feature/enhancement, but I think the proposed changed to the contribution need some polish, I'd suggest `enablement` instead of `preconditions` and a simple string instead of an array (like other context key expressions)

@jrieken fair point, but the advantage of the `preconditions` array is it better handles cases where a viewsWelcome contribution adds more than one button. For instance here the git extension contributes 2 buttons:
https://github.com/microsoft/vscode/blob/ceeb9748562afb00c191606ffa22d9bfb1b13a38/extensions/git/package.nls.json#L180

My `preconditions` proposal would operate like this:
```
      {
        "view": "scm",
        "contents": "%view.workbench.scm.empty%",
        "when": "config.git.enabled && workbenchState == empty",
        "preconditions": ["git.state == initialized", "git.state == initialized"],
        "group": "2_open@1"
      },
```
In this particular case it's right that both buttons enable/disable in lockstep, but there could be situations where each button needs a different clause.

If you're unconvinced then I'll implement `enablement` as you suggest and code things so the one enablement clause gets applied to every button in the contribution. That'll be OK for the Git contributions, and other multi-button contributions wanting to adopt the new feature will just have to live with the limitation.

**Comment by jrieken** [comment]
> In this particular case it's right that both buttons enable/disable in lockstep, but there could be situations where each button needs a different clause.

I'd say that's wanted since this contribution point talks about about welcome views. Spreading information about enablement of commands inside it into the contribution seems too loose. So, I'd day that the enablement-properties applies to the whole welcome-view thing. 

However, if we believe that fine grained enablement of individual command is needed then I would invest in a syntax that allows that to be expressed together with the command. That would keep information together and also not pose challenges about keeping the ordering correct - think about NLS and a translator reordering sentences/commands.

**Comment by gjsjohnmurray** [comment]
@jrieken thanks for your feedback. I have pushed the changes to make this work off an `enablement` string. I also updated the PR title and linked from the top of the description to the comment that shows before and after gifs.

@joaomoreno I think this is ready to merge.

**Review by joaomoreno — APPROVED** [review]

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
