### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by mousetraps** [comment]
Hey @Gama11, thanks for the PR!

I'll leave it to @alexandrudima to confirm, but this doesn't actually look like a typo, but rather a usage of ["If and only if"](https://en.wikipedia.org/wiki/If_and_only_if), which is often abbreviated as "iff".

**Comment by Gama11** [comment]
Oh, I wasn't aware of that abbreviation.

Same thing with #9538?

**Comment by alexandrudima** [comment]
Yes, `iff` stands for `if and only if`.

I'm not sure using `iff` fits in with the rest of the doc in the api.

Giving to @jrieken to decide if he wants to change it for consistency reasons or not.

**Comment by jrieken** [comment]
Yeah, idea is say 'if and only if'. I merging this because in the API docs we aren't consistently using iff and that might make it confusing.

**Pull request merged**
