### PR TITLE
Adopt icon font in find widget

### PR DESCRIPTION
**Pull request by miguelsolorio**
Related #78889

This adopts the icon font in the find widget (editor, terminal, monaco):

image

And when `icon.foreground` is modified:

image

cc @alexandrudima @rebornix

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
@misolori going forward, feel free to push this to `master` directly unless you want feedback on e.g. a new theme color key introduced 👍 . Love how our CSS gets slim, I am sure @alexandrudima will like each CSS rule that gets removed that does not slow down the editor a lot ;)

**Comment by alexandrudima** [comment]
This is great, I will also test if this works in the standalone editor...

**Comment by alexandrudima** [comment]
It looks like the built version of the editor is missing these icons...

image

To run the built version of the editor, the steps are:
* `vscode> npm run gulp editor-distro` to package the editor
* `monaco-editor> npm run simpleserver` to launch the simpleserver
* open http://localhost:8080/monaco-editor/test/?editor=built to load the editor from the `out-monaco-editor-core` folder (built into there above)

It looks like for the standalone editor, we are not shipping `codiconLabel`, but `codiconLabel.mock`. 

I am looking into a fix...

**Comment by alexandrudima** [comment]
Pushed a fix via fe5315badcaa9e326d5e5737a290ee7b299903c5

**Comment by misolori** [comment]
@alexandrudima thank you for fixing 🙏

**Comment by alexandrudima** [comment]
@misolori Sure! Moving to the font is great, the only bad thing might be that the standalone editor ends up including a ton of glyphs for icons used only in VS Code, so the editor footprint might grow a lot... Do you have any idea how we could "trim" the font to only a subset of glyphs for the standalone editor case ?

**Comment by misolori** [comment]
@alexandrudima we can absolutely do that, it's pretty easy to just create a subset of the icons we need. Once we're done adopting in all of the areas I can work on this and ping you.

**Pull request merged**
