### PR TITLE
Partial fix for task reconnection on reload (#180243)

### PR DESCRIPTION
**Pull request by markw65**
When the window is reloaded, and there are long running, non-background tasks the tasks are left running, but aren't added to the `TerminalTaskSystem`'s `_instances` or `_activeTasks` maps after the reload.

As a result, various commands, such as `workbench.action.tasks.terminate`, `workbench.action.tasks.restartTask`, `workbench.action.tasks.showTasks` all report that there are no running tasks - even though the tasks are in fact running.

In addition, trying to start the tasks starts a new copy - even if the task's `runOptions.instanceLimit` is set to 1 (the default). Note that prior to the reload, trying to start one of the already running tasks would pop up a prompt asking if you want to stop or restart the task.

Finally, if you have a task configured as `runOn: folderOpen` that is still running when the window is reloaded, the original task will still be running after the reload, and a new copy will be started in addition.

This commit partially fixes these issues.

By running `this._reconnectToTerminals()` from `TerminalTaskSystm`'s constructor, it ensures that any future attempt to run one of the already running tasks will simply select its terminal, while also adding the task to `_instances` or `_activeTasks`, so that further attempts to run it will present the prompt as expected.

This completely fixes the issue of allowing multiple copies of a task to run when its configured with an `instanceLimit` of 1. It also completely fixes all the issues for any `runOn: folderOpen` tasks.

It doesn't address the issue where various commands report that there are no running tasks; but that's no worse than before, and it can now be fixed by simply launching the tasks manually (which doesn't actually start new copies)

### CODE REVIEW

**Comment by meganrogge** [comment]
Thanks for looking into this. I'll try to investigate it during our debt week. 

>  and there are long running, non-background tasks the tasks are left running

I think this is a bug and they shouldn't still be running. If that is fixed, then the other issues will be too

**Comment by markw65** [comment]
> I think this is a bug and they shouldn't still be running. If that is fixed, then the other issues will be too

I mostly agree - and I said the same on #180243.

The downside is that currently, if you have such a long running task, reload doesn't kill it, and it gets partially reconnected. In particular, the terminal is preserved, so you can see the progress. The only problem with it is that the task service has lost track of it, so you can start a new copy (which might conflict with the existing one), and task manipulation commands (such as kill running task, show running task etc) all fail to find it. Given all that, killing the task on reload might be seen as a regression by people who are used to them surviving.

It's already kind of annoying that reload kills any open "Javascript Debug Terminals" (and regular shell terminals too). eg when I'm reloading the window because an extension needs updating - there doesn't seem to be any reason to kill all my terminals (if I wanted to do that, I could restart vscode). So I really feel the better option would be to preserve *all* terminals across reloads. And this takes one step in that direction.

In fact, if this was fixed, there would be no need (as far as I can see) for the `isBackground` flag in the first place.

**Comment by meganrogge** [comment]
We preserve all terminals that have had input /interaction. Re the JavaScript debug terminal, that is because the extension sets the `isTransient` property to opt out of reconnection. 

> The downside is that currently, if you have such a long running task, reload doesn't kill it, and it gets partially reconnected. In particular, the terminal is preserved, so you can see the progress. The only problem with it is that the task service has lost track of it, so you can start a new copy (which might conflict with the existing one), and task manipulation commands (such as kill running task, show running task etc) all fail to find it. Given all that, killing the task on reload might be seen as a regression by people who are used to them surviving.

By design we keep the terminal around but don't reconnect to the task. 

> (which might conflict with the existing one)

This is the part I'd need to investigate as I'm not clear why this would conflict with anything...

**Comment by markw65** [comment]
> This is the part I'd need to investigate as I'm not clear why this would conflict with anything

Consider a build task that starts by cleaning all the output files. If thats running, and then I start a second instance there's a good chance we end up with a broken build.

If the task has `instanceLimit` set to 1 (or not set at all), there's normally no problem. But if it's running, and I reload the window, the task continues to run, but the terminalSystem loses track of it (because its *terminal* is reconnected, but the task is not). So now I can start a second instance. *That's* the conflict I'm talking about.

As you say, we could fix that by killing the task when the window is reloaded. And that would certainly fix the issue. But it would also make reload more disruptive.

Here are the three options we're looking at:

1. The current setup. Tasks keep running across reload, which is useful, but safeguards are removed (you can now start a second instance while the first is still running), and various task manipulation commands (terminate, show etc) no longer see the task - which is confusing and could lead to problems. In addition, auto-run tasks that were running at the time of the reload *always* get a second instance started.
2. Fix it by killing all running tasks that aren't marked `isBackground` or don't have `problemMatchers`. This is safe, shouldn't be too confusing, but makes `reload` more disruptive than it is currently. If a user is 15 minutes into a build, does a reload and loses the build, they're not going to be happy (especially for users who are used to the current behavior, and expect the build to continue).
3. Fix it by keeping the tasks running as they do today, but also reconnecting them properly to the terminalSystem, so that it's fully aware of them. This seems ideal to me. Why make reload more disruptive than it needs to be?

Of the three, as far as I'm concerned, 2 is a slight improvement over 1 because it doesn't leave the tasks in the strange half-connected state they're left in today; but 3 is a huge improvement over 2. What I want (as a user) is for reload to be as transparent as possible. I'd like all my (already running) tasks to still be running. I shouldn't have to put off reloading because I don't want to have to deal with the fallout. Ideally all my terminals, and debug terminals would still be there too; but thats a separate issue.

**Comment by markw65** [comment]
> By design we keep the terminal around but don't reconnect to the task unless it has isBackground: true and problemMatchers

If it's by design, what's the rationale? Why would you want to keep the tasks running, but not reconnect them to the TaskService?

**Comment by markw65** [comment]
> It was not by design (a bug) that they remained running

I see. That makes sense.

I agree that most long running tasks probably should be background tasks. But I don't really see the point of distinguishing the two as far as preserving them across reloads goes. eg my "watch" builds should definitely be background tasks (and I've fixed that). But I still have release builds; and some of those take several minutes to run. Having reload kill them is pretty unfriendly.

That said, I've still not come up with a solid way to properly reconnect everything. I tried an alternate approach that successfully reconnects tasks defined in tasks.json; but it doesn't work for contributed tasks, like npm scripts. So maybe killing them is the best solution...

**Comment by meganrogge** [comment]
Yeah @markw65 I think that we should be killing non-background/no problem matcher tasks here because if a user wants them to persist, they can just set `isBackground:true` and `problemMatchers:[]`.

**Comment by meganrogge** [comment]
Thanks again for looking into this - we've decided to go with the approach I mentioned above

**Pull request closed without merging**
