### PR TITLE
Add Julia as Shell type

### LINKED ISSUE #224325: Add Julia as a shell type in core
Part of: https://github.com/microsoft/vscode/issues/155530 
This should allow clear separation when users attempt to "Terminal: Run Recent Command", as in Julia users will only see Julia commands from VS Code and not those from other shells.

### PR DESCRIPTION
**Pull request by anthonykim1**
Adding Julia as Shell type.
Resolves: https://github.com/microsoft/vscode/issues/224325 

Will handle adding NuShell in separate PR
Will handle separating out pwsh, python, julia into GenericShellType Enum in separate PR.

### CODE REVIEW

**Review by 1chooo — APPROVED** [review]
Look good to me!!!

**Comment by Tyriar** [comment]
FYI @davidanthoff, @pfitzseb

**Review by Tyriar — APPROVED** [review]

**Comment by pfitzseb** [comment]
Oh, great to see! Is the shell type set based on the executable name (i.e. `shellPath`)?

**Comment by Tyriar** [comment]
@pfitzseb yes, but not necessarily the path that's passed in. There's some logic that inspects the process tree of the terminal to find the inner shell path/process name:

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/src/vs/platform/terminal/node/terminalProcess.ts#L407-L416

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/src/vs/platform/terminal/node/windowsShellHelper.ts#L115-L134

The idea being, if you launch bash inside pwsh, it should correctly get changed to bash.

**Pull request merged**
