### PR TITLE
Activity action should have a name 'activity'

### LINKED ISSUE #59573: VoiceOver does not provide helpful info for activity bar gear
Issue Type: <b>Bug</b>

**Repo**
1. Enable voiceover
1. Tab through the activity bar to the gear

**Bug**
VoiceOver does not provide helpful info about what this button is

screen shot 2018-09-27 at 11 44 40 am

For other items in the activity bar, it reads the item name the its keyboard shortcut

VS Code version: Code - Insiders 1.28.0-insider (b4d09d27509f2c023f63d4315aa966a5ec7581e9, 2018-09-27T14:37:17.724Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|-psn_0_2736796|
|Screen Reader|no|
|VM|25%|

</details>

### PR DESCRIPTION
**Pull request by isidorn**
fixes #59573

fyi @joaomoreno

### CODE REVIEW

**Comment by joaomoreno** [comment]
@isidorn Is this surfacing as the tooltip as well?

**Comment by isidorn** [comment]
@joaomoreno yes

**Comment by joaomoreno** [comment]
`Activity` is pretty rough. Alternatives:

- `[Product Display Name]`, eg. `VS Code` or `VS Code Insiders`
- `Manage`
- `More...`
- `Other`

**Comment by isidorn** [comment]
I like `Manage`. Since `VS Code` is not really helpful to someone who is using a screen reader I think

**Pull request merged**
