### PR TITLE
translation to indonesian 

### PR DESCRIPTION
**Pull request by raja-rizki**

### CODE REVIEW

**Comment by egamma** [comment]
Thank you for the translation of the ´How to contribute to VS Code´ document. We currently have no support for translating project documentation. We first have to decide whether and how we can support translations for the project documentation.

**Comment by raja-rizki** [comment]
I'm waiting for the process, thanks for the response

**Comment by raja-rizki** [comment]
I am not changing the file or adding, I just translate it, I think this is not why

**Comment by raja-rizki** [comment]
please respond sir

**Comment by bungcip** [comment]
Hi @raja-rizki,
If you interested in translating vscode to indonesia you can follow the steps in https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project . 

I am happy that you like to contribute to translate vscode :)

----

Halo @raja-rizki,
Kalau kamu ingin mencoba menerjemahkan vscode ke bahasa indonesia, kamu bisa coba ikuti petunjuk di https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project . 
Saya lihat lihat kamu cukup antusias untuk berkontribusi, sayangnya PR ini tidak mungkin dimerge sebab 
kamu tidak mengikuti cara yang benar. Kamu bisa belajar terlebih dahulu untuk menggunakan transifex.

Selamat berkontribusi :)

**Comment by raja-rizki** [comment]
thanks you,I will return with the next pull request

**Pull request closed without merging**
