### PR TITLE
Implements system variable "workspaceRootFolderName".

### PR DESCRIPTION
**Pull request by ghost**
Implements #11094

### CODE REVIEW

**Comment by dbaeumer** [comment]
@marktrz thanks for the PR.

We are in endgame for August now. Needs to wait until September

**Comment by visualperception** [comment]
so what happens now?

**Comment by visualperception** [comment]
Thanks guys,
I'll keep my eyes peeled for news.

**Comment by visualperception** [comment]
I think the vscode online docs file should also be changed to include the new variable in the current list od system variable so newbies like me can see whats available:

https://code.visualstudio.com/docs/editor/tasks

thanks

**Comment by visualperception** [comment]
Are we there yet?

**Comment by dbaeumer** [comment]
this is still on the plan for September.

**Comment by visualperception** [comment]
thanks,

I saw 3 red crosses and thought maybe it wasn't happening

**Comment by dbaeumer** [comment]
@marktrz I merged in the PR by applying your changes against master. Unfortunately the code got moved and restructured so I couldn't simply apply the PR. Was too late. Hope that is OK for you. I mention you in the release notes for providing the PR.

**Pull request closed without merging**
