### PR TITLE
Add invokeSnippetForCurrentWord command.

### PR DESCRIPTION
**Pull request by bmustiata**
Hi guys, thank you for your amazing tool.

Here's the rationale: when typing code and knowing that there is a snippet, the code completion combo actually hinders the typing process.

This command allows filling in the snippets immediately, by picking the first available potential suggestion that is a snippet, without the full combo autocomplete round trip.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@alexandrudima not sure if this is you or @jrieken

**Comment by alexandrudima** [comment]
@jrieken @joaomoreno As you guys own the experience around intellisense, is this command a good idea?

**Comment by jrieken** [comment]
@bmustiata I think this is a great scenario for an extension instead of adding a built-in command. You can contribute a command (as generated by the VS Code yo generator) which in return asks for suggestions ([in this spirit](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/test/common/api/extHostApiCommands.test.ts#L248)) and inserts the best of type `snippet`.

**Comment by bmustiata** [comment]
@jrieken Is there some documentation on how to actually call the yo generator? If I try to access the [documentation site](https://code.visualstudio.com/docs/tools/yocode
) I get redirected to the main page.

The big problem with fetching _all_ completion items is that it's visible slower. That's why it seems to me that searching only for the snippets directly it's faster.

**Comment by jrieken** [comment]
`npm install yo` and `npm install generator-code` should be all you need. then run `yo code`

**Comment by bmustiata** [comment]
@jrieken I managed to create the extension, but the APIs seem quite different, including classes that you refer into the snippet you gave me, seem not available in the extension API.

For example the [EditorModel](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/test/common/api/extHostApiCommands.test.ts#L31) is not available in the `vscode.d.ts` that is generated in the extension by yo.

**Comment by jrieken** [comment]
Correct, the extension host API is documented here: https://code.visualstudio.com/docs/extensionAPI/vscode-api. You want take a look at registering an editor command which allows you to modify a document.

**Pull request closed without merging**
