### PR TITLE
Leverage native clipboard for file copy/paste

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Comment by bradennapier** [comment]
Does not appear to work - having issues on latest build - can not copy and paste between windows and all issues noted as fixed

**Comment by cruhl** [comment]
I can confirm this no longer works on a MacBook

**Comment by cgjerow** [comment]
Is this being re-opened, or is there another open issue I can track for this?

**Comment by laygir** [comment]
+1

**Comment by kenchopa** [comment]
please revisit this topic

**Pull request merged**
