### PR TITLE
On mac ctrl-n should behave exactly like DownArrow

### PR DESCRIPTION
**Pull request by elemongw**
The same is true for ctrl-p and UpArrow. This fixes that

### CODE REVIEW

**Comment by elemongw** [comment]
There is also src/vs/base/parts/quickopen/browser/quickOpenWidget.ts and it is pretty important too. However, I didn't change that as it would require a lot of if's for mac-specific code and I don't know if that is desired.

**Comment by elemongw** [comment]
I would love feedback on this one as, if it's accepted, I would like to continue with similar changes that make vscode behave more like a cocoa app on mac.

**Comment by joaomoreno** [comment]
@elemongw Why did you close it?

**Comment by elemongw** [comment]
I shouldn't be working when I'm this tired. I was using vscode 1.2 and the shortcuts I fixed here were working fine so I throught I messed up and proceeded to close the pull request. Seeing your message now I remembered that the reason they were working was because I had manually added them to my keybindings.json. Oh well, mistakes happen, I'm reopening the pull request

**Comment by joaomoreno** [comment]
Looks awesome, thanks! 🎆

**Comment by ithinkihaveacat** [comment]
I think this causes a regression from 1.3.

In 1.3, with `ctrl+n` bound to workbench.action.quickOpenNavigateNext, then in Quick Open, holding down `ctrl` and then tapping `n` moved the selection down a line (as it does now). However, after releasing `ctrl`, the selected file was automatically opened, eliminating the need to press the return key.

It took a few goes to get used to this behavior, but eventually I found it preferable. It doesn't work anymore in 1.4. If this change was intentional, is there a way to get the old behavior back?

**Comment by joaomoreno** [comment]
@bpasero Maybe I broken the behaviour when I accepted this PR. Can you review it and see what we can do about it?

**Comment by bpasero** [comment]
Can we have a new issue assigned to August for this instead of lingering in some old closed PRs?

**Comment by bpasero** [comment]
@ithinkihaveacat as a workaround you could configure this:

```
{ "key": "ctrl+n", "command": "workbench.action.openPreviousEditorFromHistory" },
{ "key": "ctrl+n", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }
```

That allows you to use Ctrl+N for quick open navigation but will disable it in all other trees.

**Pull request merged**
