### PR TITLE
Improve overflowing widgets layout

### LINKED ISSUE #12794: Parameter hints widget size is awkward when the cursor is up against the right of a left or center split editor
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

image

Compared to within a split editor on the right side:

image

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #12794, #13004 and #9882

Some widgets specify a fixed width via CSS, like the suggest widget. The overflowing code currently in place works well with those.

Others want to be as wide as their content is, up to a certain point. Most others are, namely the hover and parameter hints. This behaviour is broken currently because the text within these widgets wrap at the right-most point of their closer layout parent. We should let these widgets stretch as much as they want to.

Some widgets have a [strange](https://cloud.githubusercontent.com/assets/1794099/18745950/d1b80656-80c4-11e6-8025-95d958d5ea0f.png) [layout](https://cloud.githubusercontent.com/assets/2193314/18884526/a0c30510-849c-11e6-86a5-dfa3fb19ad50.png), while [others definitely break](https://cloud.githubusercontent.com/assets/22350/19110275/5afc1cca-8af9-11e6-9fdd-9d3310bf204c.png). 😨 

This PR places the overflowing widgets in a `fixed` container, stretched to fill the whole window.

I gave it a good smoke test around Code and the Monaco editor, but I need a quick review from your @alexandrudima just to be sure I'm not missing anything.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@alexandrudima Suggests to use a context view option to the editor instead of a `fixed` dom node.

**Comment by joaomoreno** [comment]
@alexandrudima I have a different proposal. I'm not too keen on having users implement some context view element just so they can get wrapping overflowing widgets.

Using `pointer-events` is not good since IE11 was the first IE version to support them. So we can't `position: fixed` the widget wrapper... but we can do that to each widget. What do you think?

**Comment by joaomoreno** [comment]
I implemented what I mentioned on my last comment.

**Comment by joaomoreno** [comment]
This also fixes #9882

image

**Comment by joaomoreno** [comment]
Tested in Chrome, Firefox, IE11, IE10 and IE9.

**Comment by joaomoreno** [comment]
@alexandrudima Please take a good look here.

**Comment by alexandrudima** [comment]
@joaomoreno :-1:

Sorry, but you cannot make all content widgets `position:fixed`, that boat has shipped. The content widgets are public editor API and there can be any number of third-party content widgets that are broken by this. Especially content widgets that don't appear and disappear quickly (such as hover / suggestions). I don't track any scrolling done in any of my containers and will not repaint, therefore will not relayout any content widgets when you scroll in a container.

e.g. 

image


I suggest you add a flag on the content widgets you have in mind (perhaps only for hover and intellisense?) and only if this flag is present you begin to do the new behaviour (similar to `allowEditorOverflow`). You can then have the old behaviour and the new `position:fixed` behaviour.

Moreover, there are remaining issues even with the content widgets we ship (mouse wheel scroll):

file:///C:/Alex/src/monaco-editor/test/mouse-scrollable-body.html?editor=dev
bad-intellisense1

**Comment by joaomoreno** [comment]
After discussing with @alexandrudima, here are the conclusions:

- All our widgets which set `allowEditorOverflow` would fit into this `fixed` category, so no need to introduce a new flag.
- We should introduce a `fixedOverflowWidgets` setting which, by default, preserves the old behaviour and lets us switch to a `fixed` displaying of widgets in Code.

**Pull request merged**
