### PR TITLE
Reveal closer to top (center body, not signature)

### LINKED ISSUE #80726: Reveal closer to top instead of center: outline, go to definition, etc.
This is a UX improvement suggestion for "Go to definition" and when selecting an item from the outline. Note that JetBrains IDEs behave similar to this suggestion, so someone there thought about this issue, too.

If I asked you (i.e. a human) to scroll to a certain function or class, where would you position that function on the screen? You'd probably try to ensure that:

* the whole class/function is visible (including signature, body)
* comments preceding the function signature are also visible unless they're very long
* maybe for functions longer than a few lines the whole body would be centered on the screen (though, I've often seen developers not care too much as long as the whole body is visible)

A simplification of those rules is: Scroll the definition close to the top, but not exactly to the top, so the comments (and some extra context in case of variable definitions) are still visible.

Currently, "Go to definition" and other operations **center** the function **signature** within the window.

It would be more ergonomic to position the result closer to the top of the window because then you can see longer class/function definitions without scrolling and **most** of the code after the definition is usually more important than **most** of the code before the definition. We just have to ensure that sufficient context from before the definition is visible.

So, my suggestion is to have it revealed at around 20% of the screen height. I've tested that value and had some good experience with it. 15% might also be fine. IMHO, we shouldn't go beyond 25%.

### PR DESCRIPTION
**Pull request by wkornewald**
This improves the jump to definition and outline UX esp. for long functions/classes.

Fixes #80726 (see issue description for reasoning behind this PR).

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
This cannot be implemented by changing the behavior of `VerticalRevealType.Center` and `VerticalRevealType.CenterIfOutsideViewport`. These are well established and used by various places inside VS Code, and by extensions, e.g. the vim extension makes use of the `revealLine` command which accepts as argument `"at": "center"`.

This could be implemented by adding a new kind of `VerticalRevealType` in the editor and adopting this new kind for the desired features (go to definition, etc.)

**Comment by wkornewald** [comment]
OK, I was secretly hoping that in the worst case we could just rename Center to something better, but if you at least promise to merge this once it's clean I'll try to introduce a Definition constant and accompanying `revealDefinitionAtLine/Position/Range` methods to `IEditor`. Is that naming ok or would you suggest something better?

**Comment by wkornewald** [comment]
This needs some testing whether the UX really is better in all cases. I had to make quite a few changes and I removed the `IfOutsideViewport` part to also behave more like the JetBrains IDEs. They always jump to the same (consistent) screen location.

Only the history navigation is different because JetBrains remembers the scroll position of each history entry. If you resize the window it always scrolls like with go to definition. I think VS Code should remember the scroll position, too, but I didn't look into that as part of this PR.

Very small viewports (e.g. when pressing SHIFT+F12) needed some tuning, so you can see enough preceding lines. The code ensures a minimum scroll position of 100px from the top.

What do you think?

**Comment by alexandrudima** [comment]
@wkornewald I am sorry, but I cannot accept a PR that changes the world, because I cannot estimate its impact. That was really the point of my first review. Can you please make a change that is limited to go to definition or outline? Pick one, and let's tweak that one. If we receive positive feedback (I can also take the change to VSCode's UX call), we can then expand it to the entire universe of reveal calls... but I cannot accept such a huge PR because I cannot take responsibility for such a large impact change.

**Comment by wkornewald** [comment]
@alexandrudima I see, then let's give outline a try. The change is split into one commit for the infrastructure and one for the actual outline behavior change. I hope that's easier to review and simplifies testing individual aspects.

**Comment by alexdima** [comment]
Thank you!

**Comment by alexdima** [comment]
I have created https://github.com/microsoft/vscode/issues/90068 to track the further adoption of this reveal type for other actions.

**Comment by wkornewald** [comment]
Thank you, that's great news.

**Pull request merged**
