### PR TITLE
Promise with no error log error.stack

### PR DESCRIPTION
**Pull request by cancerberoSgx**
Some non handled promises are not logged at all (so was impossible to know where the error happened). One example is calling`TreeView.reveal()` with `TreeDataProvider` that doesn't implement `getParent()` : In that case I expect to see at least the following message (and a stack if possible):

`Required registered `TreeDataProvider` to implement 'getParent' method to access 'reveal' method`

Actual behavior: nothing is shown, just the message "WARNING: Promise with no error callback" 

 I was able to reproduce this in vscode master  creating a very simple extension that just did that. Don't know / don't have the time to investigate if the real issue is when the promise is created instead of in this part of the code. Notice I don't want only to print just the stack but also the message, logging error.error did the trick

Thanks

### CODE REVIEW

**Comment by cancerberoSgx** [comment]
tests were already failing without my change - commenting failing test() solves it - I would recommend you to do that - I can PR if you want or use this same , please advice, thanks

**Comment by alexandrudima** [comment]
It is super bizzare that there is an error with an error property. If steps are understood how to reproduce, then I suggest the area owner looks into it, in this case giving to you @sandy081

**Comment by cancerberoSgx** [comment]
Thanks @alexandrudima I know the fix is more like a workaround but unfortunately I don't have the time to get familiar with the code to propose a better solution. Thanks again and keep it up!

**Comment by sandy081** [comment]
@cancerberoSgx I see following when the extension calls `reveal` API and extension does not implement `getParent` method.

image

Do you see different than this? Also can you pleas file an issue for discussion before working on the PR?

**Pull request closed without merging**
