### PR TITLE
Use HTTPS for the apt repository

### PR DESCRIPTION
**Pull request by fmarier**
Fix for https://github.com/microsoft/vscode/issues/203832

How to test:
1. Build the `.deb` package.
2. `dpkg -i` the freshly-built package.
3. Look in `/etc/apt/sources.list.d/vscode.list` for an `https://` URL.

### CODE REVIEW

**Comment by fmarier** [comment]
It could also be worthwhile to upgrade existing installations similar to https://github.com/microsoft/vscode/blob/c9f0aa5b7303c9f60cae5889a1f04f0be56d333f/resources/linux/debian/postinst.template#L43-L45, but this requires building and testing and I don't have time for that right now. I suggest we leave that for a future follow-up.

This PR will at least address new installations.

**Comment by Tyriar** [comment]
This was proposed before in https://github.com/microsoft/vscode/pull/57992#issuecomment-419921020, you can see the reasoning for it being plain http there

**Comment by fmarier** [comment]
@Tyriar That reasoning made sense 6 years ago, but if you look at https://packages.debian.org/unstable/apt-transport-https, `apt-transport-https` is no longer a separate package since the functionality was moved to `apt` directly in version 1.5.

The oldest supported version of Ubuntu (18.04) [uses apt 1.6](https://launchpad.net/ubuntu/bionic/+source/apt) and the oldest supported version of Debian (10) [uses apt 1.8](https://packages.debian.org/buster/apt). Therefore, this will be a seamless upgrade for new installs.

I don't have the permissions to reopen this PR, so please consider this a request for re-review.

**Comment by Tyriar** [comment]
Nice, thanks for the follow up!

@rzhao271 FYI, could you take a quick look and approve this, want to make sure you're aware in case anything goes wrong.

**Review by Tyriar — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]

**Pull request merged**
