### PR TITLE
WIP: add an option to disable pointer

### PR DESCRIPTION
**Pull request by bailleul-dev**
Add an option to disable pointer and get the default cursor.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@laibulle Does this fix an issue?

**Comment by mkurnikov** [comment]
@laibulle I'm the original reporter of https://github.com/Microsoft/vscode/issues/44358. Tested this PR on my machine with MATE desktop 1.18, solves the issue for me. 

The only thing is `"workbench.disablePointer"` applies only after the restart of vscode. Tried change other settings in case I missed something in setup, all apply right after settings file save, as expected.

**Comment by laibulle** [comment]
@joaomoreno Yes, it is related to this one https://github.com/Microsoft/vscode/issues/44358

**Comment by bpasero** [comment]
I am not seeing progress and a lot of merge conflicts. On top of that the tree has been rewritten. I am going ahead and close this PR for being stale.

**Pull request closed without merging**
