### PR TITLE
Panel: remove the "toggle location" action in the panel header and move to menu

### LINKED ISSUE #58575: Panel: remove the "toggle location" action in the panel header and move it to menu
I would like us to clean up the amount of actions in the panel:

image

The action to move the panel to the right is quite prominent imho. I know we probably added it for discoverability of this feature, but how often is it actually being used from there?

I suggest to check with telemetry and maybe remove it in favour of our command palette and menu. Turns out this command is actually currently not in the "Appearance" menu, where it should probably be added.

/cc @misolori @stevencl

### PR DESCRIPTION
**Pull request by isidorn**
fixes #58575

fyi @bpasero @misolori everything as we agreed in #58575
The only downside is that on the main side I can not figure the current panel location (since it is stored in storage service, not in configurations) so I always have to call it `Toggle Panel Location`

### CODE REVIEW

**Comment by bpasero** [comment]
@isidorn works for me.

**Comment by isidorn** [comment]
I have decided to also add the sidebar location action to the sidebar title area for consistency
IMHO this actions does not belong in the activity bar (since activity bar and sidebar are different example: we have there hide activity bar, no hide sidebar)

screen shot 2018-09-28 at 16 09 59

**Comment by bpasero** [comment]
Yeah I was about to ask.

**Comment by isidorn** [comment]
@bpasero I code faster than you ask questions 🤓

**Pull request merged**
