### PR TITLE
Changed the method in the indexTreeModel.test.ts

### LINKED ISSUE #148770: mismatch content from the unit test `indexTreeModel.test.ts`
Does this issue occur when all extensions are disabled?: Yes

It's not really a thing, not even a bug. 

There is a unit test in the file `indexTreeModel.test.ts` named `expand`, I think it should be testing the method `expandTo()` (maybe?), but it tests `setCollapsed()` instead.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes #148770

### CODE REVIEW

**Comment by najmiehsa** [comment]
some tests are failing -  perhaps I had a simplistic overview of the issue.
I appreciate feedback or closure of this PR.

**Comment by Bistard** [comment]
You may try `model.expandTo([0, 1]);`.

**Comment by najmiehsa** [comment]
@Bistard Thank you.
 Highly appreciate it.

**Review by Bistard — APPROVED** [review]
test passed.

**Comment by connor4312** [comment]
Should be resolved with https://github.com/microsoft/vscode-cli/issues/434

**Review by connor4312 — APPROVED** [review]

**Review by roblourens — APPROVED** [review]
Remember to label the issue @connor4312

**Comment by najmiehsa** [comment]
Thank you for merging this ^^

**Pull request merged**
