### PR TITLE
Colour for column selection in debugging mode added to high contrast …

### PR DESCRIPTION
**Pull request by michelkaporin**
Colour for column selection in debugging mode added to high contrast theme. Amended yellow frame column selection to stand out in light themes.

Fixes issue #20536 

ping @isidorn

### CODE REVIEW

**Comment by isidorn** [comment]
@michelkaporin thanks for the pr! I checked it out and I have the following concerns:
* There is no change in the background yellow color in the light theme - I believe this color is too strong and we can experiment with lighter versions of it
* Current line indicator in the margin is too light now (attached picture where you can compare it to the strong breakpoint). It should be the same color as the column indicator
* Light theme column indicator is using a different shade of yellow as before - I recommend using the same yellow as the background but with a stronger transparency. If we make the background lighter the column might not need to be this strong
* HC theme - why do we use that shade of red. I would prefer that we use the same orange as the editor uses it
* HC theme - why do we still have different shade of yellow for the column indication when we already have that outline
* Currently there is a big change in how visible the column indicator is in light vs dark theme. There should not be such a big change

screen shot 2017-02-14 at 12 09 14

**Comment by michelkaporin** [comment]
Thank you for your comments @isidorn .

1-3. I assume you mean background colour of line highlight in your first bullet point. I have come up with several options of different yellow shades (please see the image attached below).
image
First three options use the same colour but of different transparency for line and column (selection) background. The last one uses slightly different colours for line and column background. In my opinion the last option is better. However, as per your suggestion it is better to stick with the same colour of different transparency, then I would go for 'Orangish shade' then. Let me know what is better in your opinion.
4. I have used red for accessibility purposes, having orange on top of yellow does not stand out that much as with red, thus impeding accessibility in my opinion. 
5. Fixed the issue, please see the image below how it looks like with orange outline and the same background for column indicator as for the line. Is it ok?
image
6. I have made the line background colour more transparent so that column indicator stands out. Is it better like that (image below)? 
image

Please give me a feedback on this, so that I can make required code changes afterwards.

**Comment by isidorn** [comment]
3. Let's go with option Light Yellow for now - looks most similar to the current version we have and seems to fix some of the issues
4. I would try making the background yellow less promimnent - it is not so important and I would try using the same orange if possible. Also what shade of red did you choose - since we always try to not to introduce any new colors unless really necessery
6. Looks good

**Comment by michelkaporin** [comment]
4. Having yellow less prominent (rgba(255, 255, 0, 0.7)), it looks like that 
image
Note that it will also require changing the text selection background (bottom line is selected on the image above). Should I go for this change? 

I have used rgb(255,0,0) for the red.

**Comment by isidorn** [comment]
Thanks for all the pictures. Let's go with your original approach of using pure red and not touching the yellow.
Once you push your commits I will merge in the PR and I can polish the colors a bit if needed

**Comment by isidorn** [comment]
@michelkaporin nice work - especaily like the small improvments in the dark theme

**Comment by michelkaporin** [comment]
@isidorn thank you

**Pull request merged**
