### PR TITLE
Fixes #95162: preLaunchTask should complete before resolveDebugConfig…

### LINKED ISSUE #95162: Launch preLaunchTask should complete before resolveDebugConfiguration
When attaching to a program using cppdbg with processId as ${command:pickProcess}, the command pick does not wait for the preLaunchTask initialization/finalization, processId command pick should start just after the preLaunchTask finalization.

Please refer to this issue: https://github.com/microsoft/vscode-cpptools/issues/5287

### PR DESCRIPTION
**Pull request by gustavomassa**
This PR fixes #95162

- The preLaunchTask was being executed on the final execution of createSession function, calling the runTaskAndCheckErrors function passing the preLaunchTask string name as taskId parameter.

- When preLaunchTask is undefined/null, the taskId is also undefined/null, resolving a null promise, consequently resulting in a successful task.

- The substituteVariables function is responsible for calling the execution of command:PickProcess, therefore the preLaunchTask should exec before.

### CODE REVIEW

**Comment by daniv-msft** [comment]
Hi @alexr00 ,

Could you please provide an estimation on how long it usually takes to approve this kind of PRs and integrate them in VS Code?
This bug is blocking us as well, as our scenario relies on injecting environment variables in the debug session, and for that we need the preLaunchTask to run before resolveDebugConfiguration.

Thanks,
Dan

**Comment by alexr00** [comment]
@daniv-msft this PR fell off my radar, and it looks like it would be better reviewed by one of the folk who works on debug. I've re-assigned to the appropriate person.

**Comment by daniv-msft** [comment]
Thank you for your reply @alexr00!

**Comment by isidorn** [comment]
Thank you for the PR and sorry for the slow response I was on vacation.
I have commented here https://github.com/microsoft/vscode/issues/95162#issuecomment-665569737
Due to that pushing this to On-Deck. If you have thoughts please comment on the issue, thanks!

**Comment by isidorn** [comment]
As discussed in https://github.com/microsoft/vscode/issues/95162
We will do a different approach. Due to that closing this PR.
Thanks anyways!

**Pull request closed without merging**
