### PR TITLE
Address misplaced cursor

### LINKED ISSUE #156788: Line cursor shifts underlying text by a few pixels
The text under the cursor gets shifted by a pixel or two with line cursor. This can be really distracting as it sometimes makes it look like there's a typo or just something wrong in the text.

See the animation, in my normal environment and with extensions disabled:

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Darwin arm64 21.6.0, MacOS Monterey 12.5 (21G72)

Steps to Reproduce:

1. use line cursor
2. move over text
3. watch closely for the letter boundaries (especially on round characters and wide ones like O and M)

### PR DESCRIPTION
**Pull request by jacekkopecky**
Fixes #156788

It looks like the "centering" is the main culprit causing my issue.

Test this by the following steps:

1. configure a wide-ish line cursor (so the letters underneath show up inside the cursor)
2. observe how with this PR the letter is no longer shifted by a pixel inside the cursor when not in text column 0

This is most visible on high-DPI screens where a pixel translates to several real pixels.

If we want to keep the "centering", or if we actually want to truly center the line cursor by half its width, we'd need to add left padding to the cursor element so that the shift left is balanced by the content shifting right. It would mean adding left padding (or all paddings) to fastDomNode. Let me know if you'd like that.

### CODE REVIEW

**Comment by jacekkopecky** [comment]
@alexdima I've realized that my commit message might be seen as criticising your earlier commit, sorry if it came across that way. I hadn't realized that this tweak was part of a fix for an earlier issue. 

It doesn't seem that issue #55640 recurs with my reversal of that "centering"; but if you'd prefer, I can look at the approach outlined above that can shift the cursor without moving the text inside it.

**Review by alexdima — CHANGES_REQUESTED** [review]
I see how this is super annoying. Maybe we can avoid doing the `-1` when having a wide cursor. But simply removing the `-1` ends up impacting negatively the cursor placement on macOS with default settings:

#### Before the proposed change:
image

#### With the proposed change:
image

**Comment by jacekkopecky** [comment]
I understand; I've updated the PR so the cursor does shift by 1px but it adds left padding so the text is where it's supposed to be. What do you think @alexdima ?

I've spotted something else: it looks like [the last line of real code](https://github.com/microsoft/vscode/blob/e3de4f6782f8efaf15d629ac228bffe673c13001/src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts#L236) which returns `width: 2` may want to return the actual width of the cursor. But it may be harmless.

**Comment by alexdima** [comment]
> I've updated the PR so the cursor does shift by 1px but it adds left padding so the text is where it's supposed to be.

The change looks alright in principle, but I think the extra padding is making the default cursor "fatter". Here it is running from source on macOS with default settings:

| Before the proposed change | With the proposed change |
|---|---|
| image | image


> I've spotted something else: it looks like [the last line of real code](https://github.com/microsoft/vscode/blob/e3de4f6782f8efaf15d629ac228bffe673c13001/src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts#L236) which returns width: 2 may want to return the actual width of the cursor. But it may be harmless.

That's a good catch! I've created https://github.com/microsoft/vscode/issues/164484 to track fixing that.

**Review by alexdima — APPROVED** [review]
Thank you!

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
