### PR TITLE
[themeing] Use Object.create(null) instead of {} for TokenRegistry

### LINKED ISSUE #103104: Semantic token colorization fails when a token type ID matching any object.prototype property name is provided
Issue Type: <b>Bug</b>

#### Current behavior
Semantic token colorization fails when a token type ID matching any object.prototype property name is provided. Some examples are: `constructor`, `toString` and `valueOf`. `constructor` is the most problematic name since it is likely to be used as a token type ID.

#### Expected behavior
Any string should be able to be used as a token type ID without causing the colorization to fail.

### Why does this bug happen?
Because [`TokenClassificationRegistry#typeHierarchy`](https://github.com/microsoft/vscode/blob/33b51eb210d2ae1c67721df3cd5d1ab4b6a6da17/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L263) gets instantiated with an object literal, and is later accessed like this: `let hierarchy = this.typeHierarchy[typeId]`. If an extension provides a `typeId` named "constructor" (or any other property name of object.prototype), `TokenClassificationRegistry#getTypeHierarchy(typeId: string)` will return a function instead of the expected `string[]`. Finally, [this line](https://github.com/microsoft/vscode/blob/33b51eb210d2ae1c67721df3cd5d1ab4b6a6da17/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L371) tries to call `indexOf` on what was thought to be a `string[]` but was actually a `function`, which throws a TypeError and causes the colorization to fail.

### How can it be fixed?
The easiest way is probably to use a `Map<string, string[]>` instead of an object for `TokenClassificationRegistry#typeHierarchy`. Another solution might be to instantiate `TokenClassificationRegistry#typeHierarchy` using `Object.create(null)` instead of an object literal in order to avoid the object.prototype.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 4.19.0-9-amd64

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Replaces {} with Object.create(null), so that accessing the object can have properties defined that conflict with the prototype names.  `constructor`, `toString` are examples.

This PR fixes #103104

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks @nrayburn-tech !

**Comment by jrieken** [comment]
Maybe it's time for native `Map`?

**Comment by nrayburn-tech** [comment]
@jrieken where all would `Map` be preferred?  Anywhere that `Object.create(null)` is used?

There are 180ish files that use `Object.create(null)`.  I can work on a PR to get the simple uses converted, but is there a preferred way to submit it, so it isn't so overwhelming to review?

Should I create an issue for this?

**Comment by jrieken** [comment]
> Should I create an issue for this?

No please :-) We generally don't accept PRs that go across different ownerships and make changes like this. Tho, when revisiting "local" things, as it has been done here, it is always a good consider to use modern JS

**Comment by aeschli** [comment]
Thanks, no PR needed, I prefer object literals.

**Pull request merged**
