### PR TITLE
feat: add git-bash support to shell integration

### LINKED ISSUE #143769: Shell integration for Git Bash
There are various issues regarding integration for various shells, but for Windows it's limited to standalone `pwsh`, and there are open issue for WSL.

So request here is to support Git Bash as well as it's go to terminal if you install Git for Windows.

Are there plans to support it in near future?

/cc @Tyriar

### LINKED ISSUE #208958: Enable shell integration on Git Bash
I'd like to have shell integration work on Git Bash, similar to how it works on Powershell/Pwsh

### PR DESCRIPTION
**Pull request by cpendery**
Adds support for shell integration to Git Bash when using the default prompt & includes the following tweaks

- Increase `MaxCheckLineCount` to 10 since bash's commands often output responses in the 6-8 lines range for built in commands
- Add a bash prompt for `$ ` prompts
- fix `areZshBashLoginArgs` to check for `--login` instead of powershell's `-login`
- update `areZshBashLoginArgs` to ignore any interactive args since the default args for the setting `"terminal.integrated.defaultProfile.windows": "Git Bash"` is `--login -i`.
- update `shellIntegration-bash.sh` to avoid sending a command complete *OSC* when the shell first starts up as this leads to bad marker placements on new Git Bash shells.

https://github.com/microsoft/vscode/assets/35637443/f12a6504-8aed-4b03-b26d-a506f18421d6

Closes #143769

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Very nice 👏 

How confident are you in the reliability of this happening automatically? We may want to make it opt-in via a setting for git bash for a month depending on the thinking here.

**Review by Tyriar — DISMISSED** [review]
Looks pretty solid to me, let's enable it by default for April in Insiders and if there are reports about something being broken I can add an opt-in setting for it.

**Review by Tyriar — DISMISSED** [review]

**Review by lramos15 — DISMISSED** [review]

**Comment by cpendery** [comment]
> Looks pretty solid to me, let's enable it by default for April in Insiders and if there are reports about something being broken I can add an opt-in setting for it.

Ah sorry I missed this before I just pushed the opt-in setting. I reverted that change

**Review by Tyriar — APPROVED** [review]

**Review by karrtikr — APPROVED** [review]

**Comment by Tyriar** [comment]
@IllusionMH yep, thanks for pointing that out. I'll fix it now

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/pull/209107

**Pull request merged**
