### PR TITLE
HistoryService: do not reset history when file change detected

### LINKED ISSUE #35920: History is reset when a file is deleted
- VSCode Version: 1.17.0, be377c0faf7574a59f84940f593a6849f12e4de7
- OS Version: Linux

Steps to Reproduce:

1. Navigate to a series of files to build up a history.
2. Go back a few times.
3. Delete a file in one of your workspace folders.
4. Try to go back or forward in history. Note that you are "jumped" to the end of your history, instead of keeping your existing index in the history. The expected behavior would be to keep your history "index" so long as the current file was not the one removed.

Reproduces without extensions: Yes

I believe the offending code is here: https://github.com/beyang/vscode/blob/14157ce22a548d935abd6845edaae23d9b0c829f/src/vs/workbench/services/history/browser/history.ts#L616

### PR DESCRIPTION
**Pull request by beyang**
This fixes https://github.com/Microsoft/vscode/issues/35920 by computing the correct history index when a file in history has been removed. Instead of setting the history to be the last item in the history, we adjust the index to account for any items in history that have been removed on account of the file deletion.

### CODE REVIEW

**Comment by bpasero** [comment]
@beyang I think this is complex enough to have test coverage. Can you look into writing tests that make sure the behaviour we want is covered?

**Comment by beyang** [comment]
@bpasero Sure. Can you help me understand what kind of tests you're looking for in this case? One option would be to factor out the deletion logic into a helper function separate from HistoryService and test that in a way that's agnostic of HistoryService. Another would be to add tests of HistoryService itself (which judging from a quick survey of the code would entail writing a decent number of mocks of other services).

**Comment by bpasero** [comment]
@beyang if you can find a unit that is small enough for your change to be tested, that is fine as well. Otherwise we do have mocks for most of our services, e.g. see how we use [`workbenchInstantiationService()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/test/workbenchTestServices.ts#L236).

**Comment by bpasero** [comment]
Closing due to inactivity.

**Pull request closed without merging**
