### PR TITLE
Quick tab jump to bracket

### PR DESCRIPTION
**Pull request by afonsobspinto**
1. QuickTabBracketAction action created.
2. Methods quickTabJumpToBracket and _getRangeBetweenBrackets created. 
3. Unit Tests.

from #22864 (and #30040 repost)

### CODE REVIEW

**Comment by rebornix** [comment]
@afonsobspinto Thanks for your contribution on this. I like the idea of making quick tabbing outside the brackets. However simply binding tab to this action in the editor will lead to many conflicts, for example, right now in the editor, tab is used to 

* Insert Tab
* insert Snippet when in snippetMode
* jump to next Snippet Placeholder when in snippetMode
* accept suggestions when suggest window is visible
* and Emmet

I don't know how can we make sure above behaviors don't break at all if we just check whether the cursor is on a bracket or not. Any ideas? 

I personally think this is a good extension candidate as putting it in the core will make our original workflow complex and broken somehow.

**Comment by afonsobspinto** [comment]
@rebornix No problem. I do understand you, I thought the same when I was doing this PR.

The obvious alternative would be change the keybinding, but I personally think it would go against the original idea of this feature (what do you think @Rhywun, @rkennesson?)

I'm not very familiar with the conditions needed to trigger the actions you mentioned, but would it be possible to only allow this new feature when those are not met?
Something like:
{
  `"command": "editor.action.quickTabToBracket",`
  `"key": "tab",`
`  "when": "editorTextFocus && !suggestWidgetVisible && !config.emmet.triggerExpansionOnTab && !hasSnippetCompletions && !hasNextTabstop"`
}

**Comment by Rhywun** [comment]
In other editors I have seen with this feature (latest VS on Windows, and Eclipse), the shortcut is TAB. Also there is (sometimes*) a "shadow" cursor that appears outside the bracket/parenthesis after you type the first one to show you where pressing TAB will take you. Almost like it's entering a snippet mode??

*I was unable to get the 'shadow' cursor in VS. But I swear it was there under some circumstances.

**Comment by Rhywun** [comment]
@afonsobspinto 
I closed #22864 due to suggestion to use the Tabout extension which does what I want. Thanks

**Pull request closed without merging**
