### PR TITLE
Feature #88480: Empty Lines Not Getting Commented-Out

### LINKED ISSUE #88480: Empty Lines Not Getting Commented-Out
- VSCode Version: 1.41.1
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Sample code to be commented-out:

```
package com.mycompany.app;

public class MyApp {
    public static void main(String[] args) {
        SayHello();
    }

    static void SayHello() {
        System.out.println("Hello!");
    }
}
```

2. Expected result:

```
// package com.mycompany.app;
// 
// public class MyApp {
//     public static void main(String[] args) {
//         SayHello();
//     }
// 
//     static void SayHello() {
//         System.out.println("Hello!");
//     }
// }
```

3. Actual result:

```
// package com.mycompany.app;

// public class MyApp {
//     public static void main(String[] args) {
//         SayHello();
//     }

//     static void SayHello() {
//         System.out.println("Hello!");
//     }
// }
```

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alvintangz**
This PR fixes #88480

New setting _editor.comments.includeEmptyLines_ allows you to include empty lines when adding or toggling single-line comments. Default behaviour does not allow for that to happen.

Acceptance test:
1. Open up a file that supports single-line comments (e.g. JS File)
2. Select a group of lines with empty lines in between
3. Toggle single-line comments (editor.action.toggleCommentLine) or add new single-line comments (editor.action.addCommentLine)
4. Enable setting via settings.json or in the UI
5. Toggle or add new single-line comments again to see the difference

Tests provided.

Feel free to give suggestions. Cheers

### CODE REVIEW

**Comment by n4nn31355** [comment]
Are there any chances to be merged? It's a big pain, especially for those who use prettier for auto formatting that removes blank lines between comments.

**Comment by alvintangz** [comment]
@n4nn31355 new CI tests failed. Going to fix it asap and then mention the assignee in the PR to get it pushed.

**Comment by alexdima** [comment]
Thank you!

**Comment by FloatingSunfish** [comment]
@alvintangz Many thanks to you and the VS Code team for implementing this much-requested feature!
We look forward to seeing it in a future update! Cheers!

**Pull request merged**
