### PR TITLE
Add simple expandable instanceLimit option in tasks. Fixes #32264

### LINKED ISSUE #32264: No option to automatically terminate previous task when a new instance of the same task is started
- VSCode Version:  1.14.2
- OS Version: Windows 10 Creators Update

This is just a suggestion. 

Almost all IDEs allow us to set a 'Single Instance Only' option, When this option is true, And you try to run a task that is already running, It'll kill the running task and then restart it.

VS Code gives an error stating that the task is already running, go to F1->Terminate Task to terminate the task.
This gets really annoying on some machines where to access Function keys, You also need to hold down a separate  "Fn" key. 

My suggestion is to let people specify a `SingleInstanceOnly` option in `tasks.json`, If this option is true, then instead of giving an error to user, It should kill the existing task and restart it. 
And if this option is false, Then just do what it does currently.
Default value should be `false`, So, Only the people who really need this option can set it and others will see the usual behavior 

And, I'd like to work on this, if that's okay. 

Regards 
Ishan

### PR DESCRIPTION
**Pull request by cinderblock**
Since #32384 seems dead with certain desired changes unfinished, this is just a trivial rewrite of that PR with a more open ended task option named `instanceLimit` instead of `singleInstanceOnly`. I also cleaned up some implementation details that I thought were a little weird.

For now, I've kept the simple `boolean` option and simply setting `instanceLimit: true` should restart any running task if I understand the code correctly. I also think this is the sane default behavior.

Unfortunately I have not been able to test this yet as setting up the full vscode build environment has been problematic for me.

I hope someone can test this, confirm it works, and accepts this so that the other dependent issues (#30726 #40027) and [more controls](https://github.com/Microsoft/vscode/pull/32384#issuecomment-424114086) can be worked on. This trivial implementation would I think still be useful for many.

### CODE REVIEW

**Comment by cinderblock** [comment]
@dbaeumer I'm totally with you that this should be more than a boolean. However my thinking was that a value of `true` could be used for now and evolved to support more options over time. I enumerated some thoughts on this on the previous. For reference, I was thinking something like this:

> ```
> instanceLimit: {
>   instances: 1,
>   kill: 'oldest',
> }
> ```
> `kill` would have 4 possible options. Not sure which one makes sense as the default. I vote `'oldest'` or `'die'`
> 
> * `'oldest'` (or `true` ?): Kill the oldest running instance of this task
> * `'newest'`: Kill the newest running instance of this task
> * `'ask'`: Ask user which instance to kill (or abort)
> * `'die'` or `false`: Don't start a new task if limit already hit. Possibly show a dialog box indicating execution limit hit.
> 
> `instances` should also accept `0` and `-1` to respectively mean "no instances allowed" (not sure why this would ever be used) and `'*'`.

I was thinking `instanceLimit: true` would basically be the equivalent of:
```
instanceLimit: {
  instances: 1,
  kill: true
}
```
---

Should I first make a PR that modifies `vscode.proposed.d.ts`?

---
I was trying to build with Node 10 as that is now LTS. I realize this is not supported yet officially but thought it was worth a try as I'm using it for other projects and don't want to deal with `nvm`. Then I had problems with "v140" version of Visual Studio Build Tools missing while trying to build native modules. I could not find the repo for `vscode-sqlite3` which was giving build errors. Then I apparently ran out of memory trying to run `yarn watch`. I tried to do it with Node 8 instead but had problems and decided I needed sleep and have yet to try again.

**Comment by alexr00** [comment]
I'm with @dbaeumer on this. Designing for 1-n instances instead of using a boolean makes sense and to keep the code path simple/easier to maintain, I'd rather we skip the boolean phase of this feature and build it using an `instanceLimit` and `instancePolicy` (or something like the `kill` property) from the start.

And @cinderblock, yes, you should add the proposed API to `vscode.proposed.d.ts` and then it can go through an approval process.

**Comment by saurabh-hirani** [comment]
This feature would be really useful - are there any timelines on when this would get merged? Thanks for engaging with the community and adding such helpful features!

**Comment by lonelam** [comment]
This feature is rather useful to me.
But this pull request seems dead again, is this feature covered by other commits now? 
@alexr00

**Comment by alexr00** [comment]
This PR is waiting for on requested changes. If someone else wan't to pick it up feel free.

**Comment by cinderblock** [comment]
@alexr00, to clarify, before this PR can be accepted, a separate PR must be submitted and approved that modifies solely `vscode.proposed.d.ts`?

**Comment by alexr00** [comment]
The proposed API can go into vscode.proposed.d.ts in this PR. However, my next comment makes that point moot.

The task properties have changed since the PR, so I think the `instanceLimit` should be put under the existing `runOptions`. Since `runOptions` isn't currently exposed in the API no need for vscode.proposed.d.ts :). Additionally, I'd like the `instanceLimit` to be a number as discussed above. 

Finally, a good follow on PR that adds an `instancePolicy` that does something similar to the `kill` property in https://github.com/microsoft/vscode/pull/62538#issuecomment-435811168 would be welcome. I don't think that needs to be part of this PR though.

**Comment by cinderblock** [comment]
Ok. I think that makes sense.

Unfortunately, I don't have a lot of time to look into this at the moment. If someone else wants to take over, please be my guest.

**Comment by alpalla** [comment]
I'd be glad to takeover! Let me know if there's anything else I should know.

**Comment by alexr00** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
