### PR TITLE
Add support for `"log": "<level>"` to the argv.json

### LINKED ISSUE #118824: Add support for `"log": "<level>"` to the argv.json
Or `"verbose": true` if that makes more sense.

From https://github.com/microsoft/vscode/issues/118372#issuecomment-797466580_

### PR DESCRIPTION
**Pull request by chrmarti**
Fixes #118824

Realized this is easy to implement and went ahead since this will improve serviceability of env (e.g., PATH) issues on Mac when starting from the dock.

### CODE REVIEW

**Comment by bpasero** [comment]
This is cool, but should it maybe be `log-level`?

**Comment by BossFriend** [comment]
uh

**Comment by chrmarti** [comment]
> This is cool, but should it maybe be `log-level`?

My first thought too, but I then saw the CLI parameter is called `--log`. Should we keep them aligned?

**Comment by bpasero** [comment]
I think I would prefer `log-level` because that makes it clear what happens. I would have called the CLI argument `log-level` as well.

**Comment by chrmarti** [comment]
Sounds good, I've updated the PR to use `log-level`.

**Review by bpasero — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]
LGTM - Thanks for the changes

**Pull request merged**
