### PR TITLE
Fix-82352 Filename number sort in search result

### LINKED ISSUE #82352: Filename number sort in search result
Like below, you can set the sort options in Settings, I also want to sort the file in search result.
image

---
https://github.com/Microsoft/vscode/issues/5066

### PR DESCRIPTION
**Pull request by skprabhanjan**
@roblourens  , Here is the implementation of the setting which will take care of sort order to fix #82352. ( I can change the name of enum values of setting if you feel so )

PS : Tested it and works fine and also it is easier to add more values to this setting in future.

### CODE REVIEW

**Comment by roblourens** [comment]
I am more interested in the sort options that `explorer.sortOrder` has. These are different and might be useful, I'm not sure. But I don't want to take this and call the issue fixed unless it addresses the original complaint.

**Comment by skprabhanjan** [comment]
@roblourens  , Are you suggesting the setting should have same options as explorer.sortOrder ?

**Comment by roblourens** [comment]
Yes

**Comment by skprabhanjan** [comment]
@roblourens , looking at the values for `explore.sortOrder` ( `filesFirst`,`type` and so on) I am wondering if that will help in any way in the search results ?

**Comment by roblourens** [comment]
I think 'type' and 'modified' are relevant.

I will close this to clean up, you can open a new PR if you want to keep working on it.

**Pull request closed without merging**
