### PR TITLE
build: update gulp-atom-electron@1.23.0

### PR DESCRIPTION
**Pull request by deepak1556**

### CODE REVIEW

**Comment by deepak1556** [comment]
Product build to verify -> https://monacotools.visualstudio.com/Monaco/_build/results?buildId=75012&view=results

**Comment by joaomoreno** [comment]
Builds seem to be failing, converting the PR to draft.

**Comment by deepak1556** [comment]
I am not sure whats wrong here, I tested this branch locally for our custom repo by setting

`"electronRepository": "microsoft/vscode-electron-prebuilt"`

and set the env `VSCODE_MIXIN_PASSWORD`  variable with a github token to download from private repo. This works fine locally.

**Comment by joaomoreno** [comment]
@deepak1556  I'm seeing some other errors in the builds:

> [23:25:33] /__w/1/s/src/vs/workbench/services/views/browser/viewDescriptorService.ts: line 22, col 26, Warning - Please add 'vs/workbench/services/views' to ./build/lib/i18n.resources.json file to use translations here. (code-translation-remind)

And on Windows:

> $ DEBUG=* node build/lib/electron
> 'DEBUG' is not recognized as an internal or external command,
> operable program or batch file.

Not sure how that relates to your last comment?

**Comment by deepak1556** [comment]
Abandoning, after some investigation I couldn't get the downloaded stream from `@electron/get` work with gulp streams. I have updated the old version to accept electron nightlies https://github.com/joaomoreno/gulp-atom-electron/tree/robo/electron_nightlies , we can update to that version.

**Pull request closed without merging**
