### PR TITLE
Fixes race conditions of writing and reading settings from multiple windows

### LINKED ISSUE #125970: Entire settings file got erased on new latest update. Just FYI
When I recently updated VS-Code Insiders Edition,  

Version: 1.57.0-insider (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T11:49:36.076Z

it deleted the entire 600+ lines of code I had in the settings code within the settings file,
it placed only 9 lines of new code on its own, leaving my entire settings 600+ lines of code empty.
I am lucky I made a backup on the settings file on a thumb-drive, otherwise I would have lost all my settings.

Just wanted to point that out to you guys.
It took me a couple of hours to realize what happened & fix, I thought it was an extension as I was hunting for the problem. 
But, When I finally looked at my settings file, everything was gone. Settings was empty except for 9 new lines I did not write.

### PR DESCRIPTION
**Pull request by sandy081**
This PR fixes #125970

- move writing user configuration to main process
- safe guard read from writing in parallel from other windows

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
I am not a big fan, especially since this seems to be restoring the loop for iterating over the file if the contents are empty due to truncate. 

Given all this, shouldn't the file service provide a `atomic` write option and then everything can stay the same? And the implementation is a write to tmp file and then move to target?

**Comment by sandy081** [comment]
I would be happy to use If the file service supports atomic write across windows. I thought about writing to tmp and renaming as you suggested, but I think this cannot handle race conditions especially when two windows tries to write settings. I think in this case last operation will replace previous ones that can cause lose of content. I am not sure if this can be handled. The current approach of single (main or shared in future) process handling writes will make sure there will be no race conditions. When we move to sandbox solution where I am guessing fs operations are moved to shared process then I can remove these loops and use atomic reads while reading settings from workbench.

**Comment by sandy081** [comment]
I think what we needed is here not atomic write but global atomic read as writes are safe because we throw exception (file modified since). It's the read we need to make atomic so that we do not read while writes are happening.

**Review by bpasero — APPROVED** [review]
I think this is an OK intermediate solution until we have the file service in a central place, so please file a follow up issue labeled `sandbox` to revisit this change. Ideally:
* it wouldn't be the main service doing the writes but some child process / shared process
* it wouldn't require you to loop in a polling interval to detect empty reads

Btw, the dirty write prevention logic ONLY works if you pass in a `etag` and `mtime` as part of the `writeFile` options. There is no internal tracking for this otherwise, so I doubt you benefit from this unless you would actually go through a text file model for writing.

See https://github.com/microsoft/vscode/blob/466dd4e490e5c27b95f5451673f0dd5c8f0a2c99/src/vs/platform/files/common/fileService.ts#L408-L426

**Comment by sandy081** [comment]
> Btw, the dirty write prevention logic ONLY works if you pass in a etag and mtime as part of the writeFile options.

You are right. I am taking care of this in `IUserConfigurationFileService` - that writes user settings - to read and write the file using e-tag and mtime:

https://github.com/microsoft/vscode/blob/155de9d895925e6dcf4d6da1a2ea022604f050e4/src/vs/platform/configuration/common/userConfigurationFileService.ts#L54-L76

**Comment by bpasero** [comment]
Oh wow, you so smart!

**Pull request merged**
