### PR TITLE
Added a setting to open cloned repository automatically.

### LINKED ISSUE #93300: Git: After cloning and no folder is open, add option to open the folder automatically.
v1.43.1
image
Add an option in preferences, that when this message appears and you don't have anything open, open the folder automatically.

### PR DESCRIPTION
**Pull request by jpiskiewicz**
This PR fixes #93300

### CODE REVIEW

**Comment by yume-chan** [comment]
I think it's better called "git.openAfterClone" or something, current name doesn't express that "you can open the folder".

And it looks like you didn't set your Git credentials correctly (probably wrong email), so GitHub doesn't link your commits to your profile.

**Comment by eXotech-code** [comment]
> I think it's better called "git.openAfterClone" or something, current name doesn't express that "you can open the folder".

@yume-chan  Yes, you are right. I think that current name is not the best. I will work on it.

> And it looks like you didn't set your Git credentials correctly (probably wrong email), so GitHub doesn't link your commits to your profile.

Yes I've recently changed my email address. I am working to fix this issue.

**Comment by jingweno** [comment]
Love being able to configure opening directly after git clone, instead of clicking the "Open" button

**Comment by eXotech-code** [comment]
> Love being able to configure opening directly after git clone, instead of clicking the "Open" button

@jingweno this is excactly what I added. If you choose any other option than "showPrompt" it will open the repo after cloning without asking.

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Comment by eXotech-code** [comment]
> Thanks! 🍻

Glad to help!

**Comment by joaomoreno** [comment]
FYI ended up refactoring a bit and changing the setting names slightly. Overall, the PR was in very good shape!

**Comment by eXotech-code** [comment]
Thanks! I'm looking forward to my future contributions!

**Pull request merged**
