### PR TITLE
Fix for issue #27393 - UX: align file names when renaming

### PR DESCRIPTION
**Pull request by TunedMidja**
Fix for [Issue #27393](https://github.com/Microsoft/vscode/issues/27393).

### CODE REVIEW

**Comment by isidorn** [comment]
Did you verify this fix works?
On what OS did you verify?

**Comment by TunedMidja** [comment]
I've only verified it on OS X.

**Comment by isidorn** [comment]
Thanks, I have just verified it is ok on OS X.
But not on Windows. Due to that I can not merge this PR.
Can you try to fix it also on Windows? Or should we wait for some other PR which does it on all platforms?

**Comment by TunedMidja** [comment]
This is not a specific fix for OS X but I haven't verified it on any other platform. Is there any easy way to do this (without setting up the entire development environment on Windows for example)?

**Comment by isidorn** [comment]
I personally use Parallels. There is no simpler way afaik
I can merge in your PR, it helps on the mac, but I would keep the issue open since windows is still affected. Though I would prefer if we find a fix which works on all platforms

**Comment by TunedMidja** [comment]
Why do you assume that it doesn't work on Windows? I looked at a rejected PR for fixing this issue:
https://github.com/Microsoft/vscode/pull/43443
Just by looking at the CSS class names (.monaco-workbench.linux and .monaco-workbench.mac) you can guess that this is not gonna work on Windows. But in my PR I changed another CSS class which has no hints of any OS so it should work for all platforms.
Of course it's better if it has been tested on all platforms but still.

**Comment by isidorn** [comment]
I did not assume. I actually tried it on Windows and it is now working. Sorry for not being more clear.

**Comment by TunedMidja** [comment]
No problem. Thanks!

**Comment by isidorn** [comment]
Args I made the stupid typo in my previous message. I typed `now` instead of `not`. Sorry.
It is **not** working on Win

**Comment by TunedMidja** [comment]
OK, too bad. I might look into this further but I'm not sure as it would require setting up the entire dev environment on a Windows machine which would be very time consuming.

**Comment by garymathews** [comment]
@TunedMidja I had some time to look into this myself, this addresses all platforms https://github.com/Microsoft/vscode/pull/60539

**Comment by isidorn** [comment]
@garymathews thanks a lot! Let me try out your PR on all platforms. 
Closing this in in favor of the new PR

**Pull request closed without merging**
