### PR TITLE
# Add partial accept kind to inline completion handle

### PR DESCRIPTION
**Pull request by marrej**
# 1st part of the partial accept handler enrichment

This first proposal enables the metadata to be attached in the core to the partialAcceptHandler to return the `Kind` of partial acceptance that was triggered.

This allows for deeper understanding of user interactions, as well as filtering out specific triggers when doing post analysis (e.g. Suggest).

https://github.com/microsoft/vscode/issues/195369

### CODE REVIEW

**Comment by hediet** [comment]
> [eslint                  ] [16:52:03] /mnt/vss/_work/1/s/src/vs/workbench/api/common/extHostTypeConverters.ts: line 2406, col 4, Warning - Missing semicolon. (@typescript-eslint/semi)

**Comment by marrej** [comment]
> > [eslint                  ] [16:52:03] /mnt/vss/_work/1/s/src/vs/workbench/api/common/extHostTypeConverters.ts: line 2406, col 4, Warning - Missing semicolon. (@typescript-eslint/semi)

Sorry for the early ping, I tried to keep the PR in draftmode but you already got assigned. The issues should be resolved now :)

**Comment by marrej** [comment]
Reworked the API, to allow easy onboarding of new users (wouldn't cause breakage when released with extensions).

**Comment by marrej** [comment]
Hey @bhavyaus , Is there any additional changes that you would like me to add to the PR?

Also if I may be so bold to ask, why did you add the `PartialAcceptInfo` directly to the proposed API. Is it because the proposed APIs can break current extension implementations and are `experimental` only?

**Comment by bhavyaus** [comment]
> Hey @bhavyaus , Is there any additional changes that you would like me to add to the PR?

Apologies. I was performing endgame testing. Ignore my previous comment.

> Hey @bhavyaus , Is there any additional changes that you would like me to add to the PR?
> 
> Also if I may be so bold to ask, why did you add the `PartialAcceptInfo` directly to the proposed API. Is it because the proposed APIs can break current extension implementations and are `experimental` only?

Apologies. My comment was a test comment I made during our endgame testing. @justschen , could you please help take a look.

**Review by hediet — DISMISSED** [review]

**Review by aeschli — DISMISSED** [review]

**Review by hediet — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]

**Pull request merged**
