### PR TITLE
Update Octicons

### LINKED ISSUE #36053: Please update octicons from 3.1.0 to 6.0.1

### LINKED ISSUE #65508: Update Octicons
Related to #36053 #10455 #8017

This issue is to track the progress of updating our version of [Octicons](https://octicons.github.com/) (3.1.0) to the latest version (8.2.0). We'll need to create the work to convert the latest versions (svg) back into an icon font. Below are the requirements for this work:

- [x] Convert svgs into icon font
- [x] Include backward compatibility
- [x] Map old unicodes to new icons
- [x] Remove unnecessary font files
- [x] Add/update proper licenses
- [x] Test new icon font

Working branch can be found under [misolori/octicon-update](https://github.com/Microsoft/vscode/tree/misolori/octicon-update). Below is a list of the new additions:

- `arrow-both`
- `bold`
- `eye-closed`
- `fold-down`
- `fold-up`
- `grabber`
- `italic`
- `kebab-horizontal`
- `kebab-vertical`
- `logo-gist`
- `note`
- `plus-small`
- `project`
- `screen-full`
- `screen-normal`
- `smiley`
- `tasklist`
- `text-size`
- `unverified`
- `verified`

Please refer to [Octicon's Changelog](https://github.com/primer/octicons/blob/master/CHANGELOG.md) for a full list of updates.

:octocat: :heart:

### PR DESCRIPTION
**Pull request by miguelsolorio**
Fixes #65508 and fixes #36053

This updates our version of Octicons, while still having backward compatibility with icons that have been removed in the newer versions. I've [created this tool](https://github.com/Microsoft/vscode-octicons-font) that generates the new icon from the [Octicon npm module](https://github.com/primer/octicons/tree/master/lib/octicons_node).

The only minor changes are that `organization` and `person` are now filled versions instead of outlines.

## Additions
image

- `arrow-both`
- `bold`
- `eye-closed`
- `fold-down`
- `fold-up`
- `grabber`
- `italic`
- `kebab-horizontal`
- `kebab-vertical`
- ~`logo-gist`~
- `note`
- ~`plus-small`~
- `project`
- `screen-full`
- `screen-normal`
- `smiley`
- `tasklist`
- `text-size`
- `unverified`
- `verified`

## Updated
image

- `color-mode` is persisted
- `organization-filled` is for the new version of the icon
- `person-filled`  is for the new version of the icon

## Comparison
After installing a few extensions that use octicons in the statusbar (vscode-spotify, live share, github pull request), you can compare the differences.

image

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
Approving, the change looks to me good otherwise.

**Comment by bpasero** [comment]
@misolori just noticed two things:
* please keep in mind to release note this properly, I would also think we could create an issue over in vscode-docs to document the valid icons a bit better (maybe with showing the icon on the website?)
* run a search for `octicon` in our repo to see where we use octicons in our core and verify nothing is broken, e.g. it looks like in some places we directly reference an icon through CSS
* finally it would be good to run a full build with your changes just to make sure things are packaged up properly. e.g. I noticed some build rules in our gulpfiles related to octicons

**Comment by misolori** [comment]
@bpasero:

- Removing the `logo-gist` and `plus-small` is totally fine. I've seen people not wanting the Gist logo in other issues and we already have a regular plus.
- I can do a swap of the people and organization icons for live ahre and move the new ones to the appended name
- I was already planning on mentioning this in the release notes, I've created https://github.com/Microsoft/vscode-docs/issues/2315 to track this is
- I'll also do a final test and double-check the other areas Octicons are being used and create a custom build

👍 Thanks for feedback!

**Comment by bpasero** [comment]
@misolori great, feel free to merge then after you tested the build

**Comment by misolori** [comment]
Fixed a rendering bug that appeared in Windows, still need to test on Linux and then will merge.

**Comment by misolori** [comment]
Verified the changes on macOS/Win10/Linux and it all looks good, will merge this in.

**Pull request merged**
