### PR TITLE
callbacks - adopt a client only solution (#140328)

### LINKED ISSUE #140328: Rewrite polling callback solution to be serverless
By adopting a local storage based solution.

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #140328

I was not really sure about this TODO:

https://github.com/microsoft/vscode/blob/23598a0575bf6cf8e70884804bfc39cc3fea5247/src/vs/code/browser/workbench/workbench.ts#L204-L213

Sample extension code to test this:

```ts
vscode.window.registerUriHandler({
	handleUri(uri: vscode.Uri): vscode.ProviderResult<void> {
		if (uri.path === '/did-authenticate') {
			console.log(uri.toString());
		}
	}
});

const callableUri = await vscode.env.asExternalUri(vscode.Uri.parse(`${vscode.env.uriScheme}://<extension id>/did-authenticate`));
await vscode.env.openExternal(callableUri);
```

### CODE REVIEW

**Comment by joaomoreno** [comment]
The TODO is related to https://github.com/microsoft/vscode/blob/f67a8b753f55e452f38b61497662839c4691fb12/extensions/github-authentication/src/githubServer.ts#L129-L130. @TylerLeonhardt will eventually fix this, I think.

**Review by joaomoreno — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Also I think you fixed my bug maybe? https://github.com/microsoft/vscode-test-web/issues/19 :)

**Comment by bpasero** [comment]
@aeschli needs to comment on that, my change still needs support from the server and I don't know about Martins server implementation.

**Comment by aeschli** [comment]
@TylerLeonhardt I still need to adopt vscode-test-web. 

@bpasero Can we put the code that computes the callback uri on the server to the callback.html page? I think @joaomoreno does that.

**Comment by bpasero** [comment]
Yes I will take a look.

**Comment by bpasero** [comment]
Pushed. @joaomoreno @aeschli please review: https://github.com/microsoft/vscode/commit/b1b2bd6c848b72dc2791bf474d50742da941c0ea

**Pull request merged**
