### PR TITLE
[#25575] Add Git Tag feature.

### PR DESCRIPTION
**Pull request by ashutoshdhundhara**
This PR implements [Git Tag feature](https://github.com/Microsoft/vscode/issues/25575)

Preview:
image

- **Create Tag**: To create a new tag, asks for Tag name and Message.
- **Show Tags**: Lists existing tags.
- **Push With Tags**: Default `push` operation with `--tags` flag.

### CODE REVIEW

**Comment by ashutoshdhundhara** [comment]
Am I missing something in this PR or its still under review?

**Comment by Stephanevg** [comment]
Hi is still in progress? I would love to have this access to this feature :)

**Comment by joaomoreno** [comment]
@ashutoshdhundhara Don't forget to sign our CLA.

**Comment by ashutoshdhundhara** [comment]
@joaomoreno I have signed the CLA at https://cla.microsoft.com but the PR still has the "cla-required" tag?

**Comment by joaomoreno** [comment]
Thanks! 🍻 

I've removed the `showTags` feature as it didn't fit with the rest of the feature set.

**Comment by ElixirMike** [comment]
I'm wondering if you have a way of adding a tag to a specific Commit ID? Currently, it appears to auto-link to the current commit. What if I wanted to add a tag to a previos commit ID like I can via the Git command line? Is that supported?

**Pull request merged**
