### PR TITLE
Always attempt to correct indent on closing tag

### LINKED ISSUE #2116: [html] Inconsistent de-indentation behavior while closing html tags using Autocomplete
I've noticed while using VS Code that there is different de-indent behavior for closing tags contingent on whether or not I type '/' after '<'. Apologies in advance for the large and bad-quality gifs.

Below we can see what happens if I don't type '/':
no-work 04d

Below we can see what happens if I do type it:
work

I would expect these to have similar behavior, but I might be wrong.

System information:
VS Code
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:26:42.359Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

Operating System
Ubuntu Gnome 15.10 x64

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #2116 

---

/cc @aeschli, not sure what the original intent of making this false was but it would seem to be that correcting the indent is always desirable for closing tags?

### CODE REVIEW

**Comment by Tyriar** [comment]
After merging from upstream/master the tests passed, I think this might have been a flaky test?

**Comment by Tyriar** [comment]
ping @aeschli

**Comment by Tyriar** [comment]
Ping @aeschli

**Comment by aeschli** [comment]
Sorry for the delay, @Tyriar, you are right, that's the right fix. This Boolean is no longer needed, as always true, so I removed it. #2116 is now fixed. Thanks for your help!

**Pull request closed without merging**
