### PR TITLE
shrinkwrap and OSSREADME.json for emmet 

### PR DESCRIPTION
**Pull request by ramya-rao-a**

### CODE REVIEW

**Review by kieferrm — APPROVED** [review]
I re-generated the shrinkwrap file from 1.13 source and came to identical results.

**Comment by alexandrudima** [comment]
@ramya-rao-a The only thing which is not clear to me is why does the `OSSREADME.json` repeat 3 of the consumed node modules that are already present in the `npm-shrinkwrap.json` ? Was it a case that the oss tool does not discover the LICENSE files for these node modules ? If that is the case, then `isLicense` can be used in the `OSSREADME.json` to overwrite the auto-discovered license. Or are these node modules checked in to our repository ?

**Comment by ramya-rao-a** [comment]
@alexandrudima My mistake. I assumed that OSSREADME.json should have an entry for each of the dependency in the package.json

Updated with https://github.com/Microsoft/vscode/commit/275c3fd527a53a5a27bd3ed3c200842bb58022cf

**Comment by alexandrudima** [comment]
:+1: I'm sorry the README.md is worded in a funny way -- https://github.com/Microsoft/vscode-distro/tree/master/distro-tools#ossreadmejson-specification

The idea is that `OSSREADME.json` can have two types of items:

### One type fully describes an OSS dependency that does not come from `npm-shrinkwrap.json`
  * this can happen when including OSS code straight in our repository, or in other special circumstances, such as e.g. us consuming the `oniguruma` node module which fails to credit the `oniguruma` regex library in their License file although the regex library is shipped with the npm module. other special cases in this category include platform deps, such as nodejs, etc.
  * for example, we are consuming `chjj-marked` and checking it in with our sources. Since `npm-shrinkwrap.json` does not mention `chjj-marked`, we must declare that we are using it. [e.g.](https://github.com/Microsoft/vscode/blob/f47b826f7d83b6bafaa331056d42ff37853f6a3f/src/vs/base/common/marked/OSSREADME.json#L4)
```
{
	"name": "chjj-marked",
	"repositoryURL": "https://github.com/npmcomponent/chjj-marked",
	"version": "0.3.2",
	"license": "MIT"
}
```
  * in this case, since this OSS item is not resolved from npm, it is important to specify: `name`, `version`, `license` and `repositoryURL`
  * sometimes, the LICENSE text cannot be fetched automatically by the oss tool from the listed repository. e.g. the author does not include a LICENSE file. In this case, one can inline the license text via `licenseDetail`. [example here](https://github.com/Microsoft/vscode/blob/f47b826f7d83b6bafaa331056d42ff37853f6a3f/src/vs/editor/node/textMate/OSSREADME.json#L4)



---

### The second type of item is one that just binds a LICENSE text to an npm module
  * even though a dependency can come from npm, the oss-tool might not find automatically the LICENSE text. In this case it is possible to associate a license text with an npm module consumed via `npm-shrinkwrap`
  * an good example [is here](https://github.com/Microsoft/vscode/blob/f47b826f7d83b6bafaa331056d42ff37853f6a3f/extensions/markdown/OSSREADME.json#L72):
```
{
	"isLicense": true,
	"name": "uc.micro",
	"licenseDetail": [
		...
	]
}
```
  * the npm node module [`uc.micro`](https://www.npmjs.com/package/uc.micro) we consume does not include a LICENSE text file, it has a link tag in its readme and not the full license text, so the oss tool cannot automatically fetch the LICENSE text.
  * in this case `isLicense`, `name` and `licenseDetails` can be used to bind this license text to a npm module.

---

If you have a better understanding of how this works, please consider updating the README.md at https://github.com/Microsoft/vscode-distro/tree/master/distro-tools#ossreadmejson-specification to simplify or correct it.

**Pull request merged**
