### PR TITLE
Word fixes

### LINKED ISSUE #99980: storage.json - windowsState.openedWindows not updated properly.
- VSCode Version: 1.46.0
- OS Version: Mac 10.15.4

Since the last version windowsState.openedWindows is not updated properly when opening the first window, and also when closing window. 

Steps to Reproduce:

1. Open some folder with visual studio. (single window)
2. windowsState.openedWindows is now empty (should have one item).
3. Open a second window.
4. windowsState.openedWindows size is now 2 (as should).
5. Close one of the windows.
6. windowsState.openedWindows is now either empty or still have 2 items (should have one item).
7. If 2 items - wait a while (for me something around 10 seconds).
8. windowsState.openedWindows is now empty (should have one item).

It all worked just fine until the last version. 
What went wrong? 

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by keshav-bohr**
Initially was working to fix #99980 updating storage.json
But, seems like it is already fixed.

So, raised a PR for word fixes. in that file.

### CODE REVIEW

**Comment by keshav-bohr** [comment]
Is there a way to run the checks again?
Since this PR contains word change, I don't think the checks should fail.

@isidorn

**Comment by bpasero** [comment]
Thanks

**Comment by keshav-bohr** [comment]
Hi @bpasero 
I could not see my name in the contributors list. Why is that?

**Comment by bpasero** [comment]
@keshav-bohr what list are you referring to?

**Comment by keshav-bohr** [comment]
@bpasero 
Contributors section of the repo. Ideally it goes there.

**Comment by bpasero** [comment]
@keshav-bohr I am not sure, I suggest you contact GitHub Support directly.

**Pull request merged**
