### PR TITLE
Fixing various API/Comment/Variable spelling improvements

### PR DESCRIPTION
**Pull request by andiamantoukos-fadv**
Hello! I went through the codebase (with [this plugin](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)) and spent some time making as many green squiggly underlines go away as I could.

A large bulk of the changes come from the i18n ids I fixed. I did not alter any translation values, but because the id was changed it was replicated to all the languages. 

To make that part a little better, here are all the ids that have changed:
- breakpointDirtydHover -> breakpointDirtyHover
- breakpointUnverifieddHover -> breakpointUnverifiedHover
- ConfigurationParser.invalidVaraibleReference -> ConfigurationParser.invalidVariableReference
- debugRequesMissing -> debugRequestMissing
- debugTypeNotRecognised -> debugTypeNotRecognized
- disableDependeciesConfirmation -> disableDependenciesConfirmation
- editLineBrekapoint -> editLineBreakpoint
- editTtile -> editTtile
- enableDependeciesConfirmation -> enableDependenciesConfirmation
- hideActivitBar -> 
- invalidVaraibleReference -> invalidVariableReference
- JsonSchema.tasks.showOputput -> JsonSchema.tasks.showOutput
- launchJsonNeedsConfigurtion -> launchJsonNeedsConfiguration
- miOpenProcessExplorerer -> miOpenProcessExplorer
- morecCommands -> moreCommands
- openEditosrSection -> openEditorSection
- performanceIssueDesciption -> performanceIssueDescription
- referencesFailre -> referencesFailure
- reloadWindowWithExntesionsDisabled -> reloadWindowWithExtensionsDisabled
- schema.font-sstyle -> schema.font-style
- showSearchViewl -> showSearchView
- sortByPrecedene -> sortByPrecedence
- symbolicLlink -> symbolicLink
- taskService.ignoreingFolder -> taskService.ignoringFolder
- TaskService.tastToRestart -> TaskService.taskToRestart
- TaskService.tastToTerminate -> TaskService.taskToTerminate
- TaslService.noEntryToRun -> TaskService.noEntryToRun
- uninstallDependeciesConfirmation -> uninstallDependenciesConfirmation
- unkownProblemMatcher -> unknownProblemMatcher

My main motivation is to just give back to the VSCode team for this outstanding piece of Open Source Software !

### CODE REVIEW

**Comment by bpasero** [comment]
@MercifulCode I have to ask to extract those parts of the PR that relate to user acing english labels (anything within the `nls.localize()` method that is not an identifier). 

We don't take PR's that don't bring any improvement to the product itself. Typos are OK to have, especially in comments.

If you want to contribute to the project I suggest to go through https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by bpasero** [comment]
I should add: changes to vscode.d.ts and vscode.proposed.d.ts are fine as well given that we convert that file into actual documentation on code.visualstudio.com

**Comment by MercifulCode** [comment]
Thanks for the feedback, @bpasero !

If I understand right, typos in `vscode.d.ts` and `vscode.proposed.d.ts` are fair to address in a separate (and smaller) PR? 

As for the localization identifiers, is that something I can open a PR via Transifex to address, or something handled entirely separately? If I could, I'd love to help ensure consistency for people with screen readers who might encounter it.

Thanks!

**Comment by MercifulCode** [comment]
Opened #50533 !

I can definitely see the number of people interacting with the identifiers being minimal. The main two groups that came to mind are extension developers and translators, and even then I do not have empirical data on whether it is a major concern worth addressing outside the compulsion to fix all squiggles.

**Pull request closed without merging**
