### PR TITLE
Initial implementation: Support \U\u\L\l replace modifiers

### PR DESCRIPTION
**Pull request by irridia**
Support \U\u\L\l modifiers to search replacement to alter word case in the per-file Find/Replace flow. This does _not_ affect the "Replace in Files..." flow, which appears to rely on ripgrep.

The behavior is patterned after Boost, but only applied to the replacement text, not subsequent content. Thus the \E isn't relevant. This is also vaguely similar to other replacement syntax, like pcre2 and perl.

For example, to export a file full of non-exported functions in a Go file:
Find:
`^func (\w+)\(`
Replace:
`func \u$1(`
Example:
`func myPrivateFunc(...`
Result:
`func MyPrivateFunc(...`
With `\U`:
`func MYPRIVATEFUNC(...`
With `\l\l\l\U`:
`func mypRIVATEFUNC(...`

This PR partially addresses #12185

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks for the PR! We are wrapping up the April release this week but I will take a look next week.

**Review by roblourens — COMMENTED** [review]
This looks like a good approach, but it's only hooked up for the find widget in the editor, could you do it for both the editor and workspace replace? All you have to do is move it to a helper method that can be called from replacePattern.ts and also from somewhere in `.../search/...`. You can look at what we did for the "preserve case" feature for inspiration, see how `buildReplaceStringWithCasePreserved` is called.

**Review by alexdima — APPROVED** [review]
LGTM, good work.

I am OK to merge this, and adopt it for the search across files in a separate PR.

**Comment by nashikb** [comment]
I spent some time yesterday looking through the implementations of ReplacePattern in vs/editor/contrib/find/replacePattern.ts and vs/workbench/services/search/common/replace.ts. Each of these implements different mechanisms for the CharCode `switch`es, so a small CharCode-aware-only helper function doesn't seem viable.

The alternative IMO is to choose (or combine) one of the ReplacePattern implementations, move it to vs/base/common/search.ts (or perhaps .../replace.ts) and tweak the small handful of callers.

I'm probably not the best choice to perform a nuanced refactor since I'm a TS noob; however I can likely implement the replacement change in .../replace.ts as a parallel to .../replacePattern.ts.

Thoughts?

**Comment by irridia** [comment]
I spent some time yesterday looking through the implementations of ReplacePattern in vs/editor/contrib/find/replacePattern.ts and vs/workbench/services/search/common/replace.ts. Each of these implements different mechanisms for the CharCode `switch`es, so a small CharCode-aware-only helper function doesn't seem viable.

The alternative IMO is to choose (or combine) one of the ReplacePattern implementations, move it to vs/base/common/search.ts (or perhaps .../replace.ts) and tweak the small handful of callers.

I'm probably not the best choice to perform a nuanced refactor since I'm a TS noob; however I can likely implement the replacement change in .../replace.ts as a parallel to .../replacePattern.ts.

Thoughts?

**Comment by roblourens** [comment]
Yeah, I see why it will be a little complicated to do that and why it is different than what we did for `buildReplaceStringWithCasePreserved`. Maybe we can merge this PR and just do a separate one with a parallel implementation for search? Or I could do some refactoring and try to get one implementation for both.

**Comment by irridia** [comment]
I'd be happy to do the parallel PR on the workbench path. It's sort of continuing artificial code separation, but it will at least eliminate a new difference between the implementations.

**Comment by roblourens** [comment]
That sounds good to me!

**Comment by irridia** [comment]
I've spent a couple of hours on implementing case operations in `.../replace.ts`, but I've realized that I would need to essentially reimplement String.replace(), since that's what it fully relies on. `.../replacePattern.ts` already has this type of piecemeal replacement logic, so I'm thinking it would be /less/ work (and far cleaner) to use `replacePattern.ReplacePattern` everywhere that `replace.ReplacePattern` is currently used (seems like only `.../searchModel.ts`).

**Comment by roblourens** [comment]
I guess I don't really understand the difference between the two implementations @alexdima and @sandy081, why is the editor's ReplacePattern manually resolving `$` references in the replace string instead of just doing a `String.replace` like search's version?

**Comment by alexdima** [comment]
I am sorry that I don't remember everything. Here is a comment I could find -- https://github.com/microsoft/vscode/issues/18111#issuecomment-271862568 ...

I think I found the issue #18111 (searching for `/\b\s{3}\b/`) to be fundamentally caused by the researching in the matched portion of a string. In other words, searching for a regex in a large string does not yield the same result/groups as searching for the same regex in the substring that did match because regular expressions sometimes refer to characters around the matched text (like `\b` does here).

So I have changed the text buffer search to return captured groups while searching, so the capture groups are those of searching in a large string. But the search across files could not do that, so I believe that is the point where I forked things.

**Pull request merged**
