### PR TITLE
Fix #44776 - Error on "Undo Last Commit" if executed against the initial commit

### LINKED ISSUE #44776: Git: fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Windows 10/Insiders

Repro:

1. Open a folder
2. Init git repo
3. Add files and do a commit
4. Undo last commit

image

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.13.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git init
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Users\daimms.REDMOND\Documents\playground\t
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git add -A -- c:\Users\daimms.REDMOND\Documents\playground\t\script-1.bat
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git add -A -- c:\Users\daimms.REDMOND\Documents\playground\t\.vscode\tasks.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git commit --quiet --allow-empty-message --file -
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name --abbrev-ref master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git show -s --format=%H
%B HEAD
> git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git show -s --format=%H
%B HEAD
> git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### PR DESCRIPTION
**Pull request by ryu1kn**
Fix for the issue #44776. Why I fixed this way is written in https://github.com/Microsoft/vscode/issues/44776#issuecomment-378942407.

Please have a look 😉

### CODE REVIEW

**Comment by joaomoreno** [comment]
@ryu1kn While tests are great, I'm not too happy in having stubs in the git tests. Either make them not use stubs, or remove them.

**Comment by ryu1kn** [comment]
Repository’s `getCommit` and `deleteRef` are not pure function and make side effects; so i need to stub dependency or record the call from the repository. If you don’t want stub, i think i have to remove the tests i wrote...

**Comment by ryu1kn** [comment]
@joaomoreno Can you think of better way of writing those tests? I believe those tests, especially the ones for `Repository#getCommit` are showing what you can expect from the method and so valuable. I wonder if we want to keep them.

**Comment by ryu1kn** [comment]
Or I can test not the whole `Repository#getCommit` but only the logic of parsing git output by extracting it as an `export`ed function. I usually don't `export` things from a module only for testing purpose, but looks like this is how we do it.

**Comment by ryu1kn** [comment]
@joaomoreno Haven't had a chance to look at it again?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
