### PR TITLE
Add a specialized unhandled conflicts close handler

### PR DESCRIPTION
**Pull request by jrieken**
This is set dynamically whenever unhandled conflicts are detected. It unsets itself when merging is done so that the normal save-close-handler comes to play

https://github.com/microsoft/vscode/issues/152841

### CODE REVIEW

**Comment by jrieken** [comment]
fyi @bpasero

**Review by bpasero — COMMENTED** [review]
I wonder if we need to distinguish the case of closing the merge editor when the result is dirty vs. not dirty. Because I find it a bit hard to understand what "Continue with Conflicts" does depending on that state. Maybe when the file is actually dirty, it should include the word "Save" in the label (e.g. "Save & Continue with Conflicts").

Similar with "Discard Merge Changes", I understand that it restores the git merge markers but it also reverts changes that I did, so maybe that needs stronger emphasis to avoid frustrated users loosing their data.

cc @daviddossett

**Review by alexr00 — APPROVED** [review]

**Comment by bpasero** [comment]
For reference, Git shows this when you discard:

image

**Comment by jrieken** [comment]
@bpasero  https://github.com/microsoft/vscode/pull/155176 is out to tweak the message to save "Save & Continue..." when any input is dirty. Unsure about the discard tweaks - I am not keen on showing a modal after a modal. We either find something better than "Discard Merge Changes" or tweak the message "Do you want to continue with unhandled conflicts?"

**Pull request merged**
