### PR TITLE
Resize terminal direction

### LINKED ISSUE #204458: Resize terminal right shortcut broken
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: macOS 14.2.1

Reopening #204389 

Steps to Reproduce:

1. Open latest vscode, set terminal panel to right, focus on terminal, use the shortcut for resizing right
2. Terminal will resize left

Logs:

```txt
2024-02-06 08:33:17.541 [info] [KeybindingService]: | Resolving ctrl+meta+[ArrowLeft]
2024-02-06 08:33:17.541 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.resizePaneLeft, when: terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported, source: built-in.
2024-02-06 08:33:17.542 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,meta], code: ArrowLeft, keyCode: 37, key: ArrowLeft
2024-02-06 08:33:17.542 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,meta], code: ArrowLeft, keyCode: 15 ('LeftArrow')
2024-02-06 08:33:17.548 [info] [KeybindingService]: | Resolving ctrl+meta+[ArrowLeft]
2024-02-06 08:33:17.548 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.resizePaneLeft, when: terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported, source: built-in.
2024-02-06 08:33:17.549 [info] [KeybindingService]: + Invoking command workbench.action.terminal.resizePaneLeft.
2024-02-06 08:33:17.776 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:17.776 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:17.790 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:17.790 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:17.790 [info] [KeybindingService]: + Ignoring single modifier meta due to it being pressed together with other keys.
2024-02-06 08:33:17.958 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:17.959 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:17.960 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2024-02-06 08:33:17.960 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2024-02-06 08:33:17.960 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-02-06 08:33:17.985 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:17.986 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:17.986 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,meta], code: MetaLeft, keyCode: 91, key: Meta
2024-02-06 08:33:17.986 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,meta], code: MetaLeft, keyCode: 57 ('Meta')
2024-02-06 08:33:17.986 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-02-06 08:33:18.741 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:18.742 [info] [KeybindingService]: | Resolving ctrl+meta+[ArrowRight]
2024-02-06 08:33:18.742 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.resizePaneRight, when: terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported, source: built-in.
2024-02-06 08:33:18.742 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,meta], code: ArrowRight, keyCode: 39, key: ArrowRight
2024-02-06 08:33:18.742 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,meta], code: ArrowRight, keyCode: 17 ('RightArrow')
2024-02-06 08:33:18.742 [info] [KeybindingService]: | Resolving ctrl+meta+[ArrowRight]
2024-02-06 08:33:18.742 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.resizePaneRight, when: terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported, source: built-in.
2024-02-06 08:33:18.743 [info] [KeybindingService]: + Invoking command workbench.action.terminal.resizePaneRight.
2024-02-06 08:33:18.973 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:18.974 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:18.991 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-02-06 08:33:18.991 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-02-06 08:33:18.991 [info] [KeybindingService]: + Ignoring single modifier meta due to it being pressed together with other keys.
```

### PR DESCRIPTION
**Pull request by cchanche**
Fixes https://github.com/microsoft/vscode/issues/204458

Clashes a bit with the fix from https://github.com/microsoft/vscode/pull/200658 , which seems to have broken thing in the first place.

### CODE REVIEW

**Comment by cchanche** [comment]
So after reading about the difference between the Panel and the Sidebars from @Tyriar in https://github.com/microsoft/vscode/issues/204458#issuecomment-1939348733, I identified that terminals positioned in the primary sidebar (on the left) were having the same bug (resizing right had the same behaviour as resizing left).

The above commit accounts for that, and every terminal-position now seems to have a natural resizing behaviour.

> Code and seems to invert the resize directions in multiple places, and I couldn't figure out an elegant way to do it once with clear variable names. However, the following testing method ensures the proposed fix actually fixes the issue 👇 

The testing method is as follows :

- Open Code - OSS
- Open a terminal (`Terminal: Create New Terminal`)
- Open a split terminal (`Terminal: Split Terminal`)
- Make sure panel is bot (`View: Move Panel To Bottom`)

> The terminal should be visible, should be splitted (two actual terminals), be opened in the Panel (not in any sidebar), and the panel is positionned in the bottom

- Focus in the first terminal (the one on the left)
- [x] `Terminal: Resize Terminal Right` grows the split-terminals width to the right, panel keeps the same size
- [x] `Terminal: Resize Terminal Left` shrinks the split-terminals width to the left, panel keeps the same size
- [x] `Terminal: Resize Terminal Up` grows the panels height, split-terminals keep the same width
- [x] `Terminal: Resize Terminal Down` shrinks the panels height, split-terminals keep the same width

- Focus in the second terminal (the one on the right)
- [x] `Terminal: Resize Terminal Right` shrinks the split-terminals width to the right, panel keeps the same size
- [x] `Terminal: Resize Terminal Left` grows the split-terminals width to the left, panel keeps the same size
- [x] `Terminal: Resize Terminal Up` grows the panels height, split-terminals keep the same width
- [x] `Terminal: Resize Terminal Down` shrinks the panels height, split-terminals keep the same width

- Move panel to the right (`View: Move Panel Right`)
- [x] `Terminal: Resize Terminal Right` shrinks the panels width to the right, split-terminals keep the same height
- [x] `Terminal: Resize Terminal Left` grows the panels width, split-terminals keep the same height
- [x] `Terminal: Resize Terminal Up` grows the bottom-terminals height, shrinks the top-terminal height, and keeps the panels width
- [x] `Terminal: Resize Terminal Down` shrinks the bottom-terminals height, grows the top-terminal height, and keeps the panels width

- Move panel to the left (`View: Move Panel Left`)
- [x] Repeat the above steps, all resize directions should be natural (meaning panels or terminal edges should move in the direction stated by the command, and grow/shrink the corresponding pane)

- Now move the terminal to the secondary-sidebar (`Move Panel Views to the Secondary Sidebar` or drag & drop the terminal to the secondary (right) sidebar)
- [x] Repeat the above steps

- Now move the terminal tab from the secondary sidebar to the main sidebar on the right (couldn't find a command for this)
- [x] Repeat the above steps


- Run `Create new Terminal in the Editor Area to the Side`
- [ ] Repeat the above steps (⚠️ not sure about this, but `Terminal: Resize [ direction ]` commands don't act _natural_ here

**Comment by Tyriar** [comment]
Looks like the behavior of the primary side bar when on the right is inverse with this PR. In this state:

image

**Review by Tyriar — CHANGES_REQUESTED** [review]
Looks like the behavior of the primary side bar when on the right is inverse with this PR. In this state:

image

**Comment by cchanche** [comment]
> Looks like the behavior of the primary side bar when on the right is inverse with this PR. In this state:

Oh you are right, didn't know the sidebars could be repositioned too (not just the panel). I'll look into this, thank you !

**Comment by cchanche** [comment]
@microsoft-github-policy-service agree

**Comment by cchanche** [comment]
Alright so I think I've now covered every scenario.

> Add the `Move Sidebar Left` command to the above testing scenarios

Also, I moved a few things around so that it would all make more sense (at least to me) :

- If required, resizing the whole part (panel or sidebars) is now entirely under the responsibility of `TerminalGroup` class.

- Resizing individual terminals (when in split-mode, `children > 1`), when required, is still handled by the `SplitPaneContainer` class.

- Deciding whether to resize the whole part or just individual terminals within the part (`shouldResizePart`) is made using `_getPosition()` and `_getOrientation()` methods on the `TerminalGroup` class.

- For the resize to happen in the same direction as the one passed in the `resizePane()` method, I used a `shouldShrink` condition - since in the end it is all about what the new part's size should be.

**Review by Tyriar — APPROVED** [review]
Works great! Thanks for the follow up 👍

**Review by aeschli — APPROVED** [review]

**Pull request merged**
