### PR TITLE
Add prefix case for incrementFileName

### LINKED ISSUE #47014: Ability to increment prefix when duplicating file/folder
- VSCode Version: 1.22.0-insider
- OS Version: macOS 10.13.3

Currently VSCode increments suffix when copying a file. Copying `file.1.ext` makes `file.2.ext`. But there are cases when the `version` is specified in prefix not suffix, for instance when dealing with migrations we have files like `001-name.ext`, copying this results in creating a file named `001-name.1.ext` which is not the desired result. 

It would be great if VSCode could detect and increment the prefix if needed. It also requires minimal changes to `incrementFileName` method to add the functionality.

```ts
function incrementFileName(name: string, isFolder: boolean): string {

	// file.1.txt=>file.2.txt
	if (!isFolder && name.match(/(.*\.)(\d+)(\..*)$/)) {
		return name.replace(/(.*\.)(\d+)(\..*)$/, (match, g1?, g2?, g3?) => { return g1 + (parseInt(g2) + 1) + g3; });
	}

	// file.txt=>file.1.txt
	const lastIndexOfDot = name.lastIndexOf('.');
	if (!isFolder && lastIndexOfDot >= 0) {
		return strings.format('{0}.1{1}', name.substr(0, lastIndexOfDot), name.substr(lastIndexOfDot));
	}

	// folder.1=>folder.2
	if (isFolder && name.match(/(\d+)$/)) {
		return name.replace(/(\d+)$/, (match: string, ...groups: any[]) => { return String(parseInt(groups[0]) + 1); });
	}

	// file/folder=>file.1/folder.1
	return strings.format('{0}.1', name);
}
```

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Fixes https://github.com/Microsoft/vscode/issues/47014

CC: @isidorn

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
While this is naive way to add new case there are couple of problems with `incrementFileName` in general:

1. It's always using `.` as separator of version prefix/suffix, it would be good to support also other separators (like `-`, `app-1.js` should be incremented to `app-2.js`) 
2. Since it's just parsing version string to int we lose leading zeros (right now `app.0001.js` is incremented to `app.2.js` which is probably wrong behavior.)

**Comment by isidorn** [comment]
@Krzysztof-Cieslak thanks a lot for your PR.
I would be happy merging this in if we add some unit tests - they would increase my confidence and would use as a documentation how this beahves. Could you `export function incrementFileName`and add a `fileActions.test.ts` and test out that method.

**Comment by isidorn** [comment]
@Krzysztof-Cieslak yeah that would be great! Adding tests for those cases would also be awesome! Thanks

**Comment by Krzysztof-Cieslak** [comment]
This is ready for review.

**Comment by isidorn** [comment]
@Krzysztof-Cieslak thanks a lot! I love the tests, they give me confidence looking at all these regexes.
Merging in, thanks again!

**Pull request merged**
