### PR TITLE
Add filter to git hook (dev qol)

### PR DESCRIPTION
**Pull request by anthonydresser**
Currently the git hook takes every change you have and starts the filter from there and bypasses the "all" filter.

This changes it so the files from the git hook are filtered through "all" first.

I considered adding the filter at https://github.com/microsoft/vscode/blob/master/build/gulpfile.hygiene.js#L332 instead, but this seems like a more targeted fix.

### CODE REVIEW

**Comment by joaomoreno** [comment]
Actually, since one can also invoke `gulpfile.hygiene.js` as a standalone script, it would be better to have the fix up there instead, such that files [passed in such a way](https://github.com/microsoft/vscode/blob/100eead87e20813766245c9a0c785229349a87dc/build/gulpfile.hygiene.js#L438) also run through the `all` filter. What do you think?

**Comment by anthonydresser** [comment]
I was also thinking that, but I wasn't sure if there was a scenario where we would want to just hygiene exactly what the caller passed (i.e it was intentional to pass in a file not listed by the `all` filter). But I generally agree that it would make more sense just to filter everything that goes through hygiene.

**Comment by anthonydresser** [comment]
@joaomoreno I've updated it to filter everything passed into the hygiene task, let me know what you think.

**Comment by joaomoreno** [comment]
Excellent, thanks! :fireworks:

**Pull request merged**
