### PR TITLE
Go to next/previous breakpoint

### LINKED ISSUE #31806: Go to next/previous breakpoint
- VSCode Version: 1.14.2
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Set some breakpoints.
2. Fail to find shortcut to navigate between breakpoints without running the file.

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by beatriz**
Fixes #31806 

To decide which breakpoint was next, I went to the next on the same file. If there were any until the end of the file, it goes to the next file alphabetically (by path). If you have a better way, I will change it.

I believe that there is much logic that is duplicated on both `run()` methods but I wasn't sure where it was appropriate to put a method to abstract that. If you can help me with that, I can make it better.

There is also some commented code for the keyboard shortcuts, I was wondering if you have an idea of which would be best for that.

### CODE REVIEW

**Comment by isidorn** [comment]
@mbeatrizmagalhaes thank you for your PR, here's some feedback:
* we try to keep code concise and minimize duplication. These two actions basically do the same thing, can you please try to minimize dupilcaiton by having common super class
* there should be no default keybinding, so just delete that commented out code. Users can then assign any keybingind they want
* please remove debugger statments 
* should this action go between files, or only in one file? 
* do not treat specailly the case if the breakpoint is in a different file or in the same file. Simply first find the appropriate breakpoints and just open it via editorService (will be less code and more straightforward)

Once you do that I can provide more feedback.
Thanks again for the PR however I am not supper pumped up about it since not a lot of users requisted this feature.

**Comment by isidorn** [comment]
Closing since my feedback was not addresed. If it gets addressed I will gleadly reopen

**Comment by CTimmerman** [comment]
Multiple file navigation is preferable, which also matches VS Code 1.22:
"With this release, navigating errors and warnings via F8 (Go to Next Problem) takes all reported errors into account. Instead of looping inside just one file, it will take you to the next file with errors and back."

How would I test this patch?

**Comment by isidorn** [comment]
@CTimmerman I would recommend starting from scratch
https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Pull request closed without merging**
