### PR TITLE
workbench: Adds 'Show Code Version' Action

### LINKED ISSUE #40574: Have a global command which triggers the About dialog, or shows version information
- VSCode Version: 1.19.0
- OS Version: openSUSE Tumbleweed (Linux)

Steps to Reproduce:

1. press `Ctrl+Shift+P`
2. enter "version"
3. results in no entry, but should

As enhancement it would be nice if the show-all-command would have an entry to display the Visual Studio Code version (I know that I could pass the `--version` flag on the command-line).

Such a feature exists e.g. in Emacs, where it is possible to enter `M-x version` and get the current Emacs version displayed.

### PR DESCRIPTION
**Pull request by shobhitchittora**
Fixes: #40574

### CODE REVIEW

**Comment by shobhitchittora** [comment]
@joaomoreno Please review this.

**Comment by bpasero** [comment]
@shobhitchittora can I ask, why not simply show the about dialog that includes the version?

**Comment by shobhitchittora** [comment]
This is as per suggestion from @joaomoreno in the issue thread. Also I think here the intent is just show version number and not any additional info, thus adding as a Command.

**Comment by bpasero** [comment]
@shobhitchittora @joaomoreno I would prefer a command that simply shows the about dialog

**Comment by shobhitchittora** [comment]
@bpasero I found the below function which open the About dialog from menu bar items.
https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L1201
Is it possible to invoke this by registering a new Action in the registry?

**Comment by shobhitchittora** [comment]
Ping @joaomoreno . Any follow-ups on this?

**Comment by joaomoreno** [comment]
@shobhitchittora Thanks for the contribution! 🍻 

Sorry for not getting back earlier. I've renamed the command to `Help: About`. I've moved it to another contribution file. I've also changed the implementation to what @bpasero suggested.

**Comment by shobhitchittora** [comment]
Awesome ✌️

**Pull request merged**
