### PR TITLE
Add a widget for HTML select element

### PR DESCRIPTION
**Pull request by jsloyer**
Created a select element to replicate the html select.  This is to close on the PR I promised to open in #4472

### CODE REVIEW

**Comment by bpasero** [comment]
@jsloyer can I ask what the scenario for this is?

**Comment by jsloyer** [comment]
@bpasero We are building customer viewlets for an inhouse tool and thought it could be of use in the future

**Comment by bpasero** [comment]
I see. I am not thinking we would merge code into master that is not being used anywhere though. I hope that makes sense.

**Comment by bpasero** [comment]
@isidorn you as a client of select boxes (debug viewlet, output), maybe could comment if this change is useful to you?

**Comment by isidorn** [comment]
Might be useful, let me put it to May and I can try to adopt it in debt week. If it looks good I will merge it in, if it does not add nice value on top of what we have I will reject. Hope that makes sense.

**Comment by isidorn** [comment]
@jsloyer thanks for the PR, but as @bpasero pointed out we would not merge code in that is not being used.
We use native select elements in these two places:
https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/actionbar/actionbar.ts#L724
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L18

I do not see the exact value of replacing the native select with the contributed one in this PR for our use case. Though if I am missing something feel free to adopt it in those places and then we can potentially merge this PR in.

I appologize for the slow response, somehow this fell under my radar. Setting to June milestone

**Comment by isidorn** [comment]
Closing this PR for now, will reopen if @jsloyer provides more arguments and answers to the questions above.

**Pull request closed without merging**
