### PR TITLE
URL protocol: avoid unnecessary confirmation dialog on windows

### LINKED ISSUE #95670: Allow to opt-out of URL protocol confirmation dialog
Is there any way to open files by URL without confirmation?
It starts from 1.44 version and has no "Always open" checkbox.
When you need to open a lot of files with URL its not comfortable to click "Yes" every time.

- VSCode Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Open link "vscode://file/path"
2. See the confirmation dialog "An external application wants to open 'path' in Code. Do you want to open this file or folder?"

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by viperet**
This PR fixes #95670

Don't ask for confirmation when opening URL protocol links starting with a drive letter on Windows, because opening such links can't lead to a logged-in user password hash disclosure (see #95252). And Trusted Folders feature takes care of preventing arbitrary code execution using the tasks feature anyway.

So opening a link like `vscode://file/c:/folder/filename.txt` shouldn't trigger confirmation dialog in VSCode, but links like
`vscode://file/\<attacker-ip>\<share>\` will still trigger confirmation.

### CODE REVIEW

**Comment by joaomoreno** [comment]
No, this isn't right. It's still a security issue since third party extensions could easily run on activation on folders where the user didn't expect them to.

**Comment by viperet** [comment]
@joaomoreno wouldn't that be prevented by the Trusted Workspaces feature? And that dialog is only triggered on Windows, so Linux and Mac users are safe from that?

**Comment by joaomoreno** [comment]
I'll let @kieferrm comment on that.

**Comment by viperet** [comment]
@kieferrm can you help us?

**Comment by viperet** [comment]
@joaomoreno can you at least reopen this PR, and let @kieferrm judge if this is an acceptable solution?

**Comment by joaomoreno** [comment]
The PR won't get garbage collected, it can remain closed until we decide to go along with it.

**Pull request closed without merging**
