### PR TITLE
Do no install repo on Raspberry Pi OS

### LINKED ISSUE #118825: postinst script adds vscode repo on Raspberry Pi OS, although the packages are present in the existing repo
- VS Code Version: any
- OS Version: Raspberry Pi OS

Steps to Reproduce:

1. `apt install code`
2. postinst adds vscode repo and MS key although it's not required

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by XECDesign**
This PR makes sure the repo is no added when running on Raspberry Pi OS.

Additionally, the key is not added if it's not needed.

This PR fixes #118825

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Looks good, could you sign the CLA linked above?

**Review by joaomoreno — APPROVED** [review]
Pushed some smaller lipstick changes. @Tyriar I'll fire off a build with this so I can manually test it. Please give it a good look as well.

**Comment by joaomoreno** [comment]
@Tyriar Oh just missed your comment. Can you look at the changes once again, since there's a commit from me on top?

**Comment by joaomoreno** [comment]
Will hold off on firing a build, pending on the CLA signing.

**Comment by Tyriar** [comment]
@joaomoreno change looks good, the `>`/`mv` thing is equivalent I believe

**Comment by XECDesign** [comment]
Signed

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
