### PR TITLE
Remove extraneous "..." that breaks gulpfile

### PR DESCRIPTION
**Pull request by samvrlewis**
Not sure if I'm missing something but the "..." in the gulpfile breaks gulp for me. Removing it seems to allow me to build as normal.

### CODE REVIEW

**Comment by bpasero** [comment]
@joaomoreno fyi

**Comment by joaomoreno** [comment]
@samvrlewis What version of Node are you running on?

**Comment by samvrlewis** [comment]
I'm running v4.4.7 - do I need a newer version?

**Comment by joaomoreno** [comment]
[Yeah](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#installing-prerequisites) 👍

**Pull request closed without merging**
