### PR TITLE
Bump OpenTelemetry to 0.22.1

### PR DESCRIPTION
**Pull request by hdost**

### CODE REVIEW

**Review by connor4312 — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by hdost** [comment]
@TylerLeonhardt  what happened to the PR?

**Comment by hdost** [comment]
@connor4312  what happened to the PR?

**Comment by hdost** [comment]
@TylerLeonhardt any idea?

**Comment by TylerLeonhardt** [comment]
Not sure, @connor4312 would have to chime in.

**Comment by connor4312** [comment]
For security reasons we don't allow external PRs to update lockfiles (more a concern for yarn/npm than cargo). But in the CLI we also don't actually use opentelemetry any more so I'm just going to get rid of it today.

Appreciate the PR though!

**Pull request closed without merging**
