### PR TITLE
Enable `stash` only if there is an initial commit

### LINKED ISSUE #149547: Throw no commits yet error on `git stash`
When I don't have any commits, running `git stash` doesn't do anything, there are no prompts and it can be confusing. In the output, you can see the hint given by Git.
Xnip2022-05-15_02-45-50

### PR DESCRIPTION
**Pull request by liby**
This PR fixes #149547

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/149547#issuecomment-1126863867 for my suggestion to use a `when` clause instead.

**Comment by liby** [comment]
> See [#149547 (comment)](https://github.com/microsoft/vscode/issues/149547#issuecomment-1126863867) for my suggestion to use a `when` clause instead.

Okay, I'll refactor the code as you suggested later.

**Comment by liby** [comment]
@lszomoru TBR.
@gjsjohnmurray The current logic does not include judgments for `noUnstagedChanges` and `noStagedChanges`.
Since I see that [similar logic](https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L2601) is already in the code, I'm not sure I want to rewrite it.

**Comment by lszomoru** [comment]
@liby, apologies for not getting back to you on this until now. If there are no pending changes, we do not disable the stash command, and display an information notification. I would like this to be consistent with the existing experience, so I would just show a notification in case one cannot stash the changes as there are no existing commits.

**Comment by liby** [comment]
> @liby, apologies for not getting back to you on this until now. If there are no pending changes, we do not disable the stash command, and display an information notification. I would like this to be consistent with the existing experience, so I would just show a notification in case one cannot stash the changes as there are no existing commits.

Oh, I see what you mean. I understand your perspective on that. Would you mind looking into the other PR to see if there are any remaining issues? Could we possibly merge it now?

**Comment by lszomoru** [comment]
@liby, which is "the other pull request"? Could you please provide a link? Thanks!

**Comment by lszomoru** [comment]
Yep, it is on my list to be reviewed this milestone.

**Comment by lszomoru** [comment]
I was in that codebase so I have addressed this issue with https://github.com/microsoft/vscode/pull/169394.

**Pull request closed without merging**
