### PR TITLE
Enable quick fixes in the scm input

### LINKED ISSUE #159940: Enable quick fixes in SCM input
Related #159450 

For spelling issues, it would be useful to allow code actions in the scm input. We should not show the lightbulb in this case, just allow the default code action keybinding to be used when over an error

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #159940

Screen Shot 2022-09-02 at 11 28 51 AM

### CODE REVIEW

**Comment by lszomoru** [comment]
Thanks @mjbvz! This does fix part of the problem as now the quick fix menu appears but for some reason picking one of the available fixes does nothing - as in the value in the commit input does not get replaced. Not sure if you looked into that but if you do not know from the top of your head what the issue is, I can pick this up and further investigate.

**Comment by mjbvz** [comment]
@lszomoru Yes, I think there are two issues here:

1. For code actions that use commands, many existing extensions don't know how to work with the scm input. This causes the command to fail

2. For code actions that use a `WorkspaceEdit`, it's currently not possible to edit the scm input box. This is because the bulk edit service cannot resolve the text model used by the source control input:
 https://github.com/microsoft/vscode/blob/19631493d8b6afb46eab0791fae995ebe4668456/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L231


For point 2, would it make sense to register the scm input model as a normal text model?

**Comment by lszomoru** [comment]
@mjbvz, thanks for these findings. Let me chat with couple of folks and see what would be the best way to move this forward.

**Comment by mjbvz** [comment]
Superseded by #176699

**Pull request closed without merging**
