### PR TITLE
Remove notebook controller kind API proposal

### LINKED ISSUE #168535: Finalize or remove the notebookControllerKind API Proposal
From https://github.com/microsoft/vscode-jupyter/issues/7373

Let's figure out what to do with the `notebookControllerKind` API proposal. Jupyter is currently the only consumer of it

@rebornix @DonJayamanne Can you please let me know:

- If/how Jupyter is using this API today
- If, in your opinion, this API should finalized or not? Are there any know issues / gaps with it

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #168535

### CODE REVIEW

**Comment by rebornix** [comment]
Thanks @mjbvz, we also need to remove `notebookControllerKind` from the Jupyter extension, not sure if the Jupyter extension needs to be updated first.

**Comment by mjbvz** [comment]
I reviewed the jupyter code. Looks like there are two places where we use `kind`:

- Setting the kind: https://github.com/microsoft/vscode-jupyter/blob/8e55e3617f1f0f21524aef018abe62879e66be95/src/notebooks/controllers/vscodeNotebookController.ts#L318

- Showing a kernel picker: https://github.com/microsoft/vscode-jupyter/blob/e1152ca1329bc7dfb264dfdc19acd41073aef89d/src/notebooks/controllers/commands/serverConnectionControllerCommands.ts#L195


I think both should still work after this PR

@DonJayamanne Can you please take a look and confirm that we are good to remove the `kind` property?

**Comment by DonJayamanne** [comment]
Lets merge this PR once we have removed this in Jupyter extension https://github.com/microsoft/vscode-jupyter/pull/13068

**Review by DonJayamanne — DISMISSED** [review]

**Comment by mjbvz** [comment]
Should be good to merge now that we've removed the flat kernel picker

**Review by DonJayamanne — APPROVED** [review]

**Pull request merged**
