### PR TITLE
fixed settings sync has duplicate logins

### PR DESCRIPTION
**Pull request by Yash621**
This PR is with respect to issue #139323 

@TylerLeonhardt I have implemented all the suggested changes ,
please review them and let me know if any more changes are required.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Code looks good! Can you share a picture of what the end result looks like in the Account menu (in the bottom left)

**Comment by Yash621** [comment]
@TylerLeonhardt here is the ss.
Screenshot_2022-02-07_17-37-36 (1)

**Comment by TylerLeonhardt** [comment]
That's coming from the wrong window. You need to build and run VS Code out of sources for me to accept this PR. Here are steps:

https://github.com/microsoft/vscode/wiki/How-to-Contribute

Also remember what I said about Testing in the issue:

> Testing
>
> Testing this change is a little tricky because nothing inbox in the OSS version of vscode uses the Microsoft auth stuff, but what you can do is download my Microsoft To Do extension (using the "Download extension" button on the right side) and then install it in Code OSS using "Install from VSIX"

**Comment by Yash621** [comment]
@TylerLeonhardt  I am getting the following error.

```[Error: ENOENT: no such file or directory, open '/home/yash/vscode/out/vs/code/electron-main/main.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/yash/vscode/out/vs/code/electron-main/main.js',
  phase: 'loading',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ]
}
[3464:0207/233148.803814:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.```

when I run `./scripts/code.sh`

**Comment by TylerLeonhardt** [comment]
can you try running:

```
> yarn
> yarn run compile
> ./scripts/code.sh
```

**Comment by Yash621** [comment]
@TylerLeonhardt  this is how it looks when I  build and run VS Code out of sources
please review it and let me know if any changes are required :
Screenshot_2022-02-09_00-00-18 (1)
)

**Comment by TylerLeonhardt** [comment]
@Yash621 awesome! You got it! So I think the parens and then parens are not great... could we do:
```
Yash Goel - yg17381@gmail.com (Microsoft)
```
instead?

**Comment by Yash621** [comment]
@TylerLeonhardt I have updated the text style.


Screenshot_2022-02-09_00-24-31 (1)

**Comment by TylerLeonhardt** [comment]
I like it!

**Review by TylerLeonhardt — APPROVED** [review]
LGTM awesome work!

**Comment by Yash621** [comment]
@TylerLeonhardt thanks :)

**Comment by Yash621** [comment]
@TylerLeonhardt btw why didn't got merged ?

**Comment by TylerLeonhardt** [comment]
I just wanted to check one more thing. Looks good

**Comment by Yash621** [comment]
@TylerLeonhardt thanks :)

**Pull request merged**
