### PR TITLE
update php grammar

### PR DESCRIPTION
**Pull request by jens1o**
Maybe you can set up a webhook which updates the grammar after each push?

The latest updates are quite cool, because they tokenize the types inside documentation:
image
In this example, `string` is getting colorized, and this also contains some minor fixes.

### CODE REVIEW

**Comment by roblourens** [comment]
It looks like Martin took this version already, sorry for not getting to the PR sooner.

**Comment by jens1o** [comment]
Well, maybe you can repull the latest grammar, or when your pr got merged @roblourens ?

**Comment by roblourens** [comment]
Hoping for the PR to be merged this week :)

**Comment by jens1o** [comment]
@roblourens Is it considered to be in the recovery release then?

**Comment by roblourens** [comment]
I would probably put it in if I can get it before the end of the week. Otherwise, recovery release.

**Comment by jens1o** [comment]
Uh, not bad.

**Pull request closed without merging**
