### PR TITLE
chore: disable `git.mergeEditor` by default

### PR DESCRIPTION
**Pull request by JounQin**
related #157361

### CODE REVIEW

**Review by xdega — APPROVED** [review]
Looks like a pretty simple edit 👍🏻 
Thanks for doing this.

**Review by raveesh-me — APPROVED** [review]

**Comment by OtacilioN** [comment]
Just adding 1 cent of my opinion to this discussion. 

I think that 3-way editor is a great feature, but it has a significantly higher learning curve than previous experience, and on screens with fewer pixels available, the experience of viewing 3 simultaneous tabs can be quite confusing and cluttered.

Considering that, I believe 3way shouldn't be the default VsCode experience, being less inclusive than the previous one. Perhaps this option could be something configurable in an onboard installation or user welcome.

**Review by afa7789 — APPROVED** [review]

**Review by OtacilioN — APPROVED** [review]

**Review by lokinmodar — APPROVED** [review]
This is not a breaking change and should be the default property value.

**Review by Eitz — APPROVED** [review]

**Comment by JounQin** [comment]
@hediet

**Review by BlackthornYugen — APPROVED** [review]

**Review by rage-engage — APPROVED** [review]

**Review by MrOggy85 — APPROVED** [review]

**Comment by MrOggy85** [comment]
friendly ping @jrieken @bpasero

**Comment by hediet** [comment]
Thanks for your feedback!
In the last release, we added a button to make it really easy to switch to the inline merge UI:

Code_-_OSS_0bPJYaWLkG

We believe we can make the new merge UI less confusing for everyone. However, for that, we need your feedback! The new merge editor is available for four releases now, but only since we enabled it by default we got the feedback we need to make the new merge editor better.
We already adressed many pain points in the last release and will continue to do so with the next one.
For now, we have no plans to change the default back to the old experience, but we will continue to closely listen to your feedback.

Those who really dislike the new 3-way merge editor can opt-out of it completely by changing the `git.mergeEditor` setting. The inline experience will always be available.

**Pull request closed without merging**
