### PR TITLE
Fix #63625 - Git: Add setting to disable automatic refresh

### LINKED ISSUE #63625: Git: Add setting to disable automatic refresh
I find when I open file in the vscode in the explore viewlet, the git.exe will run in the background cause a little high CPU usage. From the git output, it seems that command 'git show' and 'git check-ignore -z --stdin' is running. But I don't want it run automatically.  

 Can I stop git auto-runnig in the background and set it to run when I switch to git viewlet? Thanks in advance.

### PR DESCRIPTION
**Pull request by skprabhanjan**
@joaomoreno , Here is a PR to fix #63625 .
Please review this , Thanks :)

### CODE REVIEW

**Comment by skprabhanjan** [comment]
@joaomoreno , This PR is open from a long time , can you please give some updates ?
I can at least close it if its not working for you.

**Comment by skprabhanjan** [comment]
@joaomoreno , Thanks!

**Comment by joaomoreno** [comment]
@skprabhanjan Sorry for the delay. I'm currently sitting on a [big backlog](https://github.com/microsoft/vscode/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+assignee%3Ajoaomoreno), so things are taking its time, but I'll get to it. Feel free to reopen.

**Comment by skprabhanjan** [comment]
@joaomoreno , Sorry for that and I understand it now , Thanks for getting back.
Will reopen it :)

**Comment by skprabhanjan** [comment]
@joaomoreno , i think this is already done , Since this PR was opened long time ago and now the changes here are no more valid , I am closing this , Thanks :)

**Pull request closed without merging**
