### PR TITLE
Report linux desktop-related env vars in issue reporter

### LINKED ISSUE #94388: Add some environment variables on issues reported from Linux to help identify distro and desktop environment
Advice from Canonical was to add these environment variables in issues reported from Linux.

```
DESKTOP_SESSION
XDG_SESSION_DESKTOP
XDG_CURRENT_DESKTOP
```

Example values:

```
DESKTOP_SESSION=ubuntu
XDG_SESSION_DESKTOP=ubuntu
XDG_CURRENT_DESKTOP=ubuntu:GNOME
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #94388

### CODE REVIEW

**Comment by Tyriar** [comment]
Haven't yet tested in Linux, queued a product build

**Review by dsseng — COMMENTED** [review]
Works almost right on Ubuntu 19.10
image
My `XDG_CURRENT_DESKTOP` is `ubuntu:GNOME` from the terminal (`echo $XDG_CURRENT_DESKTOP`), shown as `Unity` in VS Code

**Comment by Tyriar** [comment]
@sh7dm hmm weird, does your terminal profile/rc script set this somewhere?

**Comment by sh7dm** [comment]
I've seen this before in other apps, so no worries, probably some X.org configs or GDM3 set this value. It's not VS Code's fault for sure :smile:

**Review by RMacfarlane — APPROVED** [review]
Change looks good to me!

**Pull request merged**
