### PR TITLE
debug: use only js-debug auto attach, collapse settings

### LINKED ISSUE #732: The less settings the better
Refs: https://github.com/microsoft/vscode/issues/105771

I noticed that we introduced quite some settings for debug.javascript while most of this make perfect sense I just wanted to share my thoughts that:
* The less settings the better
* No need to intrdouce a setting only if a couple of users ask for it. Nobody will always be happy. 
* Less settings, less complexity
* We depracte the "use preview" settings once things go out of preview

I did not really review all of them but there are some quite obscure ones, like for example
"debug.javascript.warnOnLongPrediction"

Just my 2 cents.

### LINKED ISSUE #97087: Debug: Toggle Auto Attach should change user settings by default, not workspace settings
cc @connor4312 

I was confused why the auto attach status bar entry kept disappearing and I kept getting prompts to relaunch my terminals. This was happening because the toggle auto attach command saves a workspace setting, which I never want to commit so it always ends up getting cleared. Auto attach is something I want to toggle on briefly and then toggle off again and I would prefer use the command/keybinding rather than the mouse.

Related: https://github.com/microsoft/vscode/issues/53640

### LINKED ISSUE #105883: Make auto attach toggle workspace settings by default
> Are you setting auto attach to "on" in your user settings? Note that the Toggle Auto Attach command will persist in the workspace setting by default.

Oh my. I find this a bit confusing. So if I manualy first set it in user settings you will always write it there, otherwise you would do this in the workspace settings - making the whole repository dirty. I am not a fan of automatic writing in workspace settings...

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/105771#issuecomment-685118671_

### LINKED ISSUE #105963: Status bar toggle should switch between On, Smart, Off
Testing #105771

It would be nice if the status bar item to toggle auto-attach, would switch between On, Smart, Off
image

### PR DESCRIPTION
**Pull request by connor4312**
This PR removes the hook in node-debug's auto attach, and uses only
js-debug auto attach. As referenced in the linked issues, this involves
removing `debug.javascript.usePreviewAutoAttach` and collapsing
`debug.node.autoAttach` into `debug.javascript.autoAttachFilter`. The
latter option gains a new state: `disabled`. Since there's no runtime
cost to having auto attach around, there is now no distinct off versus
disabled state.

The status bar item and the `Debug: Toggle Auto Attach` command now
open a quickpick, which looks like this:

The current setting value is selected in the quickpick. If there is a
workspace setting for auto attach, the quickpick toggles the setting
there by default. Otherwise (as in the image) it will target the user
settings. The targeting is more explicit and defaults to the user
instead of the workspace, which should help reduce confusion (#97087).
Selecting the "scope change" item will reopen the quickpick in that
location.

Aside from the extra options for the `disabled` state in js-debug's
contributions, there's no changes required to it or its interaction
with debug-auto-launch.

Side note: I really wanted a separator between the states and the
scope change item, but this is not possible from an extension #74967.

Fixes https://github.com/microsoft/vscode/issues/105883
Fixes https://github.com/microsoft/vscode-js-debug/issues/732 (the rest of it)
Fixes https://github.com/microsoft/vscode/issues/105963
Fixes https://github.com/microsoft/vscode/issues/97087

### CODE REVIEW

**Comment by isidorn** [comment]
@connor4312 thanks for tackling this. It makes good sense to me, I like that we are getting rid of some settings, old code and simplifying the behavior a bit.

Minor feedback: should disable really hide it from the status bar? Since then it is a bit hard to disable and enable again? Hidding things from the status bar is an independent UX action which the user can do on her own -> context menu and hide

I am adding approved here, however for a code review I leave this up to @weinand since he did the original auto attach extension I believe.

**Review by isidorn — APPROVED** [review]

**Review by weinand — APPROVED** [review]
The changes look good to me.

**Comment by weinand** [comment]
@connor4312 I like the quickpick but this raises the question whether the "JavaScript Debug Terminal" becomes obsolete (I would hope so).

If yes, then we should remove the corresponding item from the "Welcome view" (in red) and add something along the lines of _"or automatically debug Node.js programs run from the command line (aka 'auto attach')"_ (in the green box).



"Creating a launch.json" should move down because it becomes more like a "last resort"

**Comment by isidorn** [comment]
Agree with @weinand comment, the dream scenario would be to merge this and the JavaScript debug terminal into one experince (I believe we have an issue for this)

**Comment by connor4312** [comment]
Yep, let's continue to discuss that in https://github.com/microsoft/vscode/issues/105852 🙂

**Comment by connor4312** [comment]
Following some feedback in standup, polish:



- made the state labels nicer and localized
- title the quickpick
- made the scope toggle a button (a folder or a globe to toggle to workspace or machine configuration)

**Pull request merged**
