### PR TITLE
underline for hover of all links

### LINKED ISSUE #149982: Support markdown in view welcome content
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: Windows 11

Steps to Reproduce:

1. In the below Live Share example . Welcome content is markdown. We would like to make the blue link text either bold or italic. But using ** doesn't take effect. It reads it as string . As a result output shows asterisk instead of a bold text. (tried with escape characters as well)  
image

### PR DESCRIPTION
**Pull request by isidorn**
This PR fixes https://github.com/microsoft/vscode/issues/149982

### CODE REVIEW

**Comment by bpasero** [comment]
@isidorn I would not expect `monaco-workbench` to appear in `platform`, if you want to set global CSS rules you can add it somewhere here:

https://github.com/microsoft/vscode/blob/5f3e9c120a4407de3e55465588ce788618526eb0/src/vs/workbench/browser/media/style.css#L102

Should probably check if this has unwanted side effects.

**Comment by isidorn** [comment]
@bpasero thanks, I will move it to `style.css` then.
I tested a bit - did not find bad side effects. But that is the reason why I would like to merge this at the start of the milestone - to catch the corner cases.

**Comment by misolori** [comment]
Does this actually solve the problem? I thought it was that underlines are needed regardless of hover (which I think is under discussion)? On hover, the cursor changes to the pointer, which should already be enough of an indication that it is clickable on hover.

**Comment by isidorn** [comment]
@misolori good points. I agree with you. And good example.
So based on that it seems like the underline should always be there.

Though I am still not convinced since a lot of other products - like GH do not do it.
So let's assign to backlog for now until we get clarity here.

**Comment by isidorn** [comment]
@misolori I have pinged @dantegagne, let's see what they are doing in VS.

**Comment by misolori** [comment]
@isidorn @DanteGagne do we have an update here? To me, it's still not clear if all links need to have an underline or whether we need to create a stronger distinction between product actions and hyperlinks

**Comment by misolori** [comment]
After talking with @setaskin, it appears that we just need to make the underline on hover as per the original bug:

> There must be underline or font change which should differentiate between links like "share with read only" and text around it when we hover on the links with mouse pointer

I can work on updating this PR, if needed, since @isidorn is out

**Review by miguelsolorio — APPROVED** [review]
Tested the PR and it seems like a simple enough change that shows the underline on hover for our links. Though it doesn't apply everywhere, certain areas have disabled it (we can follow up with each area owner afterwards), it does solve the original issue and helps unblock the Live Share team. @bpasero @joaomoreno if you both are good with these changes I would be happy to merge.

https://user-images.githubusercontent.com/35271042/179308692-ea34947f-92ef-4a88-b88b-71477254c9ad.mp4

**Comment by bpasero** [comment]
Works for me, I think there is 1 rule that then could be removed as being redundant:

https://github.com/microsoft/vscode/blob/78397428676e15782e253261358b0398c2a1149e/src/vs/workbench/browser/parts/editor/media/editorplaceholder.css#L40

**Review by joaomoreno — APPROVED** [review]

**Pull request merged**
