### PR TITLE
Introduce --force arg to install extension without prompts

### LINKED ISSUE #58434: CLI install extension command cannot run non-interactively
- VSCode Version: 1.27.1
- OS Version: MacOS 10.13.6

I have found that I am unable to reliably install extensions via the command line because of an update prompt that requires user interaction. A flag like `--yes` or `--force` or `--update` would be helpful in allowing the `--install-extension` command to run non-interactively.

Steps to Reproduce:

1. `code --install-extension yzhang.markdown-all-in-one` (or any extension that has a newer version than the one you have installed)
2. Prompt appears: `Extension 'yzhang.markdown-all-in-one' v1.6.0 is already installed, but a newer version 1.6.1 is available in the marketplace. Would you like to update? Yes(0) | No(1)`

Does this issue occur when all extensions are disabled?: Yes (CLI command)

### PR DESCRIPTION
**Pull request by sandy081**
Introduce --force arg to install extension without prompts

Fixes #58434

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]
LGTM

**Comment by bittner** [comment]
Shouldn't you also have updated [the related documentation](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions) and the CLI `--help` screen?

**Comment by bittner** [comment]
Also, it would be nice if this change were covered by a test. To make sure it remains functional.

**Comment by sandy081** [comment]
@bittner Added doc. Thanks for reminding. 

Would be great to have a test but it's hard for cli. Sorry.

**Pull request merged**
