### PR TITLE
experiment notebook scrollbar

### PR DESCRIPTION
**Pull request by rebornix**
Recording 2022-02-18 at 11 31 03

### CODE REVIEW

**Comment by bpasero** [comment]
@rebornix 

image

😞

**Comment by bpasero** [comment]
More specifically: https://github.com/microsoft/vscode/runs/5430222883?check_suite_focus=true#step:12:9313

**Comment by rebornix** [comment]
@bpasero thanks for the ping. The build was red all day so didn't rely on the checks. Pushed fixes for failing tests, will see if there is anything else failing the CI.

**Comment by bpasero** [comment]
Thanks!

**Pull request merged**
