### PR TITLE
Changing some for loops from "for (let i= ... i++)" to "for (let el o…

### PR DESCRIPTION
**Pull request by sdenel**
Changing some for loops from "for (let i= 0; i < list.length; i++)" to "for (let element of list)".

### CODE REVIEW

**Comment by sdenel** [comment]
This fork IS working, I do not understand why AppVeyor test failed. See my last test using AppVeyor: https://ci.appveyor.com/project/sdenel/vscode

**Comment by felixfbecker** [comment]
This should be for (const elem of coll) not for (let elem of coll) because the variable is declared for every iteration

**Comment by sdenel** [comment]
Hi Felix,
You are absolutely right. I realized it later on. May my proposal be accepted that I will anyway change more loops on another fork, and I suggest to change to const in the meantime.

* For information this loop writing transpiles to something like:
```
for(var i = 0; i < A.length; i++) { ... }
```
NOT to:
```
for(var i = 0, len = A.length; i < len; i++) { ... }
```
See this conversation: https://github.com/Microsoft/TypeScript/issues/6258
* Still, it appears the first snippet is slightly faster. See: http://stackoverflow.com/a/17995000/1795027 and this jsperf: http://jsperf.com/cache-length-no-cache

**Comment by joaomoreno** [comment]
@sdenel Sorry for picking this up so late. There are now merge conflicts, do you mind cleaning those up?

**Comment by joaomoreno** [comment]
Actually, we've discussed this in the team and decided to close it, as the `for-of` syntax doesn't really offer inherent advantages besides slight readability improvements and we don't really have guidelines for these sort of things.

**Pull request closed without merging**
