### PR TITLE
Support negated .gitignore rules.

### PR DESCRIPTION
**Pull request by markspanbroek**
Fixes issues #69035 and #38112.

When invoking `git check-ignore` it returns those paths that match against a .gitignore pattern, whether it's a negated pattern or not. This change ensures that negated pattern matches do not mark a file as ignored.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@jrieken Did you try this when implementing the ignore markers?

**Comment by jrieken** [comment]
> @jrieken Did you try this when implementing the ignore markers?

Nope, but @markspanbroek seems to know this better, the doc actually says this

**Comment by jrieken** [comment]
This actually isn't true on my system (using git 2.17) @markspanbroek Is this a recent fix/feature in git?

Screenshot 2019-05-24 at 12 26 11

**Comment by markspanbroek** [comment]
@jrieken it requires the -v flag, I also added this to line 1159 of repository.ts.

**Comment by jrieken** [comment]
> @jrieken it requires the -v flag, I also added this to line 1159 of repository.ts.

Thanks - didn't see and know that. The power of open source! @joaomoreno I am 👍 for this

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
This will be in next insiders and stable - Thanks for all the help!

**Pull request merged**
