### PR TITLE
Add preview and help text for "Go to line" during file quick open (fix #186143)

### LINKED ISSUE #186143: File quick open should allow to trigger "Go to line"
In quick open today, you can drill into symbols from the file picker such as:

Recording 2023-06-26 at 11 48 46

It would be nice if typing `:` with a line/column pattern would do the same.

//cc @Tyriar @TylerLeonhardt

### PR DESCRIPTION
**Pull request by hsfzxjy**
This PR adds preview and help text when "Go to line" is triggered by `<file>:<line>,<column>` command pattern. 

Fixes #186143 

Screenshot:

https://github.com/microsoft/vscode/assets/4702188/f25e45c2-27b8-4fe5-a83f-36c37de74417

### CODE REVIEW

**Comment by bpasero** [comment]
This is pretty cool 👏 . I personally though am not 100% convinced to show the info message for when goto line mode is active. Since the editor updates in the background to move to the location you type, I think that is enough to indicate back to the user?

**Comment by hsfzxjy** [comment]
> I personally though am not 100% convinced to show the info message for when goto line mode is active.

@bpasero I think that will be more consistent with the behavior of `:<line>` which also displays a message below.

Generally, I think these two ways of indicating users both come with pros and cons and deserve discussing:

1. **Displaying a message on the picker.** _Pros_: more resource-saving, more consistent; _Cons_: less intuitive.
2. **Updating editors and locations at the background.** _Pros_: Intuitive; _Cons_: may be expensive when files being previewed are large or at network locations.

Maybe we can choose to introduce configuration to opt-out one of them?

**Comment by TylerLeonhardt** [comment]
Does your code get invoked every time a user types a query? I would expect that it would only get invoked when there is a `:` similar to how symbols works (it looks for an `@`)

**Comment by hsfzxjy** [comment]
@TylerLeonhardt Currently if there's no  `:`, the code will still queue a request yet the handler is doing trivial job. I will change it to a more efficient way.

**Comment by hsfzxjy** [comment]
> Does your code get invoked every time a user types a query? I would expect that it would only get invoked when there is a `:` similar to how symbols works (it looks for an `@`)

I've fix this in the newest push.

**Comment by TylerLeonhardt** [comment]
Thanks for your patience. I really would love to get this feature in as I think it provides some really nice value. One thing I am hesitating with is that the implementation you've done does work, but it doesn't take advantage of the fact that the EditorSymbol feature (aka the `@` at the end of the query) handles a lot of the decoration today. 

https://github.com/microsoft/vscode/blob/fe020f236900b8a688f8379d6b2bf79ea95a1cd5/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L251-L272
https://github.com/microsoft/vscode/blob/fe020f236900b8a688f8379d6b2bf79ea95a1cd5/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L63-L66

I wish there was more code reuse there since both scenarios are just decorating the editor. We'd get even more value out of generalizing as @andreamah is also working towards implementing `filename.ts%query` for text search quick access.

Can you try to align with the Editor Symbol stuff and reuse some stuff there? Maybe:
* `IEditorSymbolAnythingQuickPickItem` becomes the general type that you use in "Go To"
* You use (and modify if need be) `decorateAndRevealSymbolRange`

I'm not convinced the message is needed and think aligning with what we do for symbols is the right way forward... at least for now.

**Comment by hsfzxjy** [comment]
@TylerLeonhardt Hi! 

I appreciate your idea to introduce more code reuse. However, after my careful consideration, I think the current implementation for gotoSymbol is not general enough to reuse, and therefore I rework a large part of `AnythingQuickAccessProvider` and introduce a new preview manager. 

The preview manager is very generic and it bases the implementation of gotoLine preview. Moreover, it can be used for implementing other previews, such as the `filename.ts%query` you've mentioned.

**Comment by bpasero** [comment]
As part of our 2024 issue cleanup I am going ahead and close this PR, as we are unlikely to accept it in its current form. Thanks for the contribution though, really appreciate it 🙏

**Pull request closed without merging**
