### PR TITLE
Invert TokenizationTextModelPart/BracketPairsImpl relationship

### LINKED ISSUE #163231: Why is bracket BracketPairsTextModelPart passed into TokenizationTextModelPart?
Part of #161622 - trying to defer bracket pairs evaluation so it doesn't impact input latency.

It looks like it only does things when events fire:

https://github.com/microsoft/vscode/blob/e3a3693b5003a3fb23fb9973062c4652e662654c/src/vs/editor/common/model/textModel.ts#L323-L332

Instead of `TokenizationTextModelPart` using it, can `BracketPairsTextModelPart` use `TokenizationTextModelPart`? ie.

```ts
this._bracketPairs = this._register(new BracketPairsTextModelPart(this, this._tokenizationTextModelPart, this._languageConfigurationService));
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #163231

### CODE REVIEW

**Review by hediet — CHANGES_REQUESTED** [review]
That's what I did initially, but then Alex did [this](https://github.com/microsoft/vscode/commit/43cf81a93d1e099a79c93adbafc0e6518cbe0402). I think it is because the order in which event handler are executed is unpredictable.

**Comment by Tyriar** [comment]
@hediet pulling it the event->handler calls into the TextModel like in https://github.com/microsoft/vscode/commit/43cf81a93d1e099a79c93adbafc0e6518cbe0402 would be good enough for what I'm after as well. Though I'm trying to move the handlers to be executed much later in a successive task. Do you have any insight as to why the bracket pairs stuff would need to be updated immediately and not deferred ~<100ms later?

**Comment by hediet** [comment]
> and not deferred ~<100ms later? Currently it happens between the user presses a key and when the change shows up in the editor

You would notice a delayed bracket colorization immediately, especially as the decoration wouldn't move when a character is inserted before.

The code is optimized to do a minimal amount of work.

**Comment by Tyriar** [comment]
> The code is optimized to do a minimal amount of work.

Sure it's optimized but it can still end up being ~1-2ms on lower end devices (measuring quickly now). If we're shooting for at least 60fps, those numbers are using up to ~12.5% of the budget. Example:

image

**Comment by Tyriar** [comment]
> You would notice a delayed bracket colorization immediately, especially as the decoration wouldn't move when a character is inserted before.
> It is important that the bracket pair AST updates before rendering, as the text would be rendered twice otherwise.

So the impact would be the bracket outline appears potentially on whitespace and the color of the bracket would flash a different color when you type?

**Comment by Tyriar** [comment]
I tested this and I think the only impact is new brackets show as white or deleted brackets may show wrong colors briefly as the token is attached to the character rather than an index of a character. Doesn't seem like that would impact the UX much?

**Comment by Tyriar** [comment]
Also it's actually worse than I thought as the document is parsed 2 times when tokenization is cheap as it triggers on tokenization and content change:

image

**Comment by Tyriar** [comment]
After our chat it doesn't look like we'll be able to defer this to after keypress, so closing this off as this change was so I could experiment with doing that conveniently.

**Pull request closed without merging**
