### PR TITLE
Improve UX for deprecated settings

### PR DESCRIPTION
**Pull request by JacksonKearl**
This PR enables modified deprecated settings to show in the new settings editor and adds additional warning text for deprecated settings in both the old editor and new. Deprecated settings now show up in old settings editor search. 

Full disclosure: this removes the existing behavior of deprecated settings not showing up at all in old editor, as the old and new share a model, and the old basically just renders the model as is. This meant that when I added deprecated settings to the model in order for the new editor to conditionally render them, the old editor would render them too. 

Edit: we previously had localized deprecation messages as well, so there isnt a positive spin like I previously said. Oh well. @roblourens if you have an idea for how to filter the old settings view, I'm all ears. It is just 5 at this point, so I personally think just having the deprecation message show up is fine.

### CODE REVIEW

**Comment by roblourens** [comment]
I think it's ok for them to show up in the old search. I think the extra lines of deprecation warning might be overkill. Do all the deprecation messages have enough context to understand the situation?

**Comment by roblourens** [comment]
I feel like deprecated settings need some styling or something in addition to just an extra line on the description. I guess we can't gray them out because we are at the color contrast limit. Maybe the deprecation message could be in blockquote `> ` style?

**Comment by roblourens** [comment]
Apparently blockquotes still have to be styled in the settings editor.

**Comment by JacksonKearl** [comment]
Yeah I think we can remove the surrounding text, I put that there because I thought that the deprecation messages were not localized. 

The messages are along the lines of "this setting has been deprecated in favor of `...`". I think we could possibly add some general information to that (i.e. "this setting show not be used and will be removed in a future release" or similar). But we could also get away with not doing that.

**Comment by JacksonKearl** [comment]
Looking at it with fresh eyes I was able to get the deprecated removed from search results pretty easily. Now they'll show up with a deprecation message if you actually look in the whole list, but not in any searches.

**Comment by roblourens** [comment]
I think that new change will remove it from search results in the new editor too, right? Is that what we want or should it also show up in search results if it's configured? I have no idea tbh.

**Comment by JacksonKearl** [comment]
Ahhh, looks like you're right. These are too darn coupled.

**Comment by roblourens** [comment]
You are right and I have another task to re work search a bit. Maybe we just stick with it for now though.

**Comment by roblourens** [comment]
I think we do need some styling to draw attention to the fact that the message is a warning, not just a sentence in the description. But we can check this in as is and play with it later and get Miguel's opinion.

**Review by roblourens — APPROVED** [review]
Feel free to merge whenever you're ready

**Comment by JacksonKearl** [comment]
@roblourens are you aware of the bug where extensions settings sometimes don't show up in the new editor? I thought it was may changes that caused it but looks like its happening in Insiders too

**Comment by roblourens** [comment]
I thought I fixed that. Is this just after startup when the settings editor is persisted as open?

**Pull request merged**
