### PR TITLE
Revert hiding some notebook toolbars

### PR DESCRIPTION
**Pull request by roblourens**
We need to rerender the menu when thsi setting changes, because it determines which actionViewItem is used. cc @jrieken @rebornix 

This reverts commit 517448a4a7708199916d9b726c47c22988cc7058.

### CODE REVIEW

**Review by rebornix — DISMISSED** [review]

**Comment by jrieken** [comment]
Sorry for the breakage and thanks for the fix

> We need to rerender the menu when thsi setting changes,

Is that something that you can express with a config-context key? Each config-value is exposed as context key named `config.<settings_name>`

**Comment by roblourens** [comment]
Hm, we already have two registrations in that menu, based on that context key, so the label can change:

https://github.com/microsoft/vscode/blob/4c41daaa261c576e8c1e8b1ac1d47fe40820659c/src/vs/workbench/contrib/notebook/browser/controller/insertCellActions.ts#L224-L251

I guess I'm not sure why it wasn't being rerendered before

**Comment by roblourens** [comment]
This is a real pain to debug, but I guess this is just because the setting is not officially registered, it's an undocumented setting. @rebornix should we just decide right now whether to officially register this setting (can still be "experimental") or delete it?

**Comment by roblourens** [comment]
In notebook standup we decided that supporting normal hiding doesn't really work in notebooks for most toolbars. They don't feel like normal menus, if we want to customize these things it should work differently. I reverted it for every toolbar except the title toolbar where it works quite well. Reverting the IW toolbar also fixed the issue we saw with the run button always showing inside a `...` fyi @rebornix, there must be something unusual on that one.

**Review by rebornix — APPROVED** [review]

**Pull request merged**
