### PR TITLE
Increase max file size for file comparison

### PR DESCRIPTION
**Pull request by LEGOL2**
As vs code is often used in professional environment, it's usual to compare very big log files for debug purposes. Current limit is too small and I often end up with `Cannot compare files because one file is too large.` error. Development machines usually have a lot of RAM installed and often have SSD drives, so bigger limit should not be a problem.

This PR fixes #
Increases limit of file size for file comparison feature.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
This particular constant is used for multiple purposes. One purpose is the diffing, but others include: syncing to the extension host, computing links, etc. At least on the extension host, many extensions are not prepared to deal with such large files. I therefore suggest that diffing itself is improved in a (local) way that is independent of the other usages.

**Comment by LEGOL2** [comment]
@alexdima is my PR ok?

**Comment by LEGOL2** [comment]
@alexdima @sbatten @rebornix Could you please review my change? This PR is already quite old, maybe this feature has been already implemented?

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
