### PR TITLE
Notifications icon polish

### LINKED ISSUE #44594: Icons in notifications are used differently to the panel
VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:17:53.785Z)
OS version: Linux x64 4.13.0-36-generic

---

#44319

image

- `x` icon
  - In the panel it means close/minimize (non-destructive)
  - In the notification center it means delete (destructive)
- bin icon
  - In the panel it means kill/delete (destructive)
- `v` icon
  - In the panel it means restore (non-destructive)
  - In the notification center header it means close/minimize (non-destructive)
  - In individual notifications it means expand (destructive) - this is the *opposite* of how it's used in the panel
- `^` icon
  - In the panel it means maximize
  - In individual notification it means minimize

### LINKED ISSUE #78857: New notification icons are not very readable
- VSCode Version: 1.37
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Generate some notifications.

Does this issue occur when all extensions are disabled?: Yes

Result:

The new notifications icons are so thin that they are barely readable, see '!' and 'i' on the screenshot (on Macbook Pro 13'' Retina display). This is especially problematic if you have less than perfect vision.

image

Compare e.g. to these icons on Github: the borders are thin but the exclamation mark is bolder and a lot more readable.

image

### PR DESCRIPTION
**Pull request by miguelsolorio**
Fixes #44594 #78857

gif

- Increases the notification icon (info/warning/error) from 16px to 18px
- Updated the info/warning `!` to be a little wider (fixes #78857)
- Updates the header icons to better match our icons in other areas
  - `clear-all` will dismiss all notifications
  - `close` will close the notification panel
- Only shows notification actions on hover

cc @Tyriar

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
@misolori in general looks good to me. Two things:
* if there are no notifications I would expect the "Clear All" action to be disabled
image
* showing actions only on hover means the actions in notifications that are not focused are not keyboard accessible anymore. Have multiple notifications and click on the first, then try to tab using keyboard to the action to configure or remove the notification below, it does not work anymore

**Comment by misolori** [comment]
@bpasero I believe those are two existing issues we have today. We don't currently disable the clear all notifications when there aren't any, and if you have a long notification title, that also is not keyboard accessible when they are hidden.

I agree that these should be fixed, though this PR is just polishing the UI elements.

**Comment by bpasero** [comment]
@misolori I can tab to the actions in other notifications just fine today.

**Comment by misolori** [comment]
@bpasero spent some time trying to figure out how to disabled the clear all actions and wasn't successful. If you have any ideas on how to accomplish this let me know or feel free to push to the branch.

I also removed only showing actions on hover as there wasn't a way to make this focusable. I also applied this to notifications with long text as in Stable this currently isn't focusable.

**Comment by bpasero** [comment]
I added:
* disablement of the clear action when no notifications are there
* restored the hiding of toolbar actions because I like how light the notifications look without it. keyboard accessibility is still preserved, you just have to use arrow up/down keys, forgot about that

Cool 👍

**Comment by misolori** [comment]
@bpasero 👏 thanks!

**Pull request merged**
