### PR TITLE
Fixes for issue #7509

### PR DESCRIPTION
**Pull request by ghost**
Originally, we were only selecting iframes, which were in webviews. However, this made selecting webviews inaccessible because we were not selecting the iframes. As a result, I modified the selection method to select both iframes and webviews and put those tags in a single collection to enumerate through.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@pi1024e Did you maybe reference the wrong issue?

@mjbvz Is this maybe related to our discussion last month? Could this fix it?

**Comment by joaomoreno** [comment]
Is this the same as https://github.com/microsoft/vscode/pull/77121?

**Comment by pi1024e** [comment]
Yes this is! I just realized, except you forgot to check for iframe and web view again in another section of code, so I did that for better state management. I just now have to wait for approval!

**Comment by joaomoreno** [comment]
@mjbvz Can you also check this one out?

**Pull request closed without merging**
