### PR TITLE
Fixed vertical alignment

### LINKED ISSUE #124382: Quick pick vertical alignment is off
Notice how the icons seem aligned to the bottom, there is also a bunch of extra padding on the bottom.

image

### PR DESCRIPTION
**Pull request by yash112-lang**
@TylerLeonhardt please take a look at the changes😀.

Before - 

image

After - 

image

This PR fixes #124382

### CODE REVIEW

**Comment by yash112-lang** [comment]
Hey @TylerLeonhardt, why this one CI check got failed/canceled, `Prevent yarn.lock changes in PRs`. Are there any mistakes? I'm new to open source that's why can you help me with this?

**Comment by yash112-lang** [comment]
@Tyriar, @TylerLeonhardt, @rzhao271, is there any mistake in the code? because it is not merged till now. I'm new to this project so can you help me with this?

**Comment by yash112-lang** [comment]
Thanks, @TylerLeonhardt for the suggestions, I had done the changes that you suggested, I had also checked for the: 

> Progress in the quick pick
> 
> * Example: Install the Remote Repositories extension and Open a GitHub Repository you get this progress bar (see the purple bar that runs across the quick pick if this were animated):

and it is working fine. Is any other improvement in the code needed?

**Review by TylerLeonhardt — APPROVED** [review]
LGTM

**Comment by TylerLeonhardt** [comment]
Thank you for your contribution!

**Pull request merged**
