### PR TITLE
Dynamic composite bar 

### PR DESCRIPTION
**Pull request by sandy081**
- Add to composite bar when new composite is added
- Sequential order for in-built viewlets

Required for https://github.com/Microsoft/vscode/issues/43645

### CODE REVIEW

**Comment by isidorn** [comment]
@sandy081 thanks for the PR. This makes sense.
What I do not understand is why composites which get registered later are added as not `pinned` to the `CompositeBar`?  
Why do you need that option and distinction?

**Comment by sandy081** [comment]
If you always pin it, then it will override the existing pinned viewlet when refreshed

**Comment by sandy081** [comment]
I will update the PR to handle following correctly

- When a viewlet is added for the first time, it has to be pinned but do not show
  - Pin it by its order
  - Do not show
- When a viewlet is added after refresh (was already added before)
  - Pin it at the position it was before 
  - Show if it was shown before
- When a viewlet is removed after refresh but was there before, then pinned should not have it.

Hope I cover all cases.

**Comment by isidorn** [comment]
> If you always pin it, then it will override the existing pinned viewlet when refreshed.

Can you please clarify this with an example. Just so we are on the same page.
Multiple viewlets can be pinned at the same time. If a user adds Azure viewlet and it is pinned that just means it is shown in the activity bar and this should not affect any other viewlet afaik.

**Comment by sandy081** [comment]
I think pinning is not the issue. It is about showing the viewlet. When adding a viewlet, it pins and shows automatically. This is overriding the viewlet that is currently shown (after refresh).

**Comment by isidorn** [comment]
Ok. Yeah compositeBar should support to show a new pinned viewlet without it being the active one.

**Comment by sandy081** [comment]
@isidorn Updated the PR with following changes

- Store all current composites with pinned state and retain the composites states
- Compute pinned composites from loaded composite states and  current composites
- Pin the added composite at correct location
- Parameter in add api to activate the added composite
- Store states on shutdown

**Comment by isidorn** [comment]
@sandy081 I took a look at the PR and previsouly we were storing a list of pinned composite ids.
A now we store a list of objects, where each object has an id and if it is pinned. So basically the difference is that each composite bar also stores unpinned composite ids. Why is that?
Can't the owner of the composite bar store that so we do not change what we store in the composite bar?

**Comment by isidorn** [comment]
Ok this makes sense. I tried it out and nothing seems broken.
Did you test it out with contributed viewlets? To be sure I would try out the following cases:
* search moved to panel and back to activity bar
* screen resized such that not all viewlets can be fit - make sure that the active one is still shown always
* You can rearrange and hide viewlets

**Comment by sandy081** [comment]
I tried with the contributed viewlets and some of the test cases you mentioned. Will test all cases and confirm.

**Comment by isidorn** [comment]
@sandy081 great, then feel free to merge this in. A  test plan item would also be good.

**Comment by sandy081** [comment]
Thanks and will have the testing part of activity groups contributions.

**Pull request merged**
