### PR TITLE
refactor: merge same namespace declaration

### PR DESCRIPTION
**Pull request by Cecil0o0**
export same two namespace in a module seems to be mis-understanding while contributors reading this module, this pr would like to solve this.

### CODE REVIEW

**Comment by Cecil0o0** [comment]
@microsoft-github-policy-service agree

**Comment by Cecil0o0** [comment]
@meganrogge hi, could you have a look for this pr? ^_^

I used es-module-lexer to scan this module in vscode codebase, and it will emit an error for duplicate namespace, while typescript could merge same namespace by it's compiler, not to emit error.

In my opinion, it could be better that merge namespaces manually because of gaining better readability for this module, meanwhile, this pr will reduce possibility of emitting errors by some lexers like es-module-lexer.

**Comment by meganrogge** [comment]
Hi @Cecil0o0 I'm not sure I understand the problem or what this PR does. Could you pls clarify in the description?

**Comment by Cecil0o0** [comment]
> Hi @Cecil0o0 I'm not sure I understand the problem or what this PR does. Could you pls clarify in the description?

Hi @meganrogge,

image

Here is background: I wrote a program to transform module code from vscode codebase, after I executed the program, got a error above.

when I saw this error, I opened the file with vscode, found two same namespace export which is `Schemas`. The first impression is wired about the code block. This pr solve the wired first impression when looking at this module.

**Review by meganrogge — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]

**Comment by Cecil0o0** [comment]
@lramos15 Hi ^_^, could you please tell me why `Monaco Editor checks` action and `Prevent yarn.lock changes in RPs` action not run automatically, because these two actions would be expected, waiting for status to be reported. Is that something else I should do for that?

**Pull request merged**
