### PR TITLE
Consolidate codicon files to vs/base/parts/codicon

### PR DESCRIPTION
**Pull request by miguelsolorio**
cc @eamodio @jrieken 

I still need to resolve these import issues:

image

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

**Review by eamodio — APPROVED** [review]

**Comment by misolori** [comment]
Had to revert this due to the icons not being bundled properly in the build. Will create another branch with these changes.

**Comment by bpasero** [comment]
I will push a few of the changes in `tslint.json` independently as they are unrelated to supporting codicons (rather fixes to our rules in general).

**Comment by jrieken** [comment]
👎 for using `/base/parts` - that something that shouldn't exist - top level folder should only have "target" folders like common, browser, note etc.  Why not use base/brower?

**Comment by bpasero** [comment]
@jrieken we have `base/parts` for a long time to group things that belong together, e.g. `quickopen` has a `common` `browser` and `test` part. 

image

**Comment by jrieken** [comment]
Only few people know that. @joaomoreno and I once concluded that it's unwanted but I guess it needs some discussion. Anyways, for codicons which is always /browser/ I see no reason to have it there.

**Comment by bpasero** [comment]
@jrieken I am fine if we move everything into one place, e.g. `src/vs/base/browser/codicon/**`. Currently we seem to have `src/vs/base/common/codicon.ts` and `src/vs/base/browser/ui/codiconLabel/codiconLabel.ts` which I am not sure why we need both.

**Comment by eamodio** [comment]
I added the `base` version because of layering issues to separate out just the raw regex replacement and escaping vs anything tied to UI.

**Comment by misolori** [comment]
I'll move everything to `src/vs/base/browser/codicon/**` then

**Comment by misolori** [comment]
Should this live in `src/vs/base/browser/ui/codicon/` then?

**Comment by bpasero** [comment]
@misolori I would assume that less changes are needed if things move into `src/vs/base/browser/ui/codicon/`. However it is true that we cannot depend on `browser` from `common` ever, so if something needs `codicon` on the `common` layer then we cannot move it to `browser`.

**Pull request merged**
