### PR TITLE
Fix #41080

### LINKED ISSUE #41080: Uncaught TypeError: Cannot read property 'uri' of null
Issue Id: <b>09b2db67-ec5b-f02f-7f98-25f92608977c</b><br /><br />*Versions* <br />- 1.19.1<br />-  816be6780ca8bd0ab80314e11478c48c70d09383<br />-  951f5a20fc820e32a65ca05bb87af86f65027470<br />*Stack* <br />TypeError: Cannot read property 'uri' of null<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L143:56 (uri)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L143:56 (uri))<br />[/vs/workbench/parts/extensions/browser/extensionEditor.ts#L325:16 (repository)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/browser/extensionEditor.ts#L325:16 (repository))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L505:16 (setInput)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L505:16 (setInput))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L395:28 (doSetInput)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L395:28 (doSetInput))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L348:14 (doOpenEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L348:14 (doOpenEditor))<br />[/vs/workbench/services/editor/common/editorService.ts#L206:25 (openEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/editor/common/editorService.ts#L206:25 (openEditor))<br />[/vs/workbench/services/editor/common/editorService.ts#L163:15 (doOpenEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/editor/common/editorService.ts#L163:15 (doOpenEditor))<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L427:28 (openEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L427:28 (openEditor))<br />[/vs/workbench/parts/extensions/browser/extensionsActions.ts#L92:34 (open)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/browser/extensionsActions.ts#L92:34 (open))<br />[/vs/base/common/actions.ts#L226:31 (run)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/actions.ts#L226:31 (run))<br />

### PR DESCRIPTION
**Pull request by KamilSzot**

### CODE REVIEW

**Comment by wangpung12** [comment]
Good

**Comment by sandy081** [comment]
@KamilSzot It is not mandatory to have a repository, so `gallery.assets.repository` can be null. Hence I would put null check [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L145) similar to others.

**Comment by KamilSzot** [comment]
There's already code nearby that generates repository with empty urls if repo urls can't be found in `version.properties`:  https://github.com/KamilSzot/vscode/blob/e2115a55c22089fa384b332e5b0d8011b587b29f/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L219

My fix just does the same for the case when there are no `version.properties` at all.

O course you can just put in the check, that was my first instinct as well. I just wasn't sure if that was the only place in the whole codebase that depended on `repository` not being `null` and I saw that in the case when repo url can't be found, the existing code returns object with empty urls rather than `null`.

**Comment by sandy081** [comment]
Ok makes sense.

**Pull request merged**
