### PR TITLE
Skip quick picker when there is only one task to select from

### PR DESCRIPTION
**Pull request by sylveon**
I find it particularly annoying when it asks me what to select from when there's only one choice. This skips the quick picker and proceeds directly when there is only one task to choose from.

### CODE REVIEW

**Comment by dbaeumer** [comment]
I had this a long time ago but then users complained that they want to have a consistent behavior independent of 1 or n tasks :-). So if we add this back it has to go behind a setting.

**Comment by sylveon** [comment]
@dbaeumer Sure. Should this be enabled or disabled by default?

**Comment by dbaeumer** [comment]
To not break anyone it should be off by default.

**Comment by dbaeumer** [comment]
@sylveon One minor thing. The setting should be in the task namespace not in the quickPick. However there might be a problem since tasks is overloaded with tasks.json. Have you tried `tasks.skipPicker` ?

**Comment by sylveon** [comment]
@dbaeumer I added a `tasks` configuration namespace, but it effectively seems affected by `tasks.json`.

Using `task` instead of `tasks` as lazy fix would work.

**Comment by dbaeumer** [comment]
Sorry for the long delay. Using task as a workaround makes perfect sense to me.

**Comment by sylveon** [comment]
Done

**Comment by dbaeumer** [comment]
@sylveon: I looked at the PR yesterday and I noticed that the tasks are now resolved outside of the quick pick. I see why this is happening however this results in the fact that the user has no progress feedback as long as the promise is resolved. This might not be so problematic for terminate and restart, however it will be for run since this on first execution might take some seconds. I need to think about what we can do here. Merging this is as is will make users unhappy where task resolving takes some time.

**Comment by GeorgeWL** [comment]
Came from #51699 

Might it make sense then, to solve the issue with quick picker if it's used for run, to add a settings option for run that's separate from the restart/terminate settings option?

Until can find a better solution that is.

**Comment by isidorn** [comment]
Not for this milestone, pushing out to August

**Comment by sylveon** [comment]
Perhaps it's possible to do something like this. If the promise in the quick pick resolves without the user picking something, and there's only one option that results out of it, pick it. But if there's multiple, don't.

**Comment by GeorgeWL** [comment]
@sylveon feels hacky, and against the way other stuff works, where if the user doesn't take a second action it cancels it.

**Comment by alexandrudima** [comment]
Cleaning up milestone

**Comment by markfinlabs** [comment]
Just hit this.

I expected ```workbench.action.tasks.restartTask``` shortcut to work the same as my existing ```workbench.action.tasks.runTask``` shortcut, i.e. use my task argument to directly restart or run.

Very surprised to see the picker....

**Comment by dbaeumer** [comment]
@alexr00 can I loop you in here?

**Comment by alexr00** [comment]
@markfinlabs, it sounds like you are seeing a different issue. Yes please do open a new issue for it and I will take a look.

**Comment by alexr00** [comment]
@sylveon thanks for working on this change! I have pushed a different version of it that doesn't resolve the tasks outside of the quick pick. The name of the setting is `task.quickOpen.skip`

**Pull request closed without merging**
