### PR TITLE
Quiet Light theme diff syntax highlighting

### LINKED ISSUE #106707: [themes] Diff highlighting breaks with Quiet Light theme
- VSCode Version: 1.49.0
- OS Version: Windows 10  2004

Steps to Reproduce:

1. Change VS Code to the built-in Quiet Light theme
2. Save the text below as `test.diff` and open it with VS Code

```diff
--- a.txt	2020-09-14 19:23:42.699158000 -0600
+++ b.txt	2020-09-14 19:23:41.501314200 -0600
@@ -1 +1 @@
-test
+hello world
```

3. Observe that with Quiet Light theme, syntax highlighting is not working: 
image

Does this issue occur when all extensions are disabled?: Yes

Tested with all extensions disabled, also with the insider build, still have this issue. Note that with other themes, the syntax highlighting is working. Looks like this is an issue with the Quiet Light theme. 
image

### PR DESCRIPTION
**Pull request by alisonnoyes**
This PR fixes #106707.  Added colors for diff deletions, insertions, and changes in the Quiet Light theme.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
Hi @alisonnoyes and @aeschli , thank you for looking into this (I'm the reporter of the issue, thanks for making the PR, I didn't have time), I think there are a few other scopes that need override (header and the `+` and `-` punctuations). For reference, this is what I have in my personal `settings.json`: 

```
  "editor.tokenColorCustomizations": {
    "[Quiet Light]": {
      "textMateRules": [
        {
          "name": "Diff: Header (Color From Solarized Light)",
          "scope": [
            "meta.diff.header",
            "meta.diff.header.from-file",
            "meta.diff.header.to-file",
            "meta.diff.range",
            "punctuation.definition.from-file.diff",
            "punctuation.definition.range.diff",
            "punctuation.definition.to-file.diff"
          ],
          "settings": {
            "fontStyle": "italic",
            "foreground": "#268bd2"
          }
        },
        {
          "name": "Diff: Only In (Color From Solarized Light)",
          "scope": "meta.diff.only-in",
          "settings": {
            "foreground": "#268bd2"
          }
        },
        {
          "name": "Diff: Deleted (Color From Solarized Light)",
          "scope": [
            "markup.deleted",
            "punctuation.definition.deleted.diff"
          ],
          "settings": {
            "foreground": "#dc322f"
          }
        },
        {
          "name": "Diff: Inserted (Color From Solarized Light)",
          "scope": [
            "markup.inserted",
            "punctuation.definition.inserted.diff"
          ],
          "settings": {
            "foreground": "#219186"
          }
        }
      ]
    }
  },
```

**Comment by misolori** [comment]
I'd just add `punctuation.definition.from-file.diff` and `punctuation.definition.to-file.diff` and use one of the existing blue colors like `#4B69C6`:

image

Sample:

```json
		{
			"name": "Extra: Diff From",
			"scope": ["meta.diff.header.from-file", "punctuation.definition.from-file.diff"],
			"settings": {
				"foreground": "#4B69C6"
			}
		},
		{
			"name": "Extra: Diff To",
			"scope": ["meta.diff.header.to-file", "punctuation.definition.to-file.diff"],
			"settings": {
				"foreground": "#4B69C6"
			}
		},
```

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
I'd just add `punctuation.definition.from-file.diff` and `punctuation.definition.to-file.diff` and use one of the existing blue colors like `#4B69C6`:

image

Sample:

```json
		{
			"name": "Extra: Diff From",
			"scope": ["meta.diff.header.from-file", "punctuation.definition.from-file.diff"],
			"settings": {
				"foreground": "#4B69C6"
			}
		},
		{
			"name": "Extra: Diff To",
			"scope": ["meta.diff.header.to-file", "punctuation.definition.to-file.diff"],
			"settings": {
				"foreground": "#4B69C6"
			}
		},
```

Besides that this looks good 👍

**Comment by aeschli** [comment]
Pushed the PR and I will also commit the changes as suggested by @misolori

**Pull request merged**
