### PR TITLE
Localize ipynb extension commands

### LINKED ISSUE #172246: Proper localization for ipynb extension
Currently some commands are not localized https://github.com/microsoft/vscode/blob/70e818f356d0b12663d5bbd40eca075a5c75cb6e/extensions/ipynb/package.json#L45-L58

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #172246

### CODE REVIEW

**Review by TylerLeonhardt — DISMISSED** [review]
These look good but there's also:
`"displayName": "Markdown it ipynb Cell Attachment renderer",`
in the notebook renderer section

**Comment by DonJayamanne** [comment]
@TylerLeonhardt thanks, updated, please re-review

**Review by amunger — DISMISSED** [review]

**Review by TylerLeonhardt — DISMISSED** [review]

**Comment by gjsjohnmurray** [comment]
Some of the command texts don't conform to capitalization convention, so look odd in the picker alongside others.

**Comment by TylerLeonhardt** [comment]
Good call out @gjsjohnmurray. We usually prefer [Title case](https://en.wikipedia.org/wiki/Title_case?wprov=sfti1) for command titles.

**Review by TylerLeonhardt — APPROVED** [review]

**Pull request merged**
