### PR TITLE
Allow multiple languages in settings key

### LINKED ISSUE #51935: Multiple languages specific editor settings
We definitely need the ability to set those for multiple languages at once.

Something like:
```
// Once for all
"[cpp, c]":{
    "editor.formatOnSave": true
}
```

Instead of:
```
// Once for C++
"[cpp]":{
    "editor.formatOnSave": true
},

// And once for C
"[c]":{
    "editor.formatOnSave": true
}
```

### PR DESCRIPTION
**Pull request by CEbbinghaus**
This PR fixes #51935. Allowing for a single definition for multiple different languages is going to eliminate unnecessary config duplication.

```json
{
    "[javascript, typescript]": {
       "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}
```
vs
```json
{
    "[javascript]": {
       "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
       "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}
```

Unfortunately, I haven't been able to do extensive testing due to having troubles getting a dev environment up and running but the unit tests in place right now are still succeeding. 

A few items that still need doing:

- [ ] Update Schema definition for settings.json to accommodate these changes
- [ ] Add additional unit tests for these new possibilities. 
- [ ] Possibly provide a warning if the same value is specified twice, once in a joined definition and once in a separate one.

Any feedback is welcome 🙂

### CODE REVIEW

**Comment by Wouterr0** [comment]
I know nothing about the inner workings of VScode and I was only looking at this PR because it seams like an awesome feature. But isn't the variable `overrideIdentifiesr` at line 159 and 161 of configurationModels.ts a misspelling? Anyway, great work 👍

**Comment by sandy081** [comment]
Thanks for your interest in supporting this feature and providing a PR. I see that it is not completely implemented and there are some open questions like how to support writing into multiple languages key programatically. I assume it is not as trivial as changing a string type to string array type and adopting it every where. 

I am planning to support this feature in this milestone (November 2021). Since it is not simple it might be time taking to get this feature contributed. So, I would like to implement this by myself so that things will move faster. 

Thanks for understanding.

**Comment by CEbbinghaus** [comment]
> Thanks for your interest in supporting this feature and providing a PR. I see that it is not completely implemented and there are some open questions like how to support writing into multiple languages key programatically. I assume it is not as trivial as changing a string type to string array type and adopting it every where.
> 
> I am planning to support this feature in this milestone (November 2021). Since it is not simple it might be time taking to get this feature contributed. ~So, I would like to implement this by myself so that things will move faster.~

Sorry i have been a little inactive. Between crunch at work and very little free time in general it has had to take a back seat. some of the changes have already been added and the unit test was added although my logic was flawed and I decided to figure out what the ideal implementation would be. Since this has taken too long I understand if you want to just take over from here. However I am still very keen to keep working on it even if its not full time. 

Hoping I can help a little more than I already have

**Comment by sandy081** [comment]
Thanks for offering help. I have already pushed some changes/refactorings which make it easy to implement this feature. I will be finishing the implementation today with tests and also taking care of most of the other gaps. Since changes are going orthogonal, I would like to close this PR. Again, thanks for the interest and help.

**Pull request closed without merging**
