### PR TITLE
fix #45346

### LINKED ISSUE #45346: Can't resize terminal panel up and down
- VSCode Version: 1.21.0
- OS Version: Windows 10 Pro, Version 1709, Build 16299.248

Steps to Reproduce:

1. Ctrl + J (opens terminal)
2. Ctrl + \ (splits terminal)
3. Ctrl + Shift + Up Arrow (Noting happens)

Does this issue occur when all extensions are disabled?: Yes

I can size left and right just not up or down.  I can use Alt + Right or left to switch panes as well. The only issue is Resize Up and Down.

### PR DESCRIPTION
**Pull request by khoitd1997**
This PR fixes #45346 by adding support for resizing up/down to horizontal terminal and left/right for vertical terminal.

### CODE REVIEW

**Comment by khoitd1997** [comment]
I should also note that to fully use this PR, #72274 need to be resolved as the keybinding conflicts

**Comment by khoitd1997** [comment]
@Tyriar Ping

**Comment by Tyriar** [comment]
@khoitd1997 sorry about the delay, did you disable maintainer pushed to your branch?

**Review by Tyriar — APPROVED** [review]
Looks good, since I can't edit the PR branch I'll make some minor clean up tweaks after merge.

**Pull request merged**
