### PR TITLE
disable initializing user data

### PR DESCRIPTION
**Pull request by sandy081**

### CODE REVIEW

**Review by alexr00 — APPROVED** [review]
Most deleted lines this year 👏

**Comment by jeanp413** [comment]
@sandy081 could you explain a little bit the reason behind this change?
Right now I found two things that regressed:
- Theme sync is broken for built-in themes,
  - Before, if the synced theme was a built-in theme then it was properly set before the workbench show up in the browser, now there's a flashing between the default theme and the synced theme, this flashing was already present for marketplace themes but I find that expected as it has to download it first.
- Extension values marked as sync with `setKeysForSync`
  - Before, synced values were properly set on workbench start, now my extension (installed as built-in) is broken as the synced values are not available on extension activation

**Comment by sandy081** [comment]
@jeanp413 This feature to initialise workbench with user's synced data is meant to support Codespaces special requirement to initialise a codespace with user's synced data, when it is first opened in a browser. Since they dropped this requirement and no longer need this, we removed this feature. 

Our recommendation always is to let user to turn on settings sync manually just like in VS Code. This will be the story going forward.

Regarding the regressions you mentioned:

> Theme sync is broken for built-in themes,
Before, if the synced theme was a built-in theme then it was properly set before the workbench show up in the browser, now there's a flashing between the default theme and the synced theme, this flashing was already present for marketplace themes but I find that expected as it has to download it first.

Since we do not initialise synced data, I assume web bits will always load with the default built in theme without any flickering. If this is not the case, can you please provide steps to repro?

> Extension values marked as sync with setKeysForSync
Before, synced values were properly set on workbench start, now my extension (installed as built-in) is broken as the synced values are not available on extension activation

Also, same reasoning as again. Workbench will start with default data and no user data is pulled from settings sync server. So, it is expected that all extensions will not have any synced data. If this is not the case, can you please provide steps to repro?

Thanks

**Comment by jeanp413** [comment]
Well, being vscode open-source I think it would be nice to consider that codespaces is not the only client using this features, and I really like that my workspaces start with my settings already synced instead of enabling it manually every time :disappointed: 

Is this a final decision or would it be possible to reconsider :pray:

**Comment by sandy081** [comment]
@jeanp413 Sorry about it and as of now this is the plan. Will update in case if there are any updates. Thanks for understanding.

**Pull request merged**
