### PR TITLE
change default  ouputWindowToggleScroll   when  outputWindow  is  focused and clicked  ,  because  the  scroll lock button is changed each time the output window is opened

### PR DESCRIPTION
**Pull request by Super1Windcloud**
图片

### CODE REVIEW

**Comment by Super1Windcloud** [comment]
@microsoft-github-policy-service agree [company="{your company}"]

**Comment by sandy081** [comment]
Can you please file and explain the issue you are the trying to address here?

**Comment by Super1Windcloud** [comment]
# you can try  to run some code  on  output  window , and when  you  click the    output windows , the  locked  icon  will be  3changed ,   This will cause the output window not to automatically scroll to the bottom after the next run

**Comment by sandy081** [comment]
This happens when smart scrolling is enabled in output. You can disable this using setting `output.smartScroll.enabled`

**Pull request closed without merging**
