### PR TITLE
Config Tests - Check Filename

### LINKED ISSUE #44957: Config.test.ts - Tests Failing
### Problem
The following tests are failing for me:
[watching]( https://github.com/Microsoft/vscode/blob/99413dc9c6b813f82a916c365ca94bcdd303b4bf/src/vs/base/test/node/config.test.ts#L101)
[watching also works when file created later](https://github.com/Microsoft/vscode/blob/99413dc9c6b813f82a916c365ca94bcdd303b4bf/src/vs/base/test/node/config.test.ts#L129)

### Digging Deeper
The config file name bubbling up from _node_ [fs_event_wrap](https://github.com/nodejs/node/blob/c05c73a634e3a88372e32e500f462851add7ea66/src/fs_event_wrap.cc#L46) to [fs](https://github.com/nodejs/node/blob/c05c73a634e3a88372e32e500f462851add7ea66/lib/fs.js#L1316) to _vscode_ [extfs](https://github.com/Microsoft/vscode/blob/99413dc9c6b813f82a916c365ca94bcdd303b4bf/src/vs/base/node/extfs.ts#L624) to [ConfigWatcher](https://github.com/Microsoft/vscode/blob/99413dc9c6b813f82a916c365ca94bcdd303b4bf/src/vs/base/node/config.ts#L154) is incorrect.
filename

As a result,  ConfigWatcher returns early in the [onConfigFileChange](https://github.com/Microsoft/vscode/blob/99413dc9c6b813f82a916c365ca94bcdd303b4bf/src/vs/base/node/config.ts#L169) event.
onfilechange

Is anyone else seeing this?

### PR DESCRIPTION
**Pull request by captainrdubb**
fixes  #44957 ConfigWatcher.onFileChange event incorrectly returns early when comparing filename of actual changed file to expected config filename

### CODE REVIEW

**Comment by bpasero** [comment]
@captainrdubb just fyi the tests are not failing for me and also not for the CI builds, so I am not sure why you see test failures. Which OS are you on?

**Comment by captainrdubb** [comment]
@bpasero Windows 10 Pro N 10.0.16299 version 1709

**Comment by captainrdubb** [comment]
@bpasero Windows 10 Pro N 10.0.16299 version 1709

Not sure why machine is special <g-emoji class="g-emoji" alias="disappointed" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f61e.png" ios-version="6.0">😞</g-emoji>. At least this may provide an additional safeguard against the behavior of an external dependency, <g-emoji class="g-emoji" alias="sun_with_face" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f31e.png" ios-version="6.0">🌞</g-emoji>

**Comment by bpasero** [comment]
@captainrdubb I do not understand this fix, sorry. The intent of that check is to ignore any file events that happen to files other than the config file to watch for. node.js will send the filename of the file that changes as argument and we do a simple triple-equals check on that name. 

Are you saying you are getting different filenames even though the change is in the config file?

**Comment by captainrdubb** [comment]
@bpasero No problem. Take a look at this issue #44957. There is an assumption that node is returning the last fragment of the changed file's uri. Unfortunately, we can't assume that. It's possible that node does not always properly parse the uri and returns more than it should. For example, it returns "abc435d/config.json" instead of "config.json". A triple equals will fail, because that assumes that node is perfect. As a solution we can just ensure that the final part of the filename returned is correct, even if it includes part of the parent directory name and a delimiter. I think that it's safe to assume that the correct path is monitored, so there is no need to worry about the entire filename returned, as long as the last part of the filename exactly matches what we expect it to be.

**Comment by bpasero** [comment]
@captainrdubb I do not see how node.js would return `776728/config.json`, what folder is `776728`? And even if there are more segments returned in the event, we always want the top level `config.json` and never any children because we are only interested in `config.json`?

**Comment by captainrdubb** [comment]
@bpasero 
>I do not see how node.js would return 776728/config.json, what folder is 776728

So the [watching](https://github.com/Microsoft/vscode/blob/8c37fa806d3044f5a3eeb2edea276c6aa66e56bc/src/vs/base/test/node/config.test.ts#L101) test calls the [testFile](https://github.com/Microsoft/vscode/blob/8c37fa806d3044f5a3eeb2edea276c6aa66e56bc/src/vs/base/test/node/config.test.ts#L21) function, where a new directory is made beneath the temp directory. In my file system it looks like ""C:\Users\<part of my username>~1\AppData\Local\Temp\vsctests\900c9432-394f-4996-92d6-053f018728ee\config\900c9432-394f-4996-92d6-053f018728ee". Then, the name of the changed file returned by node is "f018728ee\config.json". "f018728ee" is the last part of the UUID.

>(compare with their docs: . . . there is no mention of the event returning anything but the filename)?

Yeah, I looked at the node docs as well, hoping to see some indicator. There is the following section.
fs_caveats

I must confess, fs.watch does not give a warm fuzzy feeling haha. Maybe the issue lies within ReadDirectoryChangesW.

A slightly unrelated issue, if the watching test fails, then cleanup never happens and my temp directory gets junky.

**Comment by captainrdubb** [comment]
accidentally closed this.

**Comment by bpasero** [comment]
@captainrdubb that sounds more like a bug in node.js to me, can you reproduce if you create a litle node.js script where you watch on such a path and then change a file within to see what you get back in the callback?

**Comment by captainrdubb** [comment]
@bpasero I created a node script, it returned a normal filename. 

Debugging the config tests in Chrome leads me to the function below in fs.js. 
image
I know this._handle is FSEvent from fs_event_wrap.cc and that the funky file name is emitted from there. Unfortunately, I'm using Windows, so I'm having a hard time figuring out how to get the C++ stack trace or even a core dump.

**Comment by bpasero** [comment]
@captainrdubb make sure you try with node.js `7.9.0`, that is the one we ship in VS Code.

**Comment by captainrdubb** [comment]
@bpasero
# Eureka!!
caveat: i did not look into Node c++ land, but I proved it out.

The function os.temp returns a path with a search term for the user name, example "C:\Users\<FIRST SIX CHARS OF NAME>~1\AppData\Local\Temp\vsctests\3e0663bd-b6b8-4a60-9f06-8214abd07b8e\config\3e0663bd-b6b8-4a60-9f06-8214abd07b8e\config.json"

Windows api returns file name with _actual_ user name in it, example,
"C:\\Users\\<actual 18 char user name>\\AppData\\Local\\Temp\\vsctests\\3e0663bd-b6b8-4a60-9f06-8214abd07b8e\\config\\3e0663bd-b6b8-4a60-9f06-8214abd07b8e"

The difference between 8 chars (including ~1) and 18 chars equals 10, "4abd07b8e\\"!

Node is saving an index so that it can quickly determine the part of the uri that is the file name, but the path passed in by vscode is a different length than the path returned by Windows.

**Comment by bpasero** [comment]
@captainrdubb nice, so since you cannot reproduce in latest node.js I assume they fixed it meanwhile?

**Comment by captainrdubb** [comment]
@bpasero oh no, I did reproduce it. I'll edit my last comment.

**Comment by bpasero** [comment]
@captainrdubb great, can you file this as a bug to https://github.com/nodejs/node, would be interesting what they have to say.

**Comment by captainrdubb** [comment]
@bpasero Will do.

I discovered that it's not a search term, but a short name replacement created by the Windows file system for a name that is too long.
> Both FAT and NTFS use the Unicode character set for their names, which contain several forbidden characters that MS-DOS cannot read in any file name. To generate a short MS-DOS-readable file name for a file, Windows 2000 deletes all of these characters from the long file name and removes any spaces. Because an MS-DOS-readable file name can have only one period, Windows 2000 also removes all extra periods from the file name. Next, Windows 2000 truncates the file name, if necessary, to six characters and appends a tilde ( ~ ) and a number. For example, each nonduplicate file name is appended with ~1 . Duplicate file names end with ~2 , then ~3 , and so on. After the file names are truncated, the file name extensions are truncated to three or fewer characters. Finally, when displaying file names at the command line, Windows 2000 translates all characters in the file name and extension to uppercase. [full article](https://technet.microsoft.com/en-us/library/cc976806.aspx)

**Comment by bpasero** [comment]
@captainrdubb thanks, given this behaviour I do not see how to best fix this because we do not know which file was changed, unless we somehow get the absolute path, would you agree?

**Comment by captainrdubb** [comment]
@bpasero  To me there really isn't a gray area. We are already taking for granted that we are monitoring the right directory. As it stands, we already assume that the directory is correct, only checking the file name itself. Now, we discover that the file name returned isn't perfect, including part of the parent directory in the name. In this case, isn't it safe to discard the parent directory part of the returned file name, since we're assuming it's in the right directory in the first place? If discarding the cruft is acceptable, then we're back where we started, just checking the file name itself. We do not need to deem the FSWatcher change event completely unreliable. In my mind we're not getting the "wrong" file name. We're just getting a little more than we asked for, so we can say, "no thanks" and keep the part that we want.

**Comment by bpasero** [comment]
@captainrdubb your change is a bit crazy, I would suggest the following:
* use [`basename`](https://nodejs.org/docs/v7.9.0/api/path.html#path_path_basename_path_ext) from node.js to get the true basename of the file instead of running a complicated RegEx
* add a isWindows check to only do that if we are running on Windows
* add a comment pointing to your node.js issue and add a `TODO@Ben` so that I can track this in the future

**Comment by captainrdubb** [comment]
@bpasero  From what I understand, you would prefer I modify the test instead of the function?

**Comment by captainrdubb** [comment]
@bpasero  Are you suggesting that I change the test, instead of the function and drop the vcstests folder in the homedir, or should I figure out a way to still place the test folder in the temp dir?

**Comment by bpasero** [comment]
@captainrdubb no worries, I can look into that change.

**Pull request closed without merging**
