### PR TITLE
Multiple line support in Find Widget

### PR DESCRIPTION
**Pull request by rebornix**
Adding multiple line find and replace support in Find Widget. Our original implementation of the Find Widget takes quite a few assumptions of keybindings to use, Find Widget height and the query being single line. That means adding multiple line support may affect Find Widgets

* Keybindings (we are introducing one more keybindings for inserting new lines in the input box)
* Rendering (our current implementation of visibility change, fade in/out, etc takes the fixed height of Find Widget into account)
* Accessibility should still work fine
* We have quite a few features assuming that the find query is single line and we need to think about how they can work properly with multiple line support enabled.

Below verifications should pass before the PR gets merged

- [x] Keybindings
  - [x] We use `ctrl+enter` to insert new line based on the feedback we received
  - [x] `shift+enter` should be disabled on `textarea` as it's used to go to previous search result
  - [x] Replace All uses `ctrl+enter` on Windows
- [x] Rendering
  - [x] The height of the find widget should be updated when a new line is inserted
  - [x] Find Widget fade in/out should work seamlessly when the height of the Find Widget is changed
  - [x] Find Widget options/actions (toggleWord, regex, next/previous result, etc) should be positioned at the same place as before 
  - [x] When users resize the editor or the find widget by dragging the left side sash, the textarea width should be updated properly the same way as before
  - [x] textarea should have a max height and scrolling inside it should not trigger scrolling in the editor
  - [x] We show an empty view zone at the top of the editor to avoid find widget covering the editor context. The chances of overlapping increases and we should also improve the experience here.
- [x] Features
  - [x] History navigation should work only when we are pressing arrow keys when the cursor is at the end or beginning of the textarea
  - [x] Find and replace should honor editor line feed.
  - [x] Seed search string from selection may now take multiple line selection into account 
    - seed search string from selection only works when the selection is single line, when the setting is turned on.
  - [x] Auto find in selection may now take multiple line selection into account
    - since we will not seed search string if the selection is multiple line, auto find in selection works the same as before
- [x] Verify Monaco Standalone

---

image

### CODE REVIEW

**Review by MJ-Mohith — COMMENTED** [review]
This feature looks interesting. It will really help. 
I have a concern when the number of lines increases in find widget. Is there any limits imposed on number of lines? What will be the case if the user inputs more than 80 lines, in such case how does the new feature impact the look of the find widget?

**Comment by rebornix** [comment]
@MJ-Mohith thanks for brining them up, good feedback.

> Is there any limits imposed on number of lines

The max height of an input box will be limited to 6 of visible lines (wrapped lines), which is similar to Search Viewlet and SCM commit message box.

**Comment by MJ-Mohith** [comment]
@rebornix  thats a good feature. I have a minor concern how the multi-line find and replace will work with following case:

Find :: 
this 
is
a
sample
text

Replace:
this
is
a

text

what will be the result, if we have an empty new line in between our text in a replace box

**Comment by rebornix** [comment]
@MJ-Mohith the result would be 

```
this
is
a

text
```

**Comment by MJ-Mohith** [comment]
@rebornix :: Thanks and Good work.

**Pull request merged**
