### PR TITLE
Add interface for adding value selection in QuickPick for extension API

### LINKED ISSUE #233274: API to select character range of QuickPick input text value for VSCode extensions
Same as https://github.com/microsoft/vscode/issues/111944 but for VS Code extensions (It's not obvious to me if original issue is the literal duplicate and was closed due to the inactivity, or if it was meant to be used only inside VS Code codebase (at least I see `valueSelection` attribute available in the corresponding file for VS Code))

https://github.com/microsoft/vscode/blob/a38d2d0569759927ec8aa525ec4d486a2be5661d/src/vs/platform/quickinput/common/quickInput.ts#L586-L589

Copying the description from the original description:

Currently there seem to be two text selection modes for `QuickPick` values:

If `quickPick.value` is set _before_ `quickPick.show()` is called, then the value (text) will be selected when the quick pick becomes visible, and typing a character will replace the input text unless the selection is changed first.
If `quickPick.value` is set _after_ `quickPick.show()` is called, then the caret will be placed at the end of the text value, ready for more characters to be typed at the end.
These selection modes seem to be undocumented.

It would be useful to be able to select a range of text rather than all or nothing.This would allow more powerful text input control by extensions. For example, it could be used to facilitate commands with multiple auto-completed arguments. An example API could be something like

```
const input = vscode.window.createQuickPick();
input.value = "a text string";
input.setValueSelection(2, 6);
input.show()
```

The quick pick would be displayed with the word "text" selected.

### PR DESCRIPTION
**Pull request by CrafterKolyan**
Fixes https://github.com/microsoft/vscode/issues/233274

Adding interface to `setValueSelection` in `QuickInput` for extensions.
I am also fine with creating property `valueSelection` like this:
https://github.com/microsoft/vscode/blob/818169af1dac5a59b4cb43c5681cfe0ea4a23463/src/vscode-dts/vscode.d.ts#L12828-L12837

though it looks to me that having a functon `setValueSelection` explicitly documents the fact that you can't read `valueSelection` property for the current user selection.

The best implementation in my opinion should be `valueSelection` property that is also updated with user selection, though for my use case just `setValueSelection` works. Ready to reimplement it to any of these two cases.

Will probably change it to `valueSelection` any way as I think that means literally zero code from my side apart from exposing the already existing API.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
We should have this be a property `valueSelection` to be aligned with the `InputBox` equivalent.

Keep in mind, since this requires API proposal, we will discuss this internally. However, this feels small and provides value so I think this will be a good addition.

**Comment by CrafterKolyan** [comment]
Sure, no problem discussing this.

To be honest I feel that this should be the property of `QuickInput` (which is more general) rather than of `InputBox` or `QuickPick`

**Comment by CrafterKolyan** [comment]
Sure, I've changed this to have `valueSelection` on `QuickInput`

**Comment by TylerLeonhardt** [comment]
Our API review meeting brought up a good point that `value` is both on `QuickPick` and `InputBox`... let's follow that for now. Sorry to go back and forth but can you add this to `QuickPick` and in a follow up we can fix both `value` and `valueSelection`?

**Comment by CrafterKolyan** [comment]
Sorry, I think I misunderstand something. `value` already lives in `QuickInput`. `InputBox` and `QuickPick` simply inherit it from `QuickInput`. And as I said previously `value` lives in `QuickInput`. 

What change do you propose? Right now `valueSelection` is defined near `value`. Both property and getters/setters

**Comment by TylerLeonhardt** [comment]
`value` is not on `QuickInput`:
https://github.com/microsoft/vscode/blob/beaa10f0321288e08d294dfadbd8c01a06aa5c36/src/vscode-dts/vscode.d.ts#L12649

It is, however, in `QuickPick`:
https://github.com/microsoft/vscode/blob/beaa10f0321288e08d294dfadbd8c01a06aa5c36/src/vscode-dts/vscode.d.ts#L12734

and `InputBox`:
https://github.com/microsoft/vscode/blob/beaa10f0321288e08d294dfadbd8c01a06aa5c36/src/vscode-dts/vscode.d.ts#L12826

We want it to be next to `value`... which in this case would be on `InputBox` and `QuickPick`

**Comment by CrafterKolyan** [comment]
Ah sorry, got it. You were talking about the exposed API, rather than the implementation. Agree that in that case we should have valueSelection added only to QuickPick. Will do

**Comment by CrafterKolyan** [comment]
Sure, I've done that. Let me know if you think that implementation of `valueSelection` should also live in `QuickPick` and `InputBox` separately or if I can leave all of it in `QuickInput`

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Thanks for working on this @CrafterKolyan! So the timeline for this is:
* This is merged (today)
* The proposed API is released (early dec)
* We get some response that the API works as intended against real extensions (no concrete timeline, based on extension author feedback)
* finalize it by merging it in to vscode.d.ts after all the above are done

**Review by roblourens — APPROVED** [review]

**Pull request merged**
