### PR TITLE
Add WebFont feature

### PR DESCRIPTION
**Pull request by lewohy**
This PR added a function to automatically download font in vcode. The font is available even in an environment where the font of the fontFamily is not downloaded.

pic01
pic02

And to use the size-adjust of the font-face, we updated it to electron@14.2.5 that uses more than 92 versions of chrome. The reason for using size-addjust was to size other ASCII code characters and UNICODE characters.

For example, if you write it as follows, you can match the size of all UNICODE with English characters.

pic03

### CODE REVIEW

**Comment by bpasero** [comment]
This seems to be for the editor.

**Comment by bpasero** [comment]
Actually maybe not, is this for all workbench?

**Comment by lewohy** [comment]
The purpose was a function for editor and terminal, but it seems to be available for all workbench.

**Comment by bpasero** [comment]
Thanks, but it is unlikely that we would accept this PR when it changes the font for the workbench. I also think it is somewhat strange to use a web font in a desktop installed application? Wouldn't a user install the font locally to use it? Or is the purpose here for VSCode for Web?

**Comment by lewohy** [comment]
In fact, when I made this function, I was working in codespace. Since it was a public computer, it was a computer that was initialized upon reboot, so I worked using code-server or codespace. So there was a hassle of re-installing the font for powerline-font and editor. Also, when using a personal computer, I wondered if I could save the trouble of re-installing the font when using more than one computer.

**Review by MYavuzYAGIS — APPROVED** [review]

**Comment by bpasero** [comment]
As I had stated, in this form I would not accept the PR. If you want to provide a PR where the editor or terminal font specifically can be set to a web font, please go ahead and then I would assign it to respective component owners. But then I think the feature needs to be scoped to those components that explicitly allow for changing the font (editor, terminal).

For the workbench we have not yet decided how to best support font settings.

Thanks for understanding 🙏

**Pull request closed without merging**
