### PR TITLE
File explorer horizontal scroll #15539

### PR DESCRIPTION
**Pull request by Ffloriel**
## Add horizontal scroll to file explorer

This PR adds the horizontal scroll to the file explorer and the open editor views.  
**Note:** it removes the ellipsis on the file name when it's too long.

### Related issues

- https://github.com/Microsoft/vscode/issues/15539
- https://github.com/Microsoft/vscode/issues/35282

### Demo

vscode-horizontal-scroll

### CODE REVIEW

**Comment by joaomoreno** [comment]
Horizontal scrolling is much harder than this. Since these widgets are virtualised, you'd lose the horizontal scrolling position once the wide row goes out of view. Just try it.

**Comment by Ffloriel** [comment]
@joaomoreno Thank you for taking the time to review the PR.

Here is what I know about the scrolling.

The list works the same way as a recycler view in Android. Only the elements visible are rendered in the DOM, which means that the width of the container that depends on the elements inside changes constantly.
The consequence is that the scrollbar is not the same size, the dimensions are recalculated every time a new file appears on the list.

I can see a few options to work around this. It also depends on the UX you want for VsCode.

**Option 1**:
A simple option to me would be to store the maximum width encountered, so in the beginning, you might not see a scrollbar because you did not open a folder that contains a lot of long name file and folders (node modules), if you encounter a long file name, then the scrollbar appears and the size will be fixed to the long file name.

**Option 2**:
Compute the optimal width of all the elements on the list at the start (no idea about the implementation right now), the size of the container will be fixed.

**Option 3**:
Drop the virtualized list, render all the files in the dom (consequences with the performance and memory)

Please let me know what you think. I'll try to implement Option 1 to see how it goes.

**Comment by Ffloriel** [comment]
Option 1 will have the following behavior:

horizontal2

**Comment by joaomoreno** [comment]
I'll play around option 1 soon.

Options 2 and 3 are not options. 😆

**Comment by erperejildo** [comment]
At last!

**Comment by joaomoreno** [comment]
Closing this since it has compilation errors and was left undone. I've started off a new PR here: #45416

Thanks for all the research and effort, @Ffloriel, most of this happened because of it!

**Comment by Ffloriel** [comment]
Happy I could help. If I can help in any way on the new PR, let me know.

**Pull request closed without merging**
