### PR TITLE
files: add an authority filter to the history service

### LINKED ISSUE #195938: File dialog uses slash when backslash should be used in this case
- Connect with a Mac to a Windows tunnel.
- Use `Open Folder` to open a folder on the tunnel machine.
- Notice that the `Open Folder` UI starts on the wrong folder (looks like Linux, e.g., `/home/chrmarti`) and interferes in folder navigation.
- Pick a folder, window reloads.
- `vscode.workspace.workspaceFolders` has a URI missing the drive letter. (e.g., `vscode-remote://tunnel%2Bdevbox-dev1/Users/chrmarti/devel/smktst`)

This then triggers errors in Dev Containers. Maybe the root cause is with the folder picker?

from @chrmarti in https://github.com/microsoft/vscode-remote-tunnels/issues/694

### PR DESCRIPTION
**Pull request by connor4312**
Fixes https://github.com/microsoft/vscode/issues/195938

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
Do we have tests for this or can we add one?

**Comment by alexr00** [comment]
No tests. I can add some tomorrow and push them to this PR.

**Comment by alexr00** [comment]
Actually, we do have some tests: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/dialogs/test/electron-sandbox/fileDialogService.test.ts

**Comment by connor4312** [comment]
Added a few tests

**Review by bpasero — APPROVED** [review]

**Comment by connor4312** [comment]
Will merge based off Alex's initial approval in the linked issue. Please let me know if there are other concerns.

**Comment by alexr00** [comment]
Thanks for making this change! Once we have a new insiders I will try it out.

**Pull request merged**
