### PR TITLE
Restore pull and push buttons to the Source Control Graph view title

### LINKED ISSUE #230689: Restore pull and push buttons to the Source Control Graph view title
In the new version (1.94) the pull and push buttons were removed from the Source Control Graph view title.
Before the update, I had:
image
After the update, only the fetch button remains, and the pull/push buttons were replaced by new buttons with different functionality:
image

I think the pull/push buttons were useful and should be restored.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR closes #230689.

image

Users who don't want the buttons can right-click on them and hide them into an overflow menu (`...`).

image

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Please consider merging this in time for endgame.

**Comment by lszomoru** [comment]
The Pull/Push buttons in the Source Control Graph view only make sense if the current branch is being shown. Since we added the capability to limit the view to any branches, we wanted to avoid any confusion so we removed the actions. 

We can add them back into the context menu when right clicking on the "HEAD" history item.

**Comment by gjsjohnmurray** [comment]
Fair enough. Is there a suitable history item contextkey yet?

**Comment by lszomoru** [comment]
Thank you @gjsjohnmurray for the PR. Closing this in favour of https://github.com/microsoft/vscode/pull/234091.

**Pull request closed without merging**
