### PR TITLE
fix #109733 prevent double '(read-only)' suffix in titlebar

### LINKED ISSUE #109733: [regression] Files served by readonly filesystem show double '(read-only)' suffix in titlebar again
Issue Type: <b>Bug</b>

image

Previously logged as #79240 and fixed in #79241.

Repro steps are as given in previous issue.

Regression apparently occurred in https://github.com/microsoft/vscode/commit/12cf39dea3c87137d4bc1b96c16c4e0a19bd5122

I will submit a PR.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #109733

@bpasero please review and merge if satisfactory.

### CODE REVIEW

**Comment by bpasero** [comment]
Thanks, I was looking into the code myself for 5 minutes and was not able to think about a solution that is straight forward. I am not a big fan of the approach to introduce a flag, but I will comment more next milestone.

**Comment by bpasero** [comment]
My suggested fix: https://github.com/microsoft/vscode/commit/cfb74bdabd480e0305fa4a93267af2c215727b3d

**Comment by bpasero** [comment]
Thanks, but I went with the alternate approach.

**Comment by gjsjohnmurray** [comment]
No problem. Thanks for fixing it a better way.

**Pull request closed without merging**
