### PR TITLE
Sticky scroll for terminal

### LINKED ISSUE #172742: Sticky scroll for terminal commands
Quoting @lunasorcery:
> [imagining a terminal emulator with sticky-scrolling, so if a command's output would push the command itself off the top of the screen, that command gets pinned to the top of the screen instead](https://twitter.com/lunasorcery/status/1619779746904301569)

This would bring VSCode's existing sticky scroll support to terminals for easier viewing and editing of commands with long outputs.

## Suggested implementation
Use shell integration to track commands and render the currently scrolled output's command at the top of the editor in a sticky scroll if it doesn't fit on the screen.

## Potential problems

If a command's output is larger than the terminal's buffer, its command may no longer exist. We may need to cache the last command if it's not already accessible by the shell integration.

## Prior art
- [Sticky scroll](https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll)
- [warp.dev](https://www.warp.dev/)
- [sticky-shell.el](https://github.com/andyjda/sticky-shell)

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #172742

### CODE REVIEW

**Comment by Tyriar** [comment]
Created follow up items for the 4 TODOs and linked them to this PR.

**Comment by Tyriar** [comment]
Looking into the smoke test failure, I think it's a valid race condition.

**Comment by Tyriar** [comment]
This can happen on Windows which causes no sticky scroll to show for the command atm:

image

**Review by meganrogge — DISMISSED** [review]
👏🏼

**Review by meganrogge — DISMISSED** [review]

**Review by meganrogge — DISMISSED** [review]

**Review by meganrogge — DISMISSED** [review]

**Review by meganrogge — APPROVED** [review]

**Pull request merged**
