### PR TITLE
Added Copy relative path

### LINKED ISSUE #12518: Feature request: Copy reference/relative path
Pretty useful and implemented in IDEs like IntelliJ IDEA: ability to **copy reference/relative path** to the file in project tree, or to current line/definition in editor.

At this point there's a "Copy Path" menu item, which is pretty useless to me, always have to paste it, modify and then send to colleagues.

What I expect is actually a path like `src/app.js` instead of `/Users/.../Repo/.../src/app.js`. And `src/app.js:123` when copied from editor, pointing to specific line.

Mostly switched to VSCode, so hope it'll be even more convenient.
Thanks!

### PR DESCRIPTION
**Pull request by john681611**
Attempts to fix https://github.com/Microsoft/vscode/issues/12518

### CODE REVIEW

**Comment by bpasero** [comment]
@john681611 have you thought about making this an extension?

**Comment by john681611** [comment]
Seems more useful as an actual new feature than an extension. Otherwise, you might as well remove `Copy Path` and make that an extension.

**Comment by bpasero** [comment]
@john681611 we try to keep the menu items to a minimum unless there is overwhelming ask for it. The advantage of an extension is that people can install it that really want it. I am saying this because I find it unlikely we would accept this PR which seems to solve a very specific need.

**Comment by john681611** [comment]
I would argue the feature is a staple of many IDE's and a highly useful feature, more useful than a plain copy path. Its been a complaint from about every dev I know that has tried VS code.

**Comment by z-ax** [comment]
I agree with @john681611. If I'd have to choose between copying full path and relative - would take relative without a doubt because full path to file used like... **NEVER**, except cases I need a relative when I copy full path and then edit manually.

Don't know any other dev who has uses full path as it is.

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_26.md#copy-relative-path

**Pull request closed without merging**
