### PR TITLE
Add context key for editor tab visibility

### LINKED ISSUE #139303: Display whether current file is saved or not in zen mode
When a file is opened in zen mode (<kbd>Ctrl</kbd> + <kbd>K</kbd> <kbd>Z</kbd>), I cannot tell if the file is saved without exiting zen mode. It would be nice if VS Code would tell me whether the file is saved or not with a little dot or asterisk in the top bar when the file is not saved.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Rather than reading from `'config.workbench.editor.showTabs'`, which does not reflect tabs being hidden due to zen mode.
Fixes #139303

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Setting this key from the editor group imho is the wrong location because this is global across all editor groups and shouldn't be done by each group within, no?

It seems to me that the only case where `showTabs` does not match the user settings is when `enforcePartOptions` is called on editor group service, and that one exposes an event `onDidChangeEditorPartOptions` that then we could maybe listen to from the `WorkbenchContextKeysHandler` in `src/vs/workbench/browser/contextkeys.ts` that manages most context keys, also editor related ones?

**Comment by JacksonKearl** [comment]
Makes sense, moved it up to `contextkeys.ts`.

**Review by bpasero — CHANGES_REQUESTED** [review]
Isn't this missing an initial value for the context key after startup? I only see an event handler?

**Comment by JacksonKearl** [comment]
I found in practice that the event handler gets hit 3+ times on startup anyways due to default configuration updates, but doesn't hurt to make sure.

**Review by bpasero — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
