### PR TITLE
Testing out panel alignment setting

### PR DESCRIPTION
**Pull request by sbatten**
The setting only supports when the panel is positioned at the bottom of the screen.

### CODE REVIEW

**Comment by sbatten** [comment]
cc @joaomoreno regarding changes to gridview... when moving a view from one location to another, if its not in the same split view, you must know the exact number of children of the destination to move it to the end. this change supports negative numbers to allow -1 meaning move/add view to the end.

**Comment by joaomoreno** [comment]
Nice. At this point, wouldn't it be easier for you to just construct a `GridDescriptor` and use `createSerializedGrid` to create a new grid any time the layout changes its structure, while reusing all the views, a la React? All this `moveTo` imperative code is prone to break and seems harder to maintain.

**Comment by sbatten** [comment]
@joaomoreno I wanted to do something like that, but I wasn't sure what the right flow of calls should be.

e.g. do I completely destroy the previous grid or should there be an API on an existing grid? I also don't want to lose the cached size of hidden views but I suppose I just have to pull all that info out and add it to the newly constructed grid

**Comment by joaomoreno** [comment]
> e.g. do I completely destroy the previous grid or should there be an API on an existing grid? I also don't want to lose the cached size of hidden views but I suppose I just have to pull all that info out and add it to the newly constructed grid

Yeah maybe we need some additional API, but maybe not. If you call `.serialize()` on the grid you actually get a pretty good descriptor of the views within, including their sizes, cached sizes, etc. You could use that information to construct another descriptor which reflects the layout model but includes the latest view states from the initial descriptor. What do you think?

**Comment by sbatten** [comment]
@joaomoreno I haven't tried this yet, but I'm wondering what it looks like after I have a new descriptor. Still, I need to destroy the old grid, right? Which will disconnect the whole workbench from the dom and reattach. Is that what you have in mind?

**Comment by joaomoreno** [comment]
> Still, I need to destroy the old grid, right?

Correct, though all the views' DOM nodes would be reused: they would just be reparented.

> Also, today, I don't really have call layout on the whole grid when moving things around. The code is a bit gross, but the grid seems to handle calling layout on the appropriate things so there are no issues. However it seems like I would have to call a top-level layout every time a part moves with this approach. Is that not more expensive?

No need to call layout when the inside of the grid changes. The contract with layout is: you call it when the size (or position) of the entire grid box changes.

**Pull request merged**
