### PR TITLE
Completely hide tab close button when dirty state is highlighted in top border

### LINKED ISSUE #64684: Should closeTab icon be hidden when highlightModifiedTabs is true?
Using this config:
```json
"workbench.editor.tabCloseButton": "off",
"workbench.editor.highlightModifiedTabs": true,
```
\- dirty files still take space for closing button (and shifting all tabs). 

It makes sense that it worked that way when the only option to show `modified` state of files was the icon. 

Should it take into account highlighting option and not change tab width now?

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #64684 

| Before  | After |
| ------------- | ------------- |
| before | after |

### CODE REVIEW

**Comment by bpasero** [comment]
I am not sure this requires another setting, can we be sure people want this?

**Comment by usernamehw** [comment]
We can merge and wait for complaints.

**Comment by usernamehw** [comment]
It's not like people would actually upvote the issue #64684.

**Review by bpasero — CHANGES_REQUESTED** [review]
I would prefer the CSS to be just more explicit via a `:not()` pseudo:

```
.monaco-workbench > .part.editor > .content .editor-group-container > .title .tabs-container > .tab.close-button-off.dirty:not(.dirty-border-top) {
	background-repeat: no-repeat;
	background-position-y: center;
	background-position-x: calc(100% - 6px); /* to the right of the tab label */
	padding-right: 28px; /* make room for dirty indication when we are running without close button */
}

.vs .monaco-workbench > .part.editor > .content .editor-group-container > .title .tabs-container > .tab.close-button-off.dirty:not(.dirty-border-top) {
	background-image: url('close-dirty.svg');
}

.vs-dark .monaco-workbench > .part.editor > .content .editor-group-container > .title .tabs-container > .tab.close-button-off.dirty:not(.dirty-border-top),
.hc-black .monaco-workbench > .part.editor > .content .editor-group-container > .title .tabs-container > .tab.close-button-off.dirty:not(.dirty-border-top) {
	background-image: url('close-dirty-inverse.svg');
}
```

This avoids having to repeat CSS rules that have been defined elsewhere already.

**Comment by usernamehw** [comment]
No selector for `.hc` because there's no modified border there.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by usernamehw** [comment]
@bpasero Was this reverted in the latest Insiders or broken? I'm not against reverting, just asking.

**Pull request merged**
