### PR TITLE
Make hover actions keyboard accessible

### LINKED ISSUE #95702: Actions in hover are not keyboard accessible
Context: https://github.com/microsoft/vscode/issues/95573#issuecomment-616573559

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #95702

This lets you focus the actions via tab and they are correctly marked as role=button

image

### CODE REVIEW

**Comment by Tyriar** [comment]
This doesn't actually work yet, need to hook up the activation handler.

**Comment by Tyriar** [comment]
@octref ready for review

**Review by octref — APPROVED** [review]

**Comment by octref** [comment]
LGTM, do you want to add it to release note? Preferably also adding that you need to click hover widget to tab into it.
If you are using keyboard, running "Show Hover" command, I don't think it's tabbable.

**Comment by Tyriar** [comment]
> If you are using keyboard, running "Show Hover" command, I don't think it's tabbable.

It is if you're in screen reader mode. @isidorn do you think we should change that behave such that show hover always focuses the hover?

**Comment by isidorn** [comment]
@Tyriar we already do that, if screen reader mode is on show hover focuses the hover
Code pointer https://github.com/microsoft/vscode/blob/04f1f900f8a4a1b0e9da765fa3334eb21e1caf49/src/vs/editor/contrib/hover/hover.ts#L257

**Comment by Tyriar** [comment]
@isidorn right now they're not keyboard accessible (via the hover) unless you're in accessibility mode. The question is whether it should focus it regardless of accessibility mode if you trigger the hover via the command?

**Comment by isidorn** [comment]
@Tyriar not sure.
When I designed the debug hover I actually designed to behave like you say: when invoked via keybinding pass focus.
So it might make sense for the eidtor action as well. Though it might be a breaking change, so if you decide to change it do it asap so we get feedback on insiders before stable release.

**Comment by Tyriar** [comment]
I guess let's keep it as is for now since it would break the case where you're typing and want to view the hover, plus the actions are available via commands/other keybindings.

**Pull request merged**
