### PR TITLE
SCM Graph - 💄 switch to using px for badge font size (#229918)

### PR DESCRIPTION
**Pull request by sandy081**
#229918

### CODE REVIEW

**Review by aeschli — APPROVED** [review]

**Comment by sandy081** [comment]
@alexr00 I created this PR using GHPR extension and I believe this is not the summary or description I picked. In my regular flow, I do not write summary or description and I leave the extension to pick it from existing commit. If you see the commit has a different commit message. This seems to be a bug in the extension.

**Comment by alexr00** [comment]
Thanks @sandy081 I will take a look!

**Comment by alexr00** [comment]
Looks like it grabbed the commit message from the previous commit: 
image

I can't repro this though. Do you remember if you used the "Commit & Create Pull Request" button?

**Comment by sandy081** [comment]
I used `GitHub Pull Requests: Create Pull Request` command

**Comment by alexr00** [comment]
@sandy081 did you create the upstream branch for the PR branch before or after you ran "GitHub Pull Requests: Create Pull Request"?

**Comment by sandy081** [comment]
I remember I did it before creating the pull request. 
I am not seeing this anymore, It could be a timing issue. I will see if this happens again and remember the steps and report them.

**Comment by alexr00** [comment]
Ok, if you see it again, can you also share the `git` output.

**Pull request merged**
