### PR TITLE
Focus the quick pick back to the starting position

### PR DESCRIPTION
**Pull request by aaomidi**
Accessibility issue we've seen on https://github.com/microsoft/azuredatastudio/issues/9232

### CODE REVIEW

**Comment by chrmarti** [comment]
Tracked with #92076.

Currently we use `returnFocus()` to pass the focus back to the current editor. We could instead first try to return it to the previous focus element the way you suggest.
https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/quickinput/browser/quickInput.ts#L1527

**Comment by aaomidi** [comment]
Is there anything I need to do for this?

**Comment by chrmarti** [comment]
You can update the PR or I can take a look next milestone. 👍

**Comment by alanrenmsft** [comment]
@chrmarti what changes do you think @aaomidi should make to this PR? could you please add your comments directly?

**Pull request closed without merging**
