### PR TITLE
Adds workspace config for submodules detection limit

### LINKED ISSUE #45266: Make a setting out of the submodule git repository discovery limit
Related to #43528

### PR DESCRIPTION
**Pull request by shobhitchittora**
Closes #45266

### CODE REVIEW

**Comment by shobhitchittora** [comment]
@joaomoreno can you re-try travis for linux.

**Comment by shobhitchittora** [comment]
Travis still failing for linux. Not sure why.

**Comment by joaomoreno** [comment]
No worries. We'll take it.

**Comment by shobhitchittora** [comment]
Awesome! ✨🔥

**Comment by shobhitchittora** [comment]
@joaomoreno Can you close / merge this if done?

**Comment by shobhitchittora** [comment]
Moved to #45727

**Pull request closed without merging**
