### PR TITLE
Ability to use MSAL in the Desktop

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This adds a new setting `microsoft.useMsal` to be used to enable the Microsoft Authentication Library (MSAL) for signing in with a Microsoft account. In the next month or so, this will be the default... but since it's such a large change (practically re-implementing the entire extension) we have a setting to gate it. I implemented this in such a way that when we are ready to make it the default, we can simply remove the setting and `extensionV1` code without having to do much else.

Known issues and workarounds (already opened issues internally):
* MSAL-node doesn't handle a scenario where 2 processes use the same persisted cache... this caused issues when one process (window of VS Code) would sign out of an account - the sign out would not be reflected in the other process (window of VS Code). **To work around this**, we use globalStorage to write a `lastRemoval:...` which, when that date is later than the creation date, we simply re-create the MSAL object. This is funky, but it works nicely.
* MSAL-node's "reads" actually write to the persisted storage. **This doesn't need a workaround**, but it does mean the extension is doing more than it needs to do because it has to handle these "writes" that are writing the same thing to the persisted storage.
* MSAL-node's default behavior does not render an error in the user's browser when an error was detected in the sign in flow. **There is not a workaround in this PR but I will include a workaround for this in a followup**

Next steps:
* Implement the workaround for that last issues
* Add tests to this extension (none exist today)

NOTE: Currently, this change does not work in the web worker extension host. While I was able to get MSAL-node to work in the web worker extension host, it required a lot of browserifying that needs more attention. Ironing this out is a next _next_ step, I'd say.
ref https://github.com/microsoft/vscode/issues/229415

### CODE REVIEW

**Review by rebornix — APPROVED** [review]

**Comment by lippertmarkus** [comment]
@TylerLeonhardt Is there an issue that I can follow for the web worker support of MSAL? We want to onboard more non-tech users to use our extension via VS Code Web but this currently limits us :(

**Comment by TylerLeonhardt** [comment]
@lippertmarkus Just to be clear, you are talking about vscode.dev, yes?

**Comment by lippertmarkus** [comment]
@TylerLeonhardt yes, exactly

**Comment by TylerLeonhardt** [comment]
You can follow along with this one:

https://github.com/microsoft/vscode/issues/178740

**Pull request merged**
