### PR TITLE
Add update-desktop-database calls

### LINKED ISSUE #193951: rpm doesn't run update-desktop-database
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: CentOS Linux 7.9.2009

Steps to Reproduce:

1. Install the rpm on CentOS 7 following the [official instructions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)
2. Run `xdg-open vscode://.`, or do something that requires a `vscode://` URL to work such as logging into GitHub
3. You'll get an error like "The specified location is not supported" (`xdg-open`) or "We can't connect" (from the browser - it'll be reported on a `github.com` URL that is supposed to be redirecting to `vscode://`)

It all works fine on Ubuntu. 

I was able to fix it by running `sudo update-desktop-database`.

I unpacked the deb and rpm files and looked in the post-install scripts and indeed the .deb runs `update-desktop-database` and the .rpm doesn't.

### PR DESCRIPTION
**Pull request by rzhao271**
Fixes https://github.com/microsoft/vscode/issues/193951

### CODE REVIEW

**Comment by deepak1556** [comment]
Changes look good, please verify the following two scenarios before merging:

- [ ] Install rpm created from this PR on CentOS 7 and verify url handler flow works
- [ ] Update the installed package to latest published rpm and verify url handler flow continues to work

**Comment by rzhao271** [comment]
The update scripts currently no-op because the custom Insiders build is newer than the latest published Insiders.
I'll wait until later to test the remaining items.

**Comment by rzhao271** [comment]
Verified on rpm the following way:

1. I installed Insiders build 2f2b9e84891c650abf9b5ac55cf07dfbc6d1fdd5 which is based off of this branch
2. I ran `gio open vscode-insiders://.` and verified that code-insiders loaded.
3. I updated code-insiders to 4a0e77678c0295b518151ae2d706436bab96ef4f using yum by following the [official instructions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions).
4. I ran `gio open vscode-insiders://.` and verified that code-insiders loaded.

**Comment by rzhao271** [comment]
Verified on Ubuntu 22.04 the following way:

1. I installed Insiders build 0f4f31c460737bd6698329e9f6d8d30e68404172 which is based off of this branch. It's older than the build I used to verify the rpm package, but the most recent change only affects the rpm package post-install scripts, so it's fine.
2. I ran `xdg-open vscode-insiders://.` and verified that code-insiders loaded.
3. I updated code-insiders to https://github.com/microsoft/vscode/commit/4a0e77678c0295b518151ae2d706436bab96ef4f using apt-get.
4. I ran `xdg-open vscode-insiders://.` and verified that code-insiders loaded.

**Review by deepak1556 — APPROVED** [review]

**Pull request merged**
