### PR TITLE
Renaming Close Unmodified to Close Unsaved

### PR DESCRIPTION
**Pull request by itamark**
https://github.com/Microsoft/vscode/issues/44033

### CODE REVIEW

**Comment by bpasero** [comment]
@itamark note that we cannot change identifiers of actions/commands, because people might have associated keybindings already.

**Comment by itamark** [comment]
@bpasero Oh, good to know. That makes sense. Should I change all instances of `CLOSE_SAVED_EDITORS_COMMAND_ID` back?

**Comment by itamark** [comment]
@bpasero okay put back the action identifiers.

**Comment by bpasero** [comment]
Its fine, I merged it with a follow up change: https://github.com/Microsoft/vscode/commit/8015c58d78b0e7d0f23e607189d95a68617310d5

**Pull request merged**
