### PR TITLE
New git welcome missing guide

### PR DESCRIPTION
**Pull request by digitarald**
This PR applies the new `git.missing` welcome views from #136408.

The new UI is behind an experiment setting, so we can test its impact and also explore other installations like terminal-based flows.

image

---

Initial commit for reference:

image

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
I think it's misleading to start with the sentence "Source control depends on Git being installed." and only in the final paragraph mention that other providers exist.

I suggest starting with "Source control tracks code changes to look back and revert."

Next: "Git is the most popular... ...easy to learn and use."

Next: "This built-in source control depends on Git being installed on your workstation."

Next, the download button and the reload instruction.

Finally: "Other source control providers exist and can be installed from the Marketplace."

**Comment by digitarald** [comment]
Thank you for the feedback! I see how the explainer-first flow can be a good alternative. I preferred to keep the action first to avoid burying the lede.

> I think it's misleading to start with the sentence "Source control depends on Git being installed." and only in the final paragraph mention that other providers exist.

The current view for "missing git" starts in a similar fashion, focused on git:

> A valid git installation was not detected, more details can be found in the [git output]
> Please [install git], or learn more about how to use git and source control in VS Code …

The main reason for git focus is that we have more users on git vs the much smaller portion on the other providers. As this view also targets SCM beginners, users that are on other providers presumably don't need the additional onboarding that this view provides.

**Comment by misolori** [comment]
Personally I'd try to trim down the text to something that's easier to read and has links to documentation that can help users get started:

>No source control providers found. 
>
>You can install [Git], a popular source control system, which helps you track code changes and syncs with the cloud. Follow our [getting started with Git guide] for more information.
>
>[Download Git for macOS]
>
>Additional source control providers can be installed from the Marketplace.

CleanShot 2022-01-07 at 12 10 15@2x

**Comment by lszomoru** [comment]
+1 for the shorter text that has been suggested by @misolori.

**Review by lszomoru — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
