### PR TITLE
build on mac11.1: upgrade version of playwright to 1.7.1

### LINKED ISSUE #113894: Build issue: vscode compile from source fails on Mac11.1
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0

Steps to Reproduce:
1. git clone git@github.com:microsoft/vscode.git
2. cd vscode
3. yarn

Does this issue occur when all extensions are disabled?: Yes

**Error seen:**
[3/4] 🔗  Linking dependencies...
warning " > eslint-plugin-mocha@8.0.0" has incorrect peer dependency "eslint@>=7.0.0".
warning "gulp-atom-electron > @octokit/rest > @octokit/plugin-request-log@1.0.2" has incorrect peer dependency "@octokit/core@>=3".
warning " > gulp-tsb@4.0.5" has incorrect peer dependency "typescript@^3.0.0".
[4/4] 🔨  Building fresh packages...
[6/17] ⢀ spdlog
[7/17] ⢀ vscode-nsfw
[13/17] ⢀ electron
[9/17] ⢀ vscode-sqlite3
**error** /Users/swinder/code/vscode/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/swinder/code/vscode/node_modules/playwright
Output:
/Users/swinder/code/vscode/node_modules/playwright/lib/utils/utils.js:58
        throw new Error(message);
              ^

**Error**: ERROR: Playwright does not support chromium on mac11.1
    at Object.assert (/Users/swinder/code/vscode/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/Users/swinder/code/vscode/node_modules/playwright/lib/install/browserFetcher.js:131:13)

### PR DESCRIPTION
**Pull request by swinder0161**
#113894
fyi @bpasero

This PR fixes #113894

### CODE REVIEW

**Comment by bpasero** [comment]
Thanks!

**Comment by bpasero** [comment]
@swinder0161 your change included a ton of changes to `yarn.lock`, any reasons for that?

I pushed https://github.com/microsoft/vscode/commit/27ff57608932ba1c458886e35730dac47569d326 for a clean update.

**Comment by swinder0161** [comment]
I deleted yarn.lock and it was auto generated after running yarn command.

**Comment by bpasero** [comment]
Oh yeah, that explains it.

**Pull request merged**
