### PR TITLE
Update Seti webpack icons to use correct icons

### LINKED ISSUE #62636: Seti file icon theme - inconsistency with webpack icons
- VSCode Version: 1.28.2
- OS Version: Linux Mint 18.3 Sylvia (XFCE DE)

Steps to Reproduce:

1. Open `Settings` menu and set `Seti (Visual Studio Code)` to default file icon theme
2. Create new project with following files:
    - `webpack.common.js`
    - `webpack.config.js`
    - `webpack.dev.js`
    - `webpack.prod.js`

As you can see, `webpack.config.js` have different icon then other webpack files. It might make sense to use same icon for all `webpack.*.js` files.

screenshot_2018-11-06_06-13-59

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by miguelsolorio**
Fixes  #62636

|Before|After|
|---|---|
|before|after|

### CODE REVIEW

**Comment by mmilanovic4** [comment]
Wouldn't this be better solution, as icon already exists?

48156082-60f30d00-e281-11e8-8238-11a529d524c1

**Comment by misolori** [comment]
@mmilanovic4 🙈 you're right, this was a total brain fart on my part. Will update all webpack icons to use the webpack icon.

**Comment by aeschli** [comment]
@misolori I forgot to mention: the seti icon theme is generated from the original seti repo. check the header of the file.

**Comment by rajho** [comment]
Hey guys, have you created an issue in the seti repo? if yes, what is the number??

**Comment by misolori** [comment]
Sorry, this fell off my radar.

@aeschli I created a pr on the main repo https://github.com/jesseweed/seti-ui/pull/517

**Comment by aeschli** [comment]
Thanks @misolori . Closing this PR. I'm observing seti-ui and hope the next release comes out soon.

**Pull request closed without merging**
