### PR TITLE
debt - remove updateBackupPath method from environment service

### LINKED ISSUE #109019: Backup location can change in same session
I noticed some unsafe usages of the backup location for the workspace here:

https://github.com/microsoft/vscode/blob/1af5af95452a55ea65d365f62607da2dca7886f2/src/vs/workbench/electron-browser/desktop.main.ts#L234-L234

and here:

https://github.com/microsoft/vscode/blob/79c4f10983149bf4420fa20597dfe26f05c85506/src/vs/workbench/services/userData/common/fileUserDataProvider.ts#L41-L41

Truth is that this path will change when you enter a workspace (e.g. transition from a 1-folder to a multi-root workspace):

https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/services/workspaces/electron-sandbox/workspaceEditingService.ts#L173

This is ugly because it changes a property in the environment service which is unexpected. I want to change this in a way that the backup service can be re-initialized with the right location and have started this work here: https://github.com/microsoft/vscode/tree/ben/backup-reinit

I renamed `backupWorkspaceHome` to `initialBackupWorkspaceHome` but it is still not very easy to understand. I think ideally we can remove this property from the environment service altogether (maybe have it in the `IBackupFileService`) and have ways to signal a change to clients.

I only see the following clients of this property:
* `IBackupFileService` (I can handle that via the `reinitialize` method)
* `FileUserDataProvider` (I will need your help here as I do not fully understand the use case yet)

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #109019

### CODE REVIEW

**Review by rheh — APPROVED** [review]
LGMT

**Comment by bpasero** [comment]
@sandy081 somehow forgot to add you as reviewer

**Comment by sandy081** [comment]
@bpasero I think we also need reinitialise on `fileUserDataProvider` right? Otherwise backups might not work correctly after reinitialise which is the case now.

**Comment by bpasero** [comment]
@sandy081 yeah agreed, that part is still missing. Should we maybe introduce an event on `IWorkspacesService` that a workspace is entered and then let backups and your service listen to it for re-initalization?

**Comment by sandy081** [comment]
`fileUserDataProvider` is created during initialization in `*.main.ts`. So it is not having access to `IWorkspacesService`. How about an event on `IWorkbenchEnvironmentService` ? I think that would be better because environment service will also be up to date.

**Comment by bpasero** [comment]
@sandy081 I am not a big fan of changing values in environment service because as a consumer you think the value is static and never changes. I see the environment service as a static bag of properties that never changes.

The event was just an idea to decouple things, alternatively we somehow need to reach into the provider similar how we do it for the backup file service...

**Comment by sandy081** [comment]
One option is to get the provider from `IFileService` or I shall have to create a special service for this provider which can be accessed in workspace editing service. Note that `enterWorkspace` path is already reaching into internals of Workspace and Backup services to reinitialise.

**Comment by bpasero** [comment]
Let me take a look now that I see how we need to update `FileUserDataProvider`. I don't want to put too much work in it, maybe it could simply happen all from `desktop.main.ts` where `FileUserDataProvider` is created.

**Comment by bpasero** [comment]
@sandy081 one thing you could help with is to scaffold the changes needed in `FileUserDataProvider` to update the backup path, then I can call it from the right place.

**Comment by sandy081** [comment]
@bpasero Updated `FileUserDataProvider` and made backup path updatable from outside - 043d8e208667759c922d5ad36b9f2ed3f4b20629

You can just access and set the path directly on `FileUserDataProvider`

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/0593b3eb54b0c5a27836618a56c151de73814dc2

**Pull request closed without merging**
