### PR TITLE
Fix error in remote reviveTerminalProcesses

### LINKED ISSUE #187075: Error on reviveTerminalProcesses in remote
Repro:

1. Open OSS
2. Open new test resolver window
3. Close non-test resolver window
4. Close all terminals
5. Exit application
6. Open OSS
7. Open pty host log

I see an error being returned from `reviveTerminalProcesses`:

```
2023-07-05 11:32:09.225 [trace] [RPC Request] PtyService#reviveTerminalProcesses...
2023-07-05 11:32:09.226 [error] [RPC Response] PtyService#reviveTerminalProcesses Cannot read properties of undefined (reading 'cwd')
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #187075

### CODE REVIEW

**Review by meganrogge — APPROVED** [review]

**Comment by meganrogge** [comment]
How is that error happening though? when are `processDetails`

**Comment by meganrogge** [comment]
fined

**Comment by Tyriar** [comment]
It may have been bad stuff stuck in the storage service which I removed manually. The change in this PR just carries over the local change which prevents the get layout call when there isn't any data.

**Comment by Tyriar** [comment]
Actually, this doesn't actually fix the problem. It does fix part of https://github.com/microsoft/vscode/issues/187076 though. Will make a more accurate PR later

**Pull request closed without merging**
