### PR TITLE
Add an option to change extension gallery URL (fixed #21839)

### LINKED ISSUE #21839: Feature Request: Support for private marketplace/gallery
We have created several VSIX extension that have no use to anybody else except our company. We would like to host our own private extension gallery and have an ability to specify alternative extension gallery paths (like "Additional Extension Galleries" in Visual Studio 2015).

- VSCode Version: 1.10.1
- OS Version: Windows 10

### PR DESCRIPTION
**Pull request by nirolevy**

### CODE REVIEW

**Comment by frank-dspeed** [comment]
@nirnir93 good work good idea thanks for this.

**Comment by kieferrm** [comment]
We have been thinking about this as well. However, it requires us to specify in detail the protocol the gallery endpoint has to speak which in turn means that this becomes stable API. We are not yet comfortable with that level of commitment when it comes to the extension gallery.

We'll add the capability as soon as we can commit to a stable gallery API. 

Since we won't merge the PR any time soon, I close it.  Thanks understanding!

**Comment by frank-dspeed** [comment]
@kieferrm the extension api is not as complex it has not much needed endpints list, search, download i think there are not much relevant updates to that api possible :)

**Comment by frank-dspeed** [comment]
any way this issue is a part of https://github.com/microsoft/vscode/issues/81310

**Pull request closed without merging**
