### PR TITLE
Temporarily disable input method interception.

### LINKED ISSUE #72176: Some keyboard shortcuts do not work when use IME
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Turn on Japanese IME(Microsoft IME or Google Japanese Input).
2. Use Keyboard shortcut(ex. Ctrl+K M).
3. Status bar message: "The key combination (Ctrl+K, unknown) is not a command."

ime_shortcut

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

### LINKED ISSUE #151496: The waiting second key is intercepted by the input method
Issue Type: <b>Bug</b>

When the input method is activated, during the process of using the combination shortcut Ctrl-K k: (Ctrl-K) has been pressed, waiting for the second key, the second key is blocked by the input method. So the input method should be automatically disabled while waiting for the second keypress.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.18.1-arch1-1
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 2252)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.64GB (9.74GB free)|
|Process Argv|--unity-launch --crash-reporter-id fbdf6ce9-df85-417f-91bc-592561b058e1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
arm|dan|1.7.4
vscode-pull-request-github|Git|0.42.0
vue-snippets|hol|1.0.4
vscode-language-pack-zh-hans|MS-|1.67.3
cpptools-extension-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5615
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.18.0
vscode-yaml|red|1.7.0
vim|vsc|1.22.2
volar|Vue|0.37.3
vscode-typescript-vue-plugin|Vue|0.37.3
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.29
linkerscript|Zix|1.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

### PR DESCRIPTION
**Pull request by guttyon**
Fixes #151496
Fixes #72176
This fix for Windows only, not for Linux .
This fix uses ffi-napi win32 ImmGetContext ImmReleaseContext ImmSetOpenStatus ImmGetOpenStatus GetFocus.

This fix adds the following steps.
1. Disable IME when hit ctrl-k.
2. The next key press is not intercepted because IME is disabled and is passed directly to vscode.
3. Enable IME on subsequent keystroke.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
Tackling this with system calls seems to be taking a very big hammer to try to fix this problem. Have you explored calling `.preventDefault()` in the `compositionstart` event when chords are active here -- https://github.com/microsoft/vscode/blob/382a6d3a6b0910877e9142a397acac3350efa6fc/src/vs/editor/browser/controller/textAreaInput.ts#L242

**Comment by guttyon** [comment]
Thanks for the advice.
I did not know about preventDefault, so I tried calling it in onKeyDown and onCompositionStart. 
When called in onKeyDown, English input was disabled on the vscode as expected, but contrary to expectations, Japanese input was possible. 
When invoked with onCompositionStart, both English and Japanese input was possible. I could not tell if these behaviors are in accordance with the specification.
I wish there was a better way because I too think it is a big hammer.

**Comment by guttyon** [comment]
Since preventDefault does not seem to avoid interception by IME, I thought of another means.

In the end, we ended up adding two lines as follows
https://github.com/microsoft/vscode/pull/159699/files#

We decided to use the extension for IME operation and eliminated it from vscode.
Register the keybindingChordMode command in the extension to get events that manipulate the IME.
https://github.com/guttyon/vscode-extension-toggle-ime-in-chordmode

This pull request eliminates the need to turn the IME off and back on again when using shortcut keys.

**Review by alexdima — APPROVED** [review]

**Comment by alexdima** [comment]
@guttyon I've explored a different technique, to make all editors `readonly` when in chord mode. Having them be `readonly` seems to be a good way to suppress composition from starting. This works well for me on macOS, could you please give this a try on Windows?

**Review by joaomoreno — APPROVED** [review]

**Comment by guttyon** [comment]
@alexdima
It worked on windows,ubuntu22.04.
It is very comfortable.
I think the method using readonly is excellent because it doesn't need to be supported for each ime.
Thank you very much for your efforts on this issue.

**Pull request merged**
