### PR TITLE
Spaces in block comment. #28169

### LINKED ISSUE #28169: Space before block comment
When toggling block comment, it should be `/* comment */` rather than `/*comment*/`,
just like it's `// comment` rather than `//comment` in line comment.

### PR DESCRIPTION
**Pull request by yzhang-gh**
Resolve #28169.

According to [that](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/comment/common/lineCommentCommand.ts#L370) in `lineCommentCommand.ts`.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
Thank you for your contribution. At this time, this PR breaks 13 tests. Could you please look into changing tests where it makes sense and fixing any introduced regressions ?

**Comment by neilsustc** [comment]
I've fixed the tests. But I have no idea about this one ...

```
1) Search-integration Text: GameOfLife:
   Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by alexandrudima** [comment]
@neilsustc I have closed and reopened the PR to get travis to rerun the build.

This has also triggered our Contribution License Agreement bot to re-evaluate the PR, and, due to the increase in changed lines count, it now requires an agreement. Could you please go through the flow the bot asks for, it is very simple.

**Comment by neilsustc** [comment]
Thanks for your patience 😉

**Review by alexdima — APPROVED** [review]

**Comment by alexandrudima** [comment]
Very nice. Thank you for your contribution @neilsustc :heart:

**Pull request merged**
