### PR TITLE
Add new property to IConfigurationPropertySchema

### LINKED ISSUE #106737: Show enumDescriptions in settings UI dropdowns
Issue Type: <b>Bug</b>

image

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T00:56:22.923Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|-psn_0_31661616 --crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Dev Container: Alpine|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.86GB free)|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by ryanclarke**
This PR fixes #106737

### What it does

This adds the `showEnumDescriptionInSelectBox?: boolean` property to `IConfigurationPropertySchema` so that enum configuration settings can elect to show their `enumDescription` in selectboxes and dropdowns insead of the enum value. This new option is only used by `files.encoding`.

### How to verify

1. Open Settings (UI) and go to Text Editor > Files > Encoding.
> The selectbox should show the encoding's description instead of its value, e.g. `UTF-8` instead of `utf8`.

2. Click on the File: Encoding selectbox.
> The options in the dropdown should be the description not the value, e.g. `DOS (CP 437)`.
> The footer of the dropdown should be the value, e.g. `cp437`.

### Open questions

> I think we should add an option to the schema contribution for this but I have no clue what to call it
@roblourens  https://github.com/microsoft/vscode/issues/106737#issuecomment-694344103

1. Is `showEnumDescriptionInSelectBox` a good name?

2. I couldn't find any tests to add to for this bit of code. Are there any?

### CODE REVIEW

**Review by roblourens — APPROVED** [review]
This change looks fine, thanks. I'm still not sure about the schema prop name though. Any ideas @sandy081? Maybe `swapEnumDescriptionsAndValuesInUI` or `showEnumDescriptionsInUI`

**Comment by ryanclarke** [comment]
I like `swapEnumDescriptionsAndValuesInUI`.

**Comment by roblourens** [comment]
I trying to think of something that's not tied to a specified settings editor mode, but just tells me what property this setting has that would cause the UI to decide to display it differently. Like `enumDescriptionsArePrimaryNames`

**Comment by sandy081** [comment]
Seems UI related, so it might makes sense to call that out?

**Comment by ryanclarke** [comment]
So we like `showEnumDescriptionsInUI`?

**Comment by roblourens** [comment]
I just don't think the property should be _telling_ the UI what to do. We could use it in other places too, like imagine if it changed something about the way values are displayed in the json suggest widget.

Normally I wouldn't be this hung up on a name at all but this type is effectively extension API and so we should try to be thoughtful.

I think I would go with `enumDescriptionsArePrimaryNames` if you're ok with that @sandy081

**Comment by sandy081** [comment]
I see, good thinking. If it is going to be a general property I would ask @aeschli for suggestion as he owns json suggestions.

**Comment by aeschli** [comment]
I would suggest `enumItemLabels` as an array of item labels.  If present, these are used.
`enumDescriptions` should stay descriptions as before. They are already used in other contexts, such as in hovers or for code completion infos in the textual editor.

**Comment by roblourens** [comment]
I think this is tricky, the list of labels might be equal to the list of descriptions or items or it might not. What would the logic in the dropdown be to decide whether it needs to show all 3 pieces of info or just 2?

**Comment by aeschli** [comment]
@roblourens `enumItemLabels.length` must be `enum.length` or the enumItemLabels are invalid. That's the same with the enumDescriptions. 

The logic would be if `enumItemLabels` exists, use `${enumItemLabels[i]} (${enum[i]})` as label.

**Comment by ryanclarke** [comment]
So in this case, `files.encoding`, we would simply duplicate the `enumDescriptions` into the new `enumItemLabels` array? Should I add this new array to `IConfigurationPropertySchema ` or `IJSONSchema`?

**Comment by ryanclarke** [comment]
Also, with this proposal, would we revert back to the existing functionality of the dropdown footer always showing the `enumDescription`?

**Comment by roblourens** [comment]
@aeschli would setting `enumDescriptions` and `enumItemLabels` be mutually exclusive? Or is there a case where the label and the key and the description get shown?

**Comment by aeschli** [comment]
> we would simply duplicate the enumDescriptions into the new enumItemLabels array
Yes, but then `enumDescriptions` can be changed to a sentence style description as it is normally the case. 

> I add this new array to IConfigurationPropertySchema or IJSONSchema?
I would add it to `IConfigurationPropertySchema` as the settings UI is the only user (for now)

> Also, with this proposal, would we revert back to the existing functionality of the dropdown footer always showing the enumDescription?
Yes, that's a possibility

@roblourens As hinted in the last question, both `enumDescriptions` and `enumItemLabels` could be visible at the same time:
```
|            ${enumItemLabels[0]}                |
|            ${enumItemLabels[1]}                |
|            ${enumItemLabels[2]}                |
------------------------------------------------------
|   ${enumDescriptions[selectedIndex]}   |
------------------------------------------------------
```

The main idea of my proposals is to not repurpose `enumDescriptions`. They are typically sentence style description, shown in hovers. So better introduce a new property that is is for item labels.
Also remember that we also have the class JSON settings editor that also uses the `enumDescriptions`,
Ping me any time for a call.

**Comment by ryanclarke** [comment]
Thanks for the clarification. I'm working on a implementation of these changes for you all to look at.

**Comment by ryanclarke** [comment]
Let me know if that's closer to what you're looking for. I don't show both the `enumItemLabel` and the `enum` value together though, only the label. My issue with that is your proposed format `${enumItemLabels[0]} (${enum[0]})` would sometimes look odd in this encoding case. The `labelLong` already includes a parenthetical component on many entries that is usually an unformatted duplicate of the `enum` value.

Here are some samples:
> UTF-16 BE (utf16be)
> Romanian (ISO 8859-16) (iso885916)
> Traditional Chinese (Big5) (cp950)
> Traditional Chinese (Big5-HKSCS) (big5hkscs)

Or if we used square brackets and removed redundant parts of the `longLabel`:
> UTF-16 BE [utf16be]
> Romanian [iso885916]
> Traditional Chinese (Big5) [cp950]
> Traditional Chinese [big5hkscs]

I don't like that either because the formatting on most of the lines would look worse. However, if we go remove the `enum` value entirely (like the current PR state) then in the "Traditional Chinese (Big5)" case, the value of `cp950` will never be surfaced in the UI. `cp950` is the only encoding like this though.

**Comment by roblourens** [comment]
@aeschli I get it now, separating a "label" from a "description" is a better idea. Is it confusing if the `enumItemLabels` are not surfaced anywhere in the JSON editor though?

Regarding the duplication in `files.encoding` specifically, I can't decide whether it's a problem or not. Sometimes they are different and it is valuable to include both. We already show both in the editor encoding picker

image

the formatting makes it look a little nicer, and we could consider introducing that to the custom dropdown? There is already the right-aligned detail text that we use for "default" but I might consider trying to introduce this.

How about putting the key in the description area for now?

image

**Comment by ryanclarke** [comment]
Getting the nice formatting of the encoding picker is a big change for the settings UI and I'm not sure the repercussions for the rest of the settings UI. You'll have to make that call.

Adding the enum key between brackets in the description area is less nice. We could have it only appear if there is a `enumItemValues`. BUt will people know that the bracketed text is the enum key? Will it work in other cases that use `enumItemValues`?

**Comment by ryanclarke** [comment]
Let me know what you'd like to have done.

**Comment by roblourens** [comment]
Let's just put the key in square brackets in the item row, and then we can merge this, and I will keep thinking about it

**Review by roblourens — APPROVED** [review]

**Comment by roblourens** [comment]
Thanks!

**Comment by ryanclarke** [comment]
Hooray! It's cool that I can contribute to this, a project I use and benefit from every single day! Thanks for all you do.

**Comment by roblourens** [comment]
Thanks for your contribution! If you feel like working on https://github.com/microsoft/vscode/issues/109255 too, I'd be happy to guide you.

**Pull request merged**
