### PR TITLE
Added functionality to toggle rendering of URLs as clickable hyperlinks

### PR DESCRIPTION
**Pull request by brandedoutcast**
Addresses the feature-request #27632

### CODE REVIEW

**Comment by alexandrudima** [comment]
@RohithKumbharkar   thank you for your contribution :heart:. 

There are already two PRs targeting links that came in a few days ago for #27632

* #28160 
* and #28281 

I will go through them in the order they came in, and see if there is overlap/parity across the 3 PRs.

**Comment by alexandrudima** [comment]
@RohithKumbharkar Thank you for your contribution. I have just merged the first PR that came in and added a toggle for link detection, #28160 .

I have presented in today's standup and we have found that adding a toggle in the View menu for this option is a bit too much. The editor has very many toggles and we cannot fit all of them in the View menu, even if they are related to rendering, e.h. `codeLens`, `roundedSelection`, `hideCursorInOverviewRuler`, etc.

**Comment by RohithKumbharkar** [comment]
No biggie 👌 I'm game 😎 I'll just have to invade this repo with more & more PRs 😈

Thanks @alexandrudima even I hated the idea of having a menu item 😱 but left it just in case

**Comment by alexandrudima** [comment]
:+1: Looking forward to more PRs ! :heart:

**Pull request closed without merging**
