### PR TITLE
Re-enable the unused variables tslint rule for the hygiene task fixes #42157

### LINKED ISSUE #42157: Prevent committing files with unused variables
We used to block committing code with unused variables, when TSLint was making that check. Now we leave that task up to TypeScript, so the hygiene script won't catch unused variables anymore. This is too bad, since when committed and pushed, code containing unused variables will work and run, yet the build will fail.

Another point of view to this problem is that these unused variables are now considered to be compilation errors. We never prevented people from pushing code which is broken, in terms of compilation. So... this would be a no-op.

### PR DESCRIPTION
**Pull request by egamma**
This Pull request enables the tslint rule for unused-variables. This is done by performing the tslint checks in the context of a Typescript program/project with the tslint rule for unused-variables enabled. Since the checks have to be done in the context of a TS project I currently define the `src` folder to be this project, this means extensions and tests are no longer tslinted as part of the hygiene.

The tslint rule had some false positive issues in the tslint version 5.8, so this PR also updates tslint to version 5.9.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@egamma Looks good. Should we still keep the old tslint filter on the `test/**` and `extension/**` files?

**Comment by egamma** [comment]
@joaomoreno 

>Should we still keep the old tslint filter on the test/** and extension/** files?

The unused variable rule requires that linting is done in the context of a project. Currently the only project that hygiene knows about is the src project. It would be possible to add know how about the other projects in the test and extensions folder:
- in the test folder there is a single project for the smoke test
- in the extensions folder there is a project for each extension, that has a tsconfig.json (git, emmet, ...) about 10 of them.

Thinking about this again we should also run hygiene/tslint on the extensions. I´ll look into it.

**Comment by egamma** [comment]
@joaomoreno enabled linting of extensions and tests. I´ve also removed several unused variables in these extensions.

**Comment by joaomoreno** [comment]
Looks good to me!

**Comment by egamma** [comment]
@bpasero the tslint step does more work now and I measured 20% overhead on Windows. Can you point me to the commit that you think took 3-5 times? Then I will simulate this commit and measure again

**Comment by bpasero** [comment]
@egamma as someone that commits very often right after making a change, I really cannot work with this new behaviour and would like to disable it.

**Comment by egamma** [comment]
@bpasero agreed I´ve disabled it.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by joaomoreno** [comment]
Too bad... I think we're just going to have to bite unused variables as compiler errors, which we don't prevent from committing right now anyway.

**Pull request merged**
