### PR TITLE
Draft PR: Working on issue #211394

### PR DESCRIPTION
**Pull request by arup-chauhan**
Raising a draft PR to work on #211394

### CODE REVIEW

**Comment by Arup-Chauhan** [comment]
Hi @Tyriar , I have made this PR to work.

I wanted to ask, in the original issue was reported on a Linux OS machine.
Do I need to work on the Linux OS for it? I was thinking to refer the README, make the VS Code from source and start working

What do you suggest?

**Comment by Tyriar** [comment]
@Arup-Chauhan the fix for this will be entirely in the https://github.com/xtermjs/xterm.js repo, when it's done I'll update the `@xterm/xterm` module in vscode

**Comment by Tyriar** [comment]
You should be able to test and make the fix on any OS

**Comment by Arup-Chauhan** [comment]
> You should be able to test and make the fix on any OS

Thanks, I will get started on the work

**Pull request closed without merging**
