### PR TITLE
path: /vscode/src/vs/css.ts add new syntax and new comments

### PR DESCRIPTION
**Pull request by Abhishekkuntare**
path: /vscode/src/vs/css.ts

### CODE REVIEW

**Comment by Abhishekkuntare** [comment]
@microsoft-github-policy-service agree [company="{apk}"]

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by aeschli** [comment]
What is this PR for?

**Comment by alexdima** [comment]
We don't take formatting PRs

**Pull request closed without merging**
