### PR TITLE
don't use role or aria-label attributes so that contents get read out

### PR DESCRIPTION
**Pull request by jrieken**
fixes https://github.com/microsoft/vscode-internalbacklog/issues/4035

Edit by @meganrogge 
Before:

https://user-images.githubusercontent.com/29464607/234973839-b1cddd96-7b34-4894-961c-d904a0719e21.mov

After:

https://user-images.githubusercontent.com/29464607/234973870-f414dc47-2ff3-4b60-b465-461cc84c7428.mov

### CODE REVIEW

**Comment by jrieken** [comment]
@meganrogge can you please review and advise? @aiday-mar and I used aria-label and role to make these message element "important" but only removing all of those did encourage the screen reader to read the actual contents

**Review by aeschli — APPROVED** [review]

**Comment by meganrogge** [comment]
Works well 👍🏼

**Review by meganrogge — APPROVED** [review]

**Comment by aiday-mar** [comment]
This change appears to no longer read out the markdown message when it is rendered. I am wondering if we want that in light of [_3918_](https://github.com/microsoft/vscode-internalbacklog/issues/3918)?

**Comment by aiday-mar** [comment]
Agreed, I think adding an audio cue would make it clearer that some sort of response has been rendered in the IE

**Comment by meganrogge** [comment]
Yes, we will also need to play an audio cue when the response becomes available in the chat view. 

The closest thing we have to this is for task/notebook completion. I'll need to ask JooYoung why he thinks we should start playing the sound when the request is entered vs only playing it upon response.

**Pull request merged**
