### PR TITLE
Include new shell executables in traverseTree

### LINKED ISSUE #232424: Nu/julia/python detection is missing inclusion in SHELL_EXECUTABLES on Windows
Looks like the executable names are missing from here:

https://github.com/microsoft/vscode/blob/5295c9d541fa20a743cbc24672d6aa65ace24912/src/vs/platform/terminal/node/windowsShellHelper.ts#L21-L39

I think them missing here is sub shell detection won't work correctly and launching an application from the shell won't either.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #232424

Not yet tested

### CODE REVIEW

**Comment by anthonykim1** [comment]
I wonder if this would help resolve https://github.com/microsoft/vscode/issues/224325#issuecomment-2327164652 when you say " .. launching an application from the shell won't either." Perhaps julia.exe gets launched from the julialauncher.exe.

**Review by anthonykim1 — DISMISSED** [review]

**Comment by anthonykim1** [comment]
I see, I wonder if the executable is different from ARM windows. 
I've originally set this to julia.exe then switched to julialauncher.exe because I saw screenshot here when I was debugging on windows ARM: https://github.com/microsoft/vscode/pull/227724#issue-2508552556

**Comment by anthonykim1** [comment]
found and fixed root cause. Added more test

**Review by anthonykim1 — APPROVED** [review]

**Comment by Tyriar** [comment]
@anthonykim1 was that an executable that can start julia.exe? If so then it shouldn't need to be included.

**Comment by anthonykim1** [comment]
I think so, it was the executable I would get whenever I launched command "Julia REPL Restart".

**Pull request merged**
