### PR TITLE
Add toggle output auto-scrolling feature

### PR DESCRIPTION
**Pull request by ArtemGovorov**
As discussed in https://github.com/Microsoft/vscode/issues/12257#issuecomment-272423501.
The command is fully implemented, the action is ready but not exposed in UI (needs an SVG icon).

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for your PR! However this is adding too much methods on the output service and is also adding an unnecessery action. When I say unnecessry I mean it will only be used by one extension, thus I am questioning the benefit of this.
Also a UI visible action that would supress auto scrolling does not make sense for an editor also since our default behavior works for all use cases except for the wallaby extension (nobody else has raised concerns).

I am more in favor of a setting that suppresses auto scrolling in settings.json for all output channels. As that is a small change on our side and would make the wallaby scenario happy.
However I am also not 100% conviced on that.

@ArtemGovorov would it not be possible that the wallaby extension in your particular scenario shows the summary on the end, not at the beggining? So the user nicely sees the most important information at the end.

**Comment by ArtemGovorov** [comment]
Thanks for looking into this. Actually, all our extension needed was an API method to suppress scrolling for a specific output channel. I have only added this as a command+UI action because @jrieken [suggested it here during the discussion](https://github.com/Microsoft/vscode/issues/12257#issuecomment-272423501). Just the command works for us as well.

I can remove the UI action, and just leave one command so there'll be less code. Please let me know if you'd like the action to be removed.

> I am more in favor of a setting that suppresses auto scrolling in settings.json for all output channels. 

If the setting would allow to specify an **array of the output channel names** (to suppress the auto-scrolling for) - this would be a good solution. Because users may want to suppress the scrolling for some channels, but not for all channels.

> would it not be possible that the wallaby extension in your particular scenario shows the summary on the end, not at the beginning? So the user nicely sees the most important information at the end.

The output can be a pretty lengthy chunk, that can not be divided/re-arranged and has to be displayed as the whole, and reads from the top to the bottom, for example [Jest snapshot diff (or some other diff)](https://twitter.com/wallabyjs/status/819121381002489856), or a long error description/details. So if a user has the output panel of a small height (and not like a half of the screen), then they'll only see the end of the output and will have to scroll up anyway.

People may not be asking for the feature specifically because it may not be bothering them much (yet). I understand that it may look like it's only our extension needs it, but there has to be a reason all other editors/IDEs support it, for example [Visual Studio supports it](https://github.com/Microsoft/vscode/issues/12257#issuecomment-256802397) and its output channel looks very similar to VS Code output channel design (except this feature).

**Comment by isidorn** [comment]
Thnaks for your reply.
Visual studio supports a lot of things that vscode does not, the reason for that is that visual studio is an IDE an vscode is an editor. We do a lot of workarounds in the vscode side in order to be minimalstic and keep and sleek feel of the editor.

Due to that I would propose that you try some workaround on your end and only if that proves unsuccesful (users compalin here on GitHub) we can think about an alternative solution.

Due to this and my above comment closing this PR.

**Comment by ArtemGovorov** [comment]
> We do a lot of workarounds in the vscode side in order to be minimalistic and keep and sleek feel of the editor.

I'm sorry but I'm really struggling to see how adding this small and **invisible for users/UI** feature (that is just turning off another unwanted feature of auto-scrolling) makes the editor less sleek or less minimalistic. I was also suggesting an API method for the `OutputChannel`, which I also don't think will harm the minimalism of the UI in any way.

Before implementing the PR I have [asked the team about the preferred way](https://github.com/Microsoft/vscode/issues/12257#issuecomment-272423501) and @jrieken suggested the way I have implemented (which now turns out to be an unwelcome). 

I wouldn't be chasing it much or bothering to implement the PR if I didn't know it is something our users want. Being the most popular integrated [test runner/reporter for VS Code with 32.5k downloads](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode), it really makes me sad to see our users coming from other editors to find out that for the similar feature they now must be scrolling the output all the time. 

@isidorn @jrieken @egamma Guys, is there any way you could re-consider the decision? I'm happy to implement the feature the way you don't think it violates the minimalism. The only acceptable workaround for us would be to patch VS Code source code on start somehow (like I think the first icons extension did), but it's really ugly and maintenance heavy workaround.

**Comment by egamma** [comment]
Hi @ArtemGovorov. We have discussed this issue in the team again. Our conclusion was that adding a 'scroll lock' button to the output panel makes sense. This is a common idiom for output/console panels and it should also cover your scenario. 

With regard to the PR I suggest that you work with @isidorn.

**Comment by isidorn** [comment]
@ArtemGovorov as @egamma pointed out we have agreed on adding a 'scroll lock' button next to the 'clear output' button in the output panel for each output channel. We have also decided not to allow extension to change this, but each user can manually lock scrolling if he chooses.
It would be cool if the icon shows if the output is locked or not - similar to our Find in Selection button in the find widget. Which uses a native checkbox undearneath. An alternative would be to draw a border when it is active - similar to case sensitive find button in find widget

Would you be willing to update your PR such that it only adds this action to the output panel actions? If not, I can also do this on my end. Thanks!

@bgashler1 we will need a scroll lock icon both for light and dark theme that would go well next to the clear output icon.

**Comment by bgashler1** [comment]
@isidorn I just submitted a request our icon team.

**Comment by ArtemGovorov** [comment]
@egamma @isidorn Awesome, thanks!
I'll create another pull request with the change as I have accidentally trashed this one with a bad rebase.

**Comment by isidorn** [comment]
@ArtemGovorov sounds good
@bgashler1 thanks!

**Pull request closed without merging**
