### PR TITLE
Potential new formatter for userdata in serverless.

### LINKED ISSUE #114234: Paths to internal pseudofiles are incorrectly rendered as OS paths
1. `node ./resources/web/code-web.js`
2. open settings.json
3. search for text in the file
image

notice the label claims this file is in `~/User/settings.json` on MacOS, or `\\User\settings.json` on Windows. This is misleading, as those are real OS path formattings, but the file itself does not live there (I believe its really at vscode-userdata:///User/settings.json`)

we should instead label these like `User/settings.json (internal)` or something.

ref #112775

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #114234. 
image

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Alternatively, it might make more sense to change the default formatter to follow the either the `scheme:path` or `scheme://authority/path` formats, instead of right now the fallback seems to be `\\path` on windows or `~/path` otherwise. cc @bpasero I think you own that area?

**Comment by bpasero** [comment]
No, @isidorn

**Comment by isidorn** [comment]
@JacksonKearl thanks a lot for this PR. I thinks it makes good sense.
However I do not like where you register the formatter - you do it from `remote.contrubition` and this is not related to remote.
I suggest to simply move it somewhere around this file https://github.com/microsoft/vscode/blob/7a9bb5a44f9fc0dc51535959f6f15f8dd3d037cd/src/vs/workbench/services/userData/browser/userDataInit.ts#L247

So in the `userDataInit`.
You can introduce a new workbench contributions that would just regsiter the formatter.

@sandy081 as fyi

**Comment by JacksonKearl** [comment]
@isidorn my thinking was that if a remote is present, we do in fact want the existing formatting, as the user data does live on (the remote's) disk. So we'd only register this formatter if no remote is present. Alternatively, is there some way to assign priority to the formatters so that we'd fallback to this one if the remote one does not get registered?

**Comment by isidorn** [comment]
@JacksonKearl we always try to choose the most specific formatter based on matching rules. So idealy if the remote formatter is more specific it should take priority over this one. Best would be to try it out...

**Comment by JacksonKearl** [comment]
I realized the old approach would format the URI's even running on desktop with no remote extension host, so now I'm registering the formatter in the same place we assign the scheme to the in-memory provider (web.main.ts). Does this seem reasonable?

**Comment by isidorn** [comment]
@JacksonKearl thanks for updating the PR. Now we are registering the way how to handle user data URI in `web.main.ts`. Same as my preivous comment, this still feels to me very user data specific, and thus I think it should live in the userData directory. Was there some limitation that I missed why we can not put it there?
Also in the current PR you are introducing a `priority` flag. Is this really necessery? Can the user data just register it when needed (not in remote case)

Let me know what you think

**Comment by sandy081** [comment]
Agreed that this formatter shall go into userData dir and we can include this only in web. BTW we also user-data scheme in desktop (local) too.

**Comment by JacksonKearl** [comment]
I put it in `web.main.ts` because that's the same place we assign the scheme to the in-memory/indexeddb fsp, so to me it makes sense that we also assign a formatter for the scheme that represents it's in-memory/indexeddb. To me putting it away from where we register the in-memory/indexeddb fsp would be more confusing. 

Basically no matter what if we're running web.main.ts we want this formatter registered, but if we're running `userdataInit` we also need to be in a web context, *and* not have any remote context, which is bringing more logic into it that I think is needed.

**Comment by isidorn** [comment]
@JacksonKearl thanks for clariyfing.
Sounds good to me -> approved.

**Review by isidorn — APPROVED** [review]

**Pull request merged**
