### PR TITLE
Union the return value, add return type and remove useless declarations

### PR DESCRIPTION
**Pull request by ghost**
Change Logs：

Fix：

1) /vscode/src/vs/base/common/strings.ts： `compareIgnoreCase` should return you a value among -1,0,1 instead of a direct diff value between codeA and codeB.
2) /vscode/src/vs/base/common/color.ts：`_hue2rgb` should have a return type in ts.

Remove：
1) /vscode/src/vs/base/common/color.ts：Remove useless declarations.

### CODE REVIEW

**Comment by jrieken** [comment]
> compareIgnoreCase should return you a value among -1,0,1 instead of a direct diff value between codeA and codeB

Can you explain why?

**Comment by aeschli** [comment]
the brands (`_rgbaBrand`, ...) are typically there to make sure objects like {r,g,b,a} cannot be assigned to places where we want an instance of RGBA. There's no benefit of changing that. Also the extra new lines are not needed.
IMO The only change that is valid is the '_hue2rgb' return type.

**Comment by MaleDong** [comment]
@jrieken ：
Well, the reason is easy to understand：Considering that the `compareIgnoreCase ` is wholly returning you a value among -1,0,1 according to the context of codes. So if you return any negative number or positive number, which will destroy the tule. So it's better to add this.

@aeschli ：Thanks but I've read through the whole codes, and I haven't found anything related to this property yet……So you mean you'll use this in the future but not submit yet?

**Comment by jrieken** [comment]
>  So if you return any negative number or positive number, which will destroy the rule. 

What kind of rule is that? The rule for compare-functions is: `0` means equal, negative values mean the first operand is smaller than the second, and positive values mean the first operand is greater then the second. Limiting that to [-1,0,1] is just a special case of this.

**Comment by aeschli** [comment]
@MaleDong the property is not referenced but only used by the TypeScript compiler to distinguish the types of objects.

**Comment by MaleDong** [comment]
@jrieken ：First I have to say that your codes are right in logic. However it would be better if we union the return value to -1,0,1, which makes us easy to tell which string is larger in ASCII code.

Of course if you think it's NOT necessary, you can close my submit.

**Pull request closed without merging**
