### PR TITLE
Uninstall telemetry

### PR DESCRIPTION
**Pull request by joaomoreno**
The Marketplace would like to offer extension authors more telemetry data. One of those data points is the number of uninstalls.

### CODE REVIEW

**Comment by jens1o** [comment]
Why do you need to get that data? I thought you're not that type of data kraken like other big companies, but I don't see where and why this is needed...

**Comment by joaomoreno** [comment]
It's become a requirement for being a client of the Visual Studio Marketplace.

**Comment by Chillee** [comment]
@joaomoreno Are there any other kinds of telemetry data available to extension authors now?

**Comment by joaomoreno** [comment]
@Chillee This is what's available: https://marketplace.visualstudio.com/manage

**Pull request merged**
