### PR TITLE
Add 200 debounce time for mouse to find hover before hiding it

### LINKED ISSUE #228121: Special case scroll bar slider when evaluating whether to hide the hover
This issue has come up several times, maybe in the extensions view (cc @sandy081) and the new SCM graph (cc @lszomoru):

Image

The current solution is to add the hover hint explicitly which makes it show up as a way to reliably allow the user to access the hover:

Image

While hover locking is a neat feature, some aren't aware of it and therefore the ugly hint is required.

After a chat with @benibenj, I think the solution here is to allow some timeout for the mouse to reach the hover after mouse leave, say ~100ms to still remain responsive. In order to keep the delay as small as possible generally, we could also require the user of the hover API to provide an option to explicitly opt in to this behavior.

This is basically the proposal without the custom element or option part:

Image

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #228121

Early impressions of this is that it works quite nicely

@benibenj could you test this out? I tested a few things on my mac but want to also look on my Windows machine before i merge. Also I found this part of managed hover to be kind of hard to understand:

https://github.com/microsoft/vscode/blob/b3e8a4c9ef60243cde456631b0cd9d998e538f3b/src/vs/editor/browser/services/hoverService/hoverService.ts#L209-L277

Especially when it feels like it conflicts quite a bit with the HoverWidget largely managing its own lifecycle here:

https://github.com/microsoft/vscode/blob/b3e8a4c9ef60243cde456631b0cd9d998e538f3b/src/vs/editor/browser/services/hoverService/hoverWidget.ts#L238-L242

### CODE REVIEW

**Comment by benibenj** [comment]
This seems to break hovering between different items

https://github.com/user-attachments/assets/6bd8d30e-34c1-4eb4-bcc6-14f39c5338c8

**Comment by benibenj** [comment]
I also find the managed hover code to be hard to understand. I think it was initially written by someone for the resource/icon labels but was not maintained and a lot of different members made small changes to it to make their feature work. Also, I think there are a lot of small tricks to make it accessible. This makes it hard to rewrite but it would be nice to try.

**Comment by Tyriar** [comment]
> This seems to break hovering between different items

Probably weird lifecycle interaction between widget and managed, will have a look

**Comment by Tyriar** [comment]
Somewhere along the way the hover identity is being set to a stringified object 😕  Screenshot 2024-10-29 at 6 01 28 am

**Comment by Tyriar** [comment]
Here:

Screenshot 2024-10-29 at 6 02 52 am

**Comment by Tyriar** [comment]
@benibenj could you give it another try now? I don't think it regresses now

**Review by benibenj — APPROVED** [review]

**Comment by benibenj** [comment]
Great find! Seems to work very nicely now

**Pull request merged**
