### PR TITLE
Added `explorer.sortOrderNumeric` option to sort `files with numbers in natural order`.

### PR DESCRIPTION
**Pull request by id-aditya**
Adds ability for explorer to sort file numbers in natural order, example 10 comes after 2.

### CODE REVIEW

**Comment by id-aditya** [comment]
> @id-aditya please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="id-aditya"]

**Comment by id-aditya** [comment]
@microsoft-github-policy-service agree company="id-aditya"

**Comment by id-aditya** [comment]
> @id-aditya the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree

**Comment by id-aditya** [comment]
@microsoft-github-policy-service agree

**Comment by id-aditya** [comment]
agree

**Comment by id-aditya** [comment]
@lioman @lramos15 Took hints from the previous PR, what's the chance you can help me publish this?

This PR sorts file in explorer from this:
- base16.tsx
- base32.tsx
- base64.tsx
- base8.tsx

To this:
- base8.tsx
- base16.tsx
- base32.tsx
- base64.tsx

Thanks

**Comment by id-aditya** [comment]
@roblourens

**Comment by id-aditya** [comment]
@bpasero

**Review by id-aditya — COMMENTED** [review]
Looks good enough.

**Comment by id-aditya** [comment]
@lramos15
### Explanation of the "explorer.sortOrderNumeric" Feature

In the current version of VS Code, the `"explorer.sortOrder": "filesFirst"` setting allows for sorting files and folders in a specific order but does not naturally sort files that contain numbers. For example, files like `file1.txt`, `file2.txt`, and `file10.txt` are sorted as `file1.txt`, `file10.txt`, `file2.txt`, which is not intuitive for many users who expect numerical order.

To address this issue, I have introduced a new setting called `"explorer.sortOrderNumeric"`. When this option is set to `true`, files that contain numbers will be sorted in a natural numeric order. With this setting enabled, files will be sorted as `file1.txt`, `file2.txt`, `file10.txt`, providing a more intuitive and user-friendly experience.

Here’s how the settings would work together:

- `"explorer.sortOrder": "filesFirst"`: This setting still controls the general sorting behavior of files and folders.
- `"explorer.sortOrderNumeric": true`: This setting applies a natural numeric sort order to the files.

This addition aims to enhance the usability of file sorting in the Explorer, particularly for users who work with files named with numbers.

**Comment by id-aditya** [comment]
### Update on the Sorting Issue

Initially, I was using `"explorer.sortOrderLexicographicOptions": "unicode"`, which caused issues with the sorting order of files. After switching to `"explorer.sortOrderLexicographicOptions": "default"`, the sorting problem was resolved.

Given that the default lexicographic option addresses the issue, the need for this PR might be reconsidered. However, I’m leaving the final decision to the maintainers on whether to close the PR or keep it open for potential future scenarios where `"unicode"` sorting might still be preferred.

Thank you for reviewing this contribution.

**Comment by lramos15** [comment]
Closing for now as we hope to make explorer sorting extensible in the future rather than continuing to expand the core sort options.

**Pull request closed without merging**
