### PR TITLE
Open Editors respect `workbench.editor.labelFormat`

### LINKED ISSUE #61253: Open Editors respect `workbench.editor.labelFormat`
The "Open Editors" tab shows the beginning of the path relative to my workspace, which gives me this:

screen shot 2018-10-18 at 9 57 49 am

I can't tell which file is which based on that.

This issue has already been brought up here: https://github.com/Microsoft/vscode/issues/53135, but that one has been locked and closed.

@isidorn you closed the other issue because "we show paths like that in all of vscode" - but that's not true. There is a setting to fix this behavior on tabs. The setting is called "Workbench > Editor: Label Format" and the value that I like is "short". You can see it working well here:

screen shot 2018-10-18 at 10 00 18 am

Maybe that same setting should also affect the 'Open Editors' section?

### PR DESCRIPTION
**Pull request by Rekicho**
Fixes #61253

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for your PR. 
However I personally do not like how this is tackled. It seems like we are doing double the work by `root.setEditor` and than `root.setLabel`
setEditor should already take care of this. And inside that implementation we should look into configuration for displaying labels imho

**Comment by isidorn** [comment]
Ok, this looks better now. However this week we are wrapping up our milestone and are only accepting limited changes.
Due to that I plan to merge this in next week for the december milestone.
@Rekicho did you test this out? Does it works as expected?

**Comment by Rekicho** [comment]
@isidorn Yes, i did test and as far as I can tell it is working properly.
Here are some screenshots: 

default
long
medium
short

The only doubt I have is what the default setting should do, i'm currently using it as the medium as it seems to be the way vscode is displaying the path prior to this change, like this:

current

**Comment by isidorn** [comment]
Great, thanks. Will try it out next week!

**Comment by isidorn** [comment]
@Rekicho The default setting should be the current behavior.
The code looks good.

When I try it out the medium and long have the same behavior, and for short I actually get some descripion (where for medium and long I do not see a difference).
@bpasero @Rekicho though we also behave like this in the tabs title. Can you just clarify this behavior and setting for me please?

label

**Comment by bpasero** [comment]
@isidorn please consider to not use `getEditorPartOptions()`, it seems like overkill for this purpose because all you want is a single setting and this is potentially called for each entry in the open editors list. I also feel it is a bit of layer violation (even though not reported as warning) from `vs/workbench/browser/labels.ts` to `src/vs/workbench/browser/parts/editor/editor.ts` which is about parts.

Also, keep in mind that the logic of `workbench.editor.labelFormat: default` is not easily implemented. For that you need to loop over each label and check for duplicates: https://github.com/Microsoft/vscode/blob/3a88dae/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L693

**Comment by Rekicho** [comment]
@bpasero The thing is, on tabs the "default" is not to have any description shown unless there are duplicates. But on open editors, the "default" (what vscode currently is doing) is to show the path relative to the workspace. So shouldn't the default on open editors be to show the relative path instead of showing nothing (unless there are duplicates)?

**Comment by bpasero** [comment]
@Rekicho yeah I was not suggesting to do the same as tabs actually

**Comment by isidorn** [comment]
@Rekicho please try react on feddback from @bpasero when you find the time

**Comment by Rekicho** [comment]
Ok, so I have removed the `getEditorPartOptions()` call and moved the change back to openEditorsView so I can check for duplicates. @bpasero How should I deal with `workbench.editor.labelFormat: default` ? 
Equal to `workbench.editor.labelFormat: medium` except when there are duplicates, in which case the description should be the distinguishing folder?

**Pull request closed without merging**
