### PR TITLE
Enable grabbing translations from an alternate location for server distro/serverful scenarios

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
#### Server distro

enables server distro to use the new `baseUrl` configuration of the `nlsLoader` so that if `nlsBaseUrl` is defined in a product.json, you can get translations for core strings similar to how insiders.vscode.dev works today.

https://user-images.githubusercontent.com/2644648/170383888-c6efc558-9ef8-4fa4-802b-592653990349.mp4

after this goes in I will update the product.json

### CODE REVIEW

**Comment by lramos15** [comment]
I'll close this since I reviewed #150418 feel free to let me know if you would prefer I review the two separate PRs instead

**Review by lramos15 — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
With all that said, given this solution works and a similar solution is already in place in vscode.dev, I will merge this in and discuss with folks out of band.

**Comment by alexdima** [comment]
:+1: for adding this as a build-time loader configuration for our CDN / web bits.

> I'm not sure if it's truly free because CSP would need to be updated to reflect the nlsBasePath that has been added.

Why was [this change](https://github.com/microsoft/vscode/pull/150436/files#diff-86987149dfdb33da80e536afb11dbf1b18ab7137112ed164cfd5abc524439b72R348) necessary? Normally the loader uses `<script>` tags to load code (not `fetch`), so I would have thought that touching the CSP would not be necessary.

**Comment by TylerLeonhardt** [comment]
@alexdima coming back to your question... it looks like it _is_ needed. I wonder how I can apply this at build time... if at all...

image

**Comment by alexdima** [comment]
:+1: You're right! I got confused and mixed things up, you're right the CSP change is necessary to use `vscode-unpkg.net` as a script source!

**Pull request merged**
