### PR TITLE
Added `ariaContainerElement` to `IStandaloneEditorConstructionOptions`

### PR DESCRIPTION
**Pull request by crackalak**
This PR fixes issues with ARIA when using the standalone editor in shadow DOM: https://github.com/microsoft/monaco-editor/issues/619

### CODE REVIEW

**Comment by crackalak** [comment]
To test, run monaco editor shadow dom test: https://github.com/microsoft/monaco-editor/pull/2644

**Comment by simonh1000** [comment]
I'm trying to take advanatge of this change. My package.json has `"monaco-editor": "^0.28.1"` which seems to be the latest, but does not have this - oh so welcome - commit. Any advice?

**Comment by crackalak** [comment]
@simonh1000 this change hasn't been released yet, it's part of the [September 2021](https://github.com/microsoft/vscode/milestone/161) milestone, so you'll have to join me in waiting!

**Comment by simonh1000** [comment]
Seems to work exept for 
image

**Comment by alexdima** [comment]
@simonh1000 What is the problem? I'm not sure I understand from the screenshot. The property `ariaContainerElement` appears to be defined in the `IStandaloneEditorConstructionOptions` interface in the `.d.ts` that we ship.

**Pull request merged**
