### PR TITLE
drag&drop a VSIX file on the extensions viewlet

### LINKED ISSUE #12090: Implement VSIX drag and drop to extension viewlet
VSIX can now be installed via `code --install-extension extension.vsix` and via the action in the dropdown of the extension viewlet.

All that's left is the drag and drop onto the viewlet itself.

@bpasero Need your help here since the workbench seems to gobble the whole area for the drop feedback 👎

### PR DESCRIPTION
**Pull request by lszomoru**
This PR fixes #12090

Add the capability to drag&drop a VSIX file on the extensions viewlet and have it installed. While there is still room for improvement as well as some code duplication that I would like to explore removing, I want to get some early feedback on these changes. Thanks!

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Just tested this. Pretty cool! Some comments:

- There seems to be drop feedback even when I drag a non `.vsix` file onto the viewlet. Even when dropping it I see the viewlet switching to the `@installed` state. Can we prevent showing the drop feedback at all for non `.vsix` files? Else, can we show an error/warning if the user drops something which isn't a `.vsix` onto the viewlet?
- When dropping a corrupt `.vsix` file, there is no visual error to the user. The devtools console does print an error.
- For @sandy081: When I first install a `.vsix` I see a success message. When I then try to install the same `.vsix` again I get `Please reload Visual Studio Code to complete installing the extension GitHub Sharp Theme.`. This is very strange, and I believe a bug in the current VSIX installation code, right?

**Comment by sandy081** [comment]
> When I first install a .vsix I see a success message. When I then try to install the same .vsix again I get Please reload Visual Studio Code to complete installing the extension GitHub Sharp Theme.. This is very strange, and I believe a bug in the current VSIX installation code, right?

No, this is expected. When you install first time extension is enabled immediately (no reload required) and hence you see `Completed Installing...` message. Second time you need to reload to enable the newly installed/updated extension, hence reload message is shown.

**Comment by joaomoreno** [comment]
> > When I first install a .vsix I see a success message. When I then try to install the same .vsix again I get Please reload Visual Studio Code to complete installing the extension GitHub Sharp Theme.. This is very strange, and I believe a bug in the current VSIX installation code, right?
> 
> No, this is expected. When you install first time extension is enabled immediately (no reload required) and hence you see `Completed Installing...` message. Second time you need to reload to enable the newly installed/updated extension, hence reload message is shown.

But it is still confusing. How about:

- If you reinstall the same VSIX with the same version number, the message should be something like `Reinstalled EXTENSION 1.2.3. Please reload Visual Studio Code to activate the extension again`
- If you reinstall the same VSIX with a different version number, the message should be something like `Installed EXTENSION 1.2.3. Please reload Visual Studio Code to activate the extension again`

**Comment by lszomoru** [comment]
thanks for the feedback @joaomoreno. Here are some comments:

> There seems to be drop feedback even when I drag a non .vsix file onto the viewlet. Even when dropping it I see the viewlet switching to the @installed state. Can we prevent showing the drop feedback at all for non .vsix files? Else, can we show an error/warning if the user drops something which isn't a .vsix onto the viewlet? 

I have done some research on this but as far as I could tell in the `dragEnter` and `dragOver` handlers you do not have access to the data that is being dragged (ex: the extensions of the files) due to security reasons. Due to this I can't really check the extensions of the files that are being dragged and display the overlay accordingly. Let me know if I am missing something. 

> When dropping a corrupt .vsix file, there is no visual error to the user. The devtools console does print an error.

That is certainly a problem. We are just executing the existing "Install VSIX" code path so let me take a look at that.

**Comment by joaomoreno** [comment]
> I have done some research on this but as far as I could tell in the `dragEnter` and `dragOver` handlers you do not have access to the data that is being dragged (ex: the extensions of the files) due to security reasons. Due to this I can't really check the extensions of the files that are being dragged and display the overlay accordingly. Let me know if I am missing something.

Yeah I vaguely remember something like that. 👍

**Comment by sandy081** [comment]
@joaomoreno Makes sense about improving the message

**Comment by lszomoru** [comment]
@sandy081, can you please confirm that you will improve the message outside the scope of this PR? Thanks!

**Comment by sandy081** [comment]
Sure

**Comment by lszomoru** [comment]
> When dropping a corrupt .vsix file, there is no visual error to the user. The devtools console does print an error.

@joaomoreno, I have pushed another commit to address this as we have discussed.

**Review by joaomoreno — APPROVED** [review]
Works great!

**Review by sandy081 — APPROVED** [review]

**Comment by sandy081** [comment]
LGTM

**Comment by lszomoru** [comment]
🙏🏻

**Pull request merged**
