### PR TITLE
fix https://github.com/microsoft/vscode/issues/115353

### PR DESCRIPTION
**Pull request by jrieken**
Cherry pick the fix for #115353 for the 1.53 release

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
I verified this fixes the issue. However I am not sure where the `18px` comes from. Note that this changes the container height of breadcrumbs to 18px entirely:

image

vs before

image

Not sure if this has an impact on vertical alignment across OS.

**Comment by bpasero** [comment]
Looks like a similar rule exists when tabs are enabled but with `22px`:

https://github.com/microsoft/vscode/blob/bb6014df3b4312272ec741be1d794649f6a0b71e/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css#L386-L388

**Comment by jrieken** [comment]
> Looks like a similar rule exists when tabs are enabled but with 22px:

Yes - that is with tabs enabled and then things are larger

**Comment by jrieken** [comment]
> Note that this changes the container height of breadcrumbs to 18px entirely:

That's interesting... The rule only targets `::before` elements

**Comment by bpasero** [comment]
@jrieken I think since the breadcrumbs itself do not set any height, it will inherit the height from any child element that sets the height unless there is another element overriding it. 

I did not see an alignment issue on macOS though.

**Pull request merged**
