### PR TITLE
#55: Batch results for IPC

### PR DESCRIPTION
**Pull request by chrmarti**
Speeds up file search, especially under Windows. On my Windows machine with 224k results, the duration until the unsorted results were available for fuzzy-sorting went from ~35s down to ~13s. (On my OS X machine it went from ~15s down to ~13s.)

### CODE REVIEW

**Comment by joaomoreno** [comment]
@chrmarti LGTM, just not sure whether we really need that extra code in `ipc.test.ts` and `testService.ts`. Is it testing anything that the current tests aren't already testing? Besides given the strange `xtest`, it appears that they aren't really run at all, but they are supposed to be enabled on demand. If that's true, and you'd still like to keep them, I suggest to move all that into its own `ipcPerf.ts` file. You could then _enable_ the tests by renaming it to `ipcPerf.test.ts`.

Assigning for review to @sandy081, since I believe he is the latest search owner.

**Comment by sandy081** [comment]
Trying to understand the batching here..  looks like we are batching the progress calls now. Before in raw search class we call progress callback on single item and now we call progress callback on batch. And in Search service class we again do progress callback on each item. Would be interesting to know if you can share more details here.

**Comment by chrmarti** [comment]
@joaomoreno I'll move them out to a separate file as you prefer. My intent is to keep the code for measuring the performance around, but not run it by default, because there are no useful assertions we can add to it.

**Comment by joaomoreno** [comment]
Then yeah, I suggest something in the lines of `ipc.perf.test.ts`.

**Comment by chrmarti** [comment]
@sandy081 the batching is limited to the point where we send the data to the other process. That improves the performance by avoiding some of the overhead of IPC.

There will likely be more changes in the area, possibly sending batches of results as progress all the way up, but I first need to investigate in detail to be sure.

**Comment by sandy081** [comment]
@chrmarti Got it. You are minimizing the number of IPCs between Search client and Search service and is good idea. 

LGTM

**Pull request merged**
