### PR TITLE
Fixed tab switch too sensitive when scrolling

### LINKED ISSUE #96409: Trackpad: Tab switch on mouse scroll: horizontal scrolling sensitivity too high
Refs: https://github.com/microsoft/vscode/issues/95952

1. "workbench.editor.scrollToSwitchTabs": natural
2. Have a mouse with horizontal press
3. Horizontal scroll is too senstivie in the tab area and seems pretty useless due to that

Vertical scroll works just fine. And horizontal scroll in the editor has good sensitivity so maybe you could check with Alex how he handles the horizontal scroll.

### PR DESCRIPTION
**Pull request by Andre-Fonteles**
This PR fixes #96409 - Trackpad: Tab switch on mouse scroll: horizontal scrolling sensitivity too high.

### CODE REVIEW

**Comment by Andre-Fonteles** [comment]
Hello, I'm new here. Sorry, but I'm not sure why the VS Code checking did not pass. Any thoughts on how I could fix that? Thanks, and hope I'm able to contribute.

**Review by bpasero — CHANGES_REQUESTED** [review]
This follows the same approach as https://github.com/microsoft/vscode/pull/97361 and has the same issues as I commented there earlier.

**Comment by Andre-Fonteles** [comment]
Hi, bpasero. Thanks for taking your time to take a look at my PR. I realize that my code looks similar to the one at #97361 (specially after I had to remove some features to prevent "violating the layer"), but there is a fundamental difference between the two.

#97361 would reset the time past between the two events even when the event would not be triggered/handled. That would incur in events being lost. I only reset the time when an event is actually triggered and handled.

So, I'm assuming, and hoping, that you noticed the similarity between the two PR and didn't bother to try my branch. But I think that if you actually try my code you will see the difference. At least, I tried both and #97361 was indeed losing some events (which I couldn't see in my approach).

I would love to hear what you think again!
Thanks,

**Comment by bpasero** [comment]
Oh I tried your change locally on my mac with touchpad and felt that sometimes when scrolling it would scroll to the second tab and then back to the first.

**Comment by Andre-Fonteles** [comment]
Thanks, again for your feedback. I believe I fixed this issue in addition to the "tab switching too fast" in this new PR. The new code adds a second threshold, this time for the combination of deltaX and deltaY.

**Comment by bpasero** [comment]
@Andre-Fonteles I really like how you solved this for the mac touchpad, works great. However I feel now it works less than ideal for a normal mouse with a scroll button. Any chance you can try also with a normal mouse?

**Comment by Andre-Fonteles** [comment]
@bpasero, thanks for the feedback/encouragement. I'll try to improve the scrolling with a normal mouse.

**Comment by bpasero** [comment]
Sounds good, maybe you can find a way to tell a normal mouse scroll apart from a touch scroll.

**Comment by Andre-Fonteles** [comment]
I leveraged deltaX and deltaY to increase mouse scrolling responsiveness. It also increased touchpad responsiveness when the user scrolls faster (hopefully it is something desirable). Sorry for bothering so much!

**Comment by bpasero** [comment]
No problem. Is it possible that you could cleanly apply your change in a new PR on top of `master` branch? I see many unrelated commits coming in.

**Comment by Andre-Fonteles** [comment]
I'll do it right now.

**Comment by Andre-Fonteles** [comment]
Here is the new PR #112034.

**Pull request closed without merging**
