### PR TITLE
Support for uninstalling extensions given paths to their .vsix files

### PR DESCRIPTION
**Pull request by fabiospampinato**
Fix for #33106.

I tried to touch as few things as possible and to reuse already available functions. Is it good enough?

I got a `/Users/fabio/Dropbox/Projects/vscode/src/vs/code/node/cliProcessMain.ts is not formatted` trying to commit the changes, I've no idea what that means.

### CODE REVIEW

**Comment by joaomoreno** [comment]
> I got a /Users/fabio/Dropbox/Projects/vscode/src/vs/code/node/cliProcessMain.ts is not formatted trying to commit the changes, I've no idea what that means.

It means you should run `Format Document` before staging. In the team we all have `"editor.formatOnSave": true` in order to have the files always formatted.

**Comment by fabiospampinato** [comment]
Thanks for the info.

It should be properly formatted now.

**Comment by fabiospampinato** [comment]
@joaomoreno Is this PR going to get merged anytime soon?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
