### PR TITLE
Minimap: Settings for background and text opacity

### PR DESCRIPTION
**Pull request by naclonts**
Adds two new settings:

* `editor.minimap.backgroundAlpha` - controls opacity of the minimap's background
* `editor.minimap.textAlpha` - controls opacity of the minimap's text (characters and blocks)

Both settings default to the current behavior of complete opacity. 

These features are requested in [#32581](https://github.com/Microsoft/vscode/issues/32581). An example of how this could look (with box shadow removed, as well):
image

### CODE REVIEW

**Comment by cuzox-sf** [comment]
I need this in my life

**Comment by gsemet** [comment]
+1

**Comment by nairb2018** [comment]
+1 Need this!

**Comment by alexdima** [comment]
Thank you, but I have just merged #58324. The background will work via a theme color, e.g.:

```
"workbench.colorCustomizations": {
    "minimap.background": "#ffffff33"
},
```

**Comment by kokopelli314** [comment]
Thanks @alexdima!

**Comment by opensas** [comment]
Anybody knows in which version will it be available?

**Comment by alexdima** [comment]
@opensas It is available in the insiders build of vscode, and will be available in the February 2020 Stable release (that is the milestone that https://github.com/microsoft/vscode/pull/58324 is assigned to).

**Comment by SimonGLM** [comment]
I think think #58324 misses the intentions of this PR as the example provided by @alexdima not only renders the minimap in a light grey, but also renders the text transparent.

Screenshot from 2020-03-12 15-19-54

One possible workaround is to use the backgroundcolor and then adding the alpha to it. This effectively leaves the background unchanged and only changes the opacity of the text.

My ideal solution would be to be able to control the backgroundAplha and the textAlpha independently of one another, as suggested by @kokopelli.

**Comment by alexdima** [comment]
I revived this PR in https://github.com/microsoft/vscode/pull/132681 (I could not reopen it because or default branch is now called `main`).

**Pull request closed without merging**
