### PR TITLE
Allows extension install and uninstall command execution to throw exceptions back to caller

### LINKED ISSUE #88713: Executing workbench.extensions.installExtension command with an invalid extension ID\Path swallows all exceptions
- VSCode Version: 1.41.1
- OS Version: Windows 10 (Build 19546(
We have a private extension that cannot be placed in the private gallery and we have our own update mechanism for our extension.

Previously it was re-launching VSCode (new process) to install\update the extension but it was pointed out to us that executing the ''workbench.extensions.installExtension' command also works. (The ms-vscode.cpptools extension does this already). However, while ensuring that this technique would work for our extension, I discovered that exceptions from the command implementations in src\vs\workbench\contrib\extensions\browser\extensions.contribution.ts where being "logged" but not "re-thrown" to the command executor.

We would like to leverage this command (instead of having to re-spawn VSCode) but we also have a very strong desire to know when things fail, so we haven't converted our code yet.

Steps to Reproduce:

```TypeScript
try {
            await commands.executeCommand('workbench.extensions.installExtension', Uri.file('c:\\windows\\system32\\ntdll.dll'));
} catch (e) {
   console.log(JSON.stringify(e));
}
```

Does this issue occur when all extensions are disabled?: Yes

Possible fix is to pass in an optional boolean parameter to re-throw the error if the users desires:

I'll issue a pull request for this fix and we can go from there.

```TypeScript
CommandsRegistry.registerCommand({
	id: 'workbench.extensions.installExtension',
	description: {
		description: localize('workbench.extensions.installExtension.description', "Install the given extension"),
		args: [
			{
				name: localize('workbench.extensions.installExtension.arg.name', "Extension id or VSIX resource uri"),
				schema: {
					'type': ['object', 'string']
				}
			},
			{
				name: localize('workbench.extensions.installExtension.arg.throwOnFailure', "Indicates whether to re-throw any exception as well as log it"),
				schema: {
					'type' : 'boolean'
				}
			}
		]
	},
	handler: async (accessor, extensionId: string | UriComponents, throwOnFailure?: boolean) => {
		const extensionManagementService = accessor.get(IExtensionManagementService);
		const extensionGalleryService = accessor.get(IExtensionGalleryService);
		try {
			if (typeof extensionId === 'string') {
				const extension = await extensionGalleryService.getCompatibleExtension({ id: extensionId });
				if (extension) {
					await extensionManagementService.installFromGallery(extension);
				} else {
					throw new Error(localize('notFound', "Extension '{0}' not found.", extensionId));
				}
			} else {
				const vsix = URI.revive(extensionId);
				await extensionManagementService.install(vsix);
			}
		} catch (e) {
			onUnexpectedError(e);
			if (throwOnFailure) {
				throw e;
			}
		}
	}
``` TypeScript

### PR DESCRIPTION
**Pull request by GabeDeBacker**
This PR fixes #88713

We have a private extension that cannot be placed in the private gallery and we have our own update mechanism for our extension.

Previously it was re-launching VSCode (new process) to install\update the extension but it was pointed out to us that executing the ''workbench.extensions.installExtension' command also works. (The ms-vscode.cpptools extension does this already). However, while ensuring that this technique would work for our extension, I discovered that exceptions from the command implementations in src\vs\workbench\contrib\extensions\browser\extensions.contribution.ts where being "logged" but not "re-thrown" to the command executor.

This change adds an optional parameter to the install and uninstall extension command that will re-throw the exception to the caller if specified.

The optional parameter was added so as to not change the existing behavior (which can be discussed).

### CODE REVIEW

**Comment by GabeDeBacker** [comment]
@sandy081 - When creating this fix I did consider just re-throwing the exception rather than adding an additional parameter to the command. I decided to go with an additional parameter rather than change the behavior of the existing command as we probably don't know all the consumers of the API.

**Comment by sandy081** [comment]
Good point, but I would throw the error without having an additional parameter and better the callers to handle the error if they are not yet which I think is not too many.

**Comment by GabeDeBacker** [comment]
@sandy081  - Removed the parameter and re-tested our extensions code. Thanks for the quick reply!

**Review by sandy081 — COMMENTED** [review]
Can you please revert the rename changes. Lesser the changes easier to review 😄

**Comment by GabeDeBacker** [comment]
@sandy081  - Certainly, removed renames

**Review by sandy081 — APPROVED** [review]

**Comment by GabeDeBacker** [comment]
@sandy081 - Any ideas on why the checks are failing? They seem to be failing, well, randomly and not necessarily anywhere near my changes. I'll merge with master (again) and keep trying? Not sure what your requirements are for merging this back to master with these failures occuring.

**Comment by GabeDeBacker** [comment]
@sandy081 - Wondering when this will get merged back in? (Thanks!)

**Pull request merged**
