### PR TITLE
Run our custom eslint rules using ts-node

### PR DESCRIPTION
**Pull request by mjbvz**
Use `ts-node` to run our custom eslint rules.  This lets us delete the pre-compiled js. It also means you can don't have to compile the rules while editing them

As part of this change, I've also switched us to using an eslint plugin instead of a rulesDir. This is now the preferred way to ship custom rules

### CODE REVIEW

**Comment by jrieken** [comment]
LGTM but I believe there is specific build performance reason to have these files as JS in the repo. Adding @joaomoreno and @alexdima to comment on that

**Comment by mjbvz** [comment]
If performance is a concern, we could also try enabling ts-node's `transpileOnly` option or use `swc` to switch to using that compiler. This would skip the expensive type checking process

**Comment by joaomoreno** [comment]
Yeah, it was a performance choice. So, seeing runtime numbers here would help.

**Comment by mjbvz** [comment]
@joaomoreno Some quick performance tests using `time yarn eslint`

- Main: `yarn run eslint  101.58s user 5.47s system 119% cpu 1:29.77 total`

- With TS Node: `yarn run eslint  108.45s user 5.33s system 124% cpu 1:31.41 total`

- With TS Node (transpile only): `yarn run eslint  107.12s user 5.03s system 123% cpu 1:30.46 total`

- With TS Node (swc): `yarn run eslint  101.08s user 4.93s system 124% cpu 1:25.26 total`

There may be some small performance gains from switching from eslint's `rulesDir` like we do on main, to using a plugin like this branch does

**Comment by joaomoreno** [comment]
Yeah `transpileOnly` seems like the best balance here. But we'll still be type checking these scripts in some CI job, right?

**Review by jrieken — APPROVED** [review]

**Comment by mjbvz** [comment]
@joaomoreno Type checking is done by the `npmCheckJs` script under `build`. However that is currently not run as part of CI. If we think running this makes sense, I'll take a look at enabling it in a separate PR

**Pull request merged**
