### PR TITLE
re-rendering Markdown preview when updated extra configurations provided by extension

### PR DESCRIPTION
**Pull request by vitaliymaz**

### CODE REVIEW

**Comment by vitaliymaz** [comment]
fixes #70936

**Comment by mjbvz** [comment]
Thanks for looking into this. I feel this is an overly complicated solution however that is too tried to the use case from #70936.

How about just making `markdown.preview.refresh` invalidate the cached document and then refresh the markdown content? That way, the extensions themselves decide when to re-render.

**Comment by vitaliymaz** [comment]
@mjbvz, I've updated my fix. Now refresh command just cleans cache before an update.

**Comment by mjbvz** [comment]
Thanks! This will be in the first 1.34 insiders builds and is scheduled to go out with the April release

**Pull request merged**
