### PR TITLE
Ball Breaker

### PR DESCRIPTION
**Pull request by TemplateGamesInc**
Ball Breaker

This PR fixes #

### CODE REVIEW

**Comment by TemplateGamesInc** [comment]
well I hope the game works

**Comment by roblourens** [comment]
Hi @TemplateGamesInc, I'm sure it's a cool game, but I'm not going to add it to VS Code 😁

**Comment by TemplateGamesInc** [comment]
Ok I’m fine with that but I don’t know if it works...

**Comment by andykdy** [comment]
Wow Templates, would've loved to play your... Ball Breaker (???) game.
There are a lot of resources online so take the time to **level up** your skills by learning how to code.
You'll be making great games in no time, and maybe you'll find your contribution in VS Code one day too. 


https://www.codecademy.com/learn/introduction-to-javascript
https://www.learn-js.org/
https://learnjavascript.online/

**Pull request closed without merging**
