### PR TITLE
fix: Close #187795, Language pack files for some extensions not found

### LINKED ISSUE #187795: Language pack files for some extensions not found
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
版本: 1.81.0-insider
提交: d568855b2a4ef75716cdaa9a52da5315f5100a5d
日期: 2023-07-12T11:13:11.418Z
浏览器: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
- OS Version: Mac os 12.2.1 (21D62)

Steps to Reproduce:

1. Open `https://insiders.vscode.dev/`
2. Switch  Configuration Display Language to `zh-cn`.
3. Open devtools after page auto refresh

image

### PR DESCRIPTION
**Pull request by yiliang114**
To resolve an issue where some extended language packs fail to load
image

### CODE REVIEW

**Comment by yiliang114** [comment]
Hi @TylerLeonhardt @bpasero Do you take up a little time to review the code for me?

**Comment by TylerLeonhardt** [comment]
I would like to understand where the upper case CN is coming from... is that the browser? Does `navigator.language` in the Dev Tools Console of your browser return `zh-CN`?

**Comment by yiliang114** [comment]
> I would like to understand where the upper case CN is coming from... is that the browser? Does `navigator.language` in the Dev Tools Console of your browser return `zh-CN`?

Yes. console of chrome safari and firefox  respectively

image

**Comment by TylerLeonhardt** [comment]
Closing this as this should be fixed now. See: https://github.com/microsoft/vscode/issues/187795#issuecomment-1648580641

**Pull request closed without merging**
