### PR TITLE
`Git: Merge Branch...` picker duplicates branch name in description (fix #199562)

### LINKED ISSUE #199562: `Git: Merge Branch...` picker duplicates branch name in description
Type: <b>Bug</b>

image

VS Code version: Code - Insiders 1.85.0-insider (2e721b6ec731c22cd3c2853dbc7ad69deb447515, 2023-11-29T02:35:06.500Z)
OS version: Windows_NT x64 10.0.22621
Modes:

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #199562

Initially created as draft while we discuss what data (if any) to use as description.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Initial push replaces duplicated name with last commit timestamp:

image

As currently implemented this causes a noticeable delay while timestamps are fetched. Perhaps this can be improved by adding these lazily to the QuickPickItem description properties

Other ideas:

**Commit ID (short format)**

image

I think both of the above would benefit from #75835 (support for right-justfified descriptions in quickpick lists) being implemented.

**Nothing**
This is is what Rebase does for most of its entries. There the exception is the upstream entry, for which description gets set to '(upstream)'

image

**Comment by lszomoru** [comment]
@gjsjohnmurray, thanks for your contribution. Ideally, we would want **all** brach pickers should be consistent. Could we have this one look like the branch picker that is being shown when you invoke the "Checkout" command? Thanks!

**Comment by gjsjohnmurray** [comment]
image

**Comment by gjsjohnmurray** [comment]
Can this get merged soon, or do the rules of your grooming iteration mean it'll have to wait another month?

**Comment by lszomoru** [comment]
@gjsjohnmurray, thank you very much for the pull request. I took the liberty to build on top of this to distinguish local and remote branches. Closing this PR in favour of https://github.com/microsoft/vscode/pull/200331.

**Pull request closed without merging**
