### PR TITLE
override Ubuntu's default integrated terminal font options (#35901)

### PR DESCRIPTION
**Pull request by andyli**
As suggested in https://github.com/Microsoft/vscode/pull/56311#issuecomment-412975218.

### CODE REVIEW

**Review by ctrlaltvikas — APPROVED** [review]

**Comment by andyli** [comment]
Is there any problem with this PR?

**Review by Tyriar — APPROVED** [review]
Thanks @andyli and sorry about the delay. It's unfortunate that this needs to happen at all. Hopefully I can get some time soon to work on a better fix I've had in mind for a while.

**Comment by jhpratt** [comment]
Minor "bug" arising from this: zsh's (and similar shells) powerline fonts no longer work by default.

**Comment by Tyriar** [comment]
@jhpratt they should still work, you just need to set the font (try setting terminal.integrated.fontFamily instead of editor.fontFamily?)

**Pull request merged**
