### PR TITLE
Add HTML aria attribute autocomplete

### LINKED ISSUE #320: Support HTML aria attribute completion
http://www.w3.org/TR/wai-aria/

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #320 

/cc @aeschli 

aria_autocomplete

### CODE REVIEW

**Comment by dstorey** [comment]
Should this take into account the aria attributes are not really global? Some are only valid if the element is a particular role (either via role attribute or the element's natural semantics)

**Comment by Tyriar** [comment]
That's beyond the abilities of the code currently, the same applies to a set of elements only being valid within certain elements (`ul`, `ol` can only contain only contain `li` elements) which doesn't happen at the moment. That and adding descriptions to all the tags/attributes (#323) I think should follow this. I made another issue to that effect #375

**Comment by dstorey** [comment]
Sounds good

**Comment by aeschli** [comment]
Thanks @Tyriar, very nice pull request!

**Comment by zbandhan** [comment]
And also HTML role attribute should auto-complete.

**Comment by Tyriar** [comment]
@zbandhan that was added in 98f95641 and successive commits.

**Pull request merged**
