### PR TITLE
Use patched emmet to support svg and orphaned quote bug

### LINKED ISSUE #17166: Orphaned quote crashes Sass
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open a new document
2. Set language mode to Sass
3. Type a quote mark " or '  and delete the closing quote if it's auto added.
Any line of text with an orphaned quote mark will do.
4. Move cursor to column 1 (start of the line) and press TAB.

Desired behaviour:
Pressing TAB should indent the text regardless of valid code etc.

The problem:
VSCode seems to freeze.

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #17166 and #11333 and #8135

### CODE REVIEW

**Review by mando101 — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
@egamma ping

**Review by egamma — APPROVED** [review]
This is a good move.

**Comment by ramya-rao-a** [comment]
Thanks @egamma!

**Comment by gianpaj** [comment]
is a good idea to use a patch/custom fork?
looks like emmet fixed this on v1.6.1: https://github.com/emmetio/emmet/pull/477#issuecomment-267257879

**Comment by ramya-rao-a** [comment]
@gianpaj We did try to use the latest v1.6.1 of emmet, but there was almost a 4 times increase in the size of the emmet module when comparing 1.3.1 (version currently used by VS Code) and the latest 1.6.1

You can read more at https://github.com/Microsoft/vscode/pull/9002#issuecomment-234944128

Also, the emmet author is currently working on v2.0 with significant API changes.

Therefore, we took the call to not take that latest version of emmet.

Now since we didnt want to wait till v2.0 was out to fix #8135, we took the forked approach.

From now till v2.0 is out, it is unlikely that the fork is going to be changed unless there is a major bug fix to be taken

**Comment by gianpaj** [comment]
Hi @ramya-rao-a,

that makes perfect sense. Thanks very much for explaining the reasoning behind :)

**Pull request merged**
