### PR TITLE
Fix #25965 Selectbox Dropdown theming and platform consistency [WIP]

### LINKED ISSUE #25965: UI Theme Add: select-box(drop downs) selection and hover colors
Currently all widgets using 'select-box' cannot theme
the selected or hover item colors (foreground/background)
The the color is controlled by the platform. That overrides
normal CSS approaches/selectors. 

image

After a bunch of research, I did figure out one solution
and made a prototype in a small electron app.

There appear to be three options:

1 - Some CSS guru knows of a better trick
2 - Use an input box on top of the current list widget 
3 - Use something like I came up with: 

   one select box that is the normal drop-down with current selection
   automatically includes the drop-down arrow
   a second select box which can be made hidden/visible depending
   on the first lightbox focus/selection

   The second select box can be styled with option:checked and box shadow

   
option:checked {
    color: #ffffff;
    box-shadow: 0 0 10px 100px #905000 inset;
}

    This box-shadow is the only thing I found that overwrites the platform colors
    It does NOT work on a select box with only one item showing (nominal case)
    That is what I came up with the two boxes and a bit of code to display and hide
    the second box with the options list

I think option two is more complicated and inherits the unneeded list properties
if there is no option one , I would go ahead and prototype within VSC and do a PR

Thoughts ?

image

### PR DESCRIPTION
**Pull request by cleidigh**
@bpasero 
see issue for initial comments/screenshots

### CODE REVIEW

**Comment by cleidigh** [comment]
@bpasero 
just wanted to see if you have any thoughts or comments on my implementation.
cheers

**Comment by bpasero** [comment]
@cleidigh sorry I am currently not having time to look into this due to the multi root work that is ahead.

**Comment by cleidigh** [comment]
@bpasero 
no problem I understand
hopefully after the next release...

**Comment by bpasero** [comment]
@cleidigh can you bring this up to sync with master, then I can have a look

**Comment by cleidigh** [comment]
@bpasero 
Did new PR - to avoid merge issues
See comments there.
#36193

**Pull request closed without merging**
