### PR TITLE
Add history to new list/tree search/filter widget (#155578)

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR is for #155578.

While the widget remains open it accumulates search strings. Each one gets added when focus moves off the widget (typically to the tree, e.g. when DownArrow is pressed).

UpArrow in the widget's input field recalls previous history entries. <kbd>Enter</kbd> is implemented as an alternative shortcut into the tree, useful when you have navigated up the history and <kbd>DownArrow</kbd> no longer gets you there because instead it takes you down the history list.

<strike>At this time history is not persisted when the widget is closed.</strike>

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@joaomoreno please consider merging this as well as #158583. Both of them add some shine to the recent list/tree search/filter rework.

**Comment by joaomoreno** [comment]
@gjsjohnmurray This feels strange right now:

- We should definitely persist the history in memory, as long as the tree is alive.
- I don't think the current behavior makes sense: <kbd>DownArrow</kbd> will either navigate history or jump to the list, depending on the history's cursor position. This makes for very strange behavior. I don't have a good suggestion to solve this.
- Are all those changes deep in `history.ts` really necessary?

**Review by joaomoreno — CHANGES_REQUESTED** [review]
@gjsjohnmurray This feels strange right now:

- We should definitely persist the history in memory, as long as the tree is alive.
- I don't think the current behavior makes sense: <kbd>DownArrow</kbd> will either navigate history or jump to the list, depending on the history's cursor position. This makes for very strange behavior. I don't have a good suggestion to solve this.
- Are all those changes deep in `history.ts` really necessary?

**Comment by gjsjohnmurray** [comment]
> * Are all those changes deep in `history.ts` really necessary?

Adding `isLast()` and `isNowhere()` seemed necessary to make the <kbd>DownArrow</kbd> handling work. I added `isFirst()` for completeness. All three are currently only used by the corresponding new public `isXXXInHistory()` methods of `HistoryInputBox`. Currently `isAtFirstInHistory()` isn't used, but it's there for completeness.

> * I don't think the current behavior makes sense: ...  I don't have a good suggestion to solve this.

Nor do I. Removing current behaviour of <kbd>DownArrow</kbd> taking you back to the tree/list is likely to cause complaints as people adapt to using <kbd>Enter</kbd> for this instead. If I have <kbd>UpArrow</kbd>ed up the history, then press one too many <kbd>DownArrow</kbd>s, yes, I end of off the widget. But I can use <kbd>Ctrl/Cmd</kbd>+<kbd>F</kbd> to get back there quickly.

**Comment by gjsjohnmurray** [comment]
> * We should definitely persist the history in memory, as long as the tree is alive.

I have pushed a change to do this, plus another than persists the search/filter mode for the tree across close/reopen of the widget.

**Comment by gjsjohnmurray** [comment]
@bpasero I think this also addresses #156248

**Comment by gjsjohnmurray** [comment]
@joaomoreno does this need more work from me before you will merge it?

**Review by joaomoreno — APPROVED** [review]

**Comment by joaomoreno** [comment]
Sorry for the delay here @gjsjohnmurray! Happy new year and thank you! 🍻

**Review by bpasero — APPROVED** [review]

**Pull request merged**
