### PR TITLE
Enable visibility toggling for terminal and other views

### LINKED ISSUE #141405: Cannot "Hide Terminal"
Testing #141357

image

I had dragged the outline view into the side panel where terminal was and would have expected I can now "Hide Terminal".

### PR DESCRIPTION
**Pull request by benibenj**
Fixes #141405

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]

**Review by bpasero — COMMENTED** [review]
@benibenj I wonder if there is even a case for `canToggleVisibility` then, should we remove it?

**Comment by benibenj** [comment]
@bpasero I considered that, but I think we should keep if for the Explorer. We do not want new users to accidentally hide it and not know how to bring it back. 

Regarding the other views, I do not know why they `canToggleVisibility` was set to false in some cases, so it's hard for me to change it.

The following views set it to false:
- Comments
- Chat
- Edits
- Popular Extensions View
- Explorer
- Search
- Testing
- UserDataSyncViews: Conflicts

**Comment by benibenj** [comment]
Continuing here: #236226

**Comment by bpasero** [comment]
Yeah, we can maybe special case the Explorer, I agree. The others sound strange to me...

**Pull request merged**
