### PR TITLE
Don't include this function types in completeFunctionCalls

### LINKED ISSUE #104877: completeFunctionCalls should not add `this` parameters
- VSCode Version: 1.47.3
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Enable completeFunctionCall
2. Create new tyepscript file, ype
```typescript
function f(this: void) {
	// make sure `this` is unusable in this standalone function
}
f|
```
cursor at `|`
3. <kbd>TAB</kbd>

Expected: `f()`
Actual: `f(this)`

> Typescript allow annotating `this` parameter https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters
> 
> ```typescript
> function f(this: void) {
>   // make sure `this` is unusable in this standalone function
> }
> ```
> 
> Because `this` parameters are fake parameters, I think we should skip these.
> 

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by xuanduc987**
This PR fixes #104877

### CODE REVIEW

**Comment by mjbvz** [comment]
What issue does this fix?

**Comment by xuanduc987** [comment]
Typescript allow annotating `this` parameter https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

```typescript
function f(this: void) {
  // make sure `this` is unusable in this standalone function
}
```

Because `this` parameters are fake parameters, I think we should skip these.

**Comment by mjbvz** [comment]
Thanks. Can you also create a normal issue to track this problem. This helps us track issues and verify this PR fixed it

**Comment by xuanduc987** [comment]
I had created #104877 to track this issue. Thanks.

**Comment by mjbvz** [comment]
Thanks! This will be in the next VS Code insiders build and is scheduled to ship with VS Code 1.49

**Pull request merged**
