### PR TITLE
refactor menu theming to be cleaner and remove css colors

### LINKED ISSUE #58496: Do not hardcode border color for monaco-menu-container in HC theme
It looks like a color sneaked into CSS that should use our theming story instead: https://github.com/Microsoft/vscode/blob/abca8c3ce9c267605efc74d5b79ca2a23e746de1/src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css#L205

We have this color defined (`contrastBorder` I think).

### PR DESCRIPTION
**Pull request by sbatten**
fixes #58496 and https://github.com/Microsoft/monaco-editor/issues/1013

### CODE REVIEW

**Comment by bpasero** [comment]
@sbatten please clean up the merge conflicts and bring to latest in master

**Review by bpasero — APPROVED** [review]
The change makes sense to me, however introduces quite a bit of dynamic CSS. Ideally CSS is only used for complicated behaviour (e.g. when defining styles on `:hover` or `:active`). For simple widgets (e.g. the `Button`) we just try to set the style on the element directly. This would mean, instead of adding dynamic CSS, the `Menu` would have to just set the style on each menu item. But since the menu is probably never visible when the theme changes, it would probably even be fine to not update the colors dynamically but just using them when the menu is created again. Not sure how easy that is given the action items seem to be very generic, but wanted to bring it up.

**Comment by bpasero** [comment]
@sbatten when you do these changes please cross check with the standalone editor as well that things are fine.

**Review by bpasero — APPROVED** [review]
Much better 👍 .

There is one color usage left in `.context-view.monaco-menu-container`: `background-color: white`. not sure if that one should also be externalized?

**Comment by sbatten** [comment]
@bpasero  don't think that one is supposed to be there anymore, removed it

**Pull request merged**
