### PR TITLE
Log errors from feature providers as external

### LINKED ISSUE #15374: Error Telemetry has errors from processes run inside the extension that may contain PII

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #15374

When promises from language feature providers are rejected, we currently call `onUnexpectedError` which ends up calling error telemetry service that logs the error as a telemetry event.
There are 2 reasons why we wouldn't want this

- It is noise when we triage the error telemetry events because these errors are external as far as the core product is concerned.
- It may contain PII.

### CODE REVIEW

**Comment by jrieken** [comment]
This is full list of language features/registries. Unsure if we have already covered all. I am also happy to help @ramya-rao-a. If you don't mind I can push more changes straight into your branch.

- [ ] ReferenceProviderRegistry
- [ ] RenameProviderRegistry
- [ ] SuggestRegistry
- [ ] SignatureHelpProviderRegistry
- [ ] HoverProviderRegistry
- [ ] DocumentSymbolProviderRegistry
- [ ] DocumentHighlightProviderRegistry
- [ ] DefinitionProviderRegistry
- [ ] CodeLensProviderRegistry
- [ ] CodeActionProviderRegistry
- [ ] DocumentFormattingEditProviderRegistry
- [ ] DocumentRangeFormattingEditProviderRegistry
- [ ] OnTypeFormattingEditProviderRegistry
- [ ] LinkProviderRegistry

**Comment by ramya-rao-a** [comment]
@jrieken I got my list from the `modes.ts` file. The ones missing were not using `onUnexpectedError` at the moment, so didn't touch them.
Feel free to push changes to my branch

**Comment by jrieken** [comment]
yeah, we might not be using that util, but their error might still end up in normal error telemetry otherwise

**Comment by ramya-rao-a** [comment]
Updated the RenameProviderRegistry.

[DocumentFormattingEditProviderRegistry](https://github.com/Microsoft/vscode/blob/262b398026bfd8fa7c8b01aadb92b0f6a29d626a/src/vs/editor/contrib/format/common/format.ts#L57) and [DocumentRangeFormattingEditProviderRegistry](https://github.com/Microsoft/vscode/blob/262b398026bfd8fa7c8b01aadb92b0f6a29d626a/src/vs/editor/contrib/format/common/format.ts#L35) handle the rejected promises by ignoring them. So these won't bubble up and reach telemetry. Am not sure if they were ignored intentionally or did we just miss calling `onUnexpectedError` in these cases.

In case of [OnTypeFormattingEditProviderRegistry](https://github.com/Microsoft/vscode/blob/262b398026bfd8fa7c8b01aadb92b0f6a29d626a/src/vs/editor/contrib/format/common/format.ts#L74), the `provideOnTypeFormattingEdits` doesn't seem to be returning a promise. Doing a `.then` on it gives syntax errors. You know anything about that?

**Comment by jrieken** [comment]
I have pushed two more commits - one to fix a test failure as we apparently expect rename error to bubble up. I now log and send a generic error around. Also, updated the formatting logic to always log errors - I believe that wasn't ignored for a specific reason.

**Comment by ramya-rao-a** [comment]
@jrieken  Travis is failing in Mac. You know anything about the failures?

**Pull request merged**
