### PR TITLE
Inno setup - Switch from commondesktop to autodesktop

### LINKED ISSUE #104545: "IPersistFile::Save failed" during installation of VS Code Insiders
- VSCode Version: 1.48.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19041

Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-11T23:21:50.282Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Steps to Reproduce:

1. Download and run "VSCodeUserSetup-x64-1.48.0-insider.exe"
2. 
image

I'm not sure if it's relevant, but I had VS stable installed prior to the Insiders install. Also, I tried to remove stable and reinstall Insiders, which resulted in the same error. It seems like everything is functioning properly, but there's no shortcut on the desktop.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by lszomoru**
This PR fixes #104545

### CODE REVIEW

**Comment by isidorn** [comment]
I have verified this fixes the issue. 
The change also makes sense. For now optimisticaly merging.

fyi @deepak1556 for another pair of eyes.

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
@lszomoru for reference can you just provide a pointer for the docs where they mention the change of naming

**Comment by deepak1556** [comment]
@isidorn its in the same `6.0.0-beta` as the other breaking change

```
Added new "auto" constants which automatically map to their "common" form unless the installation is running in
non administrative install mode, in which case they map to their "user" form. It is recommended to update
your scripts to use these "auto" constants as much as possible to avoid mistakes. The list of added "auto"
constants is: {autoappdata}, {autocf}, {autocf32}, {autocf64}, {autodesktop}, {autodocs}, {autopf},
{autopf32}, {autopf64}, {autoprograms}, {autostartmenu}, {autostartup}, and {autotemplates}.
```

**Comment by lszomoru** [comment]
Forgot to mention that I also double checked and `{commondesktop}` was the only `common` constant that we are using.

**Comment by isidorn** [comment]
Awesome. 
@deepak1556 thanks for the pointer
@lszomoru thanks for checking other `common` constants

**Pull request merged**
