### PR TITLE
Add npm-shrinkwrap and package-lock files from npm 5.0.3 (node 8.1.2)

### PR DESCRIPTION
**Pull request by roblourens**

### CODE REVIEW

**Comment by Tyriar** [comment]
Adding @joaomoreno as he was the gatekeeper for this sort of stuff in the past I believe.

**Comment by roblourens** [comment]
https://docs.npmjs.com/files/package-locks

https://docs.npmjs.com/files/package-lock.json

**Comment by felixfbecker** [comment]
package-lock.json is the new npm-shrinkwrap.json (the only difference is that npm-shrinkwrap.json will get published to npm). You can upgrade by simply running `npm install` (which will migrate the shrinkwrap files), then renaming all npm-shrinkwrap.json to package-lock.json (they have the same schema).

**Comment by joaomoreno** [comment]
Will definitely not have time for this in June. If someone wants to pick it up, make sure all our builds (TFS, Travis, AppVeyour) would still work with this, be my guest.

**Comment by felixfbecker** [comment]
@joaomoreno did it: https://github.com/Microsoft/vscode/pull/29576

**Pull request closed without merging**
