### PR TITLE
catch error

### LINKED ISSUE #173867: Cannot register buffer element provider when terminal has not been opened yet
In VS Code exploration devtools console after update.

```
ERR Cannot register buffer element provider when terminal has not been opened yet: Error: Cannot register buffer element provider when terminal has not been opened yet
    at P.registerBufferElementProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:24234)
    at e.Terminal.registerBufferElementProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js:1:274582)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2508:33396
```

### PR DESCRIPTION
**Pull request by meganrogge**
fix #173867

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Since it's returning a promise, we could instead await opening and then call it? I think `focusWhenReady` is what I'm thinking of

**Comment by meganrogge** [comment]
yeah I thought abt that, but wasn't sure it was worth the extra call when this will almost never happen IE someone creates a terminal and immediately tries to focus the accessible buffer

**Comment by Tyriar** [comment]
The error was showing up though, so either this isn't the entry point to the error kr Ben was quickly hitting shift+tab?

**Comment by meganrogge** [comment]
the reports of this happening were 3 weeks ago, prior to this commit https://github.com/microsoft/vscode/commit/855ba20c38ae1e39d6e3ea3b2a16b53502592203

where we moved the creation of the buffer to after open, which was the fix

**Pull request closed without merging**
