### PR TITLE
Fix search editor title not updating

### LINKED ISSUE #155855: Stale search editor title when switching editor groups
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: MacOS Monterey 12.4

Steps to Reproduce:

1.  Open two editor groups.
2. Open a search editor in one of them and update the search text.
3. Switch to an editor in the other group.  The title of the search editor will not update until you focus back on the editor group that contains it.

### PR DESCRIPTION
**Pull request by ssigwart**
Fixes #155855.

This fixes the search editor title not updating until you focus on a different editor in the same editor group.  It looks like this was introduced by a fix for #145749.

To test, open a search editor and change the search text.  The title should update.

### CODE REVIEW

**Review by ProKashif — DISMISSED** [review]

**Review by roblourens — COMMENTED** [review]
Is there also an issue at line 174-177?

**Comment by roblourens** [comment]
Thanks for the PR, good catch

**Comment by ssigwart** [comment]
> Is there also an issue at line 174-177?

Yeah, that looks wrong too.  I'm not as clear on what `resolveModels` does, but in its current start it seems to never execute.  I updated it to share a private variable with the `onConfigDidUpdate` version so that if the label changes in either one, `_onDidChangeLabel` will fire.

**Review by roblourens — APPROVED** [review]
Looks great to me, thank you!

**Review by rzhao271 — APPROVED** [review]

**Pull request merged**
