### PR TITLE
Blacklist typescript.useCodeSnippetsOnMethodSuggest in certain contexts

### LINKED ISSUE #2092: Typescript: import autocomplete fills in function arguments
When I use autocomplete to import a function, it fills in the function arguments right there.

Here's what it looks like:
- `import {foo} from './fooBar'`
- `import {foo, b} from './fooBar'`
- `bar` shows up as a suggesstion; hit enter.
- It fills in as `import {foo, bar(argname)} from './fooBar'`.

### PR DESCRIPTION
**Pull request by mjbvz**
fixes #2092

**bug**
With `typescript.useCodeSnippetsOnMethodSuggest` enabled, we will automatically complete function calls inside some contexts where they should not be completed. For example, destructing assigments.

**fix**
Add a quickinfo check on the position before attempting to insert a function call. Create a blacklist of invalid contexts. Otherwise, assume that we want to complete the function call.

dec-02-2016 16-08-00

### CODE REVIEW

**Comment by dbaeumer** [comment]
Nice idea. But we should mark this as a work around and should ask the TS team to provide this information (parameter names) in the completion list result already. There might be cases which we can't easily work around.

**Comment by mjbvz** [comment]
@dbaeumer Ok, I'll open an issue on TypeScript. Since TS returns the parameter names already, the request on the TS side would be to not return parameter names when in these assignment contexts, correct?

Also, do we want to take this workaround in our side until the TS team can provide a proper fix?

**Comment by dbaeumer** [comment]
@mjbvz instead of not returning the names I would opt to return a context information in additional that lets us know where we are completing:

- function name
- arg
- import name, 
....

**Comment by mjbvz** [comment]
Tracking proper fix on the TS side, but merging in the workaround for now. Will add comment linking to the TS issue in the code

**Pull request merged**
