### PR TITLE
Revert "chore: update electron@22.4.6 (#179947)"

### PR DESCRIPTION
**Pull request by deepak1556**
Causes crash in extension host when using v8.serializer API, regressed with https://github.com/electron/electron/commit/62dddd12edb54b2fe73fd810b7a739f869f0b271

### CODE REVIEW

**Review by joyceerhl — APPROVED** [review]

**Comment by brjsp** [comment]
Example stack trace of the crash:
```
#0  blink::V8PerIsolateData::HasInstance(blink::WrapperTypeInfo const*, v8::Local<v8::Value>, WTF::HashMap<void const*, v8::Eternal<v8::Template>, blink::V8PerIsolateData::SimplePtrHash, WTF::HashTraits<void const*>, WTF::HashTraits<v8::Eternal<v8::Template> >, WTF::PartitionAllocator> const&) [clone .isra.0] () at ../../third_party/blink/renderer/platform/bindings/v8_per_isolate_data.cc:224
#1  0x0000558a74704557 in blink::V8PerIsolateData::HasInstance (this=0x0, wrapper_type_info=0x558a78a8db80 <blink::V8TrustedScript::wrapper_type_info_>, untrusted_value=...)
    at ../../third_party/blink/renderer/platform/bindings/v8_per_isolate_data.cc:218
#2  0x0000558a74b79d9f in blink::bindings::V8InterfaceBridge<blink::V8TrustedScript, blink::TrustedScript>::HasInstance () at ../../third_party/blink/renderer/platform/bindings/v8_interface_bridge.h:30
#3  blink::V8UnionStringOrTrustedScript::Create (isolate=0x2d600038c000, v8_value=..., exception_state=...) at gen/third_party/blink/renderer/bindings/core/v8/v8_union_string_trustedscript.cc:25
#4  0x0000558a73b05e33 in blink::NativeValueTraits<blink::V8UnionStringOrTrustedScript, void>::NativeValue () at ../../third_party/blink/renderer/bindings/core/v8/native_value_traits_impl.h:1489
#5  TrustedTypesCodeGenerationCheck () at ../../third_party/blink/renderer/bindings/core/v8/v8_initializer.cc:420
#6  blink::V8Initializer::CodeGenerationCheckCallbackInMainThread (context=..., source=..., is_code_like=56) at ../../third_party/blink/renderer/bindings/core/v8/v8_initializer.cc:460
#7  0x0000558a6fe77fdf in ModifyCodeGenerationFromStrings (context=..., source=..., is_code_like=48) at ../../electron/shell/common/node_bindings.cc:211
#8  0x0000558a709cfead in v8::internal::ModifyCodeGenerationFromStrings () at ../../v8/src/codegen/compiler.cc:2928
#9  v8::internal::Compiler::ValidateDynamicCompilationSource (isolate=0x2d600038c000, context=..., original_source=..., is_code_like=false) at ../../v8/src/codegen/compiler.cc:2991
#10 0x0000558a70d8d870 in CompileGlobalEval () at ../../v8/src/runtime/runtime-compiler.cc:578
#11 __RT_impl_Runtime_ResolvePossiblyDirectEval () at ../../v8/src/runtime/runtime-compiler.cc:623
#12 v8::internal::Runtime_ResolvePossiblyDirectEval (args_length=2024332160, args_object=0x2d6000280030, isolate=0x2d600038c000) at ../../v8/src/runtime/runtime-compiler.cc:607
#13 0x00005589fff170b3 in ?? ()
#14 0x00007fffdb4ff1d0 in ?? ()
#15 0x0000000000000006 in ?? ()
```

**Comment by deepak1556** [comment]
@brjsp do you have a minimal repro for the crash outside VSCode ?

**Comment by brjsp** [comment]
No, sorry. I maintain the openSUSE packages for electron and VSCode, and have also observed the extension host crashing with our electron build (which is built using GCC13 — with clang, used by upstream builds, the stack traces may look different)

**Comment by deepak1556** [comment]
No problem, thanks for confirming!

**Comment by brjsp** [comment]
It does not seem to be caused by 62dddd1 — i've reverted that commit and the extension cost still crashes

**Comment by deepak1556** [comment]
Yup I was wrong, the regression is from https://github.com/electron/electron/commit/e2c4acd5052dc8dd1fdd019981f5838e7ea06bfb which does not account for the utility process and delegates to blink which is not available in the process.

**Comment by brjsp** [comment]
Yes! Reverting e2c4acd indeed fixed the crash for us.

**Pull request merged**
