### PR TITLE
Use label for "Follow link" command's tooltip

### PR DESCRIPTION
**Pull request by dsanders11**
Currently hovering over the  "Follow link" command will show the URI for the command in text form. This PR changes it to showing the label as the tooltip.

Avoids this:

image

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Doesn't this change also mean I won't be able to preview the target of an http(s) link?

Maybe OK to omit the query string from what the hover currently shows. 

Also, based on code reading I expected the link text in your screenshot to read "Execute command" rather than "Follow link".

**Comment by dsanders11** [comment]
> Doesn't this change also mean I won't be able to preview the target of an http(s) link?

True. Is that an intended use-case, or simply a side-effect of the current behavior? The PR could be adjusted so that it only uses the label if `executeCmd` is true.

> Maybe OK to omit the query string from what the hover currently shows.

That would be an improvement, but I think showing the command name would still be undesirable behavior, as it's unexpected and not self-explanatory to anyone who doesn't know what command URIs are, as they're an implementation detail.

> Also, based on code reading I expected the link text in your screenshot to read "Execute command" rather than "Follow link".

I believe that's because it's a Markdown document, and the `markdown-language-features` extension [sets the tooltip to "Follow link"](https://github.com/microsoft/vscode/blob/7a4e81a6742ad6b1aadf5281d39abe87ccc1f1b0/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L59), so that's what's displayed.

**Comment by gjsjohnmurray** [comment]
🤷  Let's see what a team member says when this PR gets looked at.

**Comment by alexdima** [comment]
I agree that the markdown tooltip is too much. Other test cases (http and file links):
```html
<!--
    http://www.example.com
-->
<script src="script.js"></script>
```

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
