### PR TITLE
Only resolve paths in REPL if path is relative

### PR DESCRIPTION
**Pull request by felixfbecker**
Added back the root component capture to the regexp and call `toResource` conditionally. I would appreciate it if someone could check this out and test, still have trouble building, this is untested

### CODE REVIEW

**Comment by isidorn** [comment]
@felixfbecker thanks a lot for your contributions!
The changes look good. Now let's try to fix your build issues. 
From pr #15174 and looking at your original errors they all seem to be related to the generated monaco editor api file. I think we can just ignore those and still be able to run out of source with `\scripts\code.bat`. More details https://github.com/Microsoft/vscode/wiki/How-to-Contribute

As for the monaco.d.ts errors, maybe try good old `git clean -fxd`, and again `scripts\npm install` and `gulp watch`. Basically the monaco.d.ts file gets generate from monaco.d.ts.recipe and for some reason on your machine he is looking for other definition files which I do also do not have.

If running out of source does not work with these errors let me know and I will ask around for a solution for your issue.

**Comment by felixfbecker** [comment]
Another bug
image

**Comment by isidorn** [comment]
@felixfbecker did you succeed in runnning vscode out of source?

**Comment by felixfbecker** [comment]
Yes. I tested it, absolute paths work correct now. How can I get the node debugger? Mocha always throws the relative paths, would like to test those

**Comment by isidorn** [comment]
@felixfbecker awesome! To get the node debugger in the oss dev build install it from the gallery, to enable the gallery in the oss dev build first add the following to the `product.json` before building the oss dev vscode. Let me know how it looks and if it seems good I will merge it in

```json
"extensionsGallery": {
	"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
	"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
	"itemUrl": "https://marketplace.visualstudio.com/items"
}
```

**Comment by isidorn** [comment]
@felixfbecker let me know how this is working once you test those mocha relative paths

**Comment by felixfbecker** [comment]
Just tested, works!

image

Side effect: the parens are underlined. No that much of a deal imo though

**Comment by felixfbecker** [comment]
PHPUnit works:

image

**Comment by felixfbecker** [comment]
Normal call stacks not unfortunately:

image

**Comment by isidorn** [comment]
Awesome, let's merge this baby in.
You have a beer from me once you are in Zurich

**Comment by isidorn** [comment]
@felixfbecker we can not handle each and every case. This should improve once we start using the editor intead of the tree. Might investigate into that over Christmas

**Comment by felixfbecker** [comment]
Yeah I don't know how to handle it while still supporting spaces in paths (without matching the whole line by mistake).

> You have a beer from me once you are in Zurich

I will come back to that offer 😄

**Pull request merged**
