### PR TITLE
Add support to de-emphasize debuggers in run list

### LINKED ISSUE #184457: Deemphasise an initial configuration provider if an extension is installed.
I'm looking to either remove or deemphasise a debugger selection from the dropdown for initial configuration providers if an extension is installed.

For example, I'm looking to hide the `.NET 5 and .NET Core` debugger if `C# Dev Kit` is installed.
image

The other ideal is that we could somehow show a Dynamic Configuration Provider `C#` even though no file context is present.
E.g. 
image

### PR DESCRIPTION
**Pull request by WardenGnaw**
This PR supports hiding debuggers in VS Code similar to the when clause, but `when` will disable the debugger from being used, but the new field `hiddenWhen` will allow the debugger to still be used. If `hiddenWhen` is evaluated to be true, it will hide the debuggers in the list.

Example usage in `package.json` to hide the debugger selection if the C# Dev Kit is installed.
```json
    "type": "coreclr",
    "hiddenWhen ": "dotnet.debug.serviceBrokerAvailable",
    "label": ".NET 5+ and .NET Core",
```

**Before:**
image

**After:**
image

Fixes: #184457

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
I find the name hard to understand. Did you consider alternatives such as `hiddenWhen`?

**Comment by WardenGnaw** [comment]
> I find the name hard to understand. Did you consider alternatives such as `hiddenWhen`?

I agree `hiddenWhen` captures the intent of this. I'll switch it to that.

**Review by roblourens — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by Jordanwaslistening** [comment]
.diff

**Review by Jordanwaslistening — COMMENTED** [review]
I've viewed this.

**Pull request merged**
