### PR TITLE
Fix focused stack frame colors in disassembly view

### LINKED ISSUE #129574: Unfocused stack frame not rendered in disassembly view
Testing #129161

found by @yannickowow 

@yuehuang010, @xisui-MSFT

1. Open disassembly view
2. Click on the call stack on some non top stack frame
3. Notice how the location is not shown in green in the disassembly view 🐛

### PR DESCRIPTION
**Pull request by xisui-MSFT**
This PR fixes #129574 

Current stack frame icon is shown when the current stack is in focus, and this line contains the address of the top stack frame.
Current stack frame line background is set when the line contains the address of the top stack frame, no matter if the current stack is in focus.
Focused stack frame icon is shown and focused stack frame line background is set when this line contains the address of the focused stack frame, and it's not the top stack frame.

### CODE REVIEW

**Comment by xisui-MSFT** [comment]
@isidorn @weinand Can you please take a look? Thanks!

**Comment by isidorn** [comment]
@xisui-MSFT this looks good to me, however i had a hard time getting into a situation to easily try this out with mock-debug.
Did you try it out with C++, does it works as expected.
I looked at the code and it looks good -> approved.
However since I could not try it out end to end I would prefer to merge this start of next week -> August. Please let me know if you would really like to ship this as part of the July release.

Thanks 👏

**Review by isidorn — APPROVED** [review]

**Comment by xisui-MSFT** [comment]
@isidorn I'm fine either shipping this in July or August. And yes I tested this using c++ extension.

@weinand Can you please add a few more levels of stack frames that has instructionPointerReference in disassembly view in the mock debugger? I can probably help as well if you prefer.

**Comment by weinand** [comment]
@xisui-MSFT In Mock Debug all `stackframes` have a `instructionPointerReference` if the corresponding source line contains the word `disassembly`. Just make sure to use the latest Mock-Debug.

https://github.com/microsoft/vscode-mock-debug/blob/2bbb1d16e6ffafcb80d1d1584174fd9f2f635105/src/mockRuntime.ts#L249-L265

**Comment by isidorn** [comment]
@xisui-MSFT due to other PRs that I merge there are conflicts in this PR now. Can you please resolve the conflicts? Thank you

**Comment by xisui-MSFT** [comment]
@isidorn Resolved conflicts. Thanks!

**Comment by isidorn** [comment]
@xisui-MSFT thanks a lot. Merging in 👏

**Pull request merged**
