### PR TITLE
Add terminal.newHere command

### LINKED ISSUE #79133: workbench.action.terminal.new should accept cwd as an argument
I cannot deprecate [terminal here](https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here) just yet because people want to be able to configure keybindings to do both open in workspace root and current file's directory.

Allowing configuring cwd via keybindings would fix this:

```json
{
  "key": "ctrl+shift+`",
  "command": "workbench.action.terminal.new",
  "args": {
    "cwd": "${fileDirname}"
  }
}
```

See https://twitter.com/borekb/status/1161229132627402752

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #79133
Let me know if there's some missing validation for the `cwd` command argument.

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
Instead of a new command, `workbench.action.terminal.new` should accept an optional arg `cwd` so keybindings can be setup for different cwds

**Comment by jeanp413** [comment]
@Tyriar I looked into that at first but `workbench.action.terminal.new` is an action and action arguments are not generic, they just use a `from` property here
https://github.com/microsoft/vscode/blob/a26961432c1ddb36367d2eca470086b32e506eb8/src/vs/workbench/common/actions.ts#L114-L117

also when creating actions, it  doesn't seem to be a way to specify the args schema like this
```
args: [{
  name: 'cwd',
  schema: {
      'type': 'string'
  }
}]
```

Should this PR contain changes to allow actions with generic arguments?

**Comment by Tyriar** [comment]
Can `workbench.action.terminal.new` be converted to extend `Command` then?

**Comment by jeanp413** [comment]
Not sure about that, it needs to be an action because it's used in `getActions()` and `_getContextMenuActions()` from `terminalPanel`.
Do you know if there is a way for `workbench.action.terminal.new` to be an `Action` and also a `Command`?

**Comment by Tyriar** [comment]
Good point, can we do what `SwitchSideBarViewAction` does here?

https://github.com/microsoft/vscode/blob/1ba4dc6954da243a087091108e6037f0f7c27ea6/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L204

**Comment by jeanp413** [comment]
Are you referring to the parameter `offset`?  that's just a constant value provided by the child classes that inherit from `SwitchSideBarViewAction` when calling the parent method
```typescript
export class PreviousSideBarViewAction extends SwitchSideBarViewAction {
...
	run(): Promise<any> {
		return super.run(-1);
	}
}

export class NextSideBarViewAction extends SwitchSideBarViewAction {
...
	run(): Promise<any> {
		return super.run(1);
	}
}
```

**Review by Tyriar — APPROVED** [review]
@jeanp413 thanks for your patience, I tried to do what i was thinking and it ended up not working out. I changed the name of the setting to `newWithCwd` and also for the actual cwd to be wrapped in an object and gave it a description:

Screen Shot 2019-09-13 at 11 07 49 AM

Here's an example of a keybinding now:

```
{
    "key": "cmd+shift+h",
    "command": "workbench.action.terminal.newWithCwd",
    "args": {
        "cwd": "${fileDirname}"
    }
}
```

**Pull request merged**
