### PR TITLE
Add latex support to markdown rendering

### LINKED ISSUE #6529: Support mathJax formula preview in markdown
- VSCode Version:1.1.1
- OS Version:win10 64

Steps to Reproduce:

markdown code as follows can't preview:
### LaTeX 公式

可以创建行内公式，例如 $\Gamma(n) = (n-1)!\quad\forall n\in\mathbb N$。或者块级公式：
$$  x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a} $$

### PR DESCRIPTION
**Pull request by djrenren**
Adds support for latex rendering in the markdown plugin and preview window. This PR implements this via `markdown-it-katex`

Resolves: https://github.com/Microsoft/vscode/issues/6529

(This is my first PR for vscode so feedback is extremely welcome)

### CODE REVIEW

**Comment by bpasero** [comment]
@kieferrm fyi

**Comment by djrenren** [comment]
Okay so it looks like I'm getting hygiene errors on the katex static static resources that are pulled down at build time. The CSS can probably reasonably be rewritten or something but the fonts are also important. Any thoughts?

**Comment by djrenren** [comment]
Okay so fixed the hygiene issues and included the katex woff2 and css files directly since they're compile artifacts from MIT licensed code I believe redistributing them is fine. The tests that're failing is for Terminal which appears unrelated to my stuff and is breaking other builds.

**Comment by be5invis** [comment]
s/latex/LaTeX/g

**Comment by kieferrm** [comment]
Sorry it took so long. We now have extension support for markdown: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-markdown.md.

**Pull request closed without merging**
