### PR TITLE
Add Git commit amend commands

### LINKED ISSUE #28690: Enhancement: git extention should include amend commit option
Like: 
git commit --amend

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Fixes #28690 and #22215

CC: @joaomoreno

### CODE REVIEW

**Comment by eljefedelrodeodeljefe** [comment]
ping @joaomoreno

**Comment by joaomoreno** [comment]
Thanks! :beers:

**Comment by cento** [comment]
I still don't find the amend option (vscode 1.15.1), the fix is valid on which version?

**Comment by kumarharsh** [comment]
@joaomoreno how does one find this **amend previous commit** option in vscode?

image

All I see are these options which I feel are relevant:

* Commit All (Amend)
* Commit Staged (Amend)

But clicking on either show this alert:

image

Reading the text in the alert above makes me even more confused about what the "Commit All (Amend)" even really means? What's the difference between this and the regular commit? Specifically,

* How do I add more files to the already completed commit.
* How do I remove some files from the already completed commit.
* How do I add/remove some lines from the already completed commit.

**Comment by kumarharsh** [comment]
OK, so after some experimenting, I found that when I stage some files, and click the 'Commit (Amend)' option, it will

* *add* the currently staged files to the previous commit, 
* *overwrite* the previous commit message with the commit message given while running the Commit (Amend) command.

So, I guess this takes care of my first point:
> * How do I add more files to the already completed commit.

But for both of the other points, I don't see any other way other than 'Undo last commit' which is really not helpful as it unstages all the files and lines.

**Comment by joaomoreno** [comment]
@kumarharsh Use quick open:

image

**Comment by joaomoreno** [comment]
@kumarharsh Right now, in the latest Insider released today, those `Amend` commands will prepopulate the previous commit message in the input box.

**Comment by bharath144** [comment]
@joaomoreno I am on the insider build and what you wrote doesn't work. The *amend* commands are just overwriting the message I had committed earlier. Any idea when this feature will be supported?

**Pull request merged**
