### PR TITLE
Create terminal find widget lazily, add LazyValue helper

### PR DESCRIPTION
**Pull request by Tyriar**
@jrieken a review here would be appreciated as you wrote `IdleValue`. The idea here is similar to `IdleValue` but it won't initialize the value at all until requested. For this specific use case, I don't want to create find widgets for every terminal as it will often be a waste of cpu/battery/memory. I wouldn't be surprised if something like this already existed, but I couldn't find it if so.

### CODE REVIEW

**Comment by Tyriar** [comment]
fyi @meganrogge

**Review by jrieken — CHANGES_REQUESTED** [review]
Yeah, this already exists as [Lazy](https://github.com/microsoft/vscode/blob/a8cb6baddf5bae653835565ad7d6748d0edeef7e/src/vs/base/common/lazy.ts#L20) and we shouldn't duplicate that. 

However, I would always use the IdleValue because Lazy is a guarantee for "value is delayed when needed". The point of idle time is to use small remaining time chunks and be ready without blocking

**Comment by Tyriar** [comment]
@jrieken thanks for the pointer, do you think it's a good idea to derive IdleValue from Lazy like in the PR or keep them separate?

**Comment by jrieken** [comment]
I'd keep them separate

**Comment by Tyriar** [comment]
Sounds good, will create a new PR for @meganrogge to review with just the terminal changes

**Pull request closed without merging**
