### PR TITLE
feat: use custom tag instead of custom version for MS electron releases

### PR DESCRIPTION
**Pull request by deepak1556**
Refs https://github.com/microsoft/vscode-electron-prebuilt/pull/24

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
I am debating with myself if I should do a similar change for how we download node.js here:

https://github.com/microsoft/vscode/blob/36b7d5beb3f77fadd6f77d342a0b8b5366cbd12f/build/gulpfile.reh.js#L165-L168

However, what I find a bit strange is to have the `msBuildNumber` in our OSS sources and then only use it when `electronRepository` is defined in `product.json`. 

I think a more elegant solution would be to encode repository and build number in the `product.json`, no?

**Comment by deepak1556** [comment]
Yeah I thought about that, but that approach makes it bit harder since we need to bump distro everytime the buildid changes. Additionally it keeps the version updates in the public repo.

**Comment by bpasero** [comment]
Fyi for node.js I am going with an approach where the `version` and checksums are part of the `product.json`:

https://github.com/microsoft/vscode/pull/184877/files#diff-285888428ebaab4e7985b695829cc9e47f98d2857505070ccacae3432b7b11dcR85-R88

**Comment by deepak1556** [comment]
Why not upload the Sha sums to release assets `ex: https://github.com/electron/electron/releases/download/v25.1.0/SHASUMS256.txt` and download from their for validation ?

**Comment by deepak1556** [comment]
Sanity run: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=219010&view=results

**Review by roblourens — APPROVED** [review]

**Pull request merged**
