### PR TITLE
account for wrapped lines on windows 

### LINKED ISSUE #177697: `Terminal: navigate accessible buffer` does not work sometimes
found by @jooyoungseo

### PR DESCRIPTION
**Pull request by meganrogge**
fix #177697

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Can you elaborate on what's happening here exactly? The wrapping heuristic in Windows is means to mostly get it right. Also I think Windows versions past a particular build number have conpty with wrapped line support. Generally we want to trust xterm.js' wrapped line state on Windows.

**Comment by meganrogge** [comment]
On Windows, the `command.marker.line` corresponds to the last line of a wrapped line in the terminal buffer. The editor does not have a wrapped line concept, so we have to account for that here.

**Comment by Tyriar** [comment]
@meganrogge the editor should only be getting wrapped lines (as in 2 wrapped lines in the terminal should be 1 line in the editor), do you mean the line last prompt line is not marked as wrapped?

**Comment by meganrogge** [comment]
>  (as in 2 wrapped lines in the terminal should be 1 line in the editor)

exactly, but we use the terminal's line as the metadata here, which is why it has to be adjusted

**Pull request closed without merging**
