### PR TITLE
Add Vagrantfile as a ruby language file extension

### PR DESCRIPTION
**Pull request by bbenoist**
As those are just some regular ruby files.

See https://www.vagrantup.com/ for more information about the tool.

image

### CODE REVIEW

**Comment by bbenoist** [comment]
PR womewhat related with https://github.com/Microsoft/vscode/issues/1651 but it does not really closes it.

**Comment by bbenoist** [comment]
I actually ended up writing [my own extension](https://marketplace.visualstudio.com/items?itemName=bbenoist.vagrant) which also adds support for common Vagrant commands :tada: 

This PR is no more important for me. Feel free to do whatever with it or the [code of my extension](https://github.com/bbenoist/vscode-vagrant) :wink:

**Comment by egamma** [comment]
I like your extension and it covers Vagrant well. Closing this PR.

**Comment by bbenoist** [comment]
@egamma Thanks for the feedback!

Next features for the extension will be support for the `vagrant ssh`, `vagrant winrm`, `vagrant powershell` and `vagrant rdp` commands.

Any info on whether we will have a channel (like `vscode.window.createOutputChannel`) with both input ant output (like the debugger console) someday?

**Comment by egamma** [comment]
This is not on the immediate radar, if you want input output then you should open a command prompt. For that we provide the 'run-in-terminal' node module. We use it in several extensions.

**Pull request closed without merging**
