### PR TITLE
Add relativeFileNoExtension

### LINKED ISSUE #25786: Add `${relativeFileNoExtension}` to 'predefined common variables'
- VSCode Version:
1.11.2
- OS Version:
any
Steps to Reproduce:

I'm trying to make a launch configuration that will start debugging the currently-opened TypeScript file using [ava](https://github.com/avajs/ava#debugging)
Right now I can't, because you need to pass it args a bit like this in `launch.json`:
```json
{
    "program": "${workspaceRoot}/node_modules/ava/profile.js",
    "args": ["${workspaceRoot}/path/to/my/file.js"]
}
```

So if you want to run the currently opened test file, you'd use something like:
`"args": ["${workspaceRoot}/${relativeFile}"]`

Which works fine if you're writing plain JavaScript, because ava will be able to run it directly. But if you're using TypeScript, ava will try to interpret the TypeScript as JavaScript and will barf.

If we had `relativeFileNoExtension`, it'd be pretty easy to make a configuration that ran the current file:
`"args": ["${workspaceRoot}/dist/${relativeFileNoExtension}.js"]`

For example, if I have `foo/bar/tests/mytestfile.ts` open, we'd have `relativeFileNoExtension` being `foo/bar/tests/mytestfile` and the arg would be `/path/to/my/workspace/dist/foo/bar/tests/mytestfile.js`, which matches the JavaScript output from `tsc`.
where `dist` is the `outDir` in `tsconfig.json` - obviously this part is project-specific.

I'd imagine the implementation would be something like this in [configurationResolveService](https://github.com/Microsoft/vscode/blob/d4504b92f466a2882931513fde34a610170557d6/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts):

```TypeScript
private get relativeFileNoExtension(): string {
    const relativeFile = this.relativeFile();
    return relativeFile.slice(0, relativeFile.length - paths.extname(relativeFile).length);
}
```

### PR DESCRIPTION
**Pull request by unional**
Fix #25786 

I didn't see tests that are `${file} related inside `configurationResolverservice.test.ts`.

Don't know if there is a good way to put them in.

### CODE REVIEW

**Comment by isidorn** [comment]
@unional thanks for the PR. Looking at the code I belive you forgot to add `this.relativeFile.length -` in the `slice` call.
Did you test this out with the development version of vscode?

Also in order for this to be accepted I would expect a PR to the docs that explains what this new feature is doing.
Here is the docs link and repo:
https://github.com/microsoft/vscode-docs
https://code.visualstudio.com/docs/editor/debugging#_variable-substitution
https://code.visualstudio.com/docs/editor/tasks#_variable-substitution

**Comment by unional** [comment]
Just -3/4 works. Slice take nagitve second param

**Comment by isidorn** [comment]
@unional I still find that ugly and would prefer what I have proposed in my comment.
Apart from that I would like to see the documentation changes before this PR can be merged

**Comment by unional** [comment]
Sure. Updated.

**Comment by unional** [comment]
One issue on this is that it is not the complete solution. 
I added this section to the doc:

## Debugging with transpilation

Some test runners may run test codes that are transpiled from your source code. For example, you write your code in TypeScript and the test runner only understand JavaScript (e.g. `ava`). In this case, you can utilize the `${relativeFileNoExtension}` variable:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Run tests",
            "program": "${workspaceRoot}/node_modules/ava/profile.js",
            "args": [
                "your-outDir/${relativeFileNoExtension}.js"
            ]
        }
    ]
}
```

However, it does not work in my case where I put my source files under `src/*`

The example would yield `your-outdir/./src/somefile.js` which is not correct.
It needed to be `your-outdir/somefile.js` (and have a way to do both `.js` and `.jsx`

Any suggestion?

**Comment by isidorn** [comment]
@unional no I do not have a suggestion currently. But the current solution seems to be incomplete it seems. Can you improve it such that it owkrs nicely?
As for the docs, I suggest just to add a short paragraph like the other variables, not the whole section.

**Comment by isidorn** [comment]
Pushing this to the backlog until my comments from above are looked into

**Comment by unional** [comment]
How about adding a `srcRoot` property so we can do `$relativeToSrcRootNoExtension`?

Is that possible and desired?

**Comment by mmkal** [comment]
@unional as the author of https://github.com/Microsoft/vscode/issues/25786, I don't think getting ava debuggging working should necessarily be a blocker for this issue. It was just an example I gave for why this property would be useful.

That said, your solution *will* fix the problem for my scenario, because my structure looks something like this (`dist` is my `outDir`).

```
project
|-- src
|   +-- thing.ts
|-- test
|   +-- thing-tests.ts
+-- dist
    |-- src
    |   +-- thing.js
    +-- test
        +-- thing-tests.js
```

Having both `src` and `test` directories that contain typescript will tell the compiler to mirror that directory structure inside your `outDir` (in this case `dist`). If you do something similar then your configuration above will work - you could even put an empty `dummy.ts` in the project root or something and it would have the same effect (I believe `tsc` is writing your output files directly in `outDir` because there's only one folder that contains typescript).

@isidorn IMO, this PR should go in as-is. It may not be a "complete" solution for every possible project configuration, but the change right now is small and easy to understand and adds concrete value (it'll work for me!). I don't think `$relativeToSrcRootNoExtension` needs to go in with this change. To be honest the best change that would require workarounds would probably be in typescript, not vscode - maybe a compiler flag that allows strict mirroring of directory structure.

So - because 1) the issue wasn't specifically about ava and 2) it solves my original ava problem - I'd be very happy if this went in with no further changes - thanks very much @unional for making this PR!

**Comment by unional** [comment]
I'm trying another approach to get this working for me by creating an extension to handle my case.

One question is how to call `vscode-node-debug2` within my extension.
All I need to do is add `srcRoot` property in the configuration and adjust the file path before calling `vscode-node-debug2`

**Comment by isidorn** [comment]
Closing as out-of-scope

**Pull request closed without merging**
