### PR TITLE
Render multiple glyph margin decorations

### LINKED ISSUE #5923: Decorations with gutter icons hide breakpoint icons
- VSCode Version: 1.0.0
- OS Version: any

Steps to Reproduce:
1. Create a decoration type `window.createTextEditorDecorationType({ gutterIconPath: ... });` with an icon, decorate a line.
2. Set a breakpoint for the line. While the breakpoint works, the decoration type gutter icon is completely hiding it.

Ideally, there should be a way to see both (all) icons. I'm assuming the same issue happens if two different extensions set different icons for the same line. Atom and IntelliJ platform based IDEs solve this by allowing to create a plugin specific gutter/or just extending the gutter horizontally to fit all icons.

If the above mentioned solution is not desirable for some reason, then it should probably be allowed to set a gutter icon `zIndex` for a decoration type. Or maybe the breakpoint icon should just take precedence and always be displayed above any extensions icons.

### PR DESCRIPTION
**Pull request by joyceerhl**
Fixes https://github.com/microsoft/vscode/issues/5923

For https://github.com/microsoft/vscode/issues/176316, I'd like to render a share link decoration in the gutter if a whole line has been selected. This currently doesn't play nicely with breakpoint decorations so I took a stab at expanding the glyph margin to accommodate rendering multiple decorations. 

In future we could also add the ability to associate decoration click targets with specific commands (and also update the testing/breakpoint decorations to handle click events), but I wanted to address just the rendering issue as a first pass.

Recording 2023-04-10 at 20 02 14

### CODE REVIEW

**Comment by alexdima** [comment]
The call to `model.getAllDecorations()` from the view model is concerning for me because fetching all the decorations could be very expensive perf-wise. And we will now be doing this almost all the time (each keystroke, etc). I think we need to enrich the `IntervalTree`/`IntervalNode` to be a lot faster and filter out only margin decorations in the `search` function. That would avoid needing to do the offset -> range conversion for all decorations on the model all the time.

**Comment by joyceerhl** [comment]
> Could you perhaps explore enriching the IntervalNode.metadata to have a bit flag if the node renders a margin decoration, this can be done similar to getNodeIsForValidation / setNodeIsForValidation. Then, we can enrich the search to be able to include only nodes that render glyph margins, and eventually expose that as a separate method on ITextModel, similar to getAllDecorations, maybe getAllMarginDecorations.

:+1: Done in https://github.com/microsoft/vscode/pull/179657/commits/c322dd0742b27b3f01fa3706846a3dd2bf0f762c

> Another thing that might happen is that users might want to opt out of this growing of the margin area, so maybe we need to add an editor option to limit the max glyph margin lane count.

I added `editor.glyphMarginDecorationsLimit`, here is a demo of how it works. When there are more decorations than can be rendered, we stop rendering decorations, which is pretty much the same behavior that we have today since today only one div gets rendered and all the classnames are merged):

https://user-images.githubusercontent.com/30305945/231246214-8ea89ab2-6cd2-4165-bdad-011cb9f08bab.mp4

**Comment by joyceerhl** [comment]
From standup today there was some feedback on the approach this PR takes, and I also learned about some prior discussions here. I opened https://github.com/microsoft/vscode/issues/179725 to get additional feedback on a new proposal and will rework this PR once we have settled on a better approach.

**Comment by joyceerhl** [comment]
Superseded by https://github.com/microsoft/vscode/pull/180013 and https://github.com/microsoft/vscode/pull/179910

**Pull request closed without merging**
