### PR TITLE
backup scratchpads on window close for hotexit=onexit

### LINKED ISSUE #183378: scratchpad editors should not confirm on window close when `hotexit` = `onexit`
follow up on https://github.com/microsoft/vscode/issues/174485

we should change the logic to just backup/recover scratchpad working copies when a window is closed, rather than prompting and forcing the user to save/discard.

https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupTracker.ts#L151

### PR DESCRIPTION
**Pull request by amunger**
fixes https://github.com/microsoft/vscode/issues/183378

this will change scratchpads to treat both hot exit settings the same, and will only veto for

```
test('should NOT hot exit (reason: CLOSE, windows: multiple, empty workspace)'
test('should NOT hot exit (reason: LOAD, windows: single, empty workspace)'
test('should NOT hot exit (reason: LOAD, windows: multiple, empty workspace)'
```

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Isn't this change missing some cases, such as changing to a different folder inside a window when having scratchpad working copies? I think in all cases where `false` (or now `[]` with your change) is returned, we would always want to include the scratchpad working copies, no?

**Comment by amunger** [comment]
>  I think in all cases where false (or now [] with your change) is returned, we would always want to include the scratchpad working copies, no?

I could have gone either way for context switches, so I'll change to recover scratchpads in that case.

But for ``test('should NOT hot exit (reason: CLOSE, windows: multiple, empty workspace)'``, we probably can't just backup since we can't tie it to a workspace to be recovered. We have a mechanism to recover those working copies when the application exits (just open an additional window next startup), but I don't know when it would be recovered in the multi window case.

**Comment by bpasero** [comment]
Yes, I would think that scrapbook working copies can only automatically backup in workspace/folder contexts where they can easily be recovered by simply opening said workspace/folder again. For empty windows its harder because we do not keep track of them when you change away from them in a window.

**Comment by bpasero** [comment]
I think essentially scrapbook working copies should be handled as if `"files.hotExit": "onExitAndWindowClose"` was configured. I realize how the setting is a bit misleading, because in fact we also support it when the window is not closed but changed to another workspace...

**Review by bpasero — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Pull request merged**
