### PR TITLE
Introduce promises to fileService.ts

### PR DESCRIPTION
**Pull request by katainaka0503**
Refactored resolveChildren() use TPromise instead of callback.

### CODE REVIEW

**Comment by katainaka0503** [comment]
After refactoring in first commit in this PR, `flow.sequence()` seems to be used nowhere.
So, I removed the method and it's tests.

**Comment by bpasero** [comment]
I have mixed feelings of replacing everything with promises, especially around code that is performance critical. For example now we seem to create a Promise for each file of a directory to resolve it which is garbage after done. The reason I do not mind the callback hell in the file service is that I really want to let it run fast and with as little objects as possible. The same is true for example in fulltext search where potentially lots of files get crunched.

**Comment by katainaka0503** [comment]
I see. I haven't considered performance.

I was take introducing Promise on blind face. And now rethinking about performance,I think this PR should be closed.

**Comment by bpasero** [comment]
@katainaka0503 no worries, thanks.

**Pull request closed without merging**
