### PR TITLE
Add quick-open support for relative file paths

### PR DESCRIPTION
**Pull request by mrkev**
When using the quick-open feature (`Cmd+P`), typing a file path relative to the directory of the currently active file should yield results if said file path is valid. See #46242 for discussion on how the feature should behave.

For a quick glimpse of the feature in action, in the `vscode` repo with an editor to `package.json` active and typing `Cmd+P ./product.json` currently yields: 

before

But after this PR yields:

after

### CODE REVIEW

**Comment by roblourens** [comment]
Why do you want this, when you can just search `product.json` and get the same result? @chrmarti 

Also I don't like that this syntax would behave differently from the `./` syntax in the search view's "files to include/exclude" where it resolves relative to the workspace, including selecting a workspace folder by name.

**Comment by mrkev** [comment]
I ran into the annoyance this fixes on the react codebase:

ezgif-5-0ad5e34f836f

I'd assume this annoyance to be fairly common on other large projects. In such cases, it's not rare for work to be fairly local and someone to know the file structure of a small vicinity. When jumping between files I knew where they were relative to where I was working, but I couldn't leverage this to clean up the extra noise in quick-open.

> Also I don't like that this syntax would behave differently from the ./ syntax in the search view's "files to include/exclude" where it resolves relative to the workspace, including selecting a workspace folder by name.

Do you suggest this should be resolved somehow? What are your initial thoughts?

**Comment by roblourens** [comment]
I would disambiguate by including part of the path of the folder. But I see why it would be useful.

Not sure about `./`... we also have this issue for searching workspace folder names in quick open, and maybe we would want `./` syntax for that too https://github.com/Microsoft/vscode/issues/32444

It's feels odd to me that quickopen would have this context in the current file when it feels more like a global control. Also, we would want stricter detection of this case (query must start with `./`), as it's written, we would have to check the disk before every usage of quickopen.

**Comment by bpasero** [comment]
> It's feels odd to me that quickopen would have this context in the current file when it feels more like a global control. 

Same feelings here. Maybe this could be a setting where you can change the default sorting of results to a model where the location of the active file is respected? As such, the files would get sorted in their order of how close they are to the currently opened file.

**Comment by chrmarti** [comment]
`./` should search form the workspace root *and* relative to the current file's folder. Merging these is a flexibility we have in QuickOpen because filtering down is part of the interaction whereas with text search we only want precise results.

**Comment by roblourens** [comment]
> Maybe this could be a setting where you can change the default sorting of results to a model where the location of the active file is respected?

This makes more sense to me. But then we would have to introduce this concept to the extension API which may or may not make sense. If the extension provider and frontend have different sort criteria, then it can be weird because there may be a more relevant result that was cut off by the maxResults limit.

> `./` should search form the workspace root and relative to the current file's folder

Not sure about this. `./` meaning two different places feels like it could be hard for people to wrap their head around... if we were just going in this direction, I'd rather have different syntax. `$/` for "workspace root" or maybe there is some other precedent. But then we have to change "files to include" too.

**Comment by chrmarti** [comment]
@roblourens Adding another prefix will make it harder to discover. Having a setting makes sense.

Adding an additional sort criteria to the API sounds like a lot of work for a feature that can be implemented as a UX feature. Similar to the absolute path lookup.

**Comment by roblourens** [comment]
The related issue has been closed as out of scope, closing this.

**Pull request closed without merging**
