### PR TITLE
Add .npmrc file association as ini-file

### LINKED ISSUE #92350: Add .npmrc file association as ini-file
.npmrc files are INI-files so it would be nice to automatically associate the language mode, like so:

```json
            {
                "id": "ini",
                "filenames": [
                    ".npmrc"
                ]
            },
```

Since VS Code [support Node.js out-of-the-box](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial) it would be nice it also then supports .npmrc out of the box.

### PR DESCRIPTION
**Pull request by thernstig**
This PR fixes #92350

### CODE REVIEW

**Comment by thernstig** [comment]
No idea why that unit test failed, seems unrelated to my simple change.

**Comment by thernstig** [comment]
Keeps failing on various, flaky, tests.

**Comment by aeschli** [comment]
@thernstig No worries about the tests.

**Comment by aeschli** [comment]
I made the suggested change (ini to properties)

**Comment by thernstig** [comment]
@aeschli I missed your last comment. According to https://docs.npmjs.com/configuring-npm/npmrc.html#files the .npmrc file is in ini-format. What made you deduct it is really a properties format?

https://docs.npmjs.com/configuring-npm/npmrc.html#comments

Packages used to parse .npmrc: https://github.com/npm/ini

**Comment by aeschli** [comment]
In VSCode we give the Window-ini files the `ini` id, and UNIX-style ini file have the id `properties`.

You can test it in the latest insiders.

**Pull request merged**
