### PR TITLE
Git status representation in the explorer viewlet implemented

### LINKED ISSUE #5866: Show git status for files in explorer
what if i have a folder of 100 files all changed except one or two
i can see the changed one in git view but how to find the unchanged ones?
if the modified files were a different color in explorer then it would be easy to see (like Atom)
thanks

### PR DESCRIPTION
**Pull request by kisstkondoros**
Resolves #5866

image

### CODE REVIEW

**Comment by bpasero** [comment]
Unfortunately I cannot accept this PR as such because it introduces a dependency from files land to git land. Logically files land should not be aware of git land but rather we should have extension points that allow us to modify the colors and possibly icons in the explorer from the outside. This would maybe also allow extensions to do this.

**Comment by kisstkondoros** [comment]
@bpasero If I got you right then we could do the following:
The FileRenderers get's a registry whose items can be processed in renderContents method.
This way there is no thight coupling, and this registry could be used maybe even from extensions.

the interface in use could be e.g.
```typescript
interface FileRendererDecorator {
    decorateItem(tree: ITree, stat: FileStat, explorerItemLabel: HTMLElement) : void
}
```

perhaps this could even be used to support icons in the explorer.

**Comment by bpasero** [comment]
Yes, we need a registry where other components can participate in decorating explorer items. I actually think this should be generic enough for any tree we have and not just the explorer. Trees can then opt in to decide if they want to participate in decorations or not and the explorer could be the first one of those. 

Have not yet thought about how the API (both internal and possibly external could look like). Maybe we open a discussion issue first?

**Comment by kisstkondoros** [comment]
@bpasero Good idea, please open a discussion issue when you have some time :+1:

**Comment by kisstkondoros** [comment]
@bpasero I've updated the implementation according to what we have discussed, please have a look

**Comment by bpasero** [comment]
Thanks, since it is currently endgame, expect no reply until July milestone 👍

**Comment by kisstkondoros** [comment]
Some more related issues: #1394, #211, #4837, #1086, #178

**Comment by bpasero** [comment]
Adding @joaomoreno because this PR touches a lot in tree and git land.

**Comment by johanneslamers** [comment]
Oh yes please!! As soon as possible!!

**Comment by sallar** [comment]
Why is this closed? :)

**Comment by joaomoreno** [comment]
I think there are a few shortcomings with the current approach:

- Augmenting the tree's API is unnecessary. The tree provides a structure around HTML elements. The contents of each tree row, after `render` is called, are not the tree's responsibility no more. So, adding a decorator API at that layer is wrong.
- There are also layer breakers such as git knowing about `OpenEditor` and `FileStat`, or worse, knowing about how these are rendered: `row.element.querySelector('.open-editor .name')`.

**Pull request closed without merging**
