### PR TITLE
go back to replacing just one space in terminal accessible buffer

### PR DESCRIPTION
**Pull request by meganrogge**
This reverts commit 996418da33b6de4ffe464bcb3496d9fe850810cc, reversing changes made to 2fb606ead68ca10e1dded75ab31ee80e8638710e.

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]

**Comment by Tyriar** [comment]
That works, we can treat this as debt and move this to June as it probably isn't harmful.

**Comment by meganrogge** [comment]
Just a string change now, so think it's safe but yeah can push to June

**Comment by Tyriar** [comment]
Oh actually, I think monaco might do this anyway which is why I saw single spaces changed to nbsp. Maybe we could just remove the regex replace all together?

**Comment by meganrogge** [comment]
Nice, yeah will investigate in June

**Pull request closed without merging**
