### PR TITLE
`Screencast Mode` add Custom color and size

### PR DESCRIPTION
**Pull request by d1y**
I like vscode very much and hope this proposal can be passed

Thank you 🙈

### CODE REVIEW

**Comment by d1y** [comment]
@lszomoru

**Comment by d1y** [comment]
Hello, brother. How is the progress

@lszomoru

**Comment by lszomoru** [comment]
@d1y, looks like you have deleted your remote. 
I need to make some minor changes to the code so I will create a new PR, and will mark you are a co-author.

**Comment by d1y** [comment]
> @d1y, looks like you have deleted your remote.
> I need to make some minor changes to the code so I will create a new PR, and will mark you are a co-author.

What do I need to do now?

**Comment by lszomoru** [comment]
@d1y, nothing :) I have posted your changes to this PR - https://github.com/microsoft/vscode/pull/105219

**Pull request closed without merging**
