### PR TITLE
chore: update minimum installable version in inno setup

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Refs: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

According to electron's website, electron 22 will be the last version to support windows 8/8.1.

### CODE REVIEW

**Review by deepak1556 — CHANGES_REQUESTED** [review]
Thanks for the PR!

I will block this change until we send out deprecation notice and prepare for EOL.

/cc @isidorn @joaomoreno , refs https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

We should handle the deprecation notice with `v1.77` and allow enough time for Electron 23 adoption.

**Comment by deepak1556** [comment]
Yup same flow as other previous deprecations. We already have the general structure setup in both client and server, so it will be easy to add new versions. I will create an issue for this deprecation.

**Comment by deepak1556** [comment]
@ChaseKnowlden can you rebase on top of latest `main`,  I think this change is good to go now that https://github.com/microsoft/vscode/issues/177676 is resolved.

**Comment by ChaseKnowlden** [comment]
Up-to-date. @deepak1556

**Review by Alibayat4545 — COMMENTED** [review]
2971

**Review by deepak1556 — APPROVED** [review]
Thanks!

**Review by joaomoreno — APPROVED** [review]

**Pull request merged**
