### PR TITLE
delete unused fish file

### LINKED ISSUE #179353: Strange workbench contrib `src/vs/workbench/contrib/xdg_data/fish`
(I think from https://github.com/microsoft/vscode/pull/168211)

I came across `src/vs/workbench/contrib/xdg_data/fish/vendor_conf.d/vscode-shell-integration.fish` and fail to understand why it was put there. `workbench/contrib` is for code contributions that enrich the workbench experience but not for loose files. 

Can we move this into the terminal contribution land?

### PR DESCRIPTION
**Pull request by meganrogge**
fix #179353

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Bit hard to see what's going on in this diff, but I don't think the original file is being deleted?

image

I forgot why this file exists, is it referenced by docs or the CLI or fish docs or something?

**Comment by meganrogge** [comment]
from the PR, fish expects this script to be in this location, but we want it with the other scripts, so this is just a pointer to that. we could instead just move our shell integration script inside this file

**Comment by Tyriar** [comment]
I think the previous one was a symlink but the new one isn't?

Screenshot 2023-04-06 at 11 44 43 am

**Comment by Tyriar** [comment]
The docs say to run this which points at the actual script:

Screenshot 2023-04-06 at 11 46 28 am

https://code.visualstudio.com/docs/terminal/shell-integration

I'm not sure this file does anything? 😕

**Comment by meganrogge** [comment]
Yeah you're right - I had assumed that was doing something. I deleted the file and it still works

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
