### PR TITLE
💄 Include file system path in debug mode's URI/link hovers

### LINKED ISSUE #164486: Show full string when hovering string paths in debugger variables tab
When I'm debugging code I like to have the debugger tab docked to the left side of the screen. However, this is a problem when debugging anything with strings containing file paths because the end of the string gets cut off by the edge of the pane. Most other data types get around this by allowing you to hover over them, which displays a tooltip containing more information. However when hovering a string that contains a file path it instead shows "Cmd + click to follow link". Currently I have to either copy the value and paste it somewhere else to read, or I need to expand the variables tab which means I don't have much room for my code view, both of which really take me out of my debugging flow.

### PR DESCRIPTION
**Pull request by babakks**
Fixes #164486

With this PR, only file system URIs (i.e., URIs with `file://` scheme or no scheme at all) are also included in the hover box content:

With file path in hover

Note that the current behavior is kept for other URI schemes (e.g., `http`/`https`):

Without file path in hover

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks, good start. But I think the behavior for http URIs should match, and also, I'm wondering whether it should actually include the full value of the variable, not just the link target. For example, you could have `"/foo/bar more text"` and `more text` would not be part of the link, but still cut off.

**Comment by babakks** [comment]
I've updated the PR. Now it displays the full text:
hover-2

But, it also includes the full text in the links detected inside the debug console. Is that okay? See this:

hover

**Comment by roblourens** [comment]
Thanks, I like that. But no, this should only be enabled for the debug views

**Comment by babakks** [comment]
Changed it. Now it only works for the debug view expressions.

**Review by roblourens — APPROVED** [review]
This is great, thanks!

**Pull request merged**
