### PR TITLE
Typos in user-facing code and variables.

### PR DESCRIPTION
**Pull request by ghost**
This PR is all about typos. Under most circumstances, these changes do not affect the product itself. However, as some are user facing issues, I figured I fix the variable names and user-facing strings so that both programmers and users can benefit.

No behavior changes otherwise, except the user-facing strings displayed.

### CODE REVIEW

**Comment by pi1024e** [comment]
If those changes need documentation, please tell me where I can document them so these changes can be merged. Thank you!

**Comment by rebornix** [comment]
thanks for your help! it seems the pr is a mix of 

* typo fix
* if block condition
* indentation change
* grammar update https://github.com/microsoft/vscode/pull/78049/files#diff-279a1a8a5c0a9457a43e124c4f1e14aa 

I'll suggest we only do the first one for now.

**Comment by pi1024e** [comment]
Made changes!

**Comment by pi1024e** [comment]
Are there any changes that should be made to this? Are these changes acceptable? Please let me know!

**Comment by pi1024e** [comment]
Did everything. This is ready to go! @rebornix

**Comment by pi1024e** [comment]
@rebornix please check this as soon as possible, so I don't have to rebase every hour or so. Thank you!

**Comment by rebornix** [comment]
@pi1024e I plan to merge it by the end of this week, after we finish our testing of current iteration. You don't need to do rebase as we will do a merge at the end.

**Comment by rebornix** [comment]
@pi1024e thanks again for your contribution. As we discussed above https://github.com/microsoft/vscode/pull/78049#issuecomment-515841622, we want to fix typos only in the pull request for now but it seems there are many grammar changes https://github.com/microsoft/vscode/pull/78049/files#diff-279a1a8a5c0a9457a43e124c4f1e14aa and many syntax updates (e.g., https://github.com/microsoft/vscode/pull/78049/files#diff-358e9af647e68fe2ad7c0b406bb688a7), which are not expected.

Instead of making a large pull request, we always recommend PRs with smaller changes otherwise it would be difficult to review. Right now the diff view page simply crashed my browser all the time. Besides, the code change touches almost every component, which is beyond my knowledge and I can't review this alone.

My recommendation is still

1. Only user facing ones (it's fine that some of the code comments have some typos)
2. No code syntax change (for example, change the sequence of `if` block)
3. No grammar change (which is breaking change)

Thanks again for your help ;) I also recommend closing this PR as it's giant.

**Comment by pi1024e** [comment]
I just learned how to make more branches on my repo, so now I know how to keep only typo related changes here! Not to mention, there are so many typos, and now I ensured this PR only contains those fixes.

**Comment by pi1024e** [comment]
Ok. Here is what I will do.

**Comment by pi1024e** [comment]
I will make a pr for every individual file change so it will not be too much, ok?

**Comment by rebornix** [comment]
@pi1024e sending PRs for every individual would be too much I think. You can try to send prs for individual components (you can tell them by folder or names) and if every PR contains changes for individual component and only contains couples of file changes, then it's good.

BTW, before you send new PRs, I still want to make sure we are on the same page. Me personally think some typos in methods/identifiers/comments are okay as long as they don't confuse ppl. And also real typos only.

**Comment by pi1024e** [comment]
Ok. Thank you.

**Pull request closed without merging**
