### PR TITLE
fix ini #13648

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Divided ini file(use comment `;`) and other like ini file (use comment `#`)
and use [INI syntax highlighting for Sublime Text 2 ](https://packagecontrol.io/packages/INI)

related #8709

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks @Ikuyadeu . There's a spelling mistake in `propaties`. Other than that the changes look good.

**Comment by Ikuyadeu** [comment]
@aeschli ,　Thank you for correcting my mistakes. 
typo was fixed.

**Comment by aeschli** [comment]
Thanks @Ikuyadeu, PR accepted!

**Comment by aeschli** [comment]
I made a change to use the same grammar ("./syntaxes/properties.plist") for both ini and properties.
It's not clear where https://github.com/clintberry/sublime-text-2-ini comes from. We can only add it to VSCode if the license allows it.

**Pull request merged**
