### PR TITLE
Define less fonts

### PR DESCRIPTION
**Pull request by jrieken**
@alexandrudima always suspected that declaring many different fonts slows down the initial (and subsequent?) layout calls. I have measured this and found that it's true, the difference with this PR is around 10ms, not much but also an easy change. 

This is how I have measured

* show explorer (without open editors or any other section)
* show no editors
* use the performance tab to measure the duration of the first real layout

**Before**
screenshot 2018-12-28 at 12 16 42

**After**
screenshot 2018-12-28 at 12 16 02

My change defines the same fonts but per platform. There is now some duplication with

https://github.com/Microsoft/vscode/blob/dacef0561ac0e364f7add5de2177f2943dee6173/src/vs/workbench/electron-browser/workbench.ts#L295

and maybe we should make a better change for this

### CODE REVIEW

**Comment by jrieken** [comment]
Oh, I also wasn't sure what to pick for the `hans`, `hant`, `ja`, `ko` language selectors...

**Comment by bpasero** [comment]
@jrieken I think its fine to lift the platform selectors to the shell/body level but then I would remove the workbench specific platform decoration and change the CSS classes we have that leverage it. E.g. from e.g. `.monaco-workbench.linux` to `.linux > .monaco-workbench` or `.linux .monaco-workbench`

I cannot recall which of those CYK fonts is being used on which platform (except for the obvious ones with Microsoft in their name).

**Comment by jrieken** [comment]
I have pushed another change that removes the inner platform classname meaning we only have it once now...

**Comment by be5invis** [comment]
@jrieken @bpasero 

↓ This is the matrix for localized fonts. Add them after your current English font list and before the general font (`sans-serif`).

Also, `"HelveticaNeue-Light"` could be removed now: it was used by Mac (not Windows) but no longer needed.

| Language | Mac                                                    | Windows                    | Linux                                                        |
| -------- | ------------------------------------------------------ | -------------------------- | ------------------------------------------------------------ |
| zh-Hans  | `"PingFang SC", "Hiragino Sans GB"`                    | `"Microsoft YaHei"`        | `"Source Han Sans SC", "Source Han Sans CN", "Source Han Sans"` |
| zh-Hant  | `"PingFang TC"`                                        | `"Microsoft Jhenghei"`     | `"Source Han Sans TC", "Source Han Sans TW", "Source Han Sans"` |
| ja       | `"Hiragino Kaku Gothic Pro"`                           | `"Meiryo"`                 | `"Source Han Sans J", "Source Han Sans JP", "Source Han Sans"` |
| ko       | `"Nanum Gothic", "Apple SD Gothic Neo", "AppleGothic"` | `"Malgun Gothic", "Dotom"` | `"Source Han Sans K", "Source Han Sans JR", "Source Han Sans", "UnDotum", "FBaekmuk Gulim"` |

**Comment by jrieken** [comment]
@be5invis I have pushed another change (8e47e88490) that implements the matrix above. Thanks so much!

**Comment by bpasero** [comment]
Cool, I have removed `HelveticaNeue-Light` (https://github.com/Microsoft/vscode/commit/83232ef0608d56e07f7e9b92ca1026560d8fd8fc). Hope that does not brake things on older macs.

**Comment by bpasero** [comment]
@alexandrudima we could maybe let the shell.css define a rule such as ".monaco-workbench .monospace-font: ..." and then everyone that wants this font adds that class to their elements, is that what you suggest?

**Comment by alexandrudima** [comment]
@bpasero Yes, that would work nicely. We could also split that `.monospace-font` such that we have 3 rules per different OSes. i.e. "Droid Sans Mono" was used only on Linux.

We just have to be a bit careful with stuff that ships in the monaco editor, where such a class is not available (or perhaps define there somehow as well).

**Pull request merged**
