### PR TITLE
Adding most frequently used file associations

### PR DESCRIPTION
**Pull request by digitarald**
As an addition to #127075, this patch expands registered file types for VS Code based on widely and frequently used file extensions.

### CODE REVIEW

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
All code changes look good, great work 👏  Great that you added them sorted to the win file.

@digitarald did you build VS Code, so we try this out end to end before merging? Just in case I triggered a build off this branch so hopefully we should have something soon to try out and make sure we did not break anything. Once we have a build and all looks good I suggest you merge this in. Thanks!
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=131485&view=results

fyi @bpasero as an optional reviewer (in case you feel like it)

**Comment by isidorn** [comment]
We were unlucky that there was an unrelated compilation error when triggering builds. Thus I merged master on top and re-triggered build.

**Comment by digitarald** [comment]
@isidorn I checked the _darwin_ builds from the [artifacts](https://monacotools.visualstudio.com/Monaco/_build/results?buildId=131503&view=artifacts&pathAsName=false&type=publishedArtifacts) and could not see the added file types in the `Info.plist`. I'll be trying to build locally and at least validate on macOS.

**Comment by digitarald** [comment]
@isidorn I added a fix recommended by @deepak1556. I couldn't figure out how to trigger the build in time though.

**Comment by isidorn** [comment]
@digitarald oh so you also had to change the javascript file. Okey. I triggered another build and then you can verify mac, and I will do Win on my VM.
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=131628&view=results

**Comment by digitarald** [comment]
@isidorn thank you, also for teaching me how to fish! It tested on mac for most added file types 👍. If all looks good on Windows, feel free to merge.

**Comment by isidorn** [comment]
Looks good on Windows. I tried out the `.dart` extension.
Merging so we get feedback start of next week since this should be in Insiders on Monday.

fyi @xandifix

**Pull request merged**
