### PR TITLE
Separate shared process ipc (client) ready and server ready

### PR DESCRIPTION
**Pull request by sandy081**
Issue:

Currently main is waiting to register its services, until the shared process is ready and initialised. This is an issue if services in shared process need to request main during initialisation. Eg: Storage service initialisation on shared process.

Given this scenario where main as server and shared process as client, server can wait until the client connection is established to register its channels.

This PR introduces a new barrier `whenIpcReady` that is released when shared process ipc (client) is ready and thereafter server (main) can register its channels. Those who are clients to shared process should keep continue to wait `whenReady` that is when shared process is ready and initialised.

### CODE REVIEW

**Comment by joaomoreno** [comment]
I believe this got to a point which is incredibly hard to understand. I decided to take 30 minutes to unwrap it and I got lost in all the spaghetti.

I suggest to document the exact order and direction of all the expected messages during handshake, as well as what should happen between each message.

Feel free to merge if it works.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/90136/commits/edf7a551c3fdae553d9a017005bae541c9a3b88a hopefully makes this clearer now

**Comment by joaomoreno** [comment]
@bpasero Good job!

**Comment by sandy081** [comment]
Great. Thanks @bpasero for descriptive messages.

Talked to @joaomoreno and merging it.

**Pull request merged**
