### PR TITLE
Debug: Added collapse all in debug console Fixes: #38109

### PR DESCRIPTION
**Pull request by svitlana-galianova**
Added a "Collapse All" button in DEBUG CONSOLE in both light and dark color schemes.
Let me know if there is any way I can improve this code, issue #38109

collapsealllight

collapseall

### CODE REVIEW

**Comment by isidorn** [comment]
@svitlana-galianova thanks a lot for your PR. Seems to work nicely, however in the issue I already mentioned that I would only accept if this is added to the context menu, not to the title area because I do not want to introduce clutter in the debug console title area (limited space when panel is vertical).

So in order for this PR to be merged, I would require two things:
* Action added in the context menu, not the title area
* Remove all your formating changes to unrelated files, in this PR you can see all the changes you have done. A nice PR always touches the minimal amount of code needed for the change, that is not the case here as a lot of lines have been formated. All that needs to be reverted in order for us to accept this

After this has been done I can provide more detailed feedback if needed.
Thanks 🍹

**Comment by svitlana-galianova** [comment]
I have fixed an indentation. But I don't know what context menu is, could you please provide a screenshot or code pointer to that? Thank you!

**Comment by isidorn** [comment]
@svitlana-galianova cool the identation is now fixed. The context menu is when you right click anywhere in the debug repl
Here's a code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L436

screen shot 2018-02-20 at 16 38 59

**Comment by svitlana-galianova** [comment]
Here is a gif how it works now! 

collapseall

**Comment by isidorn** [comment]
@svitlana-galianova looks great. Here's some feedback:
* There is no need for CollapseAllReplAction, you can use the CollapseAllAction instead
* I would expect that the Clear action is the last since it is the strongest
* I would expect a seperator between clear debug console and everything else for nicer visual seperation

**Comment by svitlana-galianova** [comment]
I have removed that extra class and moved "Clear Console" option to the end. 

collapseall

How can I add a separator? Should it be done in CSS? Maybe you can give me an example of what you are expecting, it would be super helpful, thanks

**Comment by isidorn** [comment]
@svitlana-galianova great. Here's an example of using a separator https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts#L150
So it should be pretty simple

**Comment by svitlana-galianova** [comment]
So I have added a separator and here is a screenshot 😄 

collapseall

**Comment by isidorn** [comment]
Great work, merging in the pr 🍹

**Pull request merged**
