### PR TITLE
Switch to ESM

### PR DESCRIPTION
**Pull request by alexdima**
re https://github.com/microsoft/vscode/issues/160416

To run:
* run `node migrate.js`
* run `yarn watch`

---

To do:
* [x] run from source
  * [x] main process
  * [x] renderer window
  * [x] extension host process
  * [x] extension host web worker
  * [x] editor worker
  * [x] output link computer
  * [x] issue reporter window
  * [x] process explorer window
  * [x] shared process window
  * [x] shared process web worker (enables search and file watching)
* [x] run web from source
* [x] run server from source
* [x] run unit tests
  * [x] node-based (`mocha test/unit/node/index.mjs --delay --ui=tdd --timeout=5000 --exit --esm`)
  * [x] electron-based (`./scripts/test.sh --esm`)
  * [x] browser-based (`yarn test-browser --esm --browser chromium`, only chromium because of importmap, likely needs an update of playwright)
* [x] run integration tests
  * [x] browser-based (`./scripts/test-web-integration.sh --esm`)
  * [x] electron-based (`./scripts/test-integration.sh --esm`)
  * [x] remote
* [x] run smoke tests
* [ ] bundling
  * [ ] ASAR
  * [x] nls

### CODE REVIEW

**Comment by lemanschik** [comment]
I Should maybe inform you that i am working on a simple Raw ECMAScript build using the nativ ECMAScript Module System including its resolve and load capabilitys also i saw code references in the loader that show that you got problems with dynamic function creation for that the solution is data url imports or creating blob urls from scripts and import the blob url

types.d.ts
```ts
declare module "data:text/javascript;*" {
  export const number: number;
  export function fn(): string;
}
```

index.js
```
/// <reference path="types.d.ts"/>
import { number, fn } from 'data:text/javascript;charset=utf-8;base64,ZXhwb3J0IGNvbnN0IG51bWJlciA9IDQyOwpleHBvcnQgY29uc3QgZm4gPSAoKSA9PiAiSGVsbG8gd29ybGQiOw==';
```

else look also up as sayed creation of blub urls from js scripts. 

hope that helps,

my build is working and backward compatible it can produce any build result as it is static analyzeable i created whole import maps programatical for the old code under src/*

i am 3 functions away from a working AMD loader replacement with the same load require methods.

**Comment by lemanschik** [comment]
Also should point out that i did a proposal that would make most of this obsolete as you do not even need to build nativ components as much anymore and components in general this drops over 80% of the existing code base and leaves it to a API skeletton like repo as it offers everything implemented out of the box via existing implementations:

- https://github.com/microsoft/vscode/issues/166840

i leave it up to you to discusse that internal. the short sum up of that is use devtools nativ as UI it offers sidePanels and all that stuff

**Comment by sualehasif** [comment]
This PR looks phenomenal! Quite excited for this release. Wondering if this will lead to HMR support for development inside VSCode. Not sure if that will require switching the bundler (which feels quite hard), or possibly in the gulp pipeline.

(btw, I absolutely love [vite](https://vitejs.dev/guide/features.html#hot-module-replacement) and would be excited if VSCode transitioned to it at some [point](https://github.com/cawa-93/vite-electron-builder).) 

Is this planned for the May release or will this be coming later?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/166033/commits/51494382ebd4c77af2389b3cbc80876422b6ea68 is a larger change to make all our JS entry points and related bootstrap friends ESM ready. 

You can now `scripts/code.sh` with a `type: module` in `package.json` and a window appears. I did not want to push that change to `package.json` because it has a cost in a lot of other scripts (tests, and for example `node migrate.js` no longer runs).

**Review by Fobnud-8wokpo-qivsyz — APPROVED** [review]

**Comment by bpasero** [comment]
The changes in this PR have been ported to `main` and we can now build with ESM from `main` using this build option:

image

Developing locally from `main`:
* `node migrate.mjs`
* `yarn watch-esm`
* `scripts/code.sh`

**Pull request closed without merging**
