### PR TITLE
Clarify pipeline actions

### PR DESCRIPTION
**Pull request by rzhao271**
Part of an internal work item.

### CODE REVIEW

**Comment by rzhao271** [comment]
Disabling auto-merge to get more feedback before merging in the change.
I accidentally added Connor to the review because I thought I changed up some CLI files, but it appears I haven't.

**Comment by rzhao271** [comment]
Made changes to some CLI files.

**Review by connor4312 — APPROVED** [review]

**Review by deepak1556 — COMMENTED** [review]
LGTM

Is the name edits to specify (OSS), (Windows) etc purely for debugging purpose or is it more of a styleguide thing to distinguish similar `displayName` that should be followed from here onwards ?

**Comment by rzhao271** [comment]
It's purely for debugging purposes and because I was confused while seeing the same step seemingly duplicated multiple times

**Review by deepak1556 — APPROVED** [review]

**Review by lszomoru — APPROVED** [review]

**Pull request merged**
