### PR TITLE
improve styling of terminal accessibility help

### LINKED ISSUE #172344: Terminal Accessibility Help dialog stretches from bottom of terminal panel
Testing #171862

The bottom edge of the Terminal Accessibility Help dialog seems attached to the bottom of the Terminal panel

image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #172344
Screenshot 2023-01-25 at 9 03 19 AM

### CODE REVIEW

**Comment by Tyriar** [comment]
I suggested a different approach in https://github.com/microsoft/vscode/issues/172408#issue-1556941813, not sure if it's better

**Comment by meganrogge** [comment]
I tried your approach and the scrollbars look rough IMO. The styling in this PR aligns well with the one in the editor. Do you have concerns about specific layouts with this approach?

**Comment by Tyriar** [comment]
Oh I thought the scroll bars would only show if the container exceeded the allowed space? That was for the edge case where the terminal is so small that it needs one. This is fine, I just normally do this type of thing via translate

**Review by Tyriar — APPROVED** [review]
Approved but let's leave to February as it missed testing and is low priority

**Pull request merged**
