### PR TITLE
fix: disable shm usage in container builds

### LINKED ISSUE #111729: Build: Fix Linux integration tests
Our Linux Integration Tests have been often failing with out of memory for a while now. They have been disabled until we fix the underlying problems: https://github.com/microsoft/vscode/commit/8041440e5b6f417afec05d8e0cd677282905d520

Log: [427.txt](https://github.com/microsoft/vscode/files/5628146/427.txt)

The log shows warning messages throughout the suite:

> 2020-12-02T08:33:39.7341572Z [2187:1202/083339.733520:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space in temporary directory for shared memory files: 63

> 2020-12-02T08:35:38.7932977Z [3851:1202/083538.792646:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space in temporary directory for shared memory files: 37

And then it finally fails:

> 2020-12-02T08:35:46.8014431Z [3918:1202/083546.798288:FATAL:memory.cc(38)] Out of memory. size=131072

A few things to note:

- When the crash happens, the build step never finishes, so the build ultimately fails with a 1h timeout. We should look into why Electron doesn't exit when this happens. @deepak1556 
- That `Out of memory. size=131072` number seems extremely low. Though this could very well be the size that is asked to be allocated. 🤔 

@deepak1556 Is there any easy way of checking how much memory is available to Electron? Apparently the VM has 7 GB, so I'm thinking that the tests are running in a constrained environment and they don't have access to the entire memory.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/111729

### CODE REVIEW

**Comment by joaomoreno** [comment]
Build is failing: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=96161&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=bf591f68-b11f-58a5-2795-b482f67ba1e7

**Comment by joaomoreno** [comment]
Also before merging this, we should really be sure of the bionic update.

**Comment by deepak1556** [comment]
> Build is failing: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=96161&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=bf591f68-b11f-58a5-2795-b482f67ba1e7

Oops the xvfb step is not needed, container establishes it.

> Also before merging this, we should really be sure of the bionic update.

Yup. Although image is bionic, it now uses older gcc toolchain to maintain compatibility. Got some early testing happening here https://github.com/microsoft/vscode-remote-release/issues/4103

**Comment by joaomoreno** [comment]
@deepak1556 Now the integration tests fail misteriously: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=96200&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=a099afca-dbc0-5987-bf48-8950ed3c0139&l=198

**Comment by deepak1556** [comment]
failing due to, looking into it.

```
[2498:1204/180442.771943:ERROR:viz_main_impl.cc(152)] Exiting GPU process due to errors during initialization

[2473:1204/180442.939298:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PolicyKit1 was not provided by any .service files
```

**Comment by joaomoreno** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=96408&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=2d4939b1-2b74-59b7-3eb2-605f0910a1a9

🥳

**Comment by deepak1556** [comment]
Looks like hw compositing is not available

```
[2886:1208/083944.049321:ERROR:gl_surface_egl.cc(725)] No suitable EGL configs found.
[2886:1208/083944.049435:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Error) eglGetConfigAttrib: Bad config.
[2886:1208/083944.049468:ERROR:gl_context_egl.cc(95)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[2886:1208/083944.049579:ERROR:gl_surface_egl.cc(725)] No suitable EGL configs found.
[2886:1208/083944.049616:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Error) eglCreatePbufferSurface: Bad config.
[2886:1208/083944.049642:ERROR:gl_surface_egl.cc(2076)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[2886:1208/083944.049666:ERROR:gpu_info_collector.cc(65)] gl::GLContext::CreateOffscreenGLSurface failed
[2886:1208/083944.049690:ERROR:gpu_info_collector.cc(273)] Could not create surface for info collection.
[2886:1208/083944.049716:ERROR:gpu_init.cc(77)] CollectGraphicsInfo failed.
[2886:1208/083944.052240:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[2894:1208/083944.102557:ERROR:command_buffer_proxy_impl.cc(122)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
```

Let me fix that before we merge this.

**Comment by deepak1556** [comment]
@joaomoreno this is ready for review, shm and gpu issue logs have been cleared https://monacotools.visualstudio.com/Monaco/_build/results?buildId=96465&view=results

**Pull request merged**
