### PR TITLE
Closes #27410 - support multi-select on open file/changes commands

### LINKED ISSUE #27410: Git: Allow Open File & Open Changes commands to support multi-select
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Currently you can multi-select items in the Git files view and if you right-click, the `Open File` & `Open Changes` menu items will only open the file/change of the focused item, with the stage/unstage command work with the whole selection. It would be great to have these 2 command act upon the whole selection.

### PR DESCRIPTION
**Pull request by eamodio**
See https://github.com/Microsoft/vscode/issues/27410

Also stops the opening of an editor from stealing focus -- so that it is much easier to keyboard around (it also aligns with the behavior of the main file explorer)

That there are comments in the code noting things that need to be changed once PR https://github.com/Microsoft/vscode/pull/27357 is merged.

### CODE REVIEW

**Comment by eamodio** [comment]
I think that failure is just a timing issue unrelated to my changes

**Comment by eamodio** [comment]
@joaomoreno any thoughts on this? I'd love to get this in ;)

**Comment by joaomoreno** [comment]
@eamodio Was out on vacation, will look at this in the next few days.

**Comment by eamodio** [comment]
@joaomoreno I resolved the conflicts on this -- any chance this can make it into the August milestone? ;)

**Comment by joaomoreno** [comment]
Thanks!

**Comment by eamodio** [comment]
@joaomoreno I didn't see this PR in the release notes for August -- did this not make it in? Or just an oversight?

**Comment by joaomoreno** [comment]
Definitely an oversight.

@egamma The PR tool seems to have failed to capture this PR for the Thank You section. I've added it manually: https://github.com/Microsoft/vscode-docs/pull/1159

**Comment by egamma** [comment]
@joaomoreno the PR tool checks the milestone whether a PR should be considerd and this PR is assigned to backlog and not the August milestone.

**Comment by joaomoreno** [comment]
That explains it!

**Comment by eamodio** [comment]
@joaomoreno @egamma thank you!

**Pull request merged**
