### PR TITLE
Fix php function highlight

### PR DESCRIPTION
**Pull request by luxifer**
According to http://php.net/manual/en/functions.user-defined.php extended ascii is allowed in function name such as non breaking space ` ` (\xa0).

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks @luxifer!
The PHP grammar that we use is from https://github.com/atom/language-php and we want to avoid having our fork. Would you mind make the PR there? Once accepted there, please ping me and I'm happy to run our update script.

**Comment by luxifer** [comment]
see https://github.com/atom/language-php/pull/196

**Comment by luxifer** [comment]
If you want, when you have updated the grammar I can submit another PR with only the tests to ensure the new grammar works

**Comment by luxifer** [comment]
@aeschli the PR on atom has been merged

**Comment by aeschli** [comment]
@luxifer I updated the grammar. Thanks a lot!

**Comment by luxifer** [comment]
I guess it will be part of the may 2017 release?

Le 18 mai 2017 11:12 AM, "Martin Aeschlimann" <notifications@github.com> a
écrit :

**Comment by aeschli** [comment]
@luxifer Yes

**Comment by luxifer** [comment]
Here's the pull request with only the tests https://github.com/Microsoft/vscode/pull/26992

**Pull request closed without merging**
