### PR TITLE
CSS - Search in parent folders for node module resolution

### LINKED ISSUE #136: Ctrl+click (go to file) doesn't work for saas-loader ~ imports (node_modules)
Trying to Ctrl+click on the imported module name fails:
```scss
@import '~bootstrap/scss/bootstrap';
```
with this error:

```
Unable to open '_bootstrap.scss': File not found (file:///PROJECT/src/styles/~bootstrap/scss/_bootstrap.scss).
```

The reason is that I'm using `webpack` with `saas-loader`, and `saas-loader` treats an import path starting with `~` as an import from `node_modules`: https://github.com/webpack-contrib/sass-loader#imports

So the actual location from where the import should be loaded is:
```
file:///PROJECT/node_modules/bootstrap/scss/_bootstrap.scss
```

### LINKED ISSUE #78894: [scss] link doesn't work with ~Tilde to search in node module or webpack alias
Using a **~**Tilde to go directly to a node_module path without having to add aliases to webpack this path doesn't get resolved by VS Code. 

So with a node_module 'bootstrap' installed, we can import bootstrap sass-files using this construction:

``` scss
@import '~bootstrap/scss/bootstrap-grid';
@import '~bootstrap/scss/utilities/sizing';
```
While this is working fine with Webpack and the sass-loader/node_sass, VS Code doesn't recognise this tilde-construction and searches on a follow-link in our `source-folder\bootstrap\` instead of in `node_modules\bootstrap\`

When we use aliases in Javascript we solved his resolve problem by adding aliases to the jsconfig.json. But AFAIK there's not such a config file for Sass in VS Code.
I've been searching everywhere, including settings on sass, but couldn't find anything where we could make VS Code respect the node_modules path (and Webpack aliases) with a tilde~.

So unfortunately we seem to not being able to click to follow link on these sass imports.

**versions**
- VSCode Version: 1.37.0
- OS Version: Windows 10 Home Updated

**Steps to Reproduce:**
1. Have a node modulle, like node_modules/bootstrap, installed
2. Import a sassfile from this module, like `@import '~bootstrap/scss/bootstrap-grid';`
3. Ctrl+click on the import line to try to 'Follow Link'
Result: it shows an error-message popup saying 'Unable to open' with the wrong path

**extensions**
Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by penx**
Replaces my previous PR #79651 by implementing [recommendations](https://github.com/microsoft/vscode/issues/78894#issuecomment-535254539) from @octref on #78894 .

Further to #70693 which was reworked by @aeschli  in https://github.com/microsoft/vscode/commit/8f7293470661319099bdda43eecc386a43c87189 due to issues with require.resolve and webpack.

- Fixes #78894
- Fixes microsoft/vscode-css-languageservice#136

The current implementation for microsoft/vscode-css-languageservice#136 resolves the path to a CSS module but only looks for node_modules in the same folder as the CSS file, which for many use cases is not sufficient.

This PR updates `resolvePathToModule` so that it looks in parent folders for the existence of `node_modules/module-name` all the way up to the workspace root, following node module resolution.

Alternative approaches were raised in #79651 and this approach was preferred by @octref in https://github.com/microsoft/vscode/issues/78894#issuecomment-535254539.

Screenshot 2019-08-23 at 16 18 58
Screenshot 2019-08-23 at 16 19 48

### CODE REVIEW

**Comment by yoyo930021** [comment]
If any one try https://github.com/webpack/enhanced-resolve?

**Comment by penx** [comment]
@octref @aeschli is there anything holding up merging this PR? Any more I can do?

**Comment by penx** [comment]
@Tyriar any more I can do to get this in to a release?

**Comment by Tyriar** [comment]
@penx I have nothing to do with this, I simply pushed it out as it didn't make it into the release.

**Comment by penx** [comment]
> #20200323.20 failed
> BackupRestorer Restore backups:
> 11980
>      Error: Backup: Could not find meta end marker in vscode

After rebasing off master, the above error is reported. Pretty sure this is unrelated to this PR and tests should be rerun

**Comment by aeschli** [comment]
@penx Sorry for the wait.
Can you also add a test case in https://github.com/microsoft/vscode/blob/master/extensions/css-language-features/server/src/test/links.test.ts ?

**Comment by penx** [comment]
@aeschli no worries, I've added a test and reordered commits to show test fail then pass

**Comment by aeschli** [comment]
Thanks @penx!

**Pull request merged**
