### PR TITLE
Editor improvements (#4637, #3685)

### PR DESCRIPTION
**Pull request by outcoldman**
## Implement trim whitespaces on enter #4637

When use double enter with automatic indention - in most cases user does
not want to keep identation on skipped lines. This change introduces new
editor configuration `editor.trimWhitespacesOnEnter`, which is `false`
by default (for backcompatibility).

On every enter command cursor checks if the line which will be on the
left has some whitespaces which can be trimmed - and extend cursor
range to remove whitespaces.
## Backspaces decreases indent #3685

In case when on the left side of the line there are only spaces - help
user to delete whole indent = tabSize.

### CODE REVIEW

**Comment by Treri** [comment]
Should the option only trim empty lines(only contain space characters) and not trim trailing spaces if the line have other content?

Thus, the markdown file's wanted trailing spaces will not be removed when we press enter.
I checked the test specs and found  the wanted trailing spaces will also be removed in this case.

**Comment by outcoldman** [comment]
@Treri yeah, that makes sense, I will do appropriate changes (also checked with Sublime Text on default behaviors):

- I will remove configuration, does not seem like we need to have `editor.trimWhitespacesOnEnter` configurable.

- Spaces will be trimmed only in situation where you are on the line, where only empty whitespaces and your cursor is at the end of this line.

**Comment by Treri** [comment]
@outcoldman Thanks for your awesome work 👍

**Comment by outcoldman** [comment]
@alexandrudima @egamma could you take a look on fix for the test `Bug 9121: Auto indent + undo + redo is funky` after I did this change. I do not have access to original bug (seems like it is not on github), so cannot tell where was original issue and on what I should pay attention.

**Comment by outcoldman** [comment]
@Treri you are welcome :) This "feature" also annoys me, good to have an option to fix editor you use.

**Comment by egamma** [comment]
@outcoldman thanks for the contribution. Some of the team members are on vacation expect some delays until we get back to you.

**Comment by outcoldman** [comment]
@egamma @alexandrudima I updated this PR with one more change for the editor. I keep changes in separate commits, but the same PR, because one is depend on another one (just a common helper function).

Travis failed with some unrelated problem, could you guys bump it to run it again?

**Comment by outcoldman** [comment]
@egamma @alexandrudima can we get it to the April milestone? I made it configurable, so if it will break something - will be possible to turn it off.

**Comment by outcoldman** [comment]
Fixed merge conflict. @alexandrudima @egamma any updates on this PR? Could you add it to April milestone?

**Comment by Treri** [comment]
👍 

ping @alexandrudima @egamma

**Comment by Tyriar** [comment]
@outcoldman April's development is finishing up on Monday and @alexandrudima is still out. Since he's the one who needs to review this I don't think it will make it in.

**Comment by Treri** [comment]
Could anyone add this PR to May milestone?

**Comment by alexandrudima** [comment]
@outcoldman Thank you for the contribution! :heart:

I have merged the proposed changes in fb5b68d199918fbe58e57d4faa3909580430fa4e and I also did quite some improvements to them, specifically:
 - in the backspace case to better handle mixed whitespace (e.g. a space followed by a tab)
 - in the trim whitespace case to better handle:
  - remove only whitespace that the editor has added.
  - editing a file in two editors at the same time (the auto whitespace lines are recorded in the model)
  - when pressing Tab or Enter, the whitespace only-lines introduced are marked as auto whitespace lines
  - on any edit of the model that involves the undo/redo stack (i.e. normal editors, not output editors) the marked auto whitespace lines are trimmed if trimming does not interfere with the current edit operations to execute.

P.S. It does not appear as a merge here because this PR contains two 2 MB files and I dropped the parent reference on the merge commit to try to keep our repo .git folder footprint small.

**Comment by outcoldman** [comment]
[sarcasm]
Nice, so you are basically took my work and sign it with your name.
This is how folks in Microsoft are getting promotions :D
[/sarcasm]

**Comment by alexandrudima** [comment]
@outcoldman I am very sorry, it was not my intention to not give you credit for your work, you get all the credit for what you have contributed! :heart: .

I have tried my best to do the right thing (give credit where it's due) in the commit message (fb5b68d) and in the comments of #4637 and #3685. We will also link to this pull request and mention it in the VSCode May release notes.

Looking forward to further contributions from you where I can just click the merge button -- you can ignore `.vscode/.browse.VC.db` and `.vscode/.browse.VC.db-wal` in your local vscode git repo by editing `.git/info/exclude` such that they don't get committed by accident.

**Comment by Treri** [comment]
Maybe you can firstly checkout this PR locally, and then edit as you like, and then use `git commit --amend` to append your code onto this PR.

Then the commit log will be `outcoldman committed with alexandrudima `. like this one https://github.com/neovim/neovim/commit/f931e78fe420884447a7a5d4e17f71a2eeeff3cd

**Comment by outcoldman** [comment]
@alexandrudima next time you could ask. I know rebase/reset magic which allows me to remove these files from the history. I actually did it right after I relalized that there were checked in, but got distracted and forgot to update my branch.

Anyway, no bad feelings. Thank you for accepting the work and making improvements.

**Comment by martellaj** [comment]
Thanks so much, @outcoldman! Probs my favorite update in 1.2!

**Comment by yisibl** [comment]
@outcoldman I think you can add a option, when selected to show indentation, similar to Sublime Text.

**Pull request closed without merging**
