### PR TITLE
Avoid conflicting scopes and commandIds in quiet logins from Accounts (fix #137601)

### LINKED ISSUE #137601: Quiet authentication requests with different scopes might not be distinct on Accounts icon
Consider this line:

https://github.com/microsoft/vscode/blob/ce15e23a06afd39d3a3ddc06ff1e49fa91250b40/src/vs/workbench/services/authentication/browser/authenticationService.ts#L616

Suppose an extension runs this code:
```ts
  const session1 = await vscode.authentication.getSession('myProvider', ['A', 'BC'], {createIfNone: false});
  const session2 = await vscode.authentication.getSession('myProvider', ['AB', 'C'], {createIfNone: false});
```
The Account icon badge will report only 1 login request.

A potential solution might be to change the line to be:
```ts
   const scopesList = JSON.stringify(scopes);
```

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #137601

Internal structure now uses JSON-stringify form of scopes array in place of simple join.

Variable name changed to correspond.

commandId for generated login command now uses a naming scheme that will avoid clashes.

Two interfaces that aren't being used elsewhere are no longer exported.

/assign @TylerLeonhardt

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Repro available in [my branch of authenticationprovider-sample](https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-137601) which adds two quiet logins:

image


1. Build from the branch and run.
2. Run the `Login with Azure DevOps` command that the extension contributes.
3. Before the fix in this PR:

image

4. After:

image

The two quiet logins are now accessible, but the screenshot reveals another issue, which is that the menu item prompts for the two different-scopes requests are identical. I will open a separate issue for this.

**Comment by TylerLeonhardt** [comment]
Couldn't we join them with a comma instead? JSON stringify is fine...but I don't want the usage to give off some impression that we deserialize the scopes later since we don't do that.

**Comment by gjsjohnmurray** [comment]
Based on [this section](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3) of the OAuth2 a scope could contain a comma. But space, doublequote and backslash aren't allowed in a scope. So I've pushed a change to use space as the separator, and to fix a path my original change hadn't accounted for.

**Review by TylerLeonhardt — APPROVED** [review]
LGTM

**Pull request merged**
