### PR TITLE
Preserving the Status bar items whitespace between the codicons

### PR DESCRIPTION
**Pull request by ghost**
This is for the issue #145852

Here I bounded the choices to when the **a tag** has the class **disabled**. 
Then with the **nth-last-of-type(-n+4)** I chose the last **4 icons** because if I used **3** then the spacing would be only included between the two icons.
Finally, I removed the margin application of the last span element. 
This is a test I did, and it is inserting space between the icons. 

https://user-images.githubusercontent.com/98463228/185746638-9cf1a64a-b265-4f22-966f-b741366131e8.mp4

This works unless the order of icons has other types of specifications.

### CODE REVIEW

**Review by ProKashif — DISMISSED** [review]

**Comment by misolori** [comment]
> Here I bounded the choices to when the a tag has the class disabled.

Is there a reason why it's bound to disabled items? This wouldn't fix the issue as items with actions would appear the same

**Comment by najmiehsa** [comment]
ok, I thought this would fix the issue.

**Comment by najmiehsa** [comment]
@misolori I can replace the :is() with direct descendent but I prefer this syntax. 
Would you tell me exactly where these 3 icons are placed? 
The First section of the status bar, middle or last part? and how they are grouped and differed from the others.

**Comment by najmiehsa** [comment]
As issue #145852 is originally extracted from #145722  I reproduced the placement of the icons following this picture:

159503473-9f1526ac-ba93-41cf-a743-69dea5eeabdc

**This is for when there are two icons:**


https://user-images.githubusercontent.com/98463228/187842681-004479b1-bb1e-48c9-9ea1-7cf7a7c2d748.mp4

**Comment by najmiehsa** [comment]
**This is for when there are 3 icons:**

https://user-images.githubusercontent.com/98463228/187842926-884ec71a-1d52-4bfb-9130-23f1547537f7.mp4

**Comment by najmiehsa** [comment]
**and four icons:**

https://user-images.githubusercontent.com/98463228/187843079-51827c08-2bf4-4621-b5fb-74e2161b4ef2.mp4

**Comment by najmiehsa** [comment]
@misolori 
- Here, I populated the status bar considering if there were different icons in a row for the possible extensions. These are 2, 3, and 4 icons with text in between them.
- These icons are not in the right sections of the status bar although I populated the right section of the status bar as much as I  thought it would be ideal. 
I appreciate feedback.

https://user-images.githubusercontent.com/98463228/188054050-869e3a41-749a-4026-bb4e-02e70ad446c0.mp4

**Comment by misolori** [comment]
Thanks for the updates! I think one downside of this is that the other items that text and icons (like the problems panel) look misaligned. I think this is a tricky issue and am not sure if we'll find a solution that works here.

**Comment by najmiehsa** [comment]
> Thanks for the updates! I think one downside of this is that the other items that text and icons (like the problems panel) look misaligned. I think this is a tricky issue and am not sure if we'll find a solution that works here.

If I set aside the misalignment of the text and icons, would this one work?
I can look for other ways to align text and icons beside this.

**Comment by najmiehsa** [comment]
In every trial I wanted to do this issue, a new aspect unfolded. This is not ideal as it adds to the workload rather than providing a straightforward solution. 

First, to address the misalignment of icons and the text, I could come up with these solutions:

The icons do not have the same **font-size** as the text and this is because of the last line of code in the statubar.css:

https://github.com/microsoft/vscode/blob/d17726fe4beae5abe87ba9e9429cd298be8b53c4/src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css#L146

- Here the **codicon icons** wrapped in the **spans** are selected. This excludes the text included in the **a tags**. A suggestion for this is to change the selection in this way:

```
.monaco-workbench .part.statusbar > .items-container > .statusbar-item  a {
	text-align: center;
	font-size: 16px;
}
 ```

-  And to reposition the icons using **transform: translate(2px, 1px);**  property only for the icons. This can re-position them and align them with the text:

 ```
 .monaco-workbench .part.statusbar > .items-container > .statusbar-item  span.codicon {
	transform: translate(2px, 1px);
	color: inherit;
}
 ```

To also align the text also, I suggest changing the line height on this selection:
https://github.com/microsoft/vscode/blob/d17726fe4beae5abe87ba9e9429cd298be8b53c4/src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css#L10

Note: Changing its value pushes only items with the text in the **div** with the **class=”status-bar-item”** left up or down not the others.

**Something else to add:**
some icons maybe were wrong picks for the test as they may need custom sizing to align properly.

**Comment by najmiehsa** [comment]
As for the space between codicons icons, there is a specific scenario. The right section of the status bar has three separate sections. These sections are:

- **First-visible-item** : We have a div with the **class=”first-visible-item”** this one is a solid subsection without the flexibility of many icon changes.
- **Middle (meaning without a specific class)** : We have a div with the **class=”left”**  For this is for git branches, loading, and other synchronizations. 
- **Last-visible-item**: We have a div with the c**lass=”last-visible-item”** right after this one, here I can see there are warning icons and error icons. 

My assumption was that all the extension icons would be added to the middle section of the left part of the status bar. However, the real examples I see on my desktop vscode app prove the other cases:

In this subsection, as an example, the **gitlens extension** adds two icons one before the warning icons and error icons in the **last-visible-item div** and one after.



the other point is that, Also, a div has the **display:inline-block property** .  An example of this is line 43:
https://github.com/microsoft/vscode/blob/d17726fe4beae5abe87ba9e9429cd298be8b53c4/src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css#L43

If changing the **display property** won't affect the items because of the nature of the statue bar, maybe **display:inline-block** can be used for other property as well. With the application of emerging left and right can be easily done.


As a suggestion, maybe Instead of sectioning the main status bar div we can change the selectors like this:

- **span:first-of-type()** 
- **span:nth-of-type()**
- **span:last-of-type()**

and exclude any item that is not needed with **:not()** selector.

@misolori @daviddossett 

At this point, I can implement these or the issue needs to be renewed because I can tell that it is important and with its current state it is not neat. There are ideas pointing in all directions and chances are low for it to get resolved.

Can I open an issue with all the relevant context for this and renew the previous one? This seems to be necessary. 
Or make changes to this PR. Please let me know what to do next?

**Pull request closed without merging**
