### PR TITLE
Put marker hovers on top

### LINKED ISSUE #73120: For long hovers, errors appear all the way at the bottom and require scrolling
I'm not sure if this is new, but I'm seeing it a lot lately. When I hover over some code with a red squiggle, if the hover/tooltip has a long description, I have to scroll all the way to the bottom to find the error.

Screenshot 2019-05-01 at 9 41 21 am
Screenshot 2019-05-01 at 9 41 30 am

I think it would be better if errors/warnings were either at the top, or somehow docked at the bottom of the tooltip, so you don't have to scroll to get to them. Some tooltips a REALLY long and it's a pain. I'm aware of the F8 functionality, I just prefer the tooltips :-)

### PR DESCRIPTION
**Pull request by azdavis**
## Description

This puts marker hovers on top of all other hover kinds, and shifts down all hover kinds that used to be ahead of marker hovers by 1.

An effect of this is that diagnostic messages are now on top when hovering.

### Before

before

### After

after

## Closes

Close https://github.com/microsoft/vscode/issues/73120

## Tests

👀

### CODE REVIEW

**Comment by azdavis** [comment]
@microsoft-github-policy-service agree

**Comment by azdavis** [comment]
some more examples of errors on top:

## [Millet](https://azdavis.net/posts/millet/)

millet

## [rust-analyzer](https://rust-analyzer.github.io)

ra

**Comment by AlpacaFur** [comment]
Hi @rzhao271 and @daviddossett, if you have a minute could you take a look at this PR? Based on the corresponding issue (#73120), this would fix a UX issue that many people have been struggling with for a while (opened 2019, >110 reactions, no negative comments). It also looks like the actual code changes are minimal, so this is primarily a design decision. Thank you both for your time!

**Review by rzhao271 — DISMISSED** [review]
After this change is merged, for short hovers, if the hover is going downwards, then the error appears closer to the error squiggle, and if the hover is going upwards, then the error appears farther from the error squiggle.

For long hovers in either direction, because the user currently needs to scroll to the bottom of the hover just to see the error, the error appearing at the top instead, which would be provided by merging this PR, is good, because users wouldn't have to scroll anymore just to see the error message.

LGTM

I'll wait for @alexdima to provide a second approval, though.

**Review by rzhao271 — APPROVED** [review]

**Comment by azdavis** [comment]
Any progress on this?

**Comment by azdavis** [comment]
@alexdima are you able to approve this?

**Review by alexdima — APPROVED** [review]

**Review by aiday-mar — APPROVED** [review]

**Pull request merged**
