### PR TITLE
Allow goToLine to work backwards

### LINKED ISSUE #79286: Using -1 to go to the last line of a file.
Ctrl+g allows us to jump to any line in the editor.
If I want to go the the last line of the file, I must enter the line number of this line, which means looking at the dialog box to know what it is.
It would be convenient if we could use negative indices to jump to lines starting from the bottom of the file (-1 being the last one, -2 the one before, aso).

### PR DESCRIPTION
**Pull request by jmannanc**
Fixes https://github.com/microsoft/vscode/issues/79286

Are there any docs that would need editing too with a change like this?

### CODE REVIEW

**Review by diguifi — APPROVED** [review]

**Review by MJ-Mohith — APPROVED** [review]

**Review by bpasero — CHANGES_REQUESTED** [review]
This needs to still check for the line being valid though:

image

**Comment by SneakyFish5** [comment]
Good catch! Just pushed a fix for it.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by SneakyFish5** [comment]
Thanks for merging, just wanted to reiterate my original question about the docs. Would there be anything I need to change or no?

**Comment by bpasero** [comment]
Thanks for asking, I actually think we do not even document this feature on https://code.visualstudio.com/docs, but if you can find it we can update it!

**Pull request merged**
