### PR TITLE
Remove Mac specific keybindings that don't work

### PR DESCRIPTION
**Pull request by HookyQR**
The thing that this attempted to provide has never worked. Removing it allows Dvorak keybindings to work correctly. Previously it caused keybindings to use the QWERTY POSITION of the key rather than the actual key.

eg. On Dvorak, the default for insert comments is "Cmd+z" which would then conflict with the undo shortcut.

The current 'fix' does nothing for 'english' based keyboards such as Dvorak, it in fact makes real weird stuff happen because of the 'reverse' mapping it tries to do.

This change will cause some keybindings to be unreachable on some keyboard layouts, but it is my view that it is better to map to the _character_ than the key, and then allow the user (of those keyboard) to map to the _key_ they want to use. (Ie, the problem with the '/' key on the swiss-german keyboard)

### CODE REVIEW

**Comment by fakewaffle** [comment]
What's the status of this PR? I'm unable to use VSCode with a Dvorak layout.

**Comment by openam** [comment]
I'm having issues while using the Dvorak layout as well. I'd love it if this would fix those issues.

**Comment by HookyQR** [comment]
Seems the Microsoft team is uninterested. You can follow the steps at https://github.com/Microsoft/vscode/issues/15624#issuecomment-261412779 to fix it yourself. You'll have to do that for each release until they get interested in supporting us outliers. Interestingly, the problem is caused because they wanted to support a *different* minority group. 🙄

**Comment by HookyQR** [comment]
This will close #1492, #4712, #4619, #15624, #13417 and #6020. It will also likely close #17106, #17023, #16157, #15887 and #15711. Add a keymap extension for the keyboards you're trying to fix with the hacky code this removes and everyone will be happy.

**Comment by alexandrudima** [comment]
I am interested in fixing this and I've already started working on it, but breaking other keyboard layouts is not an option.

Work has already started in https://github.com/Microsoft/node-native-keymap

I plan to investigate using `e.code` instead of `e.keyCode` since we now consume a version of Chromium that has implemented it.

**Comment by fakewaffle** [comment]
Atom doesn't seem to have this problem.

**Comment by alexandrudima** [comment]
Turns out things are more complicated. I have documented my findings in #17521 and that issue will track the work going forward.

**Comment by alexandrudima** [comment]
I am happy to say #17521 is now closed. I will validate tomorrow on a Mac the Dvorak issues to double check that they are indeed resolved.

**Pull request closed without merging**
