### PR TITLE
Make open recent menu aware of openFoldersInNewWindow setting

### LINKED ISSUE #88665: Allow to force open in same window from the recently opened picker
Currently, "Open Recent..." defaults to opening folders in the same window. If you hold <kbd>Ctrl</kbd>, they will be opened in a new window instead as indicated in the UI:

With `"window.openFoldersInNewWindow": "on"`, the behavior changes to _always_ opening the folder in a new window, regardless of whether <kbd>Ctrl</kbd> is held or not, effectively taking away some flexibility.

I think it would be convenient if `"window.openFoldersInNewWindow": "on"` **flipped** the default behavior of "Open Recent..." instead, so that holding <kbd>Ctrl</kbd> could still be used to open the folder in the same window. This would be useful for people like me who want to open folders in a new window _most of the time_, so the more common action would have a simpler shortcut (<kbd>Enter</kbd> vs <kbd>Ctrl</kbd>+<kbd>Enter</kbd>).

### PR DESCRIPTION
**Pull request by joe-nm**
This PR fixes #88665
if window.openFoldersInNewWindow is "on", this flips the behavior of control and command key modifiers to open in the same window and changes the placeholder text accordingly.  Otherwise behavior will be the same as before.
Personally tested on mac.

### CODE REVIEW

**Comment by joe-nm** [comment]
On second thought this has a bit of a weird interaction with new files from the recently opened action, the placeholder text changes with "window.openFoldersInNewWindow" setting but file behavior change with "window.openFilesInNewWindow".  I could branch on all 4 possibilities but it's getting outside the issue's scope.  I'm open to writing more code, but let me know how you want to handle it.

**Comment by bpasero** [comment]
Yeah I agree, this needs to be configured per folder and per file based on the setting to make sense.

**Comment by Gama11** [comment]
Huh, is it intentional that this bot message triggers for pull requests?

**Comment by bpasero** [comment]
Closing as stale, please create a new PR if you still plan on working on this.

**Pull request closed without merging**
