### PR TITLE
Fixes regression: cannot open image with special characters '#', '?', '%'

### LINKED ISSUE #102188: Regression: cannot open image with special characters '#', '?', '%'
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.18.0-041800-generic

Steps to Reproduce:

1. Try to open an image with special characters in image name, e.g. `#.gif`, `?.gif`, `%41.gif`
2. :bug: Image cannot be previewed

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #102188

### CODE REVIEW

**Comment by tillig** [comment]
Looks like #102442 just caused this to be in conflict. 😢

**Comment by jeanp413** [comment]
@mjbvz not sure if you have this on you radar but just to be sure, could you take a look at this or the corresponding issue #102188 for the july release. 
Opening images with filenames containing '#', '?', '%' worked fine in version 1.46 but stopped working in the 1.47 release.
Thanks

**Comment by mjbvz** [comment]
Thanks for looking into this.

Since this was a regression, can you also look into adding a test for this so that we don't break this again. Here's the existing webview test for resource loading: https://github.com/microsoft/vscode/blob/599f3b60e2f3d6be7118fa6b9400353d7e1bcdf6/extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts#L242

In the `testWorkspace` directory, just create a new image file with a `%` and try loading that in the webview. You can run the tests using  the `single folder test` option from the debug menu:

Screen Shot 2020-07-22 at 4 03 34 PM

**Comment by jeanp413** [comment]
Added the unit test.

**Comment by mjbvz** [comment]
Thanks!

**Pull request merged**
