### PR TITLE
Fix Suggestion Widget Hanging

### LINKED ISSUE #152010: Suggestion Widget Hangs on Markdown
Using an extension that provides PHP intellisense, it creates a suggestion widget with documentation for each file in the namespace.  The documentation includes a php code snippet in markdown for each file.  When the completion shows and it goes to show the details, it hangs VS Code while rendering.  While the extension can be updated to reduce the documentation size, the issue can be triggered in VS Code directly too.  The contrived typescript file below simulates the same effect.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.68.0 (Universal)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:00.250Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1.  Open attached [markdownHang.ts.txt](https://github.com/microsoft/vscode/files/8895998/markdownHang.ts.txt) file, but rename to `.ts`.
2.  Type "test" at the bottom.
image

It will hang while typing.  If it doesn't you can copy/paste the JSDoc to make it longer.

I will open a PR in a few minutes to fix this.  It looks like the following tries to re-render after each markdown snippet instead of at the end.
https://github.com/microsoft/vscode/blob/4501f83b1e477f13f3b4c226f36431d49121622d/src/vs/editor/contrib/suggest/browser/suggestWidgetDetails.ts#L176-L179

### PR DESCRIPTION
**Pull request by ssigwart**
This PR fixes #152010

To test, see the steps to reproduce in #152010.  Running that test before and after should be a noticeable different.  On my 2014 Macbook Pro, it's around 30 seconds vs ~2 seconds.

### CODE REVIEW

**Review by jrieken — CHANGES_REQUESTED** [review]
Thanks @ssigwart. This is a nice issue and good investigation. You are on the right path to fix this but I would go "one level deeper" See https://github.com/microsoft/vscode/issues/152010#issuecomment-1172202917 - all consumers are affected by this (hover, suggest, ghost text) and I would use the `DebounceEventEmitter` for this event [onDidRenderAsync](https://github.com/microsoft/vscode/blob/efbf613639725d395e95fd25e53117256ee50195/src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts#L42). That's the same approach as yours but at the source

**Comment by ssigwart** [comment]
Thanks, @jrieken.  I couldn't find any class called `DebounceEventEmitter`, but I'm guessing you just meant to apply the `Event.debounce` change to `markdownRenderer.ts`, so I did that.

**Review by jrieken — CHANGES_REQUESTED** [review]
Sorry, I meant [`DebounceEmitter`](https://github.com/microsoft/vscode/blob/2e83f3230a8ce909dad7f2ba0266d035a69983c9/src/vs/base/common/event.ts#L912). You can also use `Event.debounce` but there is disclaimer about leakage when using the `debounce`-util to create a "public" event. In short, in this case it is best to use the `DebounceEmitter`

**Comment by ssigwart** [comment]
Thank you.  I updated to use `DebounceEmitter`.

**Review by jrieken — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]

**Pull request merged**
