### PR TITLE
Add icon explorations to master

### PR DESCRIPTION
**Pull request by miguelsolorio**
This adds the [icon explorations](https://github.com/microsoft/vscode/issues/8017) to `master` so that users on insiders can start using it. We can disable/remove this before we ship 1.35 since it's an exploration. Also assigning this to @aeschli since I'm using the file icon themes to change the workbench icons (this will be opt-in only).

To change the icons go to `Preferences` > `File Icon Theme` and select either `VS Code Icon Explorations: Outline` or `VS Code Icon Explorations: Solid`.

image

### CODE REVIEW

**Comment by Tyriar** [comment]
@aeschli please review, if we merge this into Insiders we can avoid needing people to install the exploration build (and not merge this big diff into the electron branch).

**Comment by misolori** [comment]
Main modifications are here:

https://github.com/microsoft/vscode/blob/0b2f7d22d77586ee5c7f54bc6b5397e9f59e18fd/src/vs/base/browser/ui/actionbar/actionbar.ts#L264

https://github.com/microsoft/vscode/blob/0b2f7d22d77586ee5c7f54bc6b5397e9f59e18fd/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L510

**Comment by misolori** [comment]
After talking to @bpasero about this, if this is going to live in master we should enable it via a (hidden?) setting. That probably won’t happen until after endgame is over so I’ll add that to my TODO.

**Comment by misolori** [comment]
Tried to update this PR with master and did something wrong. Will ditch this PR and create another.

**Pull request closed without merging**
