### PR TITLE
Fix #42494

### LINKED ISSUE #42494: Recently selected suggestion should not be shown on the top
Testing #42329
I am not sure if I can create a sample to reproduce it, but could do it consistently in the following file in our code base - https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/output/electron-browser/outputServices.ts#L461

- Insert a new line after 461
- Typed `this.`
- Selected `getActiveChannel` suggestion
- Undid the selection and went back to state `this.`
- Typed quickly `aaa` and deleted it to went back to state `this.`
- Triggered suggestions 
- `getActiveChannel` selection is selected
- It is revealed on the top 🐛

### PR DESCRIPTION
**Pull request by joaomoreno**
As discussed, just make sure I didn't break any suggest behaviour with this. It makes more sense to set the state before revealing, since setting the state will trigger `layout`, which influences how reveal works.

Fixes #42494

### CODE REVIEW

**Comment by jrieken** [comment]
@joaomoreno Can you fix merge conflicts. Unsure if we still want this for Feb or better March?

**Comment by joaomoreno** [comment]
@jrieken Resolved. Up to you 👍

**Comment by jrieken** [comment]
Taking the risk ;-)

**Comment by joaomoreno** [comment]
It broke stuff.

**Pull request merged**
