### PR TITLE
Fix window title prefixDecoration

### PR DESCRIPTION
**Pull request by f111fei**

### CODE REVIEW

**Comment by bpasero** [comment]
@f111fei can you open an issue on this? we have to track NLS issues differently.

**Comment by f111fei** [comment]
@bpasero  https://github.com/Microsoft/vscode/issues/8896

Are here you a plan to open source nls generation tool? It's hard to contribute now.

**Comment by dbaeumer** [comment]
@johnliu2016 can you please merge this into the original source.

**Comment by johnliu2016** [comment]
@dbaeumer "● {0}" is the title string for all languages, the root cause with issue #8896 is loc check-in timing for those impacted languages.

**Pull request closed without merging**
