### PR TITLE
Support for remote management in git

### PR DESCRIPTION
**Pull request by manjrekarom**
Added options for **adding and removing remotes**.

### CODE REVIEW

**Comment by balexandre** [comment]
@manjrekarom if it's not much to ask, can you add "Purge Remote Branches" option as well ?

```
git remote prune <remote_name>
```

**Comment by manjrekarom** [comment]
@balexandre Yes. I will be happy to add that as well. But do I need to get a confirmation first? 

@joaomoreno Should I create a **different pull request or add it here**? Sorry, I am kinda new to this stuff. Thanks!

**Comment by balexandre** [comment]
@manjrekarom that will depend if there's more than one remote, and you only prune the one set as upload stream...

would be useful to have it as well, like `git fetch` to continue in the background and purge it time to time, as all it does is remote the remotes, not local branchs ... organizations tend to have the remote clean up time to time, and I'm facing that every time they simply forget :)

I also use this snipped to get all remotes from each author (so I know what they need to clean up)

```bash
git for-each-ref --format='%(committerdate)%09%(authorname)%09%(refname)' | sort -k5n -k2M -k3n -k4n | grep remotes | awk -F "\t" '{ printf "%-32s %-27s %s\n", $1, $2, $3 }'
```

**Comment by joaomoreno** [comment]
Feel free to add that to this PR

**Comment by jongio** [comment]
@manjrekarom - would love to see this get implemented. Are you still working on it? Need help?

**Comment by manjrekarom** [comment]
@jongio I am almost forgot about that. Will start working on the purge/prune thing. I'll let you know if I need any help. Thanks for asking.

**Comment by jongio** [comment]
@manjrekarom What are your thoughts on doing it as a separate PR instead of merging it with this one… That way we can get the baseline remote stuff in there and then add prune later on?

**Comment by manjrekarom** [comment]
@jongio Yeah. That is fine to me. Priority stuff can be added first.

I've done add and remove remote. Can you tell me what more should go into the baseline?

**Comment by jongio** [comment]
How about adding a command to view the remotes - `git remote -v` and then that hows the remote in the dropdown or output pane?

**Comment by manjrekarom** [comment]
@jongio Yes, I'll add that in this PR.

Here is a list of all remote things from git scm. I've tried categorising them. Let me know what you think.

**Baseline:**
1. git remote [-v | --verbose]
2. git remote rename <old> <new> 

**Extra**
1. git remote set-head <name> (-a | --auto | -d | --delete | <branch>)
2. git remote set-branches [--add] <name> <branch>…​
3. git remote get-url [--push] [--all] <name>
4. git remote set-url [--push] <name> <newurl> [<oldurl>]
5. git remote set-url --add [--push] <name> <newurl>
6. git remote set-url --delete [--push] <name> <url>
7. git remote [-v | --verbose] show [-n] <name>…​
8. git remote prune [-n | --dry-run] <name>…​
9. git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)…​]

**Comment by k1nghat** [comment]
> Here is a list of all remote things from git scm. I've tried categorising them. Let me know what you think.
> 
> **Baseline:**
> 
> 1. git remote [-v | --verbose]
> 2. git remote rename
> 
> **Extra**
> 
> 1. git remote set-head  (-a | --auto | -d | --delete | )
> 2. git remote set-branches [--add]  …​
> 3. git remote get-url [--push] [--all]
> 4. git remote set-url [--push]   []
> 5. git remote set-url --add [--push]
> 6. git remote set-url --delete [--push]
> 7. git remote [-v | --verbose] show [-n] …​
> 8. git remote prune [-n | --dry-run] …​
> 9. git remote [-v | --verbose] update [-p | --prune] [( | )…​]

@manjrekarom would these be the main ones to be added?
`git remote add upstream`, `git fetch upstream`, and `git rebase upstream/master` or `git merge upstream/master`

**Comment by jongio** [comment]
Great point.  It would be awesome if I could have a 'rebase with remote' feature, but I think that is prob a diff PR.

**Comment by darkyuhoo01** [comment]
@jongio Yes, I'll add that in this PR.

Here is a list of all remote things from git scm. I've tried categorising them. Let me know what you think.

Baseline:

git remote [-v | --verbose]
git remote rename
Extra

git remote set-head (-a | --auto | -d | --delete | )
git remote set-branches [--add] …​
git remote get-url [--push] [--all]
git remote set-url [--push] []
git remote set-url --add [--push]
git remote set-url --delete [--push]
git remote [-v | --verbose] show [-n] …​
git remote prune [-n | --dry-run] …​
git remote [-v | --verbose] update [-p | --prune] [( | )…​]

**Comment by darkyuhoo01** [comment]
@manjrekarom - would love to see this get implemented. Are you still working on it? Need help?

**Comment by joaomoreno** [comment]
Apart from the error of sanitizing the remote URL, looks great, thanks!

**Comment by jongio** [comment]
Awesome!  @RMacfarlane - It would be awesome to see how we integrate the PR extension docs with this update.

**Comment by alexanderlsmith123** [comment]
Yeah this is awesome

**Comment by manjrekarom** [comment]
Thank you so very much everyone! :D Delighted to see my PR go into master. I started working on this as a Hacktoberfest task and never imagined it would go this way. This will be my first (real) accepted PR. And that too for something that I and millions of people enjoy using daily. Thanks again.

**Comment by jongio** [comment]
@manjrekarom

That’s awesome. Thank you so much for the effort.

**Pull request merged**
