### PR TITLE
Revert "Update C# grammar" that introduces invalid grammar

### PR DESCRIPTION
**Pull request by Gerrit0**
This reverts commit bd2493499dab8aafe8d216dfa4de7dafd04b4c94.

The reverted commit contains the regular expression `(?<!\?\s*)\?(?!\?|\.|\[)`, which is an invalid regular expression because the lookbehind is no longer fixed width.

### CODE REVIEW

**Comment by Gerrit0** [comment]
Once https://github.com/dotnet/csharp-tmLanguage/pull/220 is merged, it would be better to update again instead.

**Comment by octref** [comment]
@alexr00 Hi Alex, hope this can be fixed soon so I can continue to use shiki to highlight C# 📦

**Comment by Gerrit0** [comment]
Didn't realize that would happen, makes sense I guess... the revert is no longer necessary, an update would be better

**Comment by alexr00** [comment]
Just updated the grammar. Thanks for bringing this up!

**Pull request closed without merging**
