### PR TITLE
Get pencil to write new setting

### PR DESCRIPTION
**Pull request by rzhao271**
Ref #129861

## The behaviour we want to fix

When following the steps in the issue above, we first get a dialog prompting us that the file cannot be saved, but then the retry action does not work, due to a glitch where the new setting value has already been written to the backing file.

## The behaviour after applying this PR

By adding the `ignoreDirtyFile` flag, when following the steps in the issue above, changing a setting with the pencil while the file is dirty results in the editor editing the value of the setting for the text buffer. No dialog is displayed, and the file remains unsaved.

### CODE REVIEW

**Comment by roblourens** [comment]
> changing a setting with the pencil while the file is dirty results in the file saving 

I don't think this should save the file automatically. Can it write into the dirty file and keep it dirty?

**Comment by sandy081** [comment]
Yeah, we shall not be saving automatically. The action that is broken here is `Save & Retry`. This action shall save the file and retry the operation which used to work before.

**Review by sandy081 — CHANGES_REQUESTED** [review]
I do not think we need this new argument `ignoreDirtyFile` and we shall not be saving automatically. The action that is broken here is Save & Retry. This action shall save the file and retry the operation which used to work before.

**Comment by rzhao271** [comment]
@sandy081 the current implementation makes it so that the new value is written to the file, but the file remains unsaved.
With this implementation, we don't get the previous issue where the Save & Retry dialog would pop up.

**Comment by sandy081** [comment]
I am not sure if force saving the file is expected. May be user might have some unsaved changes which he/she does not want to save. Hence we show this prompt to save the file first and retry. User can instead ignore this prompt and revert the changes in the file and retry the operation.

**Comment by rzhao271** [comment]
@sandy081 I updated the PR contents and https://github.com/microsoft/vscode/pull/137765#issue-787450051 to hopefully be clearer. I'm not force-saving the file.

**Comment by sandy081** [comment]
@rzhao271 I am seeing following behavior with this fix and it seems Save and Retry action is just updating the dirty model without saving. 

recording

Save and retry shall save the file and retry the operation as below

recording (1)

This behavior was broken by me when redirecting user settings writes to main process. Created a PR that brings back this behaviour. Please take a look - https://github.com/microsoft/vscode/pull/138657

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/pull/138657

**Pull request closed without merging**
