### PR TITLE
Support staging for new files

### PR DESCRIPTION
**Pull request by OneThatWalks**
Addresses #78046

@joaomoreno the real 'fix' or 'feature' was adding the `--add` arg to the `update-index` when an error was thrown by `getObjectDetails()`.  This may not be the best way to go about this, but I recorded the behavior for this PR.  The diff editor was utilized to get the context menu items to show up.

stagechanges

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Two problems I see:

- When staging from untracked, the left hand side does not update at all.
- When having a file half untracked, half staged, the left hand side of the untracked makes no sense, it has repeated lines

**Comment by OneThatWalks** [comment]
> 
> 
> Two problems I see:
> 
>     * When staging from untracked, the left hand side does not update at all.
> 
>     * When having a file half untracked, half staged, the left hand side of the untracked makes no sense, it has repeated lines

I'll do some digging here.  I was wondering if the diff editor made sense to even use?  At least for untracked files.

**Comment by joaomoreno** [comment]
I think it still does:

- For untracked files: on the left we should see the "index" version of the file: everything that is already staged.
- For index added files: on the left we should always see an empty document.

**Comment by OneThatWalks** [comment]
It looked like my git uri ref was incorrect for "untracked" files.  I recorded the cases above working correctly.

The left side of an untracked file shows the staged changes, the contents update and make sense with the untracked changes.

The left side of a index add is always blank, and is updated on range stage changes.

stagechanges2

**Comment by joaomoreno** [comment]
Excellent, great fix! I've added a check for the thrown error to make sure we only catch that specific error. And debugging this actually made me catch another issue: https://github.com/microsoft/vscode/issues/78949

Thanks! :beers:

**Comment by rawtaz** [comment]
Seriously quick work by you guys, fixing the original issue so quickly. Really nice!

**Pull request merged**
