### PR TITLE
Feature - Suggesting filename based on the content in the file

### PR DESCRIPTION
**Pull request by BabyManisha**
Instead of suggesting untitled-x in the filename it will suggest a filename based on the content entered in the file.

### CODE REVIEW

**Comment by roblourens** [comment]
Not sure about this change. Is there an issue discussing this already?

**Comment by BabyManisha** [comment]
This is a new feature (Rather than suggesting filenames as Untitled-N, we are suggesting a dynamic filename based on the content entered in file.)

**Comment by roblourens** [comment]
I don't really think we should do this, I have never wanted to name a file based on its content. And it could just cause issues if the line is very long, etc. But I will assign to @bpasero for feedback. I recommend that next time you open an issue first so we can discuss whether we want a feature, before you do the work to implement it.

**Comment by BabyManisha** [comment]
ok sure. Thanks @roblourens

**Comment by bpasero** [comment]
I think what I would rather expect is a setting that - once enabled - changes the filename of the untitled to the first line content (probably capped) and then when I save this editor the suggested file name is is simply taken from there. Please search for the existing issue, I am sure we have one.

**Comment by bpasero** [comment]
Since I did not hear back, I am going ahead and close this.

**Pull request closed without merging**
