### PR TITLE
Cache release notes. Fixes #13257

### LINKED ISSUE #13257: Noticeable delay each time in-product release notes editor is made active.
- VSCode Version:1.6.0 insiders
- OS Version: Windows

Steps to Reproduce:
1. Follow test plan to enable in product release notes in insiders https://github.com/Microsoft/vscode/issues/12520
2. Help > Release Notes
3. Note delay (~1.5 seconds) when page is initially displayed.
4. Switch to a different editor and then go back to release notes.

The release notes editor is re-rendered and there is the same delay each time. 
We should look into caching the rendered page since release notes are unlikely to change during the user's reading of the release notes. We don't need to cache release notes across sessions so the user will pick up any release note changes when they first open them (Help > Release Notes).

### PR DESCRIPTION
**Pull request by olingern**

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Sorry about the lack of guidance so far.

When I said `keep them in memory` I literally meant it as a variable in some scope. Don't use the storage service, since it will polute the storage and we don't care about having this information surviving between executions.

Create an object, next to `loadReleaseNotes` that will serve as a cache and use `version` as a key for that cache.

**Comment by olingern** [comment]
No problem!

I refactored to use a string instead of the storage service.

Is there a reason you'd prefer the cache be an object with a key over a regular string? Is there a use case where multiple versions would be cached and needed to be accessed directly on an object?

**Comment by joaomoreno** [comment]
Yeah, using the version as a key lets you read the current version's release notes as well as the next one, once you get an update notification.

**Comment by olingern** [comment]
@joaomoreno Got it. I updated the PR and rebased commit history to be a bit more clean. Let me know if this all goods good and if there's anything I can do to help get the tests passing.

**Comment by joaomoreno** [comment]
Looks better! 👍 

The problem is you need to merge the latest master onto your branch, do you mind doing this? That way our continuous integration tests will run on the PR.

**Comment by olingern** [comment]
@joaomoreno I pulled the latest master branch, but opening the release notes opens in the browser each time now.

**Comment by olingern** [comment]
@joaomoreno opting to close this as I see the latest version of Insider's release opens in the browser.

**Comment by joaomoreno** [comment]
@olingern The insider release will always open in the browser. The stable one opens in the product.

**Comment by joaomoreno** [comment]
Thanks for the PR!

**Pull request merged**
