### PR TITLE
new mnemonics behavior

### LINKED ISSUE #52368: Alt codes always display with custom titlebar
Issue Type: <b>Bug</b>

1.  Enable `"window.titleBarStyle": "custom"`
2. Click on 'File' in the top left
3. Notice 'N' is underlined in 'New file', though it should only be underlined while alt is held

(The bot tagged this wrong - is there any way I can prompt it for what kind of issue this is in the future?)

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:49:07.900Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3098)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (4.00GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
vscode-custom-css|be5|2.7.1
vscode-icontheme-nomo-dark|be5|1.3.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.32
vscode-great-icons|emm|2.1.33
vsc-material-theme|Equ|2.1.0
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
todo-tree|Gru|0.0.63
beautify|Hoo|1.3.2
discord-vscode|icr|2.6.0
vscode-simple-icons|Lau|1.8.3
python|ms-|2018.5.0
vsliveshare|ms-|0.3.317
debugger-for-chrome|msj|4.6.0
material-icon-theme|PKi|3.5.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.23.0
pdf|tom|0.3.0

(5 theme extensions excluded)

</details>

### LINKED ISSUE #52935: Menu: Alt+F followed by Alt+S does not work properly
Refs: #52854

Steps:
* press `Alt+F` and keep `Alt` pressed
* press `S`

=> the Selection menu expands when I would expect the save action to trigger

### LINKED ISSUE #53071: Menus: Prevent Alt shortcuts when using Alt + Mnemonics on Menus
Refs: #52854

When holding down `Alt`, press `f` and then `Right Arrow`, the command `Go Forward` (`Alt` + `RightArrow`) will be run.

If `Alt` is being pressed for mnemonics, I suggest only allowing Mnemonics for shortcut.
If someone indeed want to press a shortcut involving `Alt`, he should release `Alt` and exit from Menu. From that point, VS Code releases him from Mnemonics mode and allows him to use any keybindings, including those using `Alt`.

### LINKED ISSUE #53609: Underlined Letters in Custom Titlebar Appear as Boxes
Issue Type: <b>Bug</b>

The screenshot captures the issue better than my description. It seems as if the underline glyph is missing from a font, the same box is shown when I receive texts containing emojis that my phone doesn't recognize.

screenshot from 2018-07-05 13-06-36

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1749)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.67GB (0.40GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

### LINKED ISSUE #53654: Shortcut problem with the new custom titleBarStyle
- VSCode Version: 1.25.0
- OS Version: Windows 10

I have very valuable shortcuts assigned to Alt+D (and Alt+A and the likes). When I enable the new custom titleBarStyle, pressing Alt+D now makes the "Debug" menu active without executing the shortcut. This used to work in the native title. Interestingly, Alt+Shift+D still works.

I'm in love with the new custom title, but there's no way I can enable it with this shortcut not working.

### LINKED ISSUE #53767: Menus are showing underscores in the menu entries
In VSC 1.25 there are underscores in the menu names.  I think these indicate a letter should be underlined indicating it is a hotkey.  I see this on CentOS 7 machine and not my Windows 10 machine.  Need to check at home and see what Windows 7 shows.
 
vsc_1 25_menu_underscrores

### LINKED ISSUE #54232: Title bar font glitch in Chinese locale when titleBarStyle is set to custom
- VSCode Version: 1.25.1
- OS Version: Deepin 15.6

Steps to Reproduce:

1. Change language to Chinese SImplified.
2. Add `"window.titleBarStyle": "custom",` to settings.
3. Toggle the title bar.

image

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #54822: New Workbench Menu does not respect Alt+<Key> hotkeys on Windows.
- VSCode Version: 1.26.0-Insider
- OS Version: Windows 10 Pro (Insider) - 17713.rs5_release.180706-1551

This bug only occurs with the setting window.titleBarStyle: custom. When using the original style menus, in VS Code and VS Code (Insiders), the Alt hotkeys work as expected.

Steps to Reproduce:
1. Enable the new menu bar
2. Press Alt+F to open the File menu
3 Press S to save
3. While the File menu does appear and the various menu entries show underscores under their Alt hotkey activators, the save never occurs and the menu does not close. This happens for every Alt hotkey I've tried.

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #55540: Custom titlebar mnemomnics  should select item
Issue Type: <b>Bug</b>

1. Set `window.menuBarVisibility` to `toggle`
2. <kbd>Alt+F</kbd> - and keep Alt pressed
3. <kbd>R</kbd>
-> `Open Recent` should be selected

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17134

### LINKED ISSUE #55681: Mnemonics in the custom menus are using a different font
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2
Date: 2018-08-02T05:18:18.450Z

image

- the right arrow for the sub menus is too prominent. A little smaller would be more elegant
- the checkmark (see `Auto Save`) is barely visible
- the characters with mnemonice seem to use a different font (e.g. see the`l` in Save All)
- the submenus upper left corner seems to be round, while other corners are not
- the black menu on the back background is hard to see. On ElementaryOS the menu background color is normally white, which works quite well. Maybe it would make sense to read out the OS colors?

### PR DESCRIPTION
**Pull request by sbatten**
Please try out the new behavior and let me know what you think. After this is in, I'll need to go back in and make the screen reader stuff work correctly.

This removes the dependency on accessKey which limits us from controlling the behavior.

fix #52368
fixes #52935 
fixed #53071
close #53609
closes #53654 
closed #53767 
resolve #54232
resolves #54822
resolved #55540
fix #55681

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
I did some testing (not a full code review) and found 2 issues so far:
* when you press `Alt+F` I would expect pressing `O` works but I need another `Alt+O`
* when you press `Alt+F` I would expect arrow up and down to navigate in the menu but it does not (focus missing?)

**Comment by sbatten** [comment]
@bpasero neither of those issues are expected or repro for me. I'm not sure what is happening for you.

**Comment by bpasero** [comment]
@sbatten ok, could be a VM issue then (I do not have a Windows machine right now). Maybe you merge and I try again next week.

**Comment by sbatten** [comment]
@bpasero I will merge these changes, but please do a complete code review on Monday. @JacksonKearl I played with it on several machines and had Jackson play with it on his machine as well.

**Comment by sbatten** [comment]
@jeffhanna these bits are not yet available in insiders, but will be in the next build

**Comment by bpasero** [comment]
@sbatten I can still reproduce this issue (on my real Windows machine): press `Alt+F` and then release all keys, then press any of the mnemonics that is underlined (e.g. `O`), it will not work.

**Comment by sbatten** [comment]
@bpasero I've a feeling this may be an issue with keyboard layout or similar. If you aren't using a US layout can you try it on a US layout to confirm? If you are using a US layout, can you confirm your version is at least: Version: 1.27.0-insider
Commit: 6e559261f677793fea424c6eb5cb13d0301ffff1
Date: 2018-08-20T08:36:52.887Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by JeffHanna** [comment]
Just to confirm this is working as expected for me now. Thanks for addressing the issue.

Version: 1.27.0-insider
Commit: 6e559261f677793fea424c6eb5cb13d0301ffff1
Date: 2018-08-20T08:36:52.887Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by bpasero** [comment]
@sbatten well it would be pretty bad if this would only work with a US keyboard layout? Can you try switching yours to German to see if its really that?

**Comment by bpasero** [comment]
@sbatten weird, now with todays insider I cannot reproduce this anymore. I still do not see focus in the first menu item, but that seems to be a VM issue.

**Comment by JackTrapper** [comment]
**Steps to Reproduce**

- Press `Alt`
- Press `F`
- Release `F`
- Press `S` *(no save)*
- Release `S` 
- Release `Alt`

Alternate steps to reproduce

- Press `Alt`
- Press `F`
- Press `S` *(no save)*
- Release `F`
- Release `S` 
- Release `Alt`

**Comment by JacksonKearl** [comment]
@JackTrapper do you have anything bound to `Alt+S`? Those steps correctly save the file for me.

**Comment by JackTrapper** [comment]
@JacksonKearl For me pressing `Alt+S` drops down the **Selection** menu

- https://i.imgur.com/omaq2Mn.png

Also, nowhere in the Steps to Reproduce did i mention pressing `Alt`+`S`.

**Comment by JackTrapper** [comment]
That *does* work:

- Press `Alt`
- Release `Alt`
- Press `F`
- Release `F`
- Press `S`
- Release `S`

Also works:

- Press `Alt`
- Press `F`
- Release `F`
- Press `S` *(saves)*
- Release `S`
- Release `Alt`

Bonus Reading
-------------

- [Menu: Alt+F followed by Alt+S does not work properly #52935](https://github.com/Microsoft/vscode/issues/52935)
- [Alt-F-S doesn't save the current file #5556](https://github.com/Microsoft/vscode/issues/5556)

**Comment by JacksonKearl** [comment]
> Also works:
> 
>     Press Alt
>     Press F
>     Release F
>     Press S (saves)
>     Release S
>     Release Alt


> Steps to Reproduce
> 
>     Press Alt
>     Press F
>     Release F
>     Press S (no save)
>     Release S
>     Release Alt
> 

These are the exact same steps but you say they behave differently. In what contexts does the behavior change?

**Comment by sbatten** [comment]
@JackTrapper  please ensure you are using the latest insiders with `window.titlebarStyle` set to `custom` Your latest comment shows steps that now work correctly to save the file.

**Comment by adamulrich** [comment]
Is it possible to get this ported back to electron? We would love to have working mnemonics in our electron app. Current electron implementation is too buggy to use.

**Pull request merged**
