### PR TITLE
Initial Strict Typing Support for Telemetry Events

### PR DESCRIPTION
**Pull request by lramos15**
This PR is quite large as it sets the foundation for the changes needed to enable stricter type checking when sending our telemetry events. There are plenty more locations in the code that I haven't touched as this PR was starting to get out from under me, but this gives plenty of examples of what stricter type checking would look like. This will replace GDPR comments with typings which will force the event sent to match the classification provided. This is part of the work for #75527

### CODE REVIEW

**Comment by sbatten** [comment]
can we split this up just a bit more? One PR for adding publicLog2 and the gdprTypings. A second PR for after that's in with your initial sweep.

Also, why do all the implementations of publicLog2 copy the code of publicLog instead of just calling publicLog?

**Review by sbatten — CHANGES_REQUESTED** [review]
s

**Comment by lramos15** [comment]
We could split it up, I just had then together because it also tests to make sure the publicLog2 works was intended. I felt it was weird to just have a function definition with no changes. The reason all the implementations of publicLog2 are just copies of publicLog is because once the change was done I was just going to delete publicLog and rename publicLog2. I could do that just by calling publicLog as well, but this was just less work

**Comment by lramos15** [comment]
*Modified Events:*
issueReporterSearchError
issueReporterSubmit
issueReporterViewSimilarIssue
issueReporterGetElementError
windowerror
workbenchActionExecuted
galleryService:requestError
galleryService:cdnFallback
galleryService:requestError
UnhandledError
optInStatus
updateConfiguration
updateConfigurationValues
updateKeybindings
extensionActivationTimes
activatePlugin

**Comment by bpasero** [comment]
@lramos15 @sbatten what is a `WBAction.*`? I find names that are acronyms rather hard to understand, can we try to avoid them and spell them out?

**Comment by lramos15** [comment]
@bpasero I tried not to abbreviate many things, but took the liberty in certain cases due to the names for each type getting way longer than I would like. I can go back and fix them, but I didn't think it was a huge deal since just going to the references of the types would point you to the publicLog call which contains the eventName which the type is referring to. I see I did WB instead of WorkBench, RE instead of RequestError, and Val instead of Values. Let me know what you think.

**Comment by bpasero** [comment]
@lramos15 I think I am reacting up a bit because I see no other case of abbreviation in our code base like that. I do not mind longer names because quick open is smart enough so that you can e.g. type only the capital letters of a class and it will auto complete just fine:

image

Doing it with abbreviations just asks for trouble because a different person does not know what you mean.

**Comment by bpasero** [comment]
@lramos15 see https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#using-abbreviations-and-acronyms

Please change it back to the long form, thanks :+1:

**Pull request merged**
