### PR TITLE
Fix 37385 by introducing addition configuration setting

### PR DESCRIPTION
**Pull request by hun1ahpu**
Fixing the issue #37385
Adding configuration parameter that allows the user to control if s(he) wants to open debug viewlet on every debug session, on the first only or never.

### CODE REVIEW

**Comment by isidorn** [comment]
@hun1ahpu thanks for this PR, I like the work. Here's my feedback, once you adress it we can merge this in:
* I would prefer if this is only a vscode configuration setting, and not a configuration in the `launch.json`. I know that `internalConsoleOptions` is present in both configurations and in launch but that is for historic reasons and I am not a fan of that
* I would prefer that the configuration name is `debug.openDebug`
That way the name is complementary with `debug.openExplorerOnEnd`. And the values I would keep as to what you already have.

Thanks a lot

**Comment by hun1ahpu** [comment]
@isidorn please take a look on the new iteration.
I renamed the setting to openDebugOnStart (similar to openExplorerOnEnd)
I think I've removed it from launch.json setting but I'm not sure. Could you check please?
Thanks

**Comment by isidorn** [comment]
@hun1ahpu please rename it to exactly `openDebug` I have discussed the name in great length with a collegue. This is our choice to not have duplication between name and value.
Yes it looks like you have removed it from the launch.json

**Comment by hun1ahpu** [comment]
@isidorn Done :)

**Comment by isidorn** [comment]
@hun1ahpu thanks a lot for your PR 🍻. Merging in

**Comment by isidorn** [comment]
I have cleaned this up a bit via bc04f0cb3d

**Pull request merged**
