### PR TITLE
Enable ok button for extensions using quickpick

### PR DESCRIPTION
**Pull request by aaomidi**
I noticed that the okay button disappeared without a way to bring it back. This PR empowers extension owners to decide if they want the button or not.

### CODE REVIEW

**Comment by mjcrouch** [comment]
looks like it's related to my issue #90365 as well - though I'm not clear if it was deliberately removed or if it's missing due to a bug? In which case does it really need to be optional?

If it is optional, shouldn't the default be to show the button, so that it is backward compatible with existing uses?

**Comment by aaomidi** [comment]
Yeah I'll let the vscode team decide on what the default should be, but having it as an option would be great :)

**Comment by chrmarti** [comment]
This shouldn't be something extensions can decide on case-by-case as that would introduce an unnecessary inconsistency. The question remains if we should always show the OK button. So far we have decided not to.

**Comment by aaomidi** [comment]
Please do take accessibility into account as well. The way it currently works has caused issues for a few people I know.

**Pull request closed without merging**
