### PR TITLE
Default folder setting while cloning a git repository

### PR DESCRIPTION
**Pull request by gagangupt16**
Added a setting for cloning a git repository to a default location.
If it is not specified in settings, it will prompt the user.

This PR is for the issue: https://github.com/Microsoft/vscode/issues/17671

### CODE REVIEW

**Comment by gagangupt16** [comment]
On checking logs of travis-ci, it is showing error at `gulp hygiene --silent`
On locally running, I found it is failing in file terminal.ts

vscode/src/vs/workbench/parts/terminal/electron-browser/terminal.ts is not formatted

**Comment by gagangupt16** [comment]
I have signed the CLA yesterday. Is there anything else that needs to be done to change the label of PR?

**Comment by gagangupt16** [comment]
Hi,

AppVeyor build is failing.
Initially, it passed but after PR was closed and opened, it failed due to...

`) ExtHostWorkspace asRelativePath:
      AssertionError: '.' == ''
      + expected - actual
      -.
      
      at Context.<anonymous> (C:\projects\vscode\out\vs\workbench\test\node\api\extHostWorkspace.test.js:12:20)
      at callFn (C:\projects\vscode\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\projects\vscode\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\projects\vscode\node_modules\mocha\lib\runner.js:422:10)
      at C:\projects\vscode\node_modules\mocha\lib\runner.js:528:12
      at next (C:\projects\vscode\node_modules\mocha\lib\runner.js:342:14)
      at C:\projects\vscode\node_modules\mocha\lib\runner.js:352:7
      at next (C:\projects\vscode\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\projects\vscode\node_modules\mocha\lib\runner.js:320:5)
`

I pulled latest code and pushed again. It failed again with...

`1) Telemetry - common properties default:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at Timeout.<anonymous> (C:\projects\vscode\node_modules\mocha\lib\runnable.js:226:19)
`

It would be great if you can guide me through the inconsistency of the error and how can we make it correct.

**Comment by joaomoreno** [comment]
Delaying this due to the upcoming SCM feature.

**Comment by joaomoreno** [comment]
@gagangupt16 So sorry to let you know that I'll have to close this since the old Git world is deprecated.

I'd happily accept a PR on the new [git extension](https://github.com/Microsoft/vscode/tree/master/extensions/git). Or I can also implement it, I just don't want to step on your toes. Let me know what you want to do. 👍

**Pull request closed without merging**
