### PR TITLE
Fix: xterm dependencie

### PR DESCRIPTION
**Pull request by lemanschik**
it was broken because of some false pushes there where a script to correct it periodical this corrects its till it changes from beta to latest. then you can change the tag at the end the tag references always work correct.

- https://github.com/microsoft/vscode/blob/main/scripts/update-xterm.js
- https://github.com/microsoft/vscode/blob/main/scripts/update-xterm.ps1

they can get removed via modification of this commit or with a extra one you choose else they get removed by:

- [x] https://github.com/microsoft/vscode/issues/167505

by the way the two above mentioned files do contain also false logic as they split into wrong frontend backend modules this leads to a desynced versioning as both use the same modules in fact. 

so if you do not merge this in and delete them you need as alternativ upgrade them at last to update both sides with the same module versions remote and the repo

### CODE REVIEW

**Comment by lemanschik** [comment]
@alexdima please review

**Comment by lemanschik** [comment]
@microsoft-github-policy-service agree

**Review by Tyriar — COMMENTED** [review]
I don't understand what the problem here is, the xterm updates work just fine and update in sync. I don't want the package.json to use the beta version as it must point at a specific version and it feels safer to me to point at the exact version that will be in yarn.lock.

Also you missed the remote/web folder which must also remain in sync.

> by the way the two above mentioned files do contain also false logic as they split into wrong frontend backend modules this leads to a desynced versioning as both use the same modules in fact.

If you find a bug where running the script successfully does not sync all 3 package.jsons please let me know. This script is only meant for our team to run though and has works fine in the past AFAIK.

**Comment by lemanschik** [comment]
@Tyriar the problem is that esm build is not working but that is ok as long as everything works for you i am fine with that i tought because of yarn correcting all the dependencies it would be clever to do it directly.

**Pull request closed without merging**
