### PR TITLE
Fix-74142 "Search: Focus Next Search Result" should put cursor in the editor panel 

### LINKED ISSUE #74142: "Search: Focus Next Search Result" should put cursor in the editor panel
Issue Type: <b>Feature Request</b>

When going through large refactorings based on search keywords it would be really nice if the `F4` Keybind would actually put the cursor in the code instead of just highlighting and focusing the next item.
EDIT: Currently the cursor only lands on the sighting if it was in the same file.

VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:18:31.618Z)
OS version: Windows_NT x64 10.0.17763

### PR DESCRIPTION
**Pull request by skprabhanjan**
@roblourens , As explained here ( https://github.com/microsoft/vscode/issues/74142#issuecomment-497597350 )
This PR will fix #74142 , please review this and let me know if anything needs to be changed , Thanks :)

### CODE REVIEW

**Comment by roblourens** [comment]
Just looking at the code, it looks like this would focus the editor also when we use the arrow keys to navigate, is that the case? We want F4 to focus the editor but the arrow keys to not focus the editor.

**Comment by skprabhanjan** [comment]
@roblourens , Sorry I tested that part but forgot to add it .
It does not focus the editor when we use arrow keys and only focuses the editor on f4 ( preserveFocus focus in true in the first case).
The type is not boolean and is undefined [here](https://github.com/microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L733) , so preserveFocus will be true
Let me know if i am still missing something and this wont work , i am happy to fix it :)

**Comment by skprabhanjan** [comment]
@roblourens , Did you get a chance to check that part and see if it works only on f4 ?

**Comment by roblourens** [comment]
I added this code for https://github.com/microsoft/vscode/issues/71757, with your change, https://github.com/microsoft/vscode/issues/71757 is regressed, I guess we have to find another solution but I'm not sure what it would be

**Comment by skprabhanjan** [comment]
@roblourens , what would you suggest for this PR now ?

**Comment by roblourens** [comment]
I don't know. I don't have time to debug it right now.

**Comment by roblourens** [comment]
Thanks for your investigation @skprabhanjan but I think I have another solution

**Pull request closed without merging**
