### PR TITLE
Fixes webview responding shortcuts twice on linux

### LINKED ISSUE #82670: Pressing Ctrl+W on release notes closes the window
Issue Type: <b>Bug</b>

Open a new window, close the Untitled tab, open Release notes and press Ctrl+W (or Cmd+W) on macOS.

Expected:
Release notes tab is closed.

Actual:
Release notes tab is closed as well as the current window.

You can also open a file, open Release notes and press Ctrl+W. Release notes and the last file will close.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-65-generic

### PR DESCRIPTION
**Pull request by onequid**
Add a platform condition for the registering of the "did-keydown" event listener.
Avoided transfering keydown events on Linux.
This PR fixes #82670

### CODE REVIEW

**Comment by mjbvz** [comment]
Looks reasonable. Let's see if this causes any regression for other comments. Please test using the next insiders build

**Comment by mjbvz** [comment]
I had to revert this change as it broke keybindings on linux: #85102

Please take another look at the addressing the problem in a different way

**Comment by OneQuid** [comment]
I apologize for not testing all the keybindings and the inconvenience brought by it.
And sorry that I have to drop this issue.

Here's something I tried. Surrounding following lines with the `!isLinux` if-condition would work properly as expected. However, the codes are there for a reason, I tried but failed to figure out what are these lines for. I doubt the change would break something somewhere else.

https://github.com/microsoft/vscode/blob/7521ebdeb48207b6848a9e13627ed653d08c7eb8/src/vs/workbench/electron-browser/window.ts#L160-L165

and the ipc event is sent here, but not listened anywhere else beside lines in `window.ts` mentioned above.
https://github.com/microsoft/vscode/blob/9c8b2f2f08e03e93a79c6a643b9b43edb4e41a86/src/vs/platform/menubar/electron-main/menubar.ts#L738-L742

**Comment by mjbvz** [comment]
Just make sure any changes:
 
- Don't break a normal keybindings for menu items when a webview is open
- Don't break a normal keybindings for menu items when a webview is not opened
- That everything works properly with both `"window.titleBarStyle": "custom"` and `"window.titleBarStyle": "native"`

**Pull request merged**
