### PR TITLE
allow focusing of next and previous page w PageUp/Down when in navigation mode

### LINKED ISSUE #149882: Support arrow keys and page up/down without modifier when in terminal navigation mode
When using command control + sdta upwards to read the terminal buffer, it is not possible to read the entire log.

Example when running a build of a java project with the mvn clean install command, thousands of log lines are produced when pressing control + up arrow I do not navigate through this entire report.

I think this command should only be pressed once and then it could be possible to navigate only using arrows and, advance or rewind a page when using pageup and pagedown and when pressing control plus down arrow it could exit the buffer area as it already does today.

I use the latest version of Nvda as well as the latest version of Vscode.

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #149882

### CODE REVIEW

**Comment by Tyriar** [comment]
I see a few issues:

- Just up and down trigger navigation mode now, I think we should require ctrl+up/down/pgup/pgdn to enter navigation mode before activating the up/down and page up/down keybindings
- Page up moves up a page but also moves to the previous row, the visible row should remain the same (opposite is true for page down)
- Sometimes page down doesn't move to the last row in the buffer, when there is no more room to scroll when using page down/page up it should move the focus to the very end

Recording 2022-06-20 at 08 22 08

**Comment by meganrogge** [comment]
> Just up and down trigger navigation mode now, I think we should require ctrl+up/down/pgup/pgdn to enter navigation mode before activating the up/down and page up/down keybindings

not for me on macOS, I'll look at the keybindings more closely. the behavior you describe above is how it currently works on mac

**Comment by Tyriar** [comment]
> not for me on macOS, I'll look at the keybindings more closely. the behavior you describe above is how it currently works on mac

Same for me now, I guess my ctrl key got stuck.

**Comment by Tyriar** [comment]
Page up/down still move 1 row when doing it.

Recording 2022-06-20 at 14 44 00

A better approach actually is to align exactly with how the editor does it; if the line is in the top 2, move up a page (to the second line, to give 1 line of context), if not it moves to the second line in the viewport without scrolling.

**Comment by Tyriar** [comment]
Opps, I hadn't pulled 🤦 still it's a bit weird at the ends and aligning with the editor is the best approach after thinking about it.
Recording 2022-06-20 at 14 48 41

**Comment by meganrogge** [comment]
definitely something weird going on when switching bw up/down line and up/down page. it's working for me to jump to the top though. not sure why that's happening for you

**Comment by meganrogge** [comment]
https://user-images.githubusercontent.com/29464607/174683971-5254cfb3-76fa-4b58-93a9-eb444aed1944.mov

**Comment by meganrogge** [comment]
the keybindings for these command w navigation mode enabled interfere with command tracking fyi @Tyriar not sure if that's expected, but it's not a new issue

**Comment by Tyriar** [comment]
@meganrogge yep I'm aware of that

**Review by Tyriar — APPROVED** [review]
Works great 👍

**Pull request merged**
