### PR TITLE
Show preview tag on extention page if extension is in preview

### LINKED ISSUE #13276: Extensions don't appear as `preview` in product
- VSCode Version: Code - Insiders 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d, 2016-10-01T00:34:33.697Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.sort-lines-1.1.0, Tyriar.theme-glacier-0.0.10, Tyriar.vscode-terminal-here-0.0.5, christian-kohler.path-intellisense-1.0.2, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, eg2.tslint-0.5.39, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.3, rebornix.Ruby-0.8.0, rebornix.nova-0.0.5, redhat.java-0.0.4, ryu1kn.annotator-0.10.0, ryzngard.vscode-header-source-1.0.4

https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs is an example of an extension that has `"preview": true` in its package.json which shows up on [web](https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs) but not in product.

### PR DESCRIPTION
**Pull request by golf1052**
This fixes #13276

### CODE REVIEW

**Comment by sandy081** [comment]
@golf1052 Thanks for the PR. I am not aware of `preview` extensions. Guess this is market place feature. Do you have an example of such an extension and how it is show in the market place?

**Comment by golf1052** [comment]
There's an example in the issue. https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs

image

**Comment by sandy081** [comment]
@golf1052 My bad, Did not notice the issue. Will take a look. Thanks.

**Comment by golf1052** [comment]
Wanted to ping on the status of this, anything that I need to do?

**Comment by sandy081** [comment]
@golf1052 Will be taken care in November.

**Comment by golf1052** [comment]
Hoping this will be merged in this month, thanks.

**Comment by sandy081** [comment]
LGTM

**Comment by golf1052** [comment]
Great, thanks!

**Pull request merged**
