### PR TITLE
Use 'r+' with truncation when saving existing files on Windows

### LINKED ISSUE #6363: Alternate data streams are removed by saving
- VSCode Version:1.1.0
- OS Windows Pro 10.0.10586.318 V1511 

Steps to Reproduce:
1. Open with VSCode a text file that has one or more alternate data stream files.
2. Make some small change in the text.
3. Save the file.
4. The ADS files have been removed.

I'm sure that there is a setting that will prevent VSCode removing ADS files when saving — they are, after all, a Windows special.  If not, could you please regard it as a bug and add such an option.

### PR DESCRIPTION
**Pull request by seishun**
Opening a file with 'w' flag removes its alternate data streams. To
prevent this, extend the logic used for hidden files to all existing
files.

Fixes: https://github.com/Microsoft/vscode/issues/6363

### CODE REVIEW

**Comment by andrewmackrodt** [comment]
I think this would be better as a configuration item (default off) for all platforms. It's becoming quite common for editors to support the ability to disable safe writes (i.e. enable save in place); I'd imagine this would therefore be of benefit to Mac OS and Linux files using ACLs?

**Comment by drujd** [comment]
This also fixes #49021

**Comment by DarthSpock** [comment]
bump

**Comment by drujd** [comment]
@bpasero Is there a chance this gets merged? This would be a blessing for all WSL users.

**Comment by bpasero** [comment]
Thanks for the PR, I think we should try to go with it as it seems like the only solution. I fear a little bit the consequences this could have compared to how we save today, but our insiders hopefully reveal if there are any. If there are issues we might have to put this behind a setting.

**Pull request merged**
