### PR TITLE
Better contrast for lineHighlight and find results #9631

### PR DESCRIPTION
**Pull request by bgashler1**
This is a plan B for https://github.com/Microsoft/vscode/issues/9631

Ideally, I would like to do what I'm recommending in https://github.com/Microsoft/vscode/issues/9631#issuecomment-242249462 instead.

### CODE REVIEW

**Comment by bgashler1** [comment]
These background colors are derived rgba colors from the existing `current-line` border color in our default theme to be more consistent yet still blend with other themes of varying backgrounds.

**Comment by sandy081** [comment]
@bgashler1 Thanks for providing the colors. Do you think the old color `rgba(253, 255, 0, 0.2)` looks good for light themes? The new one for light themes is less prominent. Also we use this color at multiple places like Go to line and Outline. 

How about retaining the old color for light themes and using the new proposed colors for Dark and High Contrast themes?

**Comment by bgashler1** [comment]
@sandy081 I think you're right.  I just reverted the change on the light theme but left the others in tact.  Thanks for the great suggestion 👍

**Comment by sandy081** [comment]
@bgashler1 This branch has conflicts and I could not merge it easily. Since changes are few, I hand picked and delivered them here - 76f690054e03db485c3fdc341e6993f79fab09a9

Hope it's ok for you.
Thanks

**Pull request closed without merging**
