### PR TITLE
CLI: When reading from stdin, exit when stdin closes

### LINKED ISSUE #39682: When reading from stdin, do not implicitly set --wait mode
testing #39330

When piping output from a terminal to code, the command in terminal waits until I close the editor or until i press `Ctrl+C`.

`ps aux | code-insiders`

result: command does not terminate until `ctrl+c` or close the editor (even though it is on disk).

I would expect that the command to terminate immediately.

### PR DESCRIPTION
**Pull request by firelizzard18**
This PR fixes #39682

Currently, when opening stdin of a command via piping to the CLI (e.g. `tar tf | code -`), the CLI adds the `--wait` flag. This is non-intuitive behavior, as most users assume that `code` will exit as soon as the process piped to it exits. This change removes the `--wait` behavior and instead will exit once stdin closes, which occurs when the process piping to `code -` exits or closes its stdout early.

### CODE REVIEW

**Comment by bpasero** [comment]
I do not see this working running out of sources on macOS:

image

`ps aux | grep code | scripts/code-cli.sh -`

**Comment by firelizzard18** [comment]
I was seeing that issue too. I solved it by adding a timeout that kept the CLI open for at least 1 second. I could also solve it by removing [`fs.unlinkSync(stdinFilePath);`](https://github.com/microsoft/vscode/pull/89314/files#diff-5abef0ee0f64ab9a837696b4688e5ae7R358) from the returned promise. However, this would leave a dangling temp file. One solution to that would be adding a `--delete-when-closed` argument to the core app.

**Comment by firelizzard18** [comment]
@bpasero Please try again with the newest commit

**Comment by bpasero** [comment]
Yeah seems to work fine now. But the dangling temp file might be odd. Needs more thought.

**Comment by firelizzard18** [comment]
One option is to use sockets/pipes to transfer data from the CLI to the GUI. Use a randomly named unix socket on macOS and Linux, and a named pipe on windows. In both cases, this can be used via `net.createServer` and `net.createConnection`:

1. `CLI>` Open a randomly named pipe/socket with `net.createServer`
2. `CLI>` Call the GUI with `--ipc-stream SOCKET_PATH --ipc-stream-name EDITOR_NAME`
3. `CLI>` Wait for a connection
4. `GUI>` Create a new editor titled EDITOR_NAME
5. `GUI>` Connect with `net.createConnection` and feed data from the connection to the editor
6. `CLI>` Pipe STDIN to the client socket stream
7. `CLI>` When STDIN is closed, close the client socket and the server, then exit

Windows 10, v1803 supports unix sockets [[1]](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) [[2]](https://bsmadhu.wordpress.com/2018/08/22/unix-domain-socket-support-in-windows/). So it might be possible to use the same implementation, when Windows supports it. To check, VSCode can run `sc query afunix`.

Implementation reference: [unix sockets](https://gist.github.com/Xaekai/e1f711cb0ad865deafc11185641c632a), [named pipes (Windows)](https://stackoverflow.com/a/32172145/762175).

**Comment by firelizzard18** [comment]
I would be happy to implement the changes I suggest, if this is something the team would accept.

**Comment by bpasero** [comment]
@firelizzard18 while I like that approach technically, I think there are challenges if VSCode is connected to a remote environment (like SSH): I do not think we could pipe the contents out of the box, since it is a remote location. So, the workaround of writing to a temp file on disk at least allows us to access the data.

@aeschli @chrmarti @roblourens can you confirm that piping from stdin is supported from a remote terminal into VSCode?

**Comment by aeschli** [comment]
@bpasero Yes, that was added for this milestone. See https://github.com/microsoft/vscode-remote-release/issues/2212.

**Comment by firelizzard18** [comment]
@bpasero I added a `--cleanup-files` flag. When files are opened via the CLI and this flag is passed, the files opened by that command will be deleted when the user closes them or when the window is closed. I added this flag to the defaults when reading from stdin, so the CLI can exit once stdin is closed, and the temp file will still be cleaned up (by the main process).

**Comment by bpasero** [comment]
I am sorry, but don't feel like this is an area I would think a PR works for me. Closing given out of date.

**Pull request closed without merging**
