### PR TITLE
refactor css variables for findWidget

### PR DESCRIPTION
**Pull request by Kalmaegi**
For https://github.com/microsoft/vscode/issues/165169
- [x] src/vs/editor/contrib/find/browser/findWidget.ts

### CODE REVIEW

**Review by Adisa101 — APPROVED** [review]

**Comment by weartist** [comment]
@rebornix Hi, how do I request a review for this PR~

**Comment by weartist** [comment]
@rebornix hi, I resolved conflicts and adapted the latest code

**Comment by weartist** [comment]
@rebornix resolved conflicts and updated the latest adaptation code

**Comment by rebornix** [comment]
Thanks for the contribution, since I can't update your PR, I cherry-picked your change and sent a separeate PR https://github.com/microsoft/vscode/pull/203762.

**Pull request closed without merging**
