### PR TITLE
#7989 Git: Allow empty commits when merging

### LINKED ISSUE #7989: Git integration fails to see merged file as staged if I reject all incoming edits
VS Code Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Date 2016-06-14T13:00:22.146Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Windows 10 Enterprise x64, latest non-Insider
git version 2.9.0.windows.1

Description: during a Git merge process, VSCode can sometimes show no pending changes and refuse to let me commit, while command-line Git believes a merge is in progress and lets me commit. This occurs if the changed file contains no changes (after merge) that came from the commit that I am merging into my local state.

Steps to Reproduce:
1. Create Git repository (e.g. on GitHub).
2. Clone to working folder A.
3. In working folder A, commit a file with some arbitrary text. Commit and sync
4. Clone to working folder B.
5. In working folder B, change some part of the file. Commit and sync.
6. In working folder A, change some part of the file, conflicting with previous. Commit and sync.

This will result in a merge conflict due to the change from working folder B getting pulled.

Resolve the conflict by removing all changes pulled form working folder B - the file should be the same as the committed state that existed in working folder A. Stage the file to mark the file as resolved.

Expected result: file is staged and VSCode lets you commit the merge.

Actual result: file disappears from Git tab and VSCode says cannot commit as there are no pending changes.

`git commit` from the command line works fine to finish the merge, only VSCode refuses to cooperate here.

### PR DESCRIPTION
**Pull request by alarr46**
This PR fixes #7989 : it allows empty git commits when a merge is in progress.

Following [this advice](https://github.com/microsoft/vscode/issues/7989#issuecomment-227873770), I made Code aware that a merge is in progress. I did so by checking for the existence of the file `.git/MERGE_HEAD` : I don't know if it is the best way, but it is used by zsh for example.

### CODE REVIEW

**Comment by sanjom** [comment]
This PR fixes #88034

**Comment by WashirePie** [comment]
Bump

**Comment by alarr46** [comment]
> 
> 
> Bump

I rebased this on master so it is mergeable again.

**Comment by joaomoreno** [comment]
Thanks for the PR! I've went another route and decided to allow empty commits via confirmation in any case.

**Pull request closed without merging**
