### PR TITLE
Allow scc providers hide commit input box.

### PR DESCRIPTION
**Pull request by IlyaBiryukov**
Fix for #51808.

### CODE REVIEW

**Comment by joaomoreno** [comment]
Review notes:

1. There already is a `SourceControlInputBox` object in the API. This feature should just be a `visible` property on that object.
2. The current implementation doesn't actually react on changes to that `visible` property, it just relies on the value when the SCM repository gets rendered, which is sub-optimal.

I've addressed both these issues and merged this in: https://github.com/Microsoft/vscode/commit/f1f5385a68bfab396232054a3bb573aa16a05e1d

Thanks! 🍻 

---

@jrieken Sorry for sidelining this, but this introduces a new proposed API: one which allows to hide a source control provider's input box. Let me know if you want me to bring it up for review in the API call.

**Comment by jrieken** [comment]
It's OK if it is just proposed but I find the scenario rather weird and LS specific. Would a real source control provider ever want to hide its input field? Should this be linked with the fact that the file system in readonly and then the main side automagically hides/disables the input box?

**Comment by jrieken** [comment]
fyi - this has caused https://github.com/Microsoft/vscode/issues/61676 and the merge has been reverted

**Comment by joaomoreno** [comment]
@jrieken Thanks for jumping on it.

🤦‍♂️ https://github.com/Microsoft/vscode/commit/e3375691ee2d64e44922ae515d0d799489ce9dc2

I am embarrassed.

**Pull request merged**
