### PR TITLE
Add experimental recursive version of executeHoverProvider command

### PR DESCRIPTION
**Pull request by mjbvz**
For #218240

Adds an experimental `executeHoverProvider_recursive`  command. This avoids calling any exclusive providers. The only use case is for an exclusive provider to invoke all the normal providers. Otherwise it behaves the same as the normal `executeHoverProvider` command

Not super happy with this as it duplicates code for a very specialized use case. However it does work and is considerably simpler than some of the other approaches I explored in #218240

Instead of adding duplicate commands, we could instead use an argument or somehow sneak this information in on the uri. Changing the uri is a little scary tho as we have to make sure the modified uri doesn't leak back and confuse providers

cc @jrieken

### CODE REVIEW

**Comment by mjbvz** [comment]
I'm going to merge these as all the new commands are behind `.experimental`. This should help the Python and Java folks as there's now a single text document type for them to worry about

Open to other ideas on how to implement this but so far this seems to work well even if it's not particularly elegant

**Review by lramos15 — APPROVED** [review]

**Comment by jrieken** [comment]
I really don't like this

**Comment by mjbvz** [comment]
Also not a fan of the implementation but it does dramatically simplify our code block intellisense story for extensions. Now they only need to know about a single virtual file system and all of the code blocks are available as text documents

I'll keep thinking about other ways to implement this and please let me know if you have any other ideas too

**Comment by jrieken** [comment]
How about unregistering respective providers that invoke `xyz_recursive` command so that they don't re-enter?

**Pull request merged**
