### PR TITLE
Add support for angle bracket matching and colorization in Typescript

### LINKED ISSUE #151196: Support <...> bracket matching in TypeScript
Mark `<` ... `>` in `punctuation.definition.typeparameters.begin.ts` and `punctuation.definition.typeparameters.end.ts` as brackets.

Should be very easy, given the new bracket matching feature to consider textmate scopes.

### PR DESCRIPTION
**Pull request by liby**
This PR fixes #151196

cc @hediet

### CODE REVIEW

**Comment by liby** [comment]
> This looks good, thank you for the PR! Did you test it / can you post a screenshot?

So far this is all I can think of.
image

**Comment by hediet** [comment]
Hmm, it should probably also be ignored for jsx elements (`return <div></div>;`).

**Comment by liby** [comment]
> Hmm, it should probably also be ignored for jsx elements (`return <div></div>;`).

It looks like we just need to filter `meta.brace.angle` and `punctuation.definition.tag` again.
image


But I feel that this implementation does not seem to work well and there is always the possibility of missing something. Are there other better options? Or use the `balancedBracketScopes` option to implement a similar whitelist pattern?

Another question is that I'm not sure if the use of `"balancedBracketScopes": ["punctuation.definition.typeparameters"],` overwrites the currently colorization brackets, and if so, that's a bit tricky.

**Comment by liby** [comment]
> This would need to allowlist all the cases for (...), {...} and [...] too then... Which might be reasonable though.

From the description, it is no different from the current solution, only now I'm doing the exclusion method. Then let's continue with the current solution, if you don't have any objections either. 🥰

**Comment by hediet** [comment]
I will merge this after the June release, so we have enough time to test this.

**Review by jrieken — APPROVED** [review]

**Pull request merged**
