### PR TITLE
Disable lightbulb in scm input

### PR DESCRIPTION
**Pull request by mjbvz**
The lightbulb decoration looks out of place in scm input. With this, we still allow code actions using the shortcut or problems UI

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
Isn't SCM a workbench contrib so that makes this a layer breaker? Can the SCM text editor disable the lightbulb feature from the contrib instead?

**Comment by Tyriar** [comment]
When I added something for the terminal into editor land I ended up getting a debt item to remove it, I suspect the same applies with scm.

**Review by rebornix — COMMENTED** [review]
I'll suggest we separate lightbulb contrib from code action contrib (maybe make light bulb depend on code action contrib) and we can avoid making editor aware of scm

**Comment by Tyriar** [comment]
Another option which is simpler but maybe not quite as nice is to get the contrib instance after it's created and disable light bulb from a public method on `CodeActionController`?

**Comment by mjbvz** [comment]
I can follow up with those changes but let's merge this first as the lightbulb is already showing up

**Review by TylerLeonhardt — DISMISSED** [review]

**Comment by TylerLeonhardt** [comment]
approved based on last comment ^

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
