### PR TITLE
Fix the handling of tabs in quickinfo Markdown code blocks

### LINKED ISSUE #95096: Tabs get replaced by four spaces in IntelliSense quick info box (for JSDoc comments in JavaScript and TypeScript)
- VSCode Version: 1.43.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. In a JavaScript file paste the following code:
    ~~~js
    /**
     * ```
     * 1234567890
     * 		90
     * 123	890
     * ```
     */
    function bar() {}
    ~~~
    **Note that there are three tabs in the code.**
2. Hover over `bar()` and have a closer look at the displayed IntelliSense quick info tooltip. Each tab, either at the beginning or in the middle of a line, has been replaced by four spaces. There is a **surplus space at the beginning of the second line** in the text displayed in the quick info box. This is due to a [whitespace bug in TypeScript's JSDoc parser](https://github.com/microsoft/TypeScript/issues/37717#issuecomment-606669473). I have [fixed this bug](https://github.com/microsoft/TypeScript/pull/37891). If you use my TypeScript version the surplus space is gone.

I have [reported this bug previously](https://github.com/microsoft/TypeScript/issues/37717#issuecomment-606669473) in combination with the whitespace bugs from TypeScript. The issue got moved to the TypeScript repo. **However, this time I made sure this is a VS Code bug. I'll explain how to verify it.**

[By modifying the file `extensions/typescript-language-features/src/features/hover.ts`](https://github.com/Neonit/vscode/commit/08a10522d544b6968ae7fd359ead3a0f025bbdae) you can add a debug output to the quickinfo tooltip, which displays the text returned by TypeScript's `quickinfo` command. For the above example, it will display the second line of the following as output:
~~~
                        ┌─┬──────────┬─ TypeScript preserved the tabs
"```\r\n1234567890\r\n \t\t90\r\n123\t890\r\n```"
                      └─ this is the surplus space from the mentioned TypeScript bug,
                         which will be gone, if you use my fix
~~~
As you can see TypeScript preserved the tabs. The replacement must take place somewhere in the VS Code code.

The **expected behavior** would be, of course, that tabs are preserved and set to a width of four (like in VS Code's Markdown preview).

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Neonit**
This PR fixes #95096

This alters the behavior of Markdown parsed from JSDoc documentation comments and its appearance in the IntelliSense quickinfo boxes on mouseover. Previously, tabs were replaced by four spaces each. I don't know, why. Also, I set the tab size to 4 for code blocks in the quickinfo box. Testing instructions are in the issue thread.

### CODE REVIEW

**Comment by Neonit** [comment]
Unfortunately I think I need to recommend against my own PR. I just found out that the file `marked.js` is an external library. I didn't see that before, because I didn't expect an external library to be in the folder it is in nor to be tracked by the repo. I wondered why it's not in TypeScript, but I thought maybe it's some legacy code.

For the used library [there exists an issue addressing this problem](https://github.com/markedjs/marked/issues/644). The tabs are replaced by spaces, because the code apparently cannot handle tab indentation in some cases. I did a quick test and it seems tab indentation screws up nested lists. I couldn't see any other issues, though.

So maybe there should be a switch in the settings for this with the two options:

1. Screw up my tabs in my Markdown code
2. Screw up my nested lists

For the user to choose from.

Preferably, [markdown-it](https://github.com/markdown-it/markdown-it) looks like a much better thought-through library. I mean, marked.js didn't bother fixing this issue for almost five years. Also, wouldn't it be smart to use the same parser for both the quick info boxes and the Markdown preview? Apparently, the library used for the Markdown preview does not replace tabs so it's likely not marked.js.

**Comment by mjbvz** [comment]
Thanks for investigating. 

I agree that `marked` has many issues, however it's also pretty small. This is important because we ship it as part of the [Monaco editor](https://github.com/Microsoft/monaco-editor). 

Is there some way to scope your fix just to code blocks?

**Comment by Neonit** [comment]
Well, the replacement is just a dumb *in all the code, replace a character* command with no further context information.

I thought of maybe another *fix*. Apart from the one informational issue that tab characters get replaced by space characters I'd say the major problem are the visual issues:

1. Tabs are being fixed to a size of 4.
2. Mid-text tabs do not have the expected aligning effect.

As long as the resulting length is 4 I personally do not care about 1. to be honest. I use them to align mid-text, though.

```txt
apple	red
banana	yellow
lime	green
```

So I am thinking about a fix for 2. I could replace the few calls to `String#replace()` by a custom function that does the current replacements and replaces tabs by either 2, 3 or 4 spaces depending on their offset within the line to mimic their aligning nature. This should have no impact on indentation tabs, but fix mid-text tabs.

```txt
apple   red
banana  yellow
lime    green
```

Currently, this would be the result:
```txt
apple    red
banana    yellow
lime    green
```

Why is this important for me? I haven't posted anything about it, yet, and I don't know how open you are for introducing new settings to VS Code, but I was thinking about a new setting allowing users to decide whether they want their quick infos with `wite-space: pre-wrap` and a monospace font (configurable globally or for the workspace and for each file type as well). I [asked on SO in the past whether I could enable preserving whitespace](https://stackoverflow.com/questions/61024647/how-to-alter-documentation-comment-parsing-or-at-least-disable-markdown-there-in) and I think there is no way currently. And as there doesn't seem to be a big demand for this feature I'd add it myself.

**Comment by mjbvz** [comment]
I'm going to close this PR as it is out of date and the corresponding issue has not seen any further interest  since it was opened

**Pull request closed without merging**
