### PR TITLE
Adapter css for #165169

### PR DESCRIPTION
**Pull request by Kalmaegi**
for #165169

- [x]  src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts

### CODE REVIEW

**Comment by weartist** [comment]
@roblourens  If it is convenient, please also help apply for this PR review, thank you very much!

**Comment by weartist** [comment]
> - src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
> 
> - src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
> 
> 
> 
> Sorry again, I am working on this debt and would like to test and push together. I very much appreciate the effort for doing this. I would request to please revert the changes.
> 
> 
> 
> Thanks


It's okay, I need to wait until I get up tomorrow morning to submit, see you tomorrow!

**Comment by weartist** [comment]
@sandy081 Solved complete

**Comment by weartist** [comment]
@sandy081 fix it again

**Comment by sandy081** [comment]
@roblourens This is adoption in the following file only

- src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts

Hence reassigning to you

**Review by roblourens — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
