### PR TITLE
Replace which-pm with preferred-pm

### LINKED ISSUE #161579: Should detect package manager with preferred-pm instead of which-pm
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: macOS 12.6

I noticed that [`preferred-pm.ts`](https://github.com/microsoft/vscode/blob/main/extensions/npm/src/preferred-pm.ts) uses `which-pm`, which only checks for which package manager installed `node_modules`. We should probably use `preferred-pm` instead, as it uses `which-pm` but checks for lockfiles first, so you can still use the package manager detection before installing anything. This would also make VSCode's installation behavior more consistent with other tools using that package, such as pnpm and Astro.

### PR DESCRIPTION
**Pull request by Balastrong**
This PR fixes #161579.

### CODE REVIEW

**Comment by Balastrong** [comment]
Oh, I didn't notice the policy "Prevent yarn.lock changes in PRs", I'm not sure how to proceed from this point.

Should I revert the `yarn.lock` changes and keep the PR up or is there any other particular handling?

**Comment by meganrogge** [comment]
Sorry for the delay and thanks for looking into this. Looks like you've got some conflicts to fix now - I'll try to get to this soon

**Comment by Balastrong** [comment]
Thanks @meganrogge  for the reply! I updated the branch and fixed the conflicts :)


(side note, the vscode git UI had some little troubles in doing this merge, it was ~1000 commits though. It took a little time to merge and push but went fine)

**Comment by meganrogge** [comment]
Thank you for that context @alexr00 and thanks for the PR @Balastrong , but I'll be closing it for the reason stated above

**Comment by Balastrong** [comment]
That makes sense, thank you for the support! :)

**Pull request closed without merging**
