### PR TITLE
Extensions are only loaded if they are allowed by a blocklist

### PR DESCRIPTION
**Pull request by jfoley**
This PR begins to address #84756.

This PR includes functionality to allow certain extension publishers or to disallow certain extension publishers. It also includes the ability to disallow particular extensions.
In order to use it, add the following to your `settings.json`:
```
"extensions.blocklist": {
		"allowedPublishers": ["my-trusted-publisher"],
		"allowedPackages": [],
		"prohibitedPackages": []
	}
```
Attempting to install a forbidden extension will result in an error notification letting the user know that the extension is prohibited by local policy.

We wanted to open this PR to gather feedback and see if we are on the right track.

### CODE REVIEW

**Comment by jfoley** [comment]
Hello, we were wondering if we might be able to get an update on this PR. We have a couple of high-profile projects that are awaiting feedback on it. Thanks!

**Comment by sandy081** [comment]
Looks like you picked up a feature which needs further discussions. Need to see how useful it is for all users? Can you also please let us know the use case behind this?

If I remember, I think I suggested to start with following feature

> The policy would include a setting whether to allow side-loading of extensions (as VSIX files)

**Comment by mike-myers-tob** [comment]
> Looks like you picked up a feature which needs further discussions. Need to see how useful it is for all users? Can you also please let us know the use case behind this?
> 
> If I remember, I think I suggested to start with following feature
> 
> > The policy would include a setting whether to allow side-loading of extensions (as VSIX files)

Hi! I work with John, I can elaborate on the use case here.

VS Code is a popular development environment, including among employees of medium/large companies, so it is installed on many (managed) company laptops and desktops. Company security teams seek to track and manage the software installed on company systems, but VS Code is an extensible application with a built-in extension marketplace. Users, even those without administrator rights, can freely choose to install any extension into VS Code. Those extensions are sandboxed, but are unsigned and managed in a user-owned directory. Extensions are installable through an extension marketplace controlled by Microsoft, but enterprise security teams want a more granular ability to mitigate risk and exposure to unapproved software on their fleet. Others before us have filed related issues in https://github.com/microsoft/vscode/issues/52116 and https://github.com/Microsoft/vscode/issues/33185 

Because of VS Code's robust extensibility, we have been approached by multiple customers asking us to develop enhancements to VS Code that make it more "manageable" within the corporate environment. The first step @sandy081 [suggested in the last discussion](https://github.com/microsoft/vscode/issues/84756#issuecomment-560120039) was to create a policy to control sideloading, but our customers have told us that the most desired use case for them is controlling what the user can install from the _marketplace_ beginning with the basic whitelist/blacklist by extension ID.

We'd like to start there, and get feedback on the feature and our implementation of it. Any response is much appreciated and we want to work with all parties to adapt a solution.

**Comment by sandy081** [comment]
I understand your requirement and this is under discussions with Marketplace team. 

- https://github.com/microsoft/vscode/issues/21839

Hence I would not suggest to introduce hacks or workarounds for a specific user.

**Comment by dguido** [comment]
@sandy081 #21839 doesn't appear to have perfect overlap with this PR. That issue describes allowing enterprises to host their own extensions. This PR addresses companies that want to control which extensions an employee can install from the public marketplace.

Also, the intention was to PR production-quality/ready code, not a "hack."

Can you please re-open this issue so we can continue to refine it with the team at Microsoft? We will get in touch with @prashantvc in the meantime. Thanks.

**Comment by sandy081** [comment]
> That issue describes allowing enterprises to host their own extensions. This PR addresses companies that want to control which extensions an employee can install from the public marketplace.

They look similar to me. Is not that enterprises want to have their own set of extensions (private or hosted from marketplace) available to their users?

It might not be a hack but it seems to be a workaround for the problem that has to fixed at another level. Ideally it's about configuring marketplace to serve only restricted extensions.

Also I do not think the provided fix/solution here will help because its always possible for users to modify settings.

I would recommend to continue discussion in the main issue - #84756.

**Comment by dguido** [comment]
> They look similar to me. Is not that enterprises want to have their own set of extensions (private or hosted from marketplace) available to their users?

> It might not be a hack but it seems to be a workaround for the problem that has to fixed at another level. Ideally it's about configuring marketplace to serve only restricted extensions.

> Also I do not think the provided fix/solution here will help because its always possible for users to modify settings.

1. Enterprises we spoke with would like to avoid having to host additional infrastructure to support yet-another-development-tool.
2. They already have endpoint controls -- JAMF, osquery, Santa, etc -- that would make it simple to deploy and enforce this setting.
3. Providing guardrails around the public marketplace provides a better end-user experience.

If you _also_ create a feature to let enterprises host their own, internal marketplaces, then I think that would be complementary but not a replacement to what we developed.

> I would recommend to continue discussion in the main issue - #84756.

We will. But in the meantime, please re-open the PR. We'll continue working on it while we're discussing this approach with the relevant PMs. Thanks.

**Comment by sandy081** [comment]
Reopened as per user request but assigning this to PMs for further continuation.

**Comment by chrisdias** [comment]
Per https://github.com/microsoft/vscode/issues/84756#issuecomment-603310468 this is a good topic on our Roadmap, but this PR is not something we can accept right now as the scope is too narrow (only applies to `settings.json`). Once we have a comprehensive design we can start to accept PRs on this.

**Pull request closed without merging**
