### PR TITLE
#98942 Clear Search Pattern Fields

### LINKED ISSUE #98942: Feature request - Clear button of search panel should clear everything
The clear button of the search panel should clear everything, all the inputs, and not only the search results + the "search" input.

We still need to manually clear some inputs after clicking the clear button :

vscode-searc-clear

### PR DESCRIPTION
**Pull request by edjeffreys**
* Make clear button a 2-stage button
* Clear search fields if text is present, and leave file pattern fields, otherwise clear file pattern fields
* Introduce clear method on PatternInputWidget

Edit (Took me longer than it should have to realise what a 2-stage button means...)

This PR fixes #98942

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Thanks! 
This should additionally at minimum change the hover text of the button to reflect the two stages, and ideally have two separate icons. (@misolori for input re. icons)

**Comment by misolori** [comment]
I wouldn't create a separate icon for this, we already do this in the Settings & Keyboard Shortcut search input. I'd ensure you update the title properly.

I also think this should be behind a setting as people will be split on a preference. I'd personally want it to clear everything on a single click.

**Comment by edjeffreys** [comment]
Happy to take a look at both the title, and the setting.

Any preference on what the default behaviour should be for clearing?

**Review by roblourens — APPROVED** [review]
Looks great! I don't want to add a setting yet, since the default behavior is not changing, and I try to avoid adding settings for every little thing. We can wait and see if we get more feedback about that though.

**Comment by roblourens** [comment]
@JacksonKearl what are you thinking that the title should be updated to say?

**Comment by edjeffreys** [comment]
Thanks @roblourens! I'll hold fire for now then.

**Comment by roblourens** [comment]
I don't know that we need to update the title, I think that it already will say "Clear Search Results" when there are no search results and it is just clearing the input box. If we want to be totally specific, I think there would 3 states.

- "Clear Search Results" whenever there are search results because we need to be clear that those are going away
- "Clear Search Query"
- "Clear Extra Query Fields" or something like that

But I don't know that it's necessary, what do you think @JacksonKearl?

**Comment by JacksonKearl** [comment]
I'm convinced, people will probably discover it anyways if they really need it.

**Comment by ArturoDent** [comment]
Just to be clear, this is the behaviour I see in the Insiders' Build:

------------------

The first click clears the search results **and** the query/replace terms and does not affect the `Files to Include/Exclude` fields.

The second click clears the `Files to Include/Exclude` fields.

----------------------

I like this, it just wasn't clear from the preceding comments that this was how it would turn out.

**Pull request merged**
