### PR TITLE
New verbosity levels for `window.title` templating

### LINKED ISSUE #145238: Request: `${rootNameShort}` for Window Titles
On all platforms, the `${rootName}` Window Title variable includes **" (Workspace)"**, and when using Remotes like WSL, the variable also includes something like **" [WSL: Ubuntu]"**. It would be useful to have a shorter variant with just the Workspace name, so instead of **"wsName (Workspace) [WSL: Ubuntu]"** we could have **"wsName"**.

I frequently have several Workspaces open and use Workspace names to distinguish between open windows in the Windows Task Bar/View and macOS Mission Control/Exposé. The extra characters describing the Workspace often cause the OS to truncate the visible window title, hiding other useful information.  The `window.title` property allows customization, but putting the Workspace first often sacrifices filename visibility for Workspace metadata. 

Since we already have access to `${remoteName}`, perhaps other Workspace component names could also be added? 

Current:
- `${rootName}` - **wsName (Workspace) [WSL: Ubuntu]**
- `${remoteName}` - **WSL: Ubuntu**

Proposed: 
- `${rootNameShort}` - **wsName**
-  `${rootIdentifier}` - **Workspace**   _// (similar to `${separator}`_

With those two variables defined, `${rootName}` could then be expressed as `${rootNameShort} (${rootIdentifier}) [${remoteName}]`

### PR DESCRIPTION
**Pull request by impliedgg**
This fixes #145238 by replacing the verbose flag with the `Verbosity` enum, allowing for SHORT, MEDIUM, and LONG lengths.

`${rootName}` is left as is, but there is also `${rootNameShort}` (stolen from #146780) and `${rootNameLong}` (in place of the verbose flag).

Current roadmap for this PR:
 - [ ] Make sure the commit didn't break anything
    - I was too lazy to set up a development environment (it's 2AM, I was bored, now I'm tired).
 - [ ] Wait for changes to be suggested
 - [ ] Implement suggested changes

### CODE REVIEW

**Comment by overestimate** [comment]
@microsoft-github-policy-service agree

**Comment by overestimate** [comment]
Anyone know exactly how I should go about this? I need to redefine the Verbosity enum or refactor it to where it's not violating any code organization rules, but I'm unsure of exactly what way should be used.
Currently, it's defined in `vs/workbench/common/editor.ts`, but I also need it in `vs/editor/standalone/browser/standaloneServices.ts`.

**Comment by bpasero** [comment]
Did you see https://github.com/microsoft/vscode/pull/165744 ?

**Comment by overestimate** [comment]
@bpasero Honestly, didn't as I don't think it was l linked in the issue. Closing as duplicate, thanks.

**Pull request closed without merging**
