### PR TITLE
Proposed Feature: Control StatusBar background color

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
This PR introduce an **API to modify the color of the status Bar** 🌈, so that it can be used by extensions. 
One of the main example use (and reason I implement it), is to *modify the statusBar color based on vim mode*: (cf https://github.com/VSCodeVim/Vim#vim-airline)
So far current implementation modify the settings with cause huge overhead (https://github.com/VSCodeVim/Vim/issues/2021#issuecomment-465729996)

**This is a draft, any feedback is more than welcome.**
I wait there is consensus on the API to write both the detailed documentation and the tests.
(Speaking of test I might need some guidance about where to write them)

One can try out by getting the following commit: https://github.com/AdrieanKhisbe/vscode/commit/8d821316fc1191afff1ec2870a8f81588d50efe1, that add command to set statusbar in green, red, or blue(for some duration)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
_(this was marked as draft to recieve first feedbacks)_

**Comment by roblourens** [comment]
The status bar is already themeable. e.g.

```
"workbench.colorCustomizations": {
    "statusBar.background": "#ff0000"
}
```

I don't understand what this is for, is there an issue for this?

**Comment by AdrieanKhisbe** [comment]
@roblourens I knew about it.

I might have not make clear enough the point of the PR was to be able to modify background color **dynamically** without having to change the settings.

(Here is another issue pointing out one of it's use: https://github.com/Microsoft/vscode/issues/68376)

**Comment by iansan5653** [comment]
Seems like you could get conflicts between extensions 'fighting' over the status bar color. How would that resolve?

**Comment by AdrieanKhisbe** [comment]
@iansan5653 It's an eventuality indeed.
A priotity mecanism could be introduce maybe.

(but nothings prevent a priority war ^^)

**Comment by pavkum** [comment]
I was just going through PRs and found this interesting. Just want to add my 2 cents. 

Can vscode employ Vim / emacs way of coloring status bar? Instead of coloring the whole status bar, what if extensions are allowed to color / theme their respective sections?

**Comment by bpasero** [comment]
I am having a hard time justifying this support. This will cause tons of issues with existing themes that define a color. Sorry, will go ahead and close.

**Comment by michaellopez** [comment]
@bpasero How unfortunate. I can of course see your point of issues with existing themes, but in my opinion you would give priority to the plugin using the API and if that messes with the theme the user would need to bug the plugin author, disable the plugin or stick with the situation (as is normal for something with a plugin/theme architecture when there are conflicts). Any respectable plugin author would of course hide this new "color the statusbar" functionality behind a plugin option that can be toggled by the user, nothing would change if the user did not opt in in those cases.

Its very close to the argument had with tokenizers and themes that do not color some tokens etc. Many things have poor interoperability, and users weed out the plugins that do not work together or the plugin authors fix/improve interoperability (whatever that may be). I'm still +1 on this, I don't think one should hinder advancements when there is a proper "upgrade path"/"opt in" approach that mitigates the badness.

**Comment by bpasero** [comment]
I think my preferred solution for getting there is to introduce dedicated accentuated colors for the status bar that we provide in VSCode and that theme authors can implement (similar to todays colors we have for empty workspace vs. folder workspace vs. debug state).

We can then provide an API where extensions can enable such a color. We would still have to figure out if that choice overrides our built in accentuated colors or not.

Btw I am not asking for a PR for this but if I had to implement this feature I would probably lean towards that solution. 

@michaellopez PS: an extension can always set the status bar color as setting which will override any theme color. So even today already you can conditionally change the color of the status bar as you like from your extension.

**Comment by michaellopez** [comment]
@bpasero You mean as @AdrieanKhisbe described above (https://github.com/VSCodeVim/Vim/issues/2021#issuecomment-465729996)? Or something else? I'm looking for dynamic support without the overhead of writings settings because its slow, as described by OP. I can settle for predefined colors for my use case, but it feels limited.

**Comment by bpasero** [comment]
Yeah I was referring to that approach. It is true that it needs a write to the settings file but I would not assume that this is slow. You can avoid a diff in the workspace by writing the state globally and not inside the workspace.

**Comment by xconverge** [comment]
I am considering removing airline (status bar color changing) support from VSCodeVim because of how bad it currently is. I am torn between really annoying quite a few people and waiting for something more performant. This would have been really great for our specific use case. https://github.com/VSCodeVim/Vim/issues/3868

**Pull request closed without merging**
