### PR TITLE
Show extension origin in `source` column of keybindings GUI

### LINKED ISSUE #37034: Improve keybindings.json UI to show extension changing the shortcuts in `Source` column
When you enabled a keymap extension https://github.com/k--kato/vscode-intellij-idea-keybindings , that changed the default shortcuts. But on the keybindings.json UI, it always shows "Default" for "Source" column. It's misleading

- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install an extension: https://github.com/k--kato/vscode-intellij-idea-keybindings
2. Open Keyboard Shortcuts UI
3. To check the key changed by above plugin. It's all "Default" for "Source" column

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #37034

This PR adds Extension column to keybindings editor.

demo

It's still possible to distinct User/Default origin of command/keybinding and at the same time to see if it was contributed by an extension.

- [x] Size is not that big `flex: 0.3`
- [x] `title` attribute is specified to be able to fully see name of the extension
- [x] Search works for the column
- [x] All contributed commands/keybindings have Extension specified
- [x] Built-in extensions excluded

It was taking > 1second to load on editor startup if the code was inside `KeybindingsEditorModel.resolve()` so it's living in the separate function that runs after.

If you have a better way of obtaining extensions list (with contributions commands & keybindings), I'll update PR.

### CODE REVIEW

**Comment by Astrantia** [comment]
@usernamehw this is great, but the view is cluttered now. What about adding a checkbox somewhere to show Extensions too?

**Comment by usernamehw** [comment]
@Astrantia I think it should be done as a generic way of hiding columns.

**Comment by sandy081** [comment]
@usernamehw I do not think adding a new `Extensions` column is a good idea. Because by default this column will be empty for all core keybindings which makes unnecessary spacing for this column.

How about adding a third dimensions to `Source`?

- Core / Built-in
- Extension Name
- User

**Comment by usernamehw** [comment]
@sandy081 It can now have 4 states:

* Default - core
* User - core assigned by user in `keybindings.json`
* Extension - extension contributed
* User ⮜ Extension - extension contributed & assigned by user in `keybindings.json`

**Comment by sandy081** [comment]
@usernamehw Thanks for considering. I would still think 4 is too many states to get confused. I would have following

- Built-in (This keybinding is defined by VS Code)
- ${Extension Name} (This keybinding is defined by extension)
- User (This keybinding is defined by User)

W.r.to commands - Show Default / Show User - change the syntax to `@default` and `@user` respectively.

**Comment by usernamehw** [comment]
Display name from extension often have spaces in it so there's 2 regex checks:

* First matches if extension is inside quotes: `@source: "sublime text" add`
* Second matches without quotes: `@source: subl add`

Both are valid and searching for case-insensitive substring (not for a complete match).

`@user`/`@default`/`@source:user`/`@source:default` still work.

**Comment by usernamehw** [comment]
This needs more tweaking. Only comparing command is not enough ... have to compare keybindings also.

screenshot 48

Selected rows should have `default` source.

**Comment by sandy081** [comment]
@usernamehw I would go for following

`@default` Shows all default keybindings
`@user` Shows all keybindings from user
`@extensions` Shows all keybindings from extensions
`@extensions:extensionId` Shows all keybindings from extension with given extension id. Eg: `@extensions:dbaeumer.vscode-eslint`

Let me know once you are ready with the changes

**Comment by usernamehw** [comment]
I will likely return to this somewhere this month (March 2019). If not - anyone is welcome to take over the PR.

**Pull request closed without merging**
