### PR TITLE
Refresh explorer view after loading all package.json of extensions.

### PR DESCRIPTION
**Pull request by featherJ**
Make sure that the operation of open editor is done after the package.json of extensions is loaded. This can allows all of the editors and inputs can use the mimetypes defines in extensions.

### CODE REVIEW

**Comment by bpasero** [comment]
@featherJ can you first tell what the problem is you are trying to solve? we should not wait with any UI until the extension host is up and loaded because that can be slow.

**Comment by featherJ** [comment]
@bpasero A mimetypes can defines in a package.json of languages extension. But the editor in vscode can not use it. If i write a new editor for an known mimetypes defines in extension, I must also use  'modesExtensions.ModesRegistry.registerLanguage' to register this mimetypes again.  I think it's not necessary to repeat the definition for a same mimetypes. So, if you think I'm not doing it right, maybe we should do something similar in other places.

**Comment by bpasero** [comment]
@featherJ do you have a concrete example?

**Comment by featherJ** [comment]
https://github.com/featherJ/vscode-testmime This is a test language extension to define a new mime in package.json.  In the MainThreadModeServiceImpl, the `text/testxml` mimetypes has been registered to the ModesRegistry.

But the registration process is ran after the FileController initialization. So in the `openEditor` of `FileController`, vscode can not get the right mimetypes in `stat`:


Only if I register a languageExtensionPoint again in vscode:
,i can get the right mimetypes.

**First:**
I think it's not necessary to repeat the definition for a same mimetypes both in extensions and vscode.

**Second:**
`MainThreadModeServiceImpl` has registered the language extensions.  Then it should play a bigger role.

**Comment by bpasero** [comment]
@featherJ can you take your comment and report it as a bug? I would always expect that extensions are being honoured when finding out which mode to pick up.

I would believe this should be fixable without changing the way the explorer works.

**Comment by bpasero** [comment]
@featherJ I am closing this because I do not understand the issue from your description. I think you got confused by the concept of mime types in VS Code. this concept is actually something to get rid of (see https://github.com/Microsoft/vscode/issues/3832) in favour of language IDs. We only have mime types in the extensions due to this debt, but otherwise do not use them.

**Pull request closed without merging**
