### PR TITLE
Edited the space between the status bar items

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes ##145852
I appreciate feedback if something is missing.

### CODE REVIEW

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
Thanks for the PR, not sure if you have tested this locally but it appears to overwrite all of our icon font styles:

CleanShot 2022-03-29 at 13 00 53@2x

CleanShot 2022-03-29 at 13 01 35@2x

**Comment by najmiehsa** [comment]
@misolori I tried to do the tests locally after this review. However, I wasn't quite successful with that. 
https://github.com/microsoft/vscode/wiki/Smoke-Test

The only way to target the space before the element is by using the *before* pseudo-selector. The only other alternative that comes to my mind is to change the class name here. 

``.monaco-workbench .part.statusbar > .items-container > .statusbar-item  span.codicon-mark-github::before {
	content: " ";
	white-space: pre;
}``

Again this may cause overwriting of other contents as I was not able to do the test locally.  

If this is the right direction to go, then I can definitely work on the issue otherwise I don't have other suggestions or solutions at the moment.

**Comment by misolori** [comment]
Unfortunately that isn't a scalable solution as an extension can add multiple icons next to each other so it's not specific to this one use case. So we'd need a more generic solution here.

**Comment by najmiehsa** [comment]
@misolori Is it possible to close this PR so that the issue remains open for others to contribute? Thank you.

**Pull request closed without merging**
