### PR TITLE
Add git stashing

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Addresses https://github.com/Microsoft/vscode/issues/1904 which is one of the oldest and most upvoted issues.

Adds 3 new commands for git integration:
* `git stash`
* `git stash pop` using latest stash
* `git stash pop` with choosing stash

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
CC: @joaomoreno

**Comment by joaomoreno** [comment]
@Krzysztof-Cieslak We don't really need to have the stashes in the model itself. This will just make git status slower since we'd need to call git once more in order to get the stashes. You can just make this call once one of the stash actions runs. Can you fix that/

**Comment by Krzysztof-Cieslak** [comment]
Yes, I'll  rebase and fix it.

**Comment by Krzysztof-Cieslak** [comment]
Ready to review again.

**Comment by joaomoreno** [comment]
@Krzysztof-Cieslak 

These changes are not formatted and violate some linting rules we have set. We have configured a git pre-commit hook to validate these for you, which gets set up when you run `./scripts/npm.sh install`. You were only able to commit by not running that or by commenting out the pre-commit hook. Next time, please commit while running through these rules. I've fixed those issues for you on this one.

Also, [this](https://github.com/Microsoft/vscode/pull/29138/files#diff-5d140a7159e83bdc81a4efdf806b8cd6R578) goes into infinite recursion. Next time, please run your changes before handing them over to us.

Also, [this condition](https://github.com/Microsoft/vscode/pull/29138/files#diff-e64cb2761ab71b6db409f7e3fb804b14R851) will fail when index is zero.

Also, I've added functionality to provide a stash message when stashing changes.

**Comment by Krzysztof-Cieslak** [comment]
Sorry for the trouble @joaomoreno, I haven't paid enough attention to this PR, indeed.  My bad :(

**Pull request merged**
