### PR TITLE
Fix wrong matches in multiline file search

### LINKED ISSUE #131507: Ctrl+Shift+F with regex show wrong results
Issue Type: <b>Bug</b>

1. Open folder which contains only one file `main.cpp`:

```c++
#include <iostream>
#include <string>
```

2. Close all files and search all files using regex `#include\s*<\w+>`, show the following result which is wrong:
```
#include <iostream>
#include <iostream>
```

3. Open `main.cpp` and search again, show correct result:
```
#include <iostream>
#include <string>
```

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.27GB free)|
|Process Argv|--crash-reporter-id 9f97c5f0-6cf3-4b21-a725-c5b519b77ecd --crash-reporter-id 9f97c5f0-6cf3-4b21-a725-c5b519b77ecd|
|Screen Reader|no|
|VM|0%|
</details>

https://user-images.githubusercontent.com/8402260/130623045-73774549-b01f-4b02-a393-e7b7a4225e38.mp4

### PR DESCRIPTION
**Pull request by bvschaik**
When multiple consecutive lines match a regular expression, RipGrep will return them  as one match with multiple submatches. The parser that converts the absolute positions of the submatches to (line number, column number) pairs was not taking into account that `inBetweenChars` may contain newlines, leading to wrong matches, and search/replace actions that gave unexpected results.

Fixes #131507

### CODE REVIEW

**Review by roblourens — COMMENTED** [review]
This looks great, thanks for investigating this. re: your comment about tests, I agree that we should add a test, and I do see tests for the class in ripgrepTextSearchEngineUtils.test.ts. This is testing the whole parser end to end, I think you should be able to construct the right input and test that it gets parsed correctly.

**Comment by bvschaik** [comment]
Thanks for the pointer, I totally overlooked those tests.

I have added two tests:
- multiple submatches without newline in between: already succeeds on main
- multiple submatches with newline in between: fails on main, succeeds with my changes

**Review by roblourens — APPROVED** [review]
Thanks!

**Review by andreamah — APPROVED** [review]
Thanks for the contribution 🙂

**Pull request merged**
