### PR TITLE
Fix quick pick message size

### LINKED ISSUE #73345: Quick input has some extra height pixels
This quick input looks strange, it's a bit too high:

image

You can get it by running `Git: Create Branch`

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #73345

### CODE REVIEW

**Comment by alexr00** [comment]
Stable on the left, running from source on the right:
image

**Comment by alexr00** [comment]
Warning message:
image

**Comment by chrmarti** [comment]
The second horizontal red line should align with the OK button vertically (like the first horizontal red line). The warning message looks like it's not well centered vertically, is it different from the input box's text?

**Comment by alexr00** [comment]
Without red border:
image
With red border:
image

I drew a line and made sure they line up now :)

**Review by chrmarti — APPROVED** [review]

**Pull request merged**
