### PR TITLE
Clean up server-main.js

### LINKED ISSUE #160015: Errors in `server-main.js`
image

### PR DESCRIPTION
**Pull request by aeschli**
Fixes #160015

Removes `--pick-port`. Deprecated for a year and I checked that the remote extension sdon't use it anymore.

### CODE REVIEW

**Comment by aeschli** [comment]
@alexdima Check out my fix for storing the `_remoteExtensionHostAgentServer`. I assume we still need this.

**Review by alexdima — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
Hello @aeschli @alexdima
With this patch merged, `server-main.js` ignores the `--port` argument.
That's expected considering https://github.com/microsoft/vscode/pull/160094/files#diff-f04c4484e826ffa3dbc332a191ee94458e77edd1399cd5ebbbd6bf40e95c2450L195-R196

Could you please take a look at it?
Thanks in advance!

**Comment by aeschli** [comment]
Oh, you already made a PR, thanks!

**Comment by azatsarynnyy** [comment]
Thank you @aeschli for looking at it!
I forgot to mention the link to my PR https://github.com/microsoft/vscode/pull/161254

**Pull request merged**
