### PR TITLE
update docs on fs provider for mtime

### PR DESCRIPTION
**Pull request by bpasero**
cc @joaomoreno

### CODE REVIEW

**Review by jrieken — APPROVED** [review]
:ship: it

**Comment by jrieken** [comment]
Looks like @joaomoreno didn't copy from the sample: https://github.com/microsoft/vscode-extension-samples/blob/master/fsprovider-sample/src/fileSystemProvider.ts#L98

**Comment by bpasero** [comment]
I wonder how many extensions do this wrong. In theory we may consider to introduce a way for an extension to bypass the checks the workbench does. Though on the other hand, you can only get the best experience if you provide these values properly.

**Comment by jrieken** [comment]
While sampling some providers I noticed that the majority are offsprings from the memfs-sample. That gives me high hopes but the possibility is there. We could so some logging like: "received file event but stat for foo:///ffff/file.txt didn't change."

**Pull request merged**
