### PR TITLE
replace settings variables in debugger config #8042

### PR DESCRIPTION
**Pull request by DonJayamanne**

### CODE REVIEW

**Comment by isidorn** [comment]
@DonJayamanne thanks for the PR however we are currently in the endgame. So I will review this first week of july -> july milestone

**Comment by DonJayamanne** [comment]
Cheers

**Comment by DonJayamanne** [comment]
@isidorn , I'll resubmit a pull request for this later today. Closing this as there were some problems in the way I created the changes at my end.
Also, there are some more changes to be made:
- Error handling
- Tests

**Comment by isidorn** [comment]
Great - looking forward to the PR. Thanks!

**Pull request closed without merging**
