### PR TITLE
fix: notify windows 7 support eol

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode-internalbacklog/issues/3119

### CODE REVIEW

**Comment by dzienisz** [comment]
Great PR, just add translations to file.

**Comment by bpasero** [comment]
Easier somewhere here: https://github.com/microsoft/vscode/blob/933c22a53f8450f56e12d5f468f633b86f0f12ee/src/vs/workbench/electron-sandbox/window.ts#L623-L624

And maybe using `INativeWorkbenchEnvironmentService.os.release`. And maybe using `productService.nameLong` instead of hardcoding VSCode.

**Review by bpasero — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]

**Comment by fireattack** [comment]
Will it still auto-update to 1.71 (and therefore broken) for Win7 users?

**Comment by deepak1556** [comment]
Nope, windows 7 users received the final update yesterday which is `1.70.3` which includes the above notification and it will not receive further version updates.

**Comment by infinnie** [comment]
> Nope, windows 7 users received the final update yesterday which is `1.70.3` which includes the above notification and it will not receive further version updates or auto-update to any newer version. Basically, it won't auto update to the broken version.

Could you please also include a documentation on this Windows 7-specific version in some easy-to-find way?

**Comment by gregvanl** [comment]
Added mention of 1.70.3 Windows 7 only release with https://github.com/microsoft/vscode-docs/commit/968ca6284b58fc5994ffa9797fbf246f8388a340

**Comment by lorand-horvath** [comment]
Instead of dropping support for Windows 7, someone could just fix Electron 19 on Windows 7 and VSCode would still be working... https://github.com/electron/electron/issues/35219

**Pull request merged**
