### PR TITLE
Adopt EnvironmentVariableCollection in git ext

### LINKED ISSUE #184331: Adopt EnvironmentVariableCollection.description in git extension
There's a new API (https://github.com/microsoft/vscode/issues/171108) being finalized this month that allows extensions to explain why it's changing environment variables. Adopting this will show additional information when hovering a terminal tab

API:

https://github.com/microsoft/vscode/blob/e6936ce0ab10bc9fb3ec220db3c4304bdd909292/src/vscode-dts/vscode.proposed.envCollectionWorkspace.d.ts#L27-L33

Current:

image

After description:

image

cc @karrtikr

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #184331

image

### CODE REVIEW

**Comment by lszomoru** [comment]
Thanks for the PR. I think that:
1) We should localize this string
2) It should be more generic as the functionality also depends on various settings (ex: `Git: Enables git experiences in the integrated terminal`

**Comment by Tyriar** [comment]
Opps forgot to localize. 

> It should be more generic as the functionality also depends on various settings (ex: Git: Enables git experiences in the integrated terminal

Could we be more explicit here and tailor strings for each set of values? "git experiences" is very mysterious still. I see git editor which I understand but is the IPC Server one only used for askpass or?

**Review by 0x4248 — APPROVED** [review]

**Comment by Tyriar** [comment]
I improved the message but I'm not sure how to do localization in an extension, I've never done it before and I don't see existing examples in the git extension used outside of the package.json?

**Comment by lszomoru** [comment]
Localization sample - https://github.com/microsoft/vscode/blob/70daab796e44df766e652ccb6ba9b6997aeb46e4/extensions/git/src/commands.ts#L52-L53

**Review by lszomoru — APPROVED** [review]

**Pull request merged**
