### PR TITLE
Add 'Fuzzy Match' toggle to tree find widget (#116286)

### LINKED ISSUE #116286: Tree: Support continuous find
Issue Type: **Feature Request**

Hi,

in a list of files I can filter them by start typing the name of the file. It is a super useful feature when you have hundreds+ files.
My issue is that the filter is trying to find the letters in the whole file name. 
Here is an example search for word "file":

* this-is-**file**-i-looked-for.jpeg (I expect this to be returned)
* **f**or-th**i**s-**l**.jp**e**g (This should not be returned, it is only a random match)

Would it be possible to add there extra settings to only returns full strings matches? Or is there some setting already buried somewhere?

Thanks a lot for all the work on awesome editor.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR resolves #116286 by adding a <strike>'Match Whole Word'</strike> 'Fuzzy Match' toggle button to the tree find widget.

(icon updated after feedback)
junk

This is particularly useful in filter mode.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@lramos15 you might have an opinion about this.

**Comment by lramos15** [comment]
> @lramos15 you might have an opinion about this.

It's also a bit weird that this doesn't work the way the editor does so we're overloading the behavior of the same icon which can be a bit confusing. I understand this is trying to do contiguous matching vs non-contiguous matching, but in the editor that button actually looks for separate words instead. I'll leave it up to @joaomoreno since this affects the whole tree

**Comment by gjsjohnmurray** [comment]
@lramos15 good point. Looks like I should use the [`search-fuzzy`](https://github.com/microsoft/vscode-codicons/issues/132) icon and invert the sense of the toggle.

Perhaps also let users set the default state of the toggle like they already can for the filter/highlight toggle.

**Comment by gjsjohnmurray** [comment]
I have changed the icon and added a `workbench.list.defaultFindMatchType` setting. Also did some renaming in the code.

**Comment by gjsjohnmurray** [comment]
Can this be considered for merging before endgame?

**Comment by joaomoreno** [comment]
This wasn't working if the substring was found at position zero, pushed a fix.

Thanks for the PR, and apologies for the delay @gjsjohnmurray! Happy new year! 🍻

**Review by joaomoreno — DISMISSED** [review]

**Review by bpasero — DISMISSED** [review]

**Review by joaomoreno — APPROVED** [review]

**Review by bpasero — APPROVED** [review]

**Pull request merged**
