### PR TITLE
Add region markers folding for Go

### PR DESCRIPTION
**Pull request by c0m3tx**
Add region markers for folding Go code

```
// Region regionName

// EndRegion
```

### CODE REVIEW

**Comment by aeschli** [comment]
Is `// Region ` already commonly used in Go? We typically use `// #region`

**Comment by c0m3tx** [comment]
@aeschli I tried to stay close to common Go syntax. # symbol is not used in the language AFAIK, but capitalized words are.

**Comment by aeschli** [comment]
Also not inside a comment? the `#` avoids that comments starting with the word 'Region' trigger a (incomplete) folding range
@ramya-rao-a Can you advise?

**Comment by c0m3tx** [comment]
@aeschli what do you mean with "Also not inside a comment?" ?

I think that adding a foreign character in Go code may look strange, but if you think it would be better it's fine for me ofc :+1:

**Comment by aeschli** [comment]
I'm just trying to understand, I'm a 'Go' novice. In the languages I know, comments can contain any character or symbol (maybe except for the comment end token). @ramya-rao-a is our Go expert. Let's wait for her input.

**Comment by c0m3tx** [comment]
Ah ok I see! No, there is no issue with # characters in comments, they are totally fine.

**Comment by aeschli** [comment]
To be consistent with the other range markers, I updated the markers to `// region`, `// endregion` and  `// #region`, `// #endregion`

**Comment by c0m3tx** [comment]
Thank you @aeschli !

**Pull request merged**
