### PR TITLE
Centered layout with fixed center view width

### LINKED ISSUE #54731: Give the option to fix centered layout width.
Previously the centered layout in zen mode had a fixed width, meaning that if you resize the window the centered section will remain the same as long as it still fits in the resized window. The behaviour now is for the centered section width to be proportional to the size of the window. See below:

image

On resize, old behaviour/new behaviour:

image

### PR DESCRIPTION
**Pull request by quhsi**
This PR fixes #54731.

When having the *Centered Layout* activated, previously the width of the center view would scale proportionally with the editor area width. This PR changes the behavior so that there is a target width stored for the center view and this width is kept as long as it fits into the editor area. This behavior should make it unnecessary to manually resize the center view when the editor area width changes e.g. when toggling panels or resizing the whole window.

The minimum size of the margin views is set to 3px so that it is possible to grab the separators with a mouse even when the center view fills the whole editor area.

The target width is restored between restarts.

How to test: manually

### CODE REVIEW

**Comment by quhsi** [comment]
@isidorn Can you please reconsider your requirement of having the centered layout editor width scaling behavior configurable in view of my comments?

**Comment by EPonyA** [comment]
> The one missing part is that this should be an option. We do not want to change the default behavior which most of the users are happy with.
I don't think most users are necessarily happy with the current default behavior. I think most users simply use line wrapping (as I do), or don't write lines longer than their panel so often that this is a significant issue for them. But I see no way that this isn't an improvement in design, personally.

**Comment by isidorn** [comment]
Closing as my original comments have not been addressed and I am not sure if we want this a part of vscde code.

**Comment by quhsi** [comment]
@isidorn I regret that you did not find the time to either react to our 
comments or clarify your position and instead blocked our efforts by 
closing the request. Note that probably everyone of us intends to make 
the best out of the software.

Am 05.11.20 um 15:46 schrieb Isidor Nikolic:

**Comment by Gameghostify** [comment]
Why was this closed? This implements a long awaited feature request (or even fix, because seemingly noone requires the viewport to scale?) and it would be awesome to have

**Comment by jan-scorl** [comment]
This would be a great addition but I also see @isidorn perspective that it should be an option instead of a default. @quhsi What's your objection to making it an option in settings?

**Comment by quhsi** [comment]
@jan-scorl As I said, I don't see any benefit of the default behavior and thus I see no use in an option, except for getting this PR through. Furthermore, making that configurable would increase the software complexity, meaning more possibilities for introducing bugs, and making it harder to maintain (than it already seems to be, when considering the duration of the resolution of long-standing bugs).

If you are willing to add an option you could fork my PR repository.

12.11.2020 08:53:28 Jan <notifications@github.com>:

**Pull request closed without merging**
