### PR TITLE
Provide an option to insert a final newline (fixes #1666)

### LINKED ISSUE #1666: Provide an option to insert a final newline
Something similar to  `insert_final_newline = true`.

### PR DESCRIPTION
**Pull request by bpasero**
My attempt to introduce a new save participant for adding a final new line at the end of the file unless:
* the file does not contain more than one line
* the last line is already whitespace

The only corner case I was not sure how to solve is that the cursor jumps to the last line when you save while you are on the last character of the previous line.

/cc @alexandrudima

### CODE REVIEW

**Comment by jrieken** [comment]
Unsure if we should add this to VS Code, there are already [insert-final-newline](https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline) and the [editorconfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)-extensions that do exactly this. The former even uses the same setting..

**Comment by bpasero** [comment]
@jrieken I noticed that Sublime for example provides this out of the box, I think we should too. It goes well together with the trim trailing whitespace setting imho. 

There is 11 votes on https://github.com/Microsoft/vscode/issues/1666 so I am not sure if people would expect this in the product or not.

**Comment by jrieken** [comment]
Not my call - I am always in for extensions and a lean product. But I'll leave it up to the PMs

**Comment by bpasero** [comment]
@egamma @chrisdias @seanmcbreen the question is wether we want to introduce a new `files.insertFinalNewline` setting or rely on people to install extensions for this. I verified that both ST and Atom ship with this feature out of the box without any extension need.

I still think editorconfig has a very valid use case because it allows you to scope this setting per file type.

**Comment by bpasero** [comment]
Also @kieferrm fyi

**Comment by octref** [comment]
Atom has a [whitespace](https://github.com/atom/whitespace) package and I do miss the feature.

image

Seeing inconsistency of line-ending in the PR is also a bit annoying.

**Comment by bpasero** [comment]
@octref well I think we could only solve that by also having an option to trim trailing new lines at the end of a file which this setting does not cover.

**Pull request merged**
