### PR TITLE
Debug picker: consider to show a gear icon to configure config

### LINKED ISSUE #92378: Debug picker: consider to show a gear icon to configure config
Compare with tasks:

image

I wonder why debug does not have this action:

image

With the new quick access, this is trivial to add and I would only add it there since we go with it soon. Here is how tasks does it, I literally just need the code to configure a debug config:

https://github.com/microsoft/vscode/blob/cb361ac3a4d9a4fee8443690cdf98efd4f4af626/src/vs/workbench/contrib/tasks/browser/tasksQuickAccess.ts#L128-L136

Challenge is there seems to be 2 entries in debug quick open:
* `ILaunch`
* config `{ launch: ILaunch, name: string, presentation?: IConfigPresentation }`

### PR DESCRIPTION
**Pull request by bpasero**
fixes #92378

This PR fixes #

### CODE REVIEW

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
Good enough for now. Would be cool if it opened on the exact lineNumber that the `configuration` is on.
WIth this approach it just opens on the first line.

**Comment by isidorn** [comment]
Currently it would not open the correct config because it always opens the focused config.
So the issue would be: have config A focused in the debug dropdown, open quick pick and trigger your action on config B. Config A would get opened.

**Comment by bpasero** [comment]
@isidorn how is the configure action doing it then in the debug viewlet? isn't that one focusing on the correct line depending on what is selected in the dropdown?

**Comment by bpasero** [comment]
> Currently it would not open the correct config because it always opens the focused config.
So the issue would be: have config A focused in the debug dropdown, open quick pick and trigger your action on config B. Config A would get opened.

Sorry I do not understand, it seem to open the correct file for me.

**Comment by isidorn** [comment]
@bpasero it opens the correct file, but not the correct **line number**. If the launch.json has 1000 lines this can be a pain. Try VSCode repository as a good example.
Also when I try this out with this PR the gear icon is actually not rendered, am I missing something?

**Comment by bpasero** [comment]
I added this via https://github.com/microsoft/vscode/commit/b8c1023dd8114b8821c28ce558634fe8c0f5d04d and filed https://github.com/microsoft/vscode/issues/92437 as follow up.

**Comment by isidorn** [comment]
@bpasero great, thanks

**Pull request closed without merging**
