### PR TITLE
Keep the hover open when the alt key is pressed

### LINKED ISSUE #151763: when hovers are not sticky, alt/opt key should make them temporarily sticky
Version 1.68 introduced the feature of holding the ALT (OPT on Mac) key down in order to make hover texted locked so that you can move the text over it, and then magnify, select text, etc. from the hover. But then this:

> Note that this feature only applies outside of the editor because editor hovers can always be moused over unless specified otherwise via the editor.hover.sticky setting

Setting 'editor.hover.sticky' to false is very good at preventing accidental clicks on a popup hover text, when you really mean to click on the line above the thing causing the hover (sometimes the hover text shows up at exactly the wrong time, and then you end up going to MDN or Can I Use, etc.). I would like it if I could keep 'editor.hover.sticky' as false, but press the ALT or option key down during a hover for when I actually do want to click on the link in the hover text, or when I do want to zoom in on it or copy something from it.

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/151763

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
The hover lock feature also changes the border width and should work on keydown/up, not just mousemove. Here's an example of the workbench hover:

Recording 2023-12-05 at 06 13 14

Docs for the feature: https://code.visualstudio.com/docs/editor/accessibility#_hover-accessibility

**Comment by aiday-mar** [comment]
So from the GIF is the following understanding correct?

- When alt/opt is pressed, the border becomes thicker. 
- When you click on the hover, the border resets and becomes thick in an alternative manner

I was wondering why the border changes thickness when you click on the hover. Does clicking on the hover while alt is pressed change something?

In the case of the hover, the border is a bright blue color. I am wondering if we want to thicken the border given its bright color (may look a bit too visible)?

Screenshot 2023-12-05 at 15 29 32

**Comment by Tyriar** [comment]
@aiday-mar I didn't click in the gif, clicking just focused the element but doesn't change rules around hiding. For workbench hover the focused border overrides the lock border currently. I think we considered making it thicker but it looked out of place.

**Comment by aiday-mar** [comment]
I see. For the editor hover, we previously decided that when the hover is focused, it prevents the hover from disappearing on mouse out. I think we should keep this feature. I'll make the border thicker on pressing alt.

**Review by Tyriar — APPROVED** [review]
Haven't tested and not too familiar with editor hover, but lgtm

**Comment by aiday-mar** [comment]
This PR will be reverted because unfortunately I introduced a regression in here and I should make a check that only alt key is pressed (meaning verify that it is not part of a chord)

**Pull request merged**
