### PR TITLE
Added background ANSI colour codes

### PR DESCRIPTION
**Pull request by danielfrankcom**
Discussed in #47457.

Due to the fact that the previous changes are not yet on master, I couldn't figure out a way to isolate the relevant changes in this pull request. Focus on the changes in commit a253dae, as the other commit is captured in pull request #49763.

### CODE REVIEW

**Comment by isidorn** [comment]
@danielfrankcom thanks a lot for this PR, let's first merge in the previous one and then we can add this one easily.

**Comment by isidorn** [comment]
@danielfrankcom since we have merged the other PR we could look into this one now.
Though I guess it needs to be updated to be on top of the latest changes we just merged in.
Pushing this to june since there is no rush for this

**Comment by danielfrankcom** [comment]
Yeah I'll need to rebase it, but everything should still work. I'll add the background colour codes to the unit tests too, since it should be relatively easy.

**Comment by isidorn** [comment]
Sounds good, thanks a lot!

**Comment by isidorn** [comment]
This looks good, let's merge it in.
Thanks a lot!

**Pull request merged**
