### PR TITLE
add editor.action.undoAddSelection

### LINKED ISSUE #6872: Add reverse command for addSelectionToNextFindMatch
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.4

I know WebStorm does this, but I don't know about other editors. I find it really useful to be able to undo the last selection when using `cmd+d` to select words. It's common to accidentally select one too many words, and then having to start all over.

I'd propose the name `addSelectionToNextFindMatchReverse` for clarity and to make it easily relatable.

I'll try to work on a PR myself unless somebody else wants this more than I do and does it before me 😃

### PR DESCRIPTION
**Pull request by Merott**
Closes #6872

### CODE REVIEW

**Comment by Merott** [comment]
I'm not sure what to make of the failed AppVeyor build. I don't see the cause of the failure. How am I supposed to fix that?

**Comment by alexandrudima** [comment]
I'm sorry I also don't know, @bpasero @joaomoreno How does one see test failures in appveyor?

image

**Comment by Tyriar** [comment]
Might be flakiness? I retried the build.

**Comment by Merott** [comment]
@Tyriar It has failed a few times already, consistently. There are some errors near the top of the logs, but I'm not sure if they have anything to do with the build failure:

screen shot 2016-05-27 at 22 20 48

**Comment by joaomoreno** [comment]
I know @bpasero once got those errors to show up.

**Comment by bpasero** [comment]
No, don't think so.

**Comment by joaomoreno** [comment]
@Merott those errors are OK, they come from an optional dependency, which should not install on Windows.

@Tyriar @alexandrudima The way I remember @bpasero was able to see errors was running with the `ELECTRON_NO_ATTACH_CONSOLE` environment variable set to `1`.

**Comment by alexandrudima** [comment]
I am sorry, I am having a very difficult time to motivate this addition, given `cursorUndo` (`ctrl+u` on windows) covers this case and many more

**Pull request closed without merging**
