### PR TITLE
add emmet support for .erb and .php files

### PR DESCRIPTION
**Pull request by mahmoudymy**
and treat them like html

### CODE REVIEW

**Comment by egamma** [comment]
Makes sense, thanks!

**Comment by LKorowicki** [comment]
Same for php template files, e.g. "*.twig"

**Comment by egamma** [comment]
Thanks, added `.twig` files to be treated as `html`. Thanks.

**Comment by PudparK** [comment]
New to GitHub. Can I use this to add emmet support for erb files? If so how?

**Pull request merged**
