### PR TITLE
Add option to restore commit template on every git.refresh 

### LINKED ISSUE #75651: Git commit template should be restored automatically (not only on commit)
## Background
In #39048, @joaomoreno says about the command `git.restoreCommitTemplate`:

> I don't think it's a command worth putting in the command palette. Seems to be very specific for users who actively modify .gitmessage, doesn't happen often.

This might be true, but there are definitely more actions (than just `commit`) where it would make sense to read the git commit template, because if you know what you can do with this, this is so damn useful. :)

## Problem:
Personally, I use the git commit template to follow our team's git commit message and branch naming conventions, which says that the commit message and the branch you are working on have to be prefixed with the id of the corresponding Jira issue.

So I created a git hook for writing the recently used commit message into the commit template on `post-commit` and also a hook on `post-checkout` to write the current branch name (title-cased) into the commit template when I create a new branch.
:heavy_check_mark: When I commit something, the git commit template updates and the last commit message stays in the scm message box.
:negative_squared_cross_mark: But in order to get the updated content from that template after a `git checkout`, I have to invoke `git.restoreCommitTemplate`.

Temporarily [I could fix this](https://gist.github.com/dmstern/d02ea41d4b0171ff2f4661daaa3e3f86) with a macro extension and mapped the `workbench.view.scm` keyboard shortcut to my new macro, which does both (`git.restoreCommitTemplate` and `workbench.view.scm`). But (a) this works only with this shortcut, not if I click on the scm icon in the activity bar and (b) I think this behavior should be possible without an extension.

## Possible solution:
Please invoke `git.restoreCommitTemplate` every time `workbench.view.scm` is invoked or on every [`git.refresh`](https://github.com/microsoft/vscode/blob/4e7545ba8a536237387848e2b8220d2b562ae041/extensions/git/src/commands.ts#L237)

### PR DESCRIPTION
**Pull request by dmstern**
(fixes #75651)

~~@joaomoreno unfortunately, I couldn't figure out how to set up the local development environment for building and testing the change.~~
~~Could you please review and test it? Or should I first solve my installation problems?~~

~~Thanks!~~

**Edit:**
I tested my changes and modified it a bit so that it works now as I would expect it:

* There is a new setting `git.restoreCommitTemplateOnRefresh`, which defaults to `true`.
* If this setting is set, the manually triggered command `git.refresh` also triggers the restoring of the template.
* If also `git.autorefresh` is set, the template gets restored automatically.

I would appreciate if you could now review my changes. :)

### CODE REVIEW

**Comment by joaomoreno** [comment]
@dmstern Make sure you can run out of sources and try this out yourself. https://github.com/microsoft/vscode/wiki/How-to-Contribute Let me know if you hit issues.

**Comment by dmstern** [comment]
@joaomoreno Thanks for your answer and link to the instructions.
After a bit more struggling with nodeJS versions and error messages, I finally got it up and running.
I tested my changes and modified it a bit so that it works now as I would expect it:

* There is a new setting `git.restoreCommitTemplateOnRefresh`, which defaults to `true`.
* If this setting is set, the manually triggered command `git.refresh` also triggers the restoring of the template.
* If also `git.autorefresh` is set, the template gets restored automatically.

I would appreciate if you could now review my changes. :)

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I don't think this should be enabled by default since the user can type a nice commit message, then a file system change happens and the commit message gets thrown out in favor of the template.

Do you have any ideas how to fix that?

If not, I'll just merge this and disable the setting by default.

**Comment by dmstern** [comment]
Hi @joaomoreno,

thanks for reviewing! Maybe we could detect user changes in the commit message input field and disabling the restoring for this "touched/dirty" state? 
If you could give me hint, if and how something like this is possible, I could try to implement it.
Otherwise, I'm okay with your suggestion to disable the feature by default.

**Comment by joaomoreno** [comment]
> Maybe we could detect user changes in the commit message input field and disabling the restoring for this "touched/dirty" state?

Well, the input is dirty if it does not match the template message (which is the empty string when there's none). But if the input already matches the template message there's nothing for you to do. There appears to be no easy way out of this but to hide the feature behind a setting.

**Comment by dmstern** [comment]
> There appears to be no easy way out of this but to hide the feature behind a setting.

Ok, thanks! Then let's set the default value for `git.restoreCommitTemplateOnRefresh` to `false`.

Do you change it?

**Comment by dmstern** [comment]
@joaomoreno I updated the default value of the new setting to `false`. 

Could you please review again?

**Comment by dmstern** [comment]
Obsolete, due to another fix: https://github.com/microsoft/vscode/issues/75651#issuecomment-543636997

**Pull request closed without merging**
