### PR TITLE
Fixes #28602

### LINKED ISSUE #28602: Keybindings in quick open aren't vertically aligned
Keybindings need vertical alignment:

image

### PR DESCRIPTION
**Pull request by joaomoreno**
Alternative to #30123 

screen shot 2017-07-06 at 10 50 54

### CODE REVIEW

**Comment by bpasero** [comment]
@joaomoreno that does not seem to work on Windows:

image

**Review by bpasero — CHANGES_REQUESTED** [review]
@joaomoreno Looks bad on Windows now:

image

**Comment by joaomoreno** [comment]
Ups... let's see...

**Comment by joaomoreno** [comment]
@bpasero Pushed fix!

**Comment by Tyriar** [comment]
@joaomoreno can you verify in the following?

- Windows
- macOS
- zoomLevel 0, < 0, > 0

Also does this fix the problem where the separator parent should be 23px not 22px?

**Comment by bpasero** [comment]
Thanks!

**Comment by joaomoreno** [comment]
I did give it a try in all OSs and zoom levels. Also, it doesn't fix the issue where the separator steals content space from one of the rows. That seems to be another problem.

**Pull request merged**
