### PR TITLE
[html] Remove dead code in html.ts

### PR DESCRIPTION
**Pull request by Tyriar**
PR contains the following changes:
- Remove `emptyElement` function from html.ts that is duplicated in htmlTags. The html.ts version is never used.
- Strongly type an array and fix a typo
- Depend on the htmlTags for knowledge of empty elements, fixing inconsistencies across html.ts and htmlTags.ts.

### CODE REVIEW

**Comment by Tyriar** [comment]
Looks like CI might have flaked?

>1) Files - TextFileEditorModel Change after auto save triggered will cause another autosave and twice the events:
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
>      at null.<anonymous> (C:\Users\appveyor\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:189:19)

`mocha` passes locally on Ubuntu.

**Comment by aeschli** [comment]
I'd rather have html.ts not reference htmlTags.ts. Sorry, all this is not document, but HTML is still one of the legacy modes that are not running in the extension host.
HTML is instead run part in the browser and HTML worker. The browser part does the colorization and editor smartness such as indent/unindent and bracket matching. The worker does the more expensive stuff like parsing, validation and intellisense. Because it is a worker it can do all that without blocking the renderer.
A build time we create two packages for each language mode, one for the browser main thread, one for the worker. html.ts is the root for the main, htmlWorker.ts is the root for the worker.
htmlTags is mainly used by intellisense and will end up in the worker package. We avoid any references to from the main files so it doesn't end up in the main files as well, increasing the memory footprint. We could separate out the empty tags in something like htmlTagsShared.ts to solve this, or duplicate the lists.

**Comment by Tyriar** [comment]
@aeschli would creating an emptyTagsShared.ts module be best for clarity? I was under the impression there were additional steps needed to introduce new files (#730)?

For future reference, Is it documented somewhere what the common directory name means? In Chromium there are the directories browser and renderer with a common directory containing shared code (this is all C++ though since node is introduced in Electron).

**Comment by aeschli** [comment]
@Tyriar 'common' refers to the minimal JS execution environment needed. For all language services, common is enough (no node, no browser). We created that to be able at compilation stage to make sure there are no node or browser dependencies.
Maybe an environment 'worker' would have been a good idea as well, but it's not up for discussion now. We want to move away from the workers into extensions.
About the separate file, I have to find out what's the story there with the copyrights. Is it going to be Microsoft, or is it the committer that create the file ( @chrisdias  ?). To avoid any wait I suggested to keep all in the files we already have. For this fix, add the Microsoft copyright until we have an answer.

**Comment by egamma** [comment]
@Tyriar regarding

>For future reference, Is it documented somewhere what the common directory name means?

The best we can offer for now is: https://github.com/Microsoft/vscode/wiki/Code-Organization

**Comment by aeschli** [comment]
Pull request delivered, thanks a lot @Tyriar !

**Pull request merged**
