### PR TITLE
Fix the case of the breakpoint placeholder

### PR DESCRIPTION
**Pull request by abhijit-chikane**
The placeholder of the breakpoint expression input is different for 'Enter' and 'esc'. So I have updated the 'esc' => 'Esc' as that's what how they mention it on keyboard.

image

### CODE REVIEW

**Review by roblourens — APPROVED** [review]
Sure, thanks

**Review by jrieken — APPROVED** [review]
This fix is legit but I feel this is wrong. Shouldn't we look up the assigned keybindings, like for `closeBreakpointWidget` and insert that.

**Comment by roblourens** [comment]
Yes, that's what it should be doing

**Comment by abhijit-chikane** [comment]
Thanks
But there should be way to close it by mouse

**Pull request merged**
