### PR TITLE
Work in progress, added user setting

### PR DESCRIPTION
**Pull request by igor-dragutinovic**
#21042 work in progress

### CODE REVIEW

**Comment by dbaeumer** [comment]
Assigning to @mjbvz due to #21042

**Comment by mjbvz** [comment]
@igor-dragutinovic Thanks for taking a look into this.

This is going to be a typescript specific setting so you should only need to touch files in `extensions/typescript`. A good example to look at is the `typescript.experimental.syntaxFolding` setting: https://github.com/Microsoft/vscode/blob/6e48ccc9e8963184863912099bf2de5c7fdba74a/extensions/typescript-language-features/src/languageProvider.ts#L25

For this case, you would add a setting such as `typescript.blockCommentStarPrefix` that toggles between one of two [`languageConfigurations`](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/utils/languageConfigurations.ts): the existing one which includes the logic to add `*` at the start of jsdoc comments, and a new one that does not (look for the rules the use `appendText: '*'`)

**Comment by igor-dragutinovic** [comment]
#21042 work in progress
JDoc comment code complete inserts * in first row, checking how to handle that.
Also, not sure how to update languageConfiguration when user makes change in settings.

**Comment by igor-dragutinovic** [comment]
Question, what is the proper way to enable debugging in extensions workspace?
I was checking StackOwerflow without success.
I see that map file exists, not sure how to setup configuration to use it.

**Review by mjbvz — COMMENTED** [review]
Sorry the the delay. Looks like good progress. To update the language settings when the new user setting changes, look at `workspace.onDidChangeConfiguration`. This event is fired whenever the user settings are changed

**Comment by igor-dragutinovic** [comment]
#21042 work in progress
First of all, thanks for the support!!!
I enabled updating of configuration following your suggestion.
Didn't move the configuration values to config, not sure what is the correct file for that.
You can explain me what to do, or do the changes as you proposed 😃 
Another issue is JDoc completion, as I mentioned above.
Even if the configuration is set to typescript.blockCommentStarPrefix: false, JDoc code complete inserts '*' in the first row of the block comment.

**Comment by igor-dragutinovic** [comment]
Hi @mjbvz ,
Any feedback on the latest commit?
Guess that you are busy with other tasks :)

**Comment by mjbvz** [comment]
Closing as out of date

**Pull request closed without merging**
