### PR TITLE
Support opening files through URL handling (fixes #4883)

### LINKED ISSUE #4883: Support opening files through URL handling
VSCode Version: 0.10.11
OS Version: Windows 10 

Details:
Please provide a URL handler for accessing vscode from external applications.
For example :
`vscode://open?url=file://path/to/file`
`vscode://new?text=text_that_will_be_in_file&type=js`

This would be very useful for lets say browser extensions etc....

### PR DESCRIPTION
**Pull request by KattMingMing**

### CODE REVIEW

**Comment by joaomoreno** [comment]
Fixes #4883

**Review by joaomoreno — CHANGES_REQUESTED** [review]
The intentions are good, and it appears at a first glance to just work. But there might be a better way to do this.

Right now, the URLService will send the `onOpenURL` event to the last focused Window. In the case of opening a file, that might not be the ideal scenario. Think about having two windows, each with a workspace open: A and B. While A is the last focused one, you can open a `vscode:file/B/foo.js` URL; ideally, the file would open in the window of workspace B, and not in A as it would occur given this PR.

For that reason, it might be better to react to the `onOpenURL` event in the main process, where we control all the windows.

I suggest to do it in the [WindowsService](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-main/windowsService.ts#L16) and just call the [`open` method in this other guy](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L313). That area is currently a [heavy reconstruction site](https://m.popkey.co/fe10c3/xMJ3r.gif) but I think you'll do fine.

**Comment by jrieken** [comment]
fyi - we have an `OpenerService` which should do this

**Comment by joaomoreno** [comment]
@jrieken That's already too late, since that service is scoped to an EditorService, which is scoped to a specific Window.

**Comment by KattMingMing** [comment]
@joaomoreno Great, thanks for the feedback!

**Comment by KattMingMing** [comment]
@joaomoreno I removed the implementation from the EditorService and moved the listener and implementation inside of the WindowsService. The opening behavior is now the same as running `code -g -r /path/to/file`. Thanks again for taking the time to review

**Comment by joaomoreno** [comment]
Good job! I just cleaned up a little bit more, added a disposables list and removed the method declaration in the service interface, we want this to be private within the service itself.

🍻  Thanks!

**Comment by KattMingMing** [comment]
@joaomoreno Awesome, thanks for the update! 🍻

**Pull request merged**
