### PR TITLE
Improve comment indenting behaviour for PHP

### PR DESCRIPTION
**Pull request by zyml**
This provides similar block comment indenting behavior from TypeScript to PHP.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by aeschli** [comment]
@mousetraps Do you take this? I had a quick glance and things look fine. I haven't tried it out as I'm not too familar with PHP.

**Comment by madflow** [comment]
Just a user feedback: This PR definitly makes the commenting/docblocks experience better for PHP. However - one "annoyance" is not adressed and done better in the Typescript extension.

`|` is the cursor

When you type `/** | */` and then `ÈNTER` Typescript does this:

```
/**
 *  |
 */
``` 

This PR yields:

```
/**
| */
```

The Typescript behavior is what I would expect from an Editor (PHP Storm, Netbeans etc does this like this). Maybe this can be addressed, too?

**Comment by zyml** [comment]
@madflow You might need to include the PHP header `<?php` before your comment for the indenting to work. This works the same way as PhpStorm.

**Comment by madflow** [comment]
@zyml Sorry - my comments turned out to be invalid! This was my first time building vscode from source (because I **really** want this feature) - and I must have botched the development after merging your branch.

But - I can confirm: The changes do behave like I would expect and how PHPStorm does it :D Can't wait to get this merged!

**Comment by neild3r** [comment]
This would be really useful for my extension as I have overriden the language config to adopt this behaviour but I'd much rather not have to.

**Comment by madflow** [comment]
@mousetraps This one is getting rather stale :( Is there anything missing to get this merged?

**Comment by bmewburn** [comment]
Yes, please merge. Keeping the php lang config centralised and continuously improved will prevent extensions having to provide their own solutions which can cause weirdness when extensions conflict.  I had also overridden the php language config to provide better formatting but it clashed with @neild3r docblocker extension so I have removed my override in the next release. See bmewburn/intelephense#30

Hi @roblourens, you appear to be active in PHP issues. Are you able to take a look?

**Comment by jens1o** [comment]
@roblourens Might be the reviewer that can bring the pr up.

**Comment by roblourens** [comment]
I'll check it out this week

**Review by roblourens — APPROVED** [review]

**Comment by roblourens** [comment]
Wow, I really lost this one. Apologies for the delay. This is a much-needed change.

**Comment by jens1o** [comment]
THANKS 😍

**Pull request merged**
