### PR TITLE
Makefile colorizing improvement: colorize at the beginning of line, handling the '\' symbol and other.

### PR DESCRIPTION
**Pull request by fadeevab**
Pull request is created into TextMate repository as well: https://github.com/textmate/make.tmbundle/pull/15

1). Colorize when there is an expression at the beginning of line.
2). Handle '\\' at the end of prerequisites (the next line should be colorized as a continuation of previous).
3). Colorize (origin|flavor).
4). Fix colorizing of built-in which stands after a common variable.

makefile_before
makefile_after

### CODE REVIEW

**Comment by aeschli** [comment]
@fadeevab Thanks a lot for your efforts!
The make grammar has been converted from https://github.com/textmate/make.tmbundle/blob/master/Syntaxes/Makefile.plist.
We don't want to maintain our own fork, therefore, if you want to provide a fix or improvement, please create a pull request against the original file.
Once accepted there, we are happy to run the update script and fix the tests.

**Comment by aeschli** [comment]
@fadeevab Sorry for my previous comment, now I see your pull request.
Give it a bit time for the guys at textmate/make.tmbundle to look into it.
If nothing happens there we can think again what to do and if we make an exception and move ahead.

**Comment by fadeevab** [comment]
@aeschli, Sure, thank you! It would be great if somebody review my pull request more carefully. But actually, current makefile colorizing couldn't be worse, so I believe this patch makes one better. At least I tried to test it carefully, that's why I recreated pull request with additional fixes. And also several fixes will come later, because some cases are still not covered.

**Comment by fadeevab** [comment]
(re-opened because it's closed accidentally from mobile phone)

**Comment by fadeevab** [comment]
Nothing happens in the referred pull request. Wait more?

**Comment by fadeevab** [comment]
1. There is some movement in the referred review.
2. I actualized makefile tests.
makefile_test_fixture

**Comment by fadeevab** [comment]
A moment ago both builds were ok. Now AppVeyor build failed, I'm sure it doesn't depend on update.
```
npm ERR! code EBADF
npm ERR! errno -4083
npm ERR! syscall fstat
npm ERR! EBADF: bad file descriptor, fstat
```

**Comment by fadeevab** [comment]
Review is stuck

**Comment by fadeevab** [comment]
@aeschli, TextMate review of Makefile syntax is not moving on. What could we do in such case: could we submit?

**Comment by aeschli** [comment]
Let's be patient one more week or so. Creating our own fork is not really what we want as we don't have the resources to maintain it. So given that you got some response on your PR I'd rather wait a bit more.

**Comment by fadeevab** [comment]
Right, I just don't want this patch would be sank into oblivion.

**Comment by aeschli** [comment]
What we can do is that we use your fork (https://github.com/fadeevab/make.tmbundle/) as the new input for the make grammar. Would that be ok for you?
- you'd have to make sure to keep master in a working state
- avoid diverging from the original so that we eventually can unify them again.
Ideally this is only a temporary solution.

Let me know when your repo is ready.

**Comment by fadeevab** [comment]
Just let's do this. I agree to send new pull request to the original repo to synchronize our repos, so we can eventually unify them. Also I'll try to take care about new issues, still maybe it worth to duplicate the issues to the original repo.

**Comment by aeschli** [comment]
Thanks @fadeevab !

**Comment by aeschli** [comment]
@fadeevab I'm now consuming your repo. To simplify thing, can you add a MIT licence to your repo?

**Comment by fadeevab** [comment]
@aeschli, Done

**Pull request merged**
