### PR TITLE
Expose Stickiness API #15758

### PR DESCRIPTION
**Pull request by CoenraadS**
For issue: https://github.com/Microsoft/vscode/issues/15758

This adds stickiness as a public decoration option.

Use case: I have an [extension ](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)which colors brackets after a timeout, and I don't want the bracket colors to expand when the user types.

### CODE REVIEW

**Comment by CoenraadS** [comment]
Unfortunately I can't seem to run tests locally

[14:57:53] Starting 'test'...
{ errorCode: 'load',
  moduleId: 'gc-signals',
  neededBy: [ 'vs/workbench/api/node/mainThreadHeapService' ],
  detail: 
   Error: %1 is not a valid Win32 application.
   \\?\d:\Downloads\vscode-fork\vscode\node_modules\gc-signals\build\Release\gcsignals.node
       at Object.Module._extensions..node (module.js:598:18)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (d:\Downloads\vscode-fork\vscode\node_modules\gc-signals\src\index.js:8:18)
       at Module._compile (module.js:571:32)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at NodeScriptLoader.load (d:\Downloads\vscode-fork\vscode\out\vs\loader.js:609:39)
       at OnlyOnceScriptLoader.load (d:\Downloads\vscode-fork\vscode\out\vs\loader.js:519:37) }

**Comment by CoenraadS** [comment]
Can I get some feedback on this?

If tests are needed, although I can't run them yet I can try to create some. However I took a look at `lineDecorations.test.ts` and it seems like my test belongs somewhere else, because I need to create a document, apply decorations, edit the document and check decorations again. If someone could point me towards similar tests I would appreciate it.

**Comment by CoenraadS** [comment]
Can I get some feedback on this? I searched the `editor/test` folder for `IThemeDecorationRenderOptions` but didn't find any matches, so if tests are needed I would appreciate some pointers to similar tests which involve using decorations via the API.

**Comment by alexandrudima** [comment]
@jrieken Any objections?

**Comment by alexandrudima** [comment]
@CoenraadS Thank you for your contribution! :heart:

**Pull request merged**
