### PR TITLE
Add elevation message to ports UI

### LINKED ISSUE #3922: Port forwarding: when the local port is privileged, offer to elevate and use the privileged port if possible
Currently, if preferred local port is privileged, we just pick some other available port. Instead, we could offer to elevate and use the privileged port instead. This would allow users who rely on specific privileged port numbers to continue to develop as though everything is local more easily.

### PR DESCRIPTION
**Pull request by alexr00**
This change allows remote extension to handle elevation if they want.
Fixes https://github.com/microsoft/vscode-remote-release/issues/3922

### CODE REVIEW

**Comment by SamuelMoraesF** [comment]
Is there anything that I need do to get this working? I'm currently using v1.53.2 and I still can't forward lower ports (like 80 and 443).

**Comment by alexr00** [comment]
@SamuelMoraesF This change just added an option for Remote extensions to support using privileged ports. There are currently no Remote extensions that have done the necessary implementation to add this support. Which remote extension are you using?

**Comment by Jake13f** [comment]
@alexr00 I have the same problem currently and really need this feature.  I am currently using the Microsoft Remote - SSH extension.  https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

**Comment by SamuelMoraesF** [comment]
@alexr00 I'm using docker containers (`ms-vscode-remote.remote-containers`)

**Comment by alexr00** [comment]
@chrmarti and @roblourens  FYI there are requests to use privileged local ports when doing port forwarding in remote containers. To accomplish this, you would need to implement a `tunnelFactory` in each extension that knows how to elevate. Maybe this is an argument that would should support this in the core.

**Comment by chrmarti** [comment]
@alexr00 When the resolver does not have a tunnel factory, could the core implement elevation? Maybe there is also a way to share that with the tunnel factory if there is one. (Remote-Containers currently does not have a tunnel factory.)

**Comment by alexr00** [comment]
That should be possible. Feature request: https://github.com/microsoft/vscode-remote-release/issues/4589

**Pull request merged**
