### PR TITLE
Take editor groups into account in navigation history

### LINKED ISSUE #9526: Make history navigation aware of editor groups
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.open a file in editor 1;
2.open same file in other editor 2(ctrl +2 side editor)
3. in editor 1 move cursor   to line 1 and then to line 2
4 in editor 2 move cursor to line 3 and then to line 4
5 click mouse backward button in editor 1 the cursor back to  line 4 but i want to line 1

It seems every file have one  cursor backward stack,and all side editor share it?
Regards

### PR DESCRIPTION
**Pull request by Timmmm**
This is a preliminary pull request to get some feedback. As far as I can tell it fixes the issue, however the code in this file is a bit of a mess and light on comments. It took several attempts to get something vaguely coherent so I would appreciate someone (@bpasero preferably) taking a look before I go to the effort of writing tests.

This PR fixes #9526

### CODE REVIEW

**Comment by Timmmm** [comment]
Video [here](https://github.com/microsoft/vscode/issues/9526#issuecomment-713871869)

**Comment by Timmmm** [comment]
I've been using this as my main editor for a few days and in some situations it doesn't work. I will investigate, but don't bother reviewing yet.

**Comment by golergka** [comment]
Thanks for taking on this issue, it's been bugging me for a long time! Is this PR still actively developed? Can I offer any help?

**Comment by Timmmm** [comment]
Depends how you define "actively"! It's still annoying me so I will probably work on it again at some point.

As I recall I got to the point where it works for manual navigation between editor groups but for some reason it doesn't work when using "Go To Definition". I haven't even tried to figure out why yet.

**Comment by yueyingjuesha** [comment]
> Depends how you define "actively"! It's still annoying me so I will probably work on it again at some point.
> 
> As I recall I got to the point where it works for manual navigation between editor groups but for some reason it doesn't work when using "Go To Definition". I haven't even tried to figure out why yet.

This is a serious problem because literally I only use the go to definition to jump code. Which basically is not fixed for me

**Comment by jasonwilliams** [comment]
Hey @Timmmm was you still working on this?

**Comment by Timmmm** [comment]
No, sorry. I did take another look at it but got depressed that it was basically impossible to rebase and I would have had to start from scratch.

I had to do quite a lot of refactoring to get anywhere and I'm not especially keen to refactor the same code twice without any guarantee it would be reviewed!

**Comment by jasonwilliams** [comment]
@Timmmm thats sad to hear. I think it would definitely get reviewed if it was in a working condition. That being said the developers may have other ideas but I’m sure they would guide you though

**Comment by bpasero** [comment]
Thanks for the PR but I decided to take a re-write approach to the editor history to support many missing features that accumulated over the years. If you want to take a look, https://github.com/microsoft/vscode/pull/142152 is up with changes already in to make history navigation editor group aware.

**Comment by Timmmm** [comment]
@bpasero great news! I definitely think a rewrite is the best plan. I'll close this.

**Pull request closed without merging**
