### PR TITLE
Multiple tab labels for diff editors

### LINKED ISSUE #110694: Allow to shorten the diff editor title
Issue Type: <b>Feature Request</b>

When comparing two codes side by side, the order is confusing. 
It takes a considerable amount of time just to realize which file is on the left and which is on the right. 

And the tab title showing comparing files is not helpful at all since it is too long
For example, in tab title;
different file names in same location
.....very/very/very/very/long/path/file1.js <-> .....very/very/very/very/long/path/file2.js
 
or

same file name in different locations
.....very/very/very/very/long/path1/file1.js <-> .....very/very/very/very/long/path2/file1.js

either situations, I find it really frustrating to identify which file is on which side by reading the long URL (title). 

What i propose is to implement the vscode interface to allow the user to add labels with custom titles to each side (when in code comparison). 

So instead of a single long URL like this:
screenshot

implement a UI feature like this:
screenshot2

to show clearly which file is open on which side and also allow the user to add custom title names to each of comparing file (temporarily - for reference)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

### PR DESCRIPTION
**Pull request by goldst**
This PR fixes #110694

Diff editors can have a tab label that is too long in some cases. This PR implements the ability for tabs to have multiple labels, each with separate code icons and shortened paths, and makes use of that for diff editors.

The alternative to this would be to just shorten the paths but keeping the current way of labeling. I have implemented that as well. See #110694 and https://github.com/microsoft/vscode/compare/master...goldst:shorten-diff-title-A for details.

Test this by opening two files with the same name but different paths, then <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> -> compare active file with...

Overview of the most important changes from a technical point of view:
- add `getNames` and `getDescriptions` to `IEditorInput` so editors can have one or multiple labels. Implement these in `EditorInput` where they return the name and description, and override them in `DiffEditorInput` to return all three labels (left editor, compare arrow, right editor)
- change the logic for rendering tabs:
  - `tabTitleControl.ts` gets all names and descriptions and shortens paths even when there are multiple paths in one label
  - add some classes in `label.ts` (eg `MultipleResourceLabels` and `ResourceLabelWidgets`) that have mostly the same methods as the ones previously in use, but they are a wrapper for multiple objects of the previous classes. Also added some interfaces/parent classes (eg `IResourceLabels`, `IResourceLabelWidget` and `ResourceLabelGroupBase`) to make sure they behave in the same way as the ones used previously.
 
This PR might have some implications that weren't clear to me, that's why I suggest that it should be reviewed thoroughly. I would also like to have a general yes or no for this approach before I/we fix the merge conflicts.

### CODE REVIEW

**Comment by goldst** [comment]
@bpasero The checks are "expected" now for a long time. Can you check what's causing the problem?

**Comment by bpasero** [comment]
Thanks for the PR, sorry for the late reply. A little bit on the expectation: I will probably not have time to review this until we get to our yearly issue grooming iteration in October.

**Comment by goldst** [comment]
I see. That is a bit unfortunate because there will probably be more merge conflicts then, but nevertheless, I'll ping you and probably be available for fixing them in October.

**Comment by goldst** [comment]
I'll close this due to the discussion in #110694 and [@bpasero's recent commit](https://github.com/microsoft/vscode/commit/adee8fa29ad3635418ff995b235c4b08a40c8434) which solves the same issue.

**Comment by bpasero** [comment]
@goldst thanks and sorry for not accepting this PR. Nevertheless I will make sure that your contribution appears in our "Thank You" section for our upcoming 1.61 release (similar to https://code.visualstudio.com/updates/v1_60#_thank-you)

**Pull request closed without merging**
