### PR TITLE
SelectBox convert to WorkbenchList WIP

### PR DESCRIPTION
**Pull request by cleidigh**
@bpasero 
- in progress, just wanted to see if this is what you want
- Moved selectBox to workbench/parts/selectbox  - to allow imports - could also be elsewhere
- Debug configurations uses new select box 
- converted to workbenchList - instantiated inside select box - could instantiate in caller - will do next
- Note: if we have caller instantiate workbench list, I have to instantiate renderer also AND
we would have to add platform switch in each caller
- kind of ugly IMHO - I prefer things as I have them fully encapsulated
- Utilize Global list commands 
- Added disabled trait and disabled list entry handling inside listWidget

### CODE REVIEW

**Comment by bpasero** [comment]
@cleidigh I am not sure why select box has to move to workbench? Here is what I had in mind:
* `SelectBox` constructor gets a new optional argument `listCreator` which is a function of `(container: HTMLElement, delegate: IDelegate<T>, renderers: IRenderer<T, any>[], options: IListOptions<T>) => List`
* if that function is not provided, a default implementation will just instantiate a `List` as it is done now
* whoever creates `SelectBox` from the workbench implements this function to return a `WorkbenchList` and sets `keyboardSupport: false` in the options so that navigation happens through our commands in the workbench (through all `list.*` commands)

I realise this drags through `SelectActionItem` which is also in base, so that one would also need this function to pass on to the `SelectBox`.

**Comment by cleidigh** [comment]
@bpasero 
I've been down and out all week, Zero work.  Sorry for the delays.
Hopefully I can update the PR tomorrow or Tuesday if back on track.

**Comment by cleidigh** [comment]
@bpasero 
Finally 'getting better, back to work. More serious than expected
working on the list creator

**Comment by cleidigh** [comment]
@bpasero 
- only converted debug actions client will convert others if this looks good to you
- workbench list allows global list commands
- modified list keyboard controller to recognize disabled options
- I will move selectbox also on clean up

**Comment by bpasero** [comment]
@cleidigh why such a large change? I was hoping for a small one where you just introduce the list creator so that the custom select box ends up using the `WorkbenchList`?

**Comment by cleidigh** [comment]
@bpasero 
not sure what you mean by large change
I have to the secondary test select box and only use the select box in the original location
I think I have the listCreator instantiating the workbench list in the client as you request
if that looks good let me clean up
for the one client did I do it as you wished?

**Comment by bpasero** [comment]
@cleidigh maybe hold on before making any more changes until I had time to review...

**Comment by cleidigh** [comment]
@bpasero 
would you like me to do a first pass cleanup at least removing the duplicate code?  I think I left too many experiments in and that makes it a difficult review...

**Comment by bpasero** [comment]
@cleidigh had some more thoughts, maybe it is actually unexpected to use custom keybindings for the dropdown widget. even though it is not the native widget, a user might expect the typical OS keybindings to work, so feel free to ignore my issue until we get strong feedback on this.

To proof my point about what I meant about having a list creator that gets passed around, have a look at my branch: https://github.com/Microsoft/vscode/compare/ben/selectlist. Not a lot of changes to get the WorkbenchList hooked in. The ugly part is that now we leak the fact that potentially a custom dropdown is being used (on Linux and Windows) to everyone.

**Comment by cleidigh** [comment]
@bpasero 
I did not realize you could use the combination of the instantiation service and the anonymous function
to avoid having to instantiate the delegate and the renderer at the client level.  My implementation of that was really ugly !

I would like to suggest merging in my changes to the listW that recognizes disabled options and the other SelectBox navigation requirements.  This gets us one step closer, eliminates the duplicate keyboard 
controller and perhaps most importantly, we can thoroughly test the evolved implementation and not throw that away later.

**Comment by bpasero** [comment]
@cleidigh I suggest we wait until users complain about this (e.g. when they expect certain keybindings to work in the dropdown). at the time I filed https://github.com/Microsoft/vscode/issues/41223 I wanted each list user to use `WorkbenchList`, but I am not so sure anymore this is really needed for the dropdown case. 

Closing this PR for now.

**Pull request closed without merging**
