### PR TITLE
🔨 Fix `list.collapseAll` prevents re-expanding newly selected node

### LINKED ISSUE #174768: `list.collapseAll` leaves selection in a broken state
Type: <b>Bug</b>

When pressing `ctrl+left` to collapse all nodes in a list view it leaves selection in such a state that you cannot expand nodes with `right` until you do something to change the selection.

list collapseAll

I believe what's happening is `list.collapseAll` is leaving the originally selected node selected. So after executing the command you end up with 2 selections, your original selection plus the last root node in the list. The original selection is the primary selection, and if it has no children `right` does not have anything to expand and is a no-op.

As a user it looks like you have the root node selected, which has children to expand, but pressing `right` does nothing.

Pressing `down` then expands the list to reveal your original selection and you see that you unexpectedly have multiple selections.

The current behavior of `list.collapseAll` appears to be:
* Leave the originally selected node selected
* Add a second selection to the last root node in the list

The expected behavior here is:
* Move selection to the root node of your currently selected node
* Ideally this also retains multiple selection: each selection is moved to the root node of that selection.

VS Code version: Code - Insiders 1.76.0-insider (c7930ca55d072608625ba76c13b5f9baaf9a2136, 2023-02-10T16:22:19.445Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.54GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257

```

</details>

### PR DESCRIPTION
**Pull request by babakks**
Fixes #174768

This PR fixes the issue with `list.collapseAll` command. As in the screen capture below, when the user invokes the `list.collapseAll` command (<kbd>Ctrl</kbd>+<kbd>Left</kbd>), the selection changes to an unwanted element (due to a stale item index) and they can no longer expand the (newly) selected item (e.g., by using <kbd>Right</kbd> key):

capture-before

The PR fixes this, by changing the tree's both selected and focused elements to their topmost parent in the tree's root. This prevents the unwanted selection of other items due to a stale selection index value:

capture-after

The original issue was about the tree view in "Find in Files" view. This is how it looks now:

capture-after-find

## Note

The same thing happens with normally collapsing items. That is, when you collapse an item whose child is selected (not focused), another element at the tree gets the selection (which has the same index offset in the new view) which seems strange. More than that, when the user expands the collapsed node again, they old selection returns and the user ends up with two selected items, which is confusing, too.

We can also apply the same logic in this PR to the `AbstractTree.collapse` method (of course, with a little change that selection goes back to the first visible parent in the chain, instead of getting back to the root elements).

### CODE REVIEW

**Comment by joaomoreno** [comment]
I'm not so sure this is completely related to collapseAll. Here's a repro with a simple collapse, using the left arrow key only:


https://github.com/microsoft/vscode/assets/22350/b8734713-d883-47e6-8d86-5a2659063af1

**Comment by joaomoreno** [comment]
> changes to an unwanted element (due to a stale item index)

It's actually due to this: https://github.com/microsoft/vscode/commit/bf495694c7c7bcd4d4893fbe089f13cb4baa11e1

**Comment by joaomoreno** [comment]
Ah I just read the **Note** section of the first post. 😆

**Comment by joaomoreno** [comment]
After giving this quite a bit of thought, I no longer thing https://github.com/microsoft/vscode/commit/bf495694c7c7bcd4d4893fbe089f13cb4baa11e1 was a good change. I am more in favor of reverting it and have trees handle this in their own way.

One more comment on:

> More than that, when the user expands the collapsed node again, they old selection returns and the user ends up with two selected items, which is confusing, too.

This is actually as designed, so selection is restored when the parent folder expands once again:

https://github.com/microsoft/vscode/assets/22350/9ce1fb41-799b-496a-a84d-6a08720c0436

**Comment by joaomoreno** [comment]
Closing in favor of https://github.com/microsoft/vscode/pull/201309

**Comment by babakks** [comment]
@joaomoreno Thanks for the explanation. I think you're right about reverting the changes.

**Pull request closed without merging**
