### PR TITLE
Remove use leading from custom tree view

### PR DESCRIPTION
**Pull request by alexr00**
https://github.com/microsoft/vscode/issues/90027

### CODE REVIEW

**Review by sandy081 — APPROVED** [review]
Approved, as the fix is to revert the change.

**Comment by solomatov** [comment]
@alexr00 Do you have a plan to investigate it?

**Comment by alexr00** [comment]
Final fix is here: https://github.com/microsoft/vscode/commit/09ed1c7c19af82076155f398c20baeaafadf7701

**Comment by solomatov** [comment]
@alexr00 Thanks!

**Pull request merged**
