### PR TITLE
SelectBox: Refactor constructor using interface. WIP for #58922

### PR DESCRIPTION
**Pull request by cleidigh**
Why this re-factoring PR?
- cleanup and consolidate per-option item parameters into interface - enable setting all in constructor
- precursor for next PR addressing decorator/'default' option for new settings editor - @roblourens   #58724
- eliminate setDetailsProvider callback - utilize interface parameters directly
- add option to force use of custom select regardless of platform (eliminate indirect details approach)
- allow for multiple disabled items (to do)

This PR is still WIP !

I am looking for a brief initial review to know I'm not going in a bad direction.
Have final cleanup and testing to do.  Will post final PR assuming no one
has any issues with the direction of change.

### CODE REVIEW

**Comment by bpasero** [comment]
(assigning myself so that this shows up in my milestone list of work - did not look at the changes yet)

**Comment by cleidigh** [comment]
@bpasero 
I will assign you as well in the future, I thought the review placed it in your workflow.
I'm going to hedge my bets assuming I'm on the right track and continue cleaning.

**Comment by bpasero** [comment]
@cleidigh you don't have to assign me, review is good, as long as I get a notification 👍

**Comment by cleidigh** [comment]
if I messed up the merge update I will do a new PR...never looks right

**Comment by bpasero** [comment]
@cleidigh GH still reports tons of commits though.

**Comment by cleidigh** [comment]
@bpasero .
I will post new PR since I cannot seem to merge/replace a PR without all the master commits

**Comment by cleidigh** [comment]
Closing for new clean PR #64109

**Pull request closed without merging**
