### PR TITLE
Add setting to prevent closing the pinned tab when using middle click (fix #115734)

### LINKED ISSUE #115734: Add setting to prevent closing the pinned tab when using middle click
I wanted to add this as a comment to #100738, but it's been locked.

A pinned tab cannot be closed with <kbd>ctrl + w</kbd>, but it can be closed with the mouse (middle click).

Please extend this behavior so the middle click cannot close a pinned tab?

### PR DESCRIPTION
**Pull request by Kalmaegi**
Fix #115734

### CODE REVIEW

**Comment by weartist** [comment]
@bpasero Hi, I have two questions:
Do we need to make settings for this obstacle? 
If I add judgment for pinned here, the scope may be a little larger. Do we need to move the judgment to where the mouse middle button is clicked to determine, in order to reduce the impact scope of this obstacle? 
Thanks!

**Comment by bpasero** [comment]
@weartist I would have a setting which then we can turn on by default to see how many users are upset. If there are no complaints I am also easy to remove the setting again and make it the default behaviour.

I would think the change should only be where we close from mouse middle click:

For the "Open Editors" view:
https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L271

For tabs:
https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L891

For no tabs:
https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L108

**Comment by weartist** [comment]
> @weartist I would have a setting which then we can turn on by default to see how many users are upset. If there are no complaints I am also easy to remove the setting again and make it the default behaviour.
> 
> I would think the change should only be where we close from mouse middle click:
> 
> For the "Open Editors" view:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L271
> 
> For tabs:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L891
> 
> For no tabs:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L108

Understand, and thank you very much for the code points! XD

**Comment by weartist** [comment]
> @weartist I would have a setting which then we can turn on by default to see how many users are upset. If there are no complaints I am also easy to remove the setting again and make it the default behaviour.
> 
> I would think the change should only be where we close from mouse middle click:
> 
> For the "Open Editors" view:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L271
> 
> For tabs:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L891
> 
> For no tabs:
> 
> https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L108

Understand, i rushed XD, and thank you for the code point!

**Comment by weartist** [comment]
I simply completed the feature and tested it, hoping it worked fine @bpasero

**Review by bpasero — COMMENTED** [review]
The method is actually called `isSticky` in the internal API, I know its misleading, but `isPinned` is for a different feature (preview tabs).

Should the setting be more specific to mention that it is for mouse middle click only? We already prevent closing a tab by keybinding irrespective of the setting.

**Comment by weartist** [comment]
> The method is actually called `isSticky` in the internal API, I know its misleading, but `isPinned` is for a different feature (preview tabs).
> 
> Should the setting be more specific to mention that it is for mouse middle click only? We already prevent closing a tab by keybinding irrespective of the setting.

That is, can I replace `isPinned` with `isSticky`? I did confuse the two judgments a bit,  I found that the two were almost identical, then I found their implementation, but still not possible to confirm whether they are equal haha

isPinned: https://github.com/microsoft/vscode/blob/885dba39a5f546c5077196a8c31b03d03a293b31/src/vs/workbench/common/editor/editorGroupModel.ts#L720
isSticky: 
https://github.com/microsoft/vscode/blob/885dba39a5f546c5077196a8c31b03d03a293b31/src/vs/workbench/common/editor/editorGroupModel.ts#L720

and I'll go and change the description again

**Comment by bpasero** [comment]
Yes, can be replaced with `isSticky`.

**Comment by bpasero** [comment]
@weartist I had a thought: what if the setting changes back to the original name you had in mind and becomes an enumeration that allows to fully control the behaviour for closing:
* one option to never close for neither keyboard nor mouse
* one option to never close for keyboard
* one option to never close for mouse
* one option to always allow to close

This would be a good way to keep the setting around even for the future to let people fully control the close behaviour and then we can think about a reasonable default?

**Comment by bpasero** [comment]
Yeah I was suggesting to target only these 2 cases:
* closing by keybinding
* closing by mouse

But not other actions, such as the menu.

**Comment by weartist** [comment]
> 

In this case, does mouse closing only include clicking the mouse middle button? I will try to write a simple version.

**Comment by weartist** [comment]
will start tomorrow. Tonight I will think about whether there are some other cases to consider XD

**Comment by bpasero** [comment]
Yeah, so I meant middle-mouse-click.

**Comment by weartist** [comment]
@bpasero I want to abstract the logic that judges whether to block closing into a method, something like 'isPinned', but I didn't find a good place for it. The current code has some repetition and verbosity

**Review by bpasero — CHANGES_REQUESTED** [review]
Yeah some code-reuse might be good, for example from a method in `src/vs/workbench/common/editor.ts`. I feel the method could accept the editor in question and then either the configuration service or the part options to return if the editor should close based on a context such as mouse or key.

**Comment by weartist** [comment]
have reworked the relevant code, but have not tested it yet

**Comment by weartist** [comment]
After a simple test, the function looks fine

**Comment by bpasero** [comment]
@weartist I did a review and pushed changes, can you please test out everything works as expected?

**Comment by weartist** [comment]
> @weartist I did a review and pushed changes, can you please test out everything works as expected?

sure, thanks! I'll start testing after reading it, this is my favorite part to learn in order for me to improve haha

**Comment by weartist** [comment]
@bpasero It's run as excepted

**Review by bpasero — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
