### PR TITLE
Improve Open in Terminal in Mac

### LINKED ISSUE #391: Open in terminal should open new terminal window
Bug: Open in terminal should open new terminal window. 
I am using mac osx 10.11. I opened a terminal, with tmux .
I ssh login into remote server debug.

now, open VSCode, open some folder, choose any one file right click mouse, then choose open in terminal.

The VSCode just open new tmux screen ? what the hell...

### PR DESCRIPTION
**Pull request by sijad**
This also fixes #391 

Tested in `Mac OS X 10.11.4 (15E65)`
With `Terminal Version 2.6.1 (361.1)` and `iTerm2 Build 2.1.4`

`DEFAULT_TERMINAL_MAC` also can be set as `terminal.app` or even `terminal` but I can't test if that works with older version of `open` command in previous Mac OS

### CODE REVIEW

**Comment by Tyriar** [comment]
Going to adding to @joaomoreno as I don't have access to a mac/vm right now.

**Comment by Tyriar** [comment]
Getting an OS X VM setup so I can do it as @joaomoreno is out.

**Comment by weinand** [comment]
@sijad thanks for the PR. 

Could you please provide some details about your improvements to 'Open in Terminal' on OS X.

I quickly reviewed the code and noticed that you have removed the AppleScripts that try to reuse the same terminal if it is not already running a command. Without that functionality, every 'Open in Terminal' creates a new Terminal window which quickly clutter the desktop.

**Comment by sijad** [comment]
@weinand that's true but applescript uses `cd` command and sometime it can be a little annoying
using `open` command is the preferred way to do this, I also did look into a few other editors and most of them uses same way to do this. but maybe using apple script is a better way, I really not sure either.

**Comment by weinand** [comment]
@sijad here is a first analysis of your PR. Please correct me if I'm wrong and add anything that is missing.

The PR:
- simplifies the implementation by using `open` to launch the Terminal.app instead of using multiple AppleScripts,
- makes the terminal application configurable through settings,
- adds a test.

The PR removes the following features:
- a user installed `iTerm.app` is no longer automatically used but must be configured manually in settings.
- 'Open in Terminal' does no longer reuse a non-busy terminal but always opens a new terminal. To get back the previous functionality a user has to install a custom application and configure it in the settings.

Verdict:
I think that the added configurability outweighs the loss of functionality of this PR.

**Comment by Tyriar** [comment]
@weinand as I understand it the main part of it is https://github.com/Microsoft/vscode/issues/5462 (OS X support for custom terminal launch settings https://github.com/Microsoft/vscode/pull/3495 )

**Comment by sijad** [comment]
@weinand you're right. As told applescript run `cd` and it will be saved in shell history. I just thought it's cleaner
I'm going to revert applescript

**Comment by weinand** [comment]
@sijad I'm not suggesting to revert the PR to use the AppleScript because that will complicate the launch settings: What do you specify in the setting instead of `Terminal.app`?
I think your PR is fine, I just wanted to understand what the PR does and how VS Code's existing behavior will change.

**Comment by sijad** [comment]
@weinand it's still possible to use AppleScript to lunch Terminal application

**Comment by weinand** [comment]
@sijad sure, instead of specifying `Terminal.app` in the settings, I can specify an AppleScript based application. But the AppleScript would not be the default and VS Code would not ship with it.

**Comment by Tyriar** [comment]
@weinand do you want to take this PR? I wouldn't have identified any issues with the AppleScript stuff.

**Comment by weinand** [comment]
@sijad today I've merged your PR into VS Code. Thanks a lot!
I could not accept the full PR because too many terminal related changes had occurred in the meantime. But I cherry picked your main commit and added three minor tweaks on top of that.

**Pull request merged**
