### PR TITLE
Add log point on middle clicking gutter

### LINKED ISSUE #204009: Use middle click to set a logpoint
To make it easier to use log points, it would be very nice if they could be set by a middle click here (the tooltip could mention this):

Code_-_Insiders_p7KbDNMCNN

Then, this editor could show:

Code_-_Insiders_8FsziUp0as

### PR DESCRIPTION
**Pull request by hsfzxjy**
Fix #204009

### CODE REVIEW

**Review by balaji-sivasakthi — APPROVED** [review]
LGTM!

**Comment by roblourens** [comment]
Thoughts @connor4312? What bugs me is that I always still have to move my hands to the keyboard after this anyway, so I wonder how much it speeds things up. And there's no way for anybody to discover this.

**Comment by connor4312** [comment]
I always set logpoints via the context menu in the gutter, so there would be a marginal benefit for me, at least until I set up a keybinding for that command 😛 

I'm not opposed to this, but there's no reason logpoint is special: the type of breakpoint should probably be configurable via a setting if we go this route.

**Comment by hsfzxjy** [comment]
> the type of breakpoint should probably be configurable via a setting if we go this route

Agreed. I will proceed to add configuration for this.

**Comment by connor4312** [comment]
This seems decent to me, what do you think @roblourens?

**Comment by roblourens** [comment]
I don't have a mouse at the moment, so I can't properly test it. But I like the setting in principal, this is fine with me.

**Review by connor4312 — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Pull request merged**
