### PR TITLE
cleanup unused files in .github

### PR DESCRIPTION
**Pull request by Jvr2022**
I have removed:

calender.yml. the The dates have not been updated since 2018 
subscribers.json. there is nothing in the file.

### CODE REVIEW

**Comment by AdamRaichu** [comment]
Is subscribers the file referenced here? I can't tell.

https://github.com/microsoft/vscode/blob/9b81a0d764c5ff811562792e1b23eb583b0042e3/.github/workflows/on-label.yml#L40-L46

**Comment by Jvr2022** [comment]
> Is subscribers the file referenced here? I can't tell.
> 
> https://github.com/microsoft/vscode/blob/9b81a0d764c5ff811562792e1b23eb583b0042e3/.github/workflows/on-label.yml#L40-L46

I don't know why it gets still used there is nothing more in the file

**Review by chrmarti — APPROVED** [review]

**Comment by Jvr2022** [comment]
When this gets the next review?

**Review by AdamRaichu — APPROVED** [review]

**Review by rebornix — APPROVED** [review]

**Comment by Jvr2022** [comment]
@rebornix thanks for aproving the pull request

**Comment by TylerLeonhardt** [comment]
Thanks for your contribution, @Jvr2022!

**Comment by Jvr2022** [comment]
@TylerLeonhardt can it get merged now or need it more reviews?

**Comment by Jvr2022** [comment]
@TylerLeonhardt thx for merging

**Comment by Jvr2022** [comment]
Can i do something others now? @TylerLeonhardt

**Comment by Jvr2022** [comment]
And can u help with reviewing 2 other pr @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
@Jvr2022 looking at our "good first issues" query is a best place to look for more straightforward issues to pick up:
https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

If those PRs are already assigned, you'll need to wait for the folks who are assigned to review. We ask for patience as we have a lot on our plate and can't always move quickly to merge in PRs 🙏 hope you can understand

**Comment by TylerLeonhardt** [comment]
I'll take a look as soon as I can 👍

**Comment by Jvr2022** [comment]
Thx this are the pull requests https://github.com/microsoft/vscode/pull/189062 https://github.com/microsoft/vscode/pull/189060

**Comment by lramos15** [comment]
> Is subscribers the file referenced here? I can't tell.
> 
> https://github.com/microsoft/vscode/blob/9b81a0d764c5ff811562792e1b23eb583b0042e3/.github/workflows/on-label.yml#L40-L46

Yeah this should've been removed as well when the file was removed as now the bot is throwing a bunch of errors. https://github.com/microsoft/vscode/pull/194934 should remove this workflow

**Pull request merged**
