### PR TITLE
Unbreak ESLint

### PR DESCRIPTION
**Pull request by arvid220u**
Since https://github.com/microsoft/vscode/commit/13a88a8da4142e1c528fb701223603772eeafd2e, I believe that `yarn eslint` has been broken. It runs for 10 seconds and reports a success.

The problem, I believe, is that `gulp-eslint` does not parse double exclamation marks. This PR changes the double exclamation mark into no exclamation mark at all, which makes `eslint` work again, and which I believe also makes the original intent of the https://github.com/microsoft/vscode/commit/13a88a8da4142e1c528fb701223603772eeafd2e commit work.

There seems to be a few lints that have gone unnoticed because of this, but I will leave that to subsequent PRs by the respective code owners.

I might be missing something! But figured I'd send it here in case I'm not :)

### CODE REVIEW

**Comment by dbaeumer** [comment]
Great catch.

**Review by dbaeumer — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Comment by dbaeumer** [comment]
@arvid220u your change doesn't pass the build pipeline since you formatted the code with spaces instead of tabs. I will redo the change.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode/pull/220037 for the merged pull request. To get this in all reported errors needed to fixed as well.

**Pull request closed without merging**
