### PR TITLE
Add theme-specific color customizations. Fix #36860

### LINKED ISSUE #36860: [theming] Add theme-specific color customizations
Now there are only 2 settings to customize current theme:
`"workbench.colorCustomizations": {}`
`"editor.tokenColorCustomizations": {}`

The downside: if you have a habit to customize each one of your themes, then you have to manually maintain the list of all of your tweaks.

#### New Syntax:
```json
"workbench.colorCustomizations": {
    "[One Dark Pro]": {}
}
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {}
}
```
#### Color priority:

`2:` Setting with theme name (`"[One Dark Pro]": {}`)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
`1:` Setting without theme name (`workbench.colorCustomizations: {}`)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
`0:` Active theme (One Dark Pro)

#### Use cases:

* Using different themes for night and day
* Using several favorite themes (in no particular order)
* Trying out new theme, tweaking it, but in the end returning to the previous one

### PR DESCRIPTION
**Pull request by usernamehw**
My attempt at implementing theme-scoped color customizations #36860 .

update_theme
intellisense

- [x] IntelliSense in settings
- [x] Colors update on settings change
- [x] Colors update on theme change
- [x] Priority `scoped` => `customized` => `theme`

---
Settings example:
```json
"workbench.colorCustomizations": {
    "[Monokai Dimmed]": {
        "activityBar.background": "#66F",
    },
    "activityBar.background": "#ddd",
    "[Monokai]": {
        "activityBar.background": "#F66"
    }
},
"editor.tokenColorCustomizations": {
    "[Monokai Dimmed]": {
        "comments": "#66F",
    },
    "comments": "#ddd",
    "[Monokai]": {
        "textMateRules": [{
            "scope": "comment",
            "settings": {
                "foreground": "#F66"
            },   
        }]
    },
},
```

cc @aeschli

### CODE REVIEW

**Comment by usernamehw** [comment]
This 2 lines were looping through themes and the 2nd doesn't use it's argument. Is this suppose to be or better to move it out of the loop?
```typescript
colorThemeSettingSchema.enum = themes.map(t => t.settingsId);
colorThemeSettingSchema.enumDescriptions = themes.map(t => themeData.description || '');
```

**Comment by aeschli** [comment]
@usernamehw Looks good!
Only suggestion is to improve the way how the schema is constructed. What do you think?

**Comment by usernamehw** [comment]
It now registers configuration with properties as empty object so it doesn't have to rewrite them.

In addition it uses shallow copy instead of deep.

**Comment by usernamehw** [comment]
@aeschli I made some changes...

**Comment by aeschli** [comment]
Thanks a lot @usernamehw , great PR!

**Pull request merged**
