### PR TITLE
chore: update electron@30.3.1

### LINKED ISSUE #213780: Linux file dialog does not use default file path
Testing #213763

Version: 1.90.0-insider
Commit: fc8762e773c35d4e52e8a7375704af2e24698e5d
Date: 2024-05-29T05:51:07.154Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-107-generic

- open a file in an editor
- run `File > Open FIle`. This opens a file selection dialog initialized to the home folder

> It should open on the folder of the currently active editor

### LINKED ISSUE #217220: VSC keeps crashing
Type: <b>Bug</b>

The IDE keeps closing randomly in the middle of development.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700KF (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.58GB free)|
|Process Argv|--crash-reporter-id 99103022-9a73-45f3-a52b-f0726de9b663|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
composer-php-vscode|DEV|1.48.15635
phptools-vscode|DEV|1.48.15635
profiler-php-vscode|DEV|1.48.15635
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
php-namespace-resolver|Meh|1.1.9
laravel-blade|one|1.36.1
vscode-thunder-client|ran|2.24.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31077528

```

</details>

### PR DESCRIPTION
**Pull request by deepak1556**
https://releases.electronjs.org/release/compare/v30.1.2/v30.3.1

Fixes https://github.com/microsoft/vscode/issues/213780
Fixes https://github.com/microsoft/vscode/issues/217220

**Features:**

- WCO support for linux is now available in the runtime /cc @benibenj @bpasero

### CODE REVIEW

**Comment by deepak1556** [comment]
Following [task smoke tests](https://github.com/microsoft/vscode/blob/a82249586f2ecb480aaa74c6b908024f15519149/test/smoke/src/areas/task/task-quick-pick.test.ts#L42-L56) fail consistently on linux product build with issue opening integrated terminal, logs show the following error

```
The terminal process failed to launch: A native exception occurred during launch ("fd" must be a positive integer: undefined)
```

Tried a couple of debugging steps:

* Error is from https://github.com/microsoft/node-pty/blob/8fc21c99bf281cb2fd2921f89660cbf8649c4a2b/src/unixTerminal.ts#L117 specifically from the check in https://github.com/nodejs/node/blob/9e6c526f6c4e21b96f999869ceb265fb1891bf15/lib/tty.js#L55-L56 where `fd` is the result of [forkpty](https://github.com/microsoft/node-pty/blob/8fc21c99bf281cb2fd2921f89660cbf8649c4a2b/src/unix/pty.cc#L396)
* Interestingly, dev pipeline does not fail on the same smoke tests https://dev.azure.com/vscode/VSCode/_build/results?buildId=128302&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&t=f548697b-f1e3-56d7-b20f-10575b2a648b
* I was also unable to repro the failure locally by using the product build from the failing CI pipeline

```
yarn smoketest-no-compile --build <insiders-build>
```
* No changes in either [Node.js update](https://github.com/nodejs/node/compare/v20.14.0...v20.15.1) or [Electron update](https://github.com/electron/electron/compare/v30.1.2...v30.3.1) stands out that could cause this regression.
* Not so surprising but using the [node-pty version](https://github.com/microsoft/vscode/pull/225106/commits/e834f75959ffd0078708db764457e05ec0f3b6b6) before the [tty change](https://github.com/microsoft/node-pty/commit/391347926a45bb0b9e2c9a9f837adc56592b3c4b) does pass in product builds https://dev.azure.com/monacotools/Monaco/_build/results?buildId=287174&view=results, maybe this was an issue we had all along but still doesn't answer why only the current update makes it more consistent in CI.
* I am now trying to run product build with OSS electron to rule out any internal patches.

**Comment by deepak1556** [comment]
> Wonder if it is some kind of sandbox issue, will run with sandbox disabled as next step.

Still fails, I am out of ideas with a lack of repro. We need some logging in the node-pty module. @Tyriar @meganrogge can I disable the smoke tests to unblock this PR and create a follow-up issue to debug further. It would also help to see if we get any real world issues with repro around this failure.

**Comment by Tyriar** [comment]
@deepak1556 if it's erroring at `tty.ReadStream` it seems like this would totally brick a terminal. I'll leave it up to you on whether this should be merged in now or not based on what you think the impact will be and how fast better logging can be put in place.

**Comment by deepak1556** [comment]
The problem is that I don't have an idea of the impact given the issue only repros in the product CI. I will try these as next steps,

1) Disable the tests and merge the Electron update
2) Add logging to see why fd is invalid in CI
3) Additionally, wait for some real world repro to turn up
4) Enable back the tests eventually

**Review by Tyriar — APPROVED** [review]
CI network flake?

**Pull request merged**
