### PR TITLE
Make border bottom visible for panel actions on focus.

### LINKED ISSUE #23947: Panel action focus border is missing bottom in high contrast theme
image

### PR DESCRIPTION
**Pull request by Kiricon**
Fixes #23947

Actions where the same height as parent container causing bottom border to not display. 
Fixed by making actions 1px smaller so that bottom border matches top border.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Not a big fan of this change, the outer container is 35px so the inner elements should also be 35px. We should play with outline-offset instead of making all actions smaller only for the outline.

**Comment by Kiricon** [comment]
@bpasero I completely understand. I thought I'd just propose the idea considering other elements in the action container where less than `35px`. I can take a look and see if there is a less intrusive way of accomplishing it.

Thank you for the feedback! :smile:

**Comment by Kiricon** [comment]
@bpasero I Does my new solution seem accurate to fix the solution? 

Also I really appreciate your guidance. I'm not 100% certain what the best practices for design changes are as outlined by the vscode team. 

:sweat_smile:

**Comment by bpasero** [comment]
Thanks, your fix is good but targets the wrong element. I pushed this via https://github.com/Microsoft/vscode/commit/b90893cb31d73fbcda558343b04a79032e789139

**Pull request closed without merging**
