### PR TITLE
Add caching to CI workflow

### PR DESCRIPTION
**Pull request by dhadka**
Updates the CI workflow to cache the dependencies.  In testing, this appears to save ~1 minute per run.  

cc @ethomson

### CODE REVIEW

**Comment by joaomoreno** [comment]
Pushed an empty commit on top to get a new CI build and see the caching in action.

1 minute saving is pretty underwhelming... It there a specific reason why loading it up from a cache is not dramatically faster than running `yarn`?

**Comment by joaomoreno** [comment]
Oh I see... yarn still runs... but just takes packages from the cache.

We currently use a more general caching task in DevOps which caches the whole `node_modules` folder and dramatically cuts down time. It would be great to have something like this.

**Comment by joaomoreno** [comment]
I actually see this being detrimental to build times.

Looking at [Linux in `master`](https://github.com/microsoft/vscode/runs/321262795), the yarn step takes 4m14s.

With this PR there are two situations:

- [Cache miss](https://github.com/microsoft/vscode/pull/85557/checks?check_run_id=319990581): 1s for restoring the cache, same 4m20s for yarn and 36s for saving the cache.
- [Cache hit](https://github.com/microsoft/vscode/pull/85557/checks?check_run_id=321250818): 19s for restoring the cache, 4m2s for yarn and 43s for saving the cache.

So, a few observations:

- This cache doesn't seem to save any time at all. The time it takes to restore the cache and run yarn is slightly above the amount of time that it just takes to run yarn without any caching at all.
- The 43s saving a cache after a cache hit is just wasted time, since we're overwriting the same bits.

**Comment by dhadka** [comment]
Thanks for the feedback.  It looks like in the Cache hit scenario, the hash of the yarn.lock files changed so it saved the cache.  If the hash were to not change, the 43s for saving the cache would be eliminated.

I'll explore caching node_modules instead.  This caching mechanism is similar to the pipelines caching, so something similar should be feasible.

**Comment by joaomoreno** [comment]
Closing due to idleness.

**Pull request closed without merging**
