### PR TITLE
New tokens format & theme matching 

### LINKED ISSUE #3008: [themes] Flattening of text mate scopes leads to wrong coloring
- Open nodeAppInsightsTelemtryAppender.ts#40
- Notice broken colouring of comments inside contructor arguments

screen shot 2016-02-14 at 18 00 03

Other problematic languages with deep scope hierarchies:
- JSX tags
- Java

### LINKED ISSUE #11597: C++ code highlighting fails for large files
- VSCode Version: 1.4.0 date: 2016-08-04
- OS Version: Windows 7/10

Upgraded vscode installation,  the C++ code highlighting now starts to fail at around line 4000

The following file was used:  https://raw.githubusercontent.com/ArashPartow/exprtk/master/exprtk.hpp

The following screenshot demonstrates the problem: http://pasteboard.co/hJ6RUAZtU.png

The following is from the start of the file: http://pasteboard.co/hJ7kaH2X7.png

The following is from the end of the file: http://pasteboard.co/hJ7Gp4nLR.png

---

Tried other files with the same results:
- https://github.com/ArashPartow/strtk/blob/master/strtk.hpp
- https://github.com/ArashPartow/wykobi/blob/master/wykobi.inl

### LINKED ISSUE #16206: tmTheme highlighting issues in vscode (Material Theme)
[The Material Theme from the tmTheme editor](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Theme) doesn't render as intended per the tmTheme specs in vscode. I'm not sure if these themes are supposed to render in vscode exactly like they appear in the mtTheme editor?

- VSCode Version: 1.7.2
- OS Version: Windows 10, macOS Sierra/El Capitan

Steps to Reproduce:

1. Download and install extension "Material Theme" by Fredrik Averpil (that's me)
2. Enable extension and switch theme to "Material Theme"
3. Copy paste the following and set syntax to Python:

```python
def hello(some_option=None):
    """docstring here"""

    call_some_function(with_arg='some_string')
    self.call_other_function(with_arg='some_string')
    some_object.call_yet_another_function(with_arg='some_string')
```

### Expected highlighting

As per Sublime Text:

sublime

...and tmTheme-Editor:

tmtheme-editor

#### Note

The docstring is rendered differently in Sublime Text, which I guess is because of a customization for Sublime, so please disregard this.

### Actual highlighting in vscode:

vscode

#### Issues with vscode highlighting

* Function arguments are not highlighted in orange (instead they are red)
* Strings inside function calls are not highlighted in green (instead they are blue)
* Objects are not highlighted in blue (instead they are white)

### Additional information

The extension is using the exact same `.tmTheme` theme which can be downloaded from the [tmTheme-editor](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Theme). The theme is also maintained by Mattia Astorino and can be found in his git repo [here](https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme.tmTheme). The theme file from tmTheme-editor and from Mattia's github repo are very similar and they both produce the same highlighting issue in vscode.

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #11597
Fixes #16206
Fixes #3008

TODO:

- [x] Common
  - [x] adopt new tokens representation in model & co.
  - [x] remove paranoia check in `ViewLineToken`
  - [x] remove `model.getMode()` and `model.getModeId()`
  - [x] rename `LanguageIdentifier.sid` and `LanguageIdentifier.iid`
  - [x] remove `token` class name from every token
- [x] Standalone editor
  - [x] generate new tokens format in monarch and manual tokenizers
  - [x] align standalone languages tokenizers to generate classic style tokens
  - [x] clean up standalone tokens css rules and move them to JS
  - [x] match tokens using theme rules in JS for monarch and manual tokenizers
  - [x] expose new tokenization API in standalone editor
  - [x] adopt standalone languages tests for tokenization
  - [x] validate new tokenization using tokenization.html standalone test
  - [x] allow for theme switching in `standaloneColorService`
  - [x] allow for theme customization in standalone editor
  - ~~check editor with bootstrap css~~ (created follow up task)
  - [x] add inspect tokens command
- [x] adopt new `vscode-textmate`
  - [x] publish `vscode-textmate`
  - [x] get theme information to `vscode-textmate`
  - [x] reimplement theme integration tests
  - [x] allow for theme switching
  - [x] handle encountered languages while tokenizing
  - [x] remove `dom` layer breaker from `TMSyntax.ts`
  - [x] add inspect tokens command

### CODE REVIEW

**Comment by joshpeng** [comment]
@alexandrudima So all tokens are now hidden behind ```mtk__``` span classes when using Dev Tools? How do theme and grammar developers see the original tokens before it got flattened? We used to be able to use Dev Tools' element inspection.

This merge has caused an issue displaying key-value pairs with different colors, but without being able to see the new tokens I have no way to address it in tmThemes or custom grammars.

**Comment by aeschli** [comment]
@joshpeng You can use https://marketplace.visualstudio.com/items?itemName=siegebell.scope-info to see a hover with the scope hierarchy at the given position.
We also have #18068 to think about other features that can help theme and grammar authors. Please add comments there is you have ideas & requests.

**Comment by joshpeng** [comment]
@aeschli Thanks for the extension link, but this extension seems to only show the original VSC scopes. It doesn't seem to be capable of showing scopes from custom grammar extensions.

**Comment by joshpeng** [comment]
Before we could piggy back off of VS Code's ```.detected-link``` css class to stylize URL links with tmThemes. Now it doesn't work anymore after the flattening. Seems like the ```.detected-link``` is applied outside of the ```mtk__```. How can we do this now?

**Comment by alexandrudima** [comment]
@aeschli @joshpeng Please use `F1 > Developer: Inspect TM Scopes`

image

**Comment by siegebell** [comment]
@joshpeng scope-info should work for custom grammar extensions, but if conflicting grammars are provided by multiple extensions or vscode, then I bet it is picking the wrong one. With `"Developer: Inspect TM Scopes"`, perhaps the issue is moot, but feel free to submit the issue [here (with a reproducable example)](https://github.com/siegebell/scope-info/issues).

**Pull request merged**
