### PR TITLE
Add ability to reload a file icon theme without restarting the editor

### LINKED ISSUE #45963: [icon themes] Expose API to provide a dynamic icon theme.
This is an API feature request.

We at `vscode-icons` extension support project detection which dynamically re-generates our icon manifest file including or not project specific icons. Additionally to that, we provide the ability to the user to provide its own custom icons and more.

All these features, in the end, require the editor to be reloaded, simply because the icon manifest gets loaded at the start of the editor and with no ability to trigger a reload upon icon manifest recreation.
This results in a poor UX.

If we could have an API to trigger an icon manifest reload, we can have a much smoother transition between changes.

Relating request: https://github.com/vscode-icons/vscode-icons/issues/1177

//cc @robertohuertasm @jens1o @PKief @EmmanuelBeziat @LaurentTreguier @file-icons @DavidBabel @be5invis

### PR DESCRIPTION
**Pull request by JimiC**
Resolves #45963 

This PRs adds the ability to reload the file icon theme without the need to restart the editor.

@aeschli I also took the liberty to do some refactoring in `workbenchThemeService` and `fileIconThemeData` files.

The changes are:
- Switched `let` to `const` where applicable.
- I noticed that those files have `functions` that where used by the `class` but where outside them, so I moved those functions inside the `class`.
- Also, there are some helper inner `functions` written in an `es5` syntax, which I switched to `es6` syntax.

If those refactorings are unwanted, I have no problem to revert them.

I also value your guidance and input, in case I implemented this feature against the coding guidelines or the code can be improved.

### CODE REVIEW

**Review by ctrlaltvikas — APPROVED** [review]
LGTM

**Comment by aeschli** [comment]
@JimiC Can you make the changes minimal? No `let` to `const` or convert functions to methods unless really necessary.

**Comment by JimiC** [comment]
@aeschli Sure. I so much guessed that all these changes will not make the code review an easy task.

**Comment by JimiC** [comment]
@aeschli Submitted code with minimal changes.

**Comment by dotnetcanuck** [comment]
What's the latest status on this PR? I use `vscode-icons`, but the constant reloading is really starting to get annoying, heh.

**Comment by JimiC** [comment]
@aeschli 
I have resolved the conflicts with `master`. Do we have any news on the fate of this PR?

**Comment by JimiC** [comment]
@aeschli A watcher over the icon definition file would do the job as well.

Is there somewhere in the code-base a similar case so I can have a look at it and maybe provide a revised PR?

**Comment by aeschli** [comment]
The fileService has methods `watchFileChange`/`unwatchFileChanges` to enable/disable the watcher, `onFileChanges` is the event to listen to.

**Comment by JimiC** [comment]
Closing in favor of #66115

**Pull request closed without merging**
