### PR TITLE
Add color array support for bracket pair colorizer settings

### LINKED ISSUE #139777: More than 6 colors in Bracket Pair Colorization? (Rainbow?)
Hi!

First of all I appreciate the work done to improve this feature and make it so much more performant :)

Today I wanted to migrate to the new built-in bracket colorization feature but realized it doesn't support the color options of the original plugin. As far as I understand the VS Code implementation supports up to 6 colors, but is there any reason not to support the array configuration of the original plugin?

It would be beautiful, so I can keep using my rainbow brackets with the added performance improvement! 😄 

Here's my config:
```
"bracketPairColorizer.colorMode": "Consecutive",
    "bracketPairColorizer.showBracketsInRuler": true,
    "bracketPairColorizer.showBracketsInGutter": true,
    "bracketPairColorizer.consecutivePairColors": [
        "()",
        "[]",
        "{}",
        [
            "#ff0000",
            "#ff8000",
            "#ffbf00",
            "#ffff00",
            "#bfff00",
            "#00ff00",
            "#00ffbf",
            "#00ffff",
            "#00bfff",
            "#0080ff",
            "#0066ff",
            "#0000ff",
            "#8000ff",
            "#bf00ff",
            "#ff00ff",
            "#ff00bf",
            "#ff0080"
        ],
        "White"
    ],
```

And here's the beautiful result:
image

I would really appreciate this 👍🏻

### PR DESCRIPTION
**Pull request by FatalMerlin**
This PR fixes #139777 @hediet 

Description:
- adds array support to color.ts without affecting existing code
- adds support for color arrays in settings.json
- unifies BracketPairColorizer color properties into single array properties
- adds snippet support for color registration
- adds snippet for BracketPairColorizer properties to emit array snippets for users

### CODE REVIEW

**Comment by hediet** [comment]
Thanks for this PR! @aeschli what do you think of this feature?

**Comment by aeschli** [comment]
The good thing about using a map is that every value can be overwritten individually. With the array it's an overwrite all. The user that overrides such array would have to provide the same number of items.
The use case for this is in the user settings where users can customize the colors of a theme.

The in the code: `themeService.getColor` is used all over the workbench (over 600 references) that now all need to be adopted to handle arrays. Your PR hacked around this basically by casting. Sorry, I don't want to start this and don't think the array brings us any real benefits.

**Comment by aeschli** [comment]
Thanks for your efforts @FatalMerlin, but I don't want to go that road given the ripples this will have in the code. The current solution might be a bit verbose but is also the most flexible regarding overwriting individual colors.

**Comment by FatalMerlin** [comment]
@aeschli Thanks for your comments. However, how will you provide a solution to allow extensible color support for the migration of the bracket pair colorizer extension?

Also I don't quite understand why you say "that now all [references] need to be adopted", when this code is specifically designed so this is explicitly an opt-in feature. Even when editing the `settings.json`, you have to explicitly specify that the property supports arrays, otherwise VS Code will warn about the value type.

Additionally this change would have safe fallbacks in both directions, if a property is an array but the code expects a single value, this change would simply return the first value, and the other way around, if an array is expected you are guaranteed to receive an array.

While I understand your point about a map allowing to overwrite every value, from my understanding the array IS the desired value for this property because the purpose is to specify a list of colors in order, and in the spirit of the original extension I don't understand where you would want to specify or overwrite a specific color in this list.

Can you explain where the "ripples in the code" stem from so that I can improve the PR?

**Comment by aeschli** [comment]
You added an optional property `array` to Color. A color is now also an array of colors. That's a hack. There are 800 references to color, set over the wire, persisted in theme files, settings, user data. There's a command the generate a theme from the action values of the theme registry... 

Sorry, no.

**Comment by FatalMerlin** [comment]
@aeschli @hediet so is there any way that I can change the approach to implement it in another way?

What about explicitly adding a separate color array type, so it's not a hack and needs to be explicitly used as well?
I would really appreciate your help.

Can you maybe also tell me which commands fail that you mentioned?

Otherwise the extension remains deprecated and unmaintained but the built-in feature is not supporting the original functionality.

**Pull request closed without merging**
