### PR TITLE
chore: bump electron@7.2.1

### LINKED ISSUE #91824: [Arch Linux]: Toggle Developer Tools crashing
- VSCode Version: 1.42.1
- OS Version: Linux x64 5.5.6-arch1-1

Steps to Reproduce:

1. Install vscode using 'visual-studio-code-bin' package from AUR
2. Click Help->Toggle Developer Tools -> watch it crash

Does this issue occur when all extensions are disabled?: Yes/No

Yes, both with running --disable-extensions and when no extensioins are installed.
(This issue exists with both VSCode and VSCode-Insiders for Arch Linux).

Running with no extensions installed (Terminal output):
image

Running with --disable-extensions (Terminal output):
image

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/91824

### CODE REVIEW

**Comment by charbelnicolas** [comment]
Do you guys know when VS Code will be adopting electron version 8?

**Comment by deepak1556** [comment]
@charbelnicolas please refer to https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209

**Review by bpasero — APPROVED** [review]
@deepak1556 why would we not go with latest 7.2.x?

**Comment by deepak1556** [comment]
The release wasn't available when I made this PR, just published the release. Will update this PR shortly :)

**Pull request merged**
