### PR TITLE
Keep expanded items open after rename.

### PR DESCRIPTION
**Pull request by ntovas**
@isidorn i think its ok, if you want to move the implementation on treeModel i can do it but not before sunday. 
#44230

ps: maybe there is some formating issues. i did this from my phone. :)

### CODE REVIEW

**Comment by isidorn** [comment]
@ntovas you should not touch the treeModel for this.
Tree should have some api to get all expanded.

I will review this PR next week as we are currently in the endgame and are wrapping up our milestone

**Comment by ntovas** [comment]
@isidorn I will create an api for this until next week. 
I am thinking to take a parameter to return the expended childrens and if no parameter was passed to return all the expended for the workspace.

**Comment by isidorn** [comment]
@ntovas probably not the best idea, we take only limited changes in the tree area.
fyi @joaomoreno as the tree owner

**Comment by ntovas** [comment]
@isidorn So i should leave it as is and let someone more experienced contributor to refactor it?

**Comment by joaomoreno** [comment]
The tree doesn't need new API for this. The explorer knows about the rename operation. It knows about expansion states of all elements. It should easily be able to reset those expansions.

**Comment by ntovas** [comment]
@joaomoreno as far as i checked the code, there is no method to get all the expanded items. 
The current implementation is hidden inside the method onFileOperation() of explorerView, i believe thet it will be better to be implemented as stand alone method in order to be used in other cases and keep the DRY principle.

@isidorn do you think that there should be some limitation to recursion in order to avoid edge cases ex symlink loop?

**Comment by joaomoreno** [comment]
There is a `getNavigator` method and a `isExpanded` one.

**Comment by ntovas** [comment]
@isidorn  is it ok now?

**Comment by isidorn** [comment]
@ntovas thanks for your work. However a proper way to do this is as @joaomoreno already specified by using the tree navigator. That will make the code much less complex and no need for an additional helper method. Please try that approach

**Comment by isidorn** [comment]
Closing as outdated

**Pull request closed without merging**
