### PR TITLE
Produce official ARM and ARM64 builds

### LINKED ISSUE #1031: Feature Request: Chromebook support
Logging this on behalf of Ed Price at Microsoft

Per this article (https://www.yahoo.com/tech/why-google-is-beating-apple-in-the-battle-for-the-142410097.html), schools are moving away from iOS/Apple devices and onto less expensive devices that run Chrome OS.

There's discussion on a related Microsoft-educator Yammer group about how we need Visual Studio Code to work on Chromebooks and related devices so educators can continue using to for teach AP Java (or other languages) Computer Science courses.

Feel free to email me or Ed Price for more info.

### LINKED ISSUE #6442: Official Support for ARM/Raspberry Pi Linux (armhf, arm64)
- VSCode Version: > 1.1
- OS Version: Ubuntu Mate / Linux

It would be good if VS Code Supports Raspberry Pi 2/3 or provide arm binaries alongside the x86 and x86-64 binaries for linux

### PR DESCRIPTION
**Pull request by joaomoreno**
- [x] Update linux build agents with cross compilation toolkit https://github.com/microsoft/vscode-linux-build-agent
- [x] Update pipelines
- [x] Fix ripgrep ARM 32 https://github.com/microsoft/vscode-ripgrep/pull/15 @roblourens 
- [x] Produce deb and rpm packages
- [x] Complete Electron adoption
- Update linux publisher to publish to MS repos https://github.com/microsoft/vscode/issues/106473

Fixes #1031
Fixes #6442

### CODE REVIEW

**Comment by joaomoreno** [comment]
image

**Comment by Helianthella** [comment]
@joaomoreno works perfectly on my chromebook. I am even able to install Codespaces but I can't actually connect to any codespace:
1. sign in to Codespaces
2. attempt to connect to a Codespace
3. VSCode Insiders asks you to sign in again
4. after re-signing in, the extension keeps saying "signing in..." and hangs there forever

(this might be the wrong repo to report in though)

**Comment by Azhe403** [comment]
What about apk, is possible?

**Comment by rumlyne** [comment]
Installed it on my pinebook pro (arm64) and so far it runs flawlessly.
java extensions & running java code out of vscode works.
flashing of devices via platformio works for the most part (some flashers don't run on arm)
Bumped the aur maintainer so one can now comfortably build vscode insiders on arch(based distros).

**Comment by maks** [comment]
I installed the armhf build on my HP Chromebook 14 G3 (tegra k1) and it runs nicely in crouton 🎉 , though I needed to start it from within an xterm running with xiwi as for some reason trying to start it directly from a shell using the xiwi command didn't allow it to connect to the chrome extension for crouton. This is running directly, without installing a X desktop. 🎉

**Comment by ihakh** [comment]
I cant download from https://code.visualstudio.com/download

**Comment by pfeerick** [comment]
Because 1.50 hasn't been released yet! Looks like the release date is the 13th of October, so you should be able to download a release build after then. Otherwise, use the links given above in :  https://github.com/microsoft/vscode/pull/106289#issuecomment-691076575

**Pull request merged**
