### PR TITLE
#17670 set FilePermission.Readonly from stat.mode & 0o200

### PR DESCRIPTION
**Pull request by jackpunt**
for #17670 

Test: 
chmod 400 test.txt
observe that test.txt (and other files without chmod 200) show in editor with 'lock' icon, and editing is blocked.
chmod 600 test.txt
Observe that test.txt shows without the lock icon, and is editable (and edits can be saved)

**This** PR is for files where the edit-ability/write-ability is controlled by the filesystem.
There is a PR (#161716) for edit-ability (of writeable files) controlled by BlobPattern in settings.

### CODE REVIEW

**Comment by bpasero** [comment]
I would think such a change at the minimum needs to be behind a setting that the user can optionally enable. Today we do not block editing so that you can still make changes and:
* either "Save As..." to a different location
* "Overwrite" and thus remove the readonly bit on disk

**Comment by jackpunt** [comment]
Totally agree! 
This should be _optional_

With #161716 and the associated code & keybinding supplied in branch [files-readonly-active](https://github.com/jackpunt/vscode/tree/files-readonly-active) with _readonlyToggle_ you get all the choices/capabilities.

1. filesystem [stat] non-writeable files initially non-editable.
2. files marked semantically _non-editable_ initially non-editable.
3. with a keystroke you can toggle the non-editable status on the current buffer.
     (other keystrokes can SET or CLEAR the non-editable flag)

Something for everyone!

The code for "keyboard/interactive" control of the non-editable state relies on base code in #161716
so I wasn't clear on how to do a separate PR for that functionality.
But if you want it all, I can merge it all into the PR #161716

More to the sense of your comment: 
We could also add a boolean setting like: `files.letMeEditNonWritableFiles` or `files.allowEditNonWritable` or `files.nonWriteableInitiallyEditable` that a user/workspace could set to make filesystem non-Writeable files initially editable (for backward compatibility) the point being that one can still override with keystroke on per-buffer basis.

Given the confusion about "readonly" I'm trying to consistently use "nonEditable" (for the editor state) and "nonWriteable" (for the filesystem state)
Maybe even change the proposed setting names to follow that convention.
(but then: people searching for "readonly" may not find the settings?)

**Comment by jackpunt** [comment]
I've been looking at adding a setting to maintain the legacy/backward-compatible feature to ignore file stat.mode when asking about 'Readonly'

`fileService.hasCapability(this.resource, FileSystemProviderCapabilities.Readonly)` is  called in a couple dozen places.
and *I* don't know which would be adversely affected by being presented with the _actual_ file stat.mode...
So it would seem that to maintain compatibility, one would need to apply the setting ("ignoreStatModeForReadonly") in diskFileSystemProvider.ts; so this PR would be:

	permissions: this.legacyStat : undefined ? (stat.mode & 0o200) === 0 ? FilePermission.Readonly : undefined; 

And use `configurationService.onDidChangeConfiguration()` to set this.legacyStat to follow the 
 value of "files.ignoreStatModeForReadonly"
[injecting configurationService into diskFileSystemProvider]

**Would that satisfy** _"needs to be behind a setting that the user can optionally enable"_ ?

[as always, I defer to you for the actual name of the setting]

**Comment by jackpunt** [comment]
May need some help on this:
How to get the 'configurationService' to use in diskFileSystemProvider?
The constructor already has required & optional args (and no InstantiationService injections) so it is non-trivial to just add an injection argument (without rewriting all existing invocations of the constructor)
Is there a way to get the extant InstantiationService or the ServiceCollection and so to obtain the IConfigurationService ?

-- EDIT --
Plan B: (actually simplifies things)
* Merge this PR with #161716 
Now we can consolidate the logic into ReadonlyHelper.isReadonly()
 `(this.legacyReadonlyStat ? false : this.lastResolvedFileStat?.readonly) ||`
And ReadonlyHelper already has a listener for `onDidChangeConfiguration`

This feature [_conditionally honor file system stat.mode & 0o200_] is now included in #161716

**Comment by jackpunt** [comment]
Note: this 'stat-read-only' branch is now identical to the 'files-readonly' branch. (see #161716)
Because I expect we want to take both sets of mods, and the code is mostly common.

If you want to have 'stat-read-only' **without** the globReadonly capability, I can remove the settings/contributions from this branch. (but that until that determination is made, it is just extra work to keep two distinct branches)

**Comment by bpasero** [comment]
Lets merge into https://github.com/microsoft/vscode/pull/161716

**Pull request closed without merging**
