### PR TITLE
Implement new notifications UX

### PR DESCRIPTION
**Pull request by bpasero**
flicker_chrome58

### CODE REVIEW

**Comment by jens1o** [comment]
Are we sentenced to use the new UX?

**Comment by bpasero** [comment]
@jens1o what?

**Comment by gulshan** [comment]
I think some sort of separators between different notifications would be nice. From the screenshot, it's hard for me to distinguish consecutive unselected notifications.

**Comment by jens1o** [comment]
@bpasero Is there a switch to get the old notification ux back? Or do we need to use the new one as soon as it is done?

**Comment by bpasero** [comment]
@jens1o the new notifications UX replaces the old one entirely. Why would you want to switch back?

**Comment by jens1o** [comment]
>  Why would you want to switch back?

Because the old notification is something that only vscode has, and I like the charm and the uniqueness.

**Comment by HazardDev** [comment]
Just going to put it out there that this is exactly what I was hoping for in terms of notifications.

- bottom right
- expandable
- small icon to show importance
- source is visible

I presume there will be some configurations for

- time to live
- max number to have on screen
- smart groupings by source (disabled would be purely based on time created)

I'm hoping there will be keyboard shortcuts to open and close the notification center, navigate through notifications and expand or close them, and press various buttons on said notifications. What's the thoughts on that?

**Comment by bpasero** [comment]
> Because the old notification ux is something that only vscode has, and I like the charm and the uniqueness.

Interesting, I hope there are not many that think like that. The old notifications never actually got any UX treatment, it was literally our first iteration without any UX thoughts. I think I do not have to repeat how many issues the old implementation has, but the biggest issue is that it covers the tab area or worse even the editor if there are multiple. 

@HazardDev yes the notifications are fully keyboard accessible. I have not thought about the other points yet but there will probably be some settings to control things coming later.

**Comment by jens1o** [comment]
> Interesting, I hope there are not many that think like that. The old notifications never actually got any UX treatment, it was literally our first iteration without any UX thoughts. I think I do not have to repeat how many issues the old implementation has, but the biggest issue is that it covers the tab area or worse even the editor if there are multiple.

It's like Microsoft and the Double-Click where you sold the license from Apple, but the users do not want a single click to execute programs.

**Comment by bpasero** [comment]
@lukewis here are the keybindings:

image

**Comment by lukewis** [comment]
@bpasero Wow.  Never knew that existed.  Opened up a whole new world for me!  Thanks for helping out a newbie!

**Comment by ndarilek** [comment]
VSCode newbie here. I'm a screen reader user and am struggling with this issue. After chasing it through several closed/locked issues, I've found this PR, which includes an image I can't read of the relevant keybindings. :)

First, is this fix available in whatever version I'd get if I go to the download page and perform a fresh install? I don't have the relevant VM booted so I'm not sure what version I have, or if I still need to be on the insider build. This installation is new as of yesterday, so is fairly representative of what a new user would get.

Then, how do I go about interacting with notifications via the keyboard? I can tab to them, but any yes/no notifications are unusable to me. Ironically I hit this with the initial "Are you using a screen reader?" notification, which I couldn't click Yes on. :) I've looked through accessibility documentation, but haven't found anything about interacting with notifications.

Thanks.

**Pull request merged**
