### PR TITLE
Add Julia grammar

### LINKED ISSUE #105229: Julia extension in the core VS Code product
It seems like the grammar of a number of popular languages are shipped out-of-the box with VS Code because they have an extension in https://github.com/microsoft/vscode/tree/master/extensions.

What are the criteria for being included there? Would Julia be a potential candidate to also ship like this? Would be great if you could share a bit about the pros and cons of that, I think I don't fully understand the implications at the moment of being included there.

We (the Julia extension team) could probably prepare a PR that would add this and would also be happy to maintain this.

Are there any guidelines about splitting a given language support up into one extension that ships with the core product and then a second extension that ships on the marketplace?

### PR DESCRIPTION
**Pull request by pfitzseb**
This PR fixes #105229 by adding a Julia grammar file pulled in from https://github.com/JuliaEditorSupport/atom-language-julia.

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks a lot @pfitzseb !

**Comment by davidanthoff** [comment]
Once this is merged and shipping, do we remove these parts from the Julia extension? Or is it best practice to still ship things in our extension in addition to having it in the core VS Code?

**Comment by aeschli** [comment]
It would be best if you remove the duplication (grammar, language definition, language configuration) and instead depend on the basic extension.
You can always temporarily adding them back,e.g. if needed for an urgent fix when you don't want to wait for the next VSCode stable.

**Comment by pfitzseb** [comment]
What's going on with the conversion code? Is this something I can/should fix upstream?

**Comment by aeschli** [comment]
We had a bug in our grammar updater related to unicode. I pushed a fix 5cfa6b7e263f01d48be0f0605deec629f0853682 (https://github.com/microsoft/vscode-grammar-updater/commit/3c5e198906afffb5070e42ba381c48f0fe3d6a65)

Thanks a lot for all your work @pfitzseb !

I added a [Julia sample code](https://github.com/microsoft/vscode/blob/master/extensions/vscode-colorize-tests/test/colorize-fixtures/test.jl) that we use to run tests against. Feel free to have it cover more Julia syntax.
We use it to understand the changes after a grammar or theme update. We compare the [tokens generated can colors assigned](https://github.com/microsoft/vscode/blob/master/extensions/vscode-colorize-tests/test/colorize-results/test_jl.json) with the last known result.
It's perfectly fine to update the expected test results after a grammar update if we think the changes are making sense,

FYI @alexr00

**Pull request merged**
