### PR TITLE
Make hidden fold ranges independent of range provider, add manual fol…

### PR DESCRIPTION
**Pull request by PieterBranderhorst**
These changes accomplish two things:

1. Ranges of lines which have been collapsed (folded) are remembered and remain folded even when a subsequent call to the folding range provider does not include the collapsed range in its returned ranges. This change prevents spontaneous unfolds of ranges which the user has hidden in two known situations:
1a. When a folding range provider misbehaves or responds slowly.
1b. When ranges temporarily disappear due to changes such as removing the end marker of a comment block.

The saved view state for an edited file includes the currently hidden ranges. To prevent these from being incorrectly applied when the file is changed via an external process and then reopened in vscode, a checksum of each folded range has been added to the saved view state.

2. Added a user command to fold an arbitrary group of lines by first selecting the lines and then invoking the command. The default keyboard assignment for this is {ctrl+K, ctrl+.}
This command wasn't possible before change (1) above. It is added now because it is possible, seems very desirable, and is useful in testing (1) above.

Testing:  All previous fold functionality should remain the same. Except when a user manually folds a group of lines which overlap a fold group defined by the range provider. In that situation the code now removes the overlapping region(s) from the range provider until the user unfolds the overlapping manual region. The new functionality can be tested by using the new ctrl+k ctrl_. command and/or creating open-ended comments which surround previously folded regions.

### CODE REVIEW

**Comment by PieterBranderhorst** [comment]
Martin, a note in case you are concerned about added cpu load for the changes I proposed.

The added cpu time for these changes is very small relative to the total cpu time spent on folding.

Excluding the range provider, i.e. considering only the code which executes after the range provider returns its results, I think we could reduce the cpu time related to folding to be well below 1/5th of what it is now with a bit of work. If that is something you'd like to see from me I'd be happy to propose code changes for that.
Currently the great majority of time is spent I think in the underlying editor's decoration related functions. The key would be to minimize calls to those functions.

**Comment by PieterBranderhorst** [comment]
Now added to this PR: A configurable folding regions limit and a user notification when the limit on number of folding regions is exceeded.

**Comment by PieterBranderhorst** [comment]
Hi Martin. No problem, now I know. I've reverted the configurable folding regions limit out of this PR. (Didn't think it was safe to delete commits so I used revert.) And submitted a new PR, #140480, with just the configurable limit in that one.

**Comment by PieterBranderhorst** [comment]
I merged current main into this to handle conflicts in folding.ts.

**Comment by PieterBranderhorst** [comment]
Martin, any news on this? I don't want it to get stale. I see there are now merge conflicts. I can deal with those if you are ready to handle this after I check that in.

**Comment by aeschli** [comment]
Yes, sorry for the wait. I'll review it next week.

**Comment by PieterBranderhorst** [comment]
Ok, thanks Martin. I have updated the branch to match current main branch.

**Comment by aeschli** [comment]
I started reviewing and testing. I like the approach.

I investigated the following issues:
Create typescript file:
```ts
class A {

    foo(p: A) {
        const foo = 9;
        console.log('fff' + p + foo);
        if (true) {
            console.log('fff');
            console.log('fff');
            console.log('fff');
        }
        console.log('fff');
    }
}
```
1.
- collapse `foo`
- set the cursor on the line above 'foo', press enter
- `foo` expands
- the problem is in `_currentHiddenRegions`, `isBlocked` is tested against the old range positions. Should test against the current positions (using getDecorationRange)

2.
- Set the cursor after `foo(p: A) {` and press enter
- The range stays folded, but no longer covers the last line
- the problem is that for the end line the old range info is used (`hiddenRange.endLineNumber - hiddenRange.startLineNumber`)

The decoration currently only covers the first line. I think we need to change to cover the full range to correctly preserve the folded range.

**Comment by PieterBranderhorst** [comment]
Thanks very much Martin.

And thank you for finding those issues. My apologies.

I'm embarrassed by the first one. As you say, the problem is in `isBlocked` using the old positions.
Now that the code is in a branch in the Microsoft repository I don't know how I should submit a correction. I think the following would be a minimal change to fix that bug. In foldingRange.ts replace:
```
    if (!isBlocked(hiddenRange.startLineNumber, hiddenRange.endLineNumber)) {
        let decRange = this._textModel.getDecorationRange(this._editorDecorationIds[i]);
        if (decRange
          && decRange.startColumn === Math.max(decRange.endColumn - 1, 1)

```
by
```
    let decRange = this._textModel.getDecorationRange(this._editorDecorationIds[i]);
    if (decRange && !isBlocked(decRange.startLineNumber, decRange.startLineNumber + hiddenRange.endLineNumber - hiddenRange.startLineNumber)) {
        if (decRange.startColumn === Math.max(decRange.endColumn - 1, 1)

```
The second problem is tougher. Typing into a collapsed range seems wrong and I could argue either way for whether the new text should remain visible or not.  Maybe a third choice, should the range automatically unfold when a user does that?  

It gets nastier. Suppose that the first line of a folded region, the one which remains visible, is something like `if (xxx) { // do something`. If the user hits enter in front of the `{` the resulting hidden region should be different than if they use enter after it. And the same is true of the terminating line if it looks like `    } // the end`

I played around with making the decoration region include a larger block of the text and things are still problematic that way. The best overall result seems to come from starting the decoration at the last character + 1 of the region and ending it at the first character of the line following the region. But it isn't perfect, especially when considering the cases mentioned above. And I'm not sure about possible consequences to other parts of the editor from having large decoration ranges hanging around.

I want to mull this over a bit. Maybe there's a simpler way.

By the way, do you recall the reason for the "isBlocked" test? I.e. under what conditions there can end up being an active selection point inside a hidden range when "update" is called?

**Comment by PieterBranderhorst** [comment]
I've explored the code which handles decorations. It is very nice. I don't think that increasing folding region decorations to cover their full range will trouble it at all. I think you were right about that as the way to go. I've ended up using the from start line's last column to the end line's last column + 1. That seems to work well in many cases. I've tested with adding text at end of first line and start of last line. Destructive backspace from start of end line un-collapses the fold. Global replace of something inside a hidden region which contains an end of line mostly works well. There are cases which misbehave, e.g. global replace which spans the start or end of a hidden region. That could be fixed by adding local (to folding) code which processes onchange events. And that might be desirable as part of an optimization effort. But for now it seems an acceptable oddity.

With this fix, all edits done in the visible line above and below a hidden region remain visible until the hidden region is unfolded by the user. To me that makes the best sense. It could be argued that some typed changes should disappear into the hidden region but I think that's just too disconcerting.

There are three places changed in foldingModel.ts for these fixes. Can you compare and pick them up from [this copy](https://github.com/PieterBranderhorst/vscode/blob/KeepCollapsedFolds/src/vs/editor/contrib/folding/browser/foldingModel.ts)? Or is there another way I should post it?

**Comment by aeschli** [comment]
Thanks @PieterBranderhorst !
I see your commits on the branch. Also the `foldingMode.ts` matches what you have in [this copy](https://github.com/PieterBranderhorst/vscode/blob/KeepCollapsedFolds/src/vs/editor/contrib/folding/browser/foldingModel.ts).
What's not working?

I haven't yet tried out your latest, so just to reply. What you write is all correct.

- The decorations should not more expansive if they cover a range. BTW, there are also several options to configure them how they behave when editing happens at the start and end offset. We want to test with operations like format that typically create a lot of modifications.
- The first line is officially not part of the folding range and editing in it should not expand the range
- IsBlocked ensures that the current cursor positions never end up in folded regions. The enter just before `...` is one example and when you remove a `}` at the end and the folding provider decides to expand the range.

What would be good to have some unit tests. The very least for the merge function.

**Comment by PieterBranderhorst** [comment]
I didn't understand how github would handle my push at this point in the process. All is well.

I am working on adding some unit tests. I expect to finish and push them tomorrow.

**Comment by aeschli** [comment]
Thanks @PieterBranderhorst 
The test case where I press enter right before the `...` is still not working, the range does not expand. I would say the fix is to change the [stickiness](https://github.com/microsoft/vscode/blob/6db11082dec6b08632d64a608b842eabf925fb87/src/vs/editor/contrib/folding/browser/foldingDecorations.ts#L21) to `AlwaysGrowsWhenTypingAtEdges`. That way the range will expand.

Another test case is to press enter right before the `{`. The range stays folded. When the new ranges come in from the TS folding provider we end up with two folding ranges. One starting at `foo` expanded) and one at `{` (folded). Expand the folded, and the range goes away.
It's the expected behavior with the approach, just a bit surprising.

**Comment by PieterBranderhorst** [comment]
Hi Martin. Is this PR stuck because of the failed automatic check? I see that it failed in "Run Monaco Editor Checks". The files it seems to have a problem with aren't related to anything I modified. And when I try running " yarn monaco-compile-check" on my checkout of same thing it runs fine. I don't know what to do next.

**Comment by aeschli** [comment]
@PieterBranderhorst I was on vacation last week. Sorry that this is not going quicker, but I also in regular work weeks I don't get much time to look at it. Please be patient.

**Comment by PieterBranderhorst** [comment]
@aeschli Might you perhaps transfer this task to someone else?

**Comment by aeschli** [comment]
Sorry for the wait. I'm afraid there's no one else that knows the folding code as I do.

I've given it another morning of testing. It's still far too easy to get in funny situations. 

- detached `...` decorators, located somewhere in the middle of the code
- folding ranges that don't open when modifications are made.
- folding regions that can be expanded but vanish right away once expanded.

fold3

I'm afraid this is not in a state that we can release it. In no time we will be flooded with issues.

Maybe we put this behind an experimental setting so that other users can try this out in real world project?

**Comment by PieterBranderhorst** [comment]
All of the behaviour in that GIF is as expected to me. It is working as I tried to explain in my note of February 9. With one possible small exception but that's not important for now I think, what's more important is the overall behaviour.

The rule the new code attempts to apply is "lines which are collapsed by the user and only those lines stay collapsed until the user expands them." I think that's more explainable than the previous rules.

I had hoped that you'd either find that an agreeable rule or suggest a different one. V.s. the production code which doesn't have an overall principle which I can easily describe. As I noted on February 9 the production code includes some behaviour which I think is rather bad. As well as having the underlying problem which was the original reason for this branch, the unwanted auto expansion of hidden regions in some situations.

You are of course the arbiter of this. I have a sense that you aren't much interested in folding enhancements and I understand that. There's no reason that you have to be interested. I have at least two more sets of folding enhancements I'd like to propose. (Visual indication of the code involved when hovering over fold icons in the gutter; language defined named types and associated fold/unfold commands and default fold-on-open settings.) If you have no enthusiasm for going there then I'd rather know and not put any time into them.

If you want to put this branch under an experimental setting then let me know and I'll recode it for that. How would that work? Am I right to guess that we'd add one setting which controls whether this code is enabled, and then rework the code so that all changes I made in this branch are conditioned on that setting?

I do think there are a fair number of users who'd like better code folding. In particular I think the "fold selected lines" command (ctrl+K ctrl+.) introduced in this current branch would get a lot of use. Personally that's the single folding feature I would most use if there were an editor which had it. Some features would probably get more use by people who process/analyze things like log files. I haven't seen an editor which does folding especially well overall and that makes this hard to predict.

I would happily do this stuff in an extension if I could. But I can't. To do so would require additions to the extension API which would allow an extension to take over the handling of what is collapsed at any given time. Would you object to adding such an API? I'm not sure how it would look. I think it would have to be called each time the fold decorations and/or the editor's hidden regions are to be updated, with a list of all regions from the folding range providers. And then skip telling the editor about decoration and hidden state changes, leaving that task to the extension when it exists.

BTW I have been working on making my suggested rule-driven folding range provider from last fall into an extension. I have it working. And I've added indent-based folding and another useful option to it. So it could now entirely replace indentRangeProvider. I like the job it is doing for typescript folding better than the default typescript provider. I have some challenges making it worthwhile for end users because of setup issues. I'll probably end up asking for some enhancements related to that, e.g. a way to specify a default folding provider, a way to select a single folding provider for a language, and adding an alternate of string to the enum currently available for folding region types.

**Comment by aeschli** [comment]
Yes, absolutely, the behavior is all expected knowing the how the new approach works. 

The old (current) approach couples the ranges tightly to a syntax element. Once the syntax element is gone, the range is gone and expanded. Not always what the user wanted, but IMO easy to explain.

From a user's standpoint (just me, I admit), I think ending up `...` somewhere in the code with a clear indication what it is folding is confusing.
Some of it can be fixed by refining when to expand on editing:  Enter after the `...` or at the beginning of the last collapsed line should unfold.

And maybe `...` is not ideal for the new approach and needs to be replaced with a placeholder that shows more about what is collapsed, e.g. `{..}`.

My problem is, I have no time budget for the folding feature. It is low on our team's priority list. I can't really afford getting many issues after a change. So we need to keep the changes small. But I also don't want to stand in the way.

If you want to continue to work on the feature and get other users opinions, we should but the new behavior behind a setting.
I'm also open to new API. Mayb eit would work if the folding provider can also give the folded state? Just a wild thought.
Or we focus on the fold selection feature, which has many requests.

Just to say it again your help is very welcome

**Comment by PieterBranderhorst** [comment]
Ok, I understand. I'm going to explore the options you mention a bit to see what tradeoffs and limitations there are. In order of preference:

1. Focus on the fold selection feature. Without changing any existing behaviour in a way which could generate ongoing user issues.
2. Enable this stuff via a new extension API.
3. Put this stuff behind an experimental setting.

I think I know what choice 1 should look like. It requires more code on this branch because manually collapsed ranges can't be automatically adjusted. My plan for choice 1 would be:

* Add a flag to each folding range indicating whether it is "manual" or "provider".
* When a folding range is added from a memento or via fold-selection it is marked as "manual". Otherwise it is marked "provider".
* When a range provider returns a range which matches an existing "manual" collapsed range that range is changed to "provider". This will handle delayed response from a range provider after opening or switching to a file.
* When a user edits the line before or the line after a hidden region:
  + If the change directly affects the hidden lines, i.e. delete key at end of first line or backspace at start of last line, expand the hidden range.
  + If the hidden lines are a "provider" range then what's hidden will change to match the new matching range returned by the range provider when it "makes sense". That's the same as the current production code with some auto-expand cases added. E.g. if the user deletes the closing "}" for a hidden range which goes from line 10 to 20 we might then get a range going from line 10 to 50 from the provider. In this case the code will auto expand the hidden region.
  + If the hidden lines are a "manual" range then what's hidden stays the same. All new typing outside the range stays outside the range.

When I've explored enough of choice 2 and 3 to make a recommendation between them and the above I will post here again.

**Comment by PieterBranderhorst** [comment]
@aeschli I've looked at 3 choices for how to proceed. I don't know enough about choice 3 to have a recommendation. I'd like you to choose among them if you don't mind.

Summary:
1. Continue with current approach.
2. Add APIs which enable extensions to provide more folding enhancements.
3. Put folding enhancements behind an experimental setting.

I think we don't want choice 1 unless neither of the other approaches looks good. Choice 1 puts the largest demand on your time. If neither other choice looks good then I think I should continue on this branch with a rule that no existing vscode behaviour is to change. And with knowing that it can take some time for you to get to reviewing.

Choice 2 requires extension API enhancements. I think the simplest ones which would enable an extension to do the work in this branch are:
* Modify registerFoldingRangeProvider to have a new optional parameter indicating the provider type. Default type is "provider", new possible type is "controller".
* Add a new optional field to the returned FoldingRange structure: isCollapsed, a boolean.
* In syntaxRangeProvider change the calling of range providers and collecting their results into a two step process. Step 1 calls any non-controller providers and gathers their results. Step 2 calls the controller providers, passing them current hidden ranges and the results from step 1, and gathers their results. Then merge the results from the last stage which ran and return them as is currently done.
* After each call to "compute" if a controller provider exists use the collapsed flags returned by the range provider(s) to update (replace) the current hidden ranges.
* A new function extensions can call: recalculateFoldingRanges.

The things done in this branch can be implemented with choice 2. But it would still be limited in what can be done in future without your careful review. Things like settings for provider priority and highlighting folding regions on mouseover wouldn't be possible via code in an extension. (But some of their implementation could be in an extension by adding more APIs.)

I don't know enough about choice 3 to assess it. If we put changes behind an experimental setting then:
1. Would it relieve you of most of the effort in reviewing and testing proposed changes? Or would they still create a large demand on your time?
2. Would it be reasonable to start by copying folding.ts to new file experimentalFolding.ts and then invoke the new class when the experimental folding flag is turned on? That would make it very easy to confirm that the new code doesn't break anything in non-experimental operation. V.s. single sourcing which would require a harder look, especially when there's a new class member or bits of code move in refactoring. If a separate file and class name is used then the new code can of course still be diff'd vs its starting point.

What do you think? Should I get going on either approach 2 or 3?

Thanks,
Pieter

**Comment by aeschli** [comment]
I was thinking of a setting like 'Always preserve folded regions`. At first, the setting would be disabled by default and have an 'experimental' in its name. The setting only affects ranges provided by folding providers that were folded but no longer reported. With the setting disabled, we would get the current (old) behavior they would be expanded). With the setting enabled, they would be preserved.
Ranges created by the 'fold selected' action would not be affected by the setting. Such ranges would always be preserved. 

I suggest we first start with `fold selected range` to run with the current `FoldingModel.update` behavior. Have one PR for that that we can commit. After that, work on a second PR with the setting. But of course, whatever is easier.

What do you think?

**Comment by PieterBranderhorst** [comment]
I'm not wild about that approach. Two problems:
1. In the current branch code fold-selected came out as an almost free side-effect. It only needed the command handler added which is simple code. If fold-selected goes first it either gets most or all of that code anyway, or it is implemented with different more specific code which then either ends up with functional overlap or ends up needing to be refactored back to where we are already.
2. Fold-selected isn't what we started out to handle. While it may be a new feature a lot of people would like, we started out to address a problem users are experiencing with the current code. A serious problem for those who experience it.

I would prefer to further modify the current branch to recreate the existing behaviour when people edit the code at either end of a collapsed region (which is approach 1 above) or take approach 2 or 3. Much of those modifications (e.g. identifying the type of each hidden range as manual vs. provided) is code which would be needed anyway if doing only fold-selected.

**Comment by aeschli** [comment]
No problem for me if you want to continue to modify the current PR code and not breaking the task up.

But are you ok with havening a setting that let's users to choose between the keeping collapsed regions or discard them if they are no longer reported? As said, when I tested I was not a big fan of having collapsed regions that no longer match a language construct. But I'm interested to see more users try this and report feedback.

**Comment by PieterBranderhorst** [comment]
Ok, I will continue via the current code. Making it match previous behaviour as much as possible. When done I think there may be just two cases where behaviour while the user is editing will be different. Let's see how close I can get it and then decide whether you still want that setting added.

This branch is adding a bunch of unnecessary merge bulk to the repository. When I have the next version ready should I rebase this, create a new branch so that this is killable, or just carry on in this branch?

**Comment by aeschli** [comment]
Yes, rebase (and squash) would be good at some point. Either create a new branch or force-push to the existing branch. Both work.

**Comment by PieterBranderhorst** [comment]
I've made some fixes, squashed all commits in this branch, and rebased it on current source.

I haven't added an experimental flag. I am hoping you'll agree that where this version behaves differently from the current code it is an improvement.

I've added use of a different icon in the margin for regions which were manually folded. Please let me know what you think of it.

Situations I know of where this code behaves differently from the current code are:

1.	With cursor at start of first line after a collapsed region do a \<backspace\>.
Current behaviour: Inconsistent. Depending on range provider and text involved either keeps region folded displaying a concatenated following line, or removes previous character with no visible change, or auto-unfolds the region.
New behaviour: Auto-unfold

2.	With cursor at end of line at start of folded region, insert a character, or <backspace> to delete a character which is not a folding token, or \<del\>
Current behaviour: Auto-unfold
New behaviour: Keep region folded.

3.  Split the line after a folded region (i.e. use \<enter\>), before the end token (e.g. "}")
Current behaviour: The newly created line before the split point disappears into the folded region.
New behaviour: Auto-unfold

4.  Add a new start-of-comment with no matching end above one or more folded regions. Or remove a preceding end-of-comment. This is a case where the new behaviour is part of the purpose of the new code.
Current behaviour: The folded regions auto-unfold.
New behaviour: If there is just one hidden region affected it auto-unfolds. This is done because the code can't distinguish this situation from one where the opening token of a fold has been removed. If more than one hidden region is affected they remain hidden and are converted to manually folded regions. If the range provider subsequently provides matching ranges again, e.g. because the unmatched start-of-comment has been fixed, the hidden ranges are converted back to normal hidden ranges.

I hope we're getting close to something satisfactory now :)

**Comment by PieterBranderhorst** [comment]
You're right, it needed a better icon. I didn't want to add one (right chevron with some added glyph seemed ideal) and I hadn't considered ellipsis. I think it works well.

And yes, auto-expanding when using \<del\> at end of start line auto-expanding makes more sense. It is more consistent with the rest of the behaviour.

I've checked in both of those changes.

**Comment by PieterBranderhorst** [comment]
Yes, that's intended. This is the one deliberate odd behaviour. When the folding provider no longer returns a region which it previously returned and which is collapsed the foldingModel logic can't easily distinguish between three possible reasons:
1. The user modified the text in such a way that the region really is gone. E.g. They deleted the opening "{" of a region. In this case we should unfold it.
2. The user modified the text such that the region is now embedded in a comment or a string. In this case it makes sense to keep the region folded - the user may next close the comment or string before the region. And even if they don't the fold still makes a kind of sense.
3. The folding range provider is misbehaving. Very slow to respond or responding incorrectly. Which we think is the case in the issue which got this whole thing going. In this case we want the hidden region(s) to stay hidden.

Since the foldingModel can't readily distinguish between these cases I decided to treat it as case (1) if only one hidden region is affected and unfold it, and treat it as case (2) or (3) if more than one hidden region is affected. My reasoning is that even if it is wrong in treating a situation as the first case, as it is in your example, only one fold is affected and that isn't a big hardship to the user. I expect it will nearly never be wrong when treating something the other way.

**Review by aeschli — APPROVED** [review]

**Review by dbaeumer — APPROVED** [review]

**Comment by aeschli** [comment]
Thanks @PieterBranderhorst. That took a long time, sorry for that. Let's see how users like it.

**Comment by PieterBranderhorst** [comment]
@aeschli Hi Martin. I'm glad you got this done, I'd given up on it.

Please ensure that the release notes mention ctrl-K ctrl-.
Though that wasn't what motivated this change I think that's the part that many people will use. It might get used more than the automated fold points :)

By the way, I've given up on my parameterized folding provider. I got it working as an extension but there are too many difficulties with integrating it with patterns provided by other extensions and as a result I don't think it would get used a lot. It really should be built-in to work well. If you ever want to reconsider it I could bring it up to date and resubmit, just let me know. It:

- Works a lot better than you might think given that it uses regular expressions. I like what it does for Typescript folding better than the built-in Typescript folding provider. It doesn't have the shortcomings you might assume with regular expression parsing.
- Has an option to include indent based folding code. So it could replace the existing indent based folding code while adding the new functionality.
- Is very fast. Faster than the existing indent based folding, even in most cases for elaborate languages.

Also, if you become interested in this area again, I have an approach sketched which would highlight things as a user moves the mouse along the gutter containing the folding icons. It would highlight the code to be folded when over a collapse icon and would temporarily expand and highlight the folded code for expand icons. Please send me a note if this becomes something you'd like to pursue.

Ditto if you'd like a cleanup pass over the folding code. I think the hiddenRangeModel.ts code is almost all unnecessary at this point and could be removed, and efficiency could be improved for all of it by restructuring the internals a bit.

**Comment by aeschli** [comment]
Hi @PieterBranderhorst, yes sorry for letting this lie around so long. The fold selection feature is a major motivation to get it out of the door. Also I wanted to get some user feedback so it's not just my opinions that shape this. I 
So if you have some resources later on to respond to user feedback and fine tune the implementation, that would be great.

- I'm curious to see if the 'unfold once' approach will work for users for 'Fold from selection'. I anticipate that some users want the range to stay, even if unfolded.
- The current heuristic to find out which folded ranges to preserve is not super clear (also to me). See the example [here](https://github.com/microsoft/vscode/pull/139779#issuecomment-1117388185) where a single folded range goes away, but if there are multiple folded ranges, they stay. If you can add more background on what 

You mention that we want to keep ranges that re in comment or a string literal. We could get that that information (`textModel.tokenization.getLineTokens`...)

On the other discussion:
- hover over a folding icon would be great to have. Maybe a hover that shows the folded content?
- parameterized folding provider: I'm not keen on adding that as a built-in provider.

**Comment by PieterBranderhorst** [comment]
Hi @aeschli,

I will watch Issues for feedback on this.

Regarding having manually created folding ranges persist: I do want to see how much that's wanted. It would be a bit tricky and require some thinking about handling detection of edits which should modify or remove it and about manual removal. It might be less wanted if we implement the highlight and temporary unfold when hovering over a fold icon. If we add that then users could quickly view the content of a manually folded range without unfolding it.

One other future feature on my list which I forgot to mention above: Ability to fold/unfold all regions of a specified type. This already exists but is minimal. It works for comments and "regions". But the folding provider interface, the settings related to "regions", and the "folding imports by default" weren't thought out as a generalizable subject so it would take a bit of rework. To allow language specific concepts like "functions" or "chapters" to be defined and used.

I understand you're not keen on the parameterized folding thing. But I think it would be used a lot. There are a huge number of syntax highlighting extensions for vscode. For many (most I think) of those languages it isn't worth the effort to create language providers nor folding providers. And some people would write custom ones for things like event logs. I think that even for Python a folding range provider was only added recently, and it had teething problems. If I continue working in this area this is the part I'd really like to do next.

**Comment by aeschli** [comment]
I started working on https://github.com/microsoft/vscode/pull/155302 to simplify the merging rules.
Would you be ok with that simplification, or do you see a problem?

**Pull request merged**
