### PR TITLE
Enable monospaced digits for statusbar items

### LINKED ISSUE #167304: Monospaced digits for the status bar items
When a status bar item updates frequently with something like a counter with a fixed number of digits it grows and shrinks depending on what digits are shown. This makes it look a bit broken, and it get worse if there are items to the sides of the counter.

I'd like to suggest that status bar items are rendered with fixed width/monospaced digits. I tried with making the whole VS Code UI render like this, with this CSS:

```
* { font-feature-settings: "tnum"; }
```

And I can't notice that it is bad anywhere. Here's what a timer-counter I wrote looks like with and without this CSS applied:

* [with](https://user-images.githubusercontent.com/30010/204099632-5f9fe1ec-e61c-442d-9dc9-be1e90f11002.mp4)
* [without](https://user-images.githubusercontent.com/30010/204099741-71892352-d0fd-4537-932a-8ae2dd3d1133.mp4)

See also:

* #73700

### PR DESCRIPTION
**Pull request by PEZ**
The statusbar-item CSS has `font-feature-settings: "tnum";` set to make the digits monospaced. Which is good for items that count. See #167304 for a problem description.

An easy way to test it is to install this extension: https://marketplace.visualstudio.com/items?itemName=keifukuda.stopwatch

Or create a statusbar item with a padded counter.

A thing to consider is if this CSS setting should be made to hit wider. In my own VS Code instance I am running with `* { font-feature-settings: "tnum"; }` and don't really see any downsides with it.

Cheers!

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Shouldnt it be `

`font-variant-numeric: tabular-nums;`

Though?

**Comment by PEZ** [comment]
> Shouldnt it be `
> 
> `font-variant-numeric: tabular-nums;`
> 
> Though?

I wasn't aware. Much more nicer just by the look of it, but I'll have to try it first, I guess. Thanks for the feedback!

**Comment by bpasero** [comment]
I think it does work.

**Comment by PEZ** [comment]
You think correctly. 😄 I tested it now. Works. Updated the PR.

**Review by bpasero — APPROVED** [review]
Thanks!

**Review by chrmarti — APPROVED** [review]

**Pull request merged**
