### PR TITLE
Fix #58532: fix terminal scroll position when opened

### LINKED ISSUE #58532: Terminal scrollbar starts at top
- VSCode Version: 1.27.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. Open terminal
2. Scroll down

Does this issue occur when all extensions are disabled?: Yes

Resurgence of  #45134.

### PR DESCRIPTION
**Pull request by bdrazen**
Fixes #58532

### CODE REVIEW

**Comment by Tyriar** [comment]
@DBjelovuk did you gain any insights into the root cause of this while investigating? I suspect a change in xterm.js would be the best fix for this.

**Comment by DBjelovuk** [comment]
@Tyriar I've tried approaches like calling the xterm's [`scrollToBottom()`](https://github.com/xtermjs/xterm.js/blob/a52aab46180a29f322f7ab6ff092c4ffdd04b2b1/src/public/Terminal.ts#L107) and directly calling [`syncScrollArea()`](https://github.com/xtermjs/xterm.js/blob/e2cfd9400591f56d8c928919f7bb43fb6aaebbb5/src/Viewport.ts#L99) from the `_core` object with no success. Definitely seems to be an xterm issue needing further investigation, but figure this could serve as a temporary patch job in the interim.

**Comment by DBjelovuk** [comment]
@Tyriar [I've made an adjustment to xterm ](https://github.com/xtermjs/xterm.js/pull/1690) that should allow this to be refactored with a simple `this._xterm.syncScrollArea(true)`.

Problem was the viewport's underlying `_refresh()` wasn't being invoked as buffer didn't change.

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1698

**Pull request closed without merging**
