### PR TITLE
position scrollbar for settings on far-right

### PR DESCRIPTION
**Pull request by itamark**
Solves #55795

### CODE REVIEW

**Comment by itamark** [comment]
@ramya-rao-a @roblourens any idea why `VSTS: VS Code` is failing so much?

**Comment by ramya-rao-a** [comment]
A unit test in master is failing. It has nothing to do with your changes. We will most likely get to it on Monday.

**Comment by roblourens** [comment]
Now the shadow extends to the right too, and it should only go over the settings tree area. Also it should extend over the TOC too. That's why I had some of the weirdness before with the absolutely positioned TOC on top of of the settings tree.

image

Personally I'm not a fan of the shadow anyway, and it's complicating things for us here, but we have to keep it for now.

**Comment by itamark** [comment]
@roblourens Okay I limited the width of the container and its shadow to not extend as far as the entire scrollable area does.

**Comment by roblourens** [comment]
Is it possible to get the shadow to show over the TOC like it did before though? 

If it's not possible to do that without jumping through hoops or changing the DOM structure, let me know. I'm not a huge fan of the shadow here, we might be able to get rid of it.

**Comment by itamark** [comment]
I'll take care of it tomorrow 😊

**Comment by itamark** [comment]
@roblourens It would be a bit of a thing to get that shadow back. Plus, I think it's incorrect to have the TOC shadowed. The tree is the thing that's scrolling - not the TOC, no?

**Comment by roblourens** [comment]
Well, we don't want to have separate shadows for the trees right next to each other, and we think it looks weird for the settings list to just have a shadow that cuts off at the TOC, so this was the compromise...  I still want to do something different here like just remove the shadow entirely... I'll just leave this open for now.

**Comment by itamark** [comment]
@roblourens I gave it another shot and was able to figure it out.

**Comment by roblourens** [comment]
It looks like the tree isn't able to shrink properly:

image

With overriding the scrollbar positioning and everything this might be getting to a hack level that I don't want to take.

**Comment by roblourens** [comment]
Going in a slightly different direction but thanks for your work on this :)

**Pull request closed without merging**
