### PR TITLE
Fixed padding property for quick pick vertical alignment

### LINKED ISSUE #124382: Quick pick vertical alignment is off
Notice how the icons seem aligned to the bottom, there is also a bunch of extra padding on the bottom.

image

### PR DESCRIPTION
**Pull request by Ashray123**
This PR fixes #124382

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@Ashray123 can you please add a screenshot of the before and after?

**Comment by Ashray123** [comment]
@TylerLeonhardt Sure please let me know if some other changes are to be made.
Before
After

**Comment by TylerLeonhardt** [comment]
Is the top image the before or after?

**Comment by Ashray123** [comment]
@TylerLeonhardt  The top image i.e the first one is before and the second one is after making changes.

**Comment by TylerLeonhardt** [comment]
I don't think this is fixing the original issue.

The issue is about the items being close to the separators (the long thin lines in the the quick pick separating each section).

I'm thinking that the actual fix for this is adding a margin above the separators.

**Comment by Ashray123** [comment]
@TylerLeonhardt would you please point me to the CSS style for separators in the quickInput.css file where the probable changes are to be made?

**Comment by TylerLeonhardt** [comment]
The change should be in the same file, you'll just have to find the class for the separator using Dev Tools.

**Comment by Ashray123** [comment]
Screenshot 2021-05-30 at 12 52 37 AM
@TylerLeonhardt After adding margin property in the class monaco-list-rows  in the quickInput.css file, I don't see any change reflected in the listed items, would you please let me know what could be the reason?

**Comment by TylerLeonhardt** [comment]
The selector in your screenshot shows you what that class represents. `monaco-list-rows` is a class that encapsulates all rows in the quick pick so adding anything to that class isn't what we want to do.

We want to add CSS that _only_ applies to the little lines that separate some of the rows...those are the separators.

**Comment by Ashray123** [comment]
I think I will need some help regarding finding the class for the separators, will you please help me with it as after trying several times I am not able to inspect the separators to find out which class it belongs to,  whenever I click to focus the quick pick closes itself. 

https://user-images.githubusercontent.com/40429213/120116523-2ede8900-c1a6-11eb-9c59-d002110149c5.mov

**Comment by TylerLeonhardt** [comment]
@Ashray123 did you see my comment in the original issue about setting a breakpoint?

https://github.com/microsoft/vscode/issues/124382#issuecomment-847484641

Setting that breakpoint helps prevent the quick pick from going away so it's easier to inspect the quick pick.

**Comment by Ashray123** [comment]
@TylerLeonhardt  I tried setting a breakpoint on the line you suggested but the quick pick is still going away.

https://user-images.githubusercontent.com/40429213/120149734-c58f6200-c207-11eb-9e0c-1c105a80f894.mov

**Comment by TylerLeonhardt** [comment]
@Ashray123 how are you launching your dev build of vscode? Via F5 or via the console `code.sh`?

**Comment by TylerLeonhardt** [comment]
Breakpoints only get hit if you launch vscode using the Launch VS Code launch config.

Here's the doc on that:
https://github.com/microsoft/vscode/wiki/How-to-Contribute#debugging

**Comment by Ashray123** [comment]
@TylerLeonhardt Please review :)

**Pull request closed without merging**
