### PR TITLE
Allow to collapse a tree recursively 

### PR DESCRIPTION
**Pull request by NAllred91**
This is implementing feature request [#9456](https://github.com/Microsoft/vscode/issues/9456)

**Request:** `alt+click` on a folder and recursively expand/collapse children.

**Implementation:** 

- Allow a boolean to be passed to the `toggleExpansion` function to indicate if the action should be recursive. 
- Allow the `expand` function to take a boolean to indicate if the action should be recursive to match the `collapse` function.

### CODE REVIEW

**Comment by NAllred91** [comment]
My main concern is that when recursively toggling large directories, such as node_modules, this action can be very slow and blocks all other actions.  This is most noticeable when collapsing.

The code for expanding/collapsing:
```
var collapseChildrenPromise = WinJS.TPromise.as(null);
this.forEachChild((child) => {
	collapseChildrenPromise = collapseChildrenPromise.then(() => child.collapse(true));
});
return collapseChildrenPromise.then(() => {
	return this.collapse(false);
});
```

can be rewritten with a setTimeout to prevent blocking and provide a quicker user experience:
```
var collapseChildrenPromise = WinJS.TPromise.as(null);
this.forEachChild((child) => {
	collapseChildrenPromise = collapseChildrenPromise.then(() => setTimeout(() => child.collapse(true)));
});
return this.collapse(false);
```

But this change would break the current unit tests and make this functionality a little more awkward to test.

**Comment by NAllred91** [comment]
https://github.com/Microsoft/vscode/issues/9456

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by NAllred91** [comment]
@bpasero @joaomoreno  I believe I now have an acceptable way of resolving the performance issue.  This issue also existed for the 'collapse all' button if you had manually opened thousands of directories.

I've updated the 'collapseAll' and the 'toggleExpansion recursively' unit tests to reflect this change.

**Comment by bpasero** [comment]
@NAllred91 there is still a severe performance issue when you have a very large `node_modules` folder (e.g. the one from this repo), expand all and then reload the window. You see the explorer stalling for many seconds before showing anything.

**Comment by NAllred91** [comment]
@bpasero I do see the delay when reloading the window after expanding all items.  Wouldn't this be a separate issue though?  If you were to manually open this entire repo and reload the window you would experience the same thing, irregardless of whether you expanded the repo manually or with `alt+click`.

Do you think the actual `alt+click` expanding/collapsing performance issue is sufficiently resolved?  If you think I'm on the right track I'm more than happy to look into the performance of reloading the window with very large directories expanded.

**Comment by bpasero** [comment]
@NAllred91 yes it can also happen today but with the ability to expand 20.000 folders with one click it is much more likely to happen. 

If you can find that you can tweak the performance of the initial startup too, feel free 👍

**Comment by NAllred91** [comment]
@bpasero Should I include that in this pull request or create a separate one?

**Comment by bpasero** [comment]
@NAllred91 fine to have it here I think.

**Comment by eyalcohen4** [comment]
Hey, there is a way I can help? I've been looking for this feature for a while. @NAllred91

**Comment by NAllred91** [comment]
@eyalcohen4 If you try out my branch you'll see that the feature is in place.  The problem now is when you reload the editor when you have a significant amount of directories open, like a large node_modules directory, the editor freezes up for a few seconds while it loads.

The way I implemented the feature was by breaking the call stack while expanding/collapsing directories so that the event loop wasn't blocked.  I was going to try and do the same for the initial load but never got around to it.

I see I've got some conflicts now.  I might take a look at this again tonight if I have some time.

**Comment by NAllred91** [comment]
I went ahead and locally updated the initial load so that it expands all the directories in the same asynchronous way I implemented the `alt+click` feature.  This does fix the performance issue, but it creates other strange user experiences.

I checked Atom and it has the `alt+click` feature but it has a significant performance issue as well.  There might not be anything we can do to completely solve the performance issue in an electron app.  I think that my solution for the `alt-click` itself is satisfactory.  I wonder if there is any way this could just be something that you can toggle on in the settings even though the initial load is slow?

**Comment by vitosamson** [comment]
Just my 2c: the performance issue mentioned is not related to this feature. As @NAllred91 pointed out, the same issue would be present if you manually expanded a large directory and so should be addressed separately. It should not block this feature.

With regards to the performance issue itself, perhaps a setting like `explorer.maxDepthOnLoad` would suffice, with a note that larger values may cause longer load times. I'm happy to work on a PR for this if desired.

**Comment by NAllred91** [comment]
@bpasero I've removed the functionality for recursively expanding using `alt-click`.  In my experience, the most common use case for `alt-click` is to collapse all the directories you've been working in so you can immediately get back to a fresh start.  Without the ability to recursively expand, the performance issues you had mentioned are no longer an issue.

Atom still has performance issues in this area as well.  Just allowing recursive collapsing seems like an acceptable middle ground?

I'm not sure what caused my checks to fail though.  Everything was fine locally.

**Comment by NAllred91** [comment]
@bpasero I've removed the functionality for recursively expanding using alt-click. In my experience, the most common use case for alt-click is to collapse all the directories you've been working in so you can immediately get back to a fresh start. Without the ability to recursively expand, the performance issues you had mentioned are no longer an issue.

Atom still has performance issues in this area as well. Just allowing recursive collapsing seems like an acceptable middle ground?

**Comment by NAllred91** [comment]
I've removed the expand all feature based on discussion here https://github.com/Microsoft/vscode/issues/9456#issuecomment-312404488

**Comment by sahiltalwar88** [comment]
@bpasero - this is a fairly popular feature that exists in many other editors, and is a definite pain point coming from Atom (see https://github.com/Microsoft/vscode/issues/9456 for more information / other opinions). Now that the "Expand All" functionality has been removed, can we please see some progress on this PR? It's been sitting still for 26 days. Thanks!

**Comment by bpasero** [comment]
I am fine enabling this feature only for the "Collapse All" (when Alt key is pressed) case for the explorer. Since we do not easily get into the state of having all folders expanded (unless the user is doing this manually) we will not hit the performance issue easily. 

Since the majority of changes are within the tree, moving to @joaomoreno for the review of that piece. Feel free to assign back to me once you are OK with those changes.

**Comment by joaomoreno** [comment]
I don't understand what has happened here.

- We reached the conclusion we don't want to enable recursive expansion, so [the change doesn't implement it](https://github.com/Microsoft/vscode/pull/20826/files#diff-e170d5d1b0543aa52f75707deb9a5fffR932).
- Recursive collapse is already implemented in `master`.

So... what does this PR really do?

**Comment by NAllred91** [comment]
@joaomoreno At the top of this PR you can see my second comment about why I made changes in the `collapse` function.  Recursively collapsing large directories was slow, so I made the `collapse` function break the call stack so that the application wouldn't freeze while collapsing.  I also changed the `expand` function to work a similar way, which I believe resolves the performance issue at the time of using `alt+click` to expand.  The problem is that, once expanded, if you reload the application there is a freeze for a few seconds.

When I took recursive expansion using `alt+click` out of the PR I just removed the ability to pass the `recursive` boolean to the `expand` function.  I probably should have removed my changes to the `expand` function as well.

I could remove my changes to the `collapse` function, then this PR would be reduced to a change [here](https://github.com/Microsoft/vscode/pull/20826/files#diff-dc18aafbfd8f8dffc023bcd6a064c83eR107)

```
toggleExpansion(element: any, recursive?: boolean): WinJS.Promise;
```

[here](https://github.com/Microsoft/vscode/pull/20826/files#diff-d9e4153b7d83b436c822c6b8606c14c2R189)

```
public toggleExpansion(element: any, recursive: boolean = false): WinJS.Promise {
	return this.model.toggleExpansion(element, recursive);
  }
```

and [here](https://github.com/Microsoft/vscode/pull/20826/files#diff-d9e4153b7d83b436c822c6b8606c14c2R189)

```
public toggleExpansion(element: any, recursive: boolean = false): WinJS.Promise {
 	return this.isExpanded(element) ? this.collapse(element, recursive) : this.expand(element);
  }
```

If the PR is reduced to just these changes then we will still have a performance issue when collapsing thousands of directories at once.  But since the ability to expand thousands of directories at once no longer exists, solving that performance issue may not be worth the complexity of breaking the call stack in the `collapse` function?

**Comment by NAllred91** [comment]
@joaomoreno The reason I left the changes in the `expand` function is because those changes do actually fix the performance issue when expanding large directories.  The issue is that the performance issue isn't fixed on startup when we iterate over all of the expanded directories and expand them.  If the issue on startup could be resolved, the changes I made in the `expand` function would already support expanding recursively in a way that doesn't cause the application to freeze.

**Comment by joaomoreno** [comment]
>  But since the ability to expand thousands of directories at once no longer exists, solving that performance issue may not be worth the complexity of breaking the call stack in the collapse function?

I believe it really isn't worth it. Also, the performance issue doesn't go away; it just gets very oddly hidden. :cry:

**Comment by NAllred91** [comment]
@joaomoreno In that case, I opened this pull request which simplifies everything. https://github.com/Microsoft/vscode/pull/32475

**Pull request closed without merging**
