### PR TITLE
Selectbox theme additions Fixes #25965, #35246

### LINKED ISSUE #25965: UI Theme Add: select-box(drop downs) selection and hover colors
Currently all widgets using 'select-box' cannot theme
the selected or hover item colors (foreground/background)
The the color is controlled by the platform. That overrides
normal CSS approaches/selectors. 

image

After a bunch of research, I did figure out one solution
and made a prototype in a small electron app.

There appear to be three options:

1 - Some CSS guru knows of a better trick
2 - Use an input box on top of the current list widget 
3 - Use something like I came up with: 

   one select box that is the normal drop-down with current selection
   automatically includes the drop-down arrow
   a second select box which can be made hidden/visible depending
   on the first lightbox focus/selection

   The second select box can be styled with option:checked and box shadow

   
option:checked {
    color: #ffffff;
    box-shadow: 0 0 10px 100px #905000 inset;
}

    This box-shadow is the only thing I found that overwrites the platform colors
    It does NOT work on a select box with only one item showing (nominal case)
    That is what I came up with the two boxes and a bit of code to display and hide
    the second box with the options list

I think option two is more complicated and inherits the unneeded list properties
if there is no option one , I would go ahead and prototype within VSC and do a PR

Thoughts ?

image

### PR DESCRIPTION
**Pull request by cleidigh**
Fixes #25965, #35246, #25700

@bpasero 

I got very delayed by a variety of things including Update/Fixes of my VMs for multiplatform testing.
"Much pain was had!", to quote Yoda ;-(  Sorry for the delay...

I did tackle all the to do items left from last time.

- Added high contrast mode
- Remove scrollbar
- Added new color registrations
	selectOptionsBorder?: Color;
	selectOptionCheckedBackground?: Color;
	selectOptionHoverBackground?: Color;
	selectOptionCheckedOutline?: Color;
	selectOptionHoverOutline?: Color;

- Added new colors to themes (other than those that defaults work)
- Generally mapped selectOptionChecked ==> color of list focus
- Generally mapped selectOptionHover ==> color of list hover
- Some exceptions to above for contrast, final colors TBD
- Other colors can be set as necessary.
- OS X matches other OS'

I did possibly see a hover quirk, but it might be a VM issue

I think the high contrast and theme colors are a nice add to select.
If you think this all makes sense I may suggest converting
to "simple list" which would eliminate any possible OS or 
odd select issues.
This would not be a big deal based on what I have already.
Just convert the options to 'li'... etc.

Thanks for checking this out!

### CODE REVIEW

**Comment by bpasero** [comment]
+ @isidorn as author of `SelectBox` widget. 

@cleidigh this is pretty cool because it fixes also https://github.com/Microsoft/vscode/issues/25700

I think we should probably not use this on macOS though where the dropdown looks very native and good imho:

image

Can we have a flag on which OS to enable this?

Some general feedack:
* pressing `Space` should also trigger the dropdown
* the dropdown flows outside of the window if the space is little, you should maybe look into [`ContextView`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/contextview/contextview.ts#L6) which is a reusable widget for showing something within the window on top of other controls. I think that widget would save you quite a bit of layout code to write. You can see it in action for example for the feedback widget:

image

**Comment by isidorn** [comment]
@cleidigh thanks for your work. Once you address @bpasero feedback I can also look into this and provide additional feedback.

**Comment by cleidigh** [comment]
@bpasero 
Excellent! Glad you like it.
Have to admit I've really learned a lot since April starting this,
all good!

@isidorn  - Sounds good, I will flush this out per comments...

- good to take care of another issue #25700 - bonus points ;-)
- Will look into contextView
- Question : Does a workbench relayout event exists somewhere?
- I used a null animation rule with callback to recalculate and reposition select box
- Question : Since OS X is presumably the only platform that has a different approach to the select box
Should there just be a switch for that?  Since the other OS' already use a partially themed
SelectBox.  Perhaps: workbench.themes.useNativeOSXDropDown (default === true)
- Question : Should I make the outline colors configurable, they mapped to active contrast selectOptionCheckedOutline
right now.

Regarding the hover issue I mentioned:

If you opened three or four terminals and hover over the drop-down list,
every once in a while option two eg Cmd 2/Bash2 would not highlight
Very odd, does not appear to happen on Debug drop-down.  I believe
this may be an odd select issue.

Do you see this?

I will start working on the punch list, take advantage of ContextView
and look at a simple list if select issues  really exist.

**Comment by cleidigh** [comment]
@bpasero 

Scratch Question 1
I got my head around ContextView and got all the clients to pass the dependency
and I think I have the basics working.  I see layout gets called with screen changes
so that answers question number one.

I'm working on the rest and converting the native select to a simple list.
I think I have found the select has  some really odd quirks that would otherwise bite us.

I am having some trouble with applying styles through the CSS file, not sure If
there are some limitations or tricks to this when using context view?

**Comment by bpasero** [comment]
@cleidigh good point, using our [`ListWidget`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listWidget.ts#L626) is probably a good idea for the dropdown because that takes away a lot of extra work and it already comes with the proper theming of list widgets as done in other places in the UI.

The styling of context view is a bit special because as far as I remember it is rooted as direct child of the body element and not within the workbench bounds. Maybe take a look at how we style the feedback widget that is using the context view.

**Comment by cleidigh** [comment]
@bpasero 

Before I go too much further I want to make sure we are on the same page
so I can do this right.  

- General goal: extend SelectBox to include two modes:
	1) existing, native select, all current limitations colors/oddities
 	2) extended theme colors , non-select (use list wiget), ContextView
- Functionality/Appearance essentially as my current implementation
- Provide settings option to allow user to choose mode (switch type/defaults TBD)
	Comments on my prior thoughts on this?
	Perhaps caller should also be able to choose mode
- Provide color overrides to allow select different from list if desired
- List navigation needs to deal with 'disabled' entries (assume not a problem)
- ARIA labels (another improvement?)
- Minimal interface changes (had to pass ContextView from all clients)

I now have a working drop-down utilizing ContextView, CSS file based styling, anchored
to the select box with focus/blur and show and hide.  I am assuming
adding the list should not be too much trouble.  After some more experiments
I will make sure my implementation for the contextView is correct.

Thanks/Cheers

**Comment by bpasero** [comment]
@cleidigh yes being able to flip between native and custom solution seems desirable to me. We can still think about using this solution on all OS, but the macOS behaviour imho is not so bad but rather what you would get with a native application too. I do not think this should be a user facing setting though, rather something we decide per platform. 

For the custom dropdown I would go with the context-view + list widget approach. I am not sure how to best deal with disabled list options though. One challenge for the list widget is how to model disabled options. The notion of disabled items is not provided from the widget. The styling could obviously be done, but the keyboard navigation is probably something that would have to be done on top (so that e.g. when you arrow up or down you jump over the disabled element).

I do not think we should use the tree widget because we are trying to model a list.

I think the list widget has all the ARIA support we need.

**Comment by cleidigh** [comment]
@bpasero 
Thanks, sounds good.
Already have the list working with keyboard support at the client level. Disabled options no problem.  May have some styling questions.
I will crank away until I have some intelligent questions or something decent to review...

**Comment by cleidigh** [comment]
@bpasero 
@isidorn 

Re-factoring for contextview and the list widget required more learning and experiments.  Hopefully it will make the next contribution faster !  

I've already done a lot of cleanup, but I still have a bit of potential renaming and simplification to do.  It is in pretty good shape for review.  Besides addressing prior comments I also
took care of a lot of small details and edge conditions.

Linking to a new branch, will merge or post new PR depending on your preference when done.  I wanted to keep selectbox-2/add separate and alone until done.
https://github.com/cleidigh/vscode/tree/selectbox-3/add

Issues/Status:

NativeSelectSwitch:
Currently forces OS X to use native select.
I put an override line if you want to see the OS X with full theming.

List container width:  
Had to use a hidden flexbox container to control width
Possible better solution ?

Contextview tracking problem:
I found instances where the contextview container/drop-down did not follow a shifted anchor.  This appears to happen with the terminal drop-down when it shifts in an overflow situation
I have some deep up tracking the positions and can see the differences but doing a correction affects other situations that work fine.

I am going to continue to test/experiment.
@Tyriar :  I would like to understand how the terminal menus get shifted
when there is a horizontal overflow condition and the terminal
drop down gets focus.

Cheers/Thanks

**Comment by isidorn** [comment]
@cleidigh keep in mind that we have adopted the composite bar in master - which basically takes care of overflow behavior for top level panel actions. Due to this the whole overflow behavior in the panel will change. You can check it out in latest insiders

**Comment by cleidigh** [comment]
@isidorn 
Thanks for the heads up.  I see you Just did stuff on this yesterday.  I will sink and test
to see if this corrects the problem.

**Comment by Tyriar** [comment]
@cleidigh I think @isidorn did the control used for the terminal dropdown. I just picked up an available component for that.

**Comment by cleidigh** [comment]
@bpasero 
@isidorn 
Re-synced with master this morning to check out the vertical panel mode with a select box utilizing
a context view drop-down.  The tracking issue still persists you can see an example in the screenshot below.  The offset does not go away even if you close the drop-down and reopen it.

I have not seen a similar issue with the debug drop-down, but this does not have the same title adjustments that the panel does.  So far this is the only 'identified' problem I have found no answer to.

image

**Comment by cleidigh** [comment]
I think I fixed the tracking issue.  There is a situation when the panel dropdown gets partially hidden.
This is a panel overflow issue.  I'll capture what I'm talking about.  

Tweaking some lipstick ;-)
Will push to my repository after pig gets lipstick.

**Comment by cleidigh** [comment]
@bpasero 
@isidorn 
I know it's endgame... just posting for the November Q.

I have fixed all the issues I have found as well as addressing a lot of aesthetic issues.

- Vertical margins addressed
- Horizontal margins - controlled by ContextV - only flips when window edge  hit 
    - Could address this with optional margin requirements passed to ContextV (your call)
    - Cannot use CSS or forced resize because it conflicts with ContextV logic
- Added VerticalScrollBar visibility option to listview - could also add horizontal
- Tweaked margins for high contrast mode
- DropDown is fully modal - could pass through other keyboard commands if desired
- As first list/ContextV effort , make sure I didn't miss use anything !

Let me know if I should try to merge, or update an issue new PR
Latest:

https://github.com/Microsoft/vscode/compare/master...cleidigh:selectbox-3/squash2

**Comment by bpasero** [comment]
@cleidigh thanks, I will try to reserve time in November to test and review in this PR.

**Comment by bpasero** [comment]
@cleidigh it looks like you are not using the `List` widget within the dropdown right? Is there any reason? I think it would make a lot of things easier, specifically keyboard handling within the list as well as theming. The list is already coming with colors for selected/focused elements.

**Comment by cleidigh** [comment]
@bpasero 
I did completely convert to both , more tricks than I expected... Sorry, I thought it was clear enough above
I created a new branch not PR to leave the PR alone since I was not sure I could update and merge well.

Latest/List/Contextv :
https://github.com/cleidigh/vscode/tree/selectbox-3/squash2

I wanted your choice whether I did a new PR or attempted to back Merge the current.  I know if I update I probably cannot squash commits on old.

**Comment by bpasero** [comment]
@cleidigh oh yeah I misunderstood you, sorry. Feel free to create a new PR with your work so we have them separate, thanks!

**Comment by cleidigh** [comment]
@bpasero 
Sounds good I will squash the commits hopefully without trouble and create a new PR now

**Comment by cleidigh** [comment]
@bpasero 
See new PR
https://github.com/Microsoft/vscode/pull/37533

**Comment by cleidigh** [comment]
Closing, replaced by PR #37533

**Pull request closed without merging**
