### PR TITLE
Updated the snapcraft.yaml to use Core18 and to stop using bionic ppa

### PR DESCRIPTION
**Pull request by Kedstar99**
Hello,

I am sorry this stuff may be a bit unfinished or rough. I was kind of hoping to do this ready for Hacktoberfest 2019 this year but it looks like Canonical(@sergiusens) and @joaomoreno are already looking at snazzing up the snap anyway.

I was just hoping to maybe ask some questions based on what I have done so far. I'm sorry if my questions are irrelevant or work so far isn't useful. 

- In the original snapcraft.yaml, everyone is using the ppa from bionic with gnome-3-26. Isn't the [desktop-launchers](https://github.com/ubuntu/snapcraft-desktop-helpers) meant to replace this? Are all electron apps meant to use this ppa mechanism as that seems strangely undocumented.

- The Core18 at seems to require multipass and potentially root. Im guessing this isn't gonna occur for your CI pipeline. If so can this be confirmed?

- Are the build gulp tasks supposed to build the vscode package or their dependencies?  At the moment, the code runs 'snapcraft build'. According to the help text, this command just  'builds artifacts defined for a part'. Without the build command am actual usable snap is created. My question is what is the intention for these functions and should [documentation](https://github.com/Microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux) be updated? If it is meant to package a product, I guess my change in gulpfile.vscode.linux.js would be useful.

Using the following changes I was able to get a working and build-able version of core18 snap. It seemed to work fine for everything including opening files and running commands. It loads fast too although I can imagine that is because of having to use the --dangerous and --classic flags.

Kind regards,
Krish

### CODE REVIEW

**Comment by joaomoreno** [comment]
> The Core18 at seems to require multipass and potentially root. Im guessing this isn't gonna occur for your CI pipeline. If so can this be confirmed?

We can have root in the CI.

As for the other questions... shouldn't those be posted to https://forum.snapcraft.io instead?

**Comment by Kedstar99** [comment]
> As for the other questions... shouldn't those be posted to https://forum.snapcraft.io instead?

I think most of those are kind of specific to how vscode is currently built which may be influenced by some aspect of the design of vscode. I'm not sure forum.snapcraft.io is the right place to ask, but these questions are pertinent to the areas i have worked on anyway. 

For example, is the command yarn run gulp vscode-linux-x64-build-snap meant to produce a snap that is installable? If so my change to gulpfile.vscode.linux.js should be accepted. Also how are snaps currently built? Does it currently manually build snapcraft afterwards?

That and it isn't really clear to me quite why vscode is currently build with that ppa and not a plugin. 

> Overall, is there any advantage to update to core18, besides riding the latest?

My thought is that you may have better fixes for some of the graphical issues being seen if we move to the commonly updated gnome plug. That fix may actually fix things but I think I need to know more.

I just figure the move to core18 would be beneficial at some point as you would need to fix these anyway if you ever decided to move from 16.04 core. Especially if core20 gets released.

**Comment by joaomoreno** [comment]
> For example, is the command yarn run gulp vscode-linux-x64-build-snap meant to produce a snap that is installable? If so my change to gulpfile.vscode.linux.js should be accepted. Also how are snaps currently built? Does it currently manually run snapcraft afterwards?

Kind of... we currently rely on the `prepare-snap` task and then offload it to [another build agent](https://github.com/microsoft/vscode/blob/d4f1c39dc055fa81dd1ba5eb0bd6b275b9e8de21/build/azure-pipelines/linux/snap-build-linux.yml#L55) which takes care of invoking `snapcraft`.

> My thought is that you may have better support if vscode moved to the commonly updated gnome plug rather than some outdated bionic ppa (last updated 46 weeks ago). That fix may actually fix graphical/font things but I think I need to know more as to how vscode is using that plug.

It would be great if you could validate any fixes of our current [snap issues](https://github.com/microsoft/vscode/labels/snap).

**Comment by Kedstar99** [comment]
So I have been doing some research this last few days and found some things which I think you may be interested in.

First of all thank you for merging my 3rd point which is now irrelevant now that the change has been merged in.

In regards to points 1 and 2, I have managed to get a snap building at least with core-18 but I am having a few issues specifically with point 1 that makes point 2 pointless. The main reason I can see why we are using the gnome ppa I think is to cache fonts and to have access to gsettings and other useful things in the gnome-desktop. 

I think the idea for graphical applications is to use the desktop-launchers stated here.

https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml

That I think is the modern way of doing things as I see no documentation detailing to use the ppa anymore. The ppa (last update 47 weeks ago) also seems to be lacking in updates whilst the gnome-content snaps seem to regularly get updates (last update 6 days). My assumption is that the gnome plug snaps are regularly getting updates for fixes and speed [improvements](https://snapcraft.io/blog/snap-startup-time-improvements) related to things like caching fonts. In addition, I think this is the way electron snaps are currently being [built](https://github.com/electron-userland/electron-builder/issues/2614).

The main blocker I am seeing with trying to use these launchers with vscode is that the content interfaces are not allowed on classic snaps. This I think is because of valid security reasons for a classic snap to affect those content plugs which would affect all other snaps on the system.

https://forum.snapcraft.io/t/enable-content-interface-type-between-classic-confinement-snaps/3780

Until this point 2 is fixed, I am not sure but I think you will be stuck with the current mechanism on core16 as there isn't an equivalent updated ppa with core18 I think.

Hopefully this information is useful to you @joaomoreno .

**Comment by joaomoreno** [comment]
@Kedstar99 Awesome investigation, you are definitely much more knowledgeable about this than I am. I would absolutely be interested in a discussion on what it would take to make the Code snap non-classic and what the consequences of that would be, especially if that brings us a more consistent UI and faster launch times. If you know what it would take, care to explain it to me and/or maybe sit down and discuss in a web chat?

**Comment by Kedstar99** [comment]
I don't quite think that it is possible to make Code follow strict confinement without massively impacting the functionality. In particular, I think switching to strict confinement would break the ability to work with anything external (Java, python, android etc..) and would basically make the console useless. It would also massively impact usability in various ways such as being unable to open files on drives that aren't mounted and accessible by the home plug.

At the moment, all the editors (atom, intellij etc) apart from kate all use classic confinement and for good reason.  This also means that they are also affected by the same problem.

For now, I have raised an issue with the snapcraft-launchers repo.

https://github.com/ubuntu/snapcraft-desktop-helpers/issues/198

**Comment by joaomoreno** [comment]
Thanks @Kedstar99

**Pull request closed without merging**
