### PR TITLE
feat: Go to Match on click of matches count #172127

### LINKED ISSUE #172127: Make "Go to match" more discoverable
Testing #172100

One idea would be to allow to click on this:

image

To bring up the picker?

### PR DESCRIPTION
**Pull request by Viijay-Kr**
Closes #172127

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@rebornix please add this to a milestone.

**Comment by gjsjohnmurray** [comment]
@rebornix please don't lose sight of this community contribution.

**Comment by amunger** [comment]
The styling needs to be updated to better match the other parts of the UI - height should match the neighboring button, don't add extra left padding

image
vs
image

**Comment by rebornix** [comment]
I like this prototype but considering that it's a relatively large UX change (making the result label actionable), I'm closing this for now and will pick it up again when we start some UX unification for the find widget (e.g., supporting multiple search/find scope). Thanks again for your contribution.

**Pull request closed without merging**
