### PR TITLE
Make titlebar more consistent with Windows 10

### PR DESCRIPTION
**Pull request by yzhang-gh**
### Window Controls Width

**Edge**
edge

**VSCode Before**
vscode before

**VSCode After**
vscode after

### Transition Duration

0.2s -> 0.1s

### CODE REVIEW

**Comment by bpasero** [comment]
@neilsustc what is the purpose of the transition for the window buttons?

**Comment by neilsustc** [comment]
The same reason, being more consistent with native effects.

It is hard to be recorded with GIFs but you can feel the transition duration is more like 0.1s rather than 0.2s.

**Comment by bpasero** [comment]
@neilsustc I was more wondering what the transition does, e.g. when and where does it apply?

**Comment by neilsustc** [comment]
transition

VSCode needs more time to react. (I should have compared them using the light theme to be fair... but you know what I mean)

**Comment by bpasero** [comment]
Interesting, thanks for the info.

**Comment by neilsustc** [comment]
I find another thing, the margin of "hr"

image

Although it seems to be a small detail, it is very noticeable to me...

Can I fix it in this PR? It is not about titlebar any more, but it is quite simple (one margin) so maybe there is no need for another PR.

**Comment by neilsustc** [comment]
image

I guess I'd better to create a separate issue for custom menus.

**Comment by misolori** [comment]
@neilsustc I’d suggest making a different PR for fixing the menu spacing/alignment

**Comment by neilsustc** [comment]
👌

**Pull request merged**
