### PR TITLE
feat: implement Git: Push Tags command

### LINKED ISSUE #109799: Git: Support `Git: Push Tags` command
- VSCode Version: 1.50.1
- OS Version: Ubuntu 18 Bionic Beaver

Steps to Reproduce:

1. Commit
2. Git Create Tag
3. Git Push (Follow Tags)

My code successful push to github, but no tags and releases file created in github.

Does this issue occur when all extensions are disabled?: Yes/No
YES (except GIT extension)

### PR DESCRIPTION
**Pull request by stdavis**
This implements the new command mentioned in #109799. To test, create a new tag and run the command: "Git: Push Tags".

I haven't yet added (or even investigated) tests. I'd love any direction on what needs to happen in this regard.

This PR fixes #109799

### CODE REVIEW

**Review by rheh — COMMENTED** [review]
Code changes LGMT.

Should git.test.ts be updated to include a new unit test for the change?

**Comment by stdavis** [comment]
> Should git.test.ts be updated to include a new unit test for the change?

I've been looking at the `pushWithTags` command for clues and haven't found any tests referencing that or any sort of push function/method including in `git.test.ts`.

But that's for the review!

**Review by rheh — APPROVED** [review]

**Comment by joaomoreno** [comment]
No need for tests! 👍

**Comment by joaomoreno** [comment]
Looks great, thanks! 🍻

**Pull request merged**
