### PR TITLE
Adds an option to view extensions in select language mode

### LINKED ISSUE #106886: Change Language Mode drop-down should allow filtering by file extension
In the [Change Language Mode drop-down](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file), it would be nice if we could filter by extension. e.g. at the moment for a `.jsx` file, typing `jsx` returns nothing. I have to start typing `javascriptreact`:

select-language-type-vscode

For TypeScript, `ts` gives you:

select-language-type-vscode-ts

Which doesn't seem intuitive. I'd expected the same results, but taking the extension into account and ordering them:

```
TypeScript > TypeScript React > JSON with Comments > CSS (Styled Components
```

### PR DESCRIPTION
**Pull request by tomerstav**
A user can search against extension names in select language mode by selecting Show Extensions. If a user wants to undo the action they can re-click the language type at the bottom right of the window.
example

Screen Shot 2020-09-19 at 8 59 37 PM
Screen Shot 2020-09-19 at 8 59 45 PM

This PR fixes #106886

### CODE REVIEW

**Comment by bpasero** [comment]
I do not fully understand how this PR fixes #106886

**Comment by tomerstav** [comment]
> I do not fully understand how this PR fixes #106886

Once you view extensions in the description of the dropdown enums you can search against these file types. Such as jsx or ts. If you pull down my branch and run it you can see this by the following steps.

1. Click the language on the bottom right.
2. Search value 'jsx', you will see that nothing is returned.
3. Click show extensions button.
4. Search again with value 'jsx', you will see results based on the file extension in the enum description.

**Comment by bpasero** [comment]
I understand, but why can we not simply allow to search by file extension? Why the extra action to enable that?

**Comment by tomerstav** [comment]
> I understand, but why can we not simply allow to search by file extension? Why the extra action to enable that?

I assume most users do not search by extension name and that those that do wouldn't want to see all the extension names in the description.

If we allow all users to search for extensions without seeing the description then that would be problematic as users would see results thinking they are in error and not relevant to their search.

**Comment by bpasero** [comment]
To clarify: my suggestion was to leave the picker as it is today but show results when you search for file extensions. You think that is confusing? Why?

**Comment by tomerstav** [comment]
> To clarify: my suggestion was to leave the picker as it is today but include the file extension to show results when you search. You think that is confusing? Why?

With extension names in the descriptions? I'm okay with that but I think having the extra action makes it cleaner.

Without extension names in the descriptions? I think it wouldn't be clear why you are getting the results you are getting. Right now the users input is being highlighted in the results to explain to the user why they are getting what they got. We wouldn't be able to highlight any of the results as the file extension would not be part of the description.

**Comment by bpasero** [comment]
Since we now have another PR for this in https://github.com/microsoft/vscode/pull/107939 I suggest that we keep it to one. I somewhat like the approach there better but think it needs more tweaking as outlined in https://github.com/microsoft/vscode/pull/107939#issuecomment-703055243

**Pull request closed without merging**
