### PR TITLE
Fix missing "Restart TS Server" command in Command Palette

### LINKED ISSUE #210649: "TypeScript: Restart TS Server" no longer displayed in command palette
Does this issue occur when all extensions are disabled?: Yes

Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0

### Expected Behavior
The "TypeScript: Restart TS Server" option is always available in the command palette when focused on an editor with the language mode set to "TypeScript" or "TypeScript JSX".

### Actual Behavior
The "TypeScript: Restart TS Server" disappears from the command palette sometimes and doesn't return until the window is reloaded.

Steps to Reproduce:

It's hard to know which of these steps or what part of my setup is contributing to this, but I'm working on a remote monorepo which contains many different TS projects that each have their own tsconfig file.

1. Open remote monorepo workspace
2. Open a .ts file.
3. Reload the window. (There should still be the one tab open for the .ts file from step 2)
4. Wait for the "Initializing JS/TS language features" status bar indicator to stop appearing.
5. Open command palette and see that the option to restart the TS server is present.
6. Select/open another .ts file (even one that lives in the same directory as the currently open one).
7. Open command palette and see that the option to restart the TS server is **no longer** present.

This is a duplicate of #206654 which was closed by the author as they apparently aren't experiencing this issue anymore, but I continue to be plagued by it.

Yes, both files are TS files. Yes, the langage mode is set to "TypeScript" for both files. It also happens for the "TypeScript JSX" langage mode.

I can also reproduce this by replacing step 6 with "open a new tab and then switch back to the original .ts tab".

If I "Developer: Reload Window" then all the normal TS commands reappear.
image

After reloading the window
image

-----------------

As a complete side note, the issue template said to:
>Instead of creating your report here, use 'Report Issue' from the 'Help' menu in VS Code to pre-fill useful information.

I tried this, but after filling out the whole thing nothing happens when I tried clicking the "Create on Github" button so I am forced to create this issue directly on Github. 🤷

### PR DESCRIPTION
**Pull request by dangerman**
Fixes https://github.com/microsoft/vscode/issues/210649

image

### Problem

Some of the TypeScript extension command rely on certain context keys being updated.

Due to changes made in https://github.com/microsoft/vscode/pull/201847 this logic was updated in `activeJsTsEditorTracker` to find active editors using **tabs**, so we can set the right context keys even if you've got the typescript files open in the diff view, and other scenarios.

However, because the logic was being run on **text editor** events, it seems that the state of the `vscode.window.tabGroups.activeTabGroup` was not always correct, resulting in the wrong editor being chosen.
As such, you might have a typescript editor open, but the commands wouldn't show up.

### Fix

This PR adds a subscription to the `tabGroups.onDidChangeTabGroups` event, so that when the `ActiveJsTsEditorTracker.update()` method is run, the `activeTabGroup` state has already been updated correctly.

### CODE REVIEW

**Comment by dangerman** [comment]
@microsoft-github-policy-service agree

**Comment by Irfansyah1234** [comment]
cloneapp2024

**Review by mjbvz — APPROVED** [review]
Thanks!

**Review by connor4312 — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks. Will be in the first 1.93 insiders build we release later this week

**Pull request merged**
