### PR TITLE
Added an image dimensions label underneath the image preview (fixes #3414)

### LINKED ISSUE #3414: Show image dimensions
It would be nice to see image dimensions when I open image in VSCode. Atom shows that information in status bar.

### PR DESCRIPTION
**Pull request by Reanmachine**
Fixes #3414

Added a dimensions label under the image preview:

Screenshot

As my first submission to **vscode** I've done my best to follow the guidelines laid out, please let me know if anything needs improvement. I was unable to cover this code with tests as I do not believe there are any for `resourceViewer.ts` and couldn't find any that test for rendered output in the view that were applicable.

### CODE REVIEW

**Comment by bpasero** [comment]
I wonder if it would not be better to show this information in the status bar instead within the image. On the right hand side we show all the meta data around a text file (encoding, line endings, etc.) and we should do the same for binary files.

**Comment by Tyriar** [comment]
Or after the file name?

> 150257.png - 96x96px

**Comment by bpasero** [comment]
That is currently not possible, I suggested the status bar because the IStatusBarService makes adding and removing entries easily possible.

**Comment by Reanmachine** [comment]
@bpasero @Tyriar 

I agree, this information would be much better in either of those locations. Correct me if I'm wrong but I didn't see any existing framework set up for handling binary files (resources) metadata. From what I can tell they're just sent from the `binaryEditory` to the `resourceViewer`. If we wanted to pull out information like dimensions so it's accessible to the file name or status bar would we not have to process the binary file (or at least snoop the headers) first?

This was my first contribution and I was trying to keep it small as I'm learning the codebase. I'm willing to take a crack at moving that to either the file name or status bar (perhaps with other metadata like file size / mime?). If there was anything you could think of (architecturally) you could point me at in the files pipeline to get me started that'd help a lot.

**Comment by bpasero** [comment]
@Reanmachine yes there are some pieces missing I would say, though I would be willing to look into this and sketch some ideas how this could be implemented. Let me come back to you tomorrow.

**Comment by bpasero** [comment]
I suggest to hook this up with the listeners in the statusbar. It reacts to editor events (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorStatus.ts#L266) and updates the status bar entries based on the meta data of any opened file. When the editor input changes (this event is fired when any file is opened or when the active editor changes if more than one are open) you can react on the event and test for the editor to be a binary editor. That editor should expose a method to retrieve metadata text (could also return information for audio files or video files). 

Since the image dimensions are not known until the image is loaded, I think the meta data needs to return a promise with the text to show.

Conceptually this would make sense to me, in the same way a text editor can return all meta data around a opened text file, the binary editor can provide this for binary files.

**Comment by Reanmachine** [comment]
@bpasero Yeah, that seems the best way to do the display.

I did some poking around looking for the right places to implement some pieces (still finding my way around the source). My major concern is that loading metadata probably shouldn't rely on actually "loading" the file (at least not fully). I'd be wary that video files that can be 100's of MB or larger or even really large uncompressed images could pose problems.

I found what I think is the right place for the actual filesystem interactions `IFileService` & It's implementation under the `node` / `electron-browser` folders. I probably would add a new call similar to `resolveFile` that would return a promise of `IFileMetadata` and use the guessed mime type to load just the headers of files and go inspecting for the dimensions / metadata / etc...

Examples for future expansion I can think of:

* Videos - Dimensions, Length, Codecs, Streams
* Images - Dimensions, Color Space (8-bit, 32-bit), Encoding / Compression
* Audio - Length, Compression Codec, Bitrate

Having this information available in the future could be useful outside of metadata display to extension authors, especially if there's a contribution point for metadata parsers. That's all probably out of scope for the initial feature but it's just some things I've been thinking about.

Does this sound like I'm thinking along the right track to you? (Trying to make sure I haven't missed some incumbent code that simplifies this approach or that I'm not creeping scope too much).

**Comment by bpasero** [comment]
@Reanmachine this makes sense to me. Every editor has an input that gets resolved once opened. The resolved state of an input is a model. In case of binary files nothing really happens for resolving because the file is just displayed raw. I suggest to add code to the binary editor model (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/binaryEditorModel.ts#L13) resolve() method (currently not used) to do the meta data lookup and then store the information in there. The editor status could then just take it from there in the same way it does when it has a text editor model in hand to get the meta data.

File service seems like the right place to do this and I like the ideas you have around the meta data to return. I think the challenge lies into how to get this meta data in an efficient way using node.

**Comment by Reanmachine** [comment]
Since this is being approached differently, I will submit a different pull request with the new code when it's ready, closing this one.

**Comment by bpasero** [comment]
Cool :+1:

**Pull request closed without merging**
