### PR TITLE
Fixed Markdown Formatting Errors in README.md

### PR DESCRIPTION
**Pull request by zfauser**
I fixed a few mistakes that were made in the `README.md` in regard to the formatting of the Markdown. I removed the html for the images, added spacing between the header and the body, and fixed spacing in the unordered list

### CODE REVIEW

**Comment by Zfauser** [comment]
@microsoft-github-policy-service agree

**Comment by mjbvz** [comment]
Sorry but these don't seem worthwhile fixes (especially removing the html because that changes how the content renders)

**Comment by Zfauser** [comment]
> Sorry but these don't seem worthwhile fixes (especially removing the html because that changes how the content renders)

What if I changed it back to HTML? Or still no? Thanks for your time regardless

**Comment by mjbvz** [comment]
Yes but please consider that PRs like this take time to review. Minor stylistic/grammar preferences generally aren't worth the time

**Pull request closed without merging**
