### PR TITLE
feature: replace electron File.path with electron webUtils

### PR DESCRIPTION
**Pull request by SimonSiefke**
From the [electron docs](https://www.electronjs.org/docs/latest/api/file-object):

> Warning: The path property that Electron adds to the File interface is deprecated and will be removed in a future Electron release. We recommend you use webUtils.getPathForFile instead.

<br>

This PR replaces the deprecated `File.path` property with the new electron `webUtils` api. 

<br>

For testing:

Native Drag and Drop in the File Explorer:
1. Drag and drop a file from the native explorer to the vscode file tree
2. Verify the file is added to the vscode explorer

Normal Drag and Drop in the File Explorer:
1. Drag and drop a file from the vscode file tree to somewhere else in the vscode file tree
2. Verify the file is moved as expected in the vscode file explorer

Drag and Drop in the Terminal:
1. Drag and drop a file from the native explorer to the vscode terminal
2. Verify the file path appears in the terminal

### CODE REVIEW

**Comment by bpasero** [comment]
Thanks, I wasn't actually sure how to approach this when I saw it, so I will learn from your changes 🙏

**Comment by SimonSiefke** [comment]
Thanks! 

Initially, I only added electron webUtils to the preload script and exposed it as a global variable `webUtils`. However, it didn't seem ideal for `browser/fileActions.ts` to depend on `electron-sandbox/globals.ts`. That's why I created the `webUtils` service, inspired by the `webViewService`.

**Comment by bpasero** [comment]
But I think a service that cannot be implemented for web is also not ideal. I think the right thing would be to depend on `globals.ts` from `electron-sandbox` and then move the actions that depend on it to `electron-sandbox` layers.

**Review by bpasero — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/vscode/pull/213031#issuecomment-2120895138

**Comment by SimonSiefke** [comment]
Thanks for the feedback.

Do you have an example of similar code where that is applied? I'm not sure how I would proceed here: 

```js
// browser/fileActions.ts
export const pasteFileHandler = async (accessor: ServicesAccessor, fileList?: FileList) => {
	if (toPaste.type === 'paths' && item instanceof URI) {
		return item.path
	}
	// how to call something some electron-sandbox here without importing the file from electron-sandbox?
}
```

Thanks again!

**Comment by bpasero** [comment]
Yeah e.g. here:

https://github.com/microsoft/vscode/blob/9f7eae5bcfb7d6e9378ef34566d60ae23ebe8c86/src/vs/workbench/electron-sandbox/window.ts#L771

For this, the action needs to be moved to a `electron-sandbox` namespace if possible.

**Comment by bpasero** [comment]
Since this action seems to be used in web as well, it probably should be subclassed on desktop to provide the extra functionality.

**Comment by SimonSiefke** [comment]
I made some changes, but had some difficulties like passing the `getPathForFile` function from `TerminalInstance` through `TerminalTabs` to `TerminalTabsRenderer` to `TerminalTabsDragAndDrop` to the `_handleExternalDrop` function. I also had difficulties overwriting `TerminalInstanceService` with `ElectronTerminalInstanceService` which doesn't seem to work well because the registration defines the `ctorDescriptor` property as readonly.

Let me know, what you think. I feel like compared to before I haven't implemented this approach well and the code feels a bit hacky.

**Comment by bpasero** [comment]
@SimonSiefke how did you find the usages initially, can you list the areas? trying to better understand how the property is used.

**Comment by SimonSiefke** [comment]
I used find all references like this:

https://github.com/microsoft/vscode/assets/23744935/9e0c6c08-d9e6-4e42-aecd-c179bbfe95e8

**Comment by bpasero** [comment]
Got it. Sorry for the back and forth but seeing how complex the change now is, maybe we do go with the service option as you had it initially but re-use an existing service we already have: `IHostService` is meant for things that the host (electron vs. browser) provides. Some methods in there are already only provided by Electron and no-op by browser. We would still need the change in preload and globals to access the internals.

**Comment by SimonSiefke** [comment]
I like reusing the `IHostService` and added some changes to implement it. What do you think?

**Comment by bpasero** [comment]
@SimonSiefke I pushed https://github.com/microsoft/vscode/pull/213031/commits/c0298e580add720d5504377c8e88d0b4305ae022 to cleanup, I found many warnings (missing semicolons, etc), did you see them in the editor before committing? please check if things still work.

**Comment by SimonSiefke** [comment]
I forgot I had ESLint disabled, thanks for the fixes! Pasting files in the explorer and terminal is also still working for me!

**Review by bpasero — APPROVED** [review]
Thanks!

**Review by lszomoru — APPROVED** [review]

**Pull request merged**
