### PR TITLE
Fix translation format code action

### PR DESCRIPTION
**Pull request by Dunemaster**
Fix russian  translation for "Fomat code" action as it was absolutely wrong (probably machine-translated)

### CODE REVIEW

**Comment by bpasero** [comment]
@johnliu2016 fyi

**Comment by johnliu2016** [comment]
@Dunemaster, thanks for raising the Russian translation fix, loc change is not open for community contribution, we'll consider the fix from loc partner.

@lukaschal Please send this to linguistic review.

Current Russian string: "Код формата"
Suggested: "Форматировать код"

/Localize/rus/vscode/src/vs/editor/contrib/format/common/format.nls.resx.lcl
/Localize/rus/vscode/src/vs/editor/contrib/format/common/formatActions.nls.resx.lcl

      <Item ItemId=";formatAction.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Format Code]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Код формата]]></Val>
          </Tgt>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\editor\contrib\format\common\formatActions.nls.resx
ID: ".resx", 0; "formatAction.label"
SRC: Format Code
TGT: Форматировать код

**Pull request closed without merging**
