### PR TITLE
Refactaring Hex RGB to Basic color name

### PR DESCRIPTION
**Pull request by Ikuyadeu**
It is very little change.
I use 16 basic color.(ex. red, blue) to improving readability of css code.
Reference (https://www.w3.org/TR/css3-color/#html4)

But I didn't touch css file that in test directory or example.css.
And changed css code already used basic color names.

### CODE REVIEW

**Comment by Tyriar** [comment]
I find hex much easier to read personally.

**Comment by Ikuyadeu** [comment]
@Tyriar Yes, I don't think hex is bad readability.
Problem is changed file which is a mixture of hex and color name.
So, I think color name to hex is good too.

**Comment by aeschli** [comment]
I'll ask around in in the team what is preferred.

**Comment by aeschli** [comment]
@Ikuyadeu First thanks for your work. Unfortunately we decided to not take the change. We have no guideline on how the colors in css are formatted and leave it up to every feature owner to use the style preferred.

**Comment by Ikuyadeu** [comment]
@aeschli Thank you for your thinking.

**Pull request closed without merging**
