### PR TITLE
Allow independent window zoom

### LINKED ISSUE #143663: Allow separate windows to have separate zoom settings
I use multiple monitors each has different DPIs and it is really annoying that I can't have different levels of zoom on each window I have opened, so at the moment smaller screens have smaller font sizes automatically.

I have seen multiple issues open on this regard, some was disregarded and some was rejected even though it had more than 20 upvotes like [#72011](https://github.com/Microsoft/vscode/issues/72011)

I am pretty sure that a lot of people will be a lot more productive if this feature was implemented.

### PR DESCRIPTION
**Pull request by stelescuraul**
This PR fixes https://github.com/microsoft/vscode/issues/143663
which is same as this: https://github.com/Microsoft/vscode/issues/72011

**Description**
This adds a new setting to allow users to control the zoom independently for each window. Enabling the `independentZoom` option allows you to control the zoom (default ctrl +/-) for the selected window, without modifying the others or saving the zoom to the config. It still allows a default value for zoom (eg: -1) which all widows will start with.

The only way to persist the zoom settings when this option is enabled is to directly modify the zoom value in the config.

**Use case**
When using multiple displays with multiple resolutions / ppi, I would like to be able to modify the zoom (scaling) of the vscode window and have it only persist on that instance. I might have two vscode windows opened and increasing the zoom on one windows _should_ not increase it across all instances.

I'd imagine this is just a starting point for more zoom/scaling configurations and perhaps there will be a way to save these settings in the future. 

I did not add tests to this but i'd be more than happy to spend some time writing them if someone could point me in the right direction where this kind of functionality could be tested. 

[Here's](https://www.loom.com/share/ff4c6b0d6853424e96b4f5c0db6185aa) a quick demo of the functionality.

### CODE REVIEW

**Comment by Zingam** [comment]
@stelescuraul Will this also fix this: https://github.com/microsoft/vscode/issues/146254

**Comment by stelescuraul** [comment]
@Zingam Unfortunately no. The output panel and the editor seem to zoom in and scale together.
This will scale the whole UI (like ctrl+/- does) but it won't persist the changes across vscode instances.

**Comment by domjancik** [comment]
Pleeeeeease

**Comment by bpasero** [comment]
Wouldn't it be frustrating that the zoom does not restore when you close and then restart VSCode later? I think the minimal requirement for this PR is to:
* allow per-window zoom
* restore per-window zoom when you restart

Open question is whether the setting is associated to the window or to the workspace, I guess rather to the window.

**Comment by bpasero** [comment]
Marking as "info-needed" since my original concerns are not addressed yet.

**Comment by bpasero** [comment]
I understand, but at this moment the PR cannot be accepted as this PR is simply not writing to the settings file (thus not impacting other windows), but I think at the very minimum the zoom level should persist per-window and restore. It currently does not (at least for me).

**Pull request closed without merging**
