### PR TITLE
Keep scroll position stable when closing an inactive tab

### LINKED ISSUE #13001: Keep scroll position stable when closing a tab in the tab well
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. open many files so that tabs are scrollable, have the first (left-most) tab active
2. scroll to the farthest (right-most) tabs
3. close a tab in that area
4. the whole tab bar scrolls back to the left-most position (active tab)

This leads to loss of focus and confusion. If I want to close multiple tabs there, I have to scroll to them each time I close one.

### PR DESCRIPTION
**Pull request by initialshl**
Fixes #13001

Will no longer automatically reveal the active tab when closing inactive tabs in the tab well when performing the following actions:
* Clicking tab close button
* Middle-clicking tabs
* Right-click menu -> Close 

Also reveals the active tab when focus is regained on the editor.

vscode-closing-tab-well

### CODE REVIEW

**Comment by initialshl** [comment]
I have signed the CLA, thank you.

**Comment by initialshl** [comment]
Hi @bpasero, is there any status update for merging this pull request? I have edited this pull request with a gif that shows the new behavior. Thanks for your time.

**Comment by bpasero** [comment]
I am having difficulties with this patch: Your `skipOnceRevealActiveTab` flag is being used anytime a tab closes, no matter how. What you actually want to express is that the tabs should not auto-reveal when the user closes a tab using the mouse, but what actually happens is that anytime a tab closes, `skipOnceRevealActiveTab` will cause the reveal to be disabled, even if the tab was closed via API and not by the user. 

I would prefer a solution where we skip revealing if and only if the user clicked into a tab that is outside of the viewport of the currently active tab to close it.

**Comment by initialshl** [comment]
Oh i get the idea now, i will try to change it to the desired behavior.

**Comment by initialshl** [comment]
I have updated the code and pull request (description and gif). It skips revealing if and only if the close action is triggered by the tab close button or middle click on the tab. I hope that this provides the desired behaviors.

**Comment by bpasero** [comment]
@initialshl this seems rather like a hack then a real good solution. It also does not cover the case where you use the right click menu on a tab to close tabs.

Btw on top of this, in order to not loose the ability to see the active tab, we need to refocus the active tab when the user clicks into the editor (as outlined in the discussion of the issue).

**Comment by initialshl** [comment]
@bpasero Sorry about that. I tried my best to keep to conventions and not affect existing features this time, so i could only use `skipOnceRevealActiveTab ` flag set from `onEditorClosed` event. Please correct me if there is a better solution.

It now covers the case for closing tabs from the right click menu.
I have also changed it to show the active tab when editor is refocused.

**Comment by bpasero** [comment]
Captured my thoughts here: https://github.com/Microsoft/vscode/issues/13001#issuecomment-285094485

**Comment by bpasero** [comment]
Closing (please see https://github.com/Microsoft/vscode/issues/13001#issuecomment-285378797)

**Pull request closed without merging**
