### PR TITLE
add 2px buffer around mouse for context menus

### LINKED ISSUE #57399: Improve context view placement around box
On Linux.

If I open the editor context menu in a small enough window, the action right below the mouse cursor will be executed instantly, since the change that makes an action run on mouse up. We should nudge the menu 1px to the side (to the right when on the right side, to the left when on the left) in order not to have the menu right below the mouse cursor.

It doesn't repro if the window is large enough since the menu will be 1px nudged down in that case.

### PR DESCRIPTION
**Pull request by sbatten**
fixes #57399

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

**Comment by joaomoreno** [comment]
Actually, this needs a better fix. It should also fix this: https://github.com/Microsoft/vscode/issues/43183

I'll get to it in September, no worries.

**Comment by sbatten** [comment]
@joaomoreno that issue would be resolved on windows with the new menus anyway. as for Linux, I believe this PR would help, no? As long as there is room, we will still draw it with 2px buffer before or after the anchor.

**Comment by joaomoreno** [comment]
> @joaomoreno that issue would be resolved on windows with the new menus anyway. 

I don't think that's true unless the menus support scrolling.

I would still prefer to improve the layout algorithm to be aware of a complete box around the anchor.

**Comment by sbatten** [comment]
@joaomoreno ah, forgot this is not the right-click case.

**Pull request closed without merging**
