### PR TITLE
Add support for an overlay context key service 

### PR DESCRIPTION
**Pull request by joaomoreno**
https://github.com/microsoft/vscode/issues/114901

The idea behind this PR is to enable using an existing context key service instance, along with some static key-value set overlay, without taking ownership of an entire child context key service instance. Owning a child CKS instance is problematic specifically in the submenu world: since submenu actions might listen on context changes, one can't preemptively dispose the context key service they are attached to. This is a common broken pattern across the workbench, eg https://github.com/microsoft/vscode/blob/46c91d443a1784bb5bdcebc90c2d2e978dcc189e/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L1237

- [x] Implement `IContextKeyService.createScoped()`
- [x] Remove the optionality from the parameter in the `createScoped(target?: IContextKeyServiceTarget)` API
- [x] Adopt `createScoped()` wherever we called `createScoped()`

### CODE REVIEW

**Comment by joaomoreno** [comment]
There are only two critical locations left:

https://github.com/microsoft/vscode/blob/c88888aa9bcc76b05779edb21c19eb8c7ebac787/src/vs/workbench/browser/parts/views/viewPane.ts#L148-L148

https://github.com/microsoft/vscode/blob/86d96faaaf8b15a66abc2d766dc47cbdabd177f9/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L303-L303

@sbatten I need your help to tackle this: The scoped context key service created is correct, but it should really be targeted to a DOM node. I can see why that is problematic given the `ctor`/`renderBody` indirection we have, but we should really refactor this such that ViewPaneContainers and ViewPanes have proper scoped context key services targeted to their respective DOM nodes, containing that `view` context key. Same goes for the `viewLocation` context key, but a level higher. We should set it on a context key service higher own (one owned by the sidebar, another owned by the panel) and then reparent the views' context key services as they move around, using the `updateParent` call. Maybe we can pair program this?

**Comment by joaomoreno** [comment]
@sandy081 Check my comment above.

**Comment by sandy081** [comment]
@joaomoreno 

yes, we can associate view/viewcontainer menu actions 's context key service with the corresponding view/view container dom nodes. I think this shall be trivial for viewPane and for viewPaneContainer its enough moving creation of viewPaneContainerActions to `create` method. In short, I think it is trivial.

We can also move view/view container location context keys to their parents viewpanecontainer/(sidebar/panel) and update them when they move. 

I will look into it and change accordingly.

**Comment by sandy081** [comment]
@joaomoreno I have adopted scoped context key services in views layer to use the associated target (domNode) - 3334b1534c9a83a4894d7108903dbfd8eed6110d

**Pull request merged**
