### PR TITLE
Reindent all lines

### PR DESCRIPTION
**Pull request by rebornix**
Reindent all lines based on the language specific indentation rules.

### CODE REVIEW

**Comment by alexandrudima** [comment]
LGTM

**Comment by alexandrudima** [comment]
@rebornix Remember to create a test plan item for this.

**Comment by DonJayamanne** [comment]
@rebornix @alexandrudima 
Is there anything that I need to do to get this command to do something for Python files?
Currently nothing happens when executing this command for python files.

**Comment by rebornix** [comment]
@DonJayamanne A proper Indentation Rules will do and this is how TypeScript does it https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L195 
For your information, Atom has builtin support for Python Indentation https://github.com/atom/language-python/blob/719e4404d2cd25a888a8111c62abd31a22a15ef3/settings/language-python.cson#L7 and you can get an idea from that. But since Python takes tab/spaces seriously, I'll suggest to give it a thorough test.

**Comment by DonJayamanne** [comment]
@rebornix Thanks for the pointers. I already have the onEnter rules, I will just need to re-use them for the indentationRules, along with the decreaseIndent pattern from Atom.
Thanks

**Pull request merged**
