### PR TITLE
Fixed SCM Badge Issue #42940

### PR DESCRIPTION
**Pull request by pushqrdx**
I have tested this out on my machine and it appears to work fine.

### CODE REVIEW

**Comment by pushqrdx** [comment]
@shobhitchittora `line-height` equals to height helps vertically align numbers, while the display prop is for `height, width` to be actually effective. also changing padding will result in a non circular badge for numbers less than `10` which will still look strange.

**Comment by shobhitchittora** [comment]
LGTM.
@joaomoreno please review and close this.

**Comment by shobhitchittora** [comment]
Ping @joaomoreno.

**Comment by paulbremer** [comment]
There are bad whitespace indentation errors during the build;
`src/vs/base/browser/ui/countBadge/countBadge.css(10,1): Bad whitespace indentation
src/vs/base/browser/ui/countBadge/countBadge.css(11,1): Bad whitespace indentation`

**Comment by shobhitchittora** [comment]
@pushqrdx Would you be so kind and fix the CI issues. Also please make sure to run the test before every commit / raising a PR. Doc link - https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
