### PR TITLE
Compact menubar option

### PR DESCRIPTION
**Pull request by sbatten**
Use `window.menuBarVisibility` setting to use the new `compact` option.

### CODE REVIEW

**Comment by sbatten** [comment]
@bpasero feel free to test out this branch and review at a high level. I've also queued a build that you can play with from the branch sbatten-build-compactMenus. some code cleanup to be done around theming and css

**Comment by bpasero** [comment]
Adding @misolori (and I would also like to hear @stevencl feedback as someone that has been designing the activity bar from the beginning with us).

image

image

Some unsorted feedback:
* I feel that the location is not good because we already have an icon with a menu to the bottom and now we have one to the top that is indistinguishable from the view icons. If we keep it to the top I would suggest to maybe change the background color of it to make clear it is something unrelated to the view icons
image
Maybe we should even put the VSCode icon in there? You should check out these designs:
image

From https://github.com/Microsoft/vscode/issues/17060
* hovering with the mouse over the menu icon should give me the same feedback as on any other icon (cursor change, color change)
* Should the compact option only be available for web or for all platforms?
* There should not be a menubar control within the activity bar, rather I feel like we need 2 locations for menu contributions in the activity bar: global (settings) and global (menu). The existing gear icon is doing it properly imho by allowing to contribute items into
* I feel like `.monaco-workbench .activitybar > .content that need :not(.monaco-menu)` is a hack to be avoided

**Comment by sbatten** [comment]
Regarding the menu bar control, this reuse minimizes the amount of code churn to recreate the menubar without breaking things like mnemonics, which work on windows on full screen. Otherwise I will have to rewrite some of the menubar logic to make this work properly. It is a fair debt item but I think this first approach is a good way to test various designs.

Regarding the css rules, for now I can change the rules to have one for global and activities to look less hacky. If we end up keeping the menubar in the activity bar I can try to clean up the menu system to address this  issue and above

**Comment by bpasero** [comment]
I am fine leaving debt items for the debt week to move this forward. What about the UX issues?

**Comment by misolori** [comment]
> If we keep it to the top I would suggest to maybe change the background color of it to make clear it is something unrelated to the view icons

I do agree that we should probably add some type of visual cue that this is different than the rest.



> Maybe we should even put the VSCode icon in there?

I did try this option out but it's not obvious that the logo is clickable/a menu:

image


I think this is enough to start to get feedback on the menu and we can continue to iterate on the styling (adding hover feedback, background color, etc.).

**Comment by bpasero** [comment]
@misolori I really like the variant with the icon, can we try it out?

**Comment by sbatten** [comment]
I've made minor changes and merged master. @misolori if you want to drop in an icon or have any idea what that *differentiator* should be, feel free to drop it in on this branch.

**Comment by misolori** [comment]
Notes from today's UX sync:
- We should look for ways to make the menu stand out so it’s obvious that it is different from the rest of the activity bar, we'll continue to iterate on this
- Merge this into master so we can get more feedback from Insiders
- Re-visit icon choice if feedback comes back negatively
- Once enabled on desktop, this could cleanup the menu on Windows

**Pull request merged**
