### PR TITLE
Add colorized bracket highlighting colours

### LINKED ISSUE #132493: Add bracket pair colorization settings for Solarized Dark theme
When the Solarized Dark theme is in use, there should be specific colours configured to match the theme in use.

image

This shows the default bracket colours in use when the `editor.bracketPairColorization.enabled` flag is set to `true`.

image

This shows the default bracket colours in use when the `editor.bracketPairColorization.enabled` flag is set to `false`.

### PR DESCRIPTION
**Pull request by TabithaLarkin**
This PR fixes #132493

As suggested in [this comment](https://github.com/microsoft/vscode/issues/130989#issuecomment-913493291) by @hediet.

This shows an preview of what these colours would look like (generated from adding these settings to my local settings.json file.

image

edit by @hediet:

With default colors:

Without bracket pair colorization:

### CODE REVIEW

**Comment by hediet** [comment]
Thanks! Can you post a before/after screenshot of the same code region?

**Comment by TabithaLarkin** [comment]
Ah, I've already added those screenshots to the issue that I raised, with the bracket colorization off and on too.

**Comment by hediet** [comment]
@roblourens what do you think?

**Comment by roblourens** [comment]
Not me :)

**Comment by roblourens** [comment]
I don't think that individual themes have owners. You could run it by @misolori if you want another opinion

**Comment by hediet** [comment]
@misolori What do you think?

**Comment by misolori** [comment]
Here's a snapshot of the theme colors + bracket colors with the original vs the proposed colors:

CleanShot 2021-09-10 at 09 10 02@2x

I'd probably keep the bracket colors closer to the original so this is what I would suggest:

CleanShot 2021-09-10 at 09 12 54@2x

## Before
CleanShot 2021-09-10 at 09 13 50@2x


## After
CleanShot 2021-09-10 at 09 16 20@2x

**Comment by TabithaLarkin** [comment]
The reason I selected the white colour was because that was what the standard colour of the brackets without any bracket pair colorization. I would also caution against using the blue colour as it's the same colour as the text, which somewhat removes the benefit of colour differences in IDEs.

image

**Comment by misolori** [comment]
> The reason I selected the white colour was because that was what the standard colour of the brackets without any bracket pair colorization

Doesn't this conflict with the feature? I think we'd want to mirror the original as close as possible while still matching the theme

> I would also caution against using the blue colour as it's the same colour as the text, which somewhat removes the benefit of colour differences in IDEs

Fair point, I think an alternate color can work here as well

**Comment by hediet** [comment]
> Doesn't this conflict with the feature? I think we'd want to mirror the original as close as possible while still matching the theme

I think it is actually not a bad idea to use white as one of three (or more) colors for specific themes: This feature is all about being able to see matching bracket pairs, not neccessarily about highlighting brackets from text.
The original extension does not support themeable colors anyway.

**Comment by TabithaLarkin** [comment]
@misolori Is there anything I can do to get this over the line? What's the blocker here?

**Review by miguelsolorio — APPROVED** [review]
Thanks for the ping, LGTM let's get this merged and see how it looks like on Insiders. Thank you!

**Pull request merged**
