### PR TITLE
Allow users to config launch args

### PR DESCRIPTION
**Pull request by Frederick888**

### CODE REVIEW

**Comment by Frederick888** [comment]
I've signed the agreement... Do I need to take any further actions?

**Comment by joaomoreno** [comment]
Why do you need this? Can't you create a shellscript in your system which simply calls `code` with those extra args?

**Comment by Frederick888** [comment]
@joaomoreno Because the Google Chrome shell wrapper has provided such a functionality and actually I have to used exactly the same arguments for VSC as well to make it work normally. So I made the changes and linked the Chrome arguments file to the one of VSC.

**Comment by joaomoreno** [comment]
Could you write a shell script for your system that picks that same args file and forwards the args to `code`, then?

**Comment by Frederick888** [comment]
@joaomoreno Ok, cool... If it does not fit your taste I'd simply close it. It's just a suggestion anyway :)

**Comment by joaomoreno** [comment]
It's all about composition and usefulness. If it's a feature not a lot of people need and you can compose it around VS Code, you're better off doing so. 👍 

Thanks for the understanding.

**Pull request closed without merging**
