### PR TITLE
Update to `playwright@1.11.1`

### PR DESCRIPTION
**Pull request by alexdima**

### CODE REVIEW

**Comment by rluvaton** [comment]
Does this issue relate this problem - https://github.com/microsoft/vscode/pull/125753#issuecomment-856864298

**Comment by alexdima** [comment]
@rluvaton Yes, I've also seen `playwright` download timeout issues and my hope is that updating to a newer version will help.

**Comment by rluvaton** [comment]
@alexdima I think it’s working now (In another PR there was no problem)

**Comment by alexdima** [comment]
@mjbvz I am running into problems with the browser integration tests on Windows after upgrading Playwright (which upgrades Firefox). I think this might have something to do with our webviews, it might be related to the usage of the `clipboard-read` or `clipboard-write` attributes as I see that logged as a warning in Firefox. Unfortunately, I am blocked as the integration tests are not self-contained. They load code from `https://UUID.vscode-webview-test.com/` so I cannot fix them without help from you.

. Here are the steps to reproduce:
* checkout this branch on Windows
* run `.\resources\server\test\test-web-integration.bat --browser firefox`
* observe how webviews don't really render at all, which I believe leads to the many test failures (on the build machine the test will time out because we allow 1 minute per test and after 10 failing tests the entire step will timeout).

**Pull request merged**
