### PR TITLE
added a warning when user tries to commit, and there are unsaved files

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
fixes the issue #33004

### CODE REVIEW

**Comment by pradeepmurugesan** [comment]
screen shot 2017-10-16 at 19 12 28

The tests passed in my local.. I am not sure why it fails in the build agent. Any idea ?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Comment by buggymcbugfix** [comment]
Is there a flag to turn this off?

**Comment by joaomoreno** [comment]
image

**Comment by buggymcbugfix** [comment]
Valeu!

**Pull request merged**
