### PR TITLE
Fix nushell

### PR DESCRIPTION
**Pull request by WeetHet**
In Nushell, strings are treated as strings, not as paths. To treat string as a path, we need to add ^ before `'${process.execPath}'`

### CODE REVIEW

**Comment by meganrogge** [comment]
Thanks for the PR. I want to be sure that I'm testing it right - I installed nushell and added it to my terminal profiles by providing the `path`. It works when I create a terminal. 

Can you pls provide an example of what didn't work before that works with these changes?

Thanks

Screenshot 2023-05-02 at 7 33 46 AM

**Comment by WeetHet** [comment]
> @meganrogge this is the code we run when vscode starts to grab the environment from the user's shell and use that as vscode's environment. From my memory, I think a way to verify it could be
> 
> * Set some environment variable in your nushell config
> * Verify that variable ends up in vscode's environment, eg by checking `process.env` in an extension
> 
> You could also just step through it or log something to verify that it spawned nushell successfully. But @WeetHet lmk if you had a different specific scenario in mind

Sure, this one is pretty accurate

**Comment by meganrogge** [comment]
I do see it reflected here though - both with and without this PR's changes

**Comment by WeetHet** [comment]
Without this PR vscode gives an error under macOS

**Comment by meganrogge** [comment]
@WeetHet are you launching from the dock? A gif of how you're reproducing the error would be helpful

**Comment by WeetHet** [comment]
> @WeetHet are you launching from the dock? A gif of how you're reproducing the error would be helpful


https://user-images.githubusercontent.com/43210583/236015372-a90a1796-5426-4199-8dc7-76bd888037bd.mov

**Review by meganrogge — APPROVED** [review]

**Comment by meganrogge** [comment]
Thanks, it works 👍🏼

**Review by rzhao271 — APPROVED** [review]

**Pull request merged**
