### PR TITLE
Including ` as part of foldEndPairCharacters

### PR DESCRIPTION
**Pull request by sumanbk92**
This PR fixes folding lines incase of backticks (`)

### CODE REVIEW

**Review by rheh — COMMENTED** [review]
Should a new test be added to folding.test.ts?

**Comment by sumanbk92** [comment]
> Should a new test be added to folding.test.ts?

Could you let me know how to run the folding.test.ts test file alone ?

**Comment by rheh** [comment]
> > Should a new test be added to folding.test.ts?
> 
> Could you let me know how to run the folding.test.ts test file alone ?

I think this should help https://github.com/microsoft/vscode/blob/master/test/unit/README.md

**Review by sumanbk92 — COMMENTED** [review]
Added Tests and `folding.test.ts ` was not found under `extensions/typescript-language-features/src/test`.
Hence added appropriate test under `extensions/html-language-features/server/src/test/folding.test.ts`

**Review by sumanbk92 — COMMENTED** [review]
@aeschli @doudou @threeve Please review this PR

**Review by rheh — APPROVED** [review]

**Comment by aeschli** [comment]
The test `extensions/html-language-features/server/src/test/folding.test.ts` is not related to the code change in `extensions/html-language-features/server/src/test/folding.test.ts`. I suggest to remove the test.

**Comment by sumanbk92** [comment]
Removed unnecessary test. 
Please review, @mjbvz

**Comment by mjbvz** [comment]
Please create an issue the describe the problem this PR fixes. We need this for tracking what we fix each iteration

**Comment by sumanbk92** [comment]
> Please create an issue the describe the problem this PR fixes. We need this for tracking what we fix each iteration

The issue was created already. It is being tagged/referenced above in this PR.

Link: https://github.com/microsoft/vscode/issues/110097

**Comment by mjbvz** [comment]
Thanks. Will be in the next VS Code insiders build

In the future, make sure include the issue number in the PR issue description (or the commit message using `fixes #110097` so that merging the PR closes the issue too)

**Pull request merged**
