### PR TITLE
Multiple theme ID scopes for customisation

### LINKED ISSUE #103694: [themes] settings: support for multiple theme names in VSCode colorCustomization
Reading the documentation on [theme customisation](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme), the syntax only allows an override for one theme.

Sometimes overrides may need to apply to different themes (e.g. all dark, light or material themes), for reasons mainly about accessibility and comfort. This has actually been asked about on [StackOverflow](https://stackoverflow.com/questions/55054156/how-to-customise-the-textmaterules-for-multiple-themes-in-vs-code).

Patterns might be useful, i.e. (`[...Material Theme...]`, `[...Material Theme Lighter]`).
Also arrays with any syntax you recommend: `[Atom One Dark] [Default Dark+]`.

[12/08/2020] Editing this to add a gist for code bloat: [`settings.json`](https://gist.github.com/nedevel/3c44ea606e0ab19765b527e4a642eee1#file-settings-json). While extracting those settings into an MVCE, I saw 3 JSON errors.

### PR DESCRIPTION
**Pull request by ghost**
Closes #103694.

- [x] Implement theme ID array scopes in theme customizations.
- [x] Implement theme ID pattern scopes in theme customizations.

For theme color customisations, this PR adds theme scoping to multiple themes (starting with 9371dc7).

Users can apply color customisations for one or multiple IDs. Syntax example:
```json
{
  "editor.tokenColorCustomizations": {
    "[Default Dark+] [Default Light+]": {
      "textMateRules": [
        {
          "scope": ["directive"],
          "settings": { "fontStyle": "bold" }
        }
      ]
    },
    "[Default...]": {
      "textMateRules": [
        {
          "scope": ["comment", "entity"],
          "settings": { "fontStyle": "" }
        }
      ]
    },
    "[...Dark+]": {
      "textMateRules": [
        {
          "scope": ["storage", "keyword", "entity.attribute-name"],
          "settings": { "foreground": "#569cd6" }
        }
      ]
    }
  }
}
```

This PR enhances four `settings.json` keys:
- `workbench.colorCustomizations`
- `editor.colorCustomizations`
- `editor.tokenColorCustomizations`
- `editor.semanticTokenColorCustomizations`

### CODE REVIEW

**Comment by lmn8** [comment]
@aeschli Array elements in the sections aren't concatenated.
In https://github.com/microsoft/vscode/issues/103694#issuecomment-678531076, only the last "textMateRules" works.

**Comment by EPonyA** [comment]
This feature is an awesome contribution!

**Comment by aeschli** [comment]
We don't use `...` anywhere else a wildcard. What about '*' ? 

Also, please try to keep the changes minimal (avoid the chnages const -> let)

**Pull request closed without merging**
