### PR TITLE
Allow zooming with ctrl+mousewheel combination

### PR DESCRIPTION
**Pull request by kisstkondoros**
related #6978

### CODE REVIEW

**Comment by bpasero** [comment]
I am not sure we want to zoom the entire UI when you use the mousewhell, I would expect only the editor font to increase. Thereby moving to @alexandrudima

**Comment by kisstkondoros** [comment]
@bpasero this change is exactly about that, it changes the font-size and line-height for the editor only (not a UI zoom)

**Comment by bpasero** [comment]
Ah nice, even better 👍

**Comment by asifm** [comment]
Currently Ctrl + +/- zooms the entire UI. I hope that behavior will change too? That is, only the code area font size will change?

**Comment by kisstkondoros** [comment]
@asifm I thought about including that as well, but I wanted to leave this simple.
I think it is better to file a separate issue for that, I would be more than happy to implement it once this PR is merged 😃

**Comment by asifm** [comment]
@kisstkondoros Looks like there's an open issue #1348 and some differences of opinion. I like what @purplecabbage suggested: "Please map ctrl+- to editor view, or better yet, whichever view has focus."

**Comment by alexandrudima** [comment]
:+1: Very nice, thank you! I shuffled the code around to bring all the logic in the /editor/ folder (not have editor knowledge in /base/) and to make it that ctrl + scroll is looked for only on editor (not on trees, etc.)

**Pull request merged**
