### PR TITLE
Package json info

### PR DESCRIPTION
**Pull request by jk21**
Implement hover + version suggestions for latest packages with npm view. Making it possible to use the suggestions with custom registrys.

Update of https://github.com/Microsoft/vscode/pull/56040

Autocomplete of package-names is still done via npms.io and more difficult to replace.

@aeschli please advise if more is needed here. I am happy to progress if needed.

### CODE REVIEW

**Comment by jk21** [comment]
@aeschli can you plase review or let me know how to proceed? thx.

**Comment by aeschli** [comment]
Sorry, I will look at it as soon as I have time, hopefully this week

**Comment by jk21** [comment]
@aeschli ping :-)

**Comment by aeschli** [comment]
Made some simplifications for parsing the result. Pushed the PR

Thanks @jk21 !

**Pull request merged**
