### PR TITLE
Enable macOS notarization

### LINKED ISSUE #74782: Investigate: macOS notarization
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

and

https://github.com/electron/electron/issues/18609

//cc @joaomoreno 

If VSCode fails to launch VSCode on macOS Catalina do this:

image

### PR DESCRIPTION
**Pull request by joaomoreno**
This PR fixes #74782 

The signing service currently has an issue, so the app bundle comes back broken. We're waiting on a fix from their side.

### CODE REVIEW

**Comment by bpasero** [comment]
🥂

**Comment by jtlapp** [comment]
Has this been released yet? I downloaded VSCode [from code.visualstudio.com](https://code.visualstudio.com/docs/?dv=osx) today, February 8, 2020, and it still gives me this error message on Catalina.

**Comment by stripedpajamas** [comment]
@jtlapp this change is in master but hasn't been released yet (should be in insider's build).

**Comment by joaomoreno** [comment]
@stripedpajamas We're currently finishing up a release, so Insiders is locked for a couple days.

**Pull request merged**
