### PR TITLE
 Add progress indicator to SCM in activity bar while QuickDiff is preparing

### LINKED ISSUE #136968: Add a progress indicator to SCM icon in activity bar when QuickDiff is being prepared
Issue Type: <b>Feature Request</b>

A source control extension I develop implements a QuickDiffProvider whose provideOriginalResource method returns uris that get resolved by another of my extensions implementing a FileSystemProvider.

When the original resource is being fetched over a slow connection it may be several seconds (or longer) before the text of the original resource arrives. Meanwhile the user has no indication that the QuickDiff changebars haven't yet been computed.

I propose adding a progress indicator to the SCM icon in the activity bar while the quickdiff is being prepared.

I will submit a PR.

VS Code version: Code - Insiders 1.63.0-insider (3a79384dbf81dc6eba781ff669996d2042ca3b72, 2021-11-11T05:15:37.996Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR closes #136968

@bpasero are you willing to review this?

### CODE REVIEW

**Comment by bpasero** [comment]
Rather @joaomoreno

**Review by joaomoreno — APPROVED** [review]
@bpasero, rather @lszomoru.

But I like it!

**Comment by lszomoru** [comment]
Thanks @gjsjohnmurray! Will take a look at this later today!

**Comment by lszomoru** [comment]
LGTM!

**Pull request merged**
