### PR TITLE
support custom cursor height

### LINKED ISSUE #27931: Configure cursor height
Using the `caret_extra_*` properties in Sublime and with css in Atom, it is possible to configure the height of the cursor. I would love to be able to make the cursor a little bit taller. Is this possible with VSCode? Couldn't find any mention of it in issues or via Google.

### PR DESCRIPTION
**Pull request by jens1o**
resolves #27931 

Do you have a proposal for the setting description? English is not my first language... :/

### CODE REVIEW

**Comment by michaelgmcd** [comment]
Is there anything I can help with to get this moved along. Would love to see this get merged.

**Comment by jens1o** [comment]
@michaelgmcd When you see any errors I did, feel free to say them. :)

**Comment by michaelgmcd** [comment]
Not familiar with the codebase so I can't really comment on your specific changes, mainly just pinging this PR as it's been over a month without any activity.

**Comment by michaelgmcd** [comment]
Pinging this PR again. Any updates?

**Comment by jens1o** [comment]
Waiting for a review from @rebornix

**Comment by Reegan01** [comment]
Anyone got solution?

**Comment by rebornix** [comment]
As we didn't plan to have feature in in near future, I'd like to close it for now to help us better maintain issues. We can reopen it when we are going to implement this feature in a proper way. Thanks anyway for your contribution!

**Pull request closed without merging**
