### PR TITLE
[folding] provide a toggle for non-selection aware fold level commands

### LINKED ISSUE #55252: When folding, area of cursor does not get folded
- VSCode Version:
vscode version
- OS Version:
Win 10 64 bit

Steps to Reproduce:

1. Open a file which has different folding levels through indentation
2. Move the cursor to a specific level x
3. Run command 'Fold level x'

All areas of that level getting folded but not the one the curor is currently in.

vs-code-issues

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by SnirBroshi**
This PR fixes #55252

To test this, go into any file with some folding regions, e.g.
```js
if (1) {
    console.log('foo');
    if (2) {
        console.log('bar');
    }
    if (3) {
        console.log('baz');
    }
}
```
place the cursor inside one of the regions, for example inside the `if (2)`, and then run `Fold Level 2` (in this case).
You'll see that the `if (3)` is folded, but not the `if (2)`, because your cursor is inside.

Now turn off the new setting `editor.foldLevelCommandsKeepSelectionVisible`, and repeat these steps, and the `if (2)` will fold as well this time.

I'm not sure whether a setting is the best UX for this, but I thought duplicating the 7 `Fold Level X` commands to add `Fold Level 
X Besides Current Position` would be too much commands. maybe the setting should be an enum of some sort?

I didn't change the `Fold All` command as it already ignored the cursor position, should I make it also aware of this setting? its name makes it sound like it should really fold everything regardless of the setting.

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks for the work. I don't like the setting so much, for the reasons you mentioned.. It's confusing that the setting doesn't apply for all folding commands (both with true or false). But doing  that would be a behavior change for `Fold All`. Also users might want both functionality, depending on the situation.

I think it would be ok to duplicate the commands. I wouldn't add any keybindings by default, but users can do that.

Alternative idea is to allow double invocation of the command.
- on the first invocation of the command, we have the current behavior
- on a subsequent invocation, we also fold the region at the cursor position

For the implementation that means:
If the command is invoked and all ranges of level x are already folded, then also fold the region the cursor is in.

Would that be good enough for you as a user?

**Comment by NotWearingPants** [comment]
> Would that be good enough for you as a user?

While it's an innovative solution, I don't think it's good - as you can see in #55252, a big issue is the confusion this behavior causes:

> many times it seems like the fold command doesn't work at all until you realize that your cursor position is preventing it from folding. [...] it's sufficiently confusing enough when folding doesn't work due to cursor position 

I've also experienced much confusion from this, especially when trying to figure out how these level commands work.

So I think the best solution so far is to duplicate the commands without keybindings.
This will provide the feature itself, and allow users who are aware of the problem to switch their keybindings to avoid being confused in the future, but there is still a lack of discoverability - it will be difficult for users to realize that the commands are affected by the cursor position, and then to find that a second set of these commands exists. This also applies to the setting solution.

I'll push an update soon, thanks!

**Comment by NotWearingPants** [comment]
image
@aeschli I've replaced the previous fix with adding `Fold Level X Including Selection`, and also added `Fold All Except Selection` to match it.

**Comment by NotWearingPants** [comment]
@aeschli What's up?

**Comment by aeschli** [comment]
Thanks @NotWearingPants !
There was another PR that added a command 'Fold All Except Selection'. Following that, I suggest
- rename the label of the existing command `Fold Level X` to `Fold Level X Except Selection`
- name your new commands `Fold Level X` 

Don't change the ids of the existing commands as they might be referenced in user keybindings.

Also it would be great to have a test. See https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/folding/test/foldingModel.test.ts#L479 as an example

**Comment by aeschli** [comment]
Closing the PR as there hasn't been any progress lately. Happy to reopen if there's any interest to continue. See my last comment for what still needs to be done.

**Pull request closed without merging**
