### PR TITLE
Implement toggle aware icons and labels in command actions

### LINKED ISSUE #92283: Handle toggle aware icons and labels in ICommandAction
Since [ICommandAction](https://github.com/microsoft/vscode/blob/849aadb72c43dffa8018ec23bca82e6c35d30b3c/src/vs/platform/actions/common/actions.ts#L23) handle toggle state, it shall also provide support for icons and labels for toggled and untoggled state. 

This allows menu registry to register single toggle action with icons and labels toggle state aware.

### PR DESCRIPTION
**Pull request by sandy081**
This PR fixes #92283

Add support for toggle aware icon and title in command action

### CODE REVIEW

**Comment by sandy081** [comment]
@jrieken This PR is still in progress. 

I am currently stuck at handling toggle state aware titles. I introduced toggle-aware icon (as discussed) and also needed to introduce the same for the title. 

Menu items are sorted by `title` and in case of toggle-state aware items, title is computed based on toggle state. 

https://github.com/microsoft/vscode/blob/37da787e91f01c6cfee3d4c50992782d9e072d92/src/vs/platform/actions/common/menuService.ts#L174-L176

Any suggestions on how to sort these? Shall I compute the title by evaluating the toggle state expr?

I am also not sure how to handle such commands while displaying in the keybindings editor. What title shall I have to show. This raises the point that whether this toggle command action is a single  or two command actions? IMO they are two different command actions as they perform two different actions. If so one has to register two command actions for each state. What do you think?

**Comment by jrieken** [comment]
> IMO they are two different command actions as they perform two different actions. If so one has to register two command actions for each state. What do you think?

Yeah - that was always my point of view and this is how it is currently achieved. Tho, I think it is a little cumbersome because most things are equals (e.g keybinding). On the other hand, having two distinct commands leaves no uncertainty in what direction to toggle e.g what your current state is. A related, alternative, design might be a richer toggled-property. Instead of a simple context key expression have an object with describes all toggle-properties (label, icons, tooltip (?)). Tho, you might endup repeating the whole command action data here... That would bring you to what's discussed here (which I am not a fan of): https://github.com/microsoft/vscode/commit/9f29782486dd19378ee1dceb0cb4064100096f73

**Comment by sandy081** [comment]
@jrieken Looks like we cannot always split a toggle command into two, since there is a need to support a single command that can be toggle-able and users can attach keybindings to that.

Here is my suggestion, I would still want to go with current approach but instead   of having toggle-able titles, lets have toggle-able tooltips. Thinking about the toggle-able commands, I feel that the title shall always be fixed and saying that it is a toggle command. It's the tool tip that shall say the state of the command.

So I would introduce - `toolTip` property to `ICommandAction`. what do you think?

**Comment by jrieken** [comment]
My preferred solution (in the name of simple consumer adoption) goes likes this

```
export interface ICommandAction {
	id: string;
	title: string | ILocalizedString;
	category?: string | ILocalizedString;
	icon?: { dark?: URI; light?: URI; } | ThemeIcon;
	precondition?: ContextKeyExpression;
	toggled?: ContextKeyExpression | { 	toggled: ContextKeyExpression, icon, title };
}
```

Overall, adding tooltip makes sense, both for all states. An alternative is to have `ToggleTitle`, `ToggleIcon` etc but would increase adoption cost and also somehow spread the toggle-ability everywhere

**Comment by sandy081** [comment]
Discussed with @jrieken and agreed upon adding additional properties to `toggled` property and we will add `icon` and `tooltip` for now. `title` can be added after when needed.

```ts
export interface ICommandAction {
	id: string;
	title: string | ILocalizedString;
	category?: string | ILocalizedString;
    tooltip?: string | ILocalizedString;
	icon?: { dark?: URI; light?: URI; } | ThemeIcon;
	precondition?: ContextKeyExpression;
	toggled?: ContextKeyExpression | { toggled: ContextKeyExpression, icon?: { dark?: URI; light?: URI; } | ThemeIcon, tooltip?: string | ILocalizedString; };
}
```

**Comment by eamodio** [comment]
To me this seems like unnecessary complexity, why build this on top of toggled (which currently is just for showing/hiding a checkmark -- right?). Menu placements are already conditional, so why not just allow changing the title/icon in the placement. IMO, that is more powerful, flexible, and easier to understand.

For example, if I have a command `toggle.command`, and depending on the context, I can have a menu/command palette placement for when it is `on` showing `Toggle Off` with a specific icon (if desired) and a placement for when it is `off` showing `Toggle On` with its specific icon.

**Comment by jrieken** [comment]
> Menu placements are already conditional, so why not just allow changing the title/icon in the placement. IMO, that is more powerful, flexible, and easier to understand.

The only reason they are conditional is that menus stay small and don't show a bunch of meaningless entries - this has nothing to do with the properties of an action (label, icon etc). I really don't understand, and you need to explain this, why for instance the save command should be called "Save" in the context menu and "Delete" in the command palette.

**Comment by sandy081** [comment]
@jrieken Updated the PR aligning to our discussion. Please take a look.

**Review by jrieken — APPROVED** [review]

**Pull request merged**
