### PR TITLE
Fix #57222 - improve no user.email/user.name config error message

### LINKED ISSUE #57222: Git extension should warn of missing user.email and user.name
Issue Type: <b>Bug</b>

Whenever i make any commit , it is showing "Git:failed to execute".what should I do??

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.136.0
material-icon-theme|PKi|3.5.3
LiveServer|rit|5.1.1

</details>

### PR DESCRIPTION
**Pull request by Git-Lior**
The new message looks like this:

image

Tell me if anything can be improved. Thanks!

### CODE REVIEW

**Comment by Git-Lior** [comment]
Now the error message looks like this:

image

@dzienisz is this better?

**Comment by dzienisz** [comment]
@Git-Lior I think so. Thanks!

**Comment by mc10** [comment]
For consistency, maybe flip the two current lines so email comes first and name comes second?

**Comment by Git-Lior** [comment]
@mc10 you're correct, done 👍

**Comment by joaomoreno** [comment]
Thanks! :beers:

**Pull request merged**
