### PR TITLE
updateInlineDecorations when model content changes

### LINKED ISSUE #43199: Debugger inline values jumps to second line when hit enter.
### Issue Type
Bug

### Description

Set "debug.inlineValues": true.
Set breakpoint somewhere.
After paused on the step, goto the end of the line and hit enter.

**Before**
`const stack = [];| stack = Array(2) [Object, Object]`

**After**
```
const stack = [];
| stack = Array(2) [Object, Object]
```

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:02:34.244Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.90GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_254014|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.0
vscode-eslint|dba|1.4.5
vscode-great-icons|emm|2.1.24
auto-rename-tag|for|0.0.15
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
cpptools|ms-|0.14.6
licenser|ymo|1.1.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

### PR DESCRIPTION
**Pull request by nojvek**
updateInlineDecorations when model content changes

 Fixes #43199: Debugger inline values jumps to second line when hit enter

### CODE REVIEW

**Comment by nojvek** [comment]
@isidorn want to take a look at this smol PR ?

**Comment by isidorn** [comment]
@nojvek thanks a lot for your PR!
I tried it out and it nicely fixes the issue. However what I do not like about this approach is that if the user is typing you can potentially update all the decorations in the editor for each keystroke - which can be expensive.
So I suggest to do this using the debounce pattern - only once the user has stopped typing to update the decoarionts. IMHO this can be achieved easily with a scheduler using a 200ms timeout.

**Comment by nojvek** [comment]
Actual updating of the inline Decorations is already done on a scheduler right?

**Comment by isidorn** [comment]
@nojvek no, they are only removed with a scheduler. Not refreshed, if I understand the code correclty.

**Comment by nojvek** [comment]
You are right. 

Fixed it to use a scheduler now.

**Comment by isidorn** [comment]
@nojvek thanks for the PR, merging it in, will polish it just a bit on top.

**Pull request merged**
