### PR TITLE
Refactor css

### PR DESCRIPTION
**Pull request by Kalmaegi**
For https://github.com/microsoft/vscode/issues/165169
- [x] src/vs/workbench/contrib/welcomeWalkthrough/browser/walkThroughPart.ts

### CODE REVIEW

**Comment by weartist** [comment]
@chrmarti need your help, thanks

**Comment by weartist** [comment]
@chrmarti Can I still provide anything

**Comment by chrmarti** [comment]
@weartist LGTM, thanks for your PR!

**Review by chrmarti — APPROVED** [review]

**Review by jrieken — APPROVED** [review]

**Comment by weartist** [comment]
> @weartist LGTM, thanks for your PR!

Thank you for your help！

**Pull request merged**
