### PR TITLE
Fixed wrong values in german translation

### PR DESCRIPTION
**Pull request by cmllr**
In the about Dialog (Help -> Info) Node.js is literally translated to "knot".
In the menu Translation for "Open recent", the sentence is translated literally which causes that the word for "files" is missing.

### CODE REVIEW

**Comment by squarerootfury** [comment]
A crap, overread the note "do not edit this file". Where can I contribute this translation fixes?

**Comment by jrieken** [comment]
@dbaeumer will know

**Comment by dbaeumer** [comment]
@squarerootfury we are currently working on this. For the meantime the only thing you can do is to open an issue here. 

@johnliu2016 I assign this to you. Can you please feed the corrections back into the translation repository.

**Comment by johnliu2016** [comment]
Thanks, ported this issue to loc side for translation fix

**Comment by johnliu2016** [comment]
Loc fix's in.

**Pull request closed without merging**
