### PR TITLE
Add Productivity into extension categories

### PR DESCRIPTION
**Pull request by Huachao**

### CODE REVIEW

**Comment by joaomoreno** [comment]
Thanks! 🎆

**Comment by jjuback** [comment]
What's the status of the Productivity category? It was visible in the marketplace two days ago (with a handful of extensions), but now it's gone. The enum value shows up when editing package.json, but when I tried to publish today I got this error:

Error: Failed Request: Bad Request(400) - The category 'Productivity' is not available in language 'en-us'.

NBD, I can continue to use Other, just asking for clarification.

**Comment by joaomoreno** [comment]
cc @seanmcbreen

**Comment by seanmcbreen** [comment]
Appologies we had an error where the category from another part of the marketplace showed up for VS Code.  We removed it and reverted back to the original 6 categories [which does not include productivity].  Sorry for the confusion.

**Pull request merged**
