### PR TITLE
Markdown region folding

### LINKED ISSUE #45118: Markdown: add region folding to syntax folding
https://github.com/Microsoft/vscode/pull/44795 adds language aware folding to markdown (Thanks a lot!)

Don't forget to also support the folding regions that we already support for markdown:
```
		"markers": {
			"start": "^\\s*<!--\\s*#?region\\b.*-->",
			"end": "^\\s*<!--\\s*#?endregion\\b.*-->"
		}
```
 Ideally your scanner known where the comment tokens are and can do this more efficiently (and correct) that a regexp on every line.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Closes #45118. 

In some cases the region comments get parsed as nested children of other elements and are not registered as being proper folding regions. This seems to only occur with wacky formatting, so I'd vote to keep the simple implementation as is unless it comes up in more common cases.

### CODE REVIEW

**Review by mjbvz — COMMENTED** [review]
Change looks good. Thanks for looking into this!

Let's hold of on merging this until next iteration though if that's ok with you. That way we get more users trying it out in insiders

**Comment by JacksonKearl** [comment]
Sure, makes sense

**Comment by JacksonKearl** [comment]
@mjbvz this should be good to merge now

**Comment by mjbvz** [comment]
@JacksonKearl Thanks. Please keep an eye on incoming issues for markdown folding (in insiders only of course)

**Pull request merged**
