### PR TITLE
Fixed #71134

### LINKED ISSUE #71134: Can't use numeric keyboard for search on macOS
Issue Type: <b>Bug</b>

When I start typing file name in file explorer **iec104** and type **104** on addition keyboard (right from arrows) **VSC** didn't catch that input.

If I type **104** on main keyboard (numbers on top of qwerty keys) **VSC** catch that input and find my file.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3617)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.65GB (0.36GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.4.1
snort|inf|1.1.4
autoconf|mae|0.0.7
cpptools|ms-|0.22.1
bash-beautify|sha|0.1.1
markdown-all-in-one|yzh|2.2.0

</details>

### PR DESCRIPTION
**Pull request by kostyabushuev**

### CODE REVIEW

**Review by diguifi — APPROVED** [review]

**Comment by joaomoreno** [comment]
Thanks!

**Comment by jeanp413** [comment]
@kostyabushuev @joaomoreno I think this should also be fixed here
https://github.com/microsoft/vscode/blob/52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L532-L542

**Comment by kostyabushuev** [comment]
Hmm, interesting
I resumed to **[my commit](https://github.com/kostyabushuev/vscode/commit/ee8372c0c798f116b6bced5ee1b61223ec5255dd)**, reinstall dependencies and build.
And I dont have the bug

**Comment by jeanp413** [comment]
Try using up-to-date master branch which already has the changes from this PR

**Comment by kostyabushuev** [comment]
@jeanp413 
could you help me with this bug?
I tried fix it, but can not understand how do it

**Comment by jeanp413** [comment]
@kostyabushuev I think I fixed it with this changes. I tested it on ubuntu 18.04 and it's working. Not sure if you need to create a new PR or push the changes here and @joaomoreno could merge it again.
```diff
--- a/src/vs/workbench/services/keybinding/browser/keybindingService.ts
+++ b/src/vs/workbench/services/keybinding/browser/keybindingService.ts
@@ -46,7 +46,7 @@ import { IKeymapService } from 'vs/workbench/services/keybinding/common/keymapIn
 import { getDispatchConfig } from 'vs/workbench/services/keybinding/common/dispatchConfig';
 import { isArray } from 'vs/base/common/types';
 import { INavigatorWithKeyboard } from 'vs/workbench/services/keybinding/common/navigatorKeyboard';
-import { ScanCodeUtils, IMMUTABLE_CODE_TO_KEY_CODE } from 'vs/base/common/scanCode';
+import { ScanCode, ScanCodeUtils, IMMUTABLE_CODE_TO_KEY_CODE, IMMUTABLE_KEY_CODE_TO_CODE } from 'vs/base/common/scanCode';
 
 interface ContributedKeyBinding {
        command: string;
@@ -535,6 +535,29 @@ export class WorkbenchKeybindingService extends AbstractKeybindingService {
                        return false;
                }
                const code = ScanCodeUtils.toEnum(event.code);
+
+               const NUMPAD_PRINTABLE_SCANCODES = [
+                       ScanCode.NumpadDivide,
+                       ScanCode.NumpadMultiply,
+                       ScanCode.NumpadSubtract,
+                       ScanCode.NumpadAdd,
+                       ScanCode.Numpad1,
+                       ScanCode.Numpad2,
+                       ScanCode.Numpad3,
+                       ScanCode.Numpad4,
+                       ScanCode.Numpad5,
+                       ScanCode.Numpad6,
+                       ScanCode.Numpad7,
+                       ScanCode.Numpad8,
+                       ScanCode.Numpad9,
+                       ScanCode.Numpad0,
+                       ScanCode.NumpadDecimal
+               ];
+               const immutableScanCode = IMMUTABLE_KEY_CODE_TO_CODE[event.keyCode];
+               if (NUMPAD_PRINTABLE_SCANCODES.indexOf(code) >= 0 && code === immutableScanCode) {
+                       return true;
+               }
+
                const keycode = IMMUTABLE_CODE_TO_KEY_CODE[code];
                if (keycode !== -1) {
                        // https://github.com/microsoft/vscode/issues/74934
```

**Comment by jeanp413** [comment]
Created another PR #77911 with the proposed solution

**Pull request merged**
