### PR TITLE
Adding the possibility to resize the content hover widget

### LINKED ISSUE #14165: Configure tooltip max width
When you hover over a type in a TypeScript file, the tooltip that appears has a very low max width, making it difficult to read long type signatures.

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/14165

This PR adds the possibility to resize the content hover. Some notes about the PR:

- The height is limited by the current total height of the hover widget given the current width. 
- The width is limited by the width of the screen.
- The content hover is positioned with regards to the positioning preference (above or below) in the settings. If there is no space, it is placed on the other side. If the widget size has been persisted to a size that does not fit in the current screen, a smaller size than the persisted size is used. 
- As soon as the widget hover is resized, the size is persisted for the duration the VS Code window is active or until refreshing the page. The reason one single persist size is not used, as is the case for the suggest hover, is because of several factors:
  - The content hovers are of different sizes by default, some are wide, some are not. From what has been observed so far the suggest hover has always the same width.
  - Using one persist size would imply having to find the maximum possible width and height achievable in order not to set a width or height higher than these thresholds. Otherwise it may be that we would show a hover bigger than what is necessary to show all the contents. This would add complexity to the code.
  -   Using one persist size could cause unintuitive sizing of the content hovers. The user most likely wants to resize content hovers on a per token basis. 
- The above points also explain why the content hover sizes are persisted only during the period of time VS Code is active or not refreshed yet, because otherwise many hover widget sizes would be persisted and take up memory.

Below you may find an example of the content hover resizing. The GIF is a bit out of date, the code has recently been modified in order to have sashes of the right size, ie, so that they are not overflowing over the height and width by 4px.

https://user-images.githubusercontent.com/61460952/227253403-8df965d3-e4fb-45f0-86fd-61450883969b.mov

### CODE REVIEW

**Comment by felixfbecker** [comment]
I can't wait for this to land ❤️  It will make reading long TypeScript errors so much easier.

**Comment by drupol** [comment]
We are all waiting for that I think :)

**Comment by aiday-mar** [comment]
Hey all, thank you all for your interest. I apologize, it will take a bit more time to release the code, as it requires some refactoring and polishing. Thanks again

**Comment by with-heart** [comment]
Thanks so much @aiday-mar for your time and effort implementing this. It will be a nice change once it lands! ❤️‍🔥

**Comment by aiday-mar** [comment]
Current PR that is worked on is the following: https://github.com/microsoft/vscode/pull/178811. It contains review changes and refactoring changes. This one will be discontinued.

**Pull request closed without merging**
