### PR TITLE
Feat: Add PascalCase to CaseActions

### LINKED ISSUE #206257: Pascal Case Actions
Currenctly we dont have a Pascal case action, an i cant figure out how to combine the current transforms to easily transform selections to PascaCase without perform another selection.

Here a table with how its should works

| before| after |
|------ | ------- |
|foo bar | FooBar | 
|foo_bar | FooBar |
|foo-bar | FooBar |
|fooBar | FooBar|
|Foo Bar | FooBar |

### PR DESCRIPTION
**Pull request by IncognitaDev**
This PR adds a new CaseAction that transform other cases to PascalCase once its not easily to do with combinations of current cases transforms.

To test: 

- clone this branch
- compile 
- run
- write a text with any case
- select the text
- call the command pallete
- select Transform to PascalCase

resolve #206257

### CODE REVIEW

**Comment by IncognitaDev** [comment]
@microsoft-github-policy-service agree

**Review by connor4312 — APPROVED** [review]

**Comment by IncognitaDev** [comment]
@connor4312 I think i shoudnt have to update manually, what i should do now?

**Comment by IncognitaDev** [comment]
@microsoft-github-policy-service agree

**Review by Tyriar — APPROVED** [review]

**Comment by connor4312** [comment]
thanks for the PR!

**Pull request merged**
