### PR TITLE
Terminal race between process exit and on ready listeners

### LINKED ISSUE #69403: Relative links do not work on task output terminal
- VSCode Version: 1.31.1 (also seeing it when debugging master)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a task that runs in a directory other than the workspace folder and outputs a relative path from that directory
2. Try and click on the resulting link

This was fixed for normal terminals with #27107 but doesn't work with tasks. Firing it up under the debugger, I see that links are resolved before the the processCwd is registered with the link handler.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #69403

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
It looks like this will fix the problem but I think this will push out showing anything in the terminal by another full round trip to the ext host. I think a better fix might be to change: 

```ts
onProcessIdReady: Event<number>
// to
onProcessReady: Event<{ pid: number, cwd: string }>
```

**Comment by alexr00** [comment]
@Tyriar, how do you want that handled here: https://github.com/Microsoft/vscode/blob/alexr00/terminalExitRace/src/vs/workbench/contrib/terminal/common/terminalProcessExtHostProxy.ts#L80
The only existing way to get the initial cwd there involves a promise.

**Comment by Tyriar** [comment]
@alexr00 it would be changing this event in TerminalProcess and in the proxy to include initialCwd, we may not need the separate initialCwd call then also as it's readonly after spawning I believe.

https://github.com/microsoft/vscode/blob/9f1040860b9e833ae60c1cf88818cca4c0ed3783/src/vs/workbench/contrib/terminal/common/terminalProcessExtHostProxy.ts#L22-L23

**Comment by alexr00** [comment]
I've made the event changes, but I'm still not sure I understand what you want to do [here](https://github.com/Microsoft/vscode/blob/alexr00/terminalExitRace/src/vs/workbench/contrib/terminal/common/terminalProcessExtHostProxy.ts#L80).
Do you want to remove `getInitalCwd()` from [here](https://github.com/Microsoft/vscode/blob/alexr00/terminalExitRace/src/vs/workbench/contrib/terminal/common/terminal.ts#L763). and then include the initial cwd in `emitPid` [here](https://github.com/Microsoft/vscode/blob/alexr00/terminalExitRace/src/vs/workbench/contrib/terminal/common/terminalProcessExtHostProxy.ts#L79)?

**Review by Tyriar — APPROVED** [review]
Works great thanks 👌

**Pull request merged**
