### PR TITLE
[folding] Added fold and unfold recursively to foldings

### PR DESCRIPTION
**Pull request by dbillingham**
Added fold and unfold recursively to foldings (cmd K, cmd ]) (cmd K, cmd [). These are two features which I use extensively within the webStorm IDE.

### CODE REVIEW

**Comment by Tyriar** [comment]
@dbillingham can you link the GitHub issue tracking this (if it exists)? Thanks :smiley:

**Comment by dbillingham** [comment]
@Tyriar there is no GitHub issue relating to this change

**Comment by aeschli** [comment]
@dbillingham The pull request removes functionality from the existing code that we want to keep:
- on unfold, if the range at the cursor is not folded, find the first contained folded range and unfold it That came from issue #3814.
- on a regular (not recursive) fold we want to fold the most inner range containing the cursor. If I see this right your change would make the most outer range to fold.

**Comment by dbillingham** [comment]
@aeschli yes I can see the unfold function is more complicated than I released :fearful: I have added a new fold/unfold recursive function so that the regular functionally is not effected.

**Comment by aeschli** [comment]
Thanks @dbillingham !

**Pull request merged**
