### PR TITLE
Add unknown argument checking

### PR DESCRIPTION
**Pull request by ntpttr**
This commit adds a handler for when the command line tool is run with unknown arguments. It will print a message displaying the unknown arg and then exit the process.

### CODE REVIEW

**Comment by ntpttr** [comment]
Tests are passing locally and the failures in the jobs seem unrelated to the change. I'll look into it when I get some time.

**Comment by RMacfarlane** [comment]
@ntpttr Sometimes the tests error out on the build machine - looks like that's what's happening here, so you don't need to spend time investigating it 👍

**Comment by ntpttr** [comment]
@RMacfarlane gotcha, thank you!

**Comment by joaomoreno** [comment]
Not too happy about this since we would need to start adding all Chrome/Node options we support to that list. This will break existing CIs in which people pass wrong options but stuff actually works. What do you think @bpasero?

**Comment by joaomoreno** [comment]
Sorry @ntpttr, even though your intentions are good, this is just not an issue.

**Comment by ntpttr** [comment]
No worries, should the issue be closed then?

**Pull request closed without merging**
