### PR TITLE
Add support for force push and force-with-lease

### LINKED ISSUE #53045: Add support for Git force push within the editor.
Issue Type: <b>Feature Request</b>

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

### PR DESCRIPTION
**Pull request by nesheroj**
This PR introduces support for force pushing with and without lease.

Force pushing is disabled by default, and if enabled, it will use force-with-lease unless set otherwise. This is to deter people that aren't aware of the consequences that the action might have. There is also a confirmation dialog which can be configured to never show if the user wants. Separate command variants with force are added to differentiate them from regular pushing, but those will not show if the option is not set to allow it.

Made this PR before realising the work made in #53170 but I think this provides enough additional value to be considered over that one.

Please be aware that English is not my primary language, so even if I made my best effort to avoid typos, I might have missed some. 

This fixes #53045

### CODE REVIEW

**Comment by nesukun** [comment]
@joaomoreno Please let me know if you need anything from me or I can help in any way to push this forward.

**Comment by joaomoreno** [comment]
@nesukun All good so far

**Comment by nesukun** [comment]
Resolved conflicts :)

**Comment by joaomoreno** [comment]
Great job! Thanks! :beers:

**Comment by qkdreyer** [comment]
Using Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9) I'm unable to see this new pushForce from the "More actions..." context menu.

image

**Comment by nesukun** [comment]
@qkdreyer unfortunately, the command is only available through the command palette as it was considered a 'dangerous' or 'advanced' operation. I'll create an additional PR to get the option added there and let the maintainers decide wether or not it should appear there.

**Comment by styfle** [comment]
@nesukun Nice PR! I just saw this in the release notes.

I wanted to point out that there might be a couple ways to avoid making a mistake for the GUI users.

1. Use `force-with-lease` since it's almost always a better choice then plain `force`. Probably don't even need a GUI option for plain `force`.
2. Avoid showing `force-with-lease` for the default/master branch and only show this GUI option for non-default branches. These branches are less likely to be shared among multiple people when compared to the default branch and thus, will be less dangerous to force push.
3. Avoid `force-with-lease` in the GUI if the branch has not diverged

**Comment by qkdreyer** [comment]
@nesukun Since it's a dangerous/advanced operation, we could let a user decide to display it in the "scm/title" menus with another option disabled by default.

**Comment by joaomoreno** [comment]
Why not use the same option to control whether the actions appear in the menu?

**Pull request merged**
