### PR TITLE
Show current problem in the status bar

### LINKED ISSUE #20183: Show current error in status bar
- VSCode Version: 1.9.0
- OS Version: all

From: https://github.com/Microsoft/vscode-eslint/issues/199

The eslint plugin on vim have a nice feature that if your cursor is on the line of a eslint error it shows the error on status bar, this plugin can do this too?

### PR DESCRIPTION
**Pull request by sandy081**
- Expose visibility change event in status bar
- Listen to the event to show or hide status entry by default
- Register a command to show current problem status entry

This PR fixes #20183

### CODE REVIEW

**Comment by sandy081** [comment]
@bpasero Added an event `onDidChangeEntryVisibility` to `IStatusbarService` to listen to visibility changes. This is needed for my status bar entry to hide it by default.

This event will also be helpful for other status bar entries to release any event listeners

**Review by bpasero — APPROVED** [review]
I typically prefer to not repeat types, e.g. this:

`private readonly _onDidChangeEntryVisibility: Emitter<{ id: string, visible: boolean }> = this._register(new Emitter<{ id: string, visible: boolean }>());`

can be written shorter as:

`private readonly _onDidChangeEntryVisibility = this._register(new Emitter<{ id: string, visible: boolean }>());`

given automatic type inference.

**Comment by sandy081** [comment]
@bpasero I no longer need this event as I decided to use setting to enable or disable the feature - Show current error in the status bar. I still think this event is helpful for others to release the listeners. So, I would push this change, what do you think?

**Comment by bpasero** [comment]
> I still think this event is helpful for others to release the listeners.

Who would use this event can you show an example?

**Comment by sandy081** [comment]
Eg: Editor Status bar contributions. They listen on editor and get updated. When they are hidden these listeners can be disposed and re-registered after getting shown again.

**Comment by bpasero** [comment]
@sandy081 oh yeah makes sense, feel free to add it

**Pull request merged**
