### PR TITLE
Fix Terminals aren't persisting anymore

### LINKED ISSUE #183445: Terminals aren't persisting anymore
1. Create terminals, type in them
2. Reload the window
3. 🐛 they aren't persisted

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #183445

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]
@meganrogge LGTM if it's working for you, I haven't tested

**Comment by meganrogge** [comment]
Thanks @jeanp413 for looking into this! Your fix works 🎉 , but some terminal API tests are failing at the moment. Rerunning to see if it was just a flake

**Comment by meganrogge** [comment]
They're only failing on windows, which is odd

**Comment by jeanp413** [comment]
@meganrogge should work now 🙂

**Review by meganrogge — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by meganrogge** [comment]
I was stumped by this one @jeanp413. thank you again.

**Pull request merged**
