### PR TITLE
Resolved git smart commit not properly work

### PR DESCRIPTION
**Pull request by Gobinath-B**
### Related issue
#190657  #190315
### Changes made
- fix the issue in `smart commit `that ensures stage all the unsaved and changes files to be automatically staged and get committed.
- re-initialized documents object from workspace text documents above the `pick == saveAndCommit` check.
```js
documents = workspace.textDocuments
.filter(d => !d.isUntitled && d.isDirty && isDescendant(repository.root, d.uri.fsPath));

if (pick === saveAndCommit) {
	await Promise.all(documents.map(d => d.save()));
	await repository.add(documents.map(d => d.uri));
        ....
....
```

### CODE REVIEW

**Comment by Gobinath-B** [comment]
@lszomoru can you please review this PR sir

**Comment by Gobinath-B** [comment]
@lszomoru kindly review this code sir.

**Comment by Gobinath-B** [comment]
This issue #190315 made major impact when a user enables `Git smart` feature in vs code.
So kindly review the code and merge it to short out the issue.
@lszomoru @Tyriar

**Comment by Gobinath-B** [comment]
@Tyriar @bpasero

**Comment by Gobinath-B** [comment]
@Tyriar sir please note this issue. @lszomoru is not available  for 1 month. i checked all the issue assigned to him . he didn't even respond to any issues please assign anyone

**Comment by Gobinath-B** [comment]
@lszomoru please review this code and merge it to resolve #190657 #190315 issue.

**Comment by lszomoru** [comment]
@Gobinath-B, thanks again for submitting the issue and for looking into fixing it. I have looked at the code, and I do not believe that the change in this pull request would solve the problem. The issue here is that **after** the dirty files are saved, they are are also staged which results in the files that are not staged to not be committed. The real fix is that we should only stage the dirty files that are already staged. I have created a separate PR with those changes - https://github.com/microsoft/vscode/pull/191300. The fix should be available in the Insiders build that will be release on Monday. Let me know if you have any questions or concerns about the fix.

**Pull request closed without merging**
