### PR TITLE
Add `workbench.quickInput.ignoreBuiltInKeybindings`

### PR DESCRIPTION
**Pull request by leep-frog**
# Summary

This PR adds the `workbench.quickInput.ignoreBuiltInKeybindings` setting to solve the following issues:

- #98479
- #193839

When the setting is set to `true`, all hardcoded quick input keybindings are ignored.

# Manual Testing

> I'm not familiar with the automated tests, but if there is a good way to add tests for these cases, point me to some docs/similar tests and I can give it a try

- Add following to keyboard bindings:
```
{
    "command": "workbench.action.focusPanel",
    "key": "pagedown" // Also try with up, down, left, right, pageup, home, end
},
```
- Open any quick input while in editor focus
- Press `pagedown` key
- Verify panel was opened (prior to this PR, the `pagedown` key would instead just jump to last selection in list)

cc: @TylerLeonhardt

### CODE REVIEW

**Comment by leep-frog** [comment]
@microsoft-github-policy-service agree

**Comment by baibhac** [comment]
hellow

**Review by TylerLeonhardt — CHANGES_REQUESTED** [review]
This is really the change we're looking for... I'd rather turn these `onKeyDown`s into proper `Action's so that they can be configured at will in the Keyboard Shortcuts editor.

**Comment by leep-frog** [comment]
> This is really the change we're looking for... I'd rather turn these `onKeyDown`s into proper `Action's so that they can be configured at will in the Keyboard Shortcuts editor.

Do you have a reference to other actions.  This is the first time I've worked on this repo, so not really sure where to start looking for that

**Comment by TylerLeonhardt** [comment]
So I was talking to @bpasero about this and realized that we already _have_ a bunch of keybindings defined here:
https://github.com/microsoft/vscode/blob/57b1f2ee49e86ecac8707086a398ed2d0559e280/src/vs/workbench/browser/actions/quickAccessActions.ts#L27-L119
but they aren't handling the keybindings because of the hardcoded ones. So here's my suggestion (and how I would do this):

* move these keybindings to `quickInput` layer in the `platform` folder
* Delete hard coded key handlers for those
* Add additional methods to do the remainder of the hardcoded key handlers
* add additional keybindings that call those methods using the pattern above

**Pull request closed without merging**
