### PR TITLE
Add Menu Item to macOS Finder Context Menu

### LINKED ISSUE #1223: Mac OS X :: "Open Folder With" VS Code
Hello,

Since Finder is obviously developed by Apple, I'm not sure if this would be possible or not. Is there any way to right-click a folder in Finder, and "open with VS Code?" You can do this with individual files, but it would be a nice, small workflow enhancement to be able to open a _folder_ with VS Code, directly from Finder, as well. If not, no big deal. This would be a fault with Finder, rather than VS Code.

Here's a screenshot of right-clicking a folder ... there's no "Open With" option. Maybe the **Share** option could work somehow?

screen shot 2015-12-12 at 3 20 03 pm

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Adds commands to install/uninstall a workflow that installs a macOS automation workflow to add an item to the finder context menu.

The only missing piece is I wasn't sure how to get the install location of the vscode app when the command is run.  The workflow action needs this, so that it can specify which app to open.  If somebody can fix this, or tell me how to access this, it is the last piece of functionality.

A few things that probably need to be updated after review.
The text for the commands and notifications
I created a new folder inside of `workbench/contrib`, but I am not sure if this is where it should be.
Storing the content of the workflow as two large strings at the bottom of the file, can this be done differently?

This PR fixes #1223

### CODE REVIEW

**Comment by bpasero** [comment]
I am personally not a big fan of doing this via code inside VSCode as opposed to some `Info.plist` modification during build time or ideally some installation routine. I think I would expect a VSCode installer that:
* moves VSCode to the `Applications` folder
* does post-installation duty such as adding context menu actions to folders and/or installing `code` as command globally.

**Comment by nrayburn-tech** [comment]
Maybe an issue should be created to get feedback on using an installer instead of just having the application file/folder.

I am not aware of all the complications of this. Here are just a few considerations that came to mind.
I think VSCode has an option to install on a usb, so the installer should probably allow this. Macs also have the global install in applications, or a user level install in the users applications.

What do existing users do? Run the installer to get the new functionality?
Currently, adding code to path and adding the context menu are the only additions, but it could expand more.

Is it more difficult to manage mass deployment installations when using an installer, instead of just an application that can be copied.
Is this our concern, or is that for the end users to resolve?

**Comment by bpasero** [comment]
I just find an installer more naturally to drive this, e.g. given the user a choice to do this or not via checkbox. Now the user has to start VSCode and do this via commands for each integration. That does not sound ideal to me imho.

**Comment by nrayburn-tech** [comment]
How does the windows installer approach this?

For example, does it have an option to add code to path? How is this process automated, in the sense that an admin can pre-configure the options for the install? Maybe we can replicate that for a macOS installer.

**Comment by bpasero** [comment]
We are leveraging Inno Setup for our Windows installer.

**Comment by nrayburn-tech** [comment]
It looks like the installer can have some customized options. There is also the ability to generate an xml file that can then be used as part of a silent install with pre-determined defaults.

I think this will do everything we need, but if not let me know any other items I need to figure out.  I can create a new PR once I have some work done on it.

Example

**Pull request closed without merging**
