### PR TITLE
Resolve env vars in settings.json

### LINKED ISSUE #1425: Use of environment variables in options values
We have an ESLint setup which uses a *custom ESLint plugin* that we would like to share across multiple projects.

Having the plugin already pre-installed as a dependency of a `GLOBAL_PACKAGE` which all users have by default, we can configure `.vscode/settings.json` to use a shareable config file (that `extends` and loads the plugin from that location): 
```json
"eslint.options": {
    "overrideConfigFile": "${PATH_TO_GLOBAL_PACKAGE}/shareableConfigFile"
}
```

Now, if the users also want to *check in* these user settings for a given project, `PATH_TO_GLOBAL_PACKAGE` may differ across their environments and I'm wondering whether it would be possible to get this from a variable?

I understand that we have the following constraints:

- VSCode only allows the use of environment variables in `launch.json` and `task.json`
- ESLint's option `overrideConfigFile` must be of type `string | null`, so `${PATH_TO_GLOBAL_PACKAGE}` would have to be interpreted *before* it gets passed on the ESLint library.

Do you think this would be possible or could you maybe recommend a workaround? Otherwise, I would also be willing to do a feature contribution (with your guidance) if such cases could be supported.

### LINKED ISSUE #2809: settings.json paths don't resolve environment variables
Hi,

I was just reading the [latest updates](https://code.visualstudio.com/updates) and it says one can install `typescript@next` globally and then set `typescript.tsdk` so VS Code can use the appropriate version/installation. In a team environment, I'd like to put that setting in our project, something like:

`.vscode/settings.json`:
```json
{
    "typescript.tsdk": "%APPDATA%/npm/node_modules/typescript/lib"
}
```

The problem is restarting VS Code results in an error:

```
The path c:\Projects\Derp\%APPDATA%\npm\node_modules\typescript\lib doesn't point to a valid tsserver install. TypeScript language features will be disabled.
```

Now the setting needs to be per-person because I highly doubt my teammates have `tsc` installed in `C:\Users\Olson\AppData\Roaming\npm\node_modules\typescript\lib` :wink:

Could we get environment variables evaluated on that and all other settings that involve paths?

I haven't tested other paths, but I see these in the Default Settings:
- `git.path`
- `markdown.styles`
- `json.schemas`
- `typescript.tsdk`
- `php.validate.executablePath`

### PR DESCRIPTION
**Pull request by mnkiefer**
### Feature contribution
- Resolves environment variables in `.vscode/settings.json` of the form `${env:...}`

### Use cases
- To be able to enter path for shared config file in `vscode-eslint`
   Fixes https://github.com/microsoft/vscode-eslint/issues/1425
- Many others requested since 2016
   Fixes https://github.com/microsoft/vscode/issues/2809#issuecomment-1031011012 

### Implementation
  - In `src/vs/platform/configuration/common/configuration.ts` [addToValueTree()](https://github.com/microsoft/vscode/blob/main/src/vs/platform/configuration/common/configuration.ts#L188), added 
  - Borrowed logic from `src/vs/workbench/services/configurationResolver/common/variableResolver.ts` for [`resolveWithEnvironment()`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L71) since importing it results in violated imports warning:
     `Imports violates 'vs/base/common/** or vs/base/parts/*/common/** or vs/platform/*/common/** ...`
-  Logic kept identical except for small alterations:
  - `replaceAsync()` replaced by `replaceSync()` to keep `addToValueTree()`/ `toValueTree()` synchronous
  - `evaluateSingleVariable()` simplified to only cover for 'env' case but could be extended
### Tests
- [addToValueTree: add key with value ${env:...}](https://github.com/mjochum/vscode/blob/settingsVars/src/vs/platform/configuration/test/common/configuration.test.ts#L123)
 `{ 'a': 1, 'b': '${env:VALUE_FOR_B} }' => { 'a': 1, 'b': '2' }`
- [addToValueTree: add key with value string containing ${env:...}](https://github.com/mjochum/vscode/blob/settingsVars/src/vs/platform/configuration/test/common/configuration.test.ts#L133)
  `{'a': 'string1', 'b': 'string${env:VALUE_FOR_B}'} => {'a': 'string1', 'b': 'string2}`

### CODE REVIEW

**Comment by sandy081** [comment]
Thanks for your effort on this contribution. I am sorry that this solution is not an ideal/best because because of following reasons

- This will impact our start up performance
- Env variables are open ended, some times it needs user input 
- This breaks existing behaviour
- It is not required in platform

**Comment by mjochum** [comment]
> Thanks for your effort on this contribution. I am sorry that this solution is not an ideal/best because because of following reasons
> 
> * This will impact our start up performance
> * Env variables are open ended, some times it needs user input
> * This breaks existing behaviour
> * It is not required in platform

@sandy081: Thank you for your reply - could you please elaborate on some of the points you mentioned?

1. Regarding the performance, I'm sure the code could be rewritten in such a way that the effect is minimal, this was only a first draft/suggestion, for example the resolving process could be made async.
2. If type `env` variables are an issue, maybe supporting [`command` variables](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables) (or others) could be an option?
3. Please elucidate on the breaking behaviour your foresee.
4. I'm not sure what the requirements in *platform* are, but for many extensions, being able to resolve variables in the project settings would be of great help.

In all of the points I'm willing to contribute given the right direction/pointers/test scenarios from your side.
Please advise.

**Comment by alexr00** [comment]
Feature request for having this as API: https://github.com/microsoft/vscode/issues/140056

**Comment by mjochum** [comment]
@sandy081: Thank you for your explanation. I understand now that this should be implemented *not* as part of the configuration service in the `platform` layer, but as a separate service in the VS Code workbench?
  
@alexr00:  Would it suffice if I added the kind of *resolve* functionality described to [`ExtHostConfigProvider.getConfiguration()`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostConfiguration.ts#L157)?

**Comment by alexr00** [comment]
@mjochum thank you for your interest in working on this issue, but we will not accept a PR for https://github.com/microsoft/vscode/issues/140056 at this time, as I'm not sure that it's the best approach for resolving variables.

**Comment by mjochum** [comment]
@alexr00: No problem, thanks for getting back to me!

Please let me know whenever a feasible solution/approach for this has been decided on in the future (and if help is wanted). 👍

**Pull request closed without merging**
