### PR TITLE
Reduce language pack checks

### LINKED ISSUE #58074: Excessive calls to the marketplace when rendering extensions viewlet
For every row render of the extensions viewlet, there's a marketplace request:

bug

This was introduced by: https://github.com/Microsoft/vscode/commit/109f6b514ff15244c043bdbd61b4ca9f803ff627

@ramya-rao-a What is the goal here? Localizable descriptions?

cc @sandy081

### PR DESCRIPTION
**Pull request by ramya-rao-a**
This PR is to reduce the number of marketplace calls being made to check if given extension is a language pack so that the extension description can be updated to be the localized language

Fixes #58074

@sandy081 

The current solution will still make a call for each ExtensionListView being created. 
A better solution would be to fetch the language pack just once per VS Code window/session in which case the `ExtensionWorkbenchService` would be the most appropriate home.

Thoughts?

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@sandy081 That would requires us to update the vsce package correct?

**Comment by sandy081** [comment]
Yes

**Comment by ramya-rao-a** [comment]
@sandy081 Please see https://github.com/Microsoft/vscode-vsce/pull/286

**Comment by ramya-rao-a** [comment]
@sandy081 I've updated the PR to use the property from the manifest.

I am keeping the previous code as it will take a while until the language packs get published with the latest vsce tool.

**Comment by sandy081** [comment]
@ramya-rao-a I think all lang packs will be published with a new version along with the next stable release. So I do not think we need to wait until next milestone to remove the old code. Only insiders will not show the localised names until stable is released which I think is fine.

@danyeh FYI

**Comment by sandy081** [comment]
Thanks @ramya-rao-a LGTM

**Pull request merged**
