### PR TITLE
Added gitter chat badge to readme

### PR DESCRIPTION
**Pull request by AkashGutha**
This would be easy access for people who are interested in VSCode development.

### CODE REVIEW

**Comment by AkashGutha** [comment]
is there need for any other badges?

**Comment by bpasero** [comment]
@AkashGutha not sure, do you have anything else in mind?

**Comment by AkashGutha** [comment]
how about node and npm versions?

**Comment by AkashGutha** [comment]
there are badges for dependecy tracking.
does vscode use any dependency tracking system?

**Comment by bpasero** [comment]
No, I think they are not needed right now. Thanks for reminding though.

**Pull request merged**
