### PR TITLE
Implement custom sorting based on rules.

### PR DESCRIPTION
**Pull request by charJKL**
SortRules allows us position file whatever we like, based on Regexp match.

It's very useful in finding files when you know exactly where they will occur in hierarchy in explorer. E.g.: Interfaces will always placed at the top.

diff

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for your PR. However before providing PR it is usually best to first start a discussion.
Regarding this the issue is that we already have a sort option, and adding another one does not really make sense. https://github.com/Microsoft/vscode/wiki/How-to-Contribute
Also I am not sure what issue would this feature solve. We do not just merge everythign into vscode otherwise there would be too much bloat.

Due to the above will not merge in this PR

**Comment by charJKL** [comment]
I am totally fine with your decision :D

On day-to-day basis I works with my custom build, this feature comes from there. I decided it is better to show implementaion right away, becouse I already had it, that's why I didn't create disscussion. Sharing it cost me nothing.

What issue it solves? Probably none :) In last update (version 1.31) I notice that it include Tree UI improvements, which refers to problem with navigation in files explorer. I finds helpful knowledge that all interfaces I have are listed at the top, or more generally that my explorer is sorted some logically / functional way. Then quick glance at explorer and I know what abstractions files I have to deal with. I don't have to typing to filter files.

**Comment by isidorn** [comment]
Ok, thanks for explanation. Still not merging it in though :)

**Comment by isidorn** [comment]
Clossing as out of scope.
Thank you again for your PR.

**Pull request closed without merging**
