### PR TITLE
use title for terminal selection

### LINKED ISSUE #123189: Rename debug terminals if a second `runInTerminal` request comes in with a different name
See https://github.com/microsoft/vscode-js-debug/issues/990#issuecomment-833809419

I think the best way for this would be for VS Code core to rename the terminal if gets a new `runInTerminal` request with a different name -- opened an issue for that https://github.com/microsoft/vscode/issues/123189. Or, at least, try to use a terminal of the same name if one exists (which would be easier and probably more feasible since the `name` is not writable.) 

Code pointer: https://github.com/microsoft/vscode/blob/de4e9067e80f079f092006929dab05516e27c70e/src/vs/workbench/api/node/extHostDebugService.ts#L74

### PR DESCRIPTION
**Pull request by danielgary**
This PR fixes #123189

This should guarantee that all launch configurations that use integrated terminal should always receive a terminal with their name.  It should also help fix issues related to vscode opening multiple terminals for the same launch process.

### CODE REVIEW

**Review by connor4312 — APPROVED** [review]

**Comment by danielgary** [comment]
I just tested with the nightly build of the vscode-js-debug extension.  This works and does prevent creating additional terminals.

**Comment by isidorn** [comment]
This looks good to me. However I know @weinand is back next week so I suggest we wait for him before we merge this in.

**Comment by danielgary** [comment]
Any update on this?  I'm happy to make changes if needed.

**Review by weinand — APPROVED** [review]

**Comment by weinand** [comment]
@danielgary thanks for the PR

**Pull request merged**
