### PR TITLE
Allow buttons to show outline on keyboard focus

### LINKED ISSUE #52676: Button focus is not clearly visible (blue on blue)
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
MAS Violated : MAS 2.4.7

**Repro Steps:**
1. Navigate to Status Bar at the bottom and move to notifications.
2. Move to any notification that appears at the screen.
3. Navigate to any button inside the notification.

**Actual:**
The focus is not marked using dotted-lines/rectangle to indicate the focus on the buttons. Only color changes to mark the focus on the buttons.

**Expected:**
The focus should be visible using dotted-lines/rectangle to indicate the focus on the buttons. 

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
Low vision/visually impaired users should be able to distinguish the focused element.

**MAS Reference:**
MAS2.4.7 - https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={3b98b04f-4fab-4d3e-81af-a0906a34849c}

**Attachment For Reference:**
[A11y_VSCode_StatusBar_Keyboard_NotificationButtonsFocusVisibility.pptx](https://github.com/Microsoft/vscode/files/2127505/A11y_VSCode_StatusBar_Keyboard_NotificationButtonsFocusVisibility.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by miguelsolorio**
Fixes #52676

This only appears on keyboard focus and doesn't show for active clicks. I also tweaked the overflow properties for the outside containers in order to get the outline focus to be shown, tested this on all platforms (macOS/Win/Linux) and didn't see this break anything.

gif

image

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Making something `overflow:visible` that was `overflow:hidden` sounds like it needs a lot of testing. Make sure to trigger notifications with many buttons, long labels, etc. to see the change in action this will have.

**Comment by bpasero** [comment]
Before:
image

After:
image

I prefer "before". Notice how in "after" the button seems unbalanced compared to the close button.

**Comment by misolori** [comment]
You beat me before I was able to comment 😄

So it looks like the only way to show the focus outline without tweaking the overflow property (which breaks the stress case of multiple buttons) is to increase the margins by 4px. This gives the buttons plenty of space to show the outline focus, though it does break the right alignment. Here's the stress test I did:

gif

**Comment by bpasero** [comment]
@misolori can the overflow change be scoped to the buttons maybe to not break?

**Comment by misolori** [comment]
@bpasero the `overflow: hidden` property is what allows multiple buttons to fit on a single line. I'll play around with the grid layout to see if I can achieve a similar style.

**Comment by misolori** [comment]
So after tweaking with the current flexbox properties and trying out a few different grid layouts, I wasn't able to get to a close solution. 

I think the next best thing is to adjust the padding/margin so that the buttons line up with the close buttons. Below is the comparison, let me know what you think.

image
image

**Review by bpasero — APPROVED** [review]
Seems to work OK. Any reason the buttons have a different left vs right padding? Why not the same?

**Comment by misolori** [comment]
@bpasero I was originally trying to make up for the previous `margin-left: 10px` but the numbers do look off. The buttons need a minimum margin of 4px in order to show the focus outline, so what I can do is make it a uniform `margin: 4px 5px`.

**Pull request merged**
