### PR TITLE
#10027 confirmSave should check the goal of running an extension is actually…

### PR DESCRIPTION
**Pull request by qadram**
… to run tests.

### CODE REVIEW

**Comment by roblourens** [comment]
Is that the right issue? It was closed a long time ago

**Comment by qadram** [comment]
I think it was not correctly closed, as it doesn't solve the problem it was being presented.

Problem: When developing an extension and running such extension using the Extension Development Host, dirty files doesn't prompt to save them. If you are developing an extension that needs such prompt, it's not possible because it was disabled on purpose.

The logic behind my pull request is:
* If the goal was to prevent VS Code to prompt saving dirty files when running tests
* Then, skipping such prompt should be done when there are **actual tests running**
* And not simply because the Extension Development Host is running, that assumption is simply false

It's subtle, but it's preventing me from using VS Code to run and debug an extension I'm working on because I cannot test all the scenarios as the prompt is not shown, and I'm not running tests, I'm just developing an extension.

Regards

**Comment by bpasero** [comment]
I find the current behaviour work better for this particular use case:
* I debug an extension and it opens in a window
* I do a lot of stuff, e.g. open editors, make them dirty
* when I am done I hit `Cmd+Q` to close the window

If we would start to prompt for saving changes, we would break this flow. This was one of the main motivations to not ask for saving dirty files initially.

**Comment by qadram** [comment]
I find that behavior very useful when running tests, like it's noted on the comment, but I find weird that the behavior of the product is modified in such an important way for a code editor. 

When I noticed my first impression is that such behavior it was a bug, that's why I investigated more and I found, while debugging the code, that it was as designed.

In any case, would be great to add a new switch to the command line (or through another mechanism) to allow users to choose the behavior. That is, the existing behavior won't be modified, but if someone wants the Extension Development Host to ask to save dirty files, there should be a mechanism for that. At this moment, there is no alternative.

In my case, I'm working on an extension that needs to make dirty several files that are related between them, and when closing one of them, different things should happen. If I don't get the prompt, I cannot verify I'm doing things properly.

**Comment by qadram** [comment]
By the way, if the suggestion of adding an extra parameter (or any other way) you think it will be OK, I can work on that direction and send another pull request.

**Comment by bpasero** [comment]
Yes, having an extra parameter works for me .

**Comment by qadram** [comment]
Sure. Will implement --confirm-save, if present, it will override the existing behavior.

**Comment by bpasero** [comment]
@qadram it needs to have some kind of prefix to make clear it is about extension development right? E.g. `--extension-development-confirm-save`?

**Comment by qadram** [comment]
Perfect, thanks!

**Comment by bpasero** [comment]
Continues in https://github.com/microsoft/vscode/pull/78033

**Comment by bpasero** [comment]
Merged. Please help by verifying this change in our insider releases after we released stable end of week.

**Pull request closed without merging**
