### PR TITLE
remove workbench/contrib/experiments

### PR DESCRIPTION
**Pull request by isidorn**
Ref https://github.com/microsoft/vscode-internalbacklog/issues/2855

Removes unused `workbench/contrib/experiments`
All tests are green and I ran VS Code out of Source and it looks OK.

fyi @bpasero

### CODE REVIEW

**Review by sandy081 — DISMISSED** [review]

**Comment by isidorn** [comment]
Code OSS check failed due to flaky smoke test.
@bpasero @sandy081 I just updated with latest from main to re-trigger the flaky smoke test.

**Comment by bpasero** [comment]
@isidorn you need to drill into the attachments of the build to find all the logs and crash dumps.

The arrow brings you back:
image

Then see "Related" artefacts:
image

This shows logs for all tests:
image

If crash dumps have any size > 100kb, thats a good hint that there are native crash dumps:
image

You can then file an issue with the crash dump attached. There are many here so maybe picking one is sufficient.

Btw this does not mean these crashes are related to your change.

**Comment by isidorn** [comment]
@bpasero sorry I got stuck. I ran the remote smoke tests locally and I can indeed reproduce the problem. I ran them via
`yarn smoketest-no-compile --remote --tracing`
Same what our build machine does. The build machine shows the following error:
`Error: Timeout: get text content '.monaco-workbench .statusbar-item[id="status.host"]' after 30 seconds`

When I run it locally I see that element exists. Do you have any hints what might be going on?

Screenshot 2023-06-27 at 11 02 40

**Comment by bpasero** [comment]
@isidorn please check for each file you delete if any code still depends on any of it. For example if you search for `enableExperiments`, all of that I think needs to go away. Maybe there is more.

**Comment by bpasero** [comment]
i brought it up because I think the smoke tests then ran for me when removing that. I have a feeling that the remote server fails to start in the smoke tests, you can see how the window quickly closes while the remote is setting up. I was not able to find the underlying reason though, but maybe its related to that setting.

**Comment by isidorn** [comment]
I think I found the issue. I removed the registration of `workbench.enableExperiments` setting. We still need that for our assignment service. I will bring it back and re-trigger tests.

So thanks Ben and the smoke tests 👏

**Comment by isidorn** [comment]
Ok. Tests passed. @bpasero can you just approve via review. Thank you!

I am having follow up discussions with Logan to see if we really need the `AssignmentService`

**Comment by isidorn** [comment]
Ok. Tests passed. @bpasero can you just approve via review. Thank you!

I am having follow up discussions with Logan to see if we really need the `AssignmentService`

**Review by bpasero — APPROVED** [review]

**Comment by isidorn** [comment]
@lramos15 confirmed that we indeed need the AssignmentService for our new experimentation framework.
So we are good here 👏

**Pull request merged**
