### PR TITLE
Fix C# in markdown header

### PR DESCRIPTION
**Pull request by golf1052**
Example

``` markdown
### C#
```
### C

Proposed fix

``` markdown
<h3>C#</h3>
```

<h3>C#</h3>

### CODE REVIEW

**Comment by Tyriar** [comment]
Nice find, I think using the HTML entity `&#35;` might be better than introducing the tag.

```markdown
### C&#35;
```

### C&#35;

**Comment by golf1052** [comment]
I like that much better. Should I just make another commit or can I amend this commit?

**Comment by Tyriar** [comment]
Whichever way is easier

**Comment by Tyriar** [comment]
Thanks for the contribution! :smiley:

**Pull request merged**
