### PR TITLE
click on disabled breakpoint enable instead of removing #125904

### LINKED ISSUE #125904: click on disabled breakpoint , option to enable instead of removing
Issue Type: <b>Feature Request</b>

Now clicking on a disabled breakpoint would remove it. I need an option to enable it first instead of removing.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic

### PR DESCRIPTION
**Pull request by xgdgsc**
This PR fixes #125904. This is only a trial edit in browser from a shallow understanding of the code section. Please correct me if I'm wrong.

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for the PR. However please setup VS Code so you can build it and try this out. Check this document out https://github.com/microsoft/vscode/wiki/How-to-Contribute

1. You have a whitespace missing
2. Your proposed solution is very complex imho, if some of the breakpoints are enabled and some disabled flip each?! This will be very hard to understand

What I propose is the following:

1. If all breakpoints on the line are disabled -> enable them all
2. Otherwise remove them all

**Comment by xgdgsc** [comment]
I' m trying to setup build env on Windows. But it fails at
```
gyp http GET https://electronjs.org/headers/v12.0.11/node-v12.0.11-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: Client network socket disconnected before secure TLS connection was established
gyp ERR! stack     at connResetException (internal/errors.js:628:14)
gyp ERR! stack     at TLSSocket.onConnectEnd (_tls_wrap.js:1561:19)
gyp ERR! stack     at TLSSocket.emit (events.js:387:35)
gyp ERR! stack     at endReadableNT (internal/streams/readable.js:1317:12)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\GitHub\vscode\node_modules\node-pty
```
 which tries to download `https://electronjs.org/headers/v12.0.11/node-v12.0.11-headers.tar.gz` , one file I couldn' t download even with VPN. Any workarounds?

**Comment by isidorn** [comment]
Sorry I never saw that error. I do not know.

**Comment by xgdgsc** [comment]
Thanks to https://github.com/microsoft/vscode/issues/124467(which could be closed) I managed to install the dependencies to run vscode. From what I tested it seems to do what I expected. I don' t get  why you say "flip each".

**Comment by isidorn** [comment]
@xgdgsc  Works like magic. Thanks a lot for your contribution :clap:

**Pull request merged**
