### PR TITLE
add more settings to gear menu

### LINKED ISSUE #28248: Add other settings to the gear menu
Suggest to add the `File Icon Theme` and `Color Theme` to the gear menu.

image

### PR DESCRIPTION
**Pull request by jens1o**
resolves #28248

### CODE REVIEW

**Comment by isidorn** [comment]
@jens1o thanks for your PR. Always make sure to first try out the PR before submiting it. Here are things which should be fixed before we can merge it in:

* The title of "Select File Icon Theme" should be just "File Icon Theme" like in the preferences menu. For consistency and conciseness
* You got the order wrong, first should be the color theme, and only then file icon theme. Since the first is more important and that is how it is currently in preferences

screen shot 2017-06-09 at 12 45 06

**Comment by jens1o** [comment]
Actually, I wanted to set "Select Color Theme", but I found no message for that, and I was unsure whether I can introduce new messages, and I was waiting for this feedback. Sorry for the inconvenience.

**Comment by jens1o** [comment]
nevermind, I fixed it.

**Comment by isidorn** [comment]
Looks good, great work!

**Pull request merged**
