### PR TITLE
Update statusBarItem.prominentBackground

### PR DESCRIPTION
**Pull request by miguelsolorio**
This updates `statusBarItem.prominentBackground` to better blend with various backgrounds:

image

### CODE REVIEW

**Comment by aeschli** [comment]
Looks good, merged.

**Comment by bpasero** [comment]
@aeschli did you?

image

**Comment by aeschli** [comment]
Hm, strange, did I really click on the `close`? Reopened, merged, also adapted the prominent hover color.

Please review:

Above new, below old: Regular toolbar in dark+
prominent-toolbar-reg-dark
Above new, below old: Debug toolbar in dark+
prominent-toolbar-debug

Above new, below old: Regular toolbar in light+
prominent-toolbar-reg

**Comment by bpasero** [comment]
I like it 👍

**Comment by misolori** [comment]
@aeschli thanks for updating the hover color!

**Comment by rediffusion** [comment]
@aeschli 

 I don't understand how it works? Maybe it works with some kind of expansion?

> "statusBarItem.prominentBackground": "#5632b9"

...also maybe you know how works this to:

> "statusBarItem.prominentForeground": "#5632b9"

 Best regards❗ ✌️

**Comment by aeschli** [comment]
The hover/description says:

`Status bar prominent items background color. Prominent items stand out from other status bar entries to indicate importance. Change mode `Toggle Tab Key Moves Focus` from command palette to see an example. The status bar is shown in the bottom of the window.`

image

**Comment by rediffusion** [comment]
@aeschli

 Yay, it works! But what is it for? I got only one when I suffering between tabs something happens...
[Check that](https://www.screencast.com/t/eHUL2zkY).

Best regards❗ ✌️

**Comment by rediffusion** [comment]
FYI, 🎬 screencast tutorial of these features, [check that](https://gitduck.com/watch/5e3ca8247ff1dfd6d0f2ae06).

**Pull request closed without merging**
