### PR TITLE
fix: color hints may display twice(#175476)

### LINKED ISSUE #175476: [Bug] Color hints may display twice at view edges with line wrap
With &#x60;"editor.wordWrap": "on"&#x60;, the color hints (inline color decorators) may be double-displayed near the wrapped view edges.

&#x2D;---

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
Embedder: github.dev

### PR DESCRIPTION
**Pull request by yshaojun**
fix #175476

### CODE REVIEW

**Review by aiday-mar — APPROVED** [review]

**Review by aiday-mar — DISMISSED** [review]
Hi thanks for the work, after a second look I notice that the unit tests are failing. The end offset is not calculated correctly according to these tests. Some more work will need to be done to find a fix. Unfortunately we can not merge it with the unit tests failing.

**Comment by yshaojun** [comment]
> Hi thanks for the work, after a second look I notice that the unit tests are failing. The end offset is not calculated correctly according to these tests. Some more work will need to be done to find a fix. Unfortunately we can not merge it with the unit tests failing.

Hi Aiday, I checked the failing test case, found the token endIndex is 30, it's also the last column of a line. I think inline decoration's endOffset shouldn't be greater than line's last column, should we update the failing test case? Please check.

WX20230715-110245@2x

**Comment by aiday-mar** [comment]
Hi thanks for the reply. @hediet I noticed you made some changes previously on the test code that this PR aims to change. If it wasn't you who wrote that specific test let me know. Do you think it would be okay to make the change proposed by @yshaojun?

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
@yshaojun thanks for fixing this!?

**Pull request merged**
