### PR TITLE
Layout: bring back previous async nature of restore

### PR DESCRIPTION
**Pull request by bpasero**
Refs: https://github.com/microsoft/vscode/issues/100059

@eamodio a follow up change from the default views: it seems to me with your change you alter the way how we specifically did not want to block startup. As you can see from the code, all the restore logic is `async` between editors, views and panels so that they can all restore in parallel and we have no waterfall.

This change tries to minimize the impact of waterfall, but could probably still be improved. For example, why does the panel have to wait to restore for the default views if no default view exists that lives in a panel?

This PR is trying to be a start but I think you should take this over and revisit the waterfall we now have. Ideally:
* if a default view is only sidebar or only panel, it does not block the restoring of the panel or sidebar
* if we have 2 default views for sidebar and panel, things can be as today

//cc @sbatten for fyi

### CODE REVIEW

**Comment by eamodio** [comment]
@bpasero Thanks for catching this. These changes look good to me. 

> For example, why does the panel have to wait to restore for the default views if no default view exists that lives in a panel?

The issue is that we don't know if the view is in the sidebar or the panel yet or not, so we have to wait until we figure out where the views are positioned.

**Comment by bpasero** [comment]
> The issue is that we don't know if the view is in the sidebar or the panel yet or not, so we have to wait until we figure out where the views are positioned.

But that is surely something that can be asked without long running operation no?

**Comment by eamodio** [comment]
Unfortunately not, unless the view is already registered we don't know where it will be, and if it isn't registered yet we have to wait until it becomes registered (by waiting until extensions are loaded)

**Comment by bpasero** [comment]
Ah ok. Feel free to merge this or consult with Steven and then merge or add changes on top.

**Pull request merged**
