### PR TITLE
Add `--prof-v8-extensions` flag

### PR DESCRIPTION
**Pull request by alexdima**
See https://github.com/microsoft/vscode/issues/112393#issuecomment-747735314

### CODE REVIEW

**Comment by deepak1556** [comment]
I can verify the flag works, it creates isolate-xxx-v8.log in the current directory once the process quits. Thanks!

**Review by deepak1556 — APPROVED** [review]

**Comment by alexdima** [comment]
@deepak1556 I have tried on Windows, and I don't see any new files when running `scripts\code-cli.bat --prof-v8-extensions`. Is there something more needed to get Windows to work as well or did you also try on Windows ?

**Comment by deepak1556** [comment]
I only tried on mac and linux, there shouldn't be anything additional required. Will look into it tomorrow.

**Comment by alexdima** [comment]
I can confirm, this works on macOS, but just FYI doesn't do anything noticeable on Windows.

**Pull request merged**
