### PR TITLE
Introduce SQLite (in-memory) for localStorage

### PR DESCRIPTION
**Pull request by bpasero**
part of https://github.com/Microsoft/vscode/issues/58957

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
@bpasero Just wondering, does this enable the scenario of switching between folders without window reloads?

**Comment by bpasero** [comment]
@NavyAdmiral 

> Just wondering, does this enable the scenario of switching between folders without window reloads
It will not enable this, but it adds a little bit of eventing that is needed for that to work, so we are getting a bit closer to eventually having it. There is more work to do the switch without reload:
* update UI state dynamically based on events (e.g. the list of opened files should update when folders change to mimic todays behaviour)
* allow to enable/disable extensions without window reload (@sandy081 's area)

> will this get merged before migrating to electron 3
Yes, this will enable the update to Electron 3 once we migrated `localStorage` into our own SQLite DB

**Comment by NavyAdmiral** [comment]
@bpasero Thanks for answering. One more question, does this have any perf implications?

**Comment by bpasero** [comment]
@NavyAdmiral yes very likely. Compared to the old solution:
* we no longer load all storage of all workspaces into memory on startup in each window. we will load only the storage that is associated with the windows workspace
* every call that alters storage will no longer result in a sync IPC message to the main process that will block the renderer while calling
* on startup we pay the price of connecting to the DB and getting the data. I will add telemetry to measure the time this takes. I already have the data from how long it takes to access `window.localStorage` for many users and times vary from 100ms to 20s (!). If disk IO is the bottleneck, we will not gain much even with the new solution

I am happy for feedback about the implementation: https://github.com/Microsoft/vscode/issues/58957#issuecomment-427368774

**Pull request merged**
