### PR TITLE
Show filtered stats

### LINKED ISSUE #105866: Show number of filtered debug console items
Testing https://github.com/microsoft/vscode/issues/105185

Just another feature request. It would be useful to see how many debug console items are filtered out. Especially if I see this number going up, then I know I am missing new messages.

### PR DESCRIPTION
**Pull request by pfongkye**
This PR fixes #105866

### CODE REVIEW

**Comment by pfongkye** [comment]
Hi @isidorn 
I've created a PR. Let me know if there's anything missing or any changes to do.
Thanks.

**Comment by isidorn** [comment]
@pfongkye thanks a lot for this PR. I will review it in detail and test it out tomorrow

**Comment by isidorn** [comment]
@pfongkye thanks for your PR, I tried it out and seems to work good. Here's my feedback:
* You are bringing back layout code for the shrink and grow of the Repl Filter, however the repl filter does not properly shrink and grow - it does not work with your changes. What I suggest is to remove this code completly from this PR and if you would like to tackle the shrink / grow issue please create an additional PR and test it out. 
* So from the above this PR should only contain the Badge which shows the number of filtered items work
* Once you filter for some term that is nonexistent the debug console will be empty but the badge will not show anything. I suggest to show "showing 0 of N". That will make it more clear. And I suggest to also change that in problems view to be consistent

Thanks!

**Comment by pfongkye** [comment]
@isidorn
Thanks for the feedback. 
I'll make the necessary changes and create another issue for the shrink/grow problem. I'll keep you updated.

**Comment by isidorn** [comment]
Great thanks. Just ping me once it is ready for review again.

**Comment by pfongkye** [comment]
@isidorn  friendly ping to let you know the PR is ready for review.
I created an issue for the layout: #107230

**Comment by isidorn** [comment]
Looks great! Merging in and I will push some polish commits on top of this work.
Thanks a lot for your work!

**Comment by isidorn** [comment]
Pushed some minor improvements via https://github.com/microsoft/vscode/commit/a47bf985eff0f2c0ae190d606ecc1a79054a02de

**Comment by pfongkye** [comment]
> Pushed some minor improvements via [a47bf98](https://github.com/microsoft/vscode/commit/a47bf985eff0f2c0ae190d606ecc1a79054a02de)

@isidorn  I like the refactoring since it's cleaner now. However, I noticed that a scenario has been left out.

When you pause the debugger and begin to type in the filter, the badge will be updated.  However, if you hit continue on the debugger, the badge will not be updated, `showing x of n` will remain the same even though there are more lines appearing.
I used the following listener for this scenario: `this._register(this.tree.onDidChangeContentHeight(() => this.refreshReplElements(false)));` but maybe there is a better solution.

**Comment by isidorn** [comment]
@pfongkye great catch. I have tackled this via 8e8267805f

**Pull request merged**
