### PR TITLE
#18696 Support line number fragments in vscode.open

### PR DESCRIPTION
**Pull request by charlespierce**
Implements #18696

Added support for line / column number fragments to `vscode.open` command. The parsing logic was taken from the link opening service at `vs/platform/opener/browser/openerService.ts`.

It seems like this logic should be consolidated somewhere, but I'm still new to the project and I'm not sure where the best place to add this kind of shared logic would be, and how to access it from both places that need it.

### CODE REVIEW

**Comment by bpasero** [comment]
@jrieken would it not make sense to allow to pass in line/col information from the `showTextDocument` method? I think this `vscode.open` command is turning into a confusing parallel way for extensions to open documents, I think we should rather stick to one.

**Comment by jrieken** [comment]
Yes, people should use `showTextDocument` and not the open command

**Comment by bpasero** [comment]
@jrieken since there is no way of specifying the line/column information in the `showTextDocument` is the idea to just apply it from the callback in the editor?

**Comment by jrieken** [comment]
that or a new PR that adds an options parameter with that information, like `showTextDocument(doc: TextDocument`, options: {revealPosition: Position})`. However, with the editor in hand the are much richer reveal [options](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L641)

**Comment by joaomoreno** [comment]
@bpasero @jrieken How about if you want to show a Diff editor?

**Comment by bpasero** [comment]
@joaomoreno we need support to showTextDocument(diffResource), I never liked the command for opening. it was initially added to allow to open an editor in a new window I think and should not be used as general way of opening editors imho.

**Comment by jrieken** [comment]
Not sure about `diffResource` but "yes" there are requests for exposing the diff editor in the API and some way to show a diff editor two resources is something we need

**Pull request closed without merging**
