### PR TITLE
adapter css variable for viewFilter #165169

### PR DESCRIPTION
**Pull request by Kalmaegi**
for #165169

- [x]  src/vs/workbench/browser/parts/views/viewFilter.ts
- [x]  src/vs/workbench/browser/style.ts
- [x]  src/vs/workbench/contrib/customEditor/browser/customEditors.ts

### CODE REVIEW

**Comment by weartist** [comment]
@roblourens If it is convenient, please also help apply for this PR review, thank you very much!

**Review by mjbvz — DISMISSED** [review]
Custom editor changes lgtm

**Comment by sandy081** [comment]
Re `src/vs/workbench/browser/parts/views/viewFilter.ts`

Unfortunately, I am working on these changes and would be testing and commit them separately. Changes in this land are proven to be too sensitive. I would request to undo this change from this PR. Thanks for understanding.

**Review by sandy081 — CHANGES_REQUESTED** [review]
Please revert these changes src/vs/workbench/browser/parts/views/viewFilter.ts

**Comment by weartist** [comment]
> Please revert these changes src/vs/workbench/browser/parts/views/viewFilter.ts

okay

**Comment by weartist** [comment]
> Please revert these changes src/vs/workbench/browser/parts/views/viewFilter.ts

Solved complete

**Comment by weartist** [comment]
@sandy081 

> Please revert these changes src/vs/workbench/browser/parts/views/viewFilter.ts

Solved complete, thanks~

**Comment by weartist** [comment]
> Please revert these changes src/vs/workbench/browser/parts/views/viewFilter.ts

revert resolved

**Comment by weartist** [comment]
@sandy081 @mjbvz  During this time, the style.ts css adapt modified by others has also been merged into main, so I also undid its changes

**Review by mjbvz — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
