### PR TITLE
Fix #178766 - VSCode does not highlight all matches of the highlighted text

### LINKED ISSUE #178766: VSCode does not highlight all matches of the highlighted text
Type: <b>Bug</b>

It seems like VSCode only highlights up to 999 matches of text highlighted by me.

See screenshot for an example.

image

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.70GB free)|
|Process Argv|--crash-reporter-id be57aed7-4363-4853-8391-6f4487bf789b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-subtitles|ast|0.4.0
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
cuesheet|zgm|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012

```

</details>

### PR DESCRIPTION
**Pull request by ikhatib**
This PR has added code to use a deque to address the issue of not being able to see all relevant highlighted text by instead keeping track of most relevant 999 matches and highlighting those. Changes to highlights.js reflects new changes. However, is not fully integrated with the rest of the codebase.

Issue #178766

### CODE REVIEW

**Comment by ikhatib** [comment]
> 

@microsoft-github-policy-service agree [company="{N/A}"]

**Comment by ikhatib** [comment]
> @ikhatib the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree

**Comment by gjsjohnmurray** [comment]
Please edit the issue description to include the number of the issue it addresses (prefixed with a hash). That way we can jump there easily, and GH will also provide a back link from it to this PR.

**Comment by hediet** [comment]
This PR does not seem to include any TypeScript sources.

**Pull request closed without merging**
