### PR TITLE
Fixes #93206 - adds extension context key

### LINKED ISSUE #93206: Add extension context key to extension/context menu
So that you can have a `when` clause like:

`extension == 'eamodio.gitlens' && extensionStatus == installed`

/cc @sandy081

### PR DESCRIPTION
**Pull request by eamodio**
This PR fixes #93206

### CODE REVIEW

**Comment by sandy081** [comment]
How about calling it `extensionId` instead of `extension` ?

**Comment by eamodio** [comment]
Hehe, honestly I had it that way first and then I looked up the other cases (view, viewItem) where we use the I'd but don't add the id  suffix. But I'm open to either.

**Comment by sandy081** [comment]
Good observation. Lets go with `extension`. We follow the same when we ask for ids, for eg: `extensionDependencies` , `extensionRecommendations` etc.,

**Review by sandy081 — APPROVED** [review]
LGTM

**Pull request merged**
