### PR TITLE
Handle binary files git preview

### LINKED ISSUE #14658: Binary files being opened in staged diff view throws
Steps to Reproduce:
1.  Have a binary file, for instance a gif
2. Open it in vscode - notice that the editor nicely says it is binary and can not be opened
3. Open git viewlet and stage it -> once you try to open it staged it throws an exception

### PR DESCRIPTION
**Pull request by akhomchenko**
Closes #14658

I've actually copied message from `resourceViewer.ts` as I'm not sure that `rawGithubService.ts:show` is related to it.

I would try to provide tests.

### CODE REVIEW

**Comment by joaomoreno** [comment]
Did you confirm that this works? I'm not really sure it would. The git library will never return that error code.

**Comment by gagoman** [comment]
@joaomoreno I've added a test for a specific case to keep PR as small as possible.
If more tests for `show` are required, I can write them.

**Comment by joaomoreno** [comment]
This PR just seems to fix this popup:

image

By showing this one instead:

image

What we should do is actually support the diffing of binary files, like images. Let's try to to that instead of this.

**Comment by gagoman** [comment]
@joaomoreno PR is based on this idea: https://github.com/Microsoft/vscode/issues/14658#issuecomment-256910344

Anyway, as VS Code is going to have a SCM API, it can be handle there.

**Comment by joaomoreno** [comment]
Thanks for the effort though, really appreciate it!

**Pull request closed without merging**
