### PR TITLE
Allow exact matches and excluded terms in fuzzy search

### LINKED ISSUE #128923: Allow exact and excluded matches in fuzzy search.
In fuzzy searches, allow you to require an exact match by using double quotes and exclude terms using a minus sign.  Here are some examples:
- `"abc"` would match `abc`, but not `abac`
- `abc -def` would match `abc`, but not `abcdef`.

### PR DESCRIPTION
**Pull request by ssigwart**
This PR fixes #128923.

## Automated Testing
```bash
yarn run mocha --ui tdd --run src/vs/base/test/common/fuzzyScorer.test.ts
```

## Manual Testing
Open "Go to File" and type in searches using double quotes for exact match and the minus sign for excluding.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
👋 @ssigwart

Thanks for contributing. I have implemented the quoting part of this in a way that didn't require regex: #131292

I'm not sure we want to have the `-foo` syntax yet because it really doesn't align with anything else that VS Code does... however, @bpasero gave a clue on how to do this here on another attempt I made: https://github.com/microsoft/vscode/pull/131215#issuecomment-903069455

**Comment by ssigwart** [comment]
Thank you, @TylerLeonhardt!  The exact match should be a great improvement.

I still think exclusions could be helpful in certain scenarios, but much less frequently than exact matches.  The scenario I'm thinking of is when you're not really sure what file you want so you start with a word you think should be in the name, then start filtering down as you find patterns that you know aren't it.

**Comment by bpasero** [comment]
What should happen if you only type a single word with a leading `-`? wouldn't then all files need to be returned?

**Comment by ssigwart** [comment]
Yeah, that was one concern I did have on this.  I have 3 thoughts on handling that:
1.  If you quote it (e.g. `"-text"`), it's no longer a leading `-`, so behaves as you'd expect.
2.  An exclusion pattern should only be valid when you have some type of inclusion pattern.
3. A `-` alone is not treated as an exclusion.  That way as you start typing, it doesn't return all files.

With 1 & 2, a simple search like `-text` shouldn't break in anyone's workflow.  The thing that could break is `-text moretext` because you'd have to write that as `"-text" moretext`.

**Comment by bpasero** [comment]
Yeah that sounds reasonable to me 👍 . My remaining worry is discoverability though.

**Comment by TylerLeonhardt** [comment]
1 2 & 3 are exactly what I was thinking as well.

Like @bpasero, I also have concerns about discovery. The fact that search engines use this syntax makes me feel a little better... But it's not called out anywhere.

Maybe we could add some items to the `?` quick access for `"foo"` (it would add `"|"` with the cursor in the middle if possible) and `-foo` (not as nice... Maybe adds `query -|` with the cursor at the end)

The other thing I worry about is having people learn a new thing that doesn't work anywhere else in the product... But the solution to that is to add toggles to the quick pick and I think that's ugly personally.

**Comment by TylerLeonhardt** [comment]
We should really talk about this in https://github.com/microsoft/vscode/issues/131431 :)

**Comment by ssigwart** [comment]
Thanks for the feedback, @bpasero and @TylerLeonhardt.  I'll comment on that issue.

**Pull request closed without merging**
