### PR TITLE
fix: remove python usage in macOS cli wrapper

### LINKED ISSUE #134635: "Visual Studio Code - Insiders" needs to be updated on macOS Monterey
Does this issue occur when all extensions are disabled?: Don't know. The message appears only once.

- VS Code Version:
- OS Version:
Version: 1.62.0-insider
Commit: 0dae77d06e33eaf1616cc1a53d77e717b284a626
Date: 2021-10-08T05:22:27.408Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

Steps to Reproduce:

1. Install the latest insiders version and run it on macOS Monterey (v12.0 beta)

image

It's not clear what needs to be done. I tried to click on "Learn more..." but the dialog disappeared and nothing else was opened. The dialog does not open again if I restart vscode.

### LINKED ISSUE #137954: `./code` helper script needs some fixes
Weird decision to use python for path resolution in a bash script when it can all be done locally.

seems this may only be a mac decision too? there's half a dozen `code` launchers throughout the source tree, but this is the strangest one we could improve a bit: https://github.com/microsoft/vscode/blob/main/resources/darwin/bin/code.sh

Also relying on python means the `code` command breaks if python isn't available, which doesn't seem ideal (it broke for me when running under a `pyenv` controlled path before a python version was defined, so `python` couldn't be used and then `code` just breaks).

I'd propose a rewrite as:

```bash
# Get absolute path of the directory holding the "code" shell script
CONTENTS="$(cd "$(dirname "$0")"; pwd)"

# Jump up 3 more directories to the Contents/ path
for i in {0..2}; do
    CONTENTS="$(dirname "$CONTENTS")" 
done

# or, could skip the "absolute path resolution" completely and just trust shell path navigation works:
# CONTENTS="$(dirname "$0")/../../../"

ELECTRON="$CONTENTS/MacOS/Electron"                                                                                                                                      
CLI="$CONTENTS/Resources/app/out/cli.js"                                                                                                                                 
ELECTRON_RUN_AS_NODE=1
exec "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"   
```


Alternatively, if for some reason we love python so much we want to re-implement bash primitives using it, a better solution would be:

```bash
function contentspath() {                                                                    
    python -c "import pathlib,sys; print(pathlib.Path(sys.argv[1]).resolve().parent.parent.parent.parent)" "$1"
}                                                                                                                                                          
                                                                               
CONTENTS="$(contentspath "$0")"                                                                                           
ELECTRON="$CONTENTS/MacOS/Electron"                                                                                                                                      
CLI="$CONTENTS/Resources/app/out/cli.js"                                                                                                                                 
ELECTRON_RUN_AS_NODE=1 
exec "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"    
```

also the original `code` script has a bug where it's giving `$0` as an argument to the python script instead of `$1` as the actual parameter (but the parameter is always just `$0` anyway, so `$1` == `$0` and the inaccurate argument never has an impact).

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/134635
Fixes https://github.com/microsoft/vscode/issues/137954

### CODE REVIEW

**Comment by deepak1556** [comment]
Pending build for verification https://monacotools.visualstudio.com/Monaco/_build/results?buildId=145742&view=results

**Comment by joaomoreno** [comment]
@deepak1556 What are your thoughts on https://github.com/microsoft/vscode/issues/137954 ?

**Comment by deepak1556** [comment]
Thanks for the pointer! I agree with the sentiment in that issue, if there is a simpler non-python way to get the absolute path it would also make this script more resilient. But I have to try it out, to confirm if it covers all cases. Let me try to adjust this PR in that order.

**Comment by stephanierifai** [comment]
Hi there! Is there an ETA on this? This would help us with a related issue folks have been hitting on Docker Desktop so appreciate the work on it.

**Comment by StefanScherer** [comment]
I don't know the history well enough, but I wonder if we can just drop the dependency on python at all. 🤔 

What does `scripts/code.sh` do different? It seems it tries to solve the same problem, but with just plain bash.
See https://github.com/microsoft/vscode/blob/main/scripts/code.sh#L5-L8

```bash
if [[ "$OSTYPE" == "darwin"* ]]; then
	realpath() { [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"; }
	ROOT=$(dirname "$(dirname "$(realpath "$0")")")
else
```

**Comment by deepak1556** [comment]
> What does scripts/code.sh do different?

It does try to achieve the same effect but that won't work for symlink cases, `resources/darwin/bin/code.sh` will usually get symlinked to default binary search path `/usr/local/bin` so that `code` command is available to users. We need a bash solution that will also work for this case.

**Comment by deepak1556** [comment]
Change works fine, tested with https://monacotools.visualstudio.com/Monaco/_build/results?buildId=152892&view=results

**Comment by deepak1556** [comment]
This PR does not handle multiple installation cases for the same bundle identifier, I am sure if there is a wide use case for it.

**Review by joaomoreno — APPROVED** [review]

**Comment by joaomoreno** [comment]
> This PR does not handle multiple installation cases for the same bundle identifier, I am sure if there is a wide use case for it.

Yeah you make a good point. I'm guessing `mdfind`will just pick a random installation, if two different versions of the same product are found in disk... I'm not too excited about that.

**Comment by deepak1556** [comment]
I think we can make a safe fallback case with https://github.com/microsoft/vscode/pull/138582/commits/e9af584edb81eb4835d8029130cb34a80bf24d84 if there are multiple results from `mdfind`. (ie) 

1) Use `mdfind` when there is exactly one result
2) Fallback to sudo `realpath` implementation otherwise

thoughts ?

**Comment by deepak1556** [comment]
You are right, I found myself in the same path when writing this PR. But given the python2 deprecation makes our cli completely useless on macOS monterey for many users, I will go ahead and try this https://github.com/microsoft/vscode/pull/138582#issuecomment-102583845, will see if I can improve it later based on user  feedback.

**Comment by n8felton** [comment]
I'm not sure that using `mdfind` should be an acceptable solution as there are plenty of instances where Spotlight may be completely disabled, or if VScode is installed to a location that is excluded from Spotlight.

I recommend using one of the `readlink` [solutions\[1\]][1] [proposed\[2\]][2] as it will use the actual symlink used to call `code`, which helps to simulate what the python `realpath` code was doing, rather than assume whatever app bundle is found with `mdfind`.

[1]: https://github.com/microsoft/vscode/commit/e9af584edb81eb4835d8029130cb34a80bf24d84
[2]: https://github.com/microsoft/vscode/pull/141891/commits/ecf4182c9e982c6c6b535f1d44206171c416e0e4

**Comment by Tyriar** [comment]
The pure bash approach seems like the way to go from my perspective. Since there's a bash shebang it should be guaranteed that the script will run under bash, you just need to make sure you support the lowest expected version of bash shipped in macOS.

**Comment by deepak1556** [comment]
Verified locally, merging for insiders testing.

**Comment by aeschli** [comment]
related: https://github.com/microsoft/vscode-remote-release/issues/6442

**Pull request merged**
