### PR TITLE
[bugs] console remains attached

### LINKED ISSUE #100516: [CommandLine] code command remain attached
executing `code .` the process remains attached in the process of my console, if I close my console vscode also closes

image

### PR DESCRIPTION
**Pull request by buster95**
This PR fixes #100516

### CODE REVIEW

**Comment by deepak1556** [comment]
The current default value is `false` for the electron version being used. Not sure how this fixes the issue.

**Comment by buster95** [comment]
When remains attached shown this
image

**Comment by buster95** [comment]
Default? what version of electron, looking for info, I found before electron 9, is not set to false by default

**Comment by deepak1556** [comment]
Master is on 8.3.3 https://github.com/electron/electron/blob/8-x-y/docs/api/app.md#appallowrendererprocessreuse which defaults to `false`

You should fine with launching the cmd wrapper for code that will not attach to the console `code.cmd` if you still want to launch the executable directly then you can set the environment variable `ELECTRON_NO_ATTACH_CONSOLE`

closing this as intended behavior.

**Pull request closed without merging**
