### PR TITLE
Group search results by root folders

### PR DESCRIPTION
**Pull request by keegancsmith**
This is a work in progress PR to add support for grouping of search results. I am submitting it now since I believe the rest of the work is mostly minor and I'll only getting back to this PR on Monday. So hopefully will get some early feedback.

image

image

TODOs:

* [x] Add replace actions. (For follow-up PR)
* [x] Make it works with extraFileResources
* [x] Always display some FileMatches. Currently will not auto-expand repos if many results
* [x] Render FileMatch names for relative to folder.
* [x] Render single folder searches without extra level.
* [x] Create CSS rule `.foldermatch`, rather than reusing `.filematch`.
* [x] Update textual descriptions of results to take into account folders.
* ~~Bug in Tree renderer for auto-expanded children~~

cc @roblourens

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks for the PR, but in the future, I would strongly recommend starting a discussion with me over a new feature before doing a lot of work to implement it. I plan to look into the search UI for multiroot in depth in July, and while this is one possibility, there are other UI options I want to investigate. I think one could make a good argument for not adding a new level of nodes to the results UI, but I will be experimenting more later.

**Comment by keegancsmith** [comment]
@roblourens apologies for not opening a discussion PR first. I've been working on multi-repo search at Sourcegraph and we found having a flat list of results frustrating. So this PR is really just the next logical step from the current UI, mainly to experiment with to see if it feels good. I understand it may not be the best UX for displaying the search results. Don't worry about it being wasted work, we want to launch a more polished multi-repo search at Sourcegraph soon so it will be used for that. I also want to try out this version to see if it feels any good. If vscode goes a different direction, I'll probably move Sourcegraph towards what vscode does.

Is the next step forward to rather close the PR and open the discussion up on an issue? Is there anything salvageable from this PR that I could maybe cherry-pick/patch into another PR?

**Comment by roblourens** [comment]
No worries, I just opened #29977 for discussion and I'll leave this open. It may be useful if we go this route. I'm about to go out of town for almost a week and will be thinking about it after that. I didn't realize Sourcegraph was working on this too, so I look forward to checking it out!

**Comment by nicksnyder** [comment]
> I didn't realize Sourcegraph was working on this too, and I look forward to checking it out!

@roblourens Would you guys be interested in knowing what we are working on on an ongoing basis? If so, we could figure something out (post our monthly plan on our public issue tracker, share a google doc, send you periodic email, etc.). cc @sqs

**Comment by roblourens** [comment]
I would be interested in following along. Posting a monthly plan on github has worked well for us.

**Comment by keegancsmith** [comment]
FYI I have resolved most of the TODOs listed in the PR description. However, they require a little bit of work to be upstreamed here. So if you would like to move forward with this PR I'll cherry-pick/clean them up and push them.

**Comment by roblourens** [comment]
Hey @keegancsmith, this is the direction I want to go with the multiroot search UI (should have figured that out earlier but I had to investigate and convince myself). I'd love to take the PR if you are interested in porting the rest of the changes forward. Let me know how I can help.

**Comment by keegancsmith** [comment]
@roblourens great. I'll update the PR this week. What I have should work well, except I neglected the non "read-only" use case. So will also implement the replace action.

If you have any early UX feedback, this is what it looks like on Sourcegraph [right now](https://sourcegraph.com/github.com/Microsoft/vscode?q=progress&repos=github.com/Microsoft/vscode,github.com/Microsoft/monaco-editor,github.com/Microsoft/vscode-languageserver-node)

image

**Comment by roblourens** [comment]
Thanks! I think that looks great. The "search groups" feature is interesting!

**Comment by keegancsmith** [comment]
@roblourens I've pushed some changes.

* I haven't tested what happens when `extraFileResources[]` is non-empty. How do I get entries into that in the UI?
* The informational text `{0} result in {1} file` is now `{0} file in {1} folder`. I can include file count if you have a suggestions for how to word it.
* Including folderQueries as part of the search test cases was done naively. I can refactor the tests to be more readable as part of this PR if ya like.
* Find Replace All works. I have only tested via clicking on the find replace button.
* The action buttons are hidden for folders. Maybe could be done as a follow-up PR?
* If we only have one folder in the workspace, we still render the extra level. I can change in this PR, but could also be a follow-up PR if ya like.

Some updated screenshots

image

image

image

**Comment by roblourens** [comment]
Looks awesome so far, thanks! Few comments:

> I haven't tested what happens when `extraFileResources[]` is non-empty. How do I get entries into that in the UI?

Those are files that are open in the window but don't belong to a workspace. You can use the "open" dialog to open something outside of a root folder. I'm not sure how they should be organized in the UI. I suppose they should get their own node. "Other files" or something.

 > The informational text `{0} result in {1} file` is now `{0} file in {1} folder`.

Hm, I think the result count is still more relevant. I think a typical workspace will only have a few root folders. I think the result count should still be included, and the folder count maybe could be omitted, or maybe like `{0} results in {1} files in {2} folders`.

> Including folderQueries as part of the search test cases was done naively. I can refactor the tests to be more readable as part of this PR if ya like.

That's ok. Are the folderQueries added because the result needs to belong to a workspace, otherwise it will be lost? I think this is related to the extraFileResources issue then?

> The action buttons are hidden for folders. Maybe could be done as a follow-up PR?

I think the folders should have action buttons, but I don't need everything in one PR.

> If we only have one folder in the workspace, we still render the extra level. I can change in this PR, but could also be a follow-up PR if ya like.

I think in general, the experience for a non-workspace window should be the same as it currently is. This would also mean showing a single level with `extraFileResources` mixed in to the workspace results. I think I'd like to have this before I send this change out.

**Comment by keegancsmith** [comment]
That all sounds great to me.

> I think in general, the experience for a non-workspace window should be the same as it currently is. This would also mean showing a single level with extraFileResources mixed in to the workspace results. I think I'd like to have this before I send this change out.

Should I render as a single level when there is only one folder query, or should I use the contextService to determine that. So for the latter a workspace with one folder will get the new rendering.

**Comment by roblourens** [comment]
I think that we should try to match what shows up in the File Explorer. There, a workspace with one folder shows the one root folder node at the top, so let's match that.

**Comment by keegancsmith** [comment]
@roblourens ok I've done everything except the action bar for FolderMatches. PTAL

image

**Comment by keegancsmith** [comment]
Aah I have test failures. I ran `./scripts/test.sh -g search`, but that excludes tests which just mentioned `Search`. I'll fix.

**Comment by keegancsmith** [comment]
Rebased against latest master and pushed fix

**Comment by roblourens** [comment]
Thanks a ton, this looks great. I've tested on Mac and Windows, and the code looks good. I'm going to wait until after today's insiders build to merge, because if any issues come up, I don't want it to be stuck in insiders for the weekend.

**Comment by felixfbecker** [comment]
Awesome, looking forward to this!

**Review by roblourens — APPROVED** [review]

**Comment by ssalka** [comment]
Is this feature no longer supported? My team uses a monorepo, so would be great if my search results could be grouped by, for example, `server` and `frontend` (two of our top-level folders in the repo)

However, wasn't able to find any settings available for configuring this 😕

**Pull request merged**
