### PR TITLE
Terminal renderer and activeTerminal APIs

### LINKED ISSUE #46192: Terminal Providers
Issue Type: <b>Feature Request</b>

Enable extensions provide custom terminals to other extensions and tasks

Today extensions and tasks use vscode's API `vscode.window.createTerminal(terminalOptions)` to create a new terminal window, and some other APIs to render task output as terminal output.
Our extension can change the way a terminal is started, and we want user to be able to apply this change to other terminals and tasks vscode may be running without changing their code.

The idea is to introduce a concept of _Terminal Provider_, an object that will be chained when something starts a new terminal:

```typescript
interface TerminalProvider {
    createTerminal(options: TerminalOptions, provider: TerminalProvider): Promise<Terminal>;
}

// A way to register a terminal provider. This function returns a disposable
// which, when disposed, unregisters the provider.
window.registerTerminalProvider(provider: TerminalProvider): Disposable;
```

When a provider is registered, it will be called when anyone calls `window.createTerminal(...)`. The `provider` argument in `createTerminal` is the previous chained provider, or internal vscode implementation that actually creates a terminal.

Registering or un-registering a provider should not affect existing terminals.

### LINKED ISSUE #47615: Track user focus across editor and integrated terminal
Issue Type: <b>Feature Request</b>

Right now only active text editor can be tracked with `window.activeTextEditor`. Though users can focus other UI elements, like integrated terminals, there is no way to tell when user switches focus from the text editor to the integrated terminal, or from one terminal to another.

Because of that user tracking in our extension cannot tell when user has changed focus to an integrated terminal, or switched active terminals.

We'll need something like `window.activeTextEditor`, but more generic, e.g.
`activeWindow: TextEditor | Terminal | .... | undefined`

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #46192
Fixes #47615

### CODE REVIEW

**Comment by sgallouet** [comment]
would activeTerminal graduate to be part of the default release ? I'm using this proposed APIs since July and it seems to work great.

**Comment by Tyriar** [comment]
@sgallouet the main thing I'm waiting on is to be aware of consumers so we can make sure it's working well. Naturally I'm interested in your use case, can you link your extension?

**Comment by sgallouet** [comment]
@Tyriar I can't disclose much unfortunately, but simply put I'm using few terminal with different or same ssh connection and the extension do something like the "send to terminal" on my current active terminal which start some computation. it works pretty well. 
is there an official channel to give proposed API feedback?

**Comment by Tyriar** [comment]
@sgallouet I don't think so, but I think I've heard enough for us to commit to the active terminal APIs. https://github.com/Microsoft/vscode/issues/58357

**Pull request merged**
