### PR TITLE
Make Clicking in Scrollbars Move By Page

### LINKED ISSUE #43564: feature-request: click below/above scrollbar handle moves one screen height
When viewing the "release notes" on VSCode, I can click above/below the scrollbar handle to scroll up/down one screen height (kind of "relative scroll"). In a regular file to be edited in VSCode, a click above/below the scrollbar handle jumps to the (absolute) position. The latter does also not match with the default Windows behaviour. 
This behaviour is also cumbersome in very large files: Even clicking on one of the markers shown in the scrollbar will send you somewhere near, if lucky. After that you have to use the scrollwheel or the scrollbars arrow buttons (both slow).
Therefore this feature-request: Please add a setting to enable a "page wise" scroll when clicking above/below the scrollbar handle. The same applied for the Minimap. But I'll suggest to create two seperate settings.

### PR DESCRIPTION
**Pull request by AE1020**
This changes clicking in the "gutter" area of a scrollbar from
jumping to a position in the file proportional to the click, to
the more standard behavior of "clicking before the slider does a
page up (or left), and clicking after the slider does a page down
(or right)".

The behavior is requested in #43564 (and 101698, 100446, 87273
70267, 62834, 55139...)  It would likely make a reasonable
default, since clicking in the source preview right next to the
scroll bar already permits jumping to absolute positions.

However, this PR could also be amended to make it an option.
Documentation of the implementation process is here:

https://ae1020.github.io/vscode-scrollbar-go-by-page/

This PR fixes #43564

### CODE REVIEW

**Comment by AE1020** [comment]
This commit modifies the behavior of 'ScrollbarState.getDesiredPositionFromOffset`.  There are two tests which apparently pass literal values into that function and expect a value back.  This has changed.

The new results make sense, and it's certainly possible to just change the existing numbers.  But both tests wind up being for page down.

### Test One - excerpted/annotated (was 32849, is now 33126)

    let actual = new ScrollbarState(
        0,  // arrowSize
        14,  // scrollbarSize
        0,  // oppositeScrollbarSize
        339,  // visibleSize
        42423,  // scrollSize
        32787  // scrollPosition
    );

    assert.equal(actual.getSliderPosition(), 249);
    assert.equal(actual.getSliderSize(), 20);
    assert.equal(actual.getDesiredScrollPositionFromOffset(259), 32849);  // this changed

Here it registered as a "page down", because the click at 259 is after the slider (249) in "slider/offset units".  So the visibleSize was added in scrollPosition units (32787 + 339 = 33126) .

### Test Two - excerpted/annotated: (was 32811, now 33126)
	
    let actual = new ScrollbarState(
        12,  // arrowSize
        14,  // scrollbarSize
        0,  // oppositeScrollbarSize
        339,  // visibleSize
        42423,  // scrollSize
        32787  // scrollPosition
     );

    assert.equal(actual.getSliderPosition(), 230);
    assert.equal(actual.getDesiredScrollPositionFromOffset(240 + 12), 32811);  // this changed

Again, this acts as a "page down", because the click at 262 is after the slider (230) in "slider/offset units".  So the visibleSize was added in scrollPosition units (32787 + 339 = 33126).

**Review by crypt096 — APPROVED** [review]

**Review by alexdima — CHANGES_REQUESTED** [review]
This new behaviour needs to be behind a setting. We have very many users who have gotten used to the current behaviour. The current behaviour is intentional, because it allows to click on an overview ruler indicator (like an error) and jump directly to the right location.

**Comment by AE1020** [comment]
> This new behaviour needs to be behind a setting.

Added `editor.scrollbar.gutterClickMovesByPage`, trying to follow the existing scrollbar pattern for settings [(read as `options` in editorScrollbar.ts)](https://github.com/microsoft/vscode/blob/94b05d07cb2891f7d42f51c217ae2ffb92e892eb/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L33).

**Comment by AE1020** [comment]
@alexdima Please let me know if any further changes are needed, while I still have this set up to work on.

> This new behaviour needs to be behind a setting.

I made the setting **`editor.scrollbar.gutterClickMovesByPage`** default to false, so that the behavior will have to be explicitly changed.  So it should not be disruptive in the near term.  The question of whether it makes a better default to use a traditional scroll bar can be revisited after people have experience with the option.

> We have very many users who have gotten used to the current behaviour. The current behaviour is intentional, because it allows to click on an overview ruler indicator (like an error) and jump directly to the right location.

As a data point when I described this issue on the phone to a friend, without prompting he offered *"Can't you just click on that preview strip that shows a miniature version of the source if you wanted to jump to an absolute position, and have the scroll bar act like a normal scroll bar when you click?"*  So again, I think the scenario you discuss about jumping to specific highlighted positions should be covered by that method--not changing how scroll bars act.

But again: that can be a separate issue or discussion, as this commit does not change it from how it is today.

**Comment by RedDragonWebDesign** [comment]
Looks like this PR hasn't had a comment since September and might be stuck. I just want to make a comment showing support for this and hopefully encourage folks to review/approve it. Thank you for your time and effort everyone.

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
