### PR TITLE
Support for custom icons in completion items

### LINKED ISSUE #2120: How to customize CompletionItemKind icon
360截图1681030599141131

### PR DESCRIPTION
**Pull request by lmvco**
When using autocomplete, the items' icon is calculated based on the [kind](https://microsoft.github.io/monaco-editor/api/enums/monaco.languages.completionitemkind.html) value. This approach works for common languages. However, if we configured a new language or if we just want to change the existing icons, it would be great to provide a way to override the default behavior.

This PR adds support for that customization using a new property in the `CompletionItem` class.

This PR fixes https://github.com/microsoft/monaco-editor/issues/2120

### CODE REVIEW

**Review by rheh — APPROVED** [review]

**Comment by afvieira** [comment]
Hi,
any update on this? I was looking for this feature too.
Thank you

**Comment by dylanvorster** [comment]
why is this marked as out of scope / closed if I may ask?

**Comment by maxcorbeau** [comment]
> Sorry, but **we** are not interested in this function because **we** have no situations in which **we** could use this.

Microsoft doing open source: "**we** ... **we** ... **we**"

Just a thought: even if Microsoft doesn't have a use-case, maybe the open source community, which contributes to the development of this software, does (and the 8 upvotes further up seem to suggest so). 

Providing an `icon` property would allow the community to customize the editor to suit their needs (that property could be made optional so that if no value is provided, it falls back to the default behaviour).

**Comment by dylanvorster** [comment]
I think what really gets me with this issue is:

* its not like we logged an issue, we actually provided a fix
* as @maxcorbeau mentioned, this is supposed to be a community
* its so glaringly obvious why this would be a requested feature, since the idea of making Monaco OSS is so that people can build their own editor-like software with their own domain specific needs. As is the case at my company.
* There are so many other cases in the editor where it clearly *is* designed to be pluggable and extensible outside of how Microsoft uses it in VS Code, so why then shut this specific feature down?

**Comment by zardoy** [comment]
> as @maxcorbeau mentioned, this is supposed to be a community

You might think that this is only Open-Source project (which means that source code of the product is opened), and meanwhile not a community project. I mean if some project has only one person responsible for the feature part - his decisions will be final.

There are my thoughts, specifically to VS Code API on dammit icon:

> Providing an icon property would allow the community to customize the editor to suit their needs

It's really unclear here, there are thousands of things that could make editor more customizable - providing DOM API (or just CSS styling) or maybe editor model API? Probably it needs some value, show what it can give, there are no hundred of thumbs on the linked issue or some long stories that would demonstrate the problem in detail.

Meanwhile API is very limited, it doesn't mean you can't use custom icons at all. You can use File Icon Theme icons in completions ([vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons) has > 1000 icons). For example if you want to see Tailwindcss completions like in WebStorm, you can use file kind + item detail with `tailwind.config.js`.

There is a proof (note that other kinds icons remain unchanged):



You might say that this is suitable only for OSS and well-known projects such as aforementioned tailwind, but you can merge FIle Icon Themes via small patching (this is really easy to do via API) and bring your own custom icons via extension.

**Comment by mratanusarkar** [comment]
I have a use-case of a query editor, where this feature would greatly help to suggest tables, columns, database names, SQL functions, and other suggestions and keywords. This feature would have been of great help, as the existing [monaco-editor](https://github.com/microsoft/monaco-editor)'s existing language support for SQL doesn't have this feature inbuilt.

I can think of so many such use cases, not sure why this PR was closed 😞

**Pull request closed without merging**
