### PR TITLE
Add "Open to the Side" action to editor tab context menu.

### PR DESCRIPTION
**Pull request by Duroktar**
This implements feature-request #26966

This adds the missing "Open to the Side" option to the right click context menu on editor tabs. It is offered as the last choice in the menu which makes it easy to see, and also makes sense IMO considering it's the first choice in the folder browser right click context menu.

vscode_opentoside

Hope it can be useful.

Cheers.

edit: feature-request link

### CODE REVIEW

**Comment by Tyriar** [comment]
@Duroktar is there a feature request issue for this PR? If not please create one and link it.

**Comment by Duroktar** [comment]
@Tyriar okay man, done. Sorry about that, I'm just getting my feet wet and may be a little on the eager side :) The link is below and I added it to the original post as well. Let me know what else I can do to improve! 

feature-request: #26966

Thanks very much!

**Comment by bpasero** [comment]
@Duroktar thanks for the PR but I am not convinced this should be part of the core experience. First of all, there already is an action very prominently to split the current editor to the side:

image

Then I think, if the action should show up in the context menu, I suggest to try to do this via an extension if possible.

**Comment by Duroktar** [comment]
@bspasero Yes that button in the corner. The difference here being that you can _choose_ the tab to send to the split by having the context menu option. So for example if you have, foo.txt, bar.txt, and pie.txt opened with pie.txt as the main editor, pushing the split button in the top corner will split the editor on _ the current tab only_, however with my proposed change it is possible to right click on bar.txt (ie: not the current active tab) select "Open to the Side" and presto, your main window is still where it was originally and bar.txt is open in a split. It's not obvious until you try to do it and realize that sending an open tab into a split requires changing to it first.

Just some of my thoughts on it. But in the end it's up to you guys and I understand that :) however I think if you consider it with my point in light it may make a bit more sense. 

Cheers :beers:

**Comment by Tyriar** [comment]
@Duroktar I must have missed the ", thanks!" at the end of my comment, didn't mean to come off as demanding 😅

**Comment by Duroktar** [comment]
@Tyriar it's okay! I wasn't offended in the slightest :)

**Comment by jrieken** [comment]
>  I suggest to try to do this via an extension if possible.

Should be possible

**Comment by bpasero** [comment]
Closing due to inactivity.

**Pull request closed without merging**
