### PR TITLE
shrinkwrap update for js and markdown

### PR DESCRIPTION
**Pull request by ramya-rao-a**

### CODE REVIEW

**Comment by joaomoreno** [comment]
@kieferrm @ramya-rao-a What's up with this one? Should we merge it, close it or defer to February?

**Comment by ramya-rao-a** [comment]
I ran the shrinkwrap tool last time and found these diffs. They were not merged, because testing was done by then and so this was pushed to Jan. 
Looks like we are having the same situation again

**Comment by joaomoreno** [comment]
OK, we should do this at the beginning of a milestone. Pushing this out.

**Comment by ramya-rao-a** [comment]
I am closing this, as it is quote obsolete now

**Pull request closed without merging**
