### PR TITLE
Dont update disabled extensions 

### LINKED ISSUE #22461: Don't update disabled extensions
There seems to be a functional difference installed extensions disabled on a workspace level (they show up in settings). In the case of an extension disabled through the UI, I don't need it kept up-to-date until it's re-enableld through the UI. 

As of now, when an extension is disabled it still gets counted in the sidebar number for "extensions waiting to update". If I've disabled an extension, it would be nice if it's out of sight, out of mind.

- VSCode Version: `Version 1.10.2 (1.10.2)`
- OS Version: macOS `10.12.2`

Steps to Reproduce:

1. Install any extension
2. Hit `Disable` in the extensions panel
3. Wait for extension to update
4. Extension is shown as both disabled, and needing an update. There's a blue number shown in the sidebar for a disabled extension.

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #22461

This PR makes changes to avoid any update related UI for disabled extensions

cc @sandy081

### CODE REVIEW

**Comment by sandy081** [comment]
@ramya-rao-a It's an easy one but not sure making it default might make other users happy. Not showing the truth about an extension especially when others are showing may not be intended. We might have mitigated this issue already by not showing them in the default view. If this is necessary for users this can go behind a flag in my opinion. What do you think?

**Comment by ramya-rao-a** [comment]
There are 3 UI locations related to extension updates
- The badge in the activity bar
- The `Check for Extensions Updates` action that results in a notification that tells you the number of updates
- The `Update to 1.2.3` button on the extension in the list.

In my opinion the count on the badge should definitely not include the disabled extensions. This is a pro-active information we show and are calling the user to take an action. And the action on disabled extensions is not urgent.

We could update the notification from `Check for Extensions Updates` action to include the count for enabled and disabled extensions separately. This is something that the user explicitly asked for, so including the disabled extensions count separately makes sense.

With the `Check for Extension Updates` now including the disabled extensions, it is a no brainer to include the `Update to 1.2.3` action on the disabled extension.

I'll make the changes appropriately.

**Comment by ramya-rao-a** [comment]
@sandy081 Done.

**Comment by sandy081** [comment]
@ramya-rao-a I am still bit uncertain to show different update badge numbers depending on disabled extensions. Did not it confuse users if the two VS Code windows show two different badge numbers? If users really want that this feature I would go for opt in rather than giving default.

**Comment by ramya-rao-a** [comment]
I am hesitant to add a new setting for a feature that will be used only by a very small section of our user base.

Updated the PR to update the hover text on the badge to show the same message as the `Check for Extension Updates` command. It will continue to show the total number of outdated extensions.

This should be a good middle ground for both sides of the argument.

**Comment by sandy081** [comment]
@ramya-rao-a Sorry I think I buy your argument to have the badge showing only for enabled extensions. As you said it is prompting user to take some action and it should not when an extension is explicitly disabled. Please revert the last commit to go to previous change and push.

Thanks.

**Comment by sandy081** [comment]
LGTM

**Comment by ramya-rao-a** [comment]
Reverted the last change. Merging.

**Comment by ramya-rao-a** [comment]
Reverted the last change.

**Pull request merged**
