### PR TITLE
Added `${rootNameShort}` formatting

### LINKED ISSUE #145238: Request: `${rootNameShort}` for Window Titles
On all platforms, the `${rootName}` Window Title variable includes **" (Workspace)"**, and when using Remotes like WSL, the variable also includes something like **" [WSL: Ubuntu]"**. It would be useful to have a shorter variant with just the Workspace name, so instead of **"wsName (Workspace) [WSL: Ubuntu]"** we could have **"wsName"**.

I frequently have several Workspaces open and use Workspace names to distinguish between open windows in the Windows Task Bar/View and macOS Mission Control/Exposé. The extra characters describing the Workspace often cause the OS to truncate the visible window title, hiding other useful information.  The `window.title` property allows customization, but putting the Workspace first often sacrifices filename visibility for Workspace metadata. 

Since we already have access to `${remoteName}`, perhaps other Workspace component names could also be added? 

Current:
- `${rootName}` - **wsName (Workspace) [WSL: Ubuntu]**
- `${remoteName}` - **WSL: Ubuntu**

Proposed: 
- `${rootNameShort}` - **wsName**
-  `${rootIdentifier}` - **Workspace**   _// (similar to `${separator}`_

With those two variables defined, `${rootName}` could then be expressed as `${rootNameShort} (${rootIdentifier}) [${remoteName}]`

### PR DESCRIPTION
**Pull request by N1kO23**
This PR implements https://github.com/microsoft/vscode/issues/145238

- Adds `${rootNameShort}` template option
- Changes verbose from `boolean` to `Verbosity` enum consisting values `SHORT`, `MEDIUM` and `LONG`

### CODE REVIEW

**Comment by N1kO23** [comment]
I will add tests for this soon

**Comment by bpasero** [comment]
Thanks for the PR, I cannot make promises currently when I get a chance to review.

**Comment by N1kO23** [comment]
> Thanks for the PR, I cannot make promises currently when I get a chance to review.

Thank you for checking in on this, take your time :+1:

**Review by bpasero — APPROVED** [review]
Thanks! i have pushed more changes on top, please check

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
