### PR TITLE
fix debug console to handle more than one graphics mode in a single escape sequence

### PR DESCRIPTION
**Pull request by dyc3**
According to [ascii-table.com](http://ascii-table.com/ansi-escape-sequences.php), the spec allows for more than one graphics mode to be specified at a time.

### CODE REVIEW

**Comment by isidorn** [comment]
@dyc3 thanks a lot for your contribution! This looks great to me.
However do you have an example where this contribution clearly helps?
Also does this maybe fix one of https://github.com/Microsoft/vscode/issues/21423 https://github.com/Microsoft/vscode/issues/6845

**Comment by dyc3** [comment]
Sure. 
Here's before my fix:
Before
and after:
After

This would appear to fix #6845, but not #21423. I think that how the function is currently written does not make #21423 easy to fix, and it'll probably have to be rewritten for that.

**Comment by isidorn** [comment]
@dyc3 I checked and this indeed fixes #6845 - great!
In the after picture I do not see the actual difference since it is cutoff but does not really matter.
The only thing which makes me nervous is the `while (chr !== 'm')` loop which can spin infinetely. Can we rewrite this in such a way that we are sure it will always finishes?

**Comment by dyc3** [comment]
@isidorn Ah, I didn't see that before. I'll see what I can figure out.

**Comment by dyc3** [comment]
Unless there is something I'm missing, there is a practical limit to the number of graphic modes specified at one time: bold, underscore, blink, reverse video, concealed, foreground color. and background color. So limiting `codes` to a length of 7 at most should do the trick.

**Comment by isidorn** [comment]
@dyc3 looks good, thanks a lot. Merging it in

**Pull request merged**
