### PR TITLE
Markdown: Capture right parenthesis as part of url

### LINKED ISSUE #25870: Issue with link highlighting in mardown files
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|javadebugger|donjayamanne|0.1.0|
|python|donjayamanne|0.6.3|
|LogFileHighlighter|emilast|1.1.1|
|tabsanity|jedmao|0.0.9|
|docomment|k--kato|0.0.14|
|vscode-rust|kalitaalexey|0.3.14|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|material-icon-theme|PKief|2.0.5|
|better-merge|pprice|0.7.0|
|Ruby|rebornix|0.12.1|
|java|redhat|0.2.1|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Add `[good](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` to a text file.
2. Observe that the link is highlighted correctly and loads the correct page when clicked.
3. Add `[bad](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` to a markdown file.
4. Observe that the link stops highlighting after the `vs.85` and loads the wrong page when clicked.

The code `[this works](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` loads the correct link in Github, so it's not invalid markdown (or it's not invalid globally, at least). [this works](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)

capture

### PR DESCRIPTION
**Pull request by kdmu**
Fixes #25870
screen shot 2017-05-11 at 12 16 41 pm

### CODE REVIEW

**Comment by mjbvz** [comment]
Can you take a look at cases like: 

```
[good](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx) text (other text)
```

With the current change, the link is incorrectly detected as: `https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)`

**Comment by kdmu** [comment]
Thanks for reviewing! @mjbvz 

I am trying with the following pattern:
>`/(\[[^\]]*\]\(\s*?)([^\s]+)\)/g` 

It accomplishes with most of cases including the one you mentioned except `([tag](link))`, i.e. referencing within parentheses.
screen shot 2017-05-17 at 8 51 01 pm
I guess it's more natural to think that the first parenthesis is part of markdown syntax and not the second one, however in this scenario we are not interpreting like that given we are capturing as much parentheses as we can instead of capturing at least as possible as response to #25870. I am not sure if we should consider this as an error since there is another interpretation, what do you think? Btw, any pointe is more than welcome.

(Please let me know if we should redirect the discussion to issue)

**Comment by kdmu** [comment]
@mjbvz I just pushed a new link pattern and seems to work with my test cases, please let me if is anything is wrong.
screen shot 2017-05-18 at 6 39 26 pm

**Comment by mjbvz** [comment]
Great! Thanks for the follow up on this.

The change will be available in the next insiders build

**Pull request merged**
