### PR TITLE
Improve Explorer welcome view (fix #137414)

### LINKED ISSUE #137414: Opening folder closes the opened files.
Issue Type: <b>Bug</b>

steps to reproduce:
Open VSCode and open any few code files from your local machine.
Now go to explorer and open any folder.

expected:
all open files should remain open and folder also should open.
what actually happens:
all open files are closed and explorer opens a folder in the left pane.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1045-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1891)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (7.48GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id c923c656-5d69-4b3c-b6a6-a0d2bc6a4c89|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: athena|
|OS|Linux x64 5.4.0-1045-aws|
|CPUs|AMD EPYC 7571 (16 x 2537)|
|Memory (System)|61.71GB (4.59GB free)|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #137414

With at least one editor open:

image

With no editors open, appearance is as before:

image

### CODE REVIEW

**Comment by JacksonKearl** [comment]
As stands, the `ContextKeyExpr.and(WorkbenchStateContext.notEqualsTo('workspace'),IsWebContext)),` clause is present in the top level OR of both contributions, I believe that'd cause duplicated content in the non-workspace web context?

**Comment by gjsjohnmurray** [comment]
@JacksonKearl good catch. I have pushed a fix (I hope).

**Comment by JacksonKearl** [comment]
I note that `editorIsOpen` will be true even if the only open editor is the getting started editor, do you think that's fine?

**Comment by gjsjohnmurray** [comment]
I think that's fine. Behaving differently in that case would require another context key to be added, I reckon.

**Pull request merged**
