### PR TITLE
fix: select theme according to current color theme in dev mode

### PR DESCRIPTION
**Pull request by harbin1053020115**
To #190034

### CODE REVIEW

**Comment by aeschli** [comment]
Can you explain what's the intention?

**Comment by harbin1053020115** [comment]
> Can you explain what's the intention?

When developping a color theme extension, which I defined more than one color themes, vscode will always initialize with the first color themes provided by my color theme extension after reload browser(vscode in web), see the code blew: 
image
I expected that vscode will initialize the color theme which is used before.

**Comment by aeschli** [comment]
> I expected that vscode will initialize the color theme which is used before.

With the suggested code change it will still pick a theme from the extension under dev. But only if it provides a theme of the same type (dark, light....)
I don't think that makes things easier to understand...

**Comment by aeschli** [comment]
Ah, but it defaults to the first.
Sure, why not.

**Review by aeschli — APPROVED** [review]

**Review by benibenj — APPROVED** [review]

**Pull request merged**
