### PR TITLE
wait for trust to be initialized before prompting in tasks

### LINKED ISSUE #156183: tasks shouldn't prompt for trust when trust has been refused
Repro steps from @sbatten:

- Open vscode folder (not trusted)
- Get the default trust prompt
- Don't trust
- Immediately prompted for trust from tasks

### PR DESCRIPTION
**Pull request by meganrogge**
fix #156183

I find the workspace trust stuff to be a little confusing, so want to make sure this approach is expected/consistent. 

In testing, I couldn't repro the bug.

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
I would have expected `requestWorkspaceTrust` to handle this already. Adding @lszomoru as @sbatten is out

**Review by Tyriar — APPROVED** [review]
Approving as it looks fine, please let us know if this is wrong trusted workspace experts 🙂

**Comment by lszomoru** [comment]
@meganrogge, @Tyriar, apologies for not getting back to you on this. I agree with @Tyriar, consumers of workspace trust should not be calling `await this._workspaceTrustManagementService.workspaceTrustInitialized;`. I see that this change was made to fix a bug (https://github.com/microsoft/vscode/issues/156183). Do we have a consistent repro of that?

**Comment by meganrogge** [comment]
Just the repro in the issue that this PR intended to fix

**Pull request merged**
