### PR TITLE
Fix launch configuration input variable resolution.

### LINKED ISSUE #96522: User input variables not working for launch configuration in multi-root workspace
- VSCode Version:

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic snap
```

- OS Version: ~~Ubuntu Bionic 18.04~~ Ubuntu Xenial 16.04 running on Docker instance.

Steps to Reproduce:

1. Create a multi-root workspace settings file.
2. Add a launch configuration object with the inputs and configurations.
3. Try to lunch the configuration (debugger).
4. Get an error message saying:

```
Undefined input variable 'variableNameHere' encountered. Remove or define 'variableNameHere' to continue.
```

E.g.

```json
{
  "folders": [
    {
      "path": "myLocalFolder"
    }
  ],
  "launch": {
    "version": "0.2.0",
    "inputs": [
      {
        "id": "myIndex",
        "type": "promptString",
        "default": "",
        "description": "Index of something to be processed."
      }
    ],
    "configurations": [
      {
        "name": "MyProject (Debug)",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder:myLocalFolder}/myproject/bin/process",
        "args": [
          "-i",
          "${input:myIndex}"
        ],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder:myLocalFolder}",
        "environment": [],
        "externalConsole": false,
        "preLaunchTask": "Build (MyProject)",
        "linux": {
          "MIMode": "gdb"
        },
        "osx": {
          "MIMode": "lldb"
        },
        "windows": {
          "MIMode": "gdb"
        }
      }
    ]
  }
    ...
}
```

Does this issue occur when all extensions are disabled?: Cannot test - working inside a docker container lunched by the docker extension.

p.s.: the inputs work just fine for tasks in multi-root workspace.

### PR DESCRIPTION
**Pull request by bzarco**
When resolving launch configuration variables during a debug session, the configuration target was not being specified, always defaulting to reading workspace folder inputs. This made it impossible for user or workspace file launch configurations to use input variables, as the inputs list was never found.

This change forwards the launch configuration source to the configurationResolverService, so that it looks for the inputs list in the right place.

Forwarding the source fixed single-root workspaces, but multi-root workspaces were skipping the inputs lookup, since they pass an undefined workspace folder... In this case, the workspace folder is not relevant, as the config and inputs are defined in the workspace file, and allowing resolution to continue yields the desired behavior.

This PR fixes #96522

### CODE REVIEW

**Comment by bzarco** [comment]
For the record, tasks already forward the source correctly, [passing `TaskSourceKind.toConfigurationTarget(task._source.kind)`](https://github.com/microsoft/vscode/blob/ba33738bb3db01e37e3addcdf776c5a68d64671c/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L575), that is why they do the right thing.

**Comment by bzarco** [comment]
Any chance this could make it in the May milestone (assuming it looks good :) )? Would love to be able to use input variables in our launch configs... Thanks!

**Comment by alexr00** [comment]
I'm fine with the configuration resolver related changes. @isidorn or @weinand for the debug changes.

**Comment by dslijepcevic** [comment]
What is the status of this PR, will it be merged anytime soon? For our team it's a major headache because the dynamic workspace file that we generate during configuration process is useless without being able to use input variables in launch configurations. I fear we will have to resort to *programatically* modifying folder's `launch.json` and `tasks.json` and these files are not checked in a repo and are meant for developers' own usage. Looks like a dirty hack to me :(

**Comment by weinand** [comment]
I'm on vacation right now, but will resolve the issue ASAP.

**Comment by dslijepcevic** [comment]
@weinand Thank you, I appreciate it!

**Comment by weinand** [comment]
@bzarco PR looks good and works fine.
Thanks a lot.

**Pull request merged**
