### PR TITLE
Fix-79658 New pattern to Preserve Case ( underscore separated variables)

### LINKED ISSUE #79658: New pattern to Preserve Case ( underscore separated variables)
@rebornix  and @roblourens  , Similar to #79525 , We can implement for underscore character as well , Proposing this will be only just underscore or just hyphen replacements and not both.

Foo-Bar replaced with newfoo-newbar with case preserved will be Newfoo-Newbar and Foo_Bar will be Newfoo_NewBar.
Please let me know if this gets a node from you guys ?
Thanks!

### PR DESCRIPTION
**Pull request by skprabhanjan**
@roblourens and @rebornix , Here is the implementation to handle underscore characters as well to fix #79658 ( As mentioned implemented it as two disjoint sets of replacement )
Please review this and let me know , Thanks :) 

PS : if you feel the request itself is not a valid one then feel free to close it :) ( I thought underscore was also useful in some places )

### CODE REVIEW

**Comment by skprabhanjan** [comment]
@roblourens and @rebornix 
Sorry , any updates on this ?

**Comment by skprabhanjan** [comment]
@roblourens  and @rebornix 
Sorry , any updates on this ? ( I will close this if this is not a legit requirement )

**Review by roblourens — APPROVED** [review]
LGTM, will let @rebornix review too

**Comment by skprabhanjan** [comment]
@rebornix , Any updates on this ? 
Did you get a chance to review this ?

**Comment by roblourens** [comment]
He's on paternity leave now but I think it's fine, I'll merge it.

**Comment by skprabhanjan** [comment]
@roblourens , sorry I did not know he was on leave and thanks for merging it 😁

**Comment by ArturoDent** [comment]
See my comment here: https://github.com/microsoft/vscode/issues/79525

**Pull request merged**
