### PR TITLE
ActionWithDropdownActionViewItem - add separator

### PR DESCRIPTION
**Pull request by lszomoru**
This pull requests adds a separate to the `ActionWithDropdownActionViewItem` which as far as I can tell is currently being used only in the extension edtior, and the extensions list. Adding the separate aligns the UX with the "Commit Action Button". 

image

### CODE REVIEW

**Review by miguelsolorio — COMMENTED** [review]
Overall the changes look good, but I noticed a very odd thing that in the [Cobalt theme](https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2), something (i think it's a transparent border) is making the container longer and is causing a weird gap with the separator background:

CleanShot 2022-07-14 at 18 41 50@2x

doesn't repro on the regular commit button

**Review by miguelsolorio — DISMISSED** [review]

**Comment by lszomoru** [comment]
Thanks @misolori! Let's give @sandy081 the chance to review and approve the PR as well.

**Comment by lszomoru** [comment]
@misolori, will be pushing a fix to this PR as the buttons does not look good using the Amethyst theme:
image

**Comment by lszomoru** [comment]
Pushed a fix:

image

**Review by miguelsolorio — DISMISSED** [review]

**Comment by sandy081** [comment]
I see following glitches:

image

Outline is broken while tabbing into the action 

image

**Comment by sandy081** [comment]
Also outline in the viewlet is slightly broken

image

image

**Comment by lszomoru** [comment]
@sandy081, I have pushed a commit to fix the issue that we have discussed today.
Before addressing things around the outline, I would wait to see if we want to explore this idea (https://github.com/microsoft/vscode/issues/157658)

**Comment by sandy081** [comment]
Thanks for the fix. Approving the changes and leave it to you if you want to tackle outline issue separately.

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
