### PR TITLE
Fix crash in JSON/HTML LSP servers when initializationOptions are not provided

### PR DESCRIPTION
**Pull request by apexskier**
A bug hasn't been filed, but this somewhat relates to https://github.com/microsoft/vscode/issues/72124.

I'm using the VSCode json language server with another LSP client (Nova.app), and am seeing crashes in the server because it's assuming the [initialization request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize) contains `initializationOptions`. The spec says they're optional and there's [some handling of them as optional](https://github.com/microsoft/vscode/blob/0c50e1db17168a738235bd7e5c02b9f05ea5df59/extensions/html-language-features/server/src/htmlServer.ts#L122), so I think this is just and oversight and a clear bug.

I've gone through usages of `initializationOptions` for the JSON, CSS, and HTML servers and updated all of them to consistently treat them as optional.

I've tested this manually with my Nova extension. I did not see any unit tests related to this functionality to add to, and I think it's a minimal enough change that I'm not planning to add any.

### CODE REVIEW

**Comment by aeschli** [comment]
Looks good! Let me know whet the PR is ready (it's still marked as draft)

**Comment by apexskier** [comment]
I think it's ready, I was just waiting for the build (and went off doing other things)

**Comment by aeschli** [comment]
Thanks @apexskier !

**Comment by apexskier** [comment]
Thanks for merging, does anyone know what the publishing schedule/process for this package is? (Asking because it doesn't seem to be published on the same cadence as vscode itself. The last version was published 7 months ago, so three are quite a few pending changes)

**Comment by aeschli** [comment]
It's done on request :-) 
I just published vscode-json-languageserver@1.3.0
If you can give it a try that would be great

**Comment by apexskier** [comment]
Dang, there's a crashing issue on startup with the new release due to bad file references. I saw this locally as well, but fixed it locally as I thought it was due to some magic happening at release time to make this cross browser.

https://github.com/microsoft/vscode/issues/107949 I'll see what I can find

**Pull request merged**
