### PR TITLE
Fix composition logic for Firefox

### LINKED ISSUE #106392: Emoji get inserted twice in OSX Firefox
**monaco-editor version:** 0.X.Y
Latest

**Browser:**
Firefox 78.0.2 (64-bit)

**OS:**
macOS 10.5.6

**Playground code that reproduces the issue:**
  1. In Firefox on OSX goto https://vscode-web-test-playground.azurewebsites.net/
  2. From the edit menu, click Emoji & Symbols
  3. Select an emoji to insert
  4. Emoji gets inserted twice

Also reproducible at:
- https://microsoft.github.io/monaco-editor/
- https://microsoft.github.io/monaco-editor/playground.html

### PR DESCRIPTION
**Pull request by belcherj**
Fixes: https://github.com/microsoft/vscode/issues/106392

In Firefox when inserting Emoji's using the macOS emoji input or using the compositor for characters with accents è, ë, î, etc. the character is inserted twice. Additionally, when adding an accented character the base character was also inserted.

Examples:

🏅 inserts 🏅🏅
è inserts eèè

This change does two things:

- It removes `this._onType.fire(typeInput);` from the compositionupdate event listener. If you are in the middle of a composition there is no need to fire off the event. This change fixes the unaccented character from being inserted. `è` no longer inserts `eè`.

- In the composition end function `browser.isFirefox` is added to the conditional that resets this._textAreaState to the value of the text area. This is needed as the insert of the composition is handled by L294. The textarea needs to be updated correctly when the compositions ends.

Tested in Firefox (Windows 10, Ubuntu, macOS), Safari (macOS), Chrome (macOS), Edge Legacy (Windows 10), Edge (Windows 10)

This PR fixes #

### CODE REVIEW

**Comment by alexdima** [comment]
Just a reminder, for changes in this area we need to go through all the input modes documented at https://github.com/microsoft/vscode/wiki/IME-Test

@rebornix Could you please also help to test this? I think removing `this._onType.fire(typeInput);` from the `compositionupdate` will break CJK input.

**Comment by belcherj** [comment]
Alex, thank you for taking a look. I will work through the tests in that doc as well.

**Comment by rebornix** [comment]
I gave it a test on macOS and found it changed the behavior of Japanese IME in both Safari and Firefox, meaning that removing `this._onType.fire(typeInput);` changes the behavior

One example:

* Install Japanese IME
* Switch to Hiragana
* Open VS Code Insiders, type `watashi`, press enter, type `watashi` again, press enter
* You will get `私私`
* With this change, type `watashi`, press enter, you will get `私`. And then press `watashi` again, press enter, it ends up with `私`. Somehow the second `私` is omitted.

**Comment by rebornix** [comment]
I'll take a closer look at why this breaks CJK in October, thanks for your help @belcherj !

**Comment by rebornix** [comment]
Tested that `if (browser.isEdge || browser.isChrome|| browser.isFirefox) {` can solve the Firefox but without breaking other browsers. Thanks for your help!

**Pull request merged**
