### PR TITLE
Update C# Grammar

### PR DESCRIPTION
**Pull request by JoeRobich**
C# 8 support (Pattern matching enhancements, Asynchronous streams, Enhancement of interpolated verbatim strings)
[csharp-tmLanguage#165](https://github.com/dotnet/csharp-tmLanguage/pull/165)
_(Contributed by [@david-driscoll](https://github.com/david-driscoll))_

Additional C# 8 support (Using Declarations, Static Local Functions, Null-coalescing Assignment)
[csharp-tmLanguage#188](https://github.com/dotnet/csharp-tmLanguage/pull/188)
_(Contributed by [@rchowe](https://github.com/rchowe))_

Add support for Nullable Array types.
[csharp-tmLanguage#175](https://github.com/dotnet/csharp-tmLanguage/pull/175)
_(Contributed by [@GeorchW](https://github.com/GeorchW))_

### CODE REVIEW

**Comment by alexr00** [comment]
@JoeRobich thanks for the PR! I update all the grammars about once per month, and I'm planning on updating on Monday. We are releasing soon, and Monday is after we branch for release. I will look at merging this PR at that time.

**Comment by alexr00** [comment]
Also, if you want me to update a specific to pick up a change earlier than my usual monthly update, then please feel free to open an issue! You are of course welcome to make a PR, but with the grammar updating script we have it is easy for me to do.

**Comment by JoeRobich** [comment]
> You are of course welcome to make a PR, but with the grammar updating script we have it is easy for me to do.

Thanks! I didn't realize this was automated. It had been such a long time since we've taken changes and I saw that Dustin has opened PRs in the past. If it is easier to close this PR and allow it to flow with your scripts, that woudl be fine with me.

**Comment by alexr00** [comment]
Thanks! I have updated all grammars with this change: https://github.com/microsoft/vscode/commit/17e7a257ffc86a48318cefd8f3b904dc546a4314

**Pull request closed without merging**
