### PR TITLE
Fix #64379 - SimpleFindWidget position was changed (in hidden state)

### LINKED ISSUE #64379: Terminal find widget shadow is visible when find widget is hidden
The shadow is visible just under the panel actions

image

### PR DESCRIPTION
**Pull request by marchenko-am**
SimpleFindWidget position was changed (in hidden state) for shadow hiding

### CODE REVIEW

**Comment by marchenko-am** [comment]
There is a box shadow too long. I just changed position for hodden box and problem was solved.

**Review by Tyriar — APPROVED** [review]
Looks good, I'll merge in after we branch off the upcoming release branch.

**Comment by marchenko-am** [comment]
@Tyriar, ok, What do "branch off" mean?

**Comment by Tyriar** [comment]
@marchenko-am the `release/1.30` branch was just created based off master, that's the one that will be released. Now we can merge in stuff for 1.31 🙂

**Pull request merged**
