### PR TITLE
product: add serverDataFolderName to product.json

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

This PR fixes connection with remote server	extension.

There's still an issue with connecting to the extension host with OSS version https://github.com/microsoft/vscode-remote-release/issues/103 .

### CODE REVIEW

**Comment by isidorn** [comment]
This looks like it is not see needed. Though assigning to @roblourens since he is the owner of that issue. Thank you

**Comment by ljmf00** [comment]
> This looks like it is not see needed. Though assigning to @roblourens since he is the owner of that issue. Thank you

Would be great to have a default on vscode remote extension rather than adding this, BUT, it seems to be inside of `product.json` file provided by the production build.

**Comment by roblourens** [comment]
Using the remote server with with OSS is not supported, it should not work even with this change.

**Comment by ljmf00** [comment]
> Using the remote server with with OSS is not supported, it should not work even with this change.

Is there any strong reason why it is not supported? Because, according to vscode official documentation, this shouldn't be dependent of the VS Code build https://code.visualstudio.com/docs/remote/ssh-tutorial and https://code.visualstudio.com/docs/remote/ssh .

**Comment by roblourens** [comment]
I don't think it's spelled out in the docs, but there are non-OSS components that are required to talk to the server.

**Comment by ljmf00** [comment]
> I don't think it's spelled out in the docs, but there are non-OSS components that are required to talk to the server.

So, this implies that I can use this with whatever build of VS Code. Microsoft advertise Visual Studio Code as an open source platform and this type of things make me unable to use it. Would be great to have the possibility to use those components, even though closed source. As an end user, I don't care if my distribution want or not to compile VS Code by themselves because at the end, it's VSCode.

**Comment by roblourens** [comment]
There are some details about the OSS vs official builds here https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code

**Comment by ljmf00** [comment]
> There are some details about the OSS vs official builds here [microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code)

These details are very controversial:

> We take great care to ensure that no proprietary code or assets are accidently contributed to the Code - OSS repo, so that it can be cloned and freely used by anyone in the community.

Freely used by anyone in the community. Do you know the concept of freedom in software? I'm unable to use it. Even if you advertise it's open to the community, according to the license, I'm unable to use the marketplace, I'm unable to use Remote Access features to my own machine. So clearly you don't care and this is not free software.

> While not open source, we believe that transparency is very important to the health of the project and community.

Of course, transparency is very important for you... Do you call wood a transparent material too?

I'm stuck with vscode because clearly vscode took a big step into the software text editors but I'm also stuck with proprietary version because I can't even implement my own remove server without breaking your license.

**Comment by ljmf00** [comment]
> Really, it's not acceptable. It's time for people to put pressure on Microsoft to allow the remote functionality to be available across the board.
> 
> I want to be able to use code from a Chromebook and have the remote coding functionality.

From: https://github.com/VSCodium/vscodium/issues/240#issuecomment-703614305

------

Unacceptable when vscode literally don't care about the community :disappointed: . Maybe @joaomoreno can help us guiding on this topic. There's a lot of people stuck with this!

**Pull request closed without merging**
