### PR TITLE
Fix file relative path link

### LINKED ISSUE #181435: Relative file links in comments do not work anymore
Possible regression of https://github.com/microsoft/vscode/issues/90848 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: Windows 11

Steps to Reproduce:

1. Open any folder with files in it
2. Open any code file that supports comments, preferably
3. Write a link to a relative file like this "file:///./relativeFile.txt"
4. Observe that upon clicking this link VSCode attempts to open the file with wrong/empty path

### PR DESCRIPTION
**Pull request by Sidebail**
Fixes #181435

Previously relative file links were not working properly. 

Now whenever in VS Code editor the file link is formatted in a style like
`file://../folderName/.../fileName.txt`
the code will take the folder of opened file as a starting point, determine where it needs to go, given the names of folders and dots in the file link path and navigate the user to the proper file. Useful!

To test it open any code file and write a link in the format described above in any comment.

### CODE REVIEW

**Comment by Sidebail** [comment]
@microsoft-github-policy-service agree

**Review by steelexia — APPROVED** [review]

**Comment by Sidebail** [comment]
It's been around a week, so, out of curiosity...
Is it blocked for now? Like, I'm seeing "Need PR Community Approvals" and I'm not really getting who should review that change. A collaborator, a microsoft employee? 

It's my first time commiting in this repo, so I'm a bit curious what the process of pull request reviews is. Not to rush anyone, I suspect there are a bunch of other priority tasks lying around, with wich I wish the best of luck ＼(ﾟｰﾟ＼) @alexdima

**Comment by Challanger524** [comment]
Hooow looong we need to wait? This is so ridiculous 😕

**Review by alexdima — APPROVED** [review]
Thank you!

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
