### PR TITLE
hover info should not be broken within word

### LINKED ISSUE #105630: TypeScript QuickInfo should not wrap in the middle of an operator
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

image

Breadcrumb for myself, in case a repro is required: I was reducing material-ui for abug.

### PR DESCRIPTION
**Pull request by Zuckjet**
Fix #105630

### CODE REVIEW

**Comment by Zuckjet** [comment]
CI error " ##[error]PowerShell exited with code '1' " seems is not relevant my changes

**Comment by alexdima** [comment]
I did a quick blame on the CSS and it looks like it was introduced via https://github.com/microsoft/vscode/pull/74582

**Comment by rheh** [comment]
The PR reserves the fix that rectified issue https://github.com/microsoft/vscode/issues/74579 so does that need reopening/addressing?  Is there a solution to fix both?

**Comment by Zuckjet** [comment]
> The PR reserves the fix that rectified issue https://github.com/microsoft/vscode/issues/74579 so does that need reopening/addressing?  Is there a solution to fix both?

the issue you posted is about adding word-wrap:break-word CSS property, but this PR is about removing word-break:break-word CSS property. I think they can work together.

**Review by rheh — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks. Let's see how this goes in insiders

**Pull request merged**
