### PR TITLE
Adopt icon font in notifications

### PR DESCRIPTION
**Pull request by miguelsolorio**
Related #78889

This adopts the icon font in the notifications area (should look identical to current):

image

I also created the following colors:
- `iconRed.foreground` for the Error icon
- `iconYellow.foreground` for the Warning icon
- `iconBlue.foreground` for the Info icon

These will end up being re-used by other icons so I tried to give them generic names that can apply to more than one icon. Once you modify the colors you can see this in action:

image

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
Generally looks ok to me. The new colors need individual descriptions.

I am not 100% sure about introducing a color key per icon color. Adding @aeschli for input. I wonder if it would not be better to have icon colors per icon that is different from the default, e.g. `iconError.foreground`, `iconDebugStop.foreground`.

**Comment by misolori** [comment]
We have quite a number of icons that re-use the same colors:

image

My preference is to keep the naming convention simple and then assign those color tokens to specific icons (like terminal colors):

image

- `icon.default`
- `icon.red`
- `icon.redBright`
- `icon.blue`
- `icon.blueBright`
- `icon.green`
- `icon.greenBright`
...

then in `style.ts`:
```ts
	const iconRedColor = theme.getColor(iconForeground);
	if (iconRedColor) {
		collector.addRule(`
			.monaco-workbench .codicon-error,
			.monaco-workbench .codicon-debug-stop,
			.monaco-workbench .codicon-debug-disconnect {
				color: ${iconForegroundColor
			}; 
		}`);
	}
```

**Comment by bpasero** [comment]
@misolori ah, I was not aware we had this concept already for terminal colors. I guess that makes it easier to go for your suggested solution.

**Comment by aeschli** [comment]
I agree with Ben's first comment. The colors should have specific names: specific to where are they used, and what they are for: `notificationsErrorIcon.foreground', ...

The notification color must go well together with all the other `notifications` colors, especially the `notifications.background` color. Also, a theme could decide to make all warnings green, not yellow. The name of the color therefore can't say 'yellow', but 'warning'.
For the debug icons you want to use `debugToolBaXYIcon.foreground'...

The terminal colors you mention are because of the spec'ed set of [ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) that can occur in terminal output. So it's not really different there. The color names describe a concept.

**Comment by misolori** [comment]
I've updated the naming convention so it follows as we discussed:

- `notificationErrorIcon.foreground`
- `notificationWarningIcon.foreground`
- `notificationInfo.foreground`

I also scoped the icon colors so they only apply to the notification area and not in others (notice info icon in the editor action bar doesn't get the color changes):

image

**Review by bpasero — CHANGES_REQUESTED** [review]
@misolori I feel the theming participant for updating the notification icon should live inside `src/vs/workbench/browser/parts/notifications/notificationsList.ts` and not outside because it is about notification icons and nothing else.

Similar, please move the color definitions into the workbench into `src/vs/workbench/common/theme.ts`, e.g. below:

https://github.com/microsoft/vscode/blob/8b6e0efc0a98639085fabeb5226a516785424796/src/vs/workbench/common/theme.ts#L512

**Comment by misolori** [comment]
Moved the theming participant to `src/vs/workbench/browser/parts/notifications/notificationsList.ts` and color definitions to `src/vs/workbench/common/theme.ts`

Merging this in and will queue up a build to verify.

**Pull request merged**
