### PR TITLE
Adds a new explorerViewer sort order configuration item, barrelFirst

### PR DESCRIPTION
**Pull request by AmbrosiaDevelopments**
This setting sorts barrel files (index.js, index.ts, etc.) in alphabetical order above all other files. Folders remain above all files including barrel files.

Partially addresses #27286 (still open but not specifically calling for this) and [a comment requesting this feature](https://github.com/microsoft/vscode/issues/12345#issuecomment-249316536) on a now closed issue, #12345.

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for this PR. However it is usually great to first start a discussion before imlpementing the whole PR.
We will not accept this since this is very javascript specific and not a lot of users requested for this.
Leaving this open as we might change our mind in the future. Thanks

**Comment by SimonDever** [comment]
That's fair enough. It doesn't specifically look at file extensions like `.ts` or `.js`, just any file starting with `index`. Would you be able to advise if this functionality (changing file explorer sort order) is possible from an extension? I have looked for how to achieve it but found nothing at all so far about changing file explorer like that.

**Comment by isidorn** [comment]
Unfortunetely this is not possible using an extension. And that is one of the reason why I will keep this PR open for now, since there is no other way to achieve this.

**Comment by isidorn** [comment]
Clossing as out of scope.
Thank you again for your PR.

**Comment by SimonDever** [comment]
Is there another way to achieve this yet? Is there a plan to open up API to allow this or anything further?

**Comment by isidorn** [comment]
There is currently no way to achieve this. We do not plan to open up the API.
There is this feature request which you can comment on and upvote https://github.com/microsoft/vscode/issues/27286

**Comment by AlanLeeMoven** [comment]
Recommend changing 'barrel' to 'index' in every use across this PR to make the name more intuitive and specific. Hoping this gets resolved some day...

**Pull request closed without merging**
