### PR TITLE
Pass one shared `macros` object into every call to katex renderer

### LINKED ISSUE #125425: Using VSCode insiders: Jupyter Notebook Markdown Cell does not support  \newcommand in Katex.
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.898847129
-   Python Extension version (available under the Extensions sidebar): v2021.6.864643163-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur 11.4
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

I started using VSCode-insiders recently and loved the way new jupyter UI looks. But I noticed that two of the features that I used to use, does not work.

1. Global CSS for Markdown cells.
2. \newcommand in Katex

## With VSCode

I usually add the common CSS and latex/katex newcommands on the the first markdown cell:

Screenshot 2021-06-03 at 10 10 24 AM

Then in any markdown cell, I am able to use those:

Screenshot 2021-06-03 at 10 11 16 AM

**Here is the output:**

Screenshot 2021-06-03 at 10 10 49 AM

## With Insiders:

None of the above features work with VS Code Insiders:

Screenshot 2021-06-03 at 10 13 36 AM

**Note 1:** The CSS works if it is in the same cell. But that means I have to repeat all the needed CSS in each cell. \newcommand does not even work when defined in same cell.

**Note 2:** I found an issue which has some different problems with Insiders: https://github.com/microsoft/vscode-jupyter/issues/6045.

### PR DESCRIPTION
**Pull request by AlbertHilb**
This PR fixes #125425

In order to make macros defined by the author persistent between KaTeX elements, we need to pass one shared `macros` object into every call to the renderer. KaTeX will insert macros into that object and since it continues to exist between calls, macros will persist. See [KaTeX docs][docs].

immagine

[docs]: https://katex.org/docs/api.html#persistent-macros

### CODE REVIEW

**Comment by Walker-Xin** [comment]
The issue of katex macros not persisting across math expressions also occurs in Jupyter notebook environment of VSC. Would this  PR also resolve the macro issue for Jupyter notebooks?

**Comment by AlbertHilb** [comment]
Yes, this PR also solves the issue for notebooks.

screen

**Comment by mjbvz** [comment]
What if you delete a previously declared macro? With this approach won't it (incorrectly) still be defined?

**Comment by AlbertHilb** [comment]
Yes, Indeed. That behavior is certainly incorrect for the markdown file preview. The new version of the patch solves the issue resetting the `macros` object on the start of each new re-rendering.

screen

This approach does not work for notebooks since each markdown cell is a *standalone* markdown document.

However, in this case, I'm not sure the actual behavior is an issue and needs to be corrected. In some sense, it seems to match the way the notebook works. Code cells act similarly. If you set a variable in a cell, execute the cell and then remove it, the variable is still accessible in the rest of the notebook.

Maybe we can add a command to reset the markdown engine just like the command to reload the kernel. What do you think?

**Comment by mjbvz** [comment]
Thanks. The new behavior sounds reasonable enough for notebooks too so we can merge as-is and wait for feedback

**Comment by chandresh** [comment]
@AlbertHilb I tested this and the issue (https://github.com/microsoft/vscode/issues/125425) that  I reported related to markdown /necommand in Jypitor notebooks is working fine with your fix. Thanks!

**Pull request merged**
