### PR TITLE
Add option for always visible action buttons in side panels. 

### LINKED ISSUE #37714: Turn off hiding of tree view buttons
When a tree view has some extra buttons (e.g., new file in explorer), they only appear when hovering, or focusing the tree view.

Could an option be added to not hide them? Hiding them does not return any space to the user, it simply makes the display a bit cleaner.

It took me ages to work out where I had once seen the git refresh button in the insiders build because with multiple source control providers another tree view is shown, which means the buttons which are normally on the source control titlebar are now hidden.

Personnally I think it is unfriendly UI design to make the user have to move their mouse around in order to find buttons.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #37714 by adding a settings config option to keep side menu title bar action buttons visible whenever their panel is expanded.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Touches many files because I needed to inject an `IConfigurationService` into `ViewletPanel`. Not sure if there is a way to do this other than passing the service up from all subclasses and letting the base `instantiationService.createInstance()` handle instantiating the config service.

**Comment by JacksonKearl** [comment]
I am not sure why these changes would cause this test:
```
test('getUntitledWorkspaceSync', done => {
	let untitled = service.getUntitledWorkspacesSync();
	assert.equal(0, untitled.length);

	return createWorkspace([process.cwd(), os.tmpdir()]).then(untitledOne => {
		untitled = service.getUntitledWorkspacesSync();

		assert.equal(1, untitled.length);
		assert.equal(untitledOne.id, untitled[0].id);

		return createWorkspace([os.tmpdir(), process.cwd()]).then(untitledTwo => {
			untitled = service.getUntitledWorkspacesSync();

			assert.equal(2, untitled.length); // here

			service.deleteUntitledWorkspaceSync(untitledOne);
			untitled = service.getUntitledWorkspacesSync();
			assert.equal(1, untitled.length);

			service.deleteUntitledWorkspaceSync(untitledTwo);
			untitled = service.getUntitledWorkspacesSync();
			assert.equal(0, untitled.length);

			done();
		});
	});
});
```
to fail with `untitled.length` being 1 instead of 2 at the marked location, on AppVeyor. Could someone with more knowledge of the ecosystem possibly take a look? Locally (macOS) the tests all pass except 
```
FileSearchEngine Files: *.* exclude with unicode:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```
which also fails for me on master.

**Comment by JacksonKearl** [comment]
Added some comments and now it works. Is the build server known to be a bit temperamental?

**Comment by joaomoreno** [comment]
@JacksonKearl Great job. Yeah, unfortunately there's no way to get around touching all those subclasses. I took care of the merge conflicts and did minor refactoring in the PanelViewlet. Thanks! 🍻

**Comment by joaomoreno** [comment]
Renamed setting to `workbench.view.alwaysShowHeaderActions`. https://github.com/Microsoft/vscode/issues/44044

**Pull request merged**
