### PR TITLE
Add setting to toggle new octicon style

### PR DESCRIPTION
**Pull request by miguelsolorio**
This is to begin the work of #76909 where we need to update Octicons to match our new icon style. I've introduced a new hidden setting, `workbench.octiconsUpdate.enabled`, that when set to `true` will enable the new version. This will allow us to better selfhost and test changes. Once the team feels confident about the new icons we can remove this and make it the default.

image

To test the Octicons, you can use [this extension that I created](https://github.com/microsoft/vscode/files/3506371/octicon-test-0.0.1.vsix.zip) that toggles all of the icon options in the status bar (make sure you have a file open and a wide width for them to show up).

Once this is merged in we'll ask the team to selfhost and create issues for icon changes/modifications. A good portion of these are from our existing icon library. I also increased the icon font to 16px in the status bar (from 14px) since these icons are smaller.

I'll be out next week so there's a good chance this will carry over into the next milestone.

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

**Comment by bpasero** [comment]
Not sure if you want feedback already, but as I mentioned earlier, the new icons do not work for me in the status bar.

Old:
image

New:
image

With Bold:
image

This feedback is not around the shape of the icon but the fact that our current octicons all have a solid background applied which puts a very nice contrast on top of the status bar. With the new transparent icons we are loosing this contrast.

**Comment by misolori** [comment]
Ok, I'll merge this and will create an issue to track that. Not sure what else we can besides create another solid version but that doubles the work. Let's see what others think, should we turn this on as a default for a week and then turn off before endgame?

**Comment by bpasero** [comment]
@misolori 

> should we turn this on as a default for a week and then turn off before endgame?

Yes, to get most feedback that makes sense.

**Comment by bpasero** [comment]
> Not sure what else we can besides create another solid version but that doubles the work

Can we play with CSS to get there maybe?

**Comment by misolori** [comment]
> Can we play with CSS to get there maybe?

Yea, I'll play around with the weights to see if there's a way to achieve more contrast.

**Pull request merged**
