### PR TITLE
Fix webview focus steal that occurs when the application is re-focused

### LINKED ISSUE #61489: Webviews take focus when vs code is refocused
Issue Type: <b>Bug</b>

Menu sometimes won't open when vscode isn't focused. (It immediately closes.)

1. Open release notes
2. Focus another application
3. Click an item in the menu bar

vscode-menu

VS Code version: Code - Insiders 1.29.0-insider (4d9f1d23a556dccd2c0fd5203923a24b21e41209, 2018-10-22T05:18:34.128Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

### PR DESCRIPTION
**Pull request by Linskeyd**
This PR fixes #61489

Prior to this change, webviews could steal focus when the application window itself has been re-focused (as long as a webview was the last active editor element).  As called out in #61489, even if something like the output panel or terminal was last focused, performing an alt+tab to switch between application windows and then back again would cause the webview to steal focus from other parts of the application.

After this change, we webviews only take focus back on application window refocus when they were actually last focused in the application window (when compared to the output panel, file explorer, or other editor layout parts).  Tested locally on Mac.

IWorkbenchLayoutService seemed like the right thing to pull in to assert whether or not the last focused part of the application was indeed an editor (so that focus does not travel across layout parts).  However, if there is better service or dependency to pull in here to check this condition, then I'd be happy to move to it :).

Thanks!

### CODE REVIEW

**Comment by Linskeyd** [comment]
@mjbvz  -> it looks like the VS Code CI failure was only on windows, and seems unrelated to my change.  Known issue?

**Comment by mjbvz** [comment]
Thanks @Linskeyd! It's a bit too late in our development cycle to include this in the May release, but I'll take a look for the June release

**Comment by lwb4** [comment]
It's now mid-July, any idea if/when this will be included in a release?

**Comment by mjbvz** [comment]
Thanks! Merging this. It will be in the  next VS Code insiders build

**Pull request merged**
