### PR TITLE
PHP Snippets Quality of Life and Continuity

### PR DESCRIPTION
**Pull request by soulshined**
Qualify of Life 
- Updated all snippets to be consistent with documentation snippets
  - No snippets have docs in them unless they are prefixed with `doc_` 
- Updated the class snippet to default to the current file's base name instead of 'ClassName'
- Add an additional tab stop to functions for chaining args/params
- Remove kvps from array since arrays can be associative or just values
  - Instead, users can chain snippet after snippet by way of the `keyval` snippet if it's an associative array
- Changed verbiage of `doc_param` to more accurately describe it's intent
  
<details>
<summary>New Snippets</summary>

- `try_finally`    
  tryfinally

- `param`
Used to chain params for any function

  param

- functions
  - `fun`
  Users should use `param` to chain parameters
  fun
      
  - `fun_anonymous`
  fun2

  - `fun_arrow`
  fun3

- `constructor_promotion`
  Users can use `property_promoted` to chain promotion properties in a constructor
  promoted

  promoted2

- `spaceship`
  spaceship
- `property`
  property
- goto
- const
  const

- namespace
  - `use_as`
  - `use_group`
  - `use_fun`
  - `use_const`

- `match` [ref](https://www.php.net/manual/en/control-structures.match.php)
  match

- Attributes [ref](https://www.php.net/manual/en/language.attributes.overview.php)
  - `attr`
    attr2
  - `attr_with_target`
     attr3
  - `attr_target`
     attr
  
- Enum [ref](https://www.php.net/manual/en/language.enumerations.php)
  - `enum`
    enum
  - `enum_backed`
    backed
  - `foreach_enum`  
  foreachenum

- Dynamic Properties Class
  dynamic

</details>

### CODE REVIEW

**Comment by soulshined** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by soulshined** [comment]
My fork was out of sync. I have synced the fork and merged vscode/main into my branch

**Comment by roblourens** [comment]
This seems like a lot of work. In the future, you might want to open an issue so that we can have a discussion about what you want to add before you do a lot of work to write the code. I'm not sure I want to merge this. Some of these snippets are really detailed and specific. I think it's nice for us to offer basic snippets for the most common scenarios out of the box, but I think that most of these would be better suited for a php snippet extension. Have you considered that?

**Comment by soulshined** [comment]
> This seems like a lot of work. In the future, you might want to open an issue so that we can have a discussion about what you want to add before you do a lot of work to write the code. I'm not sure I want to merge this. Some of these snippets are really detailed and specific. I think it's nice for us to offer basic snippets for the most common scenarios out of the box, but I think that most of these would be better suited for a php snippet extension. Have you considered that?

Unfortunately, when I rebased I lost the commit messages, but in short, there is nothing really specific to 'me' or my needs here. I'm all for taking whatever offenders you think out, but the goal with this PR is to align PHP snippets with PHP 8 features. < PHP 8 is reaching end of life and there are no snippets to bridge the gap out-of-box. This also makes the PHP doc strategy consistent, some snippets had a prefix some others didn't. I'm willing to filter and adjust if you can point to some ones that may not be suitable for the community at large, I'm not married to these by any means so if you have feedback, I'd consider this discussion just as valuable. But at minimum, there should be some PHP 8 support out-of-box imo. 

I think for starters, the heredoc and nowdoc and super global snippets are necessary. I'm okay with removing those personally. Everything else was updated for the purposes to be used across all versions of PHP *agnostically*. For example, the parameter snippets are way out of date, because we have type hints now and we have promoted parameters. Classes also need to be updated because not every class needs a constructor signature and so forth. I think if anything I'm removing a lot of the 'explicit' use cases of these snippets,

If by extension, you mean me create one, sure I could, but I don't see the difference in creating one and adding it here; at a high level anyways. Again, open to suggestions, I know you have a lot of users to think about and that's fair

**Comment by roblourens** [comment]
Sorry for the slow response. I think that for our builtin snippets, we want to stick to snippets that just cover the most common usages of general language constructs. We don't want to try to be exhaustive for every possible for- eg we'll take a `try/catch` snippet but I don't think we also need a `try/catch/finally` snippet built-in. And we don't want snippets that cover sort of opinionated workflows- I think the `echo $this->…` snippet feels that way to me. The snippets for global variables like `$_COOKIE` or the array initializers also feel that way to me- they are probably helpful for a php snippet poweruser but I don't think they need to be built in.

If you can do a pass to remove snippets that might fit that description then I will take another look. The other snippets can go in a user's snippets files or a snippets extension.

**Comment by roblourens** [comment]
Do you plan to work on this more @soulshined?

**Comment by soulshined** [comment]
Oops. sorry @roblourens I missed the last email notification about it. I will adjust based on your feedback! I should have time tomorrow or wednesday evening

**Review by roblourens — APPROVED** [review]
Thanks. I trimmed the snippets a bit more, just removing ones that I feel don't add much or are a variation of another snippet.

**Review by Tyriar — APPROVED** [review]

**Comment by soulshined** [comment]
@roblourens no issues here; just a fair warning you removed a majority of existing ones prior to my changes (ultimately like you said, people will have to add to their personal snippets as they see fit anyways) but I think at minimum we need to add back the throws exception snippet and the 2 constructors. Here's the file prior to my changes: https://github.com/soulshined/vscode/blob/d5e12a12ddcdbffa565ea36aec17d94df7c9f3d9/extensions/php/snippets/php.code-snippets

Additionally, some 'variations' come at a cost. the class snippet that existed prior to mine never accounted for promotion style constructors or chaining parameters etc. I'll leave that up to you to decide. I'm not married to anything just adding color that the old php syntax is far from php 8 snytax (yet the new 'variants' are backwards compatible, err i tried my best to be)

**Comment by roblourens** [comment]
Oops, I meant to check for that, I will at least add back the ones that were previously existing. Thanks. I will put back one constructor snippet. I think having both is just a level of detail that we don't need built in but would make sense in an extension for snippet power users.

**Pull request merged**
