### PR TITLE
Highlight fenced code in markdown

### LINKED ISSUE #155056: Markdown fenced blocks should be highlighted in a similar way to single line code blocks
When highlighting code inside markdown, single line code blocks are highlighted, but fenced blocks are not, unless they are a supported language, in which case only the contents are highlighted, which is inconsistent with single line blocks where the backticks are highlighted too:

image

For a more consistent view, I think the triple backticks should always be highlighted, and if no language is provided then the contents should also be highlighted, eg:

image

### PR DESCRIPTION
**Pull request by a-stewart**
This PR fixes #155056

Before/After

Light:
image  image

Dark:
image   image

### CODE REVIEW

**Review by mjbvz — CHANGES_REQUESTED** [review]
Change LGTM but the colorizer tests are failing. Can you please take a look at those

**Comment by a-stewart** [comment]
> Change LGTM but the colorizer tests are failing. Can you please take a look at those.

Shall do, I tried editing the file, but then running the tests seemed to just revert my changes - is there any documentation for these tests?

**Comment by mjbvz** [comment]
I fixed the tests. The key was running `./scripts/test-integration.sh`  to generate the new pinning tests

After testing this out though, I think this needs more thought. Having entire code blocks be marked in red (with default light/dark) makes it feel like something is wrong. This is something a third party theme extension could opt-into but too drastic of a change for the builtin themes 

I'm closing this as an extension candidate instead. I do think we could make these fenced code blocks more obvious but I would try to either:

- Just modify the backticks instead of the text content
- If you do modify the text, go with a more subtle change

**Comment by a-stewart** [comment]
Sorry for not replying, I was on vacation.

I think if we modify the text, it should be to make it the same as single line - I don't think another style make sense, so if we just change the backticks it just looks like this:

image

image

Here it is with some more content around it:

image

Personally, I prefer it with the full block highlighted, but I understand that that is quite a significant change. I think colouring just the backticks and language identifier is a useful change though, and it is not too drastic. 

I'll push a new commit once I get the `./scripts/test-integration.sh` to work.

**Pull request closed without merging**
