### PR TITLE
Remove VSash

### PR DESCRIPTION
**Pull request by joaomoreno**
The `VSash`'s only purpose was to keep proportions on layout, which the Splitview does by default. This PR removes `VSash` and adopts the Splitview in the two places.

@sandy081 Please review. The side-by-side comparison editor is currently broken in `master`, @bpasero is fixing it. Once he does, we can merge master here and you can give it a try.

### CODE REVIEW

**Comment by bpasero** [comment]
@joaomoreno @sandy081 pushed a fix (via https://github.com/Microsoft/vscode/commit/98d7de04d65bdaf67bb51ccd10dc1c9f7cb461ea)

**Comment by sandy081** [comment]
@joaomoreno In Settings editor, Right hand side editor is not taking the complete width

image

**Comment by joaomoreno** [comment]
@sandy081 Give it another go.

**Comment by sandy081** [comment]
@joaomoreno Only thing missing is reset on double click. Otherwise LGTM

**Review by sandy081 — APPROVED** [review]

**Comment by joaomoreno** [comment]
@sandy081 Great catch!

**Pull request merged**
