### PR TITLE
Expand monarch functionality to allow state access within rules

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
I think monarch is not powerful enough to tokenize constructs such as C++ raw string literals in the general case. This is an attempt to expand monarch functionality so it can.

Monaco tokenization of C++ raw strings is broken when the d-char-sequence  contains double quotes https://github.com/microsoft/monaco-editor/issues/3128

image

This is because  https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/cpp/cpp.ts looks for the end of a raw string literal by searching for `/(.*)(\))(?:([^ ()\\\t"]*))(\")/` and then checks `$3==$S2` to see if the end has in fact been found, but only compares what is between a closing parenthesis and the first double quote.

As far as I can tell, there is no way to solve this currently in monarch, without doing something hacky like hard-coding for all d-char-sequences of 16 or fewer characters, for example (the C++ standard does specify this limit). Maybe there is a way that I haven't thought of, in which case this PR isn't needed. Most languages do not seem to place such limitations on the delimiter sequences, e.g. PHP and C#. Rust tokenization can be improved as well with the tools provided by the PR.

---

This PR expands monarch functionality by allowing `$S2` to be used within rule regexes, so the fix for https://github.com/microsoft/monaco-editor/issues/3128 can be something along the lines of

```diff
        root: [
            // C++ 11 Raw String
            [/@encoding?R\"(?:([^ ()\\\t]*))\(/, { token: 'string.raw.begin', next: '@raw.$1' }],
            ...
        ],
        raw: [
+           [/.*\)$S2\"/, 'string.raw', '@pop']
-           [
-               /(.*)(\))(?:([^ ()\\\t"]*))(\")/,
-               {
-                   cases: {
-                       '$3==$S2': [
-                           'string.raw',
-                           'string.raw.end',
-                           'string.raw.end',
-                           { token: 'string.raw.end', next: '@pop' }
-                       ],
-                       '@default': ['string.raw', 'string.raw', 'string.raw', 'string.raw']
-                   }
-               }
-           ],
            [/.*/, 'string.raw']
        ],
```

I have not fully tested this PR yet.

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
@microsoft-github-policy-service agree

**Comment by jeremy-rifkin** [comment]
The automated test cases and unit tests pass. I could use some guidance on how to test the changes in conjunction with monaco / a test monarch grammar.

**Comment by jeremy-rifkin** [comment]
I've learned that the C++ standard does place a length limit on raw string delimiter sequences so hardcoding handling would be possible, though very ugly. I think this addition to monarch would still be good, and would also allow support for similar structures in other languages such as PHP heredocs (which I don't think are limited).

**Review by alexdima — APPROVED** [review]
Thank you!

**Review by bpasero — APPROVED** [review]

**Pull request merged**
