### PR TITLE
Return whether git.checkout succeeded

### LINKED ISSUE #346: Exit review mode -> close branch picker -> trapped
- Check out PR
- Check out a second PR
- Click Exit Review Mode
- Get branch quickpick, press esc
- Now "Exit Review Mode" is grayed out and I can't exit review mode

### PR DESCRIPTION
**Pull request by RMacfarlane**
This would help fix https://github.com/Microsoft/vscode-pull-request-github/issues/346 - in an extension I want to be able to distinguish whether the checkout command ran to completion, or if the user quit while the quick picker was open

### CODE REVIEW

**Comment by joaomoreno** [comment]
@RMacfarlane How about this instead? https://github.com/Microsoft/vscode/commit/a488569052c62a30a9b726fb2fdc1fa199f6d9af

**Comment by RMacfarlane** [comment]
sure that works

**Comment by joaomoreno** [comment]
D'oh! :man_facepalming: 

Reverting my commit, merging this.

**Comment by joaomoreno** [comment]
Double d'oh! :man_facepalming: You already resolved conflicts! :laughing:

**Pull request merged**
