### PR TITLE
Remove shell decoration icon settings

### LINKED ISSUE #156503: Terminal decoration icon configuration doesn't go well with icon theming
image

The settings to select an codicon for a decoration are not playing well with our product icon theming approach. 

We want that a product icon theme can style all icons of our UI with a new icons. Each icon that we show should be defined with a component specific name
E.g. `terminal-decoration-icon`,  `terminal-decoration-error-icon`, ...
That way the theme can come up with a custom icon for each icon location

The base icon names (`circle-outline`, `primitive-dot`, ...) should not be used directly, only as defaults, otherwise it gets complicated for a theme to change an icon as it affects many places, unknown to the theme. What might look good with our codicon based product icon theme, might look wrong with a theme that uses a different visual for `primitive-dot`

I suggest to remove the settings as we don't do that at other places. Instead we should refer to product icon themes as the way to change icons.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #156503

### CODE REVIEW

**Comment by Tyriar** [comment]
Need to fix the tests

**Review by meganrogge — APPROVED** [review]

**Comment by aeschli** [comment]
I created https://github.com/microsoft/vscode/pull/159066 to avoid the direct usage of Codicon.

**Comment by aeschli** [comment]
@Tyriar I believe `_showChangeIconQuickPick` is now dead code after your changes. Removing it would remove the last references to `Codicon` (happy to add that to https://github.com/microsoft/vscode/pull/159066)

**Comment by Tyriar** [comment]
@aeschli yep, thanks 👍

**Pull request merged**
