### PR TITLE
Update PHP grammar

### PR DESCRIPTION
**Pull request by bakerkretzmar**
This PR updates the PHP grammars to the latest from the `atom/language-php` repo. All I did was run `node ./build/update-grammar.js` from the `extensions/php` directory, the actual grammar changes are automated. Follow-up to #95029.

See atom/language-php#398 for most of the changes, including PHP 8 updates and a bunch of bug fixes.

### CODE REVIEW

**Comment by KapitanOczywisty** [comment]
Please watch out for any performance problems on bigger files (long strings), I forgot and added `a-z` instead of `a-zA-Z` in few places at the start of the pattern, this caused some issues in the past #75468 . I'll try to fix this upstream, when all php8 changes will be merged (3 PRs are ready).

Changes in general: https://github.com/atom/language-php/issues/395 but there are also some fixes.

What is important there are some changes in tokens:
- https://github.com/atom/language-php/issues/398 - function parameters / typehinting
- https://github.com/atom/language-php/issues/405 - *(not merged yet)* attributes

Themes may need to be updated.

**Comment by roblourens** [comment]
Thanks @KapitanOczywisty. Let's just wait for this update.

**Comment by KapitanOczywisty** [comment]
@bakerkretzmar @roblourens I've checked potential `(?i)[a-z...]` issues and I couldn't find any real problems (all `a-z`s are after other characters or in deeper context).

All PHP 8.0 features are implemented now and we're good to update and merge here.

**Comment by bakerkretzmar** [comment]
@KapitanOczywisty @roblourens updated!

**Comment by roblourens** [comment]
The php grammar was updated to latest outside of here, sorry @bakerkretzmar thanks for the PR

**Pull request closed without merging**
