### PR TITLE
Add next/prev conflicts

### LINKED ISSUE #38321: Git: Provide navigation through git merge conflicts
This is not a bug but a feature request.

It will be very nice if VSCode provides an easy way to navigate through conflicts. Something like a button to go to the next conflict. Currently there is hotkey support only, which is nice but having a visual representation will be useful too. 
Something similar to what is possible on git diff right now.

Regars

### PR DESCRIPTION
**Pull request by Kingwl**
This PR fixes #38321  

There's an existed pr https://github.com/microsoft/vscode/pull/47884 but not updated about 2 years

### CODE REVIEW

**Comment by Kingwl** [comment]
Well... Any update?

**Comment by Kingwl** [comment]
u'p

**Comment by Kingwl** [comment]
Well....

**Comment by chrmarti** [comment]
Thanks!

**Pull request merged**
