### PR TITLE
Quit centered layout mode when opening a diff editor. Fix #94574.

### LINKED ISSUE #94574: Centered Layout: use full width when displaying diff editor
Issue Type: <b>Feature Request</b>

* Toggle Centered Layout
* When there is two editor groups, the centered layout is turned off
* When there is only one editor group, the centered layout is activated automatically
* When a diff editor is opened, it's still in centered layout however the width for editor group is too small for two editors side by side, even though they are in the same editor group.

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T22:09:44.908Z)
OS version: Darwin x64 19.2.0

### PR DESCRIPTION
**Pull request by rebornix**
This PR fixes #94574

### CODE REVIEW

**Comment by isidorn** [comment]
@rebornix thanks a lot for this PR. It is good work. However I see some unrelated changes in the `findController` and `findWidget`, are those included by accident?

**Comment by rebornix** [comment]
@isidorn oops, I pushed to the wrong branch. I'll remove the find related code and then merge.

**Comment by robertrossmann** [comment]
Having the diff editor exit centered mode was a good idea, although I would have preferred it only did so in side-by-side diff view mode. When I open the inline diff which would fit into a single tab group it feels weird to see it suddenly span the whole editor width.

Just a quick feedback. 👍 Or... is that a bug? 🤔

**Comment by isidorn** [comment]
@robertrossmann makes sense. Yeah please file a bug and we might get @rebornix to look into it :)

**Comment by rebornix** [comment]
It's a bug or polish item (as I'm aware of it ;) ), feel free to file an issue.

**Pull request merged**
