### PR TITLE
Show cursor in diff review

### LINKED ISSUE #93498: Better diff review keyboard navigation
Diff review is used when the changes view is opened and diffs are navigated via `F7` and `shift + F7`.

As reported by @jvesouza  It seems that I can only navigate the content using the up and down arrow. It would be interesting if we could use left and right, home and end in addition to ctrl + home and ctrl + end.

Code pointer for a potential pull request 
https://github.com/microsoft/vscode/blob/51c5f904990a651cc859014971f29ecbb214ed84/src/vs/editor/browser/widget/diffReview.ts#L137

### PR DESCRIPTION
**Pull request by ChrisPapp**
Users can now navigate and select text in diff review

@isidorn 
This PR fixes #93498

The user should now be free to navigate through the diff with the keyboard. Despite using 'contentEditable' divs the user should not be able to alter the content.
I have some test cases in mind. I would be willing to create some tests if you gave me a code pointer.

### CODE REVIEW

**Comment by isidorn** [comment]
@ChrisPapp thank you for your PR. While this might be a good apprach I have tried it out and hit following issues:
* Trying to map all the keybindings is not a good appraoch since it is very easy to miss something. So for example on my mac alt + left / right navigation does not work. A better approach would be just to make the editor `readonly`
* When I navigate on a new line the screen reader first reads the line number duplicated. Based on user feedback line number should be read at the end of each line
* When I click on the editor an ugly focus horizontal line is rendered
* AriaLabel of initla line is not read ut

So this is definetly not that polished, it might be a good approach, but I suggest that you install a screen reader. Check the current VS Code insiders experience and compare it to what you have.

Thanks a lot!

**Review by isidorn — CHANGES_REQUESTED** [review]
Commented in the PR.

**Comment by ChrisPapp** [comment]
@isidorn 
The Diff Review widget is not an editor, therefore I cannot make it readonly, it is a table with a set of rows with special aria-labels. I mapped every keybinding as a last-ditch effort, since the content should change when, for example, fetching the next diff, but it should not change as a result of user input.
Still, I can easily add the keybindings I missed.

I downloaded NVDA and after testing it a bit, I found out that each 'row' of the table must be focused in order to get NVDA to read the aria-label.
However in order to get the cursor to work properly, the whole 'table' must be focused, so that's why the screen reader does not read the aria-label. Instead it reads the line's text content.

I suggest we have two states. The first state is like before, where the user can move only up and down and listen to the special aria labels, and the second state is the cursor state like the one I commited, where the user can move the cursor, move between words, select text etc, resembling an editor.
> When I navigate on a new line the screen reader first reads the line number duplicated

 Setting the attribute 'aria-hidden' on the line numbers fixes this issue.

**Comment by ChrisPapp** [comment]
Hello @isidorn ,
I uploaded a commit which features the two states I suggest, so you can see it in practice.
Use ctrl+alt+s to change between states.

**Comment by isidorn** [comment]
Thanks for polishing the PR.
I have tried it out and I could not toggle state on my macOS.
Toggling states is something that VIM users are used to and definetly not something which should be the general approach here. Thus I am against this.
Also please note that this milestone I will not have more time to look into this, thus assigning to May and I can continue to look into this then.

**Comment by ChrisPapp** [comment]
> I have tried it out and I could not toggle state on my macOS.

I don't know why this happens. I don't have a Mac to test it.

> Toggling states is something that VIM users are used to and definetly not something which should be the general approach here. Thus I am against this.
Also please note that this milestone I will not have more time to look into this, thus assigning to May and I can continue to look into this then.

In the meantime I can prepare something that works without having to explicitly toggle state. How about using only Ctrl/Cmd + Up/Down to focus next/previous row (and play accessibility messages) and the other keys perform cursor tasks?

**Comment by isidorn** [comment]
Unforutnetly this fall off my radar and is now outdated. Due to that I am closing this as out of scope.

**Pull request closed without merging**
