### PR TITLE
Wait for all installed extensions to be registered before rendering welcome page. 

### LINKED ISSUE #183249: Getting started page awaits a lifecycle phase in `setInput`?
(found this because this actually resulted in a error: https://github.com/microsoft/vscode/issues/183226)

Code is here:

https://github.com/microsoft/vscode/blob/bf9be2c3661005357d27b8099c54ec99e559cf31/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L308

I do not fully understand this, but instead of awaiting the phase in `setInput`, why not await it before opening the welcome page? And why does not wait at all there, what is the reason?

I think this may also be the cause of https://github.com/microsoft/vscode/issues/181660

### PR DESCRIPTION
**Pull request by bhavyaus**
Fixes: https://github.com/microsoft/vscode/issues/183249

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
How do we know that the categories are there in the restored phase, what is the mechanics here that contribute the categories?

**Comment by bhavyaus** [comment]
> How do we know that the categories are there in the restored phase, what is the mechanics here that contribute the categories?

The `buildCategories` populates the `Recents`, `Walkthroughs` and `Featured` extensions contents on the`welcome` page.
The walkthroughs and the step context-keys could be contributed to by installed extensions which on startup aren't initialized till after the `Ready` phase. Additionally, we also have dependencies on the experimentation service and the gallery extension service. 
Previously, featured extensions, walkthroughs and steps would populate after the Welcome page was opened causing flickering. 
I changed it up to wait till all services are ready before rendering the `Welcome` page.

**Comment by bpasero** [comment]
But then wouldn't the better check be to wait for extensions ready via the `whenInstalledExtensionsRegistered`?

**Comment by bhavyaus** [comment]
> But then wouldn't the better check be to wait for extensions ready via the `whenInstalledExtensionsRegistered`?

That works perfectly. Thanks!

**Review by bpasero — APPROVED** [review]

**Pull request merged**
