### PR TITLE
Implements whitespace rendering for "boundary" and "all" modes.

### PR DESCRIPTION
**Pull request by ghost**
Implements #3828 partially, selection rendering is entirely separate from the actual content in the editor. Would be difficult to render whitespace for only what is selected.

Also removed the View->Toggle Render Whitespace button, as it didn't seem like it would fit as it would now not be a toggle. Not sure where it would be suitable to place the new menu options, if they are to be placed at all.

### CODE REVIEW

**Comment by alexandrudima** [comment]
@marktrz :heart: Great job! I'm sorry for the nasty state machine stuff in there, the code used to do both whitespace and indent guides at the same time, in the meantime I moved out how indent guides get rendered and the whitespace rendering got stuck with the state machine stuff.

**Comment by eamodio** [comment]
@alexandrudima can the command that was removed here be brought back? I feel that is it still useful to be able to change the whitespace rendering without editing the configuration. Even if when "toggled" via the UI it just toggled between `all` and  `none` I think it would be valuable -- especially if when executing the command via `executeCommand` you could provide the actual value.

I am also currently relying on being able to alter the whitespace visibility (at least temporarily) in my extension [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

**Comment by bgever** [comment]
To @eamodio's remark, it might be better to have a new `editor.whitespaceRenderingStyle` property, with string values of the styles. Then the existing (previous) boolean toggle can still work, and in the style property you can specify how it should be rendered.

**Comment by alexandrudima** [comment]
Created #12451

**Comment by heyakyra** [comment]
Why is the use case for "boundary" and "selection" stronger than for "trailing"? 

https://github.com/Microsoft/vscode/issues/284
https://github.com/Microsoft/vscode/issues/8991
https://github.com/Microsoft/vscode/issues/17883

**Pull request merged**
