### PR TITLE
Add `PullOptions` to `pull` in git extension API

### PR DESCRIPTION
**Pull request by cdce8p**
For https://github.com/microsoft/vscode-pull-request-github/pull/2731

### CODE REVIEW

**Comment by alexr00** [comment]
@eamodio this seems like a reasonable addition to the git API. What do you think?

**Comment by cdce8p** [comment]
Any updates so far?

**Comment by alexr00** [comment]
@lszomoru this would be nice for GHPRI as it would allow https://github.com/microsoft/vscode-pull-request-github/issues/2030 to be fixed. I suspect it would improve PR checkout perf too.

**Comment by lszomoru** [comment]
Sorry for the delay on this. Will review the PR this milestone.

**Pull request closed without merging**
