### PR TITLE
Adopt `vscode-oniguruma`

### PR DESCRIPTION
**Pull request by alexdima**
All measurements done with the setting:
```
"editor.maxTokenizationLineLength": 200000000
```

### VS Code Desktop
| File | Size | Lines | Before | After | Difference |
|---|---|---|---|---|---|
| [checker.ts](https://github.com/microsoft/TypeScript/blob/c28bd6579d0a03742799d7310a1977843a222750/src/compiler/checker.ts) | 2.2MB | 38127 | 15990 | 5551 | 2.9x faster |
| [sqlite3.c](https://www.sqlite.org/snapshot/sqlite-snapshot-202004061816.tar.gz) | 7.7MB | 228634 | 23241 | 12189 | 1.9x faster |
| [bootstrap.min.css](https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip) | 152.1KB | 7 | 1653 | 6900 | 4.1x slower |
| [cpp.tmLanguage.json](https://github.com/microsoft/vscode/blob/9450b5e5fb04f2a180cfffc4d27f52f972b1f369/extensions/cpp/syntaxes/cpp.tmLanguage.json) | 477KB | 16221 | 416 | 139 | 3x faster |

image

### VS Code Web (Chrome Version 81.0.4044.122)
| File | Size | Lines | Before | After | Difference |
|---|---|---|---|---|---|
| [checker.ts](https://github.com/microsoft/TypeScript/blob/c28bd6579d0a03742799d7310a1977843a222750/src/compiler/checker.ts) | 2.2MB | 38127 | 21255 | 5573 | 3.8x faster |
| [sqlite3.c](https://www.sqlite.org/snapshot/sqlite-snapshot-202004061816.tar.gz) | 7.7MB | 228634 | 35981 | 11196 | 3.2x faster |
| [bootstrap.min.css](https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip) | 152.1KB | 7 | -- | 5100 | -- |
| [cpp.tmLanguage.json](https://github.com/microsoft/vscode/blob/9450b5e5fb04f2a180cfffc4d27f52f972b1f369/extensions/cpp/syntaxes/cpp.tmLanguage.json) | 477KB | 16221 | 261 | 136 | 1.9x faster |

image

### CODE REVIEW

**Comment by slimsag** [comment]
@alexdima are these before/after measurements in milliseconds or something else?

Do you happen to have millisecond measurements, or info on how you measured? Curious how this approach compares to https://github.com/trishume/syntect :)

**Comment by slimsag** [comment]
Also curious if you have any ideas why bootstrap.min.css became 4.1x slower on VS Code Desktop?

**Comment by nojvek** [comment]
Came here from link in release notes. 

I have massive respect for you @alexdima + vscode team's ever prioritization of performance. Really cool that this uses webassembly under the hood. Wow!

**Comment by mt-webdev** [comment]
This is insane! Keep it up!!

**Comment by alexdima** [comment]
@slimsag Yes, the measurements are in millis. I got them by running `F1 > Developer: Force Retokenize` which flushes any cached tokens and synchronously (without yielding) tokenizes the entire file top-bottom. It then prints the time taken to the developer tools... [Normally tokenization runs for some time, then yields to allow the event loop to process events, then tokenizes again, etc].

https://github.com/trishume/syntect looks like a great project. I'm not sure how times can be compared objectively. The current JS TM grammar that VS Code ships with is not written with speed in mind (it is basically the entire TS TM grammar with some minor things removed). Philosophically, it is also written more like a parser, which leads sometimes to some extraordinarily complex regular expressions --  [e.g.](https://github.com/microsoft/vscode/blob/3f4004254bb187932e7d86b6bbf3880d20d10c21/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L490)). Matching such regular expressions is no breeze for any regex engine:

image

Regarding `bootstrap.min.css`, I honestly didn't have a lot of time to dig deep into it, since I was so happy with the wins for the regular files. Minified code is something very specific to the web ecosystem (CSS/JS/HTML), and VS Code often cheats by ignoring such long lines. There is a setting to forcefully enable parsing of those, but that is used rarely in practice, since most folks end up opening a minified file due to a breakpoint or to check something out, and rarely have the intention of really editing the minified code.

**Pull request merged**
