### PR TITLE
Enable git.confirmSync by default (fixes #8655)

### LINKED ISSUE #8655: Git: status bar lacks indication that it will push
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:26:22.011Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Create commit, ready to be pushed
2. Click on Git part of status bar
3. -> Commit is pushed, which is unexpected

### PR DESCRIPTION
**Pull request by chrmarti**

### CODE REVIEW

**Comment by joaomoreno** [comment]
This can't be merged without a "Never show again" warning.

Independently of that, I think we can do much better. A hover tooltip showing what would happen on click would be a much better alternative to this.

**Comment by chrmarti** [comment]
@joaomoreno The confirmation dialog doesn't seem to allow for a third button. The hover might improve things a tiny bit, but it won't fix the issue. A hover is too easy to miss.

**Comment by joaomoreno** [comment]
Let me sketch something up, to show you what I mean.

**Comment by joaomoreno** [comment]
Fixed by 96010725e5b3e3035174b0cfc85898add1d79159

**Pull request closed without merging**
