### PR TITLE
Provide a command to close all unchanged files

### PR DESCRIPTION
**Pull request by soneymathew**
New Feature (#25667) - Support to bulk close Unmodified Files
### Change Summary
- Editor Action Support for Closing Unmodified files in a group from
  1. Explorer Open Editor's context menu 
closeviaexplorercontextmenu

  2. Editor Tab context menu 
closeviaeditortabcontextmenu

  3. Command Palette
closeviacommandpalette

- Test updates
- Interface methods implemented in the affected source and tests 

### Scenarios Handled
   - Action will close only the unmodified files in a targetted group
   - Only the active group with an active editor will be targetted when executed from the Command palette
   - In explorer the group targetted will be of the file on which the context menu is triggered.
   - If the menu is accessed via the context menu from the Editor tab that group will be the target
   - If there are no editors open and the command is invoked from the command palette it is ignored
   - Group is closed if all editors are unmodified
   - Action can be triggered using the keyboard shortcut

Please let me know if some scenario is missed.

### CODE REVIEW

**Comment by soneymathew** [comment]
@bpasero / @kieferrm could you please share some feedback on these changes.
I would appreciate if we can get this merged before it goes way out of sync with the master if the changes are satisfactory.

**Comment by bpasero** [comment]
@soneymathew thanks for your work in this area. However, I am not convinced this command should be part of the core experience. It looks like you are also the author of https://github.com/Microsoft/vscode/issues/25667 which is does not seem to get votes from other users. I would like to keep the context menus as small and concise as possible.

Instead, we encourage people to write extensions so that functionality can be provided from there and installed for users that want this feature. I suggest you give it a try through an extension and report issues for missing API that you find on the way.

**Comment by soneymathew** [comment]
@bpasero I have shared my perspective in the issue,
Looks like the pull request have at least 4 people reacting to it 👍 perhaps they should have voted in the issue instead of the pull request :)

**Comment by bpasero** [comment]
@soneymathew can't this be much simplified without having to introduce new API to stacks model and editor service with all the API we already have? Just change the run method of `CloseUnmodifiedEditorsInGroupAction` to:

```typescript
public run(context?: IEditorContext): TPromise<any> {
	const activeGroup = this.editorGroupService.getStacksModel().activeGroup;
	const groupId = context && context.group ? context.group.id : activeGroup ? activeGroup.id : null;
	if (groupId !== null) {
		const stacks = this.editorGroupService.getStacksModel();
		const group = stacks.getGroup(groupId);

		group.getEditors().filter(e => !e.isDirty()).forEach(e => this.editorService.closeEditor(stacks.positionOfGroup(group), e));

		return TPromise.as(null);
	}

	return TPromise.as(false);
}
```

**Comment by soneymathew** [comment]
Yes you are right, I will update and test, thanks

**Comment by soneymathew** [comment]
@bpasero Thanks for the feedback and the changes feels so much simpler after removing the API changes. Haven't noticed any performance impact after testing with >20 files in each group.

**Comment by soneymathew** [comment]
Also I was wondering if it is a good idea to show this option conditionally to reduce the clutter, or will it be a performance concern ?
This would mean a group with all modified files will not display this option.

`
const hasUnModifiedEditors = this.editorGroupService.getStacksModel().activeGroup
						.getEditors()
						.reduce(function (unModifiedEditors, editor) {
							if (!editor.isDirty()) {
								unModifiedEditors.push(editor);
							}
							return unModifiedEditors;
						}, [])
						.length > 0;
		if (hasUnModifiedEditors) {
			actions.push(this.closeUnmodifiedEditorsInGroupAction);
		}
`

**Comment by bpasero** [comment]
@soneymathew no I think it is fine to show the action always, we typically do not hide actions for discoverability reasons.

**Comment by bpasero** [comment]
LGTM, thanks 👍

**Comment by nikitavoloboev** [comment]
I can't find Close Unmodified action in vs code (running insiders)

image

What am I missing?

**Comment by soneymathew** [comment]
@nikitavoloboev This renamed to Close unsaved as part of
https://github.com/Microsoft/vscode/pull/44269

**Comment by nikitavoloboev** [comment]
image

I don't see it. Running `1.43.0-insider`

**Comment by soneymathew** [comment]
@nikitavoloboev 
The text is updated to be more clear as part of the mentioned PR
Menu option is now
image
image

Commands are renamed to
image

Hope this helps 🙏

**Comment by nikitavoloboev** [comment]
Close Saved Editors in Group closes all tabs. I want as the name of this PR. To close only tabs that are unchanged and leave only tabs that have changes inside them. 

Is this possible as command?

**Comment by soneymathew** [comment]
Can you explain what you mean as unchanged files here?

Are you referring to unsaved files ?
or Are you referring to saved files which are not committed to a git repo?

**Comment by nikitavoloboev** [comment]
Files that have no changes in them. Files that have changes are often marked with circle in VS Code. Like here `magefile.go` is file with changes and LICENSE is not changed.

image

This command if activated would close `LICENSE` tab.

**Comment by soneymathew** [comment]
Then it's working as expected. 
This command closes all files that are not having the circle mark.
Are you expecting the opposite behaviour by any chance?

**Comment by nikitavoloboev** [comment]
Oh right, maybe I did it wrong. Indeed it does. Thanks

**Comment by nikitavoloboev** [comment]
Is there an option to `Close Saved Editors`, not just ones in a group. And if not is it possible to please add it?

Should I open an issue for it?

**Pull request merged**
