### PR TITLE
#54204 Add commands to apply stash

### PR DESCRIPTION
**Pull request by konstantin-mueller**
Adds the "Apply Stash..." and "Apply Latest Stash" commands as suggested in #54204 .

### CODE REVIEW

**Comment by sonicdivx** [comment]
Lot of Gui tools also have "Apply and Drop"  and I know in the case of Smart Git you have "Reapply Index"

Drop is nice to keep things clean. the Reapply Index I personally rarely use so not sure how much value it has.

**Comment by ssotomayor** [comment]
Looks like this was never merged.

**Comment by joaomoreno** [comment]
Thanks! :beers:

**Comment by lvl99** [comment]
> Lot of Gui tools also have "Apply and Drop" and I know in the case of Smart Git you have "Reapply Index"
> 
> Drop is nice to keep things clean. the Reapply Index I personally rarely use so not sure how much value it has.

Using "Pop Stash..." will allow you to select a named stash which will then remove the named stash after it was merged. The difference between "pop" and "apply" is that "Apply Stash..." doesn't remove the stash if people wish to keep an archive of it.

**Pull request merged**
