### PR TITLE
Fix #122741: Change vertical positions of the walkthrough titles and close-icons to center

### LINKED ISSUE #122741: Getting started titles are off-center
image

The title appears to not be centered here

### PR DESCRIPTION
**Pull request by suema0331**
This PR fixes https://github.com/microsoft/vscode/issues/122741
スクリーンショット 2021-05-01 16 11 32
スクリーンショット 2021-05-01 16 22 47

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Thanks! 

Since extensions can contribute to this list and it's not just these specific three items, it'd be better to use a generic selector for the titles rather than the specific three default titles.

**Comment by suema0331** [comment]
@JacksonKearl
Thank you very much for your comment. 

>  it'd be better to use a generic selector for the titles rather than the specific three default title

I changed to a generic selector like below code.
Please let me know if there are any improvements.

```css
.monaco-workbench .part.editor > .content .getting-started-category .codicon::before{
    vertical-align: middle;
}
```

**Comment by JacksonKearl** [comment]
Thanks! I pushed a change to center the text too.

**Comment by suema0331** [comment]
@JacksonKearl 
Thank you so much for fixing the padding of the text.

**Pull request merged**
