### PR TITLE
Enable terminal chat variables by default

### LINKED ISSUE #229855: Enable chat.experimental.variables.terminal by default
Only issue we should fix before this is done are some keybinding problems tracked in https://github.com/microsoft/vscode/issues/229854

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #229855

After https://github.com/microsoft/vscode/pull/231479 I don't think there are any problems with terminal chat variables. We can also consider removing the settings completely?

### CODE REVIEW

**Comment by jrieken** [comment]
> After https://github.com/microsoft/vscode/pull/231479 I don't think there are any problems with terminal chat variables

I don't know. It depends on the extension/participant and whether it handles variables correctly. 

> We can also consider removing the settings completely?

Yes, this was only a guard to make places (notebooks, terminal) not look bad before they have adopted this. I believe notebooks is already done and this PR should now remove this setting

**Comment by Tyriar** [comment]
> I don't know. It depends on the extension/participant and whether it handles variables correctly.

Isn't it only the terminal participant we need to care about it as it's our first party terminal location one?

> I believe notebooks is already done and this PR should now remove this setting

Want me to remove all 3 including the editor one?

https://github.com/microsoft/vscode/blob/6c8fa5593aefac8f42e2e4f48f7b344a588ecb65/src/vs/workbench/contrib/chat/browser/chat.contribution.ts#L138-L152

**Comment by jrieken** [comment]
> Want me to remove all 3 including the editor one?

Yes

> I don't know. It depends on the extension/participant and whether it handles variables correctly.

I guess so

**Comment by Tyriar** [comment]
@meganrogge can you see this one through as I'll be out the rest of the iteration?

**Review by jrieken — APPROVED** [review]

**Review by jrieken — APPROVED** [review]

**Pull request merged**
