### PR TITLE
Add missing padding-bottom for notebook markdown cells

### LINKED ISSUE #122502: Markdown notebook cells don't theme well due to missing bottom padding
- VS Code Version: 1.56.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create new blank notebook
2. In settings.json:
```
    "workbench.colorCustomizations": {
        "editor.background": "#949494",
        "notebook.selectedCellBackground": "#ffffff",
        "notebook.focusedCellBackground": "#ffffff"
    },
```
3. Markdown cells only are missing bottom padding:
image

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by joyceerhl**
This PR fixes https://github.com/microsoft/vscode/issues/122502

Before:
image

After:
image

### CODE REVIEW

**Review by miguelsolorio — APPROVED** [review]
image

LGTM, thanks for the fix!

**Comment by joyceerhl** [comment]
@misolori would you mind approving this workflow please? I'm a first-time contributor so it looks like a maintainer must explicitly approve this workflow 😅 

image

**Comment by misolori** [comment]
Ok, kicked that off (didn't realize I had to do that 😄) so once the checks pass this will auto-merge. Thanks again!

**Comment by joyceerhl** [comment]
Thanks @misolori @rebornix 😊

**Pull request merged**
