### PR TITLE
#1611 Fix TypeScript embedded in HTML syntax highlighting

### PR DESCRIPTION
**Pull request by andy-preston**
1. Start a new .HTML file

2. Embed script with

```HTML
<script type="text/typescript">
addEventListener("load", (event) => {
    const templates = document.getElementsByClassName("image-list");
    const selected = templates[0] as HTMLElement;
    console.log(selected.dataset.tag);
});
</script>
```

3. Semantic Highlighting works - but "normal" syntax highlighting does not.

4. Apply this fix and restart

5. Repeat steps 1 & 2

6. Syntax Highlighting of the embedded script will now work correctly.

### Details of changes

At https://github.com/microsoft/vscode/blob/df7e41cc5ae63ac4f74258ba098deb070acf5ac1/extensions/html/syntaxes/html.tmLanguage.json#L1944C1-L1944C1464

There is a long and complicated (what seems to be a) regular expression with all the text MIME types that the built-in HTML extension treats as javascript. "javascript", "jscript", "ecmascript", "livescript", etc.

So, by changing this line from

```
| jscript\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  | livescript\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  |
```

to

```
| jscript\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  | typescript\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  | livescript\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  |
```

adds "text/typescript" to the MIME types to treat as JavaScript for syntax highlighting purposes.

### CODE REVIEW

**Comment by andy-preston** [comment]
https://github.com/VSCodium/vscodium/issues/1611

**Comment by andy-preston** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree

**Comment by aeschli** [comment]
This html grammar  has been converted from https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist
If you want to provide a fix or improvement, please create a pull request against the original repository
Once accepted there, we are happy to receive an update request.

**Comment by andy-preston** [comment]
The original repository is no longer accepting any changes.

On https://en.wikipedia.org/wiki/TextMate - it says: "In October 2021, the latest/last commit was made to GitHub, though no announcement has been made to the effect that the project has been officially abandoned and its source code is still publicly available."

**Comment by andy-preston** [comment]
> This html grammar has been converted from https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist If you want to provide a fix or improvement, please create a pull request against the original repository Once accepted there, we are happy to receive an update request.

This html grammar has been converted from https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist If you want to provide a fix or improvement, please create a pull request against the original repository Once accepted there, we are happy to receive an update request.

**Comment by andy-preston** [comment]
The original repository is no longer accepting any changes.

On https://en.wikipedia.org/wiki/TextMate - it says: "In October 2021, the latest/last commit was made to GitHub, though no announcement has been made to the effect that the project has been officially abandoned and its source code is still publicly available."

**Comment by aeschli** [comment]
@alexr00 Alex might know more about whether we plan to fork the HTML grammar.

**Comment by aeschli** [comment]
@alexr00 Alex might know more about whether we plan to fork the HTML grammar.

**Pull request closed without merging**
