### PR TITLE
Detect links in the terminal that don't have a path separator

### LINKED ISSUE #101155: ctrl-click in terminal doesn't handle trailing ':' in file:line:col: links
Issue Type: <b>Bug</b>

gcc generates errors in the terminal window that look like this:
```
File.cpp:52:32: error: blah blah blah
```

if you ctrl-click on the `File.cpp` bit in the terminal window, it populates the vscode file search popup with the text `File.cpp:52:32:`, but this yields **no** search results.

however, if you delete the trailing `:` from that text (resulting in `File.cpp:52:32` then the file search popup shows the correct file and hitting &lt;enter&gt; takes you to the correct file/line/column.

Either:
- the terminal window location parsing code should omit the trailing `:`, or
- the file search popup parser should handle the trailing `:`

left-hand meet right-hand.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.2
php-debug|fel|1.13.0
cmake|twx|0.0.17
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4

</details>

### PR DESCRIPTION
**Pull request by SnirBroshi**
This PR fixes #101155

It makes it so that when searching for links in the terminal output, text without any slashes (e.g. `file.cpp` or `file`) is also taken into consideration (this is before filtering files which actually exist).

It also makes it look at whether it has a trailing slash, so that paths like `./README.md/` will not work, intentionally.

It basically changes the regex from:
`(<root> | <path-part>)? (<separator> <path-part>)+`
to
`(<root>? <separator>)? <path-part> (<separator> <path-part>)* <separator>?`

The following are all the possible cases I can think of which should be considered as valid paths, and whether the old and new regexes detect them:
```
                   old  new
~                  [ ]  [ ]
~/file             [x]  [x]
~/dir/file         [x]  [x]
file               [ ]  [x]
dir/file           [x]  [x]
/file              [x]  [x]
/dir/file          [x]  [x]
```
As you can see, this PR allows using just `file` to link to a file at the root of the current workspace.

Note that as mentioned before, paths like these except that end in another slash work by having the line-number regex ignore the slash.
Now the file path regex considers it, so paths to non-directories which end in a slash will not be considered valid links anymore.

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
It's a little hard to tell what the change was because of all the `String.raw` stuff, you can split that out into a separate PR that should be easy to merge if it just ignored `\` (like `@""` in C#) as that would be great to have.

For this change if it matches just `file` then we can't really merge this as it will result in a lot more file checks on disk which can be expensive and slow depending on the backing file system (remote, sshfs, mounted drive, etc.). The current situation since the new links were added is good enough fix for the `file` case where it will not let you search the workspace for it, opening it if there is only a single match.

**Comment by NotWearingPants** [comment]
While your points are valid, I still don't get how you suggest fixing the issue.

Ctrl+clicking on text in the terminal that looks like `file.cpp:1:1: error` (which is generated by gcc) will still not open the file.

I don't think this will cause so much extra filesystem access, because it only checks it if you hover over a line 🤷‍♂️

That said, the alternative solutions I see to the problem are as follows:

1. Changing the regex to only match files without slashes if they are followed by a line number, so that in a line such as `file.cpp:1:1: error` only the file `file.cpp` will be checked, instead of also `error`.
2. Changing the `search in workspace` regex to treat dangling colons as separators, like it treats quotes and commas, except only if they are at the edge ("trimming" colons).

Thoughts?

**Comment by Tyriar** [comment]
> I don't think this will cause so much extra filesystem access, because it only checks it if you hover over a line 🤷‍♂️

Even though it's only on hover now, it would do this for every "word" on the line and the cache is short lived currently as well. For example dragging the mouse over this terminal would result in ~50 fs requests of which could potentially take seconds to complete.

image

Currently I would expect the number to be around 4 (folder name and url).

> Changing the regex to only match files without slashes if they are followed by a line number, so that in a line such as file.cpp:1:1: error only the file file.cpp will be checked, instead of also error.

This is what I was thinking when labelling https://github.com/microsoft/vscode/issues/101155 as `:<line>` at the end of the word is a very good indicator that it's likely a file.

> Changing the search in workspace regex to treat dangling colons as separators, like it treats quotes and commas, except only if they are at the edge ("trimming" colons).

Less of a fan of this approach as currently search in workspace is a very simple fallback, the complexity/edge cases live at in more specific providers.

**Comment by Tyriar** [comment]
Closing as we can't accept this as is due to the amount of file system requests it would make. The word link provider is a good solution for this problem currently.

**Pull request closed without merging**
