### PR TITLE
Added hide management build script on NPM SCRIPTS explorer pattern.

### PR DESCRIPTION
**Pull request by ghost**
Related to #71635

hidemanagescripts

### CODE REVIEW

**Comment by lonix1** [comment]
NOICE! :+1:

**Comment by jaqra** [comment]
@lonix1 thanks

@egamma sir, im ready to do something with that, if i should?

**Comment by egamma** [comment]
@jaqra (sorry overlooked the PR since there was no corresponding issue). Can please provide some more background for this feature. It looks very specific for this particular pattern `/^[#:-]build-/`

**Comment by lonix1** [comment]
@egamma  It's from issue https://github.com/microsoft/vscode/issues/71635

**Comment by egamma** [comment]
@lonix1 thanks for clarifying. 

I've commented on #71635 that this needs to be implemented in a more general way.

I'm closing this PR.

**Pull request closed without merging**
