### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow. You can also get this set up yourself in any additional repositories in this organization by following these [instructions](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning)

### CODE REVIEW

**Comment by joaomoreno** [comment]
Have you found any issues so far in our code base? What specific kind of issues should arise from here? Some examples?

**Comment by jhutchings1** [comment]
@joaomoreno I followed up offline with you in email about my findings. CodeQL is configurable, but our default set of queries is focused on finding the most precise, most severe security vulnerabilities that we can. We've tried to keep the noise way down so that this doesn't disrupt development teams. You can optionally enable more comprehensive queries which range from correctness and maintainability to more speculative security queries with a greater false positive rate.

**Comment by joaomoreno** [comment]
@jhutchings1 Thanks for the follow up, I'll get to it asap, been busy.

**Comment by joaomoreno** [comment]
Thanks, let's take this in!

**Pull request merged**
