### PR TITLE
improve default color support

### PR DESCRIPTION
**Pull request by leaxoy**
The default theme in other language looks a little bad. Such as go, python. So I improve this.
Before[go]
go
After[go]
go

Before[python]
python
After[python]
python

### CODE REVIEW

**Comment by jhasse** [comment]
Unfortunately this messes with the colors of `=`, `+`, ...

See https://github.com/Microsoft/vscode/issues/10411#issuecomment-239831283

**Comment by aeschli** [comment]
'keyword.operator' is used for operands like '+' '&' ... which we don't want to be colored.

**Comment by leaxoy** [comment]
OK! I will change it later

**Comment by aeschli** [comment]
Closing for now. Please reopen once you made the needed changes.

**Comment by jhasse** [comment]
@leaxoy Did you have another look at this?

**Pull request closed without merging**
