### PR TITLE
Update xterm for contrast ratio luminance change

### LINKED ISSUE #149495: Allow terminal minimum contrast ratio setting to change luminance the other way
Current behavior of dark selection on dark text:

image

Repro with these settings:

```json
  "workbench.colorCustomizations": {
    "terminal.selectionBackground": "#010101",
    "terminal.foreground": "#000000",
    "terminal.background": "#eeeeee",
  }
```

Desire is to invert in this case:

image

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #149495

image

### CODE REVIEW

**Comment by daviddossett** [comment]
Thank you for taking this on! Is it possible to adjust the contrast ratio to match the editor for hc themes only? The text still has fairly low contrast.

I haven't looked at what's going on under the hood but my impression is that they should be the same.

CleanShot 2022-05-13 at 13 16 48@2x

CleanShot 2022-05-13 at 13 16 20@2x

**Comment by Tyriar** [comment]
@daviddossett this is by design as the terminal has the feature that lets you configure your contrast ratio, this comes wwith the bonus of retaining the hue (unless it gets inverted).

While doing this I was thinking maybe we should do something like if the user is using a high contrast theme and has not configured  `terminal.integrated.minimumContrastRatio` then set it to 7, that could be confusing and not sure we've set that precedent yet. We could also do an explicit selection foreground color like the editor just for HC too.

**Comment by daviddossett** [comment]
I think either makes sense, with perhaps a slight lean towards just setting the foreground color explitictly for consistency. I don't know if high contrast users will want or even need such fine control over contrast given the treatment of most text/code in those themes. 

Another way of thinking about this would be like we do for preferred themes. Something like:
```
"terminal.integrated.minimumContrastRatio": "4.5",
"terminal.integrated.minimumHighContrastRatio": "7"
```
...which adds complexity but at least removes the need for magic number changes after a theme change.

**Comment by Tyriar** [comment]
@daviddossett yeah I agree, let's track that in https://github.com/microsoft/vscode/issues/149505 and https://github.com/xtermjs/xterm.js/issues/3810

**Review by meganrogge — APPROVED** [review]

**Review by Nikolabenakova90 — CHANGES_REQUESTED** [review]
Trubky

**Comment by jhpratt** [comment]
I presume this PR is why the foreground text color changed in some situations? My terminal uses `#55f` (a pastel blue) as part of the prompt, which has always been black text, but now it's white. I actually find it _harder_ to read.

**Comment by Tyriar** [comment]
@jhpratt while you may find it harder to read it should have a higher contrast ratio using standard relative luminance comparisons (correct me if I'm wrong). If this bothers you I suggest either reducing `terminal.integrated.minimumContrastRatio` a little or setting it to 1.

**Comment by jhpratt** [comment]
Ah, it's configurable? Cool. I'll give that a shot when I'm on my laptop.

And by the way, I have no doubt that the contrast ratio is better. It's just an observation on my end that it doesn't _appear_ better.

**Comment by Tyriar** [comment]
@jhpratt thanks for the feedback, my main point was I think that generally people would have an easier time since we're using contrast ratio.

**Pull request merged**
