### PR TITLE
Update coffeescript.tmLanguage.json, fixing highlighting for embedded js

### PR DESCRIPTION
**Pull request by beeplin**
In coffee-script, `` means not normal strings but embedded js, but it's not correctly highlighted in vscode, like this: 

image

After this fix, it should be like this: 

image

~~Note that in embedded js the symbols like `()[]{}` is green rather than white. This is intentional in order to indicate this is embedded js, not coffee-script.~~

[EDIT] Now in embedded js the symbols like `()[]{}` is white, not green. I found in string mode some feathers like brackets pairing is not avaiable, so it's better to change to normal code mode instead of string mode.

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks for looking into this. However our coffescript grammar comes from this project: https://github.com/atom/language-coffee-script Can you try submitting a PR against that repo first? This allows your fix will be picked up by any editors that consume that shared coffescript grammar

Once the change is in the coffeescript grammar repo, back in VSCode, simply run `npm run update-grammar` in the coffescript extension to pick up latest version of the grammar.

**Comment by beeplin** [comment]
sure

**Comment by beeplin** [comment]
https://github.com/atom/language-coffee-script/pull/121

**Comment by aeschli** [comment]
Closing this request. Waiting for atom/language-coffee-script#121 to be accepted.

**Pull request closed without merging**
