### PR TITLE
Update findWidget.css to resolve node-sass build errors

### PR DESCRIPTION
**Pull request by kamilic**
This PR is a workaround to solve node-sass Incompatible units error.

My project use sass-loader to resolve .css files.
But after importing monaco-editor, node-sass throw me some errors below.

image

After doing some research, i found that node-sass support calc() outputting.
sass/node-sass#2144

In monaco-editor project, it uses Calc().
To browser, Calc() is same to calc(), i think it is ok to change this function to make better support for sass-loader / node-sass.

### CODE REVIEW

**Comment by catskull** [comment]
I just came across this in my own project, using `monaco-editor` package with `monaco-editor-webpack-plugin` and this PR will fix my issue as well.

**Comment by kamilic** [comment]
@rebornix friendly ping.

**Comment by remcohaszing** [comment]
> I just came across this in my own project, using `monaco-editor` package with `monaco-editor-webpack-plugin` and this PR will fix my issue as well.

I’m having the same issue. The workaround is to downgrade `monaco-editor` to 0.18.1 and `monaco-editor-webpack-plugin` to 1.7.0.

**Comment by sonicwang1989** [comment]
I’m having the same issue. Please consider merge the request as soon as possible. Thanks. 
@rebornix

**Comment by kamilic** [comment]
@sonicwang1989 @remcohaszing 
I use postcss to solve this problems temporally, although it isn't beautiful. 
```bash
npm i postcss-loader --save-dev # if you have installed, ignore it.
```

```javascript
module: {
            rules: [
                {
                    test: /monaco-editor.+?findWidget\.css$/,
                    use: [
                        {
                            loader: 'postcss-loader',
                            options: {
                                // https://astexplorer.net/#/gist/dd78fdcf57e23f08c4c6001354047d38/82523789e3628cca129bd68d6313ea0a9990dc04
                                plugins: [root => {
                                    // Transform CSS AST here
                                    root.walkRules(rule => {
                                        // Transform each rule here
                                        rule.walkDecls(decl => {
                                            if (decl.prop === 'transform' && decl.value.match(/Calc\(.+?\)/)) {
                                                decl.value = decl.value.replace(/Calc/, 'calc');
                                            }
                                        });
                                    });
                                }]
                            }
                        }
                    ],
                    enforce: 'pre'
                }]
        }
```

**Comment by sonicwang1989** [comment]
@kamilic I prefer to downgrade to 0.18.1. Thanks anyway. 
：）

**Comment by remcohaszing** [comment]
Apparently this has been fixed in #89156 and released.

**Comment by kamilic** [comment]
This fixed in https://github.com/microsoft/vscode/pull/89156.
closed.

**Pull request closed without merging**
