### PR TITLE
Exploration: Better transferring of TypedArrays used in Webview.postMessage

### LINKED ISSUE #115807: Improve transfer of ArrayBuffers to and from webviews
## Problem

There are currently two issues when you try posting a ArrayBuffer to a webview or from a webview back to VS Code:

1. The `ArrayBuffer` is not revived. Instead the receiver ends up getting a JavaScript object literal with the contents of the array buffer

1. Serialized messages for typed arrays are currently super inefficient . For example, a Uint8Array is serialized as `"{ "0": 0, "1": 0, "2": 0, ... }"`

## API Proposal
In `Webview.postMesssage`, add a second parameter that lets extensions specify the types to 'transfer':

```ts
interface Webview {
    postMessage(message: any, transfer?: readonly ArrayBuffer[]): Promise<bool>;
} 
```

This is inspired by the [`postMessage` web api](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), however to start with, we'd only allow transferring of array buffers.

When `transfer` is provided, we'd walk the `message` object to find any `ArrayBuffer` object that appear in the message and make sure these are more efficiently transferred. We'd also revive them properly on the other side (so if an `ArrayBuffer` goes in, then an `ArrayBuffer` object comes out too)

### Why not just always enable this behavior instead of requiring `transfer`?

We'd potentially break existing extensions that rely on the current serialized format of ArrayBuffers/typed arrays.

Having a `transfer` parameter also lets us really transfer the `ArrayBuffer` in cases where this is possible

### Can we always "transfer" ownership of the `ArrayBuffer` the way that we can on web?

No, we can't.

Consider an extension running on a remote with a local webview for example. There is no way to actually transfer the `ArrayBuffer` between these contexts. Instead we have to serialize it and then recreate it on the other side.

However, this new api would still let us improve the serialization and reduce the amount of data transferred.

Even if we can't really transfer ownership, semantically, `transfer` should behave like `window.postMessage` in that extensions should not use transferred objects after they have transferred. I'm not sure if we can enforce this though

### Can we support other types? `Blob` or `OffscreenCanvas` for example?

Potentially, but not all of them. Because we can't support transfer all the time (see above), we can only support types that can be serialized. This means no `OffscreenCanvas` or other rich objects.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #115807

This improves optimizes the passing of ArrayBuffers to and from webviews. Previously, these objects were inefficiently serialized and were not properly revived on the webview side

This change makes it so that if a user uses the new `transfer` argument on `Webview.postMessage`, any ArrayBuffers in the message are more efficiently transferred and revived

### CODE REVIEW

**Review by alexdima — COMMENTED** [review]
> prototyped this entirely in webview code in order to avoid any changes to our RPC code

:+1: I think the approach is very good! Walking all the transferred objects is expensive and we used to do that for all our RPC calls. We used to automatically serialize regular expressions, and on the revive side we would instantiate URIs and RegExps. We then found out that was a real perf bottleneck, especially for some really large intellisense payloads, but it would add a cost to everything. Walking untyped objects is just slow... It took us quite an effort to move away from that and now we revive things manually wherever we need it. @jrieken can fill in more details if I missed anything.

So today the RPC layer only does a single walk over the arguments. It does not go inside the arguments anymore. So I like the approach of doing things outside the RPC layer, and paying the perf cost of walking the object only where we need to support this. If we find out we need this in another place (i.e. for another RPC call) we could add a utility to serialize / deserialize using this format. We have done that before in `marshalling.ts`, so I think a utility there like `serializeTypedArrays/deserializeTypedArrays` would be beneficial.

Regarding web, I'm not sure what you mean exactly, since we have so many moving parts. But AFAIK, using `VSBuffer` is the right thing to do and is supported also on web in `extHost.protocol.ts`, where we respect and send arguments of type `VSBuffer` as a transferable in the `postMessage`.

**Comment by jrieken** [comment]
> It took us quite an effort to move away from that and now we revive things manually wherever we need it. @jrieken can fill in more details if I missed anything.

Yeah, all of that is gone (and the reason us using URI.revive a lot). Tho, it was a good change because recursively walking all objects that are being send is expensive. From the looks it seems that your solution doesn't require such a walk so that you can find and replace TypedArray instances. 


> For web, it would be great if we could mark any TypedArrays in postMessage as transferable to improve performance for large arrays. I believe this would require some changes in our core RPC code. I think we are already using transferable with here

On top of that we should investigate if message ports can be used. With that we could connect webviews directly to the extension host and wouldn't need to go through the renderer anymore. (I have done that with the web extension host that is launched through an iframe). Electron now supports MessagePorts between the main and renderer processes (@bpasero explored this for the shared process) and we should figure out if message ports would also work between webview processes and the extension host. Iff so then you would use our RPC only to exchange the ports and use a direct channel from then on

**Comment by alexdima** [comment]
> Iff so then you would use our RPC only to exchange the ports and use a direct channel from then on

:+1: x :100:

**Comment by bpasero** [comment]
> On top of that we should investigate if message ports can be used. With that we could connect webviews directly to the extension host and wouldn't need to go through the renderer anymore.

I like the idea of exploring this but please keep in mind that with the `sandbox` architecture, the extension host process maybe something different than what it is today. Today it is a child process of the renderer but in the future it might even just be a normal node.js process.

I am not entirely sure if node.js supports the same concepts (found this: https://nodejs.org/api/worker_threads.html#worker_threads_class_messageport)

**Comment by jrieken** [comment]
> I like the idea of exploring this but please keep in mind that with the sandbox architecture, the extension host process maybe something different than what it is today.

I think that's a very similar question. In the sandbox world how do renderers communicate with the extension host? Replaying messaging on the main-process, use web sockets, or message ports?

**Comment by bpasero** [comment]
> I think that's a very similar question. In the sandbox world how do renderers communicate with the extension host? Replaying messaging on the main-process, use web sockets, or message ports?

This is something that @deepak1556 will start to explore this month. From the [sandbox backlog](https://github.com/microsoft/vscode/issues/92164):

image

I think whatever solution we pick, it cannot go through `electron-main` but must be a direct communication channel.

**Comment by mjbvz** [comment]
Thanks for the feedback @alexdima! I'll continue exploring making this change in the webview code. I will also look into the our marshaling code to see if I can reuse some functions sheer

@jrieken I investigated using message port as well. I think using them should be possible but it requires some more thought for webviews.

In addition to the issues @bpasero brought up, the webview context is destroyed whenever the webview is hidden. This means that every time the webview is recreated (such as switching back to a custom editor), we'd have to go through the message port exchange again. Instead of waiting for this to complete before sending any messages, I think we could do something like:

1. Webview is recreated
2. We start passing the message port from the webview to the extension host
3. If postMessage is called during this time, we pass those messages through the existing flow (extension host -> main -> webview)
4. Once the extension host receives the message port, we start using it instead

**Comment by mjbvz** [comment]
I'll merge this at the start of April for more testing

**Pull request merged**
