### PR TITLE
[WIP] Inline all decorations - attempt 2

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
This is follow up on https://github.com/Microsoft/vscode/pull/20042.
Original issue:  https://github.com/Microsoft/vscode/issues/19749

CC:  @jrieken

This is not ready yet, but I just would love to get some input whether I'm moving in right direction. 
Right now I'm just trying to replicate current behavior [without adding possibility to display all errors] but moving implementation to `IViewZone` as described in comments in original PR.

### CODE REVIEW

**Comment by jrieken** [comment]
Can you resolve conflicts and we start looking into this?

**Comment by Krzysztof-Cieslak** [comment]
Rebased to latest master

**Comment by jrieken** [comment]
Please don't make this a `ZoneWidget` which to heavy for the purpose. What about my suggestion in https://github.com/Microsoft/vscode/pull/20042#issuecomment-278608579. You will need a lot less code if you start the "Show All Errors" from scratch.

**Comment by jrieken** [comment]
Your live will be a lot easier if you start fresh and I strongly recommend that. Don't get hung up with massaging the old code, just start with a new thing that simply always shows all errors/warning inline

**Comment by Krzysztof-Cieslak** [comment]
So I guess the question is whether I should only add new functionality ( inline all errors / warnings) or also try to replace old functionality with implementation using View Zones as suggested in https://github.com/Microsoft/vscode/pull/20042#issuecomment-278608579

**Comment by jrieken** [comment]
Sorry, that was misleading. In above mentioned comment I wasn't suggesting to replace the old functionality but to start fresh for this particular feature. The old bits will stay how they are, for the show all errors/warning feature tho we come up with something new (the old might eventually benefit from this)

**Comment by Krzysztof-Cieslak** [comment]
Oh, no problem. I've might interpreted something wrongly in this comment. 

In such case, starting totally fresh definitely makes sense, I'll try to do `attempt 3` over the weekend ;)

**Comment by Krzysztof-Cieslak** [comment]
Closing in favor of #29145

**Pull request closed without merging**
