### PR TITLE
Option to disable Touch Bar controls and leave control strip (#38333)

### PR DESCRIPTION
**Pull request by Baltazore**
An attempt to add config option to disable rendering Touch Bar buttons at all issue #38333 
This is my first PR to vscode repo.

### CODE REVIEW

**Comment by bpasero** [comment]
@Baltazore you should maybe coordinate with @viztor from https://github.com/Microsoft/vscode/pull/40400

**Comment by Baltazore** [comment]
@bpasero thanks for review. I've changed my implementation according your review from #40400.
Sorry I didn't find #40400 earlier...

**Comment by bpasero** [comment]
@Baltazore thanks, now you seem to have duplicate settings defined both on window and on keyboard? Can you remove the one on window?

**Comment by bpasero** [comment]
Thanks 👍

**Comment by Baltazore** [comment]
Great 👍 Thank you! 🙏

**Pull request merged**
