### PR TITLE
Add `$schema` to `cgmanifest.json`

### PR DESCRIPTION
**Pull request by JamieMagee**
This is part of a broad effort to improve the experience of using `cgmanifest.json`. I've mostly been creating these PRs using a script (for example https://github.com/microsoft/OLive/pull/108) however, the vscode repo has a lot of custom tooling built on top of `cgmanifest.json` so I decided to create this one manually after discussing with @isidorn

### CODE REVIEW

**Comment by isidorn** [comment]
@JamieMagee thanks for this PR. So this gets rid of our own cgmanifest schema which makes sense.
Assigning to @aeschli for review for schema smarts
fyi @lszomoru

**Comment by aeschli** [comment]
`$schema` is not the most elegant way. Note that $schema is not a standard, just a convenience invented by the JSON support in VS Code.

The easiest way would have been to change the schema association in '.vscode/settings' to use 'https://json.schemastore.org/component-detection-manifest.json'.

Alternative is to have a schema association in one of our built-in extensions. `extension-editing` would be a good place.

**Comment by JamieMagee** [comment]
@aeschli Thanks for the pointers. I'll revert the changes and add the association in `.vscode/settings.json` for now.

If I were to make the change in `extension-editing`, where would I need to make it?

**Comment by aeschli** [comment]
@JamieMagee That would be here: https://github.com/Microsoft/vscode/blob/main/extensions/extension-editing/package.json#L35

**Comment by JamieMagee** [comment]
@aeschli I made the change you suggested in `.vscode/settings.json`. I'll send a followup PR for `extension-editing` at a later date.

**Review by aeschli — APPROVED** [review]

**Comment by aeschli** [comment]
Sneaking in September as this is a safe and simple change.

**Comment by isidorn** [comment]
YOLO :)

**Comment by aeschli** [comment]
@isidorn as second reviewer :-)

**Pull request merged**
