### PR TITLE
moving all openRecent calc to render

### PR DESCRIPTION
**Pull request by sbatten**
#57788

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks a lot for doing this.
I have tested it and it works great overall. There is one corner case:
Open the recent menu list as soon as you can before the renderer comes up -> the open recent list appears empty sometimes for me.
I think this might be an issue as users might open a workspace, immedatly figure out that they actually want a different workspace -> open the recent list and not find it there. I personally do this all the time.
However I can not repro that it is empty constantly. Might you know when would this happen?
What I can repro is that the list is stale if I open it too early (which is fine imho).

So could we use the storage service to persist the list, so we have some value there before the renderer is ready? Depending on how often the empty case appears.

Also since this week is endgame, I suggest to push these changes next week during debt so we would minimize the risk.
If you would like to do it this week, we can merge it in just make sure that you create a testplan item covering all 3 platforms.

Also let us know what you think @bpasero

**Comment by bpasero** [comment]
@sbatten you already have a cache for menu items to render it quickly, shouldn't the list of recently opened be covered by exactly that cache?

**Comment by sbatten** [comment]
@isidorn if it is the same to you, we can wait until next week to merge the changes, I just wanted to make sure I got this done since I've been putting it off.

@bpasero yes, I would believe so, I am not sure what situation causes the list to be empty on startup if the list is cached.

**Comment by isidorn** [comment]
@sbatten yeah, let's be on the safe side and assign this to December. I will merge it in start of next week.
As for the empty list I got this for sure for the first time I tried it. Not sure if there is some cache initialision step? Or it should have been already initialisied for me.
Anyways once we merge it in next week we can keep our eyes open for this and than fix it without pressure in December.

Related to this I will remove all dependencies on labelService from the main side.
For that I will need only one more thing. From the renderer to tell the main that the recent list might have changed. Can you please point me to a way to do this? (you probably already have a mechanism for this).

Thanks

**Comment by sbatten** [comment]
@isidorn the cache will not work for recent menu items the first time you launch with this new functionality because we cache what is sent from the render process and we didn't used to send actual recent menu items from the render process. after this, it should work indefinitely.

as for knowing the recent items have changed, `menubarControl.ts` currently registers a listener for this and updates the menubar accordingly.

**Comment by isidorn** [comment]
@sbatten ok, if the list is not shown only the first time than it should be just fine.

Is there some way to update just the open recent menu list, and not the whole menubar? I might need this in the future (not 100% sure yet)

**Comment by isidorn** [comment]
@sbatten ok this makes sense

**Comment by isidorn** [comment]
Let's merge this in and see how it goes.
@sbatten thanks!

**Comment by bpasero** [comment]
@sbatten I find it a bit weird that there is still code that assumes menu items that talk about recently opened. E.g. in `menubar.ts` there is a `createOpenRecentMenuItem` that is used whenever a menu item has a `URI`?

**Comment by sbatten** [comment]
@bpasero as I understand, we cannot send an actual function/callback across IPC so I need to reconstruct the recent menu items on main side. I thought about maybe doing something more abstract like a menu item that takes a command and parameters that would make it less "aware". I am open to suggestions or if it is already possible to send over the callbacks and I am mistaken, how to do that.

**Comment by bpasero** [comment]
@sbatten wouldn't it be possible to add something like an `argument` field to the menu item for the `command` that gets executed? That `argument` could be the serialised URI and the `command` would be to open that.

PS: you still support `Alt+click` to force open into new window right?

**Comment by sbatten** [comment]
@bpasero `Ctrl+Click` seems to be working for me on windows in both native and custom. with the current approach of reconstructing the items, that logic would be mostly the same

**Pull request merged**
