### PR TITLE
Support git worktree directory detection

### LINKED ISSUE #68038: Git: Support git worktrees in workspace
```
$ mkdir repro
$ cd repro
$ mkdir example1
$ cd example1
$ git init; echo "hello" > world.txt; git add world.txt; git commit -m "init";
$ git worktree add ../example1branchA
$ git worktree add ../example1branchB
$ cd ..

$ mkdir example2
$ cd example2
$ git init; echo "hello" > world.txt; git add world.txt; git commit -m "init";
$ cd ..
```
Scenario:
1. Open `repro` directory in VS Code
2. Go to Git tab.

**Expected:** "Source Control Providers" lists Git repos.
  * `example1`
  * `example1branchA`
  * `example1branchB`
  * `example2`

**Actual:** "Source Control Providers" lists Git repos.
 * `example1`
 * `example2`

I sometimes will have lots of branches checked out in parallel on huge repos that I can't afford to clone multiple times. I would also like to be able to use VS Code's source control functionality with these checkouts all the same.

Thanks! and thanks for Code!

### PR DESCRIPTION
**Pull request by jeffb4**
This PR fixes #68038
(actually it's just the start of fixing, but it's a start)

@raix 's code to only activate the git extension on git directories via `isGitRepository` in 10e0a22f6d439d7d511e4b3a8b1d874fb5b6be52 assumed correct git workspace directories would have a directory named `.git` . However, `git worktree` creates a file `.git` with `gitdir: /some/other/git/location` in it. This PR allows `isGitRepository` to return `true` if there is a `.git` file in a directory

IMO, this is a necessary preliminary step for properly supporting git worktree in the git extension

### CODE REVIEW

**Comment by joaomoreno** [comment]
> (actually it's just the start of fixing, but it's a start)

I've set this to be a Draft PR then.

**Comment by jeffb4** [comment]
This PR is still useful as-is, and I'm not inclined to dive into things like fixing remote development or adding UI elements for working with git worktrees. Can it be accepted as-is, as an incremental improvement?

**Comment by jeffb4** [comment]
This is still a correct, small PR for git extension support, as far as I can tell.

**Comment by william-airshipvms** [comment]
This would be nice to have when using vscode as the default editor for git. 

Ideally you go to commit a file, it opens the `COMMIT_EDITMSG` file in vscode, and then you would be able to see a list of changes in the source control tab at the same time you are writing the commit message.

What actually happens is vscode loads the `.git/worktree/branch` folder in the source control tab, and shows all branch files being marked as deleted. It also shows a warning every time it is launched as the editor.

**Pull request closed without merging**
