### PR TITLE
Proxy support for extensions #69

### LINKED ISSUE #69: Proxy support for extension gallery
Whenever I try to install any extension, using *ext install*, I get a **connect ETIMEDOUT 191.238.172.191:443** error.

Trying to navigate to **https://191.238.172.191** in the browser produces a warning regarding the certificate being valid only for **\*.market.visualstudio.com**, but I'm allowed to proceed.

Shouldn't VSCode try to connect to the name instead of the IP?

I'm behind a proxy, VSCode updates just fine behind it, and also lists the available extensions. The firewall here logs the invalid certificate but allows the connection to proceed. Doesn't look like a problem in my end...

**OS:** Windows 7
**VSCode:** 0.10.1

### PR DESCRIPTION
**Pull request by punker76**
The extension installation doesn't use the `http.proxy` settings, so this PR fixes this.

Closes #69 Proxy support for extension gallery

### CODE REVIEW

**Comment by mattn** [comment]
:+1:

**Comment by vasily-kirichenko** [comment]
:+1:

**Comment by joaomoreno** [comment]
This is just awesome. :ok_hand: Thanks!

**Comment by mattn** [comment]
@jeffmcaffer do you have plan to release this change in few days? now I can't install extensions because of this problem.

**Comment by joaomoreno** [comment]
@mattn Let's at least try.

**Comment by joaomoreno** [comment]
@mattn If you get a hold of a machine not behind a proxy, try this:

1. Install the extensions on that machine
2. Zip up `~/.vscode/extensions`
3. Extract it to `~/.vscode/extensions` on the machine behind the proxy
4. Launch Code

**Comment by mattn** [comment]
@joaomoreno thanks.

**Comment by bpasero** [comment]
@punker76 I did some changes to load the settings and landed this again (https://github.com/Microsoft/vscode/commit/e57d6db414ee2f3f4e7da0535b39c6b4c1c02817).

**Comment by joaomoreno** [comment]
:fireworks:

**Comment by punker76** [comment]
:+1:

**Pull request merged**
