### PR TITLE
Don't show quick fix link in problem hovers until we know we have quick fixes

### LINKED ISSUE #71579: Quick Fix feature not working - Really confused.
Hi, I am a bit new, and I have a simple code example on VS Code v1.32.3.
It says I have an error,   ok fine..... but then when I chose the "Quick Fix" option
there is never a Quick Fix for this or any other thing in the past I tried to do a quick fix on.
Whats the point of having a Quick Fix feature, if it doesn't do anything ?
Im a bit confused.
.
This is the code I tried to do a quick fix on (its an extremely simple code):
.
Screenshot_24

When I try to fix, I get this:
.
Screenshot_25

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #71579

**Bug**
We currently always show the `quick fix` button in problem hovers. This has confused a lot of users (see #71579) because we lead them to think that every error has a quick fix

**Fix**
Only show the quick fix button when we have known quick fixes

### CODE REVIEW

**Comment by mjbvz** [comment]
Here's what it looks like with a very slow quick fix provider:

Jul-10-2019 10-29-28

**Comment by misolori** [comment]
I think while we verify whether we can show a fix we should show a "Loading..." in the quick fix text, we do this in IntelliSense:

image

If we find no fixes we can either leave it blank or show a "No actions available" in place. This at least indicates to the user that something is happening and they can wait, otherwise things seem like they are randomly loaded and feels like a (perf) bug. Thoughts?

**Comment by mjbvz** [comment]
Quick fixes won't show up for many errors so we want a UX that doesn't suggest quick fixes should have been available (but failed to load or had some error). Maybe:

* While loading, show a `Checking for quick fixes` spinner
* If no quick fixes are found, show nothing or a `No quick fixes available` text
* Otherwise show the quick fix button

**Comment by misolori** [comment]
That sounds good to me, I think just a `Checking for quick fixes...` is sufficient without the spinner.

**Comment by mjbvz** [comment]
Here's the loading indicator. First error has no fixes, second does:
 
Jul-10-2019 11-45-15

An artificial delay of a few seconds was added to show the loading indicator feature off

**Review by miguelsolorio — APPROVED** [review]
👍 LGTM!

**Comment by sandy081** [comment]
Good solution @mjbvz. Thanks for the fix.

**Review by sandy081 — APPROVED** [review]

**Comment by mjbvz** [comment]
Just a quick update on the UX based on @Tyriar's feedback: if code actions are not quickly returned, we will defer showing the `loading...` message for a little while and then quickly fade it in. Once code actions are resolved, we swap out the loading message

(this is hard to capture on a gif but let me know if you have any feedback after seeing it in insiders)

**Comment by SEDoug** [comment]
I took a look at my installed extensions and noticed the C# extension was complaining that it needed to be reloaded. Hmm, so check your extensions list first.  This is what I was presented after clicking reload.
c#_extension01
c#_extension02
c#_extension03

**Pull request merged**
