### PR TITLE
The Web Optimization Project has optimized your repository!

### PR DESCRIPTION
**Pull request by devedse**
# Web Optimization Project (Beta)

The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:

If you have any questions, feel free to create an issue or join the gitter chat:
[Join the chat at https://gitter.im/WebOptimizationProject/Lobby](https://gitter.im/WebOptimizationProject/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

## Optimization

The Web Optimization Project optimized this repository. All optimizations (compressions) are done losslessly and no quality / data is lost. This is also verified afterwards by the Wop so you can be sure that your images are exactly the same.

### Commit 1

Information | Value
-- | --
Version | 0.0.5.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total optimizable files | 10
Files optimized successfully (size reduced) | 6
Files already fully optimized | 0
Files that failed to be optimized | 4
Total size before optimization | 259.2KB
Total size after optimization | 234.7KB
Optimized size compared to old | 90.55%
Total bytes saved | 24.5KB
Time taken for optimization | 3.1 Minutes

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Duration | Successful
-- | -- | -- | -- | -- | --
image.png | 35.9KB | 17.4KB | 18.4KB | 39 Seconds | True
code.png | 5.8KB | 1.7KB | 4.1KB | 1.7 Minutes | True
defaultIcon.png | 1.6KB | 764B | 922B | 11 Seconds | True
defaultIcon.png | 1.6KB | 764B | 922B | 12 Seconds | True
diagonal-fill.png | 185B | 108B | 77B | 7 Seconds | True
opacity-background.png | 173B | 100B | 73B | 6 Seconds | True
inno-big.bmp | 201.2KB | 201.2KB | 0B | 1 Second | False
inno-small.bmp | 12.5KB | 12.5KB | 0B | 1 Second | False
some.json.png | 174B | 174B | 0B | 1 Second | False
some.xml.png | 16B | 16B | 0B | 1 Second | False

### CODE REVIEW

**Comment by devedse** [comment]
If any other Microsoft github project might be interesting for the WOP to be optimized, let me know. Also any feedback is welcome, I'm just in beta :smile:.

**Comment by Tyriar** [comment]
@jrieken I'm mainly concerned about image.png being optimized since it's in a test dir, not sure what it's used for.

**Comment by jrieken** [comment]
The test image isn't an issue, assigning @joaomoreno for the rest

**Comment by joaomoreno** [comment]
It's an interesting idea, I think you're on to something with that service. It just doesn't seem to specifically help VS Code much, though.

I recommend going through our Contribution guide first: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#where-to-contribute

**Pull request closed without merging**
