### PR TITLE
Added use snippet body as a description when none is provided #181115

### PR DESCRIPTION
**Pull request by TheSylvester**
- added Snippets:Fill Descriptions:Enabled to use snippet body as a description when none is provided #181115
- editor.snippets.fillDescriptions.enabled toggle implemented in settings

edit: added word "implemented"

### CODE REVIEW

**Comment by TheSylvester** [comment]
@microsoft-github-policy-service agree

**Comment by jrieken** [comment]
@TheSylvester Thanks. This is already looking pretty good. 

> editor.snippets.fillDescriptions.enabled toggle in settings

I would like to disagree with that and implement this w/o setting.

**Comment by TheSylvester** [comment]
> > editor.snippets.fillDescriptions.enabled toggle in settings
> 
> I would like to disagree with that and implement this w/o setting.

I should clarify that I implemented a setting to toggle this to be enabled.  By default I've set this to be false to be optionally enabled, unless you see something different?

**Comment by jrieken** [comment]
> I should clarify that I implemented a setting to toggle this to be enabled. By default I've set this to be false to be optionally enabled, unless you see something different?

That's what I see but I am saying that a setting isn't needed. This is an improvement and shouldn't be behind a setting but just happen

**Comment by jrieken** [comment]
> I was just following the ethos of making as few changes as possible, especially to default behaviour

We take improvement without setting, so please remove that part in the PR

**Comment by TheSylvester** [comment]
> 

Thank you for confirming.  I've made the required changes.  Kindly let me know if there's anything else required.

**Review by jrieken — APPROVED** [review]
Thanks

**Review by bpasero — APPROVED** [review]

**Pull request merged**
