### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by rohmanhm**
This is the correct writing for **MIT License**.
With this, you will get MIT licenses tab beside contributors tab.

### CODE REVIEW

**Review by chrisdias — CHANGES_REQUESTED** [review]
@rohmanhm thanks for the PR, i think it is cool to get the License tab to show up in the repo.  A couple of comments on the PR...  Microsoft policy is to include the "All rights reserved." clause and omit the year.  If you make these changes, will the license tab still show up in GitHub?

**Comment by rohmanhm** [comment]
@chrisdias Done, sorry my bad miss one line, but now it's clear

**Review by chrisdias — CHANGES_REQUESTED** [review]
Thanks for the change... also can we remove the copyright year?

"Copyright (c) Microsoft Corporation"

**Comment by rohmanhm** [comment]
@chrisdias Sorry, you can't. If you remove the year, GitHub can't recognize your **MIT License** and your LICENSE Tab can't show up. Because of invalid format for **MIT License**.

References
- https://opensource.org/licenses/MIT
- http://opensource.stackexchange.com/questions/1522/what-should-be-written-in-mit-license-year-full-name
- http://softwareengineering.stackexchange.com/questions/210472/is-renewal-of-mit-license-needed-on-github-at-the-beginning-of-each-year

**Review by chrisdias — CHANGES_REQUESTED** [review]
Ok, hopefully last change request :).  

After checking with our legal folks, can you do a range on the copyright year?

Copyright (c) 2015 - present Microsoft Corporation

This should still be valid and it will show up as a new tab.

**Comment by rohmanhm** [comment]
Yes, you can. I make a new commit and it's valid **MIT License**. You can keep going.

**Review by chrisdias — APPROVED** [review]
looks great!

**Comment by AnthonyMeaux101** [comment]
yy

**Comment by AnthonyMeaux101** [comment]
>

**Pull request merged**
