### PR TITLE
Git Diff editor: show path as description

### LINKED ISSUE #109224: Diff editor: show path as description
I often miss that git diff editors do not show the path of a resource as description, e.g. here:

image

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #109224

### CODE REVIEW

**Comment by joaomoreno** [comment]
@bpasero Changes look good. But should git really be the one processing the path and splitting it? The workbench does a better job at this, namely since it knows which path separator to use. Wouldn't a better fix be at the workbench diff editor level and have it use a good parent dir description if both files share the same parent directory?

**Comment by bpasero** [comment]
@joaomoreno I tried that originally actually but then noticed that Git is using `query` params to add extra metadata to the URIs. So I cannot simply use `extUri.equals(uri1, uri2)` to find out if both sides are the same file. I could do a hack and just check for `uri.path` but that is brittle imho.

**Comment by bpasero** [comment]
@joaomoreno if you would register a label formatter that gives me the same path for both URIs, then I think we can do it. Aka, the workbench would get the label for both sides and only show it if it is the same

**Comment by bpasero** [comment]
If I run the following code today

```ts
this.labelService.getUriLabel(dirname(resourceDiffInput.leftResource), { relative: true });
```

on left and right resource I get results that are not so ideal for showing a short path:
* file on index: `/Users/bpasero/Documents/ticino-playground (git)`
* file not yet staged: `/Users/bpasero/Documents/ticino-playground (git)` (left) and `ticino-playground` (right)

I think we cannot just drop the `(git)` suffix because that is useful in other places like quick pick, but for the editor label this will make it hard to come up with something.

**Comment by joaomoreno** [comment]
Yeah the ` (git)` is also there so these files look different in views like `Problems`, which never show scheme.

**Comment by bpasero** [comment]
Obsolete.

**Pull request closed without merging**
