### PR TITLE
improve diff editor audio cue handling

### LINKED ISSUE #173256: `workbench.action.editor.nextChange` is slow in 1.75
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project in VSCode that's versioned by git.
2. Make a change.
3. Use `workbench.action.editor.nextChange`, (<kbd>Alt</kbd>+<kbd>F5</kbd>).
4. Measure the time it takes to move your cursor to the next change. You should notice a significant delay in version 1.75 compared to version 1.74.

I've only tested this in a single repository with ~30k LoC and a few hundred commits.

### PR DESCRIPTION
**Pull request by meganrogge**
fix #173256

### CODE REVIEW

**Review by rzhao271 — APPROVED** [review]
LGTM as long as preloading the sounds doesn't play them all to the user at the beginning.

**Comment by meganrogge** [comment]
> LGTM as long as preloading the sounds doesn't play them all to the user at the beginning.

volume is set to zero

**Comment by dwelle** [comment]
Thanks @meganrogge! ❤️

**Comment by weston-morty** [comment]
@meganrogge I just installed 1.78! This is the **_VERY FIRST_** thing I tested seconds after downloading 1.78.

THANK YOU!!!!!!!!  🎉

**Pull request merged**
