### PR TITLE
Support for hangul alt chars

### PR DESCRIPTION
**Pull request by Tyriar**
Part of #196203

Recording 2023-10-22 at 07 48 14

TODO

- [x] Move into a new file (`altChars.ts`?) as this concept could be used elsewhere
- [x] Fixing lint by explicitly allowing unicode chars in this file as they make it much more readable/maintainable
- [x] Reduce string/array creation
- [x] Reduce repetition, for example when looking at char indexes in the character data
- [x] Consider optimizing/compressing the hangul character data
- [x] Add unit tests

### CODE REVIEW

**Comment by Tyriar** [comment]
@TylerLeonhardt what do you think about this new "alternate characters" concept? This could be adopted by other languages as needed. Here's what I plan on doing on the PR still but don't have time this iteration:

- Move into a new file (`altChars.ts`?)
- Fixing lint by explicitly allowing unicode chars in this file as they make it much more readable/maintainable
- Reduce string/array creation

**Comment by TylerLeonhardt** [comment]
I like the approach and think this is a good list of tasks. I wonder if there are other places where we can use this (settings editor, keybindings editor, etc)

**Comment by Tyriar** [comment]
Where ever this shared filtering code is used they'll get it for free, but I'm also planning on making it its own independent module if something else wants to integrate 👍

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by Tyriar** [comment]
Opening up for review, this is fairly safe to merge due to the amount of testing. I'll make sure @TylerLeonhardt checks it out before testing and also assign the TPI manually.

**Comment by Tyriar** [comment]
@TylerLeonhardt this is pretty solid now, it doesn't work in go to file through which is one of the big use cases. I'm not sure if I can easily add it to go to file?

**Review by TylerLeonhardt — APPROVED** [review]

**Pull request merged**
