### PR TITLE
Add custom path for vscode-server socket files and named pipe length

### PR DESCRIPTION
**Pull request by MarkZuber**
Change for #172480

For socket file name length we scope version to 4 characters and type to 6 characters and have found that works great for Windows.

This has been tested and validated in our environment to remove issues related to ensuring windows named pipes are resilient to variable name length.

### CODE REVIEW

**Comment by alexdima** [comment]
Let's discuss in https://github.com/microsoft/vscode/issues/172480#issuecomment-1427980744

**Review by alexdima — DISMISSED** [review]

**Review by bpasero — CHANGES_REQUESTED** [review]
I do not really understand this change. The comment indicates this helps on Windows, but this change is for macOS/Linux?

Besides, the only consumer of this method is this it seems:

https://github.com/microsoft/vscode/blob/2d67c6fae3cf94da9558103994395ab28bc14110/src/vs/platform/environment/electron-main/environmentMainService.ts#L48

As such, the `type` is always going to be short (`main`) and the version at least for stable will be short as well (`1.75.0`).

Am I missing something?

**Comment by MarkZuber** [comment]
Our version string is longer than 1.75.0 (we use date based versions which end up extending this beyond the limit).  So in your the case of public VS Code, this wouldn't have an effect but it does for us.   If you feel this doesn't make sense to upstream given the way the public product is versioned, we can keep this fork on our end.

**Comment by bpasero** [comment]
I see. Still, this change has no impact on Windows right? So what problem does this address?

**Comment by MarkZuber** [comment]
Apologies on the comment, I went backwards. :(  windows returns early from this function with their named pipe which works fine.  but there's a limit on macos and linux for the name of the .sock file which ends up getting too long with our additional versioning.    This is related to the stackexchange comment in the original issue.

https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars

**Comment by bpasero** [comment]
Ok understood, setting to March for consideration.

**Review by bpasero — APPROVED** [review]
Actually I think this is good to go even for Feb.

**Review by alexdima — APPROVED** [review]

**Pull request merged**
