### PR TITLE
Adds "babel" support to <script> tags in html

### PR DESCRIPTION
**Pull request by phocks**
text/babel highlighting works with this now in html files.

### CODE REVIEW

**Comment by aeschli** [comment]
We use https://github.com/textmate/html.tmbundle as the grammar for html. Would you mind filing the PR against that repository? Once accepted there, feel free to ping me and I'll update our grammar. Thanks a lot!

**Comment by phocks** [comment]
Sorry I couldn't really find where to add babel support in that repo. Just letting you know that when I updated VS Code it removed this fix for me and I had to go in and redo it. I'll try looking in html.tmbundle again later.

**Comment by phocks** [comment]
Never mind, I found the place to change it in that repository. Submitting pull request now.

**Comment by aeschli** [comment]
@Awesome, thanks a lot , @phocks !

**Pull request closed without merging**
