### PR TITLE
Update quick pick list widget focus colors

### LINKED ISSUE #121493: Quick pick focused item does not meet color contrast of 3:1
_originally filed in https://github.com/microsoft/vscode-azurefunctions/issues/2680_

Issue Type: <b>Bug</b>

The color contrast of the focused item in a quick pick compared to the non-focused item is only 1.1:1, aka less than the required 3:1
Screen Shot 2021-04-16 at 11 18 40 AM
Screen Shot 2021-04-16 at 11 23 03 AM

Might I suggest you match the pattern you use in the file explorer, which _does_ meet the 3:1 contrast ratio (either the filled version or the border-only version)
Screen Shot 2021-04-16 at 11 19 37 AMScreen Shot 2021-04-16 at 11 19 51 AM

VS Code version: Code - Insiders 1.56.0-insider (394a2e4779ff767e2761a59a51b15848dcd24173, 2021-04-13T11:11:34.416Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 63154ab5-ba0e-419a-aa36-bd67d86db27f|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by miguelsolorio**
This PR fixes #121493. The main issue here is that we can't use color alone to signify state ([see 1.4.1](https://www.w3.org/TR/WCAG21/#use-of-color)), so we have to update our focus state to invert the colors (just like in our list widget) to improve the focus state. Originally I was scoping this to the quick pick but then also saw that the suggest widget relies on these colors, so I went ahead and updated those as well. This updates:

- Default focus foreground & background colors for quick pick/suggest items
- Focused highlights/labels/icons/keybindings to pass color contrast
- Introduces:
  - `list.focusHighlightForeground` which defaults to the current highlight color
  - `quickInputList.focusForeground` which defaults to `list.activeSelectionForeground`
  - `editorSuggestWidget.selectedForeground` which defaults to `list.activeSelectionForeground`

Dark theme is almost unnoticeable as the colors were close, but the light theme has the more noticeable changes. Also, since the focus bg is so strong here I was unable to find an alternate color that worked for highlights (when filtering) so for now I set that color to be white. Open to feedback on all of these changes.

## Dark
image
image

## Light
image
image

## Other themes
image
image

image
image

cc @bpasero @joaomoreno

### CODE REVIEW

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by jrieken** [comment]
> since the focus bg is so strong here I was unable to find an alternate color that worked for highlights (when filtering) so for now I set that color to be white.

Not a fan of the "missing" highlight colour. Maybe I am biased (since I wrote the highlight computation) but my feeling is that the highlights are important. You learn how an item was matched and how to tweak your typing in the future, like type all upper-case characters etc

**Comment by misolori** [comment]
I can try using an alternate highlight color for the focus state, which I did attempt but wasn't sure if it was too odd. Will post a screenshot.

**Comment by misolori** [comment]
@jrieken here's what it would look like for the light theme to have an alternate highlight color:

image

**Comment by jrieken** [comment]
Better - let's give that a try

**Review by jrieken — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Does this still look ok in the standalone editor? (Steps here: https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md)

**Comment by misolori** [comment]
@TylerLeonhardt thanks for the ping on the standalone editor, pushed fixes for them:

### Dark
image
image


## Light
image
image

## High Contrast
image
image

**Pull request merged**
