### PR TITLE
Implements run to line.

### LINKED ISSUE #123872: Debugger: Put "Run To Cursor" Into Breakpoint Context Menu
Currently, "Run To Cursor" is in a very long context menu:

image

I think it would make sense to add "Run To Cursor" to the context menu for adding breakpoints:

image

This new entry should be called "Run To Line".

Pro:
* That context menu is already strictly debugging related
* If a user does not know about "Run To Cursor" and manually places a breakpoint to the target location, they might discover this functionality in that context menu

Contra:
* "Run To Line" is not a breakpoint

### PR DESCRIPTION
**Pull request by hediet**
This PR fixes #123872

I'm unsure if I got column 0/undefined right. 

recording

What do you think of putting "Run to line" to the top of that menu? :wink:

### CODE REVIEW

**Comment by isidorn** [comment]
Did a first quick review and it looks good.
1. Seems like you have unused imports in `debugEditorActions`. Can you please fix that
2. "Run to Line" should be at the bottom of the menu so we do not break users muscle memory. Probably a lot of users memorised that adding Conditional Breakpoints is the second option, and putting a new command on the top would shift everything 

I will do one more detailed review soon.

**Comment by isidorn** [comment]
Can you please implement the newly introduced method in the `mockDebugService` in `src/vs/workbench/contrib/debug/test/browser/mockDebug.ts`

**Comment by hediet** [comment]
Gotcha. I really should check the logs before pushing :D

**Comment by isidorn** [comment]
Yeah that can be helpful :D

**Comment by isidorn** [comment]
Run to line should only be there while debugging is active

Screenshot 2021-08-03 at 17 10 53

**Comment by hediet** [comment]
I agree. Wouldn't it be nice though if "Run to line" starts debugging if debugging is not active?

**Comment by isidorn** [comment]
Yeah I also thought about that. The problem is that starting debugging we can not guarantee that the current file will actually get run.
Though I like the idea in general and we can go down that approach to try it out.

**Comment by hediet** [comment]
> Yeah I also thought about that. The problem is that starting debugging we can not guarantee that the current file will actually get run.
> Though I like the idea in general and we can go down that approach to try it out.

I see. I'm okay with hiding it for now!

**Comment by isidorn** [comment]
Cool, then let's merge it in. Thanks a lot for this great PR 👏

**Comment by scybert** [comment]
@isidorn I'm curious why you are merging a failing PR.

**Comment by isidorn** [comment]
@scybert because I double checked that it is good and that it works as expected. It might have been failing in the past, before latest commits were added.

**Comment by hediet** [comment]
Also, your tests are flakey...

**Pull request merged**
