### PR TITLE
Refactor to fix compile error with noImplicitAny

### PR DESCRIPTION
**Pull request by katainaka0503**
Some refactorings

- Introduced index signature.
- Fixed to use ES6 Map properly.
- Fixed type signature.
- Fixed to use `foo.bar` instead of `foo[bar]`

All of these changes fix compile errors which occur if `noImplicitAny` in `tsconfig.json` is set to `true`.

### CODE REVIEW

**Comment by Tyriar** [comment]
More types :+1:

**Review by Tyriar — APPROVED** [review]

**Comment by jrieken** [comment]
👍

**Review by jrieken — APPROVED** [review]

**Comment by aeschli** [comment]
👍

**Comment by bpasero** [comment]
LGTM, thanks 👍

**Review by bpasero — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by jrieken** [comment]
Merged. Thanks @katainaka0503 for the PR.

**Comment by jrieken** [comment]
No problem, tho keep in mind that larger PRs esp. those that cut across different owners are harder for us to coordinate and it's better send a heads up note first

**Comment by katainaka0503** [comment]
I am terribly sorry.

**Pull request merged**
