### PR TITLE
Allow calling extension language features even for big files

### LINKED ISSUE #99686: Allow calling extension language features even for big files
## Overview
Our [debug extension](https://github.com/RechInformatica/rech-cobol-debugger) implements `EvaluatableExpressionProvider` to have specific hover behavior, since COBOL treats hyphen as part of variable name and do not consider hyphen as subtraction symbol.

Here is the function we invoke on VSCode API to do so:

```typescript
/**
* Register a provider that locates evaluatable expressions in text documents.
* VS Code will evaluate the expression in the active debug session and will show the result in the debug hover.
*
* If multiple providers are registered for a language an arbitrary provider will be used.
*
* @param selector A selector that defines the documents this provider is applicable to.
* @param provider An evaluatable expression provider.
* @return A [disposable](#Disposable) that unregisters this provider when being disposed.
*/
export function registerEvaluatableExpressionProvider(selector: DocumentSelector, provider: EvaluatableExpressionProvider): Disposable;
```

Here is how we use it:

```typescript
languages.registerEvaluatableExpressionProvider('COBOL', new CobolEvaluatableExpressionProvider());
```

## Problem
Unfortunately, some COBOL debug files are **really huge** and have more than 50MB. We completely understand how bad it is to have such big debug sources and spent great effort trying to make them smaller. However, since it's legacy software, it's hard to do so.

The instance of _EvaluatableExpressionProvider_ we register on VSCode API is not invoked when current debug file is bigger than 50MB because:

* The [shouldSynchronizeModel of modelService.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/services/modelService.ts#L44) returns false since model is too large for syncing;
* Hence, [score function of languageSelector.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/modes/languageSelector.ts#L40) makes provider score = 0 since it's a big file;
* On the end, [EvaluatableExpressionProviderRegistry.has(model) of debugHover.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/debugHover.ts#L191) returns false and doesn't invoke the provider, since score = 0.

[Here on textModel.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/model/textModel.ts#L350) is where the limit of 50MB is applied:

```typescript
this._isTooLargeForSyncing = (bufferTextLength > TextModel.MODEL_SYNC_LIMIT);
```
## Suggestion
I can make a PR with the changes if you guys agree... but I'm not sure which is the best approach. We have a few suggestions for this:

1. Create a boolean setting e.g. "Allow language features on large files" and apply it on languageSelector.ts where _shouldSynchronizeModel_ function is currently invoked. This way large files won't affect score and will prevent score from being 0;
2. Create a boolean setting e.g. "Allow syncing for large files" and apply it on constructor of TextModel (a new option on ITextModelCreationOptions), so won't consider the MODEL_SYNC_LIMIT constant of 50MB. This way isTooLargeForSyncing() never returns true;
3. Reuse the existing setting "editor.largeFileOptimizations" on languageSelector.ts. Similar to first approach but using an existing setting (may be dangerous because may change behavior for other people).

What do you guys think?
Thanks in advance!

### PR DESCRIPTION
**Pull request by GustavoASC**
This PR fixes #99686.

When `editor.largeFileOptimizations` is set to `false`, VSCode stops considering the limit of 50MB defined on textModel.ts to invoke language providers and synchronize buffer between extension host and extensions.

I've tested model.isTooLargeForTokenization() (which represents the setting editor.largeFileOptimizations) on languageFeatureRegistry.ts, however, the document is not found on ExtHostDocuments.ts when provider is called. The reason for that is: the text buffer hasn't been synchronized from extension host to other processes.

So I'm still considering editor.largeFileOptimizations setting, but using that to define this._isTooLargeForSyncing = false on textModel.ts.

### CODE REVIEW

**Comment by GustavoASC** [comment]
@jrieken @alexdima Do you guys think this modification is dangerous? I mean... I've really tried to simply change languageFeatureRegistry.ts instead of textModel.ts, hoping that computing a different provider score would resolve this issue. However, to make it work, we need to synchronize larger buffers from extension host through RPC.

I confess I'm a little afraid it may freeze while synchronizing a really huge file with `editor.largeFileOptimizations = false`. I've tested with a 60MB file and it was OK, but for slower computers with huger files it may not be nice...

At last, if you believe the change is not worth the risk, we can leave it as it is (without these changes) an consider it a limitation. I can show a message on our [debug extension](https://github.com/RechInformatica/rech-cobol-debugger) when opening a big file, pointing out that some features are disabled due file size.

I'm up to you.

Thanks in advance! 😄

**Comment by jrieken** [comment]
>  Do you guys think this modification is dangerous? 

Yes. It means extensions that aren't authored with performance in mind see now much, much larger files and that is likely to kill the extension host. E.g there are many extensions that for instance apply regular expressions to the whole document as you type. Once a certain file size is reached the everything will just freeze.

**Comment by GustavoASC** [comment]
Uhm, I understand... Thanks for pointing this out :+1:
Should we close this PR without any change?

**Comment by GustavoASC** [comment]
I'm closing this PR because this change is quite polemic.
I agree with you @jrieken... this could lead to unexpected behavior on some scenarios.

Thanks for your attention, anyway! :smiley:

**Pull request closed without merging**
