### PR TITLE
Editors: rewrite editor history service

### LINKED ISSUE #9526: Make history navigation aware of editor groups
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.open a file in editor 1;
2.open same file in other editor 2(ctrl +2 side editor)
3. in editor 1 move cursor   to line 1 and then to line 2
4 in editor 2 move cursor to line 3 and then to line 4
5 click mouse backward button in editor 1 the cursor back to  line 4 but i want to line 1

It seems every file have one  cursor backward stack,and all side editor share it?
Regards

### LINKED ISSUE #27112: Add a jump back command from goto definition
This is a feature request.

I'd like to have a command like `workbench.action.navigateback` but that would only take into account the `go to`/`jump` commands (go to definition, implementation, type definition, start of function, ...) and no cursor move.

For example, I could jump from a function call to the definition of the function, then move my cursor down three times. If I navigate back, my cursor will go up by one line. But instead I would like to jump back to the function definition and then to the function call.

### LINKED ISSUE #42617: Introduce "Go Back" and "Go Forward" to navigate between recent edits
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 16.4.0

The existing `Go Back` and `Go Forward` commands navigate between recent points where the cursor has been. It would be great if there was an addition to these commands to navigate only between points where edits have been made (ie. ignoring points where the cursor has been but not made an edit).

I often find that I make an edit, then perform several pieces of code navigation, and then want to quickly jump back to my previous editing location. If I'm in the same file I usually do a quick undo and redo to move the cursor back to the previous editing position.

### LINKED ISSUE #133166: Support history navigation for split editors
Currently some of the history service related features do not work well for split editors:
* `forward` / `back` / `last` navigation
* last edit location

We should probably start thinking about moving the text editor specific handling in [`history.ts`](https://github.com/microsoft/vscode/blob/a91a307436c31831705a19a7c862a367145b1e11/src/vs/workbench/services/history/browser/history.ts#L109-L109) out into the respective editors which would also help for https://github.com/microsoft/vscode/issues/101779 for notebooks.

### PR DESCRIPTION
**Pull request by bpasero**
This is to investigate solutions for the following issues:
* [x] https://github.com/microsoft/vscode/issues/9526
* [x] https://github.com/microsoft/vscode/issues/101779
* [x] https://github.com/microsoft/vscode/issues/133166
* [x] https://github.com/microsoft/vscode/issues/42617
* [x] https://github.com/microsoft/vscode/issues/27112

Future work (not part of this PR):
* [x] https://github.com/microsoft/vscode/issues/45233
* [x] https://github.com/microsoft/vscode/issues/36634

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Wow, great work @bpasero 

is it ready to test out?

**Comment by bpasero** [comment]
Not yet released, only when you [run out of sources](https://github.com/microsoft/vscode/wiki/How-to-Contribute) from branch https://github.com/microsoft/vscode/tree/ben/history-tweaks

**Comment by jasonwilliams** [comment]
Seems to be working so far...

Before:
previous


After (this PR):
same-pane

**Comment by bpasero** [comment]
Yeah, specifically the identifier of the editor group of the editor is now part of the history as well and navigation goes across groups strictly following the original group the event came from. There are some implications though, for example when a editor group is removed, all entries that contributed to the history are removed as well.

I already found one issue to look at: when an editor is moved from one group to another, the history is not properly preserved.

**Comment by jasonwilliams** [comment]
> There are some implications though, for example when an editor group is removed, all entries that contributed to the history are removed as well.

This does sound about right to me though. Like when you remove a browser tab, the history that held is also gone.

**Comment by bpasero** [comment]
Yeah, it is not very consistent though because when you close an editor, we do not drop the history, at least if the editor is a text editor (and not a custom extension provided editor). So far I have not heard complaints about that though.

**Comment by bpasero** [comment]
Since I want this to be in insiders for more feedback, merging in now. Solutions for having history per editor or editor group will be a follow up.

@alexdima @hediet fyi this implements the suggestion from Alex (in https://github.com/microsoft/vscode/issues/27112#issuecomment-423294708) to expose a new `source?: string` property to methods `setSelection`, `setSelections` and `setPosition`. Please see the [`monaco.d.ts`](https://github.com/microsoft/vscode/pull/142152/files#diff-0dfa7db579eface8250affb76bc88717725a121401d4d8598bc36b92b0b6ef62) changes this brings. So far I have only added the new `navigation` type of source to a few places:
* Go to definition
* Symbol navigation
* Go to error

@jrieken @rebornix fyi this implements support for in-notebook navigation between cells as well as "Go to last edit location" for notebooks. The contract for an editor to implement is quite simple (in case you want to make the navigation even more powerful):
* signal capability by implementing `IEditorPaneWithSelection` for the editor pane
* emit a `onDidChangeSelection` whenever selection changes
* implement `getSelection` to return a `IEditorPaneSelection`
* the `IEditorPaneSelection` allows to `compare` with other selections (to figure out if selection is different) and to `restore` the selection by adding to `EditorOptions` object

**Comment by bpasero** [comment]
@jasonwilliams it should work out of the box in today's insider build: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by eamodio** [comment]
@bpasero Awesome -- can't wait to play with this too. Will this address in any way the back/forward navigation on the web? I find myself using back on the web, and I can see vscode start to jump back and then the browser back button applies.

**Comment by bpasero** [comment]
No, it does not change in anyway how navigation works in the browser.

**Pull request merged**
