### PR TITLE
ipc: use vql for uint types

### PR DESCRIPTION
**Pull request by connor4312**
On the plane I was reverse-engineering ipc.ts to implement it in Rust and see if we could have a "service mode" for the CLI that we could interact with like any other vscode process. (And maybe reuse it if we have more native processes in the future)

In doing so, I noticed that numbers in the protocol--which are used at least twice in the message header and ID--were encoded as JSON. I was curious what benefits we'd get from encoding them as variable-length integers instead.

It makes the message shorter, as expected. Encode/decode time are very, very slightly lower. I'm not sure it's worth the extra complexity, but I have included it here for your consideration.

### Encode speed

```
old length 12
old messages/s 1204819
new length 9
new messages/s 1219512
```

<details>

```ts
const encode = (serialize: any) => {
	const writer = new BufferWriter();
	serialize(writer, [201, 1234]);
	serialize(writer, undefined);
	return writer.buffer.byteLength;
};

const n = 10_000;
for (let i = 0; i < n * 5; i++) { // warmup
	encode(serialize);
	encode(serializeOld);
}

const a = performance.now();
for (let i = 0; i < n; i++) {
	encode(serializeOld);
}
const b = performance.now();
for (let i = 0; i < n; i++) {
	encode(serialize);
}
const c = performance.now();
```

</details>

### Decode speed

```ts
old messages/s 793651
new messages/s 806452
```

<details>

```ts
const newData = VSBuffer.fromByteArray([4, 2, 6, 201, 1, 6, 210, 9, 0]);
const oldData = VSBuffer.fromByteArray([4, 0, 0, 0, 2, 6, 201, 1, 6, 210, 9, 0]);

const n = 10_000;
for (let i = 0; i < n * 5; i++) { // warmup
	deserialize(new BufferReader(newData));
	deserializeOld(new BufferReader(oldData));
}
const a = performance.now();
for (let i = 0; i < n; i++) {
	deserialize(new BufferReader(newData));
}
const b = performance.now();
for (let i = 0; i < n; i++) {
	deserializeOld(new BufferReader(oldData));
}
const c = performance.now();
```

</details>

### CODE REVIEW

**Comment by connor4312** [comment]
hm, I had unit tests passing locally 😛  if there's interest I'll circle back and fix those up

**Comment by alexdima** [comment]
:+1: to doing this from my side. This particular byte-protocol is owned by @joaomoreno 

If you'd like to give it a try and optimize it too, there's a different one for the extension host [here](https://github.com/microsoft/vscode/blob/316fb895b295883dae57cc16f23ff1a29c28d818/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L693).

**Comment by connor4312** [comment]
Huh, I didn't realize that, I always assumed ipc.ts was the underlying transport. Do you recall why we have a different implementation there vs generic ipc?

**Comment by alexdima** [comment]
I don't quite remember, we kept refactoring things. I think they might have ended up in a situation where rpcProtocol.ts is built on top of ipc.ts.

**Review by joaomoreno — DISMISSED** [review]
LGTM

**Review by rebornix — APPROVED** [review]

**Pull request merged**
