### PR TITLE
add expanded support

### PR DESCRIPTION
**Pull request by alanrenmsft**
I am from the Azure Data Studio team, we had an accessibility issue: https://github.com/microsoft/azuredatastudio/issues/11551, we need to aria-expanded to the actionbar items, I think VSCode team would also benefit from it, so instead of making this change only in our repo, I am creating this PR in vscode repo.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
the build failure doesn't seem to caused by my changes.

**Comment by alanrenmsft** [comment]
@joaomoreno looks like you modified these file recently, do you mind take a look at this PR?

**Comment by alanrenmsft** [comment]
Hi @jrieken, Could you please review the PR?

**Comment by jrieken** [comment]
I don't understand the semantics here. What does expanded mean in the context of a command/action. Is that maybe a menu property.

**Comment by alanrenmsft** [comment]
@jrieken , there are multiple places where we use toolbar buttons to control the collapsed state of certain UI elements, for example, the first button controls whether the notebook cells are collapsed or expanded, and the title changes based on the state, as per accessibility requirement, we need to set the aria-expanded property.
image

**Comment by alanrenmsft** [comment]
@jrieken any update?

**Comment by jrieken** [comment]
Sorry, for the delay. The thing is that we consider actions more or less deprecated as we move to commands. So, I am not very eager to add more concepts to them.

**Comment by alanrenmsft** [comment]
ok, i will make this change in our repo.

**Pull request closed without merging**
