### PR TITLE
Set placeholder text in SourceControlInputBox

### PR DESCRIPTION
**Pull request by huizhougit**
Implement #24090

### CODE REVIEW

**Comment by huizhougit** [comment]
> 411.44s$ gulp hygiene --silent
Warning: Cannot read property 'flags' of undefined
src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts:13:13:Unused import: 'platform'
The command "gulp hygiene --silent" exited with 1.

Is it failed because of this? But my changes should be nothing about it. Why?

**Comment by huizhougit** [comment]
@joaomoreno I know this feature is not tagged as help-wanted but my extension relies on it. More important is I hope to do some contribution. Actually, this is my first contribution for vscode, even the first time for open source. Please let me know if I missed anything.

**Comment by joaomoreno** [comment]
@huizhougit You're not supposed to automatically translate strings. Can you recreate this PR without those translations?

**Comment by huizhougit** [comment]
@joaomoreno Do you mean I should not change any of the json files?

**Comment by joaomoreno** [comment]
@huizhougit Exactly.

**Comment by huizhougit** [comment]
@joaomoreno  It's updated

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
