### PR TITLE
On Type Rename for #88424

### LINKED ISSUE #88424: Improve mirror cursor implementation with Synced Regions
Although some people like mirror cursor, it currently has issues. Many of these issues are existing behavior of multi-cursor. Some are hard to change, some can only be worked around in sophisticated ways, and some can only be fixed by code in vscode core.

- Pasting creates unwanted content at HTML closing tag #87067
- Duplicate line creates two lines #87161
- Pasting create contents at two places #88072
- Multi cursor doesn't work nicely with mirror cursor #88127
- When inserting space at `<h1|></h1>`, it creates 2 edits on undo stack  #87732

UI wise, it has issues as well:

- It's confusing which cursor in the main cursor
- Content changes can happen outside viewport, and there's no indication
- The multiple cursors aren't shown in scrollbar/minimap

And in my own experience, it doesn't play nicely with Vim extension.

In short, multi-cursor was the closest we could get to auto rename tag. We had to choose it because it's the only option for making 2 changes with 1 document edit. But it's not exactly the behavior people want (people want changes reflected in the mirrored region, **not** adding one more cursor).

Additionally, people has expressed interest in having mirror cursor for JSX: #85707
And we think it would be pretty cool, if this works for loop variables, function params, etc. For example:

```js
for (let i|=0; i| < 10; i|++) {
  count += i|
}
```

To fix the issues, and to make this feature available to more languages, @alexdima, @jrieken and I think it's best to add a new editor concept, **synced regions**. It would work this way:

- We introduce an API, `OnTypeRenameProvider`
- When cursor moves in a doc, VS Code asks this provider for a list of ranges
- These ranges are marked as in sync
- Any content change (type, delete, paste) will cause all other synced regions to update in one edit
- We can have a setting to switch between `semi-automatic` (press a shortcut to enter this mode) and `full-automatic` (like current mirror cursor).

### PR DESCRIPTION
**Pull request by octref**
This fixes #88424.

- Adding editor option `editor.renameOnType`
- Adding proposed API `languages.registerOnTypeRenameProvider`
- Adding `onTypeRenameProvider` for HTML

Proposed API:

```ts
namespace languages {
	/**
	 * Register a rename provider that works on type.
	 *
	 * Multiple providers can be registered for a language. In that case providers are sorted
	 * by their [score](#languages.match) and the best-matching provider is used. Failure
	 * of the selected provider will cause a failure of the whole operation.
	 *
	 * @param selector A selector that defines the documents this provider is applicable to.
	 * @param provider An on type rename provider.
	 * @param stopPattern Stop on type renaming when input text matches the regular expression. Defaults to `^\s`.
	 * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
	 */
	export function registerOnTypeRenameProvider(selector: DocumentSelector, provider: OnTypeRenameProvider, stopPattern?: RegExp): Disposable;
}
```

I think most of the cases work fine. There are 2 failing tests but I'm not sure why they happen, since the behavior in the editor is correct but the test still fails.

The two cases that's failing in the editor are:

- Option + Delete and then undo for `<div|></div>`
- Paste (with content `div`) and then undo for `<div|></div>`

The cause seems to be that setting `EditorOperationType` doesn't work for paste/delete-word.

But other than that, this seems to work fine. I'm planning to put it in insiders and turn it on for people who have enabled `html.mirrorCursorOnType`.

### CODE REVIEW

**Review by alexdima — APPROVED** [review]
Looks good! I just left a few comments.

**Comment by alexdima** [comment]
@octref There is still the problem of the Ctrl+F2 conflict, and some tests that need to be skipped. :+1: Otherwise, please merge.

Any other work in HTML to adopt this feature should IMHO be done in another PR.

**Comment by IllusionMH** [comment]
With

> Take HTML implementation out    600a776

does it really closes #88424 or it should be closed with HTML implementation merged?

**Comment by octref** [comment]
@IllusionMH I pushed https://github.com/microsoft/vscode/commit/01e01b13f88064374ebc5aa789cb0ee76d03a17c

**Pull request merged**
