### PR TITLE
Make ~/.config the default app data path if process.platform is neither win32 nor darwin

### PR DESCRIPTION
**Pull request by rowheel**
See: https://github.com/coder/code-server/issues/5741
See: https://github.com/coder/code-server/issues/5496

### CODE REVIEW

**Review by deepak1556 — COMMENTED** [review]
Does the server in general work well on FreeBSD ? We might have other `process.platform` checks that might not cover FreeBSD, not sure we can change them all.

**Review by bpasero — CHANGES_REQUESTED** [review]
I am not convinced this is good, if there is a new platform that so far we did not support in our code we likely have a lot more places where we would have to change this.

**Comment by rowheel** [comment]
Hi deepak1556,

Yes, of course it works **good** in general, and even without this change I proposed here, the issue can be worked around by explicitly setting VSCODE_APPPATH environment variable before launching code-server (which I personally instructed so in our own FreeBSD cookbook).

In fact, most parts of vscode can be just compiled and running as-is on FreeBSD, except the Terminal part which I believe has been requiring manual workaround for quite a long time.

Looking into the source code:

- `src/vs/platform/environment/node/userDataPath.d.ts` exports `getUserDataPath`

which is called by:

- `src/vs/platform/environment/node/environmentService.ts` exports `NativeEnvironmentService`

and then is used in:

- `src/vs/platform/terminal/node/ptyHostMain.ts` as `environmentService`

On FreeBSD `getUserDataPath` would throw an exception during the construction of `environmentService` which is the direct cause of non-functioning Terminal on FreeBSD (as well as any other platforms not listed in the switch cases there)

Before the node-pty issue was introduced on FreeBSD (which I believe it should have been addressed now. Thanks again for acceptting that fix!), members of Coder community have written a dirty sed patch that directly changes `process.platform` to `linux` in order to work this whole exception chain around... which turns out to be working (facepalm).

https://github.com/coder/code-server/issues/5496#issuecomment-1240839804

Later they learned they can put a VSCODE_APPDATA environment varible to avoid hitting the default case there, too.

However, personally I don't think having to keep WA is a good idea, so I want to do something for it to be addressed for good.

Hi bpasero,

I admit that changing the `linux` case to `default` case there can be too agressive... would it be acceptable if I change the logic there to something like "if platform is linux or freebsd then"?

**Comment by deepak1556** [comment]
I am good with a change that adjusts for `FreeBSD` only as long as it is tested to work. I will incline to @bpasero decision as he owns this component.

**Comment by bpasero** [comment]
I am still not sure how it would solve my concern. We do not officially support `FreeBSD` as far as I know, so we either make a push to support it in all of our code or keep it on the list of unsupported OS 🤔

**Pull request closed without merging**
