### PR TITLE
Retain maximized group size when adding and removing groups or toggling side bar

### LINKED ISSUE #70083: Maximize editor group auto sizing stops working after closing the sidebar
When maximizing an editor group and switching between groups, the focused group will maximize. After opening or closing the sidebar, the maximizing stops happening. I have had this happen on linux as well.

Version information

Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:15:00.418Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Steps to Reproduce:

1. Open two tabs and place them in different editor groups
2. Maximize editor group
3. Switching between editor groups makes the focused group maximize
3. Open sidebar
5. Close sidebar
6. Switching between editor groups doesn't maximize focused group.

Does this issue occur when all extensions are disabled?: Yes

Gif of bug:

error

### LINKED ISSUE #137865: Preserve maximized state when opening new groups
Issue Type: <b>Bug</b>

when I split the editor vertically (ctrl-1, ctrl-2), I like to double-click the editor tab so the focused editor gets most of the space. When I split further (ctrl-3), this focus mode (I can't find what its called) breaks, and all editors get equally sized again

I would like for this focus mode to persist when I add an extra editor to the side, such that it gets focus and the most screen space.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.15GB free)|
|Process Argv|--crash-reporter-id c6c5437a-40c6-47c7-be15-d0b53324bfd2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|12.42GB (4.20GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
jinja|who|0.0.8
vscode-django|bat|1.6.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
autodocstring|njp|0.5.4
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246cf:30401891

```

</details>

### PR DESCRIPTION
**Pull request by ssigwart**
This PR fixes #137865
This PR fixes #70083

When an editor group is maximized, the active group will remain maximized as you add and remove splits or toggle the side bar.

### CODE REVIEW

**Comment by joaomoreno** [comment]
The SplitView already supports layout priorities. Could the EditorPart fix this by using layout priorities? Eg: when a view is maximized, set its priority to `High`.

**Comment by ssigwart** [comment]
Thanks for the quick review, @joaomoreno.

There is no setter for priority.  I could add one and update `GridView.maximizeViewSize` to set the priority, but then I'd need to reset the priority on the other views here:
https://github.com/microsoft/vscode/blob/1195fdb3ef6009976b46fd157aab028b7b887277/src/vs/base/browser/ui/grid/gridview.ts#L1429-L1431

However, I don't think I can set it back to `LayoutPriority.Normal` because I don't know if that was the original setting.  I can add another variable for the initial setting, but that's another variable to store.  Even after that, I don't think setting the priority work because the priorities are used in the following flow, but in this case, we already have proportions:
https://github.com/microsoft/vscode/blob/1195fdb3ef6009976b46fd157aab028b7b887277/src/vs/base/browser/ui/splitview/splitview.ts#L741-L747

So I think I'd still need to update the following anyway:
https://github.com/microsoft/vscode/blob/b9cf83f70bb6b4697b544a97c7056dfd28fccc5f/src/vs/base/browser/ui/splitview/splitview.ts#L747-L752

It's possible that I could revert adding the following code if I set the priority.
https://github.com/microsoft/vscode/blob/1195fdb3ef6009976b46fd157aab028b7b887277/src/vs/base/browser/ui/splitview/splitview.ts#L1208-L1209

However, I'm not sure if it's worth having to add a getter and save the original priority.  What do you think?

**Comment by joaomoreno** [comment]
The grid/splitview can't modify priority, they only read the value. The views themselves set it. The user of the grid (EditorPart) would coordinate across its views and set their priorities accordingly.

**Comment by ssigwart** [comment]
Thanks for all the details, @joaomoreno.  I tried looking into it, but I'm not all the familiar with the code, so I didn't make it too far.  I'll try to work on in over the next week.  For both issues, I probably still need to add a function to determine if there is a maximized view first, right?  For #70083, I'd need to check that if `DisabledWhenViewMaximized` is set.  For #137865, I'd need to know that to know if I should set `Sizing.Distribute` or not.

For #70083, essentially, I would keep the following code, but only use it if `DisabledWhenViewMaximized` is set, right?
https://github.com/microsoft/vscode/blob/1195fdb3ef6009976b46fd157aab028b7b887277/src/vs/base/browser/ui/splitview/splitview.ts#L748-L763

For #137865, what do you think of adding `Sizing.Maximize` and then adding code in `doAddView`  to update the sizes?
https://github.com/microsoft/vscode/blob/0cc0904c565399781defa830facf43141db8b6f3/src/vs/base/browser/ui/splitview/splitview.ts#L970

**Comment by joaomoreno** [comment]
Hm... After sleeping on it, I'm not entirely sure of my suggestions any more. Your initial PR might actually be a good option moving forward. 🙈

Let's do this: let's add test cases for the new splitview behavior you introduced in this PR.

**Comment by ssigwart** [comment]
I added test for this.  Noting mainly for myself that I can run them with these commands:
```bash
./scripts/test.sh --glob **/editorService.test.js
./scripts/test.sh --glob **/splitview.test.js
```

I wasn't positive if I put the test for #137865 in the right spot, so please let me know if I should move it.

I'm pretty new to VS Code and have gotten a grasp of some things enough to fix some things, but don't have a full understanding of the VS Code internal code structure.  Is there any documentation I can read on that?  In particular, I'm not really sure what the "workbench" vs "editor grid" vs "splitview" terms all mean?

**Comment by ssigwart** [comment]
@joaomoreno, do you need me to do anything else on this?

**Comment by joaomoreno** [comment]
No need for anything else... just need to time to properly look into it. Sorry about that.

**Comment by ssigwart** [comment]
No problem.  Thanks.  Just wanted to be sure I didn't miss something.

**Comment by ssigwart** [comment]
I merged main and cleaned up the failing tests after that.

**Review by joaomoreno — DISMISSED** [review]

**Comment by joaomoreno** [comment]
I'm very **very** sorry to only pick this up right now.

I've found the following issues:

- When a single group is open, opening a file on the side will now make that group maximized.
- When three views are open, one is minimzed and the rest of space split between the other two, the proportional resize will still _stretch_ the minimized view.

While these issues could be fixed with the proposed approach, I went a different direction. I made `proportionalLayout` a property of each view. That way, the editor group views can claim not to be a part of the proportional layout algorithm, whenever they are minimized. This is simpler to maintain and understand than the original proposed change of this PR. This fixes #70083.

Additionally, I also made sure to maximize new groups if the reference group was maximized. This fixes #137865.

I'll push my changes on top of this PR so we still have you as a contributor, thanks so much for your patience and passion @ssigwart. 🍻

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by ssigwart** [comment]
Thank you, @joaomoreno!

**Pull request merged**
