### PR TITLE
Offset contextmenu by 2px

### LINKED ISSUE #57399: Improve context view placement around box
On Linux.

If I open the editor context menu in a small enough window, the action right below the mouse cursor will be executed instantly, since the change that makes an action run on mouse up. We should nudge the menu 1px to the side (to the right when on the right side, to the left when on the left) in order not to have the menu right below the mouse cursor.

It doesn't repro if the window is large enough since the menu will be 1px nudged down in that case.

### PR DESCRIPTION
**Pull request by bpasero**
Fixes https://github.com/Microsoft/vscode/issues/57399

### CODE REVIEW

**Review by sbatten — COMMENTED** [review]
Won't this break if the menu ends up being drawn to the left?

**Comment by bpasero** [comment]
@sbatten I have to check, but this is literally the same code we use for native context menus too.

**Comment by sbatten** [comment]
@bpasero I might be wrong, but I think it isn't an issue in native because the menu can be drawn to the right and down in almost all cases because the menu can be drawn outside the window. You might be able to test on Linux if the issue arises in fullscreen clicking in the bottom right?

**Comment by bpasero** [comment]
This is not a good fix for the reasons mentioned.

**Pull request closed without merging**
