### PR TITLE
Change American time format to ISO time format

### LINKED ISSUE #140434: Dates on extension page use American format regardless of display language
The 'Last updated' and 'released on' dates on the extension page use the American format. This is confusing to many people.

> Last updated 12/3/2021

image

I tried [changing the display language](https://code.visualstudio.com/docs/getstarted/locales) to Spanish and German, but the problem remains:

image

image

Consider using a unambiguous date format such as yyyy-mm-dd (ISO 8601)

### PR DESCRIPTION
**Pull request by icepaq**
This PR fixes #140434

**How to Test**

1. Go to the extensions tab
2. Search for an extension (eg "Prettier")
3. Ensure that the "Released on" and "Last updated" fields follow a YYYY-MM-DD, HH:MM:SS format.

### CODE REVIEW

**Comment by icepaq** [comment]
Before
image

After
image

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by aifreedom** [comment]
Instead of supporting only ISO format, can we make it follow the datetime format set in the OS settings?

**Comment by icepaq** [comment]
> Instead of supporting only ISO format, can we make it follow the datetime format set in the OS settings?

@aifreedom I briefly looked into this. It should be doable. But not an necessarily an easy task.

**Comment by aifreedom** [comment]
Or can we get the locale from VS Code (https://code.visualstudio.com/docs/getstarted/locales) and format the date to string using `Date.prototype.toLocaleDateString()`?

**Comment by icepaq** [comment]
@aifreedom Good idea!

**Comment by aifreedom** [comment]
@icepaq are you going to update this PR to do it that way? Or if you don't have time, I can open one.

**Comment by icepaq** [comment]
@aifreedom  Yeah feel free to take over this issue. Although I'd suggest keeping this in the same PR just because this has a bit more of a track record.

**Comment by aifreedom** [comment]
I don't think I can update this PR because that requires permission to push to your branch. I'll give it a try. If no luck, I'll reference this PR in the new one I will open.

**Comment by sandy081** [comment]
Closing this in favour of https://github.com/microsoft/vscode/pull/150133

**Pull request closed without merging**
