### PR TITLE
Implement WiX based MSI setup

### PR DESCRIPTION
**Pull request by alexhass**
I've created the MSI setup of Visual Code. Compared to the InnoSetup it allows users to select file associations. This is required for AD deployment if the admin do not like to assign every file extension. This means this setup introduced an important new feature.

### CODE REVIEW

**Comment by yamlfd** [comment]
Let me note that German translation is included and complete. The others are not.

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Can you remove all the licenses from this? You should only leave behind this English license: https://github.com/Microsoft/vscode/blob/master/LICENSE.txt

Also, we have a whole different process for translations, which we would need to adopt in the WiX setup. Please remove all translations and just leave English behind.

**Comment by yamlfd** [comment]
WiX need an RTF license file. It cannot work with the default txt file. If you do not like to take the files over you can remove them on commit, but need them later for setup build.

If i remove the translation files the batch script stops working as files are missing. I‘m not aware of this process. How does it work and how are the translation files generated than? Is another undocumented script needed?

This patch is fully working. It is not just 50% of what is needed to build the setup like the innosetup. Should I break it now?

**Comment by joaomoreno** [comment]
[This is not our MIT license](https://github.com/yamlfd/vscode/blob/a85840a6ae97a26103bba16bff6b663ab5594ed9/build/wix/Resources/licenses/license.en-us.rtf). If it needs an RTF, feel free to provide an RTF **only** containing our MIT license: https://github.com/Microsoft/vscode/blob/master/LICENSE.txt. Or even better, an empty RTF.

We don't have our localisation story documented unfortunately, but we need to be able to extract strings and send it over to an external service for translation periodically. So, if you could just provide the English version, I'll pick it up and integrate it.

**Comment by yamlfd** [comment]
The MIT license from project root is in `/build/wix/Resources/licenses/license.rtf`. If you leave all the other license files outside - it is a copy&paste from the project root as RTF file.

The english translation file is `/build/wix/Lang/code.en-us.wxl`. If you do not like the other translation files just delete them, please. But do not wonder that the build.cmd can no longer build the MSI.

**Comment by jcasale** [comment]
The WIX [UI extension](http://wixtoolset.org/documentation/manual/v3/wixui/wixui_customizations.html) includes a [license file](https://github.com/wixtoolset/wix3/blob/develop/src/ext/UIExtension/wixlib/License.rtf), you can ignore it (and the related property) and re-sequence the dialogs in order to prevent displaying it.

**Comment by yamlfd** [comment]
But the setup need to show the license dialog... the current setup also does. I have implemented it like the current inno setup + better file association per file type. 

I do not really understand why I should implement or share just 50% of required files. Open source should be self containing and *complete*. It is not useful to destroy the installer and share half of the setup with the community. This disallow the community to build the setup.

**Comment by joaomoreno** [comment]
I will not merge a commit containing license files from an external source. That is just asking for legal trouble.

If you don't remove these things from the commit history, we'll still use all your work, but the PR won't be merged. You'll still get a thanks in the release notes, though. If that works for you, then you don't need to do anything.

**Comment by yamlfd** [comment]
This was the first fork and pull request on github in my life and it was no fun for me. I will try to update my pull and hopefully it is ok than.

**Comment by yamlfd** [comment]
How strange... Why does a repository hard reset close a case? I hope this patch is now good to go.

**Comment by yamlfd** [comment]
I'm also attaching the not committed language XML files here as it took some efforts to figure out the correct code pages and encodings. Especially japanese and chinese was not clear to me first. German strings are already translated.

[Lang.zip](https://github.com/Microsoft/vscode/files/1503020/Lang.zip)

**Comment by alexhass** [comment]
Now my user reference to the commit should be correct.

**Comment by alexhass** [comment]
Fixed code style issues.

**Comment by joaomoreno** [comment]
@alexhass As you see we have 109 PRs open. Please be patient.

**Comment by alexhass** [comment]
Added a new commit with two missing image files.

**Comment by alexhass** [comment]
@joaomoreno how are you making progress on this issue? It is now 3 months lingering here around. Can you commit the setup, please?

**Comment by alexhass** [comment]
This sounds extreme bad. I absolutly need an MSI Installer. Shit exe setups need to die. They cannot deployed via AD. This means the software is not enterprise ready.

I‘m not a lawer. Getting in conflict with ms is no option. Please provide the stuff that we need. Ms normally always provides msi setups. Why are you not doing this???

Please put some priority on this case. There are a lot of people who ***need*** it.

**Comment by totegi** [comment]
So the solution to this issue is laying around for over half a year now. Not being able to give dev's the tools they need is frustrating. Please add this to the plan.

**Comment by joaomoreno** [comment]
Sorry @alexhass, will have to close this, it's just not in our roadmap: https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests

**Comment by alexhass** [comment]
Thanks for the waste of time. How should we deploy the software now????????????????!

**Comment by alexhass** [comment]
@joaomoreno : People need this, Put this on your roadmap, please. There is no workaround possible. GPO can ONLY deploy MSI. Now I need to also block your sh** per User installer just because you have no idea about roaming profiles.

Are you beginners really from MS?

**Comment by compuguy** [comment]
I understand that @joaomoreno is against making a msi installer for VScode, but there are some environments where this is a necessity for deployment when pushing out software via GPO.

**Comment by snow8gaia** [comment]
can these changes be easily applied to https://github.com/VSCodium/vscodium/ or will it need updating and vscodium specific workarounds?

**Comment by alexhass** [comment]
Yes, can be done easily.

**Comment by alexhass** [comment]
I was not aware of vscodium. Would love to help getting it out of the door.

Do you know if and how we can disable automatic update in vscodium?

**Comment by snow8gaia** [comment]
tested on a fresh install of vscodium(1.35.1).


<details>

<summary>text </summary>

<p>

# in vscodium or vscode, 
# click on gear icon( bottom left corner)> click Settings> click Application> click Update>click 'Enable Windows background updates.'
</p>
</details>


images **(app theme:dark)**

<details>

<summary>1</summary>

<p>

part1

</p>
</details>

<details>

<summary>2</summary>

<p>

part2

</p>


</details>


<details>

<summary>3</summary>

<p>

part3

</p>
</details>


<details>

<summary>4</summary>

<p>

part4

</p>
</details>

<details>

<summary>5</summary>

<p>

part5

</p>
</details>

<details>

<summary>6</summary>

<p>

part6

</p>
</details>

<details>

<summary>7</summary>

<p>

part7

</p>
</details>

**Comment by snow8gaia** [comment]
## this may work.
from https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates->

  "update.mode": "none"
```json
  "update.mode": "none"
```

**Comment by alexhass** [comment]
A per machine setting is required for auto update. The one you found is a per user setting and does not work well.

**Comment by Hickory420** [comment]
A vbscript workaround for deployment in AD GPO here #33184 
I know it's far from ideal, but it gets the job done.

**Pull request closed without merging**
