### PR TITLE
Fix `--do-not-sync` server argument is ignored when installing extension

### LINKED ISSUE #148011: `--do-not-sync` server argument is ignored when installing extensions
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: insiders and from sources

Steps to Reproduce:

1. Ensure you have settings sync already enabled or run server and enable settings sync
2. Run server again with `./scripts/code-server.sh --without-connection-token --install-extension znck.vue --do-not-sync --start-server`
3. :bug: Observe extension `znck.vue` gets synced

cc @sandy081

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #148011

cc @sandy081

### CODE REVIEW

**Comment by jeanp413** [comment]
@sandy081 couldn't this be merge for this release? it's a bad regression as it breaks extension sync in Gitpod/Codespaces, all extensions in gitpod.yml/devcontainer.json will get synced for every workspace/codespace

**Comment by jeanp413** [comment]
Seems to be mitigated by https://github.com/microsoft/vscode/commit/e428b0bc9f535cdb0ecb9850cc5d30a514ee19a7 but this PR changes still makes sense as we should use `delete` instead of set to `undefined`

**Comment by sandy081** [comment]
Closing this since it is fixed by e428b0bc9f535cdb0ecb9850cc5d30a514ee19a7.

**Comment by jeanp413** [comment]
This changes still makes sense as you can still reproduce in this case:
- install extension using vsix with `--do-not-sync` disconnected from the internet for some X reason
- connect to internet, run server, and open in browser
- extension will be synced

**Comment by sandy081** [comment]
I see. Reopening it for above case.

**Pull request closed without merging**
