### PR TITLE
Fix for #49138

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes issue #49138

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@gushuro Do you want to take a look at this first before I dive in?

**Comment by gushuro** [comment]
Sure!

**Review by gushuro — COMMENTED** [review]
Besides a couple small comments, LGTM
Tested a few cases and it works fine.

**Review by ramya-rao-a — APPROVED** [review]
Thanks @jeanp413

**Pull request merged**
