### PR TITLE
Force keybindings header to behave differently from rows

### LINKED ISSUE #41558: Keybindings editor header problems
1. It changes on hover the same exact way as rows
Expected for it to stay the same
2. On click the 1st row is selected
Expected for it to do nothing (or sort columns..., the point is - the current behavior is mostly confusing)

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #41558

Header was reacting to L/M/R mouse clicks and touch events. Now it doesn't.

The only questionable thing is focus border around `.monaco-list:focused` when you click on header after input.

### CODE REVIEW

**Comment by sandy081** [comment]
@usernamehw Thanks for the fix. But instead of doing some CSS hacks I would suggest to render the header separately by removing it out from the list. This will be helpful if we want to implement sorting by clicking the header

**Comment by usernamehw** [comment]
Adding a header is not a problem, removing one...

I got an error from `RowCache`
https://github.com/Microsoft/vscode/blob/1b77525993ccdd82a40b7a4e3ba874c5a2eb7a5a/src/vs/base/browser/ui/list/rowCache.ts#L40
```javascript
"Cannot read property 'renderTemplate' of undefined"
```
Does `RowCache` auto clears on vscode update? Is there a way to clear it once? Any other way?

**Comment by sandy081** [comment]
@usernamehw I meant to implement the header separately without making it part of List widget.

**Comment by usernamehw** [comment]
@sandy081, That's exactly what I did. When you delete the header - the entire list no longer renders. Deletion from here:
https://github.com/Microsoft/vscode/blob/21cf602a6e1761edbce55474c20357fd482159ff/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L335

Removing `new KeybindingHeaderRenderer(),` from the line above results in RowCache error - list not rendered at all.

I will push a commit then, it's just before header deletion from the list; New header is added, old header not possible to remove for me. This is not a finished version, stopped right after error encountered.

**Comment by sandy081** [comment]
@usernamehw You have to remove the code that populate header elements in the list. Ref: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L388

**Comment by usernamehw** [comment]
Should I close this?

**Comment by sandy081** [comment]
@usernamehw Not yet merged. May I know if your changes are complete to review?

**Comment by usernamehw** [comment]
Hope so. The last commit was ~2 month ago. I don't even know if this code is working now.

**Pull request closed without merging**
