### PR TITLE
Support greater than and less than

### PR DESCRIPTION
**Pull request by Wscats**
Hope `contextkey.ts` supports greater than and less than, to facilitate the extension of features.

### CODE REVIEW

**Comment by roblourens** [comment]
Is there an issue for this feature?

**Comment by Wscats** [comment]
> Is there an issue for this feature?

With a small change here, a more precise and simple comparison can be made, and the extension can be more flexible.

```js
"menus": {
      "commandPalette": [
        {
          "command": "git.close",
          "when": "config.git.enabled && !git.missing && gitOpenRepositoryCount > 0"
        },
        {
          "command": "git.refresh",
          "when": "config.git.enabled && !git.missing && gitOpenRepositoryCount > 0"
        },
}

"viewsWelcome": [
      {
        "view": "scm",
        "contents": "%view.workbench.scm.workspace%",
        "when": "workspaceFolderCount > 2",
        "group": "5_scm@1"
      },
]
```

**Comment by alexdima** [comment]
Thank you!

**Comment by Wscats** [comment]
haha, I finally waited for you😁

**Pull request merged**
