### PR TITLE
Allow to select text while jumping between brackets

### PR DESCRIPTION
**Pull request by chewong**
#9768

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
@chewong Thank you for your contribution. 
I don't think it is a good idea to **change** the existing implementation of `jumpToBracket`, as many folks want to simply jump to the matching bracket and are used to the current command's behaviour.

I believe another command should be introduced, similar to the code path of `jumpToBracket`, but which is `selectToBracket`. This new command can have the behaviour of selecting to the matching bracket. The new command should have its own separate test.

**Comment by chewong** [comment]
@alexandrudima thanks for the feedback. To introduce a new command, does that mean creating `selectToBracket()` method within `BracketMatchingController`, or should I create a new file for it?

**Comment by alexandrudima** [comment]
Yes, a new method `selectToBracket()` makes sense. And a new action, similar to the improperly named `SelectBracketAction` class. Perhaps the `SelectBracketAction` can be renamed to `JumpToBracketAction`. I am sorry for the bad name of this action, perhaps that's what led you to change its behaviour to be selecting.

**Comment by chewong** [comment]
@alexandrudima Couple questions:
1) Do we also want to select the brackets as well?
2) There seems to be a bug when I perform selecting text and setting the position of the cursor. Without selecting text, I can keep pressing cmd-shift-\ to switch from open brackets to close brackets and vice versa. But with selecting text, the cursor is only able to go from open bracket to close bracket but not the other way. Is this intended?

Thanks

**Comment by alexandrudima** [comment]
@chewong 
1. I don't have a good answer. What do other editors do when running a similar command?
2. This sounds like a bug in the new code. Otherwise, it might be related to cases where there are touching brackets. e.g. `var x = ((3 + 5)*6);`. The position between the two `(` is ambiguous and today we have a certain preference, I believe we will choose to match the second `(` (the one to the right).

**Comment by chrisdavies** [comment]
@chewong I'd like this functionality, and I vote for selecting the brackets as well. I'm often trying to yank code, which generally includes the brackets.

**Comment by alexandrudima** [comment]
Closing as this appears to be abandoned.

**Pull request closed without merging**
