### PR TITLE
Fix: webview focus status block navigation action

### LINKED ISSUE #111381: Markdown Preview screen does not respond to keyboard shortcuts
- VSCode Version: 1.51.1
- OS Version: Linux x64 5.4.0

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

Steps to Reproduce:

1. Open a file with Markdown in it
2. Open the Markdown preview pane to the right side of your Markdown file
3. Click the Markdown preview pane to focus it
4. Press ctrl+shift+p to open the `Show All Commands` bar
5. Execute the command `View: Navigate to the View on the Left`
6. Notice that nothing happens 

Does this issue occur when all extensions are disabled?: Yes

Expectation: The commands from the `Show All Commands` bar should work in the `Markdown Preview` window (and also the keyboard shortcuts of those commands).

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #111381

According to the comment in [keybindingService.ts#L361](https://github.com/susiwen8/vscode/blob/master/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L361) `document` would lost focus when there were `webview` element. So false negative would block process. 

So I have add `isWebviewFocused ` to mark weather a `webview` element were focused. 

Kapture 2020-12-25 at 22 20 30
Kapture 2020-12-25 at 22 22 26

Those gifs shows that `View: Navigate to the View on the Left/Right` and `key chord` for navigation to left/right work with `markdown preview`

### CODE REVIEW

**Review by mjbvz — CHANGES_REQUESTED** [review]
I'm not in favor of adding this to core layout check unless it is absolutely required (I also don't think the current implementation is correct, since hasFocus will now return true if `isWebviewFocused` is ever called, regardless of part).

Instead, try looking at the implementation of the navigation command:

https://github.com/microsoft/vscode/blob/4e1eff7083ddd34a141d21c775f74e405338e56b/src/vs/workbench/browser/actions/navigationActions.ts#L37

to see why the webview editor is not considered focused after running the command.

**Comment by susiwen8** [comment]
> const isEditorFocus

@mjbvz Thanks for the tip, I'll look it up

**Comment by susiwen8** [comment]
@mjbvz When command panel was open, `webview` would lost focus, then `activeElement`  would be the `body` which meant no element was currently focused.
Screen Shot 2021-01-10 at 11 00 59

**Comment by susiwen8** [comment]
@mjbvz Hi, `document` would lost `focus` if there were `webview`, so I suggest using electron native `isFocused` instead of `document.hasFocus()`
[isFocused](https://www.electronjs.org/docs/api/browser-window#winisfocused)

**Comment by mjbvz** [comment]
I think the WebView should be refocused when the command palette closes, so try checking to see why the webview does not have focus. I suspect it may be related to this code we added to work around another issue:

https://github.com/microsoft/vscode/blob/d8a3dd44be13762f1a2125d82fcc8d54b5c24e9a/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L253

**Comment by susiwen8** [comment]
> I think the WebView should be refocused when the command palette closes, so try checking to see why the webview does not have focus. I suspect it may be related to this code we added to work around another issue:
> 
> https://github.com/microsoft/vscode/blob/d8a3dd44be13762f1a2125d82fcc8d54b5c24e9a/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L253

Ok, pursuing

**Comment by susiwen8** [comment]
@mjbvz Well, I can confirm webviewElement.ts#L253 cause this issue
>https://github.com/microsoft/vscode/blob/d8a3dd44be13762f1a2125d82fcc8d54b5c24e9a/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L253

it looks like `command palette` won't be close instantly when focus on `webview`(#75209), so we can blur ` active element` and focus `webview`  synchronous.

**Comment by susiwen8** [comment]
@mjbvz Hi, any suggestions?

**Comment by mjbvz** [comment]
Did you test to make sure this would not regress #75209 +  #93950?

**Comment by susiwen8** [comment]
For #75209

https://user-images.githubusercontent.com/20318608/104794723-7c082280-57e4-11eb-8460-7d146b31d40e.mp4


https://user-images.githubusercontent.com/20318608/104794845-54fe2080-57e5-11eb-8fad-37db9f091fb2.mp4

For #93950 I'm not able to find `show all task...` command in my command pannel

**Comment by susiwen8** [comment]
@mjbvz Hi, any more suggestion?

**Comment by susiwen8** [comment]
@mjbvz I think this PR should separate into tow PRs , because it relates two problems
- `hostService` `focus` status should not depend on `document` due to `webview`, using [win.isFocused](https://www.electronjs.org/docs/api/browser-window#winisfocused) is the right way.
- The timing of refocusing to `webview` after `quick pick` close. I'm not confident on this even I have tested it.

So, should I close this one

**Pull request closed without merging**
