### PR TITLE
Fix #48973 - allow hovering variables using the spread operator

### LINKED ISSUE #48973: Debug hover doesn't work with spread operator
Debug code like

```ts
arr.push(...veryLargeArray);
```

- Hover `veryLargeArray`, nothing shows up.
- Other hovers work fine.

### PR DESCRIPTION
**Pull request by roblourens**
There's no natural way to do this in the regex, as far as I know.

Do any unit tests cover this?

### CODE REVIEW

**Comment by isidorn** [comment]
@roblourens thanks for you PR.
However with this we are leaking the knowledge of a spread operator into the `debugHover`. I know we already leaked some knowledge of ->, . and so on but I do not like that already.
I would prefer if somehow the debug adapter could contribute these special symbols.
If we decide that we want to make a special case for the spread operator that is fine by me, but I would prefer a proper solution if something is in reach.

There are no unit tests covering this, however I will change that right now. Sorry that might create conflicts with this branch but that should be easy to fix.

fyi @weinand

**Comment by isidorn** [comment]
Again appologies for the conflicts. Now there are unit tests d7955610d4

**Comment by weinand** [comment]
We do not want to have language specific knowledge in the generic debugger UI.
So if we need specific logic for a hover, we will have to find a proper solution.

**Comment by roblourens** [comment]
> We do not want to have language specific knowledge in the generic debugger UI.

I agree, but that's how the entire feature works right now. We should either make the debug adapter tell us how to interpret patterns for hover, or this particular case could be handled by the debug adapter. Since we eval hovers, I can strip the ... myself.

Or to keep this in vscode in a less language-specific way, maybe the problem is that we want to capture patterns like `a.b.c` specifically, but we are also capturing `a..b` or `.....a.b....` etc, we could narrow it down to a single `.` between two words.

**Pull request closed without merging**
