### PR TITLE
Fixes #32264 - Allow N instances of the same task

### LINKED ISSUE #32264: No option to automatically terminate previous task when a new instance of the same task is started
- VSCode Version:  1.14.2
- OS Version: Windows 10 Creators Update

This is just a suggestion. 

Almost all IDEs allow us to set a 'Single Instance Only' option, When this option is true, And you try to run a task that is already running, It'll kill the running task and then restart it.

VS Code gives an error stating that the task is already running, go to F1->Terminate Task to terminate the task.
This gets really annoying on some machines where to access Function keys, You also need to hold down a separate  "Fn" key. 

My suggestion is to let people specify a `SingleInstanceOnly` option in `tasks.json`, If this option is true, then instead of giving an error to user, It should kill the existing task and restart it. 
And if this option is false, Then just do what it does currently.
Default value should be `false`, So, Only the people who really need this option can set it and others will see the usual behavior 

And, I'd like to work on this, if that's okay. 

Regards 
Ishan

### PR DESCRIPTION
**Pull request by alpalla**
# Summary
* These changes allow N instances of the same task to be run simultaneously.
* The maximum number of allowable instances can be set in `RunOptions`.
* The instances of a task are visible in the QuickPick with an ` (i)` appended to the quick pick entry label to indicate that the task is an instance of an already running task. 
For example if 3 instances of task `foo` are running, the QuickPick would display:
```
foo
foo (1)
foo (2)
```
# Implementation notes
## Distinguishing between multiple instances of the same task
When a task is run in `terminalTaskSystem`, if another instance can be created, the task that the user selected is cloned and its `id` is modified to have form `<ORIGINAL_TASK_ID>|<COUNTER>`.
The counter gets incremented each time an instance of the same task is created. The cloned task is then run like any other task.
This makes it possible to check if a task is an instance of another task because all instances of a task will have the `<ORIGINAL_TASK_ID>` substring in common in their respective ids.
## Tracking multiple instances of the same task.
The `<ORIGINAL_TASK_ID>` substring shared by all instances serves as the key in a dictionary where the value is an `InstanceManager` object that stores information related to all instances of a task such as the number of currently active instances.

## How to test changes
Create a `tasks.json` and set the `instances` property. Here is an example configuration:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "sleep 20 && echo Hello",
            "runOptions": { "instances": 3}
        }
    ]
}
```
You can then execute the `echo` task, ensure that it never runs more than 3 instances of itself and that if a 4th instance is attempted, you should be prompted to either terminate or restart **the last instance** of `echo`.

### CODE REVIEW

**Review by alexr00 — CHANGES_REQUESTED** [review]
Good PR! There are just a few changes before it can be merged.

**Review by alexr00 — APPROVED** [review]
Looks good, thank you!

**Comment by Gama11** [comment]
Will this be exposed in the Tasks API as well?

**Comment by alexr00** [comment]
Not at the moment. Do you want it in the tasks api?

**Comment by Gama11** [comment]
Yes, I have a use case for it. Though after rereading this, it seems like this only solves part of the issue, as you're still prompted each time you exceed the instance limit (so it sounds like https://github.com/microsoft/vscode/issues/32264 shouldn't have been closed just yet while `instancePolicy` is still missing?).

In general, I don't see much of a reason to only expose _some_ functionality of `tasks.json` to the Tasks API. It feels strange that the API would be less powerful than a JSON file (related: https://github.com/microsoft/vscode/issues/73840). It might lead to extension authors being tempted to generate / modify `tasks.json` files again (which was a common workaround before the Tasks API existed).

**Comment by alexr00** [comment]
That's fair. I don't really want to expose every `runOption` in the API (in particular I don't want to expose `runOn`) but the instance properties could be useful.

**Comment by Gama11** [comment]
I could actually also see an extension wanting to contribute a task with `"runOn": "folderOpen"` .  For instance In the Haxe extension that I help maintain, we need an initial compilation to build a cache for the language server. We implemented this inside of the language server, not using VSCode's tasks system at all, but it might make sense for something like that.

However, it could be argued that it's redundant since extensions can already do this in a more flexible manner via the `runTask` command, so yes, it's not much of a limitation to not have this particular option in the API.

**Pull request merged**
