### PR TITLE
Extension host service injection

### PR DESCRIPTION
**Pull request by jrieken**
This PR preps the extension host to make `ExtHostFoo` instances be injected into the `extHost.api.impl` file. The idea is that we can use different `ExtHostFoo` implementations for different extension host runtimes (Node.js, Web-worker) without re-implementing the `extHost.api.impl` - see https://github.com/microsoft/vscode/pull/73827

In essence there is `/node/extHost.services.ts` which registers singleton "services" that are used and there will be `/browser/extHost.services.ts` doing the similar thing for the web-worker world.

### CODE REVIEW

**Comment by jrieken** [comment]
I have invented `IExtHostContextService` which is a bit of a kitchen sink (see below) and plans are to have a dedicated rpc service and ext host environment service.

```ts
export interface IExtHostContextService {
	_serviceBrand: undefined;
	readonly rpc: IMainContext;
	readonly initData: IInitData;
}
```

**Comment by jrieken** [comment]
@Tyriar @weinand @alexr00 fyi what's happening here: in order to move more extension host logic into the /common/-layer I have extracted interfaces for extHost-things that require nodejs-api. E.g. there is now `IExtHostDebugService`, `IExtHostTask` etc. The api implementation (`extHost.api.impl.ts`) depends on those interfaces, not on the concrete implementations anymore - injection ftw. 

However, that also means that clients program against `IExtHost`-interfaces and that you need to expose/define public members for 3rd parties in those interfaces.

**Review by Tyriar — APPROVED** [review]
Changes look great 👍

**Review by alexr00 — APPROVED** [review]
Thank you for the heads up!

**Pull request merged**
