### PR TITLE
SelectBox Clients: Add aria-label value options (ex settingsPreview) Fixes: #53821

### LINKED ISSUE #53821: SelectBox: Add aria-label for select, drop-down list (and clients)
@AccessibilityTestingTeam-TCS 
@bpasero 

The selectBoxList for windows and Linux does not allow for
a aria-label for either the parent select or the drop-down list.

Related: #52297

Since clients may instantiate a selectBox indirectly through something
such as an action bar (e.g. Terminal), I think it should be done
as a new methods such as selectBox.ariaLabel().  This would label both
the select and the drop-down list.

Proposed client label names:

Debug configurations:  "Debug Launch Configurations"
Breakpoint widget:  "Breakpoint Type
Terminal list: "Terminals"  FYI: @Tyriar 
Output list:  "Output list"
New Settings Editor:  item title?  FYI: @roblourens

### PR DESCRIPTION
**Pull request by cleidigh**
Add aria-label value options to select box instantiations on clients 
New settings preview to follow separately.

fyi:  heads up, hopefully I chose appropriate labels
@Tyriar 
@isidorn 
@bpasero 

Fixes: #53821(ex settingsPreview) 

@roblourens
  I did not want to assume how you wanted to handle these labels.
when looking at it, it looks like it might be necessary to add the labels after instantiation
if I'm reading the code correctly.  If the labels cannot be resolved at the instantiation in the renderEnum,
I will have to add a method such as setAriaLabel()

### CODE REVIEW

**Comment by roblourens** [comment]
Yeah, we will have to add something like setAriaLabel

**Comment by cleidigh** [comment]
@roblourens 
I thought this would come up, @bpasero I assume no heartbreak if I had this?

I want to try to get all possible oddities of the drop-down in for July.  If you point me in the right place
so I don't have to hunt, I will add and let you review.

**Comment by roblourens** [comment]
I just changed this in the past few days. But now SelectBoxes in the settings editor are created once for a template and reused for many settings. So I'll need to call it from here along with setOptions: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/settingsTree.ts#L901

**Comment by cleidigh** [comment]
Cool, I'll give that a try.
I think you closed your discussion thread, so I'll ask you a related question:

I played around with adding a box shadow to better delineate when select boxes are stacked on top of each other. This would be similar to quick opens shadow. If you like the idea I can post a couple example screenshots.  Thoughts?

**Comment by roblourens** [comment]
Ideally the border would be enough. Hm, we don't use shadows in many places, but they do show up in a couple places. Maybe a **really** subtle shadow. @misolori

**Comment by cleidigh** [comment]
just the border really blends together.  But I agree we should use as little as possible.
I will post a couple different shadow widths .
here or in a new discussion issue?

**Comment by roblourens** [comment]
Open an issue but I think it's up to our designer @misolori

**Comment by misolori** [comment]
Related to #53073. I would expect that the shadow used here would be the same as menu dropdown for consistency.

**Pull request merged**
