### PR TITLE
Added ctx entry on folders for adding to workspace and renaming

### LINKED ISSUE #137331: Context menu entry for folders "Add folder to workspace"
When a project is opened as a code-workspace environment a simple entry to the context menu "Add folder to workspace" on folders in the default file tree of VSCode would be helpful in order to extend workspace files faster. 
In addition another enhancement for that would be a context menu entry for the root elements in the file tree (specified as folders in the workspace file) to rename them would simplify the process to customise them.

### PR DESCRIPTION
**Pull request by dev-manuel**
This PR fixes #137331 partly.
The "Rename" entry will follow.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
If I understand it correctly, this PR would unconditionally add an entry to every folder in an open workspace. I don't think this a good idea. Here are some reasons:

1. Explorer context menus are already quite long.
2. Users may have developed muscle memory for the current content sequence.
3. There can be types of virtual workspace (implemented using FileSystemProvider API) for which it may not be valid to add a subfolder from an arbitrary depth of the existing workspace as an extra root folder for the workspace.

**Comment by dev-manuel** [comment]
The Arguments 1 and 2 would mean that this context menu should never be expanded again, which is why I assume that this rather means that the feature is not significant enough to appear in it.

In my opinion, the feature is one that saves time when creating workspaces, as the folders don't have to be laboriously selected in the file dialog.

I also think that, in addition to the muscle memory, users also orientate themselves on the dividing lines for the individual groups in the context menu and since it would appear in the workspace section of the menu, I don't see any major problems there. The size of the context menu has already reached a certain level - that's true - but I still think that the introduction of this feature would result more in an enrichment of the usability than in a too long context menu.  There are programs whose context menu contains many more entries and it is still easy to use.

A solution can certainly be found for argument 3 to hide the entry if such a type of virtual workspace is present. If I missunderstood argument 3 It'd be nice of you to elaborate further or supply some resources for me to read about this issue.

**Comment by gjsjohnmurray** [comment]
I think the feature can already be added by an extension. That way, people who want it opt in, and those who don't aren't inconvenienced.

**Comment by dev-manuel** [comment]
In my view, VSCode is a tool that is constantly evolving and not every new feature should be outsourced as an extension just because not everyone will benefit from it. Working with workspaces is a central functionality of VSCode and therefore basic operating options of it should not only be provided by extensions but also by VSCode itself.
I also doubt that a context menu of this size (see picture) will lead to any inconveniences.


CTXMenu Folder VSCode

**Comment by dev-manuel** [comment]
Rename feature is now included

**Comment by bpasero** [comment]
I think I am with John here that we want to keep the explorer menu slim and non-confusing. This entry:

image

Is somewhat misleading for me, because the folder is in fact part of the workspace, given the parent is opened. 

Maybe there should just be a global command to pick a folder for adding to the workspace that shows a picker scoped to the folders of the workspace?

**Pull request closed without merging**
