### PR TITLE
check for valid input in search editor

### LINKED ISSUE #225315: Search Editor Progress Bar Animates Endlessly After Search Completed (intermittent)
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1 Commit eaa41d57266683296de7d118f574d0c2652e1fc4
- OS Version: macOS Sonoma 14.6.1 (23G93)

Steps to Reproduce:

1. Perform a search using the [VS Code Search Editor](https://code.visualstudio.com/docs/editor/codebasics#_search-editor)
2. Intermittent: Blue progress bar / indicator animates endlessly, even after search is completed (I have not yet identified a pattern for which search terms trigger this) - almost like hanging behavior, but everything is still responsive.
3. Reloading the editor using "Developer: Reload Window" causes the problem to disappear

Blue progress bar indicator:

Screenshot 2024-08-10 at 13 05 59

https://github.com/user-attachments/assets/dcacab77-5e07-4c7a-b0d1-d0b3a2dbad51

Search pattern (invalid regular expression):

```
pageTitle: '([^']+)',\n.+)
```

Fixing the invalid regular expression problem does not make the problem go away:

https://github.com/user-attachments/assets/343dade1-9cc8-4f02-8e6a-3f2cb1abefd4

This is not a new problem - this has been happening (intermittently) since shortly after the Search Editor was introduced.

cc @andreamah @rzhao271 @roblourens @JacksonKearl

### PR DESCRIPTION
**Pull request by andreamah**
Otherwise, you get an infinite loading bar animation. Adopting same fix as in search view.

fixes https://github.com/microsoft/vscode/issues/225315

### CODE REVIEW

**Review by joyceerhl — APPROVED** [review]

**Review by songjianet — APPROVED** [review]

**Comment by karlhorky** [comment]
@andreamah and reviewers thanks for the PR and review! 

I'm assuming this will be out in the next recovery release?

- [July 2024 Recovery 2](https://github.com/microsoft/vscode/releases/tag/1.92.2)

**Comment by andreamah** [comment]
It will be out on the August 2024 release, since it's not urgent enough to be on the recovery. However, it will be on tomorrow's VS Code Insiders.

**Comment by andreamah** [comment]
Hmm. I see this on the latest version:
image

Are you sure you're on the latest version? and which os?

**Comment by karlhorky** [comment]
Interesting, my version + system details:

```
Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z (2 days ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

macOS Sononma 14.6.1 (23G93)
Chip: Apple M1

**Comment by karlhorky** [comment]
To be clear, it doesn't appear right away. If I just paste `pageTitle: '([^']+)',\n.+)` into the field, then there is no bar, only the error.

It's when I move from a valid regex to an invalid one, repro steps:

1. Paste in `pageTitle: '([^']+)',\n.+)` - error not reproduced yet
2. Press backspace 1 time - error not reproduced yet
3. Add back `)` - error reproduced

Maybe also needs a few cycles of the above steps, if the first time doesn't work.

**Comment by andreamah** [comment]
Reopened the issue - will see if i can run into the issue a bit later

**Pull request merged**
