### PR TITLE
Expose autofocus configuration settings

### LINKED ISSUE #27352: Expose autofocus configuration settings
##### Problem

Currently, extensions that open the quick open are forced to autofocus the first element. There is no way to specify which item should be highlighted in a quick open menu when calling `showQuickPick`. This is problematic when using the quick open to navigate forwards or backwards in a stack of quick open menus for content drill down because the user loses their place in a larger list.

##### Solution

Add `IAutoFocus` options to `vscode.d.ts` file and add optional property to `QuickOpenOptions`. A possible nice to have would be to add another options for `autoFocusQuickPickItem` that accepts a quick pick item and reveals it in the tree.

### PR DESCRIPTION
**Pull request by KattMingMing**
Resolves https://github.com/Microsoft/vscode/issues/27352

### CODE REVIEW

**Comment by jrieken** [comment]
Please only tackle one issue (focus and callback index) in one PR. Not yet sure about all the API additions, there is many fields that seem redundant having the index or actual item should be enough. What would the following config mean?

```
const auto: vscode.AutoFocus =  {
  autoFocusIndex: 42,
  autoFocusFirstEntry: true,
  autoFocusSecondEntry: true,
  autoFocusLastEntry: true;
}
```

If we want to offer sugar here it must be some kind of enum that ensures mutual exclusiveness between selecting the first or last or second or third, etc

**Comment by KattMingMing** [comment]
@jrieken - This would select the `autoFocusFirstEntry` Based on the logic implemented in [QuickopenWidget.autoFocus][https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L619] It looks like this code hasn't changed in a while so if you'd like I can clean that up to not use `if else` statements and add support for an enum.

**Comment by jrieken** [comment]
Yeah, the code is all dusty and probably dated. Because we want to keep the API stable (e.g. don't break) we are very conservative with surfacing internal functionality in the extension API

**Comment by KattMingMing** [comment]
OK, that makes sense! - Would you prefer that we only expose the `autoFocusIndex`? If that is passed in then we will select that index otherwise default to the previous behavior of selecting the first index?

**Pull request closed without merging**
