### PR TITLE
Add command+UI to set arbitrary diff base in SCM viewlet

### PR DESCRIPTION
**Pull request by nicksnyder**
This PR adds a new group to the source control created by the built in git extension.
- This group displays the diff from the merge base of an arbitrary commit (when one is set by the user either by running `git.compare` from the command palette, or by using SCM group command dropdown).
- The comparison is reset to default current behavior (no comparison) any time HEAD changes.

New changes group:
image

Demo:
screen recording 2017-11-27 at 08 12 am

### CODE REVIEW

**Comment by nicksnyder** [comment]
cc @joaomoreno

**Comment by joaomoreno** [comment]
I think you are onto something here. It's definitely interesting to use a new group to do this. And I love the group actions, such that you can edit/remove the group.

I don't think the status bar command makes sense, since it doesn't provide _status_. I would keep it as a global command and dropdown menu item in the top menu of the provider itself. One could even have context menu actions on files with a `Compare with...` command which would trigger this whole scenario.

**Comment by nicksnyder** [comment]
I pushed a few commits based on your feedback.
- Added item to SCM dropdown
- Add ability to clear current comparison when running the "Compare" command

I am open to removing the status bar icon entirely (and would be trivial to modify this PR to do so), but I pushed a commit that changes the behavior slightly so it only shows a comparison status bar icon if a comparison is active. This seems useful because: 
1. It is a reminder that a comparison is active.
2. Hover tool tip tells you what the comparison is.
3. Since the comparison does impact UI in other viewlets (like decorations in explorer), it does seem relevant to have a global indicator that a comparison is active (in the future this could also impact gutter icons as requested in https://github.com/Microsoft/vscode/issues/30573)

screen recording 2017-11-25 at 02 25 pm

Thoughts?

**Comment by joaomoreno** [comment]
I'm still not a fan of the status. It easily drives the way to bloat. You don't need a reminder that a comparison is active, when you are in the explorer, or debugging, etc. I would never decorate explorer files based on a "comparison view". The files which exist in the explorer are in the Working Tree, so by definition they are compared against HEAD.

**Comment by nicksnyder** [comment]
I just pushed a commit that removes the status bar action. I have limited internet now so I haven't updated the screenshots or gif yet.

> I would never decorate explorer files based on a "comparison view". The files which exist in the explorer are in the Working Tree, so by definition they are compared against HEAD.

Oh, I am confused why you  :+1: https://github.com/Microsoft/vscode/issues/36893 then because I interpret that issue as asking for exactly this (updating decorations in explorer viewlet based on a base other than HEAD). If you aren't a fan of this, I can remove my changes to decorationProvider.ts (and https://github.com/Microsoft/vscode/issues/36893 should be clarified or closed as won't fix).

**Comment by joaomoreno** [comment]
I'd say it is a risky step. What if the files in the commit no longer exist? The explorer won't render files which are not in disk.

I believe what's missing is a tree view on SCM groups... but that's another story. 👍

**Comment by nicksnyder** [comment]
Ok, I pushed a commit to remove the diff status from explorer and removed the "fixes #36893" from the description. Will be able to update the gifs in about 30 minutes. Let me know if there are any other changes you would want me to make.

I am getting a build error that appears to be unrelated:
```
lib/typings/gulp-tslint.d.ts(7,23): error TS2688: Cannot find type definition file for 'vinyl'.
```

**Comment by joaomoreno** [comment]
Awesome stuff.

You can ignore that build error.

**Comment by nicksnyder** [comment]
gif updated in PR description

**Comment by nicksnyder** [comment]
Resolved conflicts with master

**Comment by joaomoreno** [comment]
@nicksnyder Thanks man, but don't worry about those conflicts, I'll deal with them when I get here. 👍

**Comment by joaomoreno** [comment]
Thanks for this @nicksnyder. Unfortunately I'll close it since there's not much momentum to merge this into the core. I believe GitLens already supports something like this so we're going to go with that as an alternative. Thanks for the hard work, regardless. 🙏

**Pull request closed without merging**
