### PR TITLE
Use new debug colour contributions in built-in themes

### PR DESCRIPTION
**Pull request by robertrossmann**
This is a continuation of #94838 - this PR applies some of the new debug-related colour contributions to the built-in themes. It's mostly just the token expressions that are updated, so that bools, numbers, strings, vars and values have the same colours as code itself.

This is just a draft for now to be transparent about ongoing work. I will work on this as my time permits. If some of the VS Code maintainers have some extra time to work on this feel free to leave a comment which theme you will update and push to this branch. 💪 🚀 I will do the same.

Alternatively, I can just keep sending separate PRs for each completed batch. 🤔 ❓

- [x] Abyss
- [x] Kimbie Dark
- [x] Monokai
- [x] Monokai Dimmed
- [x] Quiet Light
- [x] Red
- [x] ~Seti~ _It's just an icon theme 🤷‍♂️_
- [x] Solarized Dark
- [x] Solarized Light
- [x] Tomorrow Night Blue
- [x] Dark
- [x] Dark+
- [x] Light
- [x] Light+
- [x] High Contrast

### CODE REVIEW

**Comment by isidorn** [comment]
@robertrossmann thanks a lot for creaeting this!
For me it makes sense to keep everything in one pr.
I also checked off our default themes as I would not do any changes there.

As for the color I leave this one up to you and @misolori

**Comment by robertrossmann** [comment]
I'll work on Abyss and Kimbie Dark today. 💪

**Comment by robertrossmann** [comment]
@isidorn @misolori I just finished updating all the themes, this is now ready for review! 🎉 🎨

**Comment by isidorn** [comment]
@robertohuertasm great work. We are slowly wrapping up our endgame so I leave it up to @misolori if we review this this milestone or we leave it for next milestone in May.

**Comment by misolori** [comment]
This looks great, nice job! I just need to double check the color contrast ratio on all of these to ensure they pass. Will likely make it in in the May release since we're nearing the end of this iteration. Stellar work 💪!

**Comment by robertrossmann** [comment]
Sounds good! If it helps, I just used the colours already present in the theme, especially for the language tokens. You might want to check the "value changed" highlight colours and the labels, though. I used the theme colours for those, too, but the contrast might not be perfect in all the themes... 🤷‍♂️

**Comment by isidorn** [comment]
@misolori please move this out to May or merge today :)

**Comment by robertrossmann** [comment]
I vote merge today! 🚀 😇

**Comment by isidorn** [comment]
@misolori friendly ping regarding this :)
Let me know if or @robertrossmann can help with the color contrasts

**Comment by misolori** [comment]
I only reviewed the first 3 themes and found several color contrast issues, some are related to your changes and some are not (FYI @isidorn). I'd suggest going through the rest of the themes and check each color that's being adjusted and re-adjust.

## Abyss
- `debugView.stateLabelForeground`
  
- `debugTokenExpression.value`
  

## Kimbie Dark
- `debugView.stateLabelForeground`
  
- `list.deemphasizedForeground`
  
- `badge.foreground`
  
- `debugTokenExpression.name`
    
- `debugTokenExpression.value"`
  

## Monokai
- `badge.foreground`

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
I only reviewed the first 3 themes and found several color contrast issues, some are related to your changes and some are not (FYI @isidorn). I'd suggest going through the rest of the themes and check each color that's being adjusted and re-adjust. We need to meet at least a contrast ratio of 4.5:1 and you can use the local dev tools from OSS to check with the inspector or the [Color Contrast Analyser tool](https://developer.paciellogroup.com/resources/contrastanalyser/).

## Abyss
- `debugView.stateLabelForeground`
  
- `debugTokenExpression.value`
  

## Kimbie Dark
- `debugView.stateLabelForeground`
  
- `list.deemphasizedForeground`
  
- `badge.foreground`
  
- `debugTokenExpression.name`
    
- `debugTokenExpression.value"`
  

## Monokai
- `badge.foreground`

**Comment by isidorn** [comment]
@misolori thanks a lot for checking!
@robertrossmann is it possible that you look into this once you find time?

**Comment by robertrossmann** [comment]
@isidorn Yup, I should have some time sometime this week.

@misolori should I stick to colours already defined somewhere in the theme or may I define new, similar ones to fix the contrast? Because so far I really just copy-pasted colour values for the new contributions. 🤔

**Comment by misolori** [comment]
@robertrossmann I'd say you can tweak the colors a bit to get the right contrast (we do this in a few places), @isidorn what do you think?

**Comment by isidorn** [comment]
Agree, it would be great if @robertrossmann just tweaks the colors to get the right contrast. If that is not possible than we can go back to using some of the existing colors.

**Comment by isidorn** [comment]
Pushing this out of May, so we merge when we tackle the color contrast issues.

**Comment by isidorn** [comment]
Just to check if there have been any updates here? Do we still want this?
If no then I will have to close this PR unforutnetly.

**Comment by robertrossmann** [comment]
@isidorn Apologies for delaying this. Unfortunately I do not have the time nor motivation to work on this any further - I am extremely happy with the new debug colour contributions and I only use one (self-maintained) theme so adding them to the built-ins is no longer in my interest. 😢 

I would love to hand this off to someone else as I think the community would benefit from this. 🙏

**Comment by isidorn** [comment]
Makes sense. Thanks for your reply.
However for now I will close this and if somebody volunteeres to take this I will be happy to reopen. Thanks!

**Pull request closed without merging**
