### PR TITLE
fix #6062 and #1064

### LINKED ISSUE #6062: Emmet Stylus snippets not working
The Stylus snippets that come out of the box with Emmet do not work in VSCode, while the default setting in the 'preferences.json' (that is nowhere to be found) of Emmet 'css.syntaxes -
List of syntaxes that should be treated as CSS dialects.' has .styl

- VSCode Version: 1.0.0
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Create a .styl file
2. Add a CSS selector: ex. #test
3. Type pos:a and press TAB

**Expected result:** expands to 'position absolute' or 'position: absolute;'
**Actual result:** nothing happens

### PR DESCRIPTION
**Pull request by Ikuyadeu**
fix #6062  and #1064.
cbbcf73 and 65966e3 may not support sass and stylus file. 
`.sass` and `.stylus(.styl)` should be treated `sass`.

### CODE REVIEW

**Comment by aeschli** [comment]
@Ikuyadeu Thanks for the fix. One issue tough, we should not add the .sass and stylus file extensions in sass.contribution.ts. Our mode only supports the scss syntax.

**Comment by Ikuyadeu** [comment]
@aeschli Thank you comment. I see. I deleted sass.contribution.ts changes.
So, This PR just delete some lines that is not working.

Should I make support mode that for .sass and stylus file extensions can use emmet?
Or, It is function of Extentions?

**Comment by aeschli** [comment]
@Ikuyadeu Thanks for the change. Yes, the language contribution for stylus and sass should come from extensions. There are already a few:
- https://github.com/robinbentley/vscode-sass-indented for sass indented (language id 'sass-indented'))
- https://github.com/d4rkr00t/language-stylus for stylus (language id 'stylus')

Handing over this PR to @egamma who's owning the emmet integration.

**Comment by egamma** [comment]
Closing the PR.

**Pull request closed without merging**
