### PR TITLE
Add inline values support

### LINKED ISSUE #119489: Implement InlineValueProvider for TypeScript
I debug a test and get this:

image

Lots of inline debug values from a different unrelated test method.

Compared to devtools:

image

### PR DESCRIPTION
**Pull request by Kingwl**
This PR fixes #119489 . Would also be downstream of https://github.com/microsoft/TypeScript/pull/45173

%KE0NL%%C S%2OVZPB{ } L

/cc: @mjbvz @connor4312

### CODE REVIEW

**Comment by connor4312** [comment]
This is cool, thanks for your work on it! I'll leave it to Matt to review this change as he's far more familiar with this code.

**Comment by mjbvz** [comment]
@Kingwl @connor4312  From the typescript side, I believe we agreed inline values would ship as a plugin instead of part of core. Do you know if such a plugin has been developed yet?

**Comment by Kingwl** [comment]
> @Kingwl @connor4312  From the typescript side, I believe we agreed inline values would ship as a plugin instead of part of core. Do you know if such a plugin has been developed yet? 

AFAIK, nope.

**Comment by Kingwl** [comment]
> @Kingwl @connor4312 From the typescript side, I believe we agreed inline values would ship as a plugin instead of part of core. Do you know if such a plugin has been developed yet?

Emmmmm, should it be a builtin ts plugin provided by ts extension？

**Comment by mjbvz** [comment]
@Kingwl Yes that makes sense to me. The TS plugin needs to be shipped as its own node module but we can bundle it as part of VS Code's built-in TS extension

**Comment by Kingwl** [comment]
Happy to work on this If I may.

**Pull request closed without merging**
