### PR TITLE
Regression: adding back hover widget CSS that had been removed

### PR DESCRIPTION
**Pull request by aiday-mar**
The PR that was merged yesterday https://github.com/microsoft/vscode/pull/213700 has caused the inner right hover border to no longer be visible when it is focused. This PR adds the CSS back for the padding-right, but omits the padding-bottom.

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]
cc @benibenj

**Comment by aiday-mar** [comment]
So the issue was with regards to the resizable editor hover. If I understand correctly the hoverWidget.css affects also the workbench hover, hence I should maybe move this change to the editor hover specific CSS file?

pinging @benibenj if you think this change is okay

**Comment by benibenj** [comment]
I think this is a fix specific to the editor hover right? So it should not apply to all `.monaco-hover-content` as this will also affect all hovers shown with the `HoverService`. So make sure it only applies to the editor hovers. Maybe something like:

```
.monaco-editor .monaco-hover-content {
	padding-right: 2px;
	box-sizing: border-box;
}
```

In that case move it out of `hoverWidget.css` and into the editor layer

**Comment by aiday-mar** [comment]
I see thanks for the feedback. I'll do that thanks!

**Comment by aiday-mar** [comment]
Other PR was made, this PR will be closed

**Pull request closed without merging**
