### PR TITLE
Fix markdown cell focus indicators for notebooks

### PR DESCRIPTION
**Pull request by mjbvz**
This change fixes the highlight indicators for markdown cells in notebooks. It also makes clicking on a markdown notebook cell focus it

Part of #116393

### CODE REVIEW

**Review by roblourens — APPROVED** [review]

**Comment by rebornix** [comment]
The change looks good to me in overall, I noticed a few difference in the rendered markdown styles

image

* Header margin
* Color

I wonder if you want to fix them in this PR.

**Comment by mjbvz** [comment]
Thanks @rebornix! 

I'll look into that separately since I don't think it was introduced by this PR (@kieferrm mentioned to me that he actually prefers the new style but we should have a larger discussion about this :)

**Comment by mjbvz** [comment]
Merging this and will continue polishing. Let me know if you notice any regressions with the existing markdown renders or with the new ones

I'm also going to enable the new notebook markdown renders by default in the VS Code  workspace so that we can start collecting more feedback

**Comment by rebornix** [comment]
@mjbvz is Latex the only custom markdown renderer for now? We are not using latex in our github issue notebooks so I wonder if we can have some other custom renderers which we can use in our gh issues? For example, a custom renderer which supports `- [ ]` maybe it's a just setting of markdown-it.

**Pull request merged**
