### PR TITLE
Fix category width in extensions for better presentation

### LINKED ISSUE #150209: Wrapped extension categories don't look good
Actual:

image

Expected:

image

### PR DESCRIPTION
**Pull request by lgordey**
This PR fixes #150209

Tried to fix it with a minimum of code, in my opinion it got better

image

### CODE REVIEW

**Review by p4nu — APPROVED** [review]
LGTM

**Review by danilhendrasr — COMMENTED** [review]
In a maximized view it look like this: 
image

A little different from the original version:
image

Just pointing out, I'm not sure if the little difference is okay or not.

**Comment by sandy081** [comment]
@lgordey Thanks for the fix but it fixes one scenario but regresses other scenario like in above picture. Can you please reconsider this.

**Review by sandy081 — CHANGES_REQUESTED** [review]
Please reconsider the fix as it regresses other scenarios

**Pull request closed without merging**
