### PR TITLE
Progress on AI in search view

### PR DESCRIPTION
**Pull request by andreamah**
As if this PR, we have more integration of AI results into the search view. Example:

https://github.com/microsoft/vscode/assets/31675041/4624c6e1-5903-4e42-99e8-5b7edc1945f8

Note that we don't have support yet for disabling replace and pattern options (regex, match case, etc.). I was thinking to incorporate this later, since it's a little more involved.

To use this, you need this setting in your `settings.json` (and also an AI Text Provider):
```
"search.aiResults": true,
```

Implementation-wise, this splits the search model's storage of AI results and regular results in different areas internally so that there is less logic to discern AI and non-AI results.

### CODE REVIEW

**Review by jrieken — APPROVED** [review]

**Comment by isidorn** [comment]
I like the sparkle emoji!
I dislike that it is added to an already packed toolbar. Is there something we could remove from the toolbar to make it leaner? Or maybe introduce a secondary toolbar and move some actions there (not sparkle) `...`

**Comment by andreamah** [comment]
I'm thinking that, based on how users toggle between AI and non-AI mode also matters a lot- if it's in one view, then perhaps we don't need an icon so visible to the user all the time (and it would rather be a setting).

**Comment by isidorn** [comment]
If it is a setting then it is hardly discoverable. I still think it deserves a spot in the ui if possible.

**Comment by andreamah** [comment]
That's true. But perhaps we'd be more comfortable putting it in an overflow menu if people didn't need to toggle it much?

**Pull request merged**
