### PR TITLE
auto save - treat `autoSaveWhenNoErrors` as `AutoSaveMode.AFTER_LONG_DELAY`

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Comment by justschen** [comment]
subscribing myself here - when this goes in, I can add/verify support for this in `editor.codeActionsOnSave`

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by bpasero** [comment]
@justschen curious what you wanted to verify?

**Comment by justschen** [comment]
@bpasero just making sure that with `editor.codeActionsOnSave` , if any of the code actions are set to `always`, that it also works with `afterLongDelay` (following up from one of the Slack threads with @alexdima) !

Since I disabled code actions specifically on auto save `afterDelay` - regardless, this is a really great addition :D

**Comment by bpasero** [comment]
@justschen just to clarify: my changes around auto save are not really changing how auto save works and we always distinguished between short and long delays, specifically to decide if we show a dirty indicator or not. 

Historically, VS Code did not have dirty indication and auto save was always on by default with a delay of `1s`. When I had to implement dirty indication for our first release, I decided to preserve that behaviour by not showing any dirty indication when auto save is configured like this.

What I did change now is to support more configuration options around auto save:
* make it a language / resource overrideable setting
* allow to skip auto save for out-of-workspace files
* allow to skip auto save when the file has error markers

Is there an issue to further discuss how code actions can benefit from this?

**Comment by justschen** [comment]
@bpasero That makes sense - thanks for that. I opened an [issue here](https://github.com/microsoft/vscode/issues/200881) about this!

**Pull request merged**
