### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
Fixed some typos in the comments.

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
> 
@microsoft-github-policy-service agree [company="{dafeult}"]

**Comment by RuffaloLavoisier** [comment]
Thanks.
@microsoft-github-policy-service agree company="Stealien"

**Review by nutty323 — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
IMO your PR is unlikely to be accepted. Please see https://github.com/microsoft/vscode/wiki/How-to-Contribute#spell-check-errors

**Review by atlslscsrv-app — DISMISSED** [review]

**Review by nutty323 — CHANGES_REQUESTED** [review]
Typo

**Comment by alexr00** [comment]
Thank you for the PR, but as suggested [here](https://github.com/microsoft/vscode/pull/164955#issuecomment-1295784525) we will not accept it.

**Pull request closed without merging**
