### PR TITLE
Fix #30450

### LINKED ISSUE #30450: Fresh install on win10(zh-CN), locale.json should be "zh-CN" rather than "zh-cn"
Although "zh-cn" works, but there is a prompt: "value is not accepted".

### PR DESCRIPTION
**Pull request by shizengzhou**
Add the lower case value to the schema.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@shizengzhou this is not a good fix for the problem. The fix has to happen in the JSON validation (actually the JSON schema for the locale.json file). The place you touched list valid locales and it shouldn't contain duplicates.

**Comment by dbaeumer** [comment]
Somewhere here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/localizations/browser/localizations.contribution.ts#L39

**Comment by dbaeumer** [comment]
@shizengzhou that is the right place, however looking at the code we should do something smarter. Instead of only add the Chinese locales we should go over the passed in localed and lower case them all. If they are different add the lower case item as well. This will then fix it for all future locales. We should not hand tune this.

**Comment by dbaeumer** [comment]
@shizengzhou also only a small array that makes an O(n2) algorithm. Can you not simply lower case the locale and if different than the original value add it instead of lower casing all and the filter with indexOf

**Comment by shizengzhou** [comment]
@dbaeumer I originally intended to use Set, however there is a error.
error
In other parts of source code, I see
set
This is why?

**Comment by shizengzhou** [comment]
@dbaeumer Thank you for reviewing my code. I have changed my code.

**Comment by cyrilgandon** [comment]
I like you first version more, you just need a little tweak to not make it O(n2). For example:

```
const lowercaseLanguageIds = languageIds
    .map((languageId) => {
       languageId,
       lowerCase: languageId.toLowerCase()
   }).filter((langObj) => langObj.languageId !== lowerCase)
      .map((langObj) => langObj.lowerCase)

registerLocaleDefinitionSchema([...languageIds, ...lowercaseLanguageIds]);
```

**Comment by dbaeumer** [comment]
I merged the provided version.

**Pull request merged**
