### PR TITLE
Support actions to show up in the macOS touchbar

### PR DESCRIPTION
**Pull request by bpasero**
Ref: https://github.com/Microsoft/vscode/issues/14653

Enables support for commands to show up in the macOS touch bar. The ID for this menu is `touchBar`. We require the icon for the command to be a PNG, as the API currently does not support SVG. 

First use cases:
* editor history navigation
* new file
* debug tool bar

touch bar shot 2017-09-18 at 15 04 04
touch bar shot 2017-09-18 at 15 04 11

### CODE REVIEW

**Comment by firelizzard18** [comment]
@bpasero I'm concerned that this implementation may suffer from the same jitter issues that @jonathan-fielding's did: jonathan-fielding/vscode#2. Since the electron touch bar objects are tied to the Objective-C backend, recreating these objects has unpleasant consequences. If you recreate all of the touch bar elements, then any time `updateTouchBar()` is called, the touchbar will jitter. You can avoid this by reusing previous `TouchBar*` objects. When you don't reuse objects, the macOS API does a fade-out+fade-in from the old instances to the new instances, regardless of whether or not the content actually changed. This transition is rapid enough that it looks like jitter. If you preserve and reuse existing instances of touch bar objects, then any touch bar elements that did not change will not undergo any kind of transition.

**Comment by bpasero** [comment]
@firelizzard18 yeah good point, I thought about that issue and will see if we can be smarter about reusing touch bar entries. I think that should totally be possible.

**Comment by jonathan-fielding** [comment]
Until I got blocked by not being able to build locally I had been refactoring to reduce the jitter, my way to do this was to centralise the control of the touchbar.

**Comment by bpasero** [comment]
I pushed changes to reuse the [`TouchBarSegmentedControl`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L930) I am using as much as possible however if items change within, I have to recreate this control. At least the flicker when starting debug or leaving debug is gone with that change.

**Pull request merged**
