### PR TITLE
Updates to IndexedDBFileSystemProvider

### PR DESCRIPTION
**Pull request by JacksonKearl**
Previously Including:
 - Removing conversion to string which corrupts binary data

Now Including:
 - Adding batching to write operations
 - Keeping track of directories across reloads (currently just stored in memory)
 - Updating readdir to not scan through every file in the system for each dir-read

### CODE REVIEW

**Review by sandy081 — APPROVED** [review]
LGTM

**Comment by JacksonKearl** [comment]
Hey @sandy081 I made some more substantial changes -- the basic theme is to add batching to the readwrite calls, for instance `writeFile` and `writeDir` calls get put into a batch together until the previous batch finishes executing, then in a single transaction all the dir updates and file puts are executes. Similarly for `delete`, in the recursive case first the tree is computed, then all those entries are deleted in once transaction.

I removed the `keyValueFileSystemProvider` because it was only being used by `indexedDBFileSystemProvider.ts`, but in order to implement the perf optimizations above I needed to dive into the implementation details of IndexedDB (transactions, for instance).

**Comment by sandy081** [comment]
@JacksonKearl thanks for looking into it. It seems your use case requires performing many sequential writes and reads into the IndexedDB. But AFIK IndexedDB is not performant for such a scenario. It seems throttling is also not a good solution, source: https://stackoverflow.com/questions/22247614/optimized-bulk-chunk-upload-of-objects-into-indexeddb 


Regarding changes, some initial questions:

- You are right that `keyValueFileSystemProvider` is not needed any more. Before it was used for IndexedDB and InMemoryDB.

- May I know why are we writing directories into the IndexedDB? Previously they are stored in memory and I think this works right? This will also reduce the writes into the DB?

- Also I am sure, you would have taken the perf measurements, if so can you please add them here? It would be nice if there is a perf test recording the measurements. 

May be we can also chat directly to go through the changes?

**Comment by JacksonKearl** [comment]
close in favor of 107590

**Pull request closed without merging**
