### PR TITLE
Explorer adopt new tree

### PR DESCRIPTION
**Pull request by isidorn**
Work in progress!
This PR adopts the new tree in the Explorer.
Requires a lot of testing, this is a first very rough sketch.

Missing features:
- [x] Drag and drop #63762
- [x] Highlight renamed elements via css
- [x] Auto expand single children #64888
- [x] Customised sort order #63148
- [x] Preserving view state #65005
- [x] File actions need to be aware of the new tree
- [x] File icon theme support #64894
- [ ] Horizontal scroll #63684
- [x] Bring back willResolveExplorer and didResolveExplorer
- [x] Bring back root error decorations

Issues:
- [x] Input box is broken
- [x] auto revealing feels lagy
- [x] Multi Root workspaces is slightly broken #65500
- [x] editorService gets called twice to open on click
- [x] muti selection not working due to focus

Random todos:
- [x] Test all explorer configuration settings
- [x] Check explorer performance when there are a lot of file events
- [x] Alt click works as expected to expand / collapse

fyi @joaomoreno @jrieken

### CODE REVIEW

**Comment by Astrantia** [comment]
@isidorn Did you notice perf improvements with tree in explorer?

**Comment by isidorn** [comment]
@Astrantia I have not yet thougoughly tested it but I expect perf improvments.

**Comment by isidorn** [comment]
@bpasero might you have some old test cases how you tested the explorer for intensive file events?
I just did the simple having the explorer open while doing `yarn && yarn watch` in our repo.
Ideas welcome on how to test I did not introduce any regressions in this area.
Also let me know if there are some other delicate things I might have missed in my list from above

**Comment by bpasero** [comment]
Yeah I think doing npm install produces many events, but keep in mind that we ignore changes in node modules by default. You should easily be able to produce file events with a simple node script that creates/touches/deletes files, no?

> Also let me know if there are some other delicate things I might have missed in my list from above

We will know what you missed once this hits stable :)

**Comment by isidorn** [comment]
Test plan item https://github.com/Microsoft/vscode/issues/66485

**Comment by JosephTLyons** [comment]
I must be misunderstanding something, I can't seem to find any command anywhere for expanding all folders, only a command for collapsing all folders.

**Comment by isidorn** [comment]
There is no such command.

**Comment by JosephTLyons** [comment]
That seems like a massive design flaw to not allow opening of all folders, unless the devs are worried VS Code can't handle the memory of opening massive tree structures.

**Pull request merged**
