### PR TITLE
Implement configurable cursor style

### PR DESCRIPTION
**Pull request by ThatRendle**
With acknowledgements to @Protectator and his configurable blinking (#500), I've tried to do something similar to allow the cursor style (i.e. _line_ or _block_, at present) to be configured.

Right now, the setting is configurable from editor.config, but with the right method somewhere(?) this could also be over-ridden by Vim mode plugins such as [VsCodeVim](https://github.com/VSCodeVim/Vim/) to switch between cursor styles for Normal and Insert modes (see https://github.com/VSCodeVim/Vim/issues/19 and https://github.com/Microsoft/vscode/issues/200).

Feedback on what I've done so far would be much appreciated.

### CODE REVIEW

**Comment by glen-84** [comment]
Would it be possible to add a thin line (1px) style?

PuTTY has an `Underline` style as well. I don't use it personally, but it may be useful to extensions.

**Comment by markrendle** [comment]
@glen-84 I don't see why not, it's just a matter of getting the CSS right and adding in names for it.

**Comment by glen-84** [comment]
#### block/block-thin/block-hollow/block-outline:
block-outline
```css
? {
	background: transparent;
	border: 1px solid;
	box-sizing: border-box;
	position: absolute;
	width: 1ch;
	cursor: text;
}
```

#### block/block-filled:
block-filled
```css
? {
	position: absolute;
	width: 1ch;
	cursor: text;
}
```

#### line/line-thin/line-narrow:
line-thin
```css
? {
	position: absolute;
	width: 1px;
	cursor: text;
}
```

#### line/line-thick/line-accessible:
line-thick
```css
? {
	position: absolute;
	width: 2px;
	cursor: text;
}
```

#### underline/underline-thin:
underline-thin
```css
? {
	background: transparent;
	border-bottom: 1px solid;
	box-sizing: border-box;
	position: absolute;
	width: 1ch;
	cursor: text;
}
```

#### underline/underline-thick/underline-accessible:
underline-thick
```css
? {
	background: transparent;
	border-bottom: 2px solid;
	box-sizing: border-box;
	position: absolute;
	width: 1ch;
	cursor: text;
}
```

I'm not too sure about the names, maybe:

block-filled
block-outline
line-thin
line-thick
underline-thin
underline-thick

... I'll leave this to the developers. =)

**Comment by markrendle** [comment]
@glen-84 Good work! I'll get those added. Thanks :)

**Comment by alexandrudima** [comment]
Let's tackle the other suggested styles in a new issue. I have merged this change in with some edits to simplify it in 82f2a8afb224bda94f3b94dd73718aa3eb370f42

**Comment by alexandrudima** [comment]
Let's track the other styles in #1929

**Comment by alexandrudima** [comment]
@markrendle Sorry this appears in github as not merged, I had to manually merge it due to some bad commits in your PR, but your commit did make it in.

**Comment by markrendle** [comment]
@alexandrudima That's cool, I'm just happy to have contributed something to the project.

**Comment by igl** [comment]
Was looking for this and still have 2 issues:

Even line-thick still drowns in the brace-highlight. It's very hard to see wether the cursor is in front of a brace or after.

The settings-schema does not include these and shows an error:
> Value is not an accepted value. Valid values: ["block","line","underline"]

**Pull request closed without merging**
