### PR TITLE
Fix #46123 : Remove absolute path for python

### LINKED ISSUE #46123: vscode edit bug report
Issue Type: <b>Bug</b>

Inside the shell command script python is used (using it's full path) to infer the path for the actual script file (rather than the link used to run it):

    function realpath() { /usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }

This doesn't work when a non-default python exists in the path along wiht a matching PYTHONPATH variable
In my case, anaconda with python3 and PYTHONPATH=/usr/local/lib:/usr/local/lib/python3.6/site-packages

The script exists with an error:
Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!

I edited the script file to use python instead of /usr/bin/python, but this gets overwritten with every minor update, requiring redoing the edit every couple of days.

Script should either not get overwritten with every update if it has not changed or to use relative path (just python instead of /usr/bin/python)

VS Code version: Code - Insiders 1.22.0-insider (ec3c083444c084394ee0cd936074019c1bc0b321, 2018-03-14T06:08:15.960Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron FullChannelData.m|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.14.0
matlab|Gim|0.8.0
cmake-clangd-helper|Har|0.1.0
code-gnu-global|aus|0.2.2
togglehs|bbe|0.1.2
codecpp-minimum|dod|0.0.1
jupyter|don|1.1.4
code-runner|for|0.9.3
CppSnippets|har|0.0.13
cmake-tools-helper|mad|0.1.1
vscode-clang|mit|0.2.2
python|ms-|2018.2.1
cpptools|ms-|0.15.0
markdown-preview-enhanced|shd|0.3.4
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
markdown-all-in-one|yzh|1.1.0

(3 theme extensions excluded)

</details>
Reproduces without extensions

### PR DESCRIPTION
**Pull request by jatinsandilya**
Fixes #46123

### CODE REVIEW

**Comment by joaomoreno** [comment]
@jats22 Did you confirm that that snippet of python code runs on any python version 2 and 3?

**Comment by jats22** [comment]
@joaomoreno I tested that line of python code in version 2.7 & 3 and got the same result. And as per https://docs.python.org/3/whatsnew/3.0.html I understand that the print as a function is backpropagated into 2.6 as well.

pythonout


Am I missing something?
Also I am not sure as though how this script is used in the project however. Any pointers?

**Comment by jats22** [comment]
Ahh. I see. Thanks!

**Comment by joaomoreno** [comment]
Thanks!

**Pull request merged**
