### PR TITLE
Warning when invoking explorer.newFile (fix #100604)

### LINKED ISSUE #100604: Warning when invoking explorer.newFile
Issue Type: <b>Bug</b>

Executing `explorer.newFile` without having a folder open produces the following warning
> Cannot read property 'isReadOnly' of undefined

image

Steps to repro:
* Open vscode without any folder or workspace
* Bind `explorer.newFile` to a keyboard shortcut
* Invoke `explorer.newFile`
* Notice the warning

Expected result:
Either
* The OS file dialog is displayed to choose the file location, or
* No new file is created and a clearer warning is displayed

VS Code version: Code - Insiders 1.47.0-insider (8cd3fe080bee38d28ba01d0d71713d6ec22b254e, 2020-06-19T06:35:49.048Z)
OS version: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #100604

### CODE REVIEW

**Comment by isidorn** [comment]
@bpasero I would prefer if we use a precondition to disable the command completely in that case.
What do you think?

**Comment by bpasero** [comment]
@isidorn ah ok, my understanding was that the user explicitly binds this command to a certain key? In that case, `when` condition would not help? Check the screenshot from original issue.

**Comment by isidorn** [comment]
@bpasero I think it would help even in that case. `when` case would help, a `preconditoin` would not.
`precondition` I think applies for the keybinding
if the `when` is false even if there is a keybinding it would not trigger it

**Comment by bpasero** [comment]
@isidorn I think it is the other way around. The `when` condition is lost once the user defines the keybinding, by default it will not have any `when` condition.

Do you already have a context key for the explorer being available or not?

**Comment by isidorn** [comment]
Try this `WorkbenchStateContext.notEqualsTo('workspace')`
Code pointer how I use it for example
https://github.com/microsoft/vscode/blob/d88f0991163c2f06b632c4a3846334b06395c398/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L288

**Comment by bpasero** [comment]
@isidorn actually you already do this here:

https://github.com/microsoft/vscode/blob/c1031ceaa93ae8be971820cedc34ef73a07c3ddd/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L224-L225

via `WorkspaceFolderCountContext.notEqualsTo('0')`

Problem is that you cannot do this on the level of commands:

https://github.com/microsoft/vscode/blob/744f2ab731b59ea5c6c6ec33362b4925c9fb8591/src/vs/workbench/contrib/files/browser/fileActions.ts#L926-L938

Once you register a command, it needs to be executable always.

An alternative is to simply return early from the command if the explorer is not visible instead of showing this warning...

**Comment by isidorn** [comment]
Then it seems like there is nothing smarter to do here.
Your approach improves the error message, so let's go with that -> approved.

**Review by isidorn — APPROVED** [review]

**Pull request merged**
