### PR TITLE
Accept editor line height as multiple of font size

### LINKED ISSUE #82778: Allow Line Height to be Any number
I like to follow the golden ratio rule of design and calculate the exact line height required by a font face for it to look good. For that, `1.2 to 1.45` times the font size is the best size bracket.

I currently use:

```json
"editor.lineHeight": 24.65,
```

My claim is backed by some of the industry-leading typographers like Matthew Butterick [recommends line-height to be 120–145% of the font size](https://practicaltypography.com/line-spacing.html).

---

But I am currently having issues with it.

img

Whereas the debug console line-height still works as a non-integer.

```json
"debug.console.lineHeight": 24.65,
```

Can you folks allow any number value to be used for `"editor.lineHeight"` property as well?

Peace! ✌️

### LINKED ISSUE #115960: Option to Specify Line Height as a Multiple of Font Size
Small usability tweak request: 
It'd be really nice to be able to specify editor line height as a multiple of font size. 

Pitch for why it's worth considering: 
- It'd be more consistent with the other line height settings in VSCode. (markdown.preview.lineHeight and terminal.integrated.lineHeight are both multipliers--only editor.lineHeight is absolute).
-  It would also unbreak dynamically resizing code on the fly, which is often important while communicating, like in teaching.
- Seems like lots of people change this setting, since [VSCode's spacing default](https://github.com/microsoft/vscode/issues/23806) is significantly bigger than most editors and people like seeing lots of code on the page. And [this leads to confusion](https://github.com/microsoft/vscode/issues/33968) because most line spacing settings are a multiplier, in VSCode and elsewhere.

Being able to (optionally) specify the value in ems would solve the problem, while remaining backwards compatible. To give concrete examples, "15" could remain a valid value (implicitly in pixels), but 1.25em could also be a valid value that would rescale properly if the text size were changed.

Thank you for your consideration--and a truly excellent piece of software!

### PR DESCRIPTION
**Pull request by cpsauer**
This PR fixes #115960 with @appetite-j's great suggestion from #105888, also suggested by @usernamehw.
Should also fix #82778.

This is my first PR to VSCode; I'd love your help through!

### CODE REVIEW

**Comment by cpsauer** [comment]
Tagging @alexdima, in case he's the right reviewer, since he'd been active (and kind) on the issue, and it looks like a lot of the lines in these files are his :)

**Comment by cpsauer** [comment]
Actually, @alexdima, while you're looking at this:
While making this PR, I'd incidentally noticed that the default line height for macOS has been special-cased to 1.5 rather than the 1.35 for other platforms. (See [here](https://github.com/microsoft/vscode/blob/da65c6706320264bd4333837e8119dc097c8dee9/src/vs/editor/common/config/fontInfo.ts#L14).) 
This seems odd because Xcode (and thus macOS's) default code multiplier is 1.25, I'm pretty sure. Thoughts on removing that special-casing or to change it to 1.25? Asking you because it looks like you last edited those lines, refactoring from elsewhere. Happy to PR if you agree (and not, if opposed).

**Comment by cpsauer** [comment]
@alexdima, thanks for the review and making things better!

Looks like your auto-merge got caught by linter download flakiness, so I took a sec to quickly factor the rounding out to be with the minimum constraint. Hope that's okay, since this would have needed a merge from you anyway.

I'd originally had the integer constraint in there, but I noticed that the lines that follow that section break the integer font size constraint, and it looked like things work just fine with non-integer fonts, at least on macOS. Thoughts?

Also hoping I can still get your thoughts on the macOS golden special-casing, above.

**Comment by alexdima** [comment]
Thank you!

**Comment by cpsauer** [comment]
Sweet! Thank you, @alexdima.

**Comment by cpsauer** [comment]
Any chance I could still get your take on the integer & macOS golden sub-questions above?

**Pull request merged**
