### PR TITLE
fixes #104293

### LINKED ISSUE #104293: Experiments service still reaches out to server even when disabling telemetry
From @rob3c, https://github.com/microsoft/vscode/issues/103159#issuecomment-670773789:

> @joaomoreno VSCode Insiders build still connects to `https://default.exp-tas.com/vscode/ab` even when telemetry is disabled. It does this every 30 minutes.
> 
> Here's a sample redacted request/response pair:
> ```
> GET https://default.exp-tas.com/vscode/ab HTTP/1.1
> Host: default.exp-tas.com
> Connection: keep-alive
> X-MSEdge-ClientId: [REDACTED]
> X-VSCode-TargetPopulation: insider
> X-VSCode-Build: Visual Studio Code - Insiders
> User-Agent: [REDACTED]
> X-FD-Corpnet: 
> X-VSCode-AppVersion: 1.48.0-insider
> Accept: application/json, text/plain, */*
> X-VSCode-Language: en
> X-VSCode-ExtensionName: vscode-core
> X-MSEdge-Market: 
> Sec-Fetch-Site: cross-site
> Sec-Fetch-Mode: cors
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US
> If-None-Match: [REDACTED]
> ```
> ```
> HTTP/1.1 304 Not Modified
> ETag: [REDACTED]
> X-Content-Type-Options: nosniff
> X-ExP-TrackingId: [REDACTED]
> X-MSEdge-Ref: [REDACTED]
> Access-Control-Allow-Origin: *
> Date: [REDACTED]
> ```

### PR DESCRIPTION
**Pull request by sbatten**
This PR fixes #104293

### CODE REVIEW

**Review by joaomoreno — COMMENTED** [review]
@sbatten Shouldn't this react to the setting change at runtime?

**Comment by sbatten** [comment]
@joaomoreno it will disable at runtime but not enable, which is good because we don't really want to start an experiment in the middle of the session in case consumers have already queried.

**Review by RMacfarlane — APPROVED** [review]
LGTM!

**Comment by joaomoreno** [comment]
> @joaomoreno it will disable at runtime but not enable, which is good because we don't really want to start an experiment in the middle of the session in case consumers have already queried.

Should it then be one of those settings which prompts a restart? I didn't check if it is.

**Pull request merged**
