### PR TITLE
Provide file icons per file type

### LINKED ISSUE #4845: Provide file icons per file type
- VSCode Version: Feb. stable build (0.10.11)
- OS Version: Win 10 Pro

Steps to Reproduce:
1.  Install VSCode.
2.  See any code file in Explorer, icons are changed to vscode style, and cannot tell out C#/C++/H/etc...

Please add an option to choose whether to use VSCode file icon or not.

PS: This problem doesn't appears in insider build 0.10.13.

### PR DESCRIPTION
**Pull request by bpasero**
fixes #4845

### CODE REVIEW

**Comment by Astrantia** [comment]
@bpasero how do we start using this? Is reinstall needed or will the update of insiders work too?

**Comment by bpasero** [comment]
@Astrantia whatever the OS decides how to invalidate file icon caches. On macOS we have the icons in a Info.plist and on Windows we update the registry on each installation as far as I know.

**Comment by Astrantia** [comment]
@bpasero Makefile's icon is not changed on Windows.

**Comment by bpasero** [comment]
@Astrantia yeah we did not include icons for all file types. how did you get the new icons, is there a way in Windows to force update the icons?

**Comment by Astrantia** [comment]
@bpasero So, in my case I had both vscode and vscode-insiders installed. I had installed vscode first, so all the associations were the blue vscode icons. When I updated vscode-insiders, the file associations weren't changed, they still were the icon from stable vscode. I, then, uninstalled stable vscode (and if I remember correctly reinstalled Insiders), and this enabled the new icons. Same with other associations. E.g: I had installed Typora and markdown associations weren't replaced with the new setup. Only after uninstalling Typora and (reinstalling insiders? cant remember if reinstall is necessary) did I get the new icons.

**Pull request merged**
