### PR TITLE
Adding AI JS vector databases

### PR DESCRIPTION
**Pull request by Emmakamnang**

### CODE REVIEW

**Comment by Emmakamnang** [comment]
adding new AI JS databases.

**Comment by isidorn** [comment]
That PR looks a bit off, I see 1300 lines changed. 
It should be a small PR only changing the areas you are interested in.

**Comment by gjsjohnmurray** [comment]
See also #211822

**Review by isidorn — CHANGES_REQUESTED** [review]
The changes to the existing `workspaceTagsService.ts` looks good.
However this PR also introduces a new file workspaceTagsService. Please update the PR, so no new files are added. Thanks

**Review by isidorn — APPROVED** [review]

**Review by isidorn — CHANGES_REQUESTED** [review]
Bad whitespace identation, the oss check is failing.
Please fix the whitespace by running the formatter, or just respecting the whitespace as it is in the rest of the file (pay attention to tabs vs spaces)

**Comment by isidorn** [comment]
Also can you please add `onnxruntime-web` as an npm package. We are curious about this one.

**Comment by isidorn** [comment]
There are still errors in the source code. As you can the Code OSS check is failing.
Can you please fix?

Screenshot 2024-06-20 at 10 42 22

**Comment by isidorn** [comment]
Thanks for this PR, but GitHub shows that a `vscode` submodule is added. At the top of this PR there are 2 files changes. There should be just 1. Can you please fix?

If you hit issues, then I suggest to just open a new PR with your workspaceTagsService changes (which look good).

**Pull request closed without merging**
