### PR TITLE
Add editor action for closing all diff editors at once

### PR DESCRIPTION
**Pull request by cadewey**
This is a new editor action that greatly improves one of my most common workflows, and that I think may be encountered by other people using VS Code with settings similar to my own.

**Scenario:**

I always have VS Code configured with `"workbench.editor.enablePreview": false`, because I find that I generally want files to be kept open after navigating to them and there is less friction when I don't have to remember to double-click. The tradeoff is that when prepping my changes for commit, all of the diff viewers will remain open as well.

**Proposal:**

Add a "Close All Diff Editors" command to the relevant context menus, so that the user can get rid of all the diff views in one shot once they've finished using them, but still leave all their code editors open to continue working. This is especially useful for anyone that likes to make lots of bite-sized local commits.

This is implemented in the service-layer as a more generic "close everything of a specified type", but the only action wired up to it currently is for diff views.

**Demo:**

close-diff-editors

### CODE REVIEW

**Comment by rebornix** [comment]
Start with @joaomoreno to see if he thinks it's a good idea to have it.

**Comment by joaomoreno** [comment]
Interesting, definitely!

**Comment by joaomoreno** [comment]
Actually this should've gone to @bpasero all along. But seems OK to me.

**Comment by bpasero** [comment]
Thanks for the PR but I find this action too specific to accept it as general thing.

**Pull request closed without merging**
