### PR TITLE
When filtering a tree don't hide unresolved folders (#66971)

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR addresses #66971. When filtering a tree containing folders whose contents have not yet been fully resolved, retain these folders. This allows the user to expand any whose contents they think might match the filter. If after expanding all nested subfolders there are no matches the folder is excluded from the filtered tree.

Below is an example showing filtering the tree-view-sample Explorer tree for json files without previously having expanded the folders.

Before the change:

junk

After the change:

junk

Observe how the folders remain visible despite their names not matching the filter. Expanding `src` reveals one matching child. Expanding `media` results in that folder disappearing because it contains no matching children and no subfolders.

### CODE REVIEW

**Comment by lramos15** [comment]
Thanks for creating the PR. We will have to discuss this as from a UX perspective I think it's still a bit weird that you clicked media for example and it just dissapears

**Comment by gjsjohnmurray** [comment]
@lramos15 yes, a bit weird and I'll be interested to hear feedback from the UX sync. Perhaps some animation would help (fade, then close up the gap). But I think it's less weird than the current experience of no being able to use tree filtering to locate files in folders you haven't expanded at least once.

**Comment by ADTC** [comment]
Nice job! 100% I hope this gets merged. Honestly the `media` folder disappearing when opened is a **million times** better than all folders disappearing when searching. Unless you guys with I expertise have a better idea, please don't let that stop you from merging.

**Comment by joaomoreno** [comment]
I like the approach, and I agree with @ADTC: it's better than today.

I don't think the implementation is correct. The situation in which "a node has not yet been resolved" only happens in `AsyncDataTree` instances. It doesn't make sense to pollute the `IndexTreeModel` with unnecessary information. I'd like to see a fix around `AsyncDataTree` and, very possibly, `AbstractTree`.

**Comment by gjsjohnmurray** [comment]
> The fix should be purely around AsyncDataTree and, possibly, AbstractTree.

I just submitted #167074 as an attempt to do this. It works, but a critical line of my change produces two TS compile errors. I need guidance about how to resolve these.

**Comment by joaomoreno** [comment]
Closing in favor of https://github.com/microsoft/vscode/pull/167047

**Pull request closed without merging**
