### PR TITLE
Always Show File Names in Symbol Search Results

### LINKED ISSUE #26370: Show file (and position) of workspace symbols
Since workspace symbol search has a high chance of returning many items with duplicate names we should show the file and position where they are defined. Also, this information should be searchable. 

TypeScript has [ghetto fix](https://github.com/Microsoft/vscode/commit/c94789c509a8d85400d3d94bc70c8456af1b0a09 ) this which is bad because 
* it breaks with the paradigm that extensions provide data and that we provide the presentation/ui by abusing todays rendering/layout
* it assumes only TypeScript developers are interested in this information and sets a bad sample 
* it messes with folks that use this information via the complex api command (`vscode.executeWorkspaceSymbolProvider`)

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #26370

Updates the symbol search results to always display the filename. This feature was previously added to the TS extension specifically, so this change removes that work in favor of a change to the core symbol search experience

Here's what the new results look like:

screen shot 2017-05-11 at 11 01 28 pm

Compared to the current results:
 
screen shot 2017-05-11 at 11 07 30 pm

Please let me know if you have any UX suggestions on where to display everything here.

### CODE REVIEW

**Comment by jrieken** [comment]
Unsure about the UI. The place is today used for a category/group indication, not for filenames. Also, the lack the folder in which they are and I doubt that they are searchable. cc @bpasero for better suggestions

Wrt the implementation be aware that workspace symbol providers are free to return *incomplete* symbols, esp. without a location. You must resolve the before accessing its location (and/or be prepared for not having a location). Take a look [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2013) for a sample of resolving  items before opening them.

**Review by jrieken — CHANGES_REQUESTED** [review]
needs changes

**Comment by bpasero** [comment]
Can we start simple and just add the file name with a "-" after the symbol and get some selfhosting on it to see how it goes?

**Comment by mjbvz** [comment]
Yes, using groupName was wrong semantically but we do already do use it to display the keybindings for commands.

Here's what the update using dash looks like though:

screen shot 2017-05-12 at 7 43 45 pm


I personally still like the multiline result display (probably without the line and column indicators though):

screen shot 2017-05-10 at 5 11 04 pm

It presents useful information in logical locations and also avoids messing with the existing label that symbol providers return to us. It is entirely possible that existing providers already put the filename in their symbol labels (much like the TS prototype attempted), which is going to look weird with the ` — ` based label

**Comment by mjbvz** [comment]
Ok, I talked with @kieferrm and we're going to try out single line ux using the `containerName - fileName` approach in insiders

**Pull request merged**
