### PR TITLE
debug: allow debugging the renderer process

### PR DESCRIPTION
**Pull request by connor4312**
This adds a new parameter to the `launchVSCode` request --
`debugRenderer`. If set to true and we're in Electron, the main process
will attempt to stand up a CDP-speaking server and respond with the port
the debugger can connect to in order to handle debug events.

Note: this only works when webviews are iframe-based. It's _possible_
to do the same treatment to Electron webviews with greater complexity. I didn't
implement that today, and maybe we say since iframes are coming
eventually (and they can be toggled on with a user setting that we could
have in the starter...) we don't need do add handling for that.

This does not work when debugging in web because there's no way to
force the browser to enter debug mode.

Code in this PR is still rough, I will keep this in PR until
I have js-debug working end to end and iron out any kinks.

Works towards https://github.com/microsoft/vscode/issues/96626

### CODE REVIEW

**Comment by connor4312** [comment]
@weinand this is ready for review now; I've got it working end to end now, pending polish on the js-debug side of things.

**Review by weinand — COMMENTED** [review]
The code changes look good to me but I could not get the web UI  ("yarn web") to work with your branch (even after merging with the latest).

This is the error I was running into:


Extension debugging worked fine in the desktop app.

**Comment by connor4312** [comment]
I updated the IExtensionHostDebugService and I think will need to make the corresponding change in the server. I'll do so and merge.

**Comment by connor4312** [comment]
yarn web and web debugging actually do work for me with these changes (webviews can't be debugging in web because browsers, but that's expected). I thought I had to change something in the server but it looks like that's not the case. The error you're running into looks unrelated most likely.

**Review by mjbvz — APPROVED** [review]
Webview changes look good to me

**Pull request merged**
