### PR TITLE
Fix view order

### PR DESCRIPTION
**Pull request by ryenus**
> `const orderA = viewStateA ? viewStateA.order : a.order;`
> `const orderB = viewStateB ? viewStateB.order : b.order;`

Here when `viewStateA` has a value like `viewStateA == { order: undefined; }`, we would get `undefined`, even though we should have fallback to `a.order`.

### CODE REVIEW

**Comment by sandy081** [comment]
@ryenus What is the issue with the current code and is there some mis-behaviour we see in function?

**Comment by ryenus** [comment]
@sandy081 yes, it's about the sorting the views. there was a little surprise cause by this.
See [this comment][1] in my [other pull request][2].

Because of a recent change in this part of the code, that PR is now having a conflict, making it worth to separate this change to a separate pull request.

[1]: https://github.com/Microsoft/vscode/pull/47766#issuecomment-384511570
[2]: https://github.com/Microsoft/vscode/pull/47766

**Comment by sandy081** [comment]
@ryenus How about having this change along with other pull request.. it will be easier to understand the context?

**Comment by ryenus** [comment]
@sandy081 done, see PR #47766, which is updated to avoid conflicts.

**Pull request closed without merging**
