### PR TITLE
Fix Korean translation

### PR DESCRIPTION
**Pull request by niceb5y**
In Korean, '찾기' means Find, not mac Finder.
I changed it to '파인더' that sounds 'Finder' in Korean.

### CODE REVIEW

**Comment by niceb5y** [comment]
I added another commits with word 'later'
In Korean, '이상' doesn't mean 'later'.

**Comment by dbaeumer** [comment]
John, can you please merge this into our master database.

**Comment by dbaeumer** [comment]
@niceb5y thanks a lot for the contribution. Unfortunately, the i18n files are machine generated (as indicated in the comment) and we can't accept pull request on them. But I have the translation team to consider your changes and directly merge them into our translation database.

**Comment by johnliu2016** [comment]
@lukaschal  "Later" needs to be fixed in following loc files. Suggested KOR string is "나중에"

[cli.contribution.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Felectron-browser%2Fdarwin%2Fcli.contribution.nls.resx.lcl&version=GBmaster&_a=contents)

[update.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Felectron-browser%2Fupdate.nls.resx.lcl&version=GBmaster&_a=contents)   

   <Item ItemId=";later" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Later]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[이상]]></Val>
          </Tgt>
        </Str>
<Item>

**Comment by johnliu2016** [comment]
"Mac Finder" KOR translation issue

[electronFileActions.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Ffiles%2Felectron-browser%2FelectronFileActions.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";revealActiveFileInMac" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Reveal Active File in Finder]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[찾기에 활성 파일 표시]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="hjkim" DateTime="2016-03-16T12:32:18.0007221Z" />
        <Props>
          <Str Name="TranslationStatus" Val="In Sync" />
          <Str Name="TranslationStatusPosition" Val="6 - SignedOff" />
        </Props>
      </Item>
suggested string is "파인더에 활성 파일 표시"

      <Item ItemId=";revealInMac" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Reveal in Finder]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[찾기에 표시]]></Val>
          </Tgt>
        </Str>
      </Item>
suggested string is "파인더에 표시"

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Please, is it possible to add ENU/KOR screenshot with mentioned string "Later" ?

**Comment by niceb5y** [comment]
@lukaschal

**Comment by lukaschal** [comment]
Fixed as suggested.

SRC: Reveal Active File in Finder
NEW TGT: Finder에 활성 파일 표시

SRC: Reveal in Finder
NEW TGT: Finder에 표시

SRC: Later
TGT: 나중에

**Pull request closed without merging**
