### PR TITLE
fix: vertical alignment issue of icons in the tab list in terminal

### PR DESCRIPTION
**Pull request by vagusX**
## Before

image

## After

image

### CODE REVIEW

**Review by meganrogge — APPROVED** [review]

**Comment by vagusX** [comment]
Anyone would merge this pr

**Comment by Tyriar** [comment]
Vertical alignment looks fine to me:

image
image

**Comment by Tyriar** [comment]
Passing to @daviddossett, I'm a little scared of the change tbh as this will impact _a lot_ of places in the UI. I also can't reproduce the issue.

**Comment by daviddossett** [comment]
Chatted with a few folks on the team and all agree that this is a risky change that touches quite a number of areas. Unless we can easily prove it doesn't break anything where `.monaco-icon-label` is used, I suggest we hold off on this one.

**Pull request closed without merging**
