### PR TITLE
enable find in the debug console

### LINKED ISSUE #4338: Debug Console should support find
- VSCode Version: 0.10.10
- OS Version: Ubuntu 14.04

This goes along with a few other debug console feature requests that I see (ex: #3974), but it would also be nice if find worked in the debug console.

Steps to reproduce:
1. Start debugging something, have the console be full of text
2. Hit Ctrl-F to find

Result: Find works in the editor window instead of the debug console

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #4338

Follow up work will be:
- making it screen reader friendly: https://github.com/microsoft/vscode/issues/225157
- it looks jumpy when I search, can that be fixed?

https://github.com/user-attachments/assets/ebc4c269-aa1a-4ab8-bb71-7678c47dc069

### CODE REVIEW

**Review by connor4312 — DISMISSED** [review]
lgtm

**Comment by connor4312** [comment]
This gets rid of the filter entirely in the view now, right? I'm not sure that's something we'd want to just remove without giving some replacement action in its place, even if it's just an explicit button that opens the find widget

**Comment by meganrogge** [comment]
fixed 

Screenshot 2024-08-08 at 1 45 59 PM

**Comment by meganrogge** [comment]
I just realized that currently, tree find is limited - it can only highlight matches found in the input - like the filter widget. It cannot highlight matches found in the output, only filter those results.

**Review by mjbvz — APPROVED** [review]

**Comment by roblourens** [comment]
I wonder about removing the filter box entirely, when the replacement doesn't support all the same features (negative patterns). Any plan to support that in the tree find widget?

**Comment by burekas7** [comment]
Thanks.
I prefer that both features remain, the 'find' and the 'filter'

**Comment by meganrogge** [comment]
Ok, sounds good. I'll bring back the filter. Maybe will go with the default tree find keybinding `ctrlCmd+alt+f` vs `ctrlCmd+f` then for this feature.

**Comment by seryte** [comment]
I hope it works the same as `find` in `terminal`

**Pull request merged**
