### PR TITLE
Remove StartupWMClass from URL handler desktop file

### LINKED ISSUE #61989: Duplicate icon in GNOME sidebar when Code is added to the favorites
- VSCode Version: 1.27.2 (OSS Code, but also happens in the latest VS Code on Ubuntu)
- OS Version: Arch Linux (kernel 4.18.12-arch1-1-ARCH)

When adding Code to the favorite applications in the GNOME environment, a duplicate icon spawns when launching the application.

screenshot from 2018-10-28 19-05-50

Steps to Reproduce:

1. Add Code to favorite applications in GNOME
2. Open an instance of Code and switch to the activities overview 

Does this issue occur when all extensions are disabled?: Yes

I'm willing to try to solve the issue if you confirm that it is related to the application.

### PR DESCRIPTION
**Pull request by valenfys**
Fixes #61989 

See also https://github.com/Microsoft/vscode/pull/56727#discussion_r229212114

### CODE REVIEW

**Comment by joaomoreno** [comment]
Awesome. Does the URL handling still work without issues?

**Comment by davidbailey00** [comment]
@joaomoreno Yep, works fine! I tested with the URL `vscode://file/etc/hosts`

**Comment by joaomoreno** [comment]
Thanks!

**Comment by pycontracts** [comment]
Doesn't work at all, I am still getting getting the second icon on Gentoo, GNOME 3.30, and removes StartupWMClass.

**Comment by pycontracts** [comment]
Update: I was able to fix the issue by actually ADDING:

StartupWMClass=code

The fix in the commit obviously is a big bummer! Please revise!

**Comment by davidbailey00** [comment]
@pycontracts are you sure you're on the latest Code version? I'm also using GNOME 3.30 (and Code 1.30.2 with this fix) so not sure why you'd be experiencing the problem but not me. Can you paste each of your `.desktop` files for Code?

**Comment by saboya** [comment]
I have the exact same issue, and adding
```
StartupWMClass=code
```
also fixed the issue for me. Also using Gentoo.

**Comment by saboya** [comment]
Arch users also have the same issue, fixed the same way:

https://aur.archlinux.org/packages/visual-studio-code-bin/

**Comment by SvenKayser** [comment]
Can confirm, adding 
`StartupWMClass=code`
fixes the issue, running Gentoo 17.0/Gnome 3.24/vscode 1.31.0

**Comment by joaomoreno** [comment]
@davidbailey00 Maybe we gotta rethink this? Can you figure out why this doesn't work for you when `StartupWMClass=code` is set?

**Comment by davidbailey00** [comment]
@joaomoreno Not sure. Maybe it works for @SvenKayser and @saboya since lowercase "code" is treated differently to uppercase "Code"?

I'm running Ubuntu 18.10, Gnome Shell 3.30.2, Code 1.32.3 and it's working correctly for me.

**Comment by saboya** [comment]
@davidbailey00 That would suggest a locale issue, but is there a locale where lowercase "code" is treated the same as "Code"?

Also, I don't think removing `StartupWMClass` is correct. Not sure how Ubuntu handles this but it's certainly different from Gentoo. What determines a window's `WM_Class`?

**Comment by saboya** [comment]
https://github.com/electron/electron/pull/858/files

`$ xprop WM_CLASS
WM_CLASS(STRING) = "code", "Code"
`

**Pull request merged**
