### PR TITLE
No longer force showing input box for screenreader

### LINKED ISSUE #120176: Setting sync: Sign in dialogs not accessibility friendly
From https://github.com/microsoft/vscode/issues/120012 by @neurrone

1. New vscode-insiders with fresh user data dir
2. Turn on settings sync, you get the Please Sign In quick pick dialog where you can check off which items you want to synchronize

This dialog is very unnacessible. Problems:
* Once the dialog is created the "Please sign in to synchronize" part is not being read out by screen reader. I recommend to use a placeholder since that would nicely be read.
* Down does not move focus to the Checkboxes
* It is hard for the user to figure out there are checkboxes below. Aria label of the input box should contain this information
* Checkbox list items do not have `aria-checked` set on them. For example on how to do this, checkout [breakpoints](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L848) 

fyi @chrmarti @TylerLeonhardt 

Screenshot 2021-03-30 at 15 02 47

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This PR fixes #120176

### CODE REVIEW

**Comment by isidorn** [comment]
The change looks great, getting rid of the workaround. Just make sure to verify with the screen reader community on Linux that this does not introduce regressions. I verified all is good on Win and macOS. Thanks for working on this.
https://github.com/microsoft/vscode/issues/94360

**Review by isidorn — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
@jvesouza @joanmarie would you be willing to try out my branch here to see if the problem has been resolved with the move to Electron 12 (aka a newer version of Chromium)?

**Comment by TylerLeonhardt** [comment]
I'm gonna merge this in so insiders can pick it up so it'll be easier for you to test.

**Comment by jvesouza** [comment]
I tested and have some observations:
1. When I press the 'ctrl+,' keys to activate the navigation settings, orca reads the following information:
'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'
To be honest, I have no idea what that information means.

2. In the dialog for choosing what should be synchronized, the 'sign in & turn on' button can only receive the focus if I use shift + tab, never with the tab key. I don't know if this is expected behavior.
3. After I click on the 'sign in & turn on' button, a list appears for me to choose whether I want to sync insiders or stable. I can choose any of them but there is no button for confirmation. It seems that I can only process the choice if I press the enter key.

**Comment by isidorn** [comment]
@jvesouza thanks a lot for trying it out.
1. `Ctrl + ,` -> navigates to the setting page, and it seems like the last focus you had was on the `editor font`, thus the editor font setting gets read. If you think this is not expected can you please file a new issue. But this feels unrelated to this issue.
2. No, this sounds like a bug. @TylerLeonhardt would you like me to create a new issue for this? It sounds like the button can only be focused by `shift + tab`
3. This is actually as expected. We simply do not render a button then. Do you find this confusing? Should we mention it in the aria label. We expect the user to press the enter key.

**Comment by TylerLeonhardt** [comment]
> No, this sounds like a bug. @TylerLeonhardt would you like me to create a new issue for this? It sounds like the button can only be focused by shift + tab

Yes please!

**Comment by isidorn** [comment]
@TylerLeonhardt created this one https://github.com/microsoft/vscode/issues/122546

**Pull request merged**
