### PR TITLE
Update sponsor colors for color contrast

### PR DESCRIPTION
**Pull request by miguelsolorio**
Refs #150830

CleanShot 2022-06-13 at 08 28 35@2x

CleanShot 2022-06-13 at 08 28 28@2x

### CODE REVIEW

**Comment by isidorn** [comment]
Sexy!

**Review by isidorn — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Comment by misolori** [comment]
I'm open to try it, I know GH doesn't color the entire text

**Comment by sandy081** [comment]
Makes sense. I am coming up with a PR that
- removes the color on the text.
- update the token names.

**Comment by sandy081** [comment]
@misolori Can you please provide a codicon with filled heart?

**Pull request merged**
