### PR TITLE
Add a special entry when disassembly is unavailable

### LINKED ISSUE #129526: Disassembly view: after session ends if new session is started the disassembly view is left empty
https://github.com/microsoft/vscode/issues/129161

fyi @yuehuang010, @xisui-MSFT)

1. Start debugging, open disassembly view
2. Stop debugging. Disassembly view is still open and shows content
3. Start debugging again. Disassembly view is empty and left lingering around

We should automatically close the disassembly view when we detect it is smart to do that.
Either when the session ends (depends if you think that users still want to inspect the disassembly). Or when the new session starts.
Or at least when the new session starts it should be reused and filled with content.

Screenshot 2021-07-27 at 14 51 42

### PR DESCRIPTION
**Pull request by xisui-MSFT**
This PR fixes #129526

Add a special entry to show text 'Disassembly not available' when the disassembly view is empty.

### CODE REVIEW

**Comment by xisui-MSFT** [comment]
@isidorn @weinand Can you please take a look? Thanks!

Draft PR because I would like to add a accessibility change for this after merging #129788

**Comment by isidorn** [comment]
I am not sure this is the best approach. Visually it might not look so good, and users might need to close it manually which can be a pain. 
Let's assign to August so we can discuss this more.

First important thing to figure out, do users want to inspect Disassembly after they stopped debugging. If **YES**, I propose the following:
1. After debugging is stopped, disassembly view is still there
2. When debugging is started again, the disassembly view is reused and filled with the new content

If **NO**
1. After debugging is stopped we automatically close disassembly view

Since we have a disassembly issues with 300+ upvotes, how about we ask the users some questions there?

**Comment by xisui-MSFT** [comment]
@isidorn Yes users may want to inspect disassembly after they stopped debugging. 

> When debugging is started again, the disassembly view is reused and filled with the new content

We can't do this because disassembly is only available on debug pause, such as a breakpoint hit.

**Comment by isidorn** [comment]
@xisui-MSFT okey, but once debugging is paused again please re-use the current disassembly view. 
So there is a transition period: while a new session is starting and before it is paused. In that case I suggest to simply update the title of the view to be `Dissasembly View(outdated)` or `Dissasembly View(stale)` or something like that.

And also make sure to close it on vscode shutdown so it is not left over for user to manage.

**Comment by xisui-MSFT** [comment]
@isidorn Sometimes the view could be empty when the debugger or debug adapter have some bugs. For example, https://github.com/microsoft/vscode-cpptools/issues/7960.

We were planning to add more special entries as we move forward, and so have a consistent way of showing errors or hints for users. As for this message in this PR, we could keep it as it is or probably change it to something like "Pause debugging or hit a breakpoint for disassembly".

> once debugging is paused again please re-use the current disassembly view.

Yes, there is only one disassembly view currently.

> And also make sure to close it on vscode shutdown so it is not left over for user to manage.

I'm not sure if I need to do anything extra here? The default behavior seems to be closing the view when closing VS Code.

**Comment by isidorn** [comment]
@xisui-MSFT ok, all makes sense.

Let me know once this PR is ready to be reviewed / merged. Thanks

**Comment by xisui-MSFT** [comment]
While ready for review, it's hard for me to do complex changes right now because of this issue: https://github.com/microsoft/vscode/issues/130947

**Comment by isidorn** [comment]
@xisui-MSFT thanks for this PR, this looks good to me. Let's merge it in.
As for #130947 I see that Deepak has responded. Hopefully that helps.

**Pull request merged**
