### PR TITLE
Fixed #64679 - Delete Lines now works with multiple selections on multiple lines

### LINKED ISSUE #64679: Multicursor delete line
Issue Type: <b>Bug</b>

Deleting lines with editor.action.deleteLines acts weird with multicursor.  

1. Create a file with 12 or more lines; create multicursor selections on  3 consecutive lines, with 2 selections per line (for a total of 6 selections).  Run editor.action.deleteLines.  I expect those three lines will be deleted, but they aren't.

2. Do the same thing, but with just one selection per line.  editor.action.deleteLines still acts weird; I would expect the three cursors to collapse into a single cursor; instead there are cursors awkwardly hanging out down below.

Sublime Text handles these situations correctly; see their behavior for a good model of what should happen.  

In both cases, I feel that the cursors should probably move back to the beginning of the line, but that may be years of expectation built up by using Sublime.  However, that makes the cursors more predictable, which is critical with multicursor (as some cursors may be off the screen so anticipating their behavior properly is really important).

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.0.3
Bookmarks|ale|10.0.0
quote-flipper|all|0.0.1
unique-lines|bib|1.0.0
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.3.2
vscode-open-in-github|fab|1.1.3
code-runner|for|0.9.5
rainbow-csv|mec|0.8.0
python|ms-|2018.11.0
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.1013
vscode-docker|Pet|0.4.0
code-settings-sync|Sha|3.2.2
whiteviz|spy|0.6.0
vscode-arduino|vsc|0.2.23
debug|web|0.22.0
better-align|wwm|1.1.6
cursor-align|yo1|1.0.4

</details>

### PR DESCRIPTION
**Pull request by irrationalRock**
This PR fixes https://github.com/Microsoft/vscode/issues/64679.

It now collapses all cursors:
multi-line

Also, now deletes multiple lines with multiple selections:
multi-select-line

Thanks for considering this request.

### CODE REVIEW

**Review by alexdima — CHANGES_REQUESTED** [review]
A few things that are not 100% good:
- `editor.executeEdits` is invoked with an empty array of edits, effectively acting as if it were a call to `editor.setSelections`.
- After running this action, we are now always going to 1 cursor. This is not good, e.g. when having one cursor per line -- I would expect to have here 3 cursors at the end:

| Before | After |
|---|---|
| kapture 2019-02-07 at 12 31 29 | kapture 2019-02-07 at 12 32 47 |




Also, another case that is not great is when having two clusters of multiple cursors -- I would expect to have here 2 cursors at the end:

kapture 2019-02-07 at 12 28 29

---

All in all, tweaking the resulting selection is not the approach I would take. I would generate `IIdentifiedSingleEditOperation` and drop the entire `DeleteLinesCommand`, i.e. I would loop over all selections, and collect all lines to be deleted. I would make sure to dedup them (like a set reunion) and then issue clear edits that never overlap. I would then insert a cursor under each such deletion.

**Comment by irrationalRock** [comment]
Thanks for the feedback, I'll go back and make the appropriate changes

**Comment by irrationalRock** [comment]
So made the changes you requested.

I removed DeleteLinesCommand entirely and now issue edits to remove text.

Here is a couple of gif to show the changes.

Three Cursors:
multi-line-select-3

Two Lines with Multiple Cursors:
multi-line-select-2-multiple


My branch needs some work done on it but I wanted to see if the cursors locations after `Delete Lines` are good or if they need adjustment.

**Comment by alexandrudima** [comment]
:+1: Thank you! It was almost perfect, I just needed to add some accounting for the deleted lines in establishing the resulting cursor selection.

**Review by alexdima — APPROVED** [review]

**Pull request merged**
