### PR TITLE
WIP #90993 - Expose shellLaunchConfig as a promise

### LINKED ISSUE #90993: Consider exposing ITerminalInstance.shellLaunchConfig as a promise
This could avoid problems like this https://github.com/microsoft/vscode/pull/90847

### PR DESCRIPTION
**Pull request by dormesica**
So far I've consentrated on adapting the existing code to a new API that exposes `ITerminalInstance.shellLaunchConfig` as a promise (I haven't dealt with making it an acutal promise yet).

One function that uses `shellLaunchConfig` is `TerminalService.setActiveInstance`
https://github.com/microsoft/vscode/blob/17a59977bc73305b1eb94de6964a7e7564d8b68b/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L312-L319
whose return type had to be changed to `Promise<void>`.

I wanted to discuss 2 things regarding this:

1. I am not sure every use of this function requires `await`. It seems to me that some functions only need this operation to be performed but do not require it for the completion of their task.
2. There is one function in particular that uses `TerminalService.setActiveInstance` but returns a boolean value.
https://github.com/microsoft/vscode/blob/17a59977bc73305b1eb94de6964a7e7564d8b68b/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L297-L324
Changing it's return type to `Promise<boolean>` requires changes in the interface that then chagnes the return type of synchronous functions. Does this function really require that `setActiveInstance` completes before it returns a value?

This PR fixes #90993

### CODE REVIEW

**Comment by Tyriar** [comment]
Seems to work fine, queued a product build to make sure it passes extra testing.

**Comment by dormesica** [comment]
It's only half the job.

As you can see I simply wrapped the existing value of shellLaunchConfig in a promise that resolved immediately because I was waiting to finish with adapting all occurances to the new API.

I will soon get to resolving the value when it is actually given.

**Comment by Tyriar** [comment]
Ah ok.

> Changing it's return type to Promise<boolean> requires changes in the interface that then chagnes the return type of synchronous functions. Does this function really require that setActiveInstance completes before it returns a value?

This was part of the exploration, if it would cause too many dependents to change to async which would cause more issues still then maybe it's not the right thing so do this?

**Comment by dormesica** [comment]
In general, I believe that any value that's not immediately available should be exposed as a Promise. But because of the amout of changes it causes maybe we can do something else.

How about exposing a "second" shellLauchConfig this time as a promise and declaring the old one "deprecated". Any new acess to shellLauchConfig would have to use the Promise API (Plus, all the other thinks that I've already adapted). In time the other thing will be changed.

What do you thinks?

**Comment by Tyriar** [comment]
Wait, so was the problem that we need this code to run?

https://github.com/microsoft/vscode/blob/11ac098428c29ffb4f6b661ee079e87d0d78c215/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1462-L1467

If so I'm not sure what we could do to improve this outside of exposing a "resolved shell launch config", but even then, there's the issue that terminals get reused and the value of shell launch configs are replaced:

https://github.com/microsoft/vscode/blob/11ac098428c29ffb4f6b661ee079e87d0d78c215/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1172-L1173

**Comment by Tyriar** [comment]
The right fix here seems a lot more complicated then I was thinking initially.

**Comment by Tyriar** [comment]
Sorry I think I'll close this one out, it seems more nuanced than I was initially thinking and should probably be done by myself.

**Pull request closed without merging**
