### PR TITLE
Fix single tab context menu actions sometimes don't work

### LINKED ISSUE #201008: single tab context menu actions sometimes don't work
image
It's those 3 options that don't work, until there are multiple shells running.

Once you have two or more shells, those options start working, as below I'm showing me renaming successfully the 2nd shell:
image

_Originally posted by @JeremyTBradshaw in https://github.com/microsoft/vscode/issues/200960#issuecomment-1858379484_

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #201008

### CODE REVIEW

**Comment by meganrogge** [comment]
@jeanp413 thanks so much for looking into this. In OSS, with your changes, I'm still seeing the issue.

**Comment by jeanp413** [comment]
@meganrogge Did you happen to test with `rename`, just realized that it has been broken for a while not related to https://github.com/microsoft/vscode/issues/199228 (will look into it) , but `change color/icon` works for me :thinking:

**Comment by meganrogge** [comment]
You are correct, the issue with `rename` reproduces in stable. I'll make a separate issue for that.

**Review by meganrogge — APPROVED** [review]
Thank you!

**Review by andreamah — APPROVED** [review]

**Pull request merged**
