### PR TITLE
fix the dialog is above the tooltips

### PR DESCRIPTION
**Pull request by RichardLuo0**
image
Expected:
image

### CODE REVIEW

**Comment by roblourens** [comment]
Hm, I think maybe we just shouldn't have hovers on these buttons though? The hover is just the text of the button. 

I repro this by running `vscode.window.showInformationMessage('Hello World from testext!', { modal: true }, 'OK');`

**Comment by benibenj** [comment]
I agree, lets just remove hovers from these buttons. There doesn't seem to be any benefits from it. @RichardLuo0 want to make the fix?

**Comment by RichardLuo0** [comment]
> I agree, lets just remove hovers from these buttons. There doesn't seem to be any benefits from it. @RichardLuo0 want to make the fix?

Sure. I have created a new PR for this: https://github.com/microsoft/vscode/pull/225772

**Comment by benibenj** [comment]
Thank you!

**Pull request closed without merging**
