### PR TITLE
Rename dipose.ts to dispose.ts

### PR DESCRIPTION
**Pull request by Huachao**

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks!

**Comment by dwilliamson** [comment]
Has this change broken latest code? I'm getting errors in 3 files:

[vscode/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts)

[vscode/extensions/typescript-language-features/src/typescriptServiceClient.ts](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/typescriptServiceClient.ts)

[vscode/extensions/typescript-language-features/src/languageProvider.ts](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/languageProvider.ts)

```
Cannot find module './utils/dipose'.
```

**Comment by mjbvz** [comment]
Fixed by 1cc5e27e641c895e4d9057efccbef80434af4ed8

**Comment by dwilliamson** [comment]
Awesome!

**Pull request merged**
