### PR TITLE
Fix #78710 - Another duplicate stat call on workspace roots

### LINKED ISSUE #78710: explorer.autoReveal causes double stat call when Explorer is refreshed
Issue Type: <b>Bug</b>

1. Fetch fsprovider-sample from https://github.com/microsoft/vscode-extension-samples
2. Check that your `explorer.autoReveal` is true.
3. Set a logpoint on the return statement of the stat function in fileSystemProvider.ts, making it log the following message:
  `stat {uri.path}`
4. Start debugging the 'Launch Extension' debug configuration
5. When the Extension Development Host (EDH) window appears, use its Command Palette as follows:
- MemFS: Setup Workspace
-  MemFS: Create Files
6. Expand the workspace root.
7. Open one of the files, e.g. file.txt
8. In your main VSCode window (orange status line), clear the Debug Console pane.
9. In the EDH (blue status line), use the Command Palette to run `File: Refresh Explorer` or click the Refresh Explorer button on the workspace titlebar.
10. On the Debug Console of the main window observe that the logpoint writes `stat /` twice.
11. Set your `explorer.autoReveal` to false.
12. Repeat the `File: Refresh Explorer` and observe only one `stat /`

The duplicated stat call is a problem in situations where this is expensive (e.g. a large number of files on a remote filesystem on a slow connection).

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

Also observed in 1.37-insider.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
Prevent a double stat call on workspace roots if Explorer is refreshed and has autoReveal enabled. See #78710. For review by @isidorn

### CODE REVIEW

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for your PR.
However I do not think this approach is good. So what you changed here is that we resolve to the resource only when `refresh` is called. This is not correct in general, since the file in the explorer can be selected for many other reasons, and at that time the resource is not resolved.
You can check out the callers of `explorerService.select`.
I think this fixes your issue out of luck.

I think we need a different approach. We need to figure out why the stat is called two times on refresh and try to prevent one of them.
Putting a breakopint in the [`select`](https://github.com/Microsoft/vscode/blob/994e1315c09a6d92e57adf8cb9d386f5b30b4b3f/src/vs/workbench/contrib/files/common/explorerService.ts#L152) method might be a good start.

Thanks a let me know what you think

**Comment by gjsjohnmurray** [comment]
@isidorn thanks for your prompt review.

In my original investigation I already used breakpoints in explorerService.ts and found what caused the duplicate stat calls on root dir(s) when refresh() is called.

One was caused by the event fired unconditionally from here:
https://github.com/microsoft/vscode/blob/9c2cc80fcdab2c949294771daa05f61652ca009e/src/vs/workbench/contrib/files/common/explorerService.ts#L188

The other (conditional upon autoReveal being true and there being an active editor) arose from the select call here:
https://github.com/microsoft/vscode/blob/9c2cc80fcdab2c949294771daa05f61652ca009e/src/vs/workbench/contrib/files/common/explorerService.ts#L194

So my main change was to move the event-firing into an else-block. This eliminated the doubled stat.

However, when testing my change using fsprovider-sample and with autoReveal=true and the active editor being a file in a subfolder of the root, I noticed that the refresh didn't make a stat call for the subfolder. For example, given this situation:
image

a refresh called stat() for the following:
- `memfs:/`
- `memfs:/xyz`
- `memfs:/xyz/def`

but there was no stat() for `memfs:/folder`

I solved that by adding the optional third parameter to the select method and having the select() call from refresh() set this parameter. That causes select's fileService.resolve() call to no longer set `[resource]` as its `resolveTo` option. Doing this fixed the missing stat() call.

**Comment by isidorn** [comment]
Thanks for your PR, however after reviewing your change more and looking into it myself I decided to leave the current not optimal behavior.
Reason being there are too many corner cases, and this code is rather tedious. So changing anything will most likely end in more bugs.
Since the proposed imporvement is not ideal I would prefer to keep this PR open and maybe merge it in the future.
Hope that makes sense

**Comment by gjsjohnmurray** [comment]
@isidorn OK. I certainly don't want to create more bugs. But I hope the issue eventually gets resolved.

**Comment by isidorn** [comment]
Closing as will not merge due to the explanation above. Hope that makes sense, and thank you again for your contributions

**Pull request closed without merging**
