### PR TITLE
add audio cues for go to next/previous change

### LINKED ISSUE #166518: Add audio cues for Go to Next/ Previous Change commands
When navigating changes with f5 or the `Go to Next` / `Go to Previous` commands, we should play audio cues - modified, inserted, deleted, based on the decorations like we now do for the `DiffReview`

This was requested here https://github.com/microsoft/vscode/issues/147226 

cc @isidorn for thoughts

### PR DESCRIPTION
**Pull request by meganrogge**
fix #166518

### CODE REVIEW

**Review by alexr00 — APPROVED** [review]

**Comment by meganrogge** [comment]
Fyi @isidorn should be ready to test tomorrow and today going to look into getting the line read by screen readers

**Comment by isidorn** [comment]
@meganrogge cool - thanks! Let me know once it is in insiders and I can try it out.

**Comment by piotrsrodka** [comment]
Can I turn it off? I hate the sound!

**Comment by meganrogge** [comment]
Yep in settings starting w the prefix audioCue.

**Pull request merged**
