### PR TITLE
Fix: selecting entry should focus back to editor

### LINKED ISSUE #106824: Quick pick: selecting entry with keyboard does not put focus back to editor
Steps to Reproduce:

1. use the language mode picker to pick a language for an untitled file
2. use the mouse to select an entry and focus moves back to the editor
3. do it again and use the keyboard (pressing enter) on an entry

=> 🐛 focus is not moving in to the editor

I think it would make sense to be consistent here and always move focus back to the editor, especially given the picker is changing the editor so you are likely to continue to type afterwards.

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #106824

If active editor wasn't focused after selection, then manually focus editor.

### CODE REVIEW

**Comment by chrmarti** [comment]
Would it make sense to move this to ChangeModeAction? That way we know it is only triggered when the user went through the picker UI.

**Comment by susiwen8** [comment]
> Would it make sense to move this to ChangeModeAction? That way we know it is only triggered when the user went through the picker UI.

Yes, It makes more sense.

**Review by bpasero — CHANGES_REQUESTED** [review]
Since there are more pickers for which this issue exists (e.g. changing encoding), I wonder if this should be added to all for consistency?

**Comment by susiwen8** [comment]
> Since there are more pickers for which this issue exists (e.g. changing encoding), I wonder if this should be added to all for consistency?

@bpasero Sure.

**Review by bpasero — CHANGES_REQUESTED** [review]
I would have expected the code to focus the active editor after each individual picker, not in that place. Maybe I am missing something? Shouldn't the focus happen after the user picked something from quick pick?

**Comment by susiwen8** [comment]
> I would have expected the code to focus the active editor after each individual picker, not in that place. Maybe I am missing something? Shouldn't the focus happen after the user picked something from quick pick?

@bpasero Yes, that's right, after user pick something from quick pick, `active editor` should been focused. But somehow, for some quick pick, selecting by `mouse click` or `enter` is  kind of different.  

For `mouse click`, `document.activeElement` become `editor` after selection, but `status bar` for `enter`(some cases). That's why I decided to manually focus `editor` after each select if `editor` weren't focused.

`doRenderNow` is the 'converge' function where all post selection would cross. So I have put logic here.


https://user-images.githubusercontent.com/20318608/104929277-a3c2da80-59de-11eb-9e64-b4c22c323f73.mp4

**Comment by bpasero** [comment]
@susiwen8 that is the thing I question

> doRenderNow is the 'converge' function where all post selection action would cross. So I have put logic here.

No, it is the function called whenever a label changes in the editor status bar, not when picking something.

**Comment by bpasero** [comment]
Thanks 👍

**Pull request merged**
