### PR TITLE
try to make submodule clearly

### LINKED ISSUE #43951: SCM - Differentiate between submodules and normal repos
### Issue Type
Feature Request

**I would like submodules to be nested underneath their parent repo in the Source Control Pane.**

### Description

I love the new submodule feature, but there are a couple of issues with the Source Control pane:

  * I can't tell which providers (repos) are submodules
  * I can't tell what top-level provider a given submodule provider is associated with

For most situations, this probably isn't an issue. But for some of my projects, it is a serious issue. For example, I have projects:

  * A - depends on nothing
  * B - depends on A
  * C - depends on A and B
  * etc

For development, I use a multi-root workspace with a directory structure something like this:

  * Projects
    * A
    * B *(references `../A`)*
    * C *(references `../A` and `../B`)*

For continuous integration and deployment, I use submodules:

  * C *(references `./.libs/A` and `./.libs/B`)*
    * .libs
      * A
      * B *(references `/builds/C/.libs/A`)*

While I could leave the submodules uninitialized on my dev machine, my workflow includes doing a build with submodules before I push, to ensure I haven't forgotten to update a submodule, because why waste CPU cycles on a CI build that's guaranteed to fail.

In this particular example, where B has A as a submodule, and C has A and B, I will have six repos (A, B, C, B/.libs/A, C/.libs/A, and C/.libs/B) show up in VSCode. While I can and do disable submodule discovery for these projects, that doesn't stop VSCode from picking them up when I open a file in a submodule.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

### PR DESCRIPTION
**Pull request by wolfsilver**
This PR tries to fix #43951

before:
image

after:
image

test repos:
https://github.com/wolfsilver/repo-A
https://github.com/wolfsilver/repo-B

### CODE REVIEW

**Review by glaukiol1 — APPROVED** [review]
Yes! I was looking for something to make this clearer, thanks!

**Comment by wolfsilver** [comment]
@eamodio any better idea？

**Comment by ThaDaVos** [comment]
Any ETA of this? Having the same issue myself and would love to see a tree-view like structure like the `changes` can do, so it's easier to what it the submodule and where it is related to the base repo

**Comment by wolfsilver** [comment]
> Any ETA of this? Having the same issue myself and would love to see a tree-view like structure like the `changes` can do, so it's easier to what it the submodule and where it is related to the base repo

try this out
https://marketplace.visualstudio.com/items?itemName=R.git-submodule-sort

**Comment by ThaDaVos** [comment]
Can't use it, getting the `VSCode cannot modify itself error`

**Comment by wolfsilver** [comment]
> Can't use it, getting the `VSCode cannot modify itself error` and I am not gonna run it as Administrator

follow this step to solve.
https://github.com/be5invis/vscode-custom-css#windows-users

**Pull request closed without merging**
