### PR TITLE
Copy `code-icon.svg` to near where it is used

### LINKED ISSUE #19541: [WelcomeUX] Copy `code-icon.svg` to near where it's used
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/walkThrough/electron-browser/walkThroughPart.css#L144
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcomePage/electron-browser/welcomePage.css#L263

The icon should be copied close to the CSS where it is being used, just like every icon and image we have.

The only reason this is working now is that @alexandrudima enabled SVG inlining *when* the SVG is small enough and the loader actually is able to escape the `vs` namespace during bundling.

### PR DESCRIPTION
**Pull request by chrmarti**
@joaomoreno Please take a look (fixes #19541)

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I meant it as: literally commit a copy of that file, leaving the original untouched.

This is as bad now, since the build needs to understand `src/vs/workbench/parts/welcome`.

**Comment by chrmarti** [comment]
@joaomoreno Could you be more specific what needs to be done here?

**Comment by joaomoreno** [comment]
Sure, sorry if I was ambiguous.

```
cp resources/code-icon.svg src/vs/workbench/parts/welcome/page/electron-browser
cp resources/code-icon.svg src/vs/workbench/parts/welcome/walkThrough/electron-browser
```

And then change both references

```
background-image: url('../../../../../../../resources/code-icon.svg');
```

to

```
background-image: url('code-icon.svg');
```

**Comment by chrmarti** [comment]
@joaomoreno Got it: I'll do that in the distro repo, right? Also: I can move them since they are only used for the welcome ux. And: `src/vs/workbench/parts/welcome` would probably be ok, so I can share it between the two subfolders?

**Comment by joaomoreno** [comment]
Now I understand why the current solution is as is! And the fix likewise! The icon is in the distro repo! That's pretty bad.

I'm more in favour of using a meaningful icon for each of the features instead of the product icon. From https://vsicons.azurewebsites.net/, the VSTS Bowtie Icon Font collection, I suggest the following icons:

- For the Welcome, search for `alert`. The second icon, which is a flag, would do the trick. Alternatively, maybe `devices` or `globe`?
- For the interactive playground, search for `run`. Any of those play button icons should work perfectly. Alternatively the `log` icon is pretty good too.

What do you think?

It would be great to have a solution which isn't hacky, scales and doesn't make the build work even more.

**Comment by chrmarti** [comment]
@joaomoreno Let's fix the technical issue first and discuss the icon choice later. The only additional "work" the build does with this is to overwrite the icon as part of its existing mixin step. (Not sure which part you consider hacky.)

**Comment by chrmarti** [comment]
I already do what you suggest (except I placed the icon at `src/vs/workbench/parts/welcome`). I reverted the change to gulpfile.mixin.js in my second commit. I'll just merge that since it seems pretty clean. I've opened #20131 for revisiting the icons.

**Comment by joaomoreno** [comment]
Cool. I just don't see the matching VS icon in the right folder in the insiders and stable qualities, in the distro repo.

**Comment by chrmarti** [comment]
Hah! I better merge that from my private branch, thanks! :)

**Pull request merged**
