### PR TITLE
Improved description for editor.useTabStops setting

### LINKED ISSUE #205298: Update description for the setting `editor.useTabStops`
I'd like to update the description for the setting `editor.useTabStops`

Right now it reads

> Inserting and deleting whitespace follows tab stops

I've been programming for a long time and this doesn't make any sense to me.  I'd like to change it to something that's more intuitive to developers.  I can suggest more dev-friendly wording once someone explains what this setting does,

### PR DESCRIPTION
**Pull request by BrookMaoDev**
**Issue Reference:** Should resolve #205298

**Previous Description for `editor.useTabStops`:**
> Inserting and deleting whitespace follows tab stops.

**Proposed New Description:**
> Inserting and deleting whitespace follows tab stops. Full tab deletion occurs upon removing indentation.

This update aims to offer a more informative description for the `editor.useTabStops` setting, clarifying its behavior. Feedback and suggestions are welcome before finalizing the pull request.

### CODE REVIEW

**Comment by hediet** [comment]
To be honest, I understand neither the old nor the new description.

**Comment by BrookMaoDev** [comment]
Okay, I will try and improve it, thanks for the feedback!

**Comment by BrookMaoDev** [comment]
Hi @hediet, could you kindly review my updated description?

> Spaces and tabs are inserted and deleted in alignment with tab stops.

I also considered:

> Inserting and deleting whitespace aligns with tab stops.

I replaced "follows" with "aligns with" to improve clarity, as suggested by the author of the issue. Would you like further clarification on tab stops, or do you think the descriptions are clear enough? Thank you for your time!

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
Thank you!

**Review by chrmarti — APPROVED** [review]

**Pull request merged**
