### PR TITLE
Isidorn/vertical panel

### PR DESCRIPTION
**Pull request by isidorn**
This PR adds the vertical panel.

As part of this I have also:
* Restructured old layout code 
* improved min and max boundary computations
* removed the ToggleMaximizedPanelAction - the reason for this is that the action was damn ugly to implement and I believe the vertical panel will be a fine alternative to this (especialy since I store size per panel position, so a user can have a vertical panel very large and a horizontal quite tiny, so he can also swithc to vertical when in need of more space)
* am using a VS icon for the action currently. For a better icon I would need help from @chryw

### CODE REVIEW

**Comment by suciuvlad** [comment]
It's pretty annoying that "ToggleMaximizedPanelAction" was removed actually 👎 . I'm coming from a tmux vim setup where i have the screen split into two(line length set to 80 chars) and the terminal always open at the bottom. http://d.pr/i/Vxp7QN It's very hard to read the terminal in full height now.

**Comment by isidorn** [comment]
@suciuvlad it's back now. check out latest insiders

**Comment by suciuvlad** [comment]
@isidorn Thanks!

**Comment by contention** [comment]
@isidorn - Thanks... appreciate the work you've done on this. Been waiting for this PR a while and it makes a big and positive difference, at least to my own workflow. :o)

**Pull request merged**
