### PR TITLE
Add a setting to control which next editor to reveal after closing one

### PR DESCRIPTION
**Pull request by gurs1kh**
Addresses https://github.com/microsoft/vscode/issues/162460

### CODE REVIEW

**Comment by gurs1kh** [comment]
@microsoft-github-policy-service agree

**Comment by gurs1kh** [comment]
@bpasero what changes are needed for this? I am unable to view the build

**Comment by bpasero** [comment]
Thanks for the PR, I cannot make promises when I get a chance for review though.

**Review by bpasero — CHANGES_REQUESTED** [review]
We cannot just change an existing setting and the name of that setting is also misleading. We need to deprecate that setting and would have to add a new setting, maybe similar to the one for opening:

image

We still need to respect the deprecated setting if configured and then fallback to the new one.

**Pull request closed without merging**
