### PR TITLE
Titlebar: clear content when screen reader detected

### LINKED ISSUE #89175: VSCode title should not contain editor label when screen reader is detected
Turn on a Screen Reader.
Every time the VSCode window is focused the Title is read out with the editor aria.
This leads to duplication and annoyance.

Another issue is if the focus was for example in the search input box, the Screen reader will still announce the editor name which is part of the title. Which is confusing for the screen reader, since the focus is actually in the search.

Due to that I suggest that the title area is simply vscode when a screen reader is detected.
@bpasero if you do not have time let me know what you think and provide a code pointer and I can implement this.
Here's the event and service which we should use
https://github.com/microsoft/vscode/blob/3efd575c64786100f67d80a29783715ccb3a9f18/src/vs/platform/accessibility/common/accessibility.ts#L15

Related https://github.com/microsoft/vscode/issues/89098

### PR DESCRIPTION
**Pull request by isidorn**
Fixes #89175

As explained in #89175 currently the screen readers read too much when the vscode window gets focused. This way I clear the title to be empty so the screen reader does not read too much.
If I set the title to ' ' or '' it would be reset and set to `VS Code INsiders` which we do not want since that is already read out. I really want it to be empty and this is the only solution which workes just fine.

@bpasero Let me know what you think. Thanks

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
I think this is OK for screen readers. But this also means that any assistive tool no longer can identify the window (I think). Should we rather put just the product name always?

**Comment by isidorn** [comment]
Just double checked on Windows and there are some missing things:
- [ ] it seems like this change is only affected for native title bar. When we use a custom title bar this change is not picked up
- [ ] you are correct, we should at least have the produce name, since the product name duplication is only happening on the mac. I will update the PR, and you can provide a pointer for the first issue

**Comment by isidorn** [comment]
It actually might be just fine to only do this for the native title bar, since the custom bar does not get read out by NVDA.

So the current approach might be the way to go:
- There is only duplication read out on the mac. The mac uses the native title by default, thus clear the native title content to avoid duplication
- On windows there are no problems and the custom title is by default. So we are good.

Let me know what you think

**Comment by bpasero** [comment]
@isidorn yeah so visually for users not a lot would change if the native title was not filled (since we show a custom one), though there are cases where the user might have native title enabled via settings.

However, the title may also be used in other places for tools to identify what program is running. E.g. I think there are some third party tools that allow to navigate between opened windows and they may use the window title as a way to identify the window. We would probably loose that support if we did it.

More infos: https://github.com/microsoft/vscode/issues/84195

**Comment by isidorn** [comment]
You are correct. I just went over that thread and even installed the Witch app. 
If we do this we will break screen reader users that use Witch. I am not sure how many of those there are, and I am fine pushing this to find out and get feedback.

Currently the title is FILENAME -- vscode.
Why not just make it FILENAME? Why do we have the -- vscode suffix?

**Comment by isidorn** [comment]
Actually decided not to merge this in.
Users can configure this via `"window.title": "\u200B"` and I will advise them to do that

**Pull request closed without merging**
