### PR TITLE
Monokai fixes

### PR DESCRIPTION
**Pull request by ryanagillie**
Used color picker and sublime to get accurate colors for most of the Monokai theme. Changed the `this` keyword to be italic, and removed the underlines from class names and class inheritance

### CODE REVIEW

**Comment by rag4214** [comment]
Fulfils #55972

**Comment by rag4214** [comment]
My second round of commits went through and changed all of the color pallets to match Sublime's. No more half changed colors. All of the token colors should now be consistent.

**Comment by aeschli** [comment]
@rag4214 Thanks a lot for your efforts.
I'm hesitant to make color changes to the built-in themes as there are always users that got used to the current colors and will speak up on changes. There has been several rounds of tuning for the highlight colors so they all work well together that might be invalidated by changes.

Instead I'd suggest you to publish your theme on the Markertplace, so everyone has the choice.

**Comment by rag4214** [comment]
@aeschli would it at least be possible to change `this` to italics and not have Class / Inheritance names underlines? If not I understand.

**Comment by aeschli** [comment]
Sorry, I rather not start making changes.

**Pull request closed without merging**
