### PR TITLE
Status bar wrapping: Wrap only right items. Hide left items on overflow

### LINKED ISSUE #84258: Allow individual status bar messages to clip instead of hide
- Create a status bar item with a message
- If the message does not fit then the entry is hidden. Instead the message should be clipped.

Background: Supporting a feature to show current error in the status - https://github.com/microsoft/vscode/issues/20183

### PR DESCRIPTION
**Pull request by sandy081**
Fixes https://github.com/microsoft/vscode/issues/84258

### CODE REVIEW

**Comment by sandy081** [comment]
Kapture 2019-11-11 at 10 35 39

**Review by bpasero — APPROVED** [review]
@sandy081 I think this is a good direction, however I am missing the visual indicator "..." so that users understand the label is cut off.

Also please check how this behaves when extensions reference icons ($(....)), e.g. would that cause the icon to be broken?

**Comment by bpasero** [comment]
Sorry, I did mean to "request more changes", not to approve.

**Comment by sandy081** [comment]
I do not think it is possible to show ellipsis with the flex layout and items with octicon text. Let me know if there is a way.

**Comment by bpasero** [comment]
@sandy081 true. then I suggest we go with this change for insiders and see if people complain

**Pull request merged**
