### PR TITLE
Update spdlog, use lazy initialization in extension host

### PR DESCRIPTION
**Pull request by rzhao271**
This PR affects #121513

Currently, node-spdlog 0.13.1 exposes two async factory methods to construct rotating synchronous loggers and rotating async loggers.
I have changed some of the code in the extension host to initialize the async logger only when it needs to be used.

### CODE REVIEW

**Comment by deepak1556** [comment]
Also bump the version of spdlog in `remote/package.json` to fix the error, they should be kept in sync.

**Review by deepak1556 — APPROVED** [review]
LGTM on the native module update.

@sandy081 can you review the code changes to `extHostOutputService`, thanks!

**Review by bpasero — APPROVED** [review]
I am worried that changing the `createRotatingLogger` to be async will have unexpected consequences in the `OutputAppender` because essentially clients of `append` and `flush` might expect that the code is sync when in fact it is async within.

I [pushed a change](https://github.com/microsoft/vscode/pull/123033/commits/c1931acb184ec00c55a5cbec021e15f60b55bbce) to restore the previous behaviour of having the `Logger` be ready when used, I am not entirely sure what the lazy instantiation brings.

**Comment by bpasero** [comment]
No I am happy now, 🚢  it.

**Pull request merged**
