### PR TITLE
Let core command such as  undo/redo be overridden by webviews and notebooks

### PR DESCRIPTION
**Pull request by mjbvz**
For #90110

This change add hooks so that core command, such as undo and redo, can be overridden by higher level parts of the workbench, such as for notebooks or webviews.

## Why is this needed?
To implement undo/redo in custom editors  and webviews, we currently register special commands (`editor.action.customEditor.undo` and `editor.action.customEditor.redo`) that are only active when a custom editor is focused. This is not ideal since it means that users have to update multiple commands if they wish to rebind undo/redo

These custom command also are not invoked when the user goes to the `edit` menu and selects `undo` or `redo`. Instead, the edit menu always calls the core `UndoCommand`. `UndoCommand` live in `vs/base` so we cannot add custom editor specific logic to it

## What this change does
This change adds a new `CommandOverrides` class that stores a list of potential overrides for a command. I've updated a few of the built-in core commands to have a `CommandOverrides` property: undo, redo, cut, copy, paste, select all.

I've also updated webviews, custom editors, and notebooks to use the `CommandOverrides` instead of defining their own duplicate commands

### CODE REVIEW

**Comment by mjbvz** [comment]
@rebornix If this approach looks good, you should also be able to hook up notebooks to use the shared `undo` command instead of having your own `notebook.undo` command

@Tyriar I believe this could also let the terminal hook into our shared `select all`, `copy`, and `paste` commands if it makes sense to do so

**Review by bpasero — CHANGES_REQUESTED** [review]
I find this is not the right approach, why make this dependent on the editor? I think the better model is that the text editor is one participant of a global undo/redo command. [Eclipse had the concept of retargetable actions](https://webcache.googleusercontent.com/search?q=cache:8BS5ICCvQhsJ:https://wiki.eclipse.org/FAQ_How_do_I_hook_into_global_actions,_such_as_Copy_and_Delete%253F+&cd=6&hl=en&ct=clnk&gl=ch) for that same purpose: there is one undo/redo but different parties can hook into that command depending on e.g. what is currently focused. Maybe we can learn from that approach?

**Review by alexdima — CHANGES_REQUESTED** [review]
I also find that this way of "stealing" the command invocation through a service is complex and difficult to understand, maintain or debug.

I suggest two possible ways:
- go with an approach that Ben suggested. I like the idea to have a base command that can look at `document.activeElement` and iterate through a list of registered handlers and each handler can decide if it can handle undo/redo for this particular dom node or not. This reminds me of the chain of responsibility pattern.
- go with two distinct undo/redo commands, one for the standalone editor that can be moved somewhere imported from `editor.main.js` and that remains implemented like it is today and make another set of commands that are registered from the workbench and which can have knowledge about code editors, webviews and native DOM inputs.

**Comment by Tyriar** [comment]
> @Tyriar I believe this could also let the terminal hook into our shared select all, copy, and paste commands if it makes sense to do so

This isn't actually what we want in the terminal, at least not with default keybindings. Copy cannot be ctrl+c and select all can only be bound by default on mac. If we wanted to do this such that keybindings could be shared, we would still likely need custom keybindings for these commands registered within the terminal contrib anyway.

**Comment by mjbvz** [comment]
@Tyriar I think you could also potentially use this service to just hook into the menu commands (such as select all) but keep your existing separate commands for keyboard shortcuts. I'd need to test this though

**Comment by mjbvz** [comment]
Thanks for the feedback @alexdima and @bpasero. I've removed the service so that each of the commands now says if it is overridable or not. 

If this approach seems ok, I will try extracting a generic version of the core commands (undo, redo, copy, ....) to a new file and have the editor versions hook into there instead of having the editor versions be the base version of each command

@rebornix I've also updated notebooks to use this new approach, which simplifies the code

**Comment by mjbvz** [comment]
I tried adding a extracting restructuring the code to have the following structure:

```
export const Undo = new RegargetableCommand(options);
Undo.registerTarget(EditorOrNativeTextInputUndoCommand);
```

There are two issues with this:

- Many of our unit tests call `.runDOMCommand` or `.runEditorCommand` directly
- This does not work for the clipboard since the clipboard commands extend editor action instead of editor command

For now, I think the the composition based approach in the current PR is going to be much cleaner. I'll work on cleaning up the implementation of that

**Comment by mjbvz** [comment]
It's pretty late in the iteration so let's take a look at this for June instead

**Review by alexdima — APPROVED** [review]
I've just pushed my review changes directly to the branch. Basically, I have extracted Cut, Copy, Paste, Undo, Redo and SelectAll to be `MultiCommand`s which means they have no implementation, but rather multiple implementations, in a chain of responsibility kind of way.

This puts the editor implementation on equal footing with the custom editor & notebook implementation.

At one point, we might want to move these down to `/platform/`, but I didn't bother to try that.

**Comment by mjbvz** [comment]
Thank you for your help on this @alexdima. It looks much cleaner now.

@rebornix Please let me know if this change causes any issues for notebooks. It should enable using menu controls such as `copy`, `paste, and `select all` for notebooks

**Pull request merged**
