### PR TITLE
Ignore .git files for extension recommendations

### LINKED ISSUE #86427: Extension recommendation for .git files appearing when no .git file is opened
Issue Type: <b>Bug</b>

- Open any git repo in VS Code
- Open any file in the repo

I get the below prompt:

image

One would expect this prompt if a `.git` file was manually opened in the editor and no VS Code extension was installed that could serve .git files. But in my case, no such file was opened.

VS Code version: Code - Insiders 1.41.0-insider (bbf00d8ea6aa7e825ca3393364d746fe401d3299, 2019-12-05T06:56:28.532Z)
OS version: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #86427 for release

### CODE REVIEW

**Comment by Wowol** [comment]
Aren't we ignoring **all** `.git` files after that? So, even if I open a `.git` file, I won't see any recommendations from marketplace. This seems like a workaround, not fixing this issue, because in previous releases of vscode we didn't have this problem.

**Review by chrmarti — APPROVED** [review]

**Comment by joaomoreno** [comment]
@Wowol What file format are `.git` files? Do you know what format is that?

This now happens due to the adoption of the FileSystemProvider, maybe it triggers the recommendations code differently, but Git always appended `.git` to file names, since not doing so would trigger many other problems (.js files appearing in eslint, .ts files appearing in Typescript, all coming from Git). cc @sandy081

**Comment by Wowol** [comment]
My point is, that I think randomly hard-coding this **if** statement doesn't seem like a good idea to deal with this issue, even if it solve that. But, if you think this is a most correct way to do that, that's ok.

**Comment by sandy081** [comment]
@joaomoreno I do not know if users open `.git` files or not but I think this will break 

1. Showing file type base recommendations with `.git` extension (as @Wowol said)
2. Layering. Now we have extension knowledge in core. 

I understand that we want a safe and small fix, then why do not we do following

1. Check for the `scheme` instead - this will fix first issue.
2. To fix second issue - Follow up item fixing layering issue. For eg: We can have a registry or hardcoded list of supported schemes for triggering recommendations.

**Comment by chrmarti** [comment]
Closing without merging. @sandy081 will take over and do another PR.

**Comment by joaomoreno** [comment]
@sandy081 I like your review and proposal! 👍

**Pull request closed without merging**
