### PR TITLE
Fixes clicking on problems filter inputbox makes problems panel callapse

### LINKED ISSUE #96009: Split problems panel makes filter input unclickable
- VSCode Version: 1.45.0-insider
- OS Version: Windows 10, Build 18363.778

Steps to Reproduce:

1. Place the integrated terminal in a split panel with the problems view
2. Maximize the VS Code window
3. Press the filter input in the problems view

Does this issue occur when all extensions are disabled?: Yes

When the problems view is placed in a split panel and the VS Code window is sufficiently wide (e.g. maximized at 1080p), the filter input is placed on top of the collapsible title. Clicking the filter input instead clicks the title behind it, collapsing the problems view.
vscode_filter_bug

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #96009

### CODE REVIEW

**Comment by sandy081** [comment]
Seems the fix will fix the issue but trying to understand why the click on input box is triggering collapse button?

**Comment by jeanp413** [comment]
@sandy081  The event is bubbling up so :arrow_down: also gets triggered.
https://github.com/microsoft/vscode/blob/9f45c20088391edd55c0f94ec4deaf591ad5bcfa/src/vs/base/browser/ui/splitview/paneview.ts#L218-L223

**Comment by sandy081** [comment]
Ah I see. Thanks for explanation.

**Review by sandy081 — APPROVED** [review]
LGTM

**Pull request merged**
