### PR TITLE
Support MSYS/Cygwin absolute path notation

### PR DESCRIPTION
**Pull request by orgads**
For MSYS: /d/file is translated to D:\file
For Cygwin: /cygdrive/d/file is D:\file

### CODE REVIEW

**Comment by connor4312** [comment]
What problem does this solve?

**Comment by orgads** [comment]
When I compile with MSYS on the terminal, paths in warnings/errors are shown in MSYS/Cygwin style: `[/cygdrive]/d/Projects/test/foo.cpp:123`. Ctrl-clicking it opens the Quick open edit with the path, then I have to edit it, remove the leading slash, add a colon after the drive letter and press Enter.

This change should fix it to work out of the box.

**Comment by connor4312** [comment]
I think a change in the terminal link detection is likely better than changing core path behavior, which is quite risky.

**Comment by orgads** [comment]
I started with link detection, but I didn't find any similar use case that modifies the text. Shouldn't the text field there match the actual text for highlighting and such?

**Review by Tyriar — COMMENTED** [review]
I agree with @connor4312, changing core path code like this is extremely risky as it touches so many components. Making the terminal link code more aware of this path format is the right approach. Closing as the right fix would be a very different change, it's very welcome though 👍

**Comment by orgads** [comment]
Thank you. I'll try that and open a new PR.

**Comment by Tyriar** [comment]
@orgads awesome! Creating an issue detailing the problem would also be very helpful, we need this after fixing it in order to verify the fix anyway

**Comment by orgads** [comment]
Created an issue:
- #214615

**Pull request closed without merging**
