### PR TITLE
chore: update builds for electron@22.3.14

### PR DESCRIPTION
**Pull request by alexr00**

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]

**Comment by levrik** [comment]
It's cool that this PR is linked from the release notes but it's not very helpful without context 😅

**Comment by zhouxinghong** [comment]
Hello! Whether to consider updating `electron` to `electron` version 25+

**Comment by swarnava** [comment]
> Hello! Whether to consider updating `electron` to `electron` version 25+

https://github.com/microsoft/vscode/issues/184021

**Comment by jsphstls** [comment]
I am also curious about the context. `@playwright/test@1.36.1` was able to successfully launch the electron application of version `1.80.1` on a `darwin/arm64` runner, yet version `1.80.2` fails to launch.

**Comment by Mogga-hub** [comment]
> I am also curious about the context. `@playwright/test@1.36.1` was able to successfully launch the electron application of version `1.80.1` on a `darwin/arm64` runner, yet version `1.80.2` fails to launch.

**Comment by TECHSYS1999** [comment]
It's cool that this PR is linked from the release notes but it's not very helpful without context 😅

**Comment by swarnava** [comment]
It means they are already working on this and being tested on Insider bill,

To answer your question, yes they are considering upgrading to electron 25

**Review by Roberteclick555 — CHANGES_REQUESTED** [review]
- [ ]

**Comment by Thilksoe** [comment]
hello

**Comment by alexdima** [comment]
We had an embargo from the Electron team. For full transparency, this is what we shipped on Jul 27th -- https://github.com/microsoft/vscode/issues/192902

**Pull request merged**
