### PR TITLE
An option to copy only plain text to clipboard.

### PR DESCRIPTION
**Pull request by mshoho**
An option to copy only plain text to clipboard, without the rich text version.

### CODE REVIEW

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21071 and https://github.com/Microsoft/vscode/issues/21820 look this request (duplicates of each other?)

**Comment by Tyriar** [comment]
@rebornix maybe `"editor.copyWithFormatting": true` would be better as suggested in https://github.com/Microsoft/vscode/issues/21071#issuecomment-303750728 ?

**Comment by mshoho** [comment]
I can rename it, no problem. Just let me know.

**Comment by rsyring** [comment]
FWIW, in https://github.com/Microsoft/vscode/issues/21820 I'm arguing that the current behavior is a bug.  Copy should, by default, only copy text and copy with syntax highlighting should not be the default behavior (as there is already a separate command for this).  If that argument is accepted (big "if"  :) ), then this issue could be closed.

**Comment by mshoho** [comment]
@rsyring I know people who need the highlighted copy, I suppose this thing is still needed, perhaps the default value should be inverted.

**Comment by rebornix** [comment]
@mshoho thanks for your help, it looks great!

**Comment by rsyring** [comment]
@mshoho thanks for putting some time into resolving this issue!  :)

> @rsyring I know people who need the highlighted copy, I suppose this thing is still needed, perhaps the default value should be inverted.

Yes, I think we should keep the feature.

I'm only saying that the default copy should not copy syntax highlighting.  Let that be handled by the command that already exists.  I'm not 100% sure what this PR is doing, so can't comment on the work-in-progress.

**Pull request merged**
