### PR TITLE
Fix: Notifications and feedback should not be visible at the same time 

### LINKED ISSUE #101376: Notifications and feedback should not be visible at the same time
Testing #101334

* click on both status bar entries

Screenshot 2020-06-30 at 11 42 46

### PR DESCRIPTION
**Pull request by jppm99**
This PR fixes #101376

When opening either the notifications center or the tweet feedback item, the other one hides to avoid overlapping.
(last PR was closed because it was causing a error when there was no tweet feedback button)

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
The status bar part cannot have a dependency on the specific items. Rather I think we need a component that listens for some new event for when notifications center or feedback overlay is visible and then hides the other accordingly.

**Comment by jppm99** [comment]
> The status bar part cannot have a dependency on the specific items. Rather I think we need a component that listens for some new event for when notifications center or feedback overlay is visible and then hides the other accordingly.

I'm new to this repo, how would that look like in terms of code structure? Is there anything similar already implemented?

**Comment by bpasero** [comment]
Yes, for example for notifications:

https://github.com/microsoft/vscode/blob/0b65d0385f7d9474ec32e1bb149398db3331949b/src/vs/workbench/browser/workbench.ts#L378

**Comment by jppm99** [comment]
> Yes, for example for notifications:
> 
> https://github.com/microsoft/vscode/blob/0b65d0385f7d9474ec32e1bb149398db3331949b/src/vs/workbench/browser/workbench.ts#L378

So it would be pretty much extending that onDidChangeVisibility call and adding a new one for the feedback, right?
How could I access the feedback statusbar item instance from there? It doesn't seem to have a service associated with it in order to get it through the instantiation service nor is it created there like the notifications center is: `const notificationsCenter = this._register(instantiationService.createInstance(NotificationsCenter, this.container, notificationService.model));`

**Comment by bpasero** [comment]
Closing for now, sorry but I think this needs a bit more thinking and is not up for grab.

**Pull request closed without merging**
