### PR TITLE
Add SyncActionDescriptor.from helper

### PR DESCRIPTION
**Pull request by mjbvz**
There are a whole lot of places in our codebase where have the following pattern:

```js
actionRegistry.registerWorkbenchAction(
    SyncActionDescriptor.create(CreateNewLocalTerminalAction, CreateNewLocalTerminalAction.ID, CreateNewLocalTerminalAction.LABEL));
```

Notice how the class name (`CreateNewLocalTerminalAction`) has to be repeated  three times.

This change introduces a helper function `SyncActionDescriptor.from` that lets you instead just pass in the class:

```js
actionRegistry.registerWorkbenchAction(
    SyncActionDescriptor.create(CreateNewLocalTerminalAction));
```

### CODE REVIEW

**Comment by mjbvz** [comment]
This was just a regular expression find/replace:

```
SyncActionDescriptor.create\((\w+), \1\.ID, \1\.LABEL
```

```
SyncActionDescriptor.from($1
```

**Comment by Tyriar** [comment]
@mjbvz seems better, but `registerWorkbenchAction` is actually deprecated:

https://github.com/microsoft/vscode/blob/b442c251ac2aa35abd8288c329f4702a0d842955/src/vs/workbench/common/actions.ts#L22-L27

When I converted the terminal actions over to `Action2` I ran into problems though for any `IAction` that was used elsewhere in the terminal, like context menus and panel actions.

**Review by bpasero — APPROVED** [review]
LGTM. I think there are a few more places to look at:

image

**Review by Tyriar — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks. I'm a quick pass through the other calls to `create` in a separate PR since fixing these will involve rewriting the code

**Comment by joaomoreno** [comment]
Thanks for doing this @mjbvz

**Pull request merged**
