### PR TITLE
Checking chat providers exist before showing the action `Toggle Inline Chat Icon` in the context menu

### LINKED ISSUE #196776: Toggle Inline Chat Icon gutter item appears when inline chat isn't available
1. Open a repo in insiders.vscode.dev
2. Right click on the gutter 
3. :bug: Toggle Inline Chat Icon is present in the context menu

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/196776

### CODE REVIEW

**Comment by aeschli** [comment]
The problem is that when a provider gets added or removed later, that action is not showing or still showing
I suggest to do this inside `_onEnablementOrModelChanged`.
after `this._localToDispose.clear();`
```
if (this._editor.hasModel() && this._hasProvider()) {
   this._localToDispose.add(GutterActionsRegistry.registerGutterActionsGenerator(....
}
```

**Comment by aeschli** [comment]
At that location we also know the state of the setting, so we could use different labels
`this._isSettingEnabled() ? 'Hide Inline Chat Icon' : 'Show Inline Chat Icon'`

**Comment by aiday-mar** [comment]
Ah yes of course, my bad, I forgot about that aspect. I'll do that right away.

**Comment by aeschli** [comment]
Ah I see, then your fix is correct. Actually, my suggestion is bad as it would register `registerGutterActionsGenerator` for each editor.

**Review by aeschli — DISMISSED** [review]

**Review by aeschli — APPROVED** [review]

**Pull request merged**
