### PR TITLE
Allow to run web client out of sources

### PR DESCRIPTION
**Pull request by bpasero**
via `yarn web`

### CODE REVIEW

**Comment by LeuisKen** [comment]
Is this means that we can report web version's issue and send pull request ?

**Comment by bpasero** [comment]
@LeuisKen yes, but please be aware that we are currently only supporting Chromium browsers, simply because that is the environment we get from Electron. We will likely expand browser support in the future, but currently not.

**Comment by vegerot** [comment]
Without documentation, I'm not sure how to use this?  Running `yarn web` still opens `Sample-Folder`, and I don't know how to get outside of it

**Comment by bpasero** [comment]
`yarn web` is meant only for testing vscode in a browser, nothing else.

**Comment by vegerot** [comment]
Thanks for the response!
Is this to incentivize getting Azure subscriptions?  Not sure why `yarn web` would be so limited.  If `yarn web` is only meant for testing vscode in a browser, why not allow testing of other projects in there.  Seems like it could be done with existing `yarn web` functionality, and would be super useful to people.
Thanks again

**Comment by ThanrayTian** [comment]
@bpasero now `yarn web` is so limited. If it can connect to any remote machine, that's very great. Do you have such a plan? I am looking forward to that feature. (PS: visual studio online can do that, but not open source)

**Pull request merged**
