### PR TITLE
Make centerEditorLayout do not call layout

### LINKED ISSUE #76494: Outline view doesn't remember sizing between restarts
Steps to Reproduce:

1. Enable [centered layout mode](https://code.visualstudio.com/updates/v1_21#_centered-editor-layout)
2. Resize outline menu
3. Restart and outline menu will be near top of the page

Thanks

VSCode-Go: 0.11.0
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

### PR DESCRIPTION
**Pull request by jeanp413**
Not sure if this is the right fix but it seems to not break anything. Maybe need to call layout later?
Fixes #76494.

### CODE REVIEW

**Comment by sandy081** [comment]
@jeanp413 Do not understand how this fix is related and fixes this?
Did you investigate the root cause of this issue?

**Comment by sandy081** [comment]
Sorry, read the main issue and understood the root cause. But did you check when is the layout called when not in center editor layout mode?

**Comment by jeanp413** [comment]
Yes, do you mean this?
https://github.com/microsoft/vscode/blob/3889970797f38d826735e0e519594e87f385c164/src/vs/workbench/browser/workbench.ts#L143-L150

**Comment by sandy081** [comment]
Let's check with @isidorn if this change is ok or not.

**Comment by isidorn** [comment]
@jeanp413 thanks for your PR.
However the layout needs to be called then. The only time we can not call layout is if the layout is called afterwards.
Assigning to myself and next milestone so I can test this more.

**Comment by isidorn** [comment]
On startup the layout gets called by the workbench and yes in that case it is ok that the centered editor layout does not call layout.
Since this fixes the issue it is fine to merge this PR.
@jeanp413 thanks for the PR and the fix.

**Pull request merged**
