### PR TITLE
disable scm gutter

### LINKED ISSUE #21795: Allow control over quick diff decorations
if i am not wrong there is no way to disable SCM (git) in the gutter. I really would like to disable it.
I want my gutter to be clean and almost only see problems in there.

Thanks

### PR DESCRIPTION
**Pull request by jens1o**
resolves #21795 

Thanks to @FabianLauer to support me while I couldn't test it out myself.

### CODE REVIEW

**Comment by jens1o** [comment]
@joaomoreno Did you have a chance to take a look?

**Comment by joaomoreno** [comment]
@jens1o Issues with the current approach:

- The setting seems to disable both gutter and overview ruler decorations. The user in #21795 seems to only be annoyed with the sidebar ones. I can actually see usefulness in allowing full control over both. I suggest having two settings to control each set of decorations: `editor.scm.gutterDecorations` and `editor.scm.overviewRuler`, both defaulting to `true`.
- When disabling the decorations altogether, the `DirtyDiffDecorator` shouldn't even ask to compute them. The current approach still computes them yet displays them as invisible.
- The open editors don't update when the setting changes: one needs to close the editor and reopen it in order to see the change. The change needs to be live.

I'll leave this PR open in case you want to commit on top of the current commits. But feel free to start over.

**Comment by jens1o** [comment]
Okay, thanks for the feedback. I'll check that as soon as I got some more time. :)

**Comment by jens1o** [comment]
Okay, I think somebody else must handle that, because I feel like I'm not that deep inside the codebase. :/

**Comment by joaomoreno** [comment]
Alright, thanks for the attempt, closing the PR.

**Pull request closed without merging**
