### PR TITLE
fix: place regex in variables on `shellIntegration-bash.sh` script

### LINKED ISSUE #212139: syntax error on sellIntegration-bash.sh
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: windows 10 x64
- Terminal: MSYS 1.0 i686 [GNU bash, version 3.1.23(1)-release]

Since last update, every time i open the vscode i get this error in the terminal:
```
bash: c:\Users\kapodamy\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh: line 138: syntax error in conditional expression: unexpected token `|'
bash: c:\Users\kapodamy\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh: line 138: syntax error near `|M'
bash: c:\Users\kapodamy\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh: line 138: `if [[ "$(uname -s)" =~ ^CYGWIN*|MINGW*|MSYS* ]]; then'
```
looks like the conditionals in the following regex should be escaped:
```bash
# Send the IsWindows property if the environment looks like Windows
if [[ "$(uname -s)" =~ ^CYGWIN*|MINGW*|MSYS* ]]; then
	builtin printf '\e]633;P;IsWindows=True\a'
	__vsc_is_windows=1
else
	__vsc_is_windows=0
fi
```
```bash
if [[ "$HISTCONTROL" =~ .*(erasedups|ignoreboth|ignoredups).* ]]; then
```

Steps to Reproduce:

1. open vscode, integrated terminal is opened automatically

### PR DESCRIPTION
**Pull request by kapodamy**
Place regular expressions in variables before use, fixes #212139 and allow the script run in older shells.

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Is this really how it works and is it compatible with the older versions or does this condition just never pass then? When I run this in my msys terminal it fails:

image

**Comment by kapodamy** [comment]
should be working now, tested on:
`GNU bash, version 3.1.23(1)-release (i686-pc-msys) [MINGW32_??-10.0]` oldest
and
`GNU bash, version 5.2.26(1)-release (x86_64-pc-msys) [MINGW64_NT-10.0-19045]` lastest

**Review by Tyriar — DISMISSED** [review]
Nice, thanks!

**Review by sbatten — DISMISSED** [review]

**Comment by Tyriar** [comment]
Seems to be failing the tests which likely mean there's a regression on Linux ☹️

**Review by Tyriar — APPROVED** [review]
Thanks!

**Review by roblourens — APPROVED** [review]

**Pull request merged**
