### PR TITLE
Scroll-y menus

### LINKED ISSUE #52533: Context menus do not overflow
Custom context menus will clip at window edges instead of overflowing.
cant overflow

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.16299

### PR DESCRIPTION
**Pull request by sbatten**
When a menu is created, set a max height and use scrollable element. There is room for improvement but this only takes a visible effect when needed and in that case, it is certainly better than the current situation.

Not having used the scrollableelement  class before and due the strange behavior of overflow with regards to submenus, please review carefully.

fixes #52533

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]
Actually seems to work quite well.

**Comment by bpasero** [comment]
@sbatten please bring up to date with master

**Comment by joaomoreno** [comment]
@bpasero You can test this by running:

```
git fetch origin pull/62819/head:pr/62819 && git co pr/62819
```

**Comment by bpasero** [comment]
Yeah possibly, but I prefer to apply the changes on top of master. And besides, there is a merge conflict too.

**Comment by sbatten** [comment]
@bpasero  updated and conflicts resolved

**Review by bpasero — APPROVED** [review]
@sbatten yeah works nicely, some feedback:
* looks like the onscroll emitter is never disposed
* the scrollbar is a bit hard to see in high contrast themes (see below)
* the scrollbar should probably always be visible even when the mouse is not over the menu for accessibility reasons (see how quick open always shows a scrollbar)
* the scrollbar does not update its position when I navigate using the keyboard

image

**Pull request merged**
