### PR TITLE
Add showDeprecated option to suggest, filters out deprecated options

### LINKED ISSUE #77239: Option to prevent deprecated things from showing up in intellisense suggestions
I'd like a setting to optionally prevent deprecated things from showing up in intellisense suggestions.

For example, I'd like a way to prevent `assert.equal` from being suggested here, so that I don't use it despite a non-deprecated version being available. 

image

My linter can catch it, but it'd be even nicer never to see the deprecated option.

There are several documentation systems that use the `@deprecated` tag:
- JSDoc: https://jsdoc.app/tags-deprecated.html
- TSDoc: https://github.com/microsoft/tsdoc/blob/c5279394fa17bd6aa20ae711563b7923d44f822d/tsdoc/src/details/StandardTags.ts#L54-L58
- JavaDoc: https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html#javadoc_tag
- Yard (for Ruby): https://www.rubydoc.info/gems/yard/file/docs/Tags.md#deprecated

Other systems use different, similar tags.

I'm not sure if this is an issue for the VSCode core, or for something language-specific.

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Adds an option to `showDeprecated` in the suggest list.  When false, deprecated items are not shown.  Defaults to true, same as old behavior.

Changes were mostly done by following the `showConstructors` option.

Example
recording

This PR fixes #77239.

### CODE REVIEW

**Comment by nrayburn-tech** [comment]
I wasn't sure if `suggestOptions.showDeprecated` should be added here or not.
https://github.com/microsoft/vscode/blob/b55b12fac631a076860fc6fd9e562f5ae8734130/src/vs/editor/contrib/suggest/suggestModel.ts#L520

`Deprecated` also isn't in `CompletionItemKind`, and would have to be added.  Also wasn't sure about that.

**Comment by jrieken** [comment]
> I wasn't sure if suggestOptions.showDeprecated should be added here or not.

That would be the better place because filtering for deprecated needs to happen only once (not repeatedly as the user types). Tho, I would not add this as `CompletionItemKind` but as separate option to `CompletionOptions`.

**Comment by nrayburn-tech** [comment]
@jrieken I believe the new changes are what you are asking for.

**Review by jrieken — APPROVED** [review]
Looking good

**Pull request merged**
