### PR TITLE
Change mouse down back to focusing elements

### LINKED ISSUE #69437: New explorer: clicking on a file first shows blue focus outline
I feel like this is different behavior from before:
* close all editors
* click on a file in the explorer

=> :bug: first you see the focus outline in the tree and then the element is selected
=> I do not recall ever seeing the focus outline before when just clicking into an item

Not sure if this is a general tree/list issue or specific to the explorer.

//cc @joaomoreno

### PR DESCRIPTION
**Pull request by joaomoreno**
fixes #69437

### CODE REVIEW

**Comment by bpasero** [comment]
@joaomoreno this seems to work fine. Now I see the element show in light blue and then dark blue on mouse up:

before

If I had to choose, I still prefer the behaviour as it is now before this change because the blue outline only shows up when all editors are closed and I click on a file to open it. It does not seem to reproduce when just clicking around.

**Comment by joaomoreno** [comment]
> the blue outline only shows up when all editors are closed

It shows when the list/tree has no focused elements.

> Now I see the element show in light blue and then dark blue on mouse up:

Today, both focus and selection are set on mouse up. So, the only thing which happens on mouse down is the native browser DOM focus, that's why the border appears on mouse down. This PR brings back the old behavior of focusing the element on mouse down and selecting it on mouse up.

Another alternative solution is to add a special `outline: none` rule to `active`, `focused`, `without-focus-elements` lists/trees, which I'm not too excited about.

**Comment by bpasero** [comment]
@joaomoreno interesting, somehow I thought this was introduced by switching to the new tree, but now I see this already in `1.30.2`. So this was behaving exactly the same in older versions right?

**Comment by joaomoreno** [comment]
Yeah. Though we've been iterating on the behavior of mouse up/down wrt element focus throughout the months. It seems we can't settle on a single one.

**Comment by foxjazz** [comment]
when switching to the branch, having compile errors.
switched from master

**Comment by joaomoreno** [comment]
Let's close this and roll with the current setup for a while.

**Pull request closed without merging**
