### PR TITLE
Finalize NotebookEditor api proposal

### LINKED ISSUE #149271: Finalize notebookEditor API proposal
Splitting off from https://github.com/microsoft/vscode/issues/125758

The notebookEditor API proposal looks to be in good shape. We may revise a few names or functions, but otherwise I think it is ready for testing and finalization

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #149271

This finalizes most parts of the NotebookEditor api proposal. I haven't removed the proposal entirely as there are still a few parts being left behind:

- The deprecated properties/functions
- A few contribution points such as `notebook/cell/executePrimary`

### CODE REVIEW

**Comment by mjbvz** [comment]
@rebornix and @jrieken I just realized that the `notebookEditor` proposal is also used to gate the following menu contributions: 

- `notebook/cell/executePrimary`
- `interactive/toolbar`
- `interactive/cell/title`


Let me know if these can also be finalized or should be split into a new proposal

**Comment by jrieken** [comment]
`notebook/cell/executePrimary` sounds a bit exotic. May this should be `notebook/cell/execute` with a special group (of length 1) which is rendered prominent. /cc @roblourens for background

**Comment by jrieken** [comment]
Also `debug/toolBar` vs `notebook/toolbar` vs `interactive/toolbar` (only the latter isn't finalized)

**Comment by roblourens** [comment]
That executePrimary menu is only needed for remotehub's "Continue Working On" prompt and it will go away when that moves to core. https://github.com/microsoft/vscode/issues/149271#issuecomment-1124010213 I think that menu shouldn't be finalized. Sorry for not calling that out.

**Comment by mjbvz** [comment]
I've confirmed that `interactive/cell/title` and `interactive/toolbar` are being used by the Jupyter extension: https://github.com/microsoft/vscode-jupyter/blob/584e7e126dc1d218909e8277a6e2bb3d65315892/package.json#L1009

Not sure if there are any other users. @roblourens Do you think we can safely finalize these two contributions? Or do they need to remain proposed

**Review by rebornix — APPROVED** [review]

**Comment by rebornix** [comment]
@mjbvz I think both `interactive/cell/title` and `interactive/toolbar` are stable and good for finalization. They are similar to `notebook/cell/title` and `notebook/toolbar` and they are used uniquely in Interactive Window.

**Pull request merged**
