### PR TITLE
Adds "verified domain" identifier to url tooltip

### LINKED ISSUE #196876: [Accessibility] `Verified domain` in Extension page doesn't have a clear `title` attribute
Currently, the `Verified domain: http://example.com` only show as `http://example.com`, which make it hard for screen readers to understand its meaning.
screenshot of the text of `verified domain`
In contrast, other icons and texts are well-labelled and easy to understand.
screenshot of the text of `rating`

It would be nice to give `Verified domain` a proper accessibility attribute.

### PR DESCRIPTION
**Pull request by amaust**
closes #196876

Adds "Verified Domain" to the hover tooltip of Verified domain extension's marketplace pages.

### CODE REVIEW

**Comment by amaust** [comment]
@meganrogge Downloading the extension from the file doesn't bring over the "Verified" status. So I will need you to test this for me.

**Comment by meganrogge** [comment]
thanks for working on this. In oss, I'm seeing it work when I `shift+tab` to the element, but not when I `tab` to it 🤔 . Pretty strange.

https://github.com/microsoft/vscode/assets/29464607/e549bb62-592b-4764-a176-1d2d08f4e9d1

**Comment by amaust** [comment]
Interesting. Do you have any suggestions? I'm not sure if my fix changed the Aria label?

**Comment by meganrogge** [comment]
I'll need to investigate more tomorrow. I'm not sure why it would work when focusing it in the backward tab order and not the forward. I haven't seen anything like that before.

**Comment by amaust** [comment]
Sounds good.

**Comment by meganrogge** [comment]
@sandy081 do you know why this would only work in one direction? could you pls test and see if you experience the same?

**Comment by sandy081** [comment]
This is because when focusing using tab first element to be focused is the container (name + verified publisher) whereas in the other direction verified publisher is being focused first.

**Comment by meganrogge** [comment]
@amaust given that, do you want to add this to the container's aria label too?

**Comment by amaust** [comment]
Yep, sounds good

**Comment by amaust** [comment]
Should be good to go now @meganrogge.

**Comment by meganrogge** [comment]
with your change, the verified domain will be indicated when the link is focused. I think that's what we want 👍🏼. We don't need to apply this to the container.

**Review by meganrogge — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
