### PR TITLE
SCM history: Show details on hover (fix #200378)

### LINKED ISSUE #200378: SCM incoming/outgoing changes show full commit message on hover
When hovering over a commit in the SCM incoming/outgoing changes view I should get a tooltip showing the full commit message. Currently if I want to view full commit messages I need to resize the sidebar so they aren't cut off.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #200378

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
image

**Comment by lszomoru** [comment]
@gjsjohnmurray, thank you very much for the pull request. I was thinking that for each incoming/outgoing entry we would want to show a rich hover similar to the timeline entry. If you do not have bandwidth to update the PR, I am happy to take it from here.

**Comment by gjsjohnmurray** [comment]
I have pushed a change to make this display a Markdown-capable tooltip. I think the proposed API will probably need a `tooltip? : MarkdownString` property adding to `SourceControlHistoryItem` and wiring through to `ISCMHistoryItem` so the  Git extension can pass a Git-appropriate tooltip.

**Comment by gjsjohnmurray** [comment]
I have added vscode.SourceControlHistoryItem.tooltip to the proposed API and used it from the Git extension.

**Comment by gjsjohnmurray** [comment]
image

**Comment by gjsjohnmurray** [comment]
Please can this be reviewed (and merged 🤞) soon. I really like the new incoming/outgoing feature but it's tedious to have to widen my side bar to see the full commit messages and the authors.

**Comment by gjsjohnmurray** [comment]
@lszomoru any chance this can be merged in time for February?

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this until now. The "Timeline" proposed API is "UI driven" so it makes sense for it to have a property with which the extension describes how the hover should look. "The History Provider" API is model driven so I do not think that we should be making any changes to the existing API. We should just use the existing information (author, message, etc) to render a rich hover.

**Comment by gjsjohnmurray** [comment]
@lszomoru I think a history item "rich" hover will be impoverished if all it does is display untruncated the label and description properties of the item (which is what my original commit did, using a native tooltip). Please help me understand why you oppose allowing the extension that provides the item to also provide a markdown tooltip conveying whatever additional information the extension deems relevant.

**Comment by gjsjohnmurray** [comment]
@lszomoru can I do anything to progress this?

**Comment by gjsjohnmurray** [comment]
@lszomoru I guess this has been made obsolete by your #209373

**Comment by lszomoru** [comment]
Closing in favour of https://github.com/microsoft/vscode/pull/209373.

**Pull request closed without merging**
