### PR TITLE
chore: update to electron 18

### LINKED ISSUE #108509: VSCode segmentation fault on CentOS8 non-4k pagesize aarch64(arm64)
- VSCode Version: September 2020 (version 1.50)
- OS Version: CentOS 8.2 aarch64 pagesize 64k

Steps to Reproduce:

```
download code-stable-arm64-1602050866.tar.gz
tar zxvf code-stable-arm64-1602050866.tar.gz
cd VSCode-linux-arm64
./code 
segmentation fault
```

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #144962: Insiders VSCode on Node 16.10 breaks pipeline streams
Issue Type: <b>Bug</b>

My Pester Tests extension uses this API. The latest insiders which switched to NodeJS 16.x broke my extension. Here is the relevant issue that is fixed in later versions, if possible to bump vscode to a newer vscode 16.x version
https://github.com/nodejs/node/issues/40191

// Workaround https://github.com/nodejs/node/issues/40191
// todo: remove it when fix is released in 16.x and in AppEngine 16.x
if (process.version > 'v16.13') {
  const { pipeline } = require('stream/promises')
  _pipeline = ((streams: AnyStream[]) => pipeline(...streams)) as any
}

VS Code version: Code - Insiders 1.66.0-insider (6b7453421201c888b81eae5c04ec822a6423608f, 2022-03-11T05:17:19.559Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (2.59GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-opennewinstance|chr|0.0.12
esbuild-problem-matchers|con|0.0.2
vscode-github-actions|csc|0.22.0
vscode-eslint|dba|2.2.2
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|12.0.4
filter-lines|ear|1.0.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
lintlens|ghm|3.0.2
copilot-nightly|Git|1.7.5297
remotehub|Git|0.26.0
vscode-pull-request-github|Git|0.38.1
todo-tree|Gru|0.0.215
vscode-drawio|hed|1.6.4
change-case|hjd|1.0.2
vscode-peacock|joh|4.0.0
git-graph|mhu|1.30.0
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.77.2022031115
remote-ssh-edit|ms-|0.77.2022031115
js-debug-nightly|ms-|2022.3.717
powershell-preview|ms-|2022.3.0
indent-rainbow|ode|8.2.2
docthis|oou|0.8.2
vscode-jest|Ort|4.2.1
pester-test|psp|2022.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
vscode-sort-json|ric|1.20.0
vscode-inline-values-powershell|Tyl|0.0.5
errorlens|use|3.4.2
vscode-icons|vsc|11.10.0
codetour|vsl|0.0.58
gitmoji-vscode|Vtr|1.0.9
better-align|wwm|1.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vscscmwlcmt:30428973
vscgsvid2:30433758
dockersurvey3:30438168
pynewfile477:30451556

```

</details>

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/144962
Refs https://github.com/microsoft/vscode/issues/146584
Fixes https://github.com/microsoft/vscode/issues/108509

### CODE REVIEW

**Comment by VitalyAnkh** [comment]
[Electron 18.0.1](https://github.com/electron/electron/releases/tag/v18.0.1) has been released, so this PR could use electron 18.0.1 instead.

**Comment by deepak1556** [comment]
It will be updated when corresponding internal builds are available.

**Comment by fisforfaheem** [comment]
Electron 18.2.0 is stable enough

**Comment by mkurz** [comment]
Please bump to electron 19.0.1 straight. Electron 19 switched to [Chromium 102](https://github.com/electron/electron/releases/tag/v19.0.0) which contains an important fix to make it run on Linux on Apples M1 chips, see: https://github.com/AsahiLinux/docs/wiki/Broken-Software
Would be awesome if you could make that happen, thank you!

**Comment by deepak1556** [comment]
@mkurz can you point to the upstream bug that addresses the issue ? We can try backporting the fix to Electron 18 if it is possible.

Just to give some context on Electron version adoption for VSCode, we currently follow an 8 week stabilization cycle, the first 4 weeks we have our nightly exploration builds that is largely self-hosted by our team and then we have an endgame testing using these builds. Once we are confident with exploration builds the update would then be pushed to insiders in the following iteration for wider testing from the VSCode community and it may or may not be pushed to stable depending on the data we acquire from insiders testing. Since we have already spent time stabilizing Electron 18 for exploration builds this iteration, a jump to Electron 19 at this point would only delay the next update adoption. On the other hand, once Electron 18 is promoted to insiders we can actively look into adopting Electron 19 for exploration builds.

**Comment by mkurz** [comment]
> can you point to the upstream bug that addresses the issue ? We can try backporting the fix to Electron 18 if it is possible.

https://bugs.chromium.org/p/chromium/issues/detail?id=1301788
Thanks! If not possible to backport it's still ok to just wait, at least it will arive at some point (other projects seem to be stuck with old electron versions and never update...)

**Comment by deepak1556** [comment]
Change has been backported at https://github.com/electron/electron/pull/34385

**Comment by mkurz** [comment]
Thanks @deepak1556!

**Review by bpasero — DISMISSED** [review]
👏

**Review by bpasero — APPROVED** [review]

**Pull request merged**
