### PR TITLE
fixes #43565

### LINKED ISSUE #43565: Adding backslash to new folder/item name when renaming breaks markdown on warning message
### Issue Type
Bug

### Description

1. Create a folder
2. Enter anything and put \ at the end
3. You should notice that warning text is entirely bolded now due to markdown bold tags being escaped.
image

and this is how it normally looks 
image

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|3.87GB (0.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
project-manager|ale|0.24.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
gitlens|eam|8.0.0
vscode-npm-script|eg2|0.3.3
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.0
Angular1|joh|0.2.0
vscode-colorize|kam|0.6.16
gitignore|mic|1.0.1
prettify-json|moh|0.0.3
vscode-versionlens|pfl|0.19.1
sass-indented|rob|1.4.6
code-settings-sync|Sha|2.8.7
vscode-wakatime|Wak|1.1.22
vscode-todo-highlight|way|0.5.11
vscode-jumpy|wma|0.3.1

(2 theme extensions excluded)

</details>
Reproduces without extensions

### PR DESCRIPTION
**Pull request by tsalinger**

### CODE REVIEW

**Comment by isidorn** [comment]
@tsalinger even without these changes the issue seems to be fixed. Do you see the same behavior?
If not please let me know for what input the text gets broken in the current insiders version and it works nicely with this fix

**Comment by tsalinger** [comment]
@isidorn Problem still persists in current insiders version.
Steps to reproduce:

- New folder
- use 'a\\' or even better '%already_existing_dir%\\' (don't forget the backslash)

Result: In the validation message, the text after the path is bold cause the backslash escapes the markdown.

**Comment by isidorn** [comment]
@tsalinger I can not reproduce it both on os x and win with the exact input. Both those inputs get accepted for me, and there is no text after the path. Can you post a picutre or ping me once you are in the office so I check what you are seeing.

**Comment by isidorn** [comment]
@tsalinger great work and this works nice. The only issue is that the PR now has merge conflicts with the master branch. Can you please resolve those and once you do that I will merge it in. Thanks!

**Comment by isidorn** [comment]
@tsalinger thanks for merging conflicts. I have merged this PR, nice work!

**Pull request merged**
