### PR TITLE
fix #37570 add RELATIVE_FILEPATH snippet variable

### LINKED ISSUE #37570: Add relative directory/filepath support to snippets
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.3.9600

Currently, snippets allow you to resolve the current directory or filepath with `TM_DIRECTORY` and `TM_FILEPATH` respectively. It would be great to be able to get the path for these relative to the root folder, whether directly (e.g. `TM_DIRECTORY_REL`) or by providing a variable with the root folder.

I'm trying to write a snippet to create a new C# file. Visual Studio will auto-populate the file with `namespace Directory.Structure.Here`, but that doesn't seem possible in Visual Studio Code right now.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #37570 by adding a new snippet variable `RELATIVE_FILEPATH`

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@jrieken I attempted to add tests for the new variable into snippetVariables.test.ts but the following imports that I needed were flagged as import violations and prevented the push.

```
import { LabelService } from 'vs/workbench/services/label/common/labelService';
import { TestEnvironmentService, TestPathService } from 'vs/workbench/test/browser/workbenchTestServices';
import { TestContextService } from 'vs/workbench/test/common/workbenchTestServices';
```

I don't know the right way to solve this.

**Comment by gjsjohnmurray** [comment]
I resolved this by adding `// eslint-disable-next-line code-import-patterns` ahead of each of those lines. Don't know if this is permitted in unit tests, but at least it let me push the new tests for review.

**Comment by jrieken** [comment]
> Don't know if this is permitted in unit tests, but at least it let me push the new tests for review.

No, this isn't permitted. To mock services, I would use the [mock](https://github.com/microsoft/vscode/blob/7c045e7f0786932f9840ef9a806ae4e04945601f/src/vs/base/test/common/mock.ts#L10-L10) util. This is an sample of how it is used: https://github.com/microsoft/vscode/blob/bdb0ef4d48978773cb1173a6141985d337324274/src/vs/editor/contrib/snippet/test/snippetVariables.test.ts#L21

With `mock` you should be quick to make the compiler happy and be required to implement the minimun of the service that your test needs

**Comment by gjsjohnmurray** [comment]
My concern about providing a mock label service is that I'll naturally make the mock service do what I reckon is the right thing when the RELATIVE_PATH code calls it with options `{ relative: true, noPrefix: true }`, but the value of the test will be diminished because it's not calling the real method in src/vs/workbench/services/label/common/labelService.ts. So if the real method ever gets changed in a way that adversely affects the call from RELATIVE_PATH resolution, the unit test won't detect this.

**Comment by jrieken** [comment]
Well, you aren't writing a test for how a certain label service works but for a snippet variable that should use some instance of that service

**Review by jrieken — APPROVED** [review]

**Pull request merged**
