### PR TITLE
add notification `AccessibleView`, `next/previous` functions

### LINKED ISSUE #184612: add a way to view next/previous content in `AccessibleView`
this would be useful in notebook output cells for example so that the user doesn't have to press `f2`, `escape`, `ctrl+down` then `f2` again 

cc @amunger

### LINKED ISSUE #187114: [Accessibility] Make Alt+F2 work in notification area
Type: <b>Feature Request</b>

When focused in the notification area and moving up and down each notification item in the list view, it would be so instrumental if Alt+F2 can augment the content in the accessible Monaco view.

VS Code version: Code - Insiders 1.80.0-insider (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T10:57:02.727Z)
OS version: Windows_NT x64 10.0.22621
Modes:

### PR DESCRIPTION
**Pull request by meganrogge**
fixes https://github.com/microsoft/vscode/issues/187114
fixes #184612

### CODE REVIEW

**Comment by meganrogge** [comment]
EDIT: I've decided to remove that part for now - so only one notification will be focused at a time in the accessible view and iteration won't be possible from within that.

**Comment by meganrogge** [comment]
note that if possible, we will want to use the generic way instead of using the key handler

exploration here is proving that won't be possible for the notifications case because we need to keep track of the current index and it otherwise always returns `0` so it doesn't go to next/previous
https://github.com/microsoft/vscode/commit/27c694444d304e09f5279dea44c8b07248ef2d0c

**Comment by daviddossett** [comment]
cc @hbons

**Review by DonJayamanne — APPROVED** [review]

**Comment by bpasero** [comment]
Should I be looking at a change here?

**Comment by meganrogge** [comment]
Sure, your review would be good @bpasero

**Pull request merged**
