### PR TITLE
Add support for prune on git fetch

### LINKED ISSUE #59693: Git: Support fetch prune
Issue Type: <b>Feature Request</b>

Currently if a remote branch is deleted by others, the only way to have Code know about it is to manually run `git fetch -p` in the terminal and then the `Git: Fetch` command in Code.

We should at least have an option, if not default, to add `-p` on `Git: Fetch` or `Git: Sync`.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

### PR DESCRIPTION
**Pull request by steevsachs**
* As configuration option to prune on all fetch operations
* As fetchPrune command
Closes #59693

### CODE REVIEW

**Comment by oneslash** [comment]
Hi there is already one PR for this https://github.com/Microsoft/vscode/pull/59735

**Comment by steevsachs** [comment]
Apologies for missing that. 

This PR also adds support for a configuration to always prune on fetch. Might be worth supporting both options.

**Comment by steevsachs** [comment]
Closing in favor of https://github.com/Microsoft/vscode/pull/59735

Will reopen if necessary with only config-related changes once that is merged.

**Comment by steevsachs** [comment]
Reopening this because there hasn't been any activity on https://github.com/Microsoft/vscode/pull/59735 for 3 weeks and it's not currently passing build.

**Comment by oneslash** [comment]
since #59735 is already merged, you may close the PR

cc: @joaomoreno

**Comment by joaomoreno** [comment]
@steevsachs Sorry for the silence, missed then when looking into the other one. I wonder... is the config something you'd require on your day to day?

**Comment by steevsachs** [comment]
No problem, @joaomoreno! For me the config created parity with Webstorm, which by default prunes on fetch. 

Doesn’t seem like it’d be a deal breaker for anybody, but would make pruning a little more passive for those that want it.

**Pull request closed without merging**
