### PR TITLE
Adopt error no telemetry for filesystem providers.

### PR DESCRIPTION
**Pull request by lramos15**
This PR is part of #148831.

`ENOPRO` is probably the most common file system error we currently get still in the errors site. Let's try throwing error no telemetry and reduce the amount of data which gets in our pipeline if this is inactionable.

### CODE REVIEW

**Comment by bpasero** [comment]
LGTM, adding Jo because this seems to change behaviour for extensions. I doubt this causes any issues but just making sure.

**Review by bpasero — APPROVED** [review]

**Comment by lramos15** [comment]
I'll wait for him then. My guess is it doesn't because it will still pass an instanceof check for Error

**Review by jrieken — APPROVED** [review]
Looks good to me. Tho, I do think a special `NoTelemetry`-[symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) would be a better way than subclassing to code this

**Comment by lramos15** [comment]
@jrieken Not too familiar with Symbols would instanceof on Error still work and you be able to use it as if it was any other error. The reason we use a subclass is so that we can do `instanceof ErrorNoTelemetry` but all other error code can remain untouched

**Comment by jrieken** [comment]
Using a symbol would combine the flexibility of `ErrorNoTelemetry#logTelemetry` with the uniqueness of instanceof-checks. Checking for a symbol-property guarantees uniquness, e.g there is no false positives because a random object happens to define `logTelemetry`. All without the cumbersome inheritance chains, like what does `FileOperationError extends ErrorNoTelemetry` mean in the pure world of OOP? What is a non-report error also wants to inherit from a "true" parent type.

The JS world is going down the symbols world, e.g. you don't extend from an iterable-type but you declare avialability of the iteration-protocol via the well-know [`Symbol.iterator`-symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)

**Pull request merged**
