### PR TITLE
Fix Jade syntax highlighting issues

### PR DESCRIPTION
**Pull request by huangenyan**
As mentioned in https://github.com/Microsoft/vscode/issues/4287, Jade has some syntax highlighting problems in comments. This PR fixes that issues, as well as another issue found when "else" occurs. This issue was previously moved https://github.com/davidrios/jade-tmbundle/issues/74 but was closed because it only appears in VSC. So let's fix it ourselves.

Before:
screen shot 2016-05-20 at 1 05 56 pm

After:
screen shot 2016-05-20 at 1 06 16 pm

### CODE REVIEW

**Comment by aeschli** [comment]
Hi @huangenyan As much as I'd like to fix our syntax highlighting, I'm hesitating to branch off David's grammar at davidrios/jade-tmbundle.
I think think we need to find out why our textmate grammar engine doesn't work the same way as in Sublime. @alexandrudima Alex, FYI

**Comment by rebornix** [comment]
Just share some findings which we found when moving Markdown stuff to a separate extension: we are implementing textmate tmlanguage parser ourselves in vscode-textmate, but it lacks support for some keywords, eg `while`. I don't mean the missing of keywords lead to this bug, but likely we don't have the same coverage as textmate or sublime does.

Maybe adding textmate/sublime tmlanguage parser test suite to `vscode-textmate` too see how much we are behind.

**Comment by JamesHenry** [comment]
@aeschli has there been any progress on investigating the disparity?

Selfishly, I would love to see this fixed as I work with jade templates every day, and this is the only thing I can think of in VSCode that isn't working brilliantly for me...

**Comment by alexandrudima** [comment]
@aeschli Would fixing vscode-textmate/issues#17 fix the underlying problem here? -- you also mention Jade there.

**Comment by aeschli** [comment]
@alexandrudima Yes, Microsoft/vscode-textmate#17 is the underlying issue.

**Comment by alexandrudima** [comment]
@aeschli fyi 

Fixed Microsoft/vscode-textmate#17 and adopted via 7533f1e141f561776175043c7be6431fc25c0e1d

**Pull request closed without merging**
