### PR TITLE
Web: change `yarn web` to run with our server instead of playground

### PR DESCRIPTION
**Pull request by bpasero**
This removes your playground `yarn web` runner in favour of opening web UI via our server

### CODE REVIEW

**Comment by bpasero** [comment]
One argument from @alexdima in standup today was that this change means we loose the ability to test our bits in a "serverless" environment. 

Some ideas and questions:
* make our server also support a "serverless" mode so that we avoid having 2 different servers
* do we need 2 `yarn web` commands for "serverless" and "serverful"

**Review by Aditya664 — APPROVED** [review]

**Comment by aeschli** [comment]
@bpasero I pushed my changes to use `@vscode/test-web` to run the serverless web from sources.

I clean up the commands and names:
There are now
- `./scripts/code-server-web` for running the code-server and opening a browser on it
- `/scripts/code-web` for running VSCode in the Web (serverless)

I removed `yarn web` in favor of the other scripts

The Web UI of the code-server-web still doesn't come up (page stays white). I'll have a look.

**Comment by bpasero** [comment]
@aeschli I like it!

Running `yarn web` on macOS I get this now:

```
~/Development/Microsoft/monaco> yarn web
yarn run v1.22.17
$ echo \'yarn web\' is replaced by `./scripts/code-server-web` or `./scripts/code-web`
/bin/sh: ./scripts/code-server-web: No such file or directory
/bin/sh: ./scripts/code-web: No such file or directory
'yarn web' is replaced by or
✨  Done in 0.04s.
~/Development/Microsoft/monaco>
```

**Comment by bpasero** [comment]
Also it seems to open a Chrome instance that is not my installed Chrome, are you shipping Playwright?

**Comment by bpasero** [comment]
I pushed a fix for `yarn web` not working.

**Comment by aeschli** [comment]
Yes, the @vscode/test-web extension uses Playwright.
Would you prefer not to open a Playwright browser but your system one?

**Comment by bpasero** [comment]
@aeschli yes!

**Review by aeschli — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
