### PR TITLE
fix: git has two same title in status bar

### LINKED ISSUE #152477: Source control status bar items do not differentiate themselves when right clicked
image

Version: 1.69.0-insider (user setup)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:33.731Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #152477
Screen Shot 2022-06-19 at 1 13 27 PM

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Please paste a screenshot of the updated menu.

**Comment by susiwen8** [comment]
> Please paste a screenshot of the updated menu.

Sure, I have add in PR description

**Comment by lszomoru** [comment]
@susiwen8, thank you very much for your contribution. The approach implemented in this pull request is not ideal as it uses the tooltip of the status bar command. The problem with that is that the tooltip can change as commands are being executed which would mean that the status bar item would re-appear when the tooltip changes. I will close this pull request for now, and I will try to see if I can "group" the two status bar items similarly to the language status indicator.

**Comment by Dopeman31** [comment]
Fix

**Pull request closed without merging**
