### PR TITLE
Fix custom select box hover styles

### LINKED ISSUE #130038: Custom select box hover style issues
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2, also tested `main` (ca273fcd); Pretty sure it affects earlier versions as well
- OS Version: Linux x64; Windows should be affected as well (not macOS because it uses the native select box)

Steps to Reproduce:

1. Use a theme (or set custom colors) where focus and hover styles don't match. Example (used in the video below):
```
    "workbench.colorCustomizations": {
        "quickInputList.focusBackground": "#ff0000", // red
        "quickInputList.focusForeground": "#00ff00", // green
        "list.hoverBackground": "#0000ff", // blue
        "list.hoverForeground": "#ffff00", // yellow
        "dropdown.background": "#ff00ff", // magenta
        "dropdown.listBackground": "#00ffff" // cyan
    }
```
2. Hover over the select items of a select box (try the one in the output panel)
    * notice how the hover FG is applied with the focus BG (should be either both hover, or both focus)
    * notice how disabled options applies a style (no visible extra styling should be applied on hover)

Video:

https://user-images.githubusercontent.com/16533424/128021259-a544dfc0-f39c-4afa-9fa4-435d3c4f34d7.mp4

### PR DESCRIPTION
**Pull request by lezgomatt**
This PR fixes #130038.

Summary of changes on custom select boxes:
* Consistent application of hover styles
    * **Before:** The hover FG would apply to focused options, but the hover BG would not
    * **After:** Neither FG or BG will be set, focused styles always win
* Proper clearing of styles when hovering over disabled options
    * **Before:** Hover styles might not be cleared if some theme styles were unset, and the styles did not always match regular items
        * The `background-color` (not `color`) was set to the `listActiveSelectionForeground` (an active FG is probably a mistake too)
        * The `background-color` (again) would be set to `selectBackground` (which might not match the `selectListBackground`)
    * **After:** Hover styles are always cleared for disabled options, and should always match regular unselected items

Some other notes:
* This is the only style with an outline of `1.6px`, everything else seems to use `1px`, not sure if this is intentional
* I'm not actually sure if the regular hover styles are ever used since hovering seems to imply focus

### CODE REVIEW

**Comment by hediet** [comment]
Thanks for the PR!
Can you please open an issue to describe what problem this PR fixes (Including Gifs)?
Thank you!

**Comment by lezgomatt** [comment]
Hi @hediet, created #130038 (with a video). Please let me know if there are any other issues. Thanks!

**Comment by roblourens** [comment]
Thanks! I am still a little confused about the styling of this component. I never see `list.hoverBackground/Foreground` take effect, only the quick input style? Do you happen to know why? And I actually don't see any different between hover/focus, shouldn't there still be hover-specific styles?

**Comment by lezgomatt** [comment]
> Thanks! I am still a little confused about the styling of this component. I never see list.hoverBackground/Foreground take effect, only the quick input style? Do you happen to know why? And I actually don't see any different between hover/focus, shouldn't there still be hover-specific styles?

Yes, if I'm not mistaken, after this fix, the hover styles never show up (except the one for the disabled option which clears the styles). The reason is because hovering over an option automatically causes it to be focused as well, which is not how the other UI elements work.

To fix this, an option should not automatically focus on hover, but only on selection via keyboard (to be consistent with the other UI elements). However, that is a bigger change, and may have implications which I do not fully understand.

Alternatively, I could let the hover style win over the focused style (by removing the `:not(.focused)` part), but this would not be consistent with how the other the other UI elements behave.

**Comment by roblourens** [comment]
> The reason is because hovering over an option automatically causes it to be focused as well, which is not how the other UI elements work.

Yeah, maybe we did that to make it look a little more like a typical dropdown which I guess wouldn't have two highlight colors.

> EDIT: After playing around with the select box, I did fine one scenario where the hover styles do apply: Try hovering over an option, and then switching the focus to another option using the keyboard arrows. The hovered element should now show the hover styles.

I see that, thanks

**Review by roblourens — APPROVED** [review]
Thanks!

**Pull request merged**
