### PR TITLE
Add markdown task lists support

### PR DESCRIPTION
**Pull request by Milo123459**
Hey, 

This PR adds support for rendering github check boxes in the built in preview.

Marking as draft as I have a few questions:

The linter is failing due to bad whitespace indentation in the CSS. I can't figure it out for the life of me.

This targets the preview system, but for some reason isn't triggering on render. Have I forgot to add `markdown-task-lists` somewhere?

### CODE REVIEW

**Comment by 4086606** [comment]
Not a MS employee but did you open an issue and check the feature would be welcome? It's GitHub-exclusive syntax that already has a [Marketplace extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox)

**Comment by Milo123459** [comment]
I didn't open an issue but I know they check boxes are supported on various platforms other than github. This was designed to replace the extension.

**Comment by 4086606** [comment]
As an extension to the language, per [this reasoning](https://talk.commonmark.org/t/task-lists-in-standard-markdown/41/6). But I don't know what flavor the VSC team are using or their design goals, so I'll step out and let them judge this better

**Comment by joaomoreno** [comment]
@Milo123459 This is not how we usually do things. Please refer to the [Contribution Guide](https://github.com/microsoft/vscode/wiki/How-to-Contribute) if you want to bring in helpful contributions. Thanks for the PR, but we're going to close it. Feel free to publish that extension into the Marketplace.

**Pull request closed without merging**
