### PR TITLE
Improve readability for extensions part in issue template

### PR DESCRIPTION
**Pull request by octref**
Currently:

image

With this change:
[Generated link](https://github.com/Microsoft/vscode/issues/new?body=-%20VSCode%20Version%3A%20code-oss-dev%201.7.0%20%28Commit%20unknown%2C%20Date%20unknown%29%0A-%20OS%20Version%3A%20Darwin%20x64%2015.6.0%0A-%20Extensions%3A%0A%0A%7C%20Extension%20%7C%20Author%20%7C%20Version%20%7C%0A%7C%20---%20%7C%20---%20%7C%20---%20%7C%0A%7C%20%5Bpath-intellisense%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dchristian-kohler.path-intellisense%29%20%7C%20christian-kohler%20%7C%201.1.0%20%7C%0A%7C%20%5Bvscode-eslint%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Ddbaeumer.vscode-eslint%29%20%7C%20dbaeumer%20%7C%201.0.7%20%7C%0A%7C%20%5Bpython%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Ddonjayamanne.python%29%20%7C%20donjayamanne%20%7C%200.4.2%20%7C%0A%7C%20%5BGo%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dlukehoban.Go%29%20%7C%20lukehoban%20%7C%200.6.43%20%7C%0A%7C%20%5BTheme-TomorrowKit%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dms-vscode.Theme-TomorrowKit%29%20%7C%20ms-vscode%20%7C%200.1.3%20%7C%0A%7C%20%5Bjs-atom-grammar%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dms-vscode.js-atom-grammar%29%20%7C%20ms-vscode%20%7C%200.1.9%20%7C%0A%7C%20%5Bdebugger-for-chrome%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dmsjsdiag.debugger-for-chrome%29%20%7C%20msjsdiag%20%7C%201.1.0%20%7C%0A%7C%20%5Bvscode-json-transform%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Doctref.vscode-json-transform%29%20%7C%20octref%20%7C%200.1.2%20%7C%0A%7C%20%5Bnode-debug%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dms-vscode.node-debug%29%20%7C%20ms-vscode%20%7C%201.6.0%20%7C%0A%7C%20%5Bvim%5D%28https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Dvscodevim.vim%29%20%7C%20vscodevim%20%7C%200.3.7%20%7C%0A%0A---%0A%0ASteps%20to%20Reproduce%3A%0A%0A1.%0A2.)

image

### CODE REVIEW

**Comment by bpasero** [comment]
@octref can you make sure this works with Edge on Windows?

**Comment by octref** [comment]
The link works fine in IE.
But if I'm not logged in GitHub, this link triggers this:

image

If I'm logged in it's all good.
I asked GitHub support and am waiting for response.

**Comment by octref** [comment]
GitHub has an internal issue logged for this. Current implementation would still error out on ~20 extensions for non-logged-in user.

I changed the PR so the query remains roughly the same length as current implementation. No hyperlinks but still much easier to read:

image

image

**Comment by bpasero** [comment]
Thx

**Pull request merged**
