### PR TITLE
Highlight escaped characters in default Light+ (Fix #48638)

### LINKED ISSUE #48638: Feature request: highlight escaped javascript characters in default Light+ theme
VS Code version: Code 1.22.2
OS version: MacOS High Sierra 10.13.4

In the dark+(Default dark) theme of vs code, escape sequences in javascript are highlighted:

However, in the light+(Default light) theme, escape sequences on javascript are not highlighted:

Is there a specific reason for this? If not, it would be nice to have highlighting added to the Light+ default theme.

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Fixed #48638
Before
before
After
after

These issue is cause of `string` and `constant.character.escape` is same(`#a31515`).

This new color(`#800000`) looks not so changed. I referenced dark-theme 
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json#L159
use same color from
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_vs.json#L90
and
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_vs.json#L164

So this `#800000` is used from
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/light_vs.json#L88
and
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/light_vs.json#L66

### CODE REVIEW

**Comment by mjbvz** [comment]
Code change looks good but the color is too low contrast. What about `#ff0000` which is used by the light theme for regular expressions?

**Comment by Ikuyadeu** [comment]
@mjbvz Thank you for review!
I fixed to `#ff0000` that from `keyword.operator.or.regexp` and `keyword.control.anchor.regexp`

screen shot 2018-04-28 at 17 37 37

However `#000000` that from `keyword.operator.quantifier.regexp` is also good contrast and it is same usage of default dark theme.
screen shot 2018-04-28 at 17 37 18

**Comment by mjbvz** [comment]
Thanks. If anyone complains about the bright red color, we can switch it to black as you suggest. 

It's too late to put this change in the upcoming VS Code 1.23 release, but it will be in May VS Code release: 1.24

**Comment by Ikuyadeu** [comment]
@mjbvz OK, thank you for merge.

**Pull request merged**
