### PR TITLE
Introduce services in Electron main process

### PR DESCRIPTION
**Pull request by joaomoreno**
cc @bpasero 

The main idea here is to isolate what `env.ts` does exactly. It was a mix of aggregating options, parsing command line arguments, creating user directories, etc... We want it to simply be a collection of properties others can reach into. By making it into a service, we control what it exposes via the interface, which we should then clean. This PR only has the scope of introducing services in the main electron process side so we can proceed with the rest.

### CODE REVIEW

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by joaomoreno** [comment]
@bpasero I'm quite happy already. There are no more static managers and static env exported functions. Giving it to you for quick review.

**Comment by bpasero** [comment]
@joaomoreno I did a brief check of your changes, but since they are a lot I did not do a line by line review. Overall I like the services introduced and it makes sense to have the same service model we have on the renderer side also on the client.

The only immediate feedback I have is to keep the service names consistent:
`ISettingsManager` => `ISettingsService`
`IWindowsManager` => `IWindowService`
`IUpdateManager` => `IUpdateService`
`IEnvServie` => `IEnvironmentService`

**Comment by joaomoreno** [comment]
Just merged it as you commented, thanks for the review. Name changes make sense. I mostly did not change anything, except making a log service. Everything else stayed the same. There is much room for improvement. Would love to see a common IEnvService on all parts of our system, for example. Would also like to strip it down and clean up the many properties it currently has.

**Comment by bpasero** [comment]
+1. would be nice if you could use the same IEnvironmentService on the renderer side that just carries over all the properties it has so that you don't have to do the marshalling manually everywhere.

**Pull request merged**
