### PR TITLE
Fix Setting to disable loop of "next change" in diff view #163331

### LINKED ISSUE #163331: Setting to disable loop of "next change" in diff view
Setting to stop at the bottom (or top) when navigating in the diff view through the changes with "next change" and reaching the last change.
Like @GustavoASC did in https://github.com/microsoft/vscode/pull/92243

### PR DESCRIPTION
**Pull request by Kalmaegi**
Fixes #163331

### CODE REVIEW

**Comment by weartist** [comment]
@joaomoreno Can we reuse the loop value of the previous find?

**Comment by weartist** [comment]
@hediet Hi, how do I request a review for this PR~

**Review by hediet — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by hansu** [comment]
@weartist @hediet @aeschli How can this feature be enabled? Would be a bit useless if not known how to activate it.

**Comment by weartist** [comment]
> @weartist @hediet @aeschli How can this feature be enabled? Would be a bit useless if not known how to activate it.

sorry to just see it, you can try to open editor->find->loop~

**Comment by hansu** [comment]
Thanks for your quick answer, but this is the same like suggested here: https://github.com/microsoft/vscode/issues/163331#issuecomment-1374346838 which doesn't work.

**Pull request merged**
