### PR TITLE
Update cli proc macro2 dependency fix build

### PR DESCRIPTION
**Pull request by niuhuan**
fix build with latest rust version

before

```
➜  cli git:(main) ✗ cargo check
warning: `/Volumes/DATA/Runtimes/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling proc-macro2 v1.0.59n_shrink`
  --> /Volumes/DATA/Runtimes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

```

fix:

```
➜  cli git:(main) ✗ cargo update proc-macro2
warning: `/Volumes/DATA/Runtimes/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Updating crates.io index
    Updating proc-macro2 v1.0.59 -> v1.0.79
note: pass `--verbose` to see 254 unchanged dependencies behind latest
```

after update dependency

```
cli git:(patch-fix-build) cargo check
warning: `/Volumes/DATA/Runtimes/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Blocking waiting for file lock on build directory
    Checking code-cli v0.1.0 (/Volumes/DATA/Projects/vscode/cli)
...
warning: `code-cli` (lib) generated 14 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.93s
```

### CODE REVIEW

**Comment by niuhuan** [comment]
```
➜  cli git:(fix) rustup -V     
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.79.0-nightly (88c2f4f5f 2024-04-02)`
```

**Comment by niuhuan** [comment]
I want to build VSCode, but I don't want to lower the rust version. If it cannot be merged, please fix it.  @justschen

**Comment by justschen** [comment]
believe this is @connor4312

**Comment by connor4312** [comment]
Thanks for the PR, unfortunately we don't allow external PRs to update lockfiles by policy. I have opened the same change here: https://github.com/microsoft/vscode/pull/210414

**Pull request closed without merging**
