### PR TITLE
Fix interception of ArrowUp by search viewlet

### LINKED ISSUE #42166: Move cursor up in editor (Arrow key up) not working when search panel is open
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T16:16:25.767Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Open search panel (opened via magnifying glass on side panel, Ctrl+Shift+F, or F4)
2. Set cursor anywhere inside text editor
3. Using arrow keys the cursor will move left, right, and down, but never up.

### PR DESCRIPTION
**Pull request by usernamehw**
Fixes #42166

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks but I can't repro the original issue. `Constants.FirstMatchFocusKey` is only set when the first match is actually focused, and is cleared when the tree blurs. Are there any other repro steps?

**Comment by usernamehw** [comment]
Don't have any symbol under cursor (end of file will do) & don't have any search results => hit <kbd>F4</kbd>

**Comment by roblourens** [comment]
Now I see it. Thanks for the PR but I'm going with a different fix. `FirstMatchFocusKey` has the wrong value in this case, and I need to fix that.

**Comment by usernamehw** [comment]
I thought it's done intentionally so that when there is no search results & no items focused you still can press `ArrowUp` and go to input above...

**Comment by roblourens** [comment]
That still works with my change: https://github.com/Microsoft/vscode/commit/b48b0b041f2ced1b3bd9b8045e06decda6e9a269

**Pull request closed without merging**
