### PR TITLE
Unify the "pill" design

### LINKED ISSUE #96608: Multiple designs for the "pill" that is being shown in the input field
I have noticed two different "designs" for the pills that are being shown in input fields.

Settings sync preferences
image

Settings
image

Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:31:36.229Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:
1. Click on "Manage" in the lower left hand corner, and choose "Online Services Settings"
2. Use the palette to open "Preferences Sync: Configure..."

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by miguelsolorio**
This PR fixes #96608

This consolidates all of the "pill" designs that we have floating around so that they're unified and consistent.

## Quick pick
image

## Keybindings
image

## Settings
image

## Debug viewlet
image

## Unsaved editors
image

### CODE REVIEW

**Comment by rebornix** [comment]
IMHO the corner with less radius looks better and aligns with context menu and some other input boxes we have in the workbench

old "pill" in settings editor


debug 
image

terminal

image

context menu

**Review by roblourens — APPROVED** [review]
I don't have a strong opinion about which pill design but the code changes look fine

**Comment by roblourens** [comment]
Also dropdowns and context menus only have rounded corners on Mac, so I don't think it's that critical to make this look similar

**Comment by misolori** [comment]
@rebornix I'm not sure we want the labels to _look_ like input elements because that would give the wrong impression that they are interactive. Since these are actually label badges they should all look the same way, and since we already use the circular badges for the activity bar and extensions viewlet I thought it would make sense to use that version.

**Review by bpasero — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]

**Review by chrmarti — APPROVED** [review]

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
Nice changes, thanks for doing this.
I somewhat agree with @rebornix a bit less radius might look better - though this is just my personal preference.

**Comment by rebornix** [comment]
@misolori 👍  agree with your point that aligning with inputs will lead to confusions. The above mockup looks good in the default dark themes and the only nit I still have is it looks somewhat out of place when having the label in a input box and next to a button, but they can be adjusted by repositioning the label and text alignment.  

image

image

**Comment by misolori** [comment]
@rebornix made a slight tweak to make the quick input and button vertically centered:

image

**Comment by rebornix** [comment]
thanks, LGTM.

**Pull request merged**
