### PR TITLE
cli: use vcpkg for everything

### PR DESCRIPTION
**Pull request by connor4312**
This PR is not as big and scary as it looks.

On Windows (only, previously), we used [vcpkg](https://github.com/microsoft/vcpkg) to grab OpenSSL. However, I wanted to do that on all platforms, since:

1. We want to control the specific OpenSSL version we use, and
2. I wanted to get the CLI compiling for the last target, armhf, and vcpkg makes cross-compilation easy

(2) now works, so this PR enables building and bundling the CLI in armhf builds. (1) was a bit more convoluted: vcpkg itself only is maintaining releases for OpenSSL 3.x, but the crypto board says we should not update to that version yet. It also seems to take a few days for vcpkg to release updates for OpenSSL packages.

That's where the bulk of this comes in. Using the approach in https://github.com/microsoft/vcpkg/discussions/26723#discussioncomment-3593425, we copy the last openssl 1.x port files from vcpkg, and then just update them to build against the latest release, 1.1.1q. This is kind of ugly and noisy, but on the plus side we get precise control of the version we build against, _and_ can update as soon as any openssl patches come out (by updating the hash and URL in `portfile.cmake`) without waiting for vcpkg itself to update. Therefore, you can skip most of the `vcpkg-overlay-ports` folder, or if you'd like verify the contents are the same as https://github.com/microsoft/vcpkg/tree/3b3bd424827a1f7f4813216f6b32b6c61e386b2e/ports/openssl

Since vcpkg is also copyright by Microsoft and under the same MIT license, copying the subtree in is fine.

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Seems reasonable, I only skimmed the files and folders containing `cli*` as I don't expect the to impact the main build so I see them as low risk. If you want a thorough review for this stuff you should ping someone more familiar (Deepak, Joao?).

**Review by joaomoreno — COMMENTED** [review]
This scares me, since it's beyond non-trivial. While I can't really argue against it, I can't possibly fully review it either. It also doesn't look like anything we'd like to commit to maintain. A quick glance shows me patches on top of openssl. We need a long-term commitment of ownership on this part of the build. Who can realistically address whenever an issue arises here? How is this maintained in the future? How are versions bumped? Is licensing, third-party-notices taken care of? What's that thing about UWP?

**Comment by connor4312** [comment]
Thanks for the feedback. I have a couple ideas on how to make this less overwhelming--going to try to find time to chat with Joao to get his thoughts on the best way to go forward here 🙂

**Comment by connor4312** [comment]
Followup: I will merge this for today to unblock Martin in his work, but tomorrow will PR an improved version that removes most of the code added here.

**Pull request merged**
