### PR TITLE
menubar add extension menu

### PR DESCRIPTION
**Pull request by f111fei**
We love extension menu in Atom. 

Extension Menu can find which actions provided in installed extensions quickly.

### CODE REVIEW

**Comment by bpasero** [comment]
@f111fei thanks for this PR. Please understand that a change like this with UI impact needs to be discussed first with the team and might not be accepted if we feel that such an extension menu is desired or not.

Let's discuss in https://github.com/Microsoft/vscode/issues/6033

**Comment by f111fei** [comment]
@bpasero   Sure, It`s better if you can provide an api similar to https://atom.io/docs/api/v1.7.3/MenuManager.

**Comment by bpasero** [comment]
Closing, we do not intent to build a menu structure like this.

**Comment by smuuf** [comment]
So your intent is to have extensions placing all sorts of menu items all over the place, resulting in cluttered menus in which the user won't have any chance of finding anything?

**Pull request closed without merging**
