### PR TITLE
cleanup aux window mode forcing titlebar

### LINKED ISSUE #224051: Aux window: `WindowMode.Custom` cleanup
With https://github.com/microsoft/vscode/pull/222315, a new `WindowMode.Custom` was added. This is to enforce a native title bar (I believe).

I suggest to make this more explicit and not by hijacking the `WindowMode` property, which is mainly for driving if the window is fullscreen, maximized or not.

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/224051

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
What about the `electron-main`:

https://github.com/microsoft/vscode/blob/6b46ba06dd9de6720fb49601609f347b4e4cf198/src/vs/platform/window/electron-main/window.ts#L179

**Review by bpasero — COMMENTED** [review]
On a high level this change LGTM but now I notice we have a lot of `hasNativeTitlebar` checks through our code and all those checks would return the wrong thing for issue reporter windows. This may be OK in most cases but some maybe not. I wonder how we can mitigate issues here and make this more consistent?

**Comment by justschen** [comment]
@bpasero giving it a look, `hasNativeTitlebar` is based on settings and isn't necessarily checked anywhere else for the issue reporter window at least, so I don't know how we can change this without knowing the window is an issue reporter window.

we could potentially pass through something that specifies something is coming from the issue reporter, kind of like `isWeb`? 

this would similarly solve the other issue with `fullscreenable`. if we know something is coming from web, we could do something like this:

```typescript
if (windowState.fromIssueReporter) {
     options.fullscreenable = false;
     options.titleBarStyle = 'default';
}


```

**Comment by bpasero** [comment]
@justschen I decided to implement this from scratch in https://github.com/microsoft/vscode/pull/224567 and also tackle https://github.com/microsoft/vscode/issues/224136.

However, its still not very pretty around the fact that in these 2 cases, we will wrongly assume the native title bar is not set given configurations:

https://github.com/microsoft/vscode/blob/6966917b18b8022e14661cd8430e96ec5f27c843/src/vs/platform/auxiliaryWindow/electron-main/auxiliaryWindow.ts#L89-L91

https://github.com/microsoft/vscode/blob/6966917b18b8022e14661cd8430e96ec5f27c843/src/vs/platform/windows/electron-main/windowImpl.ts#L134-L137

I am not entirely sure if it impacts the issue reporter though...

**Comment by justschen** [comment]
@bpasero gotcha! I'll give it a look to see if there is anything else to do on the issue reporter side (looks good atm tho, thanks!)

**Pull request closed without merging**
