### PR TITLE
feat: allow using formatting parts in the workplace suffix

### PR DESCRIPTION
**Pull request by connor4312**
I wanted to use formattings parts in "open recent", like so

image

However I didn't realize that adding it to the "label" would also add it to every file.

image

Instead, allow using these variables in the `workplaceSuffix` too, so that we can get that label in "open recent" and menus without adding it _everywhere_.

### CODE REVIEW

**Comment by connor4312** [comment]
Talked to SteVen a bit about this. I didn't realize there was (remote-proposed) API for `registerResourceLabelFormatter`. Currently we keep a history of recently opened files and store a label in there. This would work really well for us, but there's currently two problems:

- In the scenario I'm working on, the remote is not opened by the extension, but by the embedder. So there's no resourceLabelFormatter registered when the workspace is resolved. We can register the formatter afterwards, and labels do get provided at that point, but they aren't cached in the recently opened objects in the `IWorkspacesService`
- Workspace trust also displays previously-seen file paths. However, it can't take advantage of programmatically-provided resource label formatters, since they might not be activated at the moment.

I propose to instead cache the most recent ~50 extension-provided resource label formatters in global storage, and provide them again on each startup. These formatters are pretty small objects, so I believe this should be fine, and should solve 99% of use cases here. I don't think any formatters will clobber each other, since our current remotes target them by `authority` which are unique and specific to each extension.

cc @bpasero since it looks like you've touched the label service the most

**Comment by connor4312** [comment]
I've now implemented this. Workspace trust has nice labels, even when not connected to the remote 🙂 

image

**Comment by aeschli** [comment]
It's a good idea and I don't see any problems with it. Went over the usages of our remote extensions but not check Codespaces, but think we are fine.
I would probably rename `registerCachedFormatter` to `registerDynamicFormatter`.

**Review by aeschli — APPROVED** [review]

**Comment by bpasero** [comment]
@connor4312 some feedback:
* `memento` was mainly introduced for workbench components to extend from, in most cases just using storage service directly should be fine
* what is the lifecycle of these cached formatters, are they cleaned up? do they update? what if I uninstall an extension?
* the `StorageTarget.User` means that this cache will sync with settings sync, it should probably not?
* I would have rather expected a boolean flag added to `registerFormatter` for deciding whether the formatter should be cached or not
* should all formatters be cached maybe?

@isidorn do you know who owns label service formatters these days? I think you had them in the beginning and then passed on?

**Comment by isidorn** [comment]
@bpasero I passed on to @JacksonKearl and he might have passed it to @lramos15 :)

**Pull request merged**
