### PR TITLE
Show line content in the breakpoints view

### LINKED ISSUE #14351: Breakpoints should render snippet of code line
Similar to how we show snippets in find references we should also show references in breakpoints pane. code snippet         filename : line number alligned to the right
Code snippet should be shown using a mono space font

### PR DESCRIPTION
**Pull request by isidorn**
Fixes #14351

Have been experimenting with showing breakpoint source in the debug viewlet. The current design has some limitations:

* How to render the X button on top of the breakpoint filename (currently I just hide the filename)
* What to show when the breakpoint is added on an empty line
* How to make the file label push out the content (tryed using flex but that screws up the checkbox and the actionbar)

@joaomoreno suggestions are very welcome

breakpoints

### CODE REVIEW

**Comment by joaomoreno** [comment]
The breakpoint could also be to the left of the checkbox, like the Open Editors view.

Empty lines could read `no content` in a different font style.

You should use flex. Not sure how that plays out with the file label, but if all four the elements (checkbox, source, file name, line number) are in a single flex zone, it will work if the source has `flex: 1`.

**Comment by kisstkondoros** [comment]
give this a go:
```css
.debug-viewlet .debug-breakpoints .breakpoint {
    display:flex;
    align-items: center;
}
.debug-viewlet .debug-breakpoints .breakpoint > input[type=checkbox] {
    flex: 0 0 auto;
}

.debug-viewlet .debug-breakpoints .breakpoint > span {
    flex: 0 1 auto;
    overflow: hidden;
    text-overflow: ellipsis;
}
.debug-viewlet .debug-breakpoints .breakpoint > .name {
    flex: 0 0 auto;
}

.debug-viewlet .debug-breakpoints .breakpoint > .line-number {
    flex: 0 0 auto;
    height: 16px;
    line-height: 16px;
}
.debug-viewlet .debug-breakpoints .breakpoint > .file-path {
    flex: 0 1 auto;
}
```

**Comment by isidorn** [comment]
@kisstkondoros thanks! I'll try it out immediatlly

**Comment by isidorn** [comment]
Closing PR as this was actually merged into master after some rework

**Pull request closed without merging**
