### PR TITLE
render icon on the left side of the suggestions

### LINKED ISSUE #123786: Allow specifying an icon for config enums
I implemented intellisense for terminal profile icons https://github.com/microsoft/vscode/issues/122473, but currently the preview is in the description, it would be much easier to use if it was to the left of the string.

Screen Shot 2021-05-13 at 7 41 36 AM

Compare that to how nice the change icon command is:

Screen Shot 2021-05-13 at 7 41 58 AM

### PR DESCRIPTION
**Pull request by BABA983**
Close #123786 
pic1

Not sure if it is an ideal approach. Looking forward to any feedback.

### CODE REVIEW

**Comment by BABA983** [comment]
@jrieken ping in case you miss that.

**Comment by BABA983** [comment]
@jrieken Could you please take a look at this PR? Thanks!

**Comment by jrieken** [comment]
Completion icons are specified (indirectly) via the completion item kind. Adding a second way, via some documentation parsing isn't really clean and desirable.

**Comment by BABA983** [comment]
> Completion icons are specified (indirectly) via the completion item kind. Adding a second way, via some documentation parsing isn't really clean and desirable.

Agree is not an ideal approach.

Should we add another completion item kind to implement this feature? e.g. `CompletionItemKind.Codicon`.

**Pull request closed without merging**
