### PR TITLE
fix: memory leak in simple find widget

### LINKED ISSUE #198977: memory leaks in extensionList and simpleFindWidget
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Ubuntu 23.04

Steps to Reproduce:

### Setup

1. In VSCode, open the extensions view
2. Search for `@builtin html`
3. Click on `HTML Language Basics`
4. Close all editors
5. Repeat steps 3 and 4 several times
6. Notice `auxclick` and `keydown` event listeners have been added but not been removed

```json
{
  "eventListenersWithStackTrace": [
    {
      "type": "auxclick",
      "description": "(e) => this.emitter.fire(e)",
      "objectId": "-4969416604808149280.4.16359",
      "stack": [
        "listener (vscode/out/vs/base/browser/event.js:13:23)",
        "Object.onWillAddFirstListener (vscode/out/vs/base/browser/event.js:16:55)",
        "_event (vscode/out/vs/base/common/event.js:810:60)",
        "vscode/out/vs/base/common/event.js:129:95",
        "Array.map (<anonymous>)",
        "vscode/out/vs/base/common/event.js:129:82",
        "renderMarkdown (vscode/out/vs/base/browser/markdownRenderer.js:158:101)",
        "ExtensionStatusWidget.render (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWidgets.js:629:99)",
        "UniqueContainer.value (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWidgets.js:618:79)",
        "Emitter._deliver (vscode/out/vs/base/common/event.js:882:26)",
        "Emitter.fire (vscode/out/vs/base/common/event.js:911:22)",
        "ExtensionStatusAction.updateStatus (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:2190:37)",
        "ExtensionStatusAction.computeAndUpdateStatus (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:2146:26)",
        "vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:1966:51",
        "Throttler.queue (vscode/out/vs/base/common/async.js:172:34)",
        "ExtensionStatusAction.update (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:1966:34)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:151:70)",
        "vscode/out/vs/workbench/contrib/extensions/common/extensions.js:47:54",
        "Array.forEach (<anonymous>)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/common/extensions.js:47:29)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:281:51)",
        "ExtensionEditor.render (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:352:32)",
        "async ExtensionEditor.setInput (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:296:17)",
        "async EditorPanes.doSetInput (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:313:17)",
        "async EditorPanes.doOpenEditor (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:180:44)",
        "async EditorPanes.openEditor (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:78:28)",
        "async vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:837:65",
        "async ExtensionsWorkbenchService.open (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.js:898:28)"
      ],
      "count": 56,
      "originalStack": ["vscode/src/vs/base/browser/event.ts:40:14"],
      "originalName": null
    },
    {
      "type": "keydown",
      "description": "(e) => {\n                const keyboardEvent = new keyboardEvent_1.StandardKeyboardEvent(e);\n                if (!keyboardEvent.equals(10 /* KeyCode.Space */) && !keyboardEvent.equals(3 /* KeyCode.Enter */)) {\n                    return;\n                }\n                _activateLink(keyboardEvent);\n            }",
      "objectId": "-4969416604808149280.4.16361",
      "stack": [
        "listener (vscode/out/vs/base/browser/markdownRenderer.js:164:96)",
        "new DomListener (vscode/out/vs/base/browser/dom.js:64:24)",
        "Object.addDisposableListener (vscode/out/vs/base/browser/dom.js:78:16)",
        "renderMarkdown (vscode/out/vs/base/browser/markdownRenderer.js:165:55)",
        "ExtensionStatusWidget.render (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWidgets.js:629:99)",
        "UniqueContainer.value (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWidgets.js:618:79)",
        "Emitter._deliver (vscode/out/vs/base/common/event.js:882:26)",
        "Emitter.fire (vscode/out/vs/base/common/event.js:911:22)",
        "ExtensionStatusAction.updateStatus (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:2190:37)",
        "ExtensionStatusAction.computeAndUpdateStatus (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:2146:26)",
        "vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:1966:51",
        "Throttler.queue (vscode/out/vs/base/common/async.js:172:34)",
        "ExtensionStatusAction.update (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:1966:34)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/browser/extensionsActions.js:151:70)",
        "vscode/out/vs/workbench/contrib/extensions/common/extensions.js:47:54",
        "Array.forEach (<anonymous>)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/common/extensions.js:47:29)",
        "set extension [as extension] (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:281:51)",
        "ExtensionEditor.render (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:352:32)",
        "async ExtensionEditor.setInput (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:296:17)",
        "async EditorPanes.doSetInput (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:313:17)",
        "async EditorPanes.doOpenEditor (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:180:44)",
        "async EditorPanes.openEditor (vscode/out/vs/workbench/browser/parts/editor/editorPanes.js:78:28)",
        "async vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:837:65",
        "async ExtensionsWorkbenchService.open (vscode/out/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.js:898:28)"
      ],
      "count": 7,
      "originalStack": ["vscode/src/vs/base/browser/markdownRenderer.ts:204:87"],
      "originalName": null
    }
  ],
  "isLeak": true
}
```

### Test Script

```sh
git clone git@github.com:SimonSiefke/vscode-memory-leak-finder.git &&
cd vscode-memory-leak-finder &&
git checkout v5.26.1 &&
npm ci &&
node packages/cli/bin/test.js --cwd packages/e2e  --check-leaks --measure-after --measure event-listeners-with-stack-traces --runs 7  --only extension.detail &&
cat .vscode-memory-leak-finder-results/event-listeners-with-stack-traces/extension.detail-view-open.json
```

### LINKED ISSUE #199043: memory leak in simpleFindWidget
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Ubuntu 23.04

Steps to Reproduce: Same as in https://github.com/microsoft/vscode/issues/198977

### PR DESCRIPTION
**Pull request by SimonSiefke**
Fixes #199043

### Output with `--measure event-listeners`

```json
{
  "eventListeners": [],
  "isLeak": false
}
```

### CODE REVIEW

**Comment by sandy081** [comment]
Thanks for the PR. I already prepared fix for the `extensionsWidgets.ts` and I do not see issue for other memory leaks fixes you made here. Can you please file issue and prepare the PR accordingly.

**Comment by SimonSiefke** [comment]
Thanks! I made a separate issue for the simpleFindWidget: https://github.com/microsoft/vscode/issues/199043 and updated this PR. 

It seems `-monaco-gesturetap` listeners are added when opening an extension detail view but not removed:

```json
{
  "eventListenersWithStackTrace": [
    {
      "type": "-monaco-gesturetap",
      "description": "(e)=>this.emitter.fire(e)",
      "objectId": "-6782061013704719865.4.16307",
      "sourceMaps": [""],
      "stack": [
        "listener (vscode/out/vs/base/browser/event.js:17:23)",
        "Object.onWillAddFirstListener (vscode/out/vs/base/browser/event.js:20:53)",
        "_event (vscode/out/vs/base/common/event.js:650:60)",
        "new Sash (vscode/out/vs/base/browser/ui/sash/sash.js:241:28)",
        "new SimpleFindWidget (vscode/out/vs/workbench/contrib/codeEditor/browser/find/simpleFindWidget.js:176:36)",
        "new WebviewFindWidget (vscode/out/vs/workbench/contrib/webview/browser/webviewFindWidget.js:33:13)",
        "InstantiationService._createInstance (vscode/out/vs/platform/instantiation/common/instantiationService.js:103:28)",
        "InstantiationService.createInstance (vscode/out/vs/platform/instantiation/common/instantiationService.js:78:31)",
        "new WebviewElement (vscode/out/vs/workbench/contrib/webview/browser/webviewElement.js:298:79)",
        "new ElectronWebviewElement (vscode/out/vs/workbench/contrib/webview/electron-sandbox/webviewElement.js:47:13)",
        "InstantiationService._createInstance (vscode/out/vs/platform/instantiation/common/instantiationService.js:103:28)",
        "InstantiationService.createInstance (vscode/out/vs/platform/instantiation/common/instantiationService.js:78:31)",
        "ElectronWebviewService.createWebviewElement (vscode/out/vs/workbench/contrib/webview/electron-sandbox/webviewService.js:16:56)",
        "OverlayWebview._show (vscode/out/vs/workbench/contrib/webview/browser/overlayWebview.js:164:54)",
        "OverlayWebview.claim (vscode/out/vs/workbench/contrib/webview/browser/overlayWebview.js:110:18)",
        "ExtensionEditor.openMarkdown (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:636:25)",
        "async ExtensionEditor.openDetails (vscode/out/vs/workbench/contrib/extensions/browser/extensionEditor.js:768:33)"
      ],
      "count": 42
    }
  ],
  "isLeak": true
}

```

**Comment by tisilent** [comment]
Sash did not dispose. 😅

**Review by rebornix — APPROVED** [review]
Thank you for the investigation and fix!

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
