### PR TITLE
Fix labels unit tests + root displayed as '..

### PR DESCRIPTION
**Pull request by hun1ahpu**
Iteration on #12040 

Unit tests should work for MacOS. Couldn't verify it though.
Also root path is displayed as '.'

### CODE REVIEW

**Comment by bpasero** [comment]
@hun1ahpu not a good fix, please keep using `nativeSep`, otherwise you end up with slashes on windows as part separator which is not correct, it should be "\". I suggest to fix your tests by using `nativeSep` in the tests too.

**Comment by bpasero** [comment]
@hun1ahpu did you get my message?

**Comment by hun1ahpu** [comment]
@bpasero Yes, i agree it's a bad fix. Will send a new iteration today-tomorrow.
Thanks.

**Comment by bpasero** [comment]
@hun1ahpu great 👍

**Comment by hun1ahpu** [comment]
@bpasero decided to create 2 separate unit tests. it's not easy to read when using nativeSep.

**Comment by bpasero** [comment]
@hun1ahpu looks good, thanks.

**Pull request merged**
