### PR TITLE
[WiP] Git: Add events to API

### PR DESCRIPTION
**Pull request by davinci26**
Implements #73617

### Outstanding Work
- [ ] Adding test cases

### CODE REVIEW

**Comment by davinci26** [comment]
@joaomoreno I am looking for some early feedback on the approach :)

**Comment by davinci26** [comment]
It would be awesome if we could distinguish between events. Dot you think that this could be added at the dotgit watcher level?

**Comment by joaomoreno** [comment]
@davinci26 The git extension has [its own API](https://github.com/microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts), which extensions can just use without any changes in the core. More details: https://github.com/microsoft/vscode/issues/67276

As to the filtering, no I don't think that should be a part of the API. The consumer decides on the filtering.

**Comment by davinci26** [comment]
@joaomoreno thanks for the feedback and the pointers

**Pull request closed without merging**
