### PR TITLE
Fixed #47151 - Added Multi-cursor support to Alt+Up/Alt+Down

### PR DESCRIPTION
**Pull request by irrationalRock**
This PR addresses https://github.com/Microsoft/vscode/issues/47151.
 
The PR adds multi-cursor support to Alt+Up/Alt+Down.
 
You can now move the whole multi-cursor instead of just one.
 
Here is what it looks like when moving up:
worksupv1

 
Here is what it looks like when moving down:
worksdownv1

 
Thanks for considering this PR.

### CODE REVIEW

**Comment by alexandrudima** [comment]
@irrationalRock Thank you!

Could you please also delete `MoveLinesCommand` since it is no longer used and port over the existing tests to use directly the action (and not the command). Here is an example for how the tests can be written using the actions:

https://github.com/Microsoft/vscode/blob/ab13671c5847d1457547b638e688266e56d6b459/src/vs/editor/contrib/linesOperations/test/linesOperations.test.ts#L78:L97

**Comment by Cow258** [comment]
MoveLinesCommand is most useful, I think Multi-cursor should map to Ctrl+Alt+Up/Ctrl+Alt+Down!

**Comment by alexandrudima** [comment]
@Cow258 Sorry, I don't understand what you're talking about. This PR is not about removing the move lines action or about changing anything regarding the keybindings for multi-cursor. It simply improves the move lines actions (up or down) in the case where there are multiple cursors.

**Review by alexdima — CHANGES_REQUESTED** [review]
Please delete `MoveLinesCommand` since it is no longer used and port over the existing tests to use directly the action (and not the command). Here is an example for how the tests can be written using the actions:

https://github.com/Microsoft/vscode/blob/ab13671c5847d1457547b638e688266e56d6b459/src/vs/editor/contrib/linesOperations/test/linesOperations.test.ts#L78:L97

**Comment by irrationalRock** [comment]
Thanks for the feedback. I'm working on porting over the tests and I'll probably get them done by the end of the weekend.

**Comment by irrationalRock** [comment]
Hi, I have ported over most of tests and fix a small bug with the feature. I haven’t porting over ` first line indentation adjust to 0 ` and `move lines across block`. Both of them use `IndentRulesMode` and I am unsure how to port them over. If these tests are necessary, it would help if you could provide some guidance. Also I will squash some of my commits soon.

**Comment by alexandrudima** [comment]
There was **a lot** of code in there handling `editor.autoIndent: true` that is now deleted. I wrote the move lines command originally, but in the meantime a lot of code was added by @rebornix . The feature consists of reindenting lines when moving them up/down. 

I will leave it to @rebornix to further review, but I believe the changes you have made should kick in only when `editor.autoIndent: false` or when there are multiple cursor or something like that and fall back to the old code when `editor.autoIndent: true`...

**Comment by zhangkaiyulw** [comment]
Hello @irrationalRock, @rebornix 
this is a really exciting enhancement. Any updates on this? 😶

**Pull request closed without merging**
