### PR TITLE
toggle dev tools active on all contexts

### PR DESCRIPTION
**Pull request by aaomidi**
The UI shows this as a valid shortcut, but currently it's only valid if you're developing vscode.

### CODE REVIEW

**Comment by bpasero** [comment]
> The UI shows this as a valid shortcut

@aaomidi where?

**Comment by aaomidi** [comment]
image

**Comment by bpasero** [comment]
@aaomidi I would prefer if we would fix the issue that shows the keybinding in the first place than changing this condition. Please report it.

**Comment by aaomidi** [comment]
Ah, I think theres a lot of use for having the ability to open developer tools :/

**Pull request closed without merging**
