### PR TITLE
repl: use tree dynamic height

### PR DESCRIPTION
**Pull request by isidorn**
In this PR the debug console adopts the `tree` `dynamicHeight` feature. Which lets us get rid of a lot of code which is no longer needed (manual measuring of character width).

However there seem to be some issue with the tree at the moment. To repro:
1. Have the following javascript program
```javascript
console.log('hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello');
```
2. Start debugging it, and notice how the debug console does not nicely wrap the long string

I investigated a bit, and it seems like the next tree elemnt overlaps it.
Note that for this element I give a "provisional" height of 18px.

### CODE REVIEW

**Comment by isidorn** [comment]
Moving this to February, as @joaomoreno is overloaded with tree feature requests.
Once we get dynamic height in the tree we can revisit this, but not this milestone

**Comment by joaomoreno** [comment]
Thanks. That feature is also still stabilizing since it's currently being used in the settings editor and we're still fixing issues. I'm gonna feel more confident if we just do this one next month.

**Comment by isidorn** [comment]
Joao sorry for the spam I am testing the PR extension.
Adding a comment

**Comment by isidorn** [comment]
@joaomoreno can I just enable the dynamic height now? Since settings is already using ti right?
Or we play it safe and push this to march?

**Comment by joaomoreno** [comment]
@isidorn Not without extensive testing please!

**Comment by isidorn** [comment]
Closing due to merge conflicts. I have a new version locally

**Pull request closed without merging**
