### PR TITLE
Repl links fix

### PR DESCRIPTION
**Pull request by felixfbecker**
@isidorn Fixes for #13370 

I got a bunch of errors trying to build VS Code. I will look into this and try to test this later but I wanted to share my commits anyway.

- "root" capture group is now optional to allow relative paths
- "column" capture group is now optional to allow paths without columns (will default to 0)
- colon was added to the path blacklist so the line doesn't get detected as part of the path and the column as line
- optional `file://` prefix was added so the a whole file URI is underlined and not just the path part

### CODE REVIEW

**Comment by felixfbecker** [comment]
Here were the errors I met when compiling:
```
[14:53:20] Using gulpfile c:\Users\felix\git\OpenSource\vscode\gulpfile.js
[14:53:20] Starting 'clean-client'...
[14:53:20] Starting 'clean-extension:configuration-editing'...
[14:53:20] Starting 'clean-extension:css-client'...
[14:53:20] Starting 'clean-extension:css-server'...
[14:53:20] Starting 'clean-extension:extension-editing'...
[14:53:20] Starting 'clean-extension:git'...
[14:53:20] Starting 'clean-extension:html-client'...
[14:53:20] Starting 'clean-extension:html-server'...
[14:53:20] Starting 'clean-extension:javascript'...
[14:53:20] Starting 'clean-extension:json-client'...
[14:53:20] Starting 'clean-extension:json-server'...
[14:53:20] Starting 'clean-extension:markdown'...
[14:53:20] Starting 'clean-extension:php'...
[14:53:20] Starting 'clean-extension:python'...
[14:53:20] Starting 'clean-extension:typescript-test-colorize-fixtures'...
[14:53:20] Starting 'clean-extension:typescript'...
[14:53:20] Starting 'clean-extension:vscode-api-tests'...
[14:53:20] Starting 'clean-extension:vscode-colorize-tests'...
[14:53:20] Finished 'clean-extension:configuration-editing' after 65 ms
[14:53:20] Starting 'watch-extension:configuration-editing'...
[14:53:20] Starting compilation...
[14:53:20] Finished 'clean-extension:css-client' after 269 ms
[14:53:20] Starting 'watch-extension:css-client'...
[14:53:20] Finished 'clean-extension:css-server' after 275 ms
[14:53:20] Starting 'watch-extension:css-server'...
[14:53:20] Finished 'clean-extension:extension-editing' after 281 ms
[14:53:20] Starting 'watch-extension:extension-editing'...
[14:53:20] Finished 'clean-extension:git' after 285 ms
[14:53:20] Starting 'watch-extension:git'...
[14:53:20] Finished 'clean-extension:html-client' after 290 ms
[14:53:20] Starting 'watch-extension:html-client'...
[14:53:20] Finished 'clean-extension:html-server' after 292 ms
[14:53:20] Starting 'watch-extension:html-server'...
[14:53:20] Finished 'clean-extension:javascript' after 296 ms
[14:53:20] Starting 'watch-extension:javascript'...
[14:53:20] Finished 'clean-extension:markdown' after 302 ms
[14:53:20] Starting 'watch-extension:markdown'...
[14:53:20] Finished 'clean-extension:python' after 308 ms
[14:53:20] Starting 'watch-extension:python'...
[14:53:20] Finished 'clean-extension:typescript-test-colorize-fixtures' after 310 ms
[14:53:20] Starting 'watch-extension:typescript-test-colorize-fixtures'...
[14:53:20] Finished 'clean-extension:vscode-colorize-tests' after 310 ms
[14:53:20] Starting 'watch-extension:vscode-colorize-tests'...
[14:53:20] Finished 'clean-extension:json-client' after 587 ms
[14:53:20] Starting 'watch-extension:json-client'...
[14:53:21] Finished 'clean-extension:vscode-api-tests' after 624 ms
[14:53:21] Starting 'watch-extension:vscode-api-tests'...
[14:53:21] Finished 'clean-extension:typescript' after 962 ms
[14:53:21] Starting 'watch-extension:typescript'...
[14:53:27] Finished 'clean-extension:php' after 6.74 s
[14:53:27] Starting 'watch-extension:php'...
[14:53:27] Finished 'clean-extension:json-server' after 6.75 s
[14:53:27] Starting 'watch-extension:json-server'...
[14:53:50] Finished 'clean-client' after 30 s
[14:53:50] Starting 'watch-client'...
[14:57:22] [monaco.d.ts] Starting monaco.d.ts generation
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/cancellation): CancellationTokenSource, CancellationToken
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\cancellation.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/uri): URI
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\uri.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/standalone/standaloneBase): KeyCode, KeyMod
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\standalone\standaloneBase.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/htmlContent): MarkedString
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\htmlContent.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/browser/keyboardEvent): IKeyboardEvent
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\browser\keyboardEvent.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/browser/mouseEvent): IMouseEvent
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\browser\mouseEvent.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/editorCommon): IScrollEvent, IPosition, IRange, ISelection
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\editorCommon.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/core/position): Position
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\core\position.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/core/range): Range
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\core\range.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/core/selection): Selection, SelectionDirection
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\core\selection.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/browser/standalone/standaloneEditor;modes.=>languages.):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\standalone\standaloneEditor.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/services/webWorker): MonacoWebWorker, IWebWorkerOptions
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\services\webWorker.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/browser/standalone/standaloneCodeEditor): IEditorConstructionOptions, IDiffEditorConstructionOptions, IStandaloneCodeEditor, IStandaloneDiffEditor
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\standalone\standaloneCodeEditor.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/platform/contextkey/common/contextkey): IContextKey
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\platform\contextkey\common\contextkey.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/browser/standalone/standaloneServices): IEditorOverrideServices
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\standalone\standaloneServices.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/platform/markers/common/markers): IMarkerData
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\platform\markers\common\markers.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/browser/standalone/colorizer): IColorizerOptions, IColorizerElementOptions
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\standalone\colorizer.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/scrollable): ScrollbarVisibility
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\scrollable.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/editorCommon;IMode=>languages.IMode): IPosition, IRange, ISelection, SelectionDirection, IScrollEvent
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\editorCommon.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/browser/editorBrowser;editorCommon.=>):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\editorBrowser.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/browser/standalone/standaloneLanguages;modes.=>;editorCommon.=>editor.;IMarkerData=>editor.IMarkerData):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\standalone\standaloneLanguages.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/modes/languageConfiguration):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\modes\languageConfiguration.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/modes;editorCommon.IRange=>IRange;editorCommon.IPosition=>IPosition;editorCommon.=>editor.;IToken2=>IToken;ILineTokens2=>ILineTokens;IState2=>IState):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\modes.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/services/modeService): ILanguageExtensionPoint
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\services\modeService.d.ts
[14:57:23] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/services/editorSimpleWorker;):
[14:57:23] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\services\editorSimpleWorker.d.ts
[14:57:23] [monaco.d.ts] Finished monaco.d.ts generation
[14:57:52] [monaco.d.ts] Starting monaco.d.ts generation
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/cancellation): CancellationTokenSource, CancellationToken
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\cancellation.d.ts
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/uri): URI
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\uri.d.ts
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/htmlContent): MarkedString
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\htmlContent.d.ts
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/browser/keyboardEvent): IKeyboardEvent
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\browser\keyboardEvent.d.ts
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/browser/mouseEvent): IMouseEvent
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\browser\mouseEvent.d.ts
[14:57:52] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/editor/common/editorCommon): IScrollEvent, IPosition, IRange, ISelection
[14:57:52] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\editorCommon.d.ts
[14:57:53] [monaco.d.ts] WHILE HANDLING RULE:  #include(vs/base/common/scrollable): ScrollbarVisibility
[14:57:53] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\base\common\scrollable.d.ts
[14:57:53] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/editorCommon;IMode=>languages.IMode): IPosition, IRange, ISelection, SelectionDirection, IScrollEvent
[14:57:53] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\editorCommon.d.ts
[14:57:53] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/browser/editorBrowser;editorCommon.=>):
[14:57:53] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\browser\editorBrowser.d.ts
[14:57:53] [monaco.d.ts] WHILE HANDLING RULE:  #includeAll(vs/editor/common/modes;editorCommon.IRange=>IRange;editorCommon.IPosition=>IPosition;editorCommon.=>editor.;IToken2=>IToken;ILineTokens2=>ILineTokens;IState2=>IState):
[14:57:53] [monaco.d.ts] CANNOT FIND FILE c:\Users\felix\git\OpenSource\vscode\out\vs\editor\common\modes.d.ts
[14:57:56] [monaco.d.ts] Finished monaco.d.ts generation
[14:58:05] Finished compilation with 0 errors after 285193 ms
[14:58:07] Starting compilation...
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(290,23): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(294,26): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(294,40): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(299,25): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(304,28): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(304,42): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(309,32): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(314,35): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(314,49): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(326,26): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(330,46): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(361,31): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(365,36): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(369,40): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(369,58): Cannot find name 'IPosition'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(373,30): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(377,37): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(377,57): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(382,26): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(387,29): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(387,40): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(391,32): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(395,35): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(395,46): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(399,28): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(403,31): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(403,42): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(435,39): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(439,28): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(443,43): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(447,45): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(447,56): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(452,44): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(452,55): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(457,42): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(457,53): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(461,42): Cannot find name 'IRange'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(497,32): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(501,35): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(501,50): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(517,35): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(521,38): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(521,55): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(525,47): Cannot find name 'ISelection'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(583,73): Cannot find name 'Uri'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(583,79): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(588,45): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(593,44): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(598,35): Cannot find name 'Uri'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(598,41): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(603,34): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(609,56): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(615,58): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(622,25): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(645,46): Cannot find name 'IModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(663,40): Cannot find name 'Uri'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(685,57): Cannot find name 'ICodeEditorWidgetCreationOptions'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(701,61): Cannot find name 'IDiffEditorOptions'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(704,52): Cannot find name 'ICodeEditor'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(707,31): Cannot find name 'IActionDescriptor'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(710,52): Cannot find name 'IDiffEditor'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(713,31): Cannot find name 'IActionDescriptor'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(779,69): Cannot find name 'TokensProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(789,77): Cannot find name 'ReferenceProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(794,74): Cannot find name 'RenameProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(799,81): Cannot find name 'SignatureHelpProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(804,73): Cannot find name 'HoverProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(809,82): Cannot find name 'DocumentSymbolProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(814,85): Cannot find name 'DocumentHighlightProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(819,78): Cannot find name 'DefinitionProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(824,76): Cannot find name 'CodeLensProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(834,90): Cannot find name 'DocumentFormattingEditProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(839,95): Cannot find name 'DocumentRangeFormattingEditProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(844,88): Cannot find name 'OnTypeFormattingEditProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(849,72): Cannot find name 'LinkProvider'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(877,42): Module 'monaco.editor' has no exported member 'IReadOnlyModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(877,107): Cannot find name 'CancellationToken'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(877,127): Cannot find name 'CodeAction'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(877,151): Cannot find name 'CodeAction'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(955,27): Module 'monaco.editor' has no exported member 'ISingleEditOperation'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(990,46): Module 'monaco.editor' has no exported member 'IReadOnlyModel'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(990,89): Cannot find name 'CancellationToken'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(997,61): Cannot find name 'CancellationToken'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/monaco.d.ts(1308,23): Cannot find name 'Uri'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/editor/common/standalone/standaloneBase.ts(222,3): Type '{ editor: undefined; languages: undefined; CancellationTokenSource: typeof CancellationTokenSourc...' is not assignable to type 'typeof monaco'.
  Object literal may only specify known properties, and 'CancellationTokenSource' does not exist in type 'typeof monaco'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/editor/browser/standalone/standaloneLanguages.ts(512,3): Type '{ register: (language: ILanguageExtensionPoint) => void; getLanguages: () => ILanguageExtensionPo...' is not assignable to type 'typeof languages'.
  Object literal may only specify known properties, and 'DocumentHighlightKind' does not exist in type 'typeof languages'.
[14:59:33] Error: c:/Users/felix/git/OpenSource/vscode/src/vs/editor/browser/standalone/standaloneEditor.ts(282,3): Type '{ create: any; createDiffEditor: (domElement: HTMLElement, options?: IDiffEditorConstructionOptio...' is not assignable to type 'typeof editor'.
  Object literal may only specify known properties, and 'ScrollbarVisibility' does not exist in type 'typeof editor'.
[14:59:33] Finished compilation with 87 errors after 86203 ms
[14:59:33] [monaco.d.ts] Starting monaco.d.ts generation
[14:59:37] [monaco.d.ts] Finished monaco.d.ts generation
[14:59:39] Starting compilation...
[15:00:20] Finished compilation with 0 errors after 41191 ms
```
I did `scripts/npm install && node_modules/.bin/gulp watch`

**Comment by isidorn** [comment]
Passing tests, code looks good -> merging in and we will see on insiders if this breaks some use cases.
@felixfbecker thanks a lot 🍻

**Comment by felixfbecker** [comment]
Looks like whitespace is included at the beginning of paths

image

**Comment by felixfbecker** [comment]
Also, passing the relative path doesn't work

image

**Comment by isidorn** [comment]
Are you willing to look into fixing this? This is no big issue so any time in november would work.

Where exactly do you see white space on the first picture - I might be missing something.
Regarding the second one - might be tricky as the editor service tries to open the relative path and does not care about the workspace. @bpasero any ideas on this one?

**Comment by bpasero** [comment]
Only absolute paths should leave the repl to any service in the workbench. If a path is relative, the link detector should convert it to an absolute path using the workspace service.

**Comment by felixfbecker** [comment]
Yes, will fix. See the `_____________` before the first "at". It is whitespace that should be matched by the regexp.

**Comment by felixfbecker** [comment]
@bpasero How can I use the "workspace service" to convert the path to absolute?

**Comment by bpasero** [comment]
@felixfbecker`contextService.toResource()` for example in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configurationService.ts#L204

**Pull request merged**
