### PR TITLE
fix uncaughtException endless loop

### PR DESCRIPTION
**Pull request by f111fei**
UncaughtException Event thrown a new Error and  Plugin host process will enter endless loop if uncaughtException occured.
we had addLisentener for uncaughtException in bootstrap.js.
Don't care my grammar mistakes, my English is poor.

### CODE REVIEW

**Comment by jrieken** [comment]
@f111fei I was able to reproduce the behaviour you are describing and trying to fix. Can you please add more steps that allow me to reproduce the endless loop?

**Comment by f111fei** [comment]
Anyway, Let plugin host process throw an uncaughtException.  For example Modify 
vs/workbench/services/thread/electron-browser/threadService.ts  line 146
let initPayload = "{}";
so plugin host process will initialize failed and throw an uncaughtException.

**Comment by jrieken** [comment]
Yes, but how does that cause an endless loop? Can you capture the stack trace of the functions involved in there?

**Comment by f111fei** [comment]
throw an uncaughtException.

vs/workbench/node/pluginHostProcess.ts
image

invoke unexpectedErrorHandler
 
vs/base/common/errors.ts


throw an uncaughtException.

Here will cause an endless loop.

Toggle Develop Tools ,  console show the stack trace 

Did I make myself clear enough?

**Comment by jrieken** [comment]
Actually, not true. When running in the extension host the handling of those errors in defined by this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/browser/pluginHost.api.impl.ts#L136

The use of `onUnexpectedError` might be questionable but being aware of uncaught exception is something we want. Because of that I disagree with the change you propose (remove of the handler).

**Pull request closed without merging**
