### PR TITLE
Try mangling `_private` service props

### PR DESCRIPTION
**Pull request by mjbvz**
This enables [property mangling](https://esbuild.github.io/api/#mangle-props) for properties with names such as `_someService`. This is designed to only touch properties that we are confident can be mangled  safely (in this  case, any private services)

This results in a very small (0.75%) reduction in the size of workbench.js. For the future:

- If we mangle every `this.someService` property, we could reduce the bundle size by 4% 

- If we mangle every `this._privateProp` properties, we could reduce the bundle size by 6%. We could likely save more by adopting `_` names for private props in more places

- If we mangle every property, we'd reduce by bundle size by 40% (this is only theoretically, as doing this completely breaks the code)

### CODE REVIEW

**Comment by jrieken** [comment]
Change looks good, unsure about the CI failure tho

**Comment by jrieken** [comment]
Could this be failing because folks use `_` for protected services that are now being mangled?

**Comment by mjbvz** [comment]
@jrieken Where were seeing the failures? I created a private build (13c08c6753efa6b0a02a305ec4c1fe988f1f40db). It [failed for unrelated reasons](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=191158&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206). I will kick off another test build though

I also sanity checked the bits that succeeded and everything seems to run ok

**Comment by jrieken** [comment]
Sorry, saw the wrong/bogous build failure. Anyways, I do believe there is an inherent risk with this or I am missing something. We have many injected services using `_fffService` that are protected properties ([sample](https://github.com/microsoft/vscode/blob/182beb6ee4bbed13deabce7ca29f52a30a31824a/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L55)). Aren't we breaking those with the mangle?

As a related FYI: I have updated https://github.com/microsoft/vscode/pull/165259 to only check for `_\w+Service` which is a smaller, but not small, list

**Comment by mjbvz** [comment]
@jrieken My understanding of property mangling is that it operates on the entire bundle (not per file). If a `protected` property is managed, all the subclasses using it should also get updated to use the new name. I will confirm this is happening correctly in our codebase

**Comment by mjbvz** [comment]
Closing in favor of #166126

**Pull request closed without merging**
