### PR TITLE
Update Electron to 2.0.9

### PR DESCRIPTION
**Pull request by mfonville**
As described in https://github.com/Microsoft/vscode/pull/57457

Fixes the glibc 2.28 problem, includes the other fixes that @bpasero  was waiting for

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
There is also a reference in the package.json of the smoke test (just search for 2.0.7)

**Comment by mfonville** [comment]
Thanks, I amended the commit for the PR

**Comment by bpasero** [comment]
@mfonville thanks, I think you need to run a yarn install in the smoke test to get the yarn.lock file also updated.

**Comment by mfonville** [comment]
Ok, I also updated the lock file

**Comment by bpasero** [comment]
Thanks!

**Pull request merged**
