### PR TITLE
Ensure hover gets disposed when icon label is removed

### LINKED ISSUE #125565: [Insiders] Terminal tooltip staying after task terminal killed
When build task fails and the terminal is killed, if the user was hovering the terminal title, the tooltip remains if there are still 2+ terminals still open.

Quick steps to reproduce:
- Open a project with no `watch` script in its `package.json`
- Open up two terminals (not split)
- `Tasks: Run Build Task` command,
- Hover over the title of the task terminal.
- When it fails, the tooltip should remain 🐛

Video:
https://user-images.githubusercontent.com/31675041/120865939-3b6b3480-c54c-11eb-84b1-b21330563226.mp4

### PR DESCRIPTION
**Pull request by Tyriar**
There were 2 problems here:
- The timeout wasn't cleared, so the hover could reshow
- When the setupCustomHover dispose was called, the hover wouldn't be disposed

Fixes #125565

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks @Tyriar , the changes make sense. I believe the mouseMoveDomEmitter also need to be disposed when the timeout is disposed.
To be save, maybe also the mouseLeaveDomEmitter, mouseDownDomEmitter.

Asking @alexr00 for a review as well. I basically moved the code from icon label to a separate class and the one change I did is moving away from the deprecated `domEvent` to use `DomEmitter`.

I'm happy to look into proper disposing, just let me know.

**Comment by Tyriar** [comment]
@aeschli thanks, if you can clean this up and merge that would be great 👍

**Comment by alexr00** [comment]
👍 to what Martin said. All the emitters should also be disposed to be safe.

**Comment by aeschli** [comment]
I polished the code a bit and made sure all listeners, the timeout and the hover widget get disposed: 8a17eb3abf7fa6ae906817d8492db2d64fa1fb56

**Pull request closed without merging**
