### PR TITLE
feature: add relativePath to predefined variables

### LINKED ISSUE #25786: Add `${relativeFileNoExtension}` to 'predefined common variables'
- VSCode Version:
1.11.2
- OS Version:
any
Steps to Reproduce:

I'm trying to make a launch configuration that will start debugging the currently-opened TypeScript file using [ava](https://github.com/avajs/ava#debugging)
Right now I can't, because you need to pass it args a bit like this in `launch.json`:
```json
{
    "program": "${workspaceRoot}/node_modules/ava/profile.js",
    "args": ["${workspaceRoot}/path/to/my/file.js"]
}
```

So if you want to run the currently opened test file, you'd use something like:
`"args": ["${workspaceRoot}/${relativeFile}"]`

Which works fine if you're writing plain JavaScript, because ava will be able to run it directly. But if you're using TypeScript, ava will try to interpret the TypeScript as JavaScript and will barf.

If we had `relativeFileNoExtension`, it'd be pretty easy to make a configuration that ran the current file:
`"args": ["${workspaceRoot}/dist/${relativeFileNoExtension}.js"]`

For example, if I have `foo/bar/tests/mytestfile.ts` open, we'd have `relativeFileNoExtension` being `foo/bar/tests/mytestfile` and the arg would be `/path/to/my/workspace/dist/foo/bar/tests/mytestfile.js`, which matches the JavaScript output from `tsc`.
where `dist` is the `outDir` in `tsconfig.json` - obviously this part is project-specific.

I'd imagine the implementation would be something like this in [configurationResolveService](https://github.com/Microsoft/vscode/blob/d4504b92f466a2882931513fde34a610170557d6/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts):

```TypeScript
private get relativeFileNoExtension(): string {
    const relativeFile = this.relativeFile();
    return relativeFile.slice(0, relativeFile.length - paths.extname(relativeFile).length);
}
```

### PR DESCRIPTION
**Pull request by bitjson**
Closes #25786 (Closes #28018)

## Problem Summary
Like in the above issue, I'm trying to debug TypeScript+AVA tests ([here in typescript-starter](https://github.com/bitjson/typescript-starter/blob/master/.vscode/launch.json#L38)).

Ideally, I'd like the flow to be as simple as with javascript spec files – navigate to the file, launch the "Debug Visible Spec" task. 

Unfortunately, this would set the`${file}` predefined variable to e.g.:
`absolute/path/to/typescript-starter/src/lib/number.spec.ts`

But In order to run the compiled test, I need the path to be transformed into:
`absolute/path/to/typescript-starter/build/main/lib/number.spec.js`

This isn't possible given the currently available predefined variables. 

## Solution

This PR adds a new `${relativePath}`, similar to the existing `${relativeFile}` variable, but which only returns the path to the file. Combined with other predefined variables, this gives us much more flexibility, e.g.: `${workspaceFolder}/${relativePath}/${fileBasenameNoExtension}.js`

One non-obvious detail: in many cases, projects need to be able to reference a path which is relative to a folder **inside** `${workspaceFolder}`, so without further configurability, `${relativePath}` doesn't help. (This is the case for most of the commenters in #25786.) 

So in addition to the standard [workspace scope argument](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder), `${relativePath}` accepts a second argument – the path from which the relative path is calculated. This lets us solve all the use cases in the linked issue. For example, this string gives us the transformation needed in the first example:

`${workspaceFolder}/build/main/${relativePath:typescript-starter:src}/${fileBasenameNoExtension}.js`

If the second argument is omitted, the path is simply calculated relative to `${workspaceFolder}`.

Documentation PR: https://github.com/Microsoft/vscode-docs/pull/1649

### CODE REVIEW

**Comment by weinand** [comment]
@bitjson how would your launch configuration look like?

I'm asking because you can specify a TS file for the "program" attribute and the VS Code node debugger will translate the TS path automatically to the corresponding JS path (if a source map exists).

**Comment by bitjson** [comment]
@weinand thanks for the response! You can see the [current `launch.json` here].(https://github.com/bitjson/typescript-starter/blob/master/.vscode/launch.json#L38)

Before this PR, we have to manually navigate to the compiled JS file to debug (but then breakpoints in the TypeScript work perfectly):
```
{
      /// Usage: set appropriate breakpoints in a *.spec.ts file, then open the
      // respective *.spec.js file to run this task. Once a breakpoint is hit,
      // the debugger will open the source *.spec.ts file for debugging.
      "type": "node",
      "request": "launch",
      "name": "Debug Visible Compiled Spec",
      "program": "${workspaceFolder}/node_modules/ava/profile.js",
      "args": [
        "${file}"
        // TODO: VSCode's launch.json variable substitution
        // (https://code.visualstudio.com/docs/editor/variables-reference)
        // doesn't quite allow us to go from:
        // `./src/path/to/file.ts` to `./build/main/path/to/file.js`
        // so the user has to navigate to the compiled file manually. (Close:)
        // "${workspaceFolder}/build/main/lib/${fileBasenameNoExtension}.js"
      ],
      "skipFiles": ["<node_internals>/**/*.js"],
      "runtimeArgs": ["--nolazy"]
    },
```

(Note the comments explaining the issue.)

And after this PR, debugging TypeScript tests is much easier (just hit debug in any test file):
```
{
      "type": "node",
      "request": "launch",
      "name": "Debug Visible Compiled Spec",
      "program": "${workspaceFolder}/node_modules/ava/profile.js",
      "args": [
        "${workspaceFolder}/build/main/${relativePath:typescript-starter:src}/${fileBasenameNoExtension}.js"
      ],
      "skipFiles": ["<node_internals>/**/*.js"],
      "runtimeArgs": ["--nolazy"]
    },
```

So the issue is that we need to provide AVA's `profile.js` as the program, and can only provide our compiled TypeScript output as an argument. 

Ideally, AVA would [support debugging in the more standard `node --inspect` way, as described here](https://github.com/avajs/ava/issues/1505#issuecomment-370654427), but currently that isn't possible. So this `relativePath` predefined variable gives us the flexibility to make debugging work in VSCode.

**Comment by bitjson** [comment]
@weinand also, I'm not sure if I understand what's going wrong with the build:

```
Windows:
PowerShell exited with code '1'.
Directory 'D:\a\1\a\artifacts' is empty. Nothing will be added to build artifact 'build-artifacts-win32'.

macOS:
Bash exited with code '1'.
Directory '/Users/vsts/agent/2.133.3/work/1/a/artifacts' is empty. Nothing will be added to build artifact 'build-artifacts-darwin'.
```

Are those errors related to this PR?

**Comment by bitjson** [comment]
@weinand @isidorn please let me know if there's any way I can improve this PR! I'd love to be able to use this for several projects (where most of the contributors are using VS Code).

**Comment by bitjson** [comment]
Pulled master, fixed conflicts 👍

**Comment by bitjson** [comment]
@weinand checks are passing now (looks like the previous failures were unrelated) – is there anything else I can do to help get this, or something like it, merged?

**Comment by bitjson** [comment]
@isidorn @weinand any news on this PR? Is there a better way to accomplish this?

This would really improve the debugging experience for a lot of Node.js-TypeScript projects.

**Comment by weinand** [comment]
@bitjson sorry, for not looking into this earlier.

Before providing feedback for your PR, first a general comment:
Instead of adding yet another variable with very specific (and difficult to understand) semantics to the growing set of variables, I suggest to create an extension that contributes a command with the specific semantics. Commands can be used in launch configs through the `${command:<command-id>}` syntax. The command's implementation could make use of configuration information that is kept in a workspace (or user's) settings file. 

Feedback:
- naming: we do not use the term "path" in any variable names because it's unhelpful and redundant as all variables return a "path". And "path" is not the directory of a file. What you probably mean is "Dirname". So the name would be "relativeDirname".
- syntax: VS Code's variable syntax supports a qualifying folder name after a ':' separator. But I think we are not yet ready to allow passing additional parameters to variables (in order to turn variables into functions). One issue is the use of ':' as a separator for both the folder name and the parameters. This would result in an awkward `relativeDirname::src` for a single root workspace.

We are willing to accept a PR for a plain variable "relativeDirname" (without the parameter feature).

But if you consider this crippled functionality as not really helpful for your use case, please consider the command based approach from above.

**Comment by bitjson** [comment]
@weinand thanks for reviewing!

On naming – makes sense, not sure how I missed that before. `relativeDirname` would be a much better fit.

And as much as I'd like this one feature to be "built-in", I agree with your rationale on not wanting the parameter. I can remove that.

On creating an extension that contributes a command – is there any chance you could direct me to an example of a similar extension? When I considered it before, I had trouble finding any examples of extensions designed to provide commands for use in `launch.json`. I'd love to take a look.

**Comment by weinand** [comment]
@bitjson 
- create Hello World extension by following these steps: https://code.visualstudio.com/docs/extensions/example-hello-world#_generate-a-new-extension
- replace the activate function with something like this:
  ```
  export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('openFilePathTransformer', (launchConf: any) => {

        const editor = vscode.window.activeTextEditor;
        if (editor) {
            let path = editor.document.fileName;
            if (extname(path) === '.ts') {
                path = path.replace('.ts', '.js');
                path = path.replace('src', 'out');
            }
            return path;
        } else {
            vscode.window.showErrorMessage("no open editor")
        }
        return undefined;
    });

    context.subscriptions.push(disposable);
  }
  ```
- in the package.json replace the three sections "activationEvents", "main", and "contributes" by this:
  ```
    "activationEvents": [
        "onCommand:openFilePathTransformer"
    ],
    "main": "./out/extension",
    "contributes": {
        "commands": [{
            "command": "openFilePathTransformer",
            "title": "Open File Path Transformer"
        }]
    },
  ```
- press F5 to compile and start the extension
- in the new window open some project and modify the launch configs to use the `${command:openFilePathTransformer}` variable. 
 
Please note: in the implementation of the command the enclosing launch config is passed as an argument. So you can analyse the launch config and create a "smart" variable.

**Comment by bitjson** [comment]
Thanks! I'll do some work and report back here in the next week or two.

**Comment by celionelson** [comment]
This is exactly what I've been looking for! Any ETA for this to make it to a VS Code update?

**Comment by jcrben** [comment]
@celionelson you're not the only one - I really think this is a missing builtin piece. but as you'll see above they're pushing for an extension solution.

**Comment by bitjson** [comment]
I would love to do this as an extension, but there's not currently a way to pass arguments to command-based variables (https://github.com/Microsoft/vscode/issues/38327). Any extension solution to this issue is waiting on that capability.

**Comment by weinand** [comment]
VS Code provides a variable `${relativeFileDirname}`.

**Pull request closed without merging**
