### PR TITLE
pass trimmedValue in case no handlerDescriptor

### LINKED ISSUE #61831: Quick opening a file with specific line/character numbers doesn't trim trailing whitespace
Steps to reproduce:
1. Press ⌘P (or equivalent) to open the quick open panel.
2. Type a file name _with a line (and optionally column)_.
image
3. Press space.
There will be no results.
image
Note that leading spaces are trimmed:
image
Additionally, without the line number, trailing spaces are also trimmed:
image

I often accidentally copy trailing whitespace and it would be much more convenient if the whitespace was trimmed (it would be more consistent too).

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Closes #61831

### CODE REVIEW

**Comment by chrmarti** [comment]
Should the same be done here: https://github.com/Microsoft/vscode/blob/b767b7a806eb3434d1753d17655edbbe55840e9b/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L392 ?

**Comment by WaleedAshraf** [comment]
@chrmarti No,
That's the fix from last mistake.

`if(handlerDescriptor)` is true in case of special keys like `term` and `task` etc. Where we don't want to used trimmed value.

**Review by bpasero — CHANGES_REQUESTED** [review]
I feel this should move closer to the place where the line/col is actually being parsed here: https://github.com/Microsoft/vscode/blob/f5fd4f69c69af5973a69cf4dc418d1a233c1692e/src/vs/workbench/contrib/search/browser/openAnythingHandler.ts#L90

Also note that [`prepareQuery`](https://github.com/Microsoft/vscode/blob/f5fd4f69c69af5973a69cf4dc418d1a233c1692e/src/vs/workbench/contrib/search/browser/openAnythingHandler.ts#L96) seems to take care of whitespace already so maybe it should come first?

**Comment by WaleedAshraf** [comment]
@bpasero thanks for pointing in right code.
I accidentally closed this PR (trying to revert last commit)

Here is new PR:  https://github.com/Microsoft/vscode/pull/71985

We are using regex `LINE_COLON_PATTERN` to get **line** and **column** number. I have added `\s*` pattern at the end of regex to ignore white-spaces.

**Pull request closed without merging**
