### PR TITLE
See issue #45997. Adjusting code to allow formatOnSave with autoSave

### PR DESCRIPTION
**Pull request by campelo**
See issue #45997. Adjusting code to allow formatOnSave with autoSave

### CODE REVIEW

**Comment by jrieken** [comment]
There is a reason we don't allow save actions with auto save and just removing it will not be accepted. 

The challenge is that auto save disables the dirty indication and just happens, e.g. there no UX synchronisation with the user to indicate "now save happens" and therefore save actions (which modify before saving) will come as a surprise. 

So, first I wonder why the soft-auto-save settings (onFocusChange, onWindowChange) aren't sufficient here? Then, if this is still an issue we need to think about a better UX that save participation is happening (cos the user didn't do anything). Last, this will only happen when it's behind a setting which is off by default

**Comment by campelo** [comment]
> There is a reason we don't allow save actions with auto save and just removing it will not be accepted.
> 
> The challenge is that auto save disables the dirty indication and just happens, e.g. there no UX synchronisation with the user to indicate "now save happens" and therefore save actions (which modify before saving) will come as a surprise.
> 
> So, first I wonder why the soft-auto-save settings (onFocusChange, onWindowChange) aren't sufficient here? Then, if this is still an issue we need to think about a better UX that save participation is happening (cos the user didn't do anything). Last, this will only happen when it's behind a setting which is off by default

It's very boring onFocusChange or onWindowChange because in some cases that I don't want to save. For example, if the project is running and the files saves onFocusChange all project will be rebuild. If I use auto save after delay I can set 10 seconds (for example) and modify a couple of files without recompiling all time. After this delay I have sure all files will be saved and only one recompilation is need to apply all changes. Our project is very big and there are machines that spend almost 3-4 minutes in each recompilation.

**Comment by jrieken** [comment]
To me, this sounds like you should use manual save

**Comment by campelo** [comment]
> To me, this sounds like you should use manual save

I think manual save is a good workaround, but in our team, there is a lot of people complaining about this feature. How can two features together not work? 
I understood you, but now I should choose only one feature. Or I use saveOnDelay and manually format all files, or I use formatOnSave and manually save all files. Do you see?
Programming is amazing because it automatizes process. So if we combine both of these features is better for everyone. No more manual process is needed to format files and to save them. I think it's important to give us this feature and the combination of them. 
At this time, it's impossible to use a combination of them because one excludes the functionality of the other.

**Comment by jrieken** [comment]
>  it's impossible to use a combination of them because one excludes the functionality of the other.

Yes, for the reasons that I have outlined above

**Pull request closed without merging**
