### PR TITLE
Add new untitled diff command

### PR DESCRIPTION
**Pull request by ste42**
Addresses #165123

This PR adds a new command called "New Untitled Diff" that opens a diff editor with two untitled sides.

I added the command in `src/vs/workbench/contrib/files/browser/fileActions.ts` because the new command is under the `File` category and similar commands (like `Compare Active File with ...` and `New Untitled File`) also appear under `src/vs/workbench/contrib/files/browser/`

Preview of the feature:

https://user-images.githubusercontent.com/49736503/206596618-ae665a48-3de3-4368-84aa-c7f219fe4f9a.mp4

### CODE REVIEW

**Comment by ste42** [comment]
@microsoft-github-policy-service agree [company=""]

**Review by bpasero — CHANGES_REQUESTED** [review]
This is already very good 👏 

I just noticed how we then have these 2 entries:

image

But the menu calls this differently:

image

So I have a suggestion:
* we rename `New Untitled File` to `New Untitled Text File`
* we rename `New Untitled Diff` to `Compare New Untitled Text Files`

I think we should keep `untitled` in the label just to support existing users that may have found the command by typing `untitled`.


I would stay way from using `Diff` in the name because we mainly refer to the diff editor via `compare` labels it seems.

**Comment by ste42** [comment]
How about renaming `New Text File` in the menu bar to `New Untitled File`? The command's id is `'workbench.action.files.newUntitledFile'`, so changing the display name to `New Untitled Text File` puts it out of sync with the id (unless we change the id as well). It also looks like the term `New Text File` is only used in the menu bar.

Another benefit is that it makes `Compare New Untitled Files` a word shorter!

**Comment by bpasero** [comment]
No, we cannot. The current wording in the menu was part of an effort to make things more discoverable and understandable if I remember correctly.

**Comment by ste42** [comment]
To clarify renaming `New Untitled File` to `New Untitled Text File`, a few questions:

- Does this mean every instance where the term shows up, or only the command label?
- How should variable names be handled (change `NEW_UNTITLED_FILE_COMMAND_ID` to `NEW_UNTITLED_TEXT_FILE_COMMAND_ID`, same with `NEW_UNTITLED_FILE_LABEL`)?
- Do command ids also merit a change, like `'workbench.action.files.newUntitledFile'`?

A few examples of other instances: https://github.com/microsoft/vscode/blob/29b117216229e4cfdd3d95fd4cb83ad4c37529fc/src/vs/workbench/contrib/watermark/browser/watermark.ts#L51
https://github.com/microsoft/vscode/blob/29b117216229e4cfdd3d95fd4cb83ad4c37529fc/src/vs/workbench/contrib/files/browser/fileCommands.ts#L658

**Comment by bpasero** [comment]
Yes, I suggest to change user facing labels, but we cannot change command IDs. I think leaving variable names as they are is also fine, but feel free to change them if you feel strong about it.

**Review by bpasero — DISMISSED** [review]
Thanks!

**Review by alexdima — APPROVED** [review]

**Pull request merged**
