### PR TITLE
Fix #33316 now add support for highlight for Unity 5.4+ built-in matrix variables

### LINKED ISSUE #33316: [shaderlab] Update shaderlab grammar
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Fixed by #33317 
The vscode could not highlight builtin shaderlab matrix for unity builtin.
for example for built-in variable unity_ObjectToWorld (introduced by unity v5.4+)

before

But, the following built-in variable could be highlighted by default (available in Unity before 5.4)
bef

Waiting for fixing...

### PR DESCRIPTION
**Pull request by Coresi7**
Fix #33316 
add support for highlight
 "UNITY_MATRIX_M|UNITY_MATRIX_I_V|unity_ObjectToWorld|unity_WorldToObject"

fixed

### CODE REVIEW

**Comment by aeschli** [comment]
Hi @Coresi7 . We get the shader lab grammar from https://github.com/tgjones/shaders-tmLanguage.
Please make the pull request there. Once accepted, I'll run our update script.
Also see:
https://github.com/Coresi7/vscode/blob/ec1f1bfd6a1dc2710632c14dd1478077e903420a/extensions/shaderlab/syntaxes/shaderlab.json#L2

**Comment by Coresi7** [comment]
@aeschli I have made such pull request, how to inform @tgjones ?

**Comment by tgjones** [comment]
@Coresi7 I've merged your PR.

**Comment by aeschli** [comment]
Great. I'll update our grammar next week (this week is our 1.16 endgame week)

**Comment by Coresi7** [comment]
Thanks~! Fixed by https://github.com/tgjones/shaders-tmLanguage/pull/1

**Pull request closed without merging**
