### PR TITLE
Update copyright year to 2016

### PR DESCRIPTION
**Pull request by henkmollema**
The copyright in the about window still shows 2015:

> Copyright (C) 2015 Microsoft. All rights reserved

### CODE REVIEW

**Comment by Tyriar** [comment]
I'm not 100%, but I think you want to keep "from" original year and add an optional "to" year for this sort of thing. @chrisdias?

**Comment by henkmollema** [comment]
Yes, that makes sense. Do you want me to change it?

**Comment by henkmollema** [comment]
Updated @Tyriar @chrisdias

**Comment by chrisdias** [comment]
I checked with our legal folks and the correct way to do this is to use the current year, not a range.  Happy to take a PR if you want to revert the range.

**Comment by henkmollema** [comment]
Hi @chrisdias, I've updated the PR.

**Comment by henkmollema** [comment]
Rebased

**Comment by chrisdias** [comment]
@joaomoreno this looks ok from my side, can you merge this in?

**Comment by joaomoreno** [comment]
Thanks!

**Comment by henkmollema** [comment]
Cool ☺️

**Pull request merged**
