### PR TITLE
Add confirm for protocol links but allow to opt-out

### LINKED ISSUE #95670: Allow to opt-out of URL protocol confirmation dialog
Is there any way to open files by URL without confirmation?
It starts from 1.44 version and has no "Always open" checkbox.
When you need to open a lot of files with URL its not comfortable to click "Yes" every time.

- VSCode Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Open link "vscode://file/path"
2. See the confirmation dialog "An external application wants to open 'path' in Code. Do you want to open this file or folder?"

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by bpasero**
fixes https://github.com/microsoft/vscode/issues/95670

### CODE REVIEW

**Review by aeschli — DISMISSED** [review]

**Review by sandy081 — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by hrgdavor** [comment]
when will this go live ? I just recently started to use open in vscode for web dev, and opt-out for the prompt will be veeeeery nice.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dantswain** [comment]
After updating insiders I am now getting this dialog every time I cmd+click to open a file from Warp terminal.  It doesn't seem to matter whether or not I click the checkbox.

Before the update I wasn't getting the dialog at all, cmd+click was working exactly as expected.

Happy to report this somewhere else if there's a better spot.

```
Version: 1.84.0-insider (Universal)
Commit: 874831ebcf088f59735879156f62308ce48f17d1
Date: 2023-10-06T19:18:47.163Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

**Comment by bpasero** [comment]
That should not happen so please report a new issue.

**Pull request merged**
