### PR TITLE
#84696 Modify git add/revert to use splitInChunks

### LINKED ISSUE #84696: git spawn ENAMETOOLONG when adding/removing a large directory
Issue Type: <b>Bug</b>

1. Have a repo with a large amount of changed files in one folder and use the tree view
2. Click <kbd>+</kbd> next to the folder to stage the changes or <kbd>-</kbd> to unstage them.
3.:
grafik

This was supposedly fixed in https://github.com/microsoft/vscode/pull/66095 for the discard command but either the other commands or the tree view was forgotten as a potential source of problems.
Clicking the button next to "changes" works fine:
grafik

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.14.2
RunOnSave|eme|0.2.0
prettier-vscode|esb|3.3.5
vscode-test-explorer|hbe|2.14.6
rest-client|hum|0.22.2
vscode-docker|ms-|0.8.2
vscode-language-pack-de|MS-|1.40.2
vscode-jest|Ort|3.0.2
project-snippets|reb|0.5.0
java|red|0.52.0
vscode-coverage-gutters|rya|2.4.2
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4

</details>

### PR DESCRIPTION
**Pull request by jzyrobert**
This PR fixes #84696 

Hi, this is my first time contributing to open source code.

- Modified the add and revert functions to also split the commands across chunks, mainly copying it from the checkout function.
- Modified paths.lengths to paths.length > 0 to be consistent with the previous PR adding chunk splitting. (TS 3.7 would allow for this to be paths?.length)

Is using a limiter necessary for either of the 2 functions?

If the revert command throws an error, is it necessary to deal with any chunks that would have already finished running?

### CODE REVIEW

**Comment by VVKot** [comment]
@joaomoreno Do you mind rerunning checks on this? I wanted to give a hand on this issue and fix tests, but it seems that all of the failing ones are flaky.

**Comment by jzyrobert** [comment]
Should I rebase this onto master again?

**Comment by joaomoreno** [comment]
@jzyrobert No, it's OK.

**Comment by nokternol** [comment]
Can we get this PR resolved? I am using insiders and keep butting up against this issue as I do a lot of architectural refactoring on a big project in vscode.

**Comment by jzyrobert** [comment]
@joaomoreno I've rebased it on top of recent updates, do you have any opinions on this?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
