### PR TITLE
Adopt icon font in lightbulb actions

### PR DESCRIPTION
**Pull request by miguelsolorio**
Related #78889

This adopts the icon font in editor and panel area for lightbulb actions:

image

image

And I also introduced two new color tokens for these, `editor.lightbulbIcon.foreground` and `editor.lightbulbAutoFixIcon.foreground`. When configured will look something like this:

image

image

cc @bpasero @aeschli

### CODE REVIEW

**Review by mjbvz — APPROVED** [review]

**Comment by aeschli** [comment]
@misolori Sorry for being late. I'd like to change the color id's to match the color naming style (2 segments: component.property)

`editorLightBulb.foreground`
`editorLightBulb.autoFixForeground`

Let me know if it's ok for you if I make the rename.

**Comment by misolori** [comment]
@aeschli don’t we need to imply it’s for the icon? The other color names include “icon”.

**Comment by aeschli** [comment]
As all there is an icon, why not just shorten it to 'LightBulp'?

**Comment by misolori** [comment]
I was leaning towards consistency across the other icon colors, but I’m ok shortening it to ‘LightBulb’. Feel free to make the change.

**Pull request merged**
