### PR TITLE
Logging navigible container events for debug

### PR DESCRIPTION
**Pull request by hsfzxjy**
This implements the tracing function mentioned in #200259

### CODE REVIEW

**Review by meganrogge — APPROVED** [review]
Thank you!

**Review by meganrogge — CHANGES_REQUESTED** [review]
I'm seeing `unknown configuration value` for that setting @hsfzxjy 

I also suggest that we should only log when that setting is enabled.

**Comment by hsfzxjy** [comment]
I was not quite familiar with how to register a config item. Could you shed some light on it?

**Comment by hsfzxjy** [comment]
> I also suggest that we should only log when that setting is enabled.

Fair enough. Would change it.

**Comment by meganrogge** [comment]
@hsfzxjy your setting is actually working as expected. we don't want to register the configuration. 

Once you've made the change to only log when that setting is enabled, this is good to go! thanks

**Review by meganrogge — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
