### PR TITLE
Fix DeleteAllLeft when executed from column 1

### LINKED ISSUE #16460: CMD + Backspace while at Col 1 should remove line
- VSCode Version: 1.7.2
- OS Version: macOS 10.12.1

CMD + Backspace at the end of a line properly removes the characters line, leaving the cursor at Col 1. But using the same combo a second time does nothing. You have to release CMD for Backspace to remove the line. You should be able to keep CMD pressed and either remove all the characters in a line, or remove the line itself if the line is empty.

Steps to Reproduce:

1. Starting at the right of a line of characters, use CMD + Backspace to remove the characters.
2. Hit the same combo again, and the line isn't removed.

### PR DESCRIPTION
**Pull request by spalger**
Fixes #16460

The logic is mostly taken from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/cursorDeleteOperations.ts#L132-L138

### CODE REVIEW

**Comment by spalger** [comment]
This change is really small, tested, 6 months old, and really important to me as a user 😢

**Comment by spalger** [comment]
This change is really small, tested, and very meaningful to me 😄

**Comment by rebornix** [comment]
@spalger thanks for your great effort, there are several corner cases, like multi cursor, not handled perfectly. https://github.com/Microsoft/vscode/pull/28392 addresses issue so I merged that pr. Sorry for not merging this one, thanks anyways for your contribution.

**Comment by spalger** [comment]
Fantastic, that works for me! Thanks @rebornix!

**Pull request closed without merging**
