### PR TITLE
Make chs translation more accutrate and comprehensive

### PR DESCRIPTION
**Pull request by hanxiaomax**
There are many mistranslations in chs internationalisation files.This one is only for `commonEditorConfig.i18n.json` and A complete inspection is coming soon.

### CODE REVIEW

**Comment by egamma** [comment]
FYI @johnliu2016

**Comment by dbaeumer** [comment]
@johnliu2016 due to our current translation process we can't accept PRs on translation files. Can you please pipe this back to the translation team so that they can work on this.

**Comment by johnliu2016** [comment]
@lukaschal please incorporate the suggested translation from the PR to following loc file[commonEditorConfig.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcommon%2Fconfig%2FcommonEditorConfig.nls.resx.lcl&version=GBmaster&_a=contents)

**Comment by lukaschal** [comment]
Changes implemented as suggested.

**Pull request closed without merging**
