### PR TITLE
Allow repeated arrow-right expansion of unresolved folders when filtering a tree (#177444)

### LINKED ISSUE #177444: When filtering the Explorer, can't always expand the highlighted directory using the keyboard
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider
- OS Version: Windows 10

Steps to Reproduce:

- Select the Explorer tab and filter it by a file name, `foo.bar`, by clicking CTRL+F and typing the file name, then selecting the filter icon (three horizontal lines). 
- The explorer don't immediately filters out directories that don't contain the required file. To "clean" the list, one could use the keyboard by repeatedly pressing arrow left to expand the directory and arrow down to select the next directory
- Pressing arrow left on a directory that don't contain the required file will remove it from the list. The selection/highlight immediately moves to the next directory in the list. However, if you press again the left arrow nothing happens. 

You can solve the isse above by simply pressing arrow down or up to select another directory and then again use the arrow keys to return to the previous selected directory.

Personally, I would prefer that VSCode would automatically filter out directories that are empty, but I'm guessing this might involve scanning the file system and was avoided for performance reasons.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #177444.

To test, open a folder that contains an unexpanded `node_modules` subfolder. Use Ctrl+F to filter the explorer tree for a contiguous string that doesn't occur in most filenames (for example `.es`). Focus onto the tree (e.g. by pressing ArrowDown after entering the filter string). Navigate to `node-modules`, the hold down ArrowRight to expand folders repeatedly. When filtering hides a fully-resolved folder because it contains no matches, ArrowRight now correctly expands the next folder.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Pinging @lramos15 because though this applies to all trees it is particularly relevant in Explorer and I would like it to be considered for inclusion in 1.78 before endgame starts next week.

**Review by lramos15 — APPROVED** [review]
A bit hacky but appears to work nicely and improve the general experience 👍

**Comment by joaomoreno** [comment]
Definitely hacky.

When debugging, I observe the problem is actually that `getFocus()` is returning the element which was just removed from the tree. We should fix that instead of implementing a workaround for the model being in an inconsistent state.

**Comment by joaomoreno** [comment]
Closing in favor of https://github.com/microsoft/vscode/pull/180704

**Pull request closed without merging**
