### PR TITLE
Fixed issue Misalignment of suggestion details widget (https://github.com/microsoft/monaco-editor/issues/3373)

### LINKED ISSUE #3373: [Bug] Missalignment of suggestion details widget
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

Yes

### Monaco Editor Playground Link
https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#XQAAAAK3CAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxENr3d8FMVJpPoRyBdi9M1_G4fz_GHkPnDw5FYv-hVPgAMoHABKlIQi4n62ngTJKgw_lB7UqM528p93eRQnjoQEYDROpybsGpmMY30rRB_zqBBRr2P8BcL6VoRPcFBP8vuHFMmQBIvpZ30h3mwtJjTJARuemYc_E2vVnPno_tjKO1C3WL07AMeVx1e4tyY0vHYHawRhyPTybHclOE6_I0gd0P4buT5vwdjeILuwtYKNzuShe7SaMw8x8puQGut6HYseICrym1wro7mpFbSu_T7R7skYT0_L5xafyGBsAuSn8HiAro1jsfIADWhKSdC42ENKJ0RCMBGoKlix_DYs2xXKqOfZMPNSKOWDkUdoOGSOAw9DpEL1VvU5JQQTsQQ28nn48G4TeOgy0ynwqZIRhSCi6kmBV__5i2cB1TeOOPKkQ7p6ALq4lNZd4HV5IcDk21AupS28ioiTDEJ01uyY8Fq5vmqPMaq6G4Y-FrsQ4ybeLtEA99N_CK4xpxgDvr9kQpCwcDBvltBUVbAGZK85dLn6D5EpRI2ABqXpfjxTAIqndQ8G_9EQDRogRyG6K_QJVs0_hUjcI6cuBT6I0J3jUfLb9XvQKWnFnNxoWYtFIeyq8ZqXTD7X30dD8HuRQ8sIhGeYCjrYfg_GVCcvRW41fVteuTe2BaMTHlX6afsXEOIZcmMtvBR6BfRfpVrv2U1tNYGcHL6MgU3atV3tFoEuYvOmWyoi74kbRetavf34ZwdUwFV2ataL3RotMX9Bq6WJwNqllg9m-5tABWmz26mxI5IqYZeP4QeKZNSG3lgAsG3Qv-HoeCRDC9-rt_-tqg_0J2xPdLiQeOyXxbVQwgFZ7Gdhj7xnKRzVxleOMDSW4Dg-5k0_zn4oXpYLBYh4jgo85IhcI5eaAcSRgDgenx_d6rw7q6PM_t7Gm5Y3PqwM9oTn4GUruLgY8dU6Nm9zhQ6PPSj0aGYdNqltpgrZTYIe7rWwnkjH9r_nKQei9iyV5DDgqS4qsIvI1cnA9uunHhDnWSgGs6N_NeevwhAi90HmkBErHYEHY4KnjfBozG-RLqT1FM8xxl3sl7vt_KegGw1kiAINzHoA2yJZMM4gb1fCizrNuCl03NTBZGLPCHKQR2kxTknGlUwkUG-PDwrtB91XFIJPCR4P_nDersmN0tThTjpXwd2dKlfjQJxI3_dQEKAA

Thanks @LyqXMU 

### Reproduction Steps

Inside the "dependencies" object type `lodash`.
After the suggestion appears, click on the "Read more" arrow to see the suggestion's documentation.
image

### Actual (Problematic) Behavior

The suggestion details widget is not aligned correctly

image

### Expected Behavior

The suggestion details widget should be aligned below the suggestions widget

image

### Additional Context

image

The root cause of the problems lies in the fact that the suggestion details widget has `fixed` css value for position.
And it assumes that it is positioned relative to the viewport. But this is not always the case (see related issues #2503 and #2793).

Excerpt [from MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed) (emphasis mine) regarding fixed positioning:
> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) established by the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport), **except when one of its ancestors has a transform, perspective, or filter property set to something other than none (see the [CSS Transforms Spec](https://www.w3.org/TR/css-transforms-1/#propdef-transform)), or the [will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) property is set to transform, in which case that ancestor behaves as the containing block**.

So when you have an ancestor element with one of the mentioned properties that forms a containing block, the suggestion details widget gets misaligned.

The problems exists also for the suggestions widget if [fixedOverflowWidgets](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IEditorOptions.html#fixedOverflowWidgets) is enabled (see mentioned related issues). But by default the suggestions widget is absolute positioned. And you can also use the [overflowWidgetsDomNode](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneDiffEditorConstructionOptions.html#overflowWidgetsDomNode) to place the elements outside so that fixed will be relative to the viewport.

You don't have such options for the suggestion details widget.

### PR DESCRIPTION
**Pull request by GenericTSDeveloper**
The offset position of the suggest-widget container is calculated relative to the editor (i.e. position is set as absolute)
On the other hand, the offset position of suggest-detail container is relative to the viewport (i.e. position is set as fixed). 

Per stated in the issue, there are some cases where offset are not properly calculated for the suggest-detail container. If the parent or ancestors of monaco-editor has either transform or perspective style set, then offset position will NOT be relative to the viewport (https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block#4)

One solution is to calculate the offset for the suggest-detail container relative to the editor (and set the position as absolute).

Since the position is set to absolute, (in the editor.css) the `position: relative;` must be removed in order to have suggest-detail-container shown properly (otherwise it will act as if it has low z-index) 

fixes https://github.com/microsoft/monaco-editor/issues/3373

### CODE REVIEW

**Comment by GenericTSDeveloper** [comment]
@microsoft-github-policy-service agree

**Comment by jrieken** [comment]
> Since the position is set to absolute, (in the editor.css) the position: relative; must be removed in order to have suggest-detail-container shown properly (otherwise it will act as if it has low z-index) 

That will cause UI glitches like this one 👇. I'd prefer another solution that less risky

Screenshot 2023-12-13 at 11 59 43

**Comment by jrieken** [comment]
@rebornix Please take a look at this and follow up (either here or separately) for notebooks. This PR changes the suggest details to not be `fixed` but positioned `absolute`. This makes sure details always stick to the suggestions list. For that we introduced editor overlay widgets that are allowed to overflow (this is similar to already existing overflow-allowed content widgets). 

I see that for the latter some notebook/suggest [specific CSS magic is applied](https://github.com/microsoft/vscode/blob/4b6c84ef9c541ccb13bc21d897ee0f41cd6a1bf5/src/vs/workbench/contrib/notebook/browser/media/notebook.css#L23-L46). This won't work for suggest details anymore because they now sit inside a different node but I also couldn't get this to work with similar tweaks 

Screenshot 2023-12-13 at 15 03 11

⬆️ notice how the details overflow the editor but now the editor-overflow doesn't overflow the notebook

**Comment by jrieken** [comment]
@GenericTSDeveloper pushed a few changes on top of yours. Thanks for starting this, I am confident that we will get this merged towards the end of this week

**Comment by rebornix** [comment]
@jrieken  The `absolute` positioned widgets will always run into this issue due to how layering works, it gets cut off at the boundary of the list view. That's also why we intentionally enable `fixedOverflowWidgets` https://github.com/GenericTSDeveloper/vscode/blob/8e3ae234e4b94b0f41eba2807df7afb014691895/src/vs/workbench/contrib/notebook/browser/viewModel/cellEditorOptions.ts#L29-L30 for the cell editors, which ensure all widgets are `fixed`. Can we check this setting and control if the widget should be `fixed` or `absolute`? This way we can have it for normal text editor and still use `fixed` widgets when embedding monaco editor in absolute `div`s.

**Comment by jrieken** [comment]
Thanks @rebornix. I have now pushed support for fixed overflow overlay widgets. This works now for notebooks tool

**Review by jrieken — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]

**Pull request merged**
