### PR TITLE
Add ts/js deprecated support

### PR DESCRIPTION
**Pull request by Kingwl**
This PR fixes #77760

https://github.com/microsoft/TypeScript/pull/38523

### CODE REVIEW

**Comment by Kingwl** [comment]
Work at TypeScript side is complete.
Please take a look. Friendly ping @mjbvz

**Review by mjbvz — APPROVED** [review]
Thanks for this change @Kingwl and for the great work on TypeScript

@jrieken Can you please take a quick look at the changes in VS Code core. They look good to me but I want you to check them since I believe you implemented the deprecated apis

**Review by jrieken — APPROVED** [review]
lgtm

**Comment by Kingwl** [comment]
Thanks for the review!

**Comment by mjbvz** [comment]
Thanks @Kingwl! This will be in the next VS Code insiders build and is scheduled to ship with VS Code 1.47 in early July

**Comment by Kingwl** [comment]
Glad to work on this.
Let me know if something wrong. Thanks!.

**Pull request merged**
