### PR TITLE
shellIntegration-rc.zsh: escape values in "E" (executed command) and "P" (property KV) codes

### PR DESCRIPTION
**Pull request by rwe**
This implements the string escaping scheme documented for the "E" (executed) and "P" (property KV) codes. This is "pure" `zsh` and relies on no external utilities.

Although currently the only "required" escapes are backslash, semicolon, `\a`, and perhaps newlines, this conservatively escapes all non-alphanumeric characters.

Backslashes are doubled, non-alphanumerics are hex-escaped.

Sibling to:
* #165631
* #165632
* #165634
* #165635

Relates to or resolves parts of:
  * #157546
  * #155639

### CODE REVIEW

**Comment by rwe** [comment]
I've opened #165665 re the lint failure on the diagram comment.

The existing "hygiene" script apparently only permits the characters `┌└├` (omitting soft elbows, down-left connectors of any kind, and horizontal/vertical lines) 😑

These could be redone in ASCII, but with loss of legibility.

**Review by Tyriar — DISMISSED** [review]
Works great 👏

**Review by joyceerhl — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by rwe** [comment]
By the way, sorry for stomping on that review with the push! I usually rebase my unreviewed branches in bulk just to keep them current and if I don't notice a review beforehand it'll clober. I'll look into updating my scripts to check for that in the last step, since reviewers also work in batches :) Done with that for now unless other change requests pop up.

**Comment by Tyriar** [comment]
No worries, that's best in my experience and what I do; don't force push after a review has occurred

**Pull request merged**
