### PR TITLE
Add window.nonNativeFullscreen option for macOS

### LINKED ISSUE #5344: Simple fullscreen support
- VSCode Version: 1.0
- OS Version: OS X 10.10

I could be missing this in an option somewhere, but if not, it would be awesome if there was an option for "use_simple_full_screen" (like in Sublime Text) which just full screens VS Code in the current window and not create a new space like it does currently.

### PR DESCRIPTION
**Pull request by ignu**
Now that Electron 2 is merged into master, we can have simpleFullScreen support!

Adds a new configuration option `window.nonNativeFullScreen` (defaulted to `false` to preserve the existing behavior) that, when true, will use `setSimpleFullScreen` and not cause the creation of a new space.

Fixes https://github.com/Microsoft/vscode/issues/5344

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
@ignu this is a great change, thanks for doing it. Looking at the screenshot from iTunes, I wonder if we should flip the setting around to be enabled by default and called `window.nativeFullscreen`

image

I would even literally copy the description they have there below the setting to VSCode to explain when it would make sense to disable that setting.

**Comment by bpasero** [comment]
@ignu one thing I noticed is that Sublime Text no longer seems to advertise this setting because when you enter simple full screen, it is hard to get out of this mode unless you know how you entered it. We could maybe show a message informing the user how to get out of the full screen mode if the native full screen mode is disabled?

**Comment by ignu** [comment]
@bpasero That's a good point. I was thinking the default being a double-negative could be confusing. `nonNativeFullScreen: false` is a bit clunky.

But as much as I dislike Apple's native fullscreen, I'd worry about making "non-native" or "simple" the default. I'm not aware of any macOS app that does that, and it'd change Code's behavior and change it in a way that's not a macOS standard. I'm sure at least a few people would be upset. 

Leaving the default native also prevents the confusion of accidentally getting into `simpleFullScreen`, as you're intentionally opting into it, presumably because you understand and prefer that behavior.

So I'd propose I get rid of the double negative and updating the description text as your proposed.

Maybe make the option and default one of:

1. `simpleFullScreen: false`
2. `useSimpleFullScreen: false`
3. `nativeFullScreen: true`
4. `useNativeFullScreen: true`

**Comment by ignu** [comment]
@bpasero updated.

I didn't completely grab that description as it is since it's a bit out of date. (When native full screen first launched, secondary monitors were completely useless.. they were just blanked out. That's no longer the case, but they're still not ideal since you can't drag windows from them to your natively full-screened app.)

I also prevented the maximize button from going into native fullscreen if `nativeFullscreen==false`.

**Comment by bpasero** [comment]
@ignu changes look good to me, however I am seeing two bugs, that seem to be related to the fullscreen support:
* I am no longer able to quit VSCode when in simple fullscreen. Neither `Cmd+Q` nor the Quit menu entry work, do you see this too?
* Right after I enter simple fullscreen, the window does not seem to have focus anymore, to reproduce, enter simple fullscreen, type `Cmd+Shift+P` to open the command palette and try to type, it does not work. it will only work if you click into the window

**Comment by ignu** [comment]
That's really weird. I think CMD+Q's not working because it's like the entire application doesn't have focus? I'm poking around now.

**Comment by ignu** [comment]
@bpasero I didn't find it in the electron docs, but I found this snippet in an electron nvim gui

https://github.com/igorgladkoborodov/vv/blob/60b513d4c728fe9a6d723d5b1d1808c2ef9ef634/src/renderer/nvim/features/fullScreen.js#L27

I added that to 476a89d and fixed most of the problems

There is a remaining bug... if you try to quit from simpleFullScreen, you're can't quit anymore, not through CMD+Q or even `Code > Quite Visual Studio Code`. 

I think something must be puking trying to serialize, but I'm not totally sure. Still digging in.

**Comment by bpasero** [comment]
@ignu yeah I also thought about adding focus, but I did not try with `webContents`, good catch.

It could be that our very own logic prevents the quit, running with `--verbose` flag I see this in the console:

image

**Comment by ignu** [comment]
Yeah. I'm not fully groking everything `SharedProcess` does yet, and really confused as to why being in `SimpleFullScreen` would change its behavior.

Continued attempts to quit (even when backing out of full-screen) result in 

    [main 2:31:27 PM] windowsService#quit
    [main 2:31:27 PM] Lifecycle#quit()
    [main 2:31:27 PM] Lifecycle#quit() - a pending quit was found

but continued `CMD+W`'s will eventually quit the app.

**Comment by bpasero** [comment]
@ignu turns out this is a known Electron bug, we will have to wait for a fix from them: https://github.com/electron/electron/issues/13135

**Comment by bpasero** [comment]
@ignu I have updated master to Electron 2.0.11 and it looks like the issues are fixed (not being able to quit when in simple fullscreen).

I pushed a couple of cleanup changes to your branch and was about to merge, but then I figured out two things:
* I see the window title visible when in simple fullscreen but would think the title should hide. maybe you could check it out and see if that is desired. to get that experience when running out of sources, change the following: comment out [this line](https://github.com/ignu/vscode/blob/8ecc7a3c898e1a2cb58fff38012601342b6788fb/src/vs/code/electron-main/window.ts#L164) and [this line](https://github.com/ignu/vscode/blob/8ecc7a3c898e1a2cb58fff38012601342b6788fb/src/vs/workbench/electron-browser/workbench.ts#L928)

image

* I see a NPE when switching between fullscreen and not and this seems like a new issue to me:

image

It could be that I did not see this issue before because I never tested running out of sources with the standard custom title behaviour (that needs the 2 changes I mention above).

Can you check?

**Comment by ignu** [comment]
I'll look at that title issue tonight. I just realized it's not consistent with native fullscreen.

I've actually been using my own build of Code with these commits in it for the last month. I like the title there since my workflow (and part of why i hate native fullscreen) is having many projects open, and the title helps me identify which window I've Option-Tabbed to quickly... but it probably should be consistent with the native fullscreen version.

The other bug I have to fix that I've recently noticed is that if my resolution changes due to switching monitors Code is in `simpleFullScreen` but it hasn't actually updated its size to the new resolution.

**Comment by bpasero** [comment]
@ignu ok thanks. any thoughts on the exception in the `layout()` method?

**Comment by bpasero** [comment]
@ignu fyi please see https://github.com/Microsoft/vscode/pull/55267/commits/9667519b858db6076f800590f3d433fb51ba6149 where I fixed the remaining issues. The title now correctly hides when in fullscreen mode and I added a workaround for the NPE in the layout call.

**Comment by bpasero** [comment]
Thanks again 👍

**Pull request merged**
