### PR TITLE
Add Read Only mode

### LINKED ISSUE #4873: Add read-only mode
- VSCode Version: 0.10.11
- OS Version: Fedora 23, 64bit

Details:
- Please add read-only mode and its keyboard shortcut.
- It should be a switch. When turned on, opening new files will be in read-only mode.
- It should be persistent across restarts.

This feature should be very useful for code reviewing. And I think it's not hard to implement.

Thank you,

### PR DESCRIPTION
**Pull request by jmannanc**
This PR fixes https://github.com/microsoft/vscode/issues/4873

SXETcQ7wgj

I attempted to follow the feedback outlined on the previous PR for this feature request: https://github.com/microsoft/vscode/pull/82748. If I missed something, please let me know and I'd be happy to change it.

### CODE REVIEW

**Comment by bpasero** [comment]
Thanks but I think this requires a different approach and I would not think that we would accept a PR to resolve this unless we can lay out exactly how this feature should work.

**Comment by henrik-jensen** [comment]
@bpasero - Come on. This have been a request of the community for a very, very, very, very long time. Please be a bit more cooperative. What kind of "different approach"/(gauntlet)  do you require for this to go through?

**Comment by bpasero** [comment]
@henrik-jensen well to begin with, this PR seems to turn the current active text editor readonly and as such if you open keybindings or settings in the editor, you cannot make changes either. I think if we want to add a feature like this, shouldn't it reset if a different file is opened?

**Comment by henrik-jensen** [comment]
@bpasero Thank you, that's the kind of response I was hoping for.
So is this a inherent design flaw of the original monaco editor (You are the expert on original Monaco)?
If so, do you have some ideas how we can mitigate this stupid design flaw? (Global solution to a local problem does not seem to work, (no surprise)).
(In other words) What can be done?

**Comment by bpasero** [comment]
Sure, I am happy to give all the answers once we decided that we want to tackle that issue. But since that issue does not have our "help wanted" flag, please understand that I am currently not having the time to explain a general solution. Rather I feel that this issue should be looked at by a developer from us and not by outside contribution.

**Comment by henrik-jensen** [comment]
Ok, that's fair enough. (But as a representative of the WNROMP (We Need Read Only Mode Party) I can assure you that haven't heard the last from us :-) )

**Comment by bpasero** [comment]
👍

**Pull request closed without merging**
