### PR TITLE
Fixed issue -filtering by extension in Change Language Mode

### LINKED ISSUE #106886: Change Language Mode drop-down should allow filtering by file extension
In the [Change Language Mode drop-down](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file), it would be nice if we could filter by extension. e.g. at the moment for a `.jsx` file, typing `jsx` returns nothing. I have to start typing `javascriptreact`:

select-language-type-vscode

For TypeScript, `ts` gives you:

select-language-type-vscode-ts

Which doesn't seem intuitive. I'd expected the same results, but taking the extension into account and ordering them:

```
TypeScript > TypeScript React > JSON with Comments > CSS (Styled Components
```

### PR DESCRIPTION
**Pull request by myovan**
This PR fixes #106886

Adding file extensions to a language's description allows a user to filter for a specific extension name (e.g. `jsx` will return `JavaScript React`)

ezgif com-gif-maker (1)

Was looking at #107939 and saw that the preferred implementation was to add meta data to quick pick list (metadata would be searchable but would not appear in the UI). Took @bpasero code pointers into account. Now users can search by extension, and results are filtered, without the extensions cluttering the results.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Thanks, this is almost what I had in mind. I think we can safely remove `metaHighlights` since we don't use it anywhere for rendering. The only important piece is to set the item to visible in [here](https://github.com/microsoft/vscode/blob/f5da8e346fcf7c4820c85da1f9e253360c7699a4/src/vs/base/parts/quickinput/browser/quickInputList.ts#L606), but otherwise we do not need to remember the highlights on the item imho.

**Comment by bpasero** [comment]
@chrmarti adding your for review since the changes in quick pick touch your area, let me know what you think. The gist is to have a way to associate meta information with a quick pick item that is searchable but not displayed to the user.

**Comment by bpasero** [comment]
Thanks!

**Comment by chrmarti** [comment]
LGTM, thanks!

**Pull request merged**
