### PR TITLE
Fixes #944 - Support wildcards on activationEvents.workspaceContains

### LINKED ISSUE #944: Wildcards on activationEvents.workspaceContains?
Is there a way to use wildcards in `activationEvents.workspaceContains`? i mean, could i do something like:

```
"activationEvents": [    
    "workspaceContains:*.config"
  ],
```

### PR DESCRIPTION
**Pull request by eamodio**
Here is a first pass at this -- I don't really like checking for wildcard/glob characters but it works as is and should be easy enough to change that part if the rest looks reasonable.

### CODE REVIEW

**Comment by eamodio** [comment]
@alexandrudima I'm not sure why the builds are failing with these changes -- it builds locally. And looking at the travis one, I don't even see any failures. Any ideas?

**Comment by eamodio** [comment]
Apparently it just needed a kick

**Comment by eamodio** [comment]
Any chance this could be looked at in the May iteration? I know the C# extension is really hoping to get this in.

**Comment by eamodio** [comment]
@alexandrudima sorry to bother you, but any feedback on this?

**Comment by alexandrudima** [comment]
@eamodio Thank you for your contribution! :heart:

@chrmarti @roblourens @jrieken fyi

**Comment by eamodio** [comment]
@alexandrudima awesome! thank you!

**Comment by jens1o** [comment]
Thanks, very cool!

**Comment by roblourens** [comment]
Future improvement: This will run until the entire workspace has been searched, even if it finds a match immediately. You could use the progress callback on `search` to complete immediately once a match is found.

**Comment by eamodio** [comment]
@roblourens doesn't this https://github.com/Microsoft/vscode/pull/24570/files#diff-7799696b0b4988cc737acff368fad1b1R140 make it return after the first match?

**Comment by roblourens** [comment]
Oh right, yes :)

**Pull request merged**
