### PR TITLE
remove panel location options in favor of new side panel behavior

### PR DESCRIPTION
**Pull request by sbatten**
This PR removes the old concept of moving the panel part in favor of a simpler model of moving view/containers into the new side panel. It "deprecates old commands" by redirecting them to the new commands to ease the transition though we know usage is already quite low of this deprecated feature.

### CODE REVIEW

**Comment by samestep** [comment]
In case anyone else stumbles upon this like I did today, here are the steps to move the terminal to the side using the new system:

- open the terminal
- run the command **View: Focus into Side Panel**
- drag the "Terminal" tab into the side panel

**Comment by sbatten** [comment]
@samestep thanks 

alternatively, if you want all the traditional panels (terminal, output, debug, problems) on the side panel, you can right click the panel and choose **Move Views to Side Panel**

**Comment by samestep** [comment]
@sbatten Ahh that's what I was looking for; thanks!

**Comment by lukecotter** [comment]
Is there a way to have that side panel on the right?

**Comment by sbatten** [comment]
@lukecotter the behavior of the side panel is that it remains opposite of the side bar. Toggling the side bar position will move the side panel as well. `F1` > `Toggle Side Bar Position`. It is not possible to stack the side panel and side bar horizontally anymore.

**Comment by lukecotter** [comment]
That's a shame. I used to like having the panel and side bar next to each other with the code pushed all the way left.

**Comment by sbatten** [comment]
feedback noted. if your primary use case of the panel is terminal, perhaps [terminal editors](https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area) are a valid solution for you

**Comment by dpooleffdc** [comment]
A small issue with"Move Views to Side Panel" is the ability toggle the terminal.

When the terminal is in its default location underneath the editor you can press ctrl + ` to toggle it, if you move this to the side panel that keyboard shortcut no longer works. I have noticed there is a command to "Toggle Side Panel" which I can rebind and will achieve the same result just a shame the Toggle terminal command does not work the same in the different locations.

**Comment by happyteque** [comment]
> That's a shame. I used to like having the panel and side bar next to each other with the code pushed all the way left.

So @sbatten let me get this right - you have "improved" the code by removing functionality that a lot of users (including me) were happy with? For ... reasons? Thanks 🙄 

Sometimes I wish MS could just leave the thing alone, I am happy with the way it works, why constantly "enhance" it and confuse your users... we got work to do. I guess I'll now go and spend a couple of hours of my time reading up on what the shiny new "Side Panel" behaviour and "Terminal Editors" are... 😡

**Comment by happyteque** [comment]
Also, with Terminal Editors, the `workbench.action.terminal.focus` which was burned into my muscle memory cannot be used anymore. Is there an equivalent for Terminal Editors?

**Comment by sbatten** [comment]
@dpooleffdc I have just made a change to fix this behaviour. It will be available in tomorrow's insiders.

**Comment by cognominal** [comment]
What is the purpose of the side panel ? I can't see any documentation about it. I understand one drags views into it. But I don't know what are views in this context.

**Comment by dpooleffdc** [comment]
> @dpooleffdc I have just made a change to fix this behaviour. It will be available in tomorrow's insiders.

Thank you @sbatten that is very much appreciated!

**Comment by sbatten** [comment]
@cognominal the side panel is a new location to drop views analogous to the side bar and panel that already exist today. It lacks documentation since it is yet to be released into stable. however that should change soon. views are the things inside of the side bar and panel, e.g. timeline view, outline view, terminal, etc.

**Comment by cognominal** [comment]
@sbatten All this easy shuffling around of views is very nice, once one get the hang of it.
Is this going eventually in the direction of supporting different layouts for different usages or different modes within the same workspace, including possibly having closed editor groups, invisible but still there ?
Speaking of mode, I am thinking of screen casting (as opposed to live sharing) which means choosing setting screen in low resolution mode and adopting in conséquence different layouts.

**Comment by sbatten** [comment]
@cognominal thanks for the feedback! I believe this issue would be a good place to share your thoughts and express your desire for the feature https://github.com/microsoft/vscode/issues/138263

**Pull request merged**
