### PR TITLE
Allow to open files as preview from the command line (--preview)

### PR DESCRIPTION
**Pull request by gzzhanghao**
It makes it easier to implement devtools in [this video](https://drive.google.com/open?id=1rGeFiNLezxzaJqnhnDbjvD_OvLMyaMIh). (from https://github.com/vuejs/vue/issues/8034)

### CODE REVIEW

**Comment by bpasero** [comment]
@gzzhanghao out of curiosity, that IDE in the development tools looks a bit like VS Code, what is it? And how would this change have any impact on that IDE of the video?

**Comment by gzzhanghao** [comment]
@bpasero that video is from @NeekSandhu, I'm not sure what it is.

I'm just trying to implement something like that but with vscode as the main editor. It could be done with a WebSocket server that opens local editor with command line. That's why I need the preview option here.

**Comment by NeekSandhu** [comment]
I'm glad to see it featured/referred here. It's a [Chrome DevTools extension](https://developer.chrome.com/extensions/devtools) I am working on. In a nutshell, it's basically a cross between vscode and devtool's workspace, bringing best of both worlds in one place.

While I have you guys here, let me know what you guys think of it (thoughts on usefulness, general feedback, etc.)

PS: I'm also looking for collaborators/contributors if you or anyone you know shares the same vision. Please hit me up.

**Comment by gzzhanghao** [comment]
I found that we can open vscode with URLs. So I wonder if we can extend the URL query to pass external options to it. eg: `vscode://file/c:/myProject/package.json:5:10?preview&preserveFocus`. We can implement the devtool without a local server if that's possible.

**Comment by bpasero** [comment]
I find it hard to argue to have this option, closing.

**Pull request closed without merging**
