### PR TITLE
Add an option to hide/show menu bar.

### LINKED ISSUE #945: There should be an option to hide the menu bar.

### PR DESCRIPTION
**Pull request by rstat1**
Adding a menu item to the view menu that allows you hide/show the menu bar. If the menu bar is hidden you toggle it on and off with the "Alt" key.

Fixes #945

### CODE REVIEW

**Comment by be5invis** [comment]
Wow that's exactly what I need.

**Comment by rstat1** [comment]
@be5invis Not bad for someone who's never written Typescript before eh?

**Comment by be5invis** [comment]
@rstat1 yeah.

**Comment by bpasero** [comment]
Thanks! But can you not rather use the setAutoHideMenuBar() [1] method instead and avoid having to implement the key listener for Alt? Also, please check if this solution is cross platform, it does not seem to work on Mac and thus should not show up there.

[1] https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetautohidemenubarhide

**Comment by rstat1** [comment]
@bpasero `setAutoHideMenuBar` gets me a `Property is undefined` error because `BrowserWindow` doesn't have it defined. Is that something I can just go and add, or is the file it's in (atom-browser.d.ts) generated from something?

As far as mac compatibility, it was something I was going to do, and for w/e reason forgot, my mistake.

**Comment by bpasero** [comment]
@rstat1 yes feel free to add it to the d.ts files if missing!

**Comment by rstat1** [comment]
@bpasero Oh well ok, that simplifies things quite a bit. I'll fix everything up and have a new request ready shortly.

**Comment by rstat1** [comment]
@bpasero Ok. Done. Menu item disappears on mac, and everything uses the official Electron APIs now instead of my custom stuff.

**Comment by bpasero** [comment]
@rstat1 nice. I wonder if this should not rather be a setting in the user settings configuration? We typically try to put settings into there instead of overloading the menu. I would think of a window.setting that controls this behavior. Otherwise, how do you persist this setting?

**Comment by rstat1** [comment]
@bpasero There's already items within the "View" menu for toggling other things like the sidebar and full screen mode, so I think it'd make sense to have the menu bar toggle there as well.. With the way settings are currently done in VS Code I don't think that'd be the best place for it. 

As far as persisting the toggle across sessions I'd agree with you on that part.

**Comment by bpasero** [comment]
@rstat1 right, those things are being persisted though (except for fullscreen, but that is for other reasons). We have 2 stories for persisting state: Either in the settings.json which is owned by the user or in local storage which is more for UI state. I think this should probably go into the local storage category as long as there is a menu item to toggle it.

**Comment by rstat1** [comment]
@bpasero Local storage it is then!

**Comment by rstat1** [comment]
@bpasero  Ok, so I added the ability to save whether the menu bar is auto hidden or not. Not sure if I've done everything in the right places.

Also there appears to be merge conflicts that I (being a git/github noob) have no idea how to resolve.

**Comment by bpasero** [comment]
@rstat1 from your branch you can update the pull request easily by merging in the changes from master. 
* git remote add upstream https://github.com/Microsoft/vscode.git
* git pull upstream master
* fix conflicts
* git push

**Comment by rstat1** [comment]
@bpasero aha! It worked! Thanks :)

**Comment by bpasero** [comment]
This landed in similar fashion, please see https://github.com/Microsoft/vscode/commit/c34d2e771bb3e372e912e081a8bd8879a92a8c91

**Comment by ssaras** [comment]
For the most part, this also works on Linux Mint 17.1 albeit a bit glitchy.

**Pull request closed without merging**
