### PR TITLE
Remove `#` from typescript language features deprecation warnings

### PR DESCRIPTION
**Pull request by wahidshafique**
Remove tags to match standard deprecation warnings, such as in:https://github.com/microsoft/vscode/blob/dceba9ebb78e4c3a5be2bea0ca5f23dde7a21b75/extensions/html-language-features/package.nls.json#L32

### CODE REVIEW

**Comment by mjbvz** [comment]
@roblourens Looks like settings links aren't supported in our json settings editor: 

Screen Shot 2021-01-22 at 12 01 09 PM

**Comment by roblourens** [comment]
Indeed, I don't think I can customize this just for one json file without changing it for other json files.

**Comment by mjbvz** [comment]
Ok, thanks @roblourens. Let's just remove the `#` then since the `#` shows up in both the hovers and in the problems view, and removing the link is not a large regression

**Comment by roblourens** [comment]
Wouldn't have worked with `js/ts` anyway

**Pull request merged**
