### PR TITLE
Provide more specific file type descriptions on macOS

### PR DESCRIPTION
**Pull request by NSExceptional**
## Motivation and Summary of Changes

Right now, VS Code defines the file type description for every file association it creates as "VS Code document", which is not very useful. The file type description is what appears in the Info pane for a file in Finder:

Info pane, PDF document

This PR aims to 1) make it possible to specify specific names at all, and 2) to provide some default names for most of the existing supported file types.

My commit messages and code documentation have more detailed information on the approach I took to this.

Oh, also, I could not for the life of me figure out how to get these changes to build. I ran `yarn compile` inside `build/` and it built the `*.js` files, but could not get the results published in the final product. If someone can tell me how to do that, I will test it on my machine to ensure it works as expected.

## PR Checklist

- [ ] There is no issue associated with this PR, because I just started on a PR first instead of making an issue.
    Do I need to create an issue anyway?

- [ ] I have read through the [coding guidelines]() and I think the only guideline I may be breaking is this one:
    > _Do not introduce new types or values to the global namespace_

    However, I'm not sure where to put the two new types I declared. I need some direction here if my PR cannot be merged because of this.

### CODE REVIEW

**Comment by NSExceptional** [comment]
Fixed the build errors, but still haven't actually been able to test it

**Comment by joaomoreno** [comment]
> ## PR Checklist
> * [ ]  There is no issue associated with this PR, because I just started on a PR first instead of making an issue.
>   Do I need to create an issue anyway?

Yeah let's create one.

> * [ ]  I have read through the coding guidelines and I think the only guideline I may be breaking is this one:
>   > _Do not introduce new types or values to the global namespace_
>   
>   
>   However, I'm not sure where to put the two new types I declared. I need some direction here if my PR cannot be merged because of this.

You're good here, no worries. 👌

> Oh, also, I could not for the life of me figure out how to get these changes to build. I ran `yarn compile` inside `build/` and it built the `*.js` files, but could not get the results published in the final product. If someone can tell me how to do that, I will test it on my machine to ensure it works as expected.

You'll be able to build an OSS version of VS Code with `yarn gulp vscode-darwin`, let me know how that goes.

**Comment by joaomoreno** [comment]
@NSExceptional I'll set the PR to draft until you've tested and we're ready for a review.

**Comment by NSExceptional** [comment]
@joaomoreno No dice, it builds without errors then fails to run :/

Screenshot 2021-03-01 at 1 44 18 PM
Screenshot 2021-03-01 at 1 44 51 PM

Is it possible I messed something up while snooping around in the OSS build folder? I tried `yarn cache clean` hoping that would blow away any build artifacts but I'm not sure if it does that

**Comment by joaomoreno** [comment]
Try `rm -r .build`, that will clean the local electron build, so it feches a new one.

**Comment by NSExceptional** [comment]
That did the trick. It worked! Here's the generated [Info.plist](https://github.com/microsoft/vscode/files/6070361/Info.txt)

Screenshot 2021-03-02 at 10 59 38 AM

**Comment by NSExceptional** [comment]
Noticed there were no associated file extensions in my screenshot 🤪 Fixed; I was indexing the object improperly in `darwinBundleDocumentTypes`:

```ts
function darwinBundleDocumentTypes(types: { [name: string]: string | string[] }, … {
    return Object.keys(types).map((name: string, idx: number): DarwinDocumentType => {
        const extensions = types[idx]; // <-- using idx by mistake
        ...
```

→

```ts
function darwinBundleDocumentTypes(types: { [name: string]: string | string[] }, … {
    return Object.keys(types).map((name: string): DarwinDocumentType => {
        const extensions = types[name]; // <-- use name instead
        ...
```

**Comment by NSExceptional** [comment]
Tests are now failing because of `src/vs/workbench/test/browser/api/extHostBulkEdits.test.ts` passing an extra argument to a function, but I didn't touch that file or any related files? 😟

**Comment by NSExceptional** [comment]
@joaomoreno Do you know what's going on?

**Comment by joaomoreno** [comment]
Just merge `main` into your branch and let's see if CI gets over that hump.

**Comment by NSExceptional** [comment]
No wonder, I was rebasing on my local `main` which was tracking my fork, not upstream 🤦🏻‍♂️

**Comment by NSExceptional** [comment]
@joaomoreno All checks passed!

**Comment by NSExceptional** [comment]
@joaomoreno does this have any blockers?

**Review by tymsai — APPROVED** [review]

**Comment by NSExceptional** [comment]
@joaomoreno will this be put into the May milestone?

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
