### PR TITLE
Fix unwanted extra spaces when pasting code with JSDoc

### LINKED ISSUE #119225: Pasting into code line below a jsdoc block comment auto-indents by one space character
- VS Code Version: 1.54.3
- OS Version: Win 10

Steps to Reproduce:

1. Have the following code snippet in a JS editor
```js
/**
 * doc
 */
x = 1;
```
2. copy a word to clipboard, e.g. "var"
3. place cursor before "x", paste

Result: The pasted word indents the line by one space. This should not happen below such a jsdoc comment block.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by ssigwart**
This PR fixes #119225. It prevents an extra space from being inserted after JavaDoc style comments.

To test, you can paste something like this into a typescript file.
```typescript
/**
 * Function
 */
public func1(): number
{
	return 1;
}
```

I also added a test that can be run with:
```bash
./scripts/test.sh --glob **/indentation.test.js --grep=119225
```

### CODE REVIEW

**Comment by ssigwart** [comment]
I realized the unit test didn't actually work properly, so I re-wrote it and update the comment above with how to run it.

**Comment by ssigwart** [comment]
When someone does review this, I just wanted to point out that reviewing with ignored whitespace will make it easier.

**Comment by ssigwart** [comment]
I rebased this to fix merge conflicts.  It is ready for review.

**Comment by jespertheend** [comment]
🥲

**Comment by ssigwart** [comment]
I fixed the merge conflicts again.  Hopefully this can get reviewed soon.

**Review by gene-pavlovsky — APPROVED** [review]

**Comment by otacke** [comment]
@hediet @sandy081 Sorry if I am disturbing you. I just picked you, because you seem to be committing a lot, even though you may not been responsible.

This pull request seems to be a fix for a bug https://github.com/microsoft/vscode/issues/119225 which is very annoying. The pull request has been open and actively maintained for over a year. Could you please give any insight into your working process in order to shed some light onto when the bug might eventually be fixed? Is there anything I could do to contribute?

**Comment by hediet** [comment]
What happens with this PR, when you paste this:
```
/**
 * Function
 */
public func1(): number
{
	return 1;
}
```

into a class that already has some indentation?
Does the pasted code get indented correctly?

**Comment by otacke** [comment]
@hediet 
> What happens with this PR, when you paste this:
> 
> ```
> /**
>  * Function
>  */
> public func1(): number
> {
> 	return 1;
> }
> ```
> 
> into a class that already has some indentation? Does the pasted code get indented correctly?

Is this a general question or addressing me? In the latter case, I need to amend my previous comment about the information that I have not built a version of VScode with the PR merged in and therefore deliberately wrote "pull-request seems to be a fix". I am confident, however, that @ssigwart would answer the question given that he contributed the code.

**Comment by ssigwart** [comment]
Thanks for responding, @hediet!

The bug is that when you paste the code you quoted in a JavaScript file, it shows up like this:
```javascript
/**
 * Function
 */
 public func1(): number
 {
	 return 1;
 }
```

Notice the extra spaces in front of "public" and the lines below it.

With this PR, it gets pastes without adding the spaces. I think you are might be asking specifically if it will still function properly if you try to paste it where you expect an extra tab in front of every line. It's been a long time since I wrote this, but I'm fairly certain that works too. I can try to verify that tonight when I get back onto the computer I wrote this patch on.

**Comment by ssigwart** [comment]
@hediet, I tested my branch. If there's existing indentation, it behaves the same way as before this change, so it seems good to me for this branch. It looks like the bug with the extra spaces only happens when there's no indentation and that's what this PR fixes.

**Comment by jespertheend** [comment]
Fwiw I'm also seeing an extra space when there is already an indentation, and if the line being pasted at is already indented formatting gets even more broken.

To be clear, this recording was made in the latest stable version of vscode that does not contain the fix of this PR yet.

https://user-images.githubusercontent.com/2737650/202429699-dd5f7e60-1c08-48cd-84fb-42956a27f9e0.mp4

**Comment by ssigwart** [comment]
@jespertheend, thanks for the recording. I'm not seeing the same behavior on the stable version of VS Code.  Maybe it's different settings.

Can you include two things so I can test it better?
1. The exact raw JS that you start with.
2. The exact raw JS that's in your clipboard. In particular, I'm curious if the text in the clipboard has tabs already or not.

**Comment by jespertheend** [comment]
Ah and my clipboard contains this (encoded as javascript string)
```js
'    /**\n     * @param {number} x \n     * @param {string} y \n     */\n    bar(x, y) {\n\n    }\n'
```

**Comment by ssigwart** [comment]
Thanks, @jespertheend. I tested with my branch and it does solve that as well.

**Review by hediet — APPROVED** [review]

**Review by joaomoreno — APPROVED** [review]

**Comment by otacke** [comment]
@hediet Thanks a lot for reacting to my request to have a look at this pull request! And some extra thanks for doing it so quickly. I really appreciate that.

**Comment by jespertheend** [comment]
I've been waiting for this moment for so long :smiling_face_with_tear:

**Comment by ssigwart** [comment]
Thank you so much, @hediet and @joaomoreno.

What is the proper way to get attention on PRs?  I [have several](https://github.com/microsoft/vscode/pulls/ssigwart) that are over a year old where I haven't heard any feedback. In particular, there are 3 about code formatting (#136572, #136577, #136593) that would fix some annoying issues that I and I'm guessing others deal with daily.

**Comment by hediet** [comment]
I can try to look at some of them some time.
Please ping me in the formatting-related PR that you would like to have the most.

**Pull request merged**
