### PR TITLE
Add lightbulb widget telemetry

### LINKED ISSUE #200629: Add telemetry to when the code action lightbulb is shown
If we could log events for when the lightbulb widget is shown to users and which kind of code actions it contains, we could get valuable insight on its usage. This is especially important now with AI code actions. With this kind of telemetry, we could monitor if displaying the lightbulb with a different icon for AI code actions increase or decrease click rate.

### PR DESCRIPTION
**Pull request by abner-math**
Fixes #200629

### CODE REVIEW

**Comment by abner-math** [comment]
> @abner-math please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Google"]

**Comment by abner-math** [comment]
@microsoft-github-policy-service agree company="Google"

**Comment by abner-math** [comment]
@microsoft-github-policy-service agree company="Google"

**Comment by mjbvz** [comment]
Closing this based on my comment in [200629](https://github.com/microsoft/vscode/issues/200629)

**Pull request closed without merging**
