### PR TITLE
ESM support for VSCode and extensions

### LINKED ISSUE #130367: Enable consuming of ES modules in extensions
When developing extensions and using either JavaScript or TypeScript we are unable to consume ES modules, only somewhat legacy CommonJS modules, setting the `type` to `module` and rewriting the extension to use `import` instead of `require` breaks the extension, generating an exception that states that all modules should use `import` instead of `require` in internal VS Code JavaScript files, I conclude it's caused by the `type: module` that forces Node to treat all `.js` files as ES modules. Tried using TypeScript which transpiles its own syntax to CommonJS module - so that's a no, I have also tried using just `.mjs` extension, again the same issue.

What is the status of this issue and are there plans to enable using of ES modules in extension development? That (could) bring somewhat big performance gains when bundling extensions with, for example, [`esbuild`](https://github.com/evanw/esbuild) because it would enable tree-shaking - dead code removal, thus loading only necessary code. But I think this is not an extension API only issue, right? This needs to be done for VS Code itself?

### LINKED ISSUE #160416: Explore AMD to ESM migration
The VS Code project uses AMD (asynchronous module definition) which is somewhat of a pre-runner of native JS modules (ESM). AMD is mostly dead technology and we should migrate away from it. Our TypeScript sources are written with ESM imports/exports but we took a few dependencies on AMD as a "runtime" and we need to understand what it takes to move towards ESM. 

High-level topics:

* we have a special AMD loader plugin that supports nls
* we also have a special plugin for CSS
* we have special bundle logic for both NLS and CSS dependencies
* we use `require.toUrl` to locate sibling resources, like images, this needs to migrate onto `import.meta.url`

Backlog Plan: https://github.com/microsoft/vscode/issues/160416#issuecomment-2269225658

Test Builds that run on ESM:

```
VS Code Build: 7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d

darwin: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/VSCode-darwin.zip
darwin-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/VSCode-darwin-arm64.zip
darwin-universal: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/VSCode-darwin-universal.zip
linux-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration-arm64-1723616523.tar.gz
linux-deb-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration_1.93.0-1723616603_arm64.deb
linux-deb-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration_1.93.0-1723617891_amd64.deb
linux-rpm-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration-1.93.0-1723616690.el8.aarch64.rpm
linux-rpm-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration-1.93.0-1723617981.el8.x86_64.rpm
linux-snap-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration-x64-1723619959.snap
linux-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/code-exploration-x64-1723616784.tar.gz
win32-arm64-user: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/VSCodeUserSetup-arm64-1.93.0-exploration.exe
win32-x64-user: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/7c7401b2553c7188f1a634b5264fc3a6d3cb1e7d/VSCodeUserSetup-x64-1.93.0-exploration.exe
```

### PR DESCRIPTION
**Pull request by SimonSiefke**
This PR adds ESM support for VSCode and extensions.  Fixes #160416. Fixes #130367

## Try Out

```sh
git clone git@github.com:SimonSiefke/vscode.git &&
cd vscode &&
git checkout simon/esm &&
yarn &&
yarn compile &&
./scripts/code.sh
```

A sample ESM extension is  located at `extensions/hello-esm`. Running the command `hello esm` displays a hello world notification:

esm-extension

## Feedback / Next Steps

It is probably too large to review and would be good to split up into smaller PRs! Before continuing it seems it would be good to gather some feedback from the VSCode team! 

---

### Type Imports

Some imports are changed from `import { IDisposable } from 'vs/base/common/lifecycle';` to `import type { IDisposable } from 'vs/base/common/lifecycle';` to work with ESM.

### Assert imports

Most of the changes in this PR are due to the `assert` import. In ESM, when using `import * as assert from 'assert'` , `assert` cannot be a function. The change is `import assert from 'assert'`

### Xterm imports

`import { Terminal } from '@xterm/headless'` 

 is changed to

```js
import xtermHeadless from '@xterm/headless';

const { Terminal } = xtermHeadless;
```

This makes the import work in ESM. It seems it could even be changed back when `@xterm/headless` is published as ESM.

### Css Imports

`import 'vs/css!./actionbar'` is compiled into `importCss('./actionbar.css', import.meta.url)`. The `importCss` function uses `document.createElement('link')` to create a stylesheet for `actionbar.css`.
`
### AmdX Loader

The amdx loader is changed from loading scripts with `document.createElement('script');` or `importScripts` to load scripts using `import`.

### ESM extensions

To support ESM extensions, the extension host is started with a custom loader `NODE_OPTIONS: `--import="vscode/src/extension-loader-register.js"`. 

The loader can change how ESM files are imported, so that `import vscode from "vscode"` works as expected:

```js
// extension-loader.js
export async function resolve(specifier, context, nextResolve) {
	if (specifier === "vscode") {
		return {
			shortCircuit: true,
			format: "module",
			url: new URL("./fake-vscode.js", import.meta.url).toString(),
		};
	}
	return nextResolve(specifier, context);
}

export function load(url, context, nextLoad) {
	return nextLoad(url);
}
```

When importing `vscode`, this `fake-vscode.js` file is imported instead:

```js
// fake-vscode.js
const api = globalThis.vscodeFakeApi
if (!api) {
	throw new Error('vscode api not available')
}

const { window, commands } = api

export { window, commands }
```

`vscodeFakeApi` is created by `extensionApiFactory()` and provides the vscode api properties `window`, `commands` and more.

NodeJS Docs for module customization hooks: https://nodejs.org/api/module.html#customization-hooks

### Tests

To support ESM for electron integration tests, import maps and preload require are used. 

```html
<script type="importmap">
	{
		"imports": {
			"fs": "./import-map/fs.js"
		}
	}
</script>
```

```js
// preload.js
window.testGlobalRequire = require // expose require function for tests
```

```js
// import-map/fs.js

const fs = window.testGlobalRequire('testGlobalRequire')

const { createWriteStream, existsSync, readFileSync, readdirSync, rmSync, writeFileSync, unwatchFile, watchFile, watch, readFile, mkdir, chmod, link, unlink, truncate, copyFile, read, access, open, rm, readdir, writeFile, constants, stat, mkdirSync, unlinkSync, fdatasync, statSync, accessSync, symlinkSync, openSync, createReadStream, realpathSync, lstatSync, promises, lstat, fdatasyncSync, closeSync, utimes, appendFile, close, symlink, readlink, rmdir, write, renameSync, rename, realpath } = fs;

export { createWriteStream, existsSync, readFileSync, readdirSync, rmSync, writeFileSync, unwatchFile, watchFile, watch, readFile, mkdir, chmod, link, unlink, truncate, copyFile, read, access, open, rm, readdir, writeFile, constants, stat, mkdirSync, unlinkSync, fdatasync, statSync, accessSync, symlinkSync, openSync, createReadStream, realpathSync, lstatSync, promises, lstat, fdatasyncSync, closeSync, utimes, appendFile, close, symlink, readlink, rmdir, write, renameSync, rename, realpath };
```

It's a lot of changes for every imported module (`assert`, `child_process`, `cookie`, `crypto`, `electron`, `events`, `fs`, `graceful-fs`, `istanbul-lib-coverage`, `istanbul-lib-instrument` and more) but it makes the tests work with ESM.

### No ESM support for web extensions yet

Making use of NodeJS loader hooks, the ESM support only applies to NodeJS extensions. There would be no ESM support for web extensions yet.

### CODE REVIEW

**Comment by jrieken** [comment]
Thanks for this huge effort! 

Haven't had the chance to drill into code-details yet but based on your description it seems that you have found the right places and are making good decisions. In the [alex/esm](https://github.com/microsoft/vscode/tree/alex/esm) branch we do some things similar and some different. You have also covered extensions (which we haven't) and that's something I would like to learn from you. 

How to continue is a very good question. Reviewing such a huge, cross-cutting PR is a big challenge for us. Also https://github.com/microsoft/vscode/pull/166033/ exists. It hasn't gotten much attention but our effort is not abandoned. For instance, this milestone we are looking into decoupling NLS from module-loading (https://github.com/microsoft/vscode/issues/212542). That's one of the big remaining items of the [todo-list](https://github.com/microsoft/vscode/pull/166033#issue-1444380230) and also outlines our strategy: whenever possible we try to make changes in `main` so that the ESM PR stays small and has less chance of conflict. E.g that's why amdX exists - it  is an (incomplete) AMD-loader that can be used for things like xterm that aren't ESM yet. 

So, that would be my general recommendation (sorry, without having looked into details yet): 

* let's try to find things that can be done in `main` 
* let's find things that can be done in `alex/esm`

I don't wanna make false promises but I have the slight hope that the NLS-work and me finishing some AI-APIs frees me up next month to get back into this. From the top of my head, there is left

* merge main 🙈 
* electron now supports ESM and we can remove/adjust our workaround
* extensions: nodejs and web with real API instances. My hope and gut-feeling is that imports maps can be helpful for this.
* (... things I will remember once back into it...)

Thanks and Happy Coding

**Comment by SimonSiefke** [comment]
@jrieken  Thanks for the great feedback! 

I very much agree it would be useful to merge smaller/more focused ESM related PR's into `main`. 

One small change towards ESM could be typescript `isolatedModules`: More details in #212835

 I am also looking forward to the NLS work! Thanks!

**Comment by SimonSiefke** [comment]
> We are heavy users and fans on const enum which makes isolatedModules a real hard sell.

I think const enums can still be used with typescript isolated modules, one would not need to change all `const enums` to `enums`. :)

> I have been thinking about esModuleInterop. I believe that's safe to do in main and will allow to make the assert-refactoring, even case-by-case to prevent monster PRs

Yes, I think that would be great also!

**Comment by jrieken** [comment]
Haven't tried it but this sounds like they would raise a compile error: https://www.typescriptlang.org/tsconfig/#references-to-const-enum-members?

**Comment by SimonSiefke** [comment]
I finished the all changes now for isolated modules now, 7 files changed: https://github.com/microsoft/vscode/pull/212913

I'm looking forward to feedback! :)

**Comment by SimonSiefke** [comment]
And a Pull Request for esModuleInterop: #213014

**Comment by SimonSiefke** [comment]
Some more ideas what (perhaps) could be done in the `main` branch: 

## Using script type module

Using `<script type="module">` would allow using imports. Even though imports are not used now, it seems it would be quite useful for later.

## Using worker type module

Similar to above, this would enable using `import` in workers. Probably some kind of workaround may be needed to keep `importScripts`  working, which is not available in module workers.


## Moving src/buildfile.js into the build folder

With the src files being ESM,  I encountered some issues with the `src/buildfile.js`  (`Error [ERR_REQUIRE_ESM]: require() of ES Module '../src/buildfile.js' not supported`). It seems to me it might be useful to move it to the `build` folder, avoiding the `ERR_REQUIRE_ESM` error.




<br>
<br>

Feedback and ideas are as always very welcome!

**Comment by lppedd** [comment]
Impressive effort!

Do you think you could get ESM to work for web extensions? I ask because using ESM wouldn't make much sense if then to ship to web I have to bundle anyway. The entire change would have limited use.

**Comment by SimonSiefke** [comment]
@lppedd Thanks for the comment! I agree it would be very useful to have ESM support in web extensions also. The issue for web extensions - which I haven't been able to solve - are these imports:

```js
import * as vscode from 'vscode'
```

The vscode import would need to be mapped to a file, for example `/workbench/api/common/extHost.api-esm.js`. 

It seems import maps for webworkers could solve this problem, once they are supported by browsers.

**Comment by SimonSiefke** [comment]
Closing in favor of https://github.com/microsoft/vscode/pull/166033. 

Parts of this PR have now been implemented in VSCode like isolatedModules and esModuleInterop. Additionally, the prototype for ESM extensions implemented here could maybe be used in the future as a starting point for proper ESM support in VSCode extensions (once the VSCode core supports ESM).

Thanks!

**Pull request closed without merging**
