### PR TITLE
Use correct resolved TDO and task for custom execution

### PR DESCRIPTION
**Pull request by GabeDeBacker**
This address issue #77757.

When using custom executions in conjunction with resolved tasks, the wrong variables where being passed to addCustomExecution and addCustomExecution2. They needed to be passed the resolvedDTO and the resolvedTask.

This change was verified by ensuing that task resolution works correctly after modifying a default build task in tasks.json for our internal MS extension. Both "terminal renderer" and "virtual terminal process" paths were verified.

### CODE REVIEW

**Comment by GabeDeBacker** [comment]
@alexr00 and @joelday, can you please take a look?

Thanks!

**Comment by Tyriar** [comment]
@alexr00 please consider for July when you get back

**Comment by alexr00** [comment]
I'm not sure this is a good path to go down. It is intentional that we don't allow changes to a task's provider provided properties. Those properties function as an ID of the task if they are changed, it is a different task.

**Comment by GabeDeBacker** [comment]
I think I’m confused on what resolveTask is supposed to do (hence issue https://github.com/microsoft/vscode/pull/77759).

What we can do in our resolveTask is essentially return as “new task” as long as the task information passed to “resolve task” is something we can execute.

Is the intention of “resovleTask” to resolve it to something that the provider provided during “provideTasks” (i.e. an already existing task?).

I guess what I’m super confused about is should the user EVER be able to edit tasks.json? If they do, then how would a task there ID ever match what is returned through “provideTasks”?

Our task provider can actually resolve to a new task with no problems as long as the edits to task.json match our schema, which VSCode happily guides the user through if your task definition information is correct in the package.json for the extension 😊

Please help me understand 😊

**Comment by alexr00** [comment]
tasks.json is for modifying non-provider specific task properties. If a task provider defines a property for their task in their package.json, then those properties are immutable for that task. Things like background, presentation, and group are all fair game to be modified in tasks.json. 

This confusion over what `resolveTask` does has happened repeatedly. I will update the documentation.

**Comment by GabeDeBacker** [comment]
Spoke with Alex about this offline. The goal here is to make sure that the resolved task definition is not different than the original task definition. If they are the same, then the resolved task can be used.

**Review by alexr00 — CHANGES_REQUESTED** [review]
We talked about this some more, and the goal of this change isn't to change the task definition (which is dangerous because it changes the task's ID). All that's needed in addition what's already here is a check that the task definition hasn't changed.

**Review by alexr00 — APPROVED** [review]

**Comment by Tyriar** [comment]
Merging as only install deps on mac failed

**Comment by alexr00** [comment]
Thank you for merging!

**Pull request merged**
