### PR TITLE
Extension management in viewlet

### PR DESCRIPTION
**Pull request by joaomoreno**
Alternative to #5074

To experiment with this:

```
git checkout -b extension-viewlet master
git pull --no-rebase https://github.com/joaomoreno/vscode.git extension-viewlet
```

### CODE REVIEW

**Comment by isidorn** [comment]
@joaomoreno I would add mention bot config to add Erich to the blacklist otherwise he will always be mentioned since he did the initial commit.

**Comment by joaomoreno** [comment]
@isidorn I think @egamma is always interested in getting pinged about PRs, so no worries.

**Comment by outcoldman** [comment]
@joaomoreno could you add a little bit more details about this pull request in description? Are we going to get extension manager UI?

**Comment by joaomoreno** [comment]
This is a UI exploration from #637

**Pull request merged**
