### PR TITLE
Add MarkdownString.baseUri proposal

### PR DESCRIPTION
**Pull request by mjbvz**
For #142051

See that API proposal for details

### CODE REVIEW

**Review by gjsjohnmurray — COMMENTED** [review]
I didn't spot where you are checking that the proposed API has been enabled.

**Review by jrieken — APPROVED** [review]
Generally liking, a few questions

* what's the default? the extension location? workspace location?
* how do know what a path and what a file is? is `/foo/file/` a folder and `/foo/file` a file?

**Comment by jrieken** [comment]
> I didn't spot where you are checking that the proposed API has been enabled.

That's really hard to classes because every API instance uses the same ctor-function. It would require that we create an extension aware subtype somewhere [here](https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/api/common/extHost.api.impl.ts#L1237). We have been playing this pragmatic but we are also open for suggestions

**Comment by gjsjohnmurray** [comment]
> We have been playing this pragmatic

I don't have a problem with that.

**Comment by mjbvz** [comment]
Yes thanks @gjsjohnmurray, this is unfortunately a pretty annoying case to restrict and since the proposal is relatively small I think it's ok

**Pull request merged**
