### PR TITLE
Allow individual comments to be marked as draft

### PR DESCRIPTION
**Pull request by hermannloose**
This is a proposal for #171166.

The names are rough suggestions, I am not sure if "visibility" is more descriptive than e.g. `CommentDraftState`.

`CommentThread.hasDraftComments` is included to show how we would conceptually want this to roll up into the thread. The surrounding features suggested in #171166 all operate on threads, but `hasDraftComments` does not necessarily need to become part of the API surface, it could be implicit and the relevant parts like line gutter decorations could just do the same iteration ad-hoc.

Staying with the example of line gutter decorations for illustration, our ideal UX would be:
- resolved thread: `$(comment)`
- unresolved thread: `$(comment-unresolved)`
- thread with a draft, regardless of status: `$(comment-draft)`

Note that in this particular case for the UI, it ends up looking like the "draft" state is mutually exclusive with resolved or unresolved `CommentThreadState`, but they are separate things, e.g. there could be two icons for lines that have a thread (or threads) with drafts, one icon to give the state, one icon to indicate presence of drafts.

### CODE REVIEW

**Comment by hermannloose** [comment]
cc @JonasMa @laurentlb

**Comment by hermannloose** [comment]
Any initial thoughts on the proposal, regarding naming or structure?

**Comment by alexr00** [comment]
@hermannloose I haven't had a chance to give this the review it deserves. I will plan to review it during our next iteration (starts in 1.5 weeks).

**Comment by hermannloose** [comment]
I dropped `hasDraftComments` as per https://github.com/microsoft/vscode/issues/171166#issuecomment-1462032107.

`visibility` vs `state` did not sound as decided yet, so I kept it in for now. I think `visibility` is more descriptive than `state` here, so personally I would still lean towards `visibility`—also because it avoids potential API user confusion around `CommentState` just being `CommentThreadState` but at the `Comment` level; as mentioned above, they are separate and I would prefer the more obvious difference in name.

No strong opinions on `Pending` vs `Draft` but that also sounded like it was still up for debate, so I left it as is for now.

**Review by alexr00 — COMMENTED** [review]
With the `visibility` to `state` change I would accept a complete PR to add the published/draft feature.

**Review by alexr00 — APPROVED** [review]
Thank you for the PR and for your patience with my slow review!

**Review by bpasero — APPROVED** [review]

**Pull request merged**
