### PR TITLE
Feat: Bolder Typeface + Configurable Letter Spacing for Minimap's Section Header Labels ✨

### LINKED ISSUE #209989: Minimap Section Header Labels Are Really Hard To Read
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Darwin arm64 23.0.0

The amazing work of @dgileadi on #190759 has been a wish come true for many of us. (Thanks a lot really!). In the past days trying to use it, I have noticed that it lacks readability a lot. I compared the feature to Xcode and what I saw was two things:

1. Xcode's version has bolder font
2. Xcode's version has letter spacing of around 1px 

The combination of the two makes readability a lot more on Xcode's side on even smaller font sizes than of the vscode: 

Screenshot 1403-01-21 at 11 46 01 PM

Thanks to the freshness of the feature, I could read the PR and develop both of them for vscode as well, which I will create as a PR right away:

### PR DESCRIPTION
**Pull request by pouyakary**
This PR fixes #209989 and brings a bolder minimal Section Header Label with letter spacing for the section header labels configurable by user:

> __Help Wanted Portion__ &mdash; I have noticed that changing the letter spacing's value in the settings doesn't translate to a rerender right away, which I haven't figured why. Can you please give me guidance on how to address it?

### CODE REVIEW

**Comment by pouyakary** [comment]
I have noticed that overflow is not addressed correctly:

Screenshot 1403-01-22 at 5 02 13 PM

I have changed the PR to a draft so that I can fix it.

**Comment by pouyakary** [comment]
Sorry I closed it by mistake trying to post a comment. One thing about the bold typeface is that if you notice it, in some screenshots it is bold, and in some (like my machine) it was not. So I guess putting the weight ensures we're all on the same thing.

**Comment by pouyakary** [comment]
@alexdima can you please check this out?

**Review by alexdima — APPROVED** [review]
Thank you!

**Review by andreamah — APPROVED** [review]

**Comment by pouyakary** [comment]
@alexdima thank you a lots! ♥️

**Pull request merged**
