### PR TITLE
A file open with auto-detected encoding.

### PR DESCRIPTION
**Pull request by tomoki1207**
This related to #5388.

A text file will opened with detected encoding by [jschardet](https://www.npmjs.com/package/jschardet).

### CODE REVIEW

**Comment by bpasero** [comment]
@tomoki1207 I am not sure this works the way you coded it because the encoding is a user setting and you always try to detect the encoding now. How can you still respect the user preference if the encoding is not clear?

My argument is that really the only way of detecting an encoding is by looking at the BOM (Byte Order Mark) for UTF (and we do this already). Any other file encoding can only be guessed.

I think one thing we could add is an action in the encoding picker to "Auto Detect" the encoding via this code and then set the encoding for the file. But always detecting the encoding for each file being opened is not right imho.

**Comment by tomoki1207** [comment]
@bpasero I understand your opinion.
However, I think many people are feeling a lot of inconvenience to open small files that are not encoded in UTF.
So, I hope to be detected automatically the encoding in some way.

Do you better the following approach? Just like [Atom auto detect package](https://atom.io/packages/auto-encoding).
1. Prepare SetEncoding API for Extension
2. Call it from auto-detect extension

**Comment by bpasero** [comment]
@tomoki1207 the approach works if every encoding can be detected with 100% certainty but I doubt that is possible for any file that does not include a BOM. What does jschardet do if the encoding is ambiguous?

Nevertheless we do have a global and workspace setting for the encoding that we cannot just drop, so I see little chance of changing this to always auto detect the encoding. The only possible thing I see is to offer an action to "Guess Encoding" from the encoding picker that executes the jschardet. I believe Atom does the same.

**Comment by bpasero** [comment]
Closing for inactivity.

**Pull request closed without merging**
