### PR TITLE
Add match-type sorting to filterSettings

### LINKED ISSUE #136028: Settings Editor filter string `java.` includes JavaScript settings as well
Issue Type: <b>Bug</b>

See https://github.com/microsoft/vscode-java-pack/issues/794

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

### PR DESCRIPTION
**Pull request by rzhao271**
This PR fixes #136028

### CODE REVIEW

**Comment by roblourens** [comment]
Cool, but is this supposed to sort those matches to the top? I don't see that happening:

image

**Comment by roblourens** [comment]
Nov-15-2021 15-01-41

I added one `java.foo` setting, and saw it sorted below javascript settings. Now I've added the Java extension but see a mix of java/javascript settings, so make sure the sorting is happening the way you expect

**Comment by rzhao271** [comment]
Matching using `includes` was a bad idea. I'm now using regex to process the query a bit and to match on word boundaries.

**Comment by rzhao271** [comment]
I suspect it sorts the results even within an extension because of the key and value matchTypes, so I'd like to exclude those for now before merging in this PR.

**Review by roblourens — APPROVED** [review]

**Pull request merged**
