### PR TITLE
Implement getProfileName for emmet

### LINKED ISSUE #16354: How do I make it so that emmet expands classNames in JSX and JS files using single quotes instead of double?
- VSCode Version: 1.7.2
- OS Version: Win10

I've tried adding a custom syntaxprofile for jsx like so:

`"emmet.syntaxProfiles": {
        "jsx": {
            "attr_quotes": "single"
        }
   }`

This does not work. Emmet still expands classNames using double quotes.
Also, how to make using single quotes the default behavior for .js files and not just .jsx files?

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #16354

cc @egamma @mrmlnc

### CODE REVIEW

**Comment by kunawut3310** [comment]
Good

**Review by egamma — APPROVED** [review]
LGTM

**Comment by ramya-rao-a** [comment]
Thanks @egamma

**Comment by mrmlnc** [comment]
My late OK :)

**Pull request merged**
