### PR TITLE
Fix bad capitalization of completion item statusbar texts (#225429)

### LINKED ISSUE #225429: Bad capitalization of "show more" and "show less" on completion status bar
> Related - do you agree with me that "show more" should be "Show More", and the same capitalization should apply to "show less"?

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/210896#issuecomment-2103363393_

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #225429

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Set `"editor.suggest.showStatusBar": true` to display the affected statusbar.

**Comment by gjsjohnmurray** [comment]
@daviddossett are you willing to approve this?

**Review by daviddossett — APPROVED** [review]

**Comment by daviddossett** [comment]
Thanks for the fix!

**Review by rzhao271 — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
@daviddossett please merge this.

**Pull request merged**
