### PR TITLE
Fix-76141 Add border around image in image preview

### LINKED ISSUE #76141: Add border around image in image preview
See https://github.com/microsoft/vscode/issues/74710 for context

### PR DESCRIPTION
**Pull request by skprabhanjan**
@mjbvz , Added the border property accordingly to fix #76141  and kept it default as I could not find the panel color that was mentioned [in this comment](https://github.com/microsoft/vscode/issues/74710#issuecomment-505568760)

I will change it if you can provide me the color code.

This is how it looks for default border `1px solid`

image

### CODE REVIEW

**Comment by dbaeumer** [comment]
@bpasero FYI. Could be you as well :-)

**Comment by mjbvz** [comment]
Thanks @skprabhanjan.

We probably want to use a border color from one of our existing theme colors, such as `panel.border` perhaps. Adding @aeschli for ideas on which theme color to use.

Here's an example of how write a style that uses a theme color: https://github.com/microsoft/vscode/blob/982e7bc2f195b323cc819529b7d4b7463011e2b7/src/vs/workbench/contrib/terminal/browser/terminalPanel.ts#L332

Just add a call to `registerThemingParticipant` in `resourceViewer` and then move the css border rule into a string within it

**Comment by aeschli** [comment]
reusing `panel.border` is not really 100% proper, but fine with me. You could also add a new color: `imagePreview.border`

**Comment by skprabhanjan** [comment]
@mjbvz and @aeschli 
Added `imagePreview.border` which has same values as `panel.border` and used that in `registerThemingParticipant` in `resourceViewer `.

Please check and review this :)

**Comment by mjbvz** [comment]
Thanks! This will be in the next VS Code 1.37 insiders build and is scheduled to go out in the July release

**Pull request merged**
