### PR TITLE
Show terminals separately in quickOpenTerm and quickOpenView

### LINKED ISSUE #48671: Changing name of terminal with split terminals in `Switch Active Terminal` changes wrong terminal name
- VSCode Version:
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version: `Windows 10`

Steps to Reproduce:

1. Open terminal (AKA `term1`) and split it (with `Ctrl+\`)
2. Open another terminal (AKA `term2`)
3. `Ctrl+Shift+P Switch Active Terminal`
4. Click on the `Rename` button of `term1` and change it's name, this changes fine: `bash, bash` -> `client, bash`
5. Click on the `Rename` button of `term2` and change it's name, this changes the name of the second split terminal of `term1`: `client, bash` -> `client, server`

Bug is bad

6. This happens when opening more terminals or split terminals.
Basically, the `Rename` action changes the terminal at `index = line in the list of terminals`,
but the list of terminals contains all the split terminals, so `index = 2` in the switch list is the second terminal in the terminals list, which is the split terminal of `term1` in the example.

### PR DESCRIPTION
**Pull request by gioragutt**
Fixes both `quickOpenTerm` and `quickOpenView` command.

### CODE REVIEW

**Comment by gioragutt** [comment]
@Tyriar The code pretty much ends up changing from iterating over `tabs` or `instances`, to iterating over the `instances` in `tabs`.

This seems like a bit of code rep, but I can't think of a way of removing it, other than exporting some method from `TerminalService` which returns:
```typescript
interface TerminalInTab { // or w/e
  tabIndex: number;
  terminalIndex: number;
  terminal: Terminal;
}
```

and thus we can make the usages outside terminal service be able to just `forEach` or `map/reduce` once, instead of doing the nested loops due to having to iterate over terminals in tabs.

**Comment by gioragutt** [comment]
@Tyriar any comments?

**Review by Tyriar — APPROVED** [review]
Works great, thanks! :smiley:

**Comment by gioragutt** [comment]
@Tyriar thanks man! Glad to contribute!

**Pull request merged**
