### PR TITLE
Rename arg `connectionToken` to `connection-token`

### LINKED ISSUE #136619: [remote] Use one casing for all the server script flags
All flags one can provide to the server are pascal case, but `--connectionToken` is camel case. I get that it is mentioned as `connectionToken` in the source code and that there it is following the code standard, but it is really confusing to see that just one of the arguments is standing out like this.

Also, I understand this is a potentially breaking change, but I think it's worth one.

### PR DESCRIPTION
**Pull request by filiptronicek**
This PR fixes https://github.com/microsoft/vscode/issues/136619

### CODE REVIEW

**Review by bigint — APPROVED** [review]
LGTM :shipit:

**Review by alexdima — CHANGES_REQUESTED** [review]
The previous argument `--connectionToken` should still be accepted. This change needs to be done by deprecating the previous argument for a few iterations, and then eventually removing it.

**Comment by alexdima** [comment]
cc @aeschli I think you want to improve things in this area

**Review by alexdima — APPROVED** [review]

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
