### PR TITLE
Extension tips

### PR DESCRIPTION
**Pull request by waderyan**
Added a couple more extensions to the tips json.

### CODE REVIEW

**Comment by egamma** [comment]
@waderyan it looks like this PR also includes changes to the Feedback widget. Is this an oversight? The changes to the extension tips looks good to me.

**Comment by waderyan** [comment]
Yep that was an oversight. Let me fix that.

**Comment by waderyan** [comment]
Close in favor of new PR

**Comment by egamma** [comment]
@waderyan no need for a new PR. I can just commit the changes to the extensiontips.

**Pull request closed without merging**
