### PR TITLE
Skip explorer reveal on visible items

### LINKED ISSUE #82828: autoReveal highlight filename where it is without always moving it to the middle in explorer
Screen Shot 2019-10-18 at 5 03 38 PM
Screen Shot 2019-10-18 at 5 03 49 PM

Version: 1.39.2

autoReveal always moves the filename entry to the middle in file explorer window when we select a file on tab. if the filename is not visible in the explorer, this is ok.

if the filename is visible in explorer, it should not move the filename to the middle in explorer, just highlight the filename where it is, right there in explorer.

thanks!

### PR DESCRIPTION
**Pull request by baileyherbert**
Fixes #82828.

Before this change, clicking on an editor tab while `explorer.autoReveal` is `true` would always scroll the explorer so that the corresponding file was vertically centered.

After this change, the explorer isn't scrolled if the corresponding file is already visible in the file tree.

### CODE REVIEW

**Comment by isidorn** [comment]
I think changing this behavior makes sense overall. However I do not like the approach that there are a lot of changes in the tree land.
The tree and list should not be aware of this. I believe you can just use tree api from the explorer to get this behavior.
fyi @joaomoreno

**Comment by joaomoreno** [comment]
This already exists in the list/tree:

https://github.com/microsoft/vscode/blob/a7ed9c9572f51eee964b5d290ac0d170d9a01439/src/vs/base/browser/ui/list/listWidget.ts#L1576-L1581

**Review by joaomoreno — CHANGES_REQUESTED** [review]
This already exists in the list/tree:

https://github.com/microsoft/vscode/blob/a7ed9c9572f51eee964b5d290ac0d170d9a01439/src/vs/base/browser/ui/list/listWidget.ts#L1576-L1581

So we don't need the list/tree changes.

**Comment by baileyherbert** [comment]
Thanks guys. Let's try again. 😊

**Comment by isidorn** [comment]
Works great. Love it.
Even when the user triggers "Reveal active file in sidebar" we center it no matter the visibility which is correct behavior since this is explicitly requirested by user.
Thanks a lot. Merging in.

**Pull request merged**
