### PR TITLE
Fix error printing

### PR DESCRIPTION
**Pull request by solomatov**
See https://github.com/microsoft/vscode/pull/86405 for details

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
if `exception.message` is not defined, let's simply use the generic error message `An unknown error occurred. Please consult the log for more details.` so that we make sure that even in the verbose case, no undefined message is printed together with the stack.

**Comment by solomatov** [comment]
@bpasero So, it seems that we're repeating what was in the previous PR :-)
Even without message it looks decent. I.e.:
```
  ERR : Error:
       at stacktrace
       at stacktrace
```
So, I think, it makes no sense to add a message. It shows a type and empty message after colon.

What do you think?

P.S. I can't reuse the code from spdlogService.ts as @sandy081 suggested, since we use the fact that console allow printing objects in JS representation, and thus more readable than what's available in the file logger.

**Comment by solomatov** [comment]
@bpasero Also, the error isn't unknown, it's Error, it just doesn't have a message.

**Comment by bpasero** [comment]
Thanks, I pushed one commit on top. The reason why I think we always want an error message is that these errors might be shown to users and it is not very helpful to have no information provided in that case.

**Comment by solomatov** [comment]
@bpasero That sounds great! Will check whether the error reported correctly.

**Pull request merged**
