### PR TITLE
Use css variables for editor scrollbar

### PR DESCRIPTION
**Pull request by GauravB159**
Fix for issue #165169 task 2

I have replaced the registerThemingParticipant in the file with the appropriate css variables. 

I needed to add the rules for the last three since they did not exist in scrollbars.css

Note: This is my first PR ever, and I'm really looking forward to Open Source Development. Let me know if there's anything wrong and I'll fix it asap, and I'll be glad to do a few of the other tasks as well if this one gets merged.

### CODE REVIEW

**Comment by GauravB159** [comment]
@microsoft-github-policy-service agree

**Review by rzhao271 — APPROVED** [review]
LGTM!

**Review by rebornix — APPROVED** [review]

**Comment by GauravB159** [comment]
@rzhao271 Thanks! Can I pick up a few of the other tasks as well then? Or if you could assign me any, that would be great

**Comment by rzhao271** [comment]
You can pick up some of the other ones. The `src/vs/workbench/contrib/codeEditor` ones are probably fine to work on.

**Comment by alexdima** [comment]
@rebornix @rzhao271 This introduced a regression. See https://github.com/microsoft/vscode/pull/166690

**Pull request merged**
