### PR TITLE
Use variadic tuples to simplify typing of `h`

### PR DESCRIPTION
**Pull request by mjbvz**
Type inference will expand `T extends Child[]` to the more specific types

### CODE REVIEW

**Comment by hediet** [comment]
> I believe this wasn't working well

Yep, this didn't use to work. @mjbvz did you check the resulting types?

**Comment by mjbvz** [comment]
@hediet Pushed a small change to also forces the parameter type to be a tuple instead of potentially being an array

Do you remember what specifically didn't seem to work when you tried this? The return types look ok:

Screen Shot 2022-11-16 at 10 23 14 AM

With the latest change, the signature looks the same too

Screen Shot 2022-11-16 at 10 34 52 AM

**Comment by hediet** [comment]
I think the problem happened when nesting some `h` calls.

**Comment by mjbvz** [comment]
@hediet In our tests, we could add some type checks using `satisfies`.  For example:

```
test('should build simple nodes', () => {
	const div = h('div') satisfies { root: HTMLElement };
        ...
```

This will assert that the type has the fields we list but not affect the actual type of `div`

I think our tests already fail to compile though if the types aren't working as expect. There are two things they would not catch:

- Use of `any` types
- Extra fields on the type

**Comment by hediet** [comment]
Exactly these any cases worry me. Typescripts often infers `any` when it gives up.

**Comment by mjbvz** [comment]
@hediet What would you like to do with this PR? I believe the typings are correct but it's difficult to prove this exhaustively

**Review by hediet — APPROVED** [review]

**Pull request merged**
