### PR TITLE
Allow css emmet completions when abbr contains period or errors in css blocks in html files 

### LINKED ISSUE #44352: Emmet regression - css - opacity: 0.5 not working in 1.21
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

`op0.5` - should be expanded into **_opacity: 0.5_**, right?

so as `op.5`

op0 5

PS:
in the stable version...
```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
```
... it works fine.

So, the problem is in Insiders build.

```
Version 1.21.0-insider
Commit ce13bb0dabd06981913c46b5a94456647864c2e0
Date 2018-02-23T05:19:18.064Z
```

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #44352

Due to https://github.com/Microsoft/vscode-css-languageservice/issues/69, css files do not get parsed after encountering an emmet abbreviation that has a `.`

This PR has workaround for such cases. 

**Update**

Reverted the move of emmet to css extension. See #44840

- Emmet completions in css/scss/less files will come from the Emmet extension like they did in 1.20
- Emmet completions in html files will come from Html extension 
- Each mode (htmlmode, cssmode) in the Html extension is responsible for Emmet in their respective modes.
- HtmlMode will ensure to trigger emmet only inside Html content area (`onHtmlContent`)
- CssMode will trigger emmet regardless of the position (this mimics what the Emmet extension does for css in html files today in 1.20)

### CODE REVIEW

**Comment by aeschli** [comment]
If this is not critical for the release I'd rather like to do this next milestone.
If you feel this must go in, please push.

The code in htmlServerMain grows and grows, with more `if mode.getId() == 'xy'` added while that code would ideally be in the mode itself, or maybe in a participant s

**Comment by ramya-rao-a** [comment]
@aeschli 

Its a regression, so I want to have this in the current milestone. 

I agree with your concern about the code insider the completion part of htmlServerMain, I had the same thought yesterday. My first instinct was to add this inside the mode, but that requires completionParticipants to have some kind of id, because I want to just call the emmet's completion participant and not the others. Let me re-visit that idea.

**Comment by ramya-rao-a** [comment]
@aeschli Moved the needed workaround from `htmlServerMain` to `cssMode`

**Comment by ramya-rao-a** [comment]
I've reverted the move of emmet to css extension. See https://github.com/Microsoft/vscode/issues/44840

In html files, the emmet extension itself has been providing css emmet completions inside style blocks without making checks if the current position is a property or selector. This PR will mimic the same behavior.

We will revisit how we want to update the css language service to better support completions in the presence of parsing errors in the next milestone

**Comment by aeschli** [comment]
@ramya-rao-a With 'css extension' you mean 'css mode'?

**Comment by ramya-rao-a** [comment]
@aeschli No, with 'css extension', I mean the css extension. For 1.21
- Emmet completions in css/scss/less files will come from the Emmet extension 
- Emmet completions in html files will come from Html extension 
- Each mode (htmlmode, cssmode) in the Html extension is responsible for Emmet in their respective modes.
- HtmlMode will ensure to trigger emmet only inside Html content area (`onHtmlContent`)
- CssMode will trigger emmet regardless of the position (this mimics what the Emmet extension does for css in html files today in 1.20)

The reason for the revert is https://github.com/Microsoft/vscode/issues/44840

**Comment by aeschli** [comment]
Oh, ok, that's quite a change, but maybe lets talk about it before starting the work.

**Comment by ramya-rao-a** [comment]
@aeschli Everything mentioned in https://github.com/Microsoft/vscode/pull/44781#issuecomment-369962330 is already done. What part are you referring to when you say "lets talk about it before starting the work"

**Pull request merged**
