### PR TITLE
fixes #52531

### LINKED ISSUE #52531: Cant click on custom context menus when on top of title bar
when the context menu overlaps with the title bar, the buttons become unclickable. It seems the clicks fall through to the title bar, as double clicking makes the window full screen. 
cant click title bar

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.16299

### PR DESCRIPTION
**Pull request by sbatten**
In order for the context menu to be clickable on top of the title bar, we must have webkit-app-region set to no-drag. In order for webkit-app-region to be effective, the dom node MUST be after the titlebar part to apply. This code would ensure that the workbench parts are always the first nodes in the workbench. It is a simple change but could have an unforeseen impact I am not aware of. If you have a better suggestion for reaching the same goal, let me know.

fixes #52531

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

**Comment by sbatten** [comment]
@bpasero I was originally doing that but: 
1) There's no user-facing reason the context menu shouldn't be able to overlap the title bar and I want to get as much real estate as possible.
2) That's a bit more complex due to the fact that the context view service doesn't and probably shouldn't really be aware of the workbench layout.
Thoughts?

**Comment by bpasero** [comment]
> That's a bit more complex due to the fact that the context view service doesn't and probably shouldn't really be aware of the workbench layout.
> Thoughts?

@sbatten Is that referring to the overflow behaviour?

**Comment by sbatten** [comment]
@bpasero no, just when knowing the viewport is actually 30px shorter than the element given as the container.

**Comment by bpasero** [comment]
@sbatten yeah agree with your comments

**Pull request merged**
