### PR TITLE
Make menubar its own widget and add overflow

### LINKED ISSUE #57756: No menu overflow causes problems with narrow windows/long titles
image

It can also look like this after alt+f, right to terminal menu

image

### PR DESCRIPTION
**Pull request by sbatten**
MenubarControl has been broken into 2 pieces:
1. a widget that controls display and interaction and 
2. a control that handles the model and vs code settings changes

This made it very easy to add a the overflow logic as part of the widget

resolves #57756

### CODE REVIEW

**Review by bpasero — APPROVED** [review]
Given the amount of changes, I did not do a code review. I like the direction though, especially making the `menubarControl.ts` in workbench slimmer. 

Playing around with it (on Linux): I agree we could use a "..." similar to this one:

image

Though I was actually not opposed to the "More" either.

PS: wow, windows seems to wrap actually (not my preference):

image

**Comment by bpasero** [comment]
@sbatten there seems to be an issue with the direction of where the menu opens in this case:

image

Since space is typically limited to the right when "More" shows up I believe you need to show the menu then to the left to account for the narrow size, otherwise a user will probably have issues accessing all menu entries from the "More" menu.

**Comment by sbatten** [comment]
@bpasero thanks for the review, you can see quite a few changes since your approval.
- Using ellipsis
- Compact menus that cascade when needed. The drawing to the left didn't help in most cases, because a lot of the time you only have room for 1.5 menus when testing this
- Mnemonics fixed when in overflow

**Comment by bpasero** [comment]
@sbatten looks good to me. if you want to merge it for Nov, it should get a good test plan item.

**Pull request merged**
