### PR TITLE
Notebook UI heading tweaks

### PR DESCRIPTION
**Pull request by christian-bromann**
Hi there 👋 

I am Christian and part of the development team that has build a VS Code extension called [Runme](https://runme.dev/). It is an extension that renders markdown files as notebooks and allows them to execute/run the code snippets in their. Runme is currently featured on the [VS Code Marketplace](https://marketplace.visualstudio.com/vscode) and grows fast day by day.

Some of the feedback we have received is that the markdown within notebooks doesn't render the same way markdown preview extension would render it. Here is example:

__Markdown Example rendered in VS Code notebook view__

Screenshot 2023-07-17 at 14 55 06

__Markdown Example rendered with [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)__
Screenshot 2023-07-17 at 15 42 44

We have been looking at many markdown preview extensions and we see the UI diverging mostly in the following areas:
- headings are generally too big
- size difference between h5 and h6 too significant
- headings have no bottom border
- `<hr />` element height is too big (2px vs. 1px)

I am proposing some small tweaks to the `markdown-language-features` extension that adjusts the styles so that it comes marginally closer to how VS Code would render markdown usually.

See a preview here:
vscode-ui-tweak

It lowers the visual difference between viewing markdown within a markdown preview extension or within the notebook UI.

Happy to answer any questions.
Thanks for reviewing.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@microsoft-github-policy-service agree company="Stateful Inc."

**Comment by daviddossett** [comment]
Not sure if you saw this but I recently updated the markdown styles in VS Code itself in https://github.com/microsoft/vscode/pull/185801. I think it would make more sense to align to those vs. an extension.

**Comment by christian-bromann** [comment]
@daviddossett thanks for the reply! I have not seen that commit but we almost made the same change. I pushed another commit to make it more align with your changes. Wdyt?

**Review by daviddossett — APPROVED** [review]
Thanks!

**Review by mjbvz — APPROVED** [review]

**Pull request merged**
