### PR TITLE
Pass results limit

### LINKED ISSUE #15778: Find and replace limited to 999 lines?
- VSCode Version: 1.7.1
- OS Version: 10.12.1

Steps to Reproduce:

1. Open a file with an excessive amount of duplicates, in my case - 19000 line CSV with `,,,,,,,,,,,,,,,,,,,,`
2. `cmd+shit+h` or `edit -> replace`
3. Using replace all will only select the first 999 occurrences 

I assume this is a performance constraint, so this may not be an issue at all. However, it makes a monthly task of mine consume more time or I have to use another editor - which I would prefer not to.

image 2016-11-20 at 10 23 11 am

### PR DESCRIPTION
**Pull request by chrmarti**
Fixes #15778

### CODE REVIEW

**Comment by roblourens** [comment]
Do we also need to pass maxResults to the FileMatch at the location of the original fix, https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/searchService.ts#L140? This is confusing...

**Comment by chrmarti** [comment]
There are two FileMatch classes:
- https://github.com/Microsoft/vscode/blob/chrmarti/15778/src/vs/workbench/parts/search/common/searchModel.ts#L93
- https://github.com/Microsoft/vscode/blob/chrmarti/15778/src/vs/platform/search/common/search.ts#L122

I have updated the first, searchService.ts is using the second.

**Comment by roblourens** [comment]
Oh, I see that one is the simple object of the same type that comes from the search service, and the other is the live object for the frontend. And we actually end up getting local results twice for each editor. I'm not sure that used to happen. Something to look into for May.

**Review by roblourens — APPROVED** [review]

**Comment by roblourens** [comment]
Thanks for fixing @chrmarti

**Pull request merged**
