### PR TITLE
voice - use `mute` and `unmute` for chat responses to trigger synthesis

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Review by roblourens — APPROVED** [review]
Maybe we should disable this when accessibility mode is enabled, since the user is probably using a screen reader too

**Comment by roblourens** [comment]
I guess this only happens on request and not automatically? Does it ever read aloud automatically?

**Comment by bpasero** [comment]
Yeah good point, @meganrogge thoughts? I am not sure about the quality of text-to-speech from screen readers for chat items.

**Comment by meganrogge** [comment]
@bpasero can you describe the steps to try this and i'll test/ let you know my thoughts?

**Comment by bpasero** [comment]
@meganrogge with latest insiders and latest speech pre-release, chat response items have a 🔈 icon to read aloud.

**Comment by meganrogge** [comment]
With the latest insiders and latest speech pre-release, clicking that button does nothing for me and I see this error in the console:

```
workbench.desktop.main.js:sourcemap:656   ERR I.provideTextToSpeechSession is not a function: TypeError: I.provideTextToSpeechSession is not a function
    at A.$createTextToSpeechSession (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:145:9087)
    at o.S (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:5505)
    at o.Q (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:5271)
    at o.M (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:4361)
    at o.L (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3440)
    at a.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:2227)
    at r.y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:660)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:877)
    at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14154)
    at a.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:8020)
    at r.y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:660)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:877)
    at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14154)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:6300)
    at MessagePortMain.emit (node:events:514:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
```

**Comment by meganrogge** [comment]
This is a really cool feature. I don't think we should disable it for screen reader users. I tried it and it didn't seem to be a problem.

**Comment by bpasero** [comment]
@meganrogge thanks, one thing I did though is to not auto-play-back a response when voice was used if a screen reader is active:

https://github.com/microsoft/vscode/blob/98e776cfba3994128e8e1745332cf98b64ea6d96/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L468-L473

I thought when a screen reader is active, we already playback a response.

**Comment by meganrogge** [comment]
Yes we already use aria alert to read the response to the user once it comes in.

**Pull request merged**
