### PR TITLE
Mark our built in webview to explicitly set role=document

### PR DESCRIPTION
**Pull request by mjbvz**
For #93087

### CODE REVIEW

**Comment by mjbvz** [comment]
Not really sure if this is the correct fix. https://github.com/w3c/respec/issues/309 suggests that `body` already defaults to `role="document"`?

Do we need to set `role="document` on webview element instead? Maybe on the outer html inside the webview?

**Comment by MarcoZehe** [comment]
> 
> 
> Not really sure if this is the correct fix. [w3c/respec#309](https://github.com/w3c/respec/issues/309) suggests that `body` already defaults to `role="document"`?

Normally yes, _but_ the root element of VS Code overrides this to be role "application", and everything inside inherits that, including the `<body>` element of embedded documents. That's exactly what role "document" is for, so this should be the correct fix.

> 
> Do we need to set `role="document` on webview element instead? Maybe on the outer html document inside the webview?

If the webview element itself is always guaranteed to hold read-only contents, you could add it there and not have to do it for each individual thing getting displayed inside it.

**Comment by isidorn** [comment]
Agree with what @MarcoZehe pointed out. Thanks!

**Comment by mjbvz** [comment]
Thanks for the clarification @MarcoZehe 

One more question: I believe we can mark all webviews as `role="Document"` however some webviews are not actually documents (such as out built-in image preview). Is setting `role="Document"` a reasonable default? If we do that, should non-document based webviews like the image preview set `role="application"`?

**Comment by MarcoZehe** [comment]
@mjbvz Does the web view use HTML, like the img or figure/figcaption elements? If so, the role "document" is appropriate here, too. If the image gets a proper alt text, screen readers will be able to easily convey that this is an image preview. And for that, browse mode/treating this like a document is appropriate, too.

**Comment by mjbvz** [comment]
Yes all webviews use full html documents. 

I've updated to PR to mark the outer document of all webviews with `role="document"` which I believe should work but I'll need help testing the change. Individual webviews can then set `role="application"` in their html content if appropriate

**Comment by MarcoZehe** [comment]
Question: Should the other explicit role"document" that were committed be reverted if this lands so there is no duplication and no unnecessary code accumulating?

**Comment by isidorn** [comment]
@MarcoZehe good question, however those other components do not use webviews. Thus there is no duplication, they have to set it explicitly.
@mattbierner PR looks good, adding approved. You can merge it in when you are comfortable with the change.

**Review by isidorn — APPROVED** [review]

**Pull request merged**
