### PR TITLE
Reinstate command items when filtering checkout quickpick (fix #202870)

### LINKED ISSUE #202870: Branch selection should always offer 'create' and 'create from'
Type: <b>Bug</b>

Expected:
Branch selection used to offer 'create' and 'create from', and use the currently entered value as the branch name for create.
In stable this works:
image

Actual:
Branch selection quick pick does not show create or create from.
In pre-release it does not:
image

VS Code version: Code - Insiders 1.86.0-insider (0b571a26e213bf1ec6266e37152ced80c006bd1e, 2024-01-18T05:36:10.559Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (14.73GB free)|
|Process Argv|--folder-uri file:///c%3A/GIT/formatters/vscode-autopep8 --log info --crash-reporter-id 4fb1ebc1-cf4c-4880-a88a-47738ec3768d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
ruff|cha|2024.2.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
copilot|Git|1.152.662
copilot-chat|Git|0.12.2024011901
remotehub|Git|0.63.2024010901
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.79.2024011911
vscode-docker|ms-|1.28.0
vscode-language-pack-de|MS-|1.85.2024011709
black-formatter|ms-|2023.9.10171009
debugpy|ms-|2023.3.13341008
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.11.6
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.41.2023121801
remote-server|ms-|1.5.0
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vsc_aacf:30263846
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772

```

</details>

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This fixes #202870.

When filtering the checkout quickpick the command entries are retained but demoted to the end of the list.

### CODE REVIEW

**Review by gjsjohnmurray — COMMENTED** [review]
/assign @lszomoru

**Comment by lszomoru** [comment]
@gjsjohnmurray, thank you very much for the contribution. Before getting this into the `vscode.git` extension I would like to give @TylerLeonhardt an opportunity to chime in to see whether it would make sense to have this added to VS Code core instead of the extension. Essentially we would like to show quick pick items marked as `alwaysShow` at the end of the list when searching.

**Comment by lszomoru** [comment]
@gjsjohnmurray, thanks again for the contribution. I have pushed a commit to the PR so that we do not have to filter the quick pick items when the value of the input field changes. I have tested the changes but I was wondering if you could take a look to make sure that I did not miss something. Thanks!

**Comment by gjsjohnmurray** [comment]
Seems good to me. Thanks for the improvement.

**Review by lszomoru — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Pull request merged**
