### PR TITLE
Git submodules support.

### PR DESCRIPTION
**Pull request by petkahl**
Basic support for #7829.

Automatically add submodules of added git repository when adding the repository.

When a repository is shown in the Index or Working tree resource groups, clicking on them does nothing. It would be better if either an informational message was shown, or the focus was shifted to that submodule in the Git view, but I'm not completely sure how to do the first, and the second doesn't seem possible at the moment.

### CODE REVIEW

**Comment by Chinafreak** [comment]
+1 I'm missing this features!

**Comment by petkahl** [comment]
@joaomoreno , I don't want to push or get in the way of the team's workflow, but is there anything I could do to help this along?

**Comment by joaomoreno** [comment]
@petkahl There were a few issues with this PR:

- Big no no with using sync FS calls, I changed it to async
- Parsing `git submodule status` seems flaky, so I changed it to manually parsing the `.gitmodules` file
- There was no use for the submodule status, so I removed it
- A lot of integration was missing (stage, unstage, revert, open, etc.)

Nevertheless, big thank you for pushing this forward! I have merged your changes into [`joao/submodules`](https://github.com/Microsoft/vscode/tree/joao/submodules) and I'm fixing up the issues as well as filling the blanks there. This PR will be closed as soon as that branch is merged to `master`.

**Comment by petkahl** [comment]
I was thinking the submodule status would be useful for adding the capability to initialize the submodule from the UI, but I never got around to doing it, so for now removing it out is the right choice. 
After this hits master, I may go work on some enhancements like that. For now I'm content to look at the changes you've made to understand them and hopefully make my next PR more straightforward to integrate.
Thanks!

**Pull request merged**
