### PR TITLE
Using Offset instead of address from disassembly

### LINKED ISSUE #129572: "Remove all breakpoints" does not remove instruction breakpoints
Testing https://github.com/microsoft/vscode/issues/129161

@yuehuang010, @xisui-MSFT 
found by @yannickowow 

1. Open disassembly view, add instruction breakpoints
2. Context menu in the breakpoints view > remove all breakpoints
3. Instruction breakpoints do not get removed 🐛

### PR DESCRIPTION
**Pull request by yuehuang010**
Refactor to use offset and a constant memoryReference from stackFrame. #129655
Fix an issue when scrolling too fast by using a "lock".  
RemoveAllBreakPoint will also remove InstructionBP. #129572

This PR fixes #129572 #129655

@isidorn @weinand

### CODE REVIEW

**Comment by isidorn** [comment]
This looks good, however changing offsets are imho always a bit risky, so I would prefer to merge this in start of next week.
Thus assigning to August.
If you would really like this to ship as part of the July release please let me know.

**Comment by yuehuang010** [comment]
@isidorn Sounds reasonable.  I will like to fix the BP and scrolling issue.

**Comment by xisui-MSFT** [comment]
I think you need to update currentAddress on stack frame changes? I would suggest not to update current address in the reset function, and instead, change the `ResetInstructionAddress` function to only reset the offsets (function name starts with lower case, btw). This would make #129721 easier.

**Comment by yuehuang010** [comment]
Abandon for now.

**Pull request closed without merging**
