### PR TITLE
Fixed Alt+Click Multi-Cursor menu label

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kieferrm** [comment]
The label shows the consequence of the action. The action switches the modifiers you can use when setting multiple cursors. It seems to work as expected.

**Comment by rtbz** [comment]
@kieferrm Here is what I see on MacOS:

multi

My settings map Multi-Cursor mode to Cmd, yet the menu suggests that I should use Alt (which is the wrong modifier.)

**Comment by kieferrm** [comment]
@rtbz what you see in the menu is an action, just like "Select All". When you execute "Select All" all text is selected. Same for "Switch to Alt-Click for Multi-Cursor". When you execute it, you switch from Cmd click to Alt click to set multiple cursors. I.e. this action, changes the entry in your settings and thus changes the behavior of VS Code.

**Comment by rtbz** [comment]
@kieferrm Ah, I see!  My mistake.

**Pull request closed without merging**
