### PR TITLE
Edit for the style bug when workbench.editor.tabCloseButton is set to "left"

### LINKED ISSUE #158625: Style bug when workbench.editor.tabCloseButton is set to "left"
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS 12.5

Steps to Reproduce:

1. Set `workbench.editor.tabCloseButton` to `left`
2. Look at the tab's close button - it's too far to the left, butting up against the start of the tab (especially noticeable when hovered over) compared to when set to `right`

Comparison:

image

image

### PR DESCRIPTION
**Pull request by ghost**
Fixes #158625

https://user-images.githubusercontent.com/98463228/190853408-b263b8b6-556f-4b3c-a03a-b1413d1602c8.mp4

### CODE REVIEW

**Review by daviddossett — DISMISSED** [review]
Looks good. Thanks!

**Comment by bpasero** [comment]
I wonder, why have margins at all?

This is button the right hand side:

image

This is after this change:
image

And this is without margins:
image

**Comment by bpasero** [comment]
I am mainly referring to https://github.com/microsoft/vscode/issues/158625#issuecomment-1221233526 where this was introduced.

**Comment by najmiehsa** [comment]
oh ok. I thought I should give an answer, maybe I was wrong?!

**Comment by bpasero** [comment]
My preferred fix I think would be to just undo the explicit `margin-right` that was added, not introduce another `margin-left`. But in the end the gap should just be the same for tab buttons left or right.

**Comment by najmiehsa** [comment]
ok. I can check that and remove the ``margin-right`` property altogether in this PR.

**Comment by najmiehsa** [comment]
Edit based on the comments  https://github.com/microsoft/vscode/pull/161170#issuecomment-1253743847

[screen-recorder-wed-sep-21-2022-18-38-36.webm](https://user-images.githubusercontent.com/98463228/191528683-ecca1380-8bd4-4760-9655-446d2e6464ed.webm)

**Review by bpasero — APPROVED** [review]

**Pull request closed without merging**
