### PR TITLE
Unbiased uri utils

### PR DESCRIPTION
**Pull request by jrieken**
Another step towards https://github.com/microsoft/vscode/issues/93368

### CODE REVIEW

**Comment by jrieken** [comment]
@bpasero with this change a few of these tests fail: https://github.com/microsoft/vscode/blob/f7dde7f949eec423ca0b0326338f6334a484ca16/src/vs/platform/backup/test/electron-main/backupMainService.test.ts#L694

I am not sure if the test is to blame of if the backup main service should use a different compare logic (which it shouldn't because it trust documents from the renderer, right?)

**Comment by jrieken** [comment]
>  I believe we could have the IURIIdentityService also in electron-main, quite sure the IFileService is also there which could tell which IExtUri to use.

Really? How does the synchronisation of file system providers etc work across processes? I'd rather opt for a local change in your service then. Basically copy (or keep) the case-ignore logic as of today use that in the service then.

**Comment by bpasero** [comment]
@jrieken on `electron-main` there is only the local disk based file system provider where we currently hardcode that mac & windows are case-insensitive. I was not suggesting that `electron-main` has the same file service as renderers.

**Comment by jrieken** [comment]
Ah, understood. I think we are basically on the same page. There is `ExtUri` implementation which takes a function to decide if a scheme means case ignore or not. You can use that - plain or wired  into the (main side) file service.

**Comment by bpasero** [comment]
@jrieken I pushed my changes to use a custom `ExtUri` for selected `electron-main` pieces to `master` and merged that change back into this branch. At least the backup main service tests should be fine then.

**Comment by jrieken** [comment]
Thanks @bpasero. I'll see what else is going wrong here...

**Comment by sandy081** [comment]
@jrieken Removed the usage of biased utility in `fileUserDataProvider` with `extUri` created using the provider's capabilities.

I could not use `IUriIdentityService` because `fileUserDataProvider` is created along with initial services where `IUriIdentityService` is not available. Hence created `extUri` by checking the data provider's capability, which makes it unbiased - d6d6fb2cbf563b641ff7d86b1af5fd2d5fd66e25

**Comment by jrieken** [comment]
Thanks @sandy081

**Pull request merged**
