### PR TITLE
Add icon exploration to master

### PR DESCRIPTION
**Pull request by miguelsolorio**
This adds the [icon exploration](https://github.com/microsoft/vscode/issues/8017) to `master` so that we can start testing on insiders. I'd like to scope the exploration to a single style (Outline) to scope the feedback since this is the version that has received the most positive feedback. I've also changed this to a user setting, so in order to enable this set `workbench.iconExploration.enabled` to `true` in your user settings:

image

cc @Tyriar @bpasero

### CODE REVIEW

**Comment by bpasero** [comment]
@misolori for selfhosting is there a way to get the new icons without forcing an icon theme onto me? I am never using icons in selfhosting but still would like to enable the new icons somehow. Ideally we have a solution that is independent from the icon-theme.

**Comment by isidorn** [comment]
Yeah, just push it to master that way you will get more feedback than you can handle.
I like the approach you took in the user studies to give more focus to feedback after a couple of days once the users get used to the change. I would take the same approach with Insiders.

**Comment by misolori** [comment]
I'll work on adding a setting instead of using file icons

**Comment by misolori** [comment]
@bpasero this is now a user setting, you can enable it via `"workbench.iconExploration.enabled": true`, which means you can now use any file icon you wish. Assigning this to you since I've added this to the layout service as it was the easiest place to make the change (talked to @sbatten about it). 

I placed todos for myself to clean this up before we ship stable as we don't want this to ship. Once we're ready to integrate these changes (hopefully by the end of the month 💪) I'll create a separate branch that will update our real icons.

**Review by bpasero — APPROVED** [review]
@misolori thanks, this is better to selfhost on.

Out of curiosity: we seem to be introducing new colors in the icons.css file as background? Should these colors be controled by theme authors eventually?

**Comment by bpasero** [comment]
@misolori I also feel the icons in the activity bar are not aligned nicely.

Screenshot 2019-06-05 at 08 35 49


PS: with the thinner icons we could maybe reduce the activity bar size from 50px to 45 or even 40?

**Comment by misolori** [comment]
@bpasero for the colors, yes these would be great to have these controlled by themes eventually. For the exploration I just used masks to make it easier to change the color on the fly, I wouldn’t use this method for when we update stable due to limited cross-browser support for masks. There’ll be a separate effort to update how we consume icons and allow themes to control the color (at least that’s my goal). 

I’ll look into the alignment of the activity bar icons. And we can also reduce the activity bar a bit so it fits better with the icons.

**Pull request merged**
