### PR TITLE
Allow interactive window to scroll beyond end (#127578)

### LINKED ISSUE #127578: Interactive window doesn't allow scrolling past the end
Testing #127378

image

Old IW allowed the user to have a full page of blank space at the bottom.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #127578

To test:

1. Install a notebook extension that implements an interactive window.
2. Open an interactive window and run some commands.
3. Verify that the scrolling region above the interactive input field can be scrolled to leave blank lines between the last output cell and the interactive input field.

/assign @rebornix

ping @rchiodo

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by rebornix** [comment]
@gjsjohnmurray thanks for the contribution. I think we did this intentionally, I can't recall all the reasons (cc @joyceerhl) but we might need to check if auto scrolling still works with this enabled.

**Comment by gjsjohnmurray** [comment]
@rebornix do you need anything from me on this?

**Comment by joyceerhl** [comment]
@rebornix I don't recall any specific reason we'd disallow scrolling past the end 🤔 also I moved this one to June 2022, hope that is OK!

**Comment by gjsjohnmurray** [comment]
Can this be merged now, or does it need more work?

**Comment by gjsjohnmurray** [comment]
Can this get merged in time for July endgame?

**Comment by gjsjohnmurray** [comment]
Please merge this soon so it gets plenty of exercise in Insiders.

**Review by amunger — CHANGES_REQUESTED** [review]
tested this out, and it does not play well with the latest auto-scroll changes - resizes and executions will scroll the window as far down as it can go

**Comment by gjsjohnmurray** [comment]
I confirmed that this PR is not only redundant as a consequence of improvements elsewhere, but that it actually now makes things worse. Closing unmerged.

**Pull request closed without merging**
