### PR TITLE
Delete hide assignment in _adoptConfiguration*

### LINKED ISSUE #197390: Hidden Task Hiding Nonhidden Dependson Task
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Windows 22H2

When a hidden task that has a "dependson" with a non-hidden task, it will hide that task too after being ran.

Steps to Reproduce:

1. Create example .vscode/tasks.json
    ```json
    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "nonhidden task",
                "type": "shell",
                "command": "echo nonhidden"
            },
            {
                "label": "hidden task",
                "dependsOn": ["nonhidden task"],
                "dependsOrder": "sequence",
                "type": "shell",
                "command": "echo hidden",
                "hide": true
            },
            {
                "label": "Run hidden task",
                "dependsOn": ["hidden task"],
                "dependsOrder": "sequence",
                "type": "shell",
                "command": "echo Run hidden"
            }
        ]
    }
    ```
3. Open "Tasks: Run Task" in the command pallet
4. Observe "nonhidden task" and "Run hidden task" are available to run
5. Run "Run hidden task"
6. Open "Tasks: Run Task" in the command pallet
7.  Observe "nonhidden task" is now missing. Only "Run hidden task" is available

### PR DESCRIPTION
**Pull request by tisilent**
fix #197390

### CODE REVIEW

**Comment by tisilent** [comment]
@meganrogge hi .
The hide of dependent tasks should not be affected by other tasks.
I don't know if this will affect the design. 😄

**Comment by meganrogge** [comment]
@alexr00 looking at the code, I'm wondering if this was by design?

**Review by alexr00 — COMMENTED** [review]
@meganrogge I think you added the `hide` property, but it seems ok to delete this.

**Review by alexr00 — COMMENTED** [review]
@meganrogge I think you added the `hide` property, but it seems ok to delete this.

**Review by meganrogge — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]

**Pull request merged**
