### PR TITLE
Extend anythingQuickAccess to provide a quickAccess file search that ignores exclusions

### LINKED ISSUE #15604: Simple way to temporarily turn off exclusions for QuickOpen files
Using a transpiled language I sometimes find the need to look at the transpiled code which typically is excluded from QuickOpen. Having a simple way to turn exclusions off would simplify this. Some options come to mind:
- Have a 'Turn Off Exclusions' entry at the end of the results list.
- Have an additional QuickOpen prefix that runs QuickOpen with exclusions turned off.
- Have an option toggle next to the QuickOpen entry field to turn exclusions off.

### PR DESCRIPTION
**Pull request by jzyrobert**
This PR fixes #15604

Video demo:

https://user-images.githubusercontent.com/20613660/175842621-b7fd9810-bae1-4658-bbc0-8b465dc91316.mp4

 This PR comes with 4 changes:
* Modifying `anythingQuickAccess` to make several properties `protected`, making the constructor prefix an argument, and refactoring the `IFileQuery` creation to pass through a helper function
* Creating `anythingQuickAccessWithoutExclusions` and overriding the prefix and `createFileQuery` function such that any query passing through is stripped of all excludes in `folderQueries`. `IFileQuery` itself has a `excludePattern` field but checking it during debugging it seems to be `undefined` for a default search.
* Creating and registering an `Action2` for the new class that uses `Ctrl` + `Alt` + `P` as the command and `!` as the prefix (should this stay in the same class?)
* Registering the new class as a `QuickAccessProvider` (here I feel like another PR could be needed to show the placeholder when the input is just the prefix but not empty, there is a placeholder also defined for `SymbolsQuickAccessProvider` but its never used either

### CODE REVIEW

**Comment by roblourens** [comment]
I will take a look at this next week, thanks

**Comment by roblourens** [comment]
We plan to take a closer look at the general experience around quick accesses in vscode. I want to keep this PR around but probably won't look at it in the short term

**Comment by asteele0** [comment]
@roblourens It's been over a year since this PR was opened, and almost 7 years since the original issue #15604 was opened.
It would be great if something can be done about it. This is a present issue in many developers' workflows (including mine).

**Comment by patrickhuy** [comment]
@TylerLeonhardt @roblourens  This feature sounds massively useful, is there a way to drive it forward?

**Comment by TylerLeonhardt** [comment]
There are some merge conflicts here but actually I'd like to explore using an in-line button & toggles in the Quick Pick to provide this functionality so I think this direction of having a separate command is not the direction we want to go. Thanks for providing feedback and contributing!

**Pull request closed without merging**
