### PR TITLE
Migrate fixed dom context views into Shadow DOM

### LINKED ISSUE #98673: Adopt shadow dom for the context view service
PR #97965 fixes issues with maintaining focus inside a dom element when the context view is opened. However, by rendering as a child of other DOM elements we risk unintended DOM interaction via css or otherwise. As a workaround for now, this has been scoped to a handful of widgets that need the behavior change. Now we have debt that we should invest in making the context view a shadow dom node that has all of its css injected to avoid unintended interaction.

/cc @joaomoreno

### PR DESCRIPTION
**Pull request by sbatten**
This PR fixes #98673

@joaomoreno for context view
@bpasero for general review (menu widgets)
@alexdima for css technique

I am only adopting the shadow dom feature for the menu widget for now to allow us to test this approach safely. If we want to try this out this milestone, we should merge it ASAP. PTAL and mention any blockers for proceeding.

### CODE REVIEW

**Review by alexdima — APPROVED** [review]
:+1: Works well! I've also tried the standalone editor hosted in a shadow dom and that works well too.

**Comment by sbatten** [comment]
@alexdima thanks for the review

**Comment by joaomoreno** [comment]
@sbatten I was saving this for tomorrow 😢 sorry for the delay. Will test it in Insiders properly.

**Comment by joaomoreno** [comment]
@sbatten Found the following issues:

- https://github.com/microsoft/vscode/issues/103166
- https://github.com/microsoft/vscode/issues/103167
- https://github.com/microsoft/vscode/issues/103169
- https://github.com/microsoft/vscode/issues/103170
- https://github.com/microsoft/vscode/issues/103171

**Comment by bpasero** [comment]
I think this change caused https://github.com/microsoft/vscode/issues/189305

**Pull request merged**
