### PR TITLE
Allow scss files to optionally be used instead of css files

### LINKED ISSUE #8589: Use Sass for vscode's styles
@bpasero thoughts on this? I'd like to give this a shot at some point if everyone is cool with it. The reasons for doing so are:
- [libsass](https://www.npmjs.com/package/node-sass) is very mature and on par with the original ruby lib in terms of features
- Significantly reduce the size and complexity of our development css files through leveraging nesting, for example this:
  
  ``` css
  .monaco-workbench .panel.integrated-terminal .xterm {
    background-color: transparent!important;
    position: relative;
  }
  
  .monaco-workbench .panel.integrated-terminal .xterm:focus {
    outline: none;
  }
  
  .hc-black .monaco-workbench .panel.integrated-terminal .xterm:focus {
    outline: 2px solid #f38518;
  }
  ```
  
  becomes:
  
  ``` scss
  // In a shared file
  $hc-outline-color: #f38518;
  
  .monaco-workbench .panel.integrated-terminal .xterm {
    background-color: transparent!important;
    position: relative;
  
    &:focus {
        outline: none;
  
        .hc-black & {
            outline: 2px solid $hc-outline-color;
        }
    }
  }
  ```
- We could leverage Sass variables (compile time) for non-themeable colors in addition to CSS variables for themeable colors (#8151). Sass variables can also be used for reusable images, media queries, margins, etc.
- Use of `//` comments are not included in compiled CSS, meaning we can add more documentation to complex styles without worrying about it ending up in the resulting file
- Mixins for commonly used styles/media queries/etc.
- It's way more fun to write in Sass

/cc @bgashler1

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #8589

### CODE REVIEW

**Comment by joaomoreno** [comment]
cc @aeschli

**Comment by egamma** [comment]
This PR brings up the SASS vs. LESS vs. CSS only discussion that we could not agree on in the past.

We can do another attempt on this discussion, but in the end we need a team agreement and we want to be consistent across the code base.

**Comment by bpasero** [comment]
@Tyriar can we get this more robust? I am playing around with it and run it as part of my gulp watch task which runs in a terminal. While adding some SCSS (I think I renamed a CSS file to SCSS) I eventually got this:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: src/vs/workbench/electron-browser/media/shell.scss
Error: Invalid CSS after "$font-stack:": expected expression (e.g. 1px, bold), was ".monaco-shell.vs [t"
        on line 52 of src/vs/workbench/electron-browser/media/shell.scss
>> $font-stack: 
   ------------^

    at options.error (/Users/bpasero/Development/monaco/node_modules/node-sass/lib/index.js:292:26)
```

Which is pretty bad because I do not even notice when my gulp watch task stops. Even worse, it stops my TS compiler either...

**Comment by joaomoreno** [comment]
Please look at http://cssnext.io/ too

**Comment by bpasero** [comment]
@joaomoreno yeah I think we should have the discussion in https://github.com/Microsoft/vscode/issues/8589 where this was suggested.

**Comment by Tyriar** [comment]
Closing off since it's out of date. The impl is still available here if we need it.

**Pull request closed without merging**
