### PR TITLE
Fix: add alwaysConsumeMouseWheel for list

### LINKED ISSUE #113389: Suggest widget should not let scroll events escape
Right now when I scroll the autocomplete box and when it reaches the end it triggers the whole window to scroll.

What I want is that when it reaches the end then it shouldn't be moving as long as the cursor is inside the autocomplete box, doesn't matter how much I scroll.

### Examples about what I want
**Intellij autocomplete box:**
(When I reached the end and tried to scroll it just stopped there and that's good)

**VS Code autocomplete box:**
(When I reached the end and continued scrolling while my cursor was in the box itself the scrolling didn't stop there and it triggered the whole window to scroll and that's something bad I guess)

**I'm looking forward to hearing other's opinions on this.**

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #113389

Add `alwaysConsumeMouseWheel` for `List`

### CODE REVIEW

**Comment by JacksonKearl** [comment]
Oops, I was testing something out and expected the "update branch" button to not immediately act. Shouldn't change anything.

**Comment by susiwen8** [comment]
@joaomoreno Hi, do you got chance to review this?

**Comment by susiwen8** [comment]
@joaomoreno Hi,  got time for this?

**Comment by joaomoreno** [comment]
Sorry @susiwen8, I'll make sure this goes in the February release.

**Review by joaomoreno — APPROVED** [review]
@jrieken Changes are good, tested them myself. So if the behavioral change is good for you, let's merge this in.

**Review by jrieken — APPROVED** [review]
lgtm

**Pull request merged**
