### PR TITLE
Investigate Electron 3.0.x

### PR DESCRIPTION
**Pull request by bpasero**
WIP (for #52629), not to be merged until Electron 3.0.x is declared stable and we are happy with it.

**Changelog:**
* Chrome: `61` => `66`
* node.js `8.9.1` => `10.2.0`
* libuv `1.15.0` => `1.20.3`

**VSCode Exploration Builds with Electron 3.0.x:**
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

### CODE REVIEW

**Comment by NateLing** [comment]
I think we can wait for Chrome 70. that version is a big upgrade.

**Comment by Tyriar** [comment]
@NateLing we're trying to keep up to date with Electron. If we waited for a Chrome 70 Electron and jumped to that, it would be a lot harder to stabilize as it's jumping 9 Chromium versions.

**Comment by bpasero** [comment]
I updated to Electron 3.0.0-beta.5

**Comment by shizonic** [comment]
Build fails with: `Module not found: Error: Can't resolve ./api/git`

**Comment by shizonic** [comment]
@bpasero Thanks. Since last merge of master branch this issue is fixed during building. :+1:

**Comment by beastdestroyer** [comment]
@bpasero Setting the window style to native causes this: 
image

**Comment by bpasero** [comment]
@beastdestroyer thanks, but that is unrelated to Electron. it should be fixed tomorrow

**Comment by bpasero** [comment]
@Astrantia no, we are 2-3 months away from landing this.

**Comment by mxschmitt** [comment]
@bpasero Electron 3.0.0 was released yesterday: https://electronjs.org/releases#3.0.0

**Comment by Astrantia** [comment]
@bpasero Now that electron v3 is stable, are we still looking at 2-3 months release time? 😀

**Comment by bpasero** [comment]
Yeah thats a good guess.

**Comment by beastdestroyer** [comment]
@NateLing he still needs to test many things to ensure that Electron 3.0.x will work, such as storage, autocomplete, menus etc. Plus he said it would take roughly 2 - 3 months to ship in insiders meaning we could see an electron 3 insiders in november or in 2019. I believe the team also said there won't be a december update too.

**Comment by bpasero** [comment]
Exploration builds will probably be updated to use Electron 4.0 and continue to be Electron version +1 in the future.

**Comment by NateLing** [comment]
@beastdestroyer  @bpasero  thx, i use VSCode from first version. now it is my main IDE, sometimes use idea. i love VSCode.

**Comment by bpasero** [comment]
@beastdestroyer well, depends what you mean. Extensions will run in an environment that matches that node version but for compiling VSCode you would not have to install node 10.2.0

**Comment by beastdestroyer** [comment]
Ah I see, because Node.js 10 went LTS today so I was thinking that VSCode might have to ctach up, thanks for the info/

**Comment by beastdestroyer** [comment]
@bpasero I know you're probs aware of this but there is electron@3.0.10 now

**Comment by shizonic** [comment]
@bpasero is it possible to build (release) the electron 3 branch by myself using azure?

**Comment by bpasero** [comment]
@shizonic yes if you follow https://github.com/Microsoft/vscode/wiki/How-to-Contribute from the `electron-3.0.x` branch

**Comment by beastdestroyer** [comment]
image
This happened to my terminal after your commit @bpasero

**Comment by Tyriar** [comment]
@beastdestroyer looks like this? https://github.com/Microsoft/vscode/issues/57803

**Pull request merged**
