### PR TITLE
Fix missing active debug line + breakpoint glyph

### LINKED ISSUE #137436: Breakpoint Indicator Is Missing For Active Line
recording

It could be that I caused this, but I doubt it (injected text has nothing to do with the gutter, maybe they shared a CSS rule).

### PR DESCRIPTION
**Pull request by mamphis**
This patch resolves #137436.
When multiple classes (e.g. codicon-debug-breakpoint,codicon-debug-hint)
are added they would disable the ::after content for consecutive classes
for the HTML Element.

This patch adds a parent element to the overlay and adds all classes as
seperated divs, so they can be drawn on top of each other.

This PR fixes #137436.

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks, but do you happen to know why it broke?

**Comment by hediet** [comment]
I think my commit https://github.com/microsoft/vscode/commit/49efe65bc3769cff56182bfd5ce881fa4654ca6a broke it.

Maybe it is the rule `.codicon-debug-breakpoint.codicon-debug-stackframe::after` that I might deleted by accident.

I think it would be easier to add that rule back instead of the fix suggested by this PR.

**Comment by hediet** [comment]
Thank you!

**Comment by mamphis** [comment]
@hediet I think that might be the case. Because the content of `.codicon-debug-breakpoint.codicon-debug-stackframe::after` is `\eb8a` which differs from `.codicon-debug-breakpoint::after` and `.codicon-debug-stackframe::after`.

Reverted in the last commits. Works like a charm.

image

**Comment by gjsjohnmurray** [comment]
Maybe edit the PR title to reflect what it ended up doing?

**Pull request merged**
