### PR TITLE
Add output channel for telemetry.log file

### PR DESCRIPTION
**Pull request by ramya-rao-a**
This PR adds a output channel for the `telemetry.log` file and addresses the issue #58536

@sandy081 When opening with `--verbose` flag, the telemetry events get logged to the `telemetry.log` file right from the start. But the output channel remains blank until I close it and open it again. Any ideas why so?

Note: To test this locally, 
- remove the `isBuilt` check at https://github.com/Microsoft/vscode/blob/74b096b6be864f92cdeadae2304b7d872034669f/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L106 
- enable telemetry in product.json, provide any dummy value for aiConfig.asimovKey

### CODE REVIEW

**Comment by sandy081** [comment]
> When opening with --verbose flag, the telemetry events get logged to the telemetry.log file right from the start. But the output channel remains blank until I close it and open it again. Any ideas why so?

Its because during the time you register the channel, file does not yet exist. You have to create the channel after the file exists. May I know where do you create the telemetry log file?

**Comment by ramya-rao-a** [comment]
> May I know where do you create the telemetry log file?

The log file is created in the [shared process](https://github.com/Microsoft/vscode/blob/74b096b6be864f92cdeadae2304b7d872034669f/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L103)

> Also why not we create the channel always even if it is empty. I think its fine to have empty channels when nothing is written into it.

For other log channels, yes it is fine do to so because as the user interacts with VS Code, they will get data. But the telemetry channel will only ever get data when the log level is changed to trace. Until, then it is an unnecessary distraction. Users who see something called "Log (Telemetry)" will expect to see something there. They might be mislead to believe that we dont send any telemetry at all after seeing the empty channel

**Comment by ramya-rao-a** [comment]
I think this a generic issue and not just for the telemetry channel.

- Open the `Log (Shared)` channel
- Close VS Code, Open VS Code
- The `Log (Shared)` channel will be open, but empty and will remain empty until we change the channel

Changing channel does not re-create the channel. So I am unsure of the theory that the channel is empty because nothing is written to the log file before its creation.

**Comment by ramya-rao-a** [comment]
> Was not it true even before, when there is a command to open telemetry log file?

Yes, but you had to go looking for the command vs now when the `Log (Telemetry)` is opened and showed to the user by default when opening with `code --verbose`.

But regardless, I'll push one line to the telemetry.log file as soon as it is created to say something to the affect of "This file logs all the telemetry from VS Code when the log level is set to trace"

**Pull request merged**
