### PR TITLE
Fix Minimap AutoHide with StickyScroll Lines Running Together

### PR DESCRIPTION
**Pull request by AVividLight**
Fixes issue described in: https://github.com/microsoft/vscode/issues/188497

This change lets stickyscroll take full-width and layers it behind the minimap. To test, simply enable both StickyScroll and Minimap AutoHide, then reduce your editor width and view long lines of code.

**_Before_** (note top-right): 

Reproduced in Latest Dev

This is caused by the hiding of the minimap:

problem explaintaion

**My fix** (minimap hidden and minimap visible):

Fixed-No Minimap

Fixed-With Minimap

### CODE REVIEW

**Comment by AVividLight** [comment]
@microsoft-github-policy-service agree

**Comment by aiday-mar** [comment]
Thank you for the PR and the contribution. I just tested your PR and see the following behavior:


https://github.com/microsoft/vscode/assets/61460952/b62e9d09-d238-4529-8cf9-da78fe058e06

In fact it is also visible in your picture. There appears to be an additional empty line below the sticky scroll lines. This will need to be fixed before the PR can be merged.

**Comment by AVividLight** [comment]
> Thank you for the PR and the contribution. I just tested your PR and see the following behavior:
> Screen.Recording.2023-07-21.at.16.47.18.mov
> 
> In fact it is also visible in your picture. There appears to be an additional empty line below the sticky scroll lines. This will need to be fixed before the PR can be merged.

Thank you for your help identifying this issue, I will resolve it and update my PR.

**Comment by AVividLight** [comment]
@aiday-mar I resolved the height issue by simply removing the added auto z-order and instead lowering the z-order in the css.

**Comment by aiday-mar** [comment]
Hi thanks for the work. I tested again your work. Indeed there is no additional empty line but I see the following: the line does not take up the full width as the fix was intending to do.

https://github.com/microsoft/vscode/assets/61460952/8ef65845-5aea-4415-914c-a08b0490552c

**Comment by AVividLight** [comment]
Hi @aiday-mar

I believe the issue has been resolved in my latest commit. Please let me know if there is anything else I can do to improve the behavior.

Thanks!

**Comment by AVividLight** [comment]
Hello @aiday-mar

This is just a friendly check-in. Please let me know if there's anything I can do to improve this submission.

Thanks!

**Comment by aiday-mar** [comment]
Hi @AVividLight, thank you for the reminder, I did not receive a notification for your second to last comment. I will have a look now.

**Comment by AVividLight** [comment]
> I looked at the PR, I am not sure that we should be decreasing the z-index of sticky scroll. It leads to sticky scroll being rendered behind some other widgets, which it should render above, for example:
> Screenshot 2023-07-28 at 15 11 34
> 
> Ideally the sticky scroll z-index should not change.

@aiday-mar Thanks for taking another look at this! I agree that the z-index is an issue in the image you posted, but if we don't change the z-index of stickyscroll, it is higher than the minimap:

image

Would changing the z-index of the minimap be more acceptable than stickyscroll?

Thanks!

**Comment by aiday-mar** [comment]
@alexdima thoughts concerning changing the z-index of the minimap?

**Comment by AVividLight** [comment]
Hi @aiday-mar @alexdima @jrieken

I just wanted to check-in on this. Thanks for your help!

**Comment by AVividLight** [comment]
Hello @aiday-mar @alexdima @jrieken

I just wanted to keep this on the radar.

Thanks!

**Comment by AVividLight** [comment]
I see that there have been some changes to stickyscroll- I'll rework this PR if the issue still persists.

However, I think the question of how to change the z-index still remains.

**Comment by AVividLight** [comment]
Hi @aiday-mar @alexdima @jrieken

I have verified that the problem still exists at the tip and rewrote my fix in https://github.com/microsoft/vscode/pull/188499/commits/84cacabbc400c27e38efaf804836f8da1b1e1fb5 

I'm still hoping you'll have some direction for the z-index issue; now that stickyscroll takes the full width, it will be layered above the minimap, which looks bad and covers part of the scrollable area (see attached image)

Screenshot 2023-08-08 210933

However, as aiday-mar pointed out, simply changing the z-index to zero, as I have, breaks the layering of some other modules.

Thanks for your help with this!

**Comment by AVividLight** [comment]
Hello @aiday-mar @alexdima @jrieken

This is just a friendly ping. I'm hoping for some direction on changing the z-index for the minimap.

Thanks!

**Comment by jrieken** [comment]
@AVividLight We are looking into this but please stop pinging us every day.

**Comment by aiday-mar** [comment]
Hi @AVividLight, thank you for your valuable contribution. We discussed your PR with the team. You can increase the z-index of the minimap. I suggest increasing just sufficiently so that it appears above sticky scroll. I will then verify that nothing is broken from this change.

**Comment by AVividLight** [comment]
Great, thank you both for the update! I'll look into adjusting the minimap z-index and will update the PR when I have a solution.

I appreciate the help!

**Comment by aiday-mar** [comment]
Hi @AVividLight, it looks good!

**Comment by AVividLight** [comment]
@aiday-mar Thank you so much for your help throughout this process! What are the next steps?

**Comment by aiday-mar** [comment]
Hi @AVividLight, a second member of our team must review and approve the PR. Once it is approved by two team members it will be merged into the code-base.

**Comment by AVividLight** [comment]
Hi @aiday-mar I just wanted to check in on the review. How long should I expect the review to take, and am I expected to continually update the code to resolve conflicts while waiting? Thanks for your help!

**Review by aiday-mar — APPROVED** [review]

**Review by alexdima — APPROVED** [review]

**Comment by aiday-mar** [comment]
Hey @AVividLight, apologies for the delay in approval and merging. Great work in this PR!

**Pull request merged**
