### PR TITLE
Show number of selected lines in status bar

### LINKED ISSUE #154327: Show number of selected lines in the status bar
When I highlight multiple lines, sometimes I want to know how many lines they are.

Right now the status bar only shows selected characters.

I don't think users should rely on an extension for this.

https://stackoverflow.com/questions/61339515/how-to-set-vscode-to-display-the-number-of-selected-lines

https://marketplace.visualstudio.com/items?itemName=gurumukhi.selected-lines-count

### PR DESCRIPTION
**Pull request by ushuz**
Display line count of current selection in status bar, e.g. `(2 lines, 5 chars)`.

Fix #154327

image

### CODE REVIEW

**Review by ProKashif — DISMISSED** [review]

**Comment by ushuz** [comment]
@bpasero May I ask what exactly is blocking this PR? Cause the change is fairly small and easy to review IMO. Anything I can help to speed things up?

**Comment by bpasero** [comment]
Nothing is blocking this PR other than a review from me and a decision if we want to have it or not. I typically find time to review PRs in our issue grooming iteration in October/November of a year.

**Comment by wmentha** [comment]
Hey @ushuz, I made some updates in https://github.com/microsoft/vscode/commit/b5d51d3132fd3d2c16f5470a72f51f895e4fe09d. Check it out and let me know what you think 😊

**Comment by ushuz** [comment]
> Hey @ushuz, I made some updates in [b5d51d3](https://github.com/microsoft/vscode/commit/b5d51d3132fd3d2c16f5470a72f51f895e4fe09d). Check it out and let me know what you think 😊

@wmentha Hi, thanks for the heads up. As long as there's line count, I'm fine.

**Comment by wmentha** [comment]
> @wmentha Hi, thanks for the heads up. As long as there's line count, I'm fine.

@ushuz  I've added an improvement to the line count algorithm so it takes multiple selections on a single line into account. Take a look:

LineCount

The commit can be found here: https://github.com/microsoft/vscode/commit/61493926ba2af7407ca45d3964cb2eb711860ab5 😊

I thought selections might have been a misnomer as a selection with no content is just a cursor, however we don't distinguish between multiple selections that contain content or no content at the moment:

LineCountCursors

As you can see, I don't count a **cursor** as adding to the line count. Thoughts?

**Comment by bpasero** [comment]
Should this be behind a setting at least? Screen real estate in the status bar is always a problem and this change forces every user to have less space, even when maybe not interested in the selected lines?

**Comment by bpasero** [comment]
@wmentha oh very cool! I would be interested in a setting like that maybe with support for line count and support for concise format. We can have the setting on the `workbench.editor.*` settings scope, I think it should not be on the `editor.*` spectrum because it only applies to the VSCode, not Monaco Editor standalone. 

**To summarise:** 
* we introduce a new setting that allows to adjust how editor selection is presented in the status bar
* we optionally allow to show line count
* we optionally allow a concise form

Maybe then we have an enum of 3?
* `default`: as today
* `concise`: a new short form
* `long`: including line count

?

**Comment by wmentha** [comment]
Awesome! I think this covers the best off all worlds 😊 Since many extensions make liberal use of the status bar, I think customisation of how much is displayed by what is built into the status bar is important. I'll get onto it with your suggestions 👍

**Comment by ushuz** [comment]
@bpasero @wmentha 

If this is desirable, may be this setting could be made into a format string, so users can configure it to whatever they like.  Something like `"Ln ${lineNo}, Col ${colNo} (${charSelected} selected)"` could be set as the default value to keep it looking the same as today.

**Comment by bpasero** [comment]
I thought about it but felt it might be an expensive feature because we literally update the status bar on each caret move. I think having such flexibility is a bit overkill at the cost of having to dynamically figure out the format and apply it?

**Comment by wmentha** [comment]
Also the issue of plurality for different languages when it comes to character(s) selected.

**Comment by wmentha** [comment]
@ushuz May I ask permission to contribute to this PR on your branch? 😊

**Comment by ushuz** [comment]
> Also the issue of plurality for different languages when it comes to character(s) selected.

If we take i18n and l10n into consideration, how would the `concise` `long` option play out for different locales? If `concise` `long` doesn't work in all locales, this setting may not make sense.

In that case, how about just dropping the `selected` from the label (which is implied and unnecessary IMO, I kept it only to make my change as small as possible), and trade the status bar real estate for the `xxx lines`?

**Comment by wmentha** [comment]
`2 Selections (3 Selected)` reads awkwardly in my view. Perhaps this is what **concise** can be for. So 4 possible options in the enum:

- `default`
- `line-count`
- `concise`
- `concise-line-count`

**Comment by bpasero** [comment]
The support for different languages is a good point, I think I would expect:
* the `concise` format to only show numbers and maybe colons? Should compare with how other editors present this maybe
* the `default` format to work as today
* the `long` format to be like `default` in terms of wording but with the additional selected lines

?

**Comment by wmentha** [comment]
> * the `concise` format to only show numbers and maybe colons? Should compare with how other editors present this maybe, possibly this becomes the same in all languages then?

@bpasero To be `concise` with support for selections and multiple line selections without text, we could do:

- `123 ∶ 456 (7)` from `Ln 123, Col 456 (7 characters)`
- `2 (3)` from `2 selections (3 characters selected)`

The `∶` character can provide context.

**Comment by ushuz** [comment]
> `2 Selections (3 Selected)` reads awkwardly in my view. 

It would be `2 Selections (3 chars)` by dropping `selected` and shorten `characters`.

---

> Perhaps this is what **concise** can be for. So 4 possible options in the enum:

@bpasero @wmentha 

If the setting doesn't work for all locales, which is very likely, it becomes an English-specific setting. And I don't think it's a good idea.

For example, in `zh-cn`, today's version is already concise enough and there may not be any wording more "concise". Then the `concise` option won't make any sense for users using `zh-cn` if nothing changes.

image
image

---

Also, if the primary concern here is the status bar real estate. Dropping `selected` and shortening `characters` would be more than enough to address it. Adding a language-specific setting feels even more like an overkill.

---

> To be `concise` with support for selections and multiple line selections without text
> - 123 ∶ 456 (7) from Ln 123, Col 456 (7 characters)
> - 2 (3) from 2 selections (3 characters selected)

@wmentha's new proposal is an interesting idea and worth exploring. However, I think it's beyond the scope of this change, and should be discussed separately.

**Comment by ushuz** [comment]
What's more, inconsistency and abbreviation already existed in the current codebase. 

It's `Line` and `Column` here.

https://github.com/microsoft/vscode/blob/6cd856c6c5b95dadbb20e0571f51b6ddfcc06a10/src/vs/editor/common/standaloneStrings.ts#L10

And `Ln` and `Col` here.

https://github.com/microsoft/vscode/blob/6cd856c6c5b95dadbb20e0571f51b6ddfcc06a10/src/vs/workbench/browser/parts/editor/editorStatus.ts#L293

---

So dropping `selected` and abbreviating `characters` could be acceptable. Also it's much easier to implement and less complication to worry about than adding a new setting.

**Comment by bpasero** [comment]
Fyi I will depart from this discussion in the PR until I am returning from my vacation end of October. I think the details still have to be figured out and I can review the changes when I am back.

**Comment by ushuz** [comment]
> @ushuz May I ask permission to contribute to this PR on your branch? 😊

@wmentha Sorry I missed this earlier. As we haven’t reach a consensus yet, I think it would be better to branch out so we have more options going forward. Feel free to use any of my code if you need, my pleasure.

**Comment by bpasero** [comment]
Is this PR still active?

**Comment by ushuz** [comment]
> Is this PR still active?

Of course, waiting for your review

**Review by bpasero — CHANGES_REQUESTED** [review]
I am not seeing a setting for this as I had asked for in https://github.com/microsoft/vscode/pull/156086#issuecomment-1259076938, so this change cannot go in like that.

Besides, changing the accessibility label for screen readers is something we need to coordinate with accessibility champs: @meganrogge @isidorn can maybe chime in whether we should announce the number of selected lines to the screen reader. I am fine to do this without an extra setting if we feel this is a good change that helps accessibility.

**Comment by isidorn** [comment]
@bpasero for accessibility I believe most users get line number information by pressing Cmd/Ctrl + G and using Quick Open. Maybe that quick open should also say how many lines are selected.
@meganrogge thoughts?

**Comment by meganrogge** [comment]
I don't think there's a harm to announcing the number of selected lines, so I agree with @isidorn that the quick open could indicate that. Maybe it could announce the line range ? "Line 1, char 3 to line 5, char 7 selected"

**Comment by ushuz** [comment]
@bpasero 

> I am not seeing a setting for this as I had asked for in [#156086 (comment)](https://github.com/microsoft/vscode/pull/156086#issuecomment-1259076938), so this change cannot go in like that.

About this, I've gave my thoughts on why the proposed setting may not be a good idea in https://github.com/microsoft/vscode/pull/156086#issuecomment-1259105986. I haven't received any feedback untill now. Is it already decided?

**Comment by ushuz** [comment]
@bpasero @isidorn @meganrogge 

I think accessibilty may need more careful consideration. This is a super small change for fully abled users, it's just a couple more characters in status bar for glimpse. But it may be quite a big change for people relying on accessibilty features. Thus I think it's outside the scope of this PR as well.

**Comment by bpasero** [comment]
Then I suggest leaving out any accessibility changes from this PR and have a separate issue and discussion for that.

As for the setting: it is likely a large set of users (maybe even the majority) that would be impacted by this change, so I still think a setting makes sense even if not applicable in all languages?

**Comment by ushuz** [comment]
@bpasero 

> As for the setting: it is likely a large set of users (maybe even the majority) that would be impacted by this change, so I still think a setting makes sense even if not applicable in all languages?

Yes, this would be rolled out to a lot of users, but it's just a *super* minor format tweak for an existing feature. It's literally just a few characters more. If we do some abbr, there may even be fewer chars than now. I doubt most of the users would even notice this change, let alone complain about a few extra chars. Besides, the current chars count isn't a particularly useful metric IMO, so I doubt the users would even care if there're changes to it.

Also, I don't think every change impacting a large number of users warrants a setting, it depends on what the impact is.

In this case, as I stated here and in https://github.com/microsoft/vscode/issues/154327#issuecomment-1194507552, the impact could be negligible. More rationale from that comment:
- line count is more useful than character count, most of the time, and VS Code does have char count built-in, so why not line count?
- competitor like Sublime Text and Notepad++ offer line count out-of-the-box
- the implementation is super lightweight, minimal burden on both maintainers and users

**Comment by ushuz** [comment]
@bpasero 

I can understand the reason for a setting now. Unfortunately, implementing something like that is beyond what I can commit to this feature. So I'll just update this PR to address the status bar space concern and leave it here.

If this feature is not mergeable under the current state, and no one else is willing to contribute, please feel free to close it.

**Comment by wmentha** [comment]
@ushuz I'm up for looking back into this issue again and implementing the enum of 3 @bpasero has been suggesting 😊

**Comment by heartacker** [comment]
👀

**Comment by bpasero** [comment]
This PR seems stale.

**Pull request closed without merging**
