### PR TITLE
Fixed #50830: On Windows, fix window position for top taskbar

### LINKED ISSUE #50830: Titlebar spawns underneath Windows taskbar at top of screen
A fresh install of Code - stable, insiders and code-oss - will spawn a floating window relative to the top of the screen, not to the work area. Code stores the window position, so moving the window makes it spawn in the new location next time.

screenshot 1

Issue Type: <b>Bug</b>

Steps to reproduce:

- Taskbar at top of screen
- Display resolution: 1366x768
- Install fresh copy of Code.
- Run Code (with or without extensions disabled)

VS Code version: Code 1.23.1+
OS version: Windows_NT x64 10.0.16299

### PR DESCRIPTION
**Pull request by jechasteen**
Windows does not prevent a titlebar being created underneath the taskbar, as far as I can tell. However, it would seem that you cannot drag a window there, as it triggers a maximize action.

This fix addresses both cases as it just checks every time if the window is trying to be created above `workArea.y`

Another solution could be:

```typescript
const options: Electron.BrowserWindowConstructorOptions = {
    ...
    y: this.windowState.y || screen.getPrimaryDisplay().workArea.y,
    ...
}
```
which I think should only get called on first run, i.e. while `this.windowState.y == undefined`.

If you think this would actually be an upstream issue, please let me know and I will file it there.

#50830

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
I see two potential issues:
* the fix is not working for the cases where the taskbar is moved to the left or right or even when it is moved from top to bottom and the window was covering the lower area, so I think the fix should work for any of these cases if possible
* what if the window is not opened on the primary display but on a different display? On that other display the workarea might be different, so we could accidentally put the wrong position in assuming the window is on the primary display, when it could be not

**Comment by jaychasteen** [comment]
Thank you for responding so quickly and for your helpful comments. This is only my second pull request ever, so I think maybe I got a little too ambitious this time.

The issue really only addresses the first run scenario, so I have changed to the approach in the snippet above.

**Comment by bpasero** [comment]
@jaychasteen so you are considering this PR as complete?

**Comment by jaychasteen** [comment]
Yes, depending on how electron handles default positioning. The docs say that default is centered, but does it default if the values are undefined? If not, then this may position the window at (default, work area.y) on first run for everyone, which might not be acceptable. Otherwise we could use logic to determine where the taskbar actually is and only if it is at top *and* the window will be positioned at (x, 0) then we change the position.

This solution does work if the value of windowState is greater than 0 though, which it should be if the default is centered and that is the value being passed here, which I’m not sure of.

**Comment by bpasero** [comment]
@jaychasteen I am not sure about Electron but I could reproduce the following issue which seems like it should also be addressed:
* taskbar bottom
* open VSCode and move the window so that the left window border is connected to the left edge of the screen
* close VSCode
* move the taskbar to the left
* start VSCode
* => it shows below the taskbar

I think the same issue is there for:
* taskbar to the right
* taskbar to the top (your issue)
* taskbar to the bottom

**Comment by jaychasteen** [comment]
Ok, so I can take a look into a more comprehensive approach and perhaps open a new issue to address taskbar placement on windows?

**Comment by bpasero** [comment]
@jaychasteen we can do it as part of the issue you filed

**Comment by bpasero** [comment]
I fixed this meanwhile, thanks.

**Pull request closed without merging**
