### PR TITLE
Show breakpoints in overview ruler

### LINKED ISSUE #15104: Display breakpoints in scrollbar
It would be nice to see at-a-glance where breakpoints have been set in a code file.  They could be displayed in red the scrollbar area, like "changed/added code lines" are currently shown in blue.

### PR DESCRIPTION
**Pull request by anirudhrb**
This makes life easier when working with breakpoints in large files. Introduce a
new setting `editor.showBreakpointsInOverviewRuler` that controls whether this
is enabled or not. This setting is `false` by default. Use maroon for breakpoint
markers in the overview ruler to differentiate them from error markers.

Closes #15104.

### CODE REVIEW

**Comment by anirudhrb** [comment]
Here's what it looks like:

Screenshot_20191017_220805

**Comment by isidorn** [comment]
Great PR, thanks a lot!
Everything is great, except can you move the setting to the debug section. Not the editor section.
The setting should be called
`debug.showBreakpointsInOverviewRuler` and it should be defined somewhere [here](https://github.com/Microsoft/vscode/blob/24bf6ecccb876f0301338f2bfa61a694e999be57/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L267)

Once you tackle this I would be happy merging in the PR

**Comment by anirudhrb** [comment]
@isidorn Moved the setting to the debug section now. Please have a look.

**Comment by isidorn** [comment]
@anirudhrb this i great work. Thanks a lot!
I tested it and it works nicely. There are just two more things:
1) We decided to not expose and make the color configurable. Reason being this should always be aligned with the breakpoint color. So this will be tackled in the future when we make the breakpoint color customisable. So can you please remove the contribution of a new color
2) BreakpointEditorContribution should update all breakpoint decorations on configuration change of `debug.showBreakpointsInOverviewRuler` . That way when the user changes this setting he will imediatly see the change and he will not need to close / reopen the edditor

Can you please tackle this and I will merge it in. THanks!

**Comment by anirudhrb** [comment]
@isidorn Thanks for the feedback. I have implemented your suggestions. I am now able to see the effect of the setting change without re-opening the editor.

Please have a look and let me know something can be done in a better way.

**Comment by isidorn** [comment]
Looks great, thanks a lot for this PR

**Pull request merged**
