### PR TITLE
Changed shebang same as code.sh

### PR DESCRIPTION
**Pull request by RakibFiha**
This PR fixes #https://github.com/microsoft/vscode/issues/74929

The two different shebang can point to two different bash, specially in MacOS.

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
lgtm

**Comment by Tyriar** [comment]
@joaomoreno just getting a second opinion as we run these all the time.

**Comment by joaomoreno** [comment]
Yeah this is the right way.

**Comment by joaomoreno** [comment]
Thanks! 🍻

**Pull request merged**
