### PR TITLE
Adds the new icons to code folding

### PR DESCRIPTION
**Pull request by bgashler1**
@aeschli, this should be pretty simple, as it's just new assets and a little CSS.  Could we pull this in before testing this?

FYI - @weinand and @Tyriar

### CODE REVIEW

**Comment by aeschli** [comment]
@bgashler1 Thanks for the update. I pushed the changes so we can test them.
Note that the icons are scaled to 1em/1em. That wasn't as problematic for the arrows as for the + which looks blurred on my machine (linux, with the default font size)
image
Also I'd suggest to use the same gray as the line numbers.

**Comment by dstorey** [comment]
@aeschli @bgashler1 not sure how much you care about code size, but would be nice to put the icons through an SVG optimiser to remove Adobe meta data and now invalid stuff like SVG Doctype. Might be better to make the colour a presentational attribute rather than a CSS block too.

**Comment by bgashler1** [comment]
@dstorey nice idea!  I'll be doing that from now on.  Thanks for the suggestion.  It looks like https://github.com/svg/svgo is a good tool—what are your thoughts.

By the way, can you clarify why presentational attributes would be better?  Is it because we could have CSS style the icon?  Is this possible if we are not injecting it in the DOM (we usually just reference each SVG as a URL in a `background-image` rule).

**Comment by dstorey** [comment]
It was just because (I think) the other SVGs do it that way, and SVG optimisers often do that optimisation anyway. Depends how often you reuse the style. If it is a one of thing then it is more compact just adding it as an attribute, but if it is something reused a bunch, using CSS may be better.

**Pull request merged**
