### PR TITLE
Promote `registerResourceLabelFormatter` API

### PR DESCRIPTION
**Pull request by jeremie-stripe**
Promote the `registerResourceLabelFormatter` API that is part of the [resolvers proposed API](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.resolvers.d.ts) so that it can be used standalone.

The motivation for promoting this specific part of the resolvers proposal is describe in https://github.com/microsoft/vscode/issues/157958

### CODE REVIEW

**Comment by alexdima** [comment]
@isidorn Who owns now `ResourceLabelFormatter` & co?

**Comment by lramos15** [comment]
Looks like this doesn't compile @jeremie-stripe

**Comment by jeremie-stripe** [comment]
@lramos15 🤞 it should be working now (the integration step might end up failing cause checkout is hanging though)

**Comment by garuma** [comment]
@lramos15 is there any specifics of "under discussion" we can help with?

We are starting the work to improve branch visibility with our remote dev implementation and would like to understand how likely it is for this functionality to ever become public. If it sounds like it won't be, we don't want to waste time and will attempt to leverage something else (likely worse) instead of this and we are fine closing the PR.

**Comment by lramos15** [comment]
> @lramos15 is there any specifics of "under discussion" we can help with?
> 
> We are starting the work to improve branch visibility with our remote dev implementation and would like to understand how likely it is for this functionality to ever become public. If it sounds like it won't be, we don't want to waste time and will attempt to leverage something else (likely worse) instead of this and we are fine closing the PR.

Under discussion means it must be brought forward to the API team, this was done earlier this week. The current path forward here is we will be extracting this proposal into its own proposal so it doesn't get lost within the resolvers proposal and then we can take a more in depth look into who is using this and for what to get feedback and ensure the API surface is stable. Once it is determined this is the shape that we want to keep then the API moves to finalization. There is no timeline however for this process as each API is different.

**Comment by jeremie-stripe** [comment]
I'm going to close this PR since this still needs discussions in the vscode team and there is no point in having to maintain a working changeset in the meantime

**Pull request closed without merging**
