### PR TITLE
Added RANDOM, RANDOM_HEX snippet variables

### LINKED ISSUE #80297: [Feature Request] snippet support RANDOM
[use case]  
`console.log('#45dlk5', $1)`  
generate a simple random string as a quick debug flag

[feature request]  
add a $RANDOM varible to snippet  
or support JS expression as ES6 did  
e.g. ``  `${Math.random().toString(36).slice(-6)}` => '45dlk5'  ``

### PR DESCRIPTION
**Pull request by Krystofee**
This PR fixes #80297

I've take the issue since there was no activity. I will be happy to write tests, when I'll get approve for this functionality.

Ping @jrieken.

### CODE REVIEW

**Review by jrieken — APPROVED** [review]
lgtm

**Comment by NotWearingPants** [comment]
Why is this specifically 6 random characters? This is very arbitrary and the use cases for exactly 6-digit random decimal or hex numbers other than a hex color are non-existent.

This should be removed.

**Comment by jrieken** [comment]
So, what is your suggestion then? Just remove? 5 numbers? 3?

**Comment by seognil** [comment]
Wow, thanks for the work
the origin request is from me

I agree with NotWearingPants
the approach is not flexible
but it's enough for my original proposal already

I thought that maybe the 'snippet system' could support *inbuilt function* rather than const only
or as what I imaged before: parse any custom valid JS statement

the first case is like `` `color: #${RANDOM(6, hex)}` `` or  `` `console.warn('tag-${RANDOM(8, 36)}')` `` 
the customable way is like `` `console.warn(${Math.random().blahblah()})` `` 

Anyway, thanks for the work~

**Pull request merged**
