### PR TITLE
Print extension errors to the console

### PR DESCRIPTION
**Pull request by solomatov**
@jrieken That's another attempt to improve diagnostics.

### CODE REVIEW

**Comment by solomatov** [comment]
So, the problem I am trying to solve with this, is visibility of extension errors. They are printed to some log file, but navigating there takes time, and there's no possibility of navigating with Cmd+Click to the source from there.

**Comment by solomatov** [comment]
See this: https://github.com/microsoft/vscode/issues/86109

**Comment by bpasero** [comment]
Will check in December. Have to figure out who is registering external errors.

**Comment by solomatov** [comment]
@bpasero do you mean January?

**Review by bpasero — CHANGES_REQUESTED** [review]
I do not feel like the "external error" part is something of my area, it is the first time I see it and it seems only to be used from many editor contributions that ask provider for results. Thus, assigning @jrieken and @alexandrudima to decide if this is correct thing to do.

However, as for where to hook this into the workbench, it should be here: 

https://github.com/microsoft/vscode/blob/d386b49dee6267238389c0a616af2be89726a4e3/src/vs/workbench/browser/workbench.ts#L82

**Comment by jrieken** [comment]
"External error" are those that are caused by extensions and because we don't want them in our error telemetry we have special handling for them. That's the fragment I know of this and the important part to keep in mind when looking at the errors-util - of which I am not very knowledgeable.

**Review by alexdima — APPROVED** [review]
LGTM. I would log even VS Code internal errors to console.log... I am not sure why we are so picky today and log errors only to the logfile.

**Comment by bpasero** [comment]
@alexandrudima but we do, no? That is what:

https://github.com/microsoft/vscode/blob/d386b49dee6267238389c0a616af2be89726a4e3/src/vs/workbench/browser/workbench.ts#L82

essentially does.

**Comment by alexandrudima** [comment]
@bpasero I looked at https://github.com/microsoft/vscode/blob/d386b49dee6267238389c0a616af2be89726a4e3/src/vs/workbench/browser/workbench.ts#L109-L125 and that appears to send it only to the log service.

AFAICT, this PR adds that errors that occur in extension are additionally being logged to the console. My review was that I would print all errors to the console, internal ones and extension ones.

**Comment by bpasero** [comment]
@alexandrudima my understanding is that we always have a console logger running that puts everything to console as well:

https://github.com/microsoft/vscode/blob/d386b49dee6267238389c0a616af2be89726a4e3/src/vs/platform/log/common/log.ts#L161

Maybe @sandy081 could chime in on that.

If this is true, the PR becomes easier, because the same method can be used basically for internal and external errors.

**Comment by solomatov** [comment]
@bpasero @alexandrudima @jrieken So is there anything I can do with PR?

**Comment by bpasero** [comment]
@solomatov see https://github.com/microsoft/vscode/pull/86405#pullrequestreview-328242534

**Comment by solomatov** [comment]
@bpasero Done. Made the PR much simpler :-)

**Comment by bpasero** [comment]
@solomatov I am not sure this resolves the issue of reporting external errors, or does it? I think your other changes for allowing to listen on external errors is still needed, no?

As for printing errors to the console, this should happen automatically when using the log service as I outlined before.

**Comment by solomatov** [comment]
@bpasero It doesn't happen automatically. It's being prints only to the log which is available in the debugged copy of vscode.

**Comment by solomatov** [comment]
@bpasero So ok. We write the fact that the error message happened. But, we don't write a stacktrace. I think it's better to write it in a way which will print exception there and remove my change.

**Comment by bpasero** [comment]
Yeah but then I would say that we should do that at the place where we log to the console, no? That way everyone benefits. Let's wait for @sandy081 to chime in. To summarize: every error that gets logged to the logger should be printed to the dev tools with a stack (if its an error).

**Comment by solomatov** [comment]
@bpasero It was printed but in a not very helpful way. See my last commit. It became even better :-)

**Comment by solomatov** [comment]
I think, it was a bug. We didn't consider Errors without a message or with an empty or undefined messages as real errors.

**Comment by solomatov** [comment]
@bpasero So, the problem was, I put a number of exceptions without error message, created like this: throw new Error(). These errors didn't print out because they didn't have message. My last commit fixes this problem. Such errors are now printed like everything else.

**Comment by bpasero** [comment]
@solomatov ah nice, I like where this is going. However, one suggestion: if `exception.message` is not defined, let's simply use the generic error message `An unknown error occurred. Please consult the log for more details.` so that we make sure that even in the verbose case, no undefined message is printed together with the stack. Does that make sense?

**Comment by solomatov** [comment]
@bpasero  I debugger it. Actually, it's defined and it's an empty string but due to how conditions works in js, it has funny behavior. Added your suggestions.

**Comment by sandy081** [comment]
Yes, we log all messages to both log file and console. 

@solomatov 

> We write the fact that the error message happened. But, we don't write a stacktrace. I think it's better to write it in a way which will print exception there and remove my change.

Yes, Console logger is not handling errors correctly thereby not printing stack traces whereas file logger (spdlog) does it correctly. Feel free to fix the console logger

https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/src/vs/platform/log/common/log.ts#L194-L204

You can refer to code how we do it already in spdlogger

https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/src/vs/platform/log/node/spdlogService.ts#L113-L124

**Comment by solomatov** [comment]
@sandy081 So, do you want me to use the same code for printing exception? Or is my way is ok? (I think they are more or less equivalent.)

**Comment by sandy081** [comment]
I would prefer the existing way as it was there already (which is in spdlog).

**Comment by solomatov** [comment]
@sandy081 I checked it, and Error isn't passed there. Just a string sent there.

**Comment by solomatov** [comment]
@bpasero @sandy081 Created https://github.com/microsoft/vscode/pull/86617 to make the change. Closing this PR.

**Pull request closed without merging**
