### PR TITLE
#78 gitignored files not displayed on explorer view by default

### PR DESCRIPTION
**Pull request by asotog**
troubleshoot for the annoying git ignored files displayed on the files explorer https://github.com/Microsoft/vscode/issues/78

### CODE REVIEW

**Comment by bpasero** [comment]
@asotog imho this should be implemented on a much lower level and fed into our configuration story. There already is a setting search.exclude and when accessing that one, it should get filled with whatever setting is in .gitignore. The work is to convert .gitignore patterns into the VS Code compatible glob system. The other work is to make sure that this scales to very large .gitignore files.

**Comment by asotog** [comment]
Actually right now that is what this code is doing, it reads the .gitignore file and push the entries into the existent excludes patterns that vscode provides out of the box, right the now the code works for files explorer, but took a look at the search part and works in similar way, it needs the excludes maps as well, havent added the code to the search yet

**Comment by bpasero** [comment]
The reason why I bring this up is that many things in the editor react on the `files.exclude` and `search.exclude` setting. If the `.gitignore` patterns are merged into one of those, you would get the explorer filtering for free. 

My understanding is that #78 is about ignoring `.gitignore` in searches but not necessarily in the explorer. We would probably have to introduce 2 new settings to pick up the patterns either in `files.exclude` or `search.exclude` or both.

Today, anything in `files.exclude` will also be ignored in searches. It causes the explorer to hide these files too.

My fear is that the VS Code exclude rules cannot fully support `.gitignore` patterns. E.g. you can negate patterns (with `!`) and the order of patterns also has an impact (VS Code ignore patterns are currently unordered).

**Comment by bpasero** [comment]
As a related note, I think Atom actually executes git natively on a path to find out if the path is ignored or not. They do not try to convert the file into any pattern.

**Comment by asotog** [comment]
good point, will need more research on this,  thanks man

**Pull request closed without merging**
