### PR TITLE
Workaround for v2 theme terminal backgrounds

### LINKED ISSUE #173475: Visual rendering glitch in terminal with V2 themes
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

Steps to Reproduce:

1. Open nano in the terminal

vscode_glitch

I have already checked, when using the macOS Terminal, the bug will not occur.

### PR DESCRIPTION
**Pull request by dlschmidt**
fixes https://github.com/microsoft/vscode/issues/173475

### CODE REVIEW

**Comment by dlschmidt** [comment]
@microsoft-github-policy-service agree [company="{your company}"]

**Comment by dlschmidt** [comment]
@microsoft-github-policy-service agree

**Review by Tyriar — APPROVED** [review]
:+1: foreground shouldn't be transparent. @daviddossett can you make sure the color is good? To be the same you could blend it with terminal/panel bg manually

**Comment by daviddossett** [comment]
Thanks for the PR @dlschmidt. I've got a larger PR up at #173844 that switches all foreground colors—including those in this PR—to use solid colors. I'll close this in favor of that one.

**Pull request closed without merging**
