### PR TITLE
Theming for keybinding label

### LINKED ISSUE #120201: Allow to theme keybindings widgets in quick open command palette
The Command Palette is almost perfect - thanks a lot!: 
it even displays **keyboard shortcuts. Unfortunately, they are sometimes not readable**:

image

According to the theme-color reference: https://code.visualstudio.com/api/references/theme-color
it is not possible to adjust the keyboard shortcut color 😞. 

Can you please allow us to configure it by something like:
```
   "workbench.colorCustomizations": {
        "[Color Scheme Name]":{
            "symbolIcon.hotkeyForeground": "#ff0011"
        }
    }
}
```

Thanks a lot, kind regards,
Thomas

### PR DESCRIPTION
**Pull request by bpasero**
fixes https://github.com/microsoft/vscode/issues/120201

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
vscode: everything updates accordingly:
* quickpick
* watermark
* keybinding editor and widget
* Extension editor "feature contributions"

standalone:
image
image

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/pull/120727/commits/8e9fa62cd28de7329786c57bf4cde915f6d934ab to ensure the quick input styles do not impact anything in the workbench, so the quick input prefix is really needed.

At first I thought it is a bad idea to remove the default colors from the widget, and I still think it is a bit of an issue because typically we really try to keep default colors in all our widgets so that in theory they can be used standalone even without the workbench or editor. But I think it is not a big deal, given that they appear like this by default:

image

@sandy081 for review of the adoption of `attachKeybindingLabelStyler` in his respective areas (keybindingsEditor, keybindingsWidget, extensionsEditor)

**Comment by bpasero** [comment]
@TylerLeonhardt can we also please revisit how keybinding label looks in HC theme, I think it should not use any box shadow and appear with most contrast (white foreground):

image

**Comment by TylerLeonhardt** [comment]
🧑‍🎨 
image

**Review by sandy081 — APPROVED** [review]
Changes in Keybinding editor and label widget LGTM

**Comment by TylerLeonhardt** [comment]
rebased on master due to styler.ts conflicts (purely in imports). Will merge when CI passes.

**Pull request merged**
