### PR TITLE
Ts server restart

### LINKED ISSUE #22335: An explicit way to restart TypeScript service (tsserver)
VSCode sometimes displays ghost TypeScript errors, and it's not that rare in my experience. For example, I have something underlined in red in VSCode but if I run `tsc` on the project, it compiles fine.

Ideally, these situations wouldn't happen but as long as they do in practice, it would be good to have a command to reload tsserver. For example, WebStorm has this piece of UI:

image

There is "TypeScript: Reload Project" command in VSCode but I didn't observe any effect of it.

VSCode 1.10, Windows 10.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #22335

Adds a command to explicitly restart the TSServer

### CODE REVIEW

**Comment by dbaeumer** [comment]
From #22335 I see why we add it but I am still not a big fan of such an actions. We should better understand why we have stale errors.

Instead of restarting would a 'Recheck all' action be the better approach to fix stale errors.

**Comment by mjbvz** [comment]
@dbaeumer I agree and will follow up about the stale error issue specifically.

I do think there is a use for this command though. The `reloadProjects` command never seems to do what I need, so our current story is to tell users to reload the VSCode window when TS starts misbehaving. Adding a restart TSServer command could make the process easier, but it also means that we now have to worry about state within the TS extension more

**Comment by dbaeumer** [comment]
Agree that this makes the process easier. What I am a little worried about is that users will restart the server instead of filing issue. Restarting the server should be an exceptional case.

**Comment by mjbvz** [comment]
Fixed by d167cf3

**Pull request closed without merging**
