### PR TITLE
Added find options to terminal find widget with keybindings

### PR DESCRIPTION
**Pull request by alexr00**
- Exposed a way for consumers of FindInput to show/hide the find options
- Passed state of FindInput options in to the xterm.js find api
- Added keybindings to the find options

### CODE REVIEW

**Comment by Tyriar** [comment]
CI failed with some compile errors:

```
2018-09-11T22:40:41.2344244Z [22:40:41] Error: D:/a/1/s/src/vs/workbench/parts/webview/electron-browser/webviewFindWidget.ts(18,3): Expected 3-4 arguments, but got 2.
2018-09-11T22:40:41.2346421Z [22:40:41] Error: D:/a/1/s/src/vs/workbench/parts/search/browser/searchWidget.ts(268,37): Expected 5 arguments, but got 4.
```

**Comment by alexr00** [comment]
Those are old compile errors and I can't make it re-run. If it were to re-run now I don't think we'd see those.

**Comment by Tyriar** [comment]
+@mjbvz +@cleidigh since this touches the simple find widget, let us know if you have comments

**Review by Tyriar — APPROVED** [review]
It's cool to finally see this working! Let's update vscode-xterm on Monday to get the other 2 buttons working before merging.

**Comment by cleidigh** [comment]
@alexr00 
Maybe I'm not looking in the right place but, I am not able to find your branch base to clone and test.
If this is not public can you post the branch in your public space.  If it is public can you point to it?
Thanks/CDL

**Comment by Tyriar** [comment]
> BTW would you like to finally also like to get the Find next/Previous commands in from my old PR: for September?

I think @alexr00 might have a better way of implementing F3/shift+F3, regardless she should check out that PR as she was looking into that briefly.

**Comment by alexr00** [comment]
I took a look at the F3/shift+F3 PR and it is more comprehensive than the key bindings I added to the checkboxes. The key bindings for the checkboxes only work when find has focus, where as the F3 PR endeavors to be more complete by handling F3/shift+F3 when the terminal has focus too. This matches what the editor find widget does, and when F3/shift+F3 is done we should convert the checkboxes to work the same way.

**Comment by Tyriar** [comment]
@alexr00 didn't your change modify the find input focused to cover when the buttons are covered too? If that's the case, I think we could just add 4 keybindings to cover this: f3 when terminalFocus, f3 when terminalInputFocus(?) and 2 for shift+f3?

**Comment by alexr00** [comment]
I didn't pipe that through to the context key. I'll do that for #29661 though.

**Comment by cleidigh** [comment]
@alexr00  Ditto on @Tyriar comment above, great to have this now on the terminal!

You allude to one issue I was going to mention, small behavioral consistency:
Besides the toggle keys only working when the terminal find has focus, there is also
the button animations if you toggle from the editor.  It would be good to get these as parallel as possible.  As you observed, these key findings have the same issue that I had to solve with the F3/s-F3
PR.

While I added a context key and logic to operate in each condition, it looks like in the editor 
two different command names are used mapping to the same keybindings.  First uses 'Find' versus second command which uses 'search'  My PR does not use two different commands.

**Pull request merged**
