### PR TITLE
Remove inner whitespace on Toggle Block Comment. Fixes #30656 & #30729

### LINKED ISSUE #30656: Added spacing when toggling block comments in JavaScript
When toggling and untoggling block comments in JavaScript (I haven't tested other languages), extra spaces are added to the beginning and end of the block each time.

This did not happen in the previous version of VSCode.

- VSCode Version: 1.14.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Toggle a block comment in a section of JavaScript.
2. Untoggle it and notice the added spacing.

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by cleidigh**
@rebornix 
- adjusted whitespace in similar fashion to single-line comment
- everything language independent

### CODE REVIEW

**Comment by rebornix** [comment]
@cleidigh thanks, it looks pretty good. Do you mind adding test cases which can cover what you added for block comments? Once we have tests for them, we can get it merged.

**Comment by cleidigh** [comment]
@rebornix 
Sounds good!
Just have to familiarize myself with the test approach...
Will attempt to do as quickly as possible.

**Comment by cleidigh** [comment]
@rebornix 
Okay, I added test cases and ran the test suite.
I think this should cover the new cases.

**Comment by rebornix** [comment]
@cleidigh thank you very much, this is really awesome!

**Comment by cleidigh** [comment]
@rebornix 
Cool. Working on VCS is great and important for me being disabled. Code's accessibility
it's great and I intend to help add more ;-)

**Comment by rebornix** [comment]
@cleidigh look forward to see more contributions from you 🚀

**Pull request merged**
