### PR TITLE
feature: allow unsetting color theme values in settings

### LINKED ISSUE #128062: [themes] Allow color customizations in settings to unset color tokens
I suggest that it be possible for `list.activeSelectionIconForeground` to be unset with a boolean too, in case of customizing existing themes that have already set this property.

_Originally posted by @infinnie in https://github.com/microsoft/vscode/issues/125998#issuecomment-866463760_

### LINKED ISSUE #170576: If a theme sets diffEditor.insertedTextBorder or diffEditor.removedTextBorder there's no way to properly unset them without border artifacts
Does this issue occur when all extensions are disabled?: Yes (but requires a theme to reproduce)

- VS Code Version: 1.74.2
- OS Version: macOS Ventura 13.0.1 (22A400)

Steps to Reproduce:

1. Use any theme that sets `diffEditor.insertedTextBorder = "#deadbeef"` or `diffEditor.removedTextBorder = "#deadbeef"`
2. In your custom JSON settings file, attempt to override those values - the only way being to set them to a transparent color:

```
"diffEditor.insertedTextBorder": "#00000000",
"diffEditor.removedTextBorder": "#00000000",
```

3. The diff viewer is left with line borders

Screenshot 2023-01-04 at 1 57 36 PM

This issue has been around for many years. This is a discussion from 2019: https://www.reddit.com/r/vscode/comments/biyfhr/how_do_i_remove_the_border_in_diff_editor/

This issue has caused theme authors to have to [remove these settings](https://github.com/BeardedBear/bearded-theme/commit/643d4311e637c06beb77184e3b83cfe7470c5542):

- https://github.com/BeardedBear/bearded-theme/issues/27
- https://github.com/BeardedBear/bearded-theme/issues/42

This issue has also been referenced here: https://github.com/microsoft/vscode/issues/128062#issuecomment-1367957081

### PR DESCRIPTION
**Pull request by SimonSiefke**
fixes #128062, fixes #170576.

https://github.com/microsoft/vscode/assets/23744935/3bef9a9d-926f-4b58-abad-f24373a4de3b

### CODE REVIEW

**Comment by SimonSiefke** [comment]
Thanks for the feedback! I agree it would not be good to set colors to null, potentially causing unexpected/undefined behaviour.

What do you think about instead of setting it to null, removing the property from `colorMap` so that customizations would only affect theme colors, but not the default colors.

E.g. with this color theme: 

```json
{
  "$schema": "vscode://schemas/color-theme",
  "type": "dark",
  "colors": {
    "activityBar.activeBackground": "#1f2727",
	"activityBar.activeBorder": "#00000000"
  }
}
```

and these settings: 

```json
{
	"workbench.colorCustomizations": {
		"activityBar.activeBackground": null
	}
}
```

the resulting colorMap would be 

```json
{
  "activityBar.activeBorder": "#00000000"
}
```

the same as if the color hasn't been defined in the color theme in the first place.

Thanks again!

**Comment by aeschli** [comment]
Yes, using `null` to reset a color to the default would be fine. But it's unclear to me how many problems this solves. It would only be useful for the `colorCustomization` settings.

**Comment by SimonSiefke** [comment]
Due to the PR being closed, I made some changes here: https://github.com/SimonSiefke/vscode/pull/14/files. What do you think?

**Comment by aeschli** [comment]
I simplified the PR by allowing `default` also in color theme files. It's not useful, but also not harmful and easy to handle. That eliminates the schema split.

**Review by bpasero — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by aeschli** [comment]
Thanks @SimonSiefke !

**Pull request merged**
