### PR TITLE
Add support for VSCode Remote URI handler to handle vscode:// URIs

### LINKED ISSUE #197586: [remote] Cannot open VS Code extension URIs in Remote instances
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84
- OS Version:  Ubuntu 20.04

As per https://github.com/microsoft/vscode-remote-release/issues/4260#issuecomment-1794908734
VSCode remote supports URL handling from inside of a VSCode terminal through the use of a `$BROWSER` helper, but this browser helper cannot manage URLs that start with `vscode://`

Steps to Reproduce:

1. Open a VSCode remote session (Remote - SSH, Remote - Container, etc)
2. Open a terminal in the VSCode window
3. in that terminal type `$BROWSER 'vscode://fabiospampinato.vscode-debug-launcher/auto?args=path/to/file'`
4. VSCode tries to convert the URL into a file name and creates a new blank file named after the URL

### PR DESCRIPTION
**Pull request by alextremblay**
This proposed change fixes #197586

### CODE REVIEW

**Comment by JesseFarebro** [comment]
From what I understand, this would fix `$BROWSER vscode://...`, but it would also be nice to have parity with the non-remote code binaries in supporting `--open-url`, i.e., `code --open-url vscode://...`..

**Comment by alextremblay** [comment]
Agreed, that would be nice

one step at a time

**Comment by alextremblay** [comment]
Hi @alexdima @jrieken do you have time to take a look at / approve this PR

I would dearly like to stop depending on a convoluted hack leveraging VSCode internals as workaround for lack of this feature :)

**Comment by alextremblay** [comment]
Hi @jrieken Any chance you can review this? it's been sitting idle waiting for review for... a while

I would DEEPLY appreciate any time you can spare to look at it

**Review by aeschli — APPROVED** [review]

**Comment by aeschli** [comment]
This got fixed by https://github.com/microsoft/vscode/pull/234380

**Pull request closed without merging**
