### PR TITLE
Git: Option to not show files in untracked dirs (#140755)

### LINKED ISSUE #140755: Git: support not passing -u to git status for large repositories
For very large git repositories, the `-u` option (an alias for `-uall`) can sometimes make `git status` take a large amount of time and CPU.

Would like to have an option (off by default) to ignore individual files in untracked directories, which is the default behavior of `git status` with no arguments (equivalent to `-unormal`).

### PR DESCRIPTION
**Pull request by brianduff**
This option is off by default. When switched on, it avoids passing the
`-u` option to `git status`, which can be significantly faster on huge
repos with the caveat that files in untracked directories will no longer
show as untracked files.

This PR fixes #140755

### CODE REVIEW

**Comment by brianduff** [comment]
Hi Ladislau - we'd love to get this in, since it would unblock us from using VSCode efficiently in our monorepo. It's a fairly small change which has no effect on default behavior. Any issues or concerns?

**Comment by brianduff** [comment]
Gentle ping. Let me know if there's another process I should follow for this.

**Comment by lszomoru** [comment]
@brianduff, apologies for not getting back to you on this until now. 

Given that we want to control whether the `-u` argument is used or not, I think that we could just leverage one of the existing settings - `git.untrackedChanges`. If this setting is set to `hidden` (not the default value), then we can omit the `-u` argument as untracked changes will not be displayed either way. Would you like to update your PR based on that, otherwise I can make the change myself. Thanks!

**Comment by lszomoru** [comment]
@brianduff, I just noticed that there is [an earlier pull request](https://github.com/microsoft/vscode/pull/131030), that implements exactly what I have suggested above. I will go ahead and close this pull request, and will complete the other one. Apologies for not spotting that earlier.

**Pull request closed without merging**
