### PR TITLE
Add the tsec dependency with a Git URL instead of a GitHub URL.

### LINKED ISSUE #42225: certain drags show an unstyled text selection highlight over code
- VSCode Version: 1.19.3 and 1.20.0-insider
- OS Version: Windows 7 and 8.1

sorry if the title sucks

Steps to Reproduce:

it's hard to explain with just words so i took a screenshot:

screenshot

- where a red line/arrow starts, the left/primary mouse button is pressed down and the arrow is followed using the mouse while the button is held down
- when the cursor is on a yellow part, the blue "native" text highlight is visible
- you might have to click something and try again if it doesn't work at first

if i disable these css rules using the dev tools, the bug disappears and normal selections still work normally:

https://github.com/Microsoft/vscode/blob/2e2b47a4944ad1dfc7bbc58756c91aa3188cfa04/src/vs/editor/browser/viewParts/lines/viewLines.css#L17-L26

i couldn't find a reason for adding them in the history of the file, they've been moved from another file but they were first added in a [big initial commit](https://github.com/Microsoft/vscode/commit/8f35cc4768393b25468416829e980d7550619fb1) that doesn't explain why/if they're needed

Does this issue occur when all extensions are disabled?: Yes, also with default settings

### PR DESCRIPTION
**Pull request by uraj**
This can trigger the prepare script in tsec so that it can correctly
compile itself.

This PR fixes the problem described in googleinterns/tsec#20

### CODE REVIEW

**Comment by uraj** [comment]
CI failing due to yarnpkg/yarn#6312.

**Comment by uraj** [comment]
It doesn't seem that we can get around the racing problem of yarn. The other solution is to build tsec through the postinstall script of VS Code.

**Review by jrieken — APPROVED** [review]
Thanks

**Comment by jrieken** [comment]
Wait... It seems that the build is failing with those changes

**Comment by jrieken** [comment]
Lol. I finally got to read your comments

**Comment by jrieken** [comment]
This doesn't seem to work. Closing and publishing a fork of tsec on npm

**Pull request closed without merging**
