### PR TITLE
Implement HLSL syntax highlighting, and use HLSL grammar to highlight Cg blocks in ShaderLab files

### PR DESCRIPTION
**Pull request by tgjones**
Implements #20128.

In contrast to the existing ShaderLab grammar, this new ShaderLab grammar delegates highlighting of Cg blocks to the separate HLSL grammar (which has the advantage that standalone HLSL files can now be highlighted).

I created both the HLSL and ShaderLab grammars by reading the relevant language documentation, so they should both be up-to-date with available types / keywords / etc.

I also looked at the latest `csharp.tmLanguage` so that my choice of scope names roughly matches what has been done there.

Because `.cginc` files are basically HLSL files, and not ShaderLab files, I've removed that file extension from the ShaderLab extension and included it in the HLSL extension.

For comparison, here's what ShaderLab syntax highlighting looks like in VSCode 1.9:

shaderlab-before

And here's what it looks like using this new ShaderLab grammar:

shaderlab-after

This is what standalone HLSL syntax highlighting looks like using the new HLSL grammar:

hlsl

This is my first contribution to VSCode - I'm very happy to make changes, just let me know what I got wrong :)

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by mjbvz** [comment]
@aeschli Can you please take a look at this change. It looks good to me but you know much more about the general language support

**Comment by aeschli** [comment]
@tgjones Thanks a lot Tim for the great work. Separating HLSL and ShaderLab sounds like a good idea.
Why I'm hesitating and I wanted to talk to @egamma about it, is that this would be the first grammar that we would 'own', where the original version lives in the VSCode repository. For all other languages we import the grammars from other repositories. Having the grammar in a separate repository has the advantage that the grammar can be maintained independently by the original authors or other committers. There's no need for the VSCode team to review and merge every change. Another benefit is that the grammar can be made available to other editors as well.
https://github.com/Microsoft/TypeScript-TmLanguage is an example for such a repository.
We forward issues to that repository and, from time to time, or on request, import the latest grammar to VSCode.
I'd suggest we follow the same model here. 
@tgjones What do you think? 
That would mean you create your own github repository that just contains the grammar. 
In order for us to use it all we need is a friendly open source licence such as MIT.

**Comment by tgjones** [comment]
@aeschli that sounds very sensible to me. In fact I've already created such a repository, because GitHub's Linguist (used for syntax highlighting on github.com) requires grammars to be in a submodule, and I've got an active PR over there for adding HLSL syntax highlighting. I'll modify this PR once I get back to my computer.

**Comment by aeschli** [comment]
Cool. What's missing to the PR is just the [grammar update script](https://github.com/Microsoft/vscode/blob/master/extensions/css/package.json#L20) plus an updated [OSSREADME](https://github.com/Microsoft/vscode/blob/master/extensions/shaderlab/OSSREADME.json).
If you point me to your repository I can make that change.

**Comment by aeschli** [comment]
Ah, I see https://github.com/tgjones/shaders-tmLanguage. I'll make the update.

**Comment by tgjones** [comment]
Great, thanks for merging!

**Pull request merged**
