### PR TITLE
Fixes #218626

### LINKED ISSUE #218626: [Bug] Drag and Drop files onto extensions also opens the file inside the default application for that file type
Type: <b>Bug</b>

1. clone repo https://github.com/maxbublik/vscode-customeditor-drop
2. press f5 to demo repo
3. drag and drop any file into the extension editor while holding shift

Notes:
I am primarily creating this issue to track the bug I made with  https://github.com/microsoft/vscode/pull/209211

VS Code version: Code - OSS Dev 1.91.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.85GB free)|
|Process Argv|. --disable-extension=vscode.vscode-api-tests|
|Screen Reader|no|
|VM|50%|
</details>Extensions disabled

https://github.com/microsoft/vscode/assets/21202515/31579895-e05b-4a5c-9b0e-ddfbc2cf19d5

### PR DESCRIPTION
**Pull request by swordensen**
This is to resolve https://github.com/microsoft/vscode/issues/218626

Basically, it prevents windows from popping up when dragging files over to extensions from the OS's file explorer. 

You can test this functionality by performing the following steps:

1. clone repo https://github.com/maxbublik/vscode-customeditor-drop
2. press f5 to open demo repo as an extension
3. drag and drop any file into the extension editor while holding shift
4. notice that a new window did _not_ appear

### CODE REVIEW

**Comment by swordensen** [comment]
I added a fix that addresses https://github.com/microsoft/vscode/issues/219047

**Comment by swordensen** [comment]
Since https://github.com/microsoft/vscode/pull/219896 got merged I will need to bring back the original changes on this PR before it gets merged. 

I am going to change this to a draft status.

**Review by mjbvz — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks for following up! Will get this into the next insiders build  which should go out at the start of next week

**Review by connor4312 — APPROVED** [review]

**Comment by swordensen** [comment]
> Thanks for following up! Will get this into the next insiders build which should go out at the start of next week

no problem! and no rush on my end. I'm sorry for any headaches my last PR caused. It feels good to help fix it!

**Review by Redemtion1 — APPROVED** [review]

**Comment by swordensen** [comment]
I was thinking about this again today and I am a little concerned that if this fix PR is not merged before the July release we may encounter the same issue(s) with the June release.

Since, I don't think the reversion here https://github.com/microsoft/vscode/pull/219896 would be included. I am not 100% sure about that though.

**Review by mjbvz — APPROVED** [review]
Thanks for following up! Let's try this again for the August release since we'll have more testing in insiders

**Pull request merged**
