### PR TITLE
Fix #17750 - Implement "revert selected lines"

### LINKED ISSUE #17750: Diff editor "revert selected lines"
There's probably already a feature request for this but I can't find it.

I want to be able to select a change in the diff editor and revert it, same as how I can stage it. In SourceTree this is called "discard selected lines" although "revert" seems better, unless it's "discard selected changes".

I'm working on a PR for this.

### PR DESCRIPTION
**Pull request by roblourens**
Reverts the selected lines in the diff editor, similar operation to "stage selected lines". If only part of a change is selected, only the selected lines are reverted. 'cmd+z' will undo the revert.

### CODE REVIEW

**Comment by roblourens** [comment]
This isn't quite right for when you have some, but not all, modified lines selected. Not totally obvious what to do in that case. It's even buggy in SourceTree.

**Comment by roblourens** [comment]
@joaomoreno I fixed this up and I think it works pretty well now. Any thoughts on taking this? I think it would be useful, especially if we were to do something like 17655.

**Comment by joaomoreno** [comment]
Added a confirmation dialog, to prevent unintentional loss of data.

**Comment by roblourens** [comment]
Cool, thanks Joao!

**Comment by iampeterbanjo** [comment]
Does this work in 1.9.1? I can see the changed line indicator but I don't see how to trigger or toggle the revert tooltip

**Comment by roblourens** [comment]
No, you can see it in Insiders or 1.10 next month.

**Pull request merged**
