### PR TITLE
Workspace trust - add tracing to track down integration test failure

### PR DESCRIPTION
**Pull request by lszomoru**

### CODE REVIEW

**Comment by bpasero** [comment]
@lszomoru do we still need these changes? trying to cleanup the logs a bit for smoke tests runs. I forgot why you added them...

**Comment by lszomoru** [comment]
@bpasero, if we have not seen any further test hangs that we suspect is related to workspace trust, we can revert these changes.

**Comment by bpasero** [comment]
@lszomoru I see no hangs lately, I also forgot what kind of hang we saw, was there an issue? I suggest to either remove the logs or change them to `trace`

**Comment by lszomoru** [comment]
@bpasero, [this is the issue](https://github.com/microsoft/vscode/issues/141734) tracking the remote integration test failures that we were investigating. Will remove the logging.

**Comment by bpasero** [comment]
@lszomoru yeah thanks!

**Comment by lszomoru** [comment]
@bpasero, I have reverted the commit that added the tracing.

**Pull request merged**
