### PR TITLE
Fix window.zoomLevel going out of bounds even if zoom doesn't change

### LINKED ISSUE #48357: Zooming in / out beyond the maximum still increases / decreases window.zoomLevel
Since it's a little tough to explain, here's a video showcasing it: https://youtu.be/rVCn0rhj76k

### PR DESCRIPTION
**Pull request by gioragutt**
Fixes #48357

### CODE REVIEW

**Comment by gioragutt** [comment]
@bpasero Can I get a comment on this? I'd love this to be merged (or get a review comments to fix)

**Comment by bpasero** [comment]
@gioragutt instead of hardcoding this value wouldn't a better approach be to try to set the new zoom level and then check if it was applied and only then update the setting?

**Comment by gioragutt** [comment]
@bpasero I'll research that, but if there's like any guidance you can provide that'd be welcomed.
I too of course dislike the hardcoded values, although they work. Will update the PR later today.
Thanks!

**Comment by bpasero** [comment]
@gioragutt yeah just search for calls to `webFrame.getZoomLevel()`, which I would assume at one point does not return a changed value (this is my guess).

**Comment by gioragutt** [comment]
@bpasero Actually the `webFrame.getZoomLevel()` returns a valid value, which just keeps on growing. I'm currently opening an issue in electron to query those `mix/max zoom` values, which are currently not exported. I've not found a way to query it via `electron` itself, or something internal in `vscode`.
Even the [.cc](https://github.com/electron/electron/blob/4fcd178c368e67e543ee10ee84a0947342412a4c/atom/renderer/api/atom_api_web_frame.h#L51) don't export query methods for those values.

**Comment by gioragutt** [comment]
@bpasero As far as I can tell, getting the actual bounds from the underlying chromium code might be quite a serious hassle.
I suggest that this PR would be merged, and in the future, another PR would update the usage of those hard-coded constants (that seem to be working nicely, as I've seen) to values obtained by the API.

**Comment by gioragutt** [comment]
@bpasero ping

**Comment by gioragutt** [comment]
@bpasero hay, it's been almost a month. Can I get some feedback here?

**Comment by bpasero** [comment]
Sorry for the late reply but I decided to go with a solution that puts the limits closer to the `electron-browser` action because I think these limits are dependent on the container (via https://github.com/microsoft/vscode/commit/af8b26c93993cdf858eeee162e31bbc586240cb4).

**Pull request closed without merging**
