### PR TITLE
Add yaml front matter support for Markdown

### LINKED ISSUE #2640: Add an option to ignore YAML front-matter data when previewing
It would be nice if Markdown preview would ignore the YAML front-matter.

An example:

``` md

---
title: my first post
date: 2016-01-18
tags: stuff, other stuff

---

# My first post

Hello world, this is my first post.
```

The preview would start at `# My first post`.

### PR DESCRIPTION
**Pull request by mjbvz**
Issue #2640

## Bug
We currently do not handle yaml front matter inside markdown files very well. In the editor, front matter  is incorrectly colorized as markdown, and the html preview tries to render the front matter as markdown content.

screen shot 2016-11-08 at 3 39 18 pm

## Fix
- Add grammar support for recognizing and tokenizing yaml front matter inside markdown files.
- Add an option to strip the yaml front matter from the html preview.

screen shot 2016-11-08 at 3 40 12 pm

Closes #2640

### CODE REVIEW

**Comment by rebornix** [comment]
Just my 2 cents, is there any possibility that we render YML as table, like how GitHub handles it.

**Comment by mjbvz** [comment]
@rebornix Good idea, but probably worth taking in as a future enhancement instead of in this PR. I'll update the markdown extensions options to better support this addition in the future, something more like `markdown.yamlFrontMatterPreview` with valid options being: `none` and `strip` currently, while `table` could be added in the future (not a huge fan of the names, so please let me know if you have any suggestions). Does that sound good?

**Comment by rebornix** [comment]
Yes make perfect sense and looks good to me.

**Comment by srberard** [comment]
Another suggestion is to make the front matter delimiters configurable.  I'm using Hugo as a static site engine which, by default, uses TOML syntax for front matter which is delimited by "+++" rather than the YAML delimiter of "---".

**Pull request merged**
