### PR TITLE
LRU Cache in resourceLoader for webviews

### LINKED ISSUE #79147: Caching/prefetching remote webview vscode-resources
We have some fairly large javascript bundles (~10-20 MB with sourcemaps added) which we include in some of our webviews. These views run remotely because they communicate with remote extensions (which perform things like file search and version control).

However currently initial load takes a very noticeable amount of time when opening the webview. I traced code to find it's all spent on a remote filesystem read operation.

Request:
I'd like for workspace extension to be able to either:

1) (ideal) declare resources that should be pre-fetched when running remotely, so initial javascript load is instant
2) have a mechanism to cache vscode-resources so they don't need to be re-downloaded on each open (e.g. by setting `?cache=true` on the URI)

Here's an example patch that does a very simple caching and makes resource reloading much faster (option 2 above):
```
diff --git a/src/vs/workbench/contrib/webview/common/resourceLoader.ts b/src/vs/workbench/contrib/webview/common/resourceLoader.ts
index ea33db2e26..74a905be71 100644
--- a/src/vs/workbench/contrib/webview/common/resourceLoader.ts
+++ b/src/vs/workbench/contrib/webview/common/resourceLoader.ts
@@ -7,7 +7,7 @@ import { VSBuffer } from 'vs/base/common/buffer';
 import { sep } from 'vs/base/common/path';
 import { startsWith, endsWith } from 'vs/base/common/strings';
 import { URI } from 'vs/base/common/uri';
-import { IFileService } from 'vs/platform/files/common/files';
+import { IFileService, IFileContent } from 'vs/platform/files/common/files';
 import { REMOTE_HOST_SCHEME } from 'vs/platform/remote/common/remoteHosts';
 import { getWebviewContentMimeType } from 'vs/workbench/contrib/webview/common/mimeTypes';
 
@@ -25,14 +25,20 @@ const AccessDenied = new class { readonly type = 'access-denied'; };
 
 type LocalResourceResponse = Success | typeof Failed | typeof AccessDenied;
 
+const cache: Map<string, Promise<IFileContent>> = new Map();
+
 async function resolveContent(
 	fileService: IFileService,
 	resource: URI,
 	mime: string
 ): Promise<LocalResourceResponse> {
 	try {
-		const contents = await fileService.readFile(resource);
-		return new Success(contents.value, mime);
+		let contentsPromise = cache.get(resource.toString());
+		if (contentsPromise === undefined) {
+			contentsPromise = fileService.readFile(resource);
+			cache.set(resource.toString(), contentsPromise);
+		}
+		return new Success((await contentsPromise).value, mime);
 	} catch (err) {
 		console.log(err);
 		return Failed;

```

### PR DESCRIPTION
**Pull request by solomatov**
Added a LRU cache to fix https://github.com/microsoft/vscode/issues/79147

Tested by putting breakpoints in the changed method, and opening image files which use webview.

### CODE REVIEW

**Comment by mjbvz** [comment]
Did using normal http methods for this as I suggested  not work? I really don't want VS Code to have to implement the caching, even if is the simplest approach in terms of code  changes

**Comment by solomatov** [comment]
@mjbvz So what do you mean by normal HTTP methods? Do you want us just not to use anything, just put our webviews somewhere on HTTP and don't touch vs.code at all? My understanding was that you wanted us to use etags which are http feature.

**Comment by mjbvz** [comment]
The caching should be implemented at the browser session level, not by VS Code. That is the approach my comment on the original issue detailed

**Comment by solomatov** [comment]
@mjbvz Could you explain? We take stuff from the file system which is implemented in vs.code. How can we do this through the browsing session?

**Comment by solomatov** [comment]
@mjbvz Could you at least point to the API which I should use?

**Comment by solomatov** [comment]
Do you want me to use cache API? https://developer.mozilla.org/en-US/docs/Web/API/Cache

**Pull request closed without merging**
