### PR TITLE
add underline option to link, and use it for welcome view

### LINKED ISSUE #149982: Support markdown in view welcome content
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: Windows 11

Steps to Reproduce:

1. In the below Live Share example . Welcome content is markdown. We would like to make the blue link text either bold or italic. But using ** doesn't take effect. It reads it as string . As a result output shows asterisk instead of a bold text. (tried with escape characters as well)  
image

### PR DESCRIPTION
**Pull request by isidorn**
fixes https://github.com/microsoft/vscode/issues/149982

Here's how it looks

Screenshot 2022-05-23 at 15 29 53

### CODE REVIEW

**Review by joaomoreno — COMMENTED** [review]
Nice. Feels weird to have an `underline` option, though. If links in general should have an underline, independent of where they appear, what if we made all links have underline? Where else do they appear?

**Comment by joaomoreno** [comment]
That, or just a small CSS change a la 

```css
.view-welcome-content .link {text-decoration: underline}
```

**Comment by isidorn** [comment]
@joaomoreno the link classed is also used in:
* Banners
* editorPlaceholder
* inlayHints
* languageStatus
* markers
* search
* getting started
* trust

I am not comfortable changing it for all these cases.
So if you agree I would go with a CSS change. Let me know what you think

**Comment by joaomoreno** [comment]
Yeah, it's definitely one of those changes which will bite you right back. I mentioned it since it might just also be an accessibility issue on all those locations as well.

Feel free to go with a simpler CSS change here.

**Comment by misolori** [comment]
I'm a little unclear as to what the original issue is. We use links in a lot of places, some links are internal (used in the product) and act more like a button, and others are external links (that open a browser). Are we suggesting we only update these for a specific category or all?

**Comment by isidorn** [comment]
@misolori thanks for jumping in. There seems to be an accessibility requirement that links need to be more differentiated. Based on the comment [here](https://github.com/microsoft/vscode/issues/149982#issuecomment-1133181368) we could also render the underline on hover or focus.

So yes, for accessibility we might need to change how all links are rendered - the point is that just using colors to differentiate links is not enough. 

@misolori what do you suggest we do here?

**Comment by isidorn** [comment]
Clsoing in favour of https://github.com/microsoft/vscode/pull/151499

**Pull request closed without merging**
