### PR TITLE
Adopt new tree in Problems panel

### PR DESCRIPTION
**Pull request by joaomoreno**
- [x] Extract CodeActions related code out of the model
- [x] Remove filtering from the model
- [x] Slim down model to its essence
- [x] Replace tree with `ObjectTree`
- [x] Add filtering back
- [x] Implement collapse all
- [x] Add context menus back
- [x] Cleanup `console.warn` calls
- [x] Type in tree and focus the input field

cc @sandy081 will ask you for review later in the milestone 👍

### CODE REVIEW

**Comment by joaomoreno** [comment]
Got mouse and keyboard navigation working in a very dirty way after 2 days. Now just found out that context menu actions are globally registered commands and everything works through context key service... this is a nightmare.

**Comment by joaomoreno** [comment]
OK easier than expected, getting closer.

**Comment by joaomoreno** [comment]
@sandy081 This is READY for a good smoketest by you and to be merged to `master`.

The only missing piece is the accessibility provider, which the list doesn't yet support, but should be easy to get in.

**Comment by joaomoreno** [comment]
Bug:

1. reload workbench with text in the filter box, filtering every single result out
2. type more text into the filter box
3. clear filter

tree doesn't appear!

**Comment by sandy081** [comment]
Good Job @joaomoreno

**Pull request merged**
