### PR TITLE
Fixes failure to load first installed web extension on desktop

### LINKED ISSUE #173779: Web Extension fails to load on VS Code desktop after first install (works fine on VS Code for Web or after restarting)
Does this issue occur when all extensions are disabled?: It is an extension loading issue

- VS Code Version: 1.75.0
- OS Version: macOS Ventura 13.2

Steps to Reproduce:

- Open an empty folder 
- Create a file `sample.qsx` and open the file and pin it in the editor
- Install `billti.qsx` extension

🐛 Error activating `billti.qsx` extension

image

<details>
  <summary>Description From Author</summary>

I am building an extension as a pure web extension. It runs great in all scenarios (on github.dev, locally installed, under the debugger), except that when first installed on VS Code for Desktop it fails to load the resources from the extension package. Once I restart VS Code it starts working fine. (It works straight away in VS Code for Web).

1. Clone the very small repo at <https://github.com/billti/qsx-demo> to ease the repro (as it has a file of the correct type and the extension is recommended).
2. Open VS Code locally at the root of the repo, and install the recommended extension (`billti.qsx`)
3. Open the QSX file and see it is mostly working (highlighting, completions, errors). There are two commands the extension installs, `Show QSX panel` and `Debug QSX file`. Neither will work as intended, and the below errors will be shown in the console of the DevTools. (Note the first line error about the DebugAdapterDescriptorFactory failing, and the two GETs which result in a 401 error).

```text
workbench.desktop.main.js:2020 Activating extension 'billti.qsx' failed: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'qsx' debugger..

index.html?id=17feadf8-9352-426a-b23d-567d72a6ad53&origin=49c6e153-5802-4051-be31-fc9fb031dfdd&swVersion=4&extensionId=nullExtensionDescription&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:973          

GET https://file+.vscode-resource.vscode-cdn.net/Users/billti/.vscode/extensions/billti.qsx-0.1.5/dist/webview-ui-toolkit/toolkit.min.js net::ERR_ABORTED 401

(anonymous) @ index.html?id=17feadf8-9352-426a-b23d-567d72a6ad53&origin=49c6e153-5802-4051-be31-fc9fb031dfdd&swVersion=4&extensionId=nullExtensionDescription&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:973
setTimeout (async)
onFrameLoaded @ index.html?id=17feadf8-9352-426a-b23d-567d72a6ad53&origin=49c6e153-5802-4051-be31-fc9fb031dfdd&swVersion=4&extensionId=nullExtensionDescription&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:971
(anonymous) @ index.html?id=17feadf8-9352-426a-b23d-567d72a6ad53&origin=49c6e153-5802-4051-be31-fc9fb031dfdd&swVersion=4&extensionId=nullExtensionDescription&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1002

GET https://file+.vscode-resource.vscode-cdn.net/Users/billti/.vscode/extensions/billti.qsx-0.1.5/dist/webview.js net::ERR_ABORTED 401
```

5. Restart VS Code and try again, and notice that the extension and its WebView loads and works fine (i.e. the same two commands in the command palette work as expected - the QSX panel shows the table as expected, and the (mock) debugger starts successfully. DevTools shows no error regarding `DebugAdapterDescriptorFactory`, and the same URIs are being requested as after initial install when they failed, but this time they load successfully (the bottom two requests below).

image

Interestingly, if you open the exact same repo in VS Code for the Web via the browser at <https://github.dev/billti/qsx-demo>, and install the exact same extension, everything works straight away with no need to reload the browser.

Happy to provide code snippets on how I'm building Uris and attempting to fetch them if of use.

</details>

### PR DESCRIPTION
**Pull request by billti**
This PR fixes #173779. 

See the issue for more details, but to repro basically:

1. Install VS Code and launch (or launch with a clean profile). This should include no Web Extensions by default, so the `WebWorker` host won't be started. <https://code.visualstudio.com/api/extension-guides/web-extensions>.
2. Install a Web Extension which tries to register a debug provider. (You can use my simple one in the marketplace with id `billti.qsx`). You'll want a file open which activates the extension (e.g. a `*.qsx` file for my extension).
3. Note the exception/error related to registering the debug adapter. (At this point the 'activate' call has failed, so various other programatic features of the extension are broken).
4. Restart VS Code and note there are no errors, and the extension works fine. (e.g. try any of the commands in the palette with the string 'QSX').
5. You can also launch VS Code for the Web and install the same extension and observe it works fine.
6. Build this PR and repeat and observe the issue is addressed.

There's probably a more correct, but more involved way to fix this, but this was the simplest fix I could find. Happy to update the PR with any feedback.

The underlying issue appears to be that by default on a clean desktop install of VS Code, there is no extension it comes with that uses a WebWorker host, thus that host is not running by default. (This explains also why the issue doesn't repo on VS Code for Web, where that host is always used from some extensions).

The issues stems from the use of the CachedExtensionScanner in the getInitData call in the NativeExtensionService, where the cached list of extensions is populated before the extension is installed, but is then used to build the list of extensions to load in the new host (thus the newly installed extension is missing from the list, even though it's the reason the new host is being started!).

This then causes the extension to be missing from the 'extensionPaths', which causes the require interceptor to return the NullExtensionDescription instead of the actual extension (due to the line at <https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostRequireInterceptor.ts#L167> returning `undefined`. This appears to be harmless for many operations, but on the calls to `registerDebugAdapterDescriptorFactory` it actually checks the extension against the languageId the debug adapter is being registered for, and throws an exception at <https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostDebugService.ts#L330>.

A more 'correct' fix may be to somehow incorporate the newly added extensions into that returned by the cached list by wiring the 'delta' through, or to fully refresh/replace the CachedExtensionScanner when the extension is installed (or not use a cached list at all).

Happy to rework the PR with guidance. Thanks!

### CODE REVIEW

**Comment by billti** [comment]
Minor updates which should be a better approach (cache is marked dirty on extension changes and repopulates on next request).

**Comment by billti** [comment]
(Sorry for the noise with the additional commits. I'm done now (pending feedback)).

**Comment by billti** [comment]
p.s. As part of finding/fixing this issue, I ended up wiring in ILogService to a few providers that didn't already have it so I could trace execution/state (e.g. ExtHostDebugService, ExtensionDescriptionRegistry, etc.). Happy to open a separate PR if you think that would be useful. (I wanted to avoid making this PR too noisy). Let me know.

**Comment by billti** [comment]
Ping @sandy081 @alexdima: This has been sitting over a week now. Should I keep updating it with main, or wait until someone looks at it. Would love to get this in. It's an easy repro and a pretty straight forward fix. Thanks.

**Comment by sandy081** [comment]
@billti I will look into this next week. Currently we are winding up current milestone.

**Comment by billti** [comment]
Thanks @sandy081 . I'm trying to merge in main again now (there are some conflicts) and the commit keeps failing with the below new issue:

```
[12:38:51] /Users/billti/src/vscode/src/vs/workbench/services/extensions/electron-sandbox/nativeExtensionService.ts: line 185, col 5, Error - Parsing error: Identifier expected. 'const' is a reserved word that cannot be used here.

1 problem


Hygiene failed with 1 errors. Check 'build / gulpfile.hygiene.js'.
```

This line is the cause: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/extensions/electron-sandbox/nativeExtensionService.ts#L157

I've re-run 'yarn' since pulling and everything appears to be up to date. I can't find any issues discussing similar problems. Any suggestions? Thanks.

**Comment by billti** [comment]
Looks like there was quite a bit of refactoring in this space! I just pull main and verified the problem still exists. I then merged and updated my branch for the conflicts and verifies the fix still works.

I looked over some of the recent changes to this area and I believe the fix is still correct. Again, happy to update with guidance if there is a better approach. Thanks!

**Review by alexdima — APPROVED** [review]
Thank you and apologies for the slow reaction times! I pushed a change which separates the init data creation of the local process extension host from the web worker extension host and we can thus avoid this problem altogether. The local process extension host is special because it can host remote authority resolvers, and it therefore needs to start up before the extension registry is populated with extensions, so that's why the local process extension host uses the extension scanner directly during the initial start. But that is not necessary for the web worker extension host, which never hosts remote authority resolvers.

**Review by lramos15 — APPROVED** [review]

**Comment by billti** [comment]
I just build your update locally and tested with VS Code desktop and browser and works great. Thanks @alexdima !

**Pull request merged**
