### PR TITLE
feat: Add editor selection evaluation for debugger

### PR DESCRIPTION
**Pull request by sagea**
This PR fixes # none that I am aware of

## Description
When hovering over a selection in debug mode, the debugger will attempt to evaluate the selected text and show a popup with the evaluated result.

## Why?
When using the debugger I quite often run into a situation where I need to see the result of a sub expressions or the return value of a function. Right now the only way to do this is to copy the expression or function and run it in the debug console. This is tedious and can result in false positives due to human error. This change attempts to make this easier by allowing users to select sub expressions and see the evaluated result without having to open up the debug console.

## Important Decisions Made
- When hovering over a selection, only evaluate the contents of that selection. Don't attempt to expand selection based on expressions due to the complexity of multiline expression syntax across multiple languages.
- Evaluate any selection and fail silently if the selected area can't be evaluated.

## A/C
1. Show popup with resulting value from selected area
2. Should be able select variables
3. Should evaluate expressions and provide the result
4. Should evaluate expressions that take up multiple lines
5. Should run functions and display their return results
6. Invalid selections should not display a popup

## Screenshots
Screen Shot 2019-12-08 at 22 23 34
Screen Shot 2019-12-08 at 22 24 03
Screen Shot 2019-12-08 at 22 27 38
Screen Shot 2019-12-08 at 22 27 54
Screen Shot 2019-12-08 at 22 29 24

### CODE REVIEW

**Comment by sagea** [comment]
I am putting this out a bit early for feedback. I still need to write some unit tests

**Comment by isidorn** [comment]
Thanks for the PR, however duplicate of https://github.com/microsoft/vscode/pull/83388
We do not want this done just on hover, it is too dangerous. Please read out that PR and related issue (search for debug, hover evaluate) and then we can contiunue the discussion.

Thansk

**Comment by sagea** [comment]
@isidorn Sorry for the delayed response. I have checked out the original ticket as well as the feature request.

Would it be possible to get a list of security concerns and examples in the original ticket so we can collectively come up with solutions?

Possible Concerns I have:
1. Evaluation may result in mutation of code elsewhere
2. Partial selection may run code that is unexpected if sharing the same name (GIF below)
3. Running http requests may be a security vulnerability
4. Running file system changes may be a security vulnerability

SelectionWithoutContext

**Comment by isidorn** [comment]
Even though this PR was good work we never got a chance to finalize it.
Now it is outdated unfortunetly and we are not sure if we want this feature, thus closing this.

**Pull request closed without merging**
