### PR TITLE
Ctrl-T to use word under cursor or current selection

### PR DESCRIPTION
**Pull request by mihailik**
Implements #29974

### CODE REVIEW

**Comment by mihailik** [comment]
@bpasero Can you please comment?

Apart from general common sense UX, in practice this helps a lot navigating large (unfamiliar) codebases (such as VSCode).

I tried to fit it with the existing design (which you @bpasero worked on), with the flag `autoPickWord` passed in the same way as `prefix` to the constructor of `QuickOpenAction` base class. The job of working out the word and passing it along is put to that base class too.

Additionally, the auto-picked word is pre-selected in the search box. That way user starting typing will instantly override the auto-picked word.

Hope to get this in the VSCode, for our team's benefit -- and to help the community too.

**Comment by mihailik** [comment]
Also can you please suggest any examples for testing these classes? I'd love to follow the approach and spirit of the project in terms of testing and SDLC.

Many thanks!

**Comment by mihailik** [comment]
I've figured out the place to stick the tests -- added there.

**Comment by bpasero** [comment]
@mihailik I do not understand why this has to be put down into the quick open action in such a generic way, can you not just add it to the action that opens the symbols picker since it is only used there?

**Comment by mihailik** [comment]
@bpasero it's because this.prefix is private, and set once in the constructor.

But that's a good point -- let me refactor it a different way, so the complexity resides in the descendant. And I need to update the tests too.

**Comment by bpasero** [comment]
@mihailik I think for Ctrl+T it is fine to always use the selection as a seed for the input but I am not sure about Ctrl+Shift+O where this may not be expected because by default we show a list of all symbols of that file and someone might like that behaviour to quickly glance at the list of symbols of a file.

As for Ctrl+T: if you seed the prefix like that I think you should select the prefix up until the "#" portion such as typing overwrites whatever the seed is. You can look at [`ShowAllCommandsAction`](https://github.com/Microsoft/vscode/blob/ben/multiroot/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L122) to see how this is done. I would actually suggest to do the `ShowAllSymbolsAction` in  similar fashion and let it not extend `QuickOpenAction`.

**Comment by mihailik** [comment]
@bpasero done.

Removed all the customisation from `QuickOpenAction`, pushed it down to `ShowAllCommandsAction`.

And I kept the piece where I've extracted `getSelectionSearchString` from its former home in `CommonFindController` -- so the same logic for picking current word is shared between Ctrl-F and Ctrl-T.

**Comment by mihailik** [comment]
BTW there are 2 failing tests in one (out of two) instances of Travis - due to 10s timeout. NOT related to my changes, might be flaky tests?

https://travis-ci.org/Microsoft/vscode/jobs/252995386#L4241

<blockquote>

  1) colorization scss-test.scss:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) colorization typescript-test.ts:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

</blockquote>

**Comment by bpasero** [comment]
@rebornix assigning you to review the change in editorCommon.ts.

**Review by bpasero — APPROVED** [review]
LGTM

**Comment by rebornix** [comment]
@mihailik I like your approaching of avoiding code duplication but I don't think `getSelectionSearchString` should go into `editorCommon`. As we already have `getWordRangeAtPosition` exposed, I would be good to keep `getSelectionSearchString` just in search part, especially when we have some similar code in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L830 

cc @roblourens

**Comment by roblourens** [comment]
I think it would be good if editor find and search could share a helper function with that code, but I don't know where to put it, since they don't share any code yet.

**Comment by bpasero** [comment]
+1 for sharing this piece of code in more places if there are more cases

@rebornix can you make a suggestion where to move this shared code so that we can continue working on this PR? I am not sure @mihailik can make that decision easily.

**Comment by mihailik** [comment]
Yes please. I will do the work, just guide me high level :-)

BTW, being used from multiple places shall I write some tests too? Just give me some directions, please.

**Comment by bpasero** [comment]
Since I leave for vacation soon I am unassigning myself in favour of @roblourens and @rebornix (also within https://github.com/Microsoft/vscode/issues/29974).

**Comment by rebornix** [comment]
@mihailik I would suggest creating a new file called `find.ts` in `contrib/find/common` and put those sharing code into it. You can start with just `getSelectionSearchString`. The file can be similar to `contrib/format/common/format.ts`.

Besides, you can add a corresponding test file named as `find.test.ts` in `contrib/find/test/common`.  It's okay that you leave the tests work to me though.

**Comment by rebornix** [comment]
@mihailik LGTM, thanks for your help!

**Comment by mihailik** [comment]
How about that, with some unit tests too! :-D

**Comment by mihailik** [comment]
Actually wait, if no editor is open Ctrl-T now fails. Let me add some defensive checks.

**Comment by mihailik** [comment]
Fixed that, works without focused editor too now.

**Comment by rebornix** [comment]
@mihailik well done sir!

**Pull request merged**
