### PR TITLE
Add support for references when no [] exists

### LINKED ISSUE #141285: Support references links when no [] exists
I see we support linking to the source for `[ref][ref]` and `[ref][]` formats, but not `[ref]`.

image
image
image

I see it's not mentioned as much in "specs" but in my experience it has always worked. Would be handy to see the underline to quickly see what references are declared below.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes #141285

Code has been updated with the `main` branch and I have personally reviewed it.

## Changes

Alters the regex to match [...] and [...][...]. Treats [...] as if it's the same as [...][].

## Testing

On the feature branch:
1. Create a new markdown file.
2. Add in some references. For example:
    ```md
    [Works]
    [Works][]
    [Works][Works]
    [Still Works][Works]
    
    [Does Not Work]
    [Does Not Work][]
    [Does Not Work][DoesNotWork]
    [Works][DoesNotWork] Jokes
    
    [Works]
    
    [Works]: https://microsoft.com
    ```
3. Make sure that the links that you'd expect to work continue to work, both in the editor display and the preview.
    - Expected behavior in editor: Ctrl-Click (or Cmd-Click on Mac) brings cursor to reference.
    - Expected behavior in preview: References turn blue and link to their targets.
    - Preview can be opened via running `Markdown: Open Preview` from the Command Palette.
    
### Expected Output
image

### CODE REVIEW

**Comment by mjbvz** [comment]
Thanks for taking a look! Can you please also add tests for this: https://github.com/microsoft/vscode/blob/7ccb8688351c111345fb928b3dacec10e77fe51a/extensions/markdown-language-features/src/test/documentLinkProvider.test.ts#L15


In the tests, also try adding test for potential edge cases or false positives where link detection should not occur

I'm also inclined to say that the link detection should not kick in for `[Works]: https://microsoft.com`. We already highlight the destination link in that case and highlighting the link id itself doesn't strike me as useful here

**Comment by BamBamboozled** [comment]
Will do! And yeah maybe got a little overzealous with link highlighting haha

Will attempt to make changes by EOD today

**Comment by BamBamboozled** [comment]
Sorry for the delay. Should be ready for review!

**Review by mjbvz — CHANGES_REQUESTED** [review]
Looks reasonable overall. Thanks for following up!

Can you please remove the binary file added under `./scripts` though? Looks like it was committed by mistake

**Comment by BamBamboozled** [comment]
Whoops! My bad for littering. Should be fixed, thanks for the heads up!

**Comment by mjbvz** [comment]
Thanks! Will be in the next insiders build

**Pull request merged**
