### PR TITLE
Quick Open show the "..." to the left or center to not hide important segments

### PR DESCRIPTION
**Pull request by drKnoxy**
Addresses #18259

It was a little suprising that `QuickOpenEntryGroup` prints it's first entry child, so I had to add some logic in there as well, but I tried to keep the spread of the magic 44 number limited.

The `monaco-icon-label` being inline-block was impacting line-height, I tested with the seti icons and minimal icons and both still render correctly.

I don't see any regressions from removing some flexbox solution from @joaomoreno aa522145aa6b16ca88414142c932935dd933f830
* sidebar: twistie spacing 
* sidebar: full width rename
* sidebar: overflow ellipsis on resize

Sidebar icon alignments don't look consistent between seti and minimal, but are in a separate sheet, and seem to be inline with master. So no impact from this PR.

Initially I was worried about the semantics of using `direction:rtl` but i'm using it because we typically care about the end of the path more.

### CODE REVIEW

**Comment by bpasero** [comment]
-1 for a solution that forces double the size for elements in quick open:

image

If we are going to tackle this, it can only be with a "..." in the center of the label if the available width is not enough imho.

**Comment by drKnoxy** [comment]
sublime duplicates the filename in the path area... not sure that is better, but atleast it is visually consistent.

screen shot 2017-01-18 at 4 17 42 pm

**Comment by drKnoxy** [comment]
@bpasero if you have any tips on coding up a solution to the ellipsis in the middle request i'm all ears. Would love to have this feature.

**Comment by bpasero** [comment]
No, ideally this would be supported with some CSS property from browsers, but I am not aware of anything like that.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/pull/19878

**Pull request closed without merging**
