### PR TITLE
Change label of indentation action in status bar

### PR DESCRIPTION
**Pull request by waldyrious**
This change is to conform to the labels of the other actions, which clearly indicate that they will provide a way to *do* something ("Go to", "Select", etc.)

I separated the changes into multiple atomic commits, so that if any of the changes are not acceptable (e.g. changes to the localization keys, or localization updates that don't go through Transifex), they can be easily left out.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@waldyrious as noted in the header of these files they are machine generated. 

The way to contribute to translations is via Transifex. Please see https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by waldyrious** [comment]
@dbaeumer should I drop bc152db and 0b583f6, then? And what about the key change -- is that OK?

**Comment by dbaeumer** [comment]
@waldyrious the keys are in our source code and need to be changed there . The translation is managed in transifex and need to be changed there. 

For example src/vs/workbench/browser/parts/editor/editorStatus.ts for the corresponding file you changed in i18n.

**Comment by waldyrious** [comment]
Just to be sure, are you saying that commit 5876213 can remain in this PR?

**Comment by dbaeumer** [comment]
No, For example the first change has to happen here: https://github.com/Microsoft/vscode/blob/master/src\vs\workbench\browser\parts\editor\editorStatus.ts#L308

**Comment by waldyrious** [comment]
> No, For example the first change has to happen here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorStatus.ts#L308

@dbaeumer 5876213 does change that ([here](https://github.com/Microsoft/vscode/commit/5876213f6cf69e5078515b75f8e0214fb033ee9e#diff-1ba53e60093143b29593e77afffaacb6L308)). Are you saying that that change must happen in isolation (i.e. that 5876213 should only contain the change to `editorStatus.ts`), and the key will automatically be updated in the i18n files after the PR is merged?

**Comment by dbaeumer** [comment]
The key change has to happen in our source code. Then in transifex the message (since it is still the same will be recycled) and when we import the next time from transfix the key change will appear in the i18n files. Message changes have to appear in Transifex itself.

What is the purpose of the key change? Usually we only change them if absolutely necessary.

**Comment by waldyrious** [comment]
> The key change has to happen in our source code. Then in transifex the message (since it is still the same will be recycled) and when we import the next time from transfix the key change will appear in the i18n files. Message changes have to appear in Transifex itself.

Got it, thanks for the confirmation. I'll update the branch accordingly.

> What is the purpose of the key change? Usually we only change them if absolutely necessary.

The change in the key is to keep it consistent with both the message contents and the other keys:

```diff
-indentation --> "Indentation"
+selectIndentation --> "Select Indentation"
 selectEncoding --> "Select Encoding"
 selectEOL --> "Select End of Line Sequence"
 selectLanguageMode --> "Select Language Mode"
```

If I changed only the message contents, then the key name would be inconsistent and potentially confusing.

**Comment by danyeh** [comment]
@dbaeumer , it is code change. So assigned back to you.

**Comment by dbaeumer** [comment]
This is editor. Assigning to @alexandrudima

**Pull request merged**
