### PR TITLE
Fix a link issue in Git start view

### PR DESCRIPTION
**Pull request by LazarusX**
This PR fixes a link issue in Git start view.

### CODE REVIEW

**Review by rheh — APPROVED** [review]

**Review by MightBeHarmless — APPROVED** [review]
Well, this change obviously makes sense.

**Comment by eamodio** [comment]
Duplicate of #113654
But as with that one, what are you trying to fix with this? The change you've made, breaks the title attribute part of the link.

**Comment by eamodio** [comment]
Closing this as there is no bug here to fix.

**Comment by LazarusX** [comment]
image
@eamodio Please see the above screenshot. With a language pack installed, the link is broken. This PR fix this issue.

**Pull request closed without merging**
