### PR TITLE
Expose theme name in webviews

### LINKED ISSUE #97663: support limit markdown.styles active in single theme
`markdown.styles` only support css link array now, it don't support limit active in one theme, and it will cause active in global scope, if it can support object like 
```js
"editor.tokenColorCustomizations": {
        "[One Dark Pro]": {
            "textMateRules": []
        },
       
    }
```
that will better

image

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #97663

Adds a data attribute `data-vsccode-theme` to webviews with the current theme name. This is lets extensions write theme specific css for webviews, for example:

```css
body[data-vscode-theme-name="One Dark Pro"] {
    background: red;
}
```

### CODE REVIEW

**Comment by aeschli** [comment]
There are hundreds of existing themes out there and they can be updated anytime. I don't see how a webview provider could keep track with that. 
It were better if views don't define theme specific colors, but that an existing color of a theme is used (or a derivative of it (darker/lighter/mix).

Can you explain the use case?

**Comment by Binaryify** [comment]
here is the origin feature request, https://github.com/Binaryify/OneDark-Pro/issues/388
I want custom markdown preview color highlight, so I write some css with the  "markdown.previewStyles" in the package.json, but then I found it also actived in other themes too, this cause some problems, and don't have any way to limit that

Here's a comparison with custom markdown preview
image
image

**Comment by aeschli** [comment]
Ok, I see a theme wants to style the markdown preview through `markdown.styles`.
@mjbvz If it's just for that background color, can't the Markdown define a new color so that all themes can easily theme it? That's more in the spirit of theming.

**Comment by Binaryify** [comment]
@aeschli no just for background color, include the code highlight and the elements style

**Comment by mjbvz** [comment]
@aeschli Extensions should use the normal theme color variables in almost all cases. We also already expose the theme kind (light, dark, high contrast)

The theme name is helpful if you want to write CSS that is only enabled in one specific theme. For example, the official GitHub theme may contribute CSS rules to the markdown preview that are only enabled when the GitHub theme is active

**Review by aeschli — APPROVED** [review]

**Pull request merged**
