### PR TITLE
Create FileReadableStream class to stream large files for d&d uploads and add progress notification

### LINKED ISSUE #83565: Web: improve the experience for large file uploads
**Check**: https://github.com/microsoft/vscode/issues/83565#issuecomment-638882779

**Outdated:**
- VSCode Version: 1.40.0-insider @ b7b21844e760e632f39bedf651da2bc93f54b0cc
- OS Version: OS X Mojave 10.14

Steps to Reproduce:

1. Create a large file (`dd if=/dev/zero of=file.txt count=1024 bs=8388608` creates an 8GB file)
2. Try to upload it
3. Nothing happens

I'm guessing we need to support some kind of streaming, I notice most files get uploaded in a single websocket frame (and supposedly loaded into memory). Chrome might not like us loading or sending very large files this way.

Does this issue occur when all extensions are disabled?: Yes

Ref: https://github.com/microsoft/vscode/issues/83225

### PR DESCRIPTION
**Pull request by steven166**
This PR fixes #83565

### CODE REVIEW

**Comment by isidorn** [comment]
@steven166 great work both on this PR and the previos one. I plan to review this after a meeting today.
Would you maybe be interested in tackling this one as well? I planned to look into this next week and if you are interested we can look into it together. Let me know what you think. https://github.com/microsoft/vscode/issues/93599

Thanks!

**Comment by bpasero** [comment]
@steven166 thanks for bringing this back so quickly, can we keep the streams support but leave out notifications for now? I think the progress reporting via the progress bar in the explorer is OK for now. We can always revisit that later, but I think notifications are a bit too much for my taste when it comes to uploading. There are other more lightweight ways to report progress, e.g. in the status bar too.

**Comment by steven166** [comment]
@isidorn yeah sure, I can help with that one. 

@bpasero I've disabled the notification part for now. I think it can be a long running operation (like minutes) where the user is waiting for, so that is why I choose for a notification. But I'm not sure when to use a notification or the status bar.

**Comment by bpasero** [comment]
@steven166 I think I found a much simpler solution by leveraging the `file.stream` property. Instead of doing this all on our own, we can simply get a stream from the file object. As such, the upload method would just be this:

```ts
private async doUploadWebFileEntry(entry: IWebkitDataTransferItemEntry, parentResource: URI, target: ExplorerItem | undefined): Promise<{ isFile: boolean, resource: URI } | undefined> {
	if (!entry.name || !entry.isFile && !entry.isDirectory) {
		return undefined;
	}

	const resource = joinPath(parentResource, entry.name);

	// Confirm overwrite as needed
	if (target && target.getChild(entry.name)) {
		const { confirmed } = await this.dialogService.confirm(getFileOverwriteConfirm(resource.path));
		if (!confirmed) {
			return undefined;
		}
	}

	// Handle file upload
	if (entry.isFile) {
		const writeableStream = newWriteableBufferStream();

		// Read the file in chunks using File.stream() web APIs
		(async () => {
			try {
				const file = await new Promise<File>((resolve, reject) => entry.file(resolve, reject));
				const reader: ReadableStreamDefaultReader<Uint8Array> = file.stream().getReader();

				let res = await reader.read();
				while (!res.done) {
					writeableStream.write(VSBuffer.wrap(res.value));

					res = await reader.read();
				}
				writeableStream.end(res.value ? VSBuffer.wrap(res.value) : undefined);
			} catch (error) {
				writeableStream.end(error);
			}
		})();

		await this.fileService.writeFile(resource, writeableStream);
		return { isFile: true, resource };
	}

	// Handle folder upload
	else {

		// Create target folder
		await this.fileService.createFolder(resource);

		// Recursive upload files in this directory
		const folderTarget = target && target.getChild(entry.name) || undefined;
		const dirReader = entry.createReader();
		const childEntries = await new Promise<IWebkitDataTransferItemEntry[]>((resolve, reject) => {
			dirReader.readEntries(resolve, reject);
		});

		for (let childEntry of childEntries) {
			await this.doUploadWebFileEntry(childEntry, resource, folderTarget);
		}

		return { isFile: false, resource };
	}
}
```

Seems to work great, except for Safari where `file.stream` seems undefined.

**Comment by bpasero** [comment]
I landed this as https://github.com/microsoft/vscode/commit/203508d5ead067dd8a4060856f7bff2bd32ddb35 with some minimal progress. Thanks for this PR that made me look into the `file.stream` API, but I prefer that approach.

**Pull request closed without merging**
