### PR TITLE
Themes: do not set classes to the <body> element.

### LINKED ISSUE #92953: Themes: set classes to the <body> element
Maybe there is a technical reason but I find it a bit weird that the theme service changes classes on the `<body>` element, especially when VSCode is running on Web in a specific container.

Do we actually need to do it this way, why can the theme service not set it on the workbench container?

image

### PR DESCRIPTION
**Pull request by aeschli**
This PR fixes #92953

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

**Comment by aeschli** [comment]
Adopted the web: 'light' theme is set as default there. To properly work also requires that the settings have a light theme as default.

**Comment by bpasero** [comment]
@aeschli looks good so far, I think to make `yarn web` not flicker we also need to adjust the default theme for when running in web to be:

`const DEFAULT_THEME_SETTING_VALUE = isWeb ? 'Default Light+' : 'Default Dark+';`

in https://github.com/microsoft/vscode/blob/6ba01ef140a90a1f307b7ac6133c94b7b635177d/src/vs/workbench/services/themes/common/themeConfiguration.ts

**Comment by aeschli** [comment]
@bpasero I was looking at this, but changing the default is problematic. If you are a Dark+ user on a regular VSCode, there's no theme setting in the User setttings, because Dark+ is the default.
Assuming we have settings sync, and you open the same workspace in the web, you get light.The The theme service has this 'smartness' to never write the default Dark+ in the user settings, but clear it. `

Where does the web user get his users settings from?

**Comment by bpasero** [comment]
I think that is probably fine, if the user has not changed the default theme, it is us that defines the default experience. And we seem to go with light for web.

In web this is controlled via the `userDataProvider` which implements the file system provider for settings:

https://github.com/microsoft/vscode/blob/442caf6cd943cc32e9ba7bd68f68e3993d1d24f4/src/vs/workbench/workbench.web.api.ts#L219

**Pull request merged**
