### PR TITLE
Fixes #198387

### LINKED ISSUE #198387: Show "implementations" code lens for TypeScript "virtual"/overridden methods
I find the "implementation" code lens feature very useful and I am looking forward to #136282.

Since TypeScript has no "virtual" keyword to explicitly state that a method can and should be overridden, it is not possible to know if a method is overridden in a derived class.

I have an abstract class A with the methods foo() and bar().
class B extends A and overrides foo().
class C extends A and does not override foo().

Looking at a parent class, I'd like to see if a method is overridden in a derived class and quickly navigate there.
The "implementation" code lens should basically display the result of "Find All Implementation" command.

### PR DESCRIPTION
**Pull request by austinchen12**
Fixes #198387  by adding implementation in code lens for overridden abstract class method. Test with 
```
abstract class A {
	foo() {
		console.log('foo from A')
	}
	bar() {
		console.log('bar from A')
	}
}

class B extends A {
	override foo() {
		console.log('foo from B')
	}
}

class C extends A {
	baz() {
		console.log('baz')
	}
}
```

Should see implementation 1 above line 2

### CODE REVIEW

**Comment by austinchen12** [comment]
@mjbvz this is my first PR, please let me know if there is anything to change. One note is that I'm currently re-using `implementationsCodeLens.showOnInterfaceMethods` but this is for abstract classes, let me know if its more appropriate to use something separate. I thought it seemed reasonable that these two should be controlled under the same flag but the name is a bit misleading

**Comment by austinchen12** [comment]
@mjbvz just following up on this

**Review by offensive-vk — APPROVED** [review]
Impressive, Good logic.👌

**Review by mjbvz — COMMENTED** [review]
I think this is an interesting feature idea but it needs a little more thought. For instance:

- Shouldn't this also work for non-abstract classes?
- Should it show if there are no overrides?
- Should it show for properties?

Maybe we can add a new setting that shows implementations on all methods/properties if there is more than one implementation?

**Comment by mjbvz** [comment]
Closing as I think this feature needs more thought. Let me know if you'd like to revisit this and address some of the concerns I raised

**Pull request closed without merging**
