### PR TITLE
Update the colouring of links in banner markdown

### LINKED ISSUE #140579: Styling of links is wrong within the banner
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.0-dev
- OS Version: Mac OS 12.1

Steps to Reproduce:

1. Create a banner which uses a link. 

```ts
    this.bannerService.show({
      id: 'test_id',
      icon: CodiconUtil.bellDot,
      message: new MarkdownString('**Test Message** [link](http://test/)'),
    });
```

image

Even though BannerService accepts a `MarkdownString`, the styling of links does not work as expected.

Note, this does not effect links provided within actions, just links defined within the markdown.

### PR DESCRIPTION
**Pull request by a-stewart**
This PR fixes #140579

### CODE REVIEW

**Comment by a-stewart** [comment]
Screenshot of after:  
image

I am not sure if we want links underlined here, I have updated bannerpart.css so that it matches the action links but can undo that if desired. Since there is no link colour available here, I think some distinction may be required.

**Comment by a-stewart** [comment]
Hi @lszomoru, @sbatten - I was wondering if you had had a change to look at this yet?

**Comment by a-stewart** [comment]
Hi @lszomoru, @sbatten - I was wondering if you might have time to take a quick look at this please.

**Review by lszomoru — APPROVED** [review]

**Comment by lszomoru** [comment]
@a-stewart, sorry for not getting on this earlier. Thanks for your contribution!

**Pull request merged**
